### ISSUE TITLE
Broken resource

### ISSUE THREAD

**Issue by chasmani** [TheOdinProject/curriculum#1022]
In rails/web_refresher.md the link to http://web-sniffer.net/ goes to a 502 error.  Also from a google search the site is down.

**Proposed solution** - change to alternative site at http://testuri.org/sniffer.  (Although I'm not sure if this has the same level or type of functionality).

**Comment by hgducharme** [comment]
@craftykate I'll leave this up to you since you've gone through the rails section and can better assess this

**Comment by craftykate** [comment]
I checked it out and it looks good. I updated link to testuri.org/sniffer link. Thanks @chasmani and @hgducharme.
