### ISSUE TITLE
Add README to course folders

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/curriculum#10238]
This would be a great first issue for someone looking to contribute.

I put a readme file in the NodeJS curriculum folder with links to the lessons in their intended order.  Doing so makes it easier to follow what's going on inside that folder without having to load up theodinproject.com to see the curriculum order.

see here:
https://github.com/TheOdinProject/curriculum/tree/master/nodeJS

Other courses and directories should have a similar README. No need to add much extra information, just create a readme with an outline or table-of-contents and links to each lesson in the correct order.

**Comment by Ania-chan** [comment]
Hi, I'd like to create readme's for odin project. I'm a beginner and I've never contributed before to an open source. 
Do I understand it correctly that 7 additional readme's will be needed? https://www.theodinproject.com/courses

**Comment by leonardovega** [comment]
@Ania-chan Do you need any help with this task? I can try to offer a helping hand if needed.

**Comment by Ania-chan** [comment]
@leonardovega Thank you! I'll let you know if I need any help!

**Comment by codyloyd** [comment]
@Ania-chan I believe that you DO understand correctly 😄

**Comment by Ania-chan** [comment]
@codyloyd Great! I'll do it then :)

**Comment by Ania-chan** [comment]
@codyloyd I've just created pull request with the readme files! Please let me know if there is anything I could improve of fix.
