### ISSUE TITLE
Node Course: Proofreading/Editing

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/curriculum#10253]
The nodeJS course lessons are currently in a _very_ rough first-draft form.  Every lesson needs proofreading, revision and editing.

If you want to take a look at one leave a comment below saying which one you're reviewing.

As the author, I'll give them all a review myself to make sure the content is accurate and that I'm saying what I want to say, but I'd like other people's eyes on each lesson to watch for silly spelling/grammar mistakes, poor/unclear wording, or any thing else.

**Comment by leonardovega** [comment]
I can help out with the following lessions:

- Introduction: What is node? 
- Getting Started
---- Getting Started Lesson
---- Getting Started Project

**Comment by suretrust** [comment]
I'll take a look at the following lessons
- Express
  - Express Introduction lesson
  - Express Tutorial
    - Lesson 1
    - Lesson 2

**Comment by suretrust** [comment]
I'll take a look at the following lessons:

- Express
    - Express Tutorial
        - Lesson 3
        - Lesson 4
        - Lesson 5

**Comment by ezrahnyanat** [comment]
Doing a read through of the course lessons!
Noticed a tiny tiny typo in the NodeJs intro -  https://www.theodinproject.com/courses/nodejs/lessons/introduction-what-is-nodejs#event-driven. definition is missing an 'i'. I can fix, but only if someone else is not already on it, so I won't step on toes.

**Comment by suretrust** [comment]
@ezrahnyanat feel free to edit as appropriate.

**Comment by AJMcDee** [comment]
I can look over this for grammar/spelling/etc but I haven't learned Node yet so can't check in any technical regard. It'd be best to have someone else who can look over that side if it's still needed.

**Comment by I3uckwheat** [comment]
@AJMcDee It sounds like a great way to learn Node ;)

**Comment by ultrawide** [comment]
I went through the 'Testing Routes and Controllers" for the first time as a student [here](https://www.theodinproject.com/courses/nodejs/lessons/testing-routes-and-controllers)

It looks like running the code snippet below errors out when issuing the command 'node <test file>'. Can someone take a look and let me know if I'm missing anything?

Error: 

> ReferenceError: test is not defined

Code:
`test("index route works", done => {
  request(app)
    .get("/")
    .expect("Content-Type", /json/)
    .expect({ name: "frodo" })
    .expect(200, done);
});`

**Comment by ZachBaird** [comment]
@codyloyd What all needs left proofread? It's been some time since this has been revisited.

**Comment by codyloyd** [comment]
@ZachBaird i am so far removed from this project lol... i say it's time to close this issue and move on.
