### ISSUE TITLE
Node Course: Learning Outcomes

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/curriculum#10254]
We need to go through and add appropriate learning objectives to most lessons inside the node course.

To help with this task, simply pick a lesson and if it doesn't have any learning outcomes, read the content and add them.  

Look at this lesson for an example: https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/basic_ruby/lesson_advanced_building_blocks.md

we do not need _nearly_ that many objectives/questions for each of our lessons, but we shouldn't shy away from being thorough either.

Comment below with which lesson you're working on.

**Express**

- [x] Introduction to Express

- [x] Express 101

- [x] Express 102

- [x] Express 103

- [x] Express 104

- [x] Express 105

**Authentication**

- [x] Authentication Basics

- [x] Security Configuration

**APIs**

- [x] API Basics

- [x] API Security

**Testing Express**

- [x] Testing routes and controllers

- [x] Testing database operations

**Comment by suretrust** [comment]
I'm working on the [Getting-Started](https://github.com/TheOdinProject/curriculum/blob/master/nodeJS/getting-started/Getting-Started.md) inside the [getting-started](https://github.com/TheOdinProject/curriculum/tree/master/nodeJS/getting-started) folder.

**Comment by leonardovega** [comment]
@suretrust I forgot that the proofing and outcomes were separate issues. So when proofing the Getting-Started.md file I added the outcomes too. Sorry about that.  I’ll stick to just proofing in the getting started project.

**Comment by suretrust** [comment]
@leonardovega That's okay. Thanks for the update.

**Comment by leonardovega** [comment]
@suretrust keep up the good work and thanks for the contributions.

**Comment by suretrust** [comment]
I'm working on the [express introduction](https://github.com/TheOdinProject/curriculum/blob/master/nodeJS/express-basics/Express-Introduction.md) under the [express basics](https://github.com/TheOdinProject/curriculum/tree/master/nodeJS/express-basics) section.

**Comment by suretrust** [comment]
I'm working on [lesson 2](https://github.com/TheOdinProject/curriculum/blob/master/nodeJS/express-basics/Express-Lesson-2.md) under the [express basics](https://github.com/TheOdinProject/curriculum/blob/master/nodeJS/express-basics/) section.

**Comment by suretrust** [comment]
I'm working on [lesson 3](https://github.com/TheOdinProject/curriculum/blob/master/nodeJS/express-basics/Express-Lesson-3.md) under the [express basic](https://github.com/TheOdinProject/curriculum/tree/master/nodeJS/express-basics) section.

**Comment by suretrust** [comment]
I'm working on [lesson 4](https://github.com/TheOdinProject/curriculum/blob/master/nodeJS/express-basics/Express-Lesson-4.md) under the [express basic](https://github.com/TheOdinProject/curriculum/tree/master/nodeJS/express-basics) section.

**Comment by suretrust** [comment]
I'm working on [lesson 5](https://github.com/TheOdinProject/curriculum/blob/master/nodeJS/express-basics/Express-Lesson-5.md) under the [express basic](https://github.com/TheOdinProject/curriculum/tree/master/nodeJS/express-basics) section.

**Comment by I3uckwheat** [comment]
Lesson 1 under authentication section: #16066

**Comment by marvingay** [comment]
Authentication > Security Configuration was here #16081

APIs > API basics is here #16133

**Comment by marvingay** [comment]
Testing Express > Testing routes and controllers
#16246

**Comment by marvingay** [comment]
Testing Express > Testing database operations

#16306
