### ISSUE TITLE
Can't change username in the Account tab -- it says it's successful but doesn't change it

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/curriculum#1045]
Reproduceable if you sign in with Github, not sure about normal signin

**Comment by hgducharme** [comment]
Was able to reproduce.

**Comment by craftykate** [comment]
Did anyone fix this? I'm not able to get my postgres working to be able to test my solution, but if I can get permission I'd like to change

```
  def update
    @user = User.find_by_id(params[:id])
    if @user
      @user.update_attributes(params[:user])
      flash[:success] = "Your profile was updated successfully"
      redirect_to @user
    end
  end
```

inside `app/controllers/users_controller.rb` to 

```
  def update
    @user = User.find_by_id(params[:id])
    if @user
      @user.update_attributes(user_params)
      flash[:success] = "Your profile was updated successfully"
      redirect_to @user
    end
  end
```

which I think *should* fix things. But I don't want to do it if someone has an issue with me not being able to test it first.

**Comment by nhquiroz** [comment]
I have the same issue with normal sign in too.

**Comment by KevinMulhern** [comment]
This belongs in the main site repo
