### ISSUE TITLE
Reposition "Command Line Basics" section

### ISSUE THREAD

**Issue by MoonKingArthur** [TheOdinProject/curriculum#10491]
## Context
A lot of students come into the discord requesting help with the command-line basics. Their confusion is usually centered around them being a Windows user with no  prior knowledge of a command line outside of the one on windows. The entire section usually doesn't make sense until they've installed a VM, or set up dual boot. The students are usually instructed by the discord mods to go about the following route:
![command-line-basics](https://user-images.githubusercontent.com/48981108/57032380-35415600-6c18-11e9-820b-6bece5f033ce.png)
## Issue
I feel that this issue affects a significant amount of users in the early stages of the curriculum. For that reason, the "Command Line Basics" section should just be repositioned appropriately.

**Comment by bycdiaz** [comment]
This issue was resolved.
