### ISSUE TITLE
Broken Link - APIs and Building Your Own

### ISSUE THREAD

**Issue by learnsometing** [TheOdinProject/curriculum#11019]
In [APIs and Building Your Own](https://www.theodinproject.com/courses/ruby-on-rails/lessons/apis-and-building-your-own), the link to the infamous google post is now broken, since google plus no longer exists. I did some digging and it looks like most mirrors of the post are also affected by the shutdown of Google+, but I did manage to find a text mirror of the post on [github](https://gist.github.com/chitchcock/1281611). This is my first time contributing to the curriculum and I would like to edit the link on the curriculum page if possible.

**Comment by leila-alderman** [comment]
This issue was resolved by PR #11012.
