### ISSUE TITLE
Change mentions of 'bundle.js' to 'main.js'

### ISSUE THREAD

**Issue by marinarose92** [TheOdinProject/curriculum#11056]
I noticed this article: https://github.com/TheOdinProject/curriculum/blob/master/javascript/organizing-js/es6-modules.md continually references `bundle.js` but it seems to have changed to `main.js` in the linked tutorial for webpack. Whether this is simply a different convention or something more significant (I'm only just being exposed to webpack) I think it would make the tutorial a bit clearer and minimize confusion.

**Comment by leosoaivan** [comment]
@marinarose92 the standard is indeed `main.js`, though you *can* name it whatever you want.

https://github.com/webpack/webpack.js.org/issues/2094

Feel free to make a PR :).

**Comment by kashura** [comment]
@leosoaivan - submitted a PR.
