### ISSUE TITLE
Michael Hartl's Rails Tutorial (https://www.railstutorial.org) is down. 

### ISSUE THREAD

**Issue by coped** [TheOdinProject/curriculum#11079]
https://www.railstutorial.org/ is currently down. This affects all lessons within TOP curriculum that reference this website such as:

* Web Development 101: Ruby on Rails Basics
https://www.theodinproject.com/courses/web-development-101/lessons/ruby-on-rails-basics

* Ruby on Rails: Project: Getting Your Feet Wet
https://www.theodinproject.com/courses/ruby-on-rails/lessons/getting-your-feet-wet

* Ruby on Rails: Project: Let's Get Building
https://www.theodinproject.com/courses/ruby-on-rails/lessons/let-s-get-building

* Ruby on Rails: Project: Basic Routes, Views and Controllers
https://www.theodinproject.com/courses/ruby-on-rails/lessons/basic-routes-views-and-controllers

And several other lessons throughout the Ruby On Rails portion of TOP.

**Comment by coped** [comment]
https://www.railstutorial.org/ is back up.

**Comment by ryanford-frontend** [comment]
In the future you can use the [Internet Archive](https://web.archive.org/) to view a [cached version](https://web.archive.org/web/20190614183225/https://www.railstutorial.org/)

**Comment by coped** [comment]
I had that in mind when trying to find a workaround, but I noticed if you tried to access any of the chapters, a "Sorry, content not available" is given instead of the chapter content. For example:

https://web.archive.org/web/20190530183804/https://www.railstutorial.org/book

This link will give you nothing.
