### ISSUE TITLE
rails section in javascript course(in NodeJS track)

### ISSUE THREAD

**Issue by srtkverma** [TheOdinProject/curriculum#11148]
if we aren't learning rails, maybe this shouldn't be in the node track
https://www.theodinproject.com/courses/javascript#javascript-and-rails

**Comment by codyloyd** [comment]
i can't tackle this immediately, but perhaps a quickfix would be to add a note at the top of the lesson that says somethign like "feel free to skip this if you don't know rails"

**Comment by I3uckwheat** [comment]
@CouchofTomato This is related to the work you have done to remove Rails from the incorrect places.

**Comment by Saranoya** [comment]
I can take this one. Will look into replacing the suggestion to use Rails with a suggestion to use Firebase instead, since I'm currently getting familiar with that.

**Comment by I3uckwheat** [comment]
@Saranoya Thanks! I've assigned it to you!

**Comment by marvingay** [comment]
Fix was merged as noted.

Closing.
