### ISSUE TITLE
[Ruby on Rails][Views] Should the lesson also cover the `<% -%>` and `<#% %>` tags?

### ISSUE THREAD

**Issue by heyapricot** [TheOdinProject/curriculum#11253]
The lesson for views in RoR covers the use of `<% %>` and `<%= %>` tags. Covering the use of `<% -%>` and `<#% %>` would be helpful

**Comment by mindovermiles262** [comment]
I'm not sure I've ever heard of using `<% -%>` before. Could you tell me an example of when you would use this?

**Comment by leosoaivan** [comment]
I agree that the lesson could include the use of the `<#% %>` ERB tag. I don't think the trim tags are helpful, as they are largely synonymous with the regular `<% %>` tag.
