### ISSUE TITLE
[Web Development 101] Command Line Basics Course references a paywalled resource

### ISSUE THREAD

**Issue by zshoals** [TheOdinProject/curriculum#11267]
The Additional Resources section of [Command Line Basics](https://www.theodinproject.com/courses/web-development-101/lessons/command-line-basics-web-development-101) references this supposedly free ebook: [Learn Enough Command Line to Be Dangerous](https://www.learnenough.com/command-line-tutorial/basics), with a suggestion to review Chapters 1 and 4. 

However, the entire ebook after Chapter 1 seems to presently be paywalled (in quite an obnoxious fashion to be honest).

I'm new to TOP, so I don't exactly know the project's stance on paid content or how it should be handled. Nonetheless, the current description of this resource is misleading and should be adjusted at the very least.

Thank you.

**Comment by leila-alderman** [comment]
@zshoals We try to reference free materials as much as possible and to clearly state when resources are not free. However, the Learn Enough books going behind a paywall is a very recent change, so we just hadn't updated this lesson to reflect that change yet. 

I've gone ahead and made this change clearer in our description of that book now. Thanks for bringing this problem to our attention!
