### ISSUE TITLE
Web Development 101 has not been updated for the Full Stack JavaScript track

### ISSUE THREAD

**Issue by MBrighty** [TheOdinProject/curriculum#11297]
The Web Development 101 course contains multiple lessons relating to Ruby and Rails when viewing the course in the Full Stack JavaScript track. Some examples: 

- [Installing Ruby](https://www.theodinproject.com/courses/web-development-101/lessons/installing-ruby)
- [Your First Rails Application](https://www.theodinproject.com/courses/web-development-101/lessons/your-first-rails-application)
- The whole "The Back End" section
- [Ruby on Rails Basics](https://www.theodinproject.com/courses/web-development-101/lessons/ruby-on-rails-basics)
- [Project: Ruby on Rails](https://www.theodinproject.com/courses/web-development-101/lessons/ruby-on-rails)

This is not particularly relevant to the "Full Stack JavaScript" track and may be confusing to beginners.

**Comment by Nelson-Chinedu** [comment]
Hey @leosoaivan , is this issue still up?

**Comment by zachmmeyer** [comment]
It is definitely the same module. It would require an entirely different module in the course, not just the lessons inside. Mainly the "Installing Ruby" and "Rails Application" would be modified. "Installing Ruby" installs git among other things that I am not sure if they are needed for NodeJS. The "Rails Application" gets the user set up using git, github and heroku. Heroku is used with NodeJS.

I would say leave it the way it is. It is a decent boilerplate introduction that gets everything you need installed.

**Comment by CouchofTomato** [comment]
@zachmmeyer We are in the process of moving the ruby install and rails installs to their own courses. In web dev 101 we will retain an intro to the backend and frameworks at a general level. There is a pull request in place for moving the lessons and once that is finalised we will update the seeds file to put the lessons into their new homes.

**Comment by zachmmeyer** [comment]
Great! Thanks for clarifying.

**Comment by I3uckwheat** [comment]
This has been completed :)
