### ISSUE TITLE
Twitter Bot lesson missing.

### ISSUE THREAD

**Issue by AaronHe7** [TheOdinProject/curriculum#11343]

**Comment by leosoaivan** [comment]
Thank you for creating an issue.

A lot of the curriculum has changed. Do you recall on what page the twitter spambot was mentioned?

**Comment by AaronHe7** [comment]
https://www.theodinproject.com/courses/ruby-programming/lessons/how-this-course-will-work-ruby-programming
https://www.theodinproject.com/courses/web-development-101/lessons/conclusion-web-development-101

**Comment by bycdiaz** [comment]
@leosoaivan It seems that the reference to the twitter spam bot is outdated. If you can 2nd it, I'll remove the references.

Thanks for pointing this out @AaronHe7.

**Comment by leosoaivan** [comment]
@KevinMulhern what ever happened to the Twitter bot project? I recall doing it.

**Comment by bycdiaz** [comment]
I'm reopening the issue since we haven't reached a resolution.

**Comment by bycdiaz** [comment]
I didn't see the twitter bot project in our curriculum. I'll remove the reference.

Thank you for bringing this to our attention @AaronHe7.
