### ISSUE TITLE
Web Development 101: Git Basics: Ry's Git Tutorial PDF hyperlinks 404

### ISSUE THREAD

**Issue by martink-rsa** [TheOdinProject/curriculum#11358]
I am referring to the [Web Development 101: Git Basics](https://www.theodinproject.com/courses/web-development-101/lessons/git-basics) lesson, and a bullet point under _"Additional Resources"_ which reads as follows:

[Git Basics | The Odin Project](https://www.theodinproject.com/courses/web-development-101/lessons/git-basics)

> - An easy-to-read, pragmatic guide to using Git is available online from [RyPress](https://github.com/alokc83/Basic-Tutorials/blob/master/rypress.com%20Git/0_Ry's%20Git%20Tutorial.pdf) and also available for free on [Kindle](https://www.amazon.com/Rys-Git-Tutorial-Ryan-Hodson-ebook/dp/B00QFIA5OC).

The hyperlink to the repo containing the PDF works, however the PDF itself only contains links to the chapters of the tutorial and not the tutorial itself. The hyperlinks lead to https://rypress.com/tutorials/git/ and sub-directories which all result in a 404 error. If you navigate to www.rypress.com, you will see that it only consists of a web mail login using the service Roundcube.

The Kindle version, as mentioned in the lesson, is still available for students to download.

I do not have the experience and knowledge foresee the implications in simply uploading the Ry's Git Tutorial PDF to a file sharing website, and then suggesting the link. I won't be adding a link to download the PDF for this reason.

A solution I propose at this stage is to simply remove the reference and hyperlink to Rypress. Ideally, a PDF version of Ry's Git Tutorial would be added as a hyperlink for students to download directly from.

Current:

> - An easy-to-read, pragmatic guide to using Git is available online from [RyPress](https://github.com/alokc83/Basic-Tutorials/blob/master/rypress.com%20Git/0_Ry's%20Git%20Tutorial.pdf) and also available for free on [Kindle](https://www.amazon.com/Rys-Git-Tutorial-Ryan-Hodson-ebook/dp/B00QFIA5OC).

After (document name excluded):

> - An easy-to-read, pragmatic guide to using Git is available online for free on [Kindle](https://www.amazon.com/Rys-Git-Tutorial-Ryan-Hodson-ebook/dp/B00QFIA5OC).

After (document name included):

> - Ry's Git Tutorial: An easy-to-read, pragmatic guide to using Git is available online for free on [Kindle](https://www.amazon.com/Rys-Git-Tutorial-Ryan-Hodson-ebook/dp/B00QFIA5OC).

---
Book information for future purposes:

Title: Ry's Git Tutorial
Author: Mr Ryan Hodson
Publisher: Rypress
Originally published:  23 December 2012
Published: 30 November 2014

(Source: [Amazon](https://www.amazon.com/Rys-Git-Tutorial-Ryan-Hodson-ebook/dp/B00QFIA5OC), [GoodReads](https://www.goodreads.com/book/show/23951943-ry-s-git-tutorial))

**Comment by leila-alderman** [comment]
Fixed the link: https://github.com/TheOdinProject/curriculum/commit/64afd2c10dc8c16943d9dfb1c83dbde6cb4a9186
