### ISSUE TITLE
Instructions not up to date(web_dev_101)minor issue

### ISSUE THREAD

**Issue by Am00702** [TheOdinProject/curriculum#11508]
On (https://www.theodinproject.com/courses/web-development-101/lessons/html-css#viewing-your-project-on-the-web)
[Git-repo](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/the_front_end/project_html_css.md)
The instructions to view the project on web state:
>* "change the Source from none to master branch and click **Save.**"

There is no save button anymore, saving happens *automatically*.

**Comment by tbmreza** [comment]
Have you opened a pull request for this?

**Comment by Am00702** [comment]
No should I add?

**Comment by tbmreza** [comment]
Yes, it will help the maintainers see what change do you wish to make. It will be a great experience too if you are new to submitting PRs.

**Comment by jmcarter006** [comment]
I have added a pull request updating this change.

Pull Request: Fix/project html css.md #11940
