### ISSUE TITLE
Additional step needed for MacOS 10.14.5 to install NVM

### ISSUE THREAD

**Issue by jcamato** [TheOdinProject/curriculum#11590]
After following curriculum/web_development_101/installations/installing_node.md, _-bash: nvm: command not found_ kept appearing when trying to use nvm. After looking at [NVM's github documentation](https://github.com/nvm-sh/nvm#installation-and-update), this section ended up solving my issue:

> If the above doesn't fix the problem, open your .bash_profile and add the following line of code:
> `source ~/.bashrc`

After that, I was able to complete The Odin Project's installation instructions.

**Comment by leosoaivan** [comment]
Would you be willing to open up a PR with the necessary change?

**Comment by jcamato** [comment]
@leosoaivan Submitted, thanks!

**Comment by leosoaivan** [comment]
Resolved with 6470fb131546e71b7244988bd68e4238afd6ec6f
