### ISSUE TITLE
Rails 6 just released. Time to update the curriculum?

### ISSUE THREAD

**Issue by heyapricot** [TheOdinProject/curriculum#11815]
So, [Rails 6 is out](https://weblog.rubyonrails.org/2019/8/15/Rails-6-0-final-release/) and [Michael Hartl says he'll be updating his book](https://www.reddit.com/r/rails/comments/cra5u5/ruby_on_rails_600_released/ex3llbz) (Which is used in plenty if not all of the rails lessons/projects)

- How does this affect TOP Curriculum?
- What do we do about it?

**Comment by tfantina** [comment]
> So, [Rails 6 is out](https://weblog.rubyonrails.org/2019/8/15/Rails-6-0-final-release/) and [Michael Hartl says he'll be updating his book](https://www.reddit.com/r/rails/comments/cra5u5/ruby_on_rails_600_released/ex3llbz) (Which is used in plenty if not all of the rails lessons/projects)
> 
> * How does this affect TOP Curriculum?
> * What do we do about it?

Apparently Hartl's book is no longer available for free.

**Comment by ptypes** [comment]
Only 3 out of the 14 original chapters are free.

**Comment by martink-rsa** [comment]
I previously wrote to Mr Hartl (6 September 2019) requesting information regarding the availability of his book.

I do not have Mr Hartl's permission to share the email publicly so I will refrain from doing and will only quote portions of his response. This is to respect Mr Hartl's privacy. TOP was CC'd in on his response so the email is available to the account holder of TOP. 

He informed me that the Rails 5 book, which I believe is the 4th Edition, is still available from this link: https://www.learnenough.com/ruby-on-rails-4th-edition-tutorial/beginning

Furthermore, being the legend that he is, Mr Hartl stated that the _"entire book is available for free by scholarship here: https://www.learnenough.com/scholarship "_. He also went on to state that _"Followers of the Odin Project... are very likely to qualify for a scholarship & are encouraged to apply"_.

tldr: The Rails 5 book, believed to be the 4th edition, is available for free from: https://www.learnenough.com/ruby-on-rails-4th-edition-tutorial/beginning

**Comment by Pauloparakleto** [comment]
I follow the RoR tutorial with **Rails version 6.0.2.1** and **Ruby version 2.6.5p114** in a **Windows** local machine and... every thing went fine. Checking for CMD outputs, the main difference is the new rails install automatically the ActiveStorage gem and fix trigged vulnerability in the database. There is others tasks also. But this vulnerability found might be a great motive to start thinking about new course on new Rails version.
This is the link of someone who survives fighting against Rails 6 :)
[Toy App](https://github.com/Pauloparakleto/toy_app)

**Comment by CouchofTomato** [comment]
@Pauloparakleto This is under active discussion. I don't think using the RailsBook is viable anymore because although a lot of our students may qualify for a scholorship we are commited to a free education for anyone that wants to learn. The decision at the moment being considered is whether we try to find an alternative source or write our own.

**Comment by minimalsm** [comment]
As Hartl has removed free access to his book this seems a natural progression now.
