### ISSUE TITLE
The CSS Grids Lesson is way outdated and should be removed

### ISSUE THREAD

**Issue by SilasSpet** [TheOdinProject/curriculum#11867]
[The CSS Grids Lesson](https://www.theodinproject.com/courses/html5-and-css3/lessons/css-grids?ref=lnav#assignment) in the CSS & HTML course is in my opinion really outdated and not useful anymore. Maybe I should even go as far as calling it dangerous because it can easily teach people the wrong approach and give them a false sense of what is in use today. 

The first assignment ([Basic Grids from CSS-Tricks](https://css-tricks.com/dont-overthink-it-grids/)) even notes right in the beginning, that the article is out of date as it has been written in 2012. The author says that instead of using floats, like he does in the article, nowadays he would choose CSS Grid or Flexbox as these tools are way better suited for the task.

The second assignment ([Fluid Grids from A List Apart](https://alistapart.com/article/fluidgrids/)) is from 2009 and as far as I can see hasn't been updated since. It goes through a lot of mathematics to get the perfect percentage value for the respective elements. If I remember correctly, in the CSS Flexbox lesson one of the sources, Wes Bos, even made fun about the fact that web developers needed to do this years ago.

The third assignment ([Responsive Grid with Media Queries Tutorial from TutsPlus](https://webdesign.tutsplus.com/articles/a-basic-responsive-grid-plus-handy-css3-media-query-reporter--webdesign-5121)) from 2011 again uses floats to get their layout going. 

In my opinion we should get rid of this lesson altogether. As I said it doesn't add anything useful and just points users in the wrong direction.

**Comment by SilasSpet** [comment]
@I3uckwheat Do you mean alternatives for the learning assignments? Because if so, then no I do not. I think the entire concept of the lesson is just not needed anymore now that we have Flexbox and Grid and both are already covered. If you mean alternative as in a different lesson then the two things that would come to my mind are:
1. TailwindCSS. There are already two CSS frameworks covered with Bootstrap and Foundation. However, because Tailwind uses an entirely different approach I think it could be pretty useful.
2. Email Design. This is not covered anywhere but it's a pretty important part of web design. Explaining some of the difficulties that come with email design and how again frameworks like Foundation Email or MJML can be a tremendouss help is an interesting and important topic for every front end developer.

**Comment by codyloyd** [comment]
i agree let's toss it

**Comment by zachmmeyer** [comment]
Would this link suffice as replacement for all three assignments?
https://css-tricks.com/snippets/css/complete-guide-grid/
The article was written in 2016 but makes a note to stay as up to date as possible.

**Comment by ZachBaird** [comment]
I can start looking into this.

**Comment by I3uckwheat** [comment]
@ZachBaird You're a issue-fixer monster 🔥

**Comment by ZachBaird** [comment]
@I3uckwheat  After touching base with @codyloyd , it makes more sense to roll this effort up into the future HTML/CSS rewrite.

I think that @zachmmeyer 's suggestions looked like great resources for when that later effort comes.

**Comment by I3uckwheat** [comment]
@ZachBaird Thanks for looking into this. I agree this should wait. I will close this for now :)
