### ISSUE TITLE
Formerly free resource for Git Basics assignment now requires payment

### ISSUE THREAD

**Issue by bycdiaz** [TheOdinProject/curriculum#12086]
The first assignment for the [Git Basics ](https://www.theodinproject.com/courses/web-development-101/lessons/git-basics) lesson is now part of the pro package at codecademy. 

The lesson is the Basic Git Workflow from the [Learn Git course at codecademy](https://www.codecademy.com/learn/learn-git).

We'll need to identify a new resource for this lesson.

**Comment by jmcarter006** [comment]
I’m on mobile so this page isn’t working right. But it looks like this resource may be a viable interactive git learning tool. Especially the “Learn by Doing” section 

https://try.github.io/

**Comment by Rickeo** [comment]
Following on from what @jmcarter006 said, specifically the link on that page to this resource:

https://learngitbranching.js.org/

That seems to be the bulk of the interactive lesson(s).

As someone who has recently just done that Code Academy course, having a brief look at the content on js.org it seems to cover the same type of material.

**Comment by bycdiaz** [comment]
I came across this resource:[git-tower.com](https://www.git-tower.com/learn/git/ebook/en/command-line/introduction#start) It feels a bit more accessible than the others. If I'm not mistaken, Part 1 - The Basics should give learners what Codecademy was covering.

I only have two (small) concerns about this resource. It mentions a set of lessons using a desktop GUI. We would just need to be explicit about folks sticking to the command line version.

Also, during the [Getting Ready lesson](https://www.git-tower.com/learn/git/ebook/en/command-line/basics/getting-ready#start), they don't mention installing in Linux (only Mac OS and Windows). But we'll just need to remind learners that they should have installed git before arriving to this lesson.

**Comment by bycdiaz** [comment]
Resolved by pull request #12291.
