### ISSUE TITLE
Michael Hartl's RoR Tutorial is now paywalled

### ISSUE THREAD

**Issue by coped** [TheOdinProject/curriculum#12098]
The content of Michael Hartl's RoR Tutorial, from chapter 4 thereon, is now behind a pay-wall.

Any lesson past the 'Introduction to Rails' section of the Ruby On Rails curriculum (https://www.theodinproject.com/courses/ruby-on-rails) now potentially links to incomplete content. 

This is a problem seeing as the RoR curriculum places a heavy reliance on the content of the tutorial.

**Comment by borjarobert** [comment]
There is still a way to access them for free (for a limited time, apparently), from: https://www.learnenough.com/ruby-on-rails-4th-edition-tutorial/beginning

**Comment by leila-alderman** [comment]
@borjarobert I'm trying to dig into this issue some more. Why do you say that the 4th edition is available for only a limited time?

**Comment by borjarobert** [comment]
> @borjarobert I'm trying to dig into this issue some more. Why do you say that the 4th edition is available for only a limited time?

Inside https://www.learnenough.com/courses if you scroll down until you find the Ruby on Rails tutorial (right column) it says: "Looking for the Ruby on Rails Tutorial for Rails 5? For a limited time the previous version of the book with remain available here: Previous Version".

**Comment by leila-alderman** [comment]
The links throughout our curriculum have been replaced with links to the older but still free version (https://github.com/TheOdinProject/curriculum/pull/12107). This issue might come up again when/if the Rails 5 version also goes behind a paywall, but I'm closing this issue for now.

**Comment by kujosHeist** [comment]
Looks like the rails 5 version is now also behind a paywall
