### ISSUE TITLE
Codecademy Command Line course now paid

### ISSUE THREAD

**Issue by leila-alderman** [TheOdinProject/curriculum#12108]
The Codecademy Command Line course is no longer free. This course is linked to as the second step in the assignment for the Command Line Basics lesson: https://www.theodinproject.com/courses/web-development-101/lessons/command-line-basics-web-development-101?ref=lnav

We would like to find a similar free resource to replace this tool. This could be an informative article, a short book, or another course.

This issue is related to Issue #12086

**Comment by asmaalshareef** [comment]
Udacity command line basics course (free) 
https://www.udacity.com/course/linux-command-line-basics--ud595

**Comment by martink-rsa** [comment]
Interactive options:
https://exercism.io/my/tracks/bash (Requires a local setup)
https://www.learnshell.org/ (Doesn't deal with navigation)

Long list of resources if you're willing to omit interactivity:
https://practity.com/lynux/

**Comment by I3uckwheat** [comment]
Codecademy has been removed :)
