### ISSUE TITLE
Web Development 101: Consider removing Treehouse video on basic forms

### ISSUE THREAD

**Issue by krupenja** [TheOdinProject/curriculum#12204]
[HTML and CSS basics](https://www.theodinproject.com/courses/web-development-101/lessons/html-and-css-basics), Assignment point 3:

> Learn about basic forms from this Treehouse video and use this w3 page as a reference.

I think the Treehouse video is a bit redundant here and could be removed. It does not cover anything on forms that is not already covered in Codecademy or HTML Dog. And both actually dig in deeper into forms than the Treehouse video.

If the maintainers agree, I could submit a PR.

**Comment by hobbes543** [comment]
I will also note that when I went to the video today, there was a notice at the top of the screen that the video is scheduled to be retired on 1/6/2020
