### ISSUE TITLE
Codecademy Git Course Requires CC info

### ISSUE THREAD

**Issue by hobbes543** [TheOdinProject/curriculum#12232]
The Codecademy course referenced in the Git basics lesson is part of a paid course.  While the specific lesson is allowed to be tried for free, Codecademy requires that you enter CC info to do so.  I think it would be best if an alternate source is found for this exercise.

**Comment by krupenja** [comment]
Duplicate of https://github.com/TheOdinProject/curriculum/issues/12086

**Comment by leosoaivan** [comment]
And related to #12108
