### ISSUE TITLE
Show your appreciation

### ISSUE THREAD

**Issue by cruzick** [TheOdinProject/curriculum#12231]
In the chat features section it shows a space before the ++ after the username.  After trying in chat I found that there cannot be a space.  

https://www.theodinproject.com/courses/web-development-101/lessons/join-the-odin-community#chat-features

**Comment by 105ron** [comment]
It does work with the space. Is there a particular user name you found this issue with?

**Comment by cruzick** [comment]
I wonder if the bot was having problems?  My message in #general at 7:17  
`@SoWoke ++`  didn't cause the bot to respond.  
`@SoWoke++`  did cause the bot to respond.

**Comment by 105ron** [comment]
The back end of the bot is hosted on heroku unless it has been changed. If no one on has allocated points, the heroku dyno needs to be woken before the request is processed, which is very slow. So it might just be the time delay from your first points coming back looking like it was sent on the one without spaces?

**Comment by cruzick** [comment]
I just tested again, it is only triggered without a space...

![image](https://user-images.githubusercontent.com/19144184/64903164-ba825000-d679-11e9-84cc-979666a19955.png)

**Comment by cruzick** [comment]
My mistake... it inserts a space automagically after @'ing someone
