### ISSUE TITLE
Getting "nvm is not compatible with the npm config..."

### ISSUE THREAD

**Issue by MJae** [TheOdinProject/curriculum#12278]
Following all previous instructions, whenever I get to `nvm use node`, this is the response I get:
```
nvm is not compatible with the npm config "prefix" option: currently set to "/home/joan/nvm/versions/node/v12.10.0"
Run `nvm use --delete-prefix v12.10.0` to unset it.
```
Ignoring that and running `node -v` as in the next step in the instructions gives me this:
```
Command 'node' not found, but can be installed with:

sudo apt install nodejs
```
Of course, running `nvm use --delete-prefix v12.10.0` gives me:
```
Now using node v12.10.0 (npm v6.10.3)
```
Then I can use `node -v` as expected: `v12.10.0`

**Comment by leosoaivan** [comment]
Did you try uninstalling and re-installing 12.10.0?

**Comment by MJae** [comment]
I just tried that and I'm not sure if it's completely OK now, but I'm not seeing the complaints from last time. Thanks.

**Comment by leosoaivan** [comment]
In that case I'll close the issue, but feel free to re-open 👍
