### ISSUE TITLE
Happy Bear blog post link no longer valid

### ISSUE THREAD

**Issue by wing117** [TheOdinProject/curriculum#12374]
Happy bear blog post hyperlink under "Motivation" is no longer valid and returns a 'no such app' error.

File path: 
curriculum/web_development_101/the_basics/introduction_to_web_development.md

Relevant text: 
"Read **this comprehensive blog post from Happy Bear Software** about the journey to getting hired as a brief introduction to what you will face ahead."

**Comment by tfantina** [comment]
I got in touch with the guy who wrote the article, although he hasn't followed up if we can post it elsewhere.  Is there any reason not to like to the article on WayBackMachine?
