### ISSUE TITLE
Remove mentions of Rails from JS Track

### ISSUE THREAD

**Issue by leosoaivan** [TheOdinProject/curriculum#12553]
## Description
After breaking out JavaScript/Node.js into its own track, we are still referencing Rails in a few lessons, including but not limited to shared lessons, such as WebDev101.

To begin addressing this issue, the following should be addressed:

- [x] Identity and list any JS/Node lessons (with links in the repository) that mention Rails that are **not** in shared tracks, if any.
- [x] If such lessons exist, discuss with mods the course of action.
- [ ] Make edits as necessary

This issue can be considered close when the above tasks have been successfully addressed.

## Related
* https://github.com/TheOdinProject/curriculum/issues/11148

**Comment by Girlscoding-ng** [comment]
Hey @leosoaivan @arku Good day.... will like to work on this issue but will need some little direction on what to do

**Comment by leosoaivan** [comment]
@Nelson-Chinedu thanks for taking a look at this.

The Odin Project's JS curriculum lives in this sub-directory: https://github.com/TheOdinProject/curriculum/tree/master/javascript.

We'd like to first identity where Ruby on Rails is mentioned. The way you search through this directory is up to you. GitHub search, or cloning the curriculum and doing a search on your IDE/text editor is fine, too.

The first step is creating a list of which pages mention Rails. Obviously, the entire section titled "JavaScript and Rails" will need to be addressed. See if you can find any other places.

Let us know if you have further questions, and thanks again for picking this up :) 👍

**Comment by Nelson-Chinedu** [comment]
Ok, so is there any style guide to follow for contributing regarding branching and commit @leosoaivan

**Comment by leila-alderman** [comment]
@Nelson-Chinedu We're not too particular about branching and committing. If you're looking for some guidance, we have [a section on contributing](https://github.com/TheOdinProject/curriculum/blob/master/contributing.md). If you're not sure where to start, I recommend [the first video linked there](https://www.youtube.com/watch?v=V74l_zS1x8E).

**Comment by Nelson-Chinedu** [comment]
Ok I just raised a PR on https://github.com/TheOdinProject/curriculum/pull/12586 regarding the issue on what to do first @leila-alderman, will like to know if am on track with the issue

**Comment by leila-alderman** [comment]
@Nelson-Chinedu Thanks for working on this issue and for creating a list of lessons! That's a great first step. We probably don't need to upload a new file with that list to our curriculum, though. This issue would be a great place to store that list to get started:

- [ ] conclusion.md
- [ ] project_final_js.md
- [ ] angular.md
- [ ] introduction.md
- [ ] project_rails_backend.md
- [ ] rails_backend.md
- [ ] README.md

**Comment by Nelson-Chinedu** [comment]
Oh ok cool, so what's the next thing to do @leila-alderman

**Comment by leosoaivan** [comment]
@leila-alderman @Nelson-Chinedu I'd like to review these pages for the content, and, in discussion with other mods, decide on a course of action.

Once that's done, I'd like to ideally create a single, separate ticket for each page. We can make sure that you are then assigned to at least one of them @Nelson-Chinedu.

**Comment by Nelson-Chinedu** [comment]
Ok cool @leosoaivan

**Comment by nearmint** [comment]
@leosoaivan I'd also be willing to help! Did you guys make any progress?

**Comment by twalton83** [comment]
Any progress? I'd be happy to help.

**Comment by I3uckwheat** [comment]
@CouchofTomato Does the work you have done to remove Rails from 101 change this?

**Comment by CouchofTomato** [comment]
@I3uckwheat No, this sounds like it's in the full JS track which I didn't touch.

**Comment by leosoaivan** [comment]
@codyloyd I reviewed the links in @leila-alderman 's comment (https://github.com/TheOdinProject/curriculum/issues/12553#issuecomment-539526350) and it doesn't seem like the mentions of Rails in these files are significant, i.e., they can be taken generally.

Proposal:
- https://github.com/TheOdinProject/curriculum/blob/master/javascript/finishing-up/conclusion.md: Leave it.
- https://github.com/TheOdinProject/curriculum/blob/master/javascript/finishing-up/project_final_js.md: Remove Ruby & Rails mentions, but replace Additional Resources.
- https://github.com/TheOdinProject/curriculum/blob/master/javascript/frameworks/angular.md: Leave it, or provide a different analogy.
- https://github.com/TheOdinProject/curriculum/blob/master/javascript/introduction/introduction.md: Leave it.
- https://github.com/TheOdinProject/curriculum/blob/master/archive/javascript/project_rails_backend.md: Archived, and therefore inconsequential.
- https://github.com/TheOdinProject/curriculum/blob/master/javascript/js-rails/rails_backend.md: Addressed by a note at the top.

**Comment by I3uckwheat** [comment]
To follow up with @leosoaivan:

- [ ] https://github.com/TheOdinProject/curriculum/blob/master/javascript/finishing-up/conclusion.md
  - Add "node" equivalent to Rails, or just mention "backend of your choice"

- [ ] https://github.com/TheOdinProject/curriculum/blob/master/javascript/finishing-up/project_final_js.md
  - Add "node" equivalent to Rails, or just mention "backend of your choice"
  - Add additional resources for Node, though this should be covered in the Node course. 

- [x] https://github.com/TheOdinProject/curriculum/blob/master/javascript/frameworks/angular.md
  - Deprecated

- [ x ] https://github.com/TheOdinProject/curriculum/blob/master/javascript/introduction/introduction.md
  - Leave it

- [ x ] https://github.com/TheOdinProject/curriculum/blob/master/archive/javascript/project_rails_backend.md
  - Archived, and therefore inconsequential.

- [ x ] https://github.com/TheOdinProject/curriculum/blob/master/javascript/js-rails/rails_backend.md
  - Fixed

**Comment by I3uckwheat** [comment]
Closing and breaking into individual issues
