### ISSUE TITLE
Event Manager Tutorial: missing "url" from Google's Civic Information API response

### ISSUE THREAD

**Issue by mammothb** [TheOdinProject/curriculum#12616]
For the the inputs from "Small Sample", `url` could not be found in the Google's Civic Information API response despite being listing in its [documentation](https://developers.google.com/civic-information/docs/v2/representatives#elected-officials).

Suggested fix: Use social media information instead so that we're still creating 2 table cells.
```
<% if legislator.channels %>
  <td>
    <%= legislator.channels.map do |channel|
          "#{channel.id} (#{channel.type})"
        end.join(", ") %>
  </td>
<% end %>
```

**Comment by mindovermiles262** [comment]
Hey @mammothb 

After looking at this it appears you were using `url` and not `urls`  The typo may have been the source of the error.

I'm going to close this for now. If you believe that it's still an issue please let us know by opening a new issue

Thanks
