### ISSUE TITLE
Each Course Is displayed twice (Photo Attached)

### ISSUE THREAD

**Issue by scottrobel** [TheOdinProject/curriculum#12636]
![odin](https://user-images.githubusercontent.com/54362821/66687409-8f772600-ec50-11e9-8a83-ec76cbd5c249.PNG)
on the  page [https://www.theodinproject.com/tracks/2](url) Every course is displayed Twice

**Comment by leosoaivan** [comment]
Issue will be tracked on main-site repo: https://github.com/TheOdinProject/theodinproject/issues/1034

**Comment by arku** [comment]
Closing as it is being tracked in https://github.com/TheOdinProject/theodinproject/issues/1034
