### ISSUE TITLE
JavaScript 101 page is not found

### ISSUE THREAD

**Issue by bon22801** [TheOdinProject/curriculum#1273]
In the [Javascript Basics] (http://www.theodinproject.com/javascript-and-jquery/javascript-basics), the  [Javascript 101 from learn.jquery.com] (http://learn.jquery.com/javascript-101/) assignment page is not found.

**Comment by nhquiroz** [comment]
What topics did it cover?

Maybe these can help:

- http://slides.com/concise/js#/
- http://gitbookio.gitbooks.io/javascript/content/en/index.html

**Comment by jacknguyen** [comment]
According to this [#257](https://github.com/jquery/learn.jquery.com/issues/257) the community seem to think that the MDN guide should be the main reference material.

[MDN reference guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide)

**Comment by jacknguyen** [comment]
Also found a cached version just to see if there's another source for some of the materials.
[Web Archive](http://web.archive.org/web/20141113155945/http://learn.jquery.com/javascript-101/)

**Comment by jacknguyen** [comment]
But I think this primer from MDN is great [MDN material](https://developer.mozilla.org/en-US/Learn/Getting_started_with_the_web/JavaScript_basics).

What do you think @eriktrautman? Can I edit the curriculum to point to this instead of the jquery material.

**Comment by eriktrautman** [comment]
It's not quite apples-to-apples.  The JS101 stuff from learn.jquery.com was comprehensive.  I'd rather not link to an archive link, though.  Does it exist anywhere else?  I'm fine with adding the MDN stuff but it's not really that effective as a main resource -- more as an "additional resource".

**Comment by nhquiroz** [comment]
Maybe this course (+ JS Basics from MDN) helps

https://www.codeschool.com/courses/javascript-road-trip-part-1
