### ISSUE TITLE
Update directions to explain how to set up SSH key if it doesn't work wtih Github

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#12820]
Related to #12259 

If someone somehow misses setting up their SSH key before they get here, they will have difficulty with the step changed in the commit above. Chances are they'll be able to google their way out of it, or ask for help in the discord, but it'd be nice to have the fix right there.

**Comment by mefaba** [comment]
First: Check if OpenSSH client active. 
Windows 10 Settings > Apps & Features > Optional Features
In listed features there should be OpenSSH Clients. If not click "Add a feature" and find OpenSSH Client.

Check next link if you couldn't do. https://ittutorials.net/microsoft/windows-10/enable-ssh-windows-10-command-prompt/

Open the cmd. Enter following commands then you can copy id_rsa.pub with "clip" or "cat" command>

```
C:\Users\Username>
C:\Users\Username>cd .ssh
C:\Users\Username\.ssh>
C:\Users\Username\.ssh>ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
C:\Users\Username\.ssh>ls
id_rsa id_rsa.pub
C:\Users\Username\.ssh>id_rsa.pub|clip or C:\Users\Username\.ssh>cat id_rsa.pub
```

SSH Key is two keys. We are generating them in our computers. They are two long passwords. One of them is private key, other is public key. We will put our public key into github settings. And when we want to take any file from github, github will know thats us.

Now you can add your public key to github>settings>SSH Keys > New SSH Key

**Comment by I3uckwheat** [comment]
@mefaba This needs a PR to modify the lesson contents. This isn't asking for help.

**Comment by mefaba** [comment]
I dont know what PR means. If you are saying this is not the contribution you need than, probably I did not understood the situation . If it is explanation is okay, you can assign me for the task I can try to make merge request or something to original file that you linked.

**Comment by I3uckwheat** [comment]
@mefaba I see you used windows commands there, this is not currently a windows curriculum. We also have git installation directions, we just need to link back to them if somebody has issues using `ssh` in this specific lesson. Can you do this?

**Comment by I3uckwheat** [comment]
@ZachBaird Awesome, thank you.

**Comment by mefaba** [comment]
Ok, I guess, I cant do this. I mean  I would like to, but seems like I am not eligible.

**Comment by I3uckwheat** [comment]
@mefaba If @ZachBaird Doesn't finish this soon, I will assign to you :)
