### ISSUE TITLE
Command Line Resource Unavailable

### ISSUE THREAD

**Issue by bycdiaz** [TheOdinProject/curriculum#12854]
The resource, [Conquering the Command Line](http://conqueringthecommandline.com/book/basics), from the [Command Line Basics lesson](https://www.theodinproject.com/courses/web-development-101/lessons/command-line-basics-web-development-101) presents this error when accessed:
![image](https://user-images.githubusercontent.com/34174677/67639071-d6585300-f8c1-11e9-8418-d3a77f58e4f7.png)

I've reached out to the author to ask about their plans for the resource. In the mean time, an alternative resource should be identified.

**Comment by ReplacedByAutocorrect** [comment]
i've also reached out to the author and looked for alternate ressources that explain the commands and found this:
https://tutorials.ubuntu.com/tutorial/command-line-for-beginners#0
will need review of a mac user so we can note differences.

**Comment by bycdiaz** [comment]
Heard back from Michael Hartl. Said they are looking into why the error is appearing.

**Comment by kennguyen01** [comment]
I found this bug several hours back and created a PR to remove link with no content. I think [Command Line](https://linuxjourney.com/lesson/the-shell) from Linux Journey is a good replacement.

**Comment by bycdiaz** [comment]
The resource is back online. Closing issue.
