### ISSUE TITLE
Dead link in the Getting Hired section

### ISSUE THREAD

**Issue by Uzay-G** [TheOdinProject/curriculum#12881]
A main part of the strategy file in the Getting hired section is the no longer functional link to this article: http://happybearsoftware.com/how-to-get-a-programmer-job.html

I could not find the same article that no longer exists but here are some alternatives that I could make a pull request for:
- https://codinginflow.com/get-job-as-programmer
- https://www.codementor.io/codementorteam/how-to-get-your-first-developer-job-even-if-you-don-t-have-a-cs-degree-8b60y8ch2

Of course I can't see the dead article so I don't know what was is in it.
Thoughts on what to do?

**Comment by martink-rsa** [comment]
The dead link @Uzay-G refers to can be found in an archive. Here is the latest snapshot available (8 March 2019):
http://web.archive.org/web/20160925155912/http://www.happybearsoftware.com/how-to-get-a-programmer-job.html

This is the search for the dead link:
http://web.archive.org/web/*/https://www.happybearsoftware.com/how-to-get-a-programmer-job.html

**Comment by Uzay-G** [comment]
Alright I fixed the dead link

**Comment by greenteaisgreat** [comment]
It seems to be dead again, as that the link now says that web archive's servers aren't responding

**Comment by twalton83** [comment]
@greenteaisgreat it appears to be working, I just accessed it. However, if web archive's servers are down, that's more so an issue with web archive. I know there was a major outage across the internet earlier today that could be related.

**Comment by greenteaisgreat** [comment]
Hmm, strange. It's giving me a ERR_NAME_NOT_RESOLVED description. I'm also trying to access it from my work's network, which has a bunch of strange restrictions (state laboratory), so that could very well be the issue.

Appreciate your prompt response! I'll check it out once I'm on my home network.

**Comment by jotisa** [comment]
Just in case the article got posted here:
https://www.scribd.com/document/521873510/How-to-get-a-job-as-a-web-developer
thx
