### ISSUE TITLE
GitHub Wiki or standard page for FAQ/Troubleshooting

### ISSUE THREAD

**Issue by martink-rsa** [TheOdinProject/curriculum#12894]
**Intro:**
GitHub has an option to add a Wiki page.

It would be incredibly useful to have a Wiki page setup that deals with common issues and errors that users often come across.

The Wiki page could feature written instructions as well as short gifs/videos (no audio) that demonstrate what should be done. These gifs/videos can easily be captured by contributors using a tool such as ShareX which allows regions to be captured.

**The effects and uses:**
Implementing this will hopefully, and not be limited to:

- keep fixes standardized for people attempting to assist others, as well as prevent errors when giving instructions
- allows students to fix issues themselves 

Hyperlinks to these issues can then be shared in Discord by others, even by those who do not have the knowledge to assist but are able to match the issue with the relevant question.

**Implementation:**
The layout of the FAQ/Troubleshooting page can correspond with the way lessons are laid out e.g. A page dedicated to Web Dev 101, a page dedicated to Javascript etc. This prevents the FAQ/Troubleshooting page from becoming a mess as it grows.

Not all questions that arise need to be added to these pages. Questions can be added on the basis of their frequency in Discord/Forums, such as it being dealt with at least 5 times a week.

The Github Wiki pages use the same system as repos, so contributions are dealt with the same way as the curriculum is.

**Comment by kashura** [comment]
@martink-rsa What kind of help do you need to get this going?

**Comment by martink-rsa** [comment]
@kashura Need moderators and those in charge to give the go ahead. Once they do, I believe they will then need to create the first Wiki page so the Wiki repo exists. It will then function as a normal repo like the way the curriculum does.

**Comment by mindovermiles262** [comment]
@martink-rsa This is a great idea. Let me see what I can do

**Comment by mindovermiles262** [comment]
https://github.com/TheOdinProject/curriculum/wiki should now be accessible. Will ping @martink-rsa on discord to determine if they have the correct permissions

**Comment by martink-rsa** [comment]
Wiki site is live and permissions granted. I don't believe there is further to add to this issue.
