### ISSUE TITLE
Easier & faster alternative to changing CD image files in VirtualBox

### ISSUE THREAD

**Issue by martink-rsa** [TheOdinProject/curriculum#12917]
This is regarding the lesson **Prerequisites** found in **Web Development 101** where a student follows instructions to mount the Xubuntu ISO in VirtualBox:

https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites?ref=lnav

The paragraph reads as follows:

> Next, go to the “Storage” tab and in the “Attributes” column, beside the “Optical Drive” indicator, click the round, blue icon. This will present a drop-down menu. Click “Choose Virtual Optical Disk File…” and select the Xubuntu ISO file you downloaded earlier. If you aren’t sure where to find it, start by looking in your Downloads folder.

A user can access the digital optical drive from the main window in VirtualBox by clicking on the text related to the digital optical drive. I believe this is a lot ore accessible, easier and faster for a user. An illustration demonstrating this should appear below:

![image](https://user-images.githubusercontent.com/52622303/67975561-02a30500-fc1d-11e9-9974-f2c60aaf3b43.png)

I am unsure of what the best route is to alter the lesson to include the above as it currently uses a sequence of events that take place within the Settings window when the other method takes place in the main VirtualBox window.

Three possible options are:
- Include two separate methods e.g. Method 1, Method 2
-  Add the new method as a **Note**, informing the student that there is an additional way to access the digital Optical Drive (This allows them to also learn how to access the digital Optical Drive within the Settings window)
- Delete the old method and alter the instructions to the suit the new method.

**Comment by zachmmeyer** [comment]
You could submit a pull request in this section with your proposed changes and reference it here :)

**Comment by I3uckwheat** [comment]
@zachmmeyer Can you please look into this after the changes you have made to the vbox installation directions?

**Comment by zachmmeyer** [comment]
The instructions provided in the rework I did have the user go through the settings. They would already be in the settings.
Clicking on the storage button on the main page seems like an exit from that flow. That's my opinion.

**Comment by I3uckwheat** [comment]
Thanks @zachmmeyer! I'm closing this for now :)
