### ISSUE TITLE
WSL chmod issue

### ISSUE THREAD

**Issue by nyanlinnaung** [TheOdinProject/curriculum#13061]
So, i was starting odin project and got stuck in Step 1.3 of [your first rails app](https://www.theodinproject.com/courses/web-development-101/lessons/your-first-rails-application?ref=lnav).

If i run `rails new my_first_rails_app`  the wsl will give me an error regarding chmod issue. I was googling the issue and found out it can be fixed by unmounting and mounting back the folder as described here [https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/](url). 

`sudo umount /mnt/c`
`sudo mount -t drvfs C: /mnt/c -o metadata`
Just thought these two command should be added before creating new rails app to help newcoming wsl users like me.

Thanks

**Comment by mindovermiles262** [comment]
WSL is not supported by The Odin Project.

Remounting the C Drive inside of WSL could cause serious issues with the windows installation if done improperly. For this reason we do not recommend using WSL.
