### ISSUE TITLE
Content in 'HTML and CSS' should be moved to Web Dev 101

### ISSUE THREAD

**Issue by martink-rsa** [TheOdinProject/curriculum#13166]
Currently, the course is structured as follows:
'Web Development 101' -> 'Javascript' -> 'HTML and CSS'

'HTML and CSS' contains content that should be introduced to students before JavaScript begins. 

I am referring to the first 3 parts of 'HTML and CSS' which are:

1. [**Basic HTML Page Structure:**](https://www.theodinproject.com/courses/html5-and-css3#basic-html-page-structure)
This mostly deals with hyperlinking, a basic concept students should become familiar with.
2. [**Displaying and Inputting Data**](https://www.theodinproject.com/courses/html5-and-css3#displaying-and-inputting-data)
Deals with Tables, Lists and Forms
3. [**CSS**](https://www.theodinproject.com/courses/html5-and-css3#css)
This deals with CSS page layout tools (Box model, float, Flexbox, grid) and then CSS gradients at the end.

These sections above are greatly out of place and should be introduced to a student before they begin with JavaScript.

The reasons for this are:
1. The sections above are part of HTML and CSS foundations, and students should become accustomed to using them which would happen if they were moved to Web Dev 101.
2. The projects instruct students to apply the above topics when they haven't yet been introduced to them as 'HTML and CSS' is only after JavaScript. This leads to students having to learn about these topics on their own, who then already know these topics in great detail by the time they reach the 'HTML and CSS' sections above. Examples of this is the Etch-a-Sketch project in which a CSS Grid is to be utilized, or the ['Forms' lesson in Javascript](https://www.theodinproject.com/courses/javascript/lessons/forms-javascript).

I wish to share some perspective as to show how out of place the `HTML and CSS' section is:
A student learns to use a Frontend Framework (Vue/Angular/React) before they are introduced to CSS Grid, Flexbox, and even HTML tables, forms and lists. 

I believe it would be prudent for the curriculum to follow a typical front-end road map for progression, such as the following image (featured here: https://medium.com/@kamranahmedse/modern-frontend-developer-in-2018-4c2072fa2b9c). Please note that I am not stating that new content should be added, but instead it could be used as a point of reference for the current content, as well as illustrate as to here the HTML and CSS sections can be moved to.

![1_DfKcPCa8GWVvWC61P2eBRg](https://user-images.githubusercontent.com/52622303/68961077-25671900-07da-11ea-9d5b-d3d92a16766b.png)

**Comment by martink-rsa** [comment]
A possible fix would simply slot the 'HTML and CSS' module between Web Dev 101 and JavaScript so the structure is as follows:
Web Dev 101 -> HTML and CSS -> JavaScript

**Comment by ch264** [comment]
I also noticed this @martink-rsa and I agree. 

Can I give this ticket a shot?

**Comment by I3uckwheat** [comment]
We really do like having people jump into code really quickly, it's really easy to get bored learning HTML, and now that we've added some different HTML+CSS stuff to the 101, this may no longer be relevant.

**Comment by codyloyd** [comment]
these things _are_ introduced in WD101.

the main HTML course is out of date and we should focus on fixing that..... but these concepts do not need to be moved at this time.
