### ISSUE TITLE
Dead Link - Ruby Programming: Recursive Methods Assignment

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/curriculum#13188]
> Watch this [Video on Recursion](http://vimeo.com/24716767) by Joshua Cheek but only until minute 17:36! (don’t want to give away the project…)

The linked video does not exist.
I have not reached this portion of the curriculum yet, but once I do I will try and find some videos that helped me out.

**Comment by martink-rsa** [comment]
Can't seem to find a mirror for the video. Asked creator (Mr Joshua Cheek) if he will be making it available again.

**Comment by Eduardo06sp** [comment]
> Can't seem to find a mirror for the video. Asked creator (Mr Joshua Cheek) if he will be making it available again.

I don't know how far you are in the curriculum, but maybe you could suggest a video that would be good for beginners :}

I want to wait until I get to it so I can see what would be beneficial to someone doing all the assignments in order!

**Comment by martink-rsa** [comment]
Author responded. I believe he will be reinstating the video so it might be best to wait a little to see what he comes back with before a new source is found.

**Comment by martink-rsa** [comment]
The author has reinstated the video. I believe this issue is resolved.

**Comment by Eduardo06sp** [comment]
I appreciate that Martin! I didn't even think to simply get his contact information and ask him directly!!!

**Comment by Eduardo06sp** [comment]
The video is up and running again. Problem solved.
