### ISSUE TITLE
Ruby Rogues podcast 404

### ISSUE THREAD

**Issue by vladthelittleone** [TheOdinProject/curriculum#13224]
The Ruby Rogues [podcast on How to Learn](http://rubyrogues.com/131-rr-how-to-learn/) responds 404.

Files including this link:
[line 21](https://github.com/TheOdinProject/curriculum/blob/3adf0938c159f4ba0dd50a26db2441b634d8fed1/archive/extra_stuff/old_lessons/introduction_to_web_development/conclusion.md)
[line 64](https://github.com/TheOdinProject/curriculum/blob/ee350ae2d6e03e1bafb1d6953b54202dd5636c95/web_development_101/the_basics/gearing_up.md)

**Comment by martink-rsa** [comment]
> line 21
This links to the archived older material and I don't believe this page is used anymore.

> line 64
Fixed with #13283
