### ISSUE TITLE
Ruby/ROR is mixed in with the Full stack JavaScript route and front end only (non ruby)

### ISSUE THREAD

**Issue by coih** [TheOdinProject/curriculum#13319]
I think that If it says ruby won't be present, that it shouldn't be seen in the non ruby routes(Full stack JavaScript and html css.
This way it will not confuse users into doing Ruby when they picked the other paths that shouldn't include ruby.

Also, when you are about to select the front-end only path, it says, 
"FRONT END ONLY
View track
This track takes you through all of the front-end content in our curriculum. You'll learn HTML, CSS and JavaScript, but you will not encounter any Ruby or **Rails."**
But in the track, Ruby is present in the Web developement 101.

As well as the full stack web dev 101 and also the JavaScript section in the full stack web dev path have got ruby in the mix.

The routes should stay true to their "promises".

**Comment by BunnyTheLifeguard** [comment]
Oh so there is absolutely no ruby in the JS route?

**Comment by BunnyTheLifeguard** [comment]
Yeah, it's a little confusing to go the Fullstack JavaScript route only to find installation instructions for Ruby in WebDevelopment 101 and JavaScript & Rails in the JavaScript section :/

**Comment by I3uckwheat** [comment]
This has been fixed :)
