### ISSUE TITLE
Unclear description @ javascript/introduction/js101-review.md

### ISSUE THREAD

**Issue by nearmint** [TheOdinProject/curriculum#13681]
Hi all, 
the following page has an unclear direction, which should be fixed: 
https://github.com/TheOdinProject/curriculum/blob/master/javascript/introduction/js101-review.md

I'm talking about this sentence: "Running through the first part of either of those exercises is a great idea for a refresher on the syntax." 

It's unclear what the author means by "the first part of either of those exercises". Exercises may refer to the MDN and the Javascript.info link, but what does he mean by "the first part"? 

Looking at the Javascript.info link, it has a plethora of Javascript resources.

**Comment by GraniteBeltWebAndSoftwareSolutions** [comment]
Maybe a better word would be keywords instead of syntax. I am thinking that is what is meant.
