### ISSUE TITLE
Add a link for designs in "Project: Building Your Personal Website"

### ISSUE THREAD

**Issue by harrisj09** [TheOdinProject/curriculum#13764]
Someone should add a link to a bunch of designs (that don't include the source code) for users to get inspiration as to how there website should look. This [link](https://www.may1reboot.com/#/) is a good example.

Students should have a good idea of what level of quality they are striving for, the nature of student solutions mean that there are varying levels of quality and a bad portfolio may not be the best thing a student should use to base their own on. Some helpful links of examples of really good portfolios to get ideas of, will help students form their own. 

A good portfolio has these elements (non inclusive or exclusive)
* Their full name
* link to their professional social media (linkedin/github)
* link to their resume
* a showcase of their projects and links to live versions of them

Some text should be added encouraging students to reflect on the linked sites and then make a design of their own for their portfolio.

**Comment by I3uckwheat** [comment]
The link attached seems to take one this
![image](https://user-images.githubusercontent.com/4411701/79415376-1a1f4180-7f62-11ea-8246-8998d00659ac.png)

I agree we could use more links on that page, below is the page:

https://www.theodinproject.com/courses/getting-hired/lessons/building-your-personal-website

**Comment by Kshubhranshu** [comment]
i will do it.

**Comment by I3uckwheat** [comment]
@Kshubhranshu Awesome! Thank you!

**Comment by harrisj09** [comment]
I don't know why that came up, It worked perfectly fine when I posted this issue. You could also add a section that allows people who used the odin project to learn web development to post there personal sites.

**Comment by I3uckwheat** [comment]
@harrisj09 That is what the "student solutions" are for here

**Comment by I3uckwheat** [comment]
Re-opening as it is not completed

**Comment by mKawi** [comment]
I'm happy to take this task on if that's okay?

**Comment by I3uckwheat** [comment]
@mKawi Sure, i'll assign this one to you!

**Comment by mKawi** [comment]
Sorry for the delay, got caught up with a few personal things.

I've managed to find a good [link](https://spyrestudios.com/web-developer-portfolio/) that showcases portfolios to derive inspiration from. It was a little difficult to find a resource that wasn't outdated, had dead links, and wasn't behind a subscription wall e.g. Medium.

However, I feel we might encounter the same issues in the future as developers make drastic changes to their portfolios or domains are abandoned.

An alternative solution is to create and link to a GitHub repository that showcases portfolios instead, solving all those issues mentioned. We can keep it constantly updated, remove any future dead links, and allow others to contribute.

I'm more than happy to do this as I have a growing collection of bookmarked portfolios. Let me know if you guys would like me to proceed with the repo, or stick with the initial plan of linking to a [resource](https://spyrestudios.com/web-developer-portfolio/).

**Comment by I3uckwheat** [comment]
@mKawi Feel free to add the list to this markdown file itself too. Then we can more easily keep an eye on them :)

**Comment by ExpressHermes** [comment]
Is @mKawi still working on this or can I take this issue?

**Comment by I3uckwheat** [comment]
@ExpressHermes I will assign it to you

**Comment by ExpressHermes** [comment]
@marvingay wouldn't be better to add website like [awwwards](https://www.awwwards.com/awwwards/collections/freelance-portfolio/) and [this](https://m.webdesign-inspiration.com/web-designs/type/portfolio) as they have whole section dedicated to portfolios. It would also avoid future dead links.
