### ISSUE TITLE
How to indicate whether a resource is useful?

### ISSUE THREAD

**Issue by LaDilettante** [TheOdinProject/curriculum#138]
As I go through the courses, some of the resources are remarkably better at explaining things than others. Is there a way for us to include a poll / upvote system that allows users to indicate the usefulness of each resource?

This will keep the curriculum fresh and constantly tested. Even if the result is not public, the ability to mark a resource as helpful is still valuable to an user as a record-keeping device.

**Comment by KevinMulhern** [comment]
No progress has been made with this in over a year, It could go in the ideas ticket on Trello.
