### ISSUE TITLE
Fix rbenv install commands in Step 2.1 of "Installing Ruby" under Web Development 101

### ISSUE THREAD

**Issue by kenrickbuduan** [TheOdinProject/curriculum#13948]
In Step 2.1 of Installing Ruby under Web Development 101, learners are instructed to type these command to the terminal:

```
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exit
```

However, these commands throw an error upon reopening the terminal. After some debugging and tinkering in the ```.bashrc```, I found that there is no line  break between the ```esac``` and ```export...```. Thus, the error I see in the terminal.

I suggest adding a new line character before the ```export...``` to solve this problem.

I'm running on elementaryOS 5.1, by the way.

**Comment by mindovermiles262** [comment]
Hi @kenrickbuduan 

I think this issue might be specific to ElementaryOS.  Using MacOS `echo` always creates a newline before appending:

```
[~]$ echo "firstline" >> newfile
[~]$ cat newfile 
firstline
[~]$ echo 'secondline' >> newfile 
[~]$ cat newfile 
firstline
secondline
```
