### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by olav35** [TheOdinProject/curriculum#13972]
Assignment: https://www.theodinproject.com/courses/ruby-programming/lessons/ruby-building-blocks?ref=lnav#assignment

Dead link: https://github.com/ruby/ruby/blob/trunk/doc/syntax/literals.rdoc#strings

I would have sent in a pr, but I am not exactly sure what it was supposed to link to. I might look into it later though.

**Comment by mindovermiles262** [comment]
I think it can be replaced with this link:

https://docs.ruby-lang.org/en/2.0.0/syntax/literals_rdoc.html#label-Strings

**Comment by CrispyCB** [comment]
Correct link is:

https://github.com/ruby/ruby/blob/master/doc/syntax/literals.rdoc#strings

**Comment by Eduardo06sp** [comment]
I had the same exact problem, looks like they updated the link now! :+1:

**Comment by olav35** [comment]
The link is revived. Closing issue.
