### ISSUE TITLE
Javascipt.Info down

### ISSUE THREAD

**Issue by imthatalex** [TheOdinProject/curriculum#14238]
page where issue is found: 

https://www.theodinproject.com/courses/web-development-101/lessons/fundamentals-part-2?ref=lnav

issue found: when trying to access tutorial "Logic Operators" 

Quick solution: use w3schools version, link here: https://www.w3schools.com/js/js_comparisons.asp

**Comment by Eduardo06sp** [comment]
Looks like it's up & running again :}

**Comment by I3uckwheat** [comment]
Closing because the site is back :)
