### ISSUE TITLE
Dead links to Flatiron school

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/curriculum#1430]
Hi,

I'm currently working through the Odin Project from start to finish. The experience has been great thus far.

Within Web Development 101 ---> The Basics: Terms to Know ---> Assignment 1, all of the links are now dead. The content is technically hosted by The Flatiron School, but I figured that giving you all a heads up was likely more beneficial / faster than trying to contact them. 

If you prefer I contact The Flatiron School, please let me know! The list of terms looks great to have as reference.

With kind regards,

Drew (shima)

**Comment by nhquiroz** [comment]
How about the prep-work material from Viking, @eriktrautman? I didn't read it, does it covers the same basics as TOP does? Maybe it can be al alternative to some links.

**Comment by eriktrautman** [comment]
It'd be great to start including the Viking prep work in Odin, I've been meaning to link relevant lessons because they are pretty much exactly what's needed to fill a few gaps but haven't had the time.  At the very least, they can be added usually as an "additional resource".  Would be great to get those added!

**Comment by nhquiroz** [comment]
I just checked the links and they're all online, this issue can be closed.
