### ISSUE TITLE
Suggestion: Replace Foundations with TailwindCSS

### ISSUE THREAD

**Issue by styamsingh** [TheOdinProject/curriculum#14376]
In the unit [CSS Frameworks like Bootstrap and Foundation](https://www.theodinproject.com/courses/html5-and-css3/lessons/css-frameworks-like-bootstrap-and-foundation), the alternative to Bootstrap is Foundation which is fine but in my opinion, it should be replaced by [TailwindCSS](https://tailwindcss.com/) since it has been gaining a lot of steam lately and companies like Mozilla have been using it. It is also praised by developers for being very customizable and extensible.

**Comment by I3uckwheat** [comment]
While I don't think a replacement is necessary, adding to the lesson could help.

**Comment by KevinMulhern** [comment]
I don't see Foundation mentioned much anymore, tailwind however seems to be cropping up everywhere. I think it would be worth at-least adding to the lesson as you suggested @I3uckwheat

**Comment by mKawi** [comment]
I'd like to be assigned this task. 

If I'm understanding correctly, we should be keeping the Foundation sections intact, only adding a few additional links to TailwindCSS resources, so students are at least aware of its existence.

**Comment by I3uckwheat** [comment]
@mKawi I've assigned this to you, thanks!
