### ISSUE TITLE
Redundant assignments in databases

### ISSUE THREAD

**Issue by olav35** [TheOdinProject/curriculum#14403]
I find it redundant to have both the SQL teaching resource and SQL Bolt. Both resources are aimed at newbies and cover the same stuff so it is a waste of time to do both of them.

I think the first (SQL teaching) should be removes as that one is less modern and less in depth.
https://www.theodinproject.com/courses/databases/lessons/databases-and-sql?ref=lnav

**Comment by dvik1950** [comment]
I disagree with this and think that both are really short and there's really no need to remove either of them. The explain things a bit differently and someone who didn't understand some concepts from one might have more luck with the other one. A lot of stuff in the curriculum is explained 2-3 times (first in the lessons and then in externals resources) for this exact reason.

**Comment by I3uckwheat** [comment]
I agree with @dvik1950. Closing this issue. Thank you for the suggestion!
