### ISSUE TITLE
Contrubuting guide is not sufficent

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#14554]
The contributing guide links to videos and a walkthrough on how to contribute with `git`, however, these videos are outdated. 

We should also have some guidelines on what is appropriate to add or remove from the curriculum. 

Such as:
* Spelling mistakes
* wording 
* outdated materials
* their projects
* stating that it's important to follow proper formatting
* etc.

**Comment by mindovermiles262** [comment]
Issue is not sufficient

**Comment by I3uckwheat** [comment]
> Issue is not sufficient

I totally meant to add more to this, and then totally forgot

**Comment by zachmmeyer** [comment]
The readme states what can be contributed clearly for the curriculum. However, the link in that readme to a "contributing guide" brings to the overall contribution to TOP as a whole, letting the user choose between curriculum and main site. Maybe it should be reworded to not be the "guide" but just say:
###### To find out more about how you can contribute to The Odin Project, please read [here](https://www.theodinproject.com/contributing)

**Comment by I3uckwheat** [comment]
@zachmmeyer Great, I think that's a good idea.

**Comment by ZachBaird** [comment]
@zachmmeyer @I3uckwheat 
Is the direction for this issue still to change the URL wording in the readme to not say "guide"?

**Comment by ZachBaird** [comment]
@I3uckwheat After some poking around, we saw that the following Git section with pretty good content exists here in the Ruby Programming course: https://www.theodinproject.com/courses/ruby-programming?ref=lnav#git

However, no parallel section is in the JavaScript or NodeJS courses. We might want to create a section like HTML & CSS that's cross-track with the Git content.

For now, I'll modify the main readme to have clearer verbage and add some PR guidelines to contributing.md.

**Comment by I3uckwheat** [comment]
@KevinMulhern Do we have anything in the works like this ☝️

**Comment by KevinMulhern** [comment]
@I3uckwheat we did actually 😃

We planned on stand alone courses along side tracks, a git course was going to be one of those. Looking back over what was left for that course, we don't have a ton remaining. A couple of lessons need to be a bit more fleshed out and polished and one project needed written.

https://github.com/TheOdinProject/curriculum/issues/5379

We definitely should have parallel sections about intermediate git in each track as @ZachBaird suggested. But I think we should use this opportunity to complete what remains in that issue so we can use updated and better content among all the tracks.

Those lessons would also fit in with the git basics on web dev 101 better as they were designed to come after those whereas the git lessons in the Ruby course were there before and live in a vacuum. 

What do you guys think?

**Comment by I3uckwheat** [comment]
@KevinMulhern We really should get this git stuff figured out ASAP with our new push for PRs and help in the Discord chat. 

It wouldn't be too bad to put it in the 101, but I wonder how many people would take it seriously at that point. I think it should come after 101, as a standalone section that can be used in both Rails and Node. That way people have touched some code and may understand the use of it better. 

People forget things that they don't see as important. (We can tell them all we want, but I fear that it won't stick unless we make them learn the hard way 😆)

I'll re-open that ticket and clean it up, @KevinMulhern Can you link to the places where the stuff you have in mind?

**Comment by I3uckwheat** [comment]
@ZachBaird https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide

This could be useful to just link to for this specific issue.

**Comment by 105ron** [comment]
I'll handle this. 🔥 🧨 🚀 🧩 ☠️

**Comment by ZachBaird** [comment]
@105ron , I've identified some additional resources for consideration:

https://github.com/firstcontributions/first-contributions
https://egghead.io/lessons/javascript-how-to-create-a-pull-request-on-github (lessons 9 and 10 for PRs)

**Comment by I3uckwheat** [comment]
@ZachBaird If you want, I can re-assign this to @105ron, otherwise I'll leave you to work on it.

**Comment by I3uckwheat** [comment]
![image](https://user-images.githubusercontent.com/4411701/79898933-4525ed00-83c9-11ea-9e1b-0cebe211c714.png)
@ZachBaird, @105ron 

This is the kind of thing I would like to prevent with good documentation.

**Comment by I3uckwheat** [comment]
@105ron Have you made any progress on this?

**Comment by Sebastian-coderbrother** [comment]
Yeah I totally agree with u

**Comment by gualygaete** [comment]
I would like to try it out

**Comment by I3uckwheat** [comment]
@gualygaete Great! I'll assign it to you!

**Comment by I3uckwheat** [comment]
@gualygaete Any progress on this?

**Comment by ryanford-dev** [comment]
@I3uckwheat can we close this with #21812 ?

**Comment by I3uckwheat** [comment]
@ryanford-dev I think so, at least for now. We can re-evaluate later too. This will also be solved by the upcoming git course material.
