### ISSUE TITLE
Bad URL in node.js introduction

### ISSUE THREAD

**Issue by oakgrovedev** [TheOdinProject/curriculum#14564]
Link to https://briggs.dev/blog/understanding-callbacks in this paragraph:

> This process is almost exactly like the way that you would use addEventListener in front-end JavaScript to wait for a user action such as a mouse-click or keyboard press. The main difference is that the events are going to be things such as network requests and database queries. This functionality is facilitated through the use of callbacks. Callbacks are incredibly important to Node so take a minute to read through this article, to make sure you’re up to speed.

Does not work.

**Comment by zachmmeyer** [comment]
Link works just fine. @oakgrovedev could you close this issue?
