### ISSUE TITLE
Additional resources don't show as a list on the Flexbox page[HTML and CSS course]

### ISSUE THREAD

**Issue by rarysson** [TheOdinProject/curriculum#14698]
![Screenshot_2020-02-10 Flexbox The Odin Project](https://user-images.githubusercontent.com/22689195/74158130-48963e80-4bf8-11ea-985e-d97329b27d76.png)

https://www.theodinproject.com/courses/html5-and-css3/lessons/flexbox

**Comment by aaron-contreras** [comment]
I'll fix it!

**Comment by I3uckwheat** [comment]
@aaron-contreras Thank you!
