### ISSUE TITLE
 Dead Link: Ruby Programming Project: Event Manager 

### ISSUE THREAD

**Issue by AndrewHuntington** [TheOdinProject/curriculum#14808]
https://www.theodinproject.com/courses/ruby-programming/lessons/event-manager?ref=lnav#null

> This document is JSON formatted. If you copy and paste the data into a pretty printer, ...

http://jsonprettyprint.com/ appears to be dead. Perhaps a link to another pretty printing site should be used?

Top Google hits: 

https://jsonformatter.org/json-pretty-print
https://jsonformatter.curiousconcept.com/
https://codebeautify.org/jsonviewer

Thanks for your help!

**Comment by zachmmeyer** [comment]
Which do you like best? Let's pick one and submit it.

**Comment by I3uckwheat** [comment]
This has been fixed
