### ISSUE TITLE
Dead link: Git basics Additional resources

### ISSUE THREAD

**Issue by emberavenge** [TheOdinProject/curriculum#15006]
Rypress link(https://github.com/alokc83/Basic-Tutorials/tree/master/rypress.com%20Git) in the "Additional resources" gives a error 404 "Page not found"

There is a web.archives.org link(http://web.archive.org/web/20161119031653/http://rypress.com/tutorials/git/index), however it would respectful to ask the writer if they are okay with it being back up.

Thanks for all the hard work.

**Comment by zachmmeyer** [comment]
Nobody has been able to contact the author for a few years now. The Kindle version of the book is still available for free on Amazon, and there are links to the epub file here: https://www.smashwords.com/books/view/498426
I think the web archive is possibly the best option.
