### ISSUE TITLE
Dead Link: HTML and CSS - INTRODUCTION TO DESIGN AND UX

### ISSUE THREAD

**Issue by ikraamg** [TheOdinProject/curriculum#15016]
In the Assignment - 2. Read UX 101 – What is User Experience:
https://www.homestead.com/blog/06/2013/ux-101-what-user-experience-infographic

Perhaps replace with: 
http://web.archive.org/web/20190825035454/http://www.homestead.com/blog/06/2013/ux-101-what-user-experience-infographic

**Comment by zachmmeyer** [comment]
You could create a pull request and reference or close this issue

**Comment by ikraamg** [comment]
Fixed in pull request #15024
