### ISSUE TITLE
Outdated information on Bootstrap vs Foundation

### ISSUE THREAD

**Issue by ikraamg** [TheOdinProject/curriculum#15166]
Hi there!

This article: [Bootsrap 3 vs Foundation 5](https://medium.com/frontend-and-beyond/8b3812c7007c) on our [CSS frameworks page](https://github.com/TheOdinProject/curriculum/blob/master/html_css/css_frameworks.md) compares Bootstrap 3 and Foundation 5. 

We are currently on Bootstrap 4 and Foundation 6. I would suggest using [this article](https://medium.com/@davegenge/bootstrap-vs-foundation-which-front-end-framework-to-use-e85319258b88) (or similar) instead.

I could create the pull request if you think that this good.

Cheers!

**Comment by kblycaglayan** [comment]
I agree with this note.
The current article looks old.
With all my respect...

**Comment by zachmmeyer** [comment]
Please do make a pull request @ikraamg :)
