### ISSUE TITLE
Dead Link : Dynamic User Interface : Inspiration 

### ISSUE THREAD

**Issue by Le-Xandar** [TheOdinProject/curriculum#15255]
In this page : https://www.theodinproject.com/courses/javascript/lessons/dynamic-user-interface-interactions
> Browse the web for **(some)** inspiration, pick something and try to implement it!

the link under the word **"some"** doesn't work
https://trydevkit.com/blog-post/steal-these-responsive-navigation-menu-ideas/bc8bec8d-ef4e-60bc-456c-525ed6f88db8

possibly removed by the site owner as it doesn't show in Google or the website's search

**Comment by AJMcDee** [comment]
I'll take this!

**Comment by Kshubhranshu** [comment]
Ready to contribute :)

**Comment by I3uckwheat** [comment]
@Kshubhranshu Awesome! thanks!

**Comment by I3uckwheat** [comment]
@AJMcDee SORRY, I didn't see you taking this. I will have to re-assign to you. My fault guys. :(
