### ISSUE TITLE
Ruby on Rails - The asset pipeline

### ISSUE THREAD

**Issue by rafeDraper** [TheOdinProject/curriculum#15599]
The path for the asset pipeline has slightly changed in Rails 6.0.0 and higher. At first I got confused since I couldn't find the folder:  app/assets/javascripts/application.js. since this was replaced in app/assets/packs/application.js
![asset-pipeline](https://user-images.githubusercontent.com/46710285/78227470-95e2ae00-74cd-11ea-8027-f586af2921a5.png)

May I kindly ask if it's possible to make a statement which clarify this? If approved I would love to collaborate and write it. Thanks in advance.

**Comment by I3uckwheat** [comment]
@rafeDraper Currently we're not using rails 6 due to other issues. There needs to be a lot of changes to make rails 6 happen. If you would like to track down some of the issues that we'll run into please attach them to issue #15995
