### ISSUE TITLE
Gitbook URLs need to be updated

### ISSUE THREAD

**Issue by hgducharme** [TheOdinProject/curriculum#15679]
Hey y'all,

I'm the owner of the [Intro to SQL](https://github.com/hgducharme/SQL-Basics) and [Intro to Ruby](https://github.com/hgducharme/Ruby-Programming) gitbooks, and Gitbook migrated their website to a newer URL so I've updated my repositories to reflect that but the links in the curriculum need to be updated as well. I'm not sure where they are located in the curriculum anymore, but I figured I would let y'all know.

The new URLs for the SQL book and the Ruby book are https://app.gitbook.com/@hunter-ducharme/s/sql-basics/ and https://app.gitbook.com/@hunter-ducharme/s/ruby-programming/, respectively. 

This is obviously assuming they still exist in the curriculum, but if not then no biggie. Feel free to discard this.

**Comment by I3uckwheat** [comment]
@hgducharme Hey, thanks for the notice! I'll triage this, but we've not had issues with people hitting 404s, but I'll look into it

**Comment by NikSeth** [comment]
I am going to do this.

**Comment by NikSeth** [comment]
Please, trust me with this task

**Comment by hgducharme** [comment]
If you search the repository for my username (hgducharme), it will bring up all the links with my Gitbook's. That might be helpful in tracking them down

**Comment by NikSeth** [comment]
I am actually looking at the link
and It works

**Comment by NikSeth** [comment]
https://www.theodinproject.com/courses/databases/lessons/databases-and-sql

Additional Resources

**Comment by I3uckwheat** [comment]
@NikSeth While it may work, we should change the links to use the correct, new link so it doesn't go offline unexpectedly

**Comment by hgducharme** [comment]
Yeah the old gitbook URLs still currently work, but they won't soon. Gitbook is shutting down their legacy site after April 30th. Here is the exact email I got from Gitbook:

> We are reaching out to you because after the 30th of April, one year after being deprecated, our legacy version of GitBook, legacy.gitbook.com, will be shutdown.
> The brand new app.gitbook.com, now live for more than two years, offers a much better experience for both your readers and your team.
> You can learn more about the complete list of differences in our official documentation.
> 
> Since you first signed up to GitBook on October 5th 2014, you have created or contributed to content on legacy.gitbook.com.
> Until the 30th of April, you can easily migrate your content in one click to the new version using the banner on your profile at https://legacy.gitbook.com/@hgducharme.
> 
> After the 30th of April, your public content will be archieved and remain accessible using its public URL, but will no longer be accessible on legacy.gitbook.com.
> We invite you to read our blog article to learn more about what's new and what remains the same on the new version of GitBook.
> 
> If you are having any trouble migrating your content, we encourage you to reach out to our support team by responding to this email directly, attaching your legacy username hgducharme.
> Hoping to see you soon on app.gitbook.com, we wish you all the best.
> 
> Best regards,
> The GitBook team

**Comment by I3uckwheat** [comment]
@hgducharme We really appreciate you bringing this up to us :)

**Comment by NikSeth** [comment]
I am on it

**Comment by hgducharme** [comment]
@I3uckwheat Absoutely!
