### ISSUE TITLE
issues with google-homepage project.

### ISSUE THREAD

**Issue by ciphermode00** [TheOdinProject/curriculum#15743]
Having issues trying to finish up this project and would appreciate any input to correct any mistakes I made. Can't get the aesthetics/style to look correct.

Here's a link: https://ciphermode00.github.io/google-homepage/#

**Comment by jordanliu** [comment]
Looked at your repo, you need more styling. Look at the assignment's page to see resources on how to get started with CSS, [click to the page](https://www.theodinproject.com/courses/web-development-101/lessons/html-css).

For a more questions or help, checkout the Discord: https://discord.gg/V75WSQG

**Comment by I3uckwheat** [comment]
Closed as this is not an issue with the TOP curriculum. 

@ciphermode00 You can get help in either the TOP forum, or the discord chat room. You can find these in the "community" tab on the website.

![image](https://user-images.githubusercontent.com/4411701/79414576-d6c3d380-7f5f-11ea-8ac4-433c16fe0c7f.png)
