### ISSUE TITLE
Investigate need and feasibility of raspberry pi installation directions

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16030]
Now that we have moved the Ruby section out of 101, we could have a much easier time allowing people to use Raspberry Pis to do the curriculum. There has also been a PR (untested by me) that gives Rails installation directions. https://github.com/TheOdinProject/curriculum/pull/13885

* This could really help with accessibility to the curriculum
* It is already Debian based

We need to do some testing and seeing how well the rpi can work with our curriculum. If anybody wants to do some testing and report back, that would be great.

**Comment by I3uckwheat** [comment]
Closing as this is something we can't support long term.

**Comment by hamzah-mujawar** [comment]
Hi, 

I've recently opened a [discussion](https://github.com/TheOdinProject/curriculum/discussions/29203). On a similar issue, and would like your input on it.
