### ISSUE TITLE
replace link to Ruby Basics markdown page once new Ruby Basics lessons are published

### ISSUE THREAD

**Issue by Tenacious-Qi** [TheOdinProject/curriculum#16035]
As a temporary fix, a broken link in the [Ruby Building Blocks](https://www.theodinproject.com/courses/ruby-programming/lessons/ruby-building-blocks#introduction) lesson page pointing to _Ruby Basics_ was [replaced with a link to the _Ruby Basics_ markdown page on Github.](https://github.com/TheOdinProject/curriculum/pull/16034). 

Once the new _Ruby Basics_ lessons are published, this link should yet again be replaced with one pointing to an Odin Project url.

**Comment by I3uckwheat** [comment]
When #15983 is merged, this ticket will no longer be blocked.

**Comment by KevinMulhern** [comment]
Hey @I3uckwheat, I think I misunderstood this one when it was created. This will no longer required as neither of these lessons are in the curriculum anymore. Sorry for the confusion.
