### ISSUE TITLE
As a student, I want all gitbook links to use the new URL so they don't 404 after deprication

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16055]
More info: https://github.com/TheOdinProject/curriculum/issues/15679

We need to make sure all gitbook links are updated so that we don't run into issues with dead links. Fixing this now, means that we won't miss any, and potentially replace a great resource that is still active and maintained. 

We should fix this while it's fresh on our minds.

**Comment by ARodrigues92** [comment]
I looked at the whole curriculum and only found 3 links that seem to have already been updated.

**Comment by I3uckwheat** [comment]
@ARodrigues92 Thanks! Closing this issue :)
