### ISSUE TITLE
Find all lessons that do not have learning outcomes.

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16074]
#10254 

It would be super helpful to go through and get a list together of what lessons have learning outcomes, and which don't. If you respond with a list here, I can edit the other ticket with the checklist.

**Comment by kashura** [comment]
I'll start working on this one.

**Comment by I3uckwheat** [comment]
@kashura Awesome, thank you!

**Comment by kashura** [comment]
**Web Development 101**

Git basics


Intro to Git - [ ]

Git basics - [ x ]

Practicing git basics - []





The front end

Introduction - [x]

HTML and CSS basics - [x]

Developer Tools - [x]

Project: HTML/CSS - []



JS Basics

Fundamentals 1 - [x] (but no table of contents)

Fundamentals 2 - [x]

Dev Tools 2 - []

Fundamentals 3 - []

Project: rock paper scissors - []

Clean code - []

Fundamentals 4 - []

DOM manipulation - [x]

project: etch a sketch - []

Fundamentals 5 - no

Project calculator - no



The Back End

Intro to the back end - [x]

Intro to frameworks - [x]





Pair Programming

Intro to pair programming - [x]

Preparing to remote pair - [ ]

Project: pairing project - []

**Comment by kashura** [comment]
- [ x ]

**Comment by kashura** [comment]
## **Web Development 101**

*Git basics*

Intro to Git - []

Git basics - [x]

Practicing git basics - []





**The front end**

Introduction - [x]

HTML and CSS basics - [x]

Developer Tools - [x]

Project: HTML/CSS - []



**JS Basics**

Fundamentals 1 - [x] (but no table of contents)

Fundamentals 2 - [x]

Dev Tools 2 - []

Fundamentals 3 - []

Project: rock paper scissors - []

Clean code - []

Fundamentals 4 - []

DOM manipulation - [x]

project: etch a sketch - []

Fundamentals 5 - []

Project calculator - []



**The Back End**

Intro to the back end - [x]

Intro to frameworks - [x]





**Pair Programming**

Intro to pair programming - [x]

Preparing to remote pair - []

Project: pairing project - []

**Comment by I3uckwheat** [comment]
- [ x ]  test

**Comment by I3uckwheat** [comment]
- [ ] test

**Comment by kashura** [comment]
Hi Briggs 

- [ ]

**Comment by I3uckwheat** [comment]
Great! Thank you @kashura I'll move these to the other issue later today

**Comment by kashura** [comment]
## NodeJS



**Express**

- [x] Introduction to Express

- [x] Express 101

- [x] Express 102

- [x] Express 103

- [x] Express 104

- [x] Express 105



**Authentication**

- [x] Authentication Basics

- [ ] Security Configuration



**APIs**

- [ ] API Basics

- [ ] API Security



**Testing Express**

- [ ] Testing routes and controllers

- [ ] Testing database operations

**Comment by I3uckwheat** [comment]
As per our discord conversation: I've adjusted the scope of this ticket. Thanks for taking on a bit more 🔥

**Comment by kashura** [comment]
# Web Development 101

**Git Basics**

- [ ] Intro to Git
- [ ] Git Basics
- [ ] Practicing Git Basics

**The Front End**

- [ ] Introductions
- [ ] HTML and CSS basics
- [ ] Developer Tools
- [ ] Project: HTML / CSS

**Comment by kashura** [comment]
#Ruby Programming

**Introduction**
- [ ] How This Course Will Work
- [ ] Installing Ruby

**Basic Ruby**
- [ ] Basic Data Types
- [ ] Variables
- [ ] Input and Output
- [ ] Conditional Logic
- [ ] Loops
- [ ] Arrays
- [ ] Hashes
- [ ] Basic Enumerable Methods
- [ ] Methods
- [ ] Debugging
- [ ] Problem Solving

**Basic Ruby Projects**
- [ ] Project: Caesar Cipher
- [ ] Project: Sub Strings
- [ ] Project: Stock Picker
- [ ] Project: Bubble Sort

**Intermediate Ruby**
- [ ] Object Oriented Programming
- [ ] Project: OOP
- [ ] Files and Serialization
- [ ] Project: Event Manager
- [ ] Project: File I/O and Serialization

**A Bit of Computer Science**

**Comment by kashura** [comment]
# Databases

- [ ] Databases
- [ ] Databases and SQL
- [ ] Project: SQL

**Comment by kashura** [comment]
# Ruby on Rails

**Introduction**
- [ ] How This Course Will Work
- [ ] Preparing for Deployment
- [ ] Project: Installing Rails

**Rails Basics**
- [ ] A Railsy Web Refresher
- [ ] Routing
- [ ] Controllers
- [ ] Views
- [ ] The Asset Pipeline
- [ ] Deployment
- [ ] Project: Blog App

**Active Record Basics**
- [ ] Active Record Basics
- [ ] Project: Building With Active Record

**Forms and Authentication**
- [ ] Forms Basics
- [ ] Project: Forms
- [ ] Sessions, Cookies, and Authentication
- [ ] Project: Authentication

**Advanced Forms and Active Record**
- [ ] Active Record Queries
- [ ] Active Record Associations
- [ ] Project: Associations
- [ ] Active Record Callbacks
- [ ] Advanced Forms
- [ ] Project: Building Advanced Forms

**APIs, Mailers and Advanced Topics**
- [ ] APIs and Building Your Own
- [ ] Working With External APIs
- [ ] Project: APIs
- [ ] Mailers
- [ ] Project: Sending Confirmation Emails
- [ ] Advanced Topics
- [ ] Project: Final Project
- [ ] Conclusion

**Comment by kashura** [comment]
# HTML and CSS


**Basic HTML Page Structure**

- [ ] How This Course Will Work
- [ ] HTML Basics
- [ ] Linking Internal and External Pages
- [ ] Working with Images, Video, and Other Media
- [ ] Project: Embedding Images and Video
- [ ] What's New in HTML5

**Displaying and Inputting Data**
- [ ] Tables in HTML
- [ ] Ordered and Unordered Lists
- [ ] Forms for Collecting Data
- [ ] Project: HTML Forms

**CSS**
- [ ] CSS Basics
- [ ] The Box Model
- [ ] Floats and Positioning
- [ ] Flexbox
- [ ] Flexbox
- [ ] Grid
- [ ] Project: Positioning and Floating Elements
- [ ] Best Practices
- [ ] Backgrounds and Gradients
- [ ] Project: Building with Backgrounds and Gradients

**Design and UX**
- [ ] Introduction to Design and UX
- [ ] Fonts and Typography
- [ ] Project: Design Teardown


**Responsive Design and CSS Frameworks**
- [ ] Responsive Design
- [ ] Project: Building with Responsive Design
- [ ] CSS Frameworks like Bootstrap and Foundation
- [ ] Project: Using Bootstrap

**Advanced CSS**
- [ ] Animations, Subtle Effects and Compatibility
- [ ] Using CSS Preprocessors to Save TIme
- [ ] Project: Design Your Own Grid-Based Framework
- [ ] Conclusion

**Comment by kashura** [comment]
# Javascript

**Introduction**

- [ ] How this course will work
- [ ] A quick review

**Organizing your JavaScript Code**

- [ ] Introduction
- [ ] Objects and Objects Constructors
- [ ] Project: Library
- [ ] Factory Functions and the Module Pattern
- [ ] Project: Tic Tac Toe
- [ ] Classes
- [ ] ES6 Modules
- [ ] Project: Restaurant Page
- [ ] OOP Principles
- [ ] Project: Todo List

**JavaScript in the Real World**

- [ ] Linting
- [ ] Dynamic User Interface Interactions
- [ ] Forms
- [ ] Webpack 2
- [ ]  ES?

**Front End Frameworks**
- [ ] Introduction to Frameworks
- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Project: Frameworks

**Asynchronous JavaScript and APIs**
- [ ] JSON
- [ ] Async
- [ ] Working with APIs
- [ ] Async and Await
- [ ] Project: Weather App

**Testing JavaScript**
- [ ] Testing Basics
- [ ] Project: Testing Practice
- [ ] More Testing
- [ ] Project: Battleship

**JavaScript and Rails**
- [ ] Using Ruby on Rails For Your Back End
- [ ] Project: Where's Waldo (A photo tagging App)

**Finishing Up with JavaScript**
- [ ] Project: Final Project
- [ ] Conclusion

**Comment by kashura** [comment]
# Getting Hired

**Preparing for Your Job Search**
- [ ] How This Course Will Work
- [ ] Strategy
- [ ] It Starts with YOU
- [ ] What Companies Want
- [ ] What You Can Do To Prepare
- [ ] Project: Building Your Personal Website

**Applying to and Interviewing for Jobs**
- [ ] Collecting Job Leads
- [ ] Qualifying Job Leads
- [ ] Project: Building Your Resume
- [ ] Applying for Web Development Jobs
- [ ] Preparing to Interview and Interviewing
- [ ] Handling a Job Offer
- [ ] Alternate Paths to a Web Development Job
- [ ] Conclusion

**Comment by kashura** [comment]
@I3uckwheat can you glance over that I didn't miss any lessons?

**Comment by kashura** [comment]
@I3uckwheat <3

**Comment by I3uckwheat** [comment]
@kashura Looks great! Thank you man! That's great work!

**Comment by nyd3lig** [comment]
So I decided to build upon this, and list the lessons that has learning outcomes and knowledge checks, and the ones that dont.
I'm pretty new to this whole contribution thing so the format might be super messy, Added some comments etc on sections.

I listed learning outcomes at the top
and knowledge checks at the bottom

x means it doesn't have it.

Some I have written if they don't have it, this only occurs if it has one but not the other.



**Webdev 101**

THE BASICS
1 How This Course Will Work
x
x
___
2 Introduction to Web Development
x
x
___
3 Gearing Up
x
x
___
4 Join the Odin Community
x
x
___
5 How Does The Web Work
Has learning outcomes and knowledge check
(But the answers to the knowledge check is inside the learning outcomes at the start of the lesson,
no knowledge check at the end)
___


INSTALLATIONS
1 Installation Overview
x
x
___
2 Prerequisites
x
x
___
3 Text Editors
x
x
___
4 Command Line Basics
Has learning outcomes and knowledge check 
___
5 Setting Up Git
x
x
___


GIT BASICS
1 Introduction To Git
Has Learning Outcomes and Knowledge check
___
2 Git Basics
Has Learning Outcomes and Knowledge check
___
3 Project: Practice Git Basics
Has Learning Outcomes 
but no Knowledge check
(maybe knowledge check is a bit tedious on this one)
_____________
THE FRONT END
1 Introduction To The Front End
Has Learning Outcomes 
but no Knowledge check
(Here I feel like it would be very beneficial as the questions are pretty open ended)
___
2 HTML and CSS Basics
Has Learning Outcomes
but no knowledge check
___
3 Developer Tools
Has Learning Outcomes
but no knowledge check
(Doesn't need knowledge check, as there isn't really any knowledge to check :^)
___
4 Project: HTML/CSS
x
x
_____________
JAVASCRIPT BASICS
1 Fundamentals PART 1
Has Learning Outcomes
but no knowledge check
___
2 Fundamentals PART 2
Has Learning Outcomes 
but no knowledge check
___
3 Developer Tools 2
x
x
___
4 Fundamentals PART 3
x
x
___
5 Problem Solving
Has Learning Outcomes
And a knowledge check 
(But this knowledge check doesn't have clickable answers like the others to see the answer)
___
6 Project: Rock Paper Scissors
x
x
___
7 Clean Code
x
x
___
8 Fundamentals PART 4
x
x
___
9 DOM Manipulation
Has learning outcomes and knowledge check
(But the answers to the knowledge check is inside the learning outcomes at the start of the lesson,
no knowledge check at the end)
___
10 Project: Etch a Sketch
x
x
___
11 Fundamentals PART 5
x
x

12 Project: Calculator
x
x
___

THE BACK END
1 Introduction To The Back End
Has Learning Outcomes
No knowledge check
___
2 Introduction To The Frameworks
Has Learning Outcomes
No knowledge check
___

**Comment by alexeiMikhail** [comment]
Hey there! Looks like this hasn't been updated in a while. I'd like to help with this task. 

I'm new, and the contributing documentation mentioned needing to be assigned to a task, so I'll wait for a response before I get started.

**Comment by ZachBaird** [comment]
I'm going to start grooming out tasks based on the great work @kashura and @hiimdines have done in regards to the learning outcomes and knowledge checks. I'm going to create a task **per course** to add knowledge checks and/or learning outcomes to missing lessons within that task's course.

Additionally, there's some additional ideas that have been introduced for the *knowledge checks* specifically that I think could be snuck in during this work. I'll go into more detail in the tasks I'm going to groom out, but the concept will be:

- read through the lesson to create knowledge checks
- when a knowledge check is created, provide a link **back** to the lesson content where that's taught
- how this would be achieved will be listed in the lesson

**Comment by ZachBaird** [comment]
The new tasks are listed above! I will be closing this one so work can start being committed to the individual courses over time.
