### ISSUE TITLE
Refresh and re-merge new vbox installation directions

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16070]
https://github.com/TheOdinProject/curriculum/pull/15273"

- [ ] Use correct version of Lubuntu from correct website
- [ ] Redo Guest Additions Instructions
- [ ] Update All Pictures to be correct for each section (might add more checkboxes)

**Comment by I3uckwheat** [comment]
@zachmmeyer got this :)

**Comment by zachmmeyer** [comment]
@I3uckwheat commenting because you told me to

**Comment by I3uckwheat** [comment]
@zachmmeyer Thanks, this is the only way I can assign it to you :)

**Comment by zachmmeyer** [comment]
[ ] Use correct version of Lubuntu from correct website
[ ] Redo Guest Additions Instructions
[ ] Update All Pictures to be correct for each section (might add more checkboxes)

**Comment by I3uckwheat** [comment]
I think we can close this issue, let me know if this is an incorrect assumption @zachmmeyer

**Comment by zachmmeyer** [comment]
That's correct @I3uckwheat I thought this was already closed! Definitely got this done and then we kept it as Xubuntu. I think Lubuntu had some setback with doing the guest additions and we ended up deciding that Xubuntu was easier in that regard.
