### ISSUE TITLE
Breakout git course

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16077]
After some poking around, we saw that the following Git section with pretty good content exists here in the Ruby Programming course: https://www.theodinproject.com/courses/ruby-programming?ref=lnav#git

However, no parallel section is in the JavaScript or NodeJS courses. We might want to create a section like HTML & CSS that's cross-track with the Git content.

For now, I'll modify the main readme to have clearer verbage and add some PR guidelines to contributing.md.

_Originally posted by @ZachBaird in https://github.com/TheOdinProject/curriculum/issues/14554#issuecomment-615521592_

**Comment by KevinMulhern** [comment]
Hey @I3uckwheat, will we use this PR: https://github.com/TheOdinProject/curriculum/issues/5379 for this instead?

**Comment by I3uckwheat** [comment]
@KevinMulhern Yeah, that sounds great, closing this one as a duplicate
