### ISSUE TITLE
Broken link due to redirection to subdomain // internetingishard.com

### ISSUE THREAD

**Issue by themetar** [TheOdinProject/curriculum#16139]
https://internetingishard.com/anypath redirects to https://www.internetingishard.com

In HTML and CSS > Flexbox, [https://internetingishard.com/html-and-css/flexbox/](https://internetingishard.com/html-and-css/flexbox/) redirects to [https://www.internetingishard.com/](https://www.internetingishard.com/).

**Comment by KevinMulhern** [comment]
Thanks for reporting @thebearmayor 

Link to lesson in question: https://www.theodinproject.com/courses/html5-and-css3/lessons/flexbox

It's the third assignment.

**Comment by ARodrigues92** [comment]
@KevinMulhern I just created a PR with a fix on the link.
