### ISSUE TITLE
Strange link behavior in Input Output section of Ruby Basics

### ISSUE THREAD

**Issue by Tenacious-Qi** [TheOdinProject/curriculum#16203]
![image](https://user-images.githubusercontent.com/53409795/79821754-8b456700-835d-11ea-9a68-8a08d1bf9de8.png)
The second link of assignment 1 "www.learnrubyonline.org" leads to an empty page here: https://www.theodinproject.com/courses/ruby-programming/lessons/www.learnrubyonline.org

I would have just done a PR but the link in the markdown file looks and works fine so I'm not sure what's causing the issue. 

edit: here is link to page: [Input and Output](https://www.theodinproject.com/courses/ruby-programming/lessons/input-and-output)

**Comment by leosoaivan** [comment]
Fixed by https://github.com/TheOdinProject/curriculum/pull/16176/files
