### ISSUE TITLE
Full Stack JS no longer has the user set up Heroku

### ISSUE THREAD

**Issue by scottBowles** [TheOdinProject/curriculum#16292]
As far as I can see, learners on the Full Stack JS track currently don't have Heroku set up during initial installations, then are later told to enter commands to push to Heroku.

On the [web-dev-101 installation overview page](https://www.theodinproject.com/courses/web-development-101/lessons/installation-overview?ref=lnav), it mentions these future steps: 
-creating an SSH key (a personal “password” that will identify you to GitHub, Heroku, and many other sites you’ll be using); and
-creating and deploying a very basic Ruby on Rails application to make sure it all works.

A [few lessons later](https://www.theodinproject.com/courses/web-development-101/lessons/setting-up-git?ref=lnav) it tells us:
"If you are doing the front-end of Node courses then you have everything you need. If you’re doing Ruby and Rails we’ll install those tools when you get to those courses." Unless I'm missing it, the Heroku bit has also been omitted. I think it was formerly set up alongside SSH/Git [here](https://www.theodinproject.com/courses/web-development-101/lessons/setting-up-git) (and perhaps could be returned to the same?).

Then, in the Node section in the [mini messageboard project](https://www.theodinproject.com/courses/nodejs/lessons/mini-message-board), the learner is told to enter commands to push to Heroku.

**Comment by I3uckwheat** [comment]
Thanks for noticing and writing a good issue up!

Currently the Heroku installations are done in the Ruby section [here](https://www.theodinproject.com/courses/ruby-on-rails/lessons/your-first-rails-application-ruby-on-rails#step-3-deploy-your-rails-application)

Here's what needs to happen:

- [ ] break out heroku setup directions from the Rails install
- [ ] edit the rails install to make sense with the broken out directions
- [ ] modify the seeds to put the installations in both the Node and Ruby course in the appropriate place
- [ ] make sure that the surrounding lessons make sense with the moved heroku installations.

**Comment by marvingay** [comment]
I can handle this.

**Comment by briantuju** [comment]
Hello @I3uckwheat 
I'm not very experienced in how issues work, but I have a suggestion.

Since I learnt web development using this project and I have been using Heroku for quite some time now, **can I do a quick detailed explanation on how to integrate NodeJs with Heroku**, and then submit for reviewing or integration with the curriculum?

**Comment by I3uckwheat** [comment]
@briantuju I suggest you make an issue on [this repository](https://github.com/TheOdinProject/discussions) after you read the [PROCESS.md page](https://github.com/TheOdinProject/discussions/blob/master/PROCESS.md)

**Comment by briantuju** [comment]
I have gone through the Process page.

I will think of how to present my idea to the panel.

Thank you @I3uckwheat

**Comment by marvingay** [comment]
Curriculum changes: #16412
Seed changes: #1131

**Comment by marvingay** [comment]
The appropriate changes have been merged.
Closing.
