### ISSUE TITLE
Broken link under views section of Rails

### ISSUE THREAD

**Issue by jithindasad** [TheOdinProject/curriculum#16359]
https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-ruby-building-blocks redirects to 404 page

**Comment by KevinMulhern** [comment]
Thanks for reporting.

The page its linking to has been removed so the link can be removed, It's on this page: https://www.theodinproject.com/courses/ruby-on-rails/lessons/views

In the paragraph above the Preprocessors heading.

**Comment by I3uckwheat** [comment]
@Saranoya got this
