### ISSUE TITLE
Small redundancy in Web 101 - DOM manuipulation additional resources

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/curriculum#16353]
[DOM manipulation additional resources](https://www.theodinproject.com/courses/web-development-101/lessons/dom-manipulation#additional-resources) contains two separate links to the same page, [Plain Javascript.](https://plainjs.com/javascript/) 

It would make sense to consolidate them into a single dot point, unless there's a good reason not to.

![dom manuip](https://user-images.githubusercontent.com/58506115/80268866-49fedf80-86ee-11ea-9464-4c711ef39a86.png)

**Comment by aaron-contreras** [comment]
I'll take it!

**Comment by devmohy** [comment]
I will like to work on this

**Comment by AJMcDee** [comment]
Dayummm you guys are too fast for me!
