### ISSUE TITLE
Markdown for Introduction Header not displaying correctly in Google Clone Project (Web Dev 101)

### ISSUE THREAD

**Issue by minimalsm** [TheOdinProject/curriculum#16404]
https://www.theodinproject.com/courses/web-development-101/lessons/html-css

<img width="847" alt="Screenshot 2020-04-26 at 22 22 13" src="https://user-images.githubusercontent.com/62268199/80320206-f0d99d80-880c-11ea-993e-bbce5c07dd13.png">

**Comment by boyuan12** [comment]
Can I work on this issue?

**Comment by aaron-contreras** [comment]
I'll take it

**Comment by I3uckwheat** [comment]
@aaron-contreras Awesome, i'll assign this to you.

**Comment by marvingay** [comment]
Issue resolved in #16406 

Closing.
