### ISSUE TITLE
JavascriptIsSexy links are 'broken'

### ISSUE THREAD

**Issue by wgoolsby** [TheOdinProject/curriculum#16525]
In the lesson [Object Constructors](https://github.com/TheOdinProject/curriculum/blob/master/javascript/organizing-js/objects-constructors.md), the [Javascript Is Sexy article](http://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/) is broken. It may be temporary, but it is currently redirecting to an error page with the following error: 
> Error establishing a database connection

**Comment by marvingay** [comment]
Thank you for reporting this issue. 

This error was reported once before less than 24 hours from this issue being created. For the time being, I believe it is advisable to use an archived/wayback machine/cache'd version of this article to access it.

A little more time should be given to see if the issue with this site will be seemingly temporarily or a permanent fixture before removing and/or updating the resources.

This website (with different articles) is in [Object Constructors](https://github.com/TheOdinProject/curriculum/blob/master/javascript/organizing-js/objects-constructors.md) and [Clean Code](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/javascript_basics/clean_code.md) (as an additional resource).

**Comment by marvingay** [comment]
#16511 Clean Code - The resource in the PR will still need to be reviewed, relevant to this issue.

In my opinion, another 24 hours should be given to evaluate if the current resources will need to be changed.

**Comment by marvingay** [comment]
Given that the information in the currently provided resources compliments the surrounding material, it's most practical to continue using these resources despite the active site being down.

The person who takes this on should:
- [ ] Identify the links to the resources
- [ ] Use the wayback machine to obtain the appropriate snapshot of the resource from the past
- [ ] Replace the links in the curriculum files in the appropriate place.

**Comment by violetguos** [comment]
Hi, I'm interested in contributing. Thamks.

**Comment by marvingay** [comment]
@violetguos Perfect. If there are any issues, feel free to mention me here or stop by our discord community.
