### ISSUE TITLE
Missing "learning outcomes" in Javascript module

### ISSUE THREAD

**Issue by Johongirr** [TheOdinProject/curriculum#16540]
Guys I could not find learning outcomes part in vanilla javascript module. I saw it only  in ajax and async lessons. best regards 

Many lessons on these pages are missing learning outcomes: 
https://www.theodinproject.com/courses/javascript

**Comment by I3uckwheat** [comment]
@Johongirr 

Can you please attach a link to the lesson where you found this issue?

**Comment by marvingay** [comment]
The lessons that require Learning Outcomes are as follows:

- [ ] Objects and Object Constructors
- [ ] Factory Functions and the Module Pattern
- [ ] Classes
- [ ] ES6 Modules
- [ ] OOP Principles

Link relevant PRs to given lesson(s) below.

**Comment by ZachBaird** [comment]
I can take this @I3uckwheat

**Comment by I3uckwheat** [comment]
@ZachBaird Sweet, thanks!

**Comment by ZachBaird** [comment]
@I3uckwheat PR submitted.
