### ISSUE TITLE
Redundant Resource in HTML Conclusion

### ISSUE THREAD

**Issue by minimalsm** [TheOdinProject/curriculum#16601]
In the conclusion for HTML/CSS, within Additional Resources, Codecademy's HTML/CSS course is recommended. This is a very high level beginner resource. I've done the course and it is completely superseded by the material presented prior. **THIS COURSE WOULD HAVE NO VALUE TO ANYONE WHO HAD BEEN THROUGH THE ENTIRE HTML/CSS SECTION.**

https://www.theodinproject.com/courses/html5-and-css3/lessons/conclusion-html5-and-css3

**Comment by ZachBaird** [comment]
@I3uckwheat I can take this.

**Comment by ZachBaird** [comment]
@I3uckwheat PR submitted.
