### ISSUE TITLE
Revert "JavascriptIsSexy" links to original resource

### ISSUE THREAD

**Issue by faishalirwn** [TheOdinProject/curriculum#16755]
I'm referring to [this article](http://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/). I've encountered issue #16525 and it seems it has been fixed, but, as the title said, I found capture with better format. 

[Here is the link](https://web.archive.org/web/20180610163043/http://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/), it was from June 10th 2018.
In the subsequent capture [here](https://web.archive.org/web/20180625141438/http://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/) on June 25th 2018, the design changed and remains till today.

I found the current format to lack syntax highlighting, 'important note' section that are separated from the post hierarchy. (Also imo the older version has better bold text color)
I've checked and found no difference in the post content to the current link, CMIIW.

As of today JavascriptIsSexy website is up. So, is it a good idea to replace the current link with the link above? If not, what about the current running website?

**Comment by marvingay** [comment]
Thank you for submitting this issue. It has been verified that the resource website is operational. In the interest of speed, we will replace the resource with the appropriate links to the original resource.

In contrast to #16525, the person who handles this issue will need to do the following for both lessons:
- [ ] Obtain the appropriate 'JavascriptIsSexy' link to the appropriate article (https)
- [ ] Modify the markdown in [Object Constructors](https://github.com/TheOdinProject/curriculum/blob/master/javascript/organizing-js/objects-constructors.md) and [Clean Code](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/javascript_basics/clean_code.md) (as an additional resource)

If there are any questions, please comment on this thread.

Please link the appropriate pull request(s) below.

**Comment by UnevenCoder** [comment]
Hi how to get the issue

**Comment by btdmaster** [comment]
Hi, can I take this?

**Comment by marvingay** [comment]
@UnevenCoder Hello,

This issue is for newer contributors that are engaging in The Odin Project curriculum. You can find out more information via our Discord community.

Thank you for reaching out.

**Comment by marvingay** [comment]
@btdmaster Yes, you can! I will assign it to you.

You're welcome to refer to our [Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/contributing.md), comment here, or ask in our Discord community if you have any questions!

**Comment by btdmaster** [comment]
After finding out how to do multiple commits in one PR, I finally did it! Here's the [PR](https://github.com/TheOdinProject/curriculum/pull/16779).

**Comment by marvingay** [comment]
@btdmaster  Thank you so much for your contribution!
