### ISSUE TITLE
Code snippets not properly formatted in NodeJS mini message board project

### ISSUE THREAD

**Issue by kikupiku** [TheOdinProject/curriculum#16776]
You can see from the markdown page of the [mini message board](https://www.theodinproject.com/courses/nodejs/lessons/mini-message-board?ref=lnav) lesson that certain things are supposed to be in bash code format (or javascript, etc.) but only the html snippets render properly. Strangely, they do show up correctly in the github preview.

**Comment by ZachBaird** [comment]
@I3uckwheat I can take this.

**Comment by I3uckwheat** [comment]
@ZachBaird Sweet, assigning it to you.

**Comment by ZachBaird** [comment]
@I3uckwheat PR submitted.

**Comment by kikupiku** [comment]
Thanks! The two last snippets still have the word bash that shouldn't be there, though, and the last snippet shows up as one long command instead in two lines.

**Comment by ZachBaird** [comment]
Numbered list was still resetting and `bash` was getting printed out and was misformatted regardless. Thanks @kikupiku for checking this!

New PR submitted @I3uckwheat
