### ISSUE TITLE
Ethical remote pairing software suggestions

### ISSUE THREAD

**Issue by remiborfigat** [TheOdinProject/curriculum#16814]
Going through the [Preparing for Remote Pair](https://www.theodinproject.com/courses/web-development-101/lessons/preparing-to-remote-pair) page, I was shocked to see that only ‘big tech’ and closed-source solutions were offered.

Since TOP is an open-source initiative, that would be nice to suggest free/libre and open-source software (FLOSS) that do not snoop on and track their users.
From a broader view, educating future Web developers about the ethics of technology is crucial if we want to prevent the Web from becoming even more centralised and closed as it is nowadays.

So, here is a humble list I suggest to add (all are FLOSS and cross-platform):

- [Jami](https://jami.net/), a distributed, privacy and user-friendly Skype alternative.
- [Jitsi Meet](https://jitsi.org/jitsi-meet/), a secured video-conference Web service that is easily accessible in the Web browser. Doesn’t require any installation. Chat, screen sharing and document pair editing included.
- [Mumble](https://www.mumble.info/), an audio-only, private and secured chat software.

**Comment by I3uckwheat** [comment]
@remiborfigat This section is going to be removed, people finding pairs has proven to be more trouble than it's wroth.
