### ISSUE TITLE
Remove pair-programming from wd101

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16816]
More info here: https://github.com/TheOdinProject/discussions/blob/master/proposals/remove-pair-programming.md

We need to remove the pairing in its entirety from wd101. This means:

- [ ] Remove lessons from the repository (it will live on in the git history)
- [ ] Remove lessons from the seeds file

**Comment by codyloyd** [comment]
I don't think we need to remove the lessons from the repository.. I'd rather keep them for now, even if they are still alive in the History.  There will be some people that are right in the middle of those lessons who will want an easier-to-access file, and we may still want to recycle the Pomodoro project some time.

**Comment by KevinMulhern** [comment]
I've been moving old lessons into an archive folder, might be an idea for this one.

**Comment by codyloyd** [comment]
perfect ^^

**Comment by zachmmeyer** [comment]
Proposal:

The Pomodoro Project is the final project in Web Dev 101. That is more or less a fact and is also the solution. Move the Pomodoro Project to "Tying it All Together" as a final project and move the pair programming section to "Getting Hired" to read about, obviously removing the mention of a project.

**Comment by I3uckwheat** [comment]
@zachmmeyer no  we need to just move it to archive and then remove mentions of it.

We can reconsider later, but it would help get students moving along. You can see the proposal has been approved.

**Comment by ZachBaird** [comment]
@I3uckwheat @KevinMulhern @codyloyd 
I can start working on this if no one has taken it yet.

**Comment by KevinMulhern** [comment]
Its all yours @ZachBaird 😃
