### ISSUE TITLE
FAQ buttons do not respond to user input

### ISSUE THREAD

**Issue by btdmaster** [TheOdinProject/curriculum#16825]
_This is my first issue, please tell me if I'm doing something blatantly wrong._

The buttons to open and close the `#faq-item`s do not work on the [TOP FAQ](https://www.theodinproject.com/faq) page. Clicking them does nothing.

However, manually editing the `class` from `collapse` to `open`  in the Inspector does work as normal.

I have tried this on both Firefox on Windows and Linux, and on Chrome on Windows, all on the latest version, and this issue is consistent across platforms.

**Comment by marvingay** [comment]
Hello,

You didn't do anything explicitly wrong. However, this repository is for the `curriculum` **only**. This issue would be more relevant in `theodinproject` repository. There is already an open issue concerning this problem: https://github.com/TheOdinProject/theodinproject/issues/1154
You can refer to that issue for further comment.

Thank you for reaching out.
