### ISSUE TITLE
Remove unmaintained WSL installation directions from wd101 installations

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16903]
https://github.com/TheOdinProject/curriculum/edit/master/web_development_101/installations/prerequisites.md
https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites

We should remove the un supported and unmaintained directions for WSL here.

**Comment by Saranoya** [comment]
Give it to me! ;).

**Comment by ZachBaird** [comment]
@Saranoya Assigned :)
