### ISSUE TITLE
"Until" loop typo

### ISSUE THREAD

**Issue by aaron-contreras** [TheOdinProject/curriculum#16943]
![Screen Shot 2020-05-10 at 4 39 17 PM](https://user-images.githubusercontent.com/61627014/81511166-e3c4b000-92dc-11ea-839d-4ac0c14f4fba.png)

On [the "until" loop section](https://www.theodinproject.com/courses/ruby-programming/lessons/loops?ref=lnav#until-loop) there's a typo below the code snippet that should be "until the condition i > 10 is **true**"

**Comment by marvingay** [comment]
The fix was previously merged. Issue was moved to 'Done'.

Closing.

**Comment by aaron-contreras** [comment]
@marvingay Someone else had made a PR for it?
