### ISSUE TITLE
GitHub Issue Templates

### ISSUE THREAD

**Issue by martink-rsa** [TheOdinProject/curriculum#17304]
#### Description
There are no Issue templates which would make the process far more efficient in regards to: 
1. Letting newcomers know what kind of information is needed;
2. Maintaining a standardization of issues being created;
3. Keep issues limited to the correct type of information e.g. Bugs, Feature request;
4. Knowing exactly which pages need to be addressed by having the template field request the URL of the lesson.

There currently is a template being used when it comes to student submissions.

#### To Fix
There are quite a few guides on the internet that illustrate the steps needed to create good Issue templates. One such video would be this: https://www.youtube.com/watch?v=UPsCXqxxJUA

Templates could include: Website Issues, Feature Request

**Comment by KevinMulhern** [comment]
Totally agree with this, more templates would help a ton with making issues more actionable.

**Comment by kashura** [comment]
I'd love to help with this. I can make the template and if it suits admins can copy/paste it into the settings.

**Comment by jatin2003** [comment]
Hey! It'l be great as It'll make Issues more useful!

**Comment by ryanford-dev** [comment]
#21810 resolves this. Closing.
