### ISSUE TITLE
Chore: Remove Requirement for Using Blocks on Binary Search Tree Project

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#17458]
Lesson: https://www.theodinproject.com/courses/ruby-programming/lessons/data-structures-and-algorithms

### Description
We removed the old basics lessons which covered blocks, procs and lambdas when we updated the basics section of the ruby course recently. We did not provide any alternative content for learning about blocks as we plan on creating a new lesson that will cover them in the future.

But currently  we instruct students to use blocks on steps 6 and 7 of the Binary Search Tree project in the Ruby course.

This has caused some issues, as students are no longer exposed to blocks at any point prior to that project.

### Acceptance Criteria
Reword the instructions so we aren't suggesting that blocks should be used in the implementation.

**Comment by rlmoser99** [comment]
I think I can make this change... it seems simple enough. 

While you guys are looking at this lesson, on 5/21 a student had a question about the #define_method. As they were helping out, Fensus & Timato made a few comments such as "It's kinda a silly exercise though, should probably remove it" and "Yeah it's probably not the best use for pushing metaprogramming. And really doesn't show off it's power well." 

In addition, a few students have remarked about wanting a way to "see" the BST as they are working on it... I made my own version, but I keep seeing others share a snippet of code from Fensus that might be helpful to include in this lesson. 

`def pretty_print(node = root, prefix="", is_left = true)
  pretty_print(node.right, "#{prefix}#{is_left ? "│   " : "    "}", false) if node.right
  puts "#{prefix}#{is_left ? "└── " : "┌── "}#{node.data.to_s}"
  pretty_print(node.left, "#{prefix}#{is_left ? "    " : "│   "}", true) if node.left
end`

I just did this lesson about 2 week ago, so I don't have a huge understanding about what is and is not important in this lesson. I'd be happy to do these changes, but would need more feedback on these two additional changes before l proceed. Also, I won't be offended if someone with more experience wants to make them.

**Comment by KevinMulhern** [comment]
I personally think we should remove the bonus define_method step. It doesn't add much to this project and can be discouraging as metaprogramming isn't something the user has been exposed to previously in the course.

I really like Fensus's suggestion. That would be a great addition 👍

**Comment by KevinMulhern** [comment]
Thanks for taking this one on @rlmoser99 💪

**Comment by rlmoser99** [comment]
Update: I am waiting to hear back from Fensus on Discord about the pretty_print method. Since it is his code, I think it is important to get his feedback, before we publish it in this lesson.

**Comment by Kfollen93** [comment]
Any update on this? Fensus hasn't been seen in a while, it might be proactive to have this updated in the meantime. Based on the Discord chat it appears that a lot of us are either currently on this lesson, or about to start (with a few people having completed it already). I don't feel comfortable updating specifics of this lesson myself, as I'm just now starting it. However, if I can help in another way please let me know.

**Comment by marvingay** [comment]
@Kfollen93 We'll follow up on this. As always, don't hesitate to ask in Discord if you need assistance.

**Comment by marvingay** [comment]
#17956 is related.

**Comment by rlmoser99** [comment]
I'll take a look at the other chore and see what I can do & hopefully complete both of them ASAP.
