### ISSUE TITLE
WD101 > CLI Basics - Revise Terminal Directory

### ISSUE THREAD

**Issue by housewifecoder** [TheOdinProject/curriculum#17756]
Can someone pls fix the curriculum? Terminal for Macs use Command + C to Copy into the terminal. I tried it every way possible and when you go into the terminal, "edit" bar in the menu, that is when it tells you to copy. It works then.

Curriculum I am referencing: Assignment #1
> First, you might have already noticed that copying and pasting inside the command line doesn’t work the way that you’d expect. When you’re inside the command line, you’ll need to use Ctrl+Shift+C to copy and Ctrl+Shift+V to paste. For example, to copy and paste commands from your browser into the command line, you’ll highlight the command text and use Ctrl+C as usual and then paste it in your terminal using Ctrl+Shift+V. Test it out!

I'm totally new to programming / GIT (hence why I'm learning via TOP. I don't know yet how to correct the curriculum because I don't know how to really use GIT so apologies if this is not how to address errors or how to raise these kinds of issues. I just want someone to know to help the next person.

**Comment by marvingay** [comment]
#17973
