### ISSUE TITLE
Broken link on Intro to Front End in WebDev 101

### ISSUE THREAD

**Issue by ZachBaird** [TheOdinProject/curriculum#17833]
There is a broken link on the [Intro to Front End](https://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-the-front-end) lesson here in the Assignments. Assignment #1 - reading the interview with Nick Schaden - is broken.

There's a few options to fix this:
1) See if the URL changed and replace it so it no longer 404s.
2) If the interview has been taken down, identify a replacement resource.
3) Remove this part of the lesson's assignments.

**Comment by srinibassamal** [comment]
<a href="https://www.anything you want to put.com">

**Comment by am-firnas** [comment]
I am on it

**Comment by am-firnas** [comment]
Hi, it seems the link is broken even we are accessing from the author's official page. http://www.nickschaden.com/2012/09/10/front-end-web-development-at-general-assembly/

**Comment by pur3asdf** [comment]
there is a snapshot on [](https://web.archive.org/web/20200601022721/https://generalassemb.ly/blog/what-is-front-end-web-development/)

**Comment by marvingay** [comment]
Change made in -> #17911

**Comment by am-firnas** [comment]
alright then
