### ISSUE TITLE
Chore: Update Rails basic forms lessons to use form_with

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/curriculum#17979]
Lesson: https://www.theodinproject.com/courses/ruby-on-rails/lessons/form-basics

**Description**

The current Rails lesson on forms uses the soft-deprecated form_url and form_with helpers rather than the current form_with. The new Rails tutorial will use form_with so this lesson now needs to be updated.

**Comment by krys2fa** [comment]
Hi @CouchofTomato, I would like to give this a try.

**Comment by CouchofTomato** [comment]
@krys2fa All yours mate. The lesson should still touch on form_for and url_for since they will still be seen in the wild but otherwise I'll leave the rest to your creativity.

There isn't a strict deadline but I'm currently writing a new Rails project to follow along with through the Rails curriculum and this ideally needs to be live before then. Possibly 3 - 4 weeks out.

**Comment by krys2fa** [comment]
Hi @CouchofTomato, I have made some few additions and will put in a pull request for a review.
Please let me know how I can improve on this. Thanks.
