### ISSUE TITLE
Broken Link In Javascript Fundamentals Part 1  

### ISSUE THREAD

**Issue by Skywalker1074** [TheOdinProject/curriculum#17994]
Under additional resources. This is the lesson https://www.theodinproject.com/courses/web-development-101/lessons/fundamentals-part-1?ref=lnav

**Comment by bycdiaz** [comment]
It looks like the article was moved to this link:

https://medium.com/hackernoon/why-you-shouldnt-use-var-anymore-f109a58b9b70

**Comment by jordanperkins98** [comment]
Ill do this one
