### ISSUE TITLE
Can't edit the html_css file to submit my solution 

### ISSUE THREAD

**Issue by niyorich** [TheOdinProject/curriculum#18041]
I am trying to submit but when I get to the repo https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/the_front_end/project_html_css.md it says "View raw
(Sorry about that, but we can’t show files that are this big right now.)". 
I am stuck and can't edit the file. Help please.

**Comment by marvingay** [comment]
This issue was resolved by reducing the file size via deletion of solutions.
Closing.
