### ISSUE TITLE
Ruby track - Link spans off the viewport

### ISSUE THREAD

**Issue by aaron-contreras** [TheOdinProject/curriculum#18314]
Intermediate Ruby - [**Project: Event Manager**](https://www.theodinproject.com/courses/ruby-programming/lessons/event-manager) - Iteration 3.

The link to the API spans off the screen, while everything else is nicely centered throughout the lesson and curriculum.

![Screen Shot 2020-06-19 at 7 01 49 AM](https://user-images.githubusercontent.com/61627014/85130858-50e03500-b1fb-11ea-8f17-cb6c4690282c.png)

**Comment by krys2fa** [comment]
Hi @aaron-contreras, 

I would like to work on this.

Regards,
Chris.

**Comment by Northrain-cmd** [comment]
Can I help? It's been a while

**Comment by marvingay** [comment]
Verified that this fix is reflected on the website.
@Northrain-cmd  Thanks again.
