### ISSUE TITLE
Ruby testing should be learned before the BST lesson

### ISSUE THREAD

**Issue by bryanluu** [TheOdinProject/curriculum#18613]
The BST lesson involves building a BST, a fairly complex structure with lots of potential to frustrate newcomers (like me) during the build. The idea of testing is to provide some feedback that the code is being built correct or the functions are working as intended. Thus, testing would be a very useful concept to learn _before_ building the BST and doing DFS for the Knight's challenge. Otherwise, coders have to trust their code to work unless they correctly implement one of the order methods. Also, the `delete` function is not tested in any capacity through the curriculum.

**Comment by rlmoser99** [comment]
Thank you for taking the time to submit this issue. We will be moving the Ruby testing section before the Computer Science section in the future. This move will take place after some revisions in the testing section.
