### ISSUE TITLE
Ubuntu is not a Linux version, it is a Linux distribution

### ISSUE THREAD

**Issue by jmnyarega** [TheOdinProject/curriculum#18725]
> Linux is a free and open-source operating system that works well with all programming languages. Most development tools are written to work natively with Linux. Your tools will likely be updated more often, have more information available for troubleshooting, and just plain run better on Linux. We'll be using Ubuntu, one of the most popular and user-friendly versions available, or the lighter weight alternative Xubuntu. If you don't use a Mac, we recommend that you use Linux. It's that simple.

Extracted from  curriculum/web_development_101/installations/installation_overview.md.

> There are thousands of versions of Linux out there, but Ubuntu is undoubtedly one of the most popular and user friendly. When installing Linux on a VM, we recommend [downloading Xubuntu 18.04](http://mirror.us.leaseweb.net/ubuntu-cdimage/xubuntu/releases/18.04/release/xubuntu-18.04-desktop-amd64.iso "Xubuntu Download Link"). Xubuntu uses the same base software as Ubuntu but has a desktop environment that requires fewer computer resources and is therefore ideal for virtual machines.

Extracted from web_development_101/installations/prerequisites.md

The quoted texts above imply that Ubuntu is a Linux version, it is a Linux distribution.

**Comment by adam-goodrich** [comment]
I got this one!
