### ISSUE TITLE
Link needs correcting

### ISSUE THREAD

**Issue by Lucas-Bide** [TheOdinProject/curriculum#18842]
I'm pretty sure this [lesson's](https://www.theodinproject.com/courses/html-and-css/lessons/css3-basics) | [first assignment](https://learn.shayhowe.com/html-css/building-your-first-web-page/) should actually be [this page](https://learn.shayhowe.com/html-css/getting-to-know-css/). The "Build Your First Website" chapter was already linked to in a previous lesson, and the learning outcomes imply that "Getting to Know CSS" is the correct chapter.

**Comment by marvingay** [comment]
@Lucas-Bide  I believe I previously stated that the link was correct (as it's not actually directly linked beforehand), however upon review it appears we jump through this resource in a non-linear fashion. 

I'll correct this. Thank you for the contribution.

**Comment by Lucas-Bide** [comment]
Glad to help!
