### ISSUE TITLE
Joshua Kemp's Link on Gearing Up doesn't work anymore

### ISSUE THREAD

**Issue by zachmmeyer** [TheOdinProject/curriculum#19019]
https://github.com/TheOdinProject/curriculum/edit/master/web_development_101/the_basics/gearing_up.md
http://joshuakemp.blogspot.co.uk/2013/11/how-blacksmith-learned-to-code-and-9.html

He redirects away from that site. You can still get to it if you stop the page loading.
I am going to bug him on twitter to see if he'll allow access to that blog post or not.

**Comment by marvingay** [comment]
Will allow a week turnover before closing the issue.

**Comment by marvingay** [comment]
@zachmmeyer Did he ever respond to you regarding this issue?

**Comment by zachmmeyer** [comment]
@marvingay no. He's currently MIA from the internet.
