### ISSUE TITLE
Google_Homepage (Easy)

### ISSUE THREAD

**Issue by Myvaleur** [TheOdinProject/curriculum#19213]
`https://myvaleur.github.io/google-homepage/

**Comment by gitdxb** [comment]
@Myvaleur Hi there! I believe you want to submit your solution, you can check this link out to learn how to do it: https://github.com/TheOdinProject/curriculum/blob/master/contributing.md

Good luck!

**Comment by bycdiaz** [comment]
Thanks @gitdxb.

@Myvaleur, if you have questions feel free to ask in our forums or discord server.
