### ISSUE TITLE
OS market share among developers

### ISSUE THREAD

**Issue by D3SL** [TheOdinProject/curriculum#19295]
Even when focusing solely on developers I haven't seen data to support the claim most use macs. Going by the Stackoverflow Developer Survey 45% use windows as their platform, 29% MacOS, and 25% Linux. Objectively that's not a majority, windows has a clear lead with a plurality of 45% and MacOS is nearly tied for second place with Linux.

Outside of the development world MacOS has a single digit marketshare. I think it's objectively inaccurate to say a majority of developers use macs and misleading not to be clear that MacOS globally has a marketshare that's almost negligible.

**Comment by marvingay** [comment]
@D3SL 
Unix-based systems hold the majority, based on the numbers provided.

A large part of Windows marketshare in Software Engineering/Development is a derivative of .NET and the C languages.

Was there a particular lesson you were referring to?

**Comment by D3SL** [comment]
Web Development 101 - Installations - Installation overview. The current lesson text is:

```If you’re using a Mac, you’re in great shape. Most professional developers rely on Macs for their coding. By installing just a few programs, you will be up and running with your education in no time!```

**Comment by bycdiaz** [comment]
Perhaps the statement can be changed to:

Most professional developers rely on Unix-based systems for their coding.

**Comment by marvingay** [comment]
@bycdiaz  I agree with this.

The person who takes ownership of this issue should:
- [ ] Modify the Mac section of the [Web Development 101 - Installations Overview](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/installations/installation_overview.md) lesson to be consistent with the suggestion commented above.

**Comment by aaron-contreras** [comment]
I'll take this

**Comment by lukastan93** [comment]
I'll take care of it

**Comment by marvingay** [comment]
@aaron-contreras  Assigned.

**Comment by marvingay** [comment]
@lukastan93  Thank you for reaching out. Keep eyes on our discord community for other opportunities.

**Comment by jatin2003** [comment]
Whoa! That was fast & I'm looking forward to contributing in the future!
