### ISSUE TITLE
Basic Enumerable Methods lesson references future lesson (RoR track, Ruby Programming course)

### ISSUE THREAD

**Issue by nguyenjessev** [TheOdinProject/curriculum#19544]
In "8. Basic Enumerable Methods" in the RoR track, in the "Bang Methods" section the text says `As you’ll recall from the Methods lesson ...`

The Methods lesson does not come until 2 lessons later.

![image](https://user-images.githubusercontent.com/67484662/88481907-2127f980-cf2c-11ea-83f1-9a3f51d7a384.png)

![image](https://user-images.githubusercontent.com/67484662/88481921-31d86f80-cf2c-11ea-8020-563362dafec5.png)

**Comment by marvingay** [comment]
Thank you for reporting this.

I read through both Methods and Basic Enumerable Methods and just reaffirming that "Methods" should be before the "Basic Enumerable Methods".

Re-arranging the lessons will take place at https://github.com/TheOdinProject/theodinproject/issues/1259

This issue will be used to add expository information to the introduction of the [Basic Enumerable Methods](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/basic_ruby/basic_enumerable_methods.md) lesson to add __recall__ to the Methods lesson.

The person who takes ownership of this issue must:
- [ ] Add an additional sentence (or 2) to the first paragraph to remind the learner of what they were exposed to in the [Methods](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/basic_ruby/methods.md) lesson.

Bonus points for adding a line at the end of the first paragraph that flows into where "Enumerables" are defined in the following paragraph.

**Comment by lukastan93** [comment]
I'll take this one

**Comment by marvingay** [comment]
@lukastan93  Thank you. If you have questions, do not hesitate to ask here or in our Discord community.
