### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AJMcDee** [TheOdinProject/curriculum#19555]
react-introduction.md has a broken link (the 30 Days of React link). 

I have just started something similar which is also free and can recommend it as a replacement, though I've only just begun it it does involve active coding and was recommended to me on the TOP Discord: https://scrimba.com/course/glearnreact/

**Comment by marvingay** [comment]
@AJMcDee  Interested in making a pull request for it?

That entire section will be removed/overhauled/updated soon.

**Comment by AJMcDee** [comment]
Sure! I can do it tomorrow just assign it to me. Whats being overhauled
about that section, out of interest?

**Comment by marvingay** [comment]
@AJMcDee We are only going to cover React. The lessons will be in the same format as the rest of TOP, with a couple of informational lessons followed by a project. The pull request is open, if you're curious to see what's in it. A student has already completed it so I will be revising/editing it accordingly.

**Comment by AJMcDee** [comment]
Nice, I'll definitely take a look! This is "React Week" for me so it's good
timing.
