### ISSUE TITLE
'Javascript: Webpack 2' Core Concepts Lessons at Webpack Academy Questionable Quality

### ISSUE THREAD

**Issue by lhuang61** [TheOdinProject/curriculum#19764]
In the 'Webpack 2' lesson, I find the “Core Concepts lessons at Webpack Academy" very questionable in quality. The loader and plugin videos were just examples without proper explanation of the underlying concepts. It is highly unlikely someone without prior knowledge of loaders and plugins would be able to follow the videos (as was my case).

**Comment by marvingay** [comment]
We haven't received comparable feedback regarding this resource since the posting of this issues.

Closing for now.
