### ISSUE TITLE
Suggestion : add tests for "Basic Ruby Projects" section of the ruby course

### ISSUE THREAD

**Issue by Sal-theSadmanShark** [TheOdinProject/curriculum#20224]
**Ruby Programming** course has the  "Testing Ruby With Rspec" section later in the course but students have to complete two other project oriented sections to reach it . Web Dev 101's js section had projects with built in test cases and TDD was advised early on . The suggested practise sites ( exercism , codewars , hackerrank) also has test driven exercises . So the exclusion of testing functionality on the basic projects section  seems a bit odd . It's not a major issue but new students may end up making the wrong projects with unexpected output . So I suggest adding some testing functionality , specifically with the minitest gem so it would be consistent with exercism's ruby track . Or the course can be readjusted  to introduce the Rspec section earlier on .

**Comment by KevinMulhern** [comment]
This is being worked on in this repo: https://github.com/TheOdinProject/ruby-exercises

**Comment by thatblindgeye** [comment]
Closing this issue per the above comment about work already being done in another repo, and over a year of inactivity.
