### ISSUE TITLE
Clarify calculator directions

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#20381]
![image](https://user-images.githubusercontent.com/4411701/90806324-1584e400-e2da-11ea-8a02-3997e171940e.png)
In the image above, it almost encourages implementing PEMDAS, this should be removed, or edited to discourage it. PEMDAS is a much harder problem at this stage. 

The calculator example is not accurate to the behavior of what we expect. Find a calculator that works like a very basic calculator, possibly a previous student solution (or your own solution!)

**Comment by adam-goodrich** [comment]
I got this issue

**Comment by I3uckwheat** [comment]
@adam-goodrich Thank you! Be sure to reference this issue in your PR :)
