### ISSUE TITLE
Single Responsibility Principle wording

### ISSUE THREAD

**Issue by josiahmokob0** [TheOdinProject/curriculum#21006]
> Single Responsibility

>One of the most important things to remember as you craft your objects is the Single Responsibility Principle which states that a class (or object or module.. you get the point) should only have one responsibility. Here's a really common example. Most of our code has functions to update and write things to the DOM in addition to our application logic. It's a really good idea to separate out your DOM stuff from the application logic.

I don't much about these principles, but I think the wording could be better. There is another school of thought that states the principle as `A given method/class/component should have a single reason to change`. This definition appeals to me because have only one reason to change means the class/component/method or class, well does one thing. I can easily relate the second definition to most of the projects I am currently working on.

I think the latter could be easier to understand especially to those learning about these principles for the first time.

**Comment by dm-murphy** [comment]
I believe this is the page you are referring to: https://www.theodinproject.com/courses/javascript/lessons/oop-principles

The wording in this section and in a few other parts of the page does sound confusing. It also seems to be written in a different syntax than many of the other curriculum pages. The page is also missing the Assignment section formatting and the Sandi Metz book might go well into an Additional Resources section. 

Your suggestion on `A given method/class/component should have a single reason to change` is discussed in the article links which should probably be in an Assignment section. But I would not suggest replacing the "one responsibility" concept in the paragraph you pointed out. Perhaps the "single reason to change" concept could be mentioned lower in the brief description of "SOLID principles" after the code block examples.

If any of the maintainers would like, I could try to fix up the wording on this page and add in the usual formatting for Assignment sections and Additional Resources. It looks like a previous issue and pull request were made to add the current Learning Outcomes section.

**Comment by jmnyarega** [comment]
Sounds good
