### ISSUE TITLE
Missing note or installations with a Chromebook.

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#21121]
https://github.com/TheOdinProject/curriculum/edit/master/web_development_101/installations/installation_overview.md

Currently we do not support Chromebooks officially, the user is responsible for getting Ubuntu to run on it themselves. We should add a note that explicitly states this, or add some links/directions on how to get Ubuntu on a Chromebook properly. 

If you choose to go the linked directions, or written directions route, you must be able to supply information proving that this will not change and the feature is a feature that is ready for all users, and that you have tested the directions.

**Comment by xandora** [comment]
Starting off, we can immediately eliminate any user that does not have a device on the [supported devices list](https://sites.google.com/a/chromium.org/dev/chromium-os/chrome-os-systems-supporting-linux). Additionally any Chromebook device released in 2019 will support the Linux Beta.

**Comment by xandora** [comment]
I ended up spending the better part of a day trying to get the Linux Beta working on a spare laptop that has CloudReady installed on it without any luck.

We might need someone with a officially supported Chromebook to volunteer as tribute.

**Comment by xandora** [comment]
Perhaps we can use https://flathub.org ?

**Comment by I3uckwheat** [comment]
> Perhaps we can use https://flathub.org ?

What does this solve?

**Comment by xandora** [comment]
@I3uckwheat sorry was just jotting my thoughts down quickly. It's a way to install prepackaged Linux software on a Chromebook using Flatpack style installers.

**Comment by xandora** [comment]
Okay, so I rolled back to CloudReady 80.3 and was able to correctly enable the Linux Beta. I'll be able to further work on the required prerequisite steps now.

**Comment by I3uckwheat** [comment]
@xandora Awesome, if this is viable, it will be a very cheap solution to help a lot of people with.

You tested a Rails install, yes? You can find it here:  https://www.theodinproject.com/courses/ruby-on-rails/lessons/your-first-rails-application-ruby-on-rails

Also Node + NVM: https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/installations/installing_node.md

**Comment by xandora** [comment]
Whoops, I swear I sent this reply over a week ago. Yes, I tested the installation instructions for NVM and Node, and rbenv and Rails. They all installed correctly.

Anyway, this was added in PR #21651 .
