### ISSUE TITLE
Suggestion: Warn against uTorrent during virtual machine installation process

### ISSUE THREAD

**Issue by mangonaise** [TheOdinProject/curriculum#21228]
Apologies if this is not the correct place to suggest this. I'm just starting the course and not knowledgeable enough about git/github to create a pull request for this issue yet.

At the beginning of the Odin introductory course it is recommended for Windows users to create a virtual machine using Xubuntu. On the Xubuntu page it is recommended to use a torrent to download the .iso file. 

It is possible that this may result in many users downloading popular torrent software such as uTorrent. The issue is that uTorrent Web borders on malware. It does not create a program listing and **therefore cannot be easily uninstalled**, it attempts to get unobservant users to install additional useless software, and it **installs the Lavasoft Web Companion without the user's consent.** 

My suggestion is either to tell Odin Project users not to torrent the .iso, or to direct them to safer options like qbittorrent or picotorrent.

**Comment by marvingay** [comment]
We provide a direct download to the `.iso` file from a mirror in the "Prerequisites" lesson.

Was there a place where we link to the Xubuntu page itself?

**Comment by mangonaise** [comment]
Huh, weird. I remember going onto the Xubuntu page for some reason. I must have just searched for it myself. 

Well, issue closed haha.
