### ISSUE TITLE
cant figure out how to post solution ceasar cipher

### ISSUE THREAD

**Issue by JimvandenBos** [TheOdinProject/curriculum#2144]
As stated in the title, i have difficulty finding out how to add my solution to the list. 
the explainations arent helping me. 
here's a link to my solution in github:

https://github.com/JimvandenBos/CeasarCipher/blob/master/solution

thanks!

**Comment by KevinMulhern** [comment]
Hey @JimvandenBos, This video explains how to do it. https://www.youtube.com/watch?v=V74l_zS1x8E
