### ISSUE TITLE
A section on React app testing

### ISSUE THREAD

**Issue by leavemydogalone** [TheOdinProject/curriculum#21506]
With the addition of the new React specific section, I feel it would be a good idea to include how to test React Apps as the information out there is fairly limited. A lot of the info from youtube and articles use the Enzyme testing library, and now the React team says to just use the React testing library

**Comment by zjcrumpton** [comment]
I agree that we need this, I'll be working on it now.

**Comment by marvingay** [comment]
@zjcrumpton  If this is something that you are interested on working on, for the sake of efficiency, it may be be better to write up a lesson(s) proposal or outline before committing to any content work.

There's potential for a conversation to be had about incorporating the Battleship project into becoming something done via React and testing it as a derivative of the lesson or lessons that would be written for React testing. 

If you have any thoughts on this we can discuss this here or you're welcome to drop into our Discord community.

**Comment by thatblindgeye** [comment]
Adding a Status of Completed to this as two PR's have been opened regarding this issue, #23222 and #23223

**Comment by thatblindgeye** [comment]
Closing as both PRs mentioned above have been merged
