### ISSUE TITLE
(WD101) Code block not properly formatted

### ISSUE THREAD

**Issue by aaron-contreras** [TheOdinProject/curriculum#21572]
Bullet point #5 on the **Assignment** is not properly formatted as a code block.
Lesson: https://www.theodinproject.com/courses/web-development-101/lessons/rock-paper-scissors?ref=lnav#assignment

**Comment by aaron-contreras** [comment]
I'll take care of this one.

**Comment by marvingay** [comment]
Resolved in #21588
