### ISSUE TITLE
Not very useful command line resource, alternative suggested

### ISSUE THREAD

**Issue by nhquiroz** [TheOdinProject/curriculum#2158]
On [*How Does Your Computer Work?*](http://www.theodinproject.com/web-development-101/how-does-your-computer-work) section, item 3 of the assignment suggests: "To gain a better understanding of your command line, start with this simple walkthrough by Avi of the Flatiron School."

As you can see on comments [1](https://gist.github.com/aviflombaum/9d6f7448119bae3a24ee#gistcomment-1288097), [2](http://www.theodinproject.com/web-development-101/how-does-your-computer-work#comment-1532872792), [3](https://gist.github.com/aviflombaum/9d6f7448119bae3a24ee#gistcomment-1463633), [4](https://gist.github.com/aviflombaum/9d6f7448119bae3a24ee#gistcomment-1480805), this often confuse more than it helps, so I think it's better to remove it.

Zed Shaw's Crash Course does a much better work. Alternatively, this is another good basics tutorial: [Command Line Basics - Level Up Tutorials](http://leveluptuts.com/tutorials/command-line-basics) (instead of N°3).

**Comment by KevinMulhern** [comment]
I came across this the other day, https://www.codecademy.com/courses/learn-the-command-line
could be another useful resource for beginners learning the command line.

**Comment by nhquiroz** [comment]
Codecademy's seems nice too.

**Comment by rbyfalr** [comment]
Here's a few more, [Introduction to the Command Line](http://www.gotealeaf.com/books/command_line), [A Beginner's Guide to the Linux Command Line: Part 1](http://www.techspot.com/guides/835-linux-command-line-basics/ and [A Beginner's Guide to the Linux Command Line: Part 2](http://www.techspot.com/guides/844-linux-command-line-part-iii/.

**Comment by japfohl** [comment]
I agree with KevinMulhern.  The Code Academy command line course is good!

**Comment by KevinMulhern** [comment]
So in a effort to close this issue can we agree on the new structure of the resources?

My thinking is:

Replace the flatiron school link and replace it with the codecademy course (an interactive course will be much more effective for a beginner.)

Add in the link @nhquiroz provided at the top of the additional resources.

**Comment by KevinMulhern** [comment]
do you guys want to way in on this? @eriktrautman, @muzfuz

**Comment by muzfuz** [comment]
I'm happy with that.

**Comment by eriktrautman** [comment]
Sounds good @KevinMulhern
