### ISSUE TITLE
Javascript conclusion mentions Rails but is missing Node

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#21774]
Page: https://github.com/TheOdinProject/curriculum/blob/master/javascript/finishing-up/conclusion.md

Solution:
a. Rewrite section to accommodate both Node and Rails
b. Rewrite section to mention "back-end of your choice" instead.

Sentences must be complete, with good English.

**Comment by The-sad-philosopher** [comment]
I'm quite new to this community and I just found this issue through discord, can I have a go at this?
