### ISSUE TITLE
Empty Additional Resources section on Rails Basics Views lesson

### ISSUE THREAD

**Issue by ZachBaird** [TheOdinProject/curriculum#21797]
**Problem:**
At the lesson [here](https://www.theodinproject.com/courses/ruby-on-rails/lessons/views), there is an Additional Resources section that has no content.

**Acceptance Criteria:**
Find some additional, useful content that explore the basics of Rails views further. Submit a pull request to the `curriculum` repository with these new resources.

Alternatively, we can compile a list of stuff to go over in this issue, but we think someone taking ownership of this issue would be great for a first-time contributor.

**Comment by nhleto** [comment]
I can dig into that. I recently watched some YouTube videos on views recently.

**Comment by ZachBaird** [comment]
Cool @nhleto ! Shall I assign this to you?

**Comment by ZachBaird** [comment]
@nhleto has addressed this in PR #21799 .
