### ISSUE TITLE
Add Content About each of the Path Choices in Web Dev 101 Conclusion Lesson

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#21806]
### Problem
Users often come into chat asking the same questions about which path to take.

### Solution
While this a problem is likely to stick around we can mitigate it a great deal by providing details about the different paths we provide to help with their decision making process.

### Acceptance Criteria
1. Go to the [conclusion lesson of Web Dev 101](https://www.theodinproject.com/courses/web-development-101/lessons/conclusion-web-development-101)
2. There should be a section of content about what users should consider when choosing a track
3. There should be a section of content about the Frontend Track and why the student might want to do that path.
3. There should be a section of content about the Full Stack JS Track and why the student might want to do that path.
4. There should be a section of content about the Full Stack Rails Track and why the student might want to do that path.

### Additional Information
Searching "which track" on the TOP Discord chat may lead to some good ideas about what to include in the content as this comes up a lot.

**Comment by I3uckwheat** [comment]
@KevinMulhern I think we need to remove number 3 from that. We are going to remove the frontend only path

**Comment by I3uckwheat** [comment]
I can also take this on

**Comment by KevinMulhern** [comment]
No worries @I3uckwheat, I just wanted to include it incase this went out before the frontend path was removed :)

**Comment by I3uckwheat** [comment]
@KevinMulhern I'll be working on this as soon as frontend only path is removed
