### ISSUE TITLE
Broken link: this quick interview with Matt Jording

### ISSUE THREAD

**Issue by cfwong** [TheOdinProject/curriculum#21828]
Assignment in Introduction to the Back End, under Web Development 101.

**Comment by I3uckwheat** [comment]
@cfwong Could you please attach a link to the TOP page?

**Comment by I3uckwheat** [comment]
This has been fixed with #21825 however, this is a temporary fix, we need to replace the archive link.

Here is the link to the lesson @cfwong forgot to add: https://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-the-back-end

**Comment by xandora** [comment]
Here's a non-web archive link to a mirror of the interview:

https://www.bizjournals.com/washington/inno/stories/news/2014/03/31/what-is-back-end-web-development.html

**Comment by I3uckwheat** [comment]
@xandora Would you like to make a PR for this?

**Comment by xandora** [comment]
Yes, and no. I'm happy to make a PR to change the link, but perhaps this is an opportunity to reflect on the article and see if there is a better alternative now?

**Comment by I3uckwheat** [comment]
@xandora This resource seems to be OK for what it is, but I'm sure there are better ones out there.

I think that we should change the link to a proper link instead of an archived one first, then we can re-evaluate.

**Comment by xandora** [comment]
Sound good. Will raise a PR.

**Comment by xandora** [comment]
Fixed under #21959
