### ISSUE TITLE
dead link 

### ISSUE THREAD

**Issue by siduck76** [TheOdinProject/curriculum#21839]
![image](https://user-images.githubusercontent.com/59060246/97186364-36c8eb80-17c7-11eb-9d0e-6f2e34707949.png)
the wired* link doesnt work 

TOP page : https://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-frameworks-web-development-101

**Comment by twalton83** [comment]
If you don't want to make the PR, I can fix this up.
