### ISSUE TITLE
view old submitions link dead

### ISSUE THREAD

**Issue by DoviMaj** [TheOdinProject/curriculum#21867]
view old submissions leads to 404 error page in all of the react projects pages.

**Comment by I3uckwheat** [comment]
@DoviMaj Please give links to the pages.

**Comment by DoviMaj** [comment]
https://www.theodinproject.com/courses/javascript/lessons/shopping-chart
https://www.theodinproject.com/courses/javascript/lessons/memory-card
https://www.theodinproject.com/courses/javascript/lessons/cv-application

someone on the chat mentioned (i think Marvin) that there are no old submitions for those. but anyhow he said to leave the issue open to fix.

**Comment by marvingay** [comment]
@DoviMaj  We were able to discuss the future of the "old submissions" link in regards to the Project Submissions feature. In the near future, this link/feature will be removed altogether as it has served its intended purpose. As such, it's not practical to put in unnecessary effort.

Thanks for keeping this up for us! We're good to close now.
