### ISSUE TITLE
Add Linux Journey as resource

### ISSUE THREAD

**Issue by igorradovanov** [TheOdinProject/curriculum#21864]
I think it would be a great addition to add a Linux Journey (https://linuxjourney.com/) as an additional resource for the COMMAND LINE BASICS section of the Odin Project curriculum (https://www.theodinproject.com/lessons/command-line-basics-web-development-101)

**Comment by I3uckwheat** [comment]
I do not think we want this in TOP at that stage. At that stage one doesn't have to know much more than the things we outline. 

I agree we could have a bit more, but this is way too much and will distract people from actually getting to the important parts of TOP, the code.
