### ISSUE TITLE
Additional Resources Thoughtbot exercise for Ruby's TDD page requires Rails and other gem installations not covered in TOP

### ISSUE THREAD

**Issue by dm-murphy** [TheOdinProject/curriculum#21869]
After a discussion about this problem on Discord it was recommended I file a new issue.

The current [Test Driven Development page](https://www.theodinproject.com/courses/ruby-programming/lessons/test-driven-development) in the Ruby track lists one Additional Resource, a link to [Thoughtbot](https://thoughtbot.com/upcase/testing) exercises. There is a basic [Fundamentals of TDD](https://thoughtbot.com/upcase/fundamentals-of-tdd) series that goes over RSpec along with more advanced ones. 

Halfway through the Fundamentals of TDD series the exercise requires cloning a [repo](https://github.com/thoughtbot-upcase-exercises/tdd-spec-cleanup-exercise) that needs Rails and at least a dozen gems that have not been covered to this point in the TOP curriculum. After troubleshooting on Discord it seems some of the gem requirements here might be old/outdated or have potential installation clashes between gems. Thoughtbot does not cover these installations either.

I would like to suggest making a note in the Additional Resources section of TOP's page giving students a heads up about the Thoughtbot exercises and how they require certain gems that have not been covered yet and may be outdated. 

If there was another suggestion on a newer RSpec tutorial resource we could add that as well.

I am happy to make a PR on this if that is alright. Thanks!

**Comment by rlmoser99** [comment]
Thanks for taking the time to create this issue. As we discussed on Discord, I had the exact same problem using that Thoughtbot repo. The original link has multiple Thoughbot testing lessons, but I think the link should be either to the Fundamentals of TDD lessons (with your suggested warning) or to its most useful video. I only did the first half of those lessons, but I found the Red-Green-Refactor video was the most helpful to me. If you are still willing to make a PR for this additional resource, please go ahead and submit one.

**Comment by dm-murphy** [comment]
Thanks @rlmoser99 I will submit a PR this week. I also agree with linking directly to the Fundamentals of TDD lesson page instead of their general testing page.
