### ISSUE TITLE
Foundations Course - Improve lesson link doesn't work

### ISSUE THREAD

**Issue by igorradovanov** [TheOdinProject/curriculum#21866]
Improve lesson link for all classes in Foundations Course resolves to 404 Page Not Found.

For example https://github.com/TheOdinProject/curriculum/edit/master/web_development_101/git_basics/introduction_to_git.md

It looks like the **web_development_101** path needs to be switched to **foundations** in order to work again.

**Comment by I3uckwheat** [comment]
@igorradovanov Please give a link to the lesson
