### ISSUE TITLE
Installing Ruby: confusing directions for installing Ruby extension - Ruby or ruby-rubocop?

### ISSUE THREAD

**Issue by PatrickMayoMoran** [TheOdinProject/curriculum#21871]
Hi,

In the first "extras" paragraph for the [Installing Ruby Lesson](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/introduction/installing_ruby.md), it currently says to search and install the "Ruby" extension, but it then has (Rubocop) at the end in parentheses.

As someone taking the lesson, this was confusing to me. This was because when I search "Ruby" in VSCode, there is an extension called ruby-rubocop. Which one am I supposed to install? The rest of the directions make it sound like it is just the first, plain "Ruby" extension that pops up, but then why is (Rubocop) there in parentheses at the end capitalized? Is this to teach that Rubocop is the name for formatting support? Or something else?

Could you clarify the language? Depending on what the true meaning is, one of the following might be clearer:

- leaving (Rubocop) out entirely

- "...which will provide you with semantic highlighting and formatting support. These features are called "Rubocop" and are used in most Ruby extensions" (or whatever the explanation is that made you want to include (Rubocop) in the first place)

Thanks!

**Comment by rlmoser99** [comment]
Thank you for taking the time to submit this issue and bringing it to our attention. This reference to rubocop is not necessary at this point in the curriculum and will be removed.
