### ISSUE TITLE
Repl.it exercise needs clearer language -- Foundations Fundamentals Part 2

### ISSUE THREAD

**Issue by dswhite11** [TheOdinProject/curriculum#21873]
Towards the end of the Foundations Fundamentals Part 2 lesson, there is a section labeled 'Practice.' In that section are 4 exercises that are all hosted on Repl.it.

Exercise 2 -- [linked here](https://repl.it/@I3uckwheat/enter-a-number#script.js) -- could use clearer language in the comments, which serve as instructions for the exercise.

On line 5 of the JavaScript, 'logs' should be changed to 'returns,' since that is more accurate. I failed the challenge multiple times because I interpreted that instruction literally and included a `console.log();` statement. Only when I changed those statements to `return` statements did I successfully complete the challenge. I imagine other folks might have similar problems, which could be solved by changing the phrasing.

**Comment by I3uckwheat** [comment]
Fixed :)
