### ISSUE TITLE
Another CSS showcase

### ISSUE THREAD

**Issue by ryodaeva** [TheOdinProject/curriculum#21889]
Hello all,

there is [Style Stage](https://stylestage.dev/) : a modern CSS showcase styled by community contributions.

That would be great to add it with CSS Garden ?

**Comment by I3uckwheat** [comment]
@ryodaeva Please add a link to the page with the issue, thanks!

**Comment by ryodaeva** [comment]
This the page : https://github.com/TheOdinProject/curriculum/blob/master/foundations/the_front_end/project_html_css.md
