### ISSUE TITLE
Typo in Command Line Basics Web Dev 101

### ISSUE THREAD

**Issue by CodeVeish** [TheOdinProject/curriculum#21883]
There's a typo in the basics of command line section that might cause some confusion when understanding tab autofill in terminal. The highlighted within the below screenshot should be a 'f' instead of a 'w' for  '/foundations/' autofill with tab key.

Marvin on Discord confirmed that this was an error when the track changed from 'Web Development 101' to 'Foundations'  and requested I open an issue here. 

![Screenshot from 2020-11-09 14-17-06](https://user-images.githubusercontent.com/73959266/98591765-50be0000-2296-11eb-9386-8bf20b5da7a1.png)

Exact URL: https://www.theodinproject.com/courses/foundations/lessons/command-line-basics-web-development-101

**Comment by xandora** [comment]
Thank you for taking the time to raise this issue.

If you'd like to give it a go, feel free to edit the lesson page here: https://github.com/TheOdinProject/curriculum/edit/master/foundations/installations/command_line_basics.md

Make the change

**Comment by barrage125** [comment]
Hi all. I'm working on this now and will be submitting a PR shortly.
