### ISSUE TITLE
Grammar fix needed in foundations/javascript_basics/fundamentals-1.md

### ISSUE THREAD

**Issue by mauryneipris** [TheOdinProject/curriculum#21882]
In the 'Variables' section of JavaScript basics in Fundamentals Part 1, there is a grammatical error.

 "This variable tutorial will explain you everything" should be "This variable tutorial will explain **to** you everything you need to know!".

**Comment by I3uckwheat** [comment]
@mauryneipris Hey! We're going to need more information. A link to the lesson is a MUST when posting an issue :)
