### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ryodaeva** [TheOdinProject/curriculum#21894]
In this page [https://www.theodinproject.com/courses/getting-hired/lessons/what-companies-want](https://www.theodinproject.com/courses/getting-hired/lessons/what-companies-want) , the link [The Best Way to Hire Software Developers](http://insights.dice.com/2013/05/31/hiring-software-developers/) is no more alive.

Page in github : [https://github.com/TheOdinProject/curriculum/blob/master/getting_hired/what_companies_want.md](https://github.com/TheOdinProject/curriculum/blob/master/getting_hired/what_companies_want.md)

**Comment by sher-s7** [comment]
It seems to be working fine for me

**Comment by CouchofTomato** [comment]
Thanks @ryodaeva 

As @sher-s7 said the link seems to be working so I'm going to close this.

**Comment by ryodaeva** [comment]
Sorry , this is due to my firewall.
