### ISSUE TITLE
Description of rest-client gem's behavior possibly outdated in Kittens API project

### ISSUE THREAD

**Issue by andrewjh271** [TheOdinProject/curriculum#21903]
Lesson: [https://www.theodinproject.com/courses/ruby-on-rails/lessons/kittens-api#json-api](https://www.theodinproject.com/courses/ruby-on-rails/lessons/kittens-api#json-api)

Step 2 of the JSON API section describes the expected output of `response = RestClient.get("http://localhost:3000/kittens")` to be an HTML string, and the server request to process as XML.

As described in the [README](https://github.com/rest-client/rest-client#upgrading-to-rest-client-20-from-1x), version 2 produces different behavior:

- `RestClient::Response` objects are a subclass of `String` rather than a Frankenstein monster. And `#body` or `#to_s` return a true `String` object.
- default request headers: rest-client sets `Accept: */*` and `User-Agent: rest-client/...`

**Comment by andrewjh271** [comment]
If approved, I could just edit the line so that it refers to `response.body` returning the HTML,  and switch the mention of `XML` to `*/*`.

**Comment by CouchofTomato** [comment]
Thanks @andrewjh271 

We're happy to receive a PR on the issue. It's easier for us to resolve any issues with text modifcations once we see the PR. I'll assign this issue to you.
