### ISSUE TITLE
Lesson on reading documentation

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#21907]
It's come to my attention that many people aren't reading the documentation and are attempting to complete projects with a very incomplete view of the frameworks they're trying to use. After talking to them, it seems they're not reading the docs because they didn't understand that they should be reading them. 

Completion criteria:

- [x] Find a place in the curriculum where this should land, it should probably be early on.
- [x] Explain *why* someone should read the docs
- [ ] Explain *how much* you should read of the documentation (hint, it's all of it)
- [ ] Explain *how* to reference the documentation after it's been read when running into issues
- [ ] Give some basic examples on how to solve problems using the documentation (for example, using a for loop)
- [x] Explain that good devs read the documentation, sometimes multiple times.
- [x] Explain that it's not rude to be told to read the documentation, often times you've missed something that's easy to understand.

**Comment by bycdiaz** [comment]
I'm very interested in taking this one. It'll be a few weeks before I can give it a ton of time but I should have progress on this in early December.

**Comment by I3uckwheat** [comment]
@bycdiaz The completion criteria are flexible, feel free to edit.

**Comment by twalton83** [comment]
Per our discussion, we could find a place, somewhere, to add a section specifically for reading error messages and leveraging them as a valuable resource rather than a "digital reprimand".

**Comment by thatblindgeye** [comment]
I'm going to be closing this due to over a year of inactivity. If this is something we still want to work towards, a new issue may be better to re-evaluate what work needs to be done.
