### ISSUE TITLE
Why there is no available course for react?, your website is made by react!!

### ISSUE THREAD

**Issue by YousifAbozid** [TheOdinProject/curriculum#21902]
I hope to see a perfect course that discussing react because most modern websites created by react as your website as well, is there any plans to add new courses especially for react?, also I know that Odin Project is made for beginners, also is there any plans to add some professional content for who is not beginner?

Thanks :)

**Comment by codyloyd** [comment]
look closer brousif ;)

https://www.theodinproject.com/courses/javascript#react-js

**Comment by I3uckwheat** [comment]
I'd also like to point out that the site is pretty much only Rails. With a small sprinkling of React.

**Comment by YousifAbozid** [comment]
Oh, thanks for that, my fault.
