### ISSUE TITLE
"Choosing coding bootcamps" book suggested in "alternative paths" isn't even published

### ISSUE THREAD

**Issue by LrdVnz** [TheOdinProject/curriculum#21918]
I was skimming throught the curriculum sessions, and in the getting hired, in "alternate paths" section
 https://theodinproject.com/courses/getting-hired/lessons/alternate-paths-to-a-web-development-job
in the "coding bootcamps" there's a link to a book that started in 2013 and isn't even published yet, so it is unobtainable. ( https://leanpub.com/coding-bootcamps ) I would suggest some other resource but the one I have is just the first result in googling "choosing a coding bootcamp" (https://www.coursereport.com/coding-bootcamp-ultimate-guide). Skimming throught it seems to have an overall comprehensive look, but I don't know if it's the type of resource wanted for TOP.

**Comment by CouchofTomato** [comment]
Thanks @LrdVnz 

I believe that section of the curriculum has now been removed.
