### ISSUE TITLE
Javascript course review doesn't make sense coming from foundations in the fullstack JS path.

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#21921]
https://www.theodinproject.com/courses/javascript/lessons/a-quick-review

The lesson above comes directly after the foundations course, which is mostly JavaScript. If the student has just been doing JS, there's no reason to do the review that's there. Also the jQuery mention may be outdated and not needed anymore.

To close this issue this is what needs to be done:

- [ ] re-write the lesson to make sense in both path's context (Ruby and Node paths)
- [ ] evaluate the jQuery mention and necessity

this whole lesson could use a re-write.

**Comment by ChargrilledChook** [comment]
I'm happy to work on this.

**Comment by LrdVnz** [comment]
This looks like a good change to talk about documentation, the importance of being able to look at it and use it . Let me try to write something about it

**Comment by LrdVnz** [comment]
Oh sorry didn't see there was an issue open about documentation ! Let's see how that goes, but I still think this isn't a bad place to make a review about it

**Comment by I3uckwheat** [comment]
@ChargrilledChook Thanks! I'll assign it to you!

**Comment by I3uckwheat** [comment]
> Oh sorry didn't see there was an issue open about documentation ! Let's see how that goes, but I still think this isn't a bad place to make a review about it

I agree with this, we could link back to the future lesson on documentation, but this is off-topic for this. Keep it in mind @LrdVnz when that other one gets merged :)

**Comment by I3uckwheat** [comment]
@ChargrilledChook Have you had a chance to work on this?
