### ISSUE TITLE
Clicking 'complete' button

### ISSUE THREAD

**Issue by sanderheieren** [TheOdinProject/curriculum#21920]
Once I click the 'complete' button it goes to incomplete first, stays there for 0.2 seconds and then it changes to "completed!". Not a big issue, but I guess it's because of some react rendering failure?

**Comment by I3uckwheat** [comment]
Ahh, yes. Flashing. This is indeed a problem, but I do not think we use React here on this component.

**Comment by sher-s7** [comment]
Seems to be working fine for me in Firefox. It goes from _incomplete state > submitting > completed_ with no flashing.

**Comment by sanderheieren** [comment]
You are right! My bad, thanks for clearing it up though :)
