### ISSUE TITLE
Remove Bootstrap mentions in the React portion of Javascript

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#21945]
See: #21944 for more info on *why* we want to make this change.

Completion criteria:

- [x] Remove Bootstrap references from [this](https://github.com/TheOdinProject/curriculum/blob/3ab3f314d3d13b818db43fa4ed09d8b7042fbc17/javascript/react-js/inputs-and-lists.md) page.
- [x] re-work the content to make sense given the new context without bootstrap
- [x] identify other places in the JS section that reference bootstrap and remove them.

**Comment by vinicius77** [comment]
May I help with this issue? I could also make a brief introduction about styling React components using CSS in order to keep the styling context valid even without Bootstrap.

**Comment by marvingay** [comment]
@vinicus77 You're welcome to start working on this if you'd like, I'll go ahead and assign it to you.
If you have any questions, concerns, or comments do not hesitate to ask here.

**Comment by vinicius77** [comment]
Thanks for assigning me @marvingay . I am already working on it. :)

**Comment by twalton83** [comment]
The first bullet has had changes merged. Thank you @vinicius77!

**Comment by TaylorJonesTRT** [comment]
I have found another mention of Bootstrap in the React course on this [page](https://github.com/TheOdinProject/curriculum/blob/master/javascript/react-js/project-cv.md) that I'll take care of removing!

**Comment by twalton83** [comment]
Thank you @TaylorJonesTRT!

**Comment by twalton83** [comment]
The last PR fulfilled the criteria of completion for removing all instances of Bootstrap from the Javascript course, so this may now be closed.
