### ISSUE TITLE
Remove Bootstrap from HTML/CSS course

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#21944]
https://www.theodinproject.com/courses/html-and-css#responsive-design-and-css-frameworks

As you can see here, we talk about CSS frameworks, and then introduce bootstrap. Bootstrap is something falling out of favor among companies, and having this framework in our course has the effect of people not practicing their CSS enough in their future projects. Removing this section will make it clear that we want students to write good CSS before diving into frameworks.

Completion criteria:

- [x] Remove the bootstrap lesson: https://www.theodinproject.com/courses/html-and-css/lessons/using-bootstrap
- [x] Edit [this lesson](https://www.theodinproject.com/courses/html-and-css/lessons/css-frameworks-like-bootstrap-and-foundation) to be more generalized about frameworks instead of mostly about Bootstrap. 
- [x] Discourage the use of frameworks for the time being in the curriculum, and promote practice of CSS fundamentals. 

The goal of the CSS frameworks lesson should be to explain what they are, and give a quick overview on them just to fill knowledge. But it should not encourage them to use them before they've learned CSS very well.

**Comment by twalton83** [comment]
All good if I take a swing to finish this out?

**Comment by ZachBaird** [comment]
This looks like it might be complete. Can @I3uckwheat or @twalton83 confirm?

**Comment by twalton83** [comment]
It’s done!
