### ISSUE TITLE
add the tittles to each lesson.

### ISSUE THREAD

**Issue by developingathome** [TheOdinProject/curriculum#21949]
Add the Tittles to each lesson -  example JavaScript - Fundamentals Part 1.
some subtitles are self-explanatory but others are not.

Note: this is my first time reporting an issue & I would be happy to help!

**Comment by I3uckwheat** [comment]
@developingathome Hey, there's not enough information here to understand what you are saying fully, please attach screenshots and links to what you're talking about and i'll re-open this issue :)
