### ISSUE TITLE
Blog author recommends updated post available on word logical operators

### ISSUE THREAD

**Issue by egomadking** [TheOdinProject/curriculum#21947]
[Conditional logic lesson](https://www.theodinproject.com/courses/ruby-programming/lessons/conditional-logic) links to http://www.virtuouscode.com/2010/08/02/using-and-and-or-in-ruby/

The post author recommends a new post with better explanation: https://avdi.codes/how-to-use-rubys-english-andor-operators-without-going-nuts/

**Comment by I3uckwheat** [comment]
@egomadking Can you make a PR with this change?
