### ISSUE TITLE
Ruby Programming Loops section Until loop issue

### ISSUE THREAD

**Issue by matt-manning** [TheOdinProject/curriculum#21953]
I was just reading through the Loops section in the Ruby course and found an error. In the Until Loop section, the lesson claims that this loop:
```
i = 0
until i > 10 do
  puts "i is #{i}"
  i += 1
end
```
does the same thing as this while loop:
```
i = 0
until i < 10 do
  puts "i is #{i}"
  i += 1
end
```
The problem is that the until loop would one more time than the while loop. The until loop would run 0 - 10, but the while loop would run 0 - 9.

**Comment by I3uckwheat** [comment]
@matt-manning Please attach a link to the lesson and I will re-open this issue.

**Comment by matt-manning** [comment]
Here is the link to the lesson. Sorry I didn't attach it before.

https://www.theodinproject.com/courses/ruby-programming/lessons/loops

**Comment by I3uckwheat** [comment]
@matt-manning You have copied the wrong parts of the code into your issue description, however, you are correct. the `until` example needs an `=` after the `>`

```ruby
i = 0
until i >= 10 do
 puts "i is #{i}"
 i += 1
end
```

is the correct `until` loop syntax to match the `while` loop.

**Comment by rlmoser99** [comment]
@matt-manning Would you be willing to make this change (adding a `=`) by submitting a PR?
