### ISSUE TITLE
Low quality resource

### ISSUE THREAD

**Issue by nanyaDev** [TheOdinProject/curriculum#21958]
In the [Files and Serialization Lesson](https://www.theodinproject.com/courses/ruby-programming/lessons/files-and-serialization-ruby-programming), Assignment 3 links to an [article](https://skorks.com/2010/04/serializing-and-deserializing-objects-with-ruby/) that is very poorly formatted. The bulk of the article's lesson is contained in a 200+ line block of code that does not use word wrap. Since the author uses long comments to explain each part of the code, you have to constantly horizontal scroll to read the lesson, and it's a hassle to scroll back to reference the code. 

This article is over a decade old, and I'm sure a better article is out there, but since I don't currently have the expertise to differentiate between good and bad articles, I've opened up this issue.

**Comment by I3uckwheat** [comment]
This article is still good and relevant. Serialization is one of those super fundamental things.

**Comment by rlmoser99** [comment]
I agree with @I3uckwheat that the article is well-written (besides the code snippets). The best way to read through these code snippets is to copy and paste it into your code editor and use word wrap. 

However, I think it is worth seeing if someone can find a more updated resource before we decide.
