### ISSUE TITLE
Update lesson to use new default branch name of 'main'

### ISSUE THREAD

**Issue by nanyaDev** [TheOdinProject/curriculum#21969]
The [Installing Rails](https://www.theodinproject.com/courses/ruby-on-rails/lessons/your-first-rails-application-ruby-on-rails) lesson uses `git init` in Step 2.1 and then uses `git push -u origin master`. This does not work anymore as the new default branch name is main. The rest of the lesson also references the non-existent master branch.

**Comment by twalton83** [comment]
Resolved with #22013.
