### ISSUE TITLE
Add zsh related instructions for NVM/node installation

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#21971]
- Currently [this lesson](https://github.com/TheOdinProject/curriculum/blob/master/foundations/installations/installing_node.md) references bash related files such as ~/.bashrc

- For those who are on Catalina and above, the default terminal is now zsh and the correlated file is ~/.zshrc

Lesson should be updated to include instructions on amending a `~/.zprofile or `~/.zshrc` file instead.

**Comment by SidWorks** [comment]
I am working on it!

**Comment by twalton83** [comment]
Thank you.

**Comment by twalton83** [comment]
Closed with #22187
