### ISSUE TITLE
Teach about environment variables in API lesson

### ISSUE THREAD

**Issue by fortypercenttitanium** [TheOdinProject/curriculum#21973]
In the [Javascript APIs lesson](https://theodinproject.com/courses/javascript/lessons/working-with-apis), we teach about using APIs and assign projects for students to use them, but we never instruct how to hide the keys in an environment variable. This is a very important aspect of working with APIs and, I believe, essential to this lesson. We have had several students commit their API keys to github as a result.

**Comment by I3uckwheat** [comment]
Talked in chat about this.
