### ISSUE TITLE
Assignment #2 of Recursive Methods in course Ruby Programming has a dead link.

### ISSUE THREAD

**Issue by minamyooui** [TheOdinProject/curriculum#21986]
The link to vimeo shows no video exists.

**Comment by shoebham** [comment]
The second link
`Watch this Video on Recursion by Joshua Cheek but only until minute 17:36! (don’t want to give away the project…)`
in the assignment section of the chapter is broken , after clicking the [link](http://vimeo.com/24716767) it takes to a page that says

![image](https://user-images.githubusercontent.com/25881429/101596404-00fc6100-3a1b-11eb-93f6-5be290333117.png)

Link to the chapter: - https://www.theodinproject.com/courses/ruby-programming/lessons/recursive-methods
