### ISSUE TITLE
Evaluate Medium Content for possible replacement

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#22020]
The Odin Project currently uses a few articles from Medium. Medium paywalls users after they view five articles in a month. Many of these authors crosspost these materials to other platforms, such as their personal blog, Dev.to, and the like. We should replace Medium links with these other free sources as much as possible. 

Completion Criteria:
- [x] Identify all areas in which we use Medium in the curriculum (you can easily achieve this by searching the repository for "medium.com"
- [x] Replace the links with non-Medium links. If a non-Medium link does not exist, please keep the content as is. 
- [ ] Identify alternatives to replace Medium content

**Comment by lucitemple** [comment]
I'd be happy to work on this.

**Comment by twalton83** [comment]
@lucitemple Awesome, thank you so much! I'll assign this to you. Please let me know if you have any issues. For each link fix, I'd appreciate if you grouped each module (each section within a course, for example,  the "Introduction" module in the "Foundations" course) together in one PR so it's easier to go over.

**Comment by lucitemple** [comment]
Sure thing @twalton83, thank you for the advice about how to best do it (grouping by course for PRs & keeping track of those I can't replace) - this is very helpful for someone new to this, as I am.

**Comment by twalton83** [comment]
@lucitemple Be sure to check out our [contributing guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md)!

**Comment by lucitemple** [comment]
Just completed the changes for the **nodeJS course**. There were three links I couldn't find an alternative to:

1. File: theOdinProject/curriculum/nodeJS/APIs/API-Security.md
- [Stateless Auth with Express Passport](https://medium.com/@paul.allies/stateless-auth-with-express-passport-jwt-7a55ffae0a5c)

2. File: nodeJS/APIs/APIs.md
- [Using Cors in Express](https://medium.com/zero-equals-false/using-cors-in-express-cac7e29b005b)
- [The 7 Restful Routes](https://medium.com/@shubhangirajagrawal/the-7-restful-routes-a8e84201f206)

**Comment by lucitemple** [comment]
Have completed find/replace for the **foundations** and **javascript** courses.

Links I couldn't find alternatives for in these sections:

**Course: Foundations**
File: foundations/javascript_basics/fundamentals-3.md
- [Node Call Stack Explained](https://medium.com/javascript-in-plain-english/node-call-stack-explained-fd9df1c49d2e)

File: foundations/tying_it_all_together/conclusion.md
- [Choosing the right language](https://medium.com/@bycdiaz/choosing-the-right-language-a-short-guide-on-how-not-to-ruin-your-career-2b353be1371)

File: foundations/introduction/motivation_and_mindset.md
- [More productivity with the pomodoro technique](https://medium.com/life-hacks/more-productivity-with-the-pomodoro-technique-d7ce8926ec0c#.hcqsv37u4)

File: foundations/installations/prerequisites.md
- [Micrososft Failed Developers and now has a plane to win them back](https://onezero.medium.com/microsoft-failed-developers-and-now-it-has-a-plan-to-win-them-back-ecdafde5b20)

**Course: JavaScript**
File: javascript/testing/testing-2.md
- [JavaScript: What are pure functions?](https://medium.com/@jamesjefferyuk/javascript-what-are-pure-functions-4d4d5392d49c)
- [Why I use Tape Insteadof Mocha](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4)
- [Mocking is a code smell](https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a)

File: javascript/organizing-js/oop-concepts.md
- [S.O.L.I.D. The first 5 principles of Object Oriented Design with JavaScript](https://medium.com/@cramirez92/s-o-l-i-d-the-first-5-priciples-of-object-oriented-design-with-javascript-790f6ac9b9fa)
- [Object-Oriented Programming in JavaScript](https://medium.com/better-programming/object-oriented-programming-in-javascript-b3bda28d3e81)

File: javascript/organizing-js/classes.md
- [Is Class in ES6 the New Bad Part?](https://medium.com/@rajaraodv/is-class-in-es6-the-new-bad-part-6c4e6fe1ee65)

File: javascript/finishing-up/conclusion.md
- [Currying in Javascript from Kristina Brainwave via Medium](https://medium.com/p/ce6da2d324fe)

File: javascript/react-js/react-introduction.md
- [Function vs Class Component in React](https://medium.com/@Zwenza/functional-vs-class-components-in-react-231e3fbd7108)

File: javascript/organizing-js/factory-functions.md
- [3 Different Kinds of Prototypal Inheritance](https://medium.com/javascript-scene/3-different-kinds-of-prototypal-inheritance-es6-edition-32d777fa16c9)

**Comment by twalton83** [comment]
@lucitemple Thank you so much for your help with this so far!

**Comment by lucitemple** [comment]
@twalton83 Did you want me to check the links in the archived courses too? I've gone through everything else, mostly having trouble finding an open source alternative for them.

There is the option to swap links for a cached text only version, but many of them include images and formatting important for understanding. 

Or perhaps there is a way to inform people of the workaround to accessing Medium articles beyond the free limit (to open links in an incognito window)? 

I have saved all the remaining medium links into a file (same info as I've shared in comments here) - is there somewhere I should upload it to?

Thanks!
 _______

### Course: HTML-CSS
File: html_css/responsive_design.md
* [Best Practices of Responsive Web Design](https://medium.com/level-up-web/best-practices-of-responsive-web-design-6da8578f65c4)

File: html_css/css_frameworks.md
* [Choosing Bootstrap or Foundation](https://medium.com/@davegenge/bootstrap-vs-foundation-which-front-end-framework-to-use-e85319258b88)

File: html_css/design_ux.md
* [Usability 101 for Startups from Ripul Kumar](https://medium.com/design-ux/dc849621262f)

### Course: Ruby
File: ruby_programming/object_oriented_programming_basics/lesson_oop.md
* [Object Relationships in Basic Ruby](https://medium.com/@marcellamaki/object-relationships-in-basic-ruby-1af5773fff48)

File: ruby_programming/testing_with_rspec/introduction_to_rspec.md
* [Getting Started with Rspec Part 1](https://medium.com/@mindovermiles262/getting-started-with-rspec-part-1-9418909f5e53)

File: ruby_programming/basic_ruby/debugging.md
* [Overcoming Ruby Error Messages](https://medium.com/@roni.shabo/overcoming-ruby-error-messages-ebf53928b64e)

File: ruby_programming/basic_ruby/basic_enumerable_methods.md
* [Reducing Enumerable](https://medium.com/@baweaver/reducing-enumerable-part-one-the-journey-begins-ddc1d4108490)

### Course: Rails
File: rails_programming/rails_basics/routing.md
* [Understanding Rails Routes and Restful Design](https://medium.com/podiihq/understanding-rails-routes-and-restful-design-a192d64cbbb5)

File: rails_programming/apis/api_interfacing.md
* [this Medium article Integrating a Third Party API with Rails5](https://revs.runtime-revolution.com/integrating-a-third-party-api-with-rails-5-134f960ddbba)
* [Using an api in Rails for Noobs](https://medium.com/food4fluctuations/using-an-api-in-rails-for-noobs-5e02edb0e56b)

**Comment by twalton83** [comment]
@lucitemple No need, this comment suffices I just wanted to see the remaining. And no, archived courses are archived :) 

I personally don’t want to inform people of a workaround because to me, it’s not a good look for the platform to promote that, and if people are interested, they’ll find it. 

Thank you for doing this, it’s much appreciated!

**Comment by twalton83** [comment]
At this point with the minimal number of Medium articles, the issue of running into the article limit is far less great than was prior, so this issue will be closed.
