### ISSUE TITLE
Fix Typo in "The Asset Pipeline" Lesson

### ISSUE THREAD

**Issue by michpara** [TheOdinProject/curriculum#22033]
Fix the typo in the following sentence (bolded):

It used to be that the **Aset** Pipeline handled all assets but since the inclusion of Webpack and the webpacker gem to give Webpack some Rails type conventions, it is now better practice to handle Javascript assets through there.

**Comment by AnimeshRy** [comment]
Could you link up the lesson or do the change yourself and add a PR.

**Comment by I3uckwheat** [comment]
@AnimeshRy Feel free to make the PR yourself! :)

**Comment by michpara** [comment]
Link to the lesson: https://www.theodinproject.com/courses/ruby-on-rails/lessons/the-asset-pipeline
