### ISSUE TITLE
404 URLs and link to newer, unvetted Ubuntu version

### ISSUE THREAD

**Issue by ZachBaird** [TheOdinProject/curriculum#22038]
The links in question are in Step 1 of the dual-booting section [here](https://github.com/ZachBaird/ZachBaird.github.io).

The 64-bit Ubuntu and Xubuntu iso downloads 404 and the first download link in the paragraph ends up linking to Ubuntu 20.

**Acceptance Criteria**:
- Find official URLs for the Ubuntu and Xubuntu iso files to replace the 404ed ones.

- Find an official download link for Ubuntu 18.

**Comment by UdokaVrede** [comment]
can I fix this?

**Comment by ZachBaird** [comment]
@UdokaVrede Go for it!

**Comment by UdokaVrede** [comment]
Hi, @ZachBaird I think there is a mix-up here, the link in "here" points to https://github.com/ZachBaird/ZachBaird.github.io. Please verify this.

**Comment by ZachBaird** [comment]
You're correct, I must have gone back in my clipboard too far. Thanks for catching this! The lesson is [here](https://theodinproject.com/courses/foundations/lessons/prerequisites).

**Comment by marvingay** [comment]
Fixed in #22062
