### ISSUE TITLE
Clarify prerequisites note about supporting other operating systems

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/curriculum#22040]
Lesson:
https://www.theodinproject.com/courses/foundations/lessons/prerequisites

Acceptance Criteria:
- Clarify the last line "If you feel you can contribute and support Windows at The Odin Project, please create a PR with Windows installation directions, and fixes for wherever the Windows commands might differ from Linux."
- Optional: Add that our Discord community will not support anything outside of these prerequisites.

**Comment by zachmmeyer** [comment]
I think with the PR closed, that means this issue can be closed as well. Do you agree @rlmoser99 ?

**Comment by rlmoser99** [comment]
Yes, totally. I just assumed it closed it automatically, but I should have checked.
