### ISSUE TITLE
JavaScript conclusion lesson not accurate

### ISSUE THREAD

**Issue by DoviMaj** [TheOdinProject/curriculum#22049]
The JS course conclusion lesson dosent make much sense for those on the Node path since JS is the first course, only on the Rails path its the last one before getting hired. [lesson](https://www.theodinproject.com/courses/javascript/lessons/conclusion)

Examples:
* _"You know Javascript works, how to build back-end using a framework of your choice, for example, Rails or NodeJS. "_ (the student wasnt exposed to Node yet.)
* _"Get a job, so someone else pays you to build."_ 
* _You’ve got all the tools you need to be a developer. And, really, the big secret is that you’ve been a web developer for a long time already._
* Most of the aditional resources are geared to the end of Ruby, building a portfolio and finding a job.
* _"We’ll be working on your HTML and CSS skills next, so get ready for that!"_ (not for those on the Ruby path)

Fix options: 
1) write conclusions for those on the Node path and have two JS conclusion lessons depending on the path the student is on.
2) write conclusions for those on the Node path and mention both conclusions in the same lesson.

**Comment by OptimBro** [comment]
+1

**Comment by sonali-dudekula** [comment]
@DoviMaj can I please work on this issue?

**Comment by twalton83** [comment]
Hello, DoviMaj is not a maintainer and cannot assign issues, however, I will discuss with the team how we would like to approach this and if they don’t want to work on this, you can take this issue.

**Comment by sonali-dudekula** [comment]
Thanks for letting me know @twalton83
