### ISSUE TITLE
Code in Event Manager lesson doesn't follow Ruby style guide.

### ISSUE THREAD

**Issue by cspablocortez** [TheOdinProject/curriculum#22058]
### Lesson: 
https://www.theodinproject.com/courses/ruby-programming/lessons/event-manager-ruby-programming

### Background:

The code written in the lesson for the Event Manager project could be rewritten to ensure that it follows the Ruby style guide, which is introduced in a previous lesson: https://www.theodinproject.com/courses/ruby-programming/lessons/object-oriented-programming-ruby-programming 

That previous lesson also recommends students to use rubocop, and when attempting the Event Manager lesson, the code raises the issues described below.

Currently, the code looks like this:

<img src="https://i.ibb.co/SQXt7MV/Screen-Shot-2021-01-02-at-4-20-01-AM.png">

breaking the Max Line Length [rule](https://rubystyle.guide/#max-line-length) and the Method Arguments Alignment [rule](https://rubystyle.guide/#no-double-indent) on [The Ruby Style Guide](https://rubystyle.guide/).

By changing the code to adhere to these rules, the code would be easier to read on smaller devices, as currently it displays horizontal scroll bars even on laptops (screenshot attached is from a 13" Macbook). 

Lastly, the method call on line 13 omits the use of parentheses, while the method call on line 20 includes them. The inconsistency could also be confusing to those following along. For more on consistency: [A note about Consistency](https://rubystyle.guide/#a-note-about-consistency).

This issue is present throughout the lesson, not just at the stage pictured above.

**Comment by rlmoser99** [comment]
@cspablocortez Thanks for taking the time to bringing this to our attention! Would you be interested in making these changes and submitting a PR?

**Comment by cspablocortez** [comment]
Absolutely, I'd love to work on this one

**Comment by cspablocortez** [comment]
Absolutely, I'd love to work on this one
