### ISSUE TITLE
Add Nested Arrays Section in Basic Ruby Lesson

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/curriculum#22051]
Lesson: https://www.theodinproject.com/courses/ruby-programming/lessons/arrays

Background: 

Students are often confused when they update one value in a 2D array and multiple values change. This happens when they create a create a 2D array similar to an example in our lesson, `Array.new(3, Array.new) #=> [[], [], []]`.

Currently, the lesson does not mention that the second optional argument populates the array with references to the same object. 

> Therefore, it is only recommended in cases when you need to instantiate arrays with natively immutable objects such as Symbols, numbers, true or false.
https://ruby-doc.org/core-2.7.0/Array.html

Acceptance Criteria:

In the "Creating Arrays" section:
- Remove this example: `Array.new(3, Array.new) #=> [[], [], []]`
- In your own words (using the documentation as a guide), explain why the second optional argument should only be used for natively immutable objects. 

Create a new section "Nested Arrays" at the end of the lesson
- In your own words (using the documentation as a guide), explain how to create a nested array that will not mutate.
- Show an example of creating a nested array without using a block, such as `Array.new(3, Array.new(3))`. Then update one value, for example `array[0][0] = 1` and reveal the updated value of the original array. 
- Show another example of creating a nested array using a block, such as `Array.new(3) {Array.new(3)}`. Then update one value, for example `array[0][0] = 1` and reveal the updated value of the original array.

**Comment by wise-king-sullyman** [comment]
I would love to work on this one.

**Comment by rlmoser99** [comment]
@wise-king-sullyman Thank you so much! Feel free to ping me if you have any questions.
