### ISSUE TITLE
Projects solutions at the end of the lessons don't show 10 most recent submissions.

### ISSUE THREAD

**Issue by buondevid** [TheOdinProject/curriculum#22054]
I've noticed that the projects "Solutions" section, at the end of the page, doesn't actually show the **10 most recent submissions**, e.g.:
- [Google Homepage](https://www.theodinproject.com/courses/foundations/lessons/html-css)
- [Rock, Paper and Scissors](https://www.theodinproject.com/courses/foundations/lessons/rock-paper-scissors)
- [Etch-a-Sketch](https://www.theodinproject.com/courses/foundations/lessons/etch-a-sketch-project)
- and so on...

I'd propose to put 2 views, shown together side by side, or alternative:
1. **Latest submission** (*for learners to get motivated and see their work on TOP*)
2. **Most voted** (*with 1-2 year caps, so the tech stays up to date, and learners can consult and inspect the best projects*)

Anyway if there's no time we can start just by correcting the ~"Showing the 10 most recent ones"~ into "Showing the 10 most voted ones", for the truth sake ⚖️ 
Thanks :smile:

**Comment by marvingay** [comment]
I realized this issue actually belongs in https://github.com/TheOdinProject/theodinproject , would you be able to re-post it over there?

**Comment by buondevid** [comment]
Done! Thanks
