### ISSUE TITLE
Remove reference to "destructuring assignment syntax" in JavaScript Path Lesson "Factory Functions and the Module Pattern"

### ISSUE THREAD

**Issue by jwern** [TheOdinProject/curriculum#22074]
In the JavaScript path - Organizing Your JavaScript Code - Lesson 4. Factory Functions and the Module Pattern: https://www.theodinproject.com/lessons/factory-functions-and-the-module-pattern#back-to-factory-functions

The second code example under the anchor linked above (directly under the sub-head "Inheritance with factories") uses an example with destructuring assignment syntax.  This syntax has not been explained or even introduced prior to being used in this example.  Because it's brand new, in a lesson already explaining a lot of new function formats, it makes it seem like it's an important part of object inheritance instead of simply a shorthand option.  

The line in question: **const {sayName} = Person(name)**
Recommend removing this syntax and using a more beginner-friendly format, like: **const sayName = Person(name).sayName**
Or adding a note explaining that this syntax is a shorthand, not a required standard.

**Comment by marvingay** [comment]
Given that we're out of our Foundations path at this point, while people are still novices, I don't believe it's appropriate to skimp out on syntax that will become critical later.

Your recommendation is valid though, using a destructuring assignment and when it's to be preferred is dependent on a few factors.

I think adding a note would be best. We will get that added.

**Comment by marvingay** [comment]
Upon re-reading the lesson material, we already have a comment pointing out what the syntax is, it should remain an exercise for the reader to look up if they feel inclined.

Closing.
