### ISSUE TITLE
MacOS Instructions for NVM installation are outdated.

### ISSUE THREAD

**Issue by xandora** [TheOdinProject/curriculum#22098]
Since [MacOS Catalina](https://support.apple.com/en-us/HT208050) (late 2019), Apple have moved to using zsh (Z Shell) by default over the bash shell.

However, our instructions still suggest that users modify their `~/.bash_profile` file. This file does not exist on Catalina.

Lesson should be updated to includes instructions on amending a `~/.zprofile or `~/.zshrc` file instead.

https://github.com/TheOdinProject/curriculum/blob/2638e9d3b95723c8ad812bb534d100f5dd1b793d/foundations/installations/installing_node.md#L46

**Comment by twalton83** [comment]
This is dupe of #21971, I never got to it though.

**Comment by xandora** [comment]
https://giphy.com/gifs/abcnetwork-modern-family-phil-dunphy-l3q2NboZyZSrDTM7S

**Comment by xandora** [comment]
Dupe of #21971
