### ISSUE TITLE
ESLint setup tutorial for VSCode triggers many 'deprecated' warnings

### ISSUE THREAD

**Issue by MaurizioTonelli** [TheOdinProject/curriculum#22096]
From this chapter of the Odin Project JS track: https://www.theodinproject.com/courses/javascript/lessons/linting

This tutorial is mentioned as a resource for configuring ESLint in your VSCode project: http://shripalsoni.com/blog/configure-eslint-in-visual-studio-code/

However, many 'deprecated' warnings appear while following it, I'll attach screenshots below:
<img width="647" alt="Captura de Pantalla 2021-01-13 a la(s) 22 56 22" src="https://user-images.githubusercontent.com/52333476/104546789-98446d80-55f2-11eb-920d-1c98e56f4894.png">
The user settings file shows the first warning

<img width="816" alt="Captura de Pantalla 2021-01-13 a la(s) 22 57 42" src="https://user-images.githubusercontent.com/52333476/104546879-c32ec180-55f2-11eb-93bd-3c8873b0f8d9.png">
The task.json file also features a deprecated version, when correcting the version as suggested, the following occurs: 
<img width="810" alt="Captura de Pantalla 2021-01-13 a la(s) 22 58 54" src="https://user-images.githubusercontent.com/52333476/104546951-f2453300-55f2-11eb-839a-50b28113ae3f.png">
More deprecated warnings

**Comment by ZachBaird** [comment]
Hey @MaurizioTonelli, it's been a bit but glad you brought this up.

We don't really have the bandwidth at the moment to identify a new resource. Are you open to finding an up-to-date tutorial? If so, I can assign this task to you and you can get started.

If not, or this task sits awhile longer, I think we'll close. While the deprecations are annoying, the tutorial is still effective at showing students how ESLint is setup.

**Comment by twalton83** [comment]
Closed by #22712
