### ISSUE TITLE
Deprecated Extension Suggested

### ISSUE THREAD

**Issue by Jorgelhus** [TheOdinProject/curriculum#22105]
In the [Text Editor's Page](https://www.theodinproject.com/courses/foundations/lessons/text-editors) is suggested the Live Server Extension. This extension, however, is being dropped by the maintainer. If there is someone in the community interested in picking it up, it's a good idea. If there isn't, maybe we should look for another extension that could fill its position before it becomes too outdated to be useful, and we have to do it in a hurry.

**Comment by xandora** [comment]
We're definitely open to all suggestions for improvements to the curriculum. Live-Server has been extremely useful, although a bit troublesome for some to get working correctly. On the other hand, the last commit to the latest release was about 2 years ago, and the extension is still working pretty well for the majority of users.
