### ISSUE TITLE
Push to Github

### ISSUE THREAD

**Issue by Derobos** [TheOdinProject/curriculum#22118]
Instructions to push to GitHub are currently:

**"Push Your Work to GitHub
Finally, let’s upload your work to the GitHub repository you created at the start of this tutorial.

Type git push origin main."**

This produced a "failed to push some refs" error for me.  Using "git push origin master" seemed to work.

**Comment by marvingay** [comment]
@Derobos  What lesson is this from?

Is your default branch on Git set to `main` as we instruct?

**Comment by Derobos** [comment]
My mistake, I missed the suggestion to rename it "main" during setup.  Thank you for the quick response.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by marvingay** [comment]
No worries, if it gives you further issues, do not hesitate to comment here.

For now, closing as this appears to be fixed.
