### ISSUE TITLE
Replace Rufus Guide

### ISSUE THREAD

**Issue by xandora** [TheOdinProject/curriculum#22129]
The Ubuntu.com guide linked in our dual booting lesson is out of date and has caused confusion on a number of occasions.

This should be replaced with a more up-to-date guide that includes screenshots from a more recent (preferably current) version of Rufus.

https://github.com/TheOdinProject/curriculum/blob/3a0668b03ad3b3db21ce533ceab939087be1ce5c/foundations/installations/prerequisites.md#L164

**Comment by ruben-vl** [comment]
Is this still an issue? I don't immediately see the problems with the ubuntu.com tutorial.

If so, this seems to be a recently updated [tutorial](https://itsfoss.com/create-live-usb-of-ubuntu-in-windows/)
It also mentions a second method with Universal USB Installer, which might be helpful for people experiencing problems with Rufus.

**Comment by xandora** [comment]
@ruben-vl The problem with the ubuntu.com guide is that it refers to a rather old version of Rufus, as such some of the instructions are no longer necessary.

Your link is a good alternative, do you want to create a PR and link it to this issue?

**Comment by ruben-vl** [comment]
You can find the PR in the refs above. I think that closes this issue. :)

**Comment by ZachBaird** [comment]
Merged!
