### ISSUE TITLE
Ubuntu link goes to 18.04.5 download when 20.04 LTS is available.

### ISSUE THREAD

**Issue by lrocampo** [TheOdinProject/curriculum#22125]
In the [Prerequisites page](https://www.theodinproject.com/courses/foundations/lessons/prerequisites), more precisely in the **Ubuntu/Windows Dual-Boot** section,  there is a link that goes to the Ubuntu 18.04.5 LTS download page when 20.04.1 LTS is available. 
In my humble opinion, the link should go to 20.04.1 LTS download page since is the latest LTS available.

**Comment by xandora** [comment]
18.04 is the release that was tested with TOP instructions. It is also still under support until sometime in 2023. Unless you have some good reasons as to why we should start suggesting 20.0 instead,, I think we can probably stick with 18.04 for the time being.
