### ISSUE TITLE
Fix typo in "Using git in the real world" lesson

### ISSUE THREAD

**Issue by MossValley** [TheOdinProject/curriculum#22136]
Just a typo in the section "A git workflow for open source contribution"; no space at "... website(check..."

![Screen Shot 2021-02-05 at 1 36 16 PM](https://user-images.githubusercontent.com/57896973/106973167-32916e80-67b7-11eb-865f-09daeefbc3b9.png)

I'm happy to solve this myself as I'm currently on this section, so I hope this is the right way to go about it.

**Comment by twalton83** [comment]
Go ahead and make the PR, we have a [contributing guide ](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md)!

**Comment by twalton83** [comment]
Closed with #22137
