### ISSUE TITLE
[Good First Issue] Two broken links in JavaScript conclusion section

### ISSUE THREAD

**Issue by ZaidKhan144** [TheOdinProject/curriculum#22153]
In the Additional Resources section of [JavaScript conclusion](https://www.theodinproject.com/courses/javascript/lessons/conclusion), there are two links that are broken.

- Front End Programming best practices from betterfrontend ([Link](http://findresultsonline.com/?_nozc_=1))
- D3 and other visualization tool examples ([Link](http://tributary.io/))

**Comment by Nathan-Galipeau** [comment]
If no one has taken this on yet, I'd love to, but are we looking to replace the deadlinks with the same resources, or would it be okay to find very similar, maybe more recent and updated resources?

**Comment by ZaidKhan144** [comment]
@Nathan-Galipeau I think it would be best to replace it with the same resources if they are discoverable, and if not, anyhow, you can reinstate with similar or updated ones.

**Comment by Nathan-Galipeau** [comment]
@ZaidKhan144 Do I need to be assigned in order to submit a PR? And okay, sounds good.

**Comment by Nathan-Galipeau** [comment]
I submitted a PR.

**Comment by ZaidKhan144** [comment]
@Nathan-Galipeau No, you can still submit a PR.

**Comment by ZaidKhan144** [comment]
@Nathan-Galipeau Glad to hear that. Maintainers will approve when they will see it.

**Comment by ZachBaird** [comment]
@ZaidKhan144 @Nathan-Galipeau Looks like the PR for this was merged but the issue wasn't closed, so I'll close it here. Great work guys!
