### ISSUE TITLE
Rock Paper Scissors game - add a reminder to plan before coding

### ISSUE THREAD

**Issue by Web-Dev-Rich** [TheOdinProject/curriculum#22179]
With regards: https://www.theodinproject.com/courses/foundations/lessons/rock-paper-scissors

This page encourages students to jump straight into coding in my opinion (that is what I initially did!).

Planning is implied, I guess, but I would like to add in a reminder for students to plan their code with pseudo-code before starting to code.

Many thanks.

**Comment by CatQueenCodes** [comment]
@Web-Dev-Rich It looks like we do: "Finally, this is your first JavaScript program built from scratch, so don’t forget the previous lesson on problem solving and plan your solution before writing any code." 

<img width="932" alt="Screen Shot 2021-03-07 at 12 35 39 PM" src="https://user-images.githubusercontent.com/59713017/110248977-b74fe380-7f41-11eb-9980-fa05f80186fa.png">

**Comment by Web-Dev-Rich** [comment]
Yep that was my PR 😃

**Comment by CatQueenCodes** [comment]
oh thanks! Next time link the issue in your pull request (if you didn't this time!) so we know to close the issue when we merge the pull request! Good addition!

**Comment by Web-Dev-Rich** [comment]
Oops apologies, will do. I'm new at this. Thanks.
