### ISSUE TITLE
Broken link Objects and Object Constructors section

### ISSUE THREAD

**Issue by es-rene99** [TheOdinProject/curriculum#22173]
Hello, I found a broken link on the Javascript curriclum: https://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/
![image](https://user-images.githubusercontent.com/43294836/109370555-6fa4ca00-7866-11eb-93ae-185f76f5d376.png)

I noticed this link had been restored previously (#22109) as it was working but now is no longer working anymore, I believe we should replace the link to the archive one like  @zachmmeyer mentioned. I can take care of this change just let me know.

**Comment by zachmmeyer** [comment]
Definitely submit the PR and I won't change it back next time haha.
