### ISSUE TITLE
Broken link on Common Data Structures & Algorithms (Ruby)

### ISSUE THREAD

**Issue by RJK-1** [TheOdinProject/curriculum#22181]
Link in bullet points 3 of assignments not functional. A google search of the article in question doesn't bring any direct results. Page possibly removed.

Article in question - Gentle Introduction to Algorithms for Web Developers

https://www.theodinproject.com/lessons/common-data-structures-and-algorithms

**Comment by rlmoser99** [comment]
Issue resolved in #22205
