### ISSUE TITLE
Broken link in Foundation Course, Intro to Git Lesson

### ISSUE THREAD

**Issue by smaylath** [TheOdinProject/curriculum#22193]
**Location**
Assignment section, Introduction to Git lesson, Foundations course 

**Issue**
First link in the section routes to a 500 error. Google search of the article leads to same result. 

**Reference Screenshot 1** 

![Screen Shot 2021-03-13 at 11 21 11 PM](https://user-images.githubusercontent.com/77697559/111058523-cc9ea380-8454-11eb-8737-2967c24b3c09.jpg)

**Reference Screenshot 2** 

![Screen Shot 2021-03-13 at 11 34 33 PM](https://user-images.githubusercontent.com/77697559/111058527-cf999400-8454-11eb-8c8a-9f24c61c14d9.jpg)

**Comment by twalton83** [comment]
Looks like they resolved the issue on their end, so it’s back online! Thanks for bringing this to our attention anyways!
