### ISSUE TITLE
Google Debugging Lesson is outdated

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#22202]
It looks like Google has recently made updates to this page: https://developer.chrome.com/docs/devtools/css/, and the instructions don't exactly align with the actual HTML from the page. 

We reference this tutorial in [this lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/developer-tools-2), and should include a note about the change but that students should still get familiar with the tools being used and follow along as best as they can with the elements present.

**Comment by Nathan-Galipeau** [comment]
I'd like to take this on, but just to clarify, is the main goal here to just to create a note within the lesson that explains the google page has been updated since the original lesson was created, but students should still utilize the resource in the way that the lesson outlines?

**Comment by twalton83** [comment]
Yes.

**Comment by Nathan-Galipeau** [comment]
Submitted.

**Comment by twalton83** [comment]
Closed with #22248
