### ISSUE TITLE
Update Chromebook guide to include git from source instructions

### ISSUE THREAD

**Issue by xandora** [TheOdinProject/curriculum#22207]
The Chromebook instructions don't mention that users will need to build git from source as the Linux Beta repository doesn't include a sufficiently high enough version of git and there is no ability to add the git ppa repository.

Requirements for completion:
- [ ] Update the [Prerequisites](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/prerequisites) lesson to include informing Chrome OS/CloudReady users to install Git from source with instructions at this Digital Ocean [tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-git-on-debian-10#installing-git-from-source).

**Comment by Nathan-Galipeau** [comment]
Has this been completed yet?

**Comment by xandora** [comment]
@Nathan-Galipeau Not yet. I've been busy. If you want to take a shot at it, I can chuck it your way.

**Comment by Nathan-Galipeau** [comment]
Sounds good, please assign when you get the chance, thanks

**Comment by xandora** [comment]
@Nathan-Galipeau It's all yours.

**Comment by Nathan-Galipeau** [comment]
PR submitted

**Comment by xandora** [comment]
Fixed under #22266
