### ISSUE TITLE
Update discord invite link

### ISSUE THREAD

**Issue by CatQueenCodes** [TheOdinProject/curriculum#22216]
Currently our Discord community invite link lands users on the #rules channel. Due to the recent change to use Discord's membership screening feature (where users are exposed to the rules before agreeing to join), it's more sensible to have them land on the #faq channel upon joining.  The new invite code (which can be appended  to the base discord invite link already there) is: fbFCkYabZB

The link needs to be updated in the following locations: 

https://github.com/TheOdinProject/curriculum/blob/60c421183d9a02c031b6c18aed94959e5ad4d586/README.md

https://github.com/TheOdinProject/curriculum/blob/e8d0c65881e151acc9bc55cd4614c1f65779c580/getting_hired/conclusion.md

https://github.com/TheOdinProject/curriculum/blob/6c0732d25390a2df3bddef4e186dfc839beb7d27/foundations/introduction/join_the_odin_community.md

https://github.com/TheOdinProject/curriculum/blob/5bab95177673ed7d31eb3b2373529650d9c3c8a9/foundations/installations/installation_overview.md

https://github.com/TheOdinProject/curriculum/blob/60c421183d9a02c031b6c18aed94959e5ad4d586/rails_programming/introduction/installing_rails.md

https://github.com/TheOdinProject/curriculum/blob/d3ccd32a5313002fe1cacb075e08f09d1e1fa92d/foundations/installations/setting_up_git.md

https://github.com/TheOdinProject/curriculum/blob/b37ce75dbca4350db7460b9db1f44ebff9ee6daf/ruby_programming/testing_with_rspec/introduction_to_rspec.md

https://github.com/TheOdinProject/curriculum/blob/0a6bd1494fc3800fa73dcfabcf1a7848a4f6ddd4/foundations/introduction/motivation_and_mindset.md

Make sure you link your pull request to this issue (over on the right side ----->)

**Comment by timjacksonm** [comment]
I am willing to take this on.
