### ISSUE TITLE
Xubuntu 20.10

### ISSUE THREAD

**Issue by curt4207** [TheOdinProject/curriculum#22220]
Ubuntu's 20.10 update ,removed a lot of the programs I had installed & lowered display resolution to a max in the low 720's .i searched online and tried all the commands that people advised ,none worked so i found Grub Customizer  . It helped me revert back to the previous version of [Ubuntu ,with Linux 5.4.0-66-generic] with all the installed programs  .

**Comment by bycdiaz** [comment]
@curt4207 I'm not really sure what this issue is meant to flag for us.

In your lesson, we invite learners to install the 18.04 version of Xubuntu. Was there a place in our curriculum that directed you to install 20.10?

**Comment by bycdiaz** [comment]
@curt4207 I'm closing the issue. If you'd like to propose a change to the curriculum in the future, please feel free to do so by creating an issue or submitting a pull request with an update.
