### ISSUE TITLE
Clarify Restaurant Project Instructions

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#22242]
Because many students overlook that Tabsy should be taken as visual representation, we need to make it clear that students should not be installing the package and only take visual and behavioral inspiration. Alternatively, we should just consider pointing to the behavior of a student submission instead of sending them to an NPM package.

**Comment by Nathan-Galipeau** [comment]
@twalton83 This seems like a good beginner issue, is it okay if I submit a potential PR that might make this more clear?
