### ISSUE TITLE
Update Foundation Lessons with Knowledge Checks

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/curriculum#22259]
Background: Only some of the Foundation Lessons that have Learning Outcomes also have a section at the end of the lesson called Knowledge Checks. These knowledge checks can be very beneficial to students, therefore let's make all of the lessons that have Learning Outcomes also have Knowledge Checks.

Suggestions:
Ten of the Foundation lessons need to have a Knowledge Check section added. For reference, here is an example of a Foundation lesson with Learning Outcomes & Knowledge Check section:
https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/problem-solving

There is a **possible exception** to the above pattern for two of the lessons. They have a Learning Outcomes section that is a combination of an older style of Knowledge Check. These two lessons can be updated to follow the above pattern or can follow the older style in the following lesson:
https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101

Acceptance Criteria:
- [x] How Does the Web Work? (**possible exception**) -> _Assigned to @dylan-workhub_
- [x] Practicing Git Basics -> _Assigned to @dylan-workhub_
- [x] Introduction to the Front End -> _Assigned to @jaredmez_
- [x] HTML and CSS Basics -> _Assigned to @aaron-kidwell_
- [x] Developer Tools -> _Assigned to @dylan-workhub_
- [x] Fundamentals Part 1 -> _Assigned to @MC-Rawlings_
- [x] Fundamentals Part 2 -> _Assigned to @thatblindgeye_
- [x] DOM Manipulation (**possible exception**)  -> _Assigned to @dylan-workhub_
- [x] Introduction to Back End -> _Assigned to @aayushmau5_ 
- [x] Introduction to Frameworks -> _Assigned to @aayushmau5_ 

Lesson Assignments:
Before working on a lesson, please comment on this issue indicating what lesson(s) you would like to work on and review our contributing guide. 
https://github.com/TheOdinProject/curriculum/wiki/Contributing-Guide

**Comment by aayushmau5** [comment]
I'm interested to work on this.

**Comment by dylan-workhub** [comment]
I can take a crack at `Practicing Git Basics`.

**Comment by Henry-Cantrell** [comment]
I'd be happy to take on `HTML and CSS basics`.

**Comment by dylan-workhub** [comment]
If you'd like, I can also do `Developer Tools` tomorrow.

**Comment by jaredmez** [comment]
I'd like to tackle Introduction to the Front End

**Comment by MC-Rawlings** [comment]
I'd like to take on Fundamentals 1

**Comment by dylan-workhub** [comment]
I can take `How Does the Web Work?` tomorrow. Just wondering, if I were to update it to match the current style, would I also be updating the Learning Outcomes so that they aren't a drop down, or would I leave those and only update the Knowledge Checks?

**Comment by rlmoser99** [comment]
@dylan-workhub Yes, you will need to update the Learning Outcomes so that they are not a drop down, whether you decide to go with the newer style or the previous style for the Knowledge Check.

**Comment by dylan-workhub** [comment]
> @dylan-workhub Yes, you will need to update the Learning Outcomes so that they are not a drop down, whether you decide to go with the newer style or the previous style for the Knowledge Check. 

Cool, I can do that later today in that case.

**Comment by thatblindgeye** [comment]
Since I'm taking a little more time to properly understand React before continuing onto a project, I can try and tackle the Fundamentals Part 2 by early-mid this week (if you need it done sooner just let me know).

**Comment by rlmoser99** [comment]
@thatblindgeye That timeline will be just fine! Thanks for letting me know!!

**Comment by dylan-workhub** [comment]
I can take DOM Manipulation, though it may take me a couple of days this time!

**Comment by aaron-kidwell** [comment]
Is it too late to jump on Git basics or HTML/CSS section? Thanks

**Comment by rlmoser99** [comment]
@aaron-kidwell All of the lessons for this issue have been claimed, but I am not 100% sure if that is what you are asking.

**Comment by aaron-kidwell** [comment]
> @aaron-kidwell All of the lessons for this issue have been claimed, but I am not 100% sure if that is what you are asking.

Yep that's what I was asking, thanks!

**Comment by Noah670** [comment]
Awesome

**Comment by harshetmaruff** [comment]
Hi Everyone, #22279 This is my pull request to Foundation Github Basics, I added only one knowledge check and only one commit

**Comment by Henry-Cantrell** [comment]
Hey, you can reassign my portion to @aaron-kidwell if you'd like. Unsure of when I'm going to be able to start work, got sidetracked with stuff.

**Comment by rlmoser99** [comment]
@Henry-Cantrell Thanks for letting me know! 

@aaron-kidwell Are you still interested in helping with this issue for the HTML/CSS Basics lesson, or should I open it up to others?

**Comment by aaron-kidwell** [comment]
@rlmoser99 I would love to give it a shot yes!

**Comment by siduck76** [comment]
I have found a link to promises tutorial which no longer works. I get this error 
![image](https://user-images.githubusercontent.com/59060246/116852714-71965b00-ac12-11eb-8ad9-b38a1ecc6f3b.png)

It has been referenced here https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/async , first link . https://davidwalsh.name/promises

**Comment by rlmoser99** [comment]
@siduck76 You should make a new issue. The problem that you are experiencing does not have anything to do this issue.
