### ISSUE TITLE
Clarify Practicing Git Basics Example

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#22254]
Often students are worried by the warning that the upstream does not exist. This is not an error, but a feature. We should add a quick explanation that what they see may differ slightly, but that this message is not indicative of an error or that they've done something wrong, and what it means. 

https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/practicing-git-basics

**Comment by twalton83** [comment]
@wise-king-sullyman

**Comment by wise-king-sullyman** [comment]
@twalton83 my apologies I hadn't noticed that you'd posted this. If you're wanting me to take this so that I can do another screenshot and keep it consistent with my previously submitted screenshots I'll be more than happy to.
