### ISSUE TITLE
Git Authentication Via Password Will Be Depreciated

### ISSUE THREAD

**Issue by tornadodobird** [TheOdinProject/curriculum#22312]
Hi tOP,

So far I'm enjoying the Odin Project's course! I'm learning a lot and its coming easliy.

In the "Foundations" course (and throughout other courses I am sure), you teach learners how to set up an SSH key with GitHub and show how to authenticate with a password.

Shortly after doing some basic Git commits and pushes through the CLI with a basic repository of mine, I was emailed with this notice:

> You recently used a password to access the repository at tornadodobird/Wallpapers with git using git/2.31.1.

> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

I am not sure how much this will affect the instructions for the Foundations course, but I assume it may need to be slightly tweaked and changed. I'm creating this issue to let you know so tOP can fix any outdated information, and won't confuse any early learners (like me - I will probably need help getting the new requirements set up).

**Comment by twalton83** [comment]
This means you use HTTPS, not SSH.
