### ISSUE TITLE
Suggestion for getting students to get more acquianted with git workflows

### ISSUE THREAD

**Issue by bokonist** [TheOdinProject/curriculum#22313]
At various points in the curriculum, students are asked to revisit older projects and refactor them with something that they've just learned in the course. These points can be a great place to suggest that students use a new git branch in their repository to work on their new 'features' and merge them back into master.

From a cursory find command, these are the lessons in the curriculum that suggests going back to an older project to refactor/rewrite. Apologies if I've missed any

- **_foundations/javascript_basics/DOM-manipulation.md:_** Student is asked to revisit the RPS game to add a simple UI.
- **_javascript/organizing-js/classes.md :_** Asked to rewrite it using class instead of plain constructors.
- **_javascript/js-in-the-real-world :_** Asked to revist the library project to add form validation
- **_javascript/js-rails/rails_backend.md :_** Students are asked to go back to a previous project and try to integrate firebase.
- **_javascript/react-js/hooks.md :_** Asked to go back to CV project for a rewrite with hooks.
- **_nodeJS/authentication/Security-configuration.md :_** Asked to revisit older porjects to secure them with dotenv
- **_nodeJS/express-basics/Express-Introduction.md :_** Asked to rewrite the first node project with express
- **_ruby_programming/object_oriented_programming_basics/project-mastermind.md :_** Asked to refactor the code for humans to have the option to be creator or guessor.

**Comment by rlmoser99** [comment]
I'm not sure about the javascript ones, but the ruby Mastermind refactor is during the initial project & is not being asked to revisit an old project.

One lesson that ruby does have students revisit is their caesar_cipher and tic_tac_toe project when they learn testing in this lesson: ruby_programming/testing_with_rspec/project_testing_your_ruby_code.md

**Comment by bokonist** [comment]
Thanks Rachel! I'm wasn't familiar with the ruby track, I'll add the suggestion there too!

**Comment by ZachBaird** [comment]
It looks like this task may be complete. Can @bokonist or @rlmoser99 confirm?

**Comment by bokonist** [comment]
yep, @ZachBaird , complete under [this PR](https://github.com/TheOdinProject/curriculum/pull/22320#event-4940667692)
