### ISSUE TITLE
Remove Drop Down functionality from Knowledge Checks

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/curriculum#22322]
**Before working on a lesson, please comment on this issue indicating what lesson that you would like to work on and wait to be assigned. In addition, please review our contributing guide:**
https://github.com/TheOdinProject/curriculum/wiki/Contributing-Guide

Background: 
There are 3 lessons in the beginning of Foundations that have Knowledge Checks with drop down functionality. We recently added 10 more knowledge checks to lessons in Foundations, using a new format that does not use drop downs. Because of these two differing formats, students occasionally report that these new knowledge checks do not work correctly. 

The drop downs made it too easy for students to just use the drop down and not think through the question, so we have implemented a new format that instructs them to review the lesson if they can not answer a question. 

For each of the following lessons:
* Update the wording to "This section contains questions for you to check your understanding of this lesson. If you’re having trouble answering the questions below on your own, review the material above to find the answer."
* Remove the drop down functionality from the Knowledge Checks, but keep the current questions.

Use the following lesson as a pattern to follow:
https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/problem-solving

Acceptance Criteria:
- [x] Command Line Basics -> Assigned to @dylan-workhub 
- [x] Introduction to Git -> Assigned to @mdlugosz1
- [x] Git Basics -> Assigned to @7u1ian

**Comment by 7u1ian** [comment]
I'd like to tackle one of these please! By the way, is the acceptance criteria a list of which lessons need updating?

**Comment by rlmoser99** [comment]
@7u1ian Yes, the lessons are listed in the acceptance criteria. Which one do you want to do?

**Comment by 7u1ian** [comment]
> @7u1ian Yes, the lessons are listed in the acceptance criteria. Which one do you want to do?

Git Basics please. Thank you!

**Comment by dylan-workhub** [comment]
I can take command line basics.

**Comment by mdlugosz1** [comment]
I can work on introduction to git.

**Comment by 7u1ian** [comment]
That was my first contribution. Let me know if everything went smoothly! By the way, is my name supposed to be assigned next to the item under Acceptance Criteria?

**Comment by rlmoser99** [comment]
> That was my first contribution. Let me know if everything went smoothly! By the way, is my name supposed to be assigned next to the item under Acceptance Criteria?

Yes, it was. Sorry about that. I've fixed it. I'm not sure why/how that happened.
