### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by agentlemanthief** [TheOdinProject/curriculum#22358]
### Description
Typo on following page:

https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/your-first-rails-application-ruby-on-rails

"First, open GitHub.com in your browser and sign in (if you aren’t already). Next, look for your profile picture in the upper right-hand corner, click the “+” symbol next to it, and then click New repository. Give the repository a name (maybe my_first_rails_app?), and make sure you do not initialise the repository with a README and Rails created one already. Click Create Repository."

@ line "README and Rails created one already" should read "README as Rails created one already" or "README because Rails created one already"?

#### Steps to Reproduce
<!-- What steps need to be taken in order to reproduce this bug?

Example:
1. Log in
2. Visit the lesson page: Installing Rails @ https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/your-first-rails-application-ruby-on-rails
4. The typo is in the section with heading: Step 2.3: Connect the Local Repository to the Remote Repository

#### Expected Behaviour
Typo 'and' should read 'as' or 'because'?

**Comment by twalton83** [comment]
Also, didn't realize this at first, curriculum issues belong in the curriculum repo, the other repo is for the website itself! Thanks!

**Comment by agentlemanthief** [comment]
Yeah, thanks, still working it all out! Took me a second to notice the content is separate.

**Comment by wise-king-sullyman** [comment]
Closed in #22356
