### ISSUE TITLE
Non-working code in Ruby Basic Enumerables lesson

### ISSUE THREAD

**Issue by JoshTheBlack** [TheOdinProject/curriculum#22369]
https://github.com/TheOdinProject/curriculum/blob/main/ruby_programming/basic_ruby/basic_enumerable_methods.md

The first code block in this lesson has code that doesn't work in Ruby 2.7.2 (the version referenced in the installation lesson.)

```
friends = ['Sharon', 'Leo', 'Leila', 'Brian', 'Arun']
invited_list = []

for friend in friends do
  if friend != 'Brian'
  invited_list.push(friend)
  end
end

invited_list #=> ["Sharon", "Leo", "Leila", "Arun"]
```

Removing the 'do' allows the code to run properly.

```
friends = ['Sharon', 'Leo', 'Leila', 'Brian', 'Arun']
invited_list = []

for friend in friends
  if friend != 'Brian'
  invited_list.push(friend)
  end
end

invited_list #=> ["Sharon", "Leo", "Leila", "Arun"]
```

My current installed version of Ruby is 2.7.2p137 (2020-10-01 revision 5445e04352).

**Comment by JoshTheBlack** [comment]
Stranger still, 

```
invited_list = []

for friend in ['Sharon', 'Leo', 'Leila', 'Brian', 'Arun']
  if friend != 'Brian'
  invited_list.push(friend)
  end
end

invited_list #=> ["Sharon", "Leo", "Leila", "Arun"]
```

This works.  Maybe its an issue with Ruby 2.7.2p137?

**Comment by RolandStuder** [comment]
Just a note, this issue has come up twice in the last three weeks:

- https://discord.com/channels/505093832157691914/543074220691947531/852578738029854753
- https://discord.com/channels/505093832157691914/543074220691947531/859809842125471775
