### ISSUE TITLE
Redundant link

### ISSUE THREAD

**Issue by Wdavery** [TheOdinProject/curriculum#22462]
Similar to my last pull request (#22452), I've come across two links that introduce the same article as new. This time it's a little more complex than a simple one line removal so I figured opening an issue would be a better choice.

The offending link is: https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603

First instance is a required reading assignment and was added 13 days ago here:  
https://github.com/TheOdinProject/curriculum/blob/d123ae89af9b7a4bc49143ea3a2d01490357c67e/foundations/introduction/asking_for_help.md#assignment

Second instance was added 6 months ago here:
https://github.com/TheOdinProject/curriculum/blob/e53fbdc8b6ffb1782f459f3d4dd6273a7a18e558/foundations/introduction/join_the_odin_community.md#an-important-read

I'd be inclined to scrap the second instance in favour of the required reading, but there is more of an explanation/summary there so I didn't want to remove that entirely without input from others.

**Comment by twalton83** [comment]
We definitely want to keep it in the “Asking for Help” lesson as that lesson will be a frequent resource in our Discord chat, and serve as a reference for all of our most common “getting help” resources. I’m more inclined to remove it from the second link.

**Comment by Wdavery** [comment]
If removed from the second link, a small rewording will be required here: https://github.com/TheOdinProject/curriculum/blob/d123ae89af9b7a4bc49143ea3a2d01490357c67e/foundations/introduction/join_the_odin_community.md#6-ask-for-clarifications

**Comment by twalton83** [comment]
We can just remove the “referenced above” part in that case.

**Comment by Wdavery** [comment]
I'll go ahead and create PR with those changes then :+1:
