### ISSUE TITLE
Add missing Knowledge Checks, Lesson Outcomes, and Knowledge Check links to Foundations

### ISSUE THREAD

**Issue by ZachBaird** [TheOdinProject/curriculum#22466]
Related to #16074 

This task is to go through the following lessons in the [Foundations](https://www.theodinproject.com/paths/foundations/courses/foundations) course and:

- Add missing Learning Outcomes
- Add missing Knowledge Checks
- add answer links in the Knowledge Checks

Below I've created a list of the courses we will need to work on and what they need. Most just need answer links created.

Answer links are a suggestion we'd like to sneak in while we do this work. The problem with Knowledge Checks is that it can be difficult to know if you're actually right. Some Knowledge Checks used to behave like dropdowns with the answer underneath. While convenient, that introduced its own issues. The proposed idea is to have a Knowledge Check be an `a` tag that links to the relevant lesson content so a student can check their answer. If the answer is in an external resource we link (ie. something in Additional Resources), we can just link to that. If the answer is in the Odin lesson content directly, you can link to it like so:

```html
Lorem ipsum dolor sit amet, <span id="js-function-knowledge-check">consectetur adipiscing elit</span>, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to the page where the span with this id lives -->
<li><a class="knowledge-check-link" href="#js-function-knowledge-check">How do you return a value from a function?</a></li>
```

**Acceptance Criteria**
In order for this task to be closed, all of these lessons should have Learning Outcomes, Knowledge Checks, and the Knowledge Checks should be able to link to their answers wherever it is in the lesson (or external resources).
The Knowledge Checks styling should **not** change. I will create a separate task to address this in [the site's repo](https://github.com/TheOdinProject/theodinproject).

I recommend creating a PR as each section is completed so that review is easier. It's also encouraged for people to share this task, but they need to leave a comment on what section they're taking so no double work is done.

**Introduction**
- [x] Asking For Help (add links)
- [x] How Does the Web Work? (add links)

**Git Basics**
- [x] Introduction to Git (add links)
- [x] Git Basics (add links)

**The Front End**
- [ ] Introduction to the Front End (add links)
- [ ] HTML and CSS Basics (add links)
- [ ] Developer Tools (add links)

**JavaScript Basics**
- [x] Fundamentals Part 1 (add links)
- [x] Fundamentals Part 2 (add links)
- [x] Developer Tools 2 (Learning Outcomes, Knowledge Checks, add links)
- [x] Fundamentals Part 3 (Learning Outcomes, Knowledge Checks, add links)
- [x] Problem Solving (add links)
- [x] Understanding Errors (add links)
- [x] Clean Code (Learning Outcomes, Knowledge Checks, add links)
- [x] Fundamentals Part 4 (Learning Outcomes, Knowledge Checks, add links)
- [x] DOM Manipulation (add links)
- [x] Fundamentals Part 5 (Learning Outcomes, Knowledge Checks, add links)

**The Back End**
- [x] Introduction to the Back End (add links)
- [x] Introduction to Frameworks (add links)

**Comment by mgrigoriev8109** [comment]
I'd love to tackle the first two tasks of this issue. So adding links to the Introduction section - 'Asking for help' and 'How does the web work?'.

**Comment by Maheshkumar-novice** [comment]
May I know how to do this? Like where to edit the HTML.

**Comment by Maheshkumar-novice** [comment]
I will add links for Introduction to Git

**Comment by BLooDBRothER** [comment]
I'll make changes for the lessons
- Introduction to the Front End (add links)
-  HTML and CSS Basics (add links)

**Comment by Jayashakthi28** [comment]
I'll add links to the lessons

- Fundamentals Part 2 (add links)
- Problem Solving (add links)

**Comment by Lakshmikant-2001** [comment]
I'll add links to the lessons

      Developer Tools (add links)
      Fundamentals Part 1 (add links)

**Comment by Jayashakthi28** [comment]
I'll add links to the lessons

- Fundamentals Part 2 (add links)
- Problem Solving (add links)

**Comment by LeoKirasic** [comment]
I would like to work on Developer Tools 2 (Learning Outcomes, Knowledge Checks, add links).

**Comment by LeoKirasic** [comment]
I will start working on:
- Fundamentals Part 3 (Learning Outcomes, Knowledge Checks, add links)
- Understanding Errors (add links)
- Clean Code (Learning Outcomes, Knowledge Checks, add links)

**Comment by LeoKirasic** [comment]
I will start working on:
- Fundamentals Part 4 (Learning Outcomes, Knowledge Checks, add links)
- DOM Manipulation (add links)
- Fundamentals Part 5 (Learning Outcomes, Knowledge Checks, add links)

**Comment by Maheshkumar-novice** [comment]
> I will start working on:
> 
> * Fundamentals Part 4 (Learning Outcomes, Knowledge Checks, add links)
> * DOM Manipulation (add links)
> * Fundamentals Part 5 (Learning Outcomes, Knowledge Checks, add links)

Hey Leo! Don't forget to add `class="knowledge-check-link"` to `<a>` tag.

**Comment by LeoKirasic** [comment]
I will start working on:
- Introduction to the Back End (add links)
- Introduction to Frameworks (add links)

**Comment by twalton83** [comment]
@Lakshmikant-2001 @BLooDBRothER @mgrigoriev8109 and @Maheshkumar-novice, did we get all of our sections done? If so, can you please update your closed PRs to reference this issue so they can be listed such as above?

**Comment by Maheshkumar-novice** [comment]
> @Lakshmikant-2001 @BLooDBRothER @mgrigoriev8109 and @Maheshkumar-novice, did we get all of our sections done? If so, can you please update your closed PRs to reference this issue so they can be listed such as above?

I got introduction to git done and referenced it. I fill finish git basics soon.

**Comment by BLooDBRothER** [comment]
> @Lakshmikant-2001 @BLooDBRothER @mgrigoriev8109 and @Maheshkumar-novice, did we get all of our sections done? If so, can you please update your closed PRs to reference this issue so they can be listed such as above? 

I'm half way done and notify you asap.

**Comment by Jayashakthi28** [comment]
> @Lakshmikant-2001 @BLooDBRothER @mgrigoriev8109 and @Maheshkumar-novice, did we get all of our sections done? If so, can you please update your closed PRs to reference this issue so they can be listed such as above?

I am Half way done..I will notify asap.

**Comment by BLooDBRothER** [comment]
@twalton83  What about the newly added lessons in the foundations.

**Comment by twalton83** [comment]
That needs to be broken out into a separate ticket.

**Comment by twalton83** [comment]
@Lakshmikant-2001 any update?

**Comment by Lakshmikant-2001** [comment]
> @Lakshmikant-2001 any update?

I will finish within today!!

**Comment by wise-king-sullyman** [comment]
We are moving to independent issues for each lesson needing this work going forward.
