### ISSUE TITLE
Broken Link on Foundations > Project: Google Homepage

### ISSUE THREAD

**Issue by bilalmaleq** [TheOdinProject/curriculum#22465]
### Description

The "Project: Git Basics" under the "[Setting Up Your Project’s GitHub Repository (optional)](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-css#setting-up-your-projects-github-repository-optional)" section leads to a broken page on the "Project: Google Homepage"

#### Steps to Reproduce

1. Navigate to https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-css
2. Find the "Project: Git Basics" link under the "Setting Up Your Project's GitHub Repository (optional)" section 
3. Click on the link and it appears to be a broken link i.e: https://www.theodinproject.com/courses/foundations/lessons/practicing-git-basics

#### Expected Behaviour

It should lead to the relevant Project page.

 #### Additional Information

I found this while going through the lesson. I am using my GitHub account to log into the Odin project.

**Comment by twalton83** [comment]
Feel free to make a pull request to resolve this by clicking on the "Improve this lesson" button at the bottom of the page. https://discord.com/channels/505093832157691914/516751477306294273/867171810251243520

**Comment by ZachBaird** [comment]
Thanks for the heads up @bilalmaleq , this was a fallout from an earlier task we did. Should be fixed now!
