### ISSUE TITLE
Add VS Code tutorial

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#22478]
The official VSC tutorial should be added to one of the existing lessons so students have a better understanding of the environment they have set up.

**Comment by ruben-vl** [comment]
Where would be a good place to add it in your opinion? I have done the foundations course in the past couple of days and the simple instructions given throughout have been more than enough. Also, students are not obliged to use VSCode, but can use another IDE/text editor. The tutorial certainly has its merits in 'additional resources', but I don't see the need for it in the obligated readings.

**Comment by twalton83** [comment]
We expect students to be follow our suggestions, so we expect VSC regardless of what they choose. Similarly, we expect students to use Chrome, and a lot of Chrome content is required.

Unfortunately, we do get a lot of students stuck on even understanding how to open a file. This would probably go in the Text Editors lesson.

**Comment by mgrigoriev8109** [comment]
Not sure if @ruben-vl  was interested in doing this, but if not then I'd like to add it to that Lesson.

**Comment by ruben-vl** [comment]
@mgrigoriev8109 go ahead! I was not planning on doing it

**Comment by twalton83** [comment]
Closed by #22499
