### ISSUE TITLE
Add missing Knowledge Checks, Learning Outcomes & answer-links to JavaScript

### ISSUE THREAD

**Issue by ZachBaird** [TheOdinProject/curriculum#22472]
Related to #16074 

This task is to go through the following lessons in the [JavaScript](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/javascript) course and:

- Add missing Learning Outcomes
- Add missing Knowledge Checks
- add answer links in the Knowledge Checks

Below I've created a list of the courses we will need to work on and what they need. Most just need answer links created.

Answer links are a suggestion we'd like to sneak in while we do this work. The problem with Knowledge Checks is that it can be difficult to know if you're actually right. Some Knowledge Checks used to behave like dropdowns with the answer underneath. While convenient, that introduced its own issues. The proposed idea is to have a Knowledge Check be an `a` tag that links to the relevant lesson content so a student can check their answer. If the answer is in an external resource we link (ie. something in Additional Resources), we can just link to that. If the answer is in the Odin lesson content directly, you can link to it like so:

```html
Lorem ipsum dolor sit amet, <span id="js-function-knowledge-check">consectetur adipiscing elit</span>, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to the page where the span with this id lives -->
<li><a class="knowledge-check-link" href="#js-function-knowledge-check">How do you return a value from a function?</a></li>
```

**Acceptance Criteria**
In order for this task to be closed, all of these lessons should have Learning Outcomes, Knowledge Checks, and the Knowledge Checks should be able to link to their answers wherever it is in the lesson (or external resources).
The Knowledge Checks styling should **not** change. I will create a separate task to address this in [the site's repo](https://github.com/TheOdinProject/theodinproject).

I recommend creating a PR as each section is completed so that review is easier. It's also encouraged for people to share this task, but they need to leave a comment on what section they're taking so no double work is done.

**Organizing your JavaScript Code**
- [x] Objects and Object Constructors (Knowledge Checks, add links)
- [x] Factory Functions and the Module Pattern (Knowledge Checks, add links)
- [x] Classes (Knowledge Checks, add links)
- [x] ES6 Modules (Knowledge Checks, add links)
- [x] Webpack (Learning Outcomes, Knowledge Checks, add links)
- [ ] OOP Principles (Knowledge Checks, add links)

**JavaScript in the Real World**
- [x] Linting (Learning Outcomes, Knowledge Checks, add links)
- [ ] Dynamic User Interface Interactions (Learning Outcomes, Knowledge Checks, add links)
- [ ] Forms (Learning Outcomes, Knowledge Checks, add links)

**Asynchronous JavaScript and APIs**
- [x] Async (Knowledge Checks, add links)
- [x] Working with APIs (Learning Outcomes, Knowledge Checks, add links)
- [x] Async and Await (Knowledge Checks, add links)

**React JS**
- [x] React Introduction (Knowledge Checks, add links)
- [x] State and Props (Knowledge Checks, add links)
- [ ] Handle Inputs and Render Lists (Knowledge Checks, add links)
- [ ] Lifecycle Methods (Knowledge Checks, add links)
- [ ] Hooks (Learning Outcomes, Knowledge Checks, add links)
- [ ] Router (Learning Outcomes, Knowledge Checks, add links)
- [ ] Advanced Concepts (Learning Outcomes, Knowledge Checks, add links)

**Testing JavaScript**
- [ ] Testing Basics (Learning Outcomes, Knowledge Checks, add links)
- [ ] More Testing (Learning Outcomes, Knowledge Checks, add links)

**JavaScript and the Backend**
- [ ] Using Ruby on Rails or BaaS For Your Back End (Knowledge Checks, add links)

**Comment by jtcaovan** [comment]
Hi, I would like to work on the first 3 sections in Organizing your Javascript code (Objects and Object Constructors, Factory Functions and the Module Pattern, Classes)

**Comment by jtcaovan** [comment]
I'll go ahead and continue off with ES6 Modules and OOP Principles

**Comment by digidub** [comment]
I'll start by taking the Async lesson. 

Having looked at the lesson, I think the Learning Outcomes could do with a reformat, they are currently worded in a Knowledge Check style (see here: https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/async#learning-outcomes)

**Comment by roshaan005** [comment]
I want to work on the testing portion : testing basics and more testing

**Comment by roshaan005** [comment]
Could I work on the testing portion? 
1. testing basics
2. More testing

**Comment by LeoKirasic** [comment]
I'll start working on:
- Webpack (Learning Outcomes, Knowledge Checks, add links)
- Linting (Learning Outcomes, Knowledge Checks, add links)

**Comment by twalton83** [comment]
@roshaan005 Go ahead if you haven't already started.

@digidub Any updates?

**Comment by digidub** [comment]
@twalton83 PR submitted.

**Comment by digidub** [comment]
I'll also take on the rest of the **Asynchronous JavaScript and APIs** section.

**Comment by digidub** [comment]
I'll work through the **React JS** section next.

**Comment by LeoKirasic** [comment]
I'll start working on:

- Dynamic User Interface Interactions (Learning Outcomes, Knowledge Checks, add links)
- Forms (Learning Outcomes, Knowledge Checks, add links)

**Comment by wise-king-sullyman** [comment]
@jtcaovan @digidub @LeoKirasic @roshaan005 to make this more manageable I have created standalone issues for each lesson and this issue will be getting closed momentarily.

If you've *already* started work on a lesson please comment on the issue for it and let me know. If you haven't started but would like to, just comment on that issue and request it be assigned to you if it's still available.

If you're currently *actively working on* multiple lessons please comment on all of them, but know that going forward we want each contributor to only to have **one** Learning Outcome/Knowledge Check issue assigned to them at any given time. Once the PR for the issue you're assigned has been merged you can comment on a new one to request it be assigned to you.

I understand this may be frustrating but we are wanting to give as many people as possible a chance to contribute, and there are possible problems related to one person "claiming" multiple issues at once that we would like to avoid. None of you have done anything wrong though, and this is a largely proactive approach.
