### ISSUE TITLE
Google Homepage projects being flagged as"deceptive"

### ISSUE THREAD

**Issue by xandora** [TheOdinProject/curriculum#22508]
There have been several reports of student submissions for the Google Homepage project being flagged as deceptive by the Google Safe Browsing initiative:

![](https://i.imgur.com/9D0eN9n.png)

To alleviate this issue, we should reconsider the branding used for the project.

**Comment by zachmmeyer** [comment]
What if there was an alternate logo supplied
![foogle](https://user-images.githubusercontent.com/34407561/128790725-887f6747-71d7-474a-8c34-93a08dc4c908.png)
and students were told to call it Foogle instead that way Google doesn't think the page is trying to scam you.
They'd just have to resize it with some CSS, which is a good way to apply some learned skills.
