### ISSUE TITLE
Heroku Application error on Foundations Command Line Basics assignment link

### ISSUE THREAD

**Issue by Dakota-Leonard** [TheOdinProject/curriculum#22528]
# Description of issue

In the command line basics portion of the Foundations course, the second assignment's link leads to an application error. This results in a rather confusing start to the learning of the command line as the remainder of the page assumes that the material at the provided link has been read.

# Steps to reproduce

1. Head to the assignments section for Command Line Basics found here: https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101#assignment
2. Follow the link for the second assignment as outlined below.
![image](https://user-images.githubusercontent.com/87897304/129343296-a431e4f5-2e9a-4206-a486-ab157b3f7c1b.png)

The link in question leads to: http://conqueringthecommandline.com/book/basics

**Comment by twalton83** [comment]
Closed with #22530
