### ISSUE TITLE
Introduction to Frameworks wording

### ISSUE THREAD

**Issue by AstroMike101** [TheOdinProject/curriculum#22526]
<img width="794" alt="Screen Shot 2021-08-12 at 3 04 18 PM" src="https://user-images.githubusercontent.com/65747601/129275880-0ac7199c-7bcf-46d6-96d2-165d7b4731d7.png">

In the introduction section of the "Introduction to Frameworks" lesson, it states that "If you’re programming with any other language, you pretty much start with a blank text file and go from there. Programmers, the best of whom are pretty lazy folk ". 

It starts off by talking about you start off coding with a blank slate with any other language, but programmers "got tired of having to write the same code over and over and over again just to cover the basic tasks that they wanted their applications to perform." 

Isn't "programmers" not the right category to have there? Shouldn't it be something like "web developers" as its speaking about inferred web frameworks?

**Comment by Abban-Fahim** [comment]
Actually, programmers are lazier than most web developers. Here, **programmers** were referred to those who wtite any sort of code, which is'nt limited to web developers. Web developers also includes designer's, who somethime doent even have to write code!

**Comment by KevinMulhern** [comment]
That is my take as well. "Programmers" is an umbrella term that web development fits under.

**Comment by twalton83** [comment]
Please do. @AstroMike101

**Comment by kashura** [comment]
@AstroMike101 do you still want to PR this or should we offer it to others? :-)
