### ISSUE TITLE
Command line basics: add how to enable full tab completion for MacOs users

### ISSUE THREAD

**Issue by coelhored** [TheOdinProject/curriculum#22554]
The lesson implies that in Mac Terminal, tab completion will behave similarly to Linux, but this is not the case.

for MacOS Users:
By default, tab completion only works for commands, but not directory and file names as described in this lesson.  To enable these completions, edit the file named .zshrc in the home directory, and add this line:

  autoload bashcompinit && bashcompinit
  
Save the file, then close and re-open terminal.  Now you've got the same awesome auto-completion as Linux users!

I learned how to do this from this page:  https://www.stuartellis.name/articles/mac-setup/

**Comment by coelhored** [comment]
I would be happy to adapt these comments  to add to the lesson.  It would be my first pull request!

**Comment by kashura** [comment]
@coelhored which version of Mac OS are you on? Since Catalina bash is replaced with zsh by default, and it does auto complete directories.

**Comment by twalton83** [comment]
@coelhored Do you mind replying to the above? Otherwise the issue will be closed because it is stale and not relevant to the latest versions of MacOS.

**Comment by kashura** [comment]
Stale.
