### ISSUE TITLE
Foundations Github: clarify ending of SSH key for macOS 

### ISSUE THREAD

**Issue by coelhored** [TheOdinProject/curriculum#22555]
The lesson states:

   Highlight and copy the output, which starts with ssh-rsa and ends with your email address.

At least for me on macOS 11.4, the ssh key doesn't end with my email, but rather username@name-of-device.local

**Comment by kashura** [comment]
Did you follow the guide and enter this command the same way?
`ssh-keygen -C <youremail>`

**Comment by kashura** [comment]
Closing as stale.
