### ISSUE TITLE
Ruby lessons / Pattern Matching : Inversion of two code blocks

### ISSUE THREAD

**Issue by paulhenri** [TheOdinProject/curriculum#22557]
In the section **Ruby 3 / Find pattern** it appears that the two code blocks should be switched. The first code block should show when a find pattern works and the second one when it does not. 
Right now it is the opposite.

**Comment by CouchofTomato** [comment]
Hi @paulhenri 

Apologies I missed this one.

It would be helpful if you could provide links or code snippets when reporting issues like this. Or even better feel free to submit a PR addressing this.

**Comment by paulhenri** [comment]
Hi,

No problem. Actually i can close this issue, it seems that the problem is rather on my side.. I think i misunderstood the chapter and i did not read the text correctly. 

Thank you for your time and sorry for the false alarm. Next time i will be more careful.
Paul-H

**Comment by CouchofTomato** [comment]
@paulhenri No need to apologise. We appreciate you taking the time to reach out.

Good luck with your learning.
