### ISSUE TITLE
Xubuntu download link broken

### ISSUE THREAD

**Issue by jomalone111** [TheOdinProject/curriculum#22589]
### Description
As of 8/27/21 the link to download xubuntu version 20.04 takes the user to a 404 not found page 

#### Steps to Reproduce
Got to Foundations Course, Prerequisites, Virtual Machine Download, Step 1.2 "Download Xubuntu" and click the link

#### Expected Behaviour
I would expect it to take me to the correct [webpage](url)

 #### Additional Information

**Comment by KevinMulhern** [comment]
I transferred this over from the main site repo. Is this still an issue?

**Comment by jomalone111** [comment]
Sorry for the delay. I just checked and it is working correctly now.
