### ISSUE TITLE
Broken link found

### ISSUE THREAD

**Issue by UnmadeBed** [TheOdinProject/curriculum#22588]
### Description
Found a broken link under the 'Additional Resources' section of the 'Foundations: Introduction to the Front End' [page](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-the-front-end).

#### Steps to Reproduce
The bug can be found [here](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-the-front-end) under the 'Skills of a Successful Front-End Web Developer from Drupal (a CMS based on PHP)' link. The link is broken and does not direct to the expected page.

**Comment by erdemYigitoglu** [comment]
the link works on my computer with crome. which device and browser did you try the link?

**Comment by UnmadeBed** [comment]
> the link works on my computer with crome. which device and browser did you try the link?

Using Chrome on MacBook. Just to clarify, the Odin Project page loads just fine, it's the link to a resource from Drupal which doesn't seem to work.

**Comment by kashura** [comment]
Link seems to be functional. Maybe an outage for their web server.
