### ISSUE TITLE
Typo on new HTML lesssons

### ISSUE THREAD

**Issue by JonathanYuan900** [TheOdinProject/curriculum#22601]
### Description
`Links to pages op other websites` contains a typo

![image](https://user-images.githubusercontent.com/76597944/132421263-569177fc-c905-4030-9cef-aa74ea09ef76.png)

#### Steps to Reproduce
[link to lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images)
The typo lies in the `Absolute Links` paragraph

#### Expected Behaviour
`Links to pages op other websites` should be `Links to pages on other websites`

**Comment by SNikhill** [comment]
I can take this one. 

I shall also like to suggest a slight change in wording for the way an Absolute Link is defined.

**Comment by kashura** [comment]
PR merged.
