### ISSUE TITLE
Wrong instruction on how to install `supertest`

### ISSUE THREAD

**Issue by refaelsh** [TheOdinProject/curriculum#22621]
In [this](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs/lessons/testing-routes-and-controllers) lesson (which corresponds to [this](https://github.com/TheOdinProject/curriculum/blob/main/nodeJS/testing/Testing.md) Markdown file), it is stated that:

```
... so go ahead and `npm install supertest` and while it’s installing ...
```

I think it should be like this: `npm install supertest --save-dev`. 

A penny for you thoughts guys :-)

**Comment by kashura** [comment]
@refaelsh good catch; want to open a Pull Request and fix it?

**Comment by refaelsh** [comment]
> @refaelsh good catch; want to open a Pull Request and fix it?

Yes, very much so, gladly. Thanks! :-)

**Comment by kashura** [comment]
@refaelsh thanks!
