### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/curriculum#2262]
Hi, 
When I clicked the first link under assignments, "For a basic and painless Internet overview", my virus projection activated . 
Below is the page I used. I don't know if the link is bad or if it was something on my computer. I rather inform you and it be nothing than not inform you and it be something. 
http://www.theodinproject.com/web-development-101/how-does-the-web-work?ref=lnav

BTW I like the webpage.

Thanks,

**Comment by rbyfalr** [comment]
The video was hosted on Vimeo, I think... (searches Vimeo), Ah ha! [Don't Fear the Internet, Episode 1](https://vimeo.com/24006296) and [Don't Fear the Browser](https://vimeo.com/25665411).

**Comment by KevinMulhern** [comment]
I am getting a 404 page when trying to access the link. Should we remove that resource? I think the rest of the assigned stuff will be enough to cover the material.

**Comment by kriox26** [comment]
I'm getting a 404 in item 1 and 5: http://www.dontfeartheinternet.com/the-basics/dont-fear-the-browser. Both from `dontfeartheinternet`, if they get hacked that often, maybe the should fear the internet.
Like kevin said, I think that all the remaining assigned stuff is enough to cover the material.

**Comment by wingyu** [comment]
Hey guys, @eriktrautman seems pretty keen on keep those resources so I've just submitted a PR fixing those broken links (#2635).

**Comment by KevinMulhern** [comment]
Thank you for this @wingyu :)
