### ISSUE TITLE
link given in the lesson is broken.

### ISSUE THREAD

**Issue by wasim7raja10** [TheOdinProject/curriculum#22631]
http://web.archive.org/web/20160925155912/http://www.happybearsoftware.com/how-to-get-a-programmer-job.html
from lesson https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-web-development#why-odin

**Comment by kashura** [comment]
Works just fine. Try the link on multiple devices, and make sure it's not an issue on your network.

**Comment by wasim7raja10** [comment]
> Works just fine. Try the link on multiple devices, and make sure it's not an issue on your network.

changing the  "http" to "https" worked for me. It would be better if you change it I guess.
