### ISSUE TITLE
Small issue in Foundations GitHub Basics

### ISSUE THREAD

**Issue by johnhitz203** [TheOdinProject/curriculum#22641]
### Description
In the Add Another File section step 1 says “Create a new file in the git_test folder called hello_world.txt. In the terminal, type git status, and notice hello_world.txt is not staged.” I think it should say “…type git status, and notice hello_world.txt is not tracked.” The next 2 step are to make a change in README.md and check the status “…and notice that README.md is now shown as modified, and not staged or committed. This is because you made a change to it, and it is already a tracked file.”

I think the point is to clearly show the difference between adding a file that is not tracked and updating a file that is tracked.

#### Steps to Reproduce
1. Log in
2. Visit a lesson page for Foundations Git Basics
3. Scroll down to the Add Another File section
4. The course progress bar does not increase

#### Expected Behaviour
Sentence should read “…type git status, and notice hello_world.txt is not tracked.”

**Comment by KevinMulhern** [comment]
Hi @johnhitz203, I've transferred this issue to the Curriculum repo where all the lesson content lives.

**Comment by KevinMulhern** [comment]
Resolved in https://github.com/TheOdinProject/curriculum/commit/089c5289b3c7fe9b6f82ccd8bf345e950982ce35
