### ISSUE TITLE
JavaScript course Objects and Object Constructors lesson has "additional resources" repeated twice

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/curriculum#22690]
# Summary

The [Object and Object Constructors lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/objects-and-object-constructors) in the JavaScript course has "additional resources" both before and after the Knowledge Check section.

## Acceptance Criteria
- [ ] The additional resources only appear once in the lesson
- [ ] The additional resources section appears in the same place as it does in our other lessons

**Comment by digidub** [comment]
I'll take it. Thanks

**Comment by wise-king-sullyman** [comment]
@digidub assigned! Thanks for volunteering to contribute!
