### ISSUE TITLE
Additional resource in the Rails course Active Record Association lesson has a broken link

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/curriculum#22691]
# Summary

The "Understanding Polymorphic Associations in Rails" additional resource in the Rails [Active Record Associations lesson](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/active-record-associations#additional-resources) no longer leads to the blog it is supposed to lead to.

## Suggested Fix

If a new link to that article can't be found the link should probably just be removed. If there is another quality resource of substantial similarity that you're aware of, feel free to propose it and we may decide to replace the old resource with this one.

You may also be able to use the internet archive wayback machine to link to the original article.

## Acceptance Criteria

- [ ] Broken link is fixed via one of the recommended remedies above

**Comment by qpongratz** [comment]
Hello from the discord, I'll take this issue please.

**Comment by wise-king-sullyman** [comment]
@qpongratz assigned! Thanks for volunteering to contribute!

**Comment by wise-king-sullyman** [comment]
Fixed in #22693
