### ISSUE TITLE
Add missing Knowledge Checks, Learning Outcomes & answer-links to Foundations/Introduction to HTML and CSS

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/curriculum#22776]
Related to #22466

This task is to go through the lesson referenced in the title of this issue and (as applicable):

- Add missing Learning Outcomes
- Add missing Knowledge Checks
- Add answer links in the Knowledge Checks

If the lesson already has Learning Outcomes or Knowledge Checks they do not need to be added to. Many lessons only need answer links added.

Knowledge check links should consist of an `<a>` tag which adds the `knowledge-check-link` class and links to the part of the lesson (or the external resource that is linked in the lesson) where the answer to the Knowledge Check can be found. Knowledge Check links should **not** point to external resources that weren't linked to as part of the lesson content or assignment. You can link to a specific line in the lesson like so:

```html
Lorem ipsum dolor sit amet, <span id="js-function-knowledge-check">consectetur adipiscing elit</span>, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to the page where the span with this id lives -->
<a class="knowledge-check-link" href="#js-function-knowledge-check">How do you return a value from a function?</a>
```
Or you can link to just a section of the lesson by just linking to the section heading and following [these](https://github.com/TheOdinProject/curriculum/wiki/Contributing-to-Wiki#anchor-linking) rules for determining how to format the link. Example:

```html
### Lorem ipsum dolor sit amet

sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to the page where the span with this id lives -->
<a class="knowledge-check-link" href="#lorem-ipsum-dolor-sit-amet">How do you return a value from a function?</a>
```

### Acceptance Criteria

- [ ] Lesson referenced in the title has Learning Outcomes, Knowledge Checks, and Knowledge Check links
- [ ] Knowledge Check links all link to the proper place in the lesson, or the proper external resource that was linked to earlier in the lesson
- [ ] Knowledge Check styling should **not** change

Please do not start work on this unless you've been assigned to it. Comment on this issue and ping me @wise-king-sullyman if you would like to be assigned to it.

Additionally, we would like for contributors to only take on one of these issues at a time. Please only request assignment for (and begin work on) an issue after the Learning Outcome/Knowledge Check/Knowledge Check link issue you're currently assigned to has been approved and merged.

**Comment by martenmatrix** [comment]
I would do it for the 4 lessons of CSS Foundations. @wise-king-sullyman

**Comment by martenmatrix** [comment]
I'll do it. You mean this [lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-html-and-css), right?

**Comment by wise-king-sullyman** [comment]
@martenmatrix correct. You're assigned! Thank you for volunteering to contribute!

Also regarding your last post, I will be making issues for the other lessons shortly. Once your PR for this lesson is merged feel free to request assignment for one of them if they're still available, but we don't want contributors to have multiple of these issues out at once.

**Comment by martenmatrix** [comment]
Yes, sorry. I did not read it carefully enough.
