### ISSUE TITLE
'CDN tab' is not on the website

### ISSUE THREAD

**Issue by martenmatrix** [TheOdinProject/curriculum#22840]
In the lesson JavaScript/Using Ruby on Rails or BaaS For Your Back End, in the Firebase assignments (Number 3) it is stated that "if you’re not going to be hosting your app on Firebase Hosting, but prefer to leave it where it is (e.g. on GitHub Pages), make sure to click the ‘from the CDN’ tab in step 3!". I am unable to find a ‘from the CDN’ tab in step 3 of the linked [website](https://firebase.google.com/docs/web/setup?hl=en). I think, the content may have moved to [this](https://firebase.google.com/docs/web/learn-more#config-object) website. However, I'm really unsure about this. Could someone validate this?

**Comment by BLooDBRothER** [comment]
Yes from web v9 firebase changed all as modules. So user needs to import modules from the cdn or install it using npm and import it.
