### ISSUE TITLE
Additional screenshot needed in Foundations/inspecting HTML and CSS

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/curriculum#22854]
In https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/inspecting-html-and-css#inspecting-elements the difference between applied and overwritten styles could be significantly clarified with the addition of a "new" screenshot that focuses on those items.

I recommend using this image: 
![image](https://user-images.githubusercontent.com/7115053/137065300-8c356366-49d8-4273-ad35-0722a67e71e1.png)
and just cropping it to only show one applied style and one overwritten style. An arrow or something pointing to the overwritten style with "overwritten" as a caption would probably be a nice add if something like that can be done in a way that looks good, I suggest Flameshot as a screenshot tool to make this easy if you don't already have something capable of doing the job.

Follow [this guide](https://github.com/TheOdinProject/curriculum/wiki/Adding-Images-to-the-Curriculum) from our wiki for the procedure to add this screenshot. I know it's a bit of an involved process so don't hesitate to ping me if you need some clarification.

**Comment by BLooDBRothER** [comment]
@wise-king-sullyman Hi, shall I proceed with the below screenshot or should I modify it?
![final_ss](https://user-images.githubusercontent.com/63643748/137446896-3af73371-45f5-459d-a8ee-6ca6543b552d.png)

**Comment by wise-king-sullyman** [comment]
@BLooDBRothER I would switch to red for the arrows, and have them pointing to the style rather than pointing to the text, other than that looks great!

**Comment by BLooDBRothER** [comment]
@wise-king-sullyman Hi! Ok, I will change and make a PR
