### ISSUE TITLE
Update Git Basics project to emphasize using SSH clone link

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#22852]
Students typically overlook the instruction which asks for learners to use the SSH tab when cloning their Github repository, and often become confused when they run into issues that arise when using HTTPS.

**Solution**: Step 4 [in this lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/git-basics) should be updated to further explain the necessity of using SSH. This instruction should be **bold**. Additionally, the associated photo should be updated [and re-uploaded](https://github.com/TheOdinProject/curriculum/wiki/Adding-Images-to-the-Curriculum) have a red arrow pointing to the SSH tab. 

**Suggested Copy Change**: "You must use the SSH option when cloning repositories so you can leverage the SSH key you set up in the prior lesson, otherwise it will ask for your username and password as well as a personal access token, which you do not have set up."

**Comment by zachmmeyer** [comment]
It's worth mentioning that this is getting addressed in the Git Basics rework.
