### ISSUE TITLE
SUGGESTION: deliver_now instead of deliver

### ISSUE THREAD

**Issue by kriox26** [TheOdinProject/curriculum#2285]
When you invoke `PassengerMailer.thank_you(Passenger.first).deliver!`, the email actually "sends" and everything works fine, but you get a `DEPRECATION warning` message like this:
```
﻿﻿DEPRECATION WARNING: `#deliver!` is deprecated and will be removed in Rails 5. Use `#deliver_now!` to deliver immediately or `#deliver_later!` to deliver through Active Job. (called from irb_binding at (irb):1)
```
Should we update to `deliver_now!`??
I put suggestion because it's not urgent since everything still works, but when rails 5 is released it won't

**Comment by muzfuz** [comment]
Good to keep note of, when the eventual upgrade happens.
