### ISSUE TITLE
Add missing Knowledge Checks, Learning Outcomes & answer-links to JavaScript/Using Ruby on Rails or BaaS For Your Back End **Rails section**

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/curriculum#22875]
The Rails portion of the `Using Ruby on Rails or Baas For Your Back End` lesson in the JavaScript course still needs knowledge checks and knowledge check links added.

I'd like to see someone doing/finished with the Rails course do this issue as knowledge of Rails will be very helpful in determining if knowledge check questions and links are adequate.

See #22805 for details.

**Comment by Jayashakthi28** [comment]
The Knowledge check links are only given for the firebase section and not for the ruby section. shall I do the ruby baas section knowledge check links?

**Comment by Jayashakthi28** [comment]
No sir.I haven't done Ruby on Rails course. My track is fullstack Javascript.

**Comment by Deetss** [comment]
Ill take on this issue if available

**Comment by Deetss** [comment]
Sorry didnt realize I was assigned to this! Ill get started!
