### ISSUE TITLE
Add missing Knowledge Checks, Learning Outcomes, and Knowledge Check links to Ruby on Rails/Form Basics

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/curriculum#22943]
Related to #22470

This task is to go through the Form Basics lesson in the Ruby on Rails course and (as applicable):

- Add missing Learning Outcomes
- Add missing Knowledge Checks
- Add answer links in the Knowledge Checks

If the lesson already has Learning Outcomes or Knowledge Checks they do not need to be added to. Many lessons only need answer links added.

Knowledge check links should consist of an `<a>` tag which adds the `knowledge-check-link` class and links to the part of the lesson (or the external resource that is linked in the lesson) where the answer to the Knowledge Check can be found. Knowledge Check links should **not** point to external resources that weren't linked to as part of the lesson content or assignment. You can link to a specific line in the lesson like so:

```html
Lorem ipsum dolor sit amet, <span id='example-knowledge-check'>consectetur adipiscing elit</span>, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to the page where the span with this id lives -->
<a class='knowledge-check-link' href='#example-knowledge-check'>How do you return a value from a function?</a>
```
Or you can link to just a section of the lesson by just linking to the section heading and following [these](https://github.com/TheOdinProject/curriculum/wiki/Contributing-to-Wiki#anchor-linking) rules for determining how to format the link. Example:

```html
### Lorem ipsum dolor sit amet

sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

...
<!-- This a tag just goes to a heading on the page-->
<a class='knowledge-check-link' href='#lorem-ipsum-dolor-sit-amet'>How do you return a value from a function?</a>
```

### Acceptance Criteria

- [ ] Lesson referenced in the title has Learning Outcomes, Knowledge Checks, and Knowledge Check links
- [ ] Knowledge Check links all link to the proper place in the lesson, or the proper external resource that was linked to earlier in the lesson
- [ ] Knowledge Check styling should **not** change

Please do not start work on this unless you've been assigned to it. Comment on this issue and ping me @wise-king-sullyman if you would like to be assigned to it.

Additionally, we would like for contributors to only take on one of these issues at a time. Please only request assignment for (and begin work on) an issue after the Learning Outcome/Knowledge Check/Knowledge Check link issue you're currently assigned to has been approved and merged.

Please check out [this new post on our wiki](https://github.com/TheOdinProject/curriculum/wiki/Learning-Outcomes-vs-Knowledge-Checks) about Learning Outcomes and Knowledge Checks if you need to write new Learning Outcomes or Knowledge Checks for this issue.

**Comment by Eduardo06sp** [comment]
I'm willing to work on this. Just one question, would you like me to modify the question in Learning Outcomes at all?

It seems to me that a lot of those questions would make excellent Knowledge Checks.

**Comment by wise-king-sullyman** [comment]
@Eduardo06sp if you think that some of the Learning Outcomes don't meet the guidelines set in our LO vs KC wiki post yes  I encourage you to update them 🙂

**Comment by Eduardo06sp** [comment]
One question. Let's say we link a knowledge check to an answer found inside the lesson.
Do you prefer:
**1)** I add a span with an id, so the user is taken to the exact location of the answer.
**2)** Just link to the section header element, so that the user is taken to the correct section, and has to look for the answer in that section

I have noticed both methods being used in different places of the curriculum. Thus far, I've been sticking to option 2, but refactoring should be fairly straightforward.

I'm not sure if you need a time-frame, but I should be finishing soon, estimating by the end of this week.

**Comment by wise-king-sullyman** [comment]
Generally, I go for linking directly to the line if the section is really long and the relevant part is in the last half of the section, otherwise, I think linking to the section is more than adequate.
