### ISSUE TITLE
Knowledge Check preamble missing on some lessons

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/curriculum#23000]
The:

"This section contains questions for you to check your understanding of this lesson. If you’re having trouble answering the questions below on your own, review the material above to find the answer."

preamble that should come after the Knowledge Check heading is missing on some lessons.

**Comment by tiagoheras** [comment]
That's a great idea! I have seen something like this in codecademy, where you had different multiple choice questions related to the topics of its respective sections. It also didn't let you advance if you didn't get those questions right, just as a test.
![codecademy quiz](https://user-images.githubusercontent.com/65797374/139606048-fb2f2614-df34-48ab-929b-fb63e826a6e0.png)

**Comment by wise-king-sullyman** [comment]
@tiagoheras I believe we're on slightly different wavelengths, as I'm not sure how that is related to a bit of text explaining the Knowledge Check sections that are already in our lesson.

Your interest in a multiple choice quiz of some sort has been noted though.

**Comment by tiagoheras** [comment]
@wise-king-sullyman I'm sorry I totally misunderstood the issue

**Comment by asadrjhk** [comment]
@wise-king-sullyman i have found some in JavaScript section where it is missing, can i make a PR

**Comment by wise-king-sullyman** [comment]
@asadrjhk I want this PR to add it to every lesson where it's missing, so if you're up for finding them / fixing them all I'll assign you.

**Comment by asadrjhk** [comment]
@wise-king-sullyman in the entire curriculum, either way I'm ready for it

**Comment by wise-king-sullyman** [comment]
@asadrjhk yes in the entire curriculum. Since this is the same thing being copied to each lesson (and many lessons already have it) it doesn't make sense to split into a bunch of different issues IMO.
