### ISSUE TITLE
Update relative pathways examples

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#23013]
We have a significant amount of people getting stuck and confused on the Recipes project due to 404s when using relative paths without `.` prepended to their route when deploying to Github Pages. Ex. `recipes/beef.html` versus `./recipes/beef.html`. 
This is because Github serves all projects from `github.io/username/projectname`, and `directory/filename` will search in the root `github.io/username` directory, not the project directory.

 We should update [this lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images) in the "Relative Link" section to include an example of using `.` to leverage the current working directory instead of only using `directory/file`.

**Comment by LeoKirasic** [comment]
I'd like to take this on!
