### ISSUE TITLE
Update React Router lesson to v6

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#23033]
Breaking changes were made and this lesson should be updated.

**Comment by DevlinRocha** [comment]
I'd like to take this on. I can replace all the references to `<Switch>` on [this page](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/javascript/lessons/router) with `<Routes>` instead.

**Comment by twalton83** [comment]
Thanks, please provide a sandbox demonstrating that this properly compiles and works with your PR.
