### ISSUE TITLE
Link to article in Fundamentals Part 3 doesn't work

### ISSUE THREAD

**Issue by itspatrickchoi** [TheOdinProject/curriculum#23030]
![image](https://user-images.githubusercontent.com/70690276/140583565-c4615411-e666-476a-a680-99920b733aba.png)
https://www.javascripttutorial.net/javascript-call-stack/ This link doesn't work anymore, Fundamentals Part 3

**Comment by DevlinRocha** [comment]
Link seems to be working again.

**Comment by itspatrickchoi** [comment]
Great
