### ISSUE TITLE
Syntax typo in CSS Foundations, external CSS section

### ISSUE THREAD

**Issue by YS-Abstract** [TheOdinProject/curriculum#23067]
![Screenshot 2021-11-15 at 10-10-49 CSS Foundations The Odin Project](https://user-images.githubusercontent.com/58709138/141833026-27a938b7-95fb-495a-b09f-06e434cd1481.png)

As shown in the screenshot, the example shows:

```html
<!-- index.html -->

<head>
  <link rel="stylesheet" href="styles.css" />
</head>
```

The `<link>` should not have a forward slash at the end since it is a self-closing tag.

**Comment by DevlinRocha** [comment]
Since this is such a small fix I went ahead and submitted a PR, I hope that's okay.
