### ISSUE TITLE
fix typo in factory function

### ISSUE THREAD

**Issue by osamamammar** [TheOdinProject/curriculum#23068]
I found the letter "s" here is unimportant and unnecessary, especially since it has a strange shape during reading.
# Screenshot:
![fix typo](https://user-images.githubusercontent.com/42181138/141847533-414a64e1-6bac-4b91-8743-fc1e80723dd0.png)

**Comment by fortypercenttitanium** [comment]
I understand why you wanted to change this now. I think the best way to make this look better is just by changing the sentence altogether. I'll offer a suggestion: ~~Then, every time we run the function it console.logs count and increments it.~~ "Then, every time we run the function is logs `count` to the console and increments it."

If you PR this change I will approve and merge.

**Comment by osamamammar** [comment]
Thank you for your patience, I did the PR @fortypercenttitanium
