### ISSUE TITLE
Typo in NodeJS Testing Lesson

### ISSUE THREAD

**Issue by fortypercenttitanium** [TheOdinProject/curriculum#23089]
https://github.com/TheOdinProject/curriculum/blob/main/nodeJS/testing/Testing.md

This lesson has a typo on line 159. The word "conjunction" is misspelled.

**Comment by digidub** [comment]
I'll take it on.

**Comment by fortypercenttitanium** [comment]
@digidub just following up. Still want this one? If not there are others who would like to get their feet wet with contributions.
