### ISSUE TITLE
Suggestion: Change ambiguous information in Flex shorthand

### ISSUE THREAD

**Issue by rfponce** [TheOdinProject/curriculum#23104]
I've noticed that is a mistake in the information about the initial value of "flex". In the lesson "[Growing and Shrinking](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/growing-and-shrinking)" the information says that the initial value of "Flex: 1" = "Flex: 0 1 0%". But MDN says in his [Flex article](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) that the initial value is "Flex: 0 1 auto". I'm attaching a screenshot from MDN and the lesson. 

![image](https://user-images.githubusercontent.com/74466204/142922484-ca6666f6-88ca-4c00-87eb-f985e264128f.png)
![image](https://user-images.githubusercontent.com/74466204/142922545-c1c85533-3ec2-45b2-abd0-0f4d1117ae5d.png)

**Comment by Manoj0Marmat** [comment]
@rfponce sir, then we need to edit the image and change 0% into the auto is it correct?

**Comment by Manoj0Marmat** [comment]
@rfponce I think the default value is flex: 1 1 0%. ?

**Comment by Manoj0Marmat** [comment]
@rfponce assign me

**Comment by Manoj0Marmat** [comment]
@rfponce fixed

**Comment by twalton83** [comment]
Hi so you’re aware, this user is not a maintainer, and ideally never do work unless you’re assigned.

**Comment by Manoj0Marmat** [comment]
@twalton83 oh sorry I'm a beginner can you please give me review

**Comment by Manoj0Marmat** [comment]
@twalton83 mam/sir, can you assist me, I wanna contribute. i sended my skillsets on your mail . assign me some work

**Comment by rfponce** [comment]
> @rfponce sir, then we need to edit the image and change 0% into the auto is it correct?

Analyzing in detail the information in the lesson looks like it refers to the default value of the _flex: 1_, not _flex_ in general, that is _flex = initial = 0 1 auto_ .

So I've changed the issue to "suggestion" about being more specific with the information in that paragraph. This might avoid confusion with newcomer students like me :)

**Comment by rfponce** [comment]
> @twalton83 oh sorry I'm a beginner can you please give me review

Hi! I suggest you read the [contributing guidelines](https://github.com/TheOdinProject/curriculum/blob/416cd575842154bc2bb561bbf9b106ac6ff75d76/CONTRIBUTING.md).

**Comment by Manoj0Marmat** [comment]
@rfponce yes i read it i also create pr request

**Comment by I3uckwheat** [comment]
@Manoj0Marmat Please be patient, trying to get attention in the way you are is a good way to make yourself difficult to work with and disqualify yourself from participating. Please slow down and understand that everyone is a volunteer and nobody is obligated to respond to you.

**Comment by Manoj0Marmat** [comment]
@I3uckwheat oh got it my bad thank you

**Comment by zachmmeyer** [comment]
This issue is closed by PR #23119
