### ISSUE TITLE
Rails | Advanced Forms Lesson uses soft deprecated methods

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/curriculum#23129]
The [Rails Advanced Forms](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/advanced-forms#prepopulating-select-tags-with-collections) lesson is currently using examples based on `form_for`, which has been soft deprecated. 

Ideally the examples should be updated to use `form_with`, as we've done in the [Basic Forms](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/form-basics) lesson.

There is also a reference to `fields_for` be using in earlier lesson which no longer seems to be the case (probably a relic of updating the basic form lesson). A short description should probably be added to one of the two lessons.

**Comment by CouchofTomato** [comment]
@ChargrilledChook Are you looking to take this on or are you wanting someone to pick this up?

**Comment by ChargrilledChook** [comment]
I'm happy to have a run at it, I can probably carve out some time in the next few weeks

**Comment by CouchofTomato** [comment]
I've assigned it to you @ChargrilledChook 

If you are unable to take it on in the next few weeks just let me know so we can open it up to someone else.

**Comment by Deetss** [comment]
If this hasn't been started id like to take a shot at it! @ChargrilledChook @CouchofTomato

**Comment by CouchofTomato** [comment]
Thanks. We'll see what @ChargrilledChook says.

**Comment by ChargrilledChook** [comment]
@Deetss @CouchofTomato I've had less time than I would have liked and haven't made a ton of progress on this, so I am happy to hand it over. Happy to help proofread / review etc when the time comes

**Comment by CouchofTomato** [comment]
@Deetss All yours mate
