### ISSUE TITLE
JS Forms Lesson links to the wrong link

### ISSUE THREAD

**Issue by jackalot** [TheOdinProject/curriculum#23142]
https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/forms 
[![image](https://user-images.githubusercontent.com/68657425/144450191-9618c1bc-e06d-4204-9ea1-b00c9c29ec9b.png)](https://cdn.discordapp.com/attachments/540903304046182425/915983511205318736/unknown.png)
this link links to https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/dom-manipulation which is a 404, and the new dom manipulation lesson is here https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/dom-manipulation-and-events. Problem is, the forms lesson links there as thats where git branching was explained. It no longer is explained there, its explained here in RPS now: https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/revisiting-rock-paper-scissors

**Comment by asadrjhk** [comment]
can i take this one?

**Comment by jackalot** [comment]
@asadrjhk sure go ahead

**Comment by thatblindgeye** [comment]
@asadrjhk If you would like to be assigned to fix this issue, please confirm and I will assign you :)

**Comment by asadrjhk** [comment]
@thatblindgeye thanks i want to, but i think this PR #23146 already solved this issue.

**Comment by thatblindgeye** [comment]
That should have been for a different lesson on Classes. The Forms lesson looks like it still has an incorrect link. I've assigned you if you want to double check and fix the issue if it still persists.
