### ISSUE TITLE
Dead link in React/State and Props section

### ISSUE THREAD

**Issue by khunhour** [TheOdinProject/curriculum#23180]
Issue: there is a dead link in the React>State and Props section, specifically under the State lesson.
Link to Lesson: https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/state-and-props
Screenshot(the second link `This article` ):
![Screenshot 2021-12-14 113043](https://user-images.githubusercontent.com/12671115/145922284-e1e370b5-5d3c-4b8e-9c34-504beeca6f29.png)

**Comment by zachmmeyer** [comment]
I'm going to try and reach out to them.

**Comment by zachmmeyer** [comment]
I reached out. Regardless if we get a response, we can use a Wayback Machine link for now. 
http://web.archive.org/web/20211101150139/https://lorenstewart.me/2017/01/22/javascript-array-methods-mutating-vs-non-mutating/

@khunhour Would you be up for making the PR?

**Comment by khunhour** [comment]
Yes I would thank you. I'll get right on in.
