### ISSUE TITLE
Add Links to Introduction to UX and Design

### ISSUE THREAD

**Issue by IkeG** [TheOdinProject/curriculum#2319]
Here are some helpful free UX resources that helped me get into UX design.

http://www.uxpin.com/knowledge.html - Pretty big collection of free UX books
https://www.mysliderule.com/learning-paths/user-experience-design - Very extensive free UX course (awesome step-by-step approach).
https://www.udacity.com/course/ux-design-for-mobile-developers-ud849 - Niche and focused on mobile, but was a great course to get me started.

**Comment by KevinMulhern** [comment]
Hey @IkeG, thanks so much for the links. The last one must have stopped working?

I think we could put this in the section: http://www.theodinproject.com/html5-and-css3/introduction-to-design-and-ux

**Comment by IkeG** [comment]
Oh no. Sorry about that.
I think the links would fit great in this article.
I hope it will be helpful for others :)

**Comment by KevinMulhern** [comment]
Hey @IkeG, sorry it took so long, I finally added your links. It would be great to break UX and design out into it's own mini course at some point in the future.
