### ISSUE TITLE
Broken link in Array lesson in Ruby

### ISSUE THREAD

**Issue by ezrahnyanat** [TheOdinProject/curriculum#23207]
I'm going through the Ruby course, noticed in the Array lesson the link for the last item in [Additional Resources](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/arrays#additional-resources) re: Set Operations is broken. 

Maybe this can be a good replacement? https://www.rubyguides.com/2018/08/ruby-set-class/

**Comment by zachmmeyer** [comment]
https://www.endpointdev.com/blog/2011/06/using-set-operators-with-ruby-arrays/
Here is the fixed link that I just found.
@ezrahnyanat Do you want to open a PR to fix this?

**Comment by ezrahnyanat** [comment]
Sure, will raise one this evening after the kids go to bed

**Comment by ezrahnyanat** [comment]
Oops... didn't know that button did that. Thought it was a toggle
