### ISSUE TITLE
Proposal: Adding a section on "React Dev Tools" in "React Introduction"

### ISSUE THREAD

**Issue by khunhour** [TheOdinProject/curriculum#23217]
I propose to briefly introduce the `React Dev Tools` inside the [React Introduction](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/react-introduction) Lesson just after React-Testing.

I haven't work on a draft yet, but I just want to confirm with the team if this is a good idea or not before making a pull request.

The section includes a brief introduction of what is "React Dev Tools" and what does it do. And as an assignment, this [this video](https://www.youtube.com/watch?v=rb1GWqCJid4) will be mentioned.

Also any suggestion is welcomed.

**Comment by twalton83** [comment]
I agree. I discussed this in the server with someone and looks like they didn't follow through on adding this. Please make a pull request.

**Comment by khunhour** [comment]
Nope. It's me. We discussed it on discord. I just thought I had to make it as an issue first to check if the resources mentioned is valid or sth. Alright, I'll work on the pull request.
