### ISSUE TITLE
Prepare Ruby's Debugging lesson to move before Enumerable lessons

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/curriculum#23224]
**Lesson:**
https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/debugging

**Description:**
People have a difficult time solving the TDD exercises for basic enumerables, predicate enumerables, and nested collections because they have not been introduced to debugging. We need to remove references to all enumerables from the debugging lesson, so that we can move it before these 3 lessons.

**Acceptance Criteria:**
* Replace enumerables examples
* Update the surrounding context/explanations of the debugging examples
* Add a link to documentation when explaining why a method is not working as expected.

**Additional Information:**
Below is an idea that I had to replace the `.map` examples, however you are welcome to come up with your own example that does not produce an error (and does not return the correct answer).

For this example, an isogram is a word that has no repeating letters (consecutive or nonconsecutive).
```rb
def isogram?(string)
  original_length = string.length
  string_array = string.downcase.split
  unique_length = string_array.uniq.length
  original_length == unique_length
end

isogram?("Odin")
```
Source: https://www.codewars.com/kata/54ba84be607a92aa900000f1

**NOTES:**
* Comment on this issue to indicate that you would like to work on it.
* Do **not** start to work on this until you have been assigned to it. 
* You must read and follow our [contribution guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)

**Comment by Maheshkumar-novice** [comment]
I'd like to work on this.

**Comment by rlmoser99** [comment]
@Maheshkumar-novice Thank you for offering to complete this issue. I'm sure you've seen people struggle with those TDD exercises, so I appreciate your help solving the root cause of this problem.

**Comment by Maheshkumar-novice** [comment]
I'm glad I could help.
