### ISSUE TITLE
Rails 7 upgrade: Update rails installation

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/curriculum#23228]
#### Lesson

[Rails installation guide](https://github.com/TheOdinProject/curriculum/blob/main/rails_programming/introduction/installing_rails.md)

#### Description

In order to update our rails course to the latest version we need to update the installation lesson.

#### Acceptance Criteria

  - [ ] The install command does not specify a Javascript version
  - [ ] Step 1.2 needs to explain that new rails applications don't require yarn but it is still required for some of the ways javascript can be bundled. The course will explain all of the options
  - [ ] Step 1.3 doesn't specify a rails version for the new command
  - [ ] Step 1.3 output of the rails new command is updated to show the rails 7 default output
  - [ ] Step 3.4 we can remove the update about the buildpacks issue

#### Additional information

You should be ok with installing rails 7 and creating this test app to ensure the instructions work as intended.

**Comment by linkonsat** [comment]
I can take this on.

**Comment by CouchofTomato** [comment]
@linkonsat All yours

**Comment by RolandStuder** [comment]
@CouchofTomato Question, will we stick to import maps for the entire rails course as it is currently the default? I think that would make sense, as currently it is very unclear what the industry most common practice will be, so just taking the default would make most sense to me. Do you aggree? Was this discussed anywhere?

**Comment by CouchofTomato** [comment]
> @CouchofTomato Question, will we stick to import maps for the entire rails course as it is currently the default? I think that would make sense, as currently it is very unclear what the industry most common practice will be, so just taking the default would make most sense to me. Do you agree? Was this discussed anywhere?

@RolandStuder yeah that's the plan. The js bundling lesson won't be until much later in the course. No need to introduce that for no obvious benefit when we're trying to stick as close to the core rails stack as possible. In the future we might just do one project requiring some transpiling or something just to show why you'd need to reach for something else but importmaps will be the default for all other projects.
