### ISSUE TITLE
Typo errors

### ISSUE THREAD

**Issue by SaezMD** [TheOdinProject/curriculum#23234]
In this page: 
https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/inspecting-html-and-css

The text says: 
Testing Styles In The Inspector

The Styles pane also allows you to edit styles directly in the browser. You can click inside of any individual selector to add a new rule, or click on an existing attribute or value to alter it.

It should says:

The Styles **panel** also allows you to edit styles directly in the browser. You can click inside of any individual selector to add a new rule, or click on an existing attribute or value to alter it.

**Comment by twalton83** [comment]
"Pane" is valid here.
<img width="627" alt="Screen Shot 2021-12-28 at 7 06 56 AM" src="https://user-images.githubusercontent.com/22967723/147590008-98ed5deb-bc15-4394-b146-c07a1fdc13e1.png">

**Comment by SaezMD** [comment]
Ok. Thanks!
