### ISSUE TITLE
Rails 7 Upgrade: New Lesson on JS bundling

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/curriculum#23244]
#### description

In order to update the rails course to version 7 we need a new lesson to cover the JsBundling gem. Although importmaps are the default they won't be suitable in every situation and students will need to know where to look for the next option

#### Acceptance Criteria
  - [ ] A brief explanation of what jsbundling is and why it is needed
  - [ ] An explanation of what bundler options are available with the gem
  - [ ] An explanation of how to add the jsbundling gem, adding to Gemfile, install command
  - [ ] An explanation of why you'd reach for this over importmaps
  - [ ] The pros and cons of this approach
  - [ ] Section on webpacker. [this link](https://github.com/rails/jsbundling-rails/blob/main/docs/comparison_with_webpacker.md) will help. Just that webpacker was a rails 6 implementation and a little bit about it. Material can be ripped from the current webpacker lesson as that will not be in the rails 7 course

#### Additional Information

The [gem readme](https://github.com/rails/jsbundling-rails) provides some excellent information. You will also find the [TOP lesson template](https://github.com/TheOdinProject/curriculum/blob/main/templates/lesson.md) handy for constructing the lesson. You can also ask questions here or in the discord chat

**Comment by linkonsat** [comment]
Could i take up this one?

**Comment by CouchofTomato** [comment]
@linkonsat Yeah for sure mate.

Just remember to add the section on webpacker. I'll update the issue too
