### ISSUE TITLE
Rails 7 Upgrade: New lesson on stimulusJS

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/curriculum#23247]
#### Description

In order to update our rails course to the latest version we need a new lesson to cover stimulusJS

#### Acceptance Criteria
  - [ ] A brief explanation of what stimulus is
  - [ ] An explanation of how to link html to a controller
  - [ ] An explanation of actions and how they are triggered
  - [ ] An explanation of targets
  - [ ] An explanation of managing state, including static values
  - [ ] An explanation of lifecycle callbacks
  - [ ] An explanation of the class attribute
  - [ ] Anything else you think is relevant to cover

#### Additional Information

The [gem readme](https://github.com/hotwired/stimulus-rails) provides some excellent information and the [handbook](https://stimulus.hotwired.dev/handbook/introduction) which is a must to read.

You will also find the [TOP lesson template](https://github.com/TheOdinProject/curriculum/blob/main/templates/lesson.md) handy for constructing the lesson. You can also ask questions here or in the discord chat

**Comment by RolandStuder** [comment]
I might take that on. Also happy to collaborate it, or just support / review, if someone else is interested.

**Comment by CouchofTomato** [comment]
Thanks @RolandStuder

**Comment by ChargrilledChook** [comment]
Closed by #23446
