### ISSUE TITLE
Rails 7 Upgrade: New lesson on turbo

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/curriculum#23246]
#### Description

In order to update our rails course to the latest version we need a new lesson to cover turbo

#### Acceptance Criteria
  - [ ] A brief explanation of what turbo is and what it replaces (turbolinks)
  - [ ] An explanation of turbo drive
  - [ ] An explanation of turbo frames
  - [ ] An explanation of turbo streams
  - [ ] An explanation covering redis, why it's needed for turbo streams and how to install it and run it.
  - [ ] A brief explanation of turbo native just to highlight that it exists and what it is intended to do.
  - [ ] Anything else you think is relevant to cover

#### Additional Information

The [gem readme](https://github.com/hotwired/turbo-rails) provides some excellent information especially the usage section which provides a link to a good tutorial and to the [handbook](https://turbo.hotwired.dev/handbook/native) which is a must to read.

You will also find the [TOP lesson template](https://github.com/TheOdinProject/curriculum/blob/main/templates/lesson.md) handy for constructing the lesson. You can also ask questions here or in the discord chat

**Comment by MchaseCov** [comment]
Hey I'd love to contribute to this one. If you'd like some "proof of understanding", my recent repos have been using the Turbo package, including a scaffold generation gem related to it..

(also down to collaborate with others if anybody else is interested!)

**Comment by CouchofTomato** [comment]
Thanks @MchaseCov 

Looking forward to the lesson
