### ISSUE TITLE
Rails 7 Upgrade: New lesson on importmaps

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/curriculum#23243]
#### Description

In order to update our rails course to the latest version we need a new lesson to cover the now default importmaps for importing third party Javascript packages.

#### Acceptance Criteria
  - [ ] A brief explanation of what the default was in rails 6 (webpacker and webpack) and why importmaps were chosen for rails 7.
  - [ ] An explanation of what importmaps are
  - [ ] An explanation of how to use importmaps
  - [ ] An explanation of using the ./bin/importmap command and how that can serve packages via a CDN
  - [ ] An explanation of preloading modules
  - [ ] An explanation of the pros and cons of importmaps

#### Additional Information

The [gem readme](https://github.com/rails/importmap-rails) provides some excellent information. You will also find the [TOP lesson template](https://github.com/TheOdinProject/curriculum/blob/main/templates/lesson.md) handy for constructing the lesson. You can also ask questions here or in the discord chat

**Comment by Deetss** [comment]
If this is still available id like to take a shot. @CouchofTomato

**Comment by CouchofTomato** [comment]
Go for it mate @Deetss

**Comment by Deetss** [comment]
Added PR to close this. I believe I have met all requirements for acceptance. @CouchofTomato 
Acceptance Criteria:

- [x] A brief explanation of what the default was in rails 6 (webpacker and webpack) and why importmaps were chosen for rails 7.
- [x] An explanation of what importmaps are
- [x] An explanation of how to use importmaps
- [x] An explanation of using the ./bin/importmap command and how that can serve packages via a CDN
- [x] An explanation of preloading modules
- [x] An explanation of the pros and cons of importmaps
