### ISSUE TITLE
Change the installing_node.md instructions to be a lesson

### ISSUE THREAD

**Issue by programmurr** [TheOdinProject/curriculum#23248]
Based on this [Discord chat](https://discord.com/channels/505093832157691914/540903304046182425/922597388412133487).

I propose breaking the [Node installation instructions](https://github.com/TheOdinProject/curriculum/blob/main/foundations/installations/installing_node.md) out into their own lesson that is placed immediately before [Fundamentals Part 4](https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/fundamentals-4.md). The [JavaScript Exercises](https://github.com/TheOdinProject/javascript-exercises) README can then be re-written to just focus on cloning the repo and installing jest.

I think this can reduce the number of questions relating to problems with installing jest or cloning the repo as this is a common friction point.

- [x] Take the existing Node Installation instructions and make them a lesson
- [x] Update the TOP website repo to point to the new lesson
- [x] Update the JavaScript Exercises README to reflect the new instructions
- [ ] Remove the old installation instructions

**Comment by xandora** [comment]
Is there anything blocking theodinproject/javascript-exercises#215 currently?

**Comment by programmurr** [comment]
@xandora Hi, thanks for approving and merging! :) 

For the final task, removing the old instructions, would I just delete the old installation instructions or is there a directory where old lessons or files are kept for posterity/backup?

**Comment by thatblindgeye** [comment]
@programmurr For now you can move it to the `archive` folder (you should see the old DOM manipulation lesson in there as well)
