### ISSUE TITLE
HTML Boilerplate lesson needs lang attribute

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23256]
In the [HTML Boilerplate lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-boilerplate), all code blocks should have the `lang` attribute added to the opening `<html>` tag, like so:

```
<html lang="en">
```

There should also be a Heading 4 `####` section (within the "HTML Element" Heading 3 `###` section) explaining **briefly** what this attribute is for, and why it is needed (mainly for accessibility reasons). 

Finally, the [MDN article on the lang attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) should be added as an additional resource, as it covers using the attribute on other elements as well. This page can also answer what the attribute is for and why it is needed for a11y reasons.

**Note**: this update may require other lessons to be updated to match. Those lessons should **not** be included in a PR for this specific issue, as a PR for this issue should only include the single HTML Boilerplate lesson.

**Comment by 01zulfi** [comment]
I can take this on @thatblindgeye

**Comment by thatblindgeye** [comment]
@01zulfi You've been assigned! Let me know if you have any questions :)
