### ISSUE TITLE
"Additional Resources" section on lesson "Block and Inline" of the "Foundations" path unavailable

### ISSUE THREAD

**Issue by Bnyth** [TheOdinProject/curriculum#23264]
The website the link points to (https://learnlayout.com/no-layout.html) is down, making it unreachable to whoever tries to access it.

**Solution:**

Redirect the user to a web archive snapshot of the website: the latest snapshot available is from August 2021, and contains the necessary slides appointed on the lesson (https://web.archive.org/web/20210813033024/https://learnlayout.com/no-layout.html).

**Comment by twalton83** [comment]
<img width="1839" alt="Screen Shot 2022-01-02 at 12 51 06 PM" src="https://user-images.githubusercontent.com/22967723/147889155-b073fce2-3ef6-479a-9aee-983b66ab6c7b.png">
Sure it's not your network?

**Comment by Bnyth** [comment]
Weird, it won't load on Firefox but it will on Chrome. I don't think it's a problem with my extensions, since even when disabling them it just won't load.

**Comment by twalton83** [comment]
I can access it on Firefox as well.

**Comment by twalton83** [comment]
I'll close this for now, but I would triple check if there's anything on your side that may be causing this. Since it's nothing to do with their servers, I'll close this.
