### ISSUE TITLE
Feedback to improve git lesson

### ISSUE THREAD

**Issue by julianchuk** [TheOdinProject/curriculum#23270]
For rookies like me this git and GitHub could be overwhelming, so i had to do extra job and found awesome Youtube playlist with very nice and friendship explanation, so suggest to include it

https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV

**Comment by zachmmeyer** [comment]
Hello! Could I ask what about the content in the curriculum you found overwhelming that the videos in this playlist were able to help you with? Could you also tell me where you are at in the curriculum currently?

**Comment by julianchuk** [comment]
> Hello! Could I ask what about the content in the curriculum you found overwhelming that the videos in this playlist were able to help you with? Could you also tell me where you are at in the curriculum currently?

Hi, ty for answer, actually i´ve completed: HTML Foundations:

Git Basics:
1. Introduction to GIT
2. Git Basics

**Comment by zachmmeyer** [comment]
I'm glad you found that playlist helpful in your learning. This playlist provides more information than what is required at that level, and the curriculum does go into more detail later on after graduating from Foundations.

Additionally, an 11 video playlist where the videos average 15 minutes is a lot to ask in the beginning of your learning journey. While it is totally fine for an individual to seek out supplemental information, this playlist unfortunately cannot be added to a lesson in Foundations.

Thank you for taking the time to write out an issue and wanting to contribute to the curriculum!

**Comment by julianchuk** [comment]
> I'm glad you found that playlist helpful in your learning. This playlist provides more information than what is required at that level, and the curriculum does go into more detail later on after graduating from Foundations.
> 
> Additionally, an 11 video playlist where the videos average 15 minutes is a lot to ask in the beginning of your learning journey. While it is totally fine for an individual to seek out supplemental information, this playlist unfortunately cannot be added to a lesson in Foundations.
> 
> Thank you for taking the time to write out an issue and wanting to contribute to the curriculum!

ye, though same as u, but believe me is very friendly to explain, so u get kinda absorbed when start to watch and get very good fundamentals, faced many issues with this part as involves many commands in terminal and how to cd in proper file and link repositories from terminal for example, as i said for rookies like me could be overwhelming, delayed me like two days stucked until i saw this first 4-5 videos in that playlist.

**Comment by zachmmeyer** [comment]
It sounds like you may have missed [Command Line Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101).

Git Basics is structured to have you create your repository online first and then clone it locally. Do not forget that if you have other questions, you can also ask in the Discord, but it is also encouraged to seek this information out. You did seek this information out yourself, but it is in the form of a large playlist. I have skimmed the videos, I understand that they are easy to understand, however all of this information is more or less present in the curriculum or documentation is linked as a larger resource.

**Comment by julianchuk** [comment]
> It sounds like you may have missed [Command Line Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101).
> 
> Git Basics is structured to have you create your repository online first and then clone it locally. Do not forget that if you have other questions, you can also ask in the Discord, but it is also encouraged to seek this information out. You did seek this information out yourself, but it is in the form of a large playlist. I have skimmed the videos, I understand that they are easy to understand, however all of this information is more or less present in the curriculum or documentation is linked as a larger resource.

i didn´t missed sir, just feedbacking that was overwhelming, at the end of the day is ur call if hear someone who don´t have any experience, followed even the diffuse method (from mindset section) to aboard it and cost me a lot.
