### ISSUE TITLE
Add Chrome Installation to installation prereqs

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#23305]
To streamline the curriculum and bring users in line with our debugging and inspector lessons, we should include a Chrome installation for Mac and Linux in the installations section of the course. 

Completion Criteria:

- Update to [this lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installation-overview) to add Google Chrome as part of the installation plan
- Update to [the Prerequisites lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/prerequisites) that adds a "Google Chrome" section after the OS installations. This section will need to house both Mac and Linux Google Chrome installation instructions.

**Comment by Maheshkumar-novice** [comment]
I'd like to work on this.

**Comment by twalton83** [comment]
Thanks.
