### ISSUE TITLE
Remove Firefox Inspector/Debugging from curriculum

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#23306]
Blocked by #23305

To achieve parity across our userbase, we should focus on Google Chrome instead of suggesting Firefox at different junctures and maintaining two sets of instructions. 

Completion Criteria: 

- Mentions of Firefox are removed from the following lessons: 
- [x] https://github.com/TheOdinProject/curriculum/blob/5f37d43908ef92499e95a9b90fc3cc291a95014c/html_css/grid-lessons/creating-a-grid.md
- [x] https://github.com/TheOdinProject/curriculum/blob/5f37d43908ef92499e95a9b90fc3cc291a95014c/html_css/grid-lessons/positioning-grid-items.md
- [x] https://github.com/TheOdinProject/curriculum/blob/e9617d42c4a540d0d3e652756afa0379d0ec6eae/foundations/html_css/html-foundations/html-boilerplate.md
- [x] https://github.com/TheOdinProject/curriculum/blob/5f37d43908ef92499e95a9b90fc3cc291a95014c/html_css/accessibility/accessible_colors.md
- [x] https://github.com/TheOdinProject/curriculum/blob/5020ffa6c16e5238c83968ff674c9315f0abb6e2/foundations/html_css/inspecting-html-and-css/inspecting-html-and-css.md
- [x] https://github.com/TheOdinProject/curriculum/blob/540783990147774cced67d30c5d7f6f1794bf09c/foundations/javascript_basics/javascript_developer_tools.md
- [x] https://github.com/TheOdinProject/curriculum/blob/5f37d43908ef92499e95a9b90fc3cc291a95014c/html_css/accessibility/accessibility_auditing.md
- [x] https://github.com/TheOdinProject/curriculum/blob/4614b4dd8b1cd66bf78fe2d8823ccf4ab85a9cd8/html_css/accessibility_auditing.md

**Comment by Zadag** [comment]
I can take this issue.

**Comment by dm-murphy** [comment]
If you're splitting this up I'm happy to do the two grid lessons I wrote and remove mention of the Firefox Developer Tools. I'm already reworking these lessons with the new Practice sections. 

I also want to clarify, you are only suggesting removing the mention of Firefox Developer Tools right? The MDN resources on Grid are one of the main external resources throughout the Grid lessons and are quite helpful.

**Comment by twalton83** [comment]
Yes, MDN is unaffected, we're focusing in on the browser itself. Please go ahead and take on your Grid lessons, thanks ! @dm-murphy

**Comment by dm-murphy** [comment]
> Yes, MDN is unaffected, we're focusing in on the browser itself because we don't want to maintain two sets of instructions for navigating tools. Please go ahead and take on your Grid lessons, thanks ! @dm-murphy

Sounds good! Thanks Tati!

**Comment by Zadag** [comment]
Should I start working on removing firefox mentions from the 6 remaining lessons?

**Comment by twalton83** [comment]
@Zadag go for it.
