### ISSUE TITLE
link to the faker module in the odin book project needs to be updated

### ISSUE THREAD

**Issue by kazumaneet** [TheOdinProject/curriculum#23310]
The faker module that was linked before no longer has any code in it because the user deleted it so it should be updated with this https://github.com/faker-js/faker instead.

**Comment by CouchofTomato** [comment]
Are you happy to make a PR for this @kazumaneet

**Comment by kazumaneet** [comment]
It's a bit late for me today but I can do it tomorrow?

**Comment by kazumaneet** [comment]
@CouchofTomato I forked it and i was trying to clone the repo but unfortunately my wifi is to slow and cloning keeps interrupting.

**Comment by kazumaneet** [comment]
I forked it and I was trying to clone the repo but unfortunately, my wifi is too slow and cloning keeps interrupting. @CouchofTomato

**Comment by CouchofTomato** [comment]
Ok, no issue @kazumaneet

**Comment by CouchofTomato** [comment]
I'm gonna create another issue that details the steps someone can take on this because it's a good first issue for someone to take on
