### ISSUE TITLE
Missing closing `>` on "CodePen Embed - flex-alignment example 2" (Foundations - HTML/CSS - Flexbox)

### ISSUE THREAD

**Issue by rog2054** [TheOdinProject/curriculum#23326]
url: https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/alignment

In the `GAP` section, the CodePen example HTML is missing the closing `>`  at the end, currently it says `</div` instead of `</div>`

**Comment by NaincyKumariKnoldus** [comment]
Hey @rog2054 I would like to do this. Can I Please?

**Comment by rog2054** [comment]
Yes of course, please do.

I'm unsure how to edit the codepen sections.

**Comment by NaincyKumariKnoldus** [comment]
Here I found only .md files.

**Comment by twalton83** [comment]
Well, @rog2054 is not a maintainer and cannot assign this, and only TOP maintainers have access to codepen. We’ll take a look and get it resolved. @NaincyKumariKnoldus

**Comment by NaincyKumariKnoldus** [comment]
okay no problem @twalton83

**Comment by thatblindgeye** [comment]
Thank you for letting us know, @rog2054. The codepen has been updated and the lesson should reflect the update now!

**Comment by rog2054** [comment]
Thank you Eric.

------ Original Message ------
