### ISSUE TITLE
Update Javascript OdinBook instructions to use the correct faker library

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/curriculum#23339]
Because of the recent controversy around the faker js library the original maintainer is now longer in control of the project

Point 4 under the getting started section [here](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs/lessons/odin-book) need to be updated to point to [the new library](https://github.com/faker-js/faker).

Acceptence criteria
  - [ ] The link directs to the new library

**Comment by ayoubmissaoui** [comment]
I want to take this

**Comment by CouchofTomato** [comment]
All yours @ayoubmissaoui 

Thank you

**Comment by zachmmeyer** [comment]
Closed by https://github.com/TheOdinProject/curriculum/pull/23340
