### ISSUE TITLE
Possibly outdated rails links in additional resources in javascript final project

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23358]
[project_final_js.md](https://github.com/TheOdinProject/curriculum/blob/main/javascript/finishing-up/project_final_js.md) has two rails links in the additional resources section. These links mention the rails version 5/5.1. They are:

1. [A Rock Solid, Modern Web Stack—Rails 5 API + ActiveAdmin + Create React App on Heroku](https://blog.heroku.com/a-rock-solid-modern-web-stack)
2. [How to Build a React App that Works with a Rails 5.1 API](https://www.sitepoint.com/react-rails-5-1/)

Considering that Rails 7 is the newest version, the aforementioned links might be outdated.

**Comment by thatblindgeye** [comment]
@CouchofTomato or @KevinMulhern  Do you have any opinion on this?

**Comment by thatblindgeye** [comment]
Gotcha. Gonna add a Help Wanted status for now; if this should be held off on we can switch to On Hold label instead, though.

**Comment by linkonsat** [comment]
I can take this up if it's alright.

**Comment by thatblindgeye** [comment]
@linkonsat You've been assigned.

**Comment by 01zulfi** [comment]
@linkonsat Any progress on this?

**Comment by linkonsat** [comment]
@01zulfi In all honesty it completely slipped my mind that I got assigned to this. I'm going to start working this one and get it finished although.

**Comment by linkonsat** [comment]
Possible resources found so far:
1. https://hibbard.eu/rails-react-crud-app/
2. https://hibbard.eu/rails-react-crud-app/

**Comment by KevinMulhern** [comment]
Closing in favour of https://github.com/TheOdinProject/curriculum/issues/25164
