### ISSUE TITLE
Incorrect Formatting and Code Snippet in the Checkboxes section of Form Basics

### ISSUE THREAD

**Issue by BenFin75** [TheOdinProject/curriculum#23377]
I found two potential issues with the Checkboxes section of [form-basics.md](https://github.com/TheOdinProject/curriculum/blob/main/html_css/intermediate_html/form-basics.md) in the intermediate HTML and CSS course.

the section title is inside of the paragraph for the section.

The code snippet showing the creation of a checkbox option for pizza toppings uses `type="radio"` instead of `type="checkbox"`

**Comment by thatblindgeye** [comment]
This issue has been resolved per PR #23394
