### ISSUE TITLE
Fix dead link in the sign-up form project under the intermediate HTML/CSS section

### ISSUE THREAD

**Issue by laur-ns** [TheOdinProject/curriculum#23381]
The page:
https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/sign-up-form

![Under Step 2: Gather Assets](https://i.imgur.com/nNnUEBJ.png)

**Comment by zachmmeyer** [comment]
I took this on because I saw that more than a few links were incorrect (not using Statically). Thanks for making an issue!
