### ISSUE TITLE
xml svg code snippet not displaying properly in HTML intermediate/SVG lesson

### ISSUE THREAD

**Issue by khunhour** [TheOdinProject/curriculum#23383]
In the HTML Intermediate/[SVG lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/svg) the XML svg code snippet does not display properly. screenshot below to demonstrate.
The markdown preview in Github is working fine, however when pasting the code into TOP markdown preview, it shows the issue.
This might be an issue with XML not being supported.
![svg](https://user-images.githubusercontent.com/12671115/150887828-ee68ed2b-f809-4222-bec5-655dd945aecd.png)

**Comment by jmmarco** [comment]
I took a look at this issue, and indeed the code snippet does not display as intended. After experimenting a bit I found that placing the code inside three backticks, and with no language specified does the trick. Like this:
```
```<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x=0 y=0 width=100 height=50 /><circle class="svg-circle" cx="50" cy="50" r="10"/></svg>```
```

The result will look like this:

<img width="739" alt="Screen Shot 2022-01-25 at 15 27 14" src="https://user-images.githubusercontent.com/3438337/150995344-639e248b-943d-411e-b052-df79294da68f.png">


However this seems a bit hacky. Perhaps this is a bug related to the markdown engine used to render the code? 🤔

**Comment by khunhour** [comment]
Hi @jmmarco, thank you for commenting on this. I just took a look at other ways of code snippets in other lessons and found that if I write it like this:
```
~~~html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
    <rect x=0 y=0 width=100 height=50 />
    <circle class="svg-circle" cx="50" cy="50" r="10"/>
</svg>
~~~
```
I put this into the TOP markdown and the result looks good!
![svgg](https://user-images.githubusercontent.com/12671115/150999370-c0278e45-9b12-4a93-a8ef-48502c22d157.png)

Would this be good enough?
I can make a PR if it's good to go.
thanks.

**Comment by jmmarco** [comment]
That's great @khunhour I think you're good to go to create a PR for this. In the PR template, reference this issue along with the proposed solution 👍

**Comment by jmmarco** [comment]
Also, I think you can specify `xml` instead of `html` since an [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG) is technically XML.
