### ISSUE TITLE
form validation assignment links to the wrong video address in form-validations.md

### ISSUE THREAD

**Issue by rcamach7** [TheOdinProject/curriculum#23380]
[This lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-validation#required-validation) has an assignment "Watch Web Dev Simplified’s JavaScript Form Validations Tutorial" that links to an incorrect video. 

If [this](https://www.youtube.com/watch?v=In0nB0ABaUk&t=5s&ab_channel=WebDevSimplified) is the correct link I can make a PR on it?

**Comment by thatblindgeye** [comment]
This is related to PR #23387 as the video link in question has been discussed regarding removal. I am closing this as that PR will be handling this issue moving forward, but thank you for bringing it to our attention!
