### ISSUE TITLE
Possibly misleading example

### ISSUE THREAD

**Issue by arito7** [TheOdinProject/curriculum#23393]
![top](https://user-images.githubusercontent.com/64824933/150961458-b6aa5d6d-aa6b-4d19-bc07-611d9d7020e0.png)

### Description
In Full Stack JS > Intermediate HTML and CSS > Form Basics lesson
The example code under 'Checkboxes' uses radio buttons.

[Form Basics](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-basics)

#### Expected Behavior
Example code using checkboxes

 #### Additional Information
Thank you for this amazing free course.

**Comment by zachmmeyer** [comment]
I went ahead and moved this to the curriculum repo.
@arito7 Would you be interested in making a PR to fix this?

**Comment by arito7** [comment]
@zachmmeyer Sure! It'll be my first time ever making a PR, I'll read the contributing guide to get started.

**Comment by zachmmeyer** [comment]
You do not need to re-open the issue. Thanks!
