### ISSUE TITLE
Improvement request on the Regular expressions pattern used in the Pattern Validation section and provision of a link to an external resource in the Additional Resources section of form_validation.md 

### ISSUE THREAD

**Issue by Artymanprince** [TheOdinProject/curriculum#23398]
I have explained the Regex pattern used in this section "(\d{5}([\-]\d{4})?)" and provided a link to an article that clearly explains how to apply Regex to most sought after data in a database which also includes the zip code(Number) format used.
As there didn't seem to be any brief explanation of it even though it was mentioned.
Using the Regular expression pattern `(\\d{5}([\\-]\\d{4})?)`. How exactly do we interpret this expression? Let’s take this step by step, going from left to right: 

<ul> 
  <li> Capturing group: ( ) </li>
  <li> Escape character: \ </li>
  <li> Digit: \d </li>
  <li> Number of characters: { } </li>
  <li> Matches characters in brackets: [ ] </li>
  <li> 0 or 1 character: ? </li>
</ul>

and the Link to the external resource:  https://towardsdatascience.com/regular-expressions-clearly-explained-with-examples-822d76b037b4

**Comment by CouchofTomato** [comment]
Can you please link to the lesson in question.

**Comment by Artymanprince** [comment]
> Can you please link to the lesson in question.

Sure. Here: https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-validation#pattern-validations

**Comment by thatblindgeye** [comment]
Just an FYI @CouchofTomato, there is also a PR up for this at #23397

**Comment by thatblindgeye** [comment]
Closing as this has been resolved in PR #23397
