### ISSUE TITLE
Form-Basics: Button Default Type Description

### ISSUE THREAD

**Issue by eltonbautista** [TheOdinProject/curriculum#23406]
Just a suggestion for the button section in the Form-Basics lesson: It talks about how <button type="button"> is a generic button, this sounds like it's saying <button> would be the same thing. But inside a form <button> is <button type="submit"> right? Maybe it's just me who thinks about it that way though since in all of Foundation I never used a type for button. 

My suggestion is just to say in the "Submit Buttons" information that <button> defaults to <button type="submit">. But then again maybe it's designed that way so people Google what the default value of a button is, that's what I did haha.  Not sure if others agree though, just thought I would share my opinion!

**Comment by thatblindgeye** [comment]
Could you copy and paste the exact text from the lesson that you either find confusing or thing could be updated?

**Comment by eltonbautista** [comment]
@thatblindgeye Oh my God I just read through the first paragraph of what I wrote and it's literally making me cringe. I don't even know what I was saying. I'm so sorry you had to read through that. **Through Google I saw that the button element's default value is _submit_** if I am incorrect feel free to ignore the rest of the text! 

I think what I was trying to say is that: The very first time I encountered button types was in the Form-Basics Lesson, but throughout all of Foundations I was using <button></button> which functioned the way it was supposed to then. BUT I didn't know that <button></button> has the default type **"submit"** so the button that I was using the whole time was actually a **"submit"** button, I think this isn't a problem because I wasn't sending any information through a form BUT if I used it in a form thinking it was just a **generic** button then I'm sure I'd have encountered a problem. 

My suggestion is that maybe somewhere in the Buttons Topic in Form-Basics Lesson it should be specified what the **default value of a button is inside a form.** I suggest this because others might think that <button></button> equals to <button type="button"> but <button> actually equals to a **submit type** <button type="submit"> and I believe there is an important distinction between those two, unless there actually isn't an important distinction between <button type="submit> and <button type="button>. Here is the associated link: https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-basics 

Thank you for reading!

**Comment by thatblindgeye** [comment]
Ah okay, I see what you're saying now. I agree that it would be worth noting the default behavior of a button when the `type` attribute isn't included. @eltonbautista can you update the title of the PR to something along the lines of "Form Basics: Button default type"?

For anyone who would like to take this on, the **acceptance criteria** for this issue would be as follows:

- [ ] In the [Form Basics](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-basics) lesson, there should be a note in the section on buttons that quickly mentions the default behavior of buttons without a `type` attribute.
- [ ] There should also be a quick note about how you should generally always explicitly state the type on a button

**Comment by DigitalKnight0** [comment]
I can take this!

**Comment by thatblindgeye** [comment]
@DigitalKnight0 you've been assigned!

**Comment by eltonbautista** [comment]
I have updated the title! Thanks!
