### ISSUE TITLE
Replace Hangman Dictionary

### ISSUE THREAD

**Issue by rhodes-david** [TheOdinProject/curriculum#23416]
[Project: Hangman](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/hangman) (in the Ruby Programming section) instructs learners to download and use the [5desk.txt dictionary file](https://www.scrapmaker.com/view/twelve-dicts/5desk.txt). Unfortunately, this dictionary contains many words at odds with TOP's Code of Conduct, including racial slurs and other offensive words. In addition to being inappropriate for use in an actual game of hangman, these words potentially put learners at risk if they use this project as a part of their GitHub portfolio.

I propose we replace the dictionary with a different one, ideally one devoid of offensive terms. As one example, [this dictionary](https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt) is formatted similarly to the original (making for an easy transition), has a permissive [license](https://github.com/first20hours/google-10000-english/blob/master/LICENSE.md) for educational use, and has been [scrubbed of swear words](https://github.com/first20hours/google-10000-english#swear-free-lists). It's not perfect, though, since it contains proper nouns (e.g., Maryland) and abbreviations (e.g., USPS).

**Comment by zachmmeyer** [comment]
@rhodes-david Well that is indeed a problem. Would you like to make a PR changing out the dictionary with the improved one you have found?

**Comment by rhodes-david** [comment]
@zachmmeyer Thanks for implementing! Do you think we should also include instructions on how to download the new file? The previous file had a button to facilitate downloading, whereas this new one does not. I ended up using the "Save Page As" option on my browser's right-click menu. I'm not sure if there's a different technique recommended for downloading a single file from Github.

**Comment by zachmmeyer** [comment]
@rhodes-david I personally do not think it's necessary. I would hope the student working on hangman would be a bit more technically sophisticated, but that might be an oversight on my part.
If you feel strongly about it, I'd definitely make a PR!
