### ISSUE TITLE
Add recursion to ruby exercise repo

### ISSUE THREAD

**Issue by DigitalKnight0** [TheOdinProject/curriculum#23420]
The CS section in ruby includes the lesson on recursion which links to [Code quiz](http://www.codequizzes.com/computer-science/beginner/recursion) in the test yourself section. I think it might be more helpful to convert it into an assignment and add some exercises for recursion in the ruby exercises repo along with some tests.

**Comment by DigitalKnight0** [comment]
To give some more context on why i made the suggestion, the code quiz page has some good exercises, but the instructions are vague and the learner can  hardly verify if their solution was correct, (again, the tests would verify that), Plus a simple misclick can reveal the answer.

**Comment by CouchofTomato** [comment]
Thanks @DigitalKnight0 

We can't entertain this for now because DS&A is undergoing a review for improvement anyway. https://github.com/TheOdinProject/top-meta/projects/6

It's a good idea though and once I'm sure is being considered for those new lessons.
