### ISSUE TITLE
Ruby 3.0 Upgrade

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/curriculum#23434]
**Description**
In order to upgrade to Ruby 3, I believe we would need to:
* Update the installation instructions in "Installing Ruby"
* Update any references to `2.7.4` in the curriculum
  - Such as links to documentation

I'm willing to take on both of these tasks. I have a Linux machine & a few MacOS devices I can try any updated instructions on.
Otherwise I'm willing to assist with anything needed.

**Additional Information**
This was discussed in the `#ruby-rails-general` channel of the Discord with @CouchofTomato just a few moments ago.
https://discord.com/channels/505093832157691914/690591236922409012/936906155932934164

**Comment by DigitalKnight0** [comment]
@Eduardo06sp i believe you meant ruby 3.0, not rails (typo)

**Comment by CouchofTomato** [comment]
All yours @Eduardo06sp

**Comment by Eduardo06sp** [comment]
@CouchofTomato I had two concerns when submitting the PR:
**1)** When installing Ruby in MacOS, the output received from typing `rbenv init` was:
```bash
eval "$(rbenv init - bash)"
```
However, TOP states ` bash` (space included) is not part of it.
Searching for answers led me to believe it's probably just an inconsistency with my particular mac.

**2)** I was going to update as many links as I could that reference `2.7.x`. They're all just documentation for Ruby methods anyways, but I felt this should be an entirely separate issue that wouldn't really affect upgrading to Ruby 3.

Please let me know if you suggest I do anything other than simply move forward with this. (And resolve any feedback I get in my pr, of course.)

**Comment by CouchofTomato** [comment]
Hey @Eduardo06sp 

On point 1 it may be because mac made the default shell zsh that the output is now different. I'm ok with you updating it. We can never be fully sure what the user will see and hope they'd be able to use common sense for when two messages are similar enough in output.

On point 2 I agree the links don't really need to be part of the same effort but I'd appreciate if you made an issue around that so we can ensure it's picked up. You aren't expected to take on the issue just because you created it but since you're creating it maybe just let us know in the issue if you want to be assigned it or not.

**Comment by Maheshkumar-novice** [comment]
We need to update `ruby version` file in the `ruby-exercises` repo also right?

**Comment by Eduardo06sp** [comment]
> We need to update `ruby version` file in the `ruby-exercises` repo also right?

Excellent catch, I didn't even know it was tracked.
I can do it myself, but I did notice you updated it last time.

If I were you, I'd straight up make the PR and reference the fact that installations updated to 3.0.3.
But I'm not a maintainer so I can't tell you what to do. :}

**Comment by CouchofTomato** [comment]
@rlmoser99 ^^ do we need to

**Comment by rlmoser99** [comment]
Yes, we update `ruby-exercises` and `ruby_testing` repos when the curriculum changes the version of ruby to be installed.

**Comment by Maheshkumar-novice** [comment]
Shall I update both?

**Comment by Eduardo06sp** [comment]
@Maheshkumar-novice don't forget to make a pr by pushing your feature branch, it doesn't seem that there's a contributing guide for both of the repos!
