### ISSUE TITLE
slight gramatical error in "form basic" chapter

### ISSUE THREAD

**Issue by Pratik-Karale** [TheOdinProject/curriculum#23453]
slight grammatical error in "checkboxes" section from "form basics" chapter of "intermediate html & css"
![image](https://user-images.githubusercontent.com/74715140/151745433-1b9c4633-09bb-49e6-9029-2b1ea4a90ad0.png)

line:
Checkboxes are similar to radio buttons in **that that** they allow users to choose from a set of predefined options.

probably the needed fix:
Checkboxes are similar to radio buttons as they also allow users to choose from a set of predefined options.

**Comment by zachmmeyer** [comment]
I took this on!
