### ISSUE TITLE
Edit codepen links to an imgur

### ISSUE THREAD

**Issue by jay4170** [TheOdinProject/curriculum#23454]
### Description
on https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/css-functions there is a link that looks like it is supposed to take us to a codepen page. It instead takes us to an imgur link picture of the codepen logo

What steps need to be taken in order to reproduce this bug?

Example:
1. Log in
2. Visit a [https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/css-functions)
3. Click the edit codepen link at the bottom of the calc() section
4. Be taken to imgur rather than codepen https://imgur.com/a/9iDhtL0

**Comment by thatblindgeye** [comment]
I will be closing this issue as it has already been reported in #23404
