### ISSUE TITLE
Typo in Foundations > Prerequisites

### ISSUE THREAD

**Issue by MasQueElite** [TheOdinProject/curriculum#23460]
In [https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/prerequisites](prerequisites), at:

> If you encounter an error requesting you to disable Intel RST while attempting to install Ubuntu, these instructions from Stack Exchange, specifically Choice `#2`.

The hyperlink text *"these instructions from Stack Exchange"* should be *"**follow** these instructions from Stack Exchange"*.

**Comment by DigitalKnight0** [comment]
@thatblindgeye i can fix this if no one is assigned

**Comment by thatblindgeye** [comment]
@DigitalKnight0 it's all yours!
