### ISSUE TITLE
Update Ruby docs to 3.0.3 / 3.0 links

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/curriculum#23465]
I noticed most of the links throughout the Ruby lessons contain links to 2.7 docs. 
The curriculum has just been updated to Ruby 3.0.3, so I think it would make sense to update all the linked documentation as well.

This was briefly discussed with @CouchofTomato in  #23434. 
Link to CouchofTomato's direct response (where he addresses point 2 of the conversation): https://github.com/TheOdinProject/curriculum/issues/23434#issuecomment-1025706387

I am willing to take this on, I only anticipate many commits as the docs are in many different lessons.

**Comment by CouchofTomato** [comment]
Thanks @Eduardo06sp
