### ISSUE TITLE
Add a custom enumerable example to the custom enumerable project for the ruby track.

### ISSUE THREAD

**Issue by linkonsat** [TheOdinProject/curriculum#23481]
One of the things I noticed while helping in the chat is that it seems a few people seem to have difficulty understanding how to use blocks and yield. I believe it may be useful to provide a detailed example in the custom enumerable projects as an example showing both the ```do...end``` and ``` {|a| does something with a }```. An example of that could be the sort enumerable in either the custom enumerable project page itself OR as the first example in the enumerable repo for learners to go over and refresh themselves on what a block is, where you could put yield within that block, and a walkthrough of how that is handled. 

I am also going to link this other issue since I believe that splitting this into two lessons/add exercises would help with making blocks more clear. #23482

**Comment by CouchofTomato** [comment]
Yeah that's not a bad shout at all mate.

@rlmoser99 @KevinMulhern Do you guys have an opinion on this?

**Comment by ChargrilledChook** [comment]
@linkonsat I've added an `On Hold` tag on the linked issue based on the discussion there. 

What would you like to do with this one? Although it's related, it seems like a much smaller scope so could be completed independently of that work

**Comment by linkonsat** [comment]
@ChargrilledChook I can go ahead and start working on the example. Although I would still want to break up the lesson when this section gets reviewed.

**Comment by CouchofTomato** [comment]
@linkonsat 

Hi mate,

Is this still something you plan on working on?

**Comment by linkonsat** [comment]
@CouchofTomato yup!

**Comment by CouchofTomato** [comment]
@linkonsat Nice. Thanks mate.
