### ISSUE TITLE
Update outdated links to ruby-exercises repo

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/curriculum#23491]
After changing from `master` to `main`, some of the links to the `ruby-exercises` repos are now outdated (but still functional w/ a notification of the change). 

So far, I've noticed it in:

* Assignment 3 Basic Data Types: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/basic-data-types
  - `ruby_programming/basic_ruby/basic_data_types.md`
* Assignment 3 Arrays: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/arrays
  - `ruby_programming/basic_ruby/arrays.md`
* Assignment 2 Hashes: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/hashes
  - `ruby_programming/basic_ruby/hashes.md`
* Assignment 4 Methods: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/methods
  - `ruby_programming/basic_ruby/methods.md`
* Assignment 4 Basic Enumerable Methods: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/basic-enumerable-methods
  - `ruby_programming/basic_ruby/basic_enumerable_methods.md`
* Assignment 2 Predicate Enumerable Methods: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/predicate-enumerable-methods
  - `ruby_programming/basic_ruby/predicate_enumerable_methods.md`
  
  I may have missed some.
  I will volunteer if it sits for a while, but I would like to give someone the opportunity to contribute.
  Briefly discussed with @thatblindgeye in the Discord (where he suggested I make a new issue).

**Comment by drossano** [comment]
I'd like to take this on.

**Comment by thatblindgeye** [comment]
@drossano You're assigned!

**Comment by Eduardo06sp** [comment]
@thatblindgeye I 100% don't mean to sound out of line here, but would it be a good idea to make the links point to the specified folder instead of just the main repo? Otherwise there's two links pointing to the main `ruby-exercises` repo in the same line.

E.g. `https://github.com/TheOdinProject/ruby-exercises/tree/main/ruby_basics/6_arrays`

Also the Basic Data Types lesson is redundantly telling you to follow the README for the main `ruby-exercises` and the README (again, same link) to complete the basic data types exercises. 

I do feel the last part is a little out of scope for this issue, so please let me know if you prefer I make these separate issues (as applicable).

**Comment by thatblindgeye** [comment]
@Eduardo06sp for your first point, it's merely a suggestion and doesn't come off as authoritative. That said, we should use whatever URL is present for that general directory rather than to a specific exercise directory (in this case for your example, `https://github.com/TheOdinProject/ruby-exercises/tree/main/ruby_basics`)

For your second point, both of those links look to be directing to two different README's: the first is the one to set things up, the other is on how to do/use the exercises.
