### ISSUE TITLE
intermediate-html-and-css/lessons/positioning typo and card heading improvement of the codepen

### ISSUE THREAD

**Issue by Pratik-Karale** [TheOdinProject/curriculum#23498]
the position value of card-heading has a typo & it doesnt have the "card-heading" feel to it...
![image](https://user-images.githubusercontent.com/74715140/152651062-fe6d9ad4-637e-4833-802e-38ed72e171ee.png)
this could be the card-heading style:
```
.card-heading {
  font-size:1.5em;
  font-weight:bold;
}
```

**Comment by thatblindgeye** [comment]
Thanks for mentioning this issue! It should be fixed now so I will be closing this.
