### ISSUE TITLE
wrong content in "/intermediate-html-and-css/lessons/css-functions"

### ISSUE THREAD

**Issue by webdevphilh** [TheOdinProject/curriculum#23493]
### Description

The content in said file has the wrong link. 
Instead of showing a codepen project it goes to a imgur image. 
It can be found at the end of the "calc()" section, right before the "min()" section begins.

Link:
https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/css-functions

**Comment by thatblindgeye** [comment]
Closing this as it has already been mentioned in #23404
