### ISSUE TITLE
Move Sandi Metz video from testing basics lesson to more testing lesson

### ISSUE THREAD

**Issue by LeoKirasic** [TheOdinProject/curriculum#23508]
Currently, the [testing basics lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/testing-basics) tells the learners to watch [this](https://www.youtube.com/watch?v=URSWYvyc42M) video as per assignment 5.

I think that it would be beneficial to move the video assignment to the [more testing lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/more-testing). 

Reasoning: testing can be confusing at first, and looking at examples of tests in the video would be more beneficial after the learners have done actual testing on their own. The assignment mentions how the video would be more beneficial coming back to after the learners have done testing on their own- that can be avoided by moving the assignment to the more testing lesson.

**Comment by CouchofTomato** [comment]
@rlmoser99 

Any thoughts on this?

**Comment by rlmoser99** [comment]
Since this is in the JavaScript path, I would want someone who has done that path to weigh in on this. On the ruby path, we have this resource later in the testing section and I have to agree with @LeoKirasic's reasoning.
