### ISSUE TITLE
Refactor Rock Paper Scissors Instructions

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/curriculum#23500]
Many learners have trouble interpreting the RPS instructions, which leads to poor outcomes in their code and anti-patterns. 

We should: 
- Refactor the instructions to change the language so `game()` does not hold declarations for `playRound` and other functions inside of it
- Show boilerplate for a simple `for` loop so they can have a better `game()` function instead of punting loops to a later lesson
- Update "Important note: you want to return the results of this function call, not console.log() them." to explain that we want to return the results so we may use them elsewhere

**Comment by scheals** [comment]
I'd love to work on this one if possible.

**Comment by twalton83** [comment]
Go for it.
