### ISSUE TITLE
html/css lessons in the fullstack tracks lacking knowledge check links

### ISSUE THREAD

**Issue by LeoKirasic** [TheOdinProject/curriculum#23509]
The following lessons in the new html/css content either don't have knowledge checks or don't have knowledge check links:

- Advanced selectors
- CSS Functions
- Browser Compatibility
- Introduction to Web Accessibility 
- The Web Content Accessibility Guidelines
- Semantic HTML
- Accessible Colors
- Keyboard Navigation
- Meaningful Text
- WAI-ARIA
- Accessibility Auditing
- Introduction to Responsive Design
- Natural Responsiveness
- Responsive Images

**Comment by thatblindgeye** [comment]
@wise-king-sullyman would this fall under the ongoing KC updates or is this fine as its own open issue?

**Comment by wise-king-sullyman** [comment]
@thatblindgeye these would definitely be KC updates, how best to go about them is maybe up for debate though.

@LeoKirasic by making this issue were you wanting to take them all on, or were you just pointing out that they're missing?

Thanks for calling out that they're missing btw.

**Comment by LeoKirasic** [comment]
@wise-king-sullyman I wanted to create the issue and see what you think the best way to go about it would be. I don't mind doing them, I also don't mind them being spread for everyone to contribute to.

**Comment by Ska0** [comment]
I wouldn't mind taking some of them, Will I have to write the knowledge checks text as well or just be setting up the links?

**Comment by wise-king-sullyman** [comment]
@Ska0 writing the Knowledge Check text if no Knowledge Checks exist already, but just adding links if the lesson already has Knowledge Checks.

**Comment by wise-king-sullyman** [comment]
@LeoKirasic this issue should be good to close then, correct?

**Comment by LeoKirasic** [comment]
@wise-king-sullyman Correct!

**Comment by wise-king-sullyman** [comment]
Closing because all of these items have been addressed, thanks @LeoKirasic and everyone else that helped with them!
