### ISSUE TITLE
Missing number or step in Setting Up Git lesson

### ISSUE THREAD

**Issue by lloydlobo** [TheOdinProject/curriculum#23515]
There is a minor inconsistency in numbering the points in "Setting Up Git" lesson, under "macOS" -> "step 1.2". 

Here's the [link](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/setting-up-git#step-12-verify-version) to the exact spot where this simple error is.

## **Issue:** 
- Point no. 3 is missing, while points 1, 2, and 4 are present.

## **Proposed Resolution:**
- Rename point no. "4." to "3."
- Someone with expertise can suggest where point no. 3. should be.

## Text For Reference
>If the version number is less than 2.28, follow the instructions again. If you are encountering a no formulae found in taps error: 1. Run brew doctor 2. You will see an output like the one below. NOTE: The actual output of brew doctor may vary based on the version of MacOS you’re running, and any other issues you may have with your own installation. Ultimately, you must run each command line snippet that Homebrew provides after running brew doctor to repair your installation of Homebrew, including brew cleanup at the end.
>![](https://cdn.statically.io/gh/TheOdinProject/curriculum/284f0cdc998be7e4751e29e8458323ad5d320303/foundations/installations/setting_up_git/imgs/00.png)
>4. Run brew install git, open a new terminal window, and then check your version of Git, which should now be the latest.

## Image for Reference
I hope this image helps clarify the doubt.

![TOP-Foundations-Setting-Up-Git_macOS-step-1 2](https://user-images.githubusercontent.com/76430758/153015474-01bf417b-650a-4d00-9621-ea100bf7240e.png)

**Comment by thatblindgeye** [comment]
In addition to what has been mentioned, whomever decides to work on this should also breakout these inner-steps that are part of the overall Step 1.2 so that they are a proper numbered list (rather than bunched up into a paragraph and easily lost).

**Comment by ronald-luo** [comment]
I would love to take this one!

**Comment by thatblindgeye** [comment]
@ronald-luo you got it!

**Comment by ronald-luo** [comment]
@thatblindgeye Thank you! This is my first contribution. I'm not too sure how to request reviewers for the last task.

**Comment by thatblindgeye** [comment]
@ronald-luo it looks like you linked your PR to this issue correctly so you should be good for now! A maintainer will eventually look over your PR and if they have any changes they'd like made they'll respond in the PR
