### ISSUE TITLE
Wording changes in Intermediate CSS Positioning lesson

### ISSUE THREAD

**Issue by pantbruin** [TheOdinProject/curriculum#23512]
Some minor wording changes should be made to the CSS positioning lesson introductory paragraph. This should be an easy fix for a first time contributor. [Lesson Link](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/positioning)

> By now you have had quite a bit of practice moving elements around the screen using things like margin, padding, flexbox, _**and grid.**_ 

The first sentence states that grid has already been learned at this point. This is incorrect--the grid section comes later. 

> This default positioning-mode is intuitive, and you’ll continue using it for almost all of your layout needs, **_however_**, there are other methods at your disposal that can be very useful in some situations.

This sentence is a run-on sentence. A semicolon/period should be placed before the word "however" to fix this. Further, it may help to give some quick examples of the "other methods" that the sentence is mentioning.

**Comment by LeoKirasic** [comment]
Hey, I can do this one !

**Comment by dm-murphy** [comment]
> Hey, I can do this one !

Assigned, thanks Leo!
