### ISSUE TITLE
CSS Funtions: min example has incorrect code snippet

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23537]
Related to #23490

In the CSS Functions lesson, the code snipped immediately following the `min()` CodePen example is incorrect. Screenshot show the CodePen code and the code snippet:

![Untitled](https://user-images.githubusercontent.com/70952936/153513668-2b5fb762-f97f-4f23-9286-c1854fdab452.png)

The code snippet after the codepen should be replaced with the `#iconHolder` declaration block instead.

**Note:** This issue is being held for another contributor currently. If it opens up a Help Wanted label will be attached.

**Comment by Funk3** [comment]
I’d like to do this!

**Comment by liridonloku** [comment]
Hi @thatblindgeye, I'd like to make this change.
