### ISSUE TITLE
inconsistency across additional resources patterns

### ISSUE THREAD

**Issue by DigitalKnight0** [TheOdinProject/curriculum#23533]
I noticed that some lessons are missing the additional resources section such as [this one](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/introduction), 
While some of them have empty ones such as [this](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/tic-tac-toe)
Then there are some which have the tagline "this section is......" such as [this](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/basic-data-types) 
while some don't like this one [here](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/intermediate-html-and-css/lessons/form-validation)
I know there were PRs opened before to remove the empty additional resource sections too but they were closed since it was decided that the section should be present regardless of the content.

My point is, there is a bit too much diversity and lessons follow quite a different pattern when it comes to Additional resources. It would be helpful if they were updated to use the same pattern across the site.
(Happy to work on this too)

**Comment by thatblindgeye** [comment]
This is something that, along with some other things, will be in the works for fixing (keep an eye out!) Since there are several lessons mentioned here, and because it is something that is being worked on, I'm going to close this issue, but thank you for keep an eye out on this sort of stuff!
