### ISSUE TITLE
note on each code pen to zoom in & out b/w 0.25x , 0.5x & 1x in /intermediate-html-and-css/lessons/advanced-grid-properties

### ISSUE THREAD

**Issue by Pratik-Karale** [TheOdinProject/curriculum#23557]
*very minor enhancemnt*
when going through the lesson i had to figure out why werent few grid containers spanning properly. it took me a while to find out that it can be seen working if adjust the zoom option of the codepen output.
ps:we can also use inform them on every code pen to use the drag and drop function of the main container

output in 1x:
![image](https://user-images.githubusercontent.com/74715140/153758667-6513a9ba-7c22-4fd9-a235-63785024d4c9.png)
same output in 0.25x:
![image](https://user-images.githubusercontent.com/74715140/153758709-b7fcfefc-9614-4868-9ce6-8b5eef0fecee.png)

suggestion for fix: add small p tag at start of the body of html in each codepen reminding user to scale the the result part to diff zoom sizes

**Comment by thatblindgeye** [comment]
I really don't think we should be reminding users about this with every Codepen, just because that's *a lot* of repeated information that users most likely won't need to be reminded of beyond the first time they discover it.

I'm actually unsure if a reminder should really be included at all. Willing to leave this open for a few days to see if there are any other strong opinions either way on this.

**Comment by 01zulfi** [comment]
Zooming out is imperative in the CodePen examples for this lesson. Going through this lesson, it took me some time to figure out why the CodePen isn't showing what the lesson is trying to describe. 

The lesson does have a suggestion that "[viewing at 0.5x or 0.25x would do us well](https://github.com/TheOdinProject/curriculum/blob/main/html_css/grid-lessons/advanced_grid_properties.md?plain=1#L36)". I think it should be put out into its own paragraph with verbiage changes and bold text. Something like:

"**Make sure to zoom out to 0.25x or 0.5x and use your cursor to resize the grid container to see the changes live.**"

**Comment by thatblindgeye** [comment]
That can work. Rather than bolding the entire line, though, just using an inline heading (`**Change Zoom Levels:** ...` or something). I think we could be utilizing inline headings more often like this.

**Comment by wise-king-sullyman** [comment]
I see that this issue has been stagnant for a while now but a solution was proposed, @Pratik-Karale were you wanting to be the one to apply the solution @thatblindgeye suggested?

**Comment by Pratik-Karale** [comment]
> I see that this issue has been stagnant for a while now but a solution was proposed, @Pratik-Karale were you wanting to be the one to apply the solution @thatblindgeye suggested?

Apologies, I won't be able to due to my incapability to use Github and git to a certain extent. I do not want to make any harm to this project. I'm still learning how git rebase works...

but having a comment in the codepen code or having a better note similar to `***Try resizing/zooming the output  window***` would help reduce confusion for people who are just getting started with the topic.

**Comment by wise-king-sullyman** [comment]
@Pratik-Karale since we would need to review the PR that is made you shouldn't need to worry about hurting anything, but if you're not feeling up to it at the moment that is, of course, fine!

Thanks for making this issue 🙂
