### ISSUE TITLE
Split JS basics - foundations

### ISSUE THREAD

**Issue by Maheshkumar-novice** [TheOdinProject/curriculum#23568]
Source: [JS Basics](https://www.theodinproject.com/paths/foundations/courses/foundations#javascript-basics)

Currently we have 15 lessons in the JS basics of foundations. It looks like too much lessons packed in one section. It feels a little overwhelming.

Suggestion is to split JS basics into 2 parts:

```
JavaScript Basics 1
1. Fundamentals Part 1
2.....
7. Project: Rock Paper Scissors
```

```
JavaScript Basics 2
1. Clean Code
2.....
8. Project: Calculator
```

**Comment by Maheshkumar-novice** [comment]
-  If there are too much lessons under one section, learners may feel overwhelmed. If we have 2 sections, after finishing one section, a learner may gain more confidence before moving on to the other section.
 -  It'll be easier to navigate to the lessons in the site.
 - It'll be easier to manage the lessons as well, in case we are adding new lessons to the section.
- It'll give a nice look and feel, if we split it.

**Comment by Maheshkumar-novice** [comment]
> It'll be easier to manage the lessons as well, in case we are adding new lessons to the section.

If we add a new lesson, we need to look into entire section to see where it'd fit. If we have 2 sections, the work will become less. Because we know 1st section will contain more basics than the 2nd section. It's not a big benefit anyway.

> It'll be easier to navigate to the lessons in the site.

Sorry. I shouldn't have put this point. I don't have a solid reason for this.

> I'm not personally sold on this particular benefit. I would consider that adding a section might make it seem longer.

As section count will increment only one, It may not look much longer I guess. Because we will have 2 smaller sections. But if we add another lesson to current js basics (Not sure we will add or not) it'll make our current section too long.

Yeah. As you told there is more aesthetic benefits than user benefits. 

Thank you for taking time to respond. I appreciate it. We can go with the decision that gives learners a good learning experience.

**Comment by twalton83** [comment]
I’m not shooting it down, just trying to understand btw.

**Comment by Maheshkumar-novice** [comment]
Yeah. I understood. It's a good experience for me to create issues more clearly in future.
