### ISSUE TITLE
Curriculum mention in Readme is confusing

### ISSUE THREAD

**Issue by Maheshkumar-novice** [TheOdinProject/curriculum#23571]
![why?](https://user-images.githubusercontent.com/67100964/153905163-c03ac178-9bcb-4449-8115-3680207baf9c.png)

Source: [Curriculum Repo Readme](https://github.com/TheOdinProject/curriculum#the-odin-project---javascript-curriculum)

We can see we have a heading `The Odin Project - JavaScript Curriculum` but the content under the heading is common to both the paths covered by TOP. 

Suggestion is to change the heading to `The Odin Project Curriculum` or other better suggestions.

**Comment by 01zulfi** [comment]
@Maheshkumar-novice Thanks for bringing this up. The README as a whole is need of an update and it is being addressed in this PR: #23587
