### ISSUE TITLE
curriculum/foundations/html_css/project/odin-project.png: copyright is out of date

### ISSUE THREAD

**Issue by jakobfrederikson** [TheOdinProject/curriculum#23590]
![Screenshot from 2022-02-15 11-47-49](https://user-images.githubusercontent.com/63636667/153959552-70db9a64-6921-42dc-a355-2f25eb565107.png)
Not sure if this is all too important, but the copyright says 2021 in 2022 :)
Image was downloaded from https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/landing-page under **Assignment**. I assume it would also need to be updated in https://github.com/TheOdinProject/curriculum/blob/main/foundations/html_css/project/html-css-foundations-project.md as well

**Comment by fortypercenttitanium** [comment]
@jakobfrederikson Can you post this in https://github.com/TheOdinProject/theodinproject/issues ? This is an issue with the website, not curriculum.

Thanks.

**Comment by fortypercenttitanium** [comment]
Ignore my previous comment. I'm looking into this. Thank you.

**Comment by fortypercenttitanium** [comment]
Thanks for the heads up. I don't think this issue is necessary to tackle. Reuploading this image every year would be tedious and unnecessary, as its purpose is to just provide a template for learners to execute the styling and markup of a web page.
