### ISSUE TITLE
CSS Foundations: Introduction - Addition of Specifishity page for an in-depth understanding of CSS selectors

### ISSUE THREAD

**Issue by Ashvith** [TheOdinProject/curriculum#23593]
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `where the change occurs: brief description of request` format, e.g. `Global SCSS file: Buttons should have XYZ`

- [ ] I would like to be assigned this issue to work on it

**1. Description of the Feature Request**
Adding this page would help a lot of newbie developers who are still struggling with the concept of specificity.

**2. Additional Information**
The part about specificity of CSS is pretty confusing even for an experienced developer. Adding this resource would improve the understanding of how CSS selectors work.

Link to Specifishity - [Specifishity::Specificity with Fish](https://specifishity.com/)

**Comment by wise-king-sullyman** [comment]
I don't feel that this resource delivers information all that well, and our CSS specificity content has been improved since this issue was opened so I'm going to close it. Thank you for taking the time to file this issue though!
