### ISSUE TITLE
 CSS Foundations: Block and Inline - Add additional resources about margin collapse

### ISSUE THREAD

**Issue by Ashvith** [TheOdinProject/curriculum#23614]
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [ ] The title of this issue follows the `where the change occurs: brief description of request` format, e.g. `Global SCSS file: Buttons should have XYZ`

- [ ] I would like to be assigned this issue to work on it

**1. Description of the Feature Request**
A small but interesting topic might have been left behind, which is margin collapse. Adding this would prove to be beneficial.

**2. Additional Information**
More information available at [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing).

**Comment by umprej** [comment]
The topic of margin collapsing is mentioned in the the assignment part of the the previous lesson, [The Box Model](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/the-box-model), linking to this [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model) page.

I agree that it's an interesting topic that might warrant being expanded upon in the main text.

**Comment by LeoKirasic** [comment]
Learners will encounter margin collapsing twice in the previous lesson. Both on MDN and on css tricks. The "mastering margin collapsing" is linked in the MDN article that the learners have to do as an assignment as well, so if they are interested, they can further expand upon that.

Closing as we want to avoid redundancy.
