### ISSUE TITLE
Hooks: React JS section - Add React docs beta in Additional Resources

### ISSUE THREAD

**Issue by DaeguDude** [TheOdinProject/curriculum#23632]
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `where the change occurs: brief description of request` format, e.g. `Global SCSS file: Buttons should have XYZ`

- [x] I would like to be assigned this issue to work on it

**1. Description of the Feature Request**

In [React JS section](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript#react-js) first 5 lessons are focused on class based React, and Hooks lesson is the first lesson transitioning to the Functional based React.

Although React Main documentation is linked to read in the Assignment, since [React docs beta](https://beta.reactjs.org/) is solely focused on React hooks and all the explanations about React are written using hooks, I think it could serve as a great additional resource along with React Main documentation.

And I think it has some of the advantage over the main documentation for the people who first encounters hooks, which is
- Interactive examples and helpful illustrations
- It has exercises at the end to check the knowledge

**2. Additional Information**

Downside I can think about React Docs beta is, it's not complete and doesn't have a lesson on lifecycle methods, which should be used in Memory card project.

**Comment by 01zulfi** [comment]
React Docs Beta would be an amazing addition to the curriculum. 

The [existing React doc](https://reactjs.org/docs/hooks-intro.html) we link to explains the transition to functional components over class based components. Considering our React curriculum does the same (i.e focus on class-based components then transition to functional based), we can't really replace it.

Let's add it as an additional resource to the [Hooks lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/hooks). If we can pinpoint some beta doc articles that will be useful to read at that point in the curriculum, we can add them to the assignment section as well.

Furthermore, I'm thinking of adding a brief section on [Context API](https://reactjs.org/docs/context.html) in the [Advanced Concepts lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/advanced-concepts). There we can add a link to the [Managing State section on the beta docs](https://beta.reactjs.org/learn/managing-state). What do you think about this?

> Downside I can think about React Docs beta is, it's not complete and doesn't have a lesson on lifecycle methods, which should be used in Memory card project.

Can you elaborate on what you mean by this?

**Comment by DaeguDude** [comment]
> Furthermore, I'm thinking of adding a brief section on [Context API](https://reactjs.org/docs/context.html) in the [Advanced Concepts lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/advanced-concepts). There we can add a link to the [Managing State section on the beta docs](https://beta.reactjs.org/learn/managing-state). What do you think about this?

I think it is really a great idea. [Context API in main React docs](https://reactjs.org/docs/context.html) is mix with class and function components, so it could confuse the learner who first encounters Context API. On the other hand, Context API in beta docs goes more in the linear fashion, therefore it is easier to understand. But do you think it's better to just link to the lesson '[Passing Data deeply with context](https://beta.reactjs.org/learn/passing-data-deeply-with-context)' or whole '[Managing state section](https://beta.reactjs.org/learn/managing-state)'?

> Downside I can think about React Docs beta is, it's not complete and doesn't have a lesson on lifecycle methods, which should be used in Memory card project.

The [memory card](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/memory-card) project in TOP right after hooks lesson, says we should use hooks or lifecycle methods as well as a lot of state. In functional based component, we could handle lifecycle method in `useEffect`, and Main react docs has a [`useEffect` documentation](https://reactjs.org/docs/hooks-effect.html). However, if you go to react docs beta, it didn't cover [useEffect](https://beta.reactjs.org/apis/useeffect) yet. So what I meant was we couldn't really replace React Main docs with beta docs, but just having it additional would be a good option.

**Comment by 01zulfi** [comment]
> But do you think it's better to just link to the lesson '[Passing Data deeply with context](https://beta.reactjs.org/learn/passing-data-deeply-with-context)' or whole '[Managing state section](https://beta.reactjs.org/learn/managing-state)'?

I'm fine either way :smile:. I'll create a separate issue later for adding a section on Context API with a "Help Wanted" label. If you want to work on that, feel free to comment on it (assuming someone else doesn't get there first).

> The [memory card](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/memory-card) project in TOP right after hooks lesson, says we should use hooks or lifecycle methods as well as a lot of state.

Thanks for elaborating here. I believe we should reword how the memory card presents this sentence.  Something like this: "The main goal of this project is to use hooks for lifecycle as well as state." Does this sound better? If so, would you be up for making a PR for this as well?

_____

Anyways, I've assigned you this issue. Let's add the beta docs to the hooks' additional resources. 🚀

**Comment by DaeguDude** [comment]
Okay! I will work on it and make a PR. 

>  Something like this: "The main goal of this project is to use hooks for lifecycle as well as state." Does this sound better? If so, would you be up for making a PR for this as well?

Yeah about this, I think both seems okay. After working on this I can make a PR about this and discuss there :)
