### ISSUE TITLE
Ruby Debugging: Update Lesson

### ISSUE THREAD

**Issue by mgrigoriev8109** [TheOdinProject/curriculum#23633]
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `where the change occurs: brief description of request` format, e.g. `Global SCSS file: Buttons should have XYZ`
- [x] I would like to be assigned this issue to work on it

**1. Description of the Feature Request**
This feature will update the Ruby Debugging lesson to include the VSCode integrated Ruby debugger. 

This update would make debugging Ruby projects quicker, and simpler through the use of a new debugging tool. 

This should help reduce the number of questions in the #ruby-help channel, by making it easier for learners to debug whichever projects they struggle with the most. 

**2. Additional Information**
I think this can be a short addition towards the very end of the [Debugging lesson](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/debugging). 
Since this is already a lengthy lesson, and learners got to learn about concepts such as Watch, Scope in the Foundations [Javascript Developer Tools lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/javascript-developer-tools), my thoughts are that the new information can be concise.

At a minimum I was thinking this addition could include: 
1) How to install the necessary gems and set up VSCode Ruby Debugger
2) How to set breakpoints and watch a variable. To save space this can even be done using the last example in the lesson's pry-byebug section. 
3) A brief mention regarding using `binding.break` to run pry *within* the VSCode debugger.

**Comment by rlmoser99** [comment]
In thinking about this issue, I want to make sure that this lesson keeps a few examples of using binding.pry, because it will be valuable to know it exists. This is important because when one gets a job, it is likely that they will be using a older version of ruby that does not support the new debugger. 

Feel free to make a PR that is a work in progress to get feedback before fine-tuning it too much.
