### ISSUE TITLE
react-js: Add section on Context API in Advanced Concepts lesson

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23646]
**1. Description of the Feature:**

It's worth having a section on Context API in [React's Advanced Concepts lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/advanced-concepts). This section should briefly go over the API and why it's useful.

Relevant Issue: #23632 

**2. Acceptance Criteria:**

- [ ] Add a heading called "Context API" right after Redux on the list under [Guide to Advanced React section](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/advanced-concepts#guide-to-advanced-react). Context API should be the number four on the list.
- [ ] Briefly explain what is Context and why we might need it (e.g to avoid "prop drilling").
- [ ] Briefly go over some use-cases. For example. provide theming or user information to deeply nested components.
- [ ] Link to the [Passing Data Deeply with Context page on React docs beta](https://beta.reactjs.org/learn/passing-data-deeply-with-context). Also invite users to further explore the beta docs.

**3. Additional Information:**

If anyone wants to work on it, comment on this issue to be assigned. I'm happy to concede to a better implementation, so feel free to suggest anything that makes the lesson better!

**Comment by Ishmam156** [comment]
I would like to take this one if someone else hasn't already been assigned to it :)

Just a small discussion point, @01zulfi, what if the section of Context API comes right after the Redux section, which is currently number 3 as they share some similarities instead of it being at number 7? Or even number 6 feels a bit more flowy to me and then after this the last can be `more hooks`.

**Comment by 01zulfi** [comment]
> Or even number 6 feels a bit more flowy to me and then after this the last can be more hooks.

According to the acceptance criteria, Context will be placed at number 6. But upon re-reading the Redux section, I do feel Context should come right after it. I've updated the acceptance criteria to place Context at number 4 (after Redux).

You've been assigned. Thanks for taking this on!
