### ISSUE TITLE
Sign-up form project: Incorrectly assumes knowledge about :focus 

### ISSUE THREAD

**Issue by NotAtec** [TheOdinProject/curriculum#23643]
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `where the change occurs: brief description of request` format, e.g. `Global SCSS file: Buttons should have XYZ`

- [x] I would like to be assigned this issue to work on it

**1. Description of the Enhancement**

On the [Sign up Form](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/intermediate-html-and-css/lessons/sign-up-form) Project, Step 3.4 requires to use a `focus` class to give a different styling to the existing form (specifically a blue border). It also mentions this isn't best practice, and that you'll learn how to in a later lesson.

This seems incorrect to me, since in the lesson on [Advanced Selectors](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/intermediate-html-and-css/lessons/advanced-selectors) the `:focus` pseudo-class is already mentioned, so knowledge about this subject should be known to the student when starting the sign-up form project.

**2. Additional Information**

A possible addition to the fix would be to link back to the relevant lesson in the assignment, but this wouldn't match the way previous projects work, so my preference / recommendation would be to just mention the fact that you should add the blue border styling to the relevant `:focus` subclass

**Comment by thatblindgeye** [comment]
I would agree that the verbiage does not currently make sense any more with the order of lessons. I also don't think linking back to a previous lesson is bad per se, though whether it *needs* to be linked to here I don't have strong feelings on.

I also agree that users should instead be using the `:focus` pseudoclass instead of a focus class. I've assigned you the issue to work on if you'd still like to, @NotAtec

**Comment by NotAtec** [comment]
Awesome, i'll start working on it right away
