### ISSUE TITLE
Bug - Ruby debugging section: Stack trace should be reversed

### ISSUE THREAD

**Issue by Flinner** [TheOdinProject/curriculum#23649]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

If I do work on it, are my screenshots accepted? or should i change my theme to match the one used on the site  (if so what is the theme's name)?

<hr>

**1. Description of the Bug:**
TOP site's image:
![image](https://user-images.githubusercontent.com/85732279/155433587-decdb5d0-874b-438f-b334-7962f8d081d3.png)
Output on my machine:
![image](https://user-images.githubusercontent.com/85732279/155433614-d8a9939b-b052-40df-ae8a-e3d7f94ec7cb.png)

**2. How To Reproduce:**
Check this page:
https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/debugging#reading-the-stack-trace

**3. Expected Behavior:**

according to TOP:
```
ERROR MESSAGE
stack trace
```
on my machine:
```
stack trace
ERROR MESSAGE
```

**5. Additional Information:**
This change is caused by an update to ruby
https://engineering.freeagent.com/2017/12/21/ruby-2-5-how-is-that-backtrace/

**Comment by Maheshkumar-novice** [comment]
@Flinner 

I agree. That image's stack trace doesn't match the one ruby 2.7.4 produced.

Our curriculum's ruby version currently changed to 3.0.3. Looks like they reversed the stack trace again in ruby version 3. Can you verify that? But there is a difference in output of ruby version 3's stack trace and the one in the curriculum. But they both follow `Message & Stack trace` order.

![stack](https://user-images.githubusercontent.com/67100964/155473088-9d93193d-1ee6-44f4-8e68-0e8230664d81.png)

**Comment by Flinner** [comment]
yes it got reversed in v3, do i close the issue?

**Comment by Maheshkumar-novice** [comment]
> yes it got reversed in v3, do i close the issue?

It reversed but you can see there is a slight difference in stack trace order between the one in the curriculum and current ruby v3 trace.

**Comment by CouchofTomato** [comment]
I don't mind the image being updated to the latest ruby 3 output if anyone wants to take that on

**Comment by Maheshkumar-novice** [comment]
> I don't mind the image being updated to the latest ruby 3 output if anyone wants to take that on

Okay. :+1: 

@Flinner Can you take that on?

**Comment by Flinner** [comment]
whoops closed the issue,
don't think i can do it this month, I think someone else can take it

**Comment by Maheshkumar-novice** [comment]
> whoops closed the issue, don't think i can do it this month, I think someone else can take it

Okay :+1:  I will update it. Thanks for bringing this up!

**Comment by Maheshkumar-novice** [comment]
Update: I'll make a PR on or before next Sunday.

**Comment by Maheshkumar-novice** [comment]
Sorry for the late response....I think I can't make it. If anybody is interested, they can take it.

**Comment by Maheshkumar-novice** [comment]
Working on it.

**Comment by CouchofTomato** [comment]
Might be nice to provide the update to show the latest version of ruby but I agree it's not a priority. Happy to merge if someone wants to pick this up though.

**Comment by ChargrilledChook** [comment]
Closed by #24267
