### ISSUE TITLE
Bug - React section - Hooks: Broken link in Additional Resources

### ISSUE THREAD

**Issue by IlyaEru** [TheOdinProject/curriculum#23651]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The Link to the first Additional Resource is broken
![broken](https://user-images.githubusercontent.com/95101177/155522500-d8e5788f-a495-4ef9-a795-4ae2fcfbf2a0.png)

**2. How To Reproduce:**

1. Go to HOOKS lesson in React
2. Click on the first Additional Resource Link

**3. Expected Behavior:**

1. Go to HOOKS lesson in React
2. Click on the first Additional Resource Link
3. The site Shows correctly

**4. Desktop/Device:**

-   Device:  PC
-   OS:  xubuntu
-   Browser:  Chrome
-   Version:  98

**Comment by LeoKirasic** [comment]
Hey, @IlyaEru. Thanks for creating an issue.

If someone wants to work on this, please comment on this issue and I'll assign you.

What needs to be done:

- Go to the [Web Archive](https://web.archive.org/) website and input the url of the first additional resource.
- Find a date with a working snapshot and copy its url.
- Follow the [Contributing guide](https://github.com/TheOdinProject/curriculum/wiki/Contributing-Guide) and replace the additional resource link with the one received from the Web Archive website.

**Comment by LeoKirasic** [comment]
@BlizZard-bot Assigned. Thank you!
