### ISSUE TITLE
Bug - Foundations PROJECT ETCH-A-SKETCH : broken link

### ISSUE THREAD

**Issue by hugompt** [TheOdinProject/curriculum#23659]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The 1st link under the Assignment is broken, see below:
![image](https://user-images.githubusercontent.com/99179407/155814067-7858b54c-d083-42b5-9edf-111fe82e98b3.png)
![image](https://user-images.githubusercontent.com/99179407/155814162-9b422977-aebe-4fe5-b2e1-5563ed8c0df4.png)

**2. How To Reproduce:**

1. Log in
2. Visit the lesson Foundations PROJECT: ETCH-A-SKETCH page
3. Click the link [reference the Commit Message lesson here](https://www.theodinproject.com/paths/html_css/html-foundations/commit-messages.md)!
4. The link is broken

**3. Expected Behavior:**

1. Log in
2. Visit the lesson Foundations PROJECT: ETCH-A-SKETCH page
3. Click the link [reference the Commit Message lesson here](https://www.theodinproject.com/paths/html_css/html-foundations/commit-messages.md)!
4. The link would open a new tab with the proper page being displayed

**4. Desktop/Device:**

-   Device: MacBook Pro 
-   OS: macOS 12.0.1 
-   Browser: Brave 
-   Version: [Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) 

**5. Additional Information:**

**Comment by zachmmeyer** [comment]
Fixed with #23660

**Comment by hugompt** [comment]
This was fast, thanks for the speedy action!
