### ISSUE TITLE
Bug - Testing basics in JS lesson: Unrelated questions from a future lesson and link to that lesson's assignment

### ISSUE THREAD

**Issue by twentysixhugs** [TheOdinProject/curriculum#23669]
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

- In this lesson's knowledge checks https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/testing-basics#knowledge-check, the last four questions are related to a different lesson - https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/more-testing, and link to the video from this lesson's assignment (the fifth one) https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/more-testing#assignment
It is not covered in the Testing Basics lesson, but it *is* covered in the More Testing lesson.

![Screenshot from 2022-02-27 17-51-35](https://user-images.githubusercontent.com/70529223/155887274-10c27a17-f10d-49a2-8eb1-07732f29dd9d.png)

**2. How To Reproduce:**

1. Log in
2. Visit the lesson page https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/testing-basics
3. Go to knowledge checks
4. Read the last four questions. Open the link in one of them.

**3. Expected Behavior:**
1. Log in
2. Visit the lesson page
3. Open knowledge checks
4. There are no unrelated questions. They are moved to the More Testing lesson that they originate from.

**Comment by LeoKirasic** [comment]
@BlizZard-bot Great. go for it!
