### ISSUE TITLE
Bug - a-deep-look-at-Git:`## Header` not displaying properly in TOP markdown

### ISSUE THREAD

**Issue by khunhour** [TheOdinProject/curriculum#23667]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Using `## Header` does not display properly on TOP Markdown. However, It does display properly on Github Markdown

**2. How To Reproduce:**

1. Visit the A Deeper Look at Git [lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/a-deeper-look-at-git)
2. Take a look at one of the sub-header. eg: Changing the Last Commit

**3. Expected Behavior:**

It should display with a bigger font smaller then those headings used with `###`

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: [Chrome]
-   Version: 

**5. Additional Information:**

**Comment by 01zulfi** [comment]
Thanks for creating this issue. Looks like it's already being addressed in https://github.com/TheOdinProject/curriculum/pull/23664/.
