### ISSUE TITLE
Bug - : Project: Restaurant Page wrong command

### ISSUE THREAD

**Issue by eltonbautista** [TheOdinProject/curriculum#23687]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Preface: I don't think it's a bug, but "bug" seemed more appropriate than "feature request", please advise me on how to post about similar posts in the future, thanks!

https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/restaurant-page

The first command in step 1 _npm init_ does not generate a package.json file but rather starts a walk through of how to create one. I believe the command is supposed to be _npm init -y_ which is the same one shown on the referenced webpack tutorial. I'm not sure if this is an issue on my end (due to my OS or something, though I use Xubuntu booted with a VM as per TOP instruction). 

**2. How To Reproduce:**

1. Go into project directory. 
2. Type 'npm init'.
3. Generating package.json file walk through initiates.

**3. Expected Behavior:**

1. Go to project directory
2. Type 'npm init'
3. package.json file is generated.

**4. Desktop/Device:**

-   Device:  PC
-   OS:  Xubuntu
-   Browser:  Chrome
-   Version:  

**5. Additional Information:**

**npm init**
![image](https://user-images.githubusercontent.com/94667178/156408529-662b9968-c0fa-4f07-9d60-a19627495f70.png) 

**npm init -y**
![image](https://user-images.githubusercontent.com/94667178/156408652-12db09bd-d510-48a8-af07-e4f5919e5e0c.png)

**Comment by LeoKirasic** [comment]
@eltonbautista Although I understand where you're coming from, having it this way could be beneficial to the learner because they get the hands on knowledge of how both commands work and how they differ, and since it's an actual project, not a lesson like when it gets introduced it could be useful for the learners to be able to input the information that they want from the CLI.

**Comment by eltonbautista** [comment]
Right that makes sense, I was a bit thrown off by the description of Step 1(1) since I expected to run "npm init" and have it generate a package.json file since that's what it claims will happen, but rather I was hit with something unfamiliar. I wasn't really sure how to proceed with it so I just ended up killing the process and defaulting to "npm init -y", was this something that was already covered because I certainly had no recollection of what steps to take afterwards - though maybe that's the teaching moment that it's trying to provide. Thanks for the response!

**Comment by LeoKirasic** [comment]
@eltonbautista It's mentioned in the ES6 Modules lesson. I think we would want to keep it the way it is.

**Comment by eltonbautista** [comment]
I must have missed it in the ES6 Modules Lesson, I tend to do that! Just thought I would bring it up, didn't think it was a **real** issue. Thanks!
