### ISSUE TITLE
Ruby's How this course will work: Remove optional Ruby materials

### ISSUE THREAD

**Issue by dm-murphy** [TheOdinProject/curriculum#23694]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Remove the full section of "Optional Ruby Materials" from the How This Course Will Work lesson in the Ruby curriculum. The Odin Project's Rails maintainers believe these supplemental resources are no longer needed in the introductory lesson and should not pull focus away from learners starting our own Ruby curriculum. 

**2. Acceptance Criteria:**

- [ ] Remove Optional Ruby Materials sub-header
- [ ] Remove the description and all three list items
- [ ] Keep the final sub-header "Okay, enough talk. Let's learn Ruby!"

**3. Additional Information:**

Issue suggestion brought up by Mike (msespos) here: https://discord.com/channels/505093832157691914/540903304046182425/947533494681206874

**Comment by dm-murphy** [comment]
@msespos please leave a comment here if you are still up for this PR and I can assign the issue to you. Thanks again for bringing this one up for discussion!

**Comment by msespos** [comment]
Happy to do this PR - thanks for the opportunity @dm-murphy !
