### ISSUE TITLE
CSS bundling lesson: Fix typo on line 59

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23716]
### Description

There's a typo on [line 59 in css_bundling.md](https://github.com/TheOdinProject/curriculum/blob/main/rails_programming/rails_sprinkles/css_bundling.md?plain=1#L59). "everytime" should be change to "every time".

### Acceptance Criteria

- [ ] Change "everytime" to "every time"

### Additional Information

Please comment on this issue to be assigned. Only start working on the pull request after you've been assigned.

**Comment by samuelisch** [comment]
I'd like to work on this issue please @01zulfi

**Comment by 01zulfi** [comment]
Thanks, assigned!

**Comment by samuelisch** [comment]
Thank you, I've sent a pull request to close this issue, do let me know if there's any problems with it!
