### ISSUE TITLE
Turbo lesson: Fix typo on line 348

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23715]
### Description

There's a typo on [line 348 in turbo.md](https://github.com/TheOdinProject/curriculum/blob/main/rails_programming/rails_sprinkles/turbo.md?plain=1#L348). "initally should be "initially".

### Acceptance Criteria

- [ ] Change "initally" to "initally"

### Additional Information

Please comment on this issue to be assigned. Only start working on the pull request after you've been assigned.

**Comment by samgliu** [comment]
I would like to learn to fix it as my first contribution practice. Thank you.

**Comment by 01zulfi** [comment]
Thanks, assigned!

**Comment by samgliu** [comment]
I've sent a pull request to close this issue. If it has any issues, please let me know. Thanks.
