### ISSUE TITLE
Bug - In curriculum/html_css/project_media.md [Dead Links & Markdown]

### ISSUE THREAD

**Issue by khitermedachraf** [TheOdinProject/curriculum#23732]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

There are some Dead Links as strings and it needs a good markdown.

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by LeoKirasic** [comment]
Hey, @khitermedachraf. Thanks for creating that issue. However, that lesson isn't a part of the curriculum anymore and is in the archived directory now. 

Going to close the issue because of that.

**Comment by khitermedachraf** [comment]
Okey dear brother
