### ISSUE TITLE
Bug - : Un-escaped </span> elements in ROR SESSIONS COOKIES, AND AUTHENTICATION lesson

### ISSUE THREAD

**Issue by Magmusacy** [TheOdinProject/curriculum#23733]
Complete the following REQUIRED checkboxes:
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

On this lesson : https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/sessions-cookies-and-authentication there are about 4 un-escaped `</span>` elements, which are only visible on this site, but not inside the markup file itself.

**Comment by 01zulfi** [comment]
Thank you for pointing this out. As far as I can tell, it's most likely the line breaks that cause this.

Here's the acceptance criteria:

- [ ] Navigate to [sessions_cookies_authentication.md](https://github.com/TheOdinProject/curriculum/blob/main/rails_programming/forms_and_authentication/sessions_cookies_authentication.md).
- [ ] Move the ending tag of  `<span id="flash-message">` on the same line. Currently, it's on line 78, while the ending tag is on line 92.
- [ ] Move the ending tag of  `<span id="login-check">` on the same line. Currently, its's on line 94, while the ending tag is on line 107.
- [ ] Move the ending tag of `<span id="http-authentication">` on the same line. Currently , it's on line 125, while the ending tag is on 129.
- [ ] Move the ending tag of `<span id="using-devise">` on the same line. Currently, it's on line 165, while the ending is on line 167.

If anyone wants to work on this, please comment below to be assigned!
