### ISSUE TITLE
Bug - Javascript : In OOP Principles, #2 Resource in Assignment is a dead link.

### ISSUE THREAD

**Issue by bananabread08** [TheOdinProject/curriculum#23730]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
In OOP Principles lesson, right before the Todo List project, [How to Write Highly Scalable and Maintainable JavaScript: Coupling](https://medium.com/@alexcastrounis/how-to-write-highly-scalable-and-maintainable-javascript-coupling-c860787dbdd4) is already deleted by the author in the Assignments section. Due to this, the link in Knowledge Check also doesn't work. This assignment needs to be replaced which talks about coupling (tightly and loosely coupled objects). Either replace or remove it completely. Replacing it is better since being familiar with coupling is really good for the Todo List project where each Project object and their respective todos need to be cohesive.

I will check some good reads if there's any. I can do the change if someone can find a good resource for it as a replacement.

**Comment by LeoKirasic** [comment]
Resolved with #23711
