### ISSUE TITLE
Rails course: Update Forms Lessons to Rails 7

### ISSUE THREAD

**Issue by RolandStuder** [TheOdinProject/curriculum#23755]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The curriculum was recently updated to Rails 7, the very essential Rails Forms lesson is not fully updated, a few people already came with questions about step 3 in the forms project #23753 because they don't see the `ActionController::InvalidAuthenticityToken` showing up in the view.

So the forms lessons needs some rework to not be confusing as form handling has changed quite a bit with Hotwire. The challenge is how to provide good guidance, without having to go into Turbo already. I will try to make a list here, of the things that are outdated.

**2. Acceptance Criteria:**

### Form lesseon

- [ ] Forms example server output and comment on it outdated, standard request is not for `html` but for `turbostream`
     so we have say something like, Rails does some fancy stuff around request from forms, to keep it simple, we will at first opt out of that, with `data-turbo="false"`
- [ ] [Railsifiyng your form](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/form-basics#railsifying-your-form) then claims that the submit won't work and give an error, but with turbo the error won't actually show. So we have to already there say to opt out and kinda explain why
- [ ]  The first `form_with` example shows the form with `remote="true"` and comments on it later one, that again is outdated
- [ ] And the following code example also gives the wrong output with `remote="true"`
- [ ] I would suggest removing the section about deprecated `form_for` and `form_tag`
- [ ] Validations: We can either again use `data-turbo="false"` again, or we might have to be explicit about what turbo expect from the controller (either a redirect or a `status :unprocessable_entity`
- [ ] Controller side refresher is outdated as well, and doesn't account for the stuff that turbo expects

### Form project

- [ ] We should tell them to use `data-turbo=false` at least for first example
- [ ] Add a step 7, where you remove the `data-turbo=false` and make them test with a successful submit and a failure, then tell them to add the correct status so turbo will show the validation errors.
- [ ] … there is probably more, one should just go through the full process and update accordingly

### More:

- [ ] Lessons on controllers should also be updates, and explain about forms submissions and render status vs redirect

**Comment by rokasgarmasukis** [comment]
This is much needed update. At least as a quick fix mention adding `status: unprocessable_entity` to the `render` method in the controller and link to [this explanation](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission) in turbo handbook. This is where I had a lot of frustration errors simply not showing up.

**Comment by CouchofTomato** [comment]
Hey Roli, I opened a PR for a fix to this https://github.com/TheOdinProject/curriculum/pull/23797

If you want to take a look and let me know what you think

**Comment by RolandStuder** [comment]
I will close this issue, since it has been addressed
