### ISSUE TITLE
More Text Styles lesson: change "I" to "we"

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23763]
**1. Description:**

Reason: for consistency throughout the lesson.

**2. Acceptance Criteria:**

- [ ] Change "I" to "we" on [line 112 in more-text-styles.md](https://github.com/TheOdinProject/curriculum/blob/main/html_css/intermediate_css/more-text-styles.md?plain=1#L112)

**3. Additional Information:**

If anyone wants to work on this, please comment to be assigned.

**Comment by Mogoatlhe** [comment]
Hello, I would like to work on this seemingly hard and challenging task please, thank you!

**Comment by Mogoatlhe** [comment]
Hello, I would like to work on this seemingly hard and challenging task please, thank you!
