### ISSUE TITLE
More Text Styles lesson: update font-style subsection

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23762]
Lesson: [More Text Styles](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/more-text-styles)

**1. Description:**

The [font-style subsection](https://github.com/TheOdinProject/curriculum/blob/main/html_css/intermediate_css/more-text-styles.md?plain=1#L70) can be improved. It should be split into two paragraphs and it should link to the [emphasis element mdn doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em). It should also have a second code example for the `em` tag.

**2. Acceptance Criteria:**

- [ ] Split current paragraph of font-style subsection into two. It could be split at "For example, if you want all your hea... ".
- [ ] The second paragraph should have an ending sentence along the lines of "The MDN doc on Emphasis Element puts stress on our point above". This sentence should also link to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em
- [ ] The current code snippet should have a describing text: "We should use `font-style: italic;` if italics is required for styling purposes."
- [ ] Add a new code snippet on a use case for the `em` element. It should have the describing text: "We should use the `em` element if italics is required for emphasis."

**3. Additional Information:**

The above acceptance criteria is flexible. It can be modified with a better implementation. If anyone wants to work on this issue, comment to be assigned. In case of any questions, please feel free to ask.

**Comment by ItsKatato** [comment]
I made the PR! Please let me know if anything needs to be changed.
