### ISSUE TITLE
More Text Styles lesson: add paragraph on font file formats

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23761]
Lesson: [More Text Styles](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/more-text-styles)

**1. Description:**

The [Downloaded file fonts subsection of the lesson](https://github.com/TheOdinProject/curriculum/blob/main/html_css/intermediate_css/more-text-styles.md?plain=1#L51) has a code snippet where a `.woff` font file is utilized. It is worth adding a couple of sentences that link to external resources on different font file formats and supported browser formats.

**2. Acceptance Criteria:**

- [ ] Add a paragraph on file formats just above the code example in the "Downloaded Fonts" subsection.
- [ ] The paragraph must have a sentence which says that there are many font file formats. This sentence must have some text that links to this resource: https://fileinfo.com/filetypes/font
- [ ] The above sentence must be followed by another sentence which says that care must be taken when choosing a font file format because of limited browser support. This sentence must have some text that links to this resource and asks to pay attention to the "Browser Support for Font Formats" table: https://www.w3schools.com/css/css3_fonts.asp

**3. Additional Information:**

The above acceptance criteria is flexible. External links can be replaced by a better resource. If anyone wants to work on this issue, comment to be assigned. In case of any questions, please feel free to ask.

**Comment by trekitch** [comment]
Hello! I can take this one

**Comment by trekitch** [comment]
Changes made and in PR here: https://github.com/TheOdinProject/curriculum/compare/main...trekitch:patch-5
