### ISSUE TITLE
Bug - Advanced grid properties lesson : Markdown heading bug

### ISSUE THREAD

**Issue by Maheshkumar-novice** [TheOdinProject/curriculum#23772]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

As you can see in the images below, The heading is weirdly formatted in the lesson, but markdown is correct. And the same markdown heading renders correctly in the lesson preview generator. But when it comes to site it appears to be rendering badly. 

I went ahead and inspected both the generated heading from the lesson and the markdown preview tool and my observations below,
* The used heading is level `###`
* In the lessons level `###` headings are used for Id's for that section with the link inside.
* For headings with text it easily generates the link. But in our case the heading is with two `code` tags in it. 
* So the problem maybe related to this parsing. 

References:
* Lesson Markdown: [LINK](https://github.com/TheOdinProject/curriculum/blob/main/html_css/grid-lessons/advanced_grid_properties.md#minimum-and-maximum-track-sizes-min-and-max)
* Lesson: [LINK](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/intermediate-html-and-css/lessons/advanced-grid-properties#minimum-and-maximum-track-sizes-min-and-max)

Lesson & Markdown:
![bug1](https://user-images.githubusercontent.com/67100964/158010850-fbfba331-9b12-4c24-92f7-b5f87a5e1df3.png)

Lesson & Preview Tool:
![bug2](https://user-images.githubusercontent.com/67100964/158010855-5d21eeb0-eb20-42f1-ab19-353f986ffa38.png)

Inspector Lesson & Preview Tool:
![bug3](https://user-images.githubusercontent.com/67100964/158010872-25d36b78-d681-4953-a9e8-c5d6642d366b.png)

**2. How To Reproduce:**

* Open the following files and compare the difference in rendering. 
* Lesson Markdown: [LINK](https://github.com/TheOdinProject/curriculum/blob/main/html_css/grid-lessons/advanced_grid_properties.md#minimum-and-maximum-track-sizes-min-and-max)
* Lesson: [LINK](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/intermediate-html-and-css/lessons/advanced-grid-properties#minimum-and-maximum-track-sizes-min-and-max) 

**3. Expected Behavior:**

* Lesson heading must be the same as the one we see in the preview tool

**4. Desktop/Device:**

Common Content Issue so no particular device

**5. Additional Information:**

None

**Comment by 01zulfi** [comment]
@Maheshkumar-novice Thanks a lot for digging deep into this and writing out a detailed issue. We really appreciate it.

Your observations are correct: lesson headings on the website are transformed into links using JavaScript. This does not allow any other HTML element in the lesson heading yet. We are aware of this bug and hopefully it will be fixed soon. 

For the time being, removing the backticks from the lesson heading will suffice. Here's the acceptance criteria: 
- [ ] Remove all of the backticks on [line 137 in advanced_grid_properties.md](https://github.com/TheOdinProject/curriculum/blob/main/html_css/grid-lessons/advanced_grid_properties.md?plain=1#L137).

If anyone wants to work on this, please comment to be assigned! In case of any questions, please feel free to ask.
