### ISSUE TITLE
CSS Functions lesson: update clamp() section

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23775]
**1. Description:**

The [clamp() section of the lesson](https://github.com/TheOdinProject/curriculum/blob/main/html_css/intermediate_css/css_math_functions.md?plain=1#L103) does not have ideal formatting. Additionally, it does not explain what the `clamp()` function actually does.

**2. Acceptance Criteria:**

- [ ] This code example should be transformed into its own code block rather than being inline:  `font-size: clamp(320px, 80vw, 60rem);`.
- [ ] Make sure the new code snippet uses valid CSS syntax.
- [ ] Right now, the numbered list does not span multiple lines, it should be updated.
- [ ] The phrases "the smallest value", "the ideal value", and "the largest value" don't need backticks. Backticks should be removed. Furthermore, they should mention the corresponding value from the given code example. For example: "the smallest value (320px)".
- [ ] Add a sentence after the list about what the `clamp()` function actually does with its arguments.

**3. Additional Information:**

The acceptance criteria is flexible. If anyone wants to work on this issue, comment to be assigned!

**Comment by mattxmade** [comment]
Hi @01zulfi, I'd be happy to take this on.

If assigned, would this be OK to come after the list?

> The `clamp()` CCS function uses these values to set the minimum value, preferred value and maximum value. In the above example, this would mean the minimum acceptable font-size would be 320px and the maximum would be 60rem. The middle value of 80vw would be the preferred font-size.

Thanks

**Comment by 01zulfi** [comment]
@mattxmade Yes, your suggestion looks good. If need be, we can iterate over the changes in the pull request you make.

I've assigned you. Thanks for taking this on!
