### ISSUE TITLE
Form Basics Lesson: Name Attribute section wording could be improved

### ISSUE THREAD

**Issue by mattxmade** [TheOdinProject/curriculum#23776]
https://github.com/TheOdinProject/curriculum/blob/2ee490d8ac551deb465bc0fd9abec6c52884fc33/html_css/intermediate_html/form-basics.md?plain=1#L89

Currently the latter part of the paragraph reads:

> "Just like that, we also need to let the backend where we send our data know what each piece of data represents."

I propose the sentence be changed to:

> "Much the same, we also need to let the backend know where we send our data and what each piece of data represents."

If this would be acceptable, I'd be happy to take this on and submit a pull-request.

Thanks

**Comment by mattxmade** [comment]
Hi @LeoKirasic, I can take this one.

**Comment by LeoKirasic** [comment]
Closing because of explanation in #23832
