### ISSUE TITLE
CSS Functions lesson: add a bullet item on CSS variables

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23774]
**1. Description:**

As far as I can tell, the [CSS functions lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/css-functions) has the first reference of CSS variables in the curriculum. It's worth mentioning what they are and that users will get a chance to learn them in a future lesson.

**2. Acceptance Criteria:**

- [ ] Add a bullet item right after the code snippet in the [calc() section of the lesson](https://github.com/TheOdinProject/curriculum/blob/main/html_css/intermediate_css/css_math_functions.md?plain=1#L29).
- [ ] The bullet must mention that `--header`, `--footer`, and `--main` are CSS variables.
- [ ] In the same bullet, mention that users will learn them in the very next lesson.

**3. Additional Information:**

The placement of this bullet item is flexible, hence it should be placed at a better position if possible. If anyone wants to work on this issue, comment to be assigned.

**Comment by ItsKatato** [comment]
I can take this one!
