### ISSUE TITLE
Bug - Getting started lesson in Node JS course: Javascript Course link does not work

### ISSUE THREAD

**Issue by DaeguDude** [TheOdinProject/curriculum#23788]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

[Getting started lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs/lessons/getting-started) in Node js course, In the first paragraph it mentions about Javascript course and has actually link to it, but the link does not work but lead to 404 page.

![Screen Shot 2022-03-14 at 9 03 12 PM](https://user-images.githubusercontent.com/35420073/158168338-d164fb3a-37a7-4b26-80f4-ee23eafdb550.png)

**2. How To Reproduce:**

1. Log in
2. Visit a [Getting started lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs/lessons/getting-started) in Node JS
3. Click the Javascript Course link in the first paragraph
4. It leads to 404 page

**3. Expected Behavior:**

It should be routed to Javascript course page.

**4. Desktop/Device:**

-   Device: Macbook M1
-   OS: Mac OS
-   Browser: Chrome
-   Version: 99

**5. Additional Information:**

When Javascript link is clicked, the path it takes to is 

- `https://www.theodinproject.com/courses/javascript`

and shows 404 page. And when I personally maneuver to Javascript course path, the url is 
- `https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript`

If this is something that has to be corrected, I am happy to make a PR.

**Comment by 01zulfi** [comment]
@DaeguDude Thanks for pointing this out, it definitely needs to be fixed.

You've been assigned!
