### ISSUE TITLE
Intermediate HTML & CSS: Update introduction

### ISSUE THREAD

**Issue by Maheshkumar-novice** [TheOdinProject/curriculum#23787]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

![feature](https://user-images.githubusercontent.com/67100964/158116985-0973d00b-ae7a-4334-be2d-dfa85d9549b6.png)
The above image is from introduction of intermediate html & css [link](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/intermediate-html-and-css/lessons/introduction#introduction)

In the introduction of intermediate html & css there are 2 paragraphs that can potentially confuse learners. Because in the intro we mention some of the content we cover in the Advanced html & css course like semantic html & animations for example. You can see in the above image, those are the 2 paragraphs that I'm mentioning. 

I think it'll be good to edit this intro and also if necessary it's better to add an intro lesson for advanced html & css also or we can provide info something like, you'll learn the following in the advanced html & css course..like that.

**2. Acceptance Criteria:**

None for now.

**3. Additional Information:**

None

**Comment by LeoKirasic** [comment]
Hey, @Maheshkumar-novice thanks for creating an issue for this!

Please make a PR re-wording the intro to include a mention of which of those concepts are covered later on in the advanced HTML/CSS course!

**Comment by Maheshkumar-novice** [comment]
> Hey, @Maheshkumar-novice thanks for creating an issue for this!
> 
> Please make a PR re-wording the intro to include a mention of which of those concepts are covered later on in the advanced HTML/CSS course!

Thanks. Sure I'll make a PR on or before this Sunday.
