### ISSUE TITLE
Creating a Grid lesson: update Gap section

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23784]
**1. Description:**

The [Gap section of Creating a Grid lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/creating-a-grid#gap) alludes that `gap` can _only_ be used to set `column-gap` and `row-gap` to the same value. In fact, `gap` is a shorthand that also allows us to set different values for `column-gap` and `row-gap`. The [MDN doc on gap](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) provides further clarification as well as live examples.

**2. Acceptance Criteria:**

- [ ] Replace the last sentence of the first paragraph with "Furthermore, we can use a shorthand property called `gap` to set both `row-gap` and `column-gap`."
- [ ] Add a paragraph after the third CodePen embed which tells users that they could "set both `row-gap` and `column-gap` using `gap`".
- [ ] The above paragraph should also mention the syntax of `gap` as well as encourage users to try it out in the embed.
- [ ] Depending on how the above changes are applied and if it becomes necessary, reword the last paragraph of this section.

**3. Additional Information:**

If anyone wants to work on this issue, please comment to be assigned!

**Comment by iawong** [comment]
Hi, can I take this one?
