### ISSUE TITLE
CSS FOUNDATIONS > Image Height and Width: Add example to make the height: auto effect more clear

### ISSUE THREAD

**Issue by PerseveranceX** [TheOdinProject/curriculum#23803]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I originally opened this issue TheOdinProject/css-exercises#150
In the **Image Height and Width** section, it explains using height: auto to keep the image proportions(aspect ratio) while changing it's size.
It can become more clear if mentioned an example of it's effect.
Example: 

> ```CSS
> img {
>   height: auto;
>   width: 500px;
> }
> ```
> In the example above, If the the proportions of the image is 2:1 (width:height), the width is set to 500px, then the height will be adjusted to 250px automatically.

**2. Acceptance Criteria:**

- [ ] Explaining the effect of using height: auto; in the example code provided

**Discussion**
Do you think adding explanation to the example like this would make it more clear to the learner or will introduce the possibility of confusion?

**Comment by thatblindgeye** [comment]
I've assigned you, @PerseveranceX 

I think an alternative suggestion would be using an image's actual sizes to help explain the effect of auto. For example, if an image's original size was 500px height and 1000px width, using the above CSS would result in a height of 250px. Except worded nicer 😆 

I'm not overly fussed which verbiage is used, though. I think what you mentioned could work, and it might depend what the actual submitted suggestion looks like in context of the surrounding lesson as well.
