### ISSUE TITLE
Bug - : DOM Manipulation and Events: Article link not working

### ISSUE THREAD

**Issue by DasTapan** [TheOdinProject/curriculum#23804]
**1. Description of the Bug:**
        Inside the DOM Manipulation and Events section in the Foundation path of TOP. There is an article link about the Javascript callback function. The link is not working. Link Text is "HERE". The URL which is not working: https://briggs.dev/blog/understanding-callbacks

**2. How To Reproduce:**

1. Log in to TOP
2. Go to Foundation path
3. Go to DOM Manipulation and Events chapter
4. Around the middle of the page there is a link called "HERE"
5. If you click it, it shows 504 Gateway Time-out error

**3. Expected Behavior:**
      The link should open

**4. Desktop/Device:**

-   Device: Linux VM
-   OS: Xubuntu
-   Browser: Mozilla Firefox
-   Version: 97.0
![Screenshot_2022-03-15_20-33-54](https://user-images.githubusercontent.com/62939481/158407783-ae848df8-87a4-4957-a30b-415c67e30b97.png)
![Screenshot_2022-03-15_20-25-27](https://user-images.githubusercontent.com/62939481/158407803-80b311d1-f2ac-4cf7-aee6-386f0beaddbd.png)

**Comment by I3uckwheat** [comment]
This was an issue with my own server, I will migrate this to Dev.to at some point to mitigate this.
