### ISSUE TITLE
Pattern matching lesson - Ruby track: Concept explanation duplication

### ISSUE THREAD

**Issue by MLGabe** [TheOdinProject/curriculum#23816]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Duplication of the explanation of rightward assignment. 

**2. Acceptance Criteria:**
- [ ] Removal of the duplication at the beginning

**3. Additional Information:**
Prints in the following discord link: https://discord.com/channels/505093832157691914/540903304046182425/948966321767477248

**Comment by wise-king-sullyman** [comment]
I think that the duplication is indeed intentional, I assume the idea is that the first instance it's brought up as a "here's a thing you can do" and the second as a "here's what's really happening here".

@CouchofTomato can you comment on if this was intentional?

**Comment by CouchofTomato** [comment]
@wise-king-sullyman Yeah it initially introduced just under the umbrella of the two ways of doing pattern matching and the second example was specifically to showcase rightward assignment. I'm open to using a different example for either of them if anyone wants to do a PR but I'm not particuarly concerned that it needs to change enough to do it myself.

**Comment by wise-king-sullyman** [comment]
Sounds like if you still want to improve this the issue is all yours @MLGabe!

**Comment by ChargrilledChook** [comment]
Closing, but feel free to ping me here if this is something you still want to work on @MLGabe

**Comment by ChargrilledChook** [comment]
Closing as this is both a fairly minor change and stale, but happy to re-open if you would still like to take this on @MLGabe
