### ISSUE TITLE
Transitions lesson: move an additional resource to assignment

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23828]
**1. Description:**

The [Transitions lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/advanced-html-and-css/lessons/transitions) has a knowledge check called "Why do you need to keep an eye on repaints?" which links to the [Debugging layout repaint issues triggered by CSS Transition article](https://dzhavat.github.io/2021/02/18/debugging-layout-repaint-issues-triggered-by-css-transition.html). This article does get linked in the additional resources section of the lesson.

The additional resource which links to the above article must be moved to the assignment so that the knowledge checks are directly linking to the lesson content or a resource from the assignment, rather than an additional resource.

**2. Acceptance Criteria:**

- [ ] Move the following resource from additional resources to the assignment section:
     -  "You can learn how to catch and debug repaint issues with this great article from [Dzhavat Ushev](https://dzhavat.github.io/2021/02/18/debugging-layout-repaint-issues-triggered-by-css-transition.html)."

**3. Additional Information:**

If anyone wants to work on this, please comment to be assigned!

**Comment by ItsKatato** [comment]
Hi! I could work on this!
