### ISSUE TITLE
Transforms lesson: change lesson headings and fix knowledge check links

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23822]
**1. Description:**

The [Transforms lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/advanced-html-and-css/lessons/transforms) has two lesson headings that begin with a numeric character: [2D Transforms](https://www.theodinproject.com/paths/full-stack-javascript/courses/advanced-html-and-css/lessons/transforms#d-transforms) and [3D Transforms](https://www.theodinproject.com/paths/full-stack-javascript/courses/advanced-html-and-css/lessons/transforms#d-transforms-1). It's just a hypothesis at the moment, but the numeric characters are causing the section ids to be `d-transforms` and `d-transforms-1` respectively. Whereas a couple of knowledge check links are expecting `2d-transforms` and `3d-transforms` as lesson section ids.

**2. Acceptance Criteria:**

- [ ] Change "2D Transforms" lesson heading to "Two-Dimensional Transforms"
- [ ] Change "3D Transforms" lesson heading to "Three-Dimensional Transforms"
- [ ] Where applicable, use `#two-dimensional-transforms` and `#three-dimensional-transforms` as `hrefs` for knowledge check links
- [ ] Make sure knowledge check links work correctly on the [Lesson Preview Tool](https://www.theodinproject.com/lessons/preview)

**3. Additional Information:**

If anyone wants to work on this, please comment to be assigned!

**Comment by thatblindgeye** [comment]
Before work is started on this, it'd be worth looking into what is causing this issue, whether it's a Markdown/GitHub thing or something in our code base.

**Comment by 01zulfi** [comment]
Putting a "Status: Investigating" on this issue. If it's decided to go ahead with this change I'll assign you, @BlizZard-bot

**Comment by 01zulfi** [comment]
After discussing with the team, we have decided to move ahead with this issue.

You're assigned, @BlizZard-bot!
