### ISSUE TITLE
(Rails): Files and Serialization outdated resource

### ISSUE THREAD

**Issue by marvingay** [TheOdinProject/curriculum#23847]
Given we use Ruby 3, [Assignment #4](http://ruby.bastardsbook.com/chapters/io/) in the [Files and Serialization lesson](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/files-and-serialization-ruby-programming) contains syntax both in the examples and exercise that are out of date with the current documentation for the `open-uri` gem, resulting in unexpected errors, more specifically, `"No such file or directory @ rb_sysopen"`

Should we add clarity surrounding this error and preserve the resource? Remove it? Find an alternative?

**Comment by CouchofTomato** [comment]
@marvingay It is mentioned the code examples are outdated but an updated resource would be good. From a quick search https://blog.kiprosh.com/serialization_in_ruby_on_rails_part_one/ looks proromising (part 1) because it covers marshalling as well.

**Comment by thatblindgeye** [comment]
@CouchofTomato Is the link you last mentioned still viable to replace in this lesson?

**Comment by CouchofTomato** [comment]
@thatblindgeye Yes, I think it's a pretty comprehensive resource.

**Comment by tomas-vidal** [comment]
I can work on this. Should I simply replace the outdated link assignment with the one Couchoftomato suggested?

**Comment by CouchofTomato** [comment]
> I can work on this. Should I simply replace the outdated link assignment with the one Couchoftomato suggested?

@tomas-vidal Yeah it's a simple replacement. It's all yours.
