### ISSUE TITLE
Bug - : React Testing Part 2 - assignment 01 reading material code is kind of errorneous!!

### ISSUE THREAD

**Issue by bappyasif** [TheOdinProject/curriculum#23840]
im getting 'resolve' is not a function' when trying to run this bit of code, to me it makes sense too, but as im going through 'act api' provided reading materials ([link attached](https://github.com/mrdulin/react-act-examples/blob/master/sync.md)), and they used this snippet, and using it causing this error in console!!

```js
it("should display fetched data", async () => {
  // a rather simple mock, you might use something more advanced for your needs
  let resolve;
  function fetch() {
    return new Promise(_resolve => {
      resolve = _resolve;
    });
  }
  const el = document.createElement("div");
  act(() => {
    ReactDOM.render(<App />, el);
  });
  expect(el.innerHTML).toBe("");
  await act(async () => {
    resolve(42);  // getting not a function error here!! which is justifiable as it is not a function!! but this reading material claims to be producing a succesful test with this code!! but im not seeing that in my console!!
  });
  expect(el.innerHTML).toBe("42");
});
```

assignment link: [react-testing-part-2](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/react-testing-part-2#react-testing-in-the-real-world)
assignment reading content link: [react-act-examples](https://github.com/mrdulin/react-act-examples/blob/master/sync.md)

NB: same thing is happening with: async/await piece of  code as well!! also to point out 'fetch' is never been called or referenced in any way, i could be wrong, see it for yourself!! 

could it be outdated or erroneous, thanks again....

snapshot of console, while running some promise related snippets, where 'resolve' is used: 
![image](https://user-images.githubusercontent.com/19854521/159122561-db3be44b-e972-4473-b6dd-af15188df6a8.png)

Complete the following REQUIRED checkboxes:
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

provided code snippets for promises / async await, produces error in console, please see above description for more info on this

**2. How To Reproduce:**

when you run test script with provided snippet you get error in console

**3. Expected Behavior:**

should successfully resolve provided argument to resolve function

**4. Desktop/Device:**

-   Device:  notebook
-   OS:  windows 10
-   Browser:  chrome
-   Version:  latest

**5. Additional Information:**

codebase seems to be bit outdated as well!! they used React.DOM.render where as in earlier materials suggested to use 'render' only, it was bit strange for me at first, had to look into it, to understand it, just my feedback, thanks

BriggsE actually knows about this and it was him who suggested that i should open an issue about this!! i would have tagged but not sure if it's ChuckBriggs or not!!

**Comment by martenmatrix** [comment]
It seems like `act()` does not provide a `resolve` callback function (anymore?). You will have to call resolve() directly on a Promise object like `Promise.resolve()`. @bappyasif

**Comment by bappyasif** [comment]
okay, ill try to doing that, thanks :) @martenmatrix

**Comment by martenmatrix** [comment]
I find your motivation to contribute great, but issues are not the right place to discuss this. TOP got an awesome Discord, where you can ask your questions. It will be seen by many people, which are happy to help. You can join [here](https://discord.com/invite/fbFCkYabZB). However, from my understanding, I agree that the mocked `fetch()` function does not get called, and that the example might be a bit misleading. Let's ask for an answer in the Discord, and then we can decide, if this should be changed. :) @bappyasif

**Comment by martenmatrix** [comment]
I've looked at it again, and I think I found the issue. The writer has put all his code (even the React components in the test file) as you can see [here](https://github.com/mrdulin/react-act-examples/blob/master/act-examples.test.js). The test you are trying to re-produce looks like this in his code:
```js
it("can handle async/await", async () => {
    let resolve;
    function fetch() {
      return new Promise(_resolve => {
        resolve = _resolve;
      });
    }

    function App() {
      let [data, setData] = useState(null);
      async function somethingAsync() {
        let response = await fetch("/some/url");
        setData(response);
      }
      useEffect(() => {
        somethingAsync();
      }, []);
      return data;
    }

    const el = document.createElement("div");
    act(() => {
      ReactDOM.render(<App />, el);
    });

    expect(el.innerHTML).toBe("");

    await act(async () => {
      resolve(42);
    });

    expect(el.innerHTML).toBe("42");
  });
```
As you can see, this way, he definitely mocks the fetch() function. We were just confused because normally you write your tests in a different file than your components.

If you want to keep your React components in another file, like you normally should. You can fix the whole error by creating a mock-implementation with Jest.
```js
fetch = jest.fn(() => {
    return new Promise(_resolve => {
        resolve = _resolve;
    });
});
```
This way, all fetch() functions in all files will be replaced with your mock function, when running tests.

Just remember to change `Promise.resolve()` back to `resolve()`.

**Comment by martenmatrix** [comment]
Maybe adding a little note would help future readers understand this quicker. Like `Keep in mind that in the following article React components are written within the tests!`? What do you think? @bappyasif

**Comment by bappyasif** [comment]
@martenmatrix thanks a lot, this makes a lot more sense now, and 'some sort of announcement' giving readers a heads up would be nice and appropriate, i would agree as well :)

**Comment by bappyasif** [comment]
now with that 'mock' function in place for fetch, it works just fine!! was that writer wanted us to discover that on our own!! here is how my code looks and passes in console....
```js
describe('using promise for fetch', () => {
    test('should display fetched data', async () => {
        // a rather simple mock, you might use something more advanced for your needs
        let resolve;
        fetch = jest.fn(() => new Promise(_resolve => resolve = _resolve))
    
        let el = document.createElement('div')
        
        act(() => ReactDOM.render(<DemoFetch />, el))
        expect(el.innerHTML).toBe("");

        await act(async () => {
            resolve(42);
        });
        expect(el.innerHTML).toBe("42");
    })
})
```
thanks again @martenmatrix that was really helpful!! so what do we now about this, do we include this in 'announcement' somewhere!!

**Comment by martenmatrix** [comment]
@babbyasif I've just created a PR, which, if accepted, would add a little note next to the assignment. :)

**Comment by bappyasif** [comment]
@martenmatrix thanks, lets hope it gets merged!! happy coding :)
