### ISSUE TITLE
Bug - : introduction-to-git page: Setting Up Git link is broken

### ISSUE THREAD

**Issue by tschew72** [TheOdinProject/curriculum#23844]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
"Setting Up Git" link is broken on [Link](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-git)
[Screenshot](https://www.icloud.com/iclouddrive/054g6gbWez4_6Gw1qEXKGftyw#Screenshot_2022-03-20_at_8.41.14_AM)

**2. How To Reproduce:**
1. Visit [Link](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-git)
2. Go to Assignment section
3. Click the link " Setting Up Git"
4. The browser redirected to a 404 page [Link](https://www.theodinproject.com/courses/foundations/lessons/setting-up-git)

**3. Expected Behavior:**
A brief description of what you expected to happen, e.g.:
1. Visit [Link](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-git)
2. Go to Assignment section
3. Click the link " Setting Up Git"
4. The browser should go to [Link](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/setting-up-git)

**4. Desktop/Device:**
Applicable to all devices and browsers

**5. Additional Information:**
NA

**Comment by LeoKirasic** [comment]
Thank you for creating the issue!

If someone wants to work on this, please tag me and I'll assign you.

This is what needs to be done:

- Get the link from the [Setting Up Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/setting-up-git) lesson.
- Follow the [Contributing Guide](https://github.com/TheOdinProject/curriculum/wiki/Contributing-Guide) and replace the link described in the issue with the working [Setting Up Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/setting-up-git) link.

**Comment by LeoKirasic** [comment]
@BlizZard-bot Go for it!

**Comment by LeoKirasic** [comment]
@BlizZard-bot My bad! Thought it was updated to the correct one. Edited my original message.
