### ISSUE TITLE
Add explanation for having regex in javascript foundations lesson.

### ISSUE THREAD

**Issue by linkonsat** [TheOdinProject/curriculum#23853]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

This feature clarifies why we have regex as well as an explanation that it should be used sparingly and often times isn't the ideal solution. As such a suggestion is to change the verbiage so it's clear regex isn't the ideal solution but is a tool that can be used in rare circumstances. Discord conversation context https://discord.com/channels/505093832157691914/540903304046182425/955225485007286273

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by LeoKirasic** [comment]
@linkonsat This sounds good to me!

**Comment by wise-king-sullyman** [comment]
@linkonsat sounds good to me as well, is this something you're still wanting to do yourself?

**Comment by linkonsat** [comment]
I am going to do this.
