### ISSUE TITLE
Bug - Motivation & Mindset section in Foundations: 404 link in the Learning Process part

### ISSUE THREAD

**Issue by teephan91** [TheOdinProject/curriculum#23850]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the Foundations course, Motivation & Mindset part, The Learning Process section, the last ul element, there is a 404 link in the anchor text "...**podcast on How to Learn**..."

Here is the link: https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/gearing-up#the-learning-process

![Screenshot 2022-03-20 1 08 49 PM](https://user-images.githubusercontent.com/101987153/159184136-c46d62c2-f7d6-42a2-81eb-a123fa42500a.png)

**2. How To Reproduce:**

Please follow the link and screenshot above.

**3. Expected Behavior:**

Maybe a 200 link or new link to some other resources or completely get rid of that ul element.

**4. Desktop/Device:**

-   Device:  Asus Chromebook
-   OS:  Chrome OS
-   Browser:  Chrome
-   Version:  Latest

**5. Additional Information:**

😐

**Comment by LeoKirasic** [comment]
Hey, @teephan91

Thank you for reporting this.

If anyone wants to work on this, please tag me and I'll assign you.
Here's what needs to be done:
- Go to the [Web Archive](https://web.archive.org/) website.
- Copy the broken link from the [lesson](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/gearing-up#the-learning-process) to the web archive website.
- Get a working snapshot of the website
- Follow the [Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md) and replace the broken link with the one from the web archive website.
