### ISSUE TITLE
Websockets and Actioncable lesson: fix broken assignment link

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#23869]
**1. Description:**

The [Websockets and Actioncable lesson](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/websockets-and-actioncable) has a link called Simple Messaging App. It links to [actioncable_lesson.md](https://github.com/TheOdinProject/curriculum/blob/main/ruby_on_rails/mailers_advanced_topics/actioncable_lesson.md) in the curriculum repository. 

Recently, the `rails_programming` folder was renamed to `ruby_on_rails`, causing the link to break.

**2. Acceptance Criteria:**

- [ ] Fix the "Simple Messaging App" link

**3. Additional Information:**

If anyone wants to work on this issue, comment to be assigned.

**Comment by ItsKatato** [comment]
Hi, I can work on this!

**Comment by 01zulfi** [comment]
@ItsKatato You've been assigned!

@nguyens20 Unfortunately, this issue is already assigned. Looking forward to your other contributions though!
