### ISSUE TITLE
Foundations course: Improve clean code lesson

### ISSUE THREAD

**Issue by LeoKirasic** [TheOdinProject/curriculum#23870]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Currently, the clean code lesson goes over some good principles, but it could go more in depth, covering more things, in bigger detail. We can utilize information from the first few chapters from the Clean Code book, by Robert Cecil Martin. There's also a javascript version of the book, available [here](https://github.com/ryanmcdermott/clean-code-javascript) which we can use as a reference.

**2. Acceptance Criteria:**

The lesson should cover the following, and every item should ideally have a code example with it:

- [ ] Go more in depth into naming(Intention revealing names, names shouldn't be misleading)
- [ ] Go more in depth into functions(Number of parameters, long function names vs short function names, functions should do one thing)
- [ ] Comments(when to comment, also mention self explaining code)
- [ ] Refactor a piece of code from etch a sketch as a code example

**3. Additional Information:**

**Comment by DaeguDude** [comment]
I didn't actually read Clean Code by Robert Cecil Martin, however, if just referencing javascript version of the book that's in the above is fine, I could work on it.

**Comment by wise-king-sullyman** [comment]
@LeoKirasic do you think @DaeguDude would be good to take on this issue even if he hasn't read the book, or do you think the work would be greatly benefitted by having someone who has read it?

**Comment by wise-king-sullyman** [comment]
@DaeguDude are you still up for this? I know it's been a while since you last commented.

**Comment by impronen** [comment]
I would be interested in working on this, as it seems to have been stale for some time. The topic is interesting and something I think I would also benefit from doing some more reading. 

I haven't read the book either but if referencing the js articles is enough, I'm game.

**Comment by wise-king-sullyman** [comment]
@impronen go for it!

**Comment by impronen** [comment]
I'm currently in middle of doing this rewrite but I'm hesitant on having code examples from an Etch-A-Sketch as an example. The lesson is placed right after the original RPS game and EaS is still many lessons ahead. Lot of the things I would probably use would be either little cheaty or not clear for the reader as DOM hasn't yet been discussed at all.

Currently I have either used some random examples or the ones in the lesson already. Would this be ok, or should I incorporate the mentioned EaS examples?

I'm not sure if it's appropriate to ping people in these so, if not... sorry @LeoKirasic 
:grimacing:

**Comment by impronen** [comment]
this is what i currently have: https://github.com/impronen/odin-curriculum/blob/clean-code-rewrite/foundations/javascript_basics/clean_code.md

**Comment by LeoKirasic** [comment]
@impronen You're right, we can avoid EaS examples. Additionally, I really like what you've done with the lesson. Once you're done, submit a PR and please mention this issue in the PR so we can get to formally reviewing the changes. Thank you for taking this on!

Additionally, you're free to ping us on GitHub.

**Comment by impronen** [comment]
@LeoKirasic I'm bugging you again with this :D 

I've been considering the more advanced concepts for functions and other things in the book. The issue I'm running with most things is the very early stage the learner will be at this point of the curriculum. 

I was planning on writing about using 2 or less arguments but the solution to that is often destructuring,  but objects haven't been covered yet. Same thing with even the lightest of mentions of Single Responsibility Principle - this would be good to illustrate with array methdos, loops etc but these are in the coming lessons.

Lot of the stuff covered would be very useful for someone past foundations, so what I'm kinda suggesting would be the following:

I'll finish this rewrite with basically the things in my earlier commit. And suggest an additional lessons, Clean Code part 2 or something to be added to somewhere in the JS path, where we can cover more in depth subjects. Do you think this sounds reasonable?

**Comment by impronen** [comment]
started a new discussion on the prospect of doing clean code part two, [here](https://github.com/TheOdinProject/curriculum/discussions/25718)

**Comment by CouchofTomato** [comment]
@LeoKirasic 

Can you take a look at the discussion linked above please.

**Comment by LeoKirasic** [comment]
@impronen Great idea, let's do it!
