### ISSUE TITLE
JavaScript Basics/Fundamentals Part 2: The instructions on Exercise 4 are unclear

### ISSUE THREAD

**Issue by M3R14M** [TheOdinProject/curriculum#23886]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

<hr>

**1. Description of the Feature Request:**

I see a lot of people having trouble with this exercise, mostly when it comes to reading what to do and when to do it. There are multiple comments on [the exercise at replit.com](https://replit.com/@I3uckwheat/direction-follow#follow.js) stating the instructions were unclear. 

Now, I'm not an expert by any means, but perhaps that helps with providing something that's clearer to beginners trying this exercise. I rearranged the instructions a bit to make it more obvious as an example below.

**2. Acceptance Criteria:**

- [ ] Improve the exercise instructions.

**3. Additional Information:**

<details><summary>Example</summary>

```javascript
/**
  If your code fails to run, or you see a "ReferenceError" in the console, make sure you have completed all of the objectives.
  
  Don't forget you can put "console.log" anywhere to see what your values are at any time.
  
  	===== NOTE ======================
  	
	In order to make the tests pass you will need to use these exact values for the years and names.  The wording needs to be exact.  If the tests fail, check spacing and punctuation:
	
	birthYear = 1948
	thisYear = 1965
	firstName = Carlos
	lastName = Stevenson

	The greeting should say "Hello! My name is Carlos Stevenson and I am 17 years old."
  
	===== Step 1: ===================
	
	1. Take a look at the code below and try to predict what it's going to do before running it...
	
	2. After making your guess, press 'run' at the top and take a look at the output in the console. If you were surprised by anything, go back and look at the code to see what's going on. 
	
*/

// Edit below this line =============

const birthYear = 1948;
const thisYear = 1965;
const firstName = "Carlos";
const lastName = "Stevenson";

const greeting = "Hello! My name is " + firstName + " " + lastName + " and I am " + (thisYear - birthYear) + " years old.";

console.log(greeting);

// Edit above this line =============

/*	===== Step 2: ===================
	
	Once you have a good handle on the code snippet, delete the code, then follow these instructions and try to recreate the snippet on your own.
	
	1. Create 4 variables: firstName, lastName, currentYear, and birthYear.
	
	2. Create a 5th variable, greeting, that is constructed from the previous  4 variables. It should contain a greeting with the person's full name and their age.
	
	3. Print the greeting with console.log
	
	4. Press 'run' to see if your code works. If not, review your code to see what went wrong. 	

	===== Step 3: ===================
	
	Once you have your version of the code working, let's go back to it and edit it to make it easier to read. 
	
	1. Add 2 more variables: "fullName" and "age". Set these variables using the calculations that were originally being done in the greeting.
	
	2. Press 'run' to see if your code still works.
	
	3. Change the test at the bottom to run the Test for Step 3.

	4. Edit the greeting string to use fullName and age instead of doing the calculations in the string itself. (the greeting should look something like this: "Hello, my name is " + fullName)
	
	5. Press 'run' to verify the code.
*/

// ===== Testing your code ==========

// == Test for Step 2: ==============

module.exports = {
	testGroup: "a",
	greeting,
	birthYear,
	thisYear,
	firstName,
	lastName
}


// == Test for Step 3: ==============

// To run this test, comment out or delete "Test for Step 2" and remove the comments below. 

/* < Remove this line completely >

 module.exports = {
 	testGroup: "b",
 	greeting,
 	birthYear,
 	thisYear,
 	firstName,
 	lastName,
 	fullName,
 	age
 }
 
< Remove this line completely > */
```
</details>

[View live version on replit.com](https://replit.com/@M3R14M/direction-follow#follow.js)

**Comment by afkus3r** [comment]
I would like to work on this issue

**Comment by bappyasif** [comment]
perhaps keeping instructions "out of editor" might help, as people are more inclined to read from a 'web page' than from an 'editor'

i might be totally wrong here, considering that assumption to be true....

**Comment by matristle** [comment]
@wise-king-sullyman I could give this a go!

Here's my first attempt at clarification:
https://replit.com/@alkirkel/direction-follow#follow.js

**Comment by enmanuelsabarua** [comment]
I can work on this.

**Comment by wise-king-sullyman** [comment]
@enmanuelsabarua thanks for the offer, but after taking another look at this issue one of the solutions proposed previously by seems to be a pretty great improvement so I went ahead and implemented it and I'll be closing this issue.

@JacobMarq thank you for taking the time to put all of that together and apologies for the delay!
