### ISSUE TITLE
Bug: Inspecting HTML and CSS chapter assignment link broken

### ISSUE THREAD

**Issue by GCENdel** [TheOdinProject/curriculum#23890]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Found a small link difference on the https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/inspecting-html-and-css page where when sent to do the CSS under Assignment, it just ends up sending you to the main overview of the Open Devtools page, which can be quite confusing to navigate as it doesn't openly state the CSS that TOP wants you to do.

The link TOP currently uses: https://developer.chrome.com/docs/devtools/#css

The correct link: https://developer.chrome.com/docs/devtools/css

Note that the only difference is the "#" infront of css in the URL.

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by ItsKatato** [comment]
I can take this issue once it gets the `help wanted` label.

**Comment by GCENdel** [comment]
Would it be possible for me to have a try at it? I'm unsure if I need permissions to access.

**Comment by LeoKirasic** [comment]
@GCENdel Go for it!

**Comment by GCENdel** [comment]
Hope everything is formatted right, made sure to read through the guidelines thoroughly. Thanks for the opportunity!
