### ISSUE TITLE
Testing Basics: Move note on import statements with Jest to previous page

### ISSUE THREAD

**Issue by jay4170** [TheOdinProject/curriculum#23904]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:
-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

In the testing section i think it makes more sense to move the "Special Note on using ES6 import statements with Jest" section to the page before the assignment. 
Personally i had issues with this and spent a while trying to figure out where i went wrong.

Current location (assignment page) - https://www.theodinproject.com/lessons/javascript-testing-practice

Suggested location (learning page)- https://www.theodinproject.com/lessons/javascript-testing-basics

It could also be placed before the assignment on the same page.

**Comment by jay4170** [comment]
Yes i agree, it would work well before the assignment.

**Comment by 01zulfi** [comment]
Thanks @jay4170 for the feedback. I'm opening this issue up for contributions.

Here's the acceptance criteria:

- [ ] Move the "[Special Note on using ES6 import statements with Jest](https://www.theodinproject.com/lessons/javascript-testing-practice#special-note-on-using-es6-import-statements-with-jest)" section before the Assignment section in the [Project: Testing Practice lesson](https://www.theodinproject.com/lessons/javascript-testing-practice).
- [ ] Update this section's description to "Using ES6 import statements with Jest".

Anyone who wants to work on this, please comment to be assigned!

**Comment by ItsKatato** [comment]
Hi @01zulfi , I would like to work on this.
