### ISSUE TITLE
Bug -  Introduction to Grid : Broken link on the paragraphe "A Look Back at Flex"

### ISSUE THREAD

**Issue by zellko** [TheOdinProject/curriculum#23911]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The link "**grow, shrink or change their size."** is broken. [Link!](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction-to-grid#a-look-back-at-flex)

(Path: Full Stack JavaScript > Intermediate HTML and CSS > Grid > Introduction to Grid > [A Look Back at Flex](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction-to-grid#a-look-back-at-flex))

**2. How To Reproduce:**
1. Visit the [lesson page](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction-to-grid#a-look-back-at-flex) 
2. Click link "**grow, shrink or change their size."** 
3. The link open a "404 error" page 

**3. Expected Behavior:**
- Broken link: https://www.theodinproject.com/lessons/-foundations-growing-and-shrinking
- Working link: https://www.theodinproject.com/lessons/foundations-growing-and-shrinking

**Comment by nguyens20** [comment]
Can I work on this issue ?

**Comment by 01zulfi** [comment]
Thanks for creating this issue, @zellko!

Since @zellko checked the "I would like to be assigned this issue to work on it" checkbox, they've been assigned!

**Comment by zellko** [comment]
Thanks @01zulfi to assign me this issue. But someone was quicker than me and [already did a PR](https://github.com/TheOdinProject/curriculum/pull/23915), which was merged. 

My first PR will be for next time!

**Comment by 01zulfi** [comment]
@zellko Right. Thanks for willing to contribute!
