### ISSUE TITLE
Bug - : Intermediate Git: Think like a git website mentioned in the lesson is down

### ISSUE THREAD

**Issue by unsungNovelty** [TheOdinProject/curriculum#23923]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

- [Think like a git website](http://think-like-a-git.net/) mentioned in [A Deeper Look at Git](https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git) is down.
- We should replace the website link with a link from Archive.org 's wayback machine. The latest snapshot available from Archive's wayback machine of the website is https://web.archive.org/web/20220307212419/http://think-like-a-git.net/.

**2. How To Reproduce:**

1. Go to https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git.
2. Go to Assignment section
3. Click on the 2nd assignment - Read Think like a git link.
4. You will visit http://think-like-a-git.net/ which is not available online anymore.

**3. Expected Behavior:**
- When you visit http://think-like-a-git.net/, the website should load.

**4. Desktop/Device:**

-   Device: Desktop
-   OS: Linux
-   Browser: Firefox
-   Version: v98.0.1

**5. Additional Information:**
- As mentioned above in the description of the bug section, we could just redirect it to - https://web.archive.org/web/20220307212419/http://think-like-a-git.net/ which is the last snapshot from Archive.org 's Wayback machine.

**Comment by martenmatrix** [comment]
The site is back up. @unsungNovelty

**Comment by unsungNovelty** [comment]
![image](https://user-images.githubusercontent.com/11845908/161676293-46443a55-a2cc-48c7-9cba-8cb0f58c569d.png)

@martenmatrix - Firefox, Firefox Developer edition and Chromium can't reach the website. Could you please double check?

**Comment by martenmatrix** [comment]
@unsungNovelty The site does not have an SSL certificate. You have to access the site over HTTP. I assume you are using a plugin, which automatically changes HTTP links to HTTPS links.

**Comment by unsungNovelty** [comment]
Thanks @martenmatrix ! The website is accessible. Closing this.
