### ISSUE TITLE
Bug - : Javascript Path/Javascript and the Backend/Where's Waldo project - Recipes project link broken

### ISSUE THREAD

**Issue by Sagelyyy** [TheOdinProject/curriculum#23925]
Complete the following REQUIRED checkboxes:
-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the Where's Waldo project section, there is a link to the recipe project that when clicked results in a 404

**2. How To Reproduce:**

1. Navigate to : https://www.theodinproject.com/lessons/node-path-javascript-where-s-waldo-a-photo-tagging-app
2. Go to the assignments section
3. Click the "Recipes project" link
4. Leads to a 404

**3. Expected Behavior:**

When you click the "Recipes project" link in the lesson, it leads to the correct project.

**4. Desktop/Device:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Version: 98.0.4758.102

**5. Additional Information:**

**Comment by 01zulfi** [comment]
Thanks for creating this issue!

Here's the acceptance criteria for anyone who wants to work on this:

- [ ] Replace the broken link to the Recipes project with the correct one in Assignment 1 of [Project: Where's Waldo](https://www.theodinproject.com/lessons/node-path-javascript-where-s-waldo-a-photo-tagging-app)

Please comment to be assigned!

**Comment by ItsKatato** [comment]
I would like to be assigned, please!
