### ISSUE TITLE
Style Guide - Foundations/Git Basics, The Back End, and Conclusion: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23938]
# Foundations/Git Basics, The Back End, and Conclusion Sections

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-git)
	- [ ] [Git Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/git-basics)
	- [ ] [Introduction to the Back End](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-the-back-end)
	- [ ] [Introduction to Frameworks](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-frameworks-web-development-101)
	- [ ] [Choose Your Path Forward](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/choose-your-path-forward)

**Comment by Ishmam156** [comment]
I would like to take this on, if possible :)

**Comment by thatblindgeye** [comment]
You've been assigned! Feel free to ask any questions you might have 🙂

**Comment by Ishmam156** [comment]
@thatblindgeye 

A small query regarding two out of the five lessons: Introduction to Git and Git Basics.

Duplicates of these lessons seems to exist in 2 folders of the curriculum repo:
foundations/git_basic
git/foundations_git

Should I do the changes on both folders or should it be done in any one of them and if so, which one should it be :)

**Comment by thatblindgeye** [comment]
@01zulfi can you provide assistance to the question above?

**Comment by 01zulfi** [comment]
@Ishmam156 Thanks for asking.

Files you'd want to change should be in the [`git/foundations_git`](https://github.com/TheOdinProject/curriculum/tree/main/git/foundations_git) folder. The duplicate files present in the `foundations/git_basics` folder will be moved to archive soon.

**Comment by Ishmam156** [comment]
Thank you for the clarification, @01zulfi ^_^ Preparing a PR shortly.
