### ISSUE TITLE
Style Guide - Foundations/Introduction: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23936]
# Foundations/Introduction Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [How This Course Will Work](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/how-this-course-will-work)
	- [ ] [Introduction to Web Development](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-web-development)
	- [ ] [Motivation and Mindset](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/gearing-up)
	- [ ] [Asking for Help](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/asking-for-help)
	- [ ] [Join the Odin Community](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/join-the-odin-community)
	- [ ] [How Does the Web Work?](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/how-does-the-web-work)

**Comment by ItsKatato** [comment]
Hi 👋🏾
I would like to be assigned!

**Comment by thatblindgeye** [comment]
You got it!

**Comment by thatblindgeye** [comment]
@ItsKatato hey, wanted to check and see how things were going with this issue? I don't believe this has a PR yet (unless I missed it which is possible 😆 )

**Comment by ItsKatato** [comment]
@thatblindgeye Sorry completely forgot about this. I got really busy with some classes, but I made the pull request 😅
