### ISSUE TITLE
Style Guide - Foundations/JavaScript Basics 1: Learning Outcomes and Knowledge Checks

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23934]
# Foundations/JavaScript Basics 1

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Learning Outcomes and Knowledge Check sections have the correct verbiage and formatting. If one of these sections does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following requirements:

- The Learning Outcomes section is renamed to "Lesson Overview".
- The Lesson Overview section follows the below format:
	```
	### Lesson Overview

	This section contains a general overview of topics that you will learn in this lesson.

	*   LESSON OVERVIEW ITEMS...
	```
- The Knowledge Check section follows the below format:
	```
	### Knowledge Check

	This section contains questions for you to check your understanding of this lesson on your own. If you’re having trouble answering a question, click it and review the material it links to.

	*   KNOWLEDGE CHECKS...
	```
- Each Knowledge Check item follows the below format:
	```
	*   <a class="knowledge-check-link" href="A KNOWLEDGE CHECK URL">A KNOWLEDGE CHECK QUESTION.</a>
	```
- Each Knowledge Check item redirects to a resource mentioned in the lesson, or to a section within the lesson, where the answer can be found. 
	- If it doesn't, note this in your PR, but don't remove the item.
  
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Fundamentals Part 1](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-1)
	- [ ] [Fundamentals Part 2](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-2)
	- [ ] [JavaScript Developer Tools](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/javascript-developer-tools)
	- [ ] [Fundamentals Part 3](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-3)
	- [ ] [Problem Solving](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/problem-solving)
	- [ ] [Understanding Errors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/understanding-errors)

**Comment by iawong** [comment]
Can I take this?

**Comment by thatblindgeye** [comment]
@iawong you got it! If you have any questions feel free to ask 🙂
