### ISSUE TITLE
Style Guide - Foundations/Installations: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23937]
# Foundations/Installations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Installation Overview](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installation-overview)
	- [ ] [Prerequisites](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/prerequisites)
	- [ ] [Text Editors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/text-editors)
	- [ ] [Command Line Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101)
	- [ ] [Setting Up Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/setting-up-git)

**Comment by Sankalp-G** [comment]
Hi there! I'd be glad to work on this one.

**Comment by thatblindgeye** [comment]
Just for future reference, be sure to wait until being assigned an issue before working on anything. Luckily not a big deal here, but it can definitely be helpful for everyone and avoid as much confusion and such as possible 🙂 Thank you for being willing to take this on either way, though!
