### ISSUE TITLE
Style Guide - Foundations/CSS Foundations: Learning Outcomes and Knowledge Checks

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23932]
# Foundations/CSS Foundations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Learning Outcomes and Knowledge Check sections have the correct verbiage and formatting. If one of these sections does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following requirements:

- The Learning Outcomes section is renamed to "Lesson Overview".
- The Lesson Overview section follows the below format:
	```
	### Lesson Overview

	This section contains a general overview of topics that you will learn in this lesson.

	*   LESSON OVERVIEW ITEMS...
	```
- The Knowledge Check section follows the below format:
	```
	### Knowledge Check

	This section contains questions for you to check your understanding of this lesson on your own. If you’re having trouble answering a question, click it and review the material it links to.

	*   KNOWLEDGE CHECKS...
	```
- Each Knowledge Check item follows the below format:
	```
	*   <a class="knowledge-check-link" href="A KNOWLEDGE CHECK URL">A KNOWLEDGE CHECK QUESTION.</a>
	```
- Each Knowledge Check item redirects to a resource mentioned in the lesson, or to a section within the lesson, where the answer can be found. 
	- If it doesn't, note this in your PR, but don't remove the item.
  
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [CSS Foundations](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/css-foundations)
	- [ ] [Inspecting HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/inspecting-html-and-css)
	- [ ] [The Box Model](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/the-box-model)
	- [ ] [Block and Inline](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/block-and-inline)

**Comment by Rmg92** [comment]
Can I work on this one?

**Comment by thatblindgeye** [comment]
@Rmg92 all yours! Any questions don't hesitate to ask 🙂
