### ISSUE TITLE
Style Guide - Foundations/HTML Foundations: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23939]
# Foundations/HTML Foundations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-html-and-css)
	- [ ] [Elements and Tags](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/elements-and-tags)
	- [ ] [HTML Boilerplate](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-boilerplate)
	- [ ] [Working with Text](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/working-with-text)
	- [ ] [Lists](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/lists)
	- [ ] [Links and Images](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images)
	- [ ] [Commit Messages](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/commit-messages)

**Comment by gefgu** [comment]
Hi! Can I get assigned to this job?

**Comment by thatblindgeye** [comment]
You've been assigned! Feel free to ask any questions you might have 🙂
