### ISSUE TITLE
Style Guide - Foundations/Flexbox: Learning Outcomes and Knowledge Checks

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23933]
# Foundations/Flexbox Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Learning Outcomes and Knowledge Check sections have the correct verbiage and formatting. If one of these sections does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following requirements:

- The Learning Outcomes section is renamed to "Lesson Overview".
- The Lesson Overview section follows the below format:
	```
	### Lesson Overview

	This section contains a general overview of topics that you will learn in this lesson.

	*   LESSON OVERVIEW ITEMS...
	```
- The Knowledge Check section follows the below format:
	```
	### Knowledge Check

	This section contains questions for you to check your understanding of this lesson on your own. If you’re having trouble answering a question, click it and review the material it links to.

	*   KNOWLEDGE CHECKS...
	```
- Each Knowledge Check item follows the below format:
	```
	*   <a class="knowledge-check-link" href="A KNOWLEDGE CHECK URL">A KNOWLEDGE CHECK QUESTION.</a>
	```
- Each Knowledge Check item redirects to a resource mentioned in the lesson, or to a section within the lesson, where the answer can be found. 
	- If it doesn't, note this in your PR, but don't remove the item.
  
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to Flexbox](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-flexbox)
	- [ ] [Growing and Shrinking](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/growing-and-shrinking)
	- [ ] [Axes](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/axes)
	- [ ] [Alignment](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/alignment)

**Comment by grmnmtz** [comment]
Hello, I'd like to work on this one.

**Comment by thatblindgeye** [comment]
@grmnmtz you got it! If you have any questions don't hesitate to ask 🙂

**Comment by grmnmtz** [comment]
@thatblindgeye  can I use the improve this lesson button or should I fork and clone locally and do the changes, then the PR on the fork ? It's my first contribution and I think I got the first changes.

**Comment by thatblindgeye** [comment]
@grmnmtz you can do either; you should be able to submit a single PR for all 4 lessons either way I believe if you want as well.

**Comment by grmnmtz** [comment]
@thatblindgeye I believe I just did that, Above your comment is my Pull Request with the changes, can you check if it satisfies the accepted criteria? Let me know if is there anything missing in it. Thanks.
