### ISSUE TITLE
Style Guide - Foundations/CSS Foundations: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23940]
# Foundations/CSS Foundations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [CSS Foundations](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/css-foundations)
	- [ ] [Inspecting HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/inspecting-html-and-css)
	- [ ] [The Box Model](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/the-box-model)
	- [ ] [Block and Inline](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/block-and-inline)

**Comment by zellko** [comment]
Hi ! Can I get this one ? :-)

**Comment by thatblindgeye** [comment]
@zellko you got it! Feel free to ask any questions if you have any 🙂
