### ISSUE TITLE
Style Guide - Foundations/Flexbox: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23941]
# Foundations/Flexbox Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to Flexbox](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-flexbox)
	- [ ] [Growing and Shrinking](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/growing-and-shrinking)
	- [ ] [Axes](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/axes)
	- [ ] [Alignment](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/alignment)

**Comment by hoad211** [comment]
Hi! Could I take this one please?

**Comment by thatblindgeye** [comment]
@hoad211 all yours! Don't hesitate to ask any questions 🙂

**Comment by Paloma-P** [comment]
Hi it says help wanted, can I work on this?

**Comment by thatblindgeye** [comment]
@Paloma-P Sorry about that, looks like I hadn't updated the label. This one has already been taken, but there'll be more issues like this eventually 🙂

**Comment by thatblindgeye** [comment]
@hoad211 wanted to check in and see how things were going with this issue?

**Comment by itswhom** [comment]
@thatblindgeye @hoad211 Has there been movement on this? It is something I would like to take on if it needs to be reassigned.

**Comment by thatblindgeye** [comment]
@itswhom if there is no response in another day or two would you still like to be assigned this issue?

**Comment by itswhom** [comment]
@thatblindgeye Absolutely.

**Comment by thatblindgeye** [comment]
@itswhom I've assigned you this issue if you would still like to work on it.

**Comment by itswhom** [comment]
What is the best way to make this type of change? I opened the first page and found how I can modify the markdown directly on GitHub, but should I be practicing using git somehow to bring it down to my computer, make changes there, then commit/push that way? 

Also, how do I commit/push in a way that ties it to this assigned issue? Thanks.

**Comment by itswhom** [comment]
I finished this and did a pull request. I figured I'd check another folder of pages and submit those separately, but I guess I didn't make branches for any of this so it's all together in the same PR.

I have since learned about branches and more about PRs in general, so this shouldn't happen again from me.
