### ISSUE TITLE
Style Guide - Foundations/JavaScript Basics 1: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23942]
# Foundations/JavaScript Basics Section 1

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Fundamentals Part 1](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-1)
	- [ ] [Fundamentals Part 2](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-2)
	- [ ] [JavaScript Developer Tools](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/javascript-developer-tools)
	- [ ] [Fundamentals Part 3](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-3)
	- [ ] [Problem Solving](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/problem-solving)
	- [ ] [Understanding Errors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/understanding-errors)

**Comment by thatblindgeye** [comment]
@williamw29 you got it! If you have any questions feel free to ask 🙂

**Comment by Dhawkins216** [comment]
Hey, this still said help wanted, could i help in anyway?

**Comment by thatblindgeye** [comment]
Ah thank you for pointing that out, @Dhawkins216 . Unfortunately somebody already claimed this one. There will be more issues like this soon, though! 🙂

**Comment by thatblindgeye** [comment]
@williamw29 wanted to check in and see how things are going with this issue?

**Comment by williamw29** [comment]
@thatblindgeye having a bit of an issue getting ToP running locally. I'm meeting with a friend today to troubleshoot. If all goes well I'll start on it right away

**Comment by williamw29** [comment]
@thatblindgeye working on it right now!

**Comment by williamw29** [comment]
>  ### Additional Resources
> 
> This section contains helpful links to related content. It isn’t required, so consider it supplemental.
> 
> *   ADDITIONAL RESOURCES...

I noticed that in the formatting template there is a whitespace before each line. Do you want this to be included? When I used the lesson preview tool the Additional Resources title didn't format correctly and was printing the ### on screen.

**Comment by thatblindgeye** [comment]
> > ### Additional Resources
> > This section contains helpful links to related content. It isn’t required, so consider it supplemental.
> > 
> > * ADDITIONAL RESOURCES...
> 
> I noticed that in the formatting template there is a whitespace before each line. Do you want this to be included? When I used the lesson preview tool the Additional Resources title didn't format correctly and was printing the ### on screen.

If it's causing issues when using the preview tool you can add that whitespace before each line.

**Comment by williamw29** [comment]
Sorry, I think I was unclear. It was only causing issues when I included the whitespace from the example. Should I just do without it?

**Comment by thatblindgeye** [comment]
Gotcha. Go ahead and try submitting a PR without the whitespace so I can get a better idea of what's going on. The line breaks between things would be a separate issue anyway so it wouldn't be a huge deal if it wasn't included in your PR.

**Comment by williamw29** [comment]
@thatblindgeye just made the PR!

**Comment by thatblindgeye** [comment]
Closing as PR #24066 resolves this issue. Thank you for making the updates, @williamw29 !
