### ISSUE TITLE
Style Guide - Foundations/JavaScript Basics 2: Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23943]
# Foundations/JavaScript Basics Section 2

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Additional Resources section has the correct verbiage and formatting.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The Additional Resources section is only included in non-project lessons.
	- The exception to this is if a project already has an Additional Resources section, or a similar section, in which case the section should not be removed.
- The Additional Resource section follows the below format:
	```
	### Additional Resources

	This section contains helpful links to related content. It isn’t required, so consider it supplemental.
	
	*   ADDITIONAL RESOURCES...
	```
- If the Additional Resources section does not have any resources or does not exist, it should be added and/or have the following default bulleted item:
	```
	*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
	```
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Clean Code](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/clean-code)
	- [ ] [Installing Node.js](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installing-node-js)
	- [ ] [Fundamentals Part 4](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-4)
	- [ ] [DOM Manipulation and Events](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/dom-manipulation-and-events)
	- [ ] [Revisiting Rock Paper Scissors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/revisiting-rock-paper-scissors)
	- [ ] [Fundamentals Part 5](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-5)

**Comment by Breadpaw** [comment]
I checked and saw that this Additional Resources section is completely according the style guide. It seems that the issue can be closed with no action required.

**Comment by thatblindgeye** [comment]
@Breadpaw There are still updates required in the lessons mentioned in the Acceptance Criteria. Some might need more of a minor update (changing "other content" to "related content" in the verbiage), while others require the Additional Resources section to be added completely.

**Comment by Breadpaw** [comment]
@thatblindgeye I see I have completely misread the issue description :) I get the scope of it now, though. I'd love to work on it.

**Comment by thatblindgeye** [comment]
@Breadpaw no worries! If you do catch any mistakes on my part definitely call them out! And you're assigned, any questions also feel free to ask 🙂
