### ISSUE TITLE
Bug - What You Can Do To Prepare : dead link

### ISSUE THREAD

**Issue by rcamach7** [TheOdinProject/curriculum#23951]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

This is from the Getting Hired path - What You Can Do To Prepare lesson. The link boxed below in the screenshot is no longer working.
![deadLink](https://user-images.githubusercontent.com/20146375/161196251-4465efa7-400a-43fa-95f2-17aa2d84a467.png)

**2. How To Reproduce:**
Visit link

**3. Expected Behavior:**
Takes you to the corresponding article.

**4. Desktop/Device:**
Both

**5. Additional Information:**
I tried searching for the article online but I don't believe it exists anymore. I can follow this issue up by removing the link al-together if needed.

**Comment by ItsKatato** [comment]
When an article is gone you can try using [archive.org](https://archive.org/web/) to find what you're looking for.

I think this is the proper article: [Control Your Online Reputation](https://web.archive.org/web/20201123201302/https://www.monster.com/career-advice/article/control-your-online-reputation)

**Comment by 01zulfi** [comment]
Thanks @ItsKatato for finding a working link to the article. 🎉 

@rcamach7 You've been assigned; here's the acceptance criteria:


- [ ] Replace the broken "Control Your Online Reputation" link with https://web.archive.org/web/20201123201302/https://www.monster.com/career-advice/article/control-your-online-reputation

**Comment by rcamach7** [comment]
Copy that, thanks for the info! PR submitted
