### ISSUE TITLE
Bug: Link directs to a page that no longer works as intended

### ISSUE THREAD

**Issue by PotaytoDev** [TheOdinProject/curriculum#23962]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**Description of the Bug:**
Under the [Additional Resources](https://www.theodinproject.com/lessons/foundations-problem-solving#additional-resources) sub-section in the [Problem Solving](https://www.theodinproject.com/lessons/foundations-problem-solving) lesson of the JavaScript Basics section in the Foundations path, there is a link to a video that directs to a page that no longer works as intended, since the content is no longer there.

![Image showing the link in question](https://user-images.githubusercontent.com/83526209/161406374-9b666c26-5373-42d0-8244-7d713e540beb.png)

![Image of website that no longer works as intended](https://user-images.githubusercontent.com/83526209/161406478-c3f9b9e6-9613-4a0d-9315-338e8c90f91d.png)

**Comment by abarnes1** [comment]
There's an open PR that fixes this link:
https://github.com/TheOdinProject/curriculum/pull/23948

**Comment by KevinMulhern** [comment]
Resolved with: https://github.com/TheOdinProject/curriculum/pull/23948
