### ISSUE TITLE
Layout Style Guide: Unordered lists explanation

### ISSUE THREAD

**Issue by ItsKatato** [TheOdinProject/curriculum#23975]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Since the Style Guide issues have been rolling out, it would be beneficial if the Layout Style Guide [(LAYOUT_STYLE_GUIDE.md)](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) was updated to mention that unordered lists are created by using either `-` hyphens or `*` asterisks. The layout templates in the style guide all use asterisks to create unordered lists. People working on the style guide issues may change the lesson's formatting from using hyphens to asterisks because of the templates, even if it's an unnecessary change.

**2. Acceptance Criteria:**

- [ ] Add verbiage explaining that unordered lists can be made using either `-` hyphens or `*` asterisks to [LAYOUT_STYLE_GUIDE.md](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

**3. Additional Information:**

This issue was brought up in the #23967 Pull Request by @thatblindgeye

**Comment by thatblindgeye** [comment]
You're assigned, @ItsKatato !
