### ISSUE TITLE
Ruby Path: Rails Track -> Project: Installing Rails - Add explanation on how to remove an app in Heroku

### ISSUE THREAD

**Issue by MLGabe** [TheOdinProject/curriculum#23996]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
At the end of the project the learners end up with a cool simple app on Heroku. This request is so we also explain how to remove it from Heroku.

**2. Acceptance Criteria:**
- [ ] A small explanation, with screenshots, on who to get to the delete page for the app

**3. Additional Information:**

**Comment by CouchofTomato** [comment]
Hey @MLGabe 

Thanks for the proposal. This is something best left for the student to Google if they really wanted to. They do need to get used to reading through the docs for any services they use for this kind of thing.
