### ISSUE TITLE
Javascript course: Edit react lessons to be in accordance with react 18 standards

### ISSUE THREAD

**Issue by Aureatus** [TheOdinProject/curriculum#24006]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Currently in the React lessons, 
```javascript
ReactDOM.render(<App />, document.getElementById('root'))
```
is used to render App into the root div. 

In react 18, as per [reactwg/react-18/discussions/5], reactDOM.createRoot, then rendering to that root, is the correct method,like so: 
```javascript
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
It would be beneficial to learners if we changed the code present in the react lessons to utilise this.

**2. Acceptance Criteria:**

- [ ] All instances of the legacy root API have been replaced by the new root API.
- [ ] Imports where applicable have been changed from react-dom to react-dom/client

**3. Additional Information:**

*This issue should be implemented after the create-react-app is fixed to include the new API in index.js*

**Comment by Aureatus** [comment]
The create-react-app has now been updated to include the new API, i'm happy to push a change for this if approved.

**Comment by 01zulfi** [comment]
@Aureatus Thanks for pointing this out. You've been assigned!

**Comment by Aureatus** [comment]
Hey, i'm not sure how to go about this, but there was an error in what was merged in the Router lesson. Is there a way to re-open the issue so that I can fix it? 

![image](https://user-images.githubusercontent.com/93552500/163580397-053c5b61-b2c6-4caa-9f30-7c1acacfe6f2.png)

Instead of <App /> it should be <RouteSwitch />

**Comment by 01zulfi** [comment]
@Aureatus Great catch! No need to reopen this issue, you should just create a PR.
