### ISSUE TITLE
Express 101 lesson: update "Using git" section

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#24024]
**1. Description:**

The [Using git section of the Express 101 lesson](https://www.theodinproject.com/lessons/nodejs-express-101#using-git) covers information already covered by the curriculum before (in the Restaurant Page project). Hence, it should be updated.

**2. Acceptance Criteria:**

- [ ]  Rename "Using git" section to "Using Git"
- [ ]  Replace the current content of this section with a single sentence to remind the users that they should put `node_modules` folder in a `.gitignore` file while working through this tutorial.

**3. Additional Information:**

If anyone wants to work on this, please comment to be assigned.

**Comment by iawong** [comment]
Hey, can I take this?
