### ISSUE TITLE
Rails member only project incompatibility with Rails 7.

### ISSUE THREAD

**Issue by linkonsat** [TheOdinProject/curriculum#24020]
Complete the following REQUIRED checkboxes:
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Currently, the Twitter clone project for members only is roughly 5 years old. The lesson can be viewed [here](https://www.theodinproject.com/lessons/ruby-on-rails-members-only). Due to the recent Rails path upgrade to 7, some of the code displayed in the video may not work. As such the project should either be replaced or updated to bring in line with the methods offered by Rails 7. There are a few different ways we could go about this. 1. Remove the project entirely as a simple code-along could be argued that it isn't in line with how TOP is aligned as there isn't research involved in this 2. As suggested by Timato [here](https://discord.com/channels/505093832157691914/514204607770001411/963682727238967337) we could also ask the creator of the video if we can have/access the code in order to update it to Rails 7 3. Create out own video displaying the steps. I believe the 2nd option as stated by Timato is the best to bring the Twitter clone up to date. However I do believe there are other very viable methods such as rolling out our own project or just dropping it entirely as it is a code-along.

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by ChargrilledChook** [comment]
@linkonsat I was browsing the backlog, saw this and had a look at the original author's youtube. Stroke of luck because they literally added an entirely new version updated for Rails 7 2 days ago.

It's quite long, so might take a bit of time to review but a good time to revisit this one I think

**Comment by linkonsat** [comment]
@ChargrilledChook indeed. so the total time is roughly 2 hours and 34 minutes and I will give it a watch. Although at this length, I wonder if it's worth just writing our own "practice" lesson. With an emphasis on how you can use Devise as a core concept. We already write up creating your own app for another lesson and I am a bit concerned it would be very easy to zone out if your just coding along with the video.

**Comment by ChargrilledChook** [comment]
> @ChargrilledChook indeed. so the total time is roughly 2 hours and 34 minutes and I will give it a watch. Although at this length, I wonder if it's worth just writing our own "practice" lesson. With an emphasis on how you can use Devise as a core concept. We already write up creating your own app for another lesson and I am a bit concerned it would be very easy to zone out if your just coding along with the video.

I agree that it's probably better to avoid codealongs at this point, but perhaps recommending the first two vids in additional resources could be worthwhile (if the content is any good)

**Comment by linkonsat** [comment]
@ChargrilledChook The first two could definitely be good. I am watching them and they are the only ones with Devise it seems. So definitely think recommending the first two in additional resources and saying the rest are optional could be a good touch? What do you think?

**Comment by ChargrilledChook** [comment]
> @ChargrilledChook The first two could definitely be good. I am watching them and they are the only ones with Devise it seems. So definitely think recommending the first two in additional resources and saying the rest are optional could be a good touch? What do you think?

Sounds great, I like it :ok_hand: I'll try to give them a watch when I get a chance

**Comment by linkonsat** [comment]
Sweet. I'll make the PR tonight or tomorrow.
