### ISSUE TITLE
Bug - SQL Lesson: delete statements

### ISSUE THREAD

**Issue by acedanger** [TheOdinProject/curriculum#24026]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

<hr>

**1. Description of the Bug:**
The delete statements presented are wrong. The commands are "delete * from blah" where they should be "delete from blah". The asterisk shouldn't be here. It seems these commands were copy/pasted from similar select statements where you would use "select * from blah"

**Comment by 13colours** [comment]
I'd be happy to fix this, could I?

**Comment by wise-king-sullyman** [comment]
@13colours are you still interested in this issue?

**Comment by ZDunc** [comment]
@wise-king-sullyman I can take care of this issue as well. Just let me know :)

**Comment by wise-king-sullyman** [comment]
@ZDunc I would like to give @13colours another 5 days to respond. If we still haven't heard back from them by that time I will assign you 🙂

**Comment by wise-king-sullyman** [comment]
@ZDunc are you still interested in tackling this issue?

**Comment by ZDunc** [comment]
@wise-king-sullyman yes, I can do it!
