### ISSUE TITLE
Bug - : Final JS lesson is using wording that implies it's the end of TOP for the Node path.

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#24031]
Complete the following REQUIRED checkboxes:
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

https://www.theodinproject.com/lessons/node-path-javascript-conclusion
On this page, the final paragraph talks about what to do post TOP, this should be adjusted to fit both Rails and Node's course.

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by yadunandanbhat** [comment]
like adding those links in the additional resources?

**Comment by wise-king-sullyman** [comment]
@yadunandanbhat I believe that this issue is more concerning the content of the lesson, but please correct me if I'm wrong @I3uckwheat

**Comment by liridonloku** [comment]
I remember thinking the wording was a bit weird when I reached this page, but actually thought this part:

 "However, we’re not done yet. There is yet more to learn!" 

...referred to the Node course that comes after. So I don't think it's a pressing matter, but if you want to change it, something that would work imo is separating last paragraph in two parts. Specifically after the "So where do you go from here?" question, you could have two answers depending on the path.

An example:

"If you're on the Node path, you can now move on to the node course...

If you're on the Rails path, BUILD! Build and build...."

**Comment by Pete-Fowler** [comment]
If you want to assign me, I can do some minor rewording to make this more clear, and add links to rails and node paths.

**Comment by wise-king-sullyman** [comment]
@Pete-Fowler are you still interested in taking a swing at this?

**Comment by Pete-Fowler** [comment]
Sure, I could do it Friday or this weekend.

Pete Fowler
970-366-1515

- Sent from a mobile phone

**Comment by wise-king-sullyman** [comment]
👍 you're assigned, thanks!

I'm not sure about having links to the other courses in it (since they should be able to follow the same workflow to reach whichever course is next in the same way they have previously) but you can try something like that if you want and we can see how it looks come PR time.
