### ISSUE TITLE
Advanced HTML/CSS folder: add README.md

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#24038]
**1. Description:**

This folder lacks a `README.md` file.

Related to: 
- https://github.com/TheOdinProject/top-meta/issues/109

### Course README template:

```markdown
# <course_name>

/* in case course belongs to multiple paths, make sure to link those paths */ 

This folder contains lesson markdown files that make up the <course_name> course. This course exists in the [<path_name>](<path_link>) path on the Odin Project Website.

## Course Outline

The following list represents how the lessons are divided into sections and presented on the website.

**Disclaimer:** Given the ever updating nature of the curriculum, the outline might be outdated. See the [<course_name> course on the website](<course_link>)
instead.

### <section_name>

/* make sure the lesson order corresponds to the order on the website */
/* make sure to use relative links with respect to this README to link the markdown file */

1. [<lesson_name>](<lesson_markdown_file_link>)
2. [**<project_name>**](<project_markdown_file_link>)
```

**2. Acceptance Criteria:**

- [ ] Update Advanced HTML/CSS folder's `README.md` file to the template provided above
- [ ] Remove comments from the template
- [ ] Fill in the appropriate information in the angle (`<>`) brackets in the template
  - Make sure to the path/course/lesson names correspond to what is on the website  
- [ ] Use relative links to link the markdown files
  - For example use `animation/keyframes.md` as the link to the markdown file instead of `https://github.com/TheOdinProject/curriculum/blob/main/advanced_html_css/animation/keyframes.md` 
  - Make sure the links work as intended

**3. Additional Information:**

If anyone wants to work on this, please comment to be assigned. In case of any questions, feel free to ask below.

**Comment by GokhanTurgut** [comment]
Hi, I would love to work on this as my first issue.
