### ISSUE TITLE
Add git bash to windows support

### ISSUE THREAD

**Issue by franfrutos** [TheOdinProject/curriculum#24045]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

As far as I have been able to get through the curriculum, git bash has the same functionality as the command line on linux. Maybe it would be a good idea to add git bash to allow windows users to avoid having to download a virtual machine or make a partition. 

**2. Acceptance Criteria:**

- [ ] Add a git bash alternative to windows users on the foundations path. 

**3. Additional Information:**

n/a

**Comment by yadunandanbhat** [comment]
You can actually download [git bash for windows](https://git-scm.com/download/win). It works the same as in Linux.

**Comment by kashura** [comment]
Hi @franfrutos , thank you for the suggestion.

There is much more behind our reasoning on why we don't support learning on Windows and git bash is the least of them. At this time, we simply cannot support windows. You're free to learn TOP on Windows, but there won't be any support from the TOP community.
