### ISSUE TITLE
Intermediate HTML and CSS: Form Validation: Add disclaimer to last article of assignment

### ISSUE THREAD

**Issue by tliebert** [TheOdinProject/curriculum#24058]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The final article in the assignment section (from CSS Tricks) uses Sass syntax / operators in the example code. The section on pre-processors comes laters, so the code cannot be duplicated via copy / paste, and is confusing if you have not encountered what these symbols mean. 

It would be good to have both a disclaimer and a brief description of what these do, so that the article is easier to understand.

**2. Acceptance Criteria:**

- [ ] Add a short disclaimer that you will encounter unknown syntax during the article.
- [ ] Add a brief description of what & and >  do in Sass, so that the main challenge of the lesson is in using the technique and not grappling with the processor-specific selectors. 

**3. Additional Information:**
 n/a

**Comment by KevinMulhern** [comment]
This may be a good alternative article: https://www.silocreativo.com/en/css-rescue-improving-ux-forms/

**Comment by bappyasif** [comment]
this also seem to be a good fit: [https://css-tricks.com/form-validation-part-1-constraint-validation-html/](https://css-tricks.com/form-validation-part-1-constraint-validation-html/)
