### ISSUE TITLE
Foundations Course: Split the CSS foundations lesson into multiple lessons

### ISSUE THREAD

**Issue by boostaboosh** [TheOdinProject/curriculum#24064]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Due to the nature of the CSS Foundations page and the assignments there learners end up scrolling to the different headings/learning sections of that page (like color property, image size, inline css, external css, etc.). 
Currently if a learner wants to have easy access to multiple sections of that page they have to open multiple tabs of the page and scroll down to different sections of the page, and remember which tab is open on which section. 
Initially I though it would be useful to have a table of contents displayed on the right hand side of that web page all the time to confront this issue while still making use of its structure and the assignments present on the page.
This feature would be useful and beneficial because this way a learner can quickly view information on a property they can't quite remember and is in the process of learning. A table of contents that doesn't go away when you scroll down the page would solve this and not clutter or ruin the look of the page. This way one tab is open and a learner can click on a link in the table of contents to take them to the section of the page they are interested in, like the internal CSS section for example. 

This is quite a unique page on the foundations course because it is very information dense and learners spend quite a bit of time here doing the CSS exercises.

Needing a table of contents because of scrolling too much is a pretty good indication the lesson is too long and may need split up into multiple lessons. 

**2. Acceptance Criteria:**

- [ ] The CSS foundations page has been split up into multiple lessons, for each topic discussed:
1 - Basic Syntax
2 - CSS Selectors
3 - CSS Properties to get started with
4 - The CSS Cascade
5 - An internal, external, and inline CSS lesson
Alternatively, a table of contents has been added to the side of the page that is always visible, and that has a link to each of these 5 sections.

**3. Additional Information:**

This is a link to the suggestion https://discordapp.com/channels/505093832157691914/540903304046182425/966345444349313085
This is a link to the suggestion of splitting the lesson up into multiple lessons which received positive feedback from multiple people, including the poster of the original suggestion (myself):
https://discordapp.com/channels/505093832157691914/540903304046182425/966394592079536158

**Comment by wise-king-sullyman** [comment]
@boostaboosh you're assigned on this one as well, and thanks again!

I think that 5 lessons might be a *bit* much, but if that's what you would like to propose you can of course PR it and we can evaluate it then 🙂 

If you have any questions please don't hesitate to reach out.

**Comment by thatblindgeye** [comment]
@boostaboosh just wanted to check in to see if you were still interested in doing this?

**Comment by boostaboosh** [comment]
Hi @thatblindgeye, I am still interested in doing this but I am not able to do it yet because I don't know how. When I get further along in the course and am able to I will be happy to do it. It may be a while.

**Comment by thatblindgeye** [comment]
@boostaboosh I've unassigned you for now and opened this up as help wanted. If you'd like to personally work on this just let us know and we can reassign you.

**Comment by JaeGif** [comment]
Hi, since the issue is reavailable may I be assigned?

**Comment by thatblindgeye** [comment]
@JaeGif You got it! If you have any questions about how to go about it or anything feel free to ask them in here

**Comment by JaeGif** [comment]
> @JaeGif You got it! If you have any questions about how to go about it or anything feel free to ask them in here

Thanks @thatblindgeye. Quick question about the scope of the issue as this is my first contribution. Does this include editing anchor links and handling routing to the new lessons on TOP main repo or is that handled by the main app already when I add new MD files?

**Comment by thatblindgeye** [comment]
@JaeGif So new lessons would require also making a PR in our web app repo. The wiki there has some information about adding new content: https://github.com/TheOdinProject/theodinproject/wiki

If you want to split the lesson files in this repo, but aren't sure about making a PR in our web app repo, just let me know and we can see about either opening a separate issue there for someone else to pick up, or if a maintainer can help guide you along with making a PR there! 🙂

**Comment by JaeGif** [comment]
@thatblindgeye I've broken the foundations section into 2 smaller sections, changing the wording in the introduction and the assignments sections so they follow with the new lesson structure. 

I'm debating whether to break it into 3, but I don't see a logical place to reduce the lesson right now. 
Currently, the 2 sections are:
1. Basic Syntax, Selectors, Properties, and Adding CSS to HTML
2. The Cascade

I wanted to put the sections required for getting started with basic CSS in the first lesson so that students can get started immediately on the assignment sections that don't require knowledge of the Cascade. Then introduce the Cascade and specificity in the next lesson to finish off the CSS exercises. I think both of the sections are a reasonable size now with CSS Foundations cut approximately in half. 

Should I submit the curriculum PR first and then start working on the web app PR? I imagine they need to be reviewed together.

**Comment by thatblindgeye** [comment]
@JaeGif 

I think 2 lessons is fine for now. We can always revisit another time if it still seems too bloated. For the first lesson, just to reduce the length of the title it might be better to just go with "CSS Basics" or something along those lines.

And you can submit the curriculum PR! It may not be able to get merged until a website PR gets in, but it'll give the curriculum one a chance to be reviewed ahead of that.

**Comment by KevinMulhern** [comment]
No worries 😄 
I can take care of adding the new lesson paths to the site if you'd rather focus on the curriculum side of things? Whatever you need, let me know.

**Comment by JaeGif** [comment]
@KevinMulhern sure. How can I submit just the curriculum changes, or get those to you?

**Comment by KevinMulhern** [comment]
Sorry @JaeGif,I think I see where the confusion is coming from now.

Our lesson content and the website code are in separate GitHub repos. 
* [Odin's main site repo](https://github.com/TheOdinProject) - the codebase for the website
* [The curriculum repo](https://github.com/TheOdinProject/curriculum) - all our lesson content is stored here

I'm guessing you were trying to set up the main site repo when running into the dotenv issues? you only need to deal with curriculum repo and can ignore the main site.

To add a new lesson, you just need to add a markdown file to the appropriate folder in the curriculum repo. No set up required, it's just a collection of folders and lesson markdown files.

In your case for these css lessons, the appropriate folder would be this one: https://github.com/TheOdinProject/curriculum/tree/main/foundations/html_css 

Heres an example of recent PR where we've added a new lesson to give you a better idea of how it works: https://github.com/TheOdinProject/curriculum/pull/25179

I can appreciate this isn't all that straight forward. If you have any questions, don't hesitate to hit me with them.

**Comment by KevinMulhern** [comment]
Looks great, thanks for all the effort you've put into @JaeGif. Someone will review that PR soon.
