### ISSUE TITLE
Foundations Course: Including an explanation of a display property in the box model lesson

### ISSUE THREAD

**Issue by boostaboosh** [TheOdinProject/curriculum#24063]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

On this page https://www.theodinproject.com/lessons/foundations-the-box-model of the foundations course introducing the box model I think that it would be worth adding a few lines of information about the display property before the link to MDN webpage that talks about the box model because I think the display property and the lack of an explanation of what it is on the MDN box model web page can be quite confusing for beginners. 
A few lines of information would be very beneficial because learners can read it before reading the MDN page on the box model. 
Something along the lines of: 

"The display property controls both outer as well as inner display type. Outer display type refers to whether an element is display:block or display:inline
Inner display type on the other hand, refers to whether the content inside an element is in the normal flow or affected by display:flex or display:grid(which you'll learn about later)

So, the .block class affects the outer display type of the span. 
The display:flex on the ul on the other hand affects its inner display type, making the list go side by side"

**2. Acceptance Criteria:**

- [ ] A few lines of information to introduce the CSS display property is present before the link to the MDN webpage on the box model, located at point 2 of the assignment section of The Box Model chapter of the CSS Foundations section of the Foundations course.

**3. Additional Information:**

https://discordapp.com/channels/505093832157691914/540903304046182425/966394401054154803 this is a link to a discord message where in response to my suggestion I was asked to make a GitHub issue for my suggestion. I made the suggestion after I was having trouble with this section of the course and required help in the html/css channels of the discord server. This suggestion being implemented could save help resources in the future which I think is a benefit.

**Comment by wise-king-sullyman** [comment]
@boostaboosh you're assigned! Thank you for taking the time to craft this issue and for wanting to help make the curriculum better 🙂

**Comment by thatblindgeye** [comment]
@boostaboosh Wanted to check if you were still interested in resolving this issue?

**Comment by boostaboosh** [comment]
Hi @thatblindgeye , I am still interested in doing this but I am not able to do it yet because I don't know how. When I get further along in the course and am able to I will be happy to do it. It may be a while.

**Comment by Kingbot13** [comment]
I would be interested in taking over this issue @thatblindgeye if @boostaboosh no longer wants to work on it or isn't able to work on it. I can add a few lines describing the display property or link to an mdn article which in my opinion does a great job of explaining the display property.

**Comment by boostaboosh** [comment]
> I would be interested in taking over this issue @thatblindgeye if @boostaboosh no longer wants to work on it or isn't able to work on it. I can add a few lines describing the display property or link to an mdn article which in my opinion does a great job of explaining the display property.

@Kingbot13 Hey, that sounds good to me.

**Comment by Kingbot13** [comment]
@boostaboosh , upon further review, I feel like the linked article to the box model does a sufficient job of explaining outer and inner displays as well as how to use the display property. It also links to the article I mentioned in my earlier comment, so readers can learn more about display if they so choose. Do you mind glancing over the mdn article again and letting me know if you still feel like more information about display is needed? [mdn box model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model)

**Comment by thatblindgeye** [comment]
Based on the above comment, I will be closing this issue out. If there are still updates to be made, it can be reopened.
