### ISSUE TITLE
Positioning lesson: 'Additional Resources' heading is shown without any content

### ISSUE THREAD

**Issue by bappyasif** [TheOdinProject/curriculum#24104]
in positioning [article](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-positioning), "Additional Resource" section has no "content in it" but "Heading remains" without even it's usual 'explanation' section in it

![image](https://user-images.githubusercontent.com/19854521/166975926-0c48c3e7-9375-4bfe-8be3-19531375cc18.png)

section link: https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-positioning#additional-resources

**Comment by 01zulfi** [comment]
@bappyasif Thanks for reporting!

If anyone wants to work on this issue, please comment below to be assigned.

Here's the acceptance criteria:

- [ ] Align the Additional Resources section of the [Positioning lesson](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-positioning#additional-resources) with the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

**Comment by iawong** [comment]
Hey, can I take this?

**Comment by bappyasif** [comment]
i am also interested!

**Comment by 01zulfi** [comment]
@bappyasif Unfortunately this issue is already assigned. For reference, if you are interested in working on an issue you created, make sure to use our issue templates, we have a checkbox specifically for interest.

**Comment by bappyasif** [comment]
@01zulfi just a thought experiment, dont you think we should tack this issue from 'js perspective' as in,  same text is going into all chapters, why not deal with it 'programatically'! same kind of thing but not quite same, me and @KevinMulhern dealt few weeks earlier where path 'course list' heading being shown 'when there is multiple course list in that path but not for solo course', if that makes any sense, thanks
