### ISSUE TITLE
Ruby: Update recommended Ruby version to 3.1

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/curriculum#24112]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

I'm happy to but it may be a good one for a less experienced contributor. I also need to finish a different issue first.

<hr>

**1. Description of the Feature Request:**

Ruby 2.6 has recently hit EOL, and Ruby 3.2 has a preview branch - we're at a point in the patch cycle where 3.1 is reasonably stable and should be safe to upgrade to. 

On top of that, there are issues with pre 3.1 versions of Ruby on Ubuntu 22.04 due to incompatibilities with openssl v3. Updating the recommended Ruby version could help get in front of this a little as people begin to move to the new LTS Ubuntu version.

**2. Acceptance Criteria:**

- [ ] The installation lesson is updated to Ruby 3.1
- [ ] Exercise repositories are also updated (ie `.ruby-version` files)
- [ ] Any other references throughout the curriculum are updated as needed

**3. Additional Information:**

Probably worthwhile looking at previous PRs to upgrade the version to check places where things need to be updated

**Comment by scheals** [comment]
The Ubuntu 22.04 issues Chook mentions have already started to crop up. Possible fixes are here:
https://deanpcmad.com/2022/installing-older-ruby-versions-on-ubuntu-22-04/
https://github.com/rbenv/ruby-build/discussions/1940#discussioncomment-2663209

They are even known by the rbenv maintainers (as linked above) and Ruby maintainers:
https://bugs.ruby-lang.org/issues/18658#note-4

It's all pretty fresh mind you, so maybe those people are going to figure something out. As it currently stands, I have managed to install Ruby 3.1.2 on a 20.04 Xubuntu and failed to install 3.0.3 on Ubuntu 22.04 with the same error message everyone posts. 
I can test those workarounds linked if y'all want to go with that route.

**Comment by wise-king-sullyman** [comment]
@ChargrilledChook @scheals before I put the help wanted and good first issue tags on this, are either of you wanting to knock this issue out?

**Comment by ChargrilledChook** [comment]
@wise-king-sullyman my bandwidth is fairly low at the moment and I think it's a good one for a beginner, so I'm happy to pass for now. If no one has picked it up in week or so I can come back to it.

Either as part of this issue or in a separate one, it would be good to update the Ruby version in the Ruby exercise and testing repos (maybe custom enumberbales too?)

**Comment by scheals** [comment]
Looked into how rbenv discussion is looking like https://github.com/rbenv/ruby-build/pull/1974 it seems that they've begun work on some kind of a solution recently but aren't really happy with it and for now rbenv is only supporting 3.1+ for 22.04.

@wise-king-sullyman Yeah, I'll gladly work on this but I might need help if problems occur. 

@ChargrilledChook Given that the idea would be to update the various repos and such would we want to update various gems in them too?
Because of #23552 I could swap the instructions for installing the gem there as well on my way there. Of course I'd test everything on fresh 20.04 and 22.04 Xubuntu VMs to make sure everything works.

**Comment by wise-king-sullyman** [comment]
@scheals since you're interested in it and this issue seems to be kind of growing in scope to include a decent amount of investigation I think I'd rather see you work on this than bring a new contributor in. If you do run into problems please don't hesitate to reach out.

And thanks for wanting to do this!

**Comment by ChargrilledChook** [comment]
@wise-king-sullyman sounds good. 

@scheals  I'm happy to assist if you want any input / a second pair of eyes. Feel free to reach out if you need :+1:

**Comment by scheals** [comment]
@ChargrilledChook Thank you!

Yeah, was rather absent-minded when it came to the gems and the fact it is different repos. Still, I'll be going through it so I'll try my best to touch on that as well.

**Comment by scheals** [comment]
I found the past issue about upgrading to 3.0 https://github.com/TheOdinProject/curriculum/issues/23434 stashing it here for continuity's sake.

**Comment by ChargrilledChook** [comment]
@scheals The three exercise updates look good at a glance, have you given them a quick test drive with Ruby 3.1 to make sure nothing blows up? ( I doubt there would be any major issues, but you never know).

Once the changes in the curriculum PR are made we should be good to wrap this up. 

Thanks again for all your work on these :tada:

**Comment by ChargrilledChook** [comment]
> I believe some sort of update to the Pattern Matching lesson might be in order because from what I've gathered some form of Rightward Assignment is no longer experimental but only one of couple, whatever that means.

Not a bad idea at all, but I'm personally not fussed if it doesn't make it in with this set of changes (although feel free if you'd like to do the legwork). Probably worth raising another issue for it if you would prefer to do it down the track

**Comment by scheals** [comment]
> > I believe some sort of update to the Pattern Matching lesson might be in order because from what I've gathered some form of Rightward Assignment is no longer experimental but only one of couple, whatever that means.
> 
> Not a bad idea at all, but I'm personally not fussed if it doesn't make it in with this set of changes (although feel free if you'd like to do the legwork). Probably worth raising another issue for it if you would prefer to do it down the track

I will raise a new issue, seems most reasonable to me.

**Comment by ChargrilledChook** [comment]
@scheals Great effort, thanks for your work on this. I don't currently have access to the Custom Enumerables repo so I can't merge that one, but the rest are all sorted. It should be fine in the meantime.
