### ISSUE TITLE
I want to contribute to this open source project

### ISSUE THREAD

**Issue by Jessemccallums** [TheOdinProject/curriculum#24133]
Complete the following REQUIRED checkboxes:
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by Tribhuwan-Joshi** [comment]
@Jessemccallums  For contribution you have to commit changes in the file and _must_ complete the Required checkboxes

**Comment by dm-murphy** [comment]
Thank you for your interest in contributing @Jessemccallums! Please read through [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md) which will detail the process on all the ways you can make that happen.
