### ISSUE TITLE
Foundations: Text Editors | Assignment video changed causing users to have trouble following it

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#24135]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
It seems to me that the video in https://www.theodinproject.com/lessons/foundations-text-editors assignment section https://code.visualstudio.com/docs/introvideos/basics might have changed. As such, it asks the watcher to run the code using F5 which runs the debugger but I talked with two users that had trouble using it since they don't have node installed. 

I do not remember this video being the one I watched - I am pretty sure it was a video featuring the same person as in this one:
https://code.visualstudio.com/docs/introvideos/codeediting

To fix this I think there are two outs:
- Find the old video and link to it since I do not recall anyone having trouble with it
- Rewrite the instructions so the users can handle the "running the code" portion by letting them know that they can just skip it at this point, as the tool needed for running it is going to be installed later in the curriculum

**2. Acceptance Criteria:**
- [ ] The old video is brought back
OR
- [ ] Instructions are rewritten in such a way that users are not confused 

**3. Additional Information:**
Discord message that documents second occurrence of this problem:
https://discord.com/channels/505093832157691914/540903304046182425/975110666723663942 
Third occurrence:
https://discord.com/channels/505093832157691914/505093832157691916/979444195200753804

**Comment by scheals** [comment]
Another occurence:
https://discord.com/channels/505093832157691914/690639791380758558/984836328132866048

**Comment by xandora** [comment]
We could drop the video entirely. It's just an introduction to VS Code anyway, and only confuses people when it goes into installing Node.js and starts talking about Python after that.

**Comment by scheals** [comment]
> We could drop the video entirely. It's just an introduction to VS Code anyway, and only confuses people when it goes into installing Node.js and starts talking about Python after that.

Doesn't seem like a bad solution to me either.

**Comment by scheals** [comment]
@xandora 
Have Maints talked about this? Would love to fix this issue.

**Comment by xandora** [comment]
@scheals I'm glad GitHub thinks about these things, because I didn't see that ping.

If you still want to work on this, it's all yours. We probably want to either find a more appropriate VSCode tour, or just remove it entirely if there isn't a suitable replacement.

**Comment by scheals** [comment]
@xandora What about digging up the old one through waybackmachine?

**Comment by scheals** [comment]
Stashing the link to old video, directly from microsoft:
https://www.microsoft.com/videoplayer/embed/RWz32O

**Comment by scheals** [comment]
I know that you've changed this in the meantime @xandora (sorry for not doing it myself...) but we've had a user refer to the original MS's video being a better fit here:
https://discord.com/channels/505093832157691914/505093832157691916/1015727446311583825
They'll hopefully leave some more feedback later.

**Comment by scheals** [comment]
Since #24513 's change we don't see any more issues regarding the video it seems. Closing the issue.
