### ISSUE TITLE
Code shown in a lesson is not working and is probably deprecated

### ISSUE THREAD

**Issue by Magmusacy** [TheOdinProject/curriculum#24165]
In that [lesson](https://www.theodinproject.com/lessons/ruby-on-rails-apis-and-building-your-own) in section "Rendering Nothing or Errors" there is this code: 

    def index
      render :nothing => true, :status => 404
    end

which according to this [article](https://ogeek.cn/qa/?qa=921266/) is not working since rails 5.1.
I suppose the correct version of this code snippet should be: 

    def index
      head 404
    end
but im not quite sure if that's the new conventional way of handling errors

**Comment by Magmusacy** [comment]
Sure, I can give it a go

**Comment by ChargrilledChook** [comment]
@Magmusacy Thanks! It's all yours.
