### ISSUE TITLE
Add guest sign-in to final NodeJS project

### ISSUE THREAD

**Issue by DevlinRocha** [TheOdinProject/curriculum#24168]
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The first requirement for the [final NodeJS project](https://www.theodinproject.com/lessons/nodejs-odin-book) is that users must sign in to see anything except the sign in page. I think it should be encouraged for Odinites to implement some sort of guest or anonymous sign in (no credentials required) feature, perhaps in the extra credit.

**2. Acceptance Criteria:**

- [ ] A new project requirement or extra credit item in place describing the guest/anonymous sign in feature and a brief description why it's important to include

**3. Additional Information:**

The reason I am requesting this change is that if Odinites are to eventually put this project on their résumés or show it to other people (especially recruiters) most will not make it past the sign in screen if they are forced to create an account. **_They won't see any of their hard work!_**

I have a project with similar functionality (the final JavaScript project) and guest sign-in was one of the last things I implemented... As of right now there are 38 registered users and 140 guest accounts. Most of those guests would not have created an account otherwise, and never seen anything beyond the sign-in screen.

I originally heard this advice from [Danny Thompson](https://twitter.com/DThompsonDev). I cannot find his original tweet, but here is a [video explanation](https://www.instagram.com/reel/CY8MYEvJdTz/?igshid=YmMyMTA2M2Y=).

**Comment by 01zulfi** [comment]
Thanks for creating this issue. I think this is a fine suggestion. Adding a guest user sign in should at least be in the extra credits section. 

You've been assigned.
