### ISSUE TITLE
Out of date Action Cable lesson for Rails 7

### ISSUE THREAD

**Issue by egemen-github** [TheOdinProject/curriculum#24186]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

This is my fist Issue, I am sorry if this isn't the correct format.

**1. Description of the Bug:**

**Ruby on Rails section**, websockets and actioncable lesson's assignment number 2 is out of date. Assignment number 2 is a GitHub lesson which you get to create a Rails chat app. But is not possible to complete the lesson as it is out of date. It is not applicable with Rails 7 anymore. 

Lesson: https://www.theodinproject.com/lessons/ruby-on-rails-websockets-and-actioncable

![Screenshot 2022-06-02 231104](https://user-images.githubusercontent.com/93445248/171736183-f6bb9220-c4f8-40ae-a65f-a7d84b155367.jpg)

**2. How To Reproduce:**

https://github.com/TheOdinProject/curriculum/blob/main/ruby_on_rails/mailers_advanced_topics/actioncable_lesson.md#action-cable

At some point in the lesson you need to have a server log like 
```
Unable to process MessageChannel#receive({"message"=>{"body"=>"hello"}})
```
However, I get something totally different on server log. Therefore from that point on, project becomes impossible to complete.
I am attaching my discord message about the problem - I was suggested to open an issue about this because this is not only me, others experienced the same problem with this GitHub Lesson.

Discord message: https://discord.com/channels/505093832157691914/514204607770001411/981922874589872168

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device:  Desktop 
-   OS:  Linux 
-   Browser: 
-   Version:  Ruby +3, Rails +7

**5. Additional Information:**

This is not a bug, but rather an out of date lesson which we can't complete. Maybe it can be revised or removed.

**Comment by ChargrilledChook** [comment]
@egemen-github Thanks for the detailed write up and all the context, great report :+1: 

Were you able to finish this lesson with the fixes from the previous discussion, or any other approaches?

**Comment by ChargrilledChook** [comment]
Related PR: #24088

**Comment by egemen-github** [comment]
@ChargrilledChook I changed "turbolinks:load" with "turbo:load" in JS controller, but this didn't solve the problem. I copy pasted everything from the lesson, however real time message update is still an issue. I need to reload the page to see the message that was sent. I decided to stop working on this lesson and went back to https://www.theodinproject.com/lessons/ruby-on-rails-turbo and watched the Hotwire Demo Video (shows how to create a chat app with turbo) and completed that. That way my approach :)

**Comment by zfz** [comment]
@egemen-github Hi, thank you so much for your PR! 

I found only changing `turbolinks:load` is not enough, we should also assign `consumer.subscriptions.create` to a const object `messageChannel`, which will be called later to send the message. The final working version of `app/javascript/channels/message_channel.js`: 
```js
import consumer from "channels/consumer"

const messageChannel = consumer.subscriptions.create("MessageChannel", {
  connected() {
    // Called when the subscription is ready for use on the server
  },  

  disconnected() {
    // Called when the subscription has been terminated by the server
  },  

  received(data) {
    // Called when there's incoming data on the websocket for this channel
  }
});

document.addEventListener("turbo:load", () => {
  let form = document.querySelector('#message-form')
  if(form) {
    form.addEventListener('submit', (e) => {
      e.preventDefault()
      let messageInput = document.querySelector('#message-input').value
      if(messageInput == '') return;
      const message = { 
        body: messageInput
      }   
      console.log(`Send message ${message.body}`)                                                                                                             
      messageChannel.send({message: message})
    })  
  }
})
```

The tutorial should remind us to declare `messageChannel`, while Rails generated file doesn't do this. Thanks!

**Comment by thejwuscript** [comment]
Hi guys, 

@egemen-github Did your issue of real-time message update occur after signing in and trying to post a message? If that's the case, I also had the same problem. I fixed it by disabling turbo on the sign in form. 

@zfz I read the e-mail you sent me, thanks. I agree with your suggestion to tell users to add the `const messageChannel `declaration. As it stands, It is a little confusing to say 
>..., but you will need to verify that the constant messageChannel is declared.

when it wasn't declared to begin with.

**Comment by egemen-github** [comment]
@zfz Thanks for the additional info. I checked my app and ```app/javascript/channels/message_channel.js``` file is containing ```const messageChannel``` object as you mentioned above. 

@thejwuscript 
> Did your issue of real-time message update occur after signing in and trying to post a message?

Exactly. Message is going to server successfully but not displaying on the html for the both sides (sender and receiver).

This is not a huge issue for me as I passed this lesson but I want to start this project over once I have some free time again.

**Comment by thejwuscript** [comment]
I'd prefer if we can address those issues in a separate PR.

**Comment by ChargrilledChook** [comment]
@thejwuscript @zfz @egemen-github Thanks everyone for sharing your thoughts and insights on this! I'm not currently super across all the issues in the lesson as I haven't had a chance to run it with the Rails 7 changes. 
Could you guys tell me if we still need to make some more changes for the lesson to function correctly, even after the changes [here](https://github.com/TheOdinProject/curriculum/pull/24088)?

**Comment by zfz** [comment]
@ChargrilledChook  Hi, with the PR [Action Cable Assignment: Update 'Simple Messaging App' code-along](https://github.com/TheOdinProject/curriculum/pull/24088), I can successfully pass through this lesson with `Rails 7`. But not sure if there's any issue with lower versions of Rails.

**Comment by ChargrilledChook** [comment]
@zfz Thanks for getting back to me. If it's now Rails 7 safe, I think that's good enough for now. It doesn't seem to be cropping up as an issue in chat so we can revisit if it continues to be an issue.

**Comment by egemen-github** [comment]
> @ChargrilledChook Hi, with the PR [Action Cable Assignment: Update 'Simple Messaging App' code-along](https://github.com/TheOdinProject/curriculum/pull/24088), I can successfully pass through this lesson with `Rails 7`. But not sure if there's any issue with lower versions of Rails.

That's very good to know. Can't wait to try it out!
