### ISSUE TITLE
Foundations Course Revisiting RPS lesson: Rewrite Sharing code example

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#24180]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

**The issue can be found within this section:** [foundations-revisiting-rock-paper-scissors#sharing-code](https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors#sharing-code "https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors#sharing-code")

There is an example use-case for branches shown that seems confusing as it is roughly formatted as the usual assignments with specific steps in the curriculum. Students have asked in Discord how they should complete these steps (which they shouldn't). 

**Proposed change**: Keep the use-case in there for sharing faulty code with a peer. Explain that you would commit your changes to the newly created branch but leave out the steps as shown since they will mostly be repeated in the actual assignment.

Then remove the last sentence:

>Thankfully, branches make it easy to share code on GitHub without having to commit problematic code where it can be seen in the future!

and change it to something along the lines of:

>You could instead create a new temporary branch and commit your code to that permanent branch. If you then push that temporary branch to GitHub you can share it with others to help you solve the problem.

**How this would improve the lesson**: It will remove any doubt if those steps should or shouldn't be followed. Right after this specific use-case is the actual assignment to branch your RPS repo which will follow the required steps to teach students how to create and switch branches. 

**2. Acceptance Criteria:**

- [ ] remove the steps for the example within the sharing code section.
- [ ] Change the last sentence to a written out summary of the steps.

**3. Additional Information:**

[Link to the conversation in Discord](https://discord.com/channels/505093832157691914/540903304046182425/979849670996160583)

**Comment by dm-murphy** [comment]
This sounds great @ManonLef! I've assigned you to this issue.

Perhaps when reworking that paragraph there could also be a note or an additional line mentioning that learners will get to practice something along these lines in the Assignment section. Your call if you think that would be helpful or not!

One last thing that sticks out to me is this line from the 4th list item: "You (or anyone else with the link to your repo!) can now select your temp branch using the branch selector dropdown."

That piece of information might be reworked into the Assignment section's 1.b. where it mentions seeing your two branches on GitHub. It could be worthwhile to point out the dropdown selector and that if you were sharing code with someone else they can select your other branch too.

Thanks again for taking this on :-)
