### ISSUE TITLE
Style Guide - Foundations/Introduction: Assignments

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24188]
# Foundations/Introduction Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Assignment section has the correct formatting. If this section does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following bulleted requirements:

- If a lesson has a section named Exercise, Practice, or something similar, its contents is moved to the Assignment section.
    - To see a before and after example of this, checkout the previously merged pull request for https://github.com/TheOdinProject/curriculum/pull/23825, specifically the "Files changed" tab.
- The Assignment section follows the below format:
	```
	### Assignment

	<div class="lesson-content__panel" markdown="1">

	1.  A RESOURCE OR EXERCISE ITEM
	    *   AN INSTRUCTION ITEM

	</div>
	```

- Do not make any updates to any actual list numbering, indentation/spacing, etc., as this will be covered by a separate issue.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Join the Odin Community](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/join-the-odin-community): for this lesson, swap Assignment items 2 and 3, with any re-wording you feel would make for a better flow. Additionally, for the instruction "Link your GitHub to your Discord profile", this should be a bulleted item with the steps to do so ("Discord Settings > Connections > ...") made inline.

**Comment by Maheshkumar-novice** [comment]
@thatblindgeye if this is still available, I will take this one.

**Comment by thatblindgeye** [comment]
@Maheshkumar-novice sure! You've been assigned. Any questions feel free to ask 🙂

**Comment by Maheshkumar-novice** [comment]
Okay sure @thatblindgeye. Thank you!
