### ISSUE TITLE
It says type code . to open all files in directory. Shouldnt it be code *?

### ISSUE THREAD

**Issue by xandora** [TheOdinProject/curriculum#24201]
### Discussed in https://github.com/TheOdinProject/curriculum/discussions/23657

<div type='discussions-op-text'>

<sup>Originally posted by **qasimala** February 26, 2022</sup>
In the installations section of the foundations chapter, it says to type "code ." to open all files in that directory. However, on every terminal that I've tried, that doesn't work. A new empty vscode window just pops up. I was wondering if this is for a specific terminal or is this a mistake? 

What works for me on every terminal is "code *". If this is a mistake, I can do a pull request and make the change but I feel like I'm missing something. That's why I decided to ask here. 
Thanks. </div>

**Comment by xandora** [comment]
Good catch. It should say something like:

    [...] if you have VS Code installed, you can cd into the project directory and then type code . (with the period) to open up that folder in VS Code.

This is an easy one for a first time contributer.

**Comment by thejwuscript** [comment]
I'd like to take this on if it is still available.

**Comment by xandora** [comment]
> I'd like to take this on if it is still available.

Thanks for volunteering. I'm not married to the wording in my example, so word it how you think would read best and we'll review it from there.
