### ISSUE TITLE
Git Basics lesson: move bonus section before the conclusion

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#24206]
**1. Description of the Feature Request:**

[Changing The Git Commit Message Editor](https://www.theodinproject.com/lessons/foundations-git-basics#bonus-changing-the-git-commit-message-editor) is currently a bonus section of the lesson. I believe it should be part of the lesson itself. The reason being is we don't want users to skip setting up VSCode for Git, as it might cause confusion with VIM/Nano when writing commit messages for the users.

**2. Acceptance Criteria:**

- [ ] Move the Changing The Commit Message Editor section before the conclusion of the lesson
- [ ] Remove "bonus" from the title and the first sentence of the section

**3. Additional Information:**

If anyone wants to work on this, please comment to be assigned. If there are any thoughts/questions, please feel free to share below.

**Comment by tramio** [comment]
Hello! I'd love to take over this issue, may I have it assigned? 😃
