### ISSUE TITLE
Bug - NodeJS Members Only project: Inconsistency in instructions

### ISSUE THREAD

**Issue by liridonloku** [TheOdinProject/curriculum#24214]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

There's a small inconsistency in the instructions for the project. Point 7 says to 'only show the author and date of the messages to other club members', while point 9 says 'only members should be able to see the author of each message' without mentioning the date.

This makes it hard to know whether to hide the date of messages from regular users or not.

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by 01zulfi** [comment]
Hello 👋 

I feel the intent of point 9 is to show the author **and** the date of the message to users who are members and/or admins. Signing up should **only** allow users to post messages.  What do you think about this?

**Comment by liridonloku** [comment]
I think that was the intent too, but I also think it would be beneficial to add the  "and date" to point 9 to prevent any confusion, since both point 7 and 9 refer to members and not regular users, and they should use the same wording.

Based on how the instructions are written now, I understand that a regular user can post and they can't see post authors, but it's unclear whether they should be able to see the date or not. Point 7 explicitly says no, but point 9 which is a 'recap' doesn't mention the date anywhere, and that makes me wonder if they included it at point 7 by accident or they omitted it from point 9 by accident.

Hopefully this is clear.

**Comment by 01zulfi** [comment]
Thanks for clarifying. Totally agreed with what you said. Here's the acceptance criteria:

- [ ] Modify point 9 in the [Members Only assignment](https://www.theodinproject.com/lessons/nodejs-members-only#assignment) that only users that have member privileges should be allowed to see authors AND date of the message

Do you want to take this on @liridonloku, if you don't want to, that's okay as well.

**Comment by liridonloku** [comment]
Yeah I can make the change @01zulfi. Though if you want to use it as a good first issue for someone else, that's ok with me too. 

I'll wait for your response/assignment before moving ahead with it.

**Comment by 01zulfi** [comment]
Cool, thank you. You're assigned, @liridonloku !
