### ISSUE TITLE
Block and Inline Lesson page: Unnecessary Link

### ISSUE THREAD

**Issue by SedlavJ** [TheOdinProject/curriculum#24213]
On the Block and Inline Lesson web page in the additional resources section there is a link which leads to : http://web.archive.org/web/20210813033024/https://learnlayout.com/no-layout.html that is creating a delay in loading in the browser. 

Suggesting to eliminate the http://web.archive.org/web/20210813033024/ part of the URL. https://learnlayout.com/no-layout.html works fine.

**Comment by SedlavJ** [comment]
Hi. I thought I created it. Confused. I just wanted to let staff know about
my bug report is all.

**Comment by LeoKirasic** [comment]
Gotcha! Thank you for creating the issue!

If anyone would like to work on this, please tag me and I'll assign you !

**Comment by matristle** [comment]
I'll take this one @LeoKirasic. Seems like a simple link swap at first glance.

**Comment by SedlavJ** [comment]
Awesome, thanks!
