### ISSUE TITLE
React Router Lesson: Add small blurp/section on why use router

### ISSUE THREAD

**Issue by palmerusaf** [TheOdinProject/curriculum#24210]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

**2. Acceptance Criteria:**

**3. Additional Information:**

When I was completing this section I was wondering why even use router as opposed to just using links. I think highlighting the fact that router prevents a screen flash/refresh at the beginning of the lesson could help people get excited about learning router, while at the same time helping them understand its benefit. Maybe the following link could be helpful as well. https://medium.com/@marcellamaki/a-brief-overview-of-react-router-and-client-side-routing-70eb420e8cde

**Comment by 01zulfi** [comment]
Hello 👋 

Thanks for bringing this up. I feel that updating the introduction of the Router lesson should be sufficient. We can expand a little on client-side routing and touch on the need for React Router. What do you think?

**Comment by palmerusaf** [comment]
Sound good to me!

**Comment by 01zulfi** [comment]
Thinking more on this, I suppose we can add a section on "Client-side Routing". Here's the acceptance criteria if anyone wants to pick it up:

- [ ] Add a section called "Client-side Routing" right after Learning Outcomes
- [ ] In the new section, discuss client-side routing and why it's useful. Then, briefly touch upon how React Router is handy for routing in React applications. For writing this new section, these articles may be used for reference: 
      1. [A brief overview of React Router and Client-side routing](https://medium.com/@marcellamaki/a-brief-overview-of-react-router-and-client-side-routing-70eb420e8cde)
      2. [React Router and Client-side routing](https://betterprogramming.pub/react-router-and-client-side-routing-2e483452fbfb#:~:text=Client%2Dside%20routing%20is%20the,%2Dpage%20applications%20(SPAs).)
- [ ] Rename the "React Router" section to "How To Use React Router"

**Comment by Lakshmikant-2001** [comment]
@01zulfi I am willing to pick this up, shall I?

**Comment by 01zulfi** [comment]
Yes, you're assigned, @Lakshmikant-2001
