### ISSUE TITLE
Project: Embedding Images and Video | How to add my solution

### ISSUE THREAD

**Issue by michael-duke** [TheOdinProject/curriculum#24223]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I would like to add the solution to my YouTube Video player page Project, I have made my github page aswell as recommended but the [video for my question](https://www.youtube.com/watch?v=V74l_zS1x8E) can't help me find thee solution section
Here's my project [Youtube Video Player Page](https://github.com/michael-duke/odin-YouTube-video-player-page) and [this is the Github Page](https://michael-duke.github.io/odin-YouTube-video-player-page/)
**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by 01zulfi** [comment]
Hello 👋 

The YouTube video player project has been archived, as we have released new HTML/CSS material on The Odin Project few 
months back. 

Nevertheless, once you complete an Odin project, you can submit it right on our website by following these steps;
1. Navigate to the project page on [https://www.theodinproject.com/](https://www.theodinproject.com/) of the project you completed
2. Make sure you are signed in on the website
3. Scroll to the bottom of the page. You should see other submissions and an option to add your own
4. Click the Add Solution button. There you will be prompted to provide the live preview URL and GitHub repo URL


Closing this issue now, if you have further questions, feel free to ask.
