### ISSUE TITLE
Intermediate HTML and CSS > Form Basics > Textarea: Add info about Textarea resize style

### ISSUE THREAD

**Issue by ZachPoole** [TheOdinProject/curriculum#24228]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

<hr>

**1. Description of the Feature Request:**

Add information about how you can prevent the resizing of a textarea element by setting the resize style to none. I think this would pair well with the information about how to set the initial size of the element with the rows and cols attributes.

**2. Acceptance Criteria:**

- [ ] Information added about how you can use the resize style to control the ability to resize the textarea element

**3. Additional Information:**

[W3Schools How To Disable Resizing of Textarea](https://www.w3schools.com/howto/howto_css_disable_resize_textarea.asp)

**Comment by ZachPoole** [comment]
Ah I didn't know it was in one of the articles. Just being honest though I feel people might not read all the articles, however it is just a minor thing, if people really want to know it they can google it

**Comment by ChargrilledChook** [comment]
@ZachPoole thanks for the suggestion! If you think it's a change worth making I'm happy for you to make a PR, but your call.
