### ISSUE TITLE
Style Guide - Foundations/HTML Foundations: Assignments

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24238]
# Foundations/HTML Foundations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Assignment section has the correct formatting. If this section does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following bulleted requirements:

- If a lesson has a section named Exercise, Practice, or something similar, its contents is moved to the Assignment section.
- The Assignment section follows the below format:
	```
	### Assignment

	<div class="lesson-content__panel" markdown="1">

	1.  A RESOURCE OR EXERCISE ITEM
	    *   AN INSTRUCTION ITEM

	</div>
	```

- Do not make any updates to any actual list numbering, indentation/spacing, etc., as this will be covered by a separate issue.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-html-and-css)
	- [ ] [Elements and Tags](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/elements-and-tags)
	- [ ] [HTML Boilerplate](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-boilerplate)
	- [ ] [Working with Text](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/working-with-text)
	- [ ] [Lists](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/lists)
	- [ ] [Links and Images](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images)
	- [ ] [Commit Messages](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/commit-messages)

**Comment by aaronlrv** [comment]
Hey is this still available? Would love to take it on!

**Comment by thatblindgeye** [comment]
@aaronlrv yep, you've been assigned!

**Comment by aaronlrv** [comment]
Hey I think all these lessons are up to date with their assignment sections? I can't seem to find any sort of relevant Practice/Exercise sections besides the "Preparation" section in 

- Links and Images

Which I wouldn't really classify as a exercise/practice. Please do check this and let me know!

**Comment by thatblindgeye** [comment]
@aaronlrv Thank you for catching that! I see what you mean about that links and images lesson. As a user, do you like the flow of that lesson where as you're learning things you're asked to update a file you created at the start?

Or do you think it would work better to learn that information then go through an assignment where you're tasked with "Create a file then do XYZ"?

**Comment by aaronlrv** [comment]
@thatblindgeye Hey! Me personally, I've always been a more application learner. Where you learn something then apply it till it works rather than a hand hold process so I'd prefer the latter.

However, This is normally always harder on the user and  I think it would be better if we stick with the current flow of the lesson, As we have the recipe's project to go ahead and reinforce those concepts that they're taught on this lesson.

But me personally? I'd learn more from the latter. The harder it is the more you learn.

**Comment by thatblindgeye** [comment]
In that case I would say the lesson could be left as-is for now, and perhaps a refresh of the lesson down the line could be done (which would ultimately be unrelated to this issue). Since it does look like no other lessons require an update, I will close this issue as "invalid". If you do notice anything or have further questions, though, feel free to comment in here, and thank you for looking through these lessons to double check!
