### ISSUE TITLE
Foundations course | HTML Foundations section | Introduction to HTML and CSS: Contradictory labeling of HTML & CSS as programming languages

### ISSUE THREAD

**Issue by fridolinba** [TheOdinProject/curriculum#24231]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
In the beginning of the lesson there is a disambiguation note which states that HTML & CSS are NOT programming languages: “If you want to get technical, HTML and CSS aren’t programming languages because […]”. 
Nevertheless, in the reading recommendation just below this statement, the author Bryan Milleris keeps stating the opposite, i.e. they ARE programming languages. 

This might seem unimportant, but it could be intriguing to the total beginner. I think at this stage in the curriculum things should be kept as clear as possible in order to not scare away the novice. 

I think this issue could be fixed either by linking an alternative resource or by inserting in the lesson  a quick note saying that “even though the two are not programming languages per se, the habit of labelling them as such still persist as is the case in the otherwise great article linked below” (something like this).

**2. Acceptance Criteria:**

**3. Additional Information:**
Link to the resource in question: https://brytdesigns.com/html-css-javascript-whats-the-difference/

**Comment by ChargrilledChook** [comment]
@fridolinba Sounds like a reasonable idea, although I'd probably want to keep it reasonably simple / brief. I think I prefer the second option (ie a quick note) as it seems like a decent introductory resource otherwise. What do you think?

 Would you like to open a PR for this?

**Comment by fridolinba** [comment]
I would give it a shot but I'm new here and it's not quite clear to me what I should do: should I open a separate issue similar to this one or should I try to formulate the disambiguation note myself? In the second case am I supposed to clone the TOP repository and make a pull request? (it would me my first time).

**Comment by ChargrilledChook** [comment]
@fridolinba No worries at all, we're here to help. 

There's two main ways you can do it - click the 'improve this lesson button' at the bottom of the lesson and it will open a PR for you to directly edit the lesson. 

That's fine, but if you want to do it the 'proper' way you can fork the curriculum repo, make a change locally, push your fork up and then make a PR. A bit longer but a bit more real world.

You can find a bit more detail in the contributing guide here https://github.com/TheOdinProject/curriculum/wiki/Contributing-Guide

If you have any trouble you can ping me here and I or another maintainer will help you out 🐔

**Comment by fridolinba** [comment]
Thank you! I'd try to do it the hard way (i.e. by forking the curriculum) because I think it's a learning opportunity. If I get stuck I'll ping you. Thanks!

**Comment by fridolinba** [comment]
I tried to do it the 'proper' way, i.e by forking, cloning, staging, commiting, pushing and finally pulling : ). Hope everything's fine. By the way, I followed the tutorial at https://github.com/TheOdinProject/curriculum/wiki/Contributing-Guide and got stuck for a while towards its end because the fact that one should first stage and commit the changes is not mentioned at all. After point 2 (creating the branch) and 3 (change what needs changing) comes 4 (push and PR) and that's it. But I found out that pushing doesn't work without a previous commit. I know, I should have known it already from the Git lesson but this is my first attempt to put all this into practice. Anyway maybe the tutorial could be completed with these steps so that total beginners like me don't get stuck.

**Comment by ChargrilledChook** [comment]
@fridolinba Nice work figuring it out, and good work on your first open source contribution :tada: 

Thanks for the feedback with the instructions - I'm happy for you to open an issue about it if you think it could be improved. In this case I think there is a bit of assumed knowledge and we probably don't wan't to get _too_ detailed with instructions lest it get too long, but I could see how a single line could help make this a bit clearer.

**Comment by fridolinba** [comment]
@ChargrilledChook Thanks for assisting me and for the feedback. I'm glad the change was accepted. I can open another issue regarding the tutorial "Contributing Guide". I am not sure though whether I should open it inside the TOP/curriculum or some place else. I'm asking this trivial question because this particular article, i.e. wiki/Contributing-Guide doesn't seem to appear within the structure of the the curriculum repo I've cloned therefore I suppose it's placed in another repo (?). Thanks a lot!

**Comment by ChargrilledChook** [comment]
Hey @fridolinba, no worries and my pleasure.
The way wiki's work is slightly different and I actually think it may not be possible to edit them as a public user. I'm happy for you to open a new issue and we can figure it out there, but before you do that - do yout think the instructions here cover the missing information in the wiki? [Link](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md#setting-up-your-local-clone)

**Comment by fridolinba** [comment]
Hey @ChargrilledChook. Yes, I think the missing information in the wiki is pretty much covered by the instructions in the [tutorial ](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md#setting-up-your-local-clone)linked by you. The commit stage is mentioned there. The staging is not mentioned but I guess a commit is not possible without stage...(?). Thanks a lot!
