### ISSUE TITLE
Style Guide - Foundations/Installations: Assignments

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24236]
# Foundations/Installations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Assignment section has the correct formatting. If this section does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following bulleted requirements:

- If a lesson has a section named Exercise, Practice, or something similar, its contents is moved to the Assignment section.
    - To see a before and after example of this, checkout the previously merged pull request for https://github.com/TheOdinProject/curriculum/pull/23825, specifically the "Files changed" tab.
- The Assignment section follows the below format:
	```
	### Assignment

	<div class="lesson-content__panel" markdown="1">

	1.  A RESOURCE OR EXERCISE ITEM
	    *   AN INSTRUCTION ITEM

	</div>
	```

- Do not make any updates to any actual list numbering, indentation/spacing, etc., as this will be covered by a separate issue.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Text Editors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/text-editors)
	- [ ] [Command Line Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101)

**Comment by muditchoudhary** [comment]
Hello! I would like to work on this.

**Comment by thatblindgeye** [comment]
@muditchoudhary you're assigned!
