### ISSUE TITLE
Style Guide - Foundations/JavaScript Basics 1: Assignments

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24241]
# Foundations/JavaScript Basics Section 1

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures the Assignment section has the correct formatting. If this section does not exist in a lesson, it should not be added.

Each applicable lesson for this issue should meet the following bulleted requirements:

- If a lesson has a section named Exercise, Practice, or something similar, its contents is moved to the Assignment section.
- The Assignment section follows the below format:
	```
	### Assignment

	<div class="lesson-content__panel" markdown="1">

	1.  A RESOURCE OR EXERCISE ITEM
	    *   AN INSTRUCTION ITEM

	</div>
	```
- Do not make any updates to any actual list numbering, indentation/spacing, etc., as this will be covered by a separate issue.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Fundamentals Part 1](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-1)
	- [ ] [Fundamentals Part 2](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-2)
	- [ ] [JavaScript Developer Tools](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/javascript-developer-tools)
	- [ ] [Fundamentals Part 3](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-3)
	- [ ] [Problem Solving](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/problem-solving)
	- [ ] [Understanding Errors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/understanding-errors)

**Comment by aaronlrv** [comment]
Hey is help still needed? Would love to work on this!

**Comment by thatblindgeye** [comment]
It is! You've been assigned @aaronlrv

**Comment by aaronlrv** [comment]
Thank you! Just wanted to ask a quick question, The following lessons

- Fundamentals Part 1
- Fundamentals Part 2
- Fundamentals Part 3
- Understanding errors

All don't have assignment tabs added on, Which means I shouldn't create an assignment tab to move them correct? Based on this criteria listed "If this section does not exist in a lesson, it should not be added.".

**Comment by aaronlrv** [comment]
> Thank you! Just wanted to ask a quick question, The following lessons
> 
> * Fundamentals Part 1
> * Fundamentals Part 2
> * Fundamentals Part 3
> * Understanding errors
> 
> All don't have assignment tabs added on, Which means I shouldn't create an assignment tab to move them correct? Based on this criteria listed "If this section does not exist in a lesson, it should not be added.".

Because as a result of this, All the lessons meet the criteria. The following lessons listed above all have practice sections but no assignment sections. Thus matches the criteria above perfectly

**Comment by aaronlrv** [comment]
> Thank you! Just wanted to ask a quick question, The following lessons
> 
> * Fundamentals Part 1
> * Fundamentals Part 2
> * Fundamentals Part 3
> * Understanding errors
> 
> All don't have assignment tabs added on, Which means I shouldn't create an assignment tab to move them correct? Based on this criteria listed "If this section does not exist in a lesson, it should not be added.".

Because as a result of this, All the lessons meet the criteria. The following lessons listed above all have practice sections but no assignment sections. Thus they do not need to be moved and match the acceptance criteria perfectly.

**Comment by thatblindgeye** [comment]
Looks like I received notifications about a reply from you @aaronlrv . Did you delete the reply or did you still have a question?
