### ISSUE TITLE
Bug - CSS Foundations: Minor grammatical error

### ISSUE THREAD

**Issue by Retr0-Flow** [TheOdinProject/curriculum#24247]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
A minor grammatical error in CSS Foundations page in the Foundations course. It's located near the end of the "Chaining Selectors" section and right above the start of the "Descendant Combinator" section in the final paragraph. The first sentence goes 

    "In general, you can’t chain more than one type selector since an element can’t be two different types at once."

when it should be,

    "In general, you can’t chain more than one type of selector since an element can’t be two different types at once."

**2. How To Reproduce:**
1. Log in
2. Visit https://www.theodinproject.com/lessons/foundations-css-foundations
3. Scroll down to just above the "Descendant Combinator" section
4. Read the first line of the paragraph.

**3. Desktop/Device:**

-   Device: Virtual Machine
-   OS: Ubuntu 22.04 LTS
-   Browser: Firefox
-   Version: 101.0.1

**Comment by afkus3r** [comment]
Hi, I'm available to work on this issue :)

**Comment by dm-murphy** [comment]
Thanks @Retr0-Flow, good catch! I've assigned this issue to you so you can go ahead and make a pull request to make the change.

Please be sure to include this issue number in the pull request template so it will automatically close this issue after merging. If you have any questions, please let me know :-)

**Comment by Retr0-Flow** [comment]
> Thanks @Retr0-Flow, good catch! I've assigned this issue to you so you can go ahead and make a pull request to make the change.
> 
> Please be sure to include this issue number in the pull request template so it will automatically close this issue after merging. If you have any questions, please let me know :-)

Sorry for the delay! I'll make the pull request today with the issue number. 😄

**Comment by Retr0-Flow** [comment]
@dm-murphy Pull request made! This is my first request ever, thank you for the opportunity! 😃

**Comment by Retr0-Flow** [comment]
Closing issue as the issue was misinterpreted as a typo.
