### ISSUE TITLE
Bug - Foundations Path, Block and Inline Lesson: Rickrolled in lesson

### ISSUE THREAD

**Issue by jproads** [TheOdinProject/curriculum#24255]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

This hyperlink that should lead to an example of inline elements leads instead to the YouTube video of Rick Astley's "Never Gonna Give You Up." Thought it was a funny joke but probably not appropriate for the curriculum.
![Screen Shot 2022-06-17 at 10 00 35 AM](https://user-images.githubusercontent.com/93178783/174207510-7a29ab53-2c46-4dbd-b4b8-a42be179aceb.png)

**2. How To Reproduce:**
1. Log in
2. Visit https://www.theodinproject.com/lessons/foundations-block-and-inline3. 
3. Scroll down to the second paragraph of the sublesson Block vs Inline
4. Click on the `(Like this...)` hyperlink

**3. Expected Behavior:**
1. Expected a resource demonstrating inline elements vs block elements

**Comment by LeoKirasic** [comment]
Hey, Thank you for creating the issue.

Unfortunately, we think adding a bit of fun to our content is a positive thing and thus we have decided to leave this in.
