### ISSUE TITLE
Intermediate HTML and CSS -> CSS Units: Remove empty "Additional Resources" section

### ISSUE THREAD

**Issue by ZachPoole** [TheOdinProject/curriculum#24256]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

<hr>

**1. Description of the Feature Request:**

Remove the empty Additional Resources section on the [CSS Units Lesson](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-css-units#additional-resources)

**2. Acceptance Criteria:**

- [ ] Additional Information section has been removed or additional information has been added

**Comment by sheilaJava** [comment]
Hi! I'm available to work on this issue if @ZachPoole doesn't want to do so himself :)

**Comment by ChargrilledChook** [comment]
We generally want to leave these in, even when empty so people know where to add resources and pages stay consistent. 
It might be a good idea to add the placeholder line 
```
* It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
``` 

You can check the `LAYOUT_STYLE_GUIDE.md` file in the curriculum repo if needed.

**Comment by ChargrilledChook** [comment]
@sheilaJava happy for you to take this on if @ZachPoole doesn't want to :+1:

**Comment by sheilaJava** [comment]
> @sheilaJava happy for you to take this on if @ZachPoole doesn't want to 👍

Great, I'll wait for @ZachPoole response!

**Comment by ZachPoole** [comment]
Feel free to do it if you want.

**Comment by ChargrilledChook** [comment]
Thanks guys, I've assigned it to you @sheilaJava
