### ISSUE TITLE
Bug - : Image contradicts with inspector in html - css inspection lesson

### ISSUE THREAD

**Issue by DigitalKnight0** [TheOdinProject/curriculum#24259]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the lesson [Inspecting HTML and CSS](https://www.theodinproject.com/lessons/foundations-inspecting-html-and-css) , The image ![here](https://cdn.statically.io/gh/TheOdinProject/curriculum/f8fd38fc62578d8e8368f5303126215a492847f0/foundations/html_css/inspecting-html-and-css/imgs/03.png) 
is different (as in those classes are not present anymore and are replaced) from what the current classes and styles look like in odin's homepage, that tagline in specific which is in question (Perhaps i am guessing due to the recent transition over to tailwind?) but it's confusing and bit misleading and thought updating it might be good idea to reflect the changes.

**Comment by giovanniPepi** [comment]
I could update this if the team needs. Just want to confirm if we should update every other screenshot to keep the same browser pattern or not.

**Comment by thatblindgeye** [comment]
This was also mentioned in #24305 which I have opened up to be taken on. @DigitalKnight0 if you'd like to take that on please comment there and let me know.
