### ISSUE TITLE
Intermediate HTML/CSS: Form Basics lesson needs updates to Input section

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24263]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The [Form Basics - Input Element section](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics#the-input-element) has several sub-sections that go over different input `type`s. Instead, a single "The Type Attribute" sub-section should replace all of these, and simply mention some of the different input types with a single code snippet showing one of them being used.

There are also a couple of other minor tweaks that could be made elsewhere in this lesson, noted below.

**2. Acceptance Criteria:**

- [ ] Replace the "Email Input", "Password Input", "Number Input", and "Date Input" sub-sections with a single "The Type Attribute" sub-section
- [ ] Under the "The Name Attribute" subsection, right before the "Using Form Controls Outside of Forms" sub-section, update the final paragraph to, "Try changing the `name` attributes of some of the input fields in the form and removing the attribute entirely, then submit the form again to see how the form data in the response changes."
- [ ] Update the opening sentence of the "Text Area" sub-section to, "While technically not an `input` element, the text area element provides an input box that can accept text that spans multiple lines like user comments and reviews."

**3. Additional Information:**

**Comment by Maheshkumar-novice** [comment]
@thatblindgeye Can I take this one?

**Comment by thatblindgeye** [comment]
@Maheshkumar-novice you got it!

**Comment by Maheshkumar-novice** [comment]
Thank you!

**Comment by edgardooliveras** [comment]
"Using Form Controls Outside of Forms" sub-section, update the final paragraph to, "Try changing the name attributes of some of the input fields in the form and removing the attribute entirely, then submit the form again to see how the form data in the response changes." GooD

**Comment by Maheshkumar-novice** [comment]
@thatblindgeye Sorry for the delay. Raised the PR.
