### ISSUE TITLE
Responsive images lesson: should include an article link in it

### ISSUE THREAD

**Issue by bappyasif** [TheOdinProject/curriculum#24275]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

currently in "Knowledge check" section, 4th checkpoint (i.e. When would you want to use an img with a srcset vs a picture?) refers to this amazing [article](https://css-tricks.com/a-guide-to-the-responsive-images-syntax-in-html/) but it didn't mention of it beforehand or not even in "Additional resources" either

**2. Acceptance Criteria:**

Suggesting inclusion of [A Guide to the Responsive Images Syntax in HTML](https://css-tricks.com/a-guide-to-the-responsive-images-syntax-in-html/) article link and mention either in "Additional resources" or "Assignment"

**3. Additional Information:**

**Comment by giovanniPepi** [comment]
It's currently linked before the Knowledge Check on the Assignment list, item 3

![image](https://user-images.githubusercontent.com/5255535/175960447-f17705d8-6115-44af-a731-8a7793681e86.png)
