### ISSUE TITLE
Bug - Foundations/Git Basics: GitHub links are broken 

### ISSUE THREAD

**Issue by notmyf4ulty** [TheOdinProject/curriculum#24300]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

*Introduction to Git* or *Git Basics* lesson links in the README.md from the [foundations directory](https://github.com/TheOdinProject/curriculum/tree/main/foundations) do not work.

**2. How To Reproduce:**

When in the [foundations directory](https://github.com/TheOdinProject/curriculum/tree/main/foundations), clicking either *Introduction to Git* or *Git Basics* will result with Page Not Found error: _The 'TheOdinProject/curriculum' repository doesn't contain the 'foundations/git_basics/introduction_to_git.md' path in 'main'._

**3. Expected Behavior:**

Links working properly.

**4. Desktop/Device:**

--

**5. Additional Information:**

I ran a global search in the curriculum repo for some phrases from these two lessons, but didn't get any results. I see some other issues around these topics and I suppose that someone, instead of moving the lessons to fit a proper structure, by mistake removed them entirely.

**Comment by sheilaJava** [comment]
Hi, it looks like the entire _Git Basics_ directory is missing. I'm available to work on it to create the directory and the MD files.

**Comment by dm-murphy** [comment]
Good catch, thanks for bringing this up @notmyf4ulty! 🙏 

@01zulfi Is this included in your curriculum repo cleanup?

The README hasn't been updated since February and is missing the Commit Messages lesson under HTML Foundations too.

@sheilaJava 👋  Thanks so much for volunteering. Just waiting to find out more on the status of this issue and will get back to you!

**Comment by 01zulfi** [comment]
The Git Basics lesson can be found in the [`curriculum/git` directory](https://github.com/TheOdinProject/curriculum/tree/main/git). We moved all the git lessons to this directly except for the "Setting Up Git" lesson.

The Foundations README is outdated, this should be fixed whenever I have a chance to get around to conforming the foundations directory to the [Suggested Implementation in this issue](https://github.com/TheOdinProject/top-meta/issues/109).

**Comment by dm-murphy** [comment]
> The Git Basics lesson can be found in the [`curriculum/git` directory](https://github.com/TheOdinProject/curriculum/tree/main/git). We moved all the git lessons to this directly except for the "Setting Up Git" lesson.
> 
> The Foundations README is outdated, this should be fixed whenever I have a chance to get around to conforming the foundations directory to the [Suggested Implementation in this issue](https://github.com/TheOdinProject/top-meta/issues/109).

Thanks for clarifying @01zulfi 🙏  

If you are looking for any community contributors to help you on this when the time comes, please consider reaching out to @sheilaJava 

@01zulfi We can either close this issue out now if it's covered by your on-going project or leave this issue open as a reminder. Whatever works best for you, thanks!

**Comment by 01zulfi** [comment]
@dm-murphy I don't see a reason to keep this issue open.

**Comment by dm-murphy** [comment]
@notmyf4ulty Closing out the issue per the above conversation. Thanks again for bringing this up! 🙂
