### ISSUE TITLE
Style Guide - Foundations/Introduction: Lists and Code Blocks

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24326]
# Foundations/Introduction Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that any lists (numbered or bulleted) and codeblocks are properly formatted.

Each applicable lesson for this issue should meet the following bulleted requirements:

- All numbered lists are numbered properly per the style guide, including:
    - Lesson Overview, Knowledge Check, and Additional Resources sections all use bulleted lists
    - The Assignment section in lessons or projects uses numbered lists for their main content, and bulleted lists for sub-items.
    - The Extra Credit sub-section in project Assignments use only bulleted lists
- All lists have the proper whitespace between the list marker (e.g. `*` or `1.`) and the item text (see Nested List Spacing section of style guide)
- All lists are properly indented.
- All codeblocks have an explicit language declared.
	- If a codeblock combines multiple languages, each language is given its own codeblock with the correct language declared.
- Codeblocks that are a part of a list are properly indented.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to Web Development](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-web-development)
	- [ ] [Motivation and Mindset](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/gearing-up)
	- [ ] [Asking for Help](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/asking-for-help)
	- [ ] [Join the Odin Community](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/join-the-odin-community)
	- [ ] [How Does the Web Work?](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/how-does-the-web-work)

**Comment by ManorSailor** [comment]
Hello there. I noticed some inconsistencies with [Calculator Project](https://www.theodinproject.com/lessons/foundations-calculator) in the Foundations curriculum. Firstly, assignment section sub-items do not use bulleted list & the next thing is that the heading for `Extra Credit` section is broken, on inspecting the element it turns out its a `<p>` tag with hashes inside of it.

I didn't want to create a separate issue for this & if its okay. I would like to be assigned to work on this issue.
Thanks!

**Comment by Overlandcoder** [comment]
I'd love to work on this if it's still available.

**Comment by thatblindgeye** [comment]
@ManorSailor are you still interested in this issue? @Overlandcoder if they aren't I'll reach out to you next! 🙂

**Comment by ManorSailor** [comment]
@thatblindgeye Hey! Thanks for reaching out, however, my hands are full at the moment. However, I appreciate the incentive! You may assign this issue to someone else.

**Comment by zachmmeyer** [comment]
@Overlandcoder Would you like to be assigned?

**Comment by szmazhr** [comment]
I would love to work on it, please assign it to me.

**Comment by zachmmeyer** [comment]
@amit-srt all yours, thanks for your patience
