### ISSUE TITLE
Style Guide - Foundations/HTML Foundations: Lists and Code Blocks

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24329]
# Foundations/HTML Foundations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that any lists (numbered or bulleted) and codeblocks are properly formatted.

Each applicable lesson for this issue should meet the following bulleted requirements:

- All numbered lists are numbered properly per the style guide, including:
    - Lesson Overview, Knowledge Check, and Additional Resources sections all use bulleted lists
    - The Assignment section in lessons or projects uses numbered lists for their main content, and bulleted lists for sub-items.
    - The Extra Credit sub-section in project Assignments use only bulleted lists
- All lists have the proper whitespace between the list marker (e.g. `*` or `1.`) and the item text (see Nested List Spacing section of style guide)
- All lists are properly indented.
- All codeblocks have an explicit language declared.
	- If a codeblock combines multiple languages, each language is given its own codeblock with the correct language declared.
- Codeblocks that are a part of a list are properly indented.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-html-and-css)
	- [ ] [Elements and Tags](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/elements-and-tags)
	- [ ] [HTML Boilerplate](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-boilerplate)
	- [ ] [Working with Text](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/working-with-text)
	- [ ] [Lists](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/lists)
	- [ ] [Links and Images](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images)
	- [ ] [Commit Messages](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/commit-messages)
	- [ ] [Project: Recipes](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/recipes)

**Comment by aleksandar-code** [comment]
I would like to be assigned this issue!

**Comment by aleksandar-code** [comment]
I'm not sure if i did exactly what i was asked to.. I added newlines before and after some lists that didn't have them (i followed the style guide). Sometimes the newline at the end of file was missing too. I think i probably shouldn't have made those changes?
Sorry it is my first PR, should i make a new PR without the changes i wasn't asked to do? @thatblindgeye
