### ISSUE TITLE
Style Guide - Foundations/Installations: Lists and Code Blocks

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24327]
# Foundations/Installations Section

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that any lists (numbered or bulleted) and codeblocks are properly formatted.

Each applicable lesson for this issue should meet the following bulleted requirements:

- All numbered lists are numbered properly per the style guide, including:
    - Lesson Overview, Knowledge Check, and Additional Resources sections all use bulleted lists
    - The Assignment section in lessons or projects uses numbered lists for their main content, and bulleted lists for sub-items.
    - The Extra Credit sub-section in project Assignments use only bulleted lists
- All lists have the proper whitespace between the list marker (e.g. `*` or `1.`) and the item text (see Nested List Spacing section of style guide)
- All lists are properly indented.
- All codeblocks have an explicit language declared.
	- If a codeblock combines multiple languages, each language is given its own codeblock with the correct language declared.
- Codeblocks that are a part of a list are properly indented.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Installation Overview](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installation-overview)
	- [ ] [Prerequisites](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/prerequisites)
	- [ ] [Text Editors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/text-editors)
	- [ ] [Command Line Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101)
	- [ ] [Setting Up Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/setting-up-git)

**Comment by ehcrae** [comment]
I can have a go at this!

**Comment by GabrielRuizVarela** [comment]
Can I work on this?

**Comment by thatblindgeye** [comment]
@GabrielRuizVarela you're assigned if you'd still like to work on it!
