### ISSUE TITLE
Style Guide - Foundations/Git Basics, The Back End, and Conclusion: Headings and Section Placement

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24337]
# Foundations/Git Basics, The Back End, and Conclusion

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that headings are properly formatted and that all sections are placed in the correct order.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The main headings use the Markdown `###` syntax.
- Sub-headings that are not inline use the Markdown `####` syntax.
- Sub-headings that are inline use the Markdown `**sub-heading**` (i.e. bold) syntax.
- Both headings and sub-headings use Wikipedia style Title Case.
- There is a newline before and after headings and non-inline sub-headings.
- The order of existing sections follows the below format:
	- Introduction
	- Lesson Overview
	- Custom Sections (lessons) / Pre-Assignment Sections (projects)
	- Assignment
	- Practice (lessons) / Post-Assignment Sections (projects)
	- Knowledge Check
	- Additional Resources
- Additionally, there should be an empty newline at the end of the file.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-git)
	- [ ] [Git Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/git-basics)
	- [ ] [Introduction to the Back End](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-the-back-end)
	- [ ] [Introduction to Frameworks](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-frameworks-web-development-101)
	- [ ] [Choose Your Path Forward](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/choose-your-path-forward)
            - Only update the two level 4 `####` headings to level 3 `###` headings

**Comment by aaronlrv** [comment]
Hey does this still need help? I can take it on

**Comment by thatblindgeye** [comment]
@aaronlrv yep, you're assigned!
