### ISSUE TITLE
Style Guide - Foundations: Image and Codepen Embeds

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24334]
# Foundations
This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that images and Codepens are properly embedded.

Each applicable lesson for this issue should meet the following bulleted requirements:

- All image embeds use Markdown syntax only
- All image embeds use statically URLs
	- If they are not, they are converted to statically URLs using our [Adding Images to the Curriculum](https://github.com/TheOdinProject/curriculum/wiki/Adding-Images-to-the-Curriculum) wiki page.
- Codepen embeds are from The Odin Project Codepen account.
	- The embed will include an `<a>` element with an `href` attribute that begins with `https://codepen.io/TheOdinProjectExamples` if it is from the TOP account.
	- If an embed is not from the TOP account, note this in your PR (or make a comment on this issue) so a maintainer can fork the embed(s). Once a maintainer forks the embed(s), you will be notified and able to update the embed with the TOP version.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Prerequisites](https://www.theodinproject.com/lessons/foundations-prerequisites)
	- [ ] [Git Basics](https://www.theodinproject.com/lessons/foundations-git-basics)
	- [ ] [CSS Foundations](https://www.theodinproject.com/lessons/foundations-css-foundations)
	- [ ] [Inspecting HTML and CSS](https://www.theodinproject.com/lessons/foundations-inspecting-html-and-css)
	- [ ] [Understanding Errors](https://www.theodinproject.com/lessons/foundations-understanding-errors)
	- [ ] [Revisiting Rock Paper Scissors](https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors)

**Comment by Maheshkumar-novice** [comment]
@thatblindgeye Can I take this one?

**Comment by thatblindgeye** [comment]
@Maheshkumar-novice if you're still interested I've assigned you, if not just let me know! 🙂

**Comment by Maheshkumar-novice** [comment]
@thatblindgeye Yes. I'm interested. I'll work on it.

**Comment by Maheshkumar-novice** [comment]
Hi @thatblindgeye Sorry for the delay. I've raised the PR.
