### ISSUE TITLE
Style Guide - Foundations/Installations: Headings and Section Placement

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24336]
# Foundations/Installations

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that headings are properly formatted and that all sections are placed in the correct order.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The main headings use the Markdown `###` syntax.
- Sub-headings that are not inline use the Markdown `####` syntax.
- Sub-headings that are inline use the Markdown `**sub-heading**` (i.e. bold) syntax.
- Both headings and sub-headings use Wikipedia style Title Case.
- There is a newline before and after headings and non-inline sub-headings.
- The order of existing sections follows the below format:
	- Introduction
	- Lesson Overview
	- Custom Sections (lessons) / Pre-Assignment Sections (projects)
	- Assignment
	- Practice (lessons) / Post-Assignment Sections (projects)
	- Knowledge Check
	- Additional Resources
- Additionally, there should be an empty newline at the end of the file.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Installation Overview](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installation-overview)
	- [ ] [Prerequisites](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/prerequisites)
            - Ensure the inline sub-headings are fixed to be properly inline
	- [ ] [Text Editors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/text-editors)
	- [ ] [Command Line Basics](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/command-line-basics-web-development-101)
            - The "Test Drive Your Terminal", "Use the Command Line Like a Pro", and "Opening files in VSCode from the Command Line" headings should be a main heading, not a sub-heading
            - The level 5 headings using Markdown `#####` syntax should be sub-headings using Markdown `####` syntax
	- [ ] [Setting Up Git](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/setting-up-git)

**Comment by Maheshkumar-novice** [comment]
@thatblindgeye Can I take this one?

**Comment by mrmchughes** [comment]
Is this available to be worked on?

**Comment by ZionLG** [comment]
Can i work on it?

**Comment by TidalSana** [comment]
I'm down to work on this one!

**Comment by thatblindgeye** [comment]
Sorry for the delay, y'all! @mrmchughes are you still interested in this issue?

**Comment by mrmchughes** [comment]
Yes I am!

**Comment by Pete-Fowler** [comment]
@thatblindgeye - Hi - I would also be willing to work on this. Thanks.

**Comment by marcusicaro** [comment]
Hey, are there any issues still avaiable?

**Comment by mrmchughes** [comment]
Apologies for the delay in starting this, the notifying email got buried in my inbox. I'll start working on this in the morning! Excited to get some open source contribution experience!

**Comment by mrmchughes** [comment]
Hi @thatblindgeye, how do I mark an item as completed? I went over the Installation Overview and didn't see anything that needed to be updated per the issue, so I was attempting to check it off.

**Comment by mrmchughes** [comment]
I've gone over the lessons brought up in the issue, and I think they are good to go. I didn't see anything wrong with the Installation Overview lesson, so I'm unsure of how to mark that one off. I've submitted pull requests for the other 4 lessons that required some level of fixing.

**Comment by mrmchughes** [comment]
@thatblindgeye I think this issue is all set, if you could please take a look at the pull requests when you've got a chance
