### ISSUE TITLE
Style Guide - Foundations/JavaScript Basics 1: Lists and Code Blocks

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24332]
# Foundations/JavaScript Basics Section 1

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that any lists (numbered or bulleted) and codeblocks are properly formatted.

Each applicable lesson for this issue should meet the following bulleted requirements:

- All numbered lists are numbered properly per the style guide, including:
    - Lesson Overview, Knowledge Check, and Additional Resources sections all use bulleted lists
    - The Assignment section in lessons or projects uses numbered lists for their main content, and bulleted lists for sub-items.
    - The Extra Credit sub-section in project Assignments use only bulleted lists
- All lists have the proper whitespace between the list marker (e.g. `*` or `1.`) and the item text (see Nested List Spacing section of style guide)
- All lists are properly indented.
- All codeblocks have an explicit language declared.
	- If a codeblock combines multiple languages, each language is given its own codeblock with the correct language declared.
- Codeblocks that are a part of a list are properly indented.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Fundamentals Part 1](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-1)
	- [ ] [Fundamentals Part 2](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-2)
	- [ ] [JavaScript Developer Tools](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/javascript-developer-tools)
	- [ ] [Fundamentals Part 3](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-3)
	- [ ] [Problem Solving](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/problem-solving)
	- [ ] [Understanding Errors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/understanding-errors)
	- [ ] [Project: Rock Paper Scissors](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/rock-paper-scissors)

**Comment by mbatson** [comment]
I would like to be assigned to this issue if that's ok

**Comment by thatblindgeye** [comment]
@mbatson you're assigned!

**Comment by mbatson** [comment]
@thatblindgeye Thanks! 
One quick question: I've noticed that these lessons so far have one space of indentation before each paragraph and list item in the Additional Resources section. The rest of the file does not have this indentation in any other section.
Here's an example of what I'm talking about: https://github.com/TheOdinProject/curriculum/blob/7919f89a1e498f6dde12e66584551d16c4a593d0/foundations/javascript_basics/javascript_developer_tools.md?plain=1#L51-L57
Would you like me to remove these extra spaces at the start of the line while I am working on this issue?
