### ISSUE TITLE
Style Guide - Foundations/Introduction: Headings and Section Placement

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24335]
# Foundations/Introduction

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that headings are properly formatted and that all sections are placed in the correct order.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The main headings use the Markdown `###` syntax.
- Sub-headings that are not inline use the Markdown `####` syntax.
- Sub-headings that are inline use the Markdown `**sub-heading**` (i.e. bold) syntax.
- Both headings and sub-headings use Wikipedia style Title Case.
- There is a newline before and after headings and non-inline sub-headings.
- The order of existing sections follows the below format:
	- Introduction
	- Lesson Overview
	- Custom Sections (lessons) / Pre-Assignment Sections (projects)
	- Assignment
	- Practice (lessons) / Post-Assignment Sections (projects)
	- Knowledge Check
	- Additional Resources
- Additionally, there should be an empty newline at the end of the file.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [How This Course Will Work](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/how-this-course-will-work)
            - The opening "Welcome to The Odin Project" section should be combined with the Introduction section
	- [ ] [Introduction to Web Development](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-web-development)
            - The opening "What Do Web Developers Do?" section should be renamed to the Introduction
	- [ ] [Motivation and Mindset](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/gearing-up)
	- [ ] [Asking for Help](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/asking-for-help)
	- [ ] [Join the Odin Community](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/join-the-odin-community)
	- [ ] [How Does the Web Work?](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/how-does-the-web-work)

**Comment by RTnhN** [comment]
Hello!

Could I take this issue?

**Comment by thatblindgeye** [comment]
@RTnhN yep! you're assigned
