### ISSUE TITLE
Style Guide - Foundations/HTML Foundations: Headings and Section Placement

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24338]
# Foundations/HTML Foundations

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that headings are properly formatted and that all sections are placed in the correct order.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The main headings use the Markdown `###` syntax.
- Sub-headings that are not inline use the Markdown `####` syntax.
- Sub-headings that are inline use the Markdown `**sub-heading**` (i.e. bold) syntax.
- Both headings and sub-headings use Wikipedia style Title Case.
- There is a newline before and after headings and non-inline sub-headings.
- The order of existing sections follows the below format:
	- Introduction
	- Lesson Overview
	- Custom Sections (lessons) / Pre-Assignment Sections (projects)
	- Assignment
	- Practice (lessons) / Post-Assignment Sections (projects)
	- Knowledge Check
	- Additional Resources
- Additionally, there should be an empty newline at the end of the file.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Introduction to HTML and CSS](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/introduction-to-html-and-css)
	- [ ] [Elements and Tags](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/elements-and-tags)
	- [ ] [HTML Boilerplate](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/html-boilerplate)
            - Remove the code backticks from the "What is the `lang` attribute?" heading
	- [ ] [Working with Text](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/working-with-text)
	- [ ] [Lists](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/lists)
	- [ ] [Links and Images](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/links-and-images)
	- [ ] [Commit Messages](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/commit-messages)
	- [ ] [Project: Recipes](https://www.theodinproject.com/lessons/foundations-recipes)
            - The "Tips on when to commit" heading should be a level 3 `###` heading

**Comment by itsaflamingo** [comment]
I can work on this one

**Comment by thatblindgeye** [comment]
@itsaflamingo all yours!

**Comment by itsaflamingo** [comment]
Sent in the pull request:) Thank you!

**Comment by szmazhr** [comment]
can I be assign here?

**Comment by Memomer** [comment]
Can i be assigned this? or is it resolved?

**Comment by thatblindgeye** [comment]
@Memomer Someone else is currently working on this, but thank you for wanting to help out! If you'd I'd definitely check out some of the other open issues in our repos.

**Comment by Memomer** [comment]
> @Memomer Someone else is currently working on this, but thank you for wanting to help out! If you'd I'd definitely check out some of the other open issues in our repos.

Ok, I will check out other issues.

**Comment by rlmoser99** [comment]
@thatblindgeye A pull request has been submitted that looks like it resolves the final two issues. This person did not asked to get assigned the issue, but since we've been waiting for quite a while for this one to re resolved, how do you think we should handle this?

**Comment by thatblindgeye** [comment]
>A pull request has been submitted that looks like it resolves the final two issues. This person did not asked to get assigned the issue, but since we've been waiting for quite a while for this one to re resolved, how do you think we should handle this?

The assignee currently has a PR open, just waiting on some changes to be made before merging

**Comment by tapiadot** [comment]
@thatblindgeye So, is this issue already resolved or is there still something I can contribute on?

**Comment by CBID2** [comment]
@KevinMulhern, is this issue still being addressed? I'd like to work on it

**Comment by thatblindgeye** [comment]
@tapiadot @CBID2 This issue is currently addressed in an open PR

**Comment by CBID2** [comment]
> @tapiadot @CBID2 This issue is currently addressed in an open PR

It looks like it hasn't been updated in 8 months. From maintainer to maintainer, I highly recommend closing it and let other people work on it. Stale PRs in my experience, causes the workflow to slow down.

**Comment by thatblindgeye** [comment]
@CBID2 the PR was originally opened then yeah, but the last update was ~a month ago. Currently some merge conflicts awaiting to be done, but did just ping the user for an update. If there's no update soon I'll come back to this issue to see if anyone else whose inquired would still like to open their own PR for it.

**Comment by CBID2** [comment]
> @CBID2 the PR was originally opened then yeah, but the last update was ~a month ago. Currently some merge conflicts awaiting to be done, but did just ping the user for an update. If there's no update soon I'll come back to this issue to see if anyone else whose inquired would still like to open their own PR for it.

Good plan. With that in mind, I reiterate my interest in solving this problem @thatblindgeye. I'm very new to this repo so I want to start with something easier to solve :)

**Comment by thatblindgeye** [comment]
@CBID2 ++ definitely appreciate it! Will keep that in mind for future issues as well

**Comment by CBID2** [comment]
> @CBID2 ++ definitely appreciate it! Will keep that in mind for future issues as well

Ooh speaking of issues, I raised [this one](https://github.com/TheOdinProject/curriculum/issues/25664). I’d love to see your viewpoint on it.

**Comment by CouchofTomato** [comment]
@CBID2 

You can see the linked pull request just above your comment.

**Comment by CBID2** [comment]
> @CBID2 
> 
> 
> 
> You can see the linked pull request just above your comment.

See this [reply](https://github.com/TheOdinProject/curriculum/issues/24338#issuecomment-1606055328) @CouchofTomato.

**Comment by CouchofTomato** [comment]
It's a different PR https://github.com/TheOdinProject/curriculum/pull/25682

**Comment by CBID2** [comment]
> It's a different PR https://github.com/TheOdinProject/curriculum/pull/25682

Thanks for the update @CouchofTomato! :)

**Comment by thatblindgeye** [comment]
Closing as completed in #25692
