### ISSUE TITLE
Style Guide - Foundations/JavaScript Basics 2: Headings and Section Placement

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#24342]
# Foundations/JavaScript Basics 2:

This issue is part of the Style Guide Community Project, a way of offering members of The Odin Project community a chance to contribute to our curriculum. Users who wish to take part and contribute to any Style Guide issues should have thoroughly read the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) and [The Odin Project contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md).
  
## Description of Issue

This issue ensures that headings are properly formatted and that all sections are placed in the correct order.

Each applicable lesson for this issue should meet the following bulleted requirements:

- The main headings use the Markdown `###` syntax.
- Sub-headings that are not inline use the Markdown `####` syntax.
- Sub-headings that are inline use the Markdown `**sub-heading**` (i.e. bold) syntax.
- Both headings and sub-headings use Wikipedia style Title Case.
- There is a newline before and after headings and non-inline sub-headings.
- The order of existing sections follows the below format:
	- Introduction
	- Lesson Overview
	- Custom Sections (lessons) / Pre-Assignment Sections (projects)
	- Assignment
	- Practice (lessons) / Post-Assignment Sections (projects)
	- Knowledge Check
	- Additional Resources
- Additionally, there should be an empty newline at the end of the file.
 
## Acceptance Criteria

- [ ] The following lessons are updated according to the issue description above:
	- [ ] [Clean Code](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/clean-code)
            - The opening "Writing Clean Code" heading should be renamed to "Introduction"
	- [ ] [Installing Node.js](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installing-node-js)
	- [ ] [DOM Manipulation and Events](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/dom-manipulation-and-events)
	- [ ] [Fundamentals Part 5](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-5)
	- [ ] [Project: Calculator](https://www.theodinproject.com/lessons/foundations-calculator)

**Comment by leinierperez** [comment]
I can work on this

**Comment by thatblindgeye** [comment]
@leinierperez thanks for wanting to take this on! Just to let you know, you do not need to update the level 3 heading "Important note" in Project Calculator as another PR is making a change to that.

**Comment by leinierperez** [comment]
@thatblindgeye Sorry, I won't be able to work on this.

**Comment by c-yip** [comment]
Hi! I can take this on.

**Comment by c-yip** [comment]
I renamed the "Writing Clean Code" heading to "Introduction" as requested in the issue. However, this leaves the page with two "Introduction" headings. Please let me know if I misunderstood the issue so that I can address it accordingly. Thank you!

**Comment by thatblindgeye** [comment]
@c-yip I see what you mean! I may have made this issue before there was a proper introduction section, or I may have made that comment in error. Don't update anything yet as I will take a look at the other files for this issue to see if there is anything else that needs to be updated, but thank you for pointing that out!

**Comment by c-yip** [comment]
@thatblindgeye No problem! I closed the pull request I made. I will be on the lookout for any other issues you may post re the other files.

**Comment by thatblindgeye** [comment]
@c-yip These lessons still need some updates/checking, mainly making sure the sections are in the correct order and that they all use Wikipedia style title case. Did you still want to work on this issue?

**Comment by c-yip** [comment]
@thatblindgeye Yes, I still want to work on this issue.
