### ISSUE TITLE
Bug - Ruby Debugging: title attribute on the images needs to be updated

### ISSUE THREAD

**Issue by Maheshkumar-novice** [TheOdinProject/curriculum#24351]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Currently we are using `statically` for images. But in the ruby debugging lesson in a few places in the image tags the title attribute still points to `imgur.com` but as we are now using `statically` we should update the title attribute with some other wording or we can remove it, if it is necessary.

**2. How To Reproduce:**

Visit: https://www.theodinproject.com/lessons/ruby-debugging
Hover the images or Open the dev tool and inspect the images
We can see the title attribute.

**3. Expected Behavior:**

title attribute should be updated to something relevant to the context like stack trace or source: statically or something like that.

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by ChargrilledChook** [comment]
@Maheshkumar-novice I'm happy for you to work on this, but I don't have strong opinions about changing it vs removing it. This is not an area of expertise for me, but my understanding is that title's are (generally) not as important for accessibility and can be skipped if they're uneeded. 

I'm not sure the hover pop up showing the source is particularly useful, so I would lean towards just removing it. You could also go the route of making it more descriptive or useful if you'd prefer, but I'll leave that choice to you.

Thanks for taking this one on! 🚀

**Comment by Maheshkumar-novice** [comment]
Thanks @ChargrilledChook . Yeah. I think removing is the better idea here. 

`Short answer: Don't use them (title), except in special circumstances.` => https://www.a11yproject.com/posts/title-attributes/
