### ISSUE TITLE
Bug - : Fundation: Commit Messages - Broken Link

### ISSUE THREAD

**Issue by Anluhen** [TheOdinProject/curriculum#24434]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The link to the assignment in the Commit Messages page in the Foundation section to the page https://cbea.ms/git-commit is not loading.

**2. How To Reproduce:**

Click in the anchor

**3. Expected Behavior:**

Load the page

**4. Desktop/Device:**

-   Device:  Computer
-   OS:  Ubuntu
-   Browser:  Chrome
-   Version:  

**5. Additional Information:**

**Comment by xandora** [comment]
This URL appears to be working now.
