### ISSUE TITLE
Bug - DOM Manipulation: Multiple Broken Knowledge Check Links

### ISSUE THREAD

**Issue by andyglover** [TheOdinProject/curriculum#24456]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Multiple links in the "Knowledge Check" section of the "DOM Manipulation" page lead to IDs that should correspond with headings on the page, but do not exist in the HTML.

**2. How To Reproduce:**

1. Visit [DOM Manipulation](https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events) page.
2. Scroll down to "Knowledge check"
3. Click on any of the following links:
-What is the DOM?
-How do you create an element in the DOM?
-How do you add an element to the DOM?
-How do you remove an element from the DOM?
-How can you alter an element in the DOM?
-What are the benefits of using named functions in your listeners?
-How do you attach listeners to groups of nodes?
-What is the difference between the return values of querySelector and querySelectorAll?
-What does a “nodelist” contain?
4. Observe that these links do not function because they link to an ID that does not exist in the HTML of the page.

**3. Expected Behavior:**

-"What is the DOM?" should link to the "DOM - Document Object Model" heading on line 16
-"How do you create an element in the DOM?" should link to the "Element Creation" heading on line 72
-"How do you add an element to the DOM?" should link to the "Append Elements" heading on line 82.
-"How do you remove an element from the DOM?" should link to the "Remove Elements" heading on line 87.
-"How can you alter an element in the DOM?" should link to the "Altering Elements" heading on line 91.
-"What are the benefits of using named functions in your listeners?" should link to the "method 3" heading on line 277.
-"How do you attach listeners to groups of nodes?" should link to the "Attaching listeners to groups of nodes" heading on line 345.
-"What is the difference between the return values of querySelector and querySelectorAll?" should link to the "Query Selectors" heading on line 63.
-"What does a “nodelist” contain?" should also link to the "Query Selectors" heading on line 63.

**4. Desktop/Device:**

-   Device:  PC
-   OS:  Ubuntu
-   Browser:  Chrome
-   Version:  103

**5. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks for reporting @andyglover 💪 

This was inadvertently caused by us turning auto_id's off for headings https://github.com/TheOdinProject/theodinproject/pull/3124/files#diff-4710541af8b76b8861587e9525eff23a8f9a224a8291f6466a18ae646df916deR13

We will get a fix out today.

**Comment by andyglover** [comment]
Well done, thanks @KevinMulhern !! : )
