### ISSUE TITLE
Full Stack Javascript - Javascript OOP principles: Replace culturally inappropriate materials

### ISSUE THREAD

**Issue by tmbruce** [TheOdinProject/curriculum#24463]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

In the OOP principles section of the full stack javascript path, article b, "5 Principles that will make you a SOLID JavaScript Developer" makes inappropriate cultural jokes and should be replaced. I propose this article on [Hackernoon](https://hackernoon.com/understanding-solid-principles-in-javascript-w1cx3yrv) as a replacement.

**2. Acceptance Criteria:**

A list of checkbox items that explain the requirements needed to be met to resolve this request, e.g.:
- [ ] A theme toggle is present on the dashboard
- [ ] Clicking the theme toggle changes between light and dark
- [ ] A user's theme choice persists after leaving the website

**3. Additional Information:**

<img width="731" alt="Screen Shot 2022-07-26 at 11 09 38 AM" src="https://user-images.githubusercontent.com/47762048/181080966-a3869977-e69d-4969-a44d-f067bc02b38b.png">

**Comment by ChargrilledChook** [comment]
@tmbruce Thanks for reporting this, it's appreciated. This has now be solved :+1:
