### ISSUE TITLE
Bug - Ruby Advanced Section: Blocks syntax not working as represented

### ISSUE THREAD

**Issue by jampamatos** [TheOdinProject/curriculum#24467]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the Blocks Lesson on Advanced Ruby, when assigning `yield` to a variable is being discussed, we have the following example:

```
@transactions = [10, -15, 25, 30, -24, -70, 999]

def transaction_statement
  formatted_transactions = []
  @transactions.each do |transaction|
    formatted_transactions << yield(transaction) # We've put () around transaction just for clarity here but they aren't required.
  end

  p formatted_transactions
end

transaction_statement do |transaction|
  "%0.2f" % transaction
end
#=> ["10.00", "-15.00", "25.00", "30.00", "-24.00", "-70.00", "999.00"]
```

The problem is on line 6, that reads reads as follows:

`formatted_transactions << yield(transaction) # We've put () around transaction just for clarity here but they aren't required.`

I tried running this example both on irb and in my IDE without the parenthesis and it didn't work, it threw a syntax error. Putting the parenthesis back runs perfectly.

**2. How To Reproduce:**

1. Type the example code on an IDE or irb
2. Run it (it will work)
3. Remove the optional parenthesis stated in the comment on line 6 as non required.
4. Run it again (it will throw an syntax error)

**3. Expected Behavior:**

1. Type the example code on an IDE or irb
2. Run it (it will work)
3. Remove the optional parenthesis stated in the comment on line 6 as non required.
4. Run it again (it should work)

**4. Desktop/Device:**

-   Device: Acer Aspire 3 Laptop
-   OS: Ubuntu 20.04.4 LTS
-   Browser: Mozilla Firefox

**5. Additional Information:**

I have reported it on Discord and was instructed to Submit it as an issue, as this syntax is really off.

**Comment by ChargrilledChook** [comment]
Hi @jampamatos, thanks for the report and and sorry for the delay getting back to you.

You're absolutely right - I think there was a change in Ruby operator precedence that affected this behavior, can't recall exactly when.

In this particular case, we would need to do `formatted_transactions << (yield transaction)` to disambiguate. But maybe it's less confusing to simply remove the last sentence

**Comment by msespos** [comment]
Happy to work on this issue! -Mike

**Comment by ChargrilledChook** [comment]
@msespos thanks! All yours

**Comment by msespos** [comment]
I'm just removing the comment here. PR coming shortly!
