### ISSUE TITLE
Revisiting RPS: Update screenshot to say main branch instead of master

### ISSUE THREAD

**Issue by zachmmeyer** [TheOdinProject/curriculum#24489]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

https://github.com/TheOdinProject/curriculum/pull/24298#discussion_r907986194

**2. Acceptance Criteria:**

- [ ] Aforementioned screenshot is updated

**3. Additional Information:**

**Comment by Overlandcoder** [comment]
I'd love to work on this!

**Comment by zachmmeyer** [comment]
@Overlandcoder All yours!
