### ISSUE TITLE
The link given on the "Linting" page does not work, the suggested page is broken (404 Error).

### ISSUE THREAD

**Issue by cagriatalay** [TheOdinProject/curriculum#24502]
Complete the following REQUIRED checkboxes:
-   [ X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

On the "Linting" page of the TOP curriculum, the first article under the heading of "Linting" is broken.

![adja](https://user-images.githubusercontent.com/90172969/183248035-8d767848-93d2-4e4d-92bf-99d17f343326.JPG)

![The broken link](https://user-images.githubusercontent.com/90172969/183247999-e29b8a39-89a9-4ee5-9550-b85897dbb6d9.JPG)

**2. How To Reproduce:**
Visit a lesson page

**3. Expected Behavior:**
Visit a lesson page

**4. Desktop/Device:**

-   Device: Computer
-   OS: 
-   Browser: Brave
-   Version: 1.42.86

**5. Additional Information:**

No additional information.

**Comment by zachmmeyer** [comment]
https://mikecavaliere.com/javascript-linting-what-developers-need-to-know
Here's the link. Would you like to fix this?

**Comment by cagriatalay** [comment]
Of course! thank you!

**Comment by cagriatalay** [comment]
@zachmmeyer Nicely done, thanks for the opportunity!

**Comment by zachmmeyer** [comment]
@cagriatalay I commented on your forked PR.

**Comment by cagriatalay** [comment]
> @cagriatalay I commented on your forked PR.

Okay thanks, i am on it.

**Comment by cagriatalay** [comment]
@zachmmeyer I hope it is working now sir.
