### ISSUE TITLE
Code examples in Ruby lesson: misnamed variables?

### ISSUE THREAD

**Issue by Leo-U** [TheOdinProject/curriculum#24569]
Apologies in advance if in fact I just don't understand the lesson content.

The lesson section is [here](https://www.theodinproject.com/lessons/ruby-nested-collections#creating-a-new-nested-array).

It states "To create an array of **mutable** objects (string, array, hash, etc), you will need to pass the default value for Array.new via a block, using curly braces, instead of the second optional argument."

Below is a screenshot. You can see that the variable in the code example with the curly brackets is named `immutable`, and the variable in the other code example is named `mutable`. Shouldn't the variable names should be switched?

![Screenshot from 2022-08-22 12-57-55](https://user-images.githubusercontent.com/47509535/185977330-2e688837-92ad-41bc-83b2-3d68be25fbaa.png)

**Comment by Uaitt** [comment]
I think the variable names are right, but the description should be switched to:
"To create an array of **immutable** objects...".

**Comment by rlmoser99** [comment]
I understand that this is confusing and you are not the only person that has questioned this. Let me see if I can clear this up.

The variable names in the code examples point indicate whether or not the entire array will be mutable or immutable. So they are correct.

The wording of "To create an array of mutable objects" is referring to the type of object INSIDE the array, like string, array, hash. These objects are mutable, therefore if you don't use the block syntax with this type of object, the entire array can be mutated. So this is also correct.

I am open to someone clearing up these point in the lesson.

**Comment by rlmoser99** [comment]
The best place to ask these types of questions is going to be our Discord community, so I really encourage you to ask these types of questions there in the future.

Below is the lesson's code example using a string, that is mutated with `upcase!`. 

The entire `mutable` array can be mutated if an object inside is mutated. However, the entire `immutable` arrays will not be mutated if an object inside is mutated.
```
mutable = Array.new(3, "odin")
=> ["odin", "odin", "odin"]
mutable[0].upcase!
=> "ODIN"
mutable
=> ["ODIN", "ODIN", "ODIN"]

immutable = Array.new(3) { "Odin" }
=> ["odin", "odin", "odin"]
immutable[0].upcase!
=> "ODIN"
immutable
=> ["ODIN", "odin", "odin"]
```

**Comment by Leo-U** [comment]
Thank you again for your attention. I will be sure to ask questions in Discord from now on.
> Below is the lesson's code example using a string, that is mutated with `upcase!`.
> 
> The entire `mutable` array can be mutated if an object inside is mutated. However, the entire `immutable` array will not be mutated if an object inside is mutated.
> 
> ```
> mutable = Array.new(3, "odin")
> => ["odin", "odin", "odin"]
> mutable[0].upcase!
> => "ODIN"
> mutable
> => ["ODIN", "ODIN", "ODIN"]
> 
> immutable = Array.new(3) { "odin" }
> => ["odin", "odin", "odin"]
> immutable[0].upcase!
> => "ODIN"
> immutable
> => ["ODIN", "odin", "odin"]
> ```
So the entire array is mutable/immutable. Gotcha. And your second code example is an immutable array of mutable objects. If I might suggest a possible content change, the phrase
> To create an array of mutable objects (string, array, hash, etc)

might be changed to
> To create an immutable array of mutable objects (string, array, hash, etc)

**Comment by rlmoser99** [comment]
@Leo-U I agree with your suggestion. Would you like to make a PR for this change?

**Comment by Leo-U** [comment]
@rlmoser99 Yes that sounds like a good learning opportunity for me since I haven't done that before.
