### ISSUE TITLE
Pattern Matching lesson (Ruby) - Incorrect info about return statement

### ISSUE THREAD

**Issue by Uaitt** [TheOdinProject/curriculum#24586]
Inside of the [Pattern Matching lesson](https://www.theodinproject.com/lessons/ruby-pattern-matching), in the paragraph about the return values of a Pattern Matching statement, this is said:

>### Return values
>There are two possible return values from a pattern match statement. The first is `true` which is returned whenever there is a match, even when the match is the else clause in a statement. The second possible return value is a `NoMatchingPatternError` whenever no match can be found. 

While the second statement is true (when there is no pattern that matches and no else guard, a NoMatchingPatternError is raised), the first one is wrong. 
When there is a match with a pattern, the return value of the Pattern Matching statement is the last evaluated value inside of the matched-pattern body. If the body is empty, then the return value is nil.
When there is no match, but the else guard is present, the return value of the statement is the last evaluated value inside of the else body. If the body is empty, then the return value is nil.

True is not the default value for a Pattern Matching Statement.

**Comment by CouchofTomato** [comment]
Hey @Uaitt 

Thanks for creating this issue. Ruby used to have that behaviour initially but it was considered unstable so seems it has been changed. Are you happy to open a PR to update this?

**Comment by Uaitt** [comment]
hey @CouchofTomato , thanks for answering! 

I will try to put down a PR for the issue in question this week. However, I'm not that good at explaining things with words, if you can come up with a neat explanation feel free to comment down here or open a PR with the changes yourself.
