### ISSUE TITLE
Bug - JS OOP Principles lesson reading material: Tasteless/offensive jokes in the reading

### ISSUE THREAD

**Issue by msespos** [TheOdinProject/curriculum#24590]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

I just read through a short article in the OOP Principles lesson in the JS course that included two fairly tasteless jokes. Since there are a number of articles on the SOLID principles in that lesson, perhaps we could remove this one? I'm referring to Principle 4 in the following article. The author even says "Bad joke" in one instance, so I don't know what he was thinking including that one.
https://thefullstack.xyz/solid-javascript/

**2. How To Reproduce:**

Read the article, specifically Principle 4

**3. Expected Behavior:**

We should stick to more professionally written and less potentially offensive articles.

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 
N/A
**5. Additional Information:**

There are several other articles on the SOLID principles in this lesson already. We could just remove this article and would probably be fine. Or we could replace this with another similar article.

**Comment by msespos** [comment]
I'm happy to work on this issue, but left that box unchecked in case anyone else would like to take it on.

**Comment by Eduardo06sp** [comment]
Duplicate issue (although it hasn't been reviewed): https://github.com/TheOdinProject/curriculum/issues/24463

**Comment by msespos** [comment]
Happy to take care of this this - please feel free to assign this to me - thanks!

**Comment by ChargrilledChook** [comment]
> Happy to take care of this - please feel free to assign this to me - thanks!

Thanks Mike, appreciated. Feel free to replace the resource if you think it's required or simply remove it - use your best judgement
