### ISSUE TITLE
Bug - "Preparing to Interview and Interviewing": the link "Mastering the phone screen by Monster" is broken.

### ISSUE THREAD

**Issue by gefgu** [TheOdinProject/curriculum#24607]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

I can't access the following link:
![image](https://user-images.githubusercontent.com/53129852/187744362-6d13880a-9c9a-4a60-a055-837aec5a3308.png)

**2. How To Reproduce:**

1. Go to https://www.theodinproject.com/lessons/node-path-getting-hired-preparing-to-interview-and-interviewing#the-phone-screen
2. Click the "Mastering the phone screen by Monster" link

**3. Expected Behavior:**

It would be expected that the website was working. From what I understood, the monster.com website is off.

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by klaw772** [comment]
This site seems to be back up @gefgu - I can't reproduce the bug that you're seeing.
