### ISSUE TITLE
General curriculum: Consider adding mermaid to better express topics that are suitable for diagramming

### ISSUE THREAD

**Issue by duckpunch** [TheOdinProject/curriculum#24617]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Some parts of the curriculum lend themselves to an explanation in a visualization of some sort.  Consider adding [Mermaid JS](https://mermaid-js.github.io/mermaid/#/) to support different kinds of diagrams.

**2. Acceptance Criteria:**

- [ ] Curriculum Markdown supports Mermaid, perhaps implemented as follows.

```
~~~mermaid
flowchart LR

some-->diagram
~~~
```

**3. Additional Information:**

[Github uses this for their diagrams](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams).

```mermaid
flowchart LR

like-->this
```

It might be enough to just include a CDN link in statics [like so](https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted?id=_3-calling-the-javascript-api).

**Comment by KevinMulhern** [comment]
Which parts of the curriculum do you think would benefit from this @duckpunch?

**Comment by duckpunch** [comment]
@KevinMulhern I think there can be a few places.  Here are some examples.  I'm sure there are probably more.

* The [git lesson](https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git) could benefit from something like [this](https://mermaid.js.org/syntax/gitgraph.html).
* [ER diagrams](https://mermaid.js.org/syntax/entityRelationshipDiagram.html) could be used in the [database explanation](https://www.theodinproject.com/lessons/databases-databases-and-sql) or the [ActiveRecord](https://www.theodinproject.com/lessons/ruby-on-rails-active-record-basics) lesson.
* [Class diagrams](https://mermaid.js.org/syntax/classDiagram.html) could be used in the [OOP lessons](https://www.theodinproject.com/lessons/ruby-object-oriented-programming).
* [Authentication](https://www.theodinproject.com/lessons/nodejs-authentication-basics) could be described with a [sequence diagram](https://mermaid.js.org/syntax/sequenceDiagram.html).

**Comment by KevinMulhern** [comment]
Thank you for that breakdown @duckpunch 💪 I can see the value in it too.

To at least get things started, something like that git graph would be great in the git branches section [of this lesson](https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors#using-branches).

Does anybody want to take a stab at it?

**Comment by JoshDevHub** [comment]
I think this is a cool idea! I played around with it some and got it working locally in the Lesson Preview tool:

![image](https://user-images.githubusercontent.com/88392688/228427534-d275a07f-6694-4915-bbac-fc4dc8309c5a.png)

I did have to add the `mermaid` node package for this as I couldn't get the CDN to work and there don't seem to be any clean integrations with `Kramdown` or anything (at least that I could find, definitely welcome any other thoughts on this). I feel like there might be a few concerns to get through before going all out, with probably the main one being [color theme](https://mermaid.js.org/config/theming.html) stuff.

**Comment by KevinMulhern** [comment]
Thanks for digging into it @JoshDevHub 💪 
I would need to see it mixed with content to say for sure, but that looks _really_ nice. Most of that coloring looks pretty good. It would be nice to have the on brand gold in place of the pink. But that wouldn't be a deal breaker for me.

For integration with Kramdown, if we need to, we may be able to write an extension similar to what [Gitlab](https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/15107/diffs) have done. We've done a little bit of that for converting [lesson content](https://github.com/TheOdinProject/theodinproject/tree/main/lib/kramdown).

**Comment by JoshDevHub** [comment]
Okay I have it working locally among lesson content @KevinMulhern 

Here's dark mode:
![image](https://user-images.githubusercontent.com/88392688/228610360-1834a800-6c6d-425c-81f5-8935f387792a.png)

And light:
![image](https://user-images.githubusercontent.com/88392688/228610940-e9ec8ed6-5baa-4d04-a4d5-5e4d5901143f.png)

I'm just using mermaid's default dark mode here, and I actually think it looks pretty nice for both themes as is lol. Or at least this particular git diagram does. Maybe good to see how all the relevant diagram types will look.

**Comment by KevinMulhern** [comment]
Thats honestly pretty amazing, it's not often these tools look _that_ seamless the box lol. If you think it's worth adding to the site, I'm totally game too.
