### ISSUE TITLE
Python course: Add a learning path like "Full Stack Python"

### ISSUE THREAD

**Issue by OmerFI** [TheOdinProject/curriculum#24633]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I'd like to see a learning path for becoming a Full Stack Python Developer

**Comment by LeoKirasic** [comment]
We appreciate the suggestion. We have discussed this before, and considering how much time and effort is needed to add and support another language the current stance is that we'd like to use our energy on making what we already have even more high quality!
