### ISSUE TITLE
Bug: Link under Javascript Classes section

### ISSUE THREAD

**Issue by eslang50** [TheOdinProject/curriculum#24638]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Under the Classes section for the Javascript path, when you click on the link under 'Knowledge Check' called 'Describe static properties', it will result in a 404 error. 

**2. How To Reproduce:**

1. Log in
2. Visit 'Classes' Lesson under Javascript path
3. Click 'Describe static properties' under Knowledge Check
4. Link destination will be an error

**3. Expected Behavior:**

1. After clicking on the link, it will not send you to the expected location. 

**4. Desktop/Device:**

-   Device: PC
-   OS: Windows 10
-   Browser: Chrome, Edge
-   Version: 21

**5. Additional Information:**
I believe the link should send you to the mdn web docs (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), specifically under the 'Static Initialization Blocks' section.

**Comment by JuanVqz** [comment]
This issue can be closed, it's already solved.

It is using this link
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
