### ISSUE TITLE
Bug - Foundation Git Basics Section: Missing parenthesis and hard to read backtick in assignment

### ISSUE THREAD

**Issue by Heromazing** [TheOdinProject/curriculum#24647]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The backtick is difficult to read, and there is a missing parenthesis.
![Typo](https://user-images.githubusercontent.com/72627224/190840565-23b73904-85d4-4584-9f37-eea0f19b53c6.png)

**2. How To Reproduce:**

1. Log in
2. Visit "Foundations"
3. Scroll to "Git Basics" then click "2. Git Basics"
4. Scroll to Assignment
5. Scroll to 3rd step of "Modify a File or Two"

**3. Expected Behavior:**

It should be like this:
> Back in your terminal (or in the fancy built-in terminal in Visual Studio Code with ( Ctrl + ` ), type git status. You’ll notice that README.md is now shown as not staged or committed.

**4. Desktop/Device:**

-   Device:  Lenovo ThinkPad E15
-   OS:  Windows 10
-   Browser:  Microsoft Edge
-   Version:  105.0.1343.42 (Official build) (64-bit)

**5. Additional Information:**

This HTML Block can't render whitespace after backtick
```html
<p>
    Back in your terminal (or in the fancy built-in terminal in Visual Studio Code with <em>Ctrl + `</em> ), type <code>git status</code>. You’ll notice that README.md is now shown as not staged or committed.
</p>
```

I think it should be like this because it can render the whitespace after backtick
```html
<p>
    Back in your terminal (or in the fancy built-in terminal in Visual Studio Code with ( <em>Ctrl + `</em>&ensp;), type <code>git status</code>. You’ll notice that README.md is now shown as not staged or committed.
</p>
```
![Fix](https://user-images.githubusercontent.com/72627224/190842175-3bac9312-5189-41c2-86ac-b9cb8705f4b5.png)

**Comment by Heromazing** [comment]
Sorry, I think I got confused between the 2 repositories, but there is a missing parenthesis.

**Comment by Lofty-Brambles** [comment]
If this is still an issue that needs to be solved, I'd like to work on it. The condition it is in right now seems more confusing.

**Comment by ManonLef** [comment]
![Screenshot 2022-11-14 at 14 41 06](https://user-images.githubusercontent.com/81025586/201714582-32f1a764-fea0-4104-938c-79217d81810f.png)

I found the lesson [here](https://www.theodinproject.com/lessons/foundations-git-basics#assignment)
and it looks like the screenshot currently so this issue seems resolved.
