### ISSUE TITLE
Bug - Rails Basics - Controller:ln 166: Remove link to SnapChat - Help users avoid Wormhole

### ISSUE THREAD

**Issue by iarobinson** [TheOdinProject/curriculum#24665]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
Avoiding falling into wormholes is hard when starting out.

Linking to SnapChat is an invitation to an infinite, addictive wormhole.

I propose that the link be removed.

**2. How To Reproduce:**
Visit the [controllers section](https://www.theodinproject.com/lessons/ruby-on-rails-controllers) and search `SnapChat`.

**3. Expected Behavior:**
The link shows up... maybe this isn't really a bug... It works as expected.

**4. Desktop/Device:**
Not applicable.

**5. Additional Information:**
The screenshots below tell the story of where the bug is.

This is more of an editorial note... so I hope I'm not annoying you guys. I'd be happy to make a PR fixing this.

Thank you for TOP - It has been a great resource. I'm a big fan.

<img width="865" alt="Screen Shot 2022-09-21 at 11 54 29" src="https://user-images.githubusercontent.com/7991933/191608928-1572c584-962b-453a-abb0-48a80f142dac.png">

<img width="1255" alt="Screen Shot 2022-09-21 at 13 48 06" src="https://user-images.githubusercontent.com/7991933/191608949-657b4244-398e-4df1-aaa4-a27bb8aa4e9a.png">

**Comment by amnindersingh12** [comment]
Hi @iarobinson , I would love to fix this issue. Can you please assign this to me?
