### ISSUE TITLE
Broken Link in Javascript Recursion Project

### ISSUE THREAD

**Issue by Aminady** [TheOdinProject/curriculum#24679]
Complete the following REQUIRED checkboxes:
-   [✓] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [✓] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [✓] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

When clicked on, the link to read about common ways to run scripts from the command line show this : 

![Screen Capture (4)](https://user-images.githubusercontent.com/89994523/192105930-5dd64187-f155-4281-bea3-349fd8a3fa87.png)

**2. How To Reproduce:**

Visit the project : Recursion and click on the second link.

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: Lenovo Thinpad
-   OS: Windows 10
-   Browser: FireFox, Chrome
-   Version: 

**5. Additional Information:**

**Comment by rtins** [comment]
This has been fixed in a recent PR. Try again :)
