### ISSUE TITLE
Foundation Path/Foundations Course/HTML Boilerplate: Briefly explain what an attribute is

### ISSUE THREAD

**Issue by alfonsusac** [TheOdinProject/curriculum#24688]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
It would be nice to also include what an attribute is and how most of them follows a key-value pair to add basic description of the element

Link:
https://www.theodinproject.com/lessons/foundations-elements-and-tags

**2. Acceptance Criteria:**
-  [ ] A description of what an attribute is
-  [ ] Followed by a picture (if needed, update the first picture in the given link)

**3. Additional Information:**
None

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @alfonsusac.

We include an explanation about html attributes in the [images and links](https://www.theodinproject.com/lessons/foundations-links-and-images) lesson. I believe that is a better place for it from a learning experience point. Front loading an explanation about html attributes long before they are needed won't help learners retain what they are learning.  

Happy for others to chime in, but thats my view on it.

**Comment by CouchofTomato** [comment]
Agreed. I think it's easy to want to introduce concepts early with hindsight but we need to be careful we don't overwhelm learners.
