### ISSUE TITLE
Bug - Rails Assets and Navigation section: CSS/SCSS Files no longer auto-generated 

### ISSUE THREAD

**Issue by KarimElsayad247** [TheOdinProject/curriculum#24717]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the Assets and Navigation section, in the [Asset Pipeline lesson](https://www.theodinproject.com/lessons/ruby-on-rails-the-asset-pipeline) particularly in the part about manifest files, it's described that scss files are created for each controller you create

> whenever you create a Controller in Rails. It generates a directory for views related to the controller where your HTML lives and it also creates a stylesheet in the same name. So if you create a Controller called CatController to handle all those requests for your awesome collection of cat GIFs then Rails will also create a cat.scss stylesheet where you can put CSS related to your cat views.

With rails 7 however, this is no longer the case. There's more explanation [in this stackoverflow answer](https://stackoverflow.com/questions/71134117/rails-7-doesn-t-generate-scss-file-on-the-generate-scaffold-command)

So that part of the lesson needs to be updated.

**2. How to reproduce**

This section feels out of place for a content "bug", that said:

1. Visit the [Asset Pipeline lesson](https://www.theodinproject.com/lessons/ruby-on-rails-the-asset-pipeline)
2. Scroll down or ctrl+f to the part about "stylesheet manifest file"

**Comment by zapxcero** [comment]
Just encountered this and was about to create an issue. Up!

**Comment by KevinMulhern** [comment]
Thanks for reporting and sorry for the delay @KarimElsayad247. I agree we should rewrite that paragraph to reflect how it now works in Rails 7

**Comment by zapxcero** [comment]
Hope someone who knows asset pipeline well do a PR. I'm really still confused with this topic still xd

**Comment by xsherryhe** [comment]
Hi, I'd like to be assigned this issue! Rails 7 took away auto-generation of stylesheets on the justification that most apps nowadays use a CSS framework rather than manually writing CSS ([source](https://github.com/rails/rails/pull/43110)). But, it's still important to show in the lesson that CSS files can be manually added to the asset pipeline. I'll update the paragraph and include an example of how to do that.

**Comment by KevinMulhern** [comment]
Thanks @xsherryhe, it's all yours.
