### ISSUE TITLE
Bug - : Foundations - Fundamentals Part 2 - Linked article (#6) under Conditionals has incorrect information

### ISSUE THREAD

**Issue by ziayanj** [TheOdinProject/curriculum#24723]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The linked article from digital ocean contains incorrect information about switch statements, and needs to be replaced with a better, more accurate tutorial. An alternative could be this great article from [javascript.info](https://javascript.info/switch)

**2. How To Reproduce:**
1. Visit the [Fundamentals Part 2](https://www.theodinproject.com/lessons/foundations-fundamentals-part-2) lesson.
2. Scroll down to the [Conditonals](https://www.theodinproject.com/lessons/foundations-fundamentals-part-2#conditionals) section.
3. Go the tutorial from digital ocean linked at [number 6](https://www.digitalocean.com/community/tutorials/how-to-use-the-switch-statement-in-javascript)
4. Scroll down to the paragraph just above the 'Switch Ranges' heading.
5. The text reads: _'If we had omitted the break keyword in each statement, none of the other case statements would have evaluated to true, but the program would have continued to check until it reached the end. In order to make our programs faster and more efficient, we include the break.'_
6. This is wrong as it implies that the reason of using a break keyword in every case of a switch statement is efficiency, and the code would run correctly even if it was omitted. That is not the case as omitting a break leads to the code in next case running, without the condition being checked.

**3. Expected Behavior:**
1. The linked tutorial on Switch statements should have the correct information, especially since this is supposed to be the reader's first introduction to the topic.
2. I also do not like how the tutorial goes on to teach the use of evaluating a different condition in each case, by keeping the original switch expression to be just 'true', and thus evaluate on a 'range of values'. This is the typical case of not using the right tool for a particular job, as an if-else construct is always the better solution in such cases.

**4. Desktop/Device:**
-   Device: MacBook Pro
-   OS: macOS Monterey 12.3
-   Browser: Google Chrome

**5. Additional Information:**
A screenshot with the highlighted erroneous text:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/32636011/193454724-2ba10342-a696-4b0d-bd4e-073eb46ff2bd.png">

**Comment by CouchofTomato** [comment]
Hey @ziayanj 

Sorry for the delay in this getting picked up. You're right about that sentence being wrong. Do you still want to work on this?

**Comment by ziayanj** [comment]
@CouchofTomato Hi, no worries

Yes, I'm open to working on this

**Comment by CouchofTomato** [comment]
All yours @ziayanj
