### ISSUE TITLE
Bug - :Foundations - HTML Foundations - HTML Boilerplate:Charset article link does not go to an article

### ISSUE THREAD

**Issue by EuphCodes** [TheOdinProject/curriculum#24724]
Complete the following REQUIRED checkboxes:
-   [ +] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ +] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

When going through the additional resources on the HTML Boilerplate page, upon clicking "Read through this article about what [charsets you should use with your HTML pages]" the website following is not showing an article but instead a searchable page.

**2. How To Reproduce:**

Visit HTML Boilerplate page
Go to additional resources
Click first additional resource titled Read through this article about what [charsets you should use with your HTML pages]
Linked page is not an article

**3. Expected Behavior:**

Visit lesson page
Click mentioned link to article
View said article

**4. Desktop/Device:**

-   Device:  Acer Desktop
-   OS:  Xubuntu
-   Browser:  Chrome
-   Version: 

**5. Additional Information:**

**Comment by scheals** [comment]
I believe #24748 fixed this issue.

**Comment by KevinMulhern** [comment]
Thanks for reporting @EuphCodes
