### ISSUE TITLE
Bug - Text Editors: Possibly unnecessary paragraph

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#24737]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
[In the Linux section of VSCode installation](https://www.theodinproject.com/lessons/foundations-text-editors) there is a mention of an alternative installation through `apt`:

> Alternative Installation
> 
> More advanced users might want to install VSCode using the built-in apt package manager. This allows VSCode to be kept up to date automatically. Instructions on how to set this up can be found on [this webpage](https://code.visualstudio.com/docs/setup/linux).

Thing is, the regular instructions do use apt to install VSCode and follow the regular instructions from VSCode. Was this supposed to mention `snap` instead?

**2. How To Reproduce:**
1. [Go to Text Editors page, Linux install section](https://www.theodinproject.com/lessons/foundations-text-editors).
2. Confirm that the regular installation and alternative installation is the same.

**3. Expected Behavior:**
1. [Go to Text Editors page, Linux install section](https://www.theodinproject.com/lessons/foundations-text-editors).
2. Either alternative installation really is alternative or there is no such thing at all.

**4. Desktop/Device:**
-   Device: PC
-   OS: Windows
-   Browser: Firefox
-   Version: 105.0.1 (64-bit)

**5. Additional Information:**

**Comment by zapxcero** [comment]
I think it was fine but a bit unclear. The instruction above that included downloading a .deb file and then installing itl. However, the alternative installation probably meant using sudo apt install code, **downloading** and **installing** the program from the repository itself.

**Comment by CouchofTomato** [comment]
@scheals 

I believe this has now been resolved but please let me know if you still want this open
