### ISSUE TITLE
Modify wording of extra credit for Etch-a-Sketch project to improve clarity

### ISSUE THREAD

**Issue by arkii1** [TheOdinProject/curriculum#24738]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Current extra credit section: 
Instead of just changing the color of a square from black to white (for example), have each pass through with the mouse change it to a completely random RGB value. Then try having each pass just add another 10% of black to it so that only after 10 passes is the square completely black.

It's not uncommon for students in discord to ask for more clarity on this section. The extra credit would benefit from 2 changes to improve clarity:
1 - Separate the random colour feature and shading feature into 2 separate problems, numbered like the main problem.
2 - Change wording of the shading feature.

Overall, I'd propose changing the extra credit to the following (with correct styling):
1 - Instead of just changing the color of a square from black to white (for example), have each pass through with the mouse change it to a completely random RGB value.
2 - Add an option which shades a cell by 10% with each pass. For example, a cells' color starts at rgb(0,0,0) (white), and after 1 pass will be rgb(25, 25, 25). After 10 passes the cells' color should be rgb(255, 255, 255) (black).

**2. Acceptance Criteria:**

-   [ ]  I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

**3. Additional Information:**

**Comment by CouchofTomato** [comment]
Hey @arkii1 

I'm really sorry this got so long to get picked up. I think your suggestion is a good one. Do you want to work on this still?

**Comment by arkii1** [comment]
@CouchofTomato no worries, but yeah I'll get a PR ready in the next few days

**Comment by CouchofTomato** [comment]
Thanks @arkii1 

I've assigned you. Appreciate the help.

**Comment by codyloyd** [comment]
@arkii1 are you still working on this?

**Comment by arkii1** [comment]
> @arkii1 are you still working on this?

Hey mate, apologies been super busy so haven't managed to. Probably better assigning it to someone else

**Comment by BigO-Dev** [comment]
Hey, if you need someone to take on this issue, I'd like to give it a shot. 

I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)

    The title of this issue follows the location for request: brief description of request format, e.g. NodeJS course: Add lessons on XYZ

The following checkbox is OPTIONAL:

    I would like to be assigned this issue to work on it

**Comment by CouchofTomato** [comment]
> Hey, if you need someone to take on this issue, I'd like to give it a shot.
> 
>     * [x]  I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
> 
>     * [x]  I would like to be assigned this issue to work on it

All yours mate.
