### ISSUE TITLE
Rails/Node Course: Add path agnostic regular expressions introduction

### ISSUE THREAD

**Issue by crespire** [TheOdinProject/curriculum#24766]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
The curriculum currently only mentions regular expressions early on in Javascript Fundamentals 2. In this lesson, regular expressions are mentioned as an aside, telling learners that it is probably not a tool to reach for at this point in time.

I agree with that lesson's assessment of regex at that time, but it seems like the topic should be covered once learners are well into their respective advanced paths.

**2. Acceptance Criteria:**
- [ ] An introductory lesson on regular expressions if drafted for review
- [ ] Placement in each advanced path is decided. I feel that around the DSA section, learners will have the right context for an introduction to regular expressions
- [ ] Lesson should include external resources that provide more depth

**3. Additional Information:**
This suggestion has hit the Discord a number of times:
- https://discord.com/channels/505093832157691914/1026604554785144932
- https://discord.com/channels/505093832157691914/1027463158434103296
- https://discord.com/channels/505093832157691914/1019286859760803950

**Comment by wise-king-sullyman** [comment]
So I am pretty strongly against a full lesson for regex, and I'm _probably_ also against even a course section on it as I'm not really sure what the value add by us adding that content would be? If you think we should discuss regex in some capacity I would be a lot more likely to be on board with us just linking a resource.

**Comment by wise-king-sullyman** [comment]
At my work we require anyone that uses a regex to create an explanation for it using this tool: https://regexr.com/

What would you think about us just linking to that somewhere that makes sense?

**Comment by wise-king-sullyman** [comment]
Yeah we're in pretty much the same place so I'm going to go ahead and close it.

That being said, thank you for taking the time to put this together!
