### ISSUE TITLE
Rails: Installations Update for Rails 7

### ISSUE THREAD

**Issue by crespire** [TheOdinProject/curriculum#24765]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

See additional comment below.
~~With the introduction of Rails 7, it is no longer required to install `yarn`, as Rails will use import maps to manage JS. While it is still possible to use the older bundle behaviour (which requires `yarn`), it is not strictly necessary for the happy path of Rails installation.~~

~~The official Rails Getting Started Guide also omits installations for `node` and `yarn`. Learners following the curriculum would have already installed `node` very early on in Javascript fundamentals.~~

Some options for rails app generation still require `yarn` to be installed. The main hurdle is that Rails bundling relies on "Yarn Classic" and the Yarn page encourages folks to install the latest release.

**2. Acceptance Criteria:**

~~- [ ] Decide if the install instructions should skip Yarn.~~
~~- [ ] Remove yarn installation~~
~~- [ ] Add note and resource to additional resources about when you might require yarn~~
- [x] Install instructions should be updated to call out that "Yarn Classic" is the version that we should install.

**3. Additional Information:**

**Comment by crespire** [comment]
Doing some investigating, it seems that usage of bootstrap (unsure about other CSS engines/frameworks) will not work unless `yarn` is installed, even on Rails 7.

Doing some testing on my own, the following css bundling options rely on `yarn` when generating a new app:
* `-c bootstrap`
* `-c bulma`
* `-c postcss`
* `-c sass`

Options for css bundling that rely on importmaps when generating a new app:
* `-c tailwind`

Given that the majority of app generation CSS bundling options utilize `yarn` I think it would be wise to install `yarn`. As an alternative to removing the instruction, Odin should specify that learners should install yarn classic as it is currently not called out.

**Comment by crespire** [comment]
> Don't have super strong feelings about this, but a note about it being Yarn V1 wouldn't hurt.
> 
> Out of curiosity, is it possible to create one of these configs with esbuild etc without installing yarn first? I'm fairly sure Rails will install a yarn binstub that installs itself if needed, but not sure if I've ever tried with no yarn first.
> 
> In any case installing yarn isn't particularly difficult and doesn't add much overhead, I think

I'm not sure about the binstub, but I uninstalled Yarn classic and generated a `rails new blog -c bootstrap` and I didn't get any errors and am able to run the app with `bin/dev` though I do see a `unknown command: yarn build:css --watch` in the bin/dev startup messages.

I suspect if I were to actually build with this app template, I would run into issues with missing `yarn`.

I'll go ahead and make a PR now to call out that we should install yarn classic.

**Comment by crespire** [comment]
@ChargrilledChook 

Is there any reason we avoid installing `yarn` via `npm`? It is now the preferred option on that page, with an "Alternatives" fold. The older instructions say to pick the operating system then follow instructions, which is the flow now hidden by default.

I wonder if the yarn page has simply changed, or if we have always instructed users to use the "Alternative" method of install.

**Comment by ChargrilledChook** [comment]
Good question, not that I know of. You would have to ask the person who originally wrote it / have a look at the git blame. 

It's possible it was written at a time when Node wasn't introduced prior to Rails, but I'm unsure. 

Personally not opposed to following the recommended path
