### ISSUE TITLE
Rails: Install PostgreSQL for Development

### ISSUE THREAD

**Issue by crespire** [TheOdinProject/curriculum#24795]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
For rails deployments of the more complex projects, having a local development environment that mirrors a production environment in terms of tools helps to reduce friction upon deployment.

Currently, the Rails curriculum does not instruct users to install psql locally at all, though most folks make the switch on their own. While I don't have data, my anecdotal hunch is that most folks tend to explore this option around flight booker.

**2. Acceptance Criteria:**
- [ ] Content should include a brief recap of Rails environments (dev, test, prod)
- [ ] Content should include a brief introduction to environment variables
- [ ] Content for installing PostgreSQL locally for Ubuntu is created and validated
- [ ] Content for installing PostgreSQL locally for macOS is created and validated
- [ ] The lesson should be inserted somewhere that makes sense. My intuition is that it should be inserted as the first lesson in the *Advanced Forms and Active Record** section, but open to discussion and input.

**3. Additional Information:**
If this issue is accepted and assigned, @JoshDevHub has agreed to work on macOS instructions.

**Comment by ChargrilledChook** [comment]
@crespire @JoshDevHub sounds like a good idea to me, I'll run it by the team briefly to check there aren't any issues but happy to give this a tentative green light :+1:

**Comment by crespire** [comment]
> @crespire @JoshDevHub sounds like a good idea to me, I'll run it by the team briefly to check there aren't any issues but happy to give this a tentative green light :+1: 
> 

Will wait to hear back!

**Comment by ChargrilledChook** [comment]
@crespire go for it, look forward to seeing how it turns out 🤌

**Comment by crespire** [comment]
I've completed a first draft for review, but as we are still missing the macOS content, I will leave the PR in draft.

@scheals Pinging you for feedback as well, as our initial conversation sparked this issue/PR.
