### ISSUE TITLE
Bug - Foundations - Introduction - Join the Odin Community: Typo in the first sentence of "How to Help Others Solve Coding Problems" Section

### ISSUE THREAD

**Issue by ahmeducf** [TheOdinProject/curriculum#24807]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

There is a typo at the beginning of the first sentence.

![image](https://user-images.githubusercontent.com/53626822/195905863-466e1287-de87-45c9-9d3f-c074147be955.png)

>Not only **is it** important to know how to ask an effective question, 

should be 

>Not only **it is** important to know how to ask an effective question,

**2. How To Reproduce:**

What steps one might need to take in order to reproduce this bug, e.g.:
1. Log in
2. Visit **Foundations** course
3. Go to **Introduction** section
4. Click **5. Join the Odin Community** lesson
5. Scroll to **How to Help Others Solve Coding Problems** lesson section

or if you are already logged in: visit this link directly: [How to Help Others Solve Coding Problems](https://www.theodinproject.com/lessons/foundations-join-the-odin-community#how-to-help-others-solve-coding-problems)

**3. Expected Behavior:**
It should be like this:

> Not only is it important to know how to ask an effective question, it is also important to know how to help others effectively. Please take a moment to review these guidelines so that you will have proper expectations of the help you will receive in our Discord community. In addition, come back and review these guidelines when you are ready to start helping others.

**4. Desktop/Device:**

-   Device: Dell Latitude E6540
-   OS: Arch Linux
-   Browser: Chrome
-   Version: 106.0.5249.103

**5. Additional Information:**

**Comment by omalsa04** [comment]
I think the original wording is correct.

**Comment by ChargrilledChook** [comment]
@ahmeducf Thank you for the suggestion and the detailed report. 

In this case the original is grammatically correct. While normally it should be 'it is', typically this is inverted after 'not only'. For instance 'Not only do we...', 'Not only should you...' etc.

Thanks again for such a detailed write up - this makes it a lot easier for the Maintainer team to respond to issues.
