### ISSUE TITLE
Bug: in Authentication basics

### ISSUE THREAD

**Issue by Cherifi-Houdaifa** [TheOdinProject/curriculum#24804]
https://github.com/TheOdinProject/curriculum/blob/547c13f0a87c04fea485448c39ab0a0c400ee096/nodeJS/authentication/authentication_basics.md?plain=1#L329-L337
This code is asynchronous and then there is a return statement after it
which will cause it to return two times
which will throw an error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
you may consider using promises with async / await to make sure that the async operation finishes before next return statement
**or you can just remove the last return statment In the LocalStrategy Function**

**Comment by wise-king-sullyman** [comment]
It seems like something should be done here but I'm not certain what. @TheOdinProject/javascript any of yall familiar enough with using bcrypt to know what the best practice approach here is?

**Comment by ManonLef** [comment]
I'm fairly sure this can be rewritten to another example using the [bcrypt docs examples](https://github.com/kelektiv/node.bcrypt.js) or from the many [bcrypt examples online](https://www.google.com/search?client=safari&rls=en&q=bcrypt.compare+code+example&ie=UTF-8&oe=UTF-8). 

I will open this up for someone experienced enough with bcrypt to propose a new code sample

**Comment by Lofty-Brambles** [comment]
Will take a dig and open a PR in 24 hours.

**Comment by ManonLef** [comment]
assigned you @Lofty-Brambles 
thanks so much!

**Comment by Lofty-Brambles** [comment]
Minimum reproducible solution: https://codesandbox.io/p/sandbox/elegant-lewin-km7pj2
