### ISSUE TITLE
Ruby Course: Update usage of open-uri gem (open(filename) needs to now be URI.open(filename)

### ISSUE THREAD

**Issue by DNeel10** [TheOdinProject/curriculum#24811]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by ChargrilledChook** [comment]
@DNeel10 can you provide any information about where this needs to be updated? You're correct that this is deprecated and removed in Ruby 3.0 +, but this is difficult to action without knowing where to look for it

**Comment by DNeel10** [comment]
Hi, @ChargrilledChook 

This usage is was actually in the bastards book of ruby examples within the Files and Serialization Lesson in the Ruby path.  

The final Assignment item is "Read the [Chapter on File I/O](http://ruby.bastardsbook.com/chapters/io/) of the Bastard’s Book of Ruby."  In one of the examples in this chapter (importing hamlet and running some code on it) it asks you to use the open-URI gem, but the usage it goes over being able to just use  open(filename) instead of URI.open(filename)

I think there may just need to be a disclaimer on the assignment itself that the usage in that book has been deprecated.

**Comment by ChargrilledChook** [comment]
@DNeel10 Thanks for getting back to me! Your suggestion sounds like a good idea, would you like to try implementing it yourself or should we open it up to contributions?

**Comment by DNeel10** [comment]
I think it would be good for me to try and update myself.  I'll give it a go, but if i run into any complications (this is my first PR and open source contribution) am i able to comment back here to seek help? 

Thank you!

**Comment by ChargrilledChook** [comment]
@DNeel10 Of course, I'll be happy to help if you have any issues. Ping me here if you need anything. Thanks for taking this one on!

**Comment by DNeel10** [comment]
@ChargrilledChook Hey, Chook - I'm not too familiar with .md files, but i noticed that the way the assignment section looks (prior to me even forking/cloning) is off.  I was able to get everything set up and ready for my changes though, but i'm not sure how to actually change how the md renders.

**Comment by ChargrilledChook** [comment]
Thanks @DNeel10, at a glance it looks perfect - I'll have a closer look in the next 24 hours or so.

For seeing how the markdown renders on the site, we can use the [lesson preview tool](https://www.theodinproject.com/lessons/preview) - just paste the raw content of the lesson and it should render how it does on the site
