### ISSUE TITLE
Foundations -> Fundamentals 5: Add a readable course in the "Intermediate/Advanced Array Magic". 

### ISSUE THREAD

**Issue by shonebinu** [TheOdinProject/curriculum#24836]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

There are only two videos of Wes Bos's Javascript 30 challenge in the Intermediate/Advanced Array Magic section of Fundamentals Part 5 (https://www.theodinproject.com/lessons/foundations-fundamentals-part-5#intermediateadvanced-array-magic). Even though his videos are great resources, I find it hard since he talks about some advanced Javascript features. And there is also a lack of 'reading study material' in that section. Henceforth, I propose the maintainer add a study material which is in the reading form. Since I couldn't understand that section properly, I looked for materials on the internet and found this awesome article by javascript.info (https://javascript.info/array-methods). This article introduces the basic array methods such as sort, and reverse and goes in-depth into advanced array methods such as reduce, filter, map etc. at the bottom of the article. They also have an additional section in their article giving us tasks which we have to solve ourselves. I suggest adding this in the section as I found this article to the all in all condensed array method study guide. Thank you.

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by shonebinu** [comment]
![Screenshot from 2022-10-23 09-57-20](https://user-images.githubusercontent.com/62597277/197373733-a73043a8-2434-4e98-b7d4-ddd0108757a7.png)
We could add this article as a third option here to crosscheck with the videos or to completely study alone with it.

**Comment by cagriatalay** [comment]
This can be very useful!

**Comment by CouchofTomato** [comment]
Hey @shonebinu 

Sorry this took so long to get looked at. This seems reasonable to me. Is this still something you want to work on?

**Comment by shonebinu** [comment]
Hello @CouchofTomato, Sorry for the late reply.

Assigning this to me would be greatly appreciated as I view it as a valuable opportunity to learn and grow. I am more than willing to take on the task.

**Comment by CouchofTomato** [comment]
> Hello @CouchofTomato, Sorry for the late reply.
> 
> Assigning this to me would be greatly appreciated as I view it as a valuable opportunity to learn and grow. I am more than willing to take on the task.

@shonebinu All yours mate

**Comment by shonebinu** [comment]
Hi @CouchofTomato,

I've made the PR. https://github.com/TheOdinProject/curriculum/pull/25438

**Comment by CouchofTomato** [comment]
Thanks @shonebinu 

We'll get that reviewed shortly.
