### ISSUE TITLE
Bug - Getting Hired Course:Unreachable Link

### ISSUE THREAD

**Issue by GeorgeCiesinski** [TheOdinProject/curriculum#24857]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

On the `Strategy` lesson of the Getting Hired Course, one of the links in the Additional Resources section. See next section for details and link.

**2. How To Reproduce:**

What steps one might need to take in order to reproduce this bug, e.g.:
1. Log in
2. Visit a lesson page: https://www.theodinproject.com/lessons/node-path-getting-hired-strategy
3. Scroll to Additional Resources
4. Click the link [Getting your first IT job from InformationWeek](https://www.informationweek.com/team-building-and-staffing/how-to-land-your-first-it-job/d/d-id/1111584)

**3. Expected Behavior:**

I expected this link to open in a new tab, but it gives a Bad Gateway error.

**4. Desktop/Device:**

-   Device: Macbook Air M1
-   OS: Mac OS Monterey 12.6
-   Browser: Firefox
-   Version: 106.0.1 (64-bit)

**5. Additional Information:**
N/A

**Comment by GeorgeCiesinski** [comment]
Sorry in advance if this comment doesn't help the progress of this issue. I just wanted to add that I find value in this link as I was curious how an IT job would help finding a programming job. If possible, I would like to have this content preserved or replaced with a substitute rather than removed as a non working page, although I will leave this decision to the repo maintainers.

**Comment by NeptuneRjo** [comment]
I can take this up if it's alright.

**Comment by GeorgeCiesinski** [comment]
That would be fine with me as I don't have any intention of pushing this fix myself. If the maintainer of this repo is cool with it, it's all yours!

**Comment by ChargrilledChook** [comment]
Thanks for the report @GeorgeCiesinski and the offer @NeptuneRjo, looks like the link is working fine - maybe a temporary outage? I'm going to close this but I'm happy to re-open it if it's still having issues

**Comment by GeorgeCiesinski** [comment]
@ChargrilledChook Thanks for checking. You're right, I can reach the link again so it must have been temporary.
