### ISSUE TITLE
Bug - : foundations, js basics, fundamentals 2

### ISSUE THREAD

**Issue by pharshavardhan2** [TheOdinProject/curriculum#24880]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

   In lesson overview and knowledge check, we are asked about eight data types but no resource is mentioned about them. In additional resources, "regex vs builtin" link points to "let vs var" in stackoverflow.

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by sheilaJava** [comment]
Hi, it seems like the issues you mentioned have been resolved.

-  The eight data are listed in the first linked resource in the [introduction](https://www.theodinproject.com/lessons/foundations-fundamentals-part-2#introduction) : 

> "Before we start digging deep, however, [this article](http://javascript.info/types) will give you a quick overview of the most common ones.".

- The "regex vs builtin" link in the [additional ressources](https://www.theodinproject.com/lessons/foundations-fundamentals-part-2#additional-resources) does point to the right Stackoverflow post.

I guess this issue could be closed :)

**Comment by xandora** [comment]
Sounds like this has been resolved. Closing
