### ISSUE TITLE
Bug -  Working with APIs : Messed up wording in Assignment point #2

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#24894]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
In https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis#assignment the second bullet point reads:
 > Check out This list of Public API and This Public API of free, open APIs and let your imagination go wild.
This seems like the wording got messed up at some point, and now doesn't fully make sense anymore.

**2. How To Reproduce:**
1. visit the above link and read bullet point #2

**3. Expected Behavior:**
The wording isn't messed up

**4. Desktop/Device:**
N/A

**5. Additional Information:**

**Comment by ChargrilledChook** [comment]
Hi @Asartea, thanks for this suggestion, good catch - I've assigned it to you :+1: 

It looks like the original intent was to follow this [point in the style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#links) and provide descriptive links, but the wording got a bit messed up in the process.

**Comment by wise-king-sullyman** [comment]
@ganga-jpg are you still interested?

**Comment by ioakeimo** [comment]
This appears to have been introduced by  #24785 (commit 8c1c7c0).
Just the wording should be an easy fix, I can work on that if needed.

**Note:** The [second repository](https://github.com/public-apis/public-apis) appears to be somewhat inactive though, I'm not sure if there's any need to do something about that fact...

**Comment by KevinMulhern** [comment]
Thanks for investigating @ioakeimo, I'll assign it to you.

Agree on the second link, theres seems to be a lot of overlap between the two. We'd be happy to lose the second link and just have the first.
