### ISSUE TITLE
Introduction to MongoDB: Outdated Course and Link

### ISSUE THREAD

**Issue by ChrisSturgeon** [TheOdinProject/curriculum#24909]
### Describe your suggestion

This lesson currently suggests to take the entirety of MongoDB University's "Mongo Basics" course, however from 15th Nov they seem to have [refreshed their university](https://learn.mongodb.com/pages/welcome-to-the-new-mongodb-university) and you cannot seem to start this course (and have until 1st Dec to finish it if already underway). 

Instead, it appears to have been replaced by a slightly longer generic [Introduction to MongoDB](https://learn.mongodb.com/learning-paths/introduction-to-mongodb), or a [Node specific course](https://learn.mongodb.com/learning-paths/mongodb-nodejs-developer-path) course on their new university site. I assume the Node course is most relevant, but aren't able to see the curriculum of the old course to compare in detail. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-to-mongodb

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

**Comment by ChargrilledChook** [comment]
@ChrisSturgeon Thanks for the report, much appreciated.

 I'm unfamilar with this content but it seems like a good idea to find a way to link to the original, or find a suitable replacement. Using [the wayback machine](https://archive.org/web/) could be a useful tool to have a look at the previous content for anyone wanting to work on this issue.

**Comment by Overlandcoder** [comment]
I'd love to be assigned so I could fix this using the wayback machine.

**Comment by ChargrilledChook** [comment]
Thanks @Overlandcoder, all yours :+1:

**Comment by Overlandcoder** [comment]
@ChargrilledChook Here's a [link to the course](https://web.archive.org/web/20221101005831/https://university.mongodb.com/courses/M001/about) using the wayback machine. I'm not too familiar with how wayback machine works, but I think this may not work since starting the course requires a login.

[This](https://learn.mongodb.com/learning-paths/introduction-to-mongodb) is the new course they've added, it's 3.5 hours longer. Perhaps someone familiar with this content could confirm whether this new course is a good replacement, and if certain chapters could be skipped etc.

**Comment by ChrisSturgeon** [comment]
I'm ~75% of the way through [the new Node course](https://learn.mongodb.com/learning-paths/introduction-to-mongodb) and have already covered all points on the agenda @Overlandcoder has found on the wayback machine. 

Chapter 1: What is MongoDB?
Chapter 2: Importing, Exporting, and Querying Data
Chapter 3: Creating and Manipulating Documents
Chapter 4: Advanced CRUD Operations
Chapter 5: Indexing and Aggregation Pipeline
Chapter 6: Next Steps

Impossible for me to say without having completed the older course, but I think the most similar of their newer courses is [Introduction to MongoDB](https://learn.mongodb.com/learning-paths/introduction-to-mongodb), and [the Node specific](https://learn.mongodb.com/learning-paths/introduction-to-mongodb) course I'm working through is exactly the same content with a few more modules tacked on the end, namely: 

1. Connecting to MongoDB in Node.js
2. MongoDB CRUD Operations in Node.js
3. MongoDB Aggregation with Node.js

I'll probably complete it within the next 1-2 days so can report back then on whether or not the additional modules are worthwhile.

**Comment by ChrisSturgeon** [comment]
I've been through the rest of the Node specific course and, whilst interesting, I don't think the last three modules listed in my previous comment are all that useful as they use MongoDB's native driver - but the remainder of the TOP Node JS course (including the MDN tutorials) revolves around Mongoose. I think the most appropriate of the new courses would therefore be [Introduction to MongoDB](https://learn.mongodb.com/learning-paths/introduction-to-mongodb).

I'd love to be assigned to this issue to update the lesson assignment link if you agree.

**Comment by ChargrilledChook** [comment]
> I've been through the rest of the Node specific course and, whilst interesting, I don't think the last three modules listed in my previous comment are all that useful as they use MongoDB's native driver - but the remainder of the TOP Node JS course (including the MDN tutorials) revolves around Mongoose. I think the most appropriate of the new courses would therefore be [Introduction to MongoDB](https://learn.mongodb.com/learning-paths/introduction-to-mongodb).
> 
> I'd love to be assigned to this issue to update the lesson assignment link if you agree.  

Really appreciate the legwork you've done for this, happy to assign it to you. Thanks @ChrisSturgeon  🙌
