### ISSUE TITLE
Bug - : Objects and Object Constructors Section: Knowledge check link privacy error

### ISSUE THREAD

**Issue by adiferrer** [TheOdinProject/curriculum#24901]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the Objects and Object Constructors lesson in the Full Stack JavaScript path, there's a resource in the assignment portion that is not secure. It's this link: https://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/ . I've tried it in different browsers (Brave, Chrome and Safari) but every single time, the browser says it is not secure and there is a privacy error.

**2. How To Reproduce:**

Open Full Stack JavaScript path -> JavaScript course -> Objects and Object Constructors Lesson -> Knowledge Check -> Link 1.1 -> Link opens a new tab but displays a privacy error message

**3. Expected Behavior:**

Open Full Stack JavaScript path -> JavaScript course -> Objects and Object Constructors Lesson -> Knowledge Check -> Link 1.1 -> Link opens a new tab with article

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 
Device: MacBook M1, OS: Mac OS, Browser: Brave (also tested link in Chrome and Safari), versions for browsers in respective order: 1.44.105, 107.0.5304.110, 15.6.1

**5. Additional Information:**
 N/A

**Comment by CouchofTomato** [comment]
Might be worth waiting to see if they update their certs to fix this unless we have another resource ready to roll

**Comment by ChargrilledChook** [comment]
The archive version seems ok, could be a decent temporary (?) replacement
https://web.archive.org/web/20220915195800/http://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/

**Comment by xandora** [comment]
@ChargrilledChook At some point does a 13 year old article need to be refreshed?

**Comment by ManonLef** [comment]
The not secure website covers:
- prototype property
- prototype attribute
- constructor
- prototype based inheritance
And the assignment states: 
> The important bits here, once you’ve covered the basics, are ‘Prototype-based inheritance’ and the ‘Prototype chain’.

Some alternatives from the additional resources section could be:

- [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain) less plain language than the javascriptissexy one but covers just those important bits. Might need a __proto__ use disclaimer

- [Digital Ocean](https://www.digitalocean.com/community/tutorials/understanding-prototypes-and-inheritance-in-javascript) I'm not personally a fan of their formatting, somehow I find it less readable, but I do think the explanation is clear in here

**Comment by CouchofTomato** [comment]
@ManonLef 

Are you happy to make a PR to address this based on the resources you've provided? Wasn't sure based on your comment if you felt you had a solution.

**Comment by ManonLef** [comment]
@CouchofTomato absolutely. I wasn't sure if you still wanted to decide on using the older archive version or go with a newer one. 

If I had to pick, I'd prefer the digital ocean resource I shared for its clear language and explanation. It doesn't introduce too much complexity and new prototype syntax concepts as I believe the MDN article does. 

Perhaps they can both receive a spot in that lesson but I'd have to check the lesson to refresh on it. 

Feel free to assign it to me.

**Comment by CouchofTomato** [comment]
Thanks @ManonLef 

Although the older version may still be relevant it's quite old and this is a good time to put in an updated version. Your suggestion is perfect 💯

**Comment by ManonLef** [comment]
@CouchofTomato It actually looks like this lesson has been updated already: https://github.com/TheOdinProject/curriculum/commit/3dc18a844991410b4bb48511c92ec147ec1b7a74

**Comment by CouchofTomato** [comment]
Thanks. Closing this then
