### ISSUE TITLE
Project: Express 105: Forms And Deployment: Password Vulnerability Risk with MDN Tutorial

### ISSUE THREAD

**Issue by ChrisSturgeon** [TheOdinProject/curriculum#24933]
### Describe your suggestion

I've just completed the MDN library tutorial on deploying the local library app to Railway, however I think their instructions on using environment variables within project files to hide database usernames/passwords aren't very clear at all. It seems I'm not alone as 6 of the top 10 project submissions have their database credentials hard-coded into their app.js files. 

MDN do have a warning about this risk under [Creating an application repository in GitHub](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#creating_an_application_repository_in_github) but they suggest to skip this section if you're already familiar with GitHub, so I'm guessing most people visiting from TOP won't see this. They also don't actually link to any resources about how to implement environment variables. 

I think it would be beneficial to have a warning about this on the TOP lesson itself, perhaps before assignment point 2. I ended using [dotenv](https://www.npmjs.com/package/dotenv) in my solution and would be happy to write something up about this but not sure if this is the best approach as I'm new to it myself. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-express-105-forms-and-deployment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by ChargrilledChook** [comment]
@ChrisSturgeon Managing this for Node is not an area of experience for me, but dotenv sounds like a reasonable solution and an improvement. I'll see if I can find someone with some more expertise to weigh in but I think your suggestion is a pretty safe bet if you want to have a go at it:+1:

**Comment by ChrisSturgeon** [comment]
Thanks! Just submitted my PR.
