### ISSUE TITLE
Intermediate HTML and CSS: Link not working in the assignment section of the introduction chapter

### ISSUE THREAD

**Issue by KrunalDarekar** [TheOdinProject/curriculum#24961]
### Describe your suggestion

In the Assignment section of the Introduction chapter a "CSS Cheat sheet" has been linked, clicking it takes me to a page that says
"Access denied
Error code 1020
You do not have access to websitesetup.org.

The site owner may have set restrictions that prevent you from accessing the site."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Nozomu#5895

**Comment by robsassack** [comment]
This link works for me. I looked up the error you got and it looks like it might be a firewall issue. Is it possible to confirm if this occurs on another network with your machine?

**Comment by KrunalDarekar** [comment]
So it did not work on my wi-fi or either of my two mobile networks but it worked when I turned on the VPN.

**Comment by robsassack** [comment]
> > This link works for me. I looked up the error you got and it looks like it might be a firewall issue. Is it possible to confirm if this occurs on another network with your machine?
> 
> 
> 
> I got the same error as mentioned here for the link and I'm using my mobile network.

If you are outside the US, it could be an issue with your carrier. I just tested it on my 5G connection and it worked fine.

**Comment by xandora** [comment]
Not sure there is much we can do about this. FWIW, it's working fine here in New Zealand, so it's certainly not regionally locked.

**Comment by KrunalDarekar** [comment]
> > This link works for me. I looked up the error you got and it looks like it might be a firewall issue. Is it possible to confirm if this occurs on another network with your machine?
> 
> I got the same error as mentioned here for the link and I'm using my mobile network.

You can use a vpn, there is no other real solution.

**Comment by Shweta200126** [comment]
> > > This link works for me. I looked up the error you got and it looks like it might be a firewall issue. Is it possible to confirm if this occurs on another network with your machine?
> > 
> > 
> > I got the same error as mentioned here for the link and I'm using my mobile network.
> 
> You can use a vpn, there is no other real solution.

Yes I could open this link on brave's private **tor** tab. So if anyone else has same issue, they might try this.
