### ISSUE TITLE
NodeJS: Debugging Node assignment resources order suggestion

### ISSUE THREAD

**Issue by Qirall79** [TheOdinProject/curriculum#25001]
### Describe your suggestion

Hi, I am currently going through the Debugging Node lesson, and when I got to the assignment section I started with the first link which links to the official VS Code Node debugger documentation. The problm is that I couldn't keep up with the content there. I decided to start with the 3rd resource which is a video to debugging in VS Code, and came back to the documentation and it was much easier. So I suggest putting the video just above the Documentation link, that will make understanding the concepts much easier.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-debugging-node

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Chrollo#7144

### (Optional) Additional Comments

Thank u so much for this Curriculum <3

**Comment by codyloyd** [comment]
I think this is a worthy and simple change.

Let's just move the video to the top of the assignment section, before directing learners to the official docs.

**Comment by roy9495** [comment]
Can I get assigned?

**Comment by KevinMulhern** [comment]
Thanks @roy9495, it's all yours.

**Comment by codyloyd** [comment]
@sathwikgaddi it has already been assigned
