### ISSUE TITLE
ruby/basic_ruby/debugging.md: instructions for pry-byebug

### ISSUE THREAD

**Issue by kyleghousel** [TheOdinProject/curriculum#25016]
### Describe your suggestion

The instructions for getting started with pry-byebug is only for Ubuntu & deals with openSSL issue. This is not explicitly stated and can be confusing to learners who are a little more "green" with the terminal. (i.e. Me. On a mac system, I know it's linux-based I'm thinking 'oh why isn't this working for me?' struggled for a good some time until Scheals guided me through and showed me the error of my ways - shoutout to Scheals!). Adding a disclaimer for Linux would be helpful, or better yet even separated instructions for different systems, just like at the start of the ruby course.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-debugging

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Houselhoff93#6945

### (Optional) Additional Comments

I love you all :)

**Comment by ChargrilledChook** [comment]
Thank you for the suggestion @kyleghousel, and apologies it took me a while to respond. 

We're currently working on revamping this lesson with some slightly different technology that should mean this is no longer a problem. 

Check out #24994 if you're intesested in the details.

Nonetheless thank you for bringing this to our attention; it's much appreciated!
