### ISSUE TITLE
JavaScript Course "Recursive Methods" -- Incorrect Answer on "Implementation Issues" in Test Yourself Section

### ISSUE THREAD

**Issue by DONTSTOPLOVINGMEBABY** [TheOdinProject/curriculum#25015]
### Describe your suggestion

There is an external exercise that is linked to the "Test Yourself" section on the "Recursive Methods" module in the Javascript Course.

Here is the question: 
"Question 7: Parse a multi-dimensional array
Given a multi-dimensional integer array, return the total number of integers stored inside this array" 

The example function call and 'correct answer' is also given: 
var seven = totalIntegers([[[5], 3], 0, 2, ['foo'], [], [4, [5, 6]]]); // 7 

The problem here is that all the integers in this array add up to 25 and not 7. I wanted to put this here in case someone wanted to add a message on TOP's website to let people know that one of the answers listed on the site is incorrect. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

h246810#1073

**Comment by scheals** [comment]
Based on what you've mentioned:
> return the total number of integers stored inside this array

The answer is indeed 7, because it is asking for the number of integers, not a sum of them.

**Comment by CouchofTomato** [comment]
Closing because this seems like it has been answered.
