### ISSUE TITLE
Ruby: Object Oriented Programming Section Additional Resources Clarity

### ISSUE THREAD

**Issue by fiveNinePlusR** [TheOdinProject/curriculum#25023]
### Describe your suggestion

The additional resources section has a link to variables in ruby which seems out of place in this section. 

https://github.com/TheOdinProject/curriculum/blob/main/ruby/object_oriented_programming_basics/object_oriented_programming.md?plain=1#L58

Perhaps adding the context of which section should be emphasized or why it's important would clarify why that's useful in the context of OOP or moving it to another section in the curriculum. 

### Path

Ruby / Rails

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/ruby/object_oriented_programming_basics/object_oriented_programming.md?plain=1#L58

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks for reporting @fiveNinePlusR, we'll get this sorted.

**Comment by MidlifeMechanicus** [comment]
I'm on the Ruby course, and I don't understand why that link is there. It says it's a refresher, but surely we can go back and look at the TOP lesson on variables ourselves? I know I have revisited many TOP lessons during my studies. 

Are the reviewers happy for me to create a PR removing the link?

**Comment by KevinMulhern** [comment]
Oof, this one fell off my radar. I think removing it makes sense. I've assigned it to you, thanks @MidlifeMechanicus
