### ISSUE TITLE
Intermediate HTML and CSS Course: Introduction

### ISSUE THREAD

**Issue by julianaflima** [TheOdinProject/curriculum#25038]
### Describe your suggestion

The link to the CSS cheat sheet gives the following error message:
```
I got an error when visiting websitesetup.org/wp-content/uploads/2019/11/wsu-css-cheat-sheet-gdocs.pdf.
Error code: 1020
Ray ID: 78d492ee98183c0c
Country: IN
Data center: blr03
IP: 49.207.204.104
Timestamp: 2023-01-22 01:39:06 UTC
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by mraslann** [comment]
It is working fine for me.
You could ask in the TOP discord server for someone to send the pdf to you

**Comment by scheals** [comment]
Duplicate of 
https://github.com/TheOdinProject/curriculum/issues/24961
https://github.com/TheOdinProject/curriculum/pull/24995
https://github.com/TheOdinProject/curriculum/issues/24908

Use web archive/VPN to access the pdf.
