### ISSUE TITLE
Issue: Contributing page, Hall of Fame distorted images on safari

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25045]
### Describe your suggestion

There seems to be an issue in safari with the hall of fame images on the [page about Contributing](https://www.theodinproject.com/contributing) where they stretch. I have tried Google Chrome and the pictures display fine in there. 

Version of Safari I'm using: 16.2

Screenshot from safari:
![Screenshot 2023-01-23 at 14 31 52](https://user-images.githubusercontent.com/81025586/214055031-6db61cef-fa7d-47ce-8fef-e6df4634be18.png)

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/contributing

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

ManonL#7220

**Comment by edgar-carrillo** [comment]
I can jump on this one if no ones claimed it yet

**Comment by KevinMulhern** [comment]
Hey @ManonLef, thanks for reporting this 💪 

Sorry I didn't see it sooner, someone reported and picked it up in the site repo too: https://github.com/TheOdinProject/theodinproject/issues/3662
