### ISSUE TITLE
JS Objects & Object Constructors : assignment article insecure link 

### ISSUE THREAD

**Issue by lukejans** [TheOdinProject/curriculum#25075]
### Describe your suggestion

Assignment section on Objects And Object Constructors in the Node / JS  path.

the first assigned article [JavaScriptIsSexy’s article on the prototype](http://javascriptissexy.com/javascript-prototype-in-plain-detailed-language/) directs you to an insecure website therefore does not load the content. I see the only solution to work would be to update the curriculum as the website is broken and has nothing to do with the way it was linked in the html.

Thanks in advance and hope to see new content there soon!

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

jans#0009

### (Optional) Additional Comments

Though this is a small improvement to the curriculum, I'm excited to have my first contribution. 

I ❤️ The Odin Project

**Comment by lukejans** [comment]
I recently found this awesome objects & constructors guide while I was trying to outsource curriculum. This website should have a good shot at getting into the curriculum.

[JavaScript Objects Guide](https://www.programiz.com/javascript/object)
[1. JavaScript Objects](https://www.programiz.com/javascript/object)
[2. JavaScript Methods & this](https://www.programiz.com/javascript/methods)
[3. JavaScript Constructor](https://www.programiz.com/javascript/constructor-function)
[4. JavaScript Getter and Setter](https://www.programiz.com/javascript/getter-setter)
[5. JavaScript Prototype](https://www.programiz.com/javascript/prototype)

Hopefully this helps improve the Objects & Constructors Lesson!

**Comment by wise-king-sullyman** [comment]
Looks like the original reason for this issue was resolved in #25070

Do you think that the resources you mentioned in your second comment are something that should still either be added to the curriculum or replace one of our existing resources? If so can you outline what your suggested resources cover that our existing resources don't, or what things they do better?

**Comment by lukejans** [comment]
All looks good now! I believe the digital ocean article is sufficient replacement content. All good on this issue now!!
