### ISSUE TITLE
Foundations: Landing Page project instructs you to use a font style that does not exist

### ISSUE THREAD

**Issue by richfromm** [TheOdinProject/curriculum#25071]
### Describe your suggestion

The landing page project (https://www.theodinproject.com/lessons/foundations-landing-page) includes an image specifying colors and font styles to use (see https://cdn.statically.io/gh/TheOdinProject/curriculum/81a5d553f4073e593d23a6ab00d50eef8620796d/foundations/html_css/project/imgs/02.png).

Some of those font styles are specified as "extra-bold". According to https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#common_weight_name_mapping, this corresponds to a CSS `font-weight` of 800.

However, the Roboto font that the exercise instructs you to use (see https://fonts.google.com/specimen/Roboto#styles) does not have an 800 weight available. There's 700 (that it refers to as "Bold"), and 900 (which is referred to as "Black").

Empirically, if I use `bold`, I get `700`. But if I use `bolder`, I do **not** get `800`, I still get `700`. I have to explicitly use `900` (which, AFAICT, does not have a named equivalent `font-weight` value) to get something bolder than just `bold`.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-landing-page

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

dingdingwikki#5887

### (Optional) Additional Comments

Assuming there's no way to actually get a Roboto with font weight 800, it would reasonable to address this by instead using either 700 or 900 where 800 is currently specified. However, I don't think that the specifications are consistent with the example shown.

The colors and font styles specification instructs that 48px extra-bold be used for the Hero Main text ("this website is awesome"), and that 36px extra-bold be used for the information header text. But if you look at the example full design shown at https://cdn.statically.io/gh/TheOdinProject/curriculum/81a5d553f4073e593d23a6ab00d50eef8620796d/foundations/html_css/project/imgs/01.png , I'm pretty sure that it is currently showing just regular bold (700) for both "This website is awesome" and "Some random information". I can attach images illustrating this, comparing it to a web site with both 700 and 900, if that would be helpful. Perhaps this is b/c whatever code generated the example tried to use 800 (or `bolder`), but because that doesn't exist, it fell back to 700 (`bold`) instead?

Regardless, my point is that if you want to fix this by changing those instances to 900, you will also need to regenerate the example. So an alternate, and perhaps easier, solution would be to just change the specifications for both of these from "extra-bold" to "bold".

This issue was originally raised on Discord in #html-css-0 at https://discord.com/channels/505093832157691914/516751477306294273/1067169164529238059

**Comment by codyloyd** [comment]
the designs are _acutally_ using "Black", but I didn't want to use _that_ particular language on the design file because it would likely be confusing to beginners as it's also a color.

We weren't thinking of "extra-bold" as a very specific weight in this case.. though you ARE correct and that's somewhat misleading/confusing in this instance.

I think our best bet is to be specific about the font weight used here and not use the "descriptor" words.  

I've done that here: 
![landing page details](https://user-images.githubusercontent.com/18574792/233677417-c5060449-78d2-438b-8dd7-b17b4a0f2e1f.png)


do you want to do a PR to update it on the site?

**Comment by Eduardo06sp** [comment]
If someone decides to take this:
You need to download the updated image file (provided right above).

Then you will replace `foundations/html_css/project/imgs/02.png` with the updated one.

I think this should be all. Someone expressed interest in taking it on (from the Discord) so wanted to just drop this here.

**Comment by Rafael-Correzi** [comment]
I had this issue right now and talked to Eduardo on the discord server, can I do a PR on it?
