### ISSUE TITLE
JavaScript: Weather App, add API key to .gitignore to practice secuirty topics

### ISSUE THREAD

**Issue by TrshPuppy** [TheOdinProject/curriculum#25097]
### Describe your suggestion

The Weather App assignment could be used to foster a security mindset earlier in the curriculum. Students at this point in the curriculum know how to use JS modules and imports, as well as `.gitignore`. The API key can be stored as a variable in a module, and then imported to the code where needed. Then the module can be added to the `.gitignore`. 

This can help students start thinking about security related to API keys and other environment variables early. Plus, they'll be applying tools they have recently learned.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-weather-app

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Sella Turcica#1304 server nick: "Trash Puppy"

### (Optional) Additional Comments

Thank you for being a great resource! I have learned so much from going through your curriculum and I feel very well trained as a software engineer!

**Comment by wise-king-sullyman** [comment]
Thank you for taking the time to file this, but we feel that this isn't an ideal point in the curriculum to start discussing API key security in more depth than we currently do. We specifically chose this API key because it is free to avoid going into the topic here.
