### ISSUE TITLE
Improvement for Binary Search Tree project

### ISSUE THREAD

**Issue by LuvKatie** [TheOdinProject/curriculum#25095]
### Describe your suggestion

Had some suggestions for videos to help students visualize and understand the different traversal methods ( inorder, preorder, postorder ) for the BST project.

Personally found these videos to be super helpful in
1. Visualizing how the tree will work step by step
2. Understanding recursion at a deeper level coupled with the visuals of step 1.

I think these videos by ygongcode would be helpful additions

Inorder Video: https://www.youtube.com/watch?v=4_UDUj1j1KQ&t=1s&ab_channel=ygongcode

Postorder video: https://www.youtube.com/watch?v=4Xo-GtBiQN0&ab_channel=ygongcode

Pre-order video: https://www.youtube.com/watch?v=8xue-ZBlTKQ&ab_channel=ygongcode

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-binary-search-trees

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Hello KT#0001

**Comment by CouchofTomato** [comment]
Hey @LuvKatie 

Thanks for raising this issue and apologies for the delay in responding.

Is your intention to add these as additional resources in the lesson?

**Comment by LuvKatie** [comment]
Sorry I was not aware that I needed to respond to this! It's my first time doing something like this.

Yes I did mean for these resources to be placed in additional resources

**Comment by CouchofTomato** [comment]
> Sorry I was not aware that I needed to respond to this! It's my first time doing something like this.
> 
> Yes I did mean for these resources to be placed in additional resources

@LuvKatie Apologies again for the delay. The comments in those videos seem really positive. If you're happy to open a PR then we would most likely be happy to merge it if these are under additional resources.
