### ISSUE TITLE
NodeJS: Ubuntu 22.04 is now supported by mongodb

### ISSUE THREAD

**Issue by finestedm** [TheOdinProject/curriculum#25092]
### Describe your suggestion

According to [this thread](https://www.mongodb.com/community/forums/t/installing-mongodb-over-ubuntu-22-04/159931/83)  on official mongodb forum the problem with installing mongo on Ubuntu 22.04  has now been fixed in version 6.0.3~rc2 and later.

Therefore this part: 

> -- [Important Notice](https://www.theodinproject.com/lessons/nodejs-introduction-to-mongodb#important-notice)
> 
> Currently MongoDB is not available on Ubuntu 22.04 or its equivalent flavours. If you are using a 22.04-based distribution, keep this in mind when you get to the steps to installing MongoDB locally. There has been [work done](https://jira.mongodb.org/browse/SERVER-62300) by the MongoDB team, but it has not yet been released. This note will be removed or updated when there is further news on the availability for 22.04 distributions.

is not needed anymore.

I've installed version 6.0.4 without issues on Ubuntu 22.04.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-to-mongodb

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Pauler#6987

**Comment by kuromika** [comment]
If this is the case, I would like to work on this, but I think that we would also need to include these [commands](https://www.mongodb.com/community/forums/t/installing-mongodb-over-ubuntu-22-04/159931/90) for the installation? It doesn't seem to be an 'official release' either, is just people finding out that a newer version worked, so I don't know how reliable this approach would be.

**Comment by KevinMulhern** [comment]
Thanks for reporting @finestedm, this has been resolved: https://github.com/TheOdinProject/curriculum/pull/25227
