### ISSUE TITLE
Rails: Members Only: Update information about Turbo with Devise

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#25112]
### Describe your suggestion

Devise has officially launched version 4.9. The key change with this update is that Devise can now work with hotwire/turbo out-of-the-box. The note in the Members Only assignment regarding Devise's compatibility with Turbo should be updated to reflect this.

The only things learners need to do now are:
1. Install the [Responders gem](https://github.com/heartcombo/responders)
2. Specify delete requests on their links/buttons for logging out.

Additional info:
- Devise 4.9 changelog: [LINK](https://github.com/heartcombo/devise/blob/v4.9.0/CHANGELOG.md#490---2023-02-17)
- Devise update guide for turbo compatibility: [LINK](https://github.com/heartcombo/devise/wiki/How-To:-Upgrade-to-Devise-4.9.0-%5BHotwire-Turbo-integration%5D)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-members-only

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

josh#0729

**Comment by ChargrilledChook** [comment]
@JoshDevHub Great idea👌
