### ISSUE TITLE
Intermediate HTML and CSS: Mixed HTTP/HTTPS error in codepen example

### ISSUE THREAD

**Issue by johnspurr** [TheOdinProject/curriculum#25135]
### Describe your suggestion

[The first codepen example](https://codepen.io/TheOdinProjectExamples/pen/dyVRMbq) on the Form Basics lesson uses a form action to `http://httpbin.org/post`. Chrome blocks this request with the following error in the console:

> Mixed Content: The page at 'https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics' was loaded over HTTPS, but requested an insecure form action 'http://httpbin.org/post'. This request has been blocked; the content must be served over HTTPS.

Changing this link to use HTTPS fixes the problem locally.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

jrs#0093

**Comment by KevinMulhern** [comment]
Thanks for reporting @johnspurr, we've updated the example to use https.
