### ISSUE TITLE
Duplicate links

### ISSUE THREAD

**Issue by pugsiman** [TheOdinProject/curriculum#2513]
I noticed there are a couple of duplicates and inconsistencies in the student's solution section here:
http://www.theodinproject.com/ruby-programming/ruby-on-the-web
Some people show up twice and in inconsistent manner.

**Comment by kriox26** [comment]
@pugsiman Could point out the duplicates??

**Comment by kriox26** [comment]
@pugsiman Thanks

**Comment by pugsiman** [comment]
No problem. You accidentally closed my merge request by the way :-)
