### ISSUE TITLE
Ruby Course : Blocks : Capturing blocks : after the 2nd code snippet : 2nd paragraph 

### ISSUE THREAD

**Issue by haritak** [TheOdinProject/curriculum#25146]
### Describe your suggestion

Rephrase : 
(Yes, methods like #to_i can be passed around using symbols. ...

To:
(Yes, names of methods like ...

Looks minor but it got me stuck for some time.
Passing around a method, bring to mind something like  a Proc object (or reference to a Proc object) somewhere that we pass around.
However it seems to me that we just pass around the name of the method. 

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-blocks#capturing-blocks

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

Well done to everyone!

Incredible work!

Thank you * 1_000_000 !!!

--yannis

**Comment by CouchofTomato** [comment]
Hey @haritak 

Thanks for raising this issue. Seems like a reasonable change. Are you happy to make a PR for it?
