### ISSUE TITLE
Express and Mongoose : Mini Message Board project

### ISSUE THREAD

**Issue by Op-Pautu** [TheOdinProject/curriculum#25150]
### Describe your suggestion

In the project steps, heroku is still recommended. I was racking my brain trying to figure out how to do it, and later found out the free service is gone (and i couldnt sign up for some reason).

Change the order a bit might help. Show the deployment lesson before this project and a lot of headache on new students who will attempt to use heroku will be relieved. 

OR remove/change steps 12-14 on https://www.theodinproject.com/lessons/nodejs-mini-message-board. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-mini-message-board

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks for reporting @Op-Pautu, that was an oversight. We'll get an update out to resolve this.
