### ISSUE TITLE
NodeJS: Authentication Basics: mongoose v7.0.0 has dropped callback support for various functions including Model.save, Model.find and Model.delete etc.

### ISSUE THREAD

**Issue by luuu-xu** [TheOdinProject/curriculum#25151]
### Describe your suggestion

Update the code examples where mongoose functions with dropped callback support.

Mongoose recommends switching to async/await, or promises.

Probably should mention this mongoose update during the Express 101 - 105 lessons as well, since I am not sure whether MDN's tutorial would reflect this update soon enough.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-authentication-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

luuuxu

**Comment by luuu-xu** [comment]
Oh and also there is a mistake where leads the code not working:

passport.serializeUser(function(user, done) {
  done(null, user.id);
});

needs to be changed to:

passport.serializeUser(function(user, done) {
  done(null, user._id);
});

otherwise the deserializeUser function would not have the user object.

**Comment by KevinMulhern** [comment]
Thanks for reporting @luuu-xu. This should now be resolved: https://github.com/TheOdinProject/curriculum/pull/25189
