### ISSUE TITLE
<Foundation Course>: <Lesson: Setting Up Git>

### ISSUE THREAD

**Issue by Amrit57** [TheOdinProject/curriculum#25154]
###  Lesson"Setting Up Git" 

In this lesson content . "step 2.3: Create an SSH Key"
after you enter `ls ~/.ssh/id_ed25519.pub` in the terminal to see if you have an Ed25519 algorithm SSH key already installed. 

A screenshot of terminal window showing that you already have an Ed25519 algorithm SSH key already installed will help students understand better to jump to step 2.4, without creating a new SSH key.

As i went through the course, I was a complete beginner and when I was following the instruction to setup git, I was unable to understand `Step 2.3` and started creating a new Ed25519 algorithm SSH key which led me to a huge problem later.

-  I couldn't link my SSH key and clone my repository in my local machine and due to frustration I uninstalled git and deleted my github account and re-tried the whole git setup process again and then after i realized that my mistake was `I didn't know what an Ed25519 algorithm SSH key  looks like and created a New Ed25519 algorithm SSH key `
- So, adding a picture of terminal window which shows the Ed25519 algorithm SSH key, if you have already installed after entering the `ls ~/.ssh/id_ed25519.pub` will help student understand and jump to step 2.4 without creating a new SSH key.

I have attached the screenshot of the exact part where i made a mistake due to a lack of understanding.

At last a image of terminal window showing the output or New Ed25519 algorithm SSH key (if you have already installed) will help students to understand better.

![solve](https://user-images.githubusercontent.com/126244637/221837464-8b64c379-48a8-4acf-b05f-6b000fbe2730.png)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment]
Thanks for taking the time to file this, but at this time we don't feel that it's an often encountered enough problem to make a change here.
