### ISSUE TITLE
Full Stack Javascript, Final Project: LInks in the lesson should be updated.

### ISSUE THREAD

**Issue by crespire** [TheOdinProject/curriculum#25164]
### Describe your suggestion

The links here are very old, referencing Rails 5. We should find updated articles that provide similar content.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-javascript-final-project

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

crespire#8269

**Comment by sumitshinde-84** [comment]
@crespire  can you provide new and updated resources ?

**Comment by crespire** [comment]
> @crespire have you found any updated or new resources ? if yes provide it here ,i will update it .

I have opened a PR to close this issue.

**Comment by KevinMulhern** [comment]
Just assigning you to this one because of your PR @crespire, thanks for sorting this out mate 💪
