### ISSUE TITLE
Working example for Async/Await lesson

### ISSUE THREAD

**Issue by michaella23** [TheOdinProject/curriculum#25162]
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The first example in the Async and Await lesson is missing context and I would not be able to test this in my own IDE. The following variables/functions are undefined - `server` and `getPeople()`.  Can a new example be provided so that learners would be able to see what is returned from the `getPersonsInfo()` function?

**2. Acceptance Criteria:**

- [ ] Define `server` and `getPeople()` in a separate code block
   OR
- [ ] Provide a different working example of asynchronous code that interfaces with an actual server

**3. Additional Information:**

![Screen Shot 2023-02-08 at 7 48 26 AM](https://user-images.githubusercontent.com/89760083/217551401-776f06a3-1fad-4d28-872c-fe8d08b0cf95.png)

**Comment by wise-king-sullyman** [comment]
Thanks for submitting this, seems like a good idea to me.

**Comment by pantbruin** [comment]
I'd like to tackle this.

**Comment by pantbruin** [comment]
Submitted a PR last week, not sure if I also had to respond to this thread. Any feedback? Thanks!

**Comment by wise-king-sullyman** [comment]
Nope, you don't need to respond on an issue unless you have questions about it, and _generally_ communication will happen on PRs once a PR is open for an issue 🙂
