### ISSUE TITLE
<Ruby Course / Conditional Logic> : <LaunchSchool conditionals using || operator provides incorrect examples>

### ISSUE THREAD

**Issue by hmatts3** [TheOdinProject/curriculum#25160]
### Describe your suggestion

In the first assignment, in the True and False section, LaunchSchool incorrectly states the returned values from irb using the OR operator 

https://launchschool.com/books/ruby/read/flow_control#casestatement

See below. Josh has emailed launchschool for the correction. 

```
0 || "foo"
# Launch School says this is "foo"
# But it's 0 because 0 is truthy in ruby

"" || "foo"
# Launch School says this is "foo"
# But it's actually "", which is also truthy
```

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-conditional-logic

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

hmatt

**Comment by JoshDevHub** [comment]
They got my email about this and have fixed it! Here's a link to updated content: https://launchschool.com/books/ruby/read/flow_control#trueandfalse

Glad it could get fixed on their end. You can feel free to close this issue @hmatts3 (or any maintainer reading of course)

**Comment by KevinMulhern** [comment]
Great outcome, thanks so much for doing that @JoshDevHub 💪

**Comment by hmatts3** [comment]
Thanks, guys!
