### ISSUE TITLE
Intermediate HTML and CSS Course: Remove ignored `tr` selector from table codepen example

### ISSUE THREAD

**Issue by jvilders** [TheOdinProject/curriculum#25165]
### Describe your suggestion

The codepen example specifies a border for the `tr` element in its CSS, but this does not appear. This is because such a border is ignored if the `table` element's `border-collapse` property is specified as `separate`, which is the default value. Quoting the [CSS 2.1 spec for the separated borders model (the default)](https://www.w3.org/TR/CSS21/tables.html#separated-borders) (emphasis added):

> **Rows**, columns, row groups, and column groups cannot have borders (i.e., user agents must [ignore](https://www.w3.org/TR/CSS21/syndata.html#ignore) the border properties for those elements).

Unless the reader knows the specific factoid from the CSS spec I quoted, it's very confusing to see a codepen example where a border is specified for the table row element, yet no such border is shown. The text makes no mention of this apparent discrepancy either.

I believe it would be better to remove `tr` from the CSS selector and avoid such confusion for the reader.

I am not able to implement this change myself as the change would need to happen within the codepen example and this codepen example (like many others) is from the [@TheOdinProjectExamples codepen account](https://codepen.io/TheOdinProjectExamples), which I do not have access to.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-tables

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by codyloyd** [comment]
fixed!
