### ISSUE TITLE
Foundations Course, Understanding Errors: Broken links

### ISSUE THREAD

**Issue by VladVrt** [TheOdinProject/curriculum#25166]
### Describe your suggestion

Due to the fact that _https://cdn.statically.io/_ is down, the following links are broken:

- Reference Error Example
- Reference Error Stack Trace
- Syntax Error Example
- Type Error Example

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-understanding-errors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

𝖛𝖔𝖑𝖔𝖉𝖎𝖆#7045

**Comment by KevinMulhern** [comment]
Thanks for reporting @VladVrt, looks like it's back up again.
