### ISSUE TITLE
Fundamentals(?): JavaScript exercise 13 (caesar) isn't linked anywhere anymore

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#25172]
### Describe your suggestion

- The exercise [13_caesar](https://github.com/TheOdinProject/javascript-exercises/tree/main/13_caesar) does not appear to be linked anywhere within our current curriculum. A [github repo search](https://github.com/search?q=repo%3ATheOdinProject%2Fcurriculum%20caesar&type=code) turns up only references to a series of Ruby lessons on the topic, a testing lesson that doesn't use the exercise, and references to it in the archives, but no references to it seem to exist within the current live content

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Asarta#5596

**Comment by ManonLef** [comment]
Seems it got removed roughly 2 years ago :) [link to removal commit](https://github.com/TheOdinProject/curriculum/commit/af0283e5b38bcfbbe29a9bd01a4289aba10b92f4)

**Comment by CouchofTomato** [comment]
The problem is now a project for the Javascript testing section https://www.theodinproject.com/lessons/node-path-javascript-testing-practice
