### ISSUE TITLE
React: Update react introduction to have a link for the ReportWebVitals documentation

### ISSUE THREAD

**Issue by linkonsat** [TheOdinProject/curriculum#25199]
### Describe your suggestion

Currently, ReportWebVitals is mentioned in the handle inputs and render lists. However the link to this specific article is not present in the previous lessons. This would add the link and therefore avoid users being confused about where to find the ReportWebVitals documentation. Adding for example this line "You can also find the [ReportWebVitals here](https://create-react-app.dev/docs/measuring-performance/#:~:text=Web%20Vitals%E2%80%8B,calculated%2C%20refer%20to%20the%20documentation) to look at more aspects of your applications performance" could also work. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-react-introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by jakemadash** [comment]
Hello! I’m commenting so that this can be assigned I think? Let me know if anything else is needed.

**Comment by linkonsat** [comment]
@jakemadash Went ahead and assigned you. Thanks for doing this!

**Comment by KevinMulhern** [comment]
Hey @jakemadash, just checking in. Are you still working on this or would you like us to open it up for someone else to work on?

**Comment by jakemadash** [comment]
Hey Kevin,I believe this was handled on the below PR. Let me know if not!Update react_introduction.md to include information on ReportWebVitals by jakemadash · Pull Request #25204 · TheOdinProject/curriculumgithub.comThanks,JakeOn May 12, 2023, at 4:24 PM, Kevin Mulhern ***@***.***> wrote:﻿
Hey @jakemadash, just checking in. Are you still working on this or would you like us to open it up for someone else to work on?

**Comment by KevinMulhern** [comment]
ahh gotcha, sorry for the confusion and many thanks for taking care of this @linkonsat
