### ISSUE TITLE
NodeJS / Javascript course: Reconsider or double check following along with the firebase video

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25207]
### Describe your suggestion

# Suggestion 
Reconsider or double check te assignment of watching and **following** along with the fireship video. 
It would be nice if someone else that has more experience with webpack could try following along with the video  to confirm my findings. 

assignment 1: Watch and follow along with [Fireship’s Module Bundlers Explained video](https://www.youtube.com/watch?v=5IG4UmULyoA) to get a great overview and some hands on experience with webpack.

## The problem 

I've been trying to follow along with the video above. 
I ran into several issues that I don't think are entirely my user error. 

Setup: Mac(M2) and recent installs according to curriculum
Issues I ran into:
## 1. sass-loader issue
- video starts this section [here](https://youtu.be/5IG4UmULyoA?t=369)
- I ran the command `npm install --save-dev css-loader style-loader sass-loader` as shown in the video
- received below error after `npm run build`
> ERROR in ./src/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/style.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Cannot find module 'sass'
- I managed to get rid of the error by separately installing the sass-loader with `npm install sass-loader sass webpack --save-dev   `
- It also throws another less intimidating error after the above fix which is because the creator of the video has used `$color` instead of `$text` in the `style.scss` file
- >ERROR in ./src/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/style.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
after fixing the scss file it will compile without errors.

## 2. webpack dev server outdated information (?)
- video section starts [here](https://youtu.be/5IG4UmULyoA?t=478)
- The video will tell you to add this to your webpack config file:
```
devServer: {
    contentBase: path.join(__dirname, "public"),
    port: 9000
  },
```
- after googling, I managed to find that `static` has to be used since web-dev 4 I believe 
- Correct code to add:
```
devServer: {
    static: {
      directory: path.join(__dirname, 'public'),
    },
    compress: true,
    port: 9000,
  },
```

I'm aware I'm a beginner with webpack and some of this might be my own user error, but the searching online made me quite confident about the above.

I believe the errors might provide a negative learning experience for users quite new to Webpack. I have seen someone in discord talking about quitting the video for receiving errors they couldn't grasp.

## Alternative suggestions for this video:
- add notes on the video discrepancies
- remove the part about 'following along` with the video
- add the video to additional resources instead

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-webpack

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Manon

**Comment by KevinMulhern** [comment]
Thanks for the detailed right up @ManonLef. This is my bad, I remember merging that one.
I agree with your findings and I think watching without following along just to get a general overview sounds great.

Would you like to be assigned to this one?

**Comment by ManonLef** [comment]
Hi @KevinMulhern !

Yes, I’d like to be assigned. Would you like to still keep this in step 1 as a video to get a general overview?

**Comment by ManonLef** [comment]
I will decide when I've covered everything thoroughly then, since that will give me a better idea if this video adds something as an intro, recap or additional resource.

**Comment by xandora** [comment]
This is something that's been on my mind recently as well. The video really *shouldn't* be the first stepping in point for Webpack. They have a *realllllly* great tutorial walkthrough in their documentation already, and video tutorials don't often update for new features (or ever).

Here's a PR that supports the idea the video isn't suitable: #25153

**Comment by ManonLef** [comment]
@xandora what would you suggest we do with this video?

I currently don’t feel it adds anything the docs don’t cover, but haven’t finished all the assignment steps yet.

**Comment by xandora** [comment]
> @xandora what would you suggest we do with this video?
> 
> I currently don’t feel it adds anything the docs don’t cover, but haven’t finished all the assignment steps yet.

We should drop people in here: https://webpack.js.org/guides/getting-started/ and tell them where they can probably stop at Output Management.

![image](https://user-images.githubusercontent.com/2021268/225099268-1d8b34a0-bfe2-47ae-b838-51dda9fcd299.png)

**Comment by ManonLef** [comment]
@xandora I had a similar idea. It doesn’t help that in the previous lesson we start there, at the end of that previous lesson, we have to edit those files through some TOP guiding, and then in this lesson we pick back up in the webpack docs but now our files are edited by TOP input. 

I’ll try piecing things together comprehensively and propose my suggested changes here.

**Comment by xandora** [comment]
We have 3 lessons that start people off with Webpack?! That seems excessive... 😂

**Comment by ManonLef** [comment]
Everything from the video (and more) is covered in the webpack guides. I don't see any added value currently from the video and think it's safe to say it can be removed.

I do think there should be some decisions made regarding the wording in the assignment section. 
> 2. go through... to see

> 3. read through... 

> 5. You don’t need to **do** the rest of the webpack tutorials at this time

The wording doesn't make it clear enough in my opinion that it's actually expected of you to **do** the tutorials as step 5 suggests.

Then we also have the previous lesson I've mentioned that isn't entirely clear on the wording but makes it seem like you are expected to edit the file you've coded along with from the first lesson in the web pack tutorial.

I'm willing to make more changes than simply removing the first link if you agree the above could use some clearing up.

Would anyone be willing to look at this with me and decide on:
- are we expected to follow along with the tutorial (if yes make that more clear in every step)
- does the previous lesson need editing to make sure we don't edit the web pack tutorial file if the above is answered with a yes?

**Comment by ManonLef** [comment]
Since it's set to triage/discussion I'm not entirely sure right now if submitting a PR is the correct way to proceed. 

If you're all okay with it, I would like to move forward and work on these steps now:

1) remove the firebase video
2) reword the assignment section to make it obvious it's expected of students to **code along**. 

I have gone through all webpack guide links while coding along and can vouch for that being very valuable. It truly brings out the power of repetition and practice before using it in the upcoming project(s). 

I think the video needs to go sooner rather than later for it will undoubtedly raise errors if students code along as told.

**Comment by ManonLef** [comment]
okay, I will limit it to the link then. 

But perhaps you can all decide on the wording (code along/not code along) when you're ready for I'm ready to move on to that one straight after this if you are.
