### ISSUE TITLE
Intermediate HTML and CSS Course: LInk this video in the additional resource section

### ISSUE THREAD

**Issue by zubairatif** [TheOdinProject/curriculum#25220]
### Describe your suggestion

This 6-minute [Video](https://www.youtube.com/watch?v=N5wpD9Ov_To) by Kevin Powell gives some advice on which units should be used I specific situations.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-css-units

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

zubairatif#5323

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @zubairatif, can we add this as an additional resource please?

Would you like to be assigned?

**Comment by sumitshinde-84** [comment]
I would like to work on this issue

**Comment by KevinMulhern** [comment]
Would you still like to do this one @sumitshinde-84?

**Comment by sumitshinde-84** [comment]
Yes offcourse,  I would like to work on this issue.

> Would you still like to do this one @sumitshinde-84?

**Comment by KevinMulhern** [comment]
It's all yours 💪
