### ISSUE TITLE
Intermediate HTML and CSS Course : Confusing definition of Grid cells

### ISSUE THREAD

**Issue by joaojgabriel** [TheOdinProject/curriculum#25255]
### Describe your suggestion

There are two issues with how grid cells are defined in the Cells section:

1. "Cells are the smallest unit of measurement in a grid"  and "You can think of grid cells like [...] a square on a graph" both encourage thinking of cells in terms of size and
2. "the element we marked with the letter “A” is a cell _between row grid lines 1 and 2 and column grid lines 1 and 2_. The element with the letter “H” is a cell _between row grid lines 3 and 4 and column grid lines 2 and 3_" asks the reader to hold more information in their mind than necessary

Both of these issues could be solved by defining cells in terms of row and column tracks. 

Something like "The space shared by a single row track and a single column track is called a grid _cell_ " would address the first. And "the element marked with the letter "A" is occupying a cell that lies in row track 1 (between row grid lines 1 and 2) and column track 1 (i.e. between column grid lines 1 and 2). The item marked with the letter "H" is in a cell at row track 3 (between row grid lines 3 and 4) and column track 2 (between column grid lines 2 and 3)" might practically be more verbose, but providing the abstraction of numbered tracks, and putting the grid lines in parentheses, makes it more legible/comprehensible.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-positioning-grid-elements#cells

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

joaojgabriel#2173

**Comment by sumitshinde-84** [comment]
@KevinMulhern I would like to work on it .
Need more info

**Comment by KevinMulhern** [comment]
We need to triage and decide on the next action for this first @sumitshinde-84 

But @joaojgabriel will be getting first dibs, they indicated they'd like work on this:

<img width="854" alt="Screenshot 2023-03-25 at 16 02 20" src="https://user-images.githubusercontent.com/7963776/227728454-9b9e0cc8-5c64-44cc-a606-c6b514f26823.png">

**Comment by joaojgabriel** [comment]
If more clarification is needed during triage, just let me know, @KevinMulhern

**Comment by codyloyd** [comment]
This seems like something worth working on.  I say @sumitshinde-84 can work on it... but try to keep the changes relatively minimal.

good thinking @joaojgabriel

**Comment by joaojgabriel** [comment]
There's been a misunderstanding on the content of your PR, but I appreciate the excitement in closing the issue @sumitshinde-84. @KevinMulhern or @codyloyd haven't yet updated the status from "Needs triage" or assigned anyone to resolve the issue, so I'm not positive if it still needs more discussion. If you guys decide on giving a green light, you can assign me to the task; I'll try to keep the changes straightforward and minimal, and we can agree on the details if you want to discuss on discord. As @codyloyd said, it _is_ something worth working on. Making sure to understand cells as an abstraction of column and row tracks, and not one of space, is crucial to grasp the concept of dynamic grid tracks and to detach from the idea that spanning tracks linearly correlates with occupying space in the screen.

**Comment by codyloyd** [comment]
@joaojgabriel go a head and do it.  I misread your original post and missed that you were proposing that YOU wanted to do the work all along.

so sorry about that!  Feel free to go ahead and make the changes you see fit to make.

**Comment by joaojgabriel** [comment]
Thanks for the guidance, @codyloyd. I didn't stick to my promise of keeping it minimal (sorry), but I'm confident that all the proposed changes add some value to students
