### ISSUE TITLE
React: CRA officially dead, suggestions based on the new React documentation

### ISSUE THREAD

**Issue by JuanGuerrero09** [TheOdinProject/curriculum#25253]
### Describe your suggestion

Hey, as some of you may know, React finally updated their documentation, among the most important features is that [create-react-app officially disappeared](https://react.dev/learn/start-a-new-react-project), now in case you want to use React for a web application they recommend using frameworks (which I consider out of the scope of the course, although it is a door that should be left open), or if you still want to use React without a framework they recommend Vite (my favorite alternative) or Parcel.
I want to suggest firstly the change in the [React introduction](https://www.theodinproject.com/lessons/node-path-javascript-react-introduction) remove CRA and suggest Vite.
In addition, I also see the need to update the links to the new documentation, and, although I don't know if it has been previously suggested, update the React course to one that focuses more on functional components than on class based components, because the latter have also been removed from the new documentation.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-react-introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

JuanGuerrero09

### (Optional) Additional Comments

Sorry if I make any mistakes here, it's my first time contributing to top, but I would like to contribute to give back what I learned when I started 8 months ago.

**Comment by wise-king-sullyman** [comment]
Hey @JuanGuerrero09, the maintainer team agrees that we want to replace CRA but is currently in discussion about what we want to replace it with.

**Comment by codyloyd** [comment]
I'm going to go ahead and close this issue.. the detailed discussion on this topic is happening elsewhere.

Thanks for bringing it up!
