### ISSUE TITLE
Foundations: Javascript Fundamentals Part 2: Broken Link to Exercise 3

### ISSUE THREAD

**Issue by JohnMarquardt** [TheOdinProject/curriculum#25264]
### Describe your suggestion

The link to the 3rd exercise in the "Assignment" section of Javascript Fundamentals Part 2 is broken.
It currently points to: https://replit.com/@I3uckwheat/lets-do-some-math#math.js

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-2

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Lamasa_Pace #9803

### (Optional) Additional Comments

Thank you for all your work!

**Comment by I3uckwheat** [comment]
Thanks for reporting, it got deleted somehow. I have restored the file and will investigate why this happened.
