### ISSUE TITLE
Fundamentals Part 2: Broken bulletpoint format

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#25269]
### Describe your suggestion

Currently in the assignment, the formatting for the bullet points is incorrect. It should show as a bullet list with sub-bullets indented. More like the below:

* Assignment 1
  * comment on assignment
* Assignment 2
  * comment on assignment 2

The issue area is outlined in the screenshot below:
![image](https://user-images.githubusercontent.com/4411701/227662966-65c3c64f-d76f-4190-934c-1d89f28b917f.png)

Use the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it's formatted correctly.

Reference: [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-2

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

BriggsE#9104

**Comment by ssolunna** [comment]
I would like to work on this issue.

**Comment by KevinMulhern** [comment]
Thanks for helping out @ssolunna, it's been assigned to you.

**Comment by sumitshinde-84** [comment]
If ssolunna  not working on it let me know kevin sir .
