### ISSUE TITLE
Ruby: Missing links for Time and Space complexity lessons in README.md

### ISSUE THREAD

**Issue by ssolunna** [TheOdinProject/curriculum#25271]
### Describe your suggestion

The following lessons don't seem to have a link in the README.md of curriculum/ruby/:
- A Bit of Computer Science:
  - Time Complexity
  - Space Complexity

### Path

Ruby / Rails

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/ruby/README.md

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by sumitshinde-84** [comment]
Hey i have fix this issue check PR #25272

**Comment by KevinMulhern** [comment]
@sumitshinde-84 thanks for contributing, but the ssolunna expressed they wanted to work on this themselves. Please don't pick up issues you haven't been assigned to.

**Comment by sumitshinde-84** [comment]
ok
