### ISSUE TITLE
JavaScript: Linking the new React docs

### ISSUE THREAD

**Issue by yousefelassal** [TheOdinProject/curriculum#25282]
### Describe your suggestion

The reading assignments throughout the React section are linked to the old documentation: ([legacy reactjs](https://legacy.reactjs.org))

<img width="582" alt="old react docs" src="https://user-images.githubusercontent.com/76617202/227775375-8f689ce5-10e4-42b8-922b-301b801ee89d.PNG">

Wouldn't it be better to link the new documentation? ([react.dev](https://react.dev))

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-react-introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by abhikrni** [comment]
I would like to work on this if no one is yet

**Comment by LeoKirasic** [comment]
@abhikrni Looks like the OP checked that they'd like to work on the issue themselves, so I'm gonna be assigning that to them. Thank you for the interest though, feel free to check out any other open issues that you'd like to work on!

@yousefelassal I'm gonna assign this one to you!

**Comment by CouchofTomato** [comment]
@yousefelassal Just checking you would still like to work on this?

**Comment by yousefelassal** [comment]
@CouchofTomato Sure! If there is any further work you would like me to do I would love to.
