### ISSUE TITLE
Foundation: Flexbox growing and shrinking: Incorrect information in an assignment.

### ISSUE THREAD

**Issue by JDl337** [TheOdinProject/curriculum#25300]
### Describe your suggestion

In [this assignment article](https://css-tricks.com/understanding-flex-grow-flex-shrink-and-flex-basis/), the flex-shrink is explained as:

> flex-shrink tells the browser what the minimum size of an element should be. The default value is 1, which is saying, “Take up the same amount of space at all times.”

And the author gives a metaphor for expanding the flex shorthand:

```
/* This is just how I think about the rule above in my head */

.child {
  flex: [flex-grow] [flex-shrink] [flex-basis];
}

/* or... */

.child {
  flex: [max] [min] [ideal size];
}
```

flex-grow being "max" and flex-shrink being the minimum size of an element are wrong. see [w3 spec](https://www.w3.org/TR/css-flexbox-1/#flex-property).

I suggest removing this assignment as I believe the other assignments and the lesson itself do a good enough job of describing what each property does.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-growing-and-shrinking

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/intermediate-html-css Can someone take a look at this please.

**Comment by codyloyd** [comment]
I agree with the above assessment.  this article can be removed. @JDl337 do you want to do the work?

**Comment by JDl337** [comment]
Sure, I'll do it.

**Comment by CouchofTomato** [comment]
@JDl337 All yours
