### ISSUE TITLE
Ruby on Rails Asset Pipeline Lesson: Update content about JavaScript, Webpack, and Rails 6

### ISSUE THREAD

**Issue by xsherryhe** [TheOdinProject/curriculum#25334]
### Describe your suggestion

There is quite a bit of content in the Asset Pipeline lesson that refers to bundling JS through Webpack in Rails 6 as the "newest" convention. For example, one of the paragraphs says:

> It used to be that the Asset Pipeline handled all assets but since the inclusion of Webpack and the webpacker gem to give Webpack some Rails type conventions, it is now better practice to handle JavaScript assets through there. Webpacker now comes as standard in Rails 6 applications.

This is outdated, since the actual newest convention at this point is to use import maps in Rails 7 for JS. 

This was something I noticed when fixing a different part of this same lesson to reflect the latest in Rails 7. I'd like to continue updating this lesson by fixing the parts of the lesson that refer to Webpack/Rails 6 and replacing them with import maps/Rails 7. This will help prevent learners from being confused, since the next lesson immediately after the Asset Pipeline lesson jumps straight into import maps.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-the-asset-pipeline

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

xsherryhe

**Comment by KevinMulhern** [comment]
Great catch! @xsherryhe, the fix sounds good to me.
