### ISSUE TITLE
A Deeper Look At Git JavaScript Course:  Provide example or expand upon when it would be appropriate to use `git reset --soft`

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/curriculum#25330]
### Describe your suggestion

`What would be an example of where we want to move the HEAD but not touch the staging area --- from this paragraph in https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

> Now let’s say we want to move where HEAD points to but don’t want to touch the staging area. If we want to leave the index alone, you can use git reset --soft. This would only perform the first part of git reset where the HEAD is moved to point somewhere else.

I found this from Eduardo06sp git-help which links to this SO question

> "also, there's a much more elaborate answer for using git reset,
> my answer was very ominous so I think it's best you're informed as to what it's really doing:
> https://stackoverflow.com/questions/3528245/whats-the-difference-between-git-reset-mixed-soft-and-hard
> (the accepted answer is amazing)

I'm just not seeing why we care / what are the benefits of leaving the index alone on a reset.  

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Wave#4186

**Comment by roy9495** [comment]
Can I contribute towards resolving this issue?

**Comment by roy9495** [comment]
Can I get assigned?

**Comment by KevinMulhern** [comment]
Hey @roy9495, good question. I'll have a deeper look into this one and get back to you.

**Comment by roy9495** [comment]
Hi @KevinMulhern, any updates? 
Thank you

**Comment by KevinMulhern** [comment]
Sorry for the delay @JustWaveThings, it's been a busy week. I've left feedback on that PR.

**Comment by roy9495** [comment]
@KevinMulhern Please don't apologise I know you guys are very busy.
