### ISSUE TITLE
HTML Foundations > Links and Images > Invalid Assignment Link

### ISSUE THREAD

**Issue by kylegitsit** [TheOdinProject/curriculum#25352]
### Describe your suggestion

The website "internetingishard.com" is used multiple times in this lesson. It is in the "Assignment" section, the "Knowledge Check" section, and the "Additional Resources" section. When trying to utilize any link from this lesson to that website, I end up with:
![internetingishard_1_2023-04-12](https://user-images.githubusercontent.com/128748629/231579688-b196bee8-098a-48e3-8f81-ebb04466ee1f.jpg)

Unsure of whether this is simply a firewall issue (I don't run any additional security software, so I'm just protected by base Windows security and base Google Chrome security), I checked the security setting for this website in particular. I allowed the following, against my better judgement, as I don't think websites should be used that require students to remove their security for the website,
![internetingishard_2_2023-04-12](https://user-images.githubusercontent.com/128748629/231581265-f9fe272a-9392-4ccd-ae04-f039f8edd9de.jpg)
 but after allowing this and reloading, nothing changed and I still got the same error page.

FYI, I did also google "internetingishard.com" and the same without .com at the end, and it does not change anything, as even taking the link through google will give me the same error.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
The website also didn't work for me. 

I have googled for some alternative lesson options that seem good alternatives at first glance. I haven't looked into the fine details of them yet.

 - this one seems to have some nice extra info on file formats and vector vs raster: https://designpowers.com/blog/image-file-formats 
 - this one is seemingly more technical and goes more into filesize management (less focus on vector pros): https://web.dev/choose-the-right-image-format/
 - this is a more general-purpose filetype explanation including the designer's target market which makes it probably less suitable but the info seems good at first glance. It may need an extra section written as an introduction on which files we will most commonly use for the web. https://99designs.com/blog/tips/image-file-types/ 
 
 [The MDN docs have a section as well but they focus on a lot more filetypes than probably needed at this point](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types)

**Comment by jztang** [comment]
Looks like their domain name has expired.

![expired](https://user-images.githubusercontent.com/12689662/231587618-719dbb41-dce3-4c7e-a295-005744b9b5e3.png)

However, the website also seems to be hosted on Netlify which is working at this link: https://internetingishard.netlify.app/
