### ISSUE TITLE
Foundation course: Invalid link in Additional Resources section

### ISSUE THREAD

**Issue by SachinHatikankar100** [TheOdinProject/curriculum#25359]
### Describe your suggestion

When I was going through the "Additional Resources" section of the page "https://www.theodinproject.com/lessons/foundations-links-and-images#additional-resources" 

I found the link [Interneting is hard’s treatment on HTML links and images](https://www.internetingishard.com/html-and-css/links-and-images/) not loading.

Analysis: Manually checked if the page is available. Unfortunately, the site "https://www.internetingishard.com" itself is not reachable

Possible workaround: I have a suggestion to update the link with MDN web docs URL with URL as "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img" and "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link" unless the Odin team has a better resource to add.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images#additional-resources

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

Would love to contribute on this issue :)

**Comment by SachinHatikankar100** [comment]
While working on this issue. I realized the issue was already raised and a pull request with a fix has already been submitted. Apologies for raising a duplicate issue.

**Comment by KevinMulhern** [comment]
Thanks for reporting @SachinHatikankar100
