### ISSUE TITLE
Javascript Course: Using BaaS For Your Back End lesson - Improve resources

### ISSUE THREAD

**Issue by ev0clu** [TheOdinProject/curriculum#25373]
I have a suggestion to the following: Full stack javascript path -> Javascript course -> Using BaaS For Your Back End lesson.

I think the caution in step 3 under Assignment does not useful. Since Firebase uses SDK version 9 we can use 'import' which is also mentioned by the Firebase docs. So the following note does not add any benefits and I think it should be replaced:

_Caution: If you’re not going to be hosting your app on Firebase Hosting, but prefer to leave it where it is (e.g. on GitHub Pages), take a closer look at the section below Step 3, there should be a link, which directs you to the “Available Libraries” page. Then, use what you learned in the codelab to make your own app actually interact with Firebase._

However, an important reference is missing, if someone want to use github for hosting a project, than he/she needs to add the github page link under the Firebase Authentication domain as the following stackoverflow answer describe it: https://stackoverflow.com/a/50799016

****Summarize, my proposal is to replace the Caution in Step3 to the following:**
 _Caution: If you’re not going to be hosting your app on Firebase Hosting, but prefer to leave it where it is (e.g. on GitHub Pages), take a closer look at the [stackoverflow answer](https://stackoverflow.com/a/50799016) to add your github page into Firebase authentication domains . Then, use what you learned in the codelab to make your own app actually interact with Firebase_

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-baas-for-your-back-end

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

ev0

### (Optional) Additional Comments

I am happy to work on this issue to practice the contribution, but I would like to ask support for this.

**Comment by LeoKirasic** [comment]
@ev0clu Thank you for creating the issue, I also agree that it would be good to add switch up the note. I'm going to assign this issue to you. 

P.S. you mentioned that you would like support with this issue. Is there anything I can do to make it easier for you to work on this?

**Comment by ev0clu** [comment]
I created a PR: https://github.com/TheOdinProject/curriculum/pull/25378. However, I found a type so I added a second commit under the same feature branch. I got an error when I tried to add a new PR with the previously used feature branch. I am not sure in this case the second commit is part of the first PR or not (I created the PR, than created the second commit).  I also realized my prettier has made some format update, which was not my goal. Could you check the PR please and give me feedback?

**Comment by ev0clu** [comment]
> The format update actually fixed the document so it follows the current style guide.

Thank you to double check it. I am glad to have chance to support TOP :) Sure you can close it.
