### ISSUE TITLE
Foundations: Outdated information in the "Text Editors" lesson, specifcally "VSCode Installation"

### ISSUE THREAD

**Issue by zachz529** [TheOdinProject/curriculum#25380]
### Describe your suggestion

TOP's [VSCode installation instructions for Linux](https://www.theodinproject.com/lessons/foundations-text-editors#vscode-installation) lists these two steps:
> 1. `wget -O code-latest.deb 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'`
> 2. `sudo apt install ./code-latest.deb`

After those steps (and steps 3/4, which aren't related to this issue), there is a paragraph about "Alternative Installation", which states:
> More advanced users might want to **install VSCode using the built-in apt package manager**. This allows **VSCode to be kept up to date automatically**. Instructions on how to set this up can be found on this [webpage](https://code.visualstudio.com/docs/setup/linux).

The linked [webpage](https://code.visualstudio.com/docs/setup/linux) states:
> The easiest way to install Visual Studio Code for Debian/Ubuntu based distributions is to download and install the .deb package (64-bit)

The webpage states that one way to do this is to:
> 1. Download the .deb file by clicking their provided link. 
> 2. `sudo apt install ./<file>.deb`. 

(There is another way mentioned on the webpage, but the results are equivalent)

After these instructions, the webpage states:
> Installing the .deb package will **automatically** install the apt repository and signing key to **enable auto-updating using the system's package manager**. 

The webpage/TOP provided installation instructions seem equivalent, but claim contradictory things about using the package manager and auto-updating VSCode.

Proof for equivalency (can skip if you understand):
> Step 1 of both instructions downloads the file ( `wget` vs browser download shouldn't matter)

> Step 2 of both instructions installs the file with the same command. 

> The links in the instructions are also the same, The following images show the network tabs when visiting the two provided links. The first is the link in TOP instructions. The second is the link in the webpage instructions. While the provided URLs are different, they end with the same URL/file.
![image](https://user-images.githubusercontent.com/94338660/232964971-d504d1aa-ef88-4b4e-a46f-08a3500ece07.png)
![image](https://user-images.githubusercontent.com/94338660/232964976-90e4b88d-2cd6-495d-ada5-e175f42ef553.png)

I brought this issue up on the TOP discord and it seems possible that the "Alternative Installation" portion is likely out of date. That message is [here](https://discord.com/channels/505093832157691914/690588805648089169/1098090535773798503).

Assuming this is all correct, I think the next steps would be to:
1. Correct TOP's claims that the install won't use the package manager or update VSCode automatically.
2. Remove the "Alternative Installation" portion, unless it serves a purpose I'm unaware of.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-text-editors#vscode-installation

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

PoggleTheGreater#0117

**Comment by wise-king-sullyman** [comment]
@xandora are you in favor of the proposed solution here?

**Comment by xandora** [comment]
@wise-king-sullyman Yep.

**Comment by wise-king-sullyman** [comment]
👍 thanks!

**Comment by zachz529** [comment]
Made the pull request. The first "next step" (correcting TOP's claim) didn't need to be done since the "Advanced Installation" portion is being entirely removed. Not sure how I didn't catch that when writing this.

Also this is my first time opening an issue and making a pull request, so if you have any feedback about them (length, formatting, too much/little provided context, etc) I'd love to hear it.

**Comment by wise-king-sullyman** [comment]
@zachz529 your issue and PR both looked great to me. Thanks for your contribution!
