### ISSUE TITLE
Express 104: MDN no longer uses/mentions async module in tutorial

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#25398]
### Describe your suggestion

MDN has changed their lessons to remove mentions and usage of the ` async` module in their express tutorial (see https://github.com/mdn/content/pull/25899 ), so Knowledge check section now references questions which are no longer relevant. While I think these can be simply removed, I'm not sure if an extra set of question about normal async should come in their place or not.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-express-104-view-templates#knowledge-check

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Asarta#5596

**Comment by wise-king-sullyman** [comment]
Seems like a change is needed here to me. Thanks for catching it!

Regarding if we should replace the checks rather than remove them I'm not sure since we already have async/await covered in a previous lesson. I'd love to get some more opinions from @TheOdinProject/javascript

**Comment by wise-king-sullyman** [comment]
👍 that makes sense to me @Asartea, do you still plan to put up a PR removing the knowledge checks?
