### ISSUE TITLE
Full Stack Javascript: Within the Project: Weather App, Remind the User of Throttling

### ISSUE THREAD

**Issue by GabeEss** [TheOdinProject/curriculum#25397]
### Describe your suggestion

When I was building the Weather App, I implemented the optional loading feature, but I barely noticed it until I remembered to test for low-end devices in the browser. Might be nice to just add in a few words in brackets reminding the user to test for that.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-weather-app

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

gabe#9464

**Comment by wise-king-sullyman** [comment]
Seems like a good idea to me.
