### ISSUE TITLE
JavaScript Course: Remove rogue HTML tags in the backend lesson

### ISSUE THREAD

**Issue by creme332** [TheOdinProject/curriculum#25391]
### Describe your suggestion

![image](https://user-images.githubusercontent.com/65414576/234309958-0a71a97f-48d6-4001-b185-7ecd5658ff91.png)

In the assignment section of `Using BaaS For Your Backend` lesson, there are some issues when rendering the markdown in html.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-baas-for-your-back-end

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks for reporting @creme332, this should be fixed now.
