### ISSUE TITLE
Fundamentals Part 2 (Exercises) Wrong text in Replit

### ISSUE THREAD

**Issue by JavierDev98** [TheOdinProject/curriculum#25403]
### Describe your suggestion

From exercises 1 through 3. In Replit, change the text when you successfully complete the exercise from "Congrats! You've solved them all, you may move onto the next lesson" to "Congrats! You've solved them all, you may move onto the next exercise".
Here are the links to the exercises that should be revised:
https://replit.com/@OdinProject/troubleshooting#troubleshooting.js
https://replit.com/@OdinProject/enter-a-number#script.js
https://replit.com/@OdinProject/lets-do-some-math#math.js

### Path

Foundations

### Lesson Url
https://www.theodinproject.com/lessons/foundations-fundamentals-part-2

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments
This little problem could lead some people to skip the exercises and go to the next lesson instead of the next exercise.

**Comment by wise-king-sullyman** [comment]
@JavierDev98 thanks for catching this!

I think we will need someone on the team with access to the replit account to address it.

**Comment by wise-king-sullyman** [comment]
Addressed. Thanks for reporting!
