### ISSUE TITLE
Full-stack JS: ES6 Modules - Global Scope Clarification

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#25405]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

-  [Lesson](https://www.theodinproject.com/lessons/node-path-javascript-es6-modules)
- In this section under ES6 modules, I would like to add clarification on how global scope works with the import/export feature.
- I have seen a number of people (including myself) ask if they should be worried about global-scope when learning about ES6 modules (more specifically in restaurant page / To-Do list). I think this stems from a high-focus on minimizing global scope in tic-tac-toe, the project before learning about this. I propose just a simple change to this paragraph.
> There are also the same benefits as when using factory functions or the module pattern (the module pattern and ES6 modules are not the same things; this naming convention is frustrating). With the introduction of ES6 Modules, the module pattern (IIFEs) is not needed anymore, though you might still encounter them in the wild. By using ES6 modules, you can keep different parts of your code cleanly separated, which makes writing and maintaining your code much easier and less error-prone. Keep in mind that you can definitely export constructors, classes and factory functions from your modules.
- I propose: 
> There are also the same benefits as when using factory functions or the module pattern (the module pattern and ES6 modules are not the same things; this naming convention is frustrating). With the introduction of ES6 Modules, the module pattern (IIFEs) is not needed anymore, though you might still encounter them in the wild. _ES6 Modules essentially get rid of global scope, and in each module only what is exported can be accessed in others by importing._ By using ES6 modules, you can keep different parts of your code cleanly separated, which makes writing and maintaining your code much easier and less error-prone. Keep in mind that you can definitely export constructors, classes and factory functions from your modules.

**2. Acceptance Criteria:**

- [ ] Approved additional line to add a lot of clarification to the user
- [ ] Possible further addition to the subject / change how sentence is written

**3. Additional Information:**

- This is something I have seen many confused with, and I think more clarification can help. I have seen many people go into To-Do list using IIFE's for everything to "avoid" global scope despite using ES6 modules.

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look at this please.

**Comment by wise-king-sullyman** [comment]
I could see the benefit of this. I would maybe avoid saying that they "get rid of global scope" but we can refine it at PR time as needed.
