### ISSUE TITLE
JavaScript: A Deeper Look at Git :  Move Assignment items into Assignment section

### ISSUE THREAD

**Issue by SimoneSalzano** [TheOdinProject/curriculum#25413]
### Describe your suggestion

Assignment item 3 and assignment item 4 are placed outside of the assignment section, as you can see in the screen below: 

![image](https://user-images.githubusercontent.com/78798707/235683260-84026c62-7c64-418f-a193-7cc85f041aeb.png)

This also causes the items to have index 1 and 2 instead of 3 and 4. Moving the items in the Assignment section will give them the right index.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Thanks @SimoneSalzano 

All yours
