### ISSUE TITLE
HTML Foundations, Links and Images: Dead link in assignment

### ISSUE THREAD

**Issue by tvontheinternet** [TheOdinProject/curriculum#25416]
### Describe your suggestion

Assignment number 4 to "[Read about the four main image formats that can be used on the web](https://www.internetingishard.com/html-and-css/links-and-images/#image-formats).", has a dead link due to internetingishard.com having expired DNS hosting. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types 

The above might be a good substitute.

**Comment by TlonUqbar** [comment]
I just came across this dead link myself.  And was about to open an issue, but I see that some else has already opened one. 

I had to ask around the discord channels to find out where to go, luckily someone pointed in the right direction.   So today, I learned what to do and how to let people know when something is broken.  Although, I didn't get to open the issue myself. 

Is there a way to make this a little easier for the newbies? Like an obvious page or channel to show us how and where to report bugs. I don't think I would have found the "curriculum" repo on my own, before giving up on reporting the issue.

**Comment by PalomoAn** [comment]
just came for this. there is also another dead link in the introduction to flexbox.

Lesson Url
https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox

in additional resources link goes to https://www.internetingishard.com/html-and-css/flexbox/ 

where now i think it should link to https://internetingishard.netlify.app/html-and-css/flexbox/index.html

**Comment by CouchofTomato** [comment]
@PalomoAn I just merged a PR to fix that one.

**Comment by CouchofTomato** [comment]
@TheOdinProject/intermediate-html-css Can someone take a look at this please

**Comment by TlonUqbar** [comment]
If anyone can just make the change and submit a PR, I can do that.

**Comment by tvontheinternet** [comment]
https://github.com/TheOdinProject/curriculum/pull/25421 submitted

**Comment by bennygoldman** [comment]
Glad to see this one already has eyes on it!

**Comment by Wathek-beji** [comment]
The link was fixed under knowledge check in #25421 but is still broken under assignment.
I just created this PR #25428 to fix it.
This is my first contribution ever so I was not sure whether to create a new issue since this one is closed or make a a simple PR.
I decided with the latter.
