### ISSUE TITLE
Layout Style Guide: Inconsistencies lead to confusion / Possibility for markdown linting?

### ISSUE THREAD

**Issue by ioakeimo** [TheOdinProject/curriculum#25412]
### Because:

While trying to correct a simple grammar mistake in a lesson file, I noticed there are some layout issues (eg using `*` for lists instead of `-`). I thought it might be a good idea to create a second commit fixing those before opening a PR. Ι gave the Layout Style Guide a read again so as to make them as correct as possible. Following are some issues I noticed.

Trying to apply guidelines to etch-a-sketch (sample of problematic layout):
https://github.com/TheOdinProject/curriculum/blob/bf47251e782d2c7c32370714716624f734ed6c4f/foundations/javascript_basics/project_etch_a_sketch.md?plain=1#L19
When trying to figure out the exact spacing for the list item (between bullet `-` and first item letter), I noticed that the style guide itself is not consistent and does not follow the guidelines.

### Examples of issue in the Layout Style Guide:

1. Headings [Sentence case guideline](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#title-case) is not consistently followed:
https://github.com/TheOdinProject/curriculum/blob/bf47251e782d2c7c32370714716624f734ed6c4f/LAYOUT_STYLE_GUIDE.md?plain=1#L110
1. List item spacing of more than 1 breaks [nested list style guideline](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#nested-lists):
   https://github.com/TheOdinProject/curriculum/blob/bf47251e782d2c7c32370714716624f734ed6c4f/LAYOUT_STYLE_GUIDE.md?plain=1#L9
   Trying to nest list items here with the suggested 2 spaces would result in:
   ~~~markdown
   -   Readable for as many users as possible.
     - Nested with 2 spaces does not line up hyphen with first letter of parent.
   ~~~
1. Inconsistencies in a single list (more spaces than the rest of the items):
https://github.com/TheOdinProject/curriculum/blob/bf47251e782d2c7c32370714716624f734ed6c4f/LAYOUT_STYLE_GUIDE.md?plain=1#L225
1. Inconsistencies to [code style guidelines](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks):
https://github.com/TheOdinProject/curriculum/blob/bf47251e782d2c7c32370714716624f734ed6c4f/LAYOUT_STYLE_GUIDE.md?plain=1#L168

### Suggestion:

Make the Layout Style Guide's Markdown exactly consistent to the requirements of the Layout Style Guide.  
Others might try what I tried (using its Markdown as a reference point) and get confused by the inconsistencies.

### Considerations:

Facing those issues made me think, aren't there any Markdown linters/formatters that could be used with a custom configuration file to completely automate solving at least some (eg. Links informative text might be more manual work by nature) of those concerns?

### Path

Other / NA

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by codyloyd** [comment]
I think making the style guide internally consistent with it's own suggestions is a really solid idea.  Approved.


A quick google of MD linters brought me here: https://github.com/markdownlint/markdownlint  I think this is worth researching, but we should at least update the style guide to make it consistent, even if we don't decide to use the linter here.

**Comment by ioakeimo** [comment]
Just a quick note

I specifically didn't mark the checkbox "Would you like to work on this issue?" in this instance because:
1. In the case a decision to go with a linter is made, such work could be deemed unnecessary
2. I feared that my lack of familiarity with the style guide, could potentially still result in remnant style guide inconsistencies/mistakes, therefore not entirely solving the issue.

That said, I'm still open/willing to work on this if needed.

**Comment by CouchofTomato** [comment]
Hey @ioakeimo 

I've discussed this with the team. Although longer term a linter would make sense. We don't have the bandwidth right now to find one that is suitable and do all the work to get it up and running.

So we're happy if you want to take on making the change you proposed, or we can see if anyone else wants to pick it up if you don't want to, but nobody on the team has the time to handle this at the moment and it's considered pretty low priority.

**Comment by ioakeimo** [comment]
Thank you @CouchofTomato 

I'll gladly work on this then, assign it to me.

Just a quick question in regards to the workflow:
If I happen to need any clarification should I tag someone and ask?
Or should I expect all feedback when time comes for Review of the PR?

**Comment by CouchofTomato** [comment]
@ioakeimo All yours mate.

You can just drop a comment here or ask on discord.
