### ISSUE TITLE
Bug: Read about image formats link is broken

### ISSUE THREAD

**Issue by andersonweeks** [TheOdinProject/curriculum#25435]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
 In the [Links and Images](https://www.theodinproject.com/lessons/foundations-links-and-images) section, the following link in the Assignments section seems to be broken: [Read about the four main image formats that can be used on the web](https://www.internetingishard.com/html-and-css/links-and-images/#image-formats)
![image](https://user-images.githubusercontent.com/131593964/236446554-fd3d31b5-5913-4364-b95f-18d42dc9a80f.png)
My firewall is turned off and I don't have any proxies selected.

The link goes to this url:
"https://www.internetingishard.com/html-and-css/links-and-images/#image-formats".
I found the following page through googling and it seems like this is where the link needs to go to work:
"https://internetingishard.netlify.app/html-and-css/links-and-images/index.html#image-formats"

**2. How To Reproduce:**
1. Sign in
2. Visit the HTML Foundations > Links and Images lesson page
3. Click Link 4 "Read about the four main image formats that can be used on the web"
4. The site can't be reached

**3. Expected Behavior:**
1. Sign in
2. Visit the HTML Foundations > Links and Images lesson page
3. Click Link 4 "Read about the four main image formats that can be used on the web"
4. The site opens successfully

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks for reporting @andersonweeks, I transfered this to the curriculum repo because its lesson content related.

This has been fixed: https://github.com/TheOdinProject/curriculum/pull/25428/files
