### ISSUE TITLE
Bug: foundations-fundamentals-part-2 has wrong additional-resources

### ISSUE THREAD

**Issue by M-519** [TheOdinProject/curriculum#25430]
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
Foundations-fundamentals-part-2 has wrong additional-resources

**2. How To Reproduce:**
What steps one might need to take in order to reproduce this bug,:
1. Sign in
2. Visit a lesson page
3. Visit the "foundations-fundamentals-part-2" 
4. Check the "additional-resources" section of "foundations-fundamentals-part-2"
5. The section "foundations-fundamentals-part-2" show information that is, at the time of completing "foundations-fundamentals-part-2", irrelevant.

**3. Expected Behavior:**
A brief description of what you expected to happen, e.g.:
1. Sign in
2. Visit a lesson page
3. Visit the "foundations-fundamentals-part-2" 
4. Check the "additional-resources" section of "foundations-fundamentals-part-2"
5. The section "foundations-fundamentals-part-2" will show information that is, at the time of completing "foundations-fundamentals-part-2", relevant.

**Comment by CouchofTomato** [comment]
@M-519 Can we get an update on this please on which parts you think are irrelevant or we'll have to close it
