### ISSUE TITLE
Bug: broken assignment link

### ISSUE THREAD

**Issue by d-4n13l** [TheOdinProject/curriculum#25431]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

the fourth link of [this lesson's assignments](https://www.theodinproject.com/lessons/foundations-links-and-images#assignment) doesn't work. I think the working and updated link is [this](https://internetingishard.netlify.app/html-and-css/links-and-images/index.html#image-formats). 

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

I tried to report the problem on Discord but they advised me to report it here.. i'm still inexperienced with GitHub, i hope i did the procedure correctly.

**Comment by CouchofTomato** [comment]
Now fixed
