### ISSUE TITLE
Foundations: Change git checkout to git switch in "Revisiting Rock Paper Scissors"

### ISSUE THREAD

**Issue by pantbruin** [TheOdinProject/curriculum#25449]
### Describe your suggestion

Branching in Git is first introduced and encouraged in the "Revisiting Rock Paper Scissors" lesson in the Foundations path. In the current state of the lesson, the recommended command to switch between branches is 'git checkout'. However, since Git version 2.23 (Aug 2019), the 'git switch' command was introduced. I propose that instead of recommending 'git checkout' to change branches, the lesson should encourage using 'git switch'. 'git switch' is more intuitive to Git newcomers, as it is easier to recall and its [documentation](https://git-scm.com/docs/git-switch) is much clearer compared to ['git checkout'](https://git-scm.com/docs/git-checkout). Furthermore, the 'git checkout' command does more than just switch branches, while the 'git switch' command is more tightly scoped and its only function is to switch branches. 

**Additional Information:**
- See this StackOverflow post (225k views) which highlights the confusing 'git checkout' command and the positive reactions for the more intuitive 'git switch' command
[source](https://stackoverflow.com/questions/57265785/whats-the-difference-between-git-switch-and-git-checkout-branch)

- "[git switch is] meant to eventually provide a better interface for the well-known git checkout. The new [command is intended] to each have a clear separation, neatly divvying up what the many responsibilities of git checkout", quoted from the GitHub blog post regarding Git version 2.23.0
[source](https://github.blog/2019-08-16-highlights-from-git-2-23/)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by codyloyd** [comment]
This is probably worth some discussion.  PERSONALLY... I only ever use 'checkout'... but that's just a habit I've formed.  If it's not best practice for whatever reason, then it's a good idea to get this lesson updated.

@TheOdinProject/foundations 

anyone have any strong opinions on this one?

**Comment by xandora** [comment]
> that's good enough for me.

Yea, it's a bit disappointing. It looks like that feature is sorta languishing now. The person developing that feature left working on Git and now they're not really sure what to do with it.

**Comment by wise-king-sullyman** [comment]
Yeah I really wish they would just freeze the functionality of it and move it out of beta. I've never run into errors because of it and I use it almost exclusively.

I suppose we could still explain things using `checkout` and suggest that people use it, but add a note that mentions `switch` is a thing, and why they maybe shouldn't use it. Though this might just cause more confusion than anything else.

We do already point to the Git docs later in the curriculum and IIRC that includes a chapter that mentions `switch`, and by that point people should be comfortable handling the situation if they do run into issues with it.

**Comment by CouchofTomato** [comment]
Closing as we aren't making the change.
