### ISSUE TITLE
Actions: Label as inactive is hitting operations limit

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#25445]
For the last ~3 weeks (starting it seems with https://github.com/TheOdinProject/curriculum/actions/runs/4738702179 ) the Label as inactive action has been running up against its operations limit, and therefore exiting early within its run. Their annotation and docs suggest raising the operations limit if that fits within the organizations quota.

Github's docs suggest that the rate limit is 1000/h/repo [[1](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions)] and given TOP mostly doesn't run that many actions it should probably be safe to raise this limit up somewhat?

### Checks

- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

Asarta#5596

**Comment by KevinMulhern** [comment]
Thanks for reporting this @Asartea, let's raise it to 100 and see how that goes.
