### ISSUE TITLE
React: Change "React Docs Beta" to "React Docs" 

### ISSUE THREAD

**Issue by DasTapan** [TheOdinProject/curriculum#25457]
### Describe your suggestion

Hi, In the **Advanced Concepts** Chapter of **React**  section. The React Docs are still labeled as "React Docs Beta". The link takes you to the current React Docs page. But the old markup text is still there. 

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-advanced-concepts

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

DasTapan

### (Optional) Additional Comments

I would love to update these two tiny pieces of text. I couldn't find a way to attach SS

**Comment by LeoKirasic** [comment]
@DasTapan Cool, go for it!
