### ISSUE TITLE
Foundations: I'd like to construct a better overview of "how the Internet works"

### ISSUE THREAD

**Issue by Ozzard** [TheOdinProject/curriculum#25451]
### Describe your suggestion

The existing video material in sections 2 and 3 of this page swerves from misleading to actively wrong and back again.  In particular:
* There is no historical perspective of how networks became internetworks.  It's difficult to understand why people refer to _the_ Internet without this.
* There is no mention of routing - in fact one video goes so far as to describe the internet as "a wire", and the other then gets very confused about ISPs.  The choice of packet switching rather than circuit switching is key to "bombproofing" Arpanet, and hence the internet.
* Computers are described as "clients" and "servers" rather than the software services running on them being client, peer, or server for a particular service.  This makes it difficult for a new learner to understand that any computer can take any role, and that running a web server on a laptop (or a microcontroller) is a perfectly reasonable thing to do.
* IP, TCP, and UDP (and the possibility of other transport protocols) are confounded, making it appear that reliability and acknowledgement are features of IP.  They're not, and that becomes *really* important with things like HTTP/2.
* DNS is presented as a monolithic address book, whereas the entire reason for DNS was to move away from a monolithic address book - it's a system for distribution of control.

I used to teach this stuff professionally.  If I were to put together a set of learning points for a c. 15 minute video (to match the lengths of the two current videos), would anyone from TOP be willing to review those learning points to see whether it's worth me proceeding to script the video, record it, and add the graphics it would inevitably need?  I'd rather not do several days' work without some indication that it might be useful to someone :-).

### Path

Foundations

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/foundations/installations/how_does_the_web_work.md

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by LeoKirasic** [comment]
Hey @Ozzard, 

Thank you for expressing interest to work on this! Just to clarify, are you talking about the assignment and the knowledge check sections when referring to sections 2 and 3? 

I want to make sure since that would mean replacing all of the current video content we have in that lesson.

**Comment by codyloyd** [comment]
@Ozzard 

I think, with the consideration of @LeoKirasic's question.. that it _would_ be worth investigating if you are interested in doing the work of scripting and producing a new video for us to link.

I don't think that our current content is particularly _harmful_... but if you are able to create something significantly better, then I'm interested in seeing what you've got.

I like your plan of getting an outline, and then a script approved before actually producing a vid :D
