### ISSUE TITLE
JavaScript: Change class-focussed React lessons to become more function-focussed

### ISSUE THREAD

**Issue by violetjordanhara** [TheOdinProject/curriculum#25470]
### Describe your suggestion

The second resource of the "Lifecycle Methods" lesson of the React section recommends React users to "define components as functions instead of classes". (https://react.dev/reference/react/Component). 

With the new update, React no longer recommends users to use Class components in new code. However, the lessons in the first half of The Odin Project's React section have focussed only on creating Class components. 

Perhaps this switch to function components warrants a change in The Odin Project's curriculum. Learners could be first introduced to function components when beginning to learn React, as opposed to Class components. 

### Path

Node / JS

### Lesson Url

The first half of the React section and this lesson in particular https://www.theodinproject.com/lessons/node-path-javascript-lifecycle-methods

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by LeoKirasic** [comment]
Hey, @violetjordanhara we're currently in the process of revamping all of the React content so this will be handled in that change!
