### ISSUE TITLE
Foundations > JavaScript Basics > Clean Code > Additional Resources: Broken link at the second bullet point

### ISSUE THREAD

**Issue by 91Flavio91** [TheOdinProject/curriculum#25483]
### Describe your suggestion

Hey! 
Nothing to add, the title speaks by itself. I just leave you a brief snapshot of the problem!

Have a good one!

Flavio

https://github.com/TheOdinProject/curriculum/assets/107210617/dccc541b-444f-4290-afaf-91129ecb9c25

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

91Flavio91#5811

**Comment by xandora** [comment]
Thanks for reporting this. The website appears to be back online now.

**Comment by 91Flavio91** [comment]
@xandora  My pleasure! Have a good one!
