### ISSUE TITLE
Foundations Course: Broken link at Additional Resources

### ISSUE THREAD

**Issue by sumi-satsuo** [TheOdinProject/curriculum#25486]
### Describe your suggestion

At: > [Additional Resources](https://www.theodinproject.com/lessons/foundations-clean-code#additional-resources)

> THE complete guide to [self-documenting code](http://wiki.c2.com/?SelfDocumentingCode)
Broken Link

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code#additional-resources

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Sumi Satsuo#8786

### (Optional) Additional Comments

My mentor said something funny that I wanna add here "That sums up self-documenting code in the industry really well" XD

**Comment by xandora** [comment]
Thanks for reporting. This website appears to be back online now.
