### ISSUE TITLE
NodeJS: Typo in the prototype section of objects and object constructors lesson

### ISSUE THREAD

**Issue by mohammedalfa** [TheOdinProject/curriculum#25519]
### Describe your suggestion

There is a typo in the prototype section of the object constructor lesson, it says 

> "The second reason is the name of this section, Prototypal Inheritance, which we’ve referred to in passing earlier, in the introduction to the Prototype. In recap, we know that can say that the player1 or player2 objects inherit from the Player.prototype object, like with the .sayHello function, by being able to access it."

It should say "In recap, we now can say that the player1 or player2 objects inherit..."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

okonkwo#9890

**Comment by KevinMulhern** [comment]
Thanks for reporting this @mohammedalfa, would you still like to work on it?

**Comment by mohammedalfa** [comment]
Sorry, I won't be able to, I'm currently traveling.
   On Saturday, June 3, 2023 at 10:29:59 PM GMT+3, Kevin Mulhern ***@***.***> wrote:  
 
 


Thanks for reporting this @mohammedalfa, would you still like to work on it?

**Comment by KevinMulhern** [comment]
It appears this has been fixed: https://github.com/TheOdinProject/curriculum/pull/25570
