### ISSUE TITLE
JavaScript Basics: replit exercise follow.js issue

### ISSUE THREAD

**Issue by i4pg** [TheOdinProject/curriculum#25516]
### Describe your suggestion

In the Fundamental 2 Exercise 4, There're two issues in the code:

1. The code tests for the variable `thisYear` instead of `currentYear`. This creates confusion for users trying to follow the exercise.
2. The test step 3 is missing a closing curly bracket, which introduce an error.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-2#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

xiyi#4897

### (Optional) Additional Comments

These issues identified on the comments section of [replit](https://replit.com/@OdinProject/direction-follow#follow.js) by [KarlAWarren](https://replit.com/@KarlAWarren) and [novice-user21](https://replit.com/@novice-user21)

**Comment by codyloyd** [comment]
we need to fix this... but only a maintainer can do it because we need the login creds for repl.it to make the changes

**Comment by wise-king-sullyman** [comment]
I've updated it, can someone give me another look? No way to PR it (or there is one and I don't know it).

https://replit.com/@OdinProject/direction-follow#follow.js

**Comment by CouchofTomato** [comment]
@wise-king-sullyman Looks ok to me mate.

**Comment by codyloyd** [comment]
yep.. looks good.  closing this issue
