### ISSUE TITLE
Intermediate HTML and CSS Course: Broken link 

### ISSUE THREAD

**Issue by TrueBulla** [TheOdinProject/curriculum#25530]
### Describe your suggestion

The link in the assignment session for browsers in iOS is broken 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-browser-compatibility#browser-releases-and-new-css-features

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

TrueBulla#2034

**Comment by KevinMulhern** [comment]
Thanks for reporting @TrueBulla, looks like its back up again.
