### ISSUE TITLE
Foundations: Give readers an explanation as to why they're installing version 22.04 of Xubuntu

### ISSUE THREAD

**Issue by Vi0lett** [TheOdinProject/curriculum#25532]
### Describe your suggestion

Hello friends. This is a very simple suggestion!

During the "Installations" path of the "Foundations" course, if the reader wishes to go for the Virtual Machine path, they are instructed to install Xubuntu 22.04. As I'm going through that stage myself, I found it weird that the download link provided in the course was so specific, so I went to check the Xubuntu website and sure enough, 22.04 is not **exactly** the latest version, and judging from my (admittedly limited) knowledge of how updates are important for maintaining security, I wanted to make sure I understood that decision.

Now, judging from what I read there and from a comment on the Odin discord, I assume the main reason 22.04 is suggested is the support longevity. I'm perfectly fine with that, especially since [the official download page](https://xubuntu.org/download/) actually showcases 22.04 as the first option, which reinforces the fact that while it's not the very latest version, it's considered current and has full support.

So the point of my suggestion is: add the information above to the [Installations page](https://www.theodinproject.com/lessons/foundations-installations), so that users can fully understand the thought process behind this decision without spending more time than necessary.

Thank you all for your time and for the course! I have obviously not delved too deep into it yet, but I really appreciate what I've got so far.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by codyloyd** [comment]
@xandora I'll leave the decision on whether or not we should action this to you.

personally, I'm not sure our installations need more bloat... but i haven't really looked at them or touched them for a while.

**Comment by xandora** [comment]
If we could condense it to a sentence it two it might not be a bad idea to quickly cover a "why LTS?" question.

**Comment by codyloyd** [comment]
works for me :D 

I'll mark it as available for work.

**Comment by lorenzomad** [comment]
I can take this issue if no one is working on it

**Comment by CouchofTomato** [comment]
@lorenzomad 

All yours.
