### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sco-bo** [TheOdinProject/curriculum#2554]
The "Gentle Introduction to Algorithms for Web Developers" link (http://www.giocc.com/a-gentle-introduction-to-algorithms-for-web-developers.html) in the 'Basic Data Structures and Algorithms' section of 'Ruby Programming' appears to be broken.

**Comment by kriox26** [comment]
Thanks @sco-bo , we'll look into alternatives to this resource, if you have any let us know!! :+1:

**Comment by sco-bo** [comment]
Actually, nevermind. This link is working for me today. I'll go ahead and close
