### ISSUE TITLE
Getting Hired: Table isn't rendered as table but markdown text on a `p` element

### ISSUE THREAD

**Issue by lemonadee71** [TheOdinProject/curriculum#25548]
### Describe your suggestion

I don't know if this is intentional but this markdown text isn't rendered as a table. The syntax is correct as it is shown properly on Github (second pic) as a table so I guess the problem is how the site transforms the markdown to html elements.
![image](https://github.com/TheOdinProject/curriculum/assets/65146874/d889c6ca-7037-4116-9021-6effb9e07215)

![image](https://github.com/TheOdinProject/curriculum/assets/65146874/4b6dae08-69f3-4884-8edf-eee331e252ce)

I'm not sure if I categorized this issue properly. If not I apologize in advance. It's been a while since I contributed.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-getting-hired-collecting-job-leads

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks for reporting @lemonadee71
