### ISSUE TITLE
Intermediate HTML and CSS Course : Links can be more specific

### ISSUE THREAD

**Issue by sabbir292** [TheOdinProject/curriculum#25595]
### Describe your suggestion

Form Basics: 
Read and follow along to [MDN’s Introductory Guides to Forms](https://developer.mozilla.org/en-US/docs/Learn/Forms#introductory_guides)

Read and follow along to [MDN’s The Different Form Controls Guides](https://developer.mozilla.org/en-US/docs/Learn/Forms#the_different_form_controls)
Styling Forms

Read and follow along to [MDN’s Form Styling Guides](https://developer.mozilla.org/en-US/docs/Learn/Forms#form_styling_guides)

These three links are redirecting the user to the same blog, the blog contains internally specified links about the above topics, so I think it would be more logical and less confusing for new users if those links redirect the user to the blog that then needs to be read instead of searching the appropriate internal links and visit it.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

sabbir292

**Comment by CouchofTomato** [comment]
Hi @sabbir292 

I'm not really understanding your suggestion here. We link to the parts relevant for what we are trying to teach. It's quite a long resource so having students read it all might be asking a bit much.

What is the issue with linking only to those parts required?

**Comment by sabbir292** [comment]
@CouchofTomato That's what I am suggesting the resource all the links are linking is the same and quite long, and it also contains its own multiple links as separate links. as per my understanding, the module links are referring to some of those separate links eg. style guides. so a new user might get confused are they supposed to go to those internal links and read all those, or only those articles that are linked by the modules in this case all three are pointing to the same resource. my suggestion is either to specify those links or we can give a message to users that they are supposed to read through all of the topics that are internally linked within the article.

**Comment by codyloyd** [comment]
it looks like to me that we DO link to the exact sections in question.... but for some reason those direct links are not working in Chrome.  This is either a browser bug, or an MDN bug.  Either way.. there isn't much we can do about it.

![CleanShot 2023-06-06 at 08 45 00](https://github.com/TheOdinProject/curriculum/assets/18574792/52ea900d-4c08-46f3-a2b5-b4775ed41bd6)

I think we can leave this issue open for the moment, in case there's more discussion to be had, but I think that we are not going to be able to fix this on our end.

**Comment by sabbir292** [comment]
> 
I guess we can be little bit more expensive for the student that they are supposed follow the sublinks in mdn under the main Heading, I think that would do the work. What you think?

And I have one more suggestions, whenever we go to resource page they contains their own referal link, I think disclaimer would helpful for students that if they need to go and read those resources inside the referral link, then how deep they should go or just read the linked resources.

**Comment by CouchofTomato** [comment]
Hey @sabbir292 

Have you come across anyone in the discord chats who has had an issue with not knowing which parts to read because it hasn't come up before.

I think it's pretty clear we're recommending only the resource we link to, if learners want to follow any links in that article it is their choice. Again, I'm not seeing feedback anywhere that it is a problem.

**Comment by sabbir292** [comment]
> Hey @sabbir292
> 
> Have you come across anyone in the discord chats who has had an issue with not knowing which parts to read because it hasn't come up before.
> 
> I think it's pretty clear we're recommending only the resource we link to, if learners want to follow any links in that article it is their choice. Again, I'm not seeing feedback anywhere that it is a problem.

I have asked in Discord if we should follow the suggested links in the resource and a guy who was on the same module told me he thinks we should, he sounded confused to me and i was also little bit confused so i have raised a question.

**Comment by CouchofTomato** [comment]
I'd be ok with a sentence added to the lesson to state something about following the links but that's about it.

**Comment by sabbir292** [comment]
Yeah, that would be fine @CouchofTomato

**Comment by CouchofTomato** [comment]
Cool. Is it something you want to take on?

**Comment by sabbir292** [comment]
Yeah, sure . why not.

**Comment by sabbir292** [comment]
should I do that?

**Comment by CouchofTomato** [comment]
@sabbir292 If you want to

**Comment by sabbir292** [comment]
Sure thanks.

**Comment by CouchofTomato** [comment]
@sabbir292 Hi mate. Are you still working on this?

**Comment by SaranshBangar** [comment]
@CouchofTomato Sir, can I continue on this issue?

**Comment by CouchofTomato** [comment]
> @CouchofTomato Sir, can I continue on this issue?

Yeah sure. I haven't heard back fro mthe other person.
