### ISSUE TITLE
Intermediate HTML and CSS > Forms > Forms Basics > Additional Resources: missing paragraph?

### ISSUE THREAD

**Issue by 91Flavio91** [TheOdinProject/curriculum#25618]
### Describe your suggestion

Hi!
I noticed that, in the path described in the title, the usual **"This section contains helpful links to related content. It isn’t required, so consider it supplemental"** paragraph is missing under Additional Resources. 

I thought that it could be on purpose, like that you shouldn't skip that part, but I didn't find anything that suggests that it shouldn't be skipped. Personally I don't care. I visit every link that I find! But I just wanted to inform you to let you know this; maybe you missed it!

I leave you a picture!
<img width="1319" alt="Schermata 2023-06-10 alle 17 28 13" src="https://github.com/TheOdinProject/curriculum/assets/107210617/87d63479-cee6-44fa-8c07-9c8f2f6a8312">

Have a good weekend!

Flavio

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by xandora** [comment]
Yep, looks like it's missing from this and at least the next lesson. This might be a good opportunity to create a PR that looks at this section across the curriculum. You indicated you'd be willing to take work on this, would you like to be assigned this one task, or take on a bigger fixer upper PR?

**Comment by 91Flavio91** [comment]
@xandora Hi! Yeah, I'd like to be assigned to this one. Honestly, I wouldn't know how to achieve what you are asking for besides trying to fix this one. It would be an opportunity for me to learn a new thing maybe but I also wouldn't like to crate a major hiccup during the process XD

**Comment by 91Flavio91** [comment]
@CouchofTomato Hi! I've just created a pull request. I added the standard "**This section contains helpful links to related content. It isn’t required, so consider it supplemental.**" 
Let me know if this is the paragraph that you guys had in mind

Thank you!
