### ISSUE TITLE
Ruby: Installing Ruby MacOS version check clarification

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25624]
## Quoted from step 2.3:

> You can double check that this worked by typing `ruby -v` and checking that the output says version 3.1.2:

~~~bash
ruby -v
ruby 3.1.2pxx (20xx-xx-xx revision xxxxx) [x86_64-darwin18]
~~~

> If you don't see the output above, log off and log back on, then try again.

## Improvement suggestion:
Clarify what is meant by `log off and log back on`. I assumed it meant another system reboot but I decided to close and reopen the terminal first (mine showed an older version than 3.1.2). After reopening the terminal and running the command, the correct version was showing.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Manonl

**Comment by CouchofTomato** [comment]
@ManonLef 

Yes I think it just meant closing and opening a new terminal. We probably should update that.
