### ISSUE TITLE
templates: Adding note box variations to lesson-template.md and lesson-example.md

### ISSUE THREAD

**Issue by luuu-xu** [TheOdinProject/curriculum#25627]
### Describe your suggestion

According to https://github.com/TheOdinProject/theodinproject/pull/3838, now the website supports 3 kinds of note boxes with optional header, I think we should add such feature to the templates here in curriculum repo so future contributors can refer to them. Both lesson-template.md and lesson-example.md can have such note boxes as examples.

### Path

Other / NA

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/templates/lesson-example.md

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Makes sense to me. All yours @luuu-xu
