### ISSUE TITLE
getting hired course: building your own website, list of porftolios

### ISSUE THREAD

**Issue by dontsn** [TheOdinProject/curriculum#25631]
### Describe your suggestion

a typo in a developer's name
Jack Jeznach > Jacek Jeznach

the link is broken
https://jacekjeznach.com/

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-getting-hired-building-your-personal-website#show-designs

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Do you have the correct link?

**Comment by KevinMulhern** [comment]
Thanks for reporting @dontsn - resolved https://github.com/TheOdinProject/curriculum/pull/25666
