### ISSUE TITLE
etch-a-sketch: a typo

### ISSUE THREAD

**Issue by kojokwakye** [TheOdinProject/curriculum#25646]
### Describe your suggestion

i think there is a typo at the assignment section of the page. let me know if it was a joke i missed
![Screenshot from 2023-06-18 22-30-00](https://github.com/TheOdinProject/curriculum/assets/90537940/6e581289-770f-441d-aa3a-9c308743619b)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-etch-a-sketch

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

kojokwakye

**Comment by wise-king-sullyman** [comment]
Ah yeah, looks like a closing tag was missed.

Thanks for raising this!

**Comment by kojokwakye** [comment]
you're welcome. 
i would like to know if i should close this issue.
