### ISSUE TITLE
Foundations: Elements and Tags - Image unreadable with warmer screen tone

### ISSUE THREAD

**Issue by ruben-vl** [TheOdinProject/curriculum#25656]
### Describe your suggestion

This is just a minor issue, but the blue text used in the image in the 'Elements and Tags' lesson of the 'Foundations' course is unreadable with ubuntu's 'night light' (warmer screen tone, or blue filter).

Since a lot of people will be reading it from ubuntu, this could be a little improvement.

Maybe perfect for a first contribution?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-elements-and-tags

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by matterramun** [comment]
Working through [Using Git in the Real World](https://www.theodinproject.com/lessons/ruby-using-git-in-the-real-world) and I would be willing to work on this change. Let me know if there's anything I need to do or wait for before getting started.

**Comment by KevinMulhern** [comment]
Thanks @matterramun, it's yours.

**Comment by thatblindgeye** [comment]
@matterramun Just wanted to check if you were still wanting to work on this? If so, I think we should actually remove the image entirely and replace it with a codeblock and list to define each part of the code. This would have a couple of benefits:

- completely avoids color contrast issues
- If the image fails to load, none of the information is lost for the user

**Comment by matterramun** [comment]
@thatblindgeye Can do! So far all I have is the image
![Frame 1](https://github.com/TheOdinProject/curriculum/assets/59074475/884b80c2-ebf9-4804-b589-8c203d5a7f70)
The updated image is a significant improvement on warmer screens and matches colors of dark mode.

Should I proceed or break it down into text as you suggested?
