### ISSUE TITLE
JavaScript Course: Potentially incorrect link

### ISSUE THREAD

**Issue by anasahmd** [TheOdinProject/curriculum#25667]
### Describe your suggestion

The link to the insert article of the binary search tree at geeks for geeks may have been changed as it links to the searching in binary search tree article instead.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-binary-search-trees

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Hey @TheOdinProject/ds-a, any thoughts on this one?

**Comment by ManonLef** [comment]
I agree, and think it should be this link instead: https://www.geeksforgeeks.org/insertion-in-binary-search-tree/?ref=lbp

I'll assign you @anasahmd since you have indicated you'd like to work on this. Thank you!

**Comment by anasahmd** [comment]
@ManonLef  Thank you for the opportunity, I will work on it.
