### ISSUE TITLE
JS NodeJS Testing: Article is quite opinionated about the tool of choice which is Jest

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25661]
### Describe your suggestion

[Article in question](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4)

Hi there, 

I'm currently going through [this lesson ](https://www.theodinproject.com/lessons/node-path-javascript-more-testing) and the above article kind of keeps burning Jest and other test suites. I think that heavily distracts and might make people doubt our Jest choice even.

I like their content most of the time but I also find it's often filled with strong opinions. Usually that's fine but in this case, as mentioned above, it distracts from the main message and it reads like an advertisement for another tool more than it reads as a good explanation for why we do testing. 

I'd love your opinion on this before I sum up the key points in that article and find an alternative that includes those as well without the distraction. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-more-testing

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

manonl

**Comment by KevinMulhern** [comment]
I had a quick read through that article and see what you mean @ManonLef. Would the second article would be enough? 

Would also like @TheOdinProject/javascript to weigh in.

**Comment by wise-king-sullyman** [comment]
Yeah, while he makes a few good points I don't love that article with its push for a particular framework, and actually strongly disagree with some of the things he's asserting. I also feel like the article is 90% promoting tape and 10% general advice, so I would be on board for removing it.

**Comment by ManonLef** [comment]
@KevinMulhern I believe the second article will be enough.

I said I wouldn't mind working on this issue. However, since this is just a removal of a link, and I don't think one needing a replacement to be found either, it might be a good first contributing option. 

I'll have you decide.

**Comment by amc131** [comment]
I can take care of this

**Comment by ManonLef** [comment]
@amc131 all yours :)

**Comment by xandora** [comment]
I wonder if we forgot to remove this article when we switched from Jasmine to Jest lol
