### ISSUE TITLE
Scrimba: Decide if/how to sandbox Scrimba iframes

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#25678]
### Describe your suggestion

With #25041 all scrimba iframes in the Foundations path were sandboxed. There are also some scrimba iframes in the JavaScript course however, and those currently aren't. These should ideally all be synchronised, probably by setting `sandbox="allow-scripts allow-same-origin allow-popups"` on all the JavaScript ones ([full list](https://github.com/search?q=repo%3ATheOdinProject%2Fcurriculum+path%3A%2F%5Ejavascript%5C%2F%2F+%3Ciframe+src%3D%22https%3A%2F%2Fscrimba&type=code))

I would be willing to work on this, but I also could see this as a relatively easy first issue, in which case I'd rather leave it to someone new to contributing

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

asarta

**Comment by nikasagina** [comment]
Hi, I am currently on the 'Using Git in the Real World' lesson and I would like to contribute to this issue

**Comment by CouchofTomato** [comment]
Hey @nikasagina 

Are you clear on what needs to be done?

**Comment by nikasagina** [comment]
@CouchofTomato, Yeah

**Comment by CouchofTomato** [comment]
@nikasagina All yours
