### ISSUE TITLE
Advanced Javascript/project Recursion: error in the fibonacci exercise

### ISSUE THREAD

**Issue by lorenzomad** [TheOdinProject/curriculum#25687]
### Describe your suggestion

In the fibonacci exercise there are 2 parts:
1.  Using iteration, write a function fibs which takes a number and returns an array containing that many numbers from the fibonacci sequence. Using an example input of 8, this function should return the array [0, 1, 1, 2, 3, 5, 8, 13].
2. Now write another function fibsRec which solves the same problem recursively. This can be done in just a couple of lines (or 1 if you’re crazy, but don’t consider either of these lengths a requirement… just get it done).

There is a mistake in part 2, since the second part should not state  to do the same with recursion. As visible in the solution linked below, the recursive solution only gives as output the nth element of the fibonacci sequence, not the whole sequence up to n.

I hope the difference is clear from my explanation. I spent quite some time trying to solve it before looking at the solution and understanding the different result expected.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursion

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Hey @lorenzomad 

Thanks for raising this issue.

You mention a solution linked below but I don't see anything linked?

The first two student submissions in the list seem to solve the recursive part the same way as the first part so I'm curious what you're referring to?

**Comment by lorenzomad** [comment]
Sorry if I was not clear: when I mentioned the solution, I mean the solution linked in the lesson, which is the following: 
https://medium.com/launch-school/recursive-fibonnaci-method-explained-d82215c5498e

As you can see the link gives a solution to obtain the nth element of the sequence, not the full sequence up to n, which in my opinion is much harder than something you do in 1 or 2 lines of code as stated in the exercise script.

To answer your other point, the first 2 solutions do that, but the second student "cheated" (let me used the term in a non-serious manner) by adding the previous list as an input, while the exercise states that the function should only take 1 number as input. The first student actually managed to do it, but in my opinion they implemented a quite complex solution with a lot of if/else states which is not exactly what the course required: 
```return n <= 0
		? "Please enter a valid number of elements to be given an answer."
		: n === 1
		? [0]
		: n === 2
		? [0, 1]
		: [...fibsRecurse(n - 1), fibsRecurse(n - 1)[n - 2] + fibsRecurse(n - 1)[n - 3]];
```

I believe the level of the previous recursion exercises was instead referring to finding the solution also linked in the medium link which is this:

```
def fibonacci(number)
  if number < 2
    number
  else
    fibonacci(number - 1) + fibonacci(number - 2)
  end
end
```

If you think I am wrong the issue can be closed however

**Comment by CouchofTomato** [comment]
Thanks @lorenzomad 

I'll ask someone to take a look at it

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by CouchofTomato** [comment]
Hey @lorenzomad 

I've discussed this with the team. We think it makes the most sense if the two assignments for fibonacci have the same expected output, and therefore feel we'd be better suited trying to find an updated resource rather than change the assignment. Is this something you want to do? Or do you want us to open it up for someone else to work on?

**Comment by lorenzomad** [comment]
Is it possible to discuss changing the first exercise to output the nth number of the fibonacci sequence?
I think that would be less tedious.
If that is not what the team wants then I can try to look for an update resource.

**Comment by CouchofTomato** [comment]
Any thoughts on this @ManonLef

**Comment by wise-king-sullyman** [comment]
I largely share @ManonLef's thoughts. While I definitely remember this exercise being quite the challenge it's nothing compared to the projects that follow not long after it.

If in the future we expand CS though I wouldn't be opposed to us breaking things into a recursion one and two and having this be in the latter though.

**Comment by CouchofTomato** [comment]
Ok I don't think we have the support for the change, so I'm closing this for now. Thanks for the contribution though @lorenzomad

**Comment by ManonLef** [comment]
If we do want an alternative article explanation it might be worth looking into these articles:

- [not sure if the explanation is lacking here, I think it probably is](https://medium.com/@apestruy/iterative-and-recursive-solutions-to-the-fibonacci-sequence-interview-question-16e226a27987)
- [this link provides a solution with visuals only](https://www.w3resource.com/javascript-exercises/javascript-recursion-function-exercise-6.php)
- [I like this one best but... It's in C (which I think is still readable) It explains the recursion depth a bit better, with first solving each step, which will solve the previous one etc.](https://www.techcrashcourse.com/2015/03/c-program-fibonacci-series-using-recursion.html)

@CouchofTomato @lorenzomad what do you think?

**Comment by CouchofTomato** [comment]
@ManonLef 

The last example doesn't explain a solution for the problem we're asking students to solve. It's using a recursive function to calculate the nth term but calling it inside a loop and just printing that number. This is the issue we'll find I think. Most resources on tackle this problem from the perspective of calculating the nth term rather than returning an array of the fibonacci series.

I'll open this issue back up for now because there is still the question of the resource but I don't have an easy solution.

**Comment by ManonLef** [comment]
@CouchofTomato Oh you're right! I was glancing at the memorization option it seems and it seemingly using an array. That was hasty of me.

**Comment by ManonLef** [comment]
I'm working on a new resource for this

**Comment by keyBash** [comment]
yes. that will help

**Comment by ManonLef** [comment]
Still got this :) It needs some more focus time from me!

**Comment by ManonLef** [comment]
I happened to come across [this article on Fibonacci](https://www.scaler.com/topics/fibonacci-series-in-javascript/) which does both with and without array storage. 

No matter how much I'd love to finish my own article, and I still intend to do so in the future, it has not been up high on my priority list since it does require quite a bit of mental resources and animation creativity brainwidth.

Would love to hear what you think about it @CouchofTomato

**Comment by CouchofTomato** [comment]
@ManonLef 

Yeah this looks a pretty comprehensive article. Definitely better than what we have I think.

**Comment by ManonLef** [comment]
Thanks @CouchofTomato 
@lorenzomad would you still like to add this?

**Comment by lorenzomad** [comment]
Thanks for finding the article! I can take care of changing the link in the course material.
