### ISSUE TITLE
The Odin Project - Foundations - Axes: Alternating between Axes and Axis in the text

### ISSUE THREAD

**Issue by akinney96** [TheOdinProject/curriculum#25685]
### Describe your suggestion

I believe the title of the section is supposed to be called Axis and within the text it alternates between 'Axis' and 'Axes'. If the text is correct and I'm reading it wrong, please disregard. If the text is incorrect, I suggest a simple replacement of 'Axes' with 'Axis'. I would like to contribute if at all possible to gain a little experience with Open Source content.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-axes

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

akinney96

### (Optional) Additional Comments

I absolutely admire all the hard work every contributor has poured into this course and would like to leave my mark, even if it's just something as simple as fixing some text within the code. I'm just getting started, but I look forward to contributing on an even higher magnitude later on once I finish the course.

**Comment by CouchofTomato** [comment]
Hey @akinney96 

Axes is the plural of axis and changes depending on whether it is referencing one axis or the two axes (horizontal and vertical). I've had a skim and can't see anything wrong but if you think any of them should be changed to either the singular or plural form then please do open a PR to fix.
