### ISSUE TITLE
Javascript Course : Link not working

### ISSUE THREAD

**Issue by PulseFiction** [TheOdinProject/curriculum#25696]
### Describe your suggestion

On the Asynchronous Code page of the Javascript Course, the first assignment link: `Read this [Promises article](https://davidwalsh.name/promises). It’s a good starting place and it’s short and to the point.`
The site cannot be reached.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-asynchronous-code

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
It was perhaps a temporary outage since the link seems to work for me. Thanks for bringing it up though!
