### ISSUE TITLE
<Foundations>: <Missing shortcuts in HTML Comments>

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#25690]
## Problem 
Even though the Comments lesson shows the symbols, typing <-- --> separately can be very time-consuming and cut a developer’s productivity.

## Possible Solution 
- Keep the symbols 
- Add the keyboard shortcuts for Mac and Windows. Something similar to the HTML Boilerplate shortcut methods.

## Possible Benefit 
These shortcuts are often used by professional devs, so it’ll give learners a real-life coding skill as well as increase their productivity rate. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-working-with-text

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

**Comment by CouchofTomato** [comment]
Thanks @CBID2 

I'll discuss with the team and come back to you.

**Comment by CBID2** [comment]
> Hey @CBID2 
> 
> 
> 
> I've discussed this with the team and we're broadly supportive of the change. We can add the shortcuts and maybe a caveat that if the shortcut doesn't work they may need to look up what it is for their system if they use something different.
> 
> 
> 
> Are you happy to take this on?

Yes I am @CouchofTomato! :)

**Comment by CouchofTomato** [comment]
@CBID2 All yours
