### ISSUE TITLE
Ruby Course: Update for installation guide of Ruby

### ISSUE THREAD

**Issue by jonichi16** [TheOdinProject/curriculum#25695]
### Describe your suggestion

The installation guide instructs users to install Ruby version 3.1.2, while the main site itself is already using version 3.2.2 which may cause confusion for learners who installed version 3.1.2 who want to contribute to the site.

The proposed solution is to revise the installation guide of ruby to both linux and macOS from:
`rbenv install 3.1.2 --verbose`
to:
`rbenv install 3.2.2 --verbose`

This update will avoid compatibility issues, and create a more accessible environment for new contributors.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Makes sense to me. All yours @jonichi16
