### ISSUE TITLE
Bug:  Resource - Assignment: Firebase Codelab seems broken at emulator step

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/curriculum#25700]
Complete the following REQUIRED checkboxes:
-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

While following the codelab https://codelabs.developers.google.com/codelabs/firebase-web/#0 in https://www.theodinproject.com/lessons/javascript-using-baas-for-your-back-end, the step where they tell you to fire up the emulator gives the error  `[error] Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier`

I am filing an issue, I know there is a discussion about the quality of the codelab, but this is different as it seems broken now. 

3 other people now have contacted me to let me know they had the same issue recently.  @bug, @hebi, are the two most recent. 

**2. How To Reproduce:**

Follow step by step the tutorial. Get to where they say to start the emulator, like step 4, get error. 

**3. Expected Behavior:**
That the emulator fires up and we get to continue on with the tutorial. 

**4. Desktop/Device:**

-   Device:  Apple MacBook Air, m1 2020
-   OS:  MacOS 13.4.1 (22F82)
-   Browser: Chrome 
Version 114.0.5735.133 (Official Build) (arm64)

**5. Additional Information:**

I had to install java SDK to use the tutorial, I chose the official sdk  the LTS version---  This is what prints for `java --version` on my machine: java 17.0.7 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

I reached out to firebase support after scouring the internet and no one seemed to have this issue. We exchanged emails with but after the 3rd one, without the issue being resolved, I didn't want to troubleshoot further, given that I had picked up basic CRUD operations and auth from the Net Ninja Firebase Tutorial enough to implement it in my library project.  I can provide my error logs / conversation with firebase if you want to troubleshoot the tutorial....  But that seems a bit out of scope, but I am offering if it's important.

I am running node - v18.12.1, if that helps. 

I suggest removing assignment or adding caveat that it might not work... 

Thanks for all that you do!

**Comment by KevinMulhern** [comment]
Hey @JustWaveThings, thanks for reporting 💪 

Just transferring this to the curriculum repo since its content related.

**Comment by JustWaveThings** [comment]
Sorry. I thought I was in the right place.

**Comment by JustWaveThings** [comment]
Another user reporting issue with this codelab.  https://discord.com/channels/505093832157691914/664184123061174274/1124507186505207909

**Comment by CouchofTomato** [comment]
Thanks @JustWaveThings

**Comment by Lofty-Brambles** [comment]
As of now, I think it's a better option to throw up a quick temporary notice regarding this if it's needed. The revamped sections aren't dealing with a BaaS solution anymore, as far as the lessons seem to go, so it's probably not something worth working on...

**Comment by Asartea** [comment]
Something like

```
<div class="lesson-note lesson-note--warning">
  <p>Some people have reported running into issues when doing the Firebase codelab. If this affects you you can skip it for now</p>
```

ought to do the trick?

**Comment by CouchofTomato** [comment]
Yeah something like that is fine.

**Comment by Asartea** [comment]
@JustWaveThings did you want to tackle this one? Otherwise I'd be happy to file a PR

**Comment by JustWaveThings** [comment]
@Asartea, no thank you, you can have it. I would suggest that the error is happening at the emulator step, though.

**Comment by ManonLef** [comment]
We have a temp solution with the merge above stating that if issues arise, firebase code lab can be skipped. 
I'm not sure if we want to proceed looking for an alternative or if we want to close this issue because the revamp will make this a non-issue.

**Comment by Asartea** [comment]
That depends a bit on the ETA of the revamp; if its still months+ away it might be worth to spend the time finding an alternative, but if its relatively close it might not be worth the effort

**Comment by ManonLef** [comment]
Indeed

**Comment by ChargrilledChook** [comment]
@01zulfi can this be closed?

**Comment by 01zulfi** [comment]
@ChargrilledChook I'm not sure we should close this now since it is still an issue we haven't addressed it yet apart from adding a lesson note. Though the new React course will make this issue outdated; closing this after the new course ships makes sense to me.

**Comment by JustWaveThings** [comment]
Good to close. Non-issue now.  I have the option to close, but I don't know if that's appropriate for me to do, so I won't.  :)

**Comment by 01zulfi** [comment]
Thanks @JustWaveThings, this issue is definitely outdated with the new React course
