### ISSUE TITLE
<Intermediate HTML and CSS>: <Apparently misworded header in lesson>

### ISSUE THREAD

**Issue by Leo-U** [TheOdinProject/curriculum#25704]
### Describe your suggestion

The Advanced Selectors lesson of the Intermediate HTML and CSS course includes a heading entitled Parent and Sibling Combinators. I have checked the lesson, and I can't find any mention of a "parent combinator", either in the lesson body or in the linked assignments. I did a brief google search and it doesn't seem to be a thing. I'd appreciate it if others could confirm if I'm right. If I'm right, then I suggest that the header be reworded. Could "parent combinator" just be a typo for "child combinator"?

Note: apparent miswording is present in both Ruby and Node paths.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/intermediate-html-and-css-advanced-selectors#parent-and-sibling-combinators

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Hey @Leo-U 

Yeah I think it's meant to be child instead of parent. You haven't indicated you want to work on this so I'll open it up for others to work on.

**Comment by sum4n** [comment]
Hello. I would I like to fix it. I'm doing "Using Git in the Real World" lesson. It would be a great practice.

**Comment by ManonLef** [comment]
@sum4n all yours!
