### ISSUE TITLE
<Intro to CSS>: <Reorganizing structure of explanations>

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#25719]
### Describe your suggestion

I was looking through the ID and Class portions of the Selectors lesson. I think it would be beneficial to put this statement "The major difference between classes and IDs is that an element can only have one ID. An ID cannot be repeated on a single page, and the ID attribute should not contain any whitespace at all."  in the beginning paragraph. Here's what I mean:

* ID selectors are similar to class selectors. They select an element with the given ID, which is another attribute you place on an HTML element. The major difference between classes and IDs is that an element can only have one ID. It cannot be repeated on a single page and should not contain any whitespace. 

By doing this, the explanation would be clearer to learners and they know how to use it effectively early on. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

### (Optional) Additional Comments

I just want to say that's been awesome contributing to the curriculum, and I can't wait to think of more ways to continue its improvement.

**Comment by CouchofTomato** [comment]
@TheOdinProject/intermediate-html-css Can someone take a look at this please.

**Comment by CouchofTomato** [comment]
@CBID2 I'm not against this and think it's a pretty good idea but I've tagged the html/css team to see if anyone else has any input.

**Comment by CBID2** [comment]
> @CBID2 I'm not against this and think it's a pretty good idea but I've tagged the html/css team to see if anyone else has any input.

Great thanks @CouchofTomato! 😊

**Comment by codyloyd** [comment]
Yep. Works for me. Do it.

**Comment by CBID2** [comment]
> Yep. Works for me. Do it.

Thanks @codyloyd! :)
