### ISSUE TITLE
Bug: Interactive Scrim's aren't displaying

### ISSUE THREAD

**Issue by shravzzv** [TheOdinProject/curriculum#25725]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
An unresponsive gray area appears in the section where an interactive example is suppossed to be:

![odinIssue](https://github.com/TheOdinProject/theodinproject/assets/94429984/af0b1c1a-e5c9-408c-9850-902717ff5d6a)

**2. How To Reproduce:**
1. Sign in
2. Visit a [lesson](https://www.theodinproject.com/lessons/foundations-the-box-model#lesson-overview)
3. Scroll to an interactive area

**3. Expected Behavior:**
1. Sign in
2. Visit a lesson page
4. The Interactive section does not update

**4. Desktop/Device:**

-   Device:  HP laptop
-   OS:  Windows
-   Browser:  Chrome
-   Version:  Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by KevinMulhern** [comment]
Thanks for reporting @shravzzv. I think we've seen this before and it was adblocker or some other extension conflicting with them.

Do they work in incognito mode for you?

**Comment by ManonLef** [comment]
@KevinMulhern probably related: https://github.com/TheOdinProject/curriculum/issues/25720

**Comment by KevinMulhern** [comment]
Nice! thanks @ManonLef 💪 

Yep I think it is, seeing a console error about allow-scripts not being the iframe on the box model lesson. We'll need to fast track that issue if this is broken for some people.

**Comment by KevinMulhern** [comment]
Pushed out those missing attributes, still seeing console errors but it might be ok.
@shravzzv when you get a moment, would you mind checking if that scrim now works ok for you please?

**Comment by shravzzv** [comment]
@KevinMulhern, @ManonLef  thanks for seeing into this issue. But I don't think the scrim is working properly. 
![Screenshot_2023-07-02-20-45-01-62_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/TheOdinProject/curriculum/assets/94429984/12c9f690-c4cf-49bd-87a1-37946b2c0564)
[here's the exact link](https://www.theodinproject.com/lessons/foundations-the-box-model#lesson-overview)

**Comment by KevinMulhern** [comment]
Thanks for reporting back @shravzzv, did you try it in an incognito window too? if we can rule out adblockers and other extensions, it will greatly narrow down this issue.

**Comment by shravzzv** [comment]
Yes, I tried it in an incognito window too.

**Comment by shravzzv** [comment]
The issue is resolved. I had third-party cookies blocked on my browser. After enabling them, I see the interactive explanations working properly. 
Thank you.
