### ISSUE TITLE
Intro to CSS: Sandbox Scrimba links

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#25720]
### Describe your suggestion

There are apparently still some unboxed scrimba links left I missed last time. All of these should also get `sandbox="allow-scripts allow-same-origin allow-popups"` set on the iframe. See #25041 for background details.

```[tasklist]
### Full list of affected files
- [x] [the-box-model.md](https://github.com/TheOdinProject/curriculum/blob/main/foundations/html_css/css-foundations/the-box-model.md?plain=1#L17)
- [x] [the-cascade.md](https://github.com/TheOdinProject/curriculum/blob/main/foundations/html_css/css-foundations/the-cascade.md?plain=1#L15)
- [x] [block-and-inline.md](https://github.com/TheOdinProject/curriculum/blob/main/foundations/html_css/css-foundations/block-and-inline.md?plain=1#L16)
- [x] [intro-to-css.md](https://github.com/TheOdinProject/curriculum/blob/main/foundations/html_css/css-foundations/intro-to-css.md?plain=1#L15)
```

### Path

Foundations

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

asarta

**Comment by KevinMulhern** [comment]
Thanks for taking the time to put this together @Asartea 🚀 

We have another issue which might be caused by these missing attributes. Gonna take this on myself just to get it done sooner.
