### ISSUE TITLE
Rails/Express: Rewriting the description of Railways as a possible deployment option.

### ISSUE THREAD

**Issue by Lofty-Brambles** [TheOdinProject/curriculum#25730]
### Describe your suggestion

Railways has recently changed from a monthy $5 or 500 hour free plan to a one-time-use $5 or 500 hour free plan. 
They "award" certain active devs a monthy recurring 500 hour free plan, but the process for applying for such a role is vague.
They have a newer $5 plan with 8GB RAM and 100GB space with unlimited up-time, which seems like a good plan.
The newer details are mentioned here: https://railway.app/pricing
They have a blog post regarding this change here: https://blog.railway.app/p/introducing-trial-hobby-pro-plans

A PR to this should fix the details in the deployment lessons under rails and express sections.

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

_lofty.dev

### (Optional) Additional Comments

We do, love open source :D

**Comment by CouchofTomato** [comment]
Thanks @Lofty-Brambles 

It's all yours.
