### ISSUE TITLE
Foundations Course: Security issues with opening links in new tabs [HTML]

### ISSUE THREAD

**Issue by Shadow5634** [TheOdinProject/curriculum#25735]
### Describe your suggestion

Course/Path: Foundations
Section: HTML Foundations
Lesson: Links and Images

I was going through the [additional resources](https://www.theodinproject.com/lessons/foundations-links-and-images#additional-resources) part of the links/images lesson of HTML and found about the target attr of the anchor tag and its use to open tabs in a new window [[https://internetingishard.netlify.app/html-and-css/links-and-images/index.html#link-targets](https://internetingishard.netlify.app/html-and-css/links-and-images/index.html#link-targets)]. 

I searched up about it more online and found out that if you want the target to be "_blank" (opens in new tab) you want to pair that with a rel="noopener noreferrer" for some security reasons about phishing (I don't understand it well myself) [[https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/](https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/)]. 

However the additional resources link fails to mention this clearly - it has a link to the mdn document pages that mentions it but I feel that people would not typically click on that link thus missing out on vital information. The mdn page mentions that most modern browsers do it themselves and thus adding a  rel="noopener noreferrer" might not be needed but it might still be good practice that one should have.

As a result, I feel that it might be helpful for the TOP webpage about links and images to cover this to ensure that learners don't pick up half and dangerous knowledge.

### Path

Foundations Path

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images#additional-resources

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Animw

**Comment by CouchofTomato** [comment]
@codyloyd 

Are you able to offer an opinion on this please mate

**Comment by CBID2** [comment]
Can I work on this once the verdict is made @codyloyd and @CouchofTomato?

**Comment by ManonLef** [comment]
@CBID2 We will first ask the person that opened the issue since they indicated they'd like to work on this themselves. If they changed their mind we can pass it on :)

**Comment by CBID2** [comment]
> @CBID2 We will first ask the person that opened the issue since they indicated they'd like to work on this themselves. If they changed their mind we can pass it on :)

Ahh ok. I’ll review the PR if they decide to work on it

**Comment by Shadow5634** [comment]
Just to confirm, I (the author) should not begin work on this until I am assigned it right?

**Comment by CBID2** [comment]
> Just to confirm, I (the author) should not begin work on this until I am assigned it right?

I recommend that @Shadow5634. Do you still want to work on it?

**Comment by Shadow5634** [comment]
Yes, I would like to contribute how much ever I can (may not be much since I am still in the Foundations course, but would like to get any usage experience I can).

**Comment by rlmoser99** [comment]
@Shadow5634 You are now assigned and are free to work on this issue.

**Comment by Shadow5634** [comment]
Just created a PR. Wow this took some time. Do let me know of any suggestions to this specific PR and how I can become better at contributions in general.
