### ISSUE TITLE
curriculum-repo: fix discord naming example

### ISSUE THREAD

**Issue by Lofty-Brambles** [TheOdinProject/curriculum#25732]
### Describe your suggestion

Since discord has moved on to pomelo naming schemes, the optional discord name field's placeholder should reflect so.

This can be a good first issue.
Change of location: curriculum/.github/ISSUE_TEMPLATE/suggestion.yaml

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

_lofty.dev

**Comment by CBID2** [comment]
I can do it! :)

**Comment by mosmn** [comment]
I am currently progressing through the material on [Using Git in the Real World](https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world#a-git-workflow-for-open-source-contribution), and I am open to actively participating in making this modification.

**Comment by ManonLef** [comment]
All yours @mosmn !
