### ISSUE TITLE
Intermediate HTML and CSS: Fix ordering of sections 'Knowledge Check' and 'Additional Resources'

### ISSUE THREAD

**Issue by DevVivan** [TheOdinProject/curriculum#25736]
### Describe your suggestion

I have noticed that some lessons in the Intermediate HTML and CSS course have issues with the positioning of the final two sections and would like to work on resolving it. This is when the section titled 'Knowledge Check' is below the section titled 'Additional Resources'. According to the Layout Style Guide, it seems as though this is not correct. Therefore, I think moving the 'Knowledge Check' section above the 'Additional Resources' section in the lessons where the issue persists would fit much better according to the Layout Style Guide.

The lessons in which this issue stands is as follows. I will be formatting them as task lists for me to work on them and tick off accordingly.

- [x] Advanced Selectors
- [x] CSS Functions
- [x] Browser Compatibility
- [x] Form Validation
- [x] Introduction to Grid
- [x] Creating a Grid
- [x] Positioning Grid Elements
- [x] Advanced Grid Properties
- [x] Using Flexbox and Grid

I would like to work on this issue.

### Path

Node / JS

### Lesson Url

Following lessons: Advanced Selectors,  CSS Functions, Browser Compatibility, Form Basics, Form Validation, Introduction to Grid, Creating a Grid, Positioning Grid Elements, Advanced Grid Properties, Using Flexbox and Grid

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

VivPro

**Comment by DevVivan** [comment]
Should I create a separate branch for each of the lessons?

**Comment by CouchofTomato** [comment]
@DevVivan 

No need. One PR should be fine because it's the same problem for each lesson.

**Comment by ManonLef** [comment]
@DevVivan It will automatically close upon merge if you use: `Closes: #issueNumber` instead of `Related to: #issueNumber`

that's no problem however. I will close this. Thanks again!
