### ISSUE TITLE
Document existence of lesson note classes

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#25744]
### Describe your suggestion

TOP provides the ability to style blocks of texts as notes by wrapping them into a div with a class of ``lesson-note` as well as an optional note type. The existence of these notes however is documented nowhere in this repo as far as I am aware/can find, _except_ in the lesson template and example. Those are files aimed more at people who are aiming to add an entire new lesson, and are likely to be overlooked by someone who is just looking to make a change. 

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

asarta

### (Optional) Additional Comments

Could potentially be a good first issue for someone? Not sure

**Comment by CouchofTomato** [comment]
Perhaps the contributing guide would be a good place. Or did you have somewhere else in mind?

**Comment by Asartea** [comment]
> Perhaps the contributing guide would be a good place. Or did you have somewhere else in mind?

I think as it stands it would make more sense in the Layout Guide? Currently CONTRIBUTING.md contains really no repo specific instructions for the curriculum outside of read the style guide and use the preview tool, while layout guide contains all the markup instructions

**Comment by Asartea** [comment]
That one yes; completely forgot its called Layout Style and not Layout ;)

**Comment by ManonLef** [comment]
Assigned it to you @Asartea for addition into the layout style guide ☺️

**Comment by ManonLef** [comment]
@Asartea checking in to see how this is coming along. I think it would be nice to include the different notes/warnings etc.

**Comment by Asartea** [comment]
@ManonLef was busy with the main repo; should have a PR in a day or so
