### ISSUE TITLE
<Foundations>: <Required attribute>

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#25748]
### Describe your suggestion

I was looking through the Form Validation lesson and thought it would beneficial to mention the `required` attribute. It’s a simple and slightly easier to way for learners to learn about validation.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/intermediate-html-and-css-form-validation

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

**Comment by ManonLef** [comment]
Hi there @CBID2 

I might be missing something but the `required` attribute is mentioned right at [the beginning of this lesson](https://www.theodinproject.com/lessons/intermediate-html-and-css-form-validation#required-validation).

Is there something you think there's missing?

The Assignment section also has a couple of links that go deeper into the subject and the `required` attribute is covered there as well.

**Comment by CBID2** [comment]
> Hi there @CBID2 
> 
> 
> 
> I might be missing something but the `required` attribute is mentioned right at [the beginning of this lesson](https://www.theodinproject.com/lessons/intermediate-html-and-css-form-validation#required-validation).
> 
> 
> 
> Is there something you think there's missing?
> 
> 
> 
> The Assignment section also has a couple of links that go deeper into the subject and the `required` attribute is covered there as well.

Ohh thanks
