### ISSUE TITLE
Javascript-Git: Improve instructions for opening Git commands in a text editor

### ISSUE THREAD

**Issue by mosmn** [TheOdinProject/curriculum#25746]
### Describe your suggestion

While progressing through the "A Deeper Look at Git" lesson in the JavaScript course, I encountered an issue with running Git commands that required opening a text editor, such as git commit --amend and git rebase -i. The default behavior was to open the text editor in the CLI, preventing me from saving and closing the editor after making changes. Like so:

![Screenshot 2023-07-04 at 5 42 39 PM](https://github.com/TheOdinProject/curriculum/assets/104483181/29883891-61be-4961-80cb-f3552cee6e2d)

After researching a solution, I found that running the command `git config --global core.editor "code --wait"` resolved the issue.

![Screenshot 2023-07-04 at 6 09 47 PM](https://github.com/TheOdinProject/curriculum/assets/104483181/4afae8f3-49b7-4eff-9a78-3fed61e355c2)

I suggest improving the instructions in the lesson to address this issue and provide a better user experience for learners. Additionally, it would be beneficial to introduce Gitlense interactive rebase tool as an alternative for changing multiple commits, which provides a more user-friendly interface than the standard text editor.

![Screenshot 2023-07-04 at 6 06 16 PM](https://github.com/TheOdinProject/curriculum/assets/104483181/9927d97a-04dd-4e18-8533-9e6a577d0c14)

Find attached screenshots illustrating the problem and the solution for reference. Let me know if you need any further information or clarification.

Thank you for considering this improvement suggestion.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git#changing-history

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mosmn

**Comment by Mclilzee** [comment]
Sitting up your code editor is mentioned in Git Basics lesson: https://www.theodinproject.com/lessons/foundations-git-basics#changing-the-git-commit-message-editor

Maybe it would be a good idea to add a link to it in `A Deeper Look at Git` as a reminder, since it comes way after in the course, and people who have forgotten to set it up already from Git Basics, get reminded to do so.

**Comment by CouchofTomato** [comment]
Yeah I agree explicitly linking setting up the code editor early on might be beneficial.

That is probably the best solution.

**Comment by mosmn** [comment]
It seems I missed the mention of setting up the code editor in the Git Basics lesson. Since I took the basics course a while ago, I don't remember coming across this issue with them. Adding a link to the Git Basics lesson in the "A Deeper Look at Git" lesson as a reminder is a great suggestion. It will help learners who might have forgotten to set it up already.

Also, i would like to get your input on the Gitlense interactive rebase tool.

**Comment by CouchofTomato** [comment]
We generally try as much as possible to avoid recommending tools to do the heavy lifting before the user has learned the basics. It could _perhaps_ be added as an additional resource.
