### ISSUE TITLE
Foundations: Correcting Outdated External Code

### ISSUE THREAD

**Issue by savwiley** [TheOdinProject/curriculum#25745]
### Describe your suggestion

The exercises on the **DOM Manipulation and Events** lesson are known to be outdated, and you guys make mention about `keycode` now just being `code`. However, while coding along with the videos, I found that Wes Bos' use of `this` also no longer works as he intended.

A user can correct the error and continue the lesson by changing `this` to `e.target`. While he mentions using `e.target` earlier in the first video, he doesn't use it or mention it during the steps he uses `this`. My concern was that people brand new to JavaScript may not know that they can use it.

Also, specifically in regards to the second video, most of what he performs doesn't react the same anymore. He intends for every class in the body to appear in console when clicking the innermost div, but that div's class just repeats instead. This is fine, the lesson gets the right information across eventually, but new learners may be confused or think they're following along incorrectly for the first six minutes or so.

I just thought that giving a quick note to learners about these things could be helpful and wanted to at least let you know it existed. Couldn't find an issue/pull about this, so I'm sorry if this is already known. Either way, thank you!

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events#exercise

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

.jay.bee

**Comment by CouchofTomato** [comment]
Thanks @savwiley 

Do you know of any other resources that might be a better fit now?

**Comment by savwiley** [comment]
Hi, @CouchofTomato!

Well, while outdated, I think Wes Bos' videos teach a lot of useful information while making it fun and interactive. Like learning how to manipulate the keyboard itself to work with elements in a page. It's pretty interesting.

That said, I did some digging that could probably supplement it, at least.

* [MDN's article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#active_learning_a_dynamic_shopping_list) on manipulating documents retreads some of what was talked about in the lesson and a few things from Wes Bos' videos, like the use of `window`. There are a couple of activities for learners to code along, not to mention a little foreshadowing of the Todo List project further down the JS line.
* [This article from Medium](https://medium.com/nerd-for-tech/manipulating-the-dom-with-html-javascript-and-css-part-1-25b34ae2f932) is another precursor of the Todo List project and has a lot of interactivity. Learners are also made to work with strings in an array and `.map()`, which was touched on in earlier lessons but hasn't really been put into practice yet.
* [This Section.io article](https://www.section.io/engineering-education/dom-manipulation-with-javascript/) is about yet another Todo List with interactivity. I don't feel it's as thorough as the first two, but it goes into how DOM's are structured in HTML and covers some instances with using `target` in events.
* Lastly, the [JavaScript DOM section](https://www.javascripttutorial.net/javascript-dom/) from JavaScript Tutorial is very thorough and could be a great resource for users to look back on if they need to remember a particular issue in the future. It's a **lot** of reading, though, but can be very helpful.

I hope this helps! I looked through YouTube but couldn't find anything of Wes Bos' caliber that wasn't through another organization like FreeCodeCamp.

**Comment by CouchofTomato** [comment]
Thanks @savwiley 

That's really thorough and much appreciated. I've asked someone from the JS team to take a look and give their opinion on the best way forwards.

**Comment by Raymond-Adams** [comment]
This may also be helpful (and includes exercises): https://javascript.info/introduction-browser-events

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by ManonLef** [comment]
The [MDN article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#active_learning_a_dynamic_shopping_list) including the "test your skills" assignment should in my opinion be enough to cover all that's needed for the next projects to come.

The second assignment video currently in the lesson on bubbling and event propagation will have to stay put. @savwiley is that assignment still up to date and can it be coded along with?

[the JS tutorial on DOM](https://www.javascripttutorial.net/javascript-dom/) although very thorough, is quite likely too overwhelming for learners at this stage. It would be a great additional resource with the strong disclaimer that it covers a lot of things not required in the foundational projects. I thought we could perhaps cherrypick and add the first sections but in my opinion it also lacks disclaimers on the older `getElementById` etc. vs `querySelector`. Going through those sections I'd consider assignment worthy, I came to the conclusion that the MDN article above already does a great enough job at covering all those. 

[This Article with accompanying video](https://medium.com/nerd-for-tech/manipulating-the-dom-with-html-javascript-and-css-part-1-25b34ae2f932) is actually quite solid. I think it's a bit advanced in some spots, but so is the Wes Bos video. 

My proposal: 
- [Code along with this video/written explanation](https://medium.com/nerd-for-tech/manipulating-the-dom-with-html-javascript-and-css-part-1-25b34ae2f932) 
- [Tie it all together with this article and test your skills!](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#active_learning_a_dynamic_shopping_list)

Curious to hear if other maintainers have opinions on this.

**Comment by savwiley** [comment]
@ManonLef sorry I'm late in replying!

To answer your question about the second video: for the most part, yes. What Wes Bos is trying to teach does still get across. The only real problem is that coding along with it doesn't yield the *exact* same results as the video for the first several minutes. It still works to a degree, but learners might get confused by it or think they're doing something wrong when they aren't. If they stick with it, though, their code and the code in the video ends up outputting the same information with no changes needed.

What I mean about the results not being the exact same, is that when Wes Bos intends for every class in the body to print to console, the class of the element being clicked prints to console repeatedly, as many times as there are elements in the body. The other classes print but they also repeat in a similar fashion. The change is slight. It's just enough to be a little confusing.

**Comment by ManonLef** [comment]
That's okay @savwiley thanks for elaborating. 

Then that would also mean that a different resource might be required to address event propagation and bubbling. 
I'll wait for other maintainers to chime in with thoughts as well.

**Comment by wise-king-sullyman** [comment]
@ManonLef I agree with your proposal.

For the second video would it be adequate for us to just add a note that warns learners about the slight difference in behavior?

**Comment by ManonLef** [comment]
I think it might be @wise-king-sullyman but it's hard to judge without going through it first. For me personally it's been a while. I've opened it up because we have sufficient resources to pick from. Then the one taking this on would ideally check the difference in output and note that. We can then discuss said solution on the PR :)

**Comment by ZachBaird** [comment]
I can take this.

**Comment by CouchofTomato** [comment]
All yours @ZachBaird

**Comment by ZachBaird** [comment]
@wise-king-sullyman @ManonLef 

I spent some time thinking about how we could bring in these new assignments while retaining the old ones. I ended up settling on going with @ManonLef 's suggestion while moving the existing assignments into extra credit as-is. Additionally, I included the JS Tutorial link as extra credit specifying the sections students may find useful (though section 7 gets much further into events than the lesson does).

I just wanted to share it first before making a PR to get your thoughts. It is formatted as such:

<img width="769" alt="Screenshot 2023-09-09 at 12 10 09 PM" src="https://github.com/TheOdinProject/curriculum/assets/30800863/50708eca-1362-4b85-a0dd-36a50524194b">

**Comment by wise-king-sullyman** [comment]
I'm still not 100% sure how I feel about it and will mull it over a bit more, but something about that feels odd to me. I think it's that "extra credit" assignments are typically reserved for projects.

If we think the old assignments are worth keeping in what would you think about having them as additional resources? I think that's more where that kind of stuff would typically go with our current lesson structure. Admittedly though it isn't really a _great_ fit for that either, and this lesson is already overloaded on additional resources 🤔

**Comment by ZachBaird** [comment]
Perhaps we should go the route of this [Node.js lesson](https://www.theodinproject.com/lessons/nodejs-getting-started)? It appears that that extra credit stuck around for exactly the same reason as this would, though I don't know the history on this lesson.

**Comment by thatblindgeye** [comment]
Personally any "extra credit"/"optional" assignment items are more Additional Resource material. The Node JS would be in need of an update as well. @ManonLef wdyt?

**Comment by ManonLef** [comment]
Thanks so much  for looking at this with us @ZachBaird !

I agree with the extra credit looking "off" here since usually all assignment items are expected to be completed unless it's a project as Sully mentioned. If it's not required to progress, I'd prefer it in additional resources as well. 

@ZachBaird did you go through the resources? If so, I'd be curious what exact topics we're still missing if we were to leave the assignment section to the first two links only. I'd be afraid that event propagation and bubbling wouldn't be touched upon or not enough but it's been a while. IF that's the case, we might have to keep it in the assignment (without the extra credit), but add a note as applicable taking the below information from @savwiley into account. Might have to double check the video to be more specific about the discrepancies. 
> To answer your question about the second video: for the most part, yes. What Wes Bos is trying to teach does still get across. The only real problem is that coding along with it doesn't yield the exact same results as the video for the first several minutes. It still works to a degree, but learners might get confused by it or think they're doing something wrong when they aren't. If they stick with it, though, their code and the code in the video ends up outputting the same information with no changes needed.

If we're not sure about the above, I'd be happy to help go through the current resources, make a definitive list of topics covered in the current lesson and the gaps that come from changing to the proposed setup. It seems like a bit of work so might not be bad to team up on going through the code along videos.

**Comment by ZachBaird** [comment]
If we went with just the top two resources, the material covered in Wes's 2nd video is pretty much not covered by the first 2 resources @ManonLef. There's really no mention of bubbling, more on event capture and propagation, etc.

Of the new resources, that thorough JS Tutorial one _does_ cover that in Section 7.

I think perhaps the medium article should be left behind and we swap out Wes's first video with the MDN assignment, and Wes' second video with the JS Tutorial's Sections 1, 2, and 7 (or just 7, if we want to keep that assignment entirely focused on events).

**Comment by wise-king-sullyman** [comment]
I'd be on board with that plan.

**Comment by ZachBaird** [comment]
Went ahead and spun up a PR with that in mind.
