### ISSUE TITLE
 The Cascade - Foundations Course: CSS correction 

### ISSUE THREAD

**Issue by msfonrouge** [TheOdinProject/curriculum#25752]
### Describe your suggestion

<div class="main">
  <div class="list" id="subsection"></div>
</div>

## old code
/* rule 1 */
#subsection .list {
  background-color: yellow;
  color: blue;
}

/* rule 2 */
#subsection .main .list {
  color: red;
}

## correction

/* rule 1 */
#subsection.list {
  background-color: yellow;
  color: blue;
}

/* rule 2 */
.main #subsection.list {
  color: red;
}

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade#the-cascade-of-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Is this linked to another issue?

**Comment by msfonrouge** [comment]
My bad. Missed #25742
