### ISSUE TITLE
Foundations Course: Deletion of Section in Intro to CSS lesson

### ISSUE THREAD

**Issue by Shadow5634** [TheOdinProject/curriculum#25768]
### Describe your suggestion

Course: Foundations
Section: CSS Foundations
Lesson: Intro to CSS

The [Intro to CSS](https://www.theodinproject.com/lessons/foundations-intro-to-css) lesson covers some CSS basics like definition of important terms, adding CSS to HTML files, basic properties, etc. One section is the [Order Matters](https://www.theodinproject.com/lessons/foundations-intro-to-css#order-matters) section that goes into how rules/selectors of same specificity interact - the bottom one wins.

**However I feel that the this section is best removed from here.** This is because of two main reasons:

1. First it mentions the word "**specificity**" which the reader will most likely not know and is not expected to know since this is covered in the [next lesson](https://www.theodinproject.com/lessons/foundations-the-cascade). This may confuse the reader (at least that was what happened with me). I feel that covering this content will make much more sense after one gains an understanding of the Cascade which is the crux of the next lesson.

2. This part is covered again in the next lesson in the Rule Orders part of [The Cascade of CSS](https://www.theodinproject.com/lessons/foundations-the-cascade#the-cascade-of-css) section (or to locate more easily just above the [Assignment](https://www.theodinproject.com/lessons/foundations-the-cascade#assignment) section). This duplication seems unnecessary.

In essence, I feel that the [Order Matters](https://www.theodinproject.com/lessons/foundations-intro-to-css#order-matters) section is duplicative and may be getting into concepts that are too specific/complex for the Intro to CSS lesson.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css#order-matters

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Animw

**Comment by codyloyd** [comment]
I agree with this assessment.  that content is very important, of course.. but it is covered later and doesn't need to be introduced here.

**Comment by codyloyd** [comment]
@Shadow5634 do  you want to do this work?

**Comment by Shadow5634** [comment]
Yes. As highlighted I can just go ahead and create a PR with this section **deleted** right?
