### ISSUE TITLE
Git Basics: Adding another command to Cheatsheet

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#25765]
## Proposed Suggestion 
I recently learned this Git command: `git commit -am "message"`. I think it's fitting to add it to the cheatsheet. 
##Benefits 
It would help learners increase productivity when committing their code to a repository.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

**Comment by CouchofTomato** [comment]
I think productivity needs to come after learners understand the git flow. Taking shortcuts too early can be detrimental to learning how git is working under the hood to track changes. We need to be careful about adding shortcuts when we're trying to teach the basics of a subject. Happy to hear from others on this though.

**Comment by ManonLef** [comment]
I am of the opinion that this is a more advanced command for users that know what’s happening with their files. Most learners already stage too many files in one commit until they get more comfortable with the workflow. I see a lot of those where a JS, HTML and CSS file get committed with an message `fix function string` for example.

I believe there’s a benefit for new learners in mindfully going through the motions of purposely adding specific files and considering what changed for their commit message.

**Comment by CBID2** [comment]
> I think it would bring more confusion to new git users because it does not work for new files. This would be unexpected behavior and overcomplicate it for new learners.
> 
> 
> 
> > -a
> 
> --all
> 
> Tell the command to automatically stage files that have been modified and deleted, but new files you have not told Git about are not affected.
> 
> 
> 
> https://git-scm.com/docs/git-commit
> 
> 

Ooh good point. Maybe this could go in the intermediate courses?

**Comment by rlmoser99** [comment]
I am not sure I am a fan of this tip to improve productivity, because it takes me more time to recall if I have any new files, then to just type `git add .` and `git commit -m "..."` I honestly do not think it belongs in any of our lesson as our "in house content" for the reasons that have already been stated.

**Comment by CBID2** [comment]
> I am not sure I am a fan of this tip to improve productivity, because it takes me more time to recall if I have any new files, then to just type `git add .` and `git commit -m "..."` I honestly do not think it belongs in any of our lesson as our "in house content" for the reasons that have already been stated.

I understand

**Comment by rlmoser99** [comment]
Going to close this issue, since it has been decided to not add to our curriculum.
