### ISSUE TITLE
Foundations: Inconsistent Git instructions

### ISSUE THREAD

**Issue by crystalsolenoid** [TheOdinProject/curriculum#25763]
### Describe your suggestion

Step 3 in the Revisiting Rock Paper Scissors assignment instructions currently says this:
> Once you’re all done with your UI and made sure everything’s satisfactory, commit your changes to the rps-ui branch.

This implies the student should go against the advice to commit early and often from the top of the assignment instructions and [the commit messages lesson](https://www.theodinproject.com/lessons/foundations-commit-messages), which I don't think is intended, right? It gave me a little pause when going through this lesson, and then I saw someone else ask for clarification about it on Discord as well.

I looked through the blame for why this step was written, and found this commit, explaining that the motivation was to make sure people knew to commit before merging. 59b9474 

So a change would have to both remove this implication while still keeping the value that commit added. Maybe something like this?
> Once you’re all done with your UI and made sure everything’s satisfactory, ensure all of your changes are committed to the rps-ui branch with `git status` before continuing.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

Having a great time with TOP so far, thank you to everyone who's worked so hard on it!

**Comment by CBID2** [comment]
Since you haven't checked the second box in the "Checks" section, do you mind if I work on this issue @crystalsolenoid?

**Comment by crystalsolenoid** [comment]
@CBID2 No, I don't mind! :)

**Comment by CBID2** [comment]
> @CBID2 No, I don't mind! :)

Thanks @crystalsolenoid! :) If you like, I love to have your review of my PR once I publish it. If you need help, here is an article I wrote on [giving feedback](https://www.freecodecamp.org/news/code-review-tips/).

**Comment by 01zulfi** [comment]
Great suggestion @crystalsolenoid, this definitely needs to be updated.

Hey @CBID2, please wait for a maintainer to triage the issue and having it assigned to you before starting work on it. That said, I'm assigning the issue to you now, good luck on the pull request.

**Comment by CBID2** [comment]
Hi @crystalsolenoid! :) Here's my [PR](https://github.com/TheOdinProject/curriculum/pull/25792)

**Comment by crystalsolenoid** [comment]
Thank you! Just commented.

**Comment by CBID2** [comment]
> Thank you! Just commented.

It got merged @crystalsolenoid! :) Thanks for your help! :)
