### ISSUE TITLE
Bug: Expected vs. actual behavior is different in lesson because code snippet uses a later version than default 

### ISSUE THREAD

**Issue by RyanNDao** [TheOdinProject/curriculum#25779]
Complete the following REQUIRED checkboxes:

-   [ X ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ X  ] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ X ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Under [this section of the React testing pt1 lesson](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1#simulating-user-events), the expected behavior differs from the actual behavior.
The instructions expect that pasting in the code in their respective files, the UI tests will pass. However, only one test passes while the other one fails with an error saying the setup function is not found. 

![image](https://github.com/TheOdinProject/theodinproject/assets/10081834/853cbeab-4def-441a-ad75-3651b37a0f47)

This is because create-react-app uses a default v13 for @testing-library/user-event while setup() uses v14 ([source](https://stackoverflow.com/questions/72186021/cant-find-setup-on-userevent))

**2. How To Reproduce:**

1. Go to [this section](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1#simulating-user-events)
2. Use create-react-app to create a new react app: `npx create-react-app {filename}`
3. Navigate to the package.json and check the dependencies and look for what version _@testing-library/user-event_ is using. By default, react-scripts 5.0.1 (latest version of create-react-app) should be _"@testing-library/user-event": "^13.5.0"_.
4. Replace the App.js and App.test.js in your newly created create-react-app to the code in the _Simulating User Events_ section snippets
5. Run `npm test App.test.js` in the terminal

**3. Expected Behavior:**

Expected behavior: Both tests, "**renders magnificent monkeys**" and "**renders radical rhinos after button click**" should pass
Actual behavior: Only  "**renders magnificent monkeys**" passes. The other test, "**renders radical rhinos after button click**", throws the following error:  TypeError: _userEvent.default.setup is not a function.

**4. Desktop/Device:**

-   Device:  Xubuntu VM - host computer is a Windows 11 Lenovo laptop
-   OS: Ubuntu 22.04
-   Browser: Chrome
-   Version: 113.0.5672.92

**5. Additional Information:**

Even though in the lesson section, it references that v14 has different features than v13, this issue is not addressed. Using the legacy code underneath, the test still fails.
![image](https://github.com/TheOdinProject/theodinproject/assets/10081834/c9c5a979-79b3-4dba-8e9d-df88fb8b3e3d)

**Comment by rlmoser99** [comment]
@01zulfi would you be able to take a look at this issue? I am not familiar with React Testing and would appreciate your input to triage this correctly.

**Comment by 01zulfi** [comment]
Yeah, this is because of the outdated user-event package that ships with create-react-app. Easy fix is to just run the following command:

```
npm install @testing-library/user-event --save-dev
```

The lesson for the new React course fixes this https://github.com/TheOdinProject/curriculum/pull/25670/

For now, we can just add that command to the current lesson, will you be up for that, @RyanNDao?

**Comment by RyanNDao** [comment]
> Yeah, this is because of the outdated user-event package that ships with create-react-app. Easy fix is to just run the following command:
> 
> ```
> npm install @testing-library/user-event --save-dev
> ```
> 
> The lesson for the new React course fixes this #25670
> 
> For now, we can just add that command to the current lesson, will you be up for that, @RyanNDao?

I can take care of that

**Comment by RyanNDao** [comment]
Closed in new react lessons
