### ISSUE TITLE
JS Path: Recursive Methods 

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#25783]
### Describe your suggestion

I think that the Recursive Methods is a great introduction to the idea and implementation of recursion, but I do think that adding one more addition resource would prove quite beneficial.
- I noticed that there is mention of the call stack and recursion, but I think it would be much more beneficial to include a more visually appeasing example of it to get a deeper understanding of how recursion works.
### I Propose *In Assignments*:
That this link: https://medium.com/swlh/visualizing-recursion-6a81d50d6c41
Is put directly under: 1. Read [this recursion resource](https://javascript.info/recursion) for a good intro to recursion.

I think this can help the learner/user understand what is happening behind the scenes with recursion, and is a little more simple that the first resource.  

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mfrayray

**Comment by CouchofTomato** [comment]
There is already quite a lot to take in. Could we possibly add this as an additional resource?

**Comment by ManonLef** [comment]
@CouchofTomato Do we include resources usually that require you to sign up? I have to sign up or sign in to read this medium article. 

I haven’t done so yet so I can’t judge the content but I’ll happily have a look tomorrow.

**Comment by Baguirre03** [comment]
I think this could be an additional resource, it kind of just. helped me visualize the callstack. I also didnt realize it was behind a sign-up wall, so that could prove against this issue.

**Comment by ManonLef** [comment]
It doesn't seem like a paid sub article, but it does require a free medium account at least. 
![Screenshot 2023-07-11 at 11 26 42](https://github.com/TheOdinProject/curriculum/assets/81025586/78443fa5-f265-4993-ade7-1058034ab8fb)

**Comment by CouchofTomato** [comment]
Yeah we still can't really proceed on that basis. We shouldn't force people to sign up to medium. Maybe there is a dev.to article on the matter.

**Comment by Baguirre03** [comment]
Totally agreed, didnt realize it was behind that wall. My bad there.

I feel like there isnt any resource that really visualizes the call stack and recursion, except in a few later projects like BST. I can try to find a different article, but thats the best I could find. Thanks for looking at the issue still!

**Comment by Baguirre03** [comment]
Yeah, I cant seem to find a resource that covers something similar to this. That also isnt in video format. 

If yall would be okay as adding this as an additional resource as @CouchofTomato mentionds, Id be happy to do so. If we feel that isnt needed/not okay because of the sign-up wall I can close this issue!

**Comment by CouchofTomato** [comment]
Yeah I think add it as an additional resource.

**Comment by ManonLef** [comment]
@Baguirre03 I will assign this to you since you have indicated you'd like to work on it.
