### ISSUE TITLE
Git Basics: Typo in "Additional Resources"

### ISSUE THREAD

**Issue by alik-r** [TheOdinProject/curriculum#25791]
### Describe your suggestion

There is a typo in "Additional Resources" section: "...Basics to Advance" should be corrected to "...Basics to **Advanced**"

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by alik-r** [comment]
> May I take it? It will take me minutes but I have read that I have to be assigned.

@Mistermakos Sure. 
I don't think you have to be assigned. Just open a Pull Request (PR) and link the issue, and it will probably be ok.
[Linking a pull request to an issue - GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by Mistermakos** [comment]
Done it. Thank you for help

**Comment by rlmoser99** [comment]
@alik-r Just a heads up, they did need to ask to be assigned before working on the issue. Please see the below section in out contributing guide.

> Ask to be assigned the issue by a maintainer.
If you are not a maintainer, do not give others permission to work on an issue
Wait to be assigned the issue before starting any work.

https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#being-assigned-an-issue

**Comment by alik-r** [comment]
@rlmoser99 I apologize for my misunderstanding. I forgot that being assigned to an issue is required. Thank you for bringing it up!
