### ISSUE TITLE
<Git Basics>: <Missing information on using different branches>

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#25796]
### Describe your suggestion

While I was looking through the [Git Best Practices section](https://www.theodinproject.com/lessons/foundations-git-basics#git-best-practices), I noticed that the command for creating a different branch was missing. I think it would be beneficial to mention this information in this section so learners won't develop the habit of pushing commits from the `main` branch in their repository(this was a habit I finally broke not too long ago), especially if they decide to contribute to the curriculum in the future. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics#git-best-practices

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

**Comment by ManonLef** [comment]
Branches are not covered until later for the “RPS revisited” lesson.

**Comment by rlmoser99** [comment]
Thanks for taking the time to make this issue. I am going to close this, since we intentionally do not mention using other branches in this git basics lesson.
