### ISSUE TITLE
Foundations: Wrong info about cascade in scrimba playground

### ISSUE THREAD

**Issue by piatrashkakanstantinass** [TheOdinProject/curriculum#25800]
### Describe your suggestion

The interactive video in "The Cascade" lesson provides wrong information (that many class selectors can override id selector) about specificity overriding at 5:00.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by rc-gr** [comment]
Hi. I'm actually currently working through the Foundation CSS lessons at the moment and got confused at the Scrimba video. Before long, I came across this issue in hopes of finding corrections to it.

I noticed that the OP did not indicate wanting to work on this issue. If possible, may I request to undertake it instead? I am aware of and have read the contributing guide for the repo.

**Comment by ChargrilledChook** [comment]
All yours @rc-gr
