### ISSUE TITLE
Curriculum: Clean up non-descripitve markdown links

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#25816]
### Describe your suggestion

Both the Layout Style Guide as well as a11y best practices recommend that links should wrap around text that clearly indicates where the link will lead.

[A quick search ](https://github.com/search?q=repo%3ATheOdinProject%2Fcurriculum+%28%22%5Bthis%5D%28%22+OR+%22%5Bthis+article%5D%28%22+OR+%22%5Bthis+video%5D%28%22%29+NOT+path%3A%2F%5Earchive%5C%2F%2F&type=code&p=1)however (using the "dumb" method of simply looking for any occurrence of either `[this](`, `[this article](` or `[this video](`, which should return a large enough percentage of links with issues) shows that those problematic descriptions show up in **52** different lesson files.

These should all be cleaned up (although possibly splitting the PR on a course basis to avoid making too big contributions) by replacing them with descriptive text

### Path

Other / NA

### Lesson Url

N/A; see [GitHub Codesearch](https://github.com/search?q=repo%3ATheOdinProject%2Fcurriculum+%28%22%5Bthis%5D%28%22+OR+%22%5Bthis+article%5D%28%22+OR+%22%5Bthis+video%5D%28%22%29+NOT+path%3A%2F%5Earchive%5C%2F%2F&type=code&p=1) above

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

asarta

**Comment by thatblindgeye** [comment]
@ManonLef We could, yeah.

**Comment by thatblindgeye** [comment]
@Asartea I'm currently doing an audit for Foundations for Style Guide issues. Once I have a list of things to be done, I'll use this issue to track lessons that need some sort of update to links for Foundations, then we can open this up to contributors to work on a lesson from the list.

**Comment by Asartea** [comment]
Sounds good to me; will note that we'll need to do the same to both NodeJS and RoR at some point as well

**Comment by Asartea** [comment]
_gently pikes @thatblindgeye _

**Comment by thatblindgeye** [comment]
@Asartea still on the radar, for now I've added it to the style guide project

**Comment by MaoShizhong** [comment]
@Asartea Just letting you know that we've now started the epic for getting these links all sorted - #27681 
Since there are plenty of sections and more to come with the full stack pathways afterwards, if you wish to be assigned a section then feel free to comment on that issue!

**Comment by Asartea** [comment]
Superseded by #27681
