### ISSUE TITLE
<Objects and Object Constructors>: <Article explaining "this" is a bit hard to understand>

### ISSUE THREAD

**Issue by aRav3n** [TheOdinProject/curriculum#25810]
### Describe your suggestion

The third article in the assignment section is hard to understand at first due to being so technical. This [video](https://www.youtube.com/watch?v=cwChC4BQF0Q) does a good job at explaining and is helpful to watch before reading the article in the assignment section.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

Really loving the course thus far; many thanks for all the hard work and insight from everyone involved!

**Comment by rlmoser99** [comment]
Thanks for taking the time to make this issue. To determine if this video is something we want to add, we need some input from our @TheOdinProject/javascript team.

**Comment by ManonLef** [comment]
I can see it being a useful resource! I'd prefer it to be placed as an additional resource as it doesn't introduce new information and we prefer written articles over video resources.

So adding it as an additional resource with the description of it being a video resource on the `this` keyword and not introducing new concepts, sounds good to me.

**Comment by saltsphinx** [comment]
Hi, would it be fine if I resolved this issue?

**Comment by saltsphinx** [comment]
> Hello, yes that works for me!

hi, I believe only maintainers can give the go ahead on fixing an issue

**Comment by ManonLef** [comment]
@saltsphinx I assigned it to you. Thanks for taking this on!

**Comment by saltsphinx** [comment]
@ManonLef Thank you!
