### ISSUE TITLE
<Getting Hired: What You Can Do To Prepare>: <More actionable ways to Get Good >

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#25822]
### Describe your suggestion

The "Get Good" subsection provides great tips, but I think it would be beneficial to mention more specific ways learners can improve and learn their skills. I've recently read some articles written by people who landed jobs as a result of [participating in the 100 Days of Code challenge](https://www.freecodecamp.org/news/how-freecodecamp-and-100daysofcode-helped-me-get-hired-in-under-a-year/) and [contributing to open source projects](https://dev.to/opensauced/how-i-got-hired-contributing-to-open-source-projects-546i), and I believe this can be a great way to emphasize the importance of getting good. 

##Update
Through other people’s suggestions, I will add the open source suggestion to the Portfolio section and raise a related issue about adding information on 100 Days of Code to the beginning section 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/node-path-getting-hired-what-you-can-do-to-prepare

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

**Comment by CouchofTomato** [comment]
I wouldn't mind an additional section mentioning learners should keep going with their own projects and challenges perhaps. Happy to hear others opinions on this.

**Comment by CBID2** [comment]
> Hi, this is my first time leaving a comment on the open issue, please let me know if isn't encouraged for contributors other than the author/maintainers to leave a comment on open issues.
> 
> I did 100 days of code challenge myself on Twitter because I thought it'd be a good way to discipline myself at the very beginning of TOP. And most of its participants are complete beginners who are motivating one another by tagging #100daysOfCode in their posts. Occasionally there were people still doing the challenge even after their initial 100 days, resetting the day to 0 and starting all over again. But I can say that that is rare.
> 
> Having said that, including a suggestion on 100 days of code challenge is in my opinion a bit out of place, since the Getting Hired Section is the very last course of the entire curriculum. Learners are expected to have coded for over 100 days already.
> 
> If we were to include a suggestion on 100 days of code challenge, I think it'd be a good fit at the beginning of the curriculum - in the foundations course - instead of in the Getting Hired course. And I do think it's a reasonable suggestion, for those who want some more social support and accountability at the start of their programming journey.

Good point @Eveieve! :) Now that I think about it, putting a suggestion for 100 days does seem more fitting at the beginning, so that they could track their progress when they first start the program.

**Comment by CBID2** [comment]
Hey @CouchofTomato! :) Can I be assigned to this issue and make a PR for it? I've agreed with the suggestions being made here and want to move forward :)
