### ISSUE TITLE
NodeJS: Project: Odin-Book

### ISSUE THREAD

**Issue by VACostin** [TheOdinProject/curriculum#25821]
### Describe your suggestion

**Context**: Being the final boss project, the user is essentially tasked with using as many tools as he can (ideally tools learned from the curriculum) . So far so good.

**Issue**: However, some of the said tools don't make sense when used together, at least from my viewpoint (do keep in mind I'm just a student who's capable to do Hello World tier apps in a bunch of languages/frameworks learned from TOP). For instance, the React Course teaches us to render websites using react components while the NodeJS Course teaches us to use Express with template engines (pug/jade).  I don't see a world where I can use both, but, with a bit of research, the compromise would be something like React + Express + **Next.js** (which is not part of the curriculum).

**Question**: How should the end user approach the final project? Since the final assignment is bound to the NodeJS course, should he specifically use Express with pug/jade, at the expense of ditching 1/3rd of the curriculum (React) ? Or should he ditch pug/jade & ask Google how he could use both React & Express?

Best answer I could find was: [_For example, you can use Next JS for rendering pages and handling API requests that require server-side rendering or static site generation, and use Express for more complex API logic and middleware that require full control over the server-side behavior_](https://www.frontendmag.com/insights/next-js-vs-express/#:~:text=For%20example%2C%20you%20can%20use,over%20the%20server%2Dside%20behavior.)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-odin-book

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Lofty-Brambles** [comment]
Just saying, I'm not sure what the point is. The Node course integrates with react from the blog project and beyond, ditching template engines for the stereotypical jamstack-y approach of separate web servers serving react apps and working with a static REST API as backend. This was already covered under the assignment instructions here: https://www.theodinproject.com/lessons/nodejs-blog-api

**Comment by JoshDevHub** [comment]
It doesn't seem like this issue was ever fully triaged, so it got a bit lost in the shuffle.

That said, I agree with what Lofty has said above: the course *definitely* goes into how express APIs and React can fit together. I'll be closing this issue down, but if you still have concerns, you can ping me here and we can talk about it some more @VACostin
