### ISSUE TITLE
Foundations: Mention MacOS's default ZSH shell in Command Line Basics lesson

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/curriculum#25839]
### Describe your suggestion

After a certain update, MacOS began using the Z shell by default. 

I noticed that this has caused confusion when learners ask about it in the Discord server.

I believe that adding a simple note & a screenshot of what it looks like would really help clarify things for new users. Perhaps something like:

> MacOS users: Please note that since Catalina (version 10.15), MacOS switched to zsh as its default shell. You do not have to change anything, but your prompt will look a little different, as seen in the screenshot below:
[insert screenshot of what the z shell looks like in MacOS]

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-command-line-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

eduardo06sp

**Comment by CouchofTomato** [comment]
Hey @Eduardo06sp 

I think that would be a good idea. As you haven't indicated you want to work on it I'll label it as good for a beginner.

**Comment by ManonLef** [comment]
You've got it @fabulousgk

**Comment by fabulousgk** [comment]
I would like some feedback on the change before I submit.

https://github.com/TheOdinProject/curriculum/compare/main...fabulousgk:top-curriculum:terminal_update

I also modified the color of the terminal since black is not a given anymore.
