### ISSUE TITLE
Revisiting RPS: Change title to 'Implement git Branches into RPS project'

### ISSUE THREAD

**Issue by carafelix** [TheOdinProject/curriculum#25837]
### Describe your suggestion

I think the 'Revisiting Rock Papers Scissors' project as a critical information on git Branch management, and for someone that is not doing the curriculum from start-to-end, that could get lost. 
So idk if my proposed title is good enough, but something along those lines, that could let you know that all basics about Git Branches is there. Maybe split them into 2 lessons. Git Branches and Revisiting RPS.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors

### Checks

- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Discord Name

humano32

**Comment by CouchofTomato** [comment]
Thanks @carafelix 

You raise a fair point but at this point in time our curriculum is created to be taken from start to finish. We don't have a way around this so I'm closing this issue.
