### ISSUE TITLE
Foundations: update heading placement

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#25848]
### Describe your suggestion

The following lessons have the last two sections (Additional Resources and Knowledge Checks) in the wrong order. The "Knowledge checks" section should come before "Additional resources".

- [Command Line Basics](https://www.theodinproject.com/lessons/foundations-command-line-basics)
- [Fundamentals Part 1](https://www.theodinproject.com/lessons/foundations-fundamentals-part-1)
- [Fundamentals Part 2](https://www.theodinproject.com/lessons/foundations-fundamentals-part-2)
- [JavaScript Developer Tools ](https://www.theodinproject.com/lessons/foundations-javascript-developer-tools)
- [Problem Solving](https://www.theodinproject.com/lessons/foundations-problem-solving)
- [Understanding Errors](https://www.theodinproject.com/lessons/foundations-understanding-errors)
- [Fundamentals Part 4](https://www.theodinproject.com/lessons/foundations-fundamentals-part-4)

### Path

Foundations

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by hmzq-404** [comment]
@thatblindgeye Can I take this issue?

**Comment by thatblindgeye** [comment]
@hmzq-404 all yours!
