### ISSUE TITLE
Foundations/Inspecting HTML and CSS: assignment needs numbered items

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#25849]
### Describe your suggestion

The [Inspecting HTML and CSS lesson ](https://www.theodinproject.com/lessons/foundations-inspecting-html-and-css)'s assignment section needs to be updated so that the task is a numbered list with the bulleted list nested inside of it. It should end up looking something like:

```
1. Go through the following sections...
   - Each bulleted item...
```
Resulting in:

1. Go through the following sections...
   - Each bulleted item...

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-inspecting-html-and-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by latsonj** [comment]
Can I be assigned this issue? Thanks.

**Comment by CouchofTomato** [comment]
@latsonj All yours
