### ISSUE TITLE
Fix: Foundations headers to all follow sentence case per our style guide

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25843]
### Describe your suggestion

Our [Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#headings) requires all headings to be in **sentence case**. This means many lessons need to be reviewed.

I would like to open this up for **first-time contributors** to work on. You can follow the links to see how big the sections are. Some will have only one or just a few lessons and some will have quite a lot more. Feel free to pick one you feel comfortable with. 

Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution. 
Please add the following to your PR in the Issues section: Related to https://github.com/TheOdinProject/curriculum/issues/25843 
Since this issue is divided into sections, individual PR's should not include the `closes` issue link. 

| Section | Link | Assignee | completed |
| ------------- | ------------- | ------------- | ------------- |
| Foundations Introduction | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#introduction) |@hmzq-404 |✅ https://github.com/TheOdinProject/curriculum/pull/25847 |
| Foundations Prerequisites | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#prerequisites) | @Baguirre03 | ✅ https://github.com/TheOdinProject/curriculum/pull/25855 |
| Git Basics | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#git-basics) | @jrumbawa  | ✅ https://github.com/TheOdinProject/curriculum/pull/25853 |
| HTML Foundations | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#html-foundations) | @OmarNaguib | ✅ https://github.com/TheOdinProject/curriculum/pull/25862|
| CSS Foundations | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#css-foundations) | @Advaitmenon1106 | ✅ https://github.com/TheOdinProject/curriculum/pull/25859 |
| Flexbox | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#flexbox) | @kristenmazza  | ✅ https://github.com/TheOdinProject/curriculum/pull/25858 |
| JavaScript Basics | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#javascript-basics) | @fabulousgk | ✅ https://github.com/TheOdinProject/curriculum/pull/25852 |
| Conclusion | [link](https://www.theodinproject.com/paths/foundations/courses/foundations#conclusion) | @fabulousgk |✅ https://github.com/TheOdinProject/curriculum/pull/25852  |

Example:

```md
### Knowledge Check

should be changed to

### Knowledge check
```

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/paths/foundations/courses/foundations

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

ManonL

**Comment by hmzq-404** [comment]
Hey, I am a first time contributor. (Opened a few pull requests and issues on other repos but they never got accepted). Can I work on Foundations Introduction?

**Comment by ManonLef** [comment]
@hmzq-404 all yours!

**Comment by hmzq-404** [comment]
Is there a deadline to this?

**Comment by ManonLef** [comment]
@hmzq-404 Do you have an estimate on how much time you need? It's not a high priority issue but with multiple people working on it, it would be nice if it didn't take multiple weeks to wrap up :)

**Comment by hmzq-404** [comment]
Nevermind about the deadline thing, this will probably take around 20 minutes.

**Comment by Baguirre03** [comment]
Ill happily do "*Foundations Prerequisites"

**Comment by fabulousgk** [comment]
Hello, I would like to do JavaScript Basics.

Thank you

**Comment by ManonLef** [comment]
@Baguirre03 and @fabulousgk wonderful thank you, I'll add your names to the table!

**Comment by jrumbawa** [comment]
I can do Git Basics and whichever else you need done

**Comment by kristenmazza** [comment]
I would be glad to do Flexbox. :)

**Comment by OmarNaguib** [comment]
I would like to contribute

**Comment by Advaitmenon1106** [comment]
I am a first time contributor (discord TOP nickname: Advait; username: a_v_it)
I'd like to work on one of these (HTML Foundations seems to be done, so maybe Flexbox or CSS Foundations?)

**Comment by ManonLef** [comment]
@kristenmazza I'll add you to the flexbox section! All yours

**Comment by ManonLef** [comment]
@OmarNaguib If you could go through the [HTML Foundations section](https://www.theodinproject.com/paths/foundations/courses/foundations#html-foundations) that would be great! Most lessons there seem to be updated but not all. Thank you!

**Comment by ManonLef** [comment]
@Advaitmenon1106 I'll put your name up for the [CSS Foundations section](https://www.theodinproject.com/paths/foundations/courses/foundations#css-foundations)

Most lessons there still need updating it seems. Thank you for taking this on!

**Comment by Baguirre03** [comment]
@ManonLef My section should be clear now.

**Comment by ManonLef** [comment]
All done! Thank you everyone for working on this!

**Comment by ManonLef** [comment]
FYI: [another one of these header issues](https://discord.com/channels/505093832157691914/700355756188368926/1131340515523170364) opened for new or newish contributors. Feel free to comment there if you'd like to work on another section
