### ISSUE TITLE
Foundations/Fundamentals 5: Introduction section needs content

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#25850]
### Describe your suggestion

[Fundamentals Part 5 ](https://www.theodinproject.com/lessons/foundations-fundamentals-part-5)needs content added to its introduction section

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-5

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by BrendonTheDev** [comment]
Hello, I would like to contribute by adding content to the introduction section of fundamentals lesson 5. 

Welcome to my crib! I'd like to introduce you to **Objects**. Think of an object like house. The house contains many rooms called properties "key-value" pairs. You use the key to access whatever is assigned to it, think "the room and its contents". If you use the _kitchen_ key you get access to the stored value of a stove, microwave, and refrigerator. The best part is, you can store just about anything in an object! Data, variables, arrays, functions, can all be neatly stored as properties on object to be easily accessed later! You will also learn about the all powerful _array methods._ Array methods are predefined functions that manipulate and create arrays. Array methods unlock the ultimate functional power of arrays. Objects and arrays are two of the most important programming concepts, and will both be an indispensable part of your JavaScript tool kit!

**Comment by BrendonTheDev** [comment]
May I please get assigned to the issue?

**Comment by thatblindgeye** [comment]
@BrendonTheDev Yep you can be assigned! Regarding your draft, we probably don't want to go into that much detail just in the introduction alone. Since this is the final lesson in Foundations (ignoring the project and "Choose your path forward"), we could try to incorporate that. Something like mention that the user has learned a lot of the fundamentals to JavaScript and that objects are one more important part. We could briefly mention what objects are ("...a collection of key-value pairs...") and a quick analogy.

For the array methods, users will have already been introduced to some from a previous lesson, so we could just mention that users will also learn some more powerful and commonly used array methods.

I think we could keep this line you had, "Objects and arrays are two of the most important programming concepts, and will both be an indispensable part of your JavaScript tool kit!" with maybe a tweak, though. Maybe, "Before you know it, you'll have a better understanding for how important objects and arrays are, and how both can be an indispensable part of your JavaScript tool kit!"

**Comment by BrendonTheDev** [comment]
Great, thank you! Sorry for the late reply, I could not work on it this weekend. This is my first time contributing so I am excited, and appreciate the opportunity. I will shorten this up and work on adding the content. now!
