### ISSUE TITLE
Adv HTML/CSS: CSS exercises are not part of the assignment

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25854]
### Describe your suggestion

In [the lesson on keyframes](https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-keyframes#assignment), I think the CSS exercises should be part of the `assignment` section. Instead they got their own `practice` section which feels like a different approach to what we're used to in the curriculum so far. 

If this is agreed upon by another maintainer to indeed include in the `assignment` section, this has to be changed in both the lessons on the NodeJS and RoR Paths.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-keyframes#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

ManonL

### (Optional) Additional Comments

Criteria for completion
- [ ] change the lesson on the RoR path
- [ ] change the lesson on the NodeJS path

**Comment by ManonLef** [comment]
Tagged you Cody to review this. You seem to know most about the HTML/CSS sections. If you agree this needs to be part of the assignment I can open it up for others to work on :)

**Comment by codyloyd** [comment]
I'm not sure I care too much.. I think we had a reason, initially for pulling them out of 'assignments'... but I can't think of it now, which means it probably wasn't a compelling one.

Should probably get at least _someone_ else to sign off on this though :D @TheOdinProject/foundations

**Comment by thatblindgeye** [comment]
@ManonLef Not sure if it's part of the layout style guide, but yeah any sort of "practice" sections should be moved to assignments. Maybe there's a scenario where a separate "practice" section makes sense, i.e. maybe between two topics we tell users "practice with this codepen" or whatever.

For this though, let's move it to assignments.

**Comment by fabulousgk** [comment]
I will take this.

**Comment by ManonLef** [comment]
perfect @fabulousgk ! I will assign you now!
