### ISSUE TITLE
Bug: React Lesson 'How to Deal With Side Effects' knowledge check contains broken links

### ISSUE THREAD

**Issue by amc131** [TheOdinProject/curriculum#25871]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the knowledge check for this lesson : https://www.theodinproject.com/lessons/node-path-react-new-how-to-deal-with-side-effects all of the links are broken. The first link leads to the advanced HTML and CSS intro lesson, and the rest return page not found.

**5. Additional Information:**

**Comment by ChargrilledChook** [comment]
@fabulousgk  I've moved it to the correct place :+1:
