### ISSUE TITLE
Join the Odin community lesson: Change bullet points to a sentence-case

### ISSUE THREAD

**Issue by Eveieve** [TheOdinProject/curriculum#25876]
### Describe your suggestion

Since all headers in lessons follow a sentence-case per the style guide, I think it would make sense to make all bullet points under the Assignment section to sentence-case as well. The bullet points are sentences in nature too. The bullet point under number 2 follows a sentence-case and the ones below don't either. 

Suggestion: Make the bullet points' style consistent by making them sentence-cased. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Makes sense, I'll assign you!
