### ISSUE TITLE
React: Update headings to sentance capatilization per style guide

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#25872]
### Describe your suggestion

The lessons in the React course need to have headings updated to sentence capitalization per style guide.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/paths/full-stack-javascript/courses/react-new

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

FabulousGeek

**Comment by ManonLef** [comment]
This one is covered in: https://github.com/TheOdinProject/curriculum/issues/25861
