### ISSUE TITLE
Advanced HTML and CSS_Transitions: Remove additional resource on cubic-bezier

### ISSUE THREAD

**Issue by Eveieve** [TheOdinProject/curriculum#25885]
### Describe your suggestion

Under the Additional resources section: 
`
You can play around with the CSS Cubic Bezier Generator to not only view how the cubic-bezier value works in an editable demo, but also to compare the different transition-timing-function values side by side.
`
But `cubic-bezier` was not mentioned in this lesson. All other TOP Additional resources sections contain resources that further explain concepts that were covered in the lesson, so I thought this was an odd suggestion. 

I have checked out this lesson in the past, and at that time I believe the lesson contained `cubic-bezier`. I thought perhaps it was mistakenly not removed from the additional resources since its removal from the lesson altogether. 

Suggestion: Either include a brief explanation of the `cubic-bezier` concept under Additional resources or remove it. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transitions

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by codyloyd** [comment]
approved.  I think we should keep this resource and add a small section about animation timing, including a mention of cubic-bezier

**Comment by Eveieve** [comment]
@Lofty-Brambles What I meant by 'cubic-bezier is not mentioned in the lesson' is that it was not even briefly introduced, either on its own or as an extension of other concepts covered in the lesson, once. The way it's currently worded under Additional resources implies the learner is aware of this property on their own, which isn't how it's structured in all other top lessons. 

If we were to add a short explanation of it with the link, I will let others who are more familiar with the concept work on this issue. I thought we'd be removing the link on cubic-bezier since it's not in the lesson. I'll uncheck 'Would you like to work on this issue?' on this post.

**Comment by Lofty-Brambles** [comment]
I'd vouch codyloyd on this, then. I think a short explanation to cubic bezier curves, or a small article on it, and linking to this lesson is good, considering that it's something that gets used often.
[KP has a good video](https://youtu.be/Nloq6uzF8RQ) on this, or this [CSS tricks article](https://css-tricks.com/advanced-css-animation-using-cubic-bezier) works, but the thing is, it deals with animations, which's not taught yet. If you can make a short paragraph on it, feel free, otherwise, someone needs to address it.

**Comment by Lofty-Brambles** [comment]
I'll link a PR in the next 24 hours if it isn't done.
