### ISSUE TITLE
How does the web work lesson: Remove periods after bullet points 

### ISSUE THREAD

**Issue by Eveieve** [TheOdinProject/curriculum#25887]
### Describe your suggestion

I noticed that the bullet points under the `Lesson overview` section often have periods in the end or don't. This is inconsistent across lessons, as well as courses. 

![image](https://github.com/TheOdinProject/curriculum/assets/85281165/65a0d3a3-72b9-4ab2-ab94-23ee47d2ee52)

An example of a lesson that has no periods:
https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transitions

I was wondering if this is something that should be changed. Personally, I like bullet points without periods. 

Perhaps these could be assigned to first-time contributors, but if not, I do not mind working on these issues. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-how-does-the-web-work

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Yeah we should aim for consistency on this. https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md the style guide seems to use them but not exclusively. I'll get some opinions on this.

**Comment by CouchofTomato** [comment]
From discussion we like the approach here https://developers.google.com/style/lists#numbered-lettered-bulleted-lists

**Comment by Eveieve** [comment]
So we should be adding end punctuation and not removing them? Since those lists are sentences. 

Also, I noticed the headings are inconsistent across lessons, sometimes they're `Lesson overview` and sometimes they are `Learning outcomes`. Was this intended or is this something that should be corrected too?

**Comment by Lofty-Brambles** [comment]
Clarifying this in the style guide explicity won't be a bad idea too.

**Comment by ManonLef** [comment]
@Eveieve we're aware of the discrepancy between lesson overview and learning outcomes and we'll rework that after a verdict is out :)

Regarding the style guide; I agree the linked list formatting should be part of the style guide. Would you want to pick that up or open an issue on @Eveieve ?

**Comment by Eveieve** [comment]
@ManonLef Yes, I can make a PR for it. Should I work on it right away or open another issue for it first? 

>  should be part of the style guide.
By this, you're saying we should add a section specifying the punctuation rules for bulleted lists in the `style guide` repository, right?

**Comment by ManonLef** [comment]
@Eveieve I tagged you on an issue where I proposed some ideas that should clarify it a bit. If you comment there, I can assign you!

**Comment by thatblindgeye** [comment]
@ManonLef @Eveieve Do we want to close this issue out for now? We probably want to do an audit of lists and create issues based on that, but it seems like this particular lesson doesn't need updating

**Comment by Eveieve** [comment]
@ManonLef has assigned me to work on adding a section in the style guide on bulleted lists. I think this issue can be closed because the lesson's overview section doesn't need changing.
