### ISSUE TITLE
Style Guide: add punctuation rules for list items 

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25921]
### Describe your suggestion

As discussed here: https://github.com/TheOdinProject/curriculum/issues/25887#issuecomment-1646556086 it would be good to add some guidance in the style guide on how we would like to format list items. 

Proposal:

- [ ] make sure the [current list examples](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lists) in the style guide follow the [google styleguide](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists)
- [ ] add some instructions on how to deal with punctuation and capitalization in lists
- [ ] add a link to the [Google style guide section on lists](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists) for examples

### Path

Other / NA

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lists

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

Another learner indicated they'd be willing to make this change to the style guide

**Comment by ManonLef** [comment]
@Eveieve I will assign you here :)

**Comment by Eveieve** [comment]
Hi, I'd like to work on this issue.

**Comment by ManonLef** [comment]
you've got it @Eveieve !

**Comment by ManonLef** [comment]
@Eveieve I'd personally put it right under the list header as a general note about rules surrounding lists
