### ISSUE TITLE
Advanced HTML and CSS: Recommend Kevin Powell course

### ISSUE THREAD

**Issue by hebiscus** [TheOdinProject/curriculum#25935]
### Describe your suggestion

I think it'd be nice to have Kevin Powell's Conquering Responsive Layouts course linked at the end of the Course in additional resources. It's totally free and solid, ties up and adds to a lot of concepts previously mentioned in the course. 

Course link: https://courses.kevinpowell.co/conquering-responsive-layouts

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-media-queries or wherever suitable

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

hebiscus.

**Comment by CouchofTomato** [comment]
@codyloyd Any views on this mate?

**Comment by codyloyd** [comment]
i don't love that you have to make an account and "buy" this free course for $0.

maybe technically free... but generally we prefer resources that can be accessed without signing up for things.

Having said that, I'm not against sticking it in as an additional resource.

**Comment by 01zulfi** [comment]
@hebiscus Would you be up for adding this resource in additional resources as suggested in the comment above?

**Comment by hebiscus** [comment]
@01zulfi sure thing!
