### ISSUE TITLE
JavaScript: LocalStorage DevTools addition

### ISSUE THREAD

**Issue by hebiscus** [TheOdinProject/curriculum#25943]
### Describe your suggestion

There's no mention in any of the resources listed that localStorage can be visible in DevTools, which is very helpful while working with it. Instead of console logging multiple times, using DevTools should be encouraged. It's not something that's normally mentioned in any main page articles or videos on localStorage either. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-todo-list

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

hebiscus.

**Comment by linkonsat** [comment]
After foundations, it's definitely a tool worth leaning on. Maybe it could be added in the tip list on step 8. Is that something you would be interested in doing?

**Comment by hebiscus** [comment]
Yeah, would love to!
