### ISSUE TITLE
Introduction to Git: Remove colon after "lesson overview" heading

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#25941]
### Describe your suggestion

The "Lesson overview" heading has a colon that needs to be removed

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
https://github.com/thecodetato is working on this one
