### ISSUE TITLE
Js React: update header in React Class Based Components to avoid spell check issue

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#25953]
### Describe your suggestion

The GitHub Actions will throw an error on this file during the spelling check during PR's. 
The [lesson can be found here](https://www.theodinproject.com/lessons/node-path-react-new-class-based-components)

One of the headers is named `The whats and whys` and we should find another appropriate title for this.

Error Preview on GH:
![Screenshot_2023-07-25_at_12 11 14](https://github.com/TheOdinProject/curriculum/assets/81025586/24d21fa0-a35a-4e84-b5c9-e5d93491dde9)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-class-based-components

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Some suggestions from @thatblindgeye about this:

> I feel like we could just rename that section to "A brief summary", "A brief history lesson", "Class components - what and why".
> We could also just replace the current Introduction with the text from that section (maybe tweaking the verbiage a little to shorten it). Keeping the section as it is and renaming it could allow expanding a bit more on the "what" if we wanted, though. 


![](https://cdn.discordapp.com/attachments/891423158836547665/1133358983093170256/image.png)

**Comment by thatblindgeye** [comment]
@ManonLef Not particularly 😆 Only thing off the top of my head would be instead of mentioning what functional components used to be in a "what and why" about class components, putting the POV on class components.

**Comment by ManonLef** [comment]
I'll open this up for someone to make a change. I think something along the lines of `some background on class components` or `the history of the React component` might do the trick, but I'd be curious about other ideas

**Comment by fabulousgk** [comment]
I will take this.

I am thinking  `Historical React component patterns`

**Comment by fabulousgk** [comment]
@ManonLef can I take this and proceede?
