### ISSUE TITLE
React Course: Rewrite "Introduction to React" lesson

### ISSUE THREAD

**Issue by seanmckone** [TheOdinProject/curriculum#25959]
### Describe your suggestion

The "Introduction to React" lesson contains multiple grammatical errors and could generally be made more clear and descriptive.

### Rewrite lesson overview
> This section contains a general overview of topics that you will learn in this lesson.
> - Understand what is React

could be rewritten as

> This section contains a general overview of topics that you will learn in this lesson.
> - Understand what React is and why you should use it

### Rewrite "What is React" section

>React according to their [official website](https://react.dev/) is "The library for web and native interfaces" however let's break this down a bit further.

>Generally speaking, a JavaScript library is a collection of pre-written code that's designed to make development easier, not to be confused with frameworks however as you'll be reading the differences later on in the lesson. This code can be reused/reimplemented in our own codebases to achieve complex tasks. That said, the terms library and framework are often used interchangeably, so don't worry too much about the difference.

>Similarly, React provides powerful primitives (built-in functions/modules) that allow us to build user interfaces of varying complexities. Throughout this course, we'll learn all about the functionality React provides and learn to build cool applications.

could be rewritten as

> React, according to their [official website](https://react.dev/), is "The library for web and native interfaces". This is pretty general, so let's break it down a bit further.

>A library, not to be confused with a framework (you'll learn the difference later in this lesson), is a collection of pre-written code that's designed to make development easier. That said, the terms library and framework are often used interchangeably, so don't worry too much about the difference.

>React provides powerful primitives (built-in functions/modules) that allow us to build user interfaces of varying complexities. Throughout this course, we'll learn about the functionality React provides and how to use it to build complex and maintainable applications.

Note: these are just examples; the content would benefit greatly from a more drastic rework

There are various other changes that could be made to improve the lesson, such as removing "React is not opinionated" from reasons to learn (this isn't really a reason to learn React, just one of the characteristics of libraries in general).

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
Agreed. Please create a pull request so the specifics of the change can be reviewed there thanks @SDMckone

**Comment by ManonLef** [comment]
@seanmckone Hi, I'm checking in to see if this is still on your radar? I know many people have been opening PR's on these lessons lately so perhaps the issue is resolved. If you still think work is needed but you didn't get to it yet, that's fine of course. I'd appreciate an update :)

**Comment by seanmckone** [comment]
Yes, still on my radar. I plan to create a PR within the next 2 weeks.
