### ISSUE TITLE
React: Add Clarifications in More on state Lesson

### ISSUE THREAD

**Issue by Mclilzee** [TheOdinProject/curriculum#25956]
### Describe your suggestion

There are a couple of Points that stands out to me in React State Lesson.

- The wording of one of the titles, `State is immutable` Is highly misleading, the title should be reworded, `State should not be mutated` is a better title for the subject. Link : https://www.theodinproject.com/lessons/node-path-react-new-more-on-state#state-is-immutable

- The recommendation is not consistent with React Documentation. In the section about Updater Function, it says `You will find yourself reaching out for state updater functions rarely, but it’s good to know they exist.` Which is something I disagree with. Using State Update always insures consistency and reduces the chances a hidden bug might fire up any moment. According to React Documentation, which states It's better for consistently when you want to update the State when using the Previous State. 
Link : https://react.dev/reference/react/useState#is-using-an-updater-always-preferred

- I would like to add Clarification of why do we always need to return a new object in `setState` function, regardless of state mutability issue. And explain why it most of the time wouldn't re-render by only using `setState` without using a new Object.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-more-on-state

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mclilzee

**Comment by 01zulfi** [comment]
I generally agree with point 1 and 3 while somewhat agree with point 2. Please create a pull request so the specifics of the proposed changes can be discussed there, thanks @Mclilzee
