### ISSUE TITLE
<Fetching Data In React>: <Wrong wording>

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#25958]
### Describe your suggestion

![image](https://github.com/TheOdinProject/curriculum/assets/55961349/00cad903-5e5e-4051-92d7-a4b300e4497b)

Repeating "will be" twice in the same sentence 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Omar (onsmak) @onsmak

**Comment by 01zulfi** [comment]
Assigned @OmarNaguib!
