### ISSUE TITLE
<React>: <Fix text>

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#25966]
### Describe your suggestion

![Screenshot 2023-07-26 220955](https://github.com/TheOdinProject/curriculum/assets/55961349/6a851a99-e9de-4df2-ab17-c0035e0607d1)

Repeated words in:
"You have an even longer still have a longer" 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-shopping-cart

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Omar (onsmak) @onsmak

**Comment by ManonLef** [comment]
Good catch, I've assigned you since you indicated you'd like to work on it. 
For obvious typos like this, you can also go for a PR directly :)

**Comment by OmarNaguib** [comment]
Ok thanks!
Noted, I also make an issue as a way to schedule it for later
