### ISSUE TITLE
<React>: <Fix type>

### ISSUE THREAD

**Issue by fgostev** [TheOdinProject/curriculum#25971]
### Describe your suggestion

If I'm right, there is a mistake:

<img width="782" alt="Screenshot 2023-07-26 at 17 51 36" src="https://github.com/TheOdinProject/curriculum/assets/50133788/29c6e301-fe62-48c9-b10f-f0d814c49421">

It should be main.jsx, not index.js

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-react-router

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

fgostev

**Comment by 01zulfi** [comment]
@fgostev assigned!

**Comment by fgostev** [comment]
Added a commit with fixing the issue. (_hoepfully did it right in terms of coomit, accidently closed the first one made a new one_)
