### ISSUE TITLE
Foundations - Intro to CSS: iframe in `Lesson overview` not working

### ISSUE THREAD

**Issue by DariaNico** [TheOdinProject/curriculum#25984]
### Describe your suggestion

The iframe tag for the Scrim under `Lesson overview` is showing up as a black box within the lesson.
![Iframe-issue](https://github.com/TheOdinProject/curriculum/assets/4218728/f97a0361-faf2-46f3-b502-acaface4d048)

### Piece of code with the issue
```
<iframe src="https://scrimba.com/scrim/co12d4cf99cf2776f19e84a9d?embed=odin,mini-header,no-sidebar,no-next-up" sandbox="allow-scripts allow-same-origin allow-popups" width="100%" height="400"></iframe>
```

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@theodinproject/foundations can someone with knowledge of scrims look into this please

**Comment by thatblindgeye** [comment]
I'm not noticing this issue:

![image](https://github.com/TheOdinProject/curriculum/assets/70952936/eb660908-5985-4588-9a7b-e98e575337f7)

That said, we do plan on moving these Scrims as additional resource links rather than planted in the middle of lessons. If others are seeing this issue we can expedite this particular lesson, though.

**Comment by suzuhe481** [comment]
It looks like the black box is related to whether the user has third party cookies enabled or not. Specifically, for the https://scrimba.com/ domain.

I also have this issue on Chrome, both in the regular browser and in incognito. But I can see the Scrimba if I enable third party cookies.
On Firefox, I can see the Scrimba, but if I add the Scrimba domain to my list of websites to block cookies, the black box appears again.

I've seen this on every Scrimba I've encountered during the Full Stack JavaScript course, but my workaround is to just get the direct link using the inspect tool.
I would also just recommend a direct link under the Scrimba. Or some kind of overlay/popup telling the user the Scrimba won't work properly unless third party cookies anre enabled.

**Comment by ManonLef** [comment]
@TheOdinProject/foundations any thoughts/input on the above issue? It came up in discord a few times as well lately

**Comment by roy9495** [comment]
Normally I was able to see it 

![Capturel](https://github.com/TheOdinProject/curriculum/assets/98920199/ad3dfeae-6245-437f-89c2-0e5e81f85190)

But after disabling the cookies

![Capturhe](https://github.com/TheOdinProject/curriculum/assets/98920199/6b17fbae-8e39-4b3e-b0f3-1c5267701398)

It was gone

![Cahpture](https://github.com/TheOdinProject/curriculum/assets/98920199/276a830b-50b4-4590-8317-04f115e641e3)

**Comment by thatblindgeye** [comment]
We should probably fast track this particular lesson to remove the embedded scrimba from its current location, and add it to this lesson's Additional Resources (as a simple link, not embedded). @ManonLef

**Comment by fabulousgk** [comment]
I am game to do this, in fact I am game to do them all, if that would be any help.

**Comment by thatblindgeye** [comment]
@fabulousgk for now let's just update this particular lesson, but you're assigned for this one!
