### ISSUE TITLE
JavaScript: Add video resource to explain callback functions and their drawbacks

### ISSUE THREAD

**Issue by MahmoudTalass** [TheOdinProject/curriculum#25988]
### Describe your suggestion

I came across a video from Akshay Saini (a creator whose videos have previously been provided as a good resource in previous TOP javascript lessons) that discusses callback functions and callback hell. I found it to be very easy to follow and explained callbacks and their drawback very well. I think students who prefer watching videos to learn would find this video helpful. 

here is the link: https://www.youtube.com/watch?v=yEKtJGha3yM&ab_channel=AkshaySaini

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-asynchronous-code

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Thanks for the suggestion @MahmoudTalass 
Since we have multiple resources on callbacks and various video ones speaking touching on it well, could you describe what else it covered that isn't already covered in the other resources provided. 

If you feel it's better than a current resource that covers the same thing, you could mention it as well. Either way, since this lesson is already covering a lot of written and video material already, it really needs more context.

**Comment by MahmoudTalass** [comment]
Thanks for your response @ManonLef!

The video tutorial I came across provided a great visual summary of Chapter 2 on callbacks from "You Don't Know JS." It covered many of the same key points as the reading, including callback hell and inversion of control. While the video in this lesson focused solely on avoiding callback hell and didn't touch upon inversion control. 

For learners who prefer video tutorials over reading material, I think adding this as an extra resource link at the end of the lesson could be helpful.

**Comment by ManonLef** [comment]
@TheOdinProject/javascript could someone have a look at this please?

**Comment by wise-king-sullyman** [comment]
Since this lesson already has so many additional resources already I would be hesitant to add another one that covers already covered content just in a different format personally.

**Comment by ManonLef** [comment]
While we do know some people prefer video content, this lesson is already jam-packed with information covering all necessary topics to proceed and we will not be including it at this time. I will close this for now but really do appreciate your suggestion @MahmoudTalass !

**Comment by MahmoudTalass** [comment]
Thank you for the consideration, @ManonLef !
