### ISSUE TITLE
React: Fix links submissions-list.jsx and submissions-list.test.jsx 

### ISSUE THREAD

**Issue by kristenmazza** [TheOdinProject/curriculum#25989]
### Describe your suggestion

The "Mocking Callbacks and Components" lesson asks users to read the submissions-list.jsx component and its test file, submissions-list.test.jsx. Both links give a 404 error:
- [submissions-list.jsx](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/project-submissions/components/submissions-list.jsx)
- [submissions-list.test.jsx](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/project-submissions/components/__tests__/submissions-list.test.jsx)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-mocking-callbacks-and-components

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ZachBaird** [comment]
I can take this.
