### ISSUE TITLE
CS Section: Knights Travails update examples

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#26006]
### Describe your suggestion

What i found is that there is a bit of a discrepancy between the chessboard provided and the example problems for knights travails. I think that we should update the image so that it included numbers on the bottom of the grid _and_ update the example problems shown below so they no longer include index [0, 0], but instead use examples [1,1]

This can make it a bit easier to understand the goal, and let people use the board to visualize need be. 

<img width="658" alt="Screenshot 2023-07-31 at 9 29 07 AM" src="https://github.com/TheOdinProject/curriculum/assets/114883353/9deaa048-0dd5-4d1a-a060-6d3a5427a957">

```
knight_moves([0,0],[1,2]) == [[0,0],[1,2]]
knight_moves([0,0],[3,3]) == [[0,0],[1,2],[3,3]]
knight_moves([3,3],[0,0]) == [[3,3],[1,2],[0,0]]
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-knights-travails

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mfrayray

### (Optional) Additional Comments

I can change the code snippet, though I dont think it is super necessary to change the image.

**Comment by 01zulfi** [comment]
@TheOdinProject/ds-a can someone look into this please?

**Comment by ManonLef** [comment]
@Baguirre03 sounds like a good update. Do you have the means to create a new image for it?

**Comment by ManonLef** [comment]
Important to note: this has to be updated in both paths, so also for the Ruby CS lesson

**Comment by Baguirre03** [comment]
@ManonLef if you could create the image that would be great! Also - I realized that too, but I didnt know how to tag Ruby and JS

**Comment by ManonLef** [comment]
How about we keep it at 0, 0? 😅

![TOP-KT](https://github.com/TheOdinProject/curriculum/assets/81025586/5a948f27-a475-48e5-a069-9fc503d4772a)

**Comment by ManonLef** [comment]
I do agree chessboards start at 1, but they also use letters for the other axis which is more work to implement for the project. I guess that's why they went with numbers for both axes. 

I *could* redesign to start at 1 as well, but if we use this as a reference, the rest can be left unaltered :)

**Comment by Baguirre03** [comment]
@ManonLef  going to go with the image change, looks great to me! I cant believe you drew that horse :0!

**Comment by ManonLef** [comment]
well 'drawing' is a big word. I nudged some vector paths, nodes and curves 😄

**Comment by Baguirre03** [comment]
Hi @ManonLef can you open this for someone else to contribute? Dont think I can get around to it. Thank you!

**Comment by ManonLef** [comment]
Sure @Baguirre03 !!

**Comment by ManonLef** [comment]
So to whoever would like to pick this up, [this should become the new image] for this lesson. Just reply here and you will be assigned

**Comment by Ruchita1010** [comment]
I would like to take this! But will it be okay if I submit it by today and not right now, instantly!

**Comment by ManonLef** [comment]
@Ruchita1010 there is no rush whatsoever. Thanks for taking this on! I'll assign you

**Comment by Ruchita1010** [comment]
Hi @ManonLef! I tried to delete the previous image and replaced it with the new one (giving it the same name), but that doesn't seem to work. After going through the [statically.io docs](https://statically.io/docs/using-staticzap/), I think I need a new tag value given the pattern hyperlink follows  `/gh/:user/:repo/:tag/:file`. It seems we're using the commit hash but I am not able to understand how to do that? I mean how would I get the commit hash before committing 👀

**Comment by ManonLef** [comment]
@Ruchita1010 thanks for reaching out. You can find the [instructions about adding new images here](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#images)

I hope this helps since I’m not around a computer so walking through it together will be hard. Just leave any questions that still arise after that here for me or another maintainer to pick up. Hopefully the directions are clear enough however.
