### ISSUE TITLE
Default Styles - Intermediate HTML and CSS Course:  2nd assignment link has dead links in it

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/curriculum#26009]
### Describe your suggestion

> lesson link - https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-default-styles

#### 2nd lesson assignment: 
> [Normalize.css](http://nicolasgallagher.com/about-normalize-css/) is another popular one. It’s a little different in that it doesn’t remove all the default styles, but tweaks them slightly to ensure that browsers are consistent.

The article suggests downloading the project to install and that link is dead. 

> How to use normalize.css
First, install or [download normalize.css](http://necolas.github.com/normalize.css/) from GitHub. There are then 2 main ways to make use of it.

I'd suggest appending a note to the assignment text to ignore this and instead go to https://github.com/necolas/normalize.css  and follow the NPM install directions in the README.md, or link directly to the repo. 

> NPM

npm install --save normalize.css

### Path

Node / JS

### Lesson Url

 https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-default-styles

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Fred

### (Optional) Additional Comments

I'm willing to make the change if what I propose is good enough. If you decide you want a different resource, it might be better for someone else to take that on.

**Comment by 01zulfi** [comment]
@JustWaveThings looks good to me. Please create a pull request so that the changes can get reviewed there, thanks

**Comment by JustWaveThings** [comment]
Done  @01zulfi  #26018
