### ISSUE TITLE
Foundations Course: Slightly outdated screenshots 

### ISSUE THREAD

**Issue by IneffableKoD** [TheOdinProject/curriculum#26014]
### Describe your suggestion

The screenshots in the lesson are slightly outdated: 

<img width="779" alt="image" src="https://github.com/TheOdinProject/curriculum/assets/34814092/f9f4c805-3221-4ee2-8478-8f25594efdd4">

.gitignore and License are now dropdown menus. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@TheOdinProject/foundations can someone look into these please?

**Comment by ManonLef** [comment]
Since you mentioned you don't want to work on this, I will open it up for other contributors. I will attach an updated screenshot :)
![Screenshot 2023-08-01 at 13 21 57](https://github.com/TheOdinProject/curriculum/assets/81025586/c573f89f-f468-42b2-91ea-724447bbf577)

**Comment by oluwatobiss** [comment]
I will like to do this.

**Comment by ManonLef** [comment]
@oluwatobiss all yours!

**Comment by oluwatobiss** [comment]
PR submitted! 

Ref: #26047
