### ISSUE TITLE
Layout style guide: Add note about formatters

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26016]
### Describe your suggestion

We should make mention that when contributing to the curriculum, users should either avoid using a formatter or be sure they save without applying any formatting. This has caused issues in the past where things like list items, Markdown styling, or code blocks get updated to the opposite of what we prefer.

@ManonLef Anything else you can think to add? If not would you mind moving this to "ready for work" in the project board?

Acceptance criteria:

- [ ] Add a note to the Layout Style Guide file that mentions when contributing to a lesson, users should ensure they either disable any formatter they have installed or that they edit/save a file without formatting. Ideally this could go immediately after the "Note on language" verbiage at the start of the file.

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
I think it would be good to mention that this is important for every repo you work on that is not your own or has their own style guide perhaps?

Otherwise, great suggestion!

**Comment by thatblindgeye** [comment]
Yeah I feel like that could be a note in a lesson somewhere... One of the later Git lessons might make more sense, but considering how early users may begin contributing it could also make sense in one of the Foundations lessons somewhere. That could be a separate issue to tackle at some point, thogh.

**Comment by ManonLef** [comment]
@thatblindgeye I was thinking wherever we put the formatter note. But if you think that is not desirable, that's fine to omit.

Putting it inside a lesson would be great. I checked yesterday but couldn't find mention of it in neither the linting/formatter nor the git lessons. 

TOP learners don't get introduced to formatters until way into JS however. So placing it in the later git lessons might make sense indeed.

**Comment by thatblindgeye** [comment]
Ah gotcha, yeah we could also put a note in the style guide as well, it definitely wouldn't hurt.

**Comment by Baguirre03** [comment]
Adding it to the style guide would be nice. Being someone who accidentally changed much of the MD formatting because of it, it could be avoided and make people's life easier if they want to contribute before reaching later git lessons.

**Comment by fabulousgk** [comment]
I will take this.
