### ISSUE TITLE
Foundations:Intro to CSS

### ISSUE THREAD

**Issue by housepanther** [TheOdinProject/curriculum#26029]
### Describe your suggestion

While the Intro to CSS is generally good, I would recommend moving the Scrim video to the end of the lesson and just before the assignment section. The narrator sets expectations in the challenges that could be confusing. For example, she does not mention anything about descendant combinators yet expects the student to properly implement them. 

Also, I would recommend adding the following clarification to the end of the section named Descendant combinators: Descendant combinators can be a confusing subject. Sometimes it can help your understanding to turn the CSS code into an English statement. Take the following for example:

```
.preview-card ul li {
    font-size: 18px;
    color: green;
    text-decoration: none;
}
```
To put this into an English sentence, we could tell ourselves that  _all line items of an unordered list that are a member of an element with the class of .preview-card will get the font-size, color, and text-decoration styles applied to it._ 

The inspiration for this idea came from the CSS Tricks' website describing descendant combinators. By using less technical wording, it helped me personally to grasp the concept, whereas without it, I was really puzzled and confused. Thanks for your time and attention to this matter.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

While I am absolutely new to this course, I am loving it so far. I want to contribute some changes that simply helped my understanding when my brain could not wrap itself around the material. But that's more of a _me_ problem.

**Comment by codyloyd** [comment]
This is already something that is on our minds, we're actively thinking about and working on a solution.  Closing this issue, Thanks!
