### ISSUE TITLE
NodeJS: Authentication Basics: Additional Resources article is paywalled

### ISSUE THREAD

**Issue by CutlerSheridan** [TheOdinProject/curriculum#26028]
### Describe your suggestion

The [first article](https://levelup.gitconnected.com/everything-you-need-to-know-about-the-passport-local-passport-js-strategy-633bbab6195), from Medium, in the [Additional Resources section](https://www.theodinproject.com/lessons/nodejs-authentication-basics#additional-resources) of the Authentication Basics lesson is behind a paywall.

I recommend finding a suitable free replacement so the Additional Resources section includes a free article in addition to the videos.

Here is a screenshot demonstrating that I am signed in to Medium but unable to read the article without upgrading my account.

<img width="1211" alt="Screenshot 2023-08-02 at 1 01 44 PM" src="https://github.com/TheOdinProject/curriculum/assets/43424003/1a0222cf-ab86-4f35-a600-f83cd6754c79">

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-authentication-basics#additional-resources

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
It seems to be member-only (not paid). We could add a note about that. Since you have indicated you'd not like to work on this issue, I will open it up for others to work on! thanks for reporting

**Comment by fabulousgk** [comment]
Medium's wording there is misleading.  It is paid, you have to pay to be a member.  I signed up for an account to get another article and found out all about this after doing so.

**Comment by CutlerSheridan** [comment]
Yeah it is paid.  I'm signed in to my free account and here's a screenshot of what you see after you click that "Upgrade" button.

<img width="613" alt="Screenshot 2023-08-03 at 9 36 31 AM" src="https://github.com/TheOdinProject/curriculum/assets/43424003/cc68241d-fa3f-4dda-9f67-dc6973f73655">

**Comment by ManonLef** [comment]
Thanks again @CutlerSheridan

**Comment by fabulousgk** [comment]
If all we need to do is remove it, I will take it

**Comment by CutlerSheridan** [comment]
No problem!
If all that's needed is to remove the article I could handle that myself, but I do wonder if someone more experienced with server-side authentication practices could find a well-informed, up-to-date replacement article for those of us who might want a deeper dive into the material but would struggle to sit through the almost three hours of videos recommended by the second bullet point.

**Comment by ManonLef** [comment]
I will let @CutlerSheridan take it then since they opened this issue. 

Finding an alternative shouldn't be a priority since the resource isn't part of the lesson but is an additional resources. You're free to suggest one if you come across one however, or open a separate issue on it for it to be discussed :)

**Comment by CutlerSheridan** [comment]
Alright I'm on it!

**Comment by ManonLef** [comment]
@CutlerSheridan just to be sure: you have to open a PR for this. I see you mention it on your own repo but it should be a PR for our repo instead. The steps are explained in our [contributor's guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md) ☺️

**Comment by CutlerSheridan** [comment]
Weird, I clicked through from "Improve this lesson" like I always do to make changes and usually they get merged, not sure why it was different this time.

Anyway, PR submitted, I think
