### ISSUE TITLE
<Foundations> <Adding New Section in Installation Section for Scroll Wheel Problems Among Users with Solution>

### ISSUE THREAD

**Issue by trivenge** [TheOdinProject/curriculum#26024]
### Describe your suggestion

A potential section worthy of adding to the installation section. Contact me on discord if you have any questions.

**For Users Who Have Issues with Mouse Scroll Wheel in VirtualBox/VMware in Ubuntu:**

The issue lies in users who are in a virtual machine on windows, and this is a common issue where the user will attempt to use the scroll wheel while moving the mouse pointer. This causes the mouse to stop scrolling when the cursor is moving. 

**The solution:**

**Install:**
`sudo apt-get install xserver-xorg-input-evdev-dev`

**Update xorg to use evdev:**
`cd /usr/share/X11/xorg.conf.d/`

**then open the file with a program:**

`sudo vim 40-libinput.conf`

**You will see something like this:**

`Section "InputClass"
        Identifier "libinput pointer catchall"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection`

**and change it to:**

`Section "InputClass"
        Identifier "libinput pointer catchall"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection`

**install imwheel:**
`sudo apt install imwheel`

**type this into terminal to start imwheel with the solution:**
`imwheel -b "4 5"`

Lastly, to ensure this solution works every time, change current directory to home, where your .bashrc file will be located. This is hidden from view. You can type `ls -a` to see hidden files and folders if need be:

Type `cd` into terminal, then type `selectProgramToUse .bashrc`  to open the file in an editor.

**add this to the .bashrc file and make sure to save it:**

`# Start imwheel for scrolling fix:
imwheel -b "4 5" > /dev/null 2>&1`

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

trivenge

### (Optional) Additional Comments

 If you use visual studio code, you may be prompted with a problem in using `sudo code .bashrc` as it is deemed a vulnerability concern, so I would suggest saying don't worry  but dont use sudo to open things with vs code moving forward, or use a separate program or method.

**Comment by ManonLef** [comment]
Could someone from @TheOdinProject/installations have a look at this suggestion please?

**Comment by CouchofTomato** [comment]
@xandora 

Are you able to give an opinion on this please mate?

**Comment by xandora** [comment]
Where would we put it? The installation lessons are very wordy, and we already have trouble getting people to see some of the very important instructions that should following.

I'd be happy for this to be a sticky in the Discord or linked to in an additional resources section. I'm just not sure how it'd fit in the curriculum lesson itself.

**Comment by CouchofTomato** [comment]
Yeah having it maybe as an additional section might help.

@trivenge what do you think about that?

**Comment by trivenge** [comment]
Sounds good to me. I don't think it needs to be an important section, but more of a quality of life-based section, for those who may get frustrated from this type of thing, especially if they are mouse dependent and are not efficient with keyboard shortcuts and so forth. I think it is a useful quality of life consideration for those who use their scroll wheel and find frustration in noticing a problem in scrolling while moving the mouse in a virtual machine. For reference, I found this happened in virtualbox and vmware, though I presently solely use vmware workstation 17 pro. Though this should not be a problem as this would be ubuntu specific. I have not tested if this problem occurs on anything else except ubuntu and it's variants. So I cannot speak if this occurs in other operating systems. Hope that helps. 

> Yeah having it maybe as an additional section might help.
> 
> @trivenge what do you think about that?

**Comment by ManonLef** [comment]
@trivenge since you've indicated you'd like to work on this, can I assign this to you so you can link to a resource in the additional resources section? This is assuming that you have a resource that contain these instructions.

**Comment by CouchofTomato** [comment]
@trivenge 

Hi mate, are you still interested in working on this or should we open it for others to contribute to?

**Comment by trivenge** [comment]
> @trivenge
> 
> Hi mate, are you still interested in working on this or should we open it for others to contribute to?

Sure, how would you like it to be done? Can also chat on discord if need be.

**Comment by CouchofTomato** [comment]
@trivenge Seems the consensus is to find a resource which describes adding this and then linking to it under the additional resources section in the relevant lesson.

**Comment by farrukh007** [comment]
cat ~/.ssh/id_ed25519.pub
while typing above command showing following error:
'cat' is not recognized as an internal or external command,
operable program or batch file.

**Comment by trivenge** [comment]
> @trivenge Seems the consensus is to find a resource which describes adding this and then linking to it under the additional resources section in the relevant lesson.

I don't know if there is a resource. It's really just to allow proper scrolling in a vm, where scrolling and moving the mouse at the same time currently doesnt work properly. That's where this is a solution for, mainly a quality of life so people feel more comfortable learning and using their vm while they continue studying and learning.
