### ISSUE TITLE
<JavaScript>: <Splitting Deeper Look at Git>

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#26042]
### Describe your suggestion

Per @wise-king-sullyman's suggestion in [this closed pull request](https://github.com/TheOdinProject/curriculum/pull/25803#issuecomment-1646950912), we should split the the deeper look at Git lesson.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

### (Optional) Additional Comments

I’d love to work on this with @wise-king-sullyman and @Ba

**Comment by ManonLef** [comment]
Hi @CBID2 thanks for opening this issue. 
Did you mean to tag `ba` or `baguirre` ?

Do you all have a lesson setup in mind or does that still need fleshing out?

**Comment by rlmoser99** [comment]
I am not sure we need a new lesson just to look at Git history... there was a lot of options discussed in that closed PR and I would put more weight behind @wise-king-sullyman's suggestions than mine.

**Comment by CBID2** [comment]
> Hi @CBID2 thanks for opening this issue. 
> 
> Did you mean to tag `ba` or `baguirre` ?
> 
> 
> 
> Do you all have a lesson setup in mind or does that still need fleshing out?
> 
> 
> 
> 

Hi @ManonLef. I meant @Baguirre03. For some reason, I can't tag people on GitHub's mobile app ugh 😑. I've saved some of content from the closed PR on this [Google Doc](https://docs.google.com/document/d/1xQzMJcwrK2tYvg6E0TuDh1vGttq-HxFHpJKhobGcU_M/edit), but it still needs fleshing out.

**Comment by CBID2** [comment]
> I am not sure we need a new lesson just to look at Git history... there was a lot of options discussed in that closed PR and I would put more weight behind @wise-king-sullyman's suggestions than mine. 
> 
> 
> 
> 

I see @rlmoser99. Maybe I should edit the issue a bit then?

**Comment by rlmoser99** [comment]
Yes, feel free to edit the issue, because the way it is worded right now is not the direction that sully suggested.

**Comment by CBID2** [comment]
> Yes, feel free to edit the issue, because the way it is worded right now is not the direction that sully suggested.

Done

**Comment by rlmoser99** [comment]
@CBID2 To make sure we are all on the same page, can you add more detail about how you want to split the the deeper look at Git lesson? Include a list of information that will stay in that lesson and the what information you want to split out into a new lesson. Currently it is really hard for me to approve this suggestion without more detailed information. I'd much rather work out these details on this issue, then go back and forth on a PR.

**Comment by CBID2** [comment]
> @CBID2 To make sure we are all on the same page, can you add more detail about how you want to split the the deeper look at Git lesson? Include a list of information that will stay in that lesson and the what information you want to split out into a new lesson. Currently it is really hard for me to approve this suggestion without more detailed information. I'd much rather work out these details on this issue, then go back and forth on a PR.

I'm still brainstorming that part @rlmoser99

**Comment by CBID2** [comment]
> https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

Hi @rlmoser99! :) Here are [my ideas on how to split the lessons](https://docs.google.com/document/d/1Hwyc2CYPt2-zIV0bE8ez6d5Z_xaeyZUlb66RfS0e63w/edit?usp=sharing). I put them into two separate ideas so you can visualize the structure and pick the one that best suits TOP's overall curriculum. Personally, I like idea 2 because the topics seem to have a scaffolding method(a formal way of describing a lesson building on another one), but I'm open to suggestions. You too @wise-king-sullyman and @Baguirre03

**Comment by rlmoser99** [comment]
@CBID2 I'm not sure I follow your notes. I thought we were discussing taking the deeper look at Git lesson and making it two lessons. But your notes mention 3 lessons, plus a 2b lesson. 

Plus, I am not sure what you mean by "Lessons to Keep in the current Version "

**Comment by CBID2** [comment]
> @CBID2 I'm not sure I follow your notes. I thought we were discussing taking the deeper look at Git lesson and making it two lessons. But your notes mention 3 lessons, plus a 2b lesson.
> 
> Plus, I am not sure what you mean by "Lessons to Keep in the current Version "

Lessons to Keep in the current version means information to keep in the current version of the lesson. Also, thanks for clarifying that the lessons need to be in two @rlmoser99. I'll go back to my Google Doc and make the necessary adjustments.

**Comment by rlmoser99** [comment]
@CBID2 To help you understand what I think would be the most useful, is for you to take each heading and sub-heading of the current lesson and then divide it into two lessons. I think your current notes left off some of these sections, so it is not clear what you are wanting to do.

A Deeper Look at Git
- Introduction
- Lesson overview
- Changing history
  - Getting set up
  - Setting up the code editor
  - Changing the last commit
  - Changing multiple commits
  - Squashing commits
  - Splitting up a commit
- Working with remotes
  - git push -\-force
- Dangers and best practices
- Branches are pointers
- Assignment
- Additional resources
- Knowledge check

**Comment by CBID2** [comment]
> @CBID2 To help you understand what I think would be the most useful, is for you to take each heading and sub-heading of the current lesson and then divide it into two lessons. I think your current notes left off some of these sections, so it is not clear what you are wanting to do.
> 
> A Deeper Look at Git
> 
> * Introduction
> * Lesson overview
> * Changing history
>   
>   * Getting set up
>   * Setting up the code editor
>   * Changing the last commit
>   * Changing multiple commits
>   * Squashing commits
>   * Splitting up a commit
> * Working with remotes
>   
>   * git push --force
> * Dangers and best practices
> * Branches are pointers
> * Assignment
> * Additional resources
> * Knowledge check

I made the [changes here](https://docs.google.com/document/d/1Hwyc2CYPt2-zIV0bE8ez6d5Z_xaeyZUlb66RfS0e63w/edit?usp=sharing) @rlmoser99

**Comment by rlmoser99** [comment]
@CBID2 Thanks for getting to this so quickly. Two concerns that I have:

In our curriculum, each lesson has it's own introduction, lesson overview, assignment, additional information, and knowledge check. So this format of having 2 lessons share them does not fit into our current structure.

I am not sure the there is enough information in lesson 1 to make it worth splitting it up. Is there a way that makes sense to you to makes two lessons of more equal sizes?
> Lesson 1 
 Changing Git History
Getting Set Up Code Editor
Lesson 2
Changing the last commit
Changing multiple commits
Squashing commits
Splitting commits  
Working with remote —> git push - - force 
Dangers and best practices 
Branches are pointers

**Comment by CBID2** [comment]
> @CBID2 Thanks for getting to this so quickly. Two concerns that I have:
> 
> In our curriculum, each lesson has it's own introduction, lesson overview, assignment, additional information, and knowledge check. So this format of having 2 lessons share them does not fit into our current structure.
> 
> I am not sure the there is enough information in lesson 1 to make it worth splitting it up. Is there a way that makes sense to you to makes two lessons of more equal sizes?
> 
> > Lesson 1
> > Changing Git History
> > Getting Set Up Code Editor
> > Lesson 2
> > Changing the last commit
> > Changing multiple commits
> > Squashing commits
> > Splitting commits
> > Working with remote —> git push - - force
> > Dangers and best practices
> > Branches are pointers

Hmmm... 🤔. Since changing commits is the first actual thing learners do after they set up their IDE, I'm thinking "Changing the last commit" and Changing multiple commits can turn into Changing commits and be placed into Lesson 1. For lesson 2, I'm thinking it can focus on Squashing and Splitting commits, and working with remote. As far as the Dangers and best practices and branches are pointers section, I think it would best to organize them as an optional assignment since they seem to be like things TOP wants learners to consider as they work with Git.  Here it is in full:
 Lesson 1
Changing Git History
Getting Set Up Code Editor
Changing Commits (this is combining the sections "Changing the last commit" and "Changing multiple commits" together)
Lesson 2
Squashing and Splitting commits
Working with remote ---> git push -- force 
Additional Resources
Best practices 
Branches are pointers 

What do you think now @rlmoser99?

**Comment by rlmoser99** [comment]
@CBID2 I do not think the solution is to take the Best practices and Branches are pointers sections and making them be an optional assignment. We think this information is important for everyone to know, so making it optional communicates that it is not important. Plus, the lesson format is pretty standard with Additional Resources being the last thing in the lesson.
https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lesson-layout

**Comment by CBID2** [comment]
> @CBID2 I do not think the solution is to take the Best practices and Branches are pointers sections and making them be an optional assignment. We think this information is important for everyone to know, so making it optional communicates that it is not important. Plus, the lesson format is pretty standard with Additional Resources being the last thing in the lesson.
> 
> https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lesson-layout

How about this?

Lesson 1
Changing Git History
Getting Set Up Code Editor
Changing Commits (this is combining the sections "Changing the last commit" and "Changing multiple commits" together)
Lesson 2
Squashing and Splitting commits
Working with remote repos and branches (combining the lesson on working remote with remote repos and branches)
Best practices and dangers

How about now @rmoser99?

**Comment by rlmoser99** [comment]
@CBID2 I'm not sure combining two sections (either in first or section lesson) is the best solution. I think it makes sense to keep them separate, so that this information is easily found when reviewing the lesson.

However, your list does not really communicate what is a heading and what is a sub-heading in the lesson. So maybe what I am missing is having these two lessons with a complete bullet list of headings and sub-headings like this: https://github.com/TheOdinProject/curriculum/issues/26042#issuecomment-1666585796

**Comment by CBID2** [comment]
Hi @rlmoser99. Here's what I came up with:
 ## Lesson 1 
* Introduction
> * Lesson overview
> * Changing history
>   * Getting set up
>   * Setting up the code editor
>   * Changing the last commit
>   * Changing multiple commits
> * Assignment
> * Additional resources
> * Knowledge check

## Lesson 2
* Introduction
* Lesson overview 
>   * Squashing commits
>   * Splitting up a commit
> * Working with remotes
>   * git push --force
> * Dangers and best practices
> * Branches are pointers
> * Assignment
> * Additional resources
> * Knowledge check

**Comment by rlmoser99** [comment]
@CBID2 Thanks for getting back with this complete bullet list so quickly. I have been reviewing the lesson in more depth and there is a part of me that thinks we need some new content to justify splitting this lesson into two parts. However, maybe I am missing what you'll put in the assignments or something else.

@wise-king-sullyman Would you be able to take over this reviewing this issue because I am in the middle of a busy week with preparing and helping 2 kids move to college.

**Comment by wise-king-sullyman** [comment]
After further thought, I'm also a bit on the fence about splitting this lesson in its current state, but I'm not opposed to it. This _is_ a fairly long and dense lesson.

I wouldn't split the commit squashing and splitting away from the rest of the history changing content though, as I feel like those topics go best with amending and rebasing.

If we are to split this lesson I would split it at the remote section.

**Comment by CBID2** [comment]
> After further thought, I'm also a bit on the fence about splitting this lesson in its current state, but I'm not opposed to it. This _is_ a fairly long and dense lesson.
> 
> I wouldn't split the commit squashing and splitting away from the rest of the history changing content though, as I feel like those topics go best with amending and rebasing.
> 
> If we are to split this lesson I would split it at the remote section.

Ok @wise-king-sullyman. So...something like this?
 ## Lesson 2
- Working with remotes
   - git push --force
 - Assignment
  - Make a copy of [this open source project](https://github.com/firstcontributions/first-contributions/blob/main/README.md) and try to make your first contribution (I came up with this as a way to put their new-found knowledge into practice) 
  - Additional Resources
    - Read the chapter on Branches covered by git-scm to deepen your knowledge about Branches 
    - Check out this [VS Code extension](https://marketplace.visualstudio.com/items?itemName=github.remotehub) to further your experience with remote repositories. 
 - Knowledge Check
   - What is the safest way to push commit history changes to a remote repository?
   - What happens when changes are pushed to a local branch that has not been updated yet? 
   - When should the `--force` be used?

**Comment by wise-king-sullyman** [comment]
I'm not sure that going through a regular fork/clone/commit/push cycle would really flex the muscles we want to flex here. And since we've already told learners to follow along during the process of the lesson there's already an interactive element to the lesson.

We _could_ link this [gamified Git practice resource](https://learngitbranching.js.org) as a new assignment. It's a little bit rough around the edges so I'd love to hear some others thoughts on it, but I know that it helped me understand some of the more difficult concepts.

Alternatively, I don't think it would be bad for us to leave the assignments as they are and just split them between the new lessons. In which case I think the best layout would be for the assignments that are currently 1 and 2 to be in the second lesson, and 3 and 4 in the first. We could also add the Branches chapter of git-scm as an assignment on the second lesson.
 
The new VS Code extension additional resource you proposed I'm not sure about since it's still in a prerelease state.

**Comment by CBID2** [comment]
> I'm not sure that going through a regular fork/clone/commit/push cycle would really flex the muscles we want to flex here. And since we've already told learners to follow along during the process of the lesson there's already an interactive element to the lesson.
> 
> 
> 
> We _could_ link this [gamified Git practice resource](https://learngitbranching.js.org) as a new assignment. It's a little bit rough around the edges so I'd love to hear some others thoughts on it, but I know that it helped me understand some of the more difficult concepts.
> 
> 
> 
> Alternatively, I don't think it would be bad for us to leave the assignments as they are and just split them between the new lessons. In which case I think the best layout would be for the assignments that are currently 1 and 2 to be in the second lesson, and 3 and 4 in the first. We could also add the Branches chapter of git-scm as an assignment on the second lesson.
> 
>  
> 
> The new VS Code extension additional resource you proposed I'm not sure about since it's still in a prerelease state.
> 
> 
> 
> EDIT: actually right after I hit send I realized that a better setup would probably be to have the branches chapter of git-scm as an assignment in the second lesson and have that gamified practice resource as an additional resource.

I'm not on my computer so I'll check out the game later.

**Comment by Asartea** [comment]
> We could link this [gamified Git practice resource](https://learngitbranching.js.org/) as a new assignment. It's a little bit rough around the edges so I'd love to hear some others thoughts on it, but I know that it helped me understand some of the more difficult concepts.

I was actually playing this like yesterday because someone linked it in the Discord, and my main concern is that it builds up very deep into local work before even touching remotes, and then only really uses remotes in the context of these advanced git commands.

On the other hand, it is an amazing resource, and it does really help solidify the concepts in your mind.

**Comment by Mclilzee** [comment]
> > We could link this [gamified Git practice resource](https://learngitbranching.js.org/) as a new assignment. It's a little bit rough around the edges so I'd love to hear some others thoughts on it, but I know that it helped me understand some of the more difficult concepts.

> On the other hand, it is an amazing resource, and it does really help solidify the concepts in your mind.

It's a fantastic website, It would be a must to introduce it in some form in the lessons. It is split into different sections and exercises, so it is not a bad idea to even introduce it in all Git lessons, by instructing users which section to finish. Just like we do with the exercises.

**Comment by CBID2** [comment]
> > > We could link this [gamified Git practice resource](https://learngitbranching.js.org/) as a new assignment. It's a little bit rough around the edges so I'd love to hear some others thoughts on it, but I know that it helped me understand some of the more difficult concepts.
> 
> > On the other hand, it is an amazing resource, and it does really help solidify the concepts in your mind.
> 
> It's a fantastic website, It would be a must to introduce it in some form in the lessons. It is split into different sections and exercises, so it is not a bad idea to even introduce it in all Git lessons, by instructing users which section to finish. Just like we do with the exercises.

Ooh you just go an idea @Mclilzee

**Comment by wise-king-sullyman** [comment]
Instructing learners to only do certain sections in multiple lessons is an interesting idea, but I'm a _bit_ weary about that as in the past we've had a good amount of people go further than they should in the exercise repos accidentally.

**Comment by CBID2** [comment]
> Instructing learners to only do certain sections in multiple lessons is an interesting idea, but I'm a _bit_ weary about that as in the past we've had a good amount of people go further than they should in the exercise repos accidentally.

I understand @wise-king-sullyman. To address this concern, there could be a little note on highly recommending certain parts of the game and they can go on to other parts of it and the other lessons if they feel comfortable. Some learners grasp concepts quickly, so we don't want to make them feel confined. Speaking of the game, I tried it, and it's pretty good.

**Comment by wise-king-sullyman** [comment]
I would still rather see it as an additional resource linked on the second of your lessons here. While splitting it amongst the lessons is an interesting idea my knowledge of learner experience with the exercise repos says that keeping it simple and having it listed in one place is a better plan.

**Comment by CBID2** [comment]
> I would still rather see it as an additional resource linked on the second of your lessons here. While splitting it amongst the lessons is an interesting idea my knowledge of learner experience with the exercise repos says that keeping it simple and having it listed in one place is a better plan.

Ok I understand @wise-king-sullyman

**Comment by CBID2** [comment]
Hey @wise-king-sullyman and co. I apologize for the delay due to other obligations. Anywho, I made [the draft PR of the new lesson](https://github.com/TheOdinProject/curriculum/pull/26118). Check it out when you're free! :)
