### ISSUE TITLE
Advanced Javascrip : Small addition to the Factory Functions and Module Pattern module

### ISSUE THREAD

**Issue by Haswell-s** [TheOdinProject/curriculum#26049]
### Describe your suggestion

This is a much simpler way to explain the Object.assign() and its real-world implications in a video format.
[Video on Object.assign()](https://www.youtube.com/watch?v=JmGJUzNsGFs)

And another point to address would be the Backbone reference in the [article](https://medium.com/javascript-scene/3-different-kinds-of-prototypal-inheritance-es6-edition-32d777fa16c9) at the [Scopes section](https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#scope-and-closure), since it is referenced heavily in the video.
You could write something like: "The Backbone framework mentioned in the article was the first one to introduce the MVC pattern (Which we cover later in this course) to Javascript, coupled with event-driven development. See [this](https://www.youtube.com/watch?v=RBgm7Zgv2dM) video for more context on the subject. this framework is a thing of the past, thus there is no need to dive too deep into it."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#scope-and-closure

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Haswell

### (Optional) Additional Comments

I'm not that good at professional writing, therefore the help of a native speaker would be highly appreciated.
I would surely like to be notified if my advice is implemented in the curriculum, this is my first contribution to the project after all :)

**Comment by ManonLef** [comment]
@TheOdinProject/javascript could you please offer some insights here? :)

**Comment by wise-king-sullyman** [comment]
@i5x64BIT Thank you for taking the time to make this issue, but I'm not sure I'm understanding your proposal here.

- Where do you think this video should be added? (i.e. as an assignment, additional resource, etc)
- Do you think it should replace other existing content?
- Does this video cover material that we currently don't cover, or just cover it in video form rather than text?

Regarding the references to Backbone I would say that we can just tell learners not to worry about it rather than link to a video explaining it.

**Comment by i5x64BIT** [comment]
Yes, the first one is a video format of object.assing that explains more clearly the concept and usage than the MDN article.

And about Backbone, I agree.
Nevertheless, I would consider mentioning the reasons for why it was used in the past.

**Comment by codyloyd** [comment]
@i5x64BIT 

- Where do you think this video should be added? (i.e. as an assignment, additional resource, etc)
- Do you think it should replace other existing content?

**Comment by i5x64BIT** [comment]
### For object.assign() :
![Screenshot from 2023-08-09 05-57-32](https://github.com/TheOdinProject/curriculum/assets/62185136/02b4e62a-8adb-4869-ab6f-b96878f74860) 
<br>Over at "Back to factory functions"
... you can certainly do that as well with ```Object.assign``` (read the docs for that one [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)) or watch [this video](https://www.youtube.com/watch?v=JmGJUzNsGFs).

### For backbone.js
![Screenshot from 2023-08-09 06-12-21](https://github.com/TheOdinProject/curriculum/assets/62185136/dbd04b35-b76d-467f-9991-d629f37e9339)
Before moving on have a look at [this](https://medium.com/javascript-scene/3-different-kinds-of-prototypal-inheritance-es6-edition-32d777fa16c9) article. That's a tough one but you will get rewarded if you spend some time with it, Good Stuff!
A notice about ```backbone.js```, this is a javascript framework from the past. Don't spend much time on it, [this video](https://www.youtube.com/watch?v=RBgm7Zgv2dM) should suffice.

**Comment by codyloyd** [comment]
nice... thanks.

I like the addition of the Object.assign video, but I think it should be moved to 'additional resources' instead of included inline here.

I don't think adding a resource about backbone.js is worth it.

**Comment by codyloyd** [comment]
@i5x64BIT if you want to go ahead and do a PR with this change, that would be great. Iv'e assigned this issue to you

**Comment by i5x64BIT** [comment]
@codyloyd 
In that case, I would suggest moving this article to the extra resources too. 
As I see it, these two should go together since I did get a little confused in my learning journey.

And a small remark, thanks to odin's resources and that small video about the backbone, I can now understand frontend-lore videos on the fly, without extra resaserch. I would strongly advise to keep them together since, in my opinion, this is worthy addition to the "historical" picture completeness.

**Comment by codyloyd** [comment]
well, there's a pretty clear distinction between the official docs for something and a supplemental video.

what if we move the vid down to additional resources, but put a note there by the docs link that says something like  `(check the additional resources for more about Object.assign if you need it)`
