### ISSUE TITLE
Project: Node project: Basic Informational Site  - Issue with submission replit.com

### ISSUE THREAD

**Issue by fgostev** [TheOdinProject/curriculum#26045]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Found an issue with this page. At the end of the assignment is mentioned that if we went to submit our work to the page we can deploy it with replit.com. However, seems that Replit from now is behind a paywall. I tried to double-check students' submissions - everyones pages are re-directed to relit and none seems to be deployed. 

<img width="737" alt="Screenshot 2023-08-03 at 17 53 21" src="https://github.com/TheOdinProject/theodinproject/assets/50133788/f944f909-963b-4c11-adba-459102ef41bd">
<img width="712" alt="Screenshot 2023-08-03 at 17 53 36" src="https://github.com/TheOdinProject/theodinproject/assets/50133788/a2e14255-4fc4-4122-a13d-55615cd5ba8a">
<img width="760" alt="Screenshot 2023-08-03 at 17 53 34" src="https://github.com/TheOdinProject/theodinproject/assets/50133788/24773742-1219-44d9-b47f-9e1ae04ca738">

**2. Acceptance Criteria:**

**3. Additional Information:**

-Just as a small note - I won't mind to try to work on it, but I'm quite I'm just learning node now so I will be okay also if it will be assigned to someone else (that's why haven't checked the box)

**Comment by thatblindgeye** [comment]
May need more context for this issue. Going through the steps mentioned in the screenshot, I was able to create a new Repl + import from GitHub just fine (a private repo I couldn't, though).

If the main issue is that existing solutions don't lead to a proper preview, I'm wondering if it's more a case of the urls needing to be updated by those users. There was one I clicked at random that did work correctly.

**Comment by fgostev** [comment]
From my experience when I tried to follow it I was able to deploy in a
preview link, however if I would enter in an hour or so after - the link
wouldn't work. From my understanding it has to do with reply being paid
only, but I might be wrong as well.

**Comment by ManonLef** [comment]
I haven't seen this come up as an issue anymore. I will close it and we can reopen as needed.

**Comment by kentshenlim** [comment]
This is still an issue. For those who couldn't even see a preview on Replit, try adding "scripts": {"start": "node <index.js>"} into your package.json, where the index.js is the name of your server js file. This step was not outlined in the curriculum.
