### ISSUE TITLE
foundations-installations: Mention that the username in a VM should not start with an uppercase letter.

### ISSUE THREAD

**Issue by EverlastingKraut** [TheOdinProject/curriculum#26055]
### Describe your suggestion

The automatic installation of Xubuntu in the VM halted, because my username started with an uppercase letter(see bottom of screenshot). This would be useful in the installation guide (at this time, it isn't mentioned. Top of screenshot)
![image](https://github.com/TheOdinProject/curriculum/assets/141327360/94a650ab-6675-4525-8b8f-9d805a33f2c3)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

EverlastingKraut

### (Optional) Additional Comments

This is my first action ever an github (besides the initial hello world-tutorial). Pleas tell me, if I did something wrong/odd.

**Comment by ManonLef** [comment]
Does that screen come up straight away upon entering a capitalized username?

**Comment by EverlastingKraut** [comment]
No. That screen comes up a few minutes into the unattended installation. I recreated the moment by setting up another VM:
![Preview](https://github.com/TheOdinProject/curriculum/assets/141327360/e3e9b0f2-eb15-45e1-b700-97442d4bcfc3)

**Comment by ManonLef** [comment]
Thanks for elaborating! I will open this up for someone to work on!

**Comment by ben-oldham1** [comment]
Hey, i'm interested in having a go at this. It's my first issue so hopefully should be simple enough!

**Comment by ManonLef** [comment]
@ben-oldham1 I'll assign you!

**Comment by ManonLef** [comment]
Let me know if you need any help. Thanks for doing this

**Comment by ben-oldham1** [comment]
Will do, thank you!
