### ISSUE TITLE
Intermediate HTML and CSS Course: Positioning: The url of the picture doesn't work in example of CodeOpen

### ISSUE THREAD

**Issue by ena0berzerk** [TheOdinProject/curriculum#26052]
### Describe your suggestion

![img](https://github.com/TheOdinProject/curriculum/assets/110235307/be4ce2c6-0079-471a-a69f-ad4f71f80e7b)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-positioning

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Thanks for opening an issue! I don't see an issue here so it's local 
![Screenshot 2023-08-06 at 00 39 47](https://github.com/TheOdinProject/curriculum/assets/81025586/218e2c8c-b140-4234-9c2f-b4f2e5238ef1)
