### ISSUE TITLE
Fetching Data In React: MicroVM failing to load 

### ISSUE THREAD

**Issue by Eveieve** [TheOdinProject/curriculum#26053]
### Describe your suggestion

- microVM is failing to load in the lesson

![image](https://github.com/TheOdinProject/curriculum/assets/85281165/d2e683f0-8b3b-4a69-9d6d-188e56ab1fa0)

I refresh the page and the issue persists. The embedded link fails to load anything. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react#managing-multiple-fetch-requests

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
I have opened it up as a bug. Thanks for reporting!

@TheOdinProject/javascript if anyone has any idea how to fix this, please advise

**Comment by ManonLef** [comment]
@Eveieve I'm not sure what you mean by the tag not being `activated` since it looks fine to me!

Yes I can reproduce this error. It indeed doesn't work.

**Comment by ZachPoole** [comment]
This looks like it affects all CodeSandox examples. https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

Network tab shows JWT Auth failed. Maybe something wrong with the build to add the API Key?

**Comment by ManonLef** [comment]
I have opened this up for it does involve multiple lessons. I haven't looked into the problem yet but hopefully, others will find out where the issue lies!

**Comment by Lofty-Brambles** [comment]
I'll take a peek at this ASAP.

**Comment by ManonLef** [comment]
@TheOdinProject/core-team team-guess regarding maintainer with codesandbox login. See above ☝️

**Comment by wise-king-sullyman** [comment]
I don't seem to be seeing this error.
![image](https://github.com/TheOdinProject/curriculum/assets/7115053/39d556c6-0360-4034-85da-85a3c450167e)

Is this something you all are still seeing?

**Comment by ZachPoole** [comment]
Fixed for me!

**Comment by ManonLef** [comment]
@wise-king-sullyman I've been keeping an eye on this for two days while it failed to work or start up. I swear it didn't until you put your eyes on it 😆

**Comment by wise-king-sullyman** [comment]
@ManonLef I'm just that good 😂
