### ISSUE TITLE
Foundations: Intro to CSS

### ISSUE THREAD

**Issue by housepanther** [TheOdinProject/curriculum#26050]
### Describe your suggestion

Greetings! Something I discovered that was really useful to me in helping to begin to grasp how CSS works is creating a playground environment to use with the example code fragments provided in this lesson and in future lessons. I found the tactile approach of actively typing the code fragments in helped commit concepts to memory. Additionally, I could see visually and almost in real time how the changes I made impacted (or failed to impact) the styling. I would like to recommend adding the following to the beginning of the lesson curriculum:

**Setting up a Playground Environment**
Prior to beginning the journey into learning CSS is the time to setup a _playground_ environment in VS Code. The playground is a space that you may use to practice the CSS concepts introduced in this lesson and expounded on in future lessons. The idea is to try typing in the example code fragments and observing what happens. Once you do this, try making small changes in the example code fragments and observe what happens or even fails to happen as expected. This will help you to grasp concepts that may be challenging and causing you to struggle.  

A playground environment will also come in handy when working on the future assignments and projects in Odin. In some of these assignments, you may want to test an idea out separately. Testing an idea out separately from your main workspace, can help lessen the possibility of breaking something that is already working.

Here is how to go about setting up a playground environment:

1. Create the playground files in the root of your home directory by typing the following in your terminal:
```
cd ~
touch playground.html
touch playground.css
````
2. Open the playground.html file in VS Code and add the boilerplate template to it. Take note of the "" tag as this is the comment in HTML. Comments in HTML have no impact on the presentation. The comment will be there to remind you that your working in your playground environment.  
```
<!-- This is the playground for file for HTML -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset lang="en">
        <title>Playground for Testing</title>
        <link rel="stylesheet" href="./playground.css">
    </head>
    <body>
       
    </body>
</html>
```
3. Open the playground.css file in VS Code and add the fragment below to the first line of the file. This fragment is a comment in CSS, and like the HTML comment, will have no impact on the way CSS works. Again, this is just to help remind you that you are working in your playground environment. There will be more on CSS comments in future lessons.
```
/* This is the playground file for CSS*/
```

Be sure to save your work. Now that you have your basic playground built, you can begin to dive into CSS. You will find this playground to be invaluable once you start learning JavaScript and/or Ruby. What you can do is create playground files for one or both languages. This can even help you develop good future web development habits.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

housepanther.03031977

### (Optional) Additional Comments

The above are just some thoughts for helping to improve the curriculum. Since I am on the autistic spectrum, I learned to become hyper-aware of how I learn and how to learn. I am hoping to impart some of this learning into Odin. Please feel free to reach out to me for any clarifications.

**Comment by codyloyd** [comment]
I think we already mention, several times that it's beneficial to play around and experiment with the code examples we give, so I'm not sure that adding this explicit instruction is necessary.

Also, there are many ways someone could experiment with stuff like this, such as codepen/repl.it or even just messing around in devtools.

@TheOdinProject/foundations how do y'all feel about this suggestion?  Do we think this is something worth adding somewhere?

**Comment by ManonLef** [comment]
I agree with @codyloyd and it’s what I also tried to mention in [this comment](https://github.com/TheOdinProject/curriculum/issues/26030#issuecomment-1666197446) but might have come across as a personal opinion instead. TOP suggests to code along many times from the start and presents various way to do so.
