### ISSUE TITLE
Move Scrimbs embeds to Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26057]
The existing Scrimba embeds in lessons should be moved from their current position and added to Additional Resources as link text instead of embedded. This link text should align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Guidance:

- Comment on this issue to let us know you'd like to get a set of lessons assigned to you (one of the bulleted checkboxes). You can also ask for a specific one. 
- Please do not work on all of the lessons; we'd like to spread this contribution to more people for experience
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` keyword. 

### Lessons to update

- [ ] @aniket-agra - [Block and inline](https://www.theodinproject.com/lessons/foundations-block-and-inline), [The box model](https://www.theodinproject.com/lessons/foundations-the-box-model), and [Alignment](https://www.theodinproject.com/lessons/foundations-alignment)
- [ ] @SohamKukreti - [Axes](https://www.theodinproject.com/lessons/foundations-axes), [Growing and shrinking](https://www.theodinproject.com/lessons/foundations-growing-and-shrinking), and [Introduction to Flexbox](https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox)
- [x] @ht-l1 - [Async and await](https://www.theodinproject.com/lessons/node-path-javascript-async-and-await) and [Asynchronous code](https://www.theodinproject.com/lessons/node-path-javascript-asynchronous-code)
- [x] @ToobaJamal - [factory functions and module pattern](https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern), and [objects and object constructors](https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors)

**Comment by aniket-agra** [comment]
Hi, I'd like to work on this for the block and inline, the box model, and alignment lessons.

**Comment by thatblindgeye** [comment]
@aniket-agra you got it!

**Comment by SohamKukreti** [comment]
Hi, I would like to work on the Axes, Growing and shrinking, and Introduction to Flexbox lessons.

**Comment by thatblindgeye** [comment]
@SohamKukreti all yours!

**Comment by ht-l1** [comment]
hey can I work on Async and await, and Asynchronous code?

**Comment by thatblindgeye** [comment]
@ht-l1 if you'd prefer doing only those 2 lessons I'll assign you those 2!

**Comment by ToobaJamal** [comment]
Hey, I would like to take the fourth bullet :)

**Comment by thatblindgeye** [comment]
@ToobaJamal all yours!
