### ISSUE TITLE
Styling react applications: Change the placeholder text for when reporting an issue to the curriculum repo

### ISSUE THREAD

**Issue by Eveieve** [TheOdinProject/curriculum#26054]
### Describe your suggestion

Currently, when redirected to an issue reporting page as such: https://github.com/TheOdinProject/curriculum/issues/new?assignees=nil&labels=Status%3A+Needs+Triage&projects=&template=suggestion.yaml&title=Styling%20React%20Applications%3A+%3CShort+description+of+your+suggestion%3E

The `Describe your suggestion` text field has a placeholder of 'There is a typo in this lesson...'. However, for obvious typo fixes, they are encouraged to request a PR directly, per TOP's contributing guide. How about changing the placeholder text to something that's more fitting to the 'reporting/opening an issue'? 

![image](https://github.com/TheOdinProject/curriculum/assets/85281165/92802c88-4f40-49e0-a296-be16932159ce)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-styling-react-applications

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

This issue is not particular to the lesson linked, but I'm linking it just so that other reviewers can take a look at it.

**Comment by ManonLef** [comment]
If this is something we have control over, this could be added to the issue opened yesterday to avoid duplicate fixes @JustWaveThings  https://github.com/TheOdinProject/theodinproject/issues/4066

Thanks for reporting
