### ISSUE TITLE
Setting Up A React Environment: Assignment's link to "guide for React Developer Tools" isn't working

### ISSUE THREAD

**Issue by QuicksVolex1** [TheOdinProject/curriculum#26069]
### Describe your suggestion

The link to the second assignment isn't working properly, the website give the 500 code error;

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Lofty-Brambles** [comment]
https://www.pluralsight.com/guides/debugging-components-with-react-developer-tools loads fine for me? Can you specify the link?

**Comment by QuicksVolex1** [comment]
This is [the link](https://www.pluralsight.com/guides/debugging-components-with-react-developer-tools), and its still not working for me.
