### ISSUE TITLE
Foundations: add hyperlinks to common errors and solutions

### ISSUE THREAD

**Issue by MuhammadAbdullahWarraich** [TheOdinProject/curriculum#26063]
### Describe your suggestion

I faced some problems during the "Installing Node.js" lesson in the "JavaScript Basics" section. My problem was fixed with the help of these two webpages: 

https://www.tecmint.com/sub-process-usr-bin-dpkg-returned-an-error-in-ubuntu/

https://askubuntu.com/questions/1116778/how-to-set-the-resume-variable-to-override-these-issues

I was motivated to make a PR to add these urls under the heading of common errors and their fixes or under the heading of Additional Resources but I was concerned that it seems against TOP's philosophy to spoon-feed learners with solutions to every possible problem. On the other hand, again, exists my sympathy towards new learners who may not have become confident enough to believe that the answer to even the most complex problem may just be a search away, unlike people like me, who have a little bit of a background in computer science(1 year c++) and know that often duct-taping solutions from StackOverflow does the trick.

What do you guys think, should this feature be added, atleast to the lessons involving installations?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installing-node-js

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Many errors can and will arise during installations, googling, and handling said errors is covered a few lessons before that. At that point in the curriculum, learners should be or get very comfortable researching and troubleshooting. 

Thanks for bringing it up though!

**Comment by MuhammadAbdullahWarraich** [comment]
Thank you for clearing my head!
