### ISSUE TITLE
httpbin

### ISSUE THREAD

**Issue by AL04723** [TheOdinProject/curriculum#26075]
### Describe your suggestion

http://httpbin.org/
504 Gateway Time-out

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics#introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Lofty-Brambles** [comment]
@AL04723  Can you please provide more information on this?
