### ISSUE TITLE
<React>: Fix error in (The unexpected infinite loop) section in (More on state) lesson

### ISSUE THREAD

**Issue by ahmeducf** [TheOdinProject/curriculum#26071]
### Describe your suggestion
![image](https://github.com/ahmeducf/curriculum/assets/53626822/581a678c-c706-48c6-b8ea-a9cc5a882318)

The code snippet in this example was supposed to go infinite, as said in the lesson, but what actually happens is it throws an error:

***Uncaught TypeError: Cannot read properties of undefined (reading 'toLocaleTimeString')***

the solution is easy, just initialize the **time** state with a **Date** object.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-more-on-state

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

ahmeducf

**Comment by codyloyd** [comment]
this seems reasonable, but we should get some input/verification from @TheOdinProject/react

**Comment by codyloyd** [comment]
@01zulfi might want to have a look too 😄

**Comment by wise-king-sullyman** [comment]
Checks out to me

**Comment by 01zulfi** [comment]
Definitely needs to be fixed, now sure how it sneaked in there 😆

**Comment by 01zulfi** [comment]
@ahmeducf I've assigned you, please make a PR to fix this, thanks!
