### ISSUE TITLE
Form Validation: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Sherab-Z** [TheOdinProject/curriculum#26086]
### Describe your suggestion

The suggested reading article at the bottom named 'Regular Expressions clearly explained' is a Medium article and is now hidden behind a paywall. Here's the link: https://towardsdatascience.com/regular-expressions-clearly-explained-with-examples-822d76b037b4

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-validation#required-validation

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

Thank you all for all your work! I'm gaining so much from TOP :)

**Comment by fabulousgk** [comment]
I will take this

**Comment by fabulousgk** [comment]
I was thinking of replacing it with these two:

https://www.sitepoint.com/learn-regex/
https://www.sitepoint.com/demystifying-regex-with-practical-examples/
