### ISSUE TITLE
Foundations: GitHub pages bug

### ISSUE THREAD

**Issue by UniquePixels** [TheOdinProject/curriculum#26081]
### Describe your suggestion

GitHub frequently glitches when publishing a page.  You have to reset your branch to get it actually to deploy.

As this comes up in discord very frequently, I am thinking an additional note in the recipes lesson that mentions this might be appropriate.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

fabulousgk

**Comment by codyloyd** [comment]
Looking for feedback from @TheOdinProject/foundations 

My take: I haven't seen this personally.. but I don't use GH pages all that much.  If it's coming up quite a lot, and there's an easy fix (even if that fix is just "try again until it works") we should probably add it.

**Comment by ManonLef** [comment]
I’ve personally never experienced this.

**Comment by fabulousgk** [comment]
I have never had the issue myself.  But it is a daily question in Discord.  Essentially, they set the branch to Main and push save, but the page never deploys.  You have to set it to none then save, then main then save.
\

**Comment by ManonLef** [comment]
If you could share the link here, that would be great. I’ll not be on discord for a bit and here we know it doesn’t get lost. Please share all examples you have if there are more. Thanks in advance!

**Comment by fabulousgk** [comment]
Here are three, the last one is where I leaned about the issue myself:

https://discord.com/channels/505093832157691914/690639791380758558/1138480373467193394

https://discord.com/channels/505093832157691914/690639791380758558/1135067121446043748

https://discord.com/channels/505093832157691914/690639791380758558/1134992500331913289

**Comment by ManonLef** [comment]
I noticed these were mostly new users so I dug a little deeper in the realms of our Discord. 
I think we could add a note as there are indeed many cases. I do believe that many of these should have asked for a repo link to confirm it was set up correctly and to check if pages failed for some reason. 

However, adding a note that a redeploy as you proposed might fix the issue but also stating they have to make sure everything else is set up correctly/pushed etc., sounds like a plan. 

I'll assign you!
