### ISSUE TITLE
Installing Node.js: Update NVM version to latest (v0.39.4)

### ISSUE THREAD

**Issue by jherot** [TheOdinProject/curriculum#26095]
### Describe your suggestion

In the section Installation on MacOS, the version of NVM that is installed in the second step is v0.39.3.

According to the documentation on the nvm-sh/nvm repo on GitHub, the latest version is now v0.39.4. This is minor but I thought I would point it out, as I had to install via the lesson then update via the repo.

I suggest changing the second line from:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
to:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
simply to give Odin users the latest version of NVM.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installing-node-js

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

grandwaffle

### (Optional) Additional Comments

I'm new to this whole issue and pull request thing... I hope that my pointing this out has been meaningful in some small way.

**Comment by codyloyd** [comment]
Seems reasonable.  I'll move this ticket to 'in progress' and assign you.
