### ISSUE TITLE
Form Basics: Dead link in the assignment

### ISSUE THREAD

**Issue by MikeCodesSomething** [TheOdinProject/curriculum#26099]
### Describe your suggestion

In the assignment of [this page](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics) one of the links in the bullet point no longer works. Page appears to be dead.

"Read and follow along to the internetingishard guide to forms: https://internetingishard.netlify.app/html-and-css/forms/index.html "

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by codyloyd** [comment]
this link works for me 🤔 

@TheOdinProject/foundations anyone else around to give it a try?

**Comment by MikeCodesSomething** [comment]
> this link works for me 🤔
> 
> @TheOdinProject/foundations anyone else around to give it a try?

Just tried it again now and it's working, guess it was down temporarily as I tried it on a couple of devices. Thanks for checking, closing this now.

**Comment by fabulousgk** [comment]
When I go to the link I get a warning from Avast
