### ISSUE TITLE
Working with APIs: <Short description of your suggestion>

### ISSUE THREAD

**Issue by HappySlappyFace** [TheOdinProject/curriculum#26108]
### Assignment
Question 4 mentions the following
"You should also investigate adding a `.catch()` to the end of the promise chain in case Giphy doesn't find any gifs with the searched keyword. "
after looking into it it seems like giphy's api is faulty and will return a status code of 200 with no data if the search term doesnt exist ( shown in the photo below is the search term `fetching data` having no images but still containing status code 200 )
![FancyWM_yLxYdTsA8E](https://github.com/TheOdinProject/curriculum/assets/11047926/a012da7b-57c2-47d5-9d7d-2cdef290a299)
personally the question isn't very clear and it should be refactored to for example "add a .then statement to handle the empty data array by raising a new error then handling it in the .catch at the end"

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

HappySlappyFace

### (Optional) Additional Comments

i suppose this is a bit of a blurry area because theoredically APIs should handle such errors in a better way than giphy did

**Comment by Lofty-Brambles** [comment]
fetch requests only throw error when network error occurs.. Seems like a solid point to cover. I wonder if there should be a mention about it, or if this should be covered properly in a section as well.

**Comment by HappySlappyFace** [comment]
as someone who is just learning promises and having a bit of prior knowledge to how all of this stuff works, i feel like for ppl that are just new to all of this status codes and catching errors stuff that it is mandatory to cover this exact point about giphy mishandling status codes.

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by codyloyd** [comment]
I agree that a little clarification is necessary here.

@HappySlappyFace you mentioned you wanted to work on this issue, so i'm going to move it to 'in progress' and assign it to you.  If you do not want to do the work let me know so we can find someone else to cover it.

**Comment by HappySlappyFace** [comment]
just submitted a pull request https://github.com/TheOdinProject/curriculum/pull/26136

**Comment by wise-king-sullyman** [comment]
Should #26136 have closed this issue?

**Comment by CouchofTomato** [comment]
Yeah it looks like it should have so I'm closing out.
