### ISSUE TITLE
JS: Improve explanation on the point of Webpack/bundlers

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26104]
### Describe your suggestion

I remember when going through the Webpack lessons/tutorials that I was *very* stuck on understand the point of using webpack (especially with all the configuration needed), especially when the official webpack tutorials linked as assignments, in my honest opinion, do not do the greatest job of explaining the point/benefits in using a bundler in general vs no bundler at all. They feel like they focus more on the "what" with simply telling you what code/config to achieve specific things that still leave you with more questions on "why would this ever be useful".

Evidently from multiple discord conversations, people have felt the same (both going through it and looking back at it). A big example of this is multiple entry points - something that especially nowadays with smallers SPAs (which is what most if not all of the projects for the rest of the JS course are) you may not need - I've seen plenty get so confused as to what this is for/why you'd use multiple entry points and start trying to do so for their restaurant page/todo list which understandably confuses them further since they shouldn't need it. The official tutorial on that only briefly mentions the use of it including a short link to code splitting at the very top of the page.

I feel the section on webpack in the ES6 modules lesson in particular could greatly benefit from a little more explicit explanation into why bundlers are used and some simple reasons why someone would benefit from using one over not.
Something even like a short explanation about the server needing to download multiple JS module files as well as any dependencies individually, and how a bundler can bundle everything into a single file which is more performant to download *and* includes all dependencies for that bundle.

One such resource that was of great help to me was: https://snipcart.com/blog/javascript-module-bundler
Simply to explain and demonstrate the difference between using a bundler and not.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-es6-modules and possibly also https://www.theodinproject.com/lessons/node-path-javascript-webpack

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Can someone take a look please.

**Comment by codyloyd** [comment]
I agree that this section needs some work... but as it's definitely not just a quick-fix, I'm not sure if it's something we can actually stick on our backlog at the moment.

Definitely worth having a discussion here though.

@TheOdinProject/javascript what does everyone think?  Is there a good solution to be had here that's not a complete rework of the content?

**Comment by MaoShizhong** [comment]
The very first thing that came to mind for me based on my experience and what other's have said/struggled with, is primarily the point of using a) webpack, and really, b) a bundler in the first place.
Until then, we wouldn't have worked with multiple JS files and unlikely multiple dependencies and all, so the whole concept of why bundle anything is alien, which feeds into "well then what *is* the point of webpack other than to just be confusing with all this config?".

I think at the very least, it would make sense to "set the scene" when introducing webpack in ES6 modules with why bundlers are useful, so people know what a bundler is and some of the benefits vs without a bundler.
Then when actually diving into webpack specifically, hopefully then it'll make a little more sense because they know why something like this would be useful and used, and are now learning how to actually use one such bundler.

**Comment by codyloyd** [comment]
I agree with this statement.  THat does sound feasible without a complete rework (though I think it still needs that in the future.

I'll go ahead and set this issue to 'in progress' and assign you to it @MaoShizhong, assuming you still want to do the work.
