### ISSUE TITLE
DOM Manipulation and Events: <Short description of your suggestion>

### ISSUE THREAD

**Issue by thatdeveloperkokou** [TheOdinProject/curriculum#26103]
### Describe your suggestion

On the mobile version of the web app some little text-based feautures has been changed .in the lesson sections the headers are a little bit tiny and the links are not highlighted like before.code too can not be differentiated from text.in the assigment section the tasks are not numbered so you wpuld have to read through without knowing the first thing to do.this is also the problem with the additional resources section.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

_solo911

### (Optional) Additional Comments

it would help if you could help solve this issue

**Comment by KevinMulhern** [comment]
Thanks for reporting @thatdeveloperkokou. That lesson looks ok to me, but I might be looking in the wrong place. Would you mind sharing screenshots of the problems you're seeing please?

**Comment by Luise8** [comment]
Hi, in my phone that lesson looks great too. I tried with Firefox and Chrome.

**Comment by ManonLef** [comment]
@thatdeveloperkokou did you see the below quoted request?

> Thanks for reporting @thatdeveloperkokou. That lesson looks ok to me, but I might be looking in the wrong place. Would you mind sharing screenshots of the problems you're seeing please?
