### ISSUE TITLE
templates: Adding new note box variations to lesson-template.md and lesson-example.md

### ISSUE THREAD

**Issue by luuu-xu** [TheOdinProject/curriculum#26101]
### Describe your suggestion

According to [issue #4045](https://github.com/TheOdinProject/theodinproject/issues/4045), our lesson-note has a new variation: `lesson-note--critical`, we should reflect such addition in our template and examples to provide better documentation for lesson content contributors later on.

### Path

Other / NA

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/templates/lesson-example.md

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks @luuu-xu, this is all yours 💪

**Comment by luuu-xu** [comment]
@KevinMulhern Thank you! Just some slight updates. (I actually updated this md a few days ago when I first worked on the other issue, now it's time for PR!
