### ISSUE TITLE
Foundation: Introduction to Git Video Plagiarizes ProGit Book

### ISSUE THREAD

**Issue by ccellis** [TheOdinProject/curriculum#26109]
### Describe your suggestion

[The second video](https://m.youtube.com/watch?v=1h9_cB9mPT8&feature=youtu.be&t=13s) linked in this lesson directly lifts text from the [Short History of Git](https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git) chapter of the ProGit textbook. It repeats, word for word, the entire chapter.

This video, as far as I can tell, does not cite the ProGit book as a source at any point during the video or anywhere in the description or comments. This violates the Creative Commons license the book is distributed under.

I think this video should be replaced.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

I’m going to look for some potential replacements later today

**Comment by Mclilzee** [comment]
Putting the book on the side while listening, this person is literally reading from the book directly. I, too, didn't see any mention of the git book during this video or in the description. I agree with replacing this link.

**Comment by codyloyd** [comment]
wow.. good catch!  This should definitely be resolved.  I'll go ahead and set this to 'in progress' and assign it to you, so you can do a PR when you find a good replacement

**Comment by Lofty-Brambles** [comment]
😬 great catch!

**Comment by ccellis** [comment]
I’ve been looking for a good drop in replacement for this video to no avail— there’s nothing I’ve found that’s less than five minutes long, coherently explains the difference between Git and GitHub, has reasonable audio quality, and doesn’t obviously plagiarize an existing source.

I’m going to broaden my search and try to find a chapter in an intro programming book that talks about the difference, but does anyone else have suggestions on what else I could be looking into?

**Comment by ccellis** [comment]
Alright, I still haven't found any good alternative. I think the best course of action at this point is to just remove the link entirely and slightly reword the corresponding assignment bullet point-- the body of the lesson does a good job introducing github and clarifying git vs github, and there's an article in the additional resources that goes into great detail for people who need more clarification

**Comment by codyloyd** [comment]
I approve of this plan of action 👍🏽
