### ISSUE TITLE
Foundations: The Cascade needs specificity text made more clear.

### ISSUE THREAD

**Issue by SpekkioKilwala** [TheOdinProject/curriculum#26119]
One of the examples on Specificity states,
"In this final example, both rules are using ID and class selectors, so neither rule is using a more specific selector than the other. The cascade then checks the amounts of each selector type. Both rules only have one ID selector, but rule 2 has more class selectors, so rule 2 has a higher specificity!"

I read this as saying that both rules individually have both ID and class selectors, but in the actual example, Rule 1 has an ID selector and no class selector. I would either add a class selector to both rules (leaving the description the same) or modify the wording of the description to clarify that the rules use class-and-ID collectively, not each individually.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Lofty-Brambles** [comment]
Linked: #26118 
I'm assuming, they want to work on it

**Comment by codyloyd** [comment]
this is a duplicate issue, as @Lofty-Brambles has mentioned.  Closing this one.

Thanks!
