### ISSUE TITLE
Shopping Cart: Netlify deploy directions should include creating a 'netfily.tomal' file.

### ISSUE THREAD

**Issue by man7788** [TheOdinProject/curriculum#26112]
### Describe your suggestion

My deploy without a 'netfily.tomal' file included would not show up and displaying a 404 Error.
Source: https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-shopping-cart

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by codyloyd** [comment]
@TheOdinProject/react also might need to take a look.  I think this `.tomal` file might be a new requirement for netlify... I've not used or come across it (but it's been a few years since I actually used netlify for anything)

@man7788 it is not clear what you're proposing as an error or a fix here.  Can you give a little more info, please?

**Comment by Lofty-Brambles** [comment]
Just providing some context:
I think it's a typo for `netlify.toml` files, which's netlify's blanket config file. Usually a redirects file at the base of public works, which's being addressed in https://github.com/TheOdinProject/curriculum/pull/26017 - and that *should* fix it

**Comment by MaoShizhong** [comment]
Can confirm, a `_redirects` with the specified content at the base of `public/` does work for Netlify and a `netlify.toml` file is not strictly necessary.

**Comment by codyloyd** [comment]
great.. thanks!

closing this issue because #26017 should fix it.
