### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by wondersavant** [TheOdinProject/curriculum#26117]
### Describe your suggestion

The cascade of CSS
Specificity

`/* rule 1 */
#subsection {
  background-color: yellow;
  color: blue;
}

/* rule 2 */
.main #subsection {
 color: red;
}`
"In this final example, both rules are using ID and class selectors,"

Only rule 2 use a class selector not "both".

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade#the-cascade-of-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

wondersavant

**Comment by Lofty-Brambles** [comment]
@wondersavant can you open a PR with the proposed wording changes?

**Comment by codyloyd** [comment]
This does deserve a slight tweak in the language here.  The bulk of that paragraph is correct, so don't make too many changes.

@wondersavant you mention you want to work on th is, so i will assign it to you and set the status of this issue to 'in progress' if you do NOT want to fix it, let me know so we can get it assigned to someone else.

Thanks!

**Comment by wondersavant** [comment]
I would do it, thanks for the opportunity.

**Comment by wondersavant** [comment]
PR submitted!
Ref: [#26125](https://github.com/TheOdinProject/curriculum/pull/26125)

**Comment by ManonLef** [comment]
Closed with the above PR
