### ISSUE TITLE
Introduction to Flexbox: There is a missing link in the course

### ISSUE THREAD

**Issue by KhalilAr42** [TheOdinProject/curriculum#26128]
There is a missing link in the Introduction to Flexbox course, 

As you can see in this screenshot there is no link to the Scrim tutorial.

![image](https://github.com/TheOdinProject/curriculum/assets/63666821/55a2aadb-11b1-482e-8bc4-cf4c598e1d0e)

However if you go to the additional resources part, you'll find the tutorial link.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox#how-to-create-flex-item-knowledge-check

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

khalilar42

**Comment by codyloyd** [comment]
We have recently moved the scrims.  This line should just be deleted.

**Comment by fabulousgk** [comment]
I can take this if @KhalilAr42 does not want to do it

**Comment by codyloyd** [comment]
you got it @fabulousgk
