### ISSUE TITLE
JS Battleships: Inconsistency with factory function/class in instructions

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26126]
### Describe your suggestion

In the instructions, it initially instructs you to write a Gameboard factory. Later in step 4.3, it refers to the Gameboard *class*. Just seen a few times people confused in discord over the class as they've written a factory function instead.

Could the following be clarified:
- Do the "blueprints" (Gameboard, Ship etc.) *have* to be a factory function? Or should there be freedom for someone to choose how they construct and instantiate (via constructor, factory or class)? Given that step 4.4 refers to "figure out which class or module", my feeling is that it was intended to be a choice and not "must be a factory function only".
- Should step 4.3 therefore be corrected to refer to the Gameboard as a factory (or if any type of constructor is allowed, the equivalent wording for consistency)?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/javascript thoughts?

**Comment by ManonLef** [comment]
Yes this threw me off as well when doing this project myself. I was even doubtful back then if I could use a class. 

Since learners at this point should be comfortable enough with both classes and factories, I'd propose leaving it up to them which to use.

**Comment by wise-king-sullyman** [comment]
Sounds like a plan to me. All yours @MaoShizhong, thanks!
