### ISSUE TITLE
Introduction to Flexbox: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Tim-odm** [TheOdinProject/curriculum#26135]
### Describe your suggestion

The scrim is missing from the end of the 'Let's Flex' section.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

I'm really enjoying this course btw. Thank you for providing such a unique and helpful way to learning web dev!

**Comment by codyloyd** [comment]
this is a duplicate issue :D thanks for reporting it.
