### ISSUE TITLE
Routing: Remove or Update Link to CodeSchools video

### ISSUE THREAD

**Issue by CoryMCodes** [TheOdinProject/curriculum#26130]
### Describe your suggestion

Description: 
Under Additional Resources : [CodeSchool’s Surviving APIs with Rails](https://www.youtube.com/watch?v=99nZVo9amAQ) - Level 1 is free and gets into REST, Routes, Constraints, and Namespaces.

Links to a youtube error page: Video unavailable - This video is no longer available because the uploader has closed their YouTube account.

Recommendation:
Can't find another link to the original video, recommend deleting or replacing with similar resource

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-routing

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by codyloyd** [comment]
agree, should find a new video ( or delete)

**Comment by ht-l1** [comment]
Hello can I help with this issue?

**Comment by codyloyd** [comment]
@ht-l1 looks like @Sushant9473 has a PR that removes the link. I'll go ahead and merge theirs... if you can find a good article or video to replace it with, you can do a separate PR to add it.

@Sushant9473 thanks for this.... in the future though, make sure you tell us you're working on something, so we don't assign it to multiple people!

**Comment by Sushant9473** [comment]
@codyloyd You're welcome! I'll be sure to let you know next time I'm working on something so that we can avoid double-assigning tasks.I'll make sure to communicate more proactively in the future.
