### ISSUE TITLE
Clean Code: Broken link to "THE complete guide to self-documenting code"

### ISSUE THREAD

**Issue by KDLGates** [TheOdinProject/curriculum#26134]
### Broken link to "THE complete guide to [self-documenting code](http://wiki.c2.com/?SelfDocumentingCode)"

There appears to be a broken link on https://www.theodinproject.com/lessons/foundations-clean-code#assignment, but what brought me here is the irony. 😅Made a throwaway comment about this on the Discord and was directed to report it as an issue, sorry if I'm not using a correct report template.

![image](https://github.com/TheOdinProject/curriculum/assets/842713/79252321-d9fe-4e07-8a27-5a98e17da774)

returns

![image](https://github.com/TheOdinProject/curriculum/assets/842713/d1b3aebb-42b1-4b88-8c5c-4828aebfde87)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

heathenist

**Comment by codyloyd** [comment]
this link should simply be removed.  thanks for reporting!

**Comment by danibassprod** [comment]
I was about to report the same thing, nice!

**Comment by fabulousgk** [comment]
I will take this if someone needs to do it.

**Comment by codyloyd** [comment]
it's yours!
