### ISSUE TITLE
Mocking Callbacks And Components: <Arrange-Act-Assert links to a page that no longer exists>

### ISSUE THREAD

**Issue by xandernesta** [TheOdinProject/curriculum#26131]
### Describe your suggestion

The webpage http://wiki.c2.com/?ArrangeActAssert no longer has any content on the page it seems, so the [Arrange-Act-Assert](http://wiki.c2.com/?ArrangeActAssert) link in the "Exploring further" paragraph of theodinproject lesson may need an update to some new content.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-mocking-callbacks-and-components

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by codyloyd** [comment]
@TheOdinProject/react do we need a new resource here? or can this be removed?

**Comment by wise-king-sullyman** [comment]
IMO either a new resource or some first party content would be worthwhile. The wayback machine also has[ a capture of it ](https://web.archive.org/web/20210225161833/http://wiki.c2.com/?ArrangeActAssert).

**Comment by ManonLef** [comment]
I still see content on that site 🤔

**Comment by codyloyd** [comment]
it was missing when I commented last week.. perhaps it was just a little blip in their webserver.  Since it seems to be working now, I'll close this issue.
