### ISSUE TITLE
Clean Code: Link in Additional Resources is Broken

### ISSUE THREAD

**Issue by DPeteLovesYou** [TheOdinProject/curriculum#26133]
### Describe your suggestion

Second bullet in Additional resources, THE complete guide to self documenting code, links to this page: http://wiki.c2.com/?SelfDocumentingCode. This page no longer seems to exist. Thank you!!

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

DPeteLovesYou

**Comment by codyloyd** [comment]
soemone else reported this... closing this issue.  thanks for reporting!
