### ISSUE TITLE
The Cascade - Move Scrimba to Additional Resources

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26145]
### Describe your suggestion

The existing Scrimba embeds in lessons should be moved from their current position and added to Additional Resources as link text instead of embedded. This link text should align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

See https://github.com/TheOdinProject/curriculum/issues/26057 for similar issues that have been worked on.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Luise8** [comment]
Hi, I'd like to work on this. I have already read the similar [issue](https://github.com/TheOdinProject/curriculum/issues/26057) as well as similar PR's accepted.

**Comment by thatblindgeye** [comment]
@Luise8 all yours!
