### ISSUE TITLE
Introduction to Flexbox: Missing content or link

### ISSUE THREAD

**Issue by ArchILLtect** [TheOdinProject/curriculum#26143]
### Describe your suggestion

This has probably been reported already, but since I don't know how to check and just in case:

At the end of the "Let's Flex" section, there is a reference to Scrimm:

![Screenshot from 2023-08-16 14-51-22](https://github.com/TheOdinProject/curriculum/assets/140122527/248891d6-fca7-41e3-a278-e2bbb8218a1b)

However the section just ends and nothing else is shown. Like I said in the subject header, something is missing here obviously due to the face that the statement ends with a colon, which would indicate that there is something to follow. My assumption is that either a link or maybe another API or _some_ kind of content is missing.

Hopefully this isn't just redundant.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox#lets-flex

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

TBH I would just fork, fix and PR this, but I'm not very confident in my abilities on that yet. Any comments or questions email:
nickhansonsr@gmail.com

**Comment by fabulousgk** [comment]
https://github.com/TheOdinProject/curriculum/issues/26141

**Comment by ArchILLtect** [comment]
Well _**now**_ I know where the issue log is...
It wasn't clear to my ultra noobish eyes when I submitted, so thanks.

**Comment by fabulousgk** [comment]
@ArchILLtect  you are all good, if not for the fact that I watch the issues, I would not have known!

**Comment by wise-king-sullyman** [comment]
Thanks for reporting! Looks like this was fixed in #26152
