### ISSUE TITLE
Introduction to Flexbox: <Short description of your suggestion>

### ISSUE THREAD

**Issue by royalh23** [TheOdinProject/curriculum#26141]
### Describe your suggestion

Even though Scrim examples are being moved to "additional resources" section, there still remains a title for one of such examples in the lesson I've linked to:

![Screenshot from 2023-08-16 14-26-06](https://github.com/TheOdinProject/curriculum/assets/69067512/32fdabe2-e2b9-420f-9756-fde947fc2e05)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

royalh23

**Comment by wise-king-sullyman** [comment]
Thanks for reporting! Looks like this was already fixed in #26152
