### ISSUE TITLE
Revisiting Rock Paper Scissors: The command to delete repo from github through terminal is wrong

### ISSUE THREAD

**Issue by Sushant9473** [TheOdinProject/curriculum#26142]
### Describe your suggestion

In Assignment section -
Point 4 , subpoint 5
the command to delete the side branch from repo on GitHub is wrong 
The correct command should be git push origin --delete rps-ui

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

sushant167

### (Optional) Additional Comments

![Screenshot 2023-08-16 at 1 08 54 PM](https://github.com/TheOdinProject/curriculum/assets/72797131/b3c18681-10e0-46ee-8510-ebdbc901acbe)

**Comment by fcasibu** [comment]
Hi @Sushant9473 

It's not particularly wrong, both are valid syntax. Git uses a syntax of:
`git push [<options>] [<repository> [<refspec>...]`

But I would agree that `git push origin --delete rps-ui` might read better as `git push <remote> --delete <branch_name>` than `git push --delete <remote> <branch_name>`

**Comment by fcasibu** [comment]
@Sushant9473 I would suggest keeping this open if it's a valid issue

**Comment by wise-king-sullyman** [comment]
Having the remote before the flags is definitely the more common order if nothing else so I'm not opposed to the suggested change, thanks for reporting!

**Comment by Sushant9473** [comment]
Please delete the pull request (#26163 ) i had made which i closed by mistake as i did not know that by deleting the fork repository it will close the pull request automatically . 
I have opened a new pull request as i wasn't able to reopen the previous pull request as it was saying "closed this by deleting the head repository".

**Comment by wise-king-sullyman** [comment]
Unless there's some hidden GitHub feature I'm not aware of I don't think there's a way for us to "delete" those pull requests.
