### ISSUE TITLE
<NodeJs>: <Clarify assignment scope>

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#26158]
### Describe your suggestion

![image](https://github.com/TheOdinProject/curriculum/assets/55961349/fae2918b-6c07-48d3-a36c-659587dd27f0)

does the highlighted text assignment include or exclude the TypeScript module?
I think we should clarify

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-what-is-nodejs#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment]
It would not include the TypeScript module. I'm not against a clarification. Thanks!
