### ISSUE TITLE
Conclusion: Ruby Best Practices book by Gregory Brown link opens a blank page

### ISSUE THREAD

**Issue by jwatelet** [TheOdinProject/curriculum#26156]
### Describe your suggestion

When I try to open the [link](https://itbook.store/books/9780596523008) on the bottom of the page, it redirect me correctly to the site but the page remains blank. I tried with Firefox and Chrome, the problem is the same.

<img width="1346" alt="image" src="https://github.com/TheOdinProject/curriculum/assets/13626345/7af229c5-6791-420a-b598-325f3c8307c3">

If I do the search on the website with the ISBN of the book it works correctly : 

<img width="1274" alt="image" src="https://github.com/TheOdinProject/curriculum/assets/13626345/70580fab-92b2-42b3-8b54-7e73dae978a3">

I'm aware that the problem does not come from the Odin Project itself but from the itbook.store. 
I don't know how to fix this the right way, maybe point to another site that sells this book?

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-conclusion

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

flakethemongoose

**Comment by wise-king-sullyman** [comment]
Seems like the kind of thing that might just be a temporary issue, but unless we feel really strongly that people should get this book I wonder if the link is worth having.

@TheOdinProject/ruby WDYT?

**Comment by ChargrilledChook** [comment]
The book was released in 2009 and seems to be based on Ruby 1.9. It's definitely not an ideal recommendation to be making anymore.

Happy to remove the link altogether. 

If we wanted to replace it with another paid resource, the [pickaxe book](https://pragprog.com/titles/ruby5/programming-ruby-3-2-5th-edition/) is probably the most canoical and up to date general language reference.

Other paid alternatives: 'Eloquent Ruby' or 'The Well Grounded Rubyist'.

For a free book, we could use [Why's Poignant Guide to Ruby](https://poignant.guide/) which while slightly older (and more than a bit strange) is a classic of the Ruby community.

**Comment by sapienfrom2000s** [comment]
Can I link the second edition of pickaxe book which is completely free? It includes Ruby 1.8. Students at this point can google and find the latest edition.
