### ISSUE TITLE
Memory Card: Correct the improper sentence in the Introduction of memory cards project

### ISSUE THREAD

**Issue by mizerablepi** [TheOdinProject/curriculum#26161]
### Describe your suggestion

The second line of the Introduction in the memory card project is not correctly formed, 
instead of _"The main goal of this project is to concepts and hooks learned thus far to manage and utilize state while fetching and using data from an external API"_
It should be something like _"The main goal of this project is to **practice the** concepts and hooks learned thus far to manage and utilize state while fetching and using data from an external API"_

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-memory-card#introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by skim2264** [comment]
Hi, can I get assigned this issue?

**Comment by wise-king-sullyman** [comment]
Ah yep, good catch. @skim2264 all yours.

**Comment by RushilJalal** [comment]
I read this issue is stale. Can I pick it up?

**Comment by ManonLef** [comment]
@RushilJalal Someone is already assigned and working on this

**Comment by ManonLef** [comment]
Yes this looks fixed and I will close it. Thanks for getting back @skim2264
