### ISSUE TITLE
Recipes: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Njabariene12** [TheOdinProject/curriculum#26166]
### Describe your suggestion

my index.html page on github works but the link in it leads to a blank. The message i get is about:blank#blocked
https://github.com/Njabariene12/odin-cooking/actions/runs/5924860193
https://njabariene12.github.io/odin-cooking/

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

Kindly help out

**Comment by ManonLef** [comment]
Feel free to join [our Discord](https://discord.gg/fbFCkYabZB) for personal project help requests. Issues on the Github curriculum repository are for lesson content suggestions. 

Good luck with your project, and I hope you find the help in our community!
