### ISSUE TITLE
Fix: Full Ruby/Rails Path: Rewrite headings to follow sentence case Style Guide

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/curriculum#26169]
### Describe your suggestion

Our [Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#headings) requires all headings to be in **sentence case**. This means many lessons need to be reviewed and corrected as needed.

I would like to open this up for **first-time contributors or those still very new to contributing** to work on. You can follow the links to see how big the sections are. Some will have only a few lessons and some will have quite a lot more. Feel free to pick one you feel comfortable with. 

Some sections might have been corrected already but it's good to review them to make sure nothing is missed. 

Example:

```md
### Knowledge Check

should be changed to

### Knowledge check
```

## Guidance:

- Comment on this issue to let us know you'd like to get a section assigned to you. You can also ask for a specific one. If you don't mention a specific one to work on, you'll be assigned a random one.
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons.
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution.
- Please add the following to your PR in the Issues section: `Related to #26169` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` issue link. 

### Ruby Course
- [x] 1. [Introduction](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#introduction) && [Basic Ruby](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#basic-ruby) Assignee: @headlessNode **COMPLETE**
- [x] 2. [Basic Ruby Projects](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#basic-ruby-projects) && [Object Oriented Programming Basics](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#object-oriented-programming-basics) && [Files and Serialization](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#files-and-serialization) Assignee: @Ruchita1010 **COMPLETE**
- [x] 3. [Advanced Ruby](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#advanced-ruby) && [A bit of CompSci](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#a-bit-of-computer-science) Assignee:  @MooseCowBear **COMPLETE**
- [x] 4. [Intermediate Git](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#intermediate-git) && [Testing Ruby with RSPEC](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#testing-ruby-with-rspec) && [Conclusion](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#testing-ruby-with-rspec) Assignee: @jp524 **COMPLETE**

### Databases
- [x] 5. [All Lessons](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/databases) Assignee: @ht-l1 **COMPLETE**
### Ruby on Rails
- [x] 6. [Introduction](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#introduction) && [Rails Basics](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#rails-basics) Assignee: @EmilyErickson **COMPLETE**
- [x] 7. [Active Record Basics](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#active-record-basics) && [Assets and Navigation](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#assets-and-navigation) Assignee: @danieletie **COMPLETE**
- [x] 8. [Forms and Authentication](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#forms-and-authentication) && [Advanced Forms and Active Record](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#advanced-forms-and-active-record) Assignee: @errantpianist 
- [x] 9. [APIs](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#apis) && [Rails Sprinkles](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#rails-sprinkles) && [Mailers and Advanced Topics](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails#mailers-and-advanced-topics) Assignee: @Kacegz **COMPLETE**

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

manonl

**Comment by Ruchita1010** [comment]
I would like to work on this issue. Can I get assigned?

**Comment by ht-l1** [comment]
Hello can I work on Databases?

**Comment by jp524** [comment]
I'd like to help with this issue

**Comment by ManonLef** [comment]
@Ruchita1010 @MooseCowBear @ht-l1 @jp524 thanks for being willing to help out! I'll assign you

**Comment by EmilyErickson** [comment]
Hello, could I work on 6. Introduction && Rails Basics? This will be my first contribution.

**Comment by ManonLef** [comment]
Thank you @EmilyErickson, you are assigned!

**Comment by danieletie** [comment]
Hello, Can I work on some? I'd love to help out... This is my first contribution as well

**Comment by ManonLef** [comment]
Absolutely @danieletie ! Much appreciated and I will assign you to number 7

**Comment by errantpianist** [comment]
Hi @ManonLef, could I help out too? This would be my first contribution. Thank you so much!

**Comment by ManonLef** [comment]
@errantpianist yes thank you, I will assign you!

**Comment by Kacegz** [comment]
Hello, can I help too?

**Comment by macauleydev** [comment]
I'll be happy to work on this.

**Comment by ManonLef** [comment]
Thank you so much everyone!
