### ISSUE TITLE
Adv. JavaScript - Tic Tac Toe: Remove minimax "extra credit" suggestion

### ISSUE THREAD

**Issue by jernestmyers** [TheOdinProject/curriculum#26172]
### Describe your suggestion

A learner asked for advice on whether or not to implement the minimax in their TTT or if they should do so _**after**_ the CS module. This brings up a great point: learners have yet to encounter recursion and other abstract ideas that would facilitate the implementation of such an algorithm. Now that the Node path includes a CS section, I think we should remove any suggestion to implement an unbeatable AI.

For further justifications, let's consider these things:
- the CS section has plenty of authentic, challenging, deep-dive practice with recursion and similar CS-y things
- the CS section is placed quite a bit beyond the TTT project, which implies to me that folks found that to be a more appropriate point at which to dive into these difficult concepts
- TTT is not a portfolio project, so even suggesting folks go down this rabbit hole seems problematic to me (again, remembering that learners will get great exposure to these ideas at a more appropriate point in their journey)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-tic-tac-toe

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

jmyers

**Comment by wise-king-sullyman** [comment]
I wouldn't be against this, the reasoning for removal makes sense. @TheOdinProject/javascript is anyone opposed?

**Comment by ManonLef** [comment]
I'm not opposed.

**Comment by wise-king-sullyman** [comment]
Take it away @jernestmyers. Thanks!

**Comment by Lofty-Brambles** [comment]
Since *quite* a few projects provide a basic AI, would it be a good idea to at least mention the removal? Since learners do check the working projects to get an idea of a "finished" product, they can get confused with some projects having an "Human vs. AI" settings.

**Comment by ManonLef** [comment]
I personally think that many of the top projects include a lot of extra unneeded functionality. At this point in the curriculum, learners are probably aware of the assignment and people going beyond the assignment. There's currently a PR in the making to make people extra aware (during the foundations projects) about the fact many people revisit their projects at a later stage, and to focus only on meeting the requirements as stated in the projects.

**Comment by c-auri** [comment]
I agree that the suggestion is poorly placed in the curriculum and also have seen it guide more than one person in the wrong direction. But I also see potential in the assignment and think it _could_ be a portfolio-worthy piece if done well. In my opinion, showing an interviewer a game that has a good AI can be something that helps one to stand out amongst other applicants, even if it is just a simple game like this.

So I see why it is suggested in the first place, I just think it's poorly placed. I do like what @Arkanheal suggests: mention it in the Getting Hired part as something than can be done after finishing the curriculum, if the learner feels like adding some more computer-sciency projects would be valuable to them. Perhaps that section could also contain some other optional assignments that currently sit in the middle of the curriculum?

**Comment by ManonLef** [comment]
Thanks for sharing your thoughts everyone. We’ll go ahead with removing the extra credit for now to keep the scope of this issue small and focused. But please feel free to open a new discussion for these ideas about adding something to the `Getting Hired` section.

**Comment by 01zulfi** [comment]
@jernestmyers Just checking in to see if you're still interested in completing this issue

**Comment by jernestmyers** [comment]
> @jernestmyers Just checking in to see if you're still interested in completing this issue

Ah, I got confused thinking it was being handled by https://github.com/TheOdinProject/curriculum/pull/26286. I'm happy to let the other PR resolve this issue since I have been away for awhile (👶)!

**Comment by 01zulfi** [comment]
Resolved with https://github.com/TheOdinProject/curriculum/pull/26286

**Comment by MaoShizhong** [comment]
I just realised that when I opened #26286 I saw this issue and removed the optional credit step because I completely missed that Jmyers had already been assigned by that point! That's totally on me, I should have checked properly to avoid confusion and overlapping assigned work, my apologies!
