### ISSUE TITLE
Setting up Git: <Understanding SSH Key Pairs >

### ISSUE THREAD

**Issue by arapmahir** [TheOdinProject/curriculum#26186]
### Describe your suggestion

Inside the [Setting up Git](https://www.theodinproject.com/lessons/foundations-setting-up-git), the Additional resources such as [Understanding SSH Key Pairs](https://winscp.net/eng/docs/ssh_keys) link doesn't seem opening. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Thanks for reporting but I can't reproduce this. It opens on my end

**Comment by arapmahir** [comment]
Hello,
Thank you for your comment! I tried to open the link on Windows 11, Chrome Browser (which I still have this same problem in Xubuntu, Virtualbox VM), and here is the [screenshot: < Understanding SSH Key Pairs >](https://github.com/TheOdinProject/curriculum/assets/125707766/4b8f4df6-9c5a-4cb9-84bf-a44a671c568c)  My guess is that it might be due to my location maybe Idk?
