### ISSUE TITLE
Foundations/Introduction: Update lists per layout style guide

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26189]
Lists should be updated in the following ways to align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md):

- Any unordered list items that are created with an asterisk `*` are replaced with a hyphen `-` instead. For example, `* A list item` should be updated to `- A list item`
- The list item content is updated so it only has a single space before it. For example, `1.   A list item` has 3 spaces before the list item content ("A list item"), and should be updated to `1. A list item`
- Appropriate punctuation is added at the end of each list item in the "Lesson overview", "Assignment", "Knowledge check", and "Additional resources" sections
  - Follow the [Google style guide ](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists) to determine when to add punctuation
- Any additional updates mentioned for specific lessons

### Guidance:

- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` keyword. 

### Lessons to update

- [x] @ascodeasice - [How this course will work](https://www.theodinproject.com/lessons/foundations-how-this-course-will-work)
- [x] @ht-l1 - [Introduction to web development](https://www.theodinproject.com/lessons/foundations-introduction-to-web-development)
- [x] @kahmoh  [Motivation and mindset](https://www.theodinproject.com/lessons/foundations-motivation-and-mindset)
- [x] @seanghods  [Asking for help](https://www.theodinproject.com/lessons/foundations-asking-for-help)
- [x] @aadityyxa  [Join the Odin community](https://www.theodinproject.com/lessons/foundations-join-the-odin-community)

**Comment by ascodeasice** [comment]
Hi, I'd like to get one or multiple lessons assigned to me

**Comment by ht-l1** [comment]
Hello also hope to help out here

**Comment by thatblindgeye** [comment]
@ascodeasice I'll assign you "How this course will work" for now, just in case others would like to sign up (there'll be more issues along these lines, though!)

@ht-l1 Ill assign you "Intro to web dev"

Thanks both for volunteering!

**Comment by kahmoh** [comment]
Hi, I'd like the opportunity to get involved here and help out!

**Comment by seanghods** [comment]
Hi, I can help as well :)

**Comment by thatblindgeye** [comment]
@kahmoh I'll assign you "Motivation and Mindset", and @seanghods you "Asking for help"!

**Comment by kahmoh** [comment]
I closed my original pull request and added a new one that I believe is more in line with the correct way to contribute here. Original pull request having the issue of an updated .gitignore file.

**Comment by aadityyxa** [comment]
I'd like to help out if it's still needed.

**Comment by Ruchita1010** [comment]
I would like to work on a section too!

**Comment by thatblindgeye** [comment]
@aadityyxa I'll assign you the last lesson!

@Ruchita1010 the last lesson for this issue is assigned, but keep an eye out for other issues like this! We have several similar issues that'll be great opportunity
