### ISSUE TITLE
<foundations-dom-manipulation-and-events>: <Clarification/Simplification of 'Events' section>

### ISSUE THREAD

**Issue by Landryman** [TheOdinProject/curriculum#26188]
### Describe your suggestion

In this section I found myself getting confused (lost in the weeds).

Specifically, in the portion after this excerpt:
"Note that all 3 of these methods can be used with named functions like so:"

Here, it took a significant amount of time for me to figure out that I needed to be using the previously associated lines of HTML with these new methods. Of course, after finally figuring it out it seemed pretty obvious, hindsight being 20/20.

It may also be worth mentioning that the constant variables used in the previous samples are not needed in the new samples incorporating named functions. 

All that said, as a beginner, I'm not always on the lookout for these "implied" aspects in the curriculum, and my natural inclination is to take everything at face value. Therefore, if it is possible to avoid this type of confusion by making the curriculum's flow and readability more streamlined, where possible, I believe, overall, it would result in a more positive experience for fellow students like myself.

My solution:
Inside the sample code snippet that explains how the three methods can be used with named functions, I would suggest inserting a comment underneath the function, instructing the reader to refer to/include the HTML snippets used with each individual method in the preceding code samples. And perhaps to ignore the variables in the previous samples. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

### Checks

- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

hambonoire

### (Optional) Additional Comments

This is my first time opening an issue on a GitHub repo.

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by thatblindgeye** [comment]
I think this makes sense. We should try to avoid users needing to constantly scroll up and down in a lesson just to follow along/keep in mind previously mentioned bits and pieces as much as possible.

**Comment by Landryman** [comment]
If you've read the description of this issue. I would suggest quickly going back over it. I noticed a flaw in my logic in how I was interpreting the instructional elements of the lesson. So, I made some edits to correct that.

**Comment by Landryman** [comment]
> I think this makes sense. We should try to avoid users needing to constantly scroll up and down in a lesson just to follow along/keep in mind previously mentioned bits and pieces as much as possible.

Please see my comment below if you have a moment.

**Comment by Landryman** [comment]
> I think this makes sense. We should try to avoid users needing to constantly scroll up and down in a lesson just to follow along/keep in mind previously mentioned bits and pieces as much as possible.

Please see my recent comment if you have a moment.

**Comment by rlmoser99** [comment]
@Landryman I've assigned you this issue, so you can make a PR with your proposed changes and then we can review the specifics on the PR.

**Comment by thatblindgeye** [comment]
@Landryman just checking to see how this is going?

**Comment by CouchofTomato** [comment]
Opening this back up since we haven't received an update.

**Comment by Achra-f** [comment]
I would like to work on this.

**Comment by CouchofTomato** [comment]
Hey @Achra-f 

All yours if you still want it?

**Comment by bdaniels8135** [comment]
Hi @CouchofTomato, I just got to the contributing lesson and found this issue. I remember tripping over this lesson in foundations and would love to take a stab at fixing it! If no one else is assigned yet, let me know.
