### ISSUE TITLE
Rails Sprinkles: Span closing tag displaying in paragraph

### ISSUE THREAD

**Issue by Kacegz** [TheOdinProject/curriculum#26182]
### Describe your suggestion

There is a tag apparently not displaying correctly in a paragraph below ``webpacker`` header.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-js-bundling#webpacker

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

_kace_

**Comment by strawHat121** [comment]
Can I work on this ?

Seems like a simple issue to fix.

**Comment by ManonLef** [comment]
sure @strawHat121 I'll assign you
