### ISSUE TITLE
React: RTL setup suggested no longer works

### ISSUE THREAD

**Issue by kentshenlim** [TheOdinProject/curriculum#26198]
### Describe your suggestion

The lesson proposes following https://www.robinwieruch.de/vitest-react-testing-library/ for Vitest and RTL setup.
The setup.js file in the website no longer works following the update of @testing-libary/jest-dom.
Instead of
`import matchers from '@testing-library/jest-dom/matchers';`
use
`import * as matchers from '@testing-library/jest-dom/matchers';`

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react-testing

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by wise-king-sullyman** [comment]
Not able to test it myself atm, but it looks like the RTL team has a different suggestion: https://github.com/testing-library/jest-dom#with-vitest

**Comment by davmedeiros** [comment]
I just tested the instructions on https://github.com/testing-library/jest-dom#with-vitest right now the setup.js file can be simplified to this: 

```
import { afterEach } from 'vitest';
import { cleanup } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';

// runs a cleanup after each test case (e.g. clearing jsdom)
afterEach(() => {
  cleanup();
});
```

The changes are these.
from:
`import matchers from '@testing-library/jest-dom/matchers';`
to:
import '@testing-library/jest-dom/vitest';

and

remove this:
`expect.extend(matchers);`
