### ISSUE TITLE
Javascript Path OOP Principles -  Dead Link

### ISSUE THREAD

**Issue by fadelyking** [TheOdinProject/curriculum#26192]
### Describe your suggestion

There is a link in the Assignments section that seems to be dead.

[How to Write Highly Scalable and Maintainable JavaScript: Coupling](https://web.archive.org/web/20200810210808/https://medium.com/@alexcastrounis/how-to-write-highly-scalable-and-maintainable-javascript-coupling-c860787dbdd4) explains loosely coupled objects pretty well.

Thanks

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-oop-principles

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

fadely

**Comment by ht-l1** [comment]
this is an interesting link. I accessed it yesterday and it was not opening too. 
today this link suddenly works again but it takes a few seconds to actually load the content.

**Comment by Lofty-Brambles** [comment]
The article mentions pub-sub and provides a good, terse example. I do like the content.

**Comment by CouchofTomato** [comment]
Ok. Happy to close this out then.
