### ISSUE TITLE
Ruby on Rails Deployment: Typo in section header

### ISSUE THREAD

**Issue by Sankalp-G** [TheOdinProject/curriculum#26207]
### Describe your suggestion

In the [Deployment](https://www.theodinproject.com/lessons/ruby-on-rails-deployment#what-are-gosting-providers) lesson in the Ruby on Rails path

- Currently the third heading says: What are gosting providers
- But it should be: What are hosting providers

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-deployment#what-are-gosting-providers

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks for reporting @Sankalp-G - I've assigned it to you
