### ISSUE TITLE
A Very Brief Intro to CS: Confusing quora answer

### ISSUE THREAD

**Issue by kol3x** [TheOdinProject/curriculum#26219]
### Describe your suggestion

Assignment number 3 is a link to a Quora question about algorithms in web dev: "Read this Quora question about the importance of algorithms in web development to get some context for why we’re going over this stuff." 
However, when i opened the link, the only answer to that question i saw was some guy saying that Computer Science people are stupid and algorithms are almost NEVER needed in web development. Really weird and basically the opposite of what i expected from what's said in the assignment.(https://qr.ae/py3NYu - link to the answer)
I then changed sorting method on Quora from "recommended" to "upvotes" and got actually good answer.(https://qr.ae/py3NAc)
May be you should point out what exact answer is supposed to be read, because the first one was really confusing.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-very-brief-intro-to-cs

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

kol3x

### (Optional) Additional Comments

I downvoted the bad answer and upvoted the other one, so may be it will be displayed more for other people. However, probably best to straight up link the answer (or multiple answers) that was intended to be read instead of the whole question.

**Comment by Lofty-Brambles** [comment]
+1 on this. It still comes up as "recommended" for me, but it may be better to directly link to the answer than depend on the algorithm (pun intended).

**Comment by MrLuckyCat** [comment]
Not gonna lie, you're correct. I litterally was confused as to what answer to read because the first one was very confusing and didn't understand a single thing

**Comment by kol3x** [comment]
> @kol3x I have assigned this issue to you since you indicated that you want to work on it. Will you update the link please?

Great! I've been sick for the past few days, I will work on this tomorrow.
