### ISSUE TITLE
Ruby on Rails, Rails Basics, Views: Output of example ERB line different from description

### ISSUE THREAD

**Issue by wwrk22** [TheOdinProject/curriculum#26210]
### Describe your suggestion

Under the Preprocessors section, the ERB example `<%= "<em>I am emphasized</em>" %>` doesn’t output an emphasized line of string as described in the lesson.
Fix: `<em><%= “I am emphasized” %></em>`

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-views#preprocessors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

wwrk22

**Comment by KevinMulhern** [comment]
Thanks for reporting @wwrk22 - I've assigned it to you 💪
