### ISSUE TITLE
JavaScript: Factory functions and module pattern

### ISSUE THREAD

**Issue by Lofty-Brambles** [TheOdinProject/curriculum#26225]
### Describe your suggestion

A decent sized overhaul of the lesson with better, more interactive examples, a flow of information where it doesn't jump between links and leaves stray links all over the lesson with little context for a learner as to how far to read, fulfilling the lack of an assignment section and revamping the multiple "mini", unmarked link lists, while replacing links to articles like [this one from Eric Elliot](https://medium.com/javascript-scene/3-different-kinds-of-prototypal-inheritance-es6-edition-32d777fa16c9) with content within the lesson, which while work, are filled with biases and not intended for a learner but for an already experienced developer adjusted to the jargon used.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#back-to-factory-functions

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

_lofty.dev

**Comment by ManonLef** [comment]
I didn't see this PR before I opened the #26231 issue. 
I'll close that and assign you. 

Here was my suggestion:
```
Rewrite this lesson to:

- Add a clear Assignment section.
- Make it clear which articles should be read and which are optional. 
- update links to be more descriptive
```
