### ISSUE TITLE
<foundations/javascript_basics/fundamentals-4>: <Improve readability of exercises>

### ISSUE THREAD

**Issue by davidomullan** [TheOdinProject/curriculum#26234]
### Describe your suggestion

# Problem Explanation
When students are completing *Javascript fundamentals part 4*, the **list of exercises doesn't include the exercise numbers**. They happen to be the first 7, but are presented as if they could be any. For readability, I recommend we change these to an ordered list. Example found at bottom of list. I will create a pull request if you guys agree. This will also affect the remaining exercises, completed [here](https://www.theodinproject.com/lessons/foundations-fundamentals-part-5).

## Current state
*How exercises appear in repo that student will fork*
<img width="200" alt="Screenshot 2023-08-28 at 10 13 07" src="https://github.com/TheOdinProject/curriculum/assets/35239651/b1b6c7f1-7fa2-4c0e-b715-ad13601c8f2c">
*How task appears on site*
<img width="400" alt="Screenshot 2023-08-28 at 10 15 29" src="https://github.com/TheOdinProject/curriculum/assets/35239651/9f761e4e-554e-4dd3-b664-00c9f0a90049">

[Course page, current state:](https://github.com/TheOdinProject/curriculum/blob/6c5439046faa79fccc72b30a2cf62adf094dff27/foundations/javascript_basics/fundamentals-4.md?plain=1#L45C1-L52C21)
```markdown
2. Now that you have cloned the repository and run `npm install` to install Jest, complete these exercises in the following order:
    * helloWorld (This exercise is intentionally very simple to ensure that you have set up everything properly!)
    * repeatString
    * reverseString
    * removeFromArray
    * sumAll
    * leapYears
    * tempConversion
```

## Recommended change:

```markdown
2. Now that you have cloned the repository and run `npm install` to install Jest, complete these exercises in the following order:
    1. helloWorld (This exercise is intentionally very simple to ensure that you have set up everything properly!)
    2. repeatString
    3. reverseString
    4. removeFromArray
    5. sumAll
    6. leapYears
    7. tempConversion
```

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-4

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

irish12358

**Comment by Sushant9473** [comment]
@davidomullan I think that by numbering all the tasks it would make it feel more cluttered. ( in my opinion )

**Comment by davidomullan** [comment]
> @davidomullan I think that by numbering all the tasks it would make it feel more cluttered. ( in my opinion )

Fair enough, I just think there is some inconsistency in how the coding challenges are presented.

This is flexbox:
![image](https://github.com/TheOdinProject/curriculum/assets/35239651/3eb12da7-6f64-410b-b7bd-ed473fa65de4)

This is css:
![image](https://github.com/TheOdinProject/curriculum/assets/35239651/c2584fb5-ff80-463f-88da-5e1de1a772a9)

Maybe just a rewording of the task? Certainly open to ideas. While I was going through it, because they weren't numbered, I assumed they were out of order but that's just me. Obviously not a top priority.

**Comment by CouchofTomato** [comment]
Yeah I think we should have some consistency across lessons. The list looks good to me so happy to assign this to you if you want it?

**Comment by Sushant9473** [comment]
I can work on it if @davidomullan don't want it .

**Comment by davidomullan** [comment]
@CouchofTomato I'm happy to work on it. Will link the pull request when done. @Sushant9473 I'm happy to take any inputs/feedback you have.

**Comment by davidomullan** [comment]
@Sushant9473 You were right, adding numbered bullets was against the layout style guide and felt less clean. I ended up just changing the text to the name of each folder the student would find in the repo. `helloWorld` to `01_helloWorld`. And then I just made sure each assignment was structured the same. Let me know what you think!

**Comment by Sushant9473** [comment]
> @Sushant9473 You were right, adding numbered bullets was against the layout style guide and felt less clean. I ended up just changing the text to the name of each folder the student would find in the repo. `helloWorld` to `01_helloWorld`. And then I just made sure each assignment was structured the same. Let me know what you think!

You did great, now its looking clean 👍
