### ISSUE TITLE
Javascript OOP Principles: Rework "Single responsibility" example

### ISSUE THREAD

**Issue by radtradcath** [TheOdinProject/curriculum#26243]
### Describe your suggestion

The example for the 'Single responsibility' in 'OOP Principles' lesson is written in a contradictory way which may confuse students:

- The example firstly states the incorrect way by saying "So instead of this";

- Then proceeds to show the correct way of solving the issue by saying "You should extract all the DOM manipulation into its own module _and use it like so_";

- Lastly, contradicts the above by saying "In fact - the function `isGameOver` shouldn’t be calling the DOM function anyway. That should go elsewhere (directly in the game-loop).";

The example must make clear that there are two issues with the given code block and address each problem separately to avoid the apparent contradiction. My initial suggestion is in the Lesson Preview Tool below:

https://www.theodinproject.com/lessons/preview?uuid=e0025422-6b40-4cb7-b9d8-ee3fcc9c05a4

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-oop-principles#single-responsibility

### Checks

- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

.radtrad

### (Optional) Additional Comments

The idea comes from a short Discord discussion. Most part of the rework came from another user, who suggested me to open an issue. The conversation found starting from this message: 

https://discordapp.com/channels/505093832157691914/505093832157691916/1145856420504424559

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look at this please.

**Comment by ManonLef** [comment]
I agree this could be rewritten and I like the initial setup you've provided! @radtradcath would you mind proceeding with a PR so we can review details there? I will assign you since you've indicated you wanted to work on this.
