### ISSUE TITLE
Working with APIs: Add a definition of an endpoint

### ISSUE THREAD

**Issue by hebiscus** [TheOdinProject/curriculum#26249]
### Describe your suggestion

It's first time in the curriculum (for JS path) the term "endpoint" is used and in my opinion it'd be useful to give it's definition, since it's technical and googling doesn't give the best results for a newbie. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript can someone respond to this please.

**Comment by 01zulfi** [comment]
Suggestion looks good to me. Opening this up for contribution.

**Comment by OmarNaguib** [comment]
I'd like to take this on

**Comment by CouchofTomato** [comment]
Hey @OmarNaguib 

That's my bad. I'm on rotation this week and it's been a busy weekend of activity so I didn't check linked issues for every request I had to deal with. I'm sorry for any inconvenience. If you feel you could add to what was done please feel free to submit a PR.
