### ISSUE TITLE
Bug: Lesson note tips do not render links correctly

### ISSUE THREAD

**Issue by lizeth-b** [TheOdinProject/curriculum#26241]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

HTML elements with class `lesson-note--tip` do not render links correctly.

**Example:**
![tip-2](https://github.com/TheOdinProject/theodinproject/assets/99046476/9c3d7d0e-35bd-40a5-9516-e3be199088ae)

### How to reproduce

1. Visit a lesson page with a lesson note tip like [DOM Manipulation and Events](https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events)
2. Scroll to a lesson note tip (HTML element with class `lesson-note--tip`) with a link
3. The link text is not rendered correctly, and the link itself is not clickable

### Expected behavior

1. Visit a lesson page with a lesson note tip like [DOM Manipulation and Events](https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events)
2. Scroll to a lesson note tip (HTML element with class `lesson-note--tip`) with a link
3. The link text is rendered correctly, and the link itself is clickable

### What browsers are you seeing the problem on?

Chrome

### What OS are you using?

MacOS

**Comment by hebiscus** [comment]
Could I take this?

**Comment by Sushant9473** [comment]
can i take this?

**Comment by Sushant9473** [comment]
> Thanks for reporting @lizeth-b.
> 
> Just like the div around our assignment panel, the div element around notes needs to have a `markdown="1"` attribute for nested markdown elements to work correctly.
> 
> This attribute needs to be included in the [note example](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#note-boxes) in our layout style guide as well.

can we just add an anchor link to resolve this ?

**Comment by KevinMulhern** [comment]
Thanks @hebiscus, I've assigned it to you.

Thanks for also offering to help @Sushant9473,  the other contributor just got there before you. Its first come first served.

> can we just add an anchor tag to resolve this ?

We'd prefer markdown to be used wherever it can in our content. The parser we use on the site adds target and rel attributes so we don't have to.
