### ISSUE TITLE
Computer Basics: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Jrv-Dark** [TheOdinProject/curriculum#26257]
### Describe your suggestion

There are some errors in the url of the assignments since they only redirect me to the web where the learning resources are but there are no knowledge verification resources

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-computer-basics https://www.theodinproject.com/lessons/foundations-asking-for-help

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by fabulousgk** [comment]
@Jrv-Dark the questions in the Knowledge Check sections are meant to be sort of reflexive.  You need to answer the question in your mind, if you cant, or ou want to brush up on the topic you click the link to get the material for review.

**Comment by CouchofTomato** [comment]
Yes we don't give full answers always so some link back to the material.

**Comment by Jrv-Dark** [comment]
oh ok i understand thank you
