### ISSUE TITLE
The Box Model: The second Assignment is so out of the place

### ISSUE THREAD

**Issue by cevherkemalsirin** [TheOdinProject/curriculum#26252]
### Describe your suggestion

The second assignment of this topic which is reading this [website:](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model)

is so out of the place. They way it is written and the topics it consists is not really related to the subject we are learning for now and it just confuses the mind. The article is written poorly and you need way more knowledge before reading it. And the topics are for the future. 
Specify what to read in this article to prevent the confision.

Solution:
Read the article from:
**"What is the CSS box model? "** to **The box model and inline boxes**
and skip the next until next chapter.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-box-model

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@codyloyd 

Can you give your thoughts on this mate.
