### ISSUE TITLE
Introduction To React: Broken Link

### ISSUE THREAD

**Issue by seanghods** [TheOdinProject/curriculum#26250]
### Describe your suggestion

Link is broken:
https://laptrinhx.com/top-10-reasons-why-you-should-learn-react-right-now-3718263995/
Cloudflare says host is down, not sure if it's temporary or the domain expired.

Can replace with web archive:
https://web.archive.org/web/20221207194618/https://laptrinhx.com/top-10-reasons-why-you-should-learn-react-right-now-3718263995/

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@seanghods 

Seems to be up for me now. Are you seeing the same thing?

**Comment by oliverfrost1** [comment]
This is an adblocking issue. Let's write a quick note in the lesson about this.

**Comment by seanghods** [comment]
Hm, it works for me now. Must have been a temporary Cloudflare host issue? Either way, looks all good, my fault.
