### ISSUE TITLE
React: Broken link, webpage with no content

### ISSUE THREAD

**Issue by angelrcd** [TheOdinProject/curriculum#26266]
### Describe your suggestion

One of the links in the lesson takes you to a webpage that has no text content in it:
https://laptrinhx.com/top-10-reasons-why-you-should-learn-react-right-now-3718263995/

It seems to be broken or the content was deleted.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

angelrcd

**Comment by xandora** [comment]
Thanks for taking the time to report this, however even with uBlock Origin on, this website works fine for me. I think this one is on you. :)
