### ISSUE TITLE
Nested Collections: Expected exercise not provided

### ISSUE THREAD

**Issue by alexaldearroyo** [TheOdinProject/curriculum#26275]
### Describe your suggestion

RSpec expects a "delete seat from grid exercise" for the Nested Array Exercises but there's  not such a "delete seat from grid exercise" in the nested_arary_exercses.rb file's code.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-nested-collections

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@rlmoser99 

Can you look at this please.

![image](https://github.com/TheOdinProject/curriculum/assets/12649577/529f6542-cc71-4e2d-8960-97e2f8db23ba)

https://github.com/TheOdinProject/ruby-exercises/blob/main/ruby_basics/12_nested_collections/spec/nested_array_exercises_spec.rb 

Is the test supposed to be called delete from row?

**Comment by rlmoser99** [comment]
Sure. This line could be changed to: `describe 'delete seat from row exercise' do`
https://github.com/TheOdinProject/ruby-exercises/blob/main/ruby_basics/12_nested_collections/spec/nested_array_exercises_spec.rb#L55

It would need to be changed on the main branch and the solutions branch, to keep both of them in sync.

**Comment by CouchofTomato** [comment]
@alexaldearroyo 

Are you interested in making this change?

**Comment by alexaldearroyo** [comment]
@CouchofTomato

Sure! I don't know the procedures though, should I just go and change the code in the main and the solutions branches as suggested by @rlmoser99?

**Comment by CouchofTomato** [comment]
Yes, just update the wording of the test I linked in the previous comment so it more directly references the name of the method under test.

**Comment by alexaldearroyo** [comment]
Perfect. I've just proposed the changes.
