### ISSUE TITLE
Foundations JS Clean Code: Outdated information in links

### ISSUE THREAD

**Issue by sykul** [TheOdinProject/curriculum#26277]
### Describe your suggestion

Number 1 in the assignment list on [Foundations Clean Code](https://www.theodinproject.com/lessons/foundations-clean-code) links to an article, [10 Principles for Keeping Your Programming Code Clean](https://onextrapixel.com/10-principles-for-keeping-your-programming-code-clean/), which was written in 2011 and is outdated in parts.

Section 2 from that article prescribes things like `<div id="header">`, which has now been superseded by semantic html, e.g. `<header>`.

Section 5 cites "Authoring specifications (e.g. /* Coded by John, November 13th 2010 */)" as an example of _good_ comment use, which contradicts the TOP lesson, which tells us "Don’t comment when you should be using git".

There is good advice in that article and I managed to spot the contradictions, but it was still a little confusing to be presented with conflicting information. It may be worth finding a similar article that has been written more recently and which uses more current practices.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

luflat

**Comment by thompsonslee** [comment]
I would love to help out with this issue. I'm currently on the lesson "Git in the Real World"

**Comment by CouchofTomato** [comment]
Thanks @sykul 

I agree we need to update this. Do you have an alternative in mind?

**Comment by sykul** [comment]
> Thanks @sykul
> 
> I agree we need to update this. Do you have an alternative in mind?

I didn't have an alternative in mind at the time, and it's not that easy to find one pitched at the right level for a learner at this stage of the course, however this one looks pretty good to me: https://dev.to/yogini16/clean-code-principles-4270

Section 4 references classes, which might go over their heads, and we should probably explicitly tell them to ignore section 9-16 and 19-20 because they're too technical for this level, but in general this article has really sound advice which is mostly at the right level in my opinion.

Happy to see other good alternatives of course.

**Comment by sykul** [comment]
I'm happy to work on it. I would love some feedback on my idea or possible alternatives before I go ahead and make the PR.

**Comment by ManonLef** [comment]
@sykul I think you can go ahead with your suggestion. If the alternative article is covering things not relevant to the lesson we indeed need to mention they can skip the points not covered yet.

**Comment by thompsonslee** [comment]
Sorry for the late reply, im happy for sykul to take the job. Good Luck!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CouchofTomato** [comment]
@sykul 

Hey, I'm just checking in to see if you are still interested in taking this on.

**Comment by CouchofTomato** [comment]
Closing due to lack of a response.
