### ISSUE TITLE
Wrong placement of page Commit Messages

### ISSUE THREAD

**Issue by its-hk** [TheOdinProject/curriculum#26281]
### Describe your suggestion

I think that this should be within the Foundations/Git Basics section rather than Foundations/HTML Foundations since that would make more sense to follow straight from there. It is in the correct place according to the git repo, but not in the website.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-commit-messages

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/foundations

Anyone have a view on this?

**Comment by KevinMulhern** [comment]
Thanks for taking the time to report @its-hk. However, the placement of this lesson is intentional. We want learners to go through it right before they tackle their first real project. The closer this lesson is to where learners can put it into practice, the more will be retained. We do this throughout the curriculum with Git topics.

But I'm sure this isn't the first time someone has asked this question. Maybe we should make the reasoning for its placement clear within the opening paragraph of the Commit lesson?

**Comment by waynefuchs** [comment]
I would like to propose the following text be added to the end of the section: [Lesson overview](https://www.theodinproject.com/lessons/foundations-commit-messages#lesson-overview):

> You should now be experienced enough with the basics of git to learn proper composition of your commit messages without getting bogged down by general theory and syntax. Your first big project, in the next lesson, will provide an excellent opportunity to practice authoring your commit messages while the knowledge is fresh in your mind.

**Comment by thatblindgeye** [comment]
@waynefuchs That content wouldn't really fit in the lesson overview section; that section is more meant as a quick, bulleted rundown of what the lesson will cover. We could maybe update the Introduction for this lesson to something like:

> In our [Git Basics lesson](https://www.theodinproject.com/lessons/foundations-git-basics), you learned how to write some basic commit messages without getting too bogged down by general theory and syntax. With the first big project coming up in the next lesson, it's time to focus more on the importance of commit messages so that you can fully take advantage of that knowledge while it's still fresh in your mind.

Or something along those lines.

**Comment by its-hk** [comment]
> Thanks for taking the time to report @its-hk. However, the placement of this lesson is intentional. We want learners to go through it right before they tackle their first real project. The closer this lesson is to where learners can put it into practice, the more will be retained. We do this throughout the curriculum with Git topics.
> 
> But I'm sure this isn't the first time someone has asked this question. Maybe we should make the reasoning for its placement clear within the opening paragraph of the Commit lesson?

Cool got you :) ! yeah, I think adding a reason would be nice 😀
