### ISSUE TITLE
Fundamentals Part 2: Typo Error in instruction.

### ISSUE THREAD

**Issue by AbuMahir980** [TheOdinProject/curriculum#26284]
### Describe your suggestion

I'd like to point out an error in the **5th instruction** for **step 3** under **Foundations of JavaScript 2 Exercise 4**.
[https://replit.com/@OdinProject/direction-follow#follow.js](url).

In step 3 of the exercise, it was stated that the outcome of **_greeting_** after creating **_fullName_** and **_age_** variables should look something like: **"Hello, my name is " + fullName.**

In the string above, if a **comma** is added after **hello** and the **m** is in lowercase and not in uppercase as stated in the example, the processor will indicate **greeting** is incorrect.

But what is meant to be there is an **exclamation mark after hello** as this gives a correct output. ie.  **"Hello! My name is " + fullName**.... This can cause one to be in a state of confusion when the output keeps showing incorrect and one is certain of doing the right thing.

### Path

Foundations

### Lesson Url

https://replit.com/@OdinProject/direction-follow#follow.js

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

@AbuMahir

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please

**Comment by wise-king-sullyman** [comment]
Unfortunately, we don't have Replit integrated with GitHub so contributors aren't able to make changes on it.

I did make the change you suggested, does it look good to you now @AbuMahir980?

**Comment by AbuMahir980** [comment]
@wise-king-sullyman Thank you for the correction, it looks better now.

**Comment by ManonLef** [comment]
I'll close this then. Thank you @AbuMahir980 and @wise-king-sullyman !
