### ISSUE TITLE
Foundations: Add info about size attributes to img tag introduction

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#26288]
### Describe your suggestion

It is really important to include height and width attributes in every img tag to help prevent layout shift.  This is touched on later in the CSS lessons but is somewhat confusing as it is not mentioned here.

I don't think we should go into a lot of detail at this point, but I do think we should mention that height and width need to be specified.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images#images

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

FabulousGeek

**Comment by rlmoser99** [comment]
@codyloyd Since you are very familiar with Foundation's html/css lessons, what do you think of this suggestion?

**Comment by DonnieAndMooie** [comment]
I think this sounds like a good idea. I'm looking to contribute to TOP for the first time, and feel this would be a fairly simple thing for me to start with.

**Comment by codyloyd** [comment]
While it’s not necessarily true that height and width _neeeed_ to be defined, I do think it’s worth mentioning here.  👍🏽

**Comment by rlmoser99** [comment]
Assigned @fabulousgk because they created this issue and indicated that they would like to work on it in the original issue.
