### ISSUE TITLE
NodeJS: inaccurate mention of database

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#26298]
### Describe your suggestion

The "Deployment" lesson provides instructions for publishing the database from the the "Mini Message Board" project ,
But that project doesn't have a database,
This information remains important for later projects, so it needs to be revised and moved elsewhere in the lesson or to another lesson.
![image](https://github.com/TheOdinProject/curriculum/assets/55961349/de0af11f-4794-4423-97ea-9f0759be2055)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-deployment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Omar (onsmak) @onsmak

**Comment by rlmoser99** [comment]
Can someone from the @TheOdinProject/javascript team review this issue and if this is something we want to move forward with, suggest a place where the database instructions should go.

**Comment by fortypercenttitanium** [comment]
This is correct. The mention of a database should be removed, it's an artifact of a previous version of the lesson that used a database. I'm not sure when that change happened, but I just checked the lesson and the messages are stored in memory now.

**Comment by OmarNaguib** [comment]
> This is correct. The mention of a database should be removed, it's an artifact of a previous version of the lesson that used a database. I'm not sure when that change happened, but I just checked the lesson and the messages are stored in memory now.

Okay, where should i put the instructions on database deployment?

**Comment by OmarNaguib** [comment]
@fortypercenttitanium 
I have now read [Security Configuration](https://www.theodinproject.com/lessons/nodejs-security-configuration).
![image](https://github.com/TheOdinProject/curriculum/assets/55961349/d959eabc-24e5-4525-9a4c-215a21e59c5a)
And seeing that it it's made specifically for this subject, and it advises on going back to past projects to secure them,
I now suggest removing all relevant content from the deployment and copying over the medium article and the PaaS instructions to the Security Configuration lesson.

**Comment by fortypercenttitanium** [comment]
@OmarNaguib this is a tricky one, because the lesson is about deployment and these tips about deploying a DB are useful. Maybe we can make them not part of the "assignments" but just part of the core lesson instead? Maybe make a note like "even though the message board doesn't use a database, here are some things to keep in mind when deploying an app that does use one."

What are your thoughts?

**Comment by CouchofTomato** [comment]
Hi @OmarNaguib 

Are you still interested in taking this idea forward?

**Comment by OmarNaguib** [comment]
@CouchofTomato yes

**Comment by CouchofTomato** [comment]
@OmarNaguib 

Thanks. Is there any support you need at this time?
