### ISSUE TITLE
NodeJS: Insufficient guidance for deploying on Fly.io and connect to MongoDB

### ISSUE THREAD

**Issue by sawfiz** [TheOdinProject/curriculum#26302]
### Describe your suggestion

At the end of the NodeJs deploy lesson, it does not mention if you are deploy on a PaaS, you need to make sure to also edit the IP address access list of the MongoDB database to accept access from the deployed app.

Specifically for Fly.io, the IP of the host machine is for ingress only.  To be able to access the MongoDB database, there are 2 options:
1. enable "Allow access from anywhere", less secure
2. use an intermediate service, e.g., discussed at https://community.fly.io/t/mongodb-atlas-ip-addresses/12605

> "Currently, we don’t support static egress IPs.
> 
> So your best option is to proxy all your database traffic through a service that allows you to have static egress IPs. I’ve seen a few people use Digital Ocean Droplets on the forum.
> 
> your fly app → digital ocean droplet → mongodb atlas"

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-deployment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by rlmoser99** [comment]
Can someone from the @TheOdinProject/javascript team please review this issue

**Comment by codyloyd** [comment]
I'm a little unsure about this one.  I have a feeling that each of the PaaS sites will end up behaving a little differently, so I'm not sure we _can_ write specific instructions about this particular issue.

We probably _could_ make a kind of general mention of it, and state a little more strongly that users will need to rely on their chosen PaaS provider's official documentation.  However, I do think that is already kind of implied.

@TheOdinProject/javascript anyone else have any input on this?

**Comment by 01zulfi** [comment]
Agreed with @codyloyd. It won't be feasible to keep up with all PaaS's implementations w.r.t. the projects in the curriculum. Though I wouldn't be opposed to adding this particular link in the "Links" subsection of Fly.io section in the lesson:

![image](https://github.com/TheOdinProject/curriculum/assets/85733202/68a32fbe-5d9c-4496-9c0e-086729a5a8f4)

**Comment by CouchofTomato** [comment]
@sawfiz 

Are you still wanting to take this on or are you happy for us to close the issue?

**Comment by sawfiz** [comment]
Hi,

Plasse close.

Thanks,
Victor
