### ISSUE TITLE
<Ruby>: <Add time complexity resource to additional learning>

### ISSUE THREAD

**Issue by brandonkounse** [TheOdinProject/curriculum#26300]
### Describe your suggestion

I would like to suggest a video for additional resources in the lesson ruby time complexity. This is a ~36 minute video going over the introduction of Big O notation and time complexities. The reason I believe this would be a valuable additional resource is because the host goes over how to think through the code and break down each component into time complexities. I found it very helpful, and thought it might be of help to others.

Here is the URL for the YouTube video for review/consideration:

https://www.youtube.com/watch?v=D6xkbGLQesk

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-time-complexity

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Korr

**Comment by rlmoser99** [comment]
Can someone from the @TheOdinProject/ds-a team please review this issue

**Comment by codyloyd** [comment]
re-pinging @TheOdinProject/ds-a

**Comment by 01zulfi** [comment]
Thanks @brandonkounse for creating an issue.; will go over the resource soon

**Comment by brandonkounse** [comment]
Thank you all for looking into it. I hope it adds value like I think it does. If it isn't used, I totally understand and just wanted to try and help improve the curriculum.

**Comment by CouchofTomato** [comment]
@brandonkounse 

Hey dude,

sorry for the delay. I'm fine with this being added as an additional resource.

**Comment by brandonkounse** [comment]
@CouchofTomato 

Thanks for the information. To move forward, do you want me to submit a pull request for the change and close the issue? Still new to the flow/process here, thanks!

**Comment by 01zulfi** [comment]
@brandonkounse Please create a pull request. We can close this issue once the pull request is merged, thanks
