### ISSUE TITLE
Foundations/Git Basics: Update lists per layout style guide

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26304]
Lists should be updated in the following ways to align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md):

- Any unordered list items that are created with an asterisk `*` are replaced with a hyphen `-` instead. For example, `* A list item` should be updated to `- A list item`
- The list item content is updated so it only has a single space before it. For example, `1.   A list item` has 3 spaces before the list item content ("A list item"), and should be updated to `1. A list item`
- Appropriate punctuation is added at the end of each list item in the "Lesson overview", "Assignment", "Knowledge check", and "Additional resources" sections
  - Follow the [Google style guide ](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists) to determine when to add punctuation
- Any additional updates mentioned for specific lessons

### Guidance:

- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` keyword. 

### Lessons to update

- [x] @Sushant9473 [Introduction to Git](https://www.theodinproject.com/lessons/foundations-introduction-to-git)
- [x] @ht-l1  [Git basics](https://www.theodinproject.com/lessons/foundations-git-basics)

**Comment by Sushant9473** [comment]
can i work on this

**Comment by Sushant9473** [comment]
Using `-` instead of `*` is preferred but throughout Odin Project `*` is used for unordered list .  If we were to change it to `-` then we would have to change it everywhere .

**Comment by ManonLef** [comment]
@Sushant9473 that's exactly what's being worked on. Changing it everywhere, section by section.

**Comment by Sushant9473** [comment]
Can i start working on this ?

**Comment by ManonLef** [comment]
Yes, @Sushant9473 I'll assign you the top lesson. Thank you!

**Comment by Sushant9473** [comment]
I can also update list layout of Git basics if no one assigned .

**Comment by ht-l1** [comment]
would love to work on it :)

**Comment by thatblindgeye** [comment]
@ht-l1 you got the last lesson!

**Comment by thatblindgeye** [comment]
@Sushant9473 If you mean linking a PR to an issue that you got the go-ahead to start work on, that's fine. Typically it's good etiquette to wait to work on/put a PR up until you've gotten the "okay" from a maintainer (which you did in this case). Thanks for double checking on that (and hopefully this answers your question).

**Comment by waynefuchs** [comment]
@ManonLef  If possible, I would like to be assigned one of the lessons, please.

**Comment by ManonLef** [comment]
@waynefuchs it looks like all of the lessons have been assigned already. 
Keep an eye on this [repo's issues](https://github.com/TheOdinProject/curriculum/issues) because more good first issues similar to this one are still planned.

**Comment by Sushant9473** [comment]
Is there a problem with my PR cause it's not being merged ?

**Comment by ManonLef** [comment]
@Sushant9473 it looks like a maintainer asked @thatblindgeye for some feedback first.

**Comment by thatblindgeye** [comment]
Closing as all tasks are complete
