### ISSUE TITLE
JavaScript: A typo in Objects and Object Constructors lesson

### ISSUE THREAD

**Issue by headlessNode** [TheOdinProject/curriculum#26306]
### Describe your suggestion

There is typo in the lesson overview section, 4th bullet point "Understand the basic do’s and don’t’s of **prototypical inheritance**". It should be prototypal inheritance.

**edit: There is a second instance of this typo in the knowledge check.**

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors#lesson-overview

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

headlessNode

**Comment by OmarNaguib** [comment]
@headlessNode good catch

i'd like to do it (unless you'd like for a first time contributor to do it)

**Comment by rlmoser99** [comment]
@OmarNaguib Thanks for the offer. I am going to put a label on it for a first time contributor, but if no one picks this up within the next 3 days, you are welcome to ask again.

**Comment by danzym** [comment]
Perfect, thank you! No questions so far.

**Comment by MikeJakuszewski** [comment]
Is this still available? I would love the opportunity to contribute to this.

**Comment by rlmoser99** [comment]
@MikeJakuszewski Sorry it is not available, but please keep on eye on our issues page for other opportunities!

**Comment by MikeJakuszewski** [comment]
@rlmoser99 Okay, thank you. If anything changes, please let me know :)
