### ISSUE TITLE
Update level 2 headings to level 3 headings

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26305]
### Describe your suggestion

There are a few lessons where level 2 headings are being used as section headers, when those should really be level 3 headings.

- The "Additional resources" section in [fetching data in React](https://github.com/TheOdinProject/curriculum/blob/main/react/the_react_ecosystem/fetching_data_in_react.md)
- Several sections in both the "model testing" and "unit testing" files in our [`ruby_on_rails/testing` directory](https://github.com/TheOdinProject/curriculum/tree/main/ruby_on_rails/testing)

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by laxcapy** [comment]
@thatblindgeye Would I be able to work on this issue?

**Comment by OmarNaguib** [comment]
> @thatblindgeye Would I be able to work on this issue?

It's marked as a good first issue, if you're a first time contributer, then yes.

AFIAK
Level 2 headings are marked with ##
Level 3 are ###

**Comment by Sushant9473** [comment]
Can i work on this .

**Comment by thatblindgeye** [comment]
@laxcapy you got it! Feel free to update all the lessons listed in the original comment

**Comment by laxcapy** [comment]
@thatblindgeye Thanks! I'll start chipping at it
