### ISSUE TITLE
Foundation-The Cascade: Add text to demo html

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#26303]
### Describe your suggestion

The demo html does not contain any text in the divs and therefore if a student copies and pastes the code there is no visible effect.  I believe that the samples are not really meant to be executed, but some folks will do so.

I suggest we add some text, perhaps the word of the color that the text should be.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade#the-cascade-of-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

FabulousGeek

**Comment by rlmoser99** [comment]
I think this is a great suggestion, as I often copy/paste every code snippet when I am learning something new. Since you indicated that you'd like to work on this issue, I will assign it to you.
