### ISSUE TITLE
Fundamentals Part 2: Additional resources nesting

### ISSUE THREAD

**Issue by azureskyes** [TheOdinProject/curriculum#26313]
### Describe your suggestion

Reaching the "Additional resources" section of the page, I thought there was supposed to be a link in the first bullet point, specifically for the first few words "Regular expressions ... " (html: <ul>
<li> Regular expressions, commonly known as ...</li></ul>).

For easier/better readability, Id like to put forth a suggestion to nest the next two hyperlinked bullet points with the first bullet point as parent; or, sub-optimally, to inject the links underneath within the first bulletpoint paragraph.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-2

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Can someone take a look please https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/fundamentals-2.md

Assume there should be a link here somewhere.

**Comment by thatblindgeye** [comment]
Yeah we could place those links in the first bullet point. We can also remove some unnecessary verbiage, namely the last two sentences, "Although it shouldn't be your immediate solution this early on, you can still use this resource to understand how websites know that myemail@com isn't a valid email address. On top of that, other solutions to filter out strings exist, and regex is considered a slow operation." We can just use the first sentence and then add some verbiage that links to those 2 resources.

@azureskyes you're assigned if you'd still like to put a PR up

**Comment by azureskyes** [comment]
Done. Thanks for the suggestions!
