### ISSUE TITLE
Node: Railway no longer has 500-hour free tier

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26316]
#### Update:
It appears my issue currently relates to Railway not being able to verify my GH account and thus have blocked code deployment with the $5 trial credit via a limited trial account. It appears there may be a code deployment issue ongoing so it's entirely possible that my verification issue is related.

What does need changing is the free tier description being from 500 hours to a [one-time $5 credit grant](https://docs.railway.app/reference/pricing#free-trial) for verified accounts (automated process).

---

### Describe your suggestion

Railway no longer has a 500 hour free plan as they have deprecated their starter plan.
The lowest-cost option on their site is now the $5/mo "Hobby" plan.

Proposal to move Railway.app's listing to the bottom with `N/A` in its free plan section, by Heroku.

This also leads to an issue with the MDN "local-library" tutorial project, as that uses Railway for deployment and has not yet been updated to reflect the dropping of the free tier. In [the lesson that links that part of the tutorial](https://www.theodinproject.com/lessons/nodejs-express-105-forms-and-deployment), a simple note about Railway could be added that if you want to deploy the local library, you will need to use a different PaaS if you do not want to pay (understandable).

In [the deployment lesson itself](https://www.theodinproject.com/lessons/nodejs-deployment), it says `Later in this course, we will be following the MDN tutorial's instructions on deploying both our app and database connection to Railway.` This little part should probably be reworded (as well as the assignment part that says `If for some reason the deployment is still too difficult, and you just can't seem to get it to work, move onto the next project and come back once you've deployed your MDN project.`, since Railway will no longer be a free option for anyone).

Fly.io also seems to have very recently started to move away from Express Node. I had no issues a few weeks ago but now the link in the deployment lesson to their [guide on deploying a NodeJS app](https://fly.io/docs/languages-and-frameworks/node/) now redirects to their basic JS page, and the sidebar option for NodeJS/Express has now gone. The search bar also no longer returns relevant Express/Node results.

Currently Render seems to work fine for free.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-deployment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

mao_sz

**Comment by OmarNaguib** [comment]
Hello, @MaoShizhong 
I think railway still works for free, I deployed local-library 5 days ago
This [article](https://leofinance.io/@geekgirl/railway-will-be-discontinuing-free-plans) explains that they give you 5$ dollars of one time credit for free.
The same is specified in their [docs](https://docs.railway.app/reference/pricing).
It appears the difference is you get 5$ one time instead of 500 hours.

This checks out with what appears when I login to Railway.app
![image](https://github.com/TheOdinProject/curriculum/assets/55961349/ab2667a2-7cfa-4f1b-936f-2d73f5843045)

I don't think instructions should be changed to move away from Railway for now as they will still work, but we can change the lesson to say 5$ instead of 500 hours, what do you think?

**Comment by MaoShizhong** [comment]
Interesting - after connecting my GH account, mine shows that I'm on a limited trial account which disallows deployment of code and only allows database deployments within the $5 free credit, hence believing they've scrapped the free trial for our specific purposes.

Looking into it further, it says that there's an automated verification process when you connect your GH account against various parameters - no mention of how long such a process takes and exactly what those parameters are (it does vaguely mention "a number of factors include age and activity of the account").
I don't see any glaring issues with my GH account that would prevent verification (not a new account, plenty of activity) so if this is a longer process a fresh Railway account must sign up for, at the very least that should be mentioned. Anyone else who signs up and is put in the same limited trial state will be unable to use Railway for their deployments.

**Comment by MaoShizhong** [comment]
But certainly, the 500 hours should be changed to $5 worth of credit if your account is verified for code deployment, with a note to the docs indicating depending on resource-usage, that could maintain deployment for anywhere around a month or beyond.

**Comment by OmarNaguib** [comment]
@MaoShizhong The plot thickens 😄 
 just tried clicking on "new project" and this appeared.
![image](https://github.com/TheOdinProject/curriculum/assets/55961349/8de28070-b9d9-4bcd-8848-6dfded2a2763)

This "ongoing incident" might be why you're having trouble.
FWIW making an account and deploying was very smooth with me




> But certainly, the 500 hours should be changed to $5 worth of credit if your account is verified for code deployment, with a note to the docs indicating depending on resource-usage, that could maintain deployment for anywhere around a month or beyond.

good idea

**Comment by MaoShizhong** [comment]
@OmarNaguib Interesting!
Perhaps we should give it time to evaluate the ongoing issue, but yes, if the 500 hours thing has otherwise been replaced by the one-time $5 credit then that does need to be changed eventually.

I previously had no issues with fly.io (deployed my message board just a few weeks ago via instructions in their docs) but they've now removed those instructions and have removed a lot of Express/Node stuff since.

**Comment by HromasDev** [comment]
If you install the app and don't spend $ 5 per month, is it possible to extend this trial period for free?

**Comment by MaoShizhong** [comment]
@HromasDev I'm not sure what "app" you're referring to? AFAIK Railway doesn't have an app to download and regardless, there's no extending of anything. A free account is granted a a one-time $5 credit which (if the account passees the automated verification) can be used to deploy an app on their service. Using resources will cost money and once that $5 credit is used up, there's no getting more credit back other than paying.

**Comment by MaoShizhong** [comment]
Just checked yesterday and today and about time, today my GH account finally passed verification so it was just an issue on their end - successfully deployed a test server on it so all is good and Railway have not returned their free tier (yet.......)

However, it still requires changing from the 500 hours to the one-time $5 free credit Grant for verified trial accounts as discussed above.

I am happy to do this but also don't mind at all if anyone else wishes to be assigned to this if so.

**Comment by srivathsa-yashwanth** [comment]
Hello, I would like to work on this. @TheOdinProject could you please confirm if these changes are welcome?

**Comment by srivathsa-yashwanth** [comment]
@TheOdinProject/Javascript did I tag you guys correctly?

**Comment by OmarNaguib** [comment]
@srivathsa-yashwanth i would say make the pull request directly and it will be reviewed there since it's a small change

**Comment by srivathsa-yashwanth** [comment]
Great. Please assign this issue to me.  Thank you!

**Comment by OmarNaguib** [comment]
@srivathsa-yashwanth i am not a maintainer,
I have been advised by mannon (a maintainer) that for small changes you can make a pull request directly

**Comment by srivathsa-yashwanth** [comment]
Oh got it. Thank you for your patience😊

**Comment by rainbowswordd** [comment]
erm guys can we not use railway for free now

**Comment by MaoShizhong** [comment]
> erm guys can we not use railway for free now

This is an old issue when Railway changed their free system. New users get a one-time $5 credit grant. Once that's used up, Railway is no longer free. This is what our backend deployment lessons say.
