### ISSUE TITLE
Restaurant page - JS: Remove instruction

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#26324]
### Describe your suggestion

In the restaurant page project I would like to remove this instruction:
```
Set up an HTML skeleton inside of dist/index.html with single <div id="content">.
```
I think that this is a better point, because students will be using webpack to create their HTML file, and should not be using a template for this project as well. It is a bit confusing and I really do not think it is necessary. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-restaurant-page

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

mfrayray

**Comment by urialevy** [comment]
I would like to work on this issue, too. :D

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by xandora** [comment]
If we remove the step to create the `<div id="content">` from that part of the lesson, we won't have anything to anchor to when we reach these steps later:

> 4. Create a bare-bones homepage for a restaurant. Include an image, headline, and some copy about how wonderful the restaurant is. It’s okay to hard-code these into the HTML for now just to see how they look on the page.

> 5. Now remove those elements from the HTML (so leave only the `<html>`, `<body>`, and `<div id="content">` tags) and instead create them by using JavaScript only, e.g. by appending each new element to `div#content` once the page is first loaded. Since we’re all set up to write our code in multiple files, let’s write this initial page-load function inside of its own module and then import and call it inside of index.js.

Webpack doesn't magically do this for us and after working through the lesson, but skipping that step, I find I have to go back and create that anchor div anyway.

**Comment by Baguirre03** [comment]
@xandora -- I think the main issue here, is that by now _if_ the user had followed the webpack instructions correctly, they _should_ be using the `HtmlWebpackPlugin` which will auto-generate the `index.html` in turn erasing this dummy content that is being created. I see though how this should stay if they are not using it.

**Comment by xandora** [comment]
Yep, that makes sense to me. We do introduce the Output Management section of the Webpack documentation in the lesson immediately prior to this one, so we could replace all these mentions with something focused on `HtmlWebpackPlugin` instead. Or, at the very least, make mention of both ways if someone doesn't feel like using the plugin for this.

@urialevy I think this one is ready for work if you'd like to start looking into how we can modify this lesson to make better mention of the `HtmlWebpackPlugin` to generate `index.html` files.

Criteria for Acceptance:
- [ ] Introduces mention to include `HtmlWebpackPlugin`
- [ ] Reworks or removes need to create `index.html` with `<div id="content">`
- [ ] Reworks or removes steps 4. and 5. to better reflect the previous 2 points
- [ ] Other tasks to be determined by code review

**Comment by ManonLef** [comment]
I think mentioning the use of `HtmlWebpackPlugin` is a great addition. It gets introduced as an optional tool, but learners would benefit from using it. 

Nice criteria @xandora  🎉

**Comment by Baguirre03** [comment]
Woot. I agree this is a good choice. @xandora  thank you!

@urialevy , let me know if you need help with anything :)

**Comment by urialevy** [comment]
Will do! I'm currently abroad without access to the machine, but I'll work on this when I have access again (assuming no deadline on this)

**Comment by MaoShizhong** [comment]
I agree and think this is a great idea. I've been trying to champion the idea of the course promoting *all* dev work to be done within `src/` (which will also allow you to point `webpack-dev-server` to `src/` instead of `dist/`, making using it far easier), so trying to promote this in the restaurant project is something I like a lot.

**Comment by urialevy** [comment]
OK, I created a new version that I think fulfills the criteria: https://github.com/urialevy/odin-curriculum/blob/main/javascript/organizing_your_javascript_code/project_restaurant_page.md

What are the next steps? Do I create a pull request or something for this?
