### ISSUE TITLE
Foundations: A brief mention of HTML attributes before using the word 'attribute' in the lesson "HTML Boilerplate"

### ISSUE THREAD

**Issue by satvator** [TheOdinProject/curriculum#26320]
### Describe your suggestion

The lesson "HTML Foundations" has a section "HTML Boilerplate", where there's a topic named "HTML element". It contains a sub-heading "lang attribute" where it is nowhere mentioned what are HTML attributes in the first place. Considering it is mentioned in one of the following lessons, it is worth acknowledging the same or maybe briefly defining the term here itself.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-html-boilerplate

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Satyam

**Comment by rlmoser99** [comment]
Thank you for taking the time to write up this issue. I think this is a chicken & egg situation and the lesson that you linked provides enough context for the minimal use of the word "attribute". As mentioned, the [Links and Images](https://www.theodinproject.com/lessons/foundations-links-and-images#anchor-elements) lesson goes into much more in depth. However, I think moving some/all of it would over-complicate the Boilerplate lesson.

However, I am not an expert on these lessons, so I am going to ask @codyloyd who is much more familiar with the reasons behind the structure of these lessons to review this issue as well before making a decision.

**Comment by satvator** [comment]
I appreciate your prompt response, and I totally see your point. It's just that I thought some sort of acknowledgment regarding 'attributes' might help the absolute beginners.

**Comment by codyloyd** [comment]
I do believe that a one or two sentence description of 'attribute' would be appropriate there.

it's not a hard concept, but it does come up more than once.

**Comment by rlmoser99** [comment]
@satvator Before I assign you to work on this issue, I would like to confirm that you still would like to work on this by adding 1-2 sentences to the boilerplate lesson.

**Comment by satvator** [comment]
@rlmoser99 Yeah sure. I don't see why not.
