### ISSUE TITLE
Emmet: Unclear that Emmet is built into VS code

### ISSUE THREAD

**Issue by rpoirier** [TheOdinProject/curriculum#26329]
### Describe your suggestion

I found it unclear that Emmet is built into VS Code and is not an extension I needed to install. I only found that out by googling how to install the Emmet extension because I couldn't find an extension just named Emmet in the VS Code Extension marketplace. It only wasted a few minutes, but man, that was a confusing way to start a lesson.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-emmet#emmet

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by oscargmora** [comment]
Hi, may I be assigned this issue?

**Comment by xandora** [comment]
I'm not sure it's necessary to assign this to anyone. It's made clear in the first paragraph of the lesson that it's a built-in to VSCode.

![image](https://github.com/TheOdinProject/curriculum/assets/2021268/8affd586-6a5d-49d0-b59f-6b8a1891f073)
