### ISSUE TITLE
<Ruby on Rails>: <Fix Broken Link>

### ISSUE THREAD

**Issue by Leo-U** [TheOdinProject/curriculum#26333]
### Describe your suggestion

[The third link listed under the 'HTTP' section of the lesson is broken.](https://www.theodinproject.com/lessons/ruby-on-rails-a-railsy-web-refresher#http)

It's supposed to link to a video by tutsplus.com.

Wayback Machine (https://archive.org/web/) gives us the author, video length, and video title as you can see [here](https://web.archive.org/web/20220525222111/https://code.tutsplus.com/tutorials/how-the-web-works-http-and-the-web-server--cms-25971). Using that, I was able to find the new video location:

https://code.tutsplus.com/how-to-become-a-web-developer--CRS-200371c/http-and-the-web-server

So to reiterate, someone needs to:
Replace [this link](https://code.tutsplus.com/tutorials/how-the-web-works-http-and-the-web-server--cms-25971) with [this link](https://code.tutsplus.com/how-to-become-a-web-developer--CRS-200371c/http-and-the-web-server).

I do not want to work on this.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-a-railsy-web-refresher#http

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by oscargmora** [comment]
Hi, may I be assigned this issue?

**Comment by xandora** [comment]
@oscargmora Certainly. It's all yours.

**Comment by sachinrao8312** [comment]
Hi, I have created a PR for this issue have a look. https://github.com/TheOdinProject/curriculum/pull/26338
Thanks 
Sachin Rao

**Comment by xandora** [comment]
> Hi, I have created a PR for this issue have a look. #26338 Thanks Sachin Rao

Hi, we already have someone assigned for this issue. Please do not work on issues that have not been assigned to you, as this wastes time for everyone.
