### ISSUE TITLE
Foundations/Git Basics: Incorrect content in the Knowledge Check section

### ISSUE THREAD

**Issue by nasal-siesta** [TheOdinProject/curriculum#26332]
### Describe your suggestion

The Knowledge Check section of Git Basics contains Lesson Contents rather than questions.

![image](https://github.com/TheOdinProject/curriculum/assets/106816721/13146e3b-eb55-474f-a2bd-71b8ac760fd9)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics#knowledge-check

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Asartea** [comment]
This seems to have happened accidentally in https://github.com/TheOdinProject/curriculum/commit/4cf38f2714c27882ec5acae7755cedbfd3fa9a44.

**Comment by ascodeasice** [comment]
Hi, can I work on this issue?

**Comment by ManonLef** [comment]
Thank you!
