### ISSUE TITLE
<NodeJS>:Clarify passports behaviour

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#26342]
### Describe your suggestion

![image](https://github.com/TheOdinProject/curriculum/assets/55961349/e52780cb-9f5c-4efd-b8b2-814d4368e150)

The text above makes use of the id property which is a virtual property created by mongoose (string version of _id).

learners at that point aren't aware of this virtual property.
it led me to believe that the user object was created by passport while it's created and passed by us, which is an important distinction.

I'd like to clarify what user.id is.
 and also clarify that the functions we defined for passport are using the user object we passed it, injecting it's id in the cookies, and then using that id to get a user object again, and this loop allows the client to remain logged in and synced with the server.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-authentication-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
Hmm, I need more time to mull over this. @TheOdinProject/javascript, what do y'all think?

**Comment by wise-king-sullyman** [comment]
I'm not sure that I understand the confusion, but I'm not opposed.

**Comment by codyloyd** [comment]
I'm with Sully here.  It seems like it wouldn't _hurt_ to include whatever you have in mind @OmarNaguib.  I have gone ahead and assigned this issue to you, go ahead and do the PR if you want.

If you're adding more than a few lines of text, then it might be worth summarizing/outlining what you plan to say here so you can get a 👍🏽 before adding it.  It would be a bummer if you spent a ton of time writing out hundreds of words only to have the PR rejected.

**Comment by MaoShizhong** [comment]
Missed this in my search before opening #26516.
Just wanted to point out whilst the `.id` thing is an arguably less vital clarification, I think the clarification of what the two functions and their callbacks actually do is really quite useful. Unfortunately exactly what they do and how they work (in case you would want to change the callbacks to suit your needs) seems to be very poorly documented and led me on quite an annoying search through resources to find one member-blocked medium article where the author explained them (and also complained about the lack of documentation on these (and other passport middleware specifics)).

**Comment by OmarNaguib** [comment]
@MaoShizhong feel free to take on this issue if you want

**Comment by MaoShizhong** [comment]
@OmarNaguib it's fine, you opened the same issue first which I missed so I don't want to take over what you were assigned 👍

**Comment by OmarNaguib** [comment]
@MaoShizhong well mine was focused on the id thing so i think you'd be more able to write on passport's behaviour.
Maybe i can write the id part and you the passport part

**Comment by OmarNaguib** [comment]
Looks good! @MaoShizhong 
That's exactly what was missing,
I will be making the pull request and adding you as co-author
