### ISSUE TITLE
<Fundamentals Part 3>: <add additional resources for scope chain>

### ISSUE THREAD

**Issue by ht-l1** [TheOdinProject/curriculum#26343]
### Describe your suggestion

Add one link reference [Global, Function and Block Scope, Lexical vs Dynamic Scoping](https://dev.to/pranav016/advanced-javascript-series-part-41-global-function-and-block-scope-lexical-vs-dynamic-scoping-20pg)  under section Additional Resources to better understand scope chain. It helps clarify the difference between Block Scope, Function Scope, Local Scope, and Global Scope. Also it explains the difference of Lexical vs Dynamic Scoping. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-3

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@ht-l1 Thanks for opening this issue. I like the resource, though I feel it might be a little more advanced for learners who are at the fundamentals part 3 lesson. Especially when it goes through lexical vs dynamic scope. For this reason, I'm hesitant to add this in the additional resources. What do you think?

**Comment by ht-l1** [comment]
yeah I actually got this concept from a fundamental web dev course so I was under the impression that it is a basic concept. I searched around including odin to find more resources but don't see it in Odin that's why I proposed this add. but what you said makes sense to me!

**Comment by 01zulfi** [comment]
Thanks, looking forward to more contributions. Closing this issue now
