### ISSUE TITLE
Chore: NPM article in "Getting started with node" should be replaced with new official link

### ISSUE THREAD

**Issue by Voltz7788** [TheOdinProject/curriculum#26345]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Chore description

In the "Getting Started" lesson in the node section, it says that some of the articles aren't available so the github repo links were given instead. I found that the NPM article (where it says "Let's get an introduction to NPM") is actually available on the official website (at this link: https://nodejs.dev/en/learn/an-introduction-to-the-npm-package-manager/). Maybe it's worth replacing the old link with this new one?

### Acceptance criteria

- [x] replace old "Let's get an introduction to NPM" link with the new link to the official website

**Comment by xandora** [comment]
We originally did this because someone at Node, in their infinite wisdom, nuked all the articles from the official website. There was much uproar from the community.

If all the articles are back online, and still include the same content, we can probably switch them back to the hosted versions.

@Voltz7788 You've marked that you want to work on this one, please confirm with a reply and I'll get it assigned to you.

**Comment by Voltz7788** [comment]
Yeah I'd like to work on this one. I'm not sure what other articles are back online but the npm one definitely is so I'll work on that!

**Comment by xandora** [comment]
I assume you mean this section of the Getting Started in Node section?

![image](https://github.com/TheOdinProject/curriculum/assets/2021268/d347d45c-74d5-4087-8f2c-8e30ba736aff)

If you do, you'll find a lot of these links point to the nodejs github page. They are the articles I'm talking about. If possible, can you check them all?

**Comment by Voltz7788** [comment]
Yeah those are the articles I was talking about, the "Let's get an introduction to NPM" one in particular. I'll check if the others are online too and add them in if they are

**Comment by Voltz7788** [comment]
I've replaced the links to some of the articles with the newly uploaded docs but not all since some are still unavailable. I've made a pull request with my changes.

Also thanks for assigning this to me! I just worked through the advanced git section on the JavaScript course and was hoping to find something where I could contribute :)
