### ISSUE TITLE
React: Vite not running

### ISSUE THREAD

**Issue by i5x64BIT** [TheOdinProject/curriculum#26351]
### Describe your suggestion

In the current lts version of node, the latest vite version throws an error.
as stated in [this issue](https://github.com/vitejs/vite/issues/14299), vite can be run on node version 20.6.1.
Easily fixed it by running `nvm install node`.
Maybe add a temporary notice?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@i5x64BIT We have learners install Node's LTS version in the earlier installation lesson (which is v18.18.0 currently). Does this bug persist on Node's LTS version?

**Comment by i5x64BIT** [comment]
Yes, it is some problem between the latest Vite and the LTS version of node.
So either we should ask the students to install a specific version of vite or the latest of nodejs.

**Comment by 01zulfi** [comment]
I'm unable to reproduce any errors on the Node's LTS version `18.18.0`. 

Commands I used for Vite w/ Vite version `4.4.5`:

```bash
# this is the command we use in the curriculum
npm create vite@latest my-first-react-app -- --template react

cd my-first-react-app

npm install
npm run dev
npm run build
```

None of the above gave any errors and worked as expected. Though I did get the [this error](https://github.com/vitejs/vite/issues/14299) on Node `20.6.0`

@i5x64BIT, please confirm. Also, what do you think we should do? Maybe a reminder in the [setting up React lesson](https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment) to use Node LTS?

**Comment by i5x64BIT** [comment]
@01zulfi Yep, just leave a note about a possible conflict.

**Comment by 01zulfi** [comment]
Sounds good.

I'm opening the issue up for contribution. Acceptance criteria as follows:

- [ ] Add a sentence in [setting up a React env lesson](https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment#creating-a-react-app) right before the `npm create ...` command:
    - It needs to be something along the lines of, "Please make sure that you're on Node's LTS version.'

**Comment by ScaxCodes** [comment]
Good morning, ☕
Would you assign me to this issue? I'd like to fix it. It would be my first contribution on github.

I've read the contribution guide. ✅

**Comment by 01zulfi** [comment]
Thanks @ScaxCodes, I've assigned the issue to you.
