### ISSUE TITLE
React: add note on PropTypes error

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#26352]
### Describe your suggestion

I have noticed that this [question](https://discord.com/channels/505093832157691914/664184123061174274/1153232857104400465)  pops up repeatedly on discord.

That is people being confused on why they are getting a PropTypes error before doing the later lesson.

I suggest adding a quick note about.
A possible location would be the passing data lesson

Note content would be something like this:

![Screenshot_20230918-132321](https://github.com/TheOdinProject/curriculum/assets/55961349/8367fbf6-ea91-4244-9332-ad51dd478057)

And maybe provide the linting rule to be copied directly.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-passing-data-between-components

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Omar (onsmak) @onsmak

**Comment by ManonLef** [comment]
Thanks, there's already [a PR for that](https://github.com/TheOdinProject/curriculum/pull/26270) so I'll close this now :)
