### ISSUE TITLE
Stale: Investigate using new major version

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#26368]
### Describe your suggestion

I was poking around the workflows for #26367 and noticed we are three major versions behind on the current one on `actions/stale` (`v5` vs `v8`). Given that `v5` got last updated over a year ago, it might be worth upgrading to the newest major.

### Path

Other / NA

### Lesson Url

N/A

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

asarta

**Comment by 01zulfi** [comment]
Makes sense, assigned.
