### ISSUE TITLE
Intro to CSS: <Short description of your suggestion>

### ISSUE THREAD

**Issue by johnly25** [TheOdinProject/curriculum#26364]
### Describe your suggestion

For "02-class-id-selectors" section, the solution.css and solution.html doesn't display the desired outcome for the forth element. It's supposed to be have a green background but it doesn't. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css#adding-css-to-html

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by OmarNaguib** [comment]
Seems to work for me
Try asking in the discord community to see why it's not working with you.

![image](https://github.com/TheOdinProject/curriculum/assets/55961349/a9acc738-12de-4c3b-bf9e-35b98774f1b3)

If it's indeed an issue with the exercise, you should make an issue in the css-exercises repo
