### ISSUE TITLE
Setting up Git: <Short description of your suggestion>

### ISSUE THREAD

**Issue by SilkyGator** [TheOdinProject/curriculum#26372]
### Describe your suggestion

Under "create an SSH key" I would suggest once again stating that if you use a private github email, that is the email you need to use to create the key! I did it wrong the first time, and while I was very easily able to see the problem and fix the issue, it may be easier for others to have it specified right there.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Mclilzee** [comment]
If you mean the `ssh-keygen -t ed25519 -C <youremail>` the -C flag stands for comment it can be anything, it can even be omitted entirely and the keygen comment will be replaced with your machine name. It is just for you to know who or where that key generated through that comment.

It is not related to your email.

**Comment by codyloyd** [comment]
closing this issue because #26373 is a clearer statement of the problem
