### ISSUE TITLE
css= exercises/ margin-and-padding#2

### ISSUE THREAD

**Issue by jstoltz2** [TheOdinProject/curriculum#26378]
### Describe your suggestion

in the README it becomes unclear what the full objective of the content is, subjects you want changes done too are beyond vague and make the exercises difficult to navigate. being more clear on the objective of the project and specific changes. without such necessities these projects end up looking unlike your example. previous exercises actually instruct to work on elements never fully covered on top of now being vague on what needs to be done. some parts go from hand holding to vague descriptions of what you want done the very next exercise. it doesn't facilitate learning giving a road map taking it away ripping it up and gluing whats left back together expecting it to make sense. this has been rather a problem with a few exercises. stay on the content of what is taught later lessons are for later lessons not to give sneak peaks and confuse people on the upcoming project. some of the lessons just feel disjointed or unable to explain properly. Introduce a new element to work on, explain it, give an exercise thats open and clear on objective. keep it relative to one subject at a time, you are overloading people and like i said fluffing up the source material leading to confusion on the project or visa versa and over expecting after under explaining. take this for example. You went from simple borders of one square than throw people into doing 3 different boxes all with different instructions. coming from a background of teaching this is the primary problem of your project and a large issue a that. You do not teach from doing one box to interacting with two boxes adding a few instructions and working your way up. it goes from super basic to complex giving no workup to it, it creates unnecessary frustration and learning barriers. The understanding of this concept is in some previous lessons so its importance id hope should be understood.
here is an example of what i mean by vauge. "The content section has 16px space on the top and bottom, and 8px on either side." space where space between what or near what? doesnt give even a hint if its supposed to be a margin you are looking for or a border or what. it doesnt say space between the eedge of card or content like the other requests. although ive been learning new things i feel like its half learned because of issues like these.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-block-and-inline

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

the lesson plan is really the only problem here again i had one assignment that forgot to even mention that the html file needed fixed with the CSS file. its blockages like these that can cause information to become skewed and hard to understand. Ive found myself looking at the css solution file due to the lackluster instructions in the README files. Id say this is even more of an issue with someone with absolutely no background is computers. Luckily i have quite the history in computer science and yet even i felt lost in what and why i was supposed to do something. its not that its hard it lacks proper context.

**Comment by codyloyd** [comment]
I'm having a hard time following everything you're trying to say here, so I'm having a hard time coming up with a reasonable response.

I _will_ say, that the instructions are intentionally vague. You're supposed to figure things out on your own, and/or research and google.  Check out previous lessons again if you need to, or ask questions in our discord server.

To respond to the specific critique you listed:
> The content section has 16px space on the top and bottom, and 8px on either side." space where space between what or near what? doesnt give even a hint if its supposed to be a margin you are looking for or a border or what.

I believe the image that is attached to that exercise provides the answer to your question: 
![CleanShot 2023-09-27 at 13 16 38@2x](https://github.com/TheOdinProject/curriculum/assets/18574792/18e38ace-df4c-4524-8cab-646bb87b8acb)

the reason we left it vague and didn't use specific terms like margin and padding is that we want YOU, the learner to think about and apply the knowledge you've gained.  You'll notice that the section you're referring to is not "instructions for completing the exercise" but "self check" as in, you can use that to check your work and make sure you've done everything you're supposed to do.

**Comment by jstoltz2** [comment]
To be fair visually I'm not going to currently identify what space is 16 or 13 or 20 pixel spaces. This is the beginning of css after all.. 

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 27, 2023 at 2:20 PM, Cody ***@***.***> wrote:   


I'm having a hard time following everything you're trying to say here, so I'm having a hard time coming up with a reasonable response.

I will say, that the instructions are intentionally vague. You're supposed to figure things out on your own, and/or research and google. Check out previous lessons again if you need to, or ask questions in our discord server.

To respond to the specific critique you listed:


The content section has 16px space on the top and bottom, and 8px on either side." space where space between what or near what? doesnt give even a hint if its supposed to be a margin you are looking for or a border or what.


I believe the image that is attached to that exercise provides the answer to your question:


the reason we left it vague and didn't use specific terms like margin and padding is that we want YOU, the learner to think about and apply the knowledge you've gained. You'll notice that the section you're referring to is not "instructions for completing the exercise" but "self check" as in, you can use that to check your work and make sure you've done everything you're supposed to do.

**Comment by jstoltz2** [comment]
I had a friend who's been in the industry for years takea look at my code. By his admission, while my stufftechnically works it doesn't look good and has tons ofnewbie mistakes and bad habits that a proper Comp Scicourse would've stamped out early. But in Odin you'rejust given a manual and a task. It's great for learning thewhat", but it neglects the "how/why" too much. They havesupplemental resources on almost every page, but seem towag their finger at spending much time on them.When they say Odin's enough to get a job, l've realizedwhat that means. It's enough to function in a hypotheticalidealized entry level dev job. An easy one, in anuncompetitive location, where you'd be feel lost anduncomfortable for the first 6-12 months. It's nowhere nearenough to slot in as a true junior at a realistic company. It'snowhere near enough to impress a hiring manager on itsown merits, no one is going to look at your final project inOdin and hire you off that.So after 15 months of doing Odin what I'm left with is theability to make sites and very little insight into how it reallyall works. I know next to nothing about CS concepts andstruggle immensely to solve even easy algorithm stylequestion. I'm wishing I just did a smattering of CS MOOCsinstead or something.
Sent from Yahoo Mail on Android
On Wed, Sep 27, 2023 at 2:20 PM, Cody ***@***.***> wrote:Closed #26378 as completed.

**Comment by jstoltz2** [comment]
This is a better example on what I was trying to say. The learning is disjointed sometimes you want a line of code in the solution that I've never learned in the same module. The first module does go over alot of terms used ( at least on the terminal) but when I look at the solutions there are css commands I didn't even know existed because they weren't mentioned ( unless at the very beginning) at that point the term has been lost and not fully memorized so not going over it again when you want it performed in the activity is very confusing. I'm literally left asking why this specific command over that one or why does this css element or Javascript element have to interact this specific way. This was a friend of mines quoted issues with what is offered here and they are much more elegant in wordplay than I. I get it this is your project but it's open source ready for suggestions to make the learning and webpage look and function better right? Maybe add those definitions and terms back into the module where we are going to practice it. An example css flex exercises ask a few things in css I didn't know existed because it wasn't sonthing that was gone over recently. If I had every day to come and learn maybe some things wouldn't feel so distant but people have busy lives. So I'd say it wouldn't hurt to add a bit more detail. These are the terms in the assignment at the end of the module this is what they do and why you should use them. Instead I'm taught a few like justify-content and align-items. But then asked in the below assignment on flex header and flex information I see in the solution tab terms the module didn't just go over. It feels disjointed. And it makes learning harder for some who may not have all the time in the world. I feel to make the project better for others some changes to the curriculum are necessary. And I'd love to contribute lesson structure to help some of these modules become easier to understand. And for someone who knows to add the why to some things that aren't explained why I do this or that. ( most modules do now but some are still missing and I'm found wondering if so early we are meant to copy/ use the solution folder to just understand the interaction and not to attempt to find the solution on our own. I mean that part is the most confusing for me. Usually assignments show what you learned. These seem to try to cement the learning through seeing visually what is happening but not trying to do it yourself. (Like I said before some instructions need to be specific and aren't in early modules how am I to be expected to know the space in the example 16 px when I'm told to just put a space between the words aka content/ element and the blank. I know how to add 16 pixel space with margin or padding ect. But only when I know of its the margin or padding. And visually so early I wouldn't know the margin is the part that's 16px its literally the first css exercises we are given so nobody would from experience so I don't know what the point of being vague was...

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 15, 2023 at 3:33 PM, L ***@***.***> wrote:   I had a friend who's been in the industry for years takea look at my code. By his admission, while my stufftechnically works it doesn't look good and has tons ofnewbie mistakes and bad habits that a proper Comp Scicourse would've stamped out early. But in Odin you'rejust given a manual and a task. It's great for learning thewhat", but it neglects the "how/why" too much. They havesupplemental resources on almost every page, but seem towag their finger at spending much time on them.When they say Odin's enough to get a job, l've realizedwhat that means. It's enough to function in a hypotheticalidealized entry level dev job. An easy one, in anuncompetitive location, where you'd be feel lost anduncomfortable for the first 6-12 months. It's nowhere nearenough to slot in as a true junior at a realistic company. It'snowhere near enough to impress a hiring manager on itsown merits, no one is going to look at your final project inOdin and hire you off that.So after 15 months of doing Odin what I'm left with is theability to make sites and very little insight into how it reallyall works. I know next to nothing about CS concepts andstruggle immensely to solve even easy algorithm stylequestion. I'm wishing I just did a smattering of CS MOOCsinstead or something.
Sent from Yahoo Mail on Android
On Wed, Sep 27, 2023 at 2:20 PM, Cody ***@***.***> wrote:Closed #26378 as completed.

**Comment by jstoltz2** [comment]
I'm currently working long hours and I'm trying to learn what I can. I'm struggling to pay bills and my wife needs medical insurance that's good. My life literally needs a good opportunity. It becomes beyond frustrating and painful to go through all this and wonder if I can even achieve that after this. I don't have money for college and I don't qualify for half of them my parents won't help and my credit sucks for loans. I'm left with little options. I desperately need to learn web development or somthing to get my life in a better place. My wife is autistic so she is limited in what she can do to help and It makes me want to take care of her even more. So having the learning experience I'm having has resulted in some extra stress amd frustration. I apologize if I came too forward or anything. But I've tried everything else I can. I make too much for assistance and too little to keep up on bills. I have almost no food and only a pc.. this is the only thing I have left I can try.. the preassure of it all is beyond astounding. So I apologize for any misgivings and the hellfest that was my unstructured thought process. I was just currently wondering if I'll starve to death first or if they'll come take the car before I die of hunger. I need to learn web development I need to support my wife and I'm at my wits end. I don't know what else I can do... 

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 15, 2023 at 3:33 PM, L ***@***.***> wrote:   I had a friend who's been in the industry for years takea look at my code. By his admission, while my stufftechnically works it doesn't look good and has tons ofnewbie mistakes and bad habits that a proper Comp Scicourse would've stamped out early. But in Odin you'rejust given a manual and a task. It's great for learning thewhat", but it neglects the "how/why" too much. They havesupplemental resources on almost every page, but seem towag their finger at spending much time on them.When they say Odin's enough to get a job, l've realizedwhat that means. It's enough to function in a hypotheticalidealized entry level dev job. An easy one, in anuncompetitive location, where you'd be feel lost anduncomfortable for the first 6-12 months. It's nowhere nearenough to slot in as a true junior at a realistic company. It'snowhere near enough to impress a hiring manager on itsown merits, no one is going to look at your final project inOdin and hire you off that.So after 15 months of doing Odin what I'm left with is theability to make sites and very little insight into how it reallyall works. I know next to nothing about CS concepts andstruggle immensely to solve even easy algorithm stylequestion. I'm wishing I just did a smattering of CS MOOCsinstead or something.
Sent from Yahoo Mail on Android
On Wed, Sep 27, 2023 at 2:20 PM, Cody ***@***.***> wrote:Closed #26378 as completed.

**Comment by xandora** [comment]
@jstoltz2 I have removed the information about your personal situation from the issue here. While I empathise with your situation, this isn't the right place for those kinds of discussions. Unfortunately, I'm not sure where you are from, or I would try and share some resources you could make use of to get you through your hard times.

As far as working on our curriculum is concerned, have you joined the Discord server? A link is available on top of every lesson page, marked as "Community". Asking questions in the Discord is where our community really shines. Being able to ask questions when you get stuck is a crucial part of the learning process, and the Discord server helps tremendously in that regard.
