### ISSUE TITLE
Foundations - Links and Images: Codepen was not transfered to offical account

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#26376]
### Describe your suggestion

The new codepen for the width and height section on images was not transferred to the official account, still linked to mine.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images#image-size-attributes

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

fabulousgk

**Comment by 01zulfi** [comment]
@TheOdinProject/foundations can someone with access to CodePen sort this out please

**Comment by codyloyd** [comment]
I will do this.  Might be a minute before I actually  get time to do it, but I can take care of it.

**Comment by fabulousgk** [comment]
@codyloyd just a small reminder.

**Comment by kamranzafar4343** [comment]
It looks like this is for only maintainers

**Comment by fabulousgk** [comment]
Bump to prevent bot close.

**Comment by fabulousgk** [comment]
@codyloyd mostly just to keep from being closed.

**Comment by zachmmeyer** [comment]
@fabulousgk Hey there, just letting you know this is still on our radar. Having difficulty logging in to Codepen. @TheOdinProject/maintainers for future reference.

**Comment by fabulousgk** [comment]
Thanks, I just bump it when the stale thing happens to keep it open, no biggy!

**Comment by zachmmeyer** [comment]
@fabulousgk Check this out: 
- https://github.com/TheOdinProject/curriculum/actions/runs/8226500463/workflow#L23
- https://github.com/actions/stale?tab=readme-ov-file#days-before-close
As things are right now issues and PRs will never close due to the stale bot.
We appreciate your diligence! You may rest now.

**Comment by fabulousgk** [comment]
oh..../embarrassed
