### ISSUE TITLE
Binary Search Trees: Advise students not to read the implementation section inside Geeks for Geeks BST link

### ISSUE THREAD

**Issue by radtradcath** [TheOdinProject/curriculum#26388]
### Describe your suggestion

At Binary Search Tree project, right at the start, there are two links for students to learn about the subject:

"Read [this article](https://www.geeksforgeeks.org/sorted-array-to-balanced-bst/) and watch [this video](https://youtu.be/VCTP81Ij-EM) to understand the basic algorithm used to build a balanced BST."

The first article contains useful information about the algorithm at the beginning. But after that, there's an implementation section that must not be read. Otherwise, students will know the answer beforehand. The inattentive reader could ruin the project for himself.

My suggestion is to address that the article must not be read past the point of the pseudocode to avoid the risk.

![image](https://github.com/TheOdinProject/curriculum/assets/138630339/3d7673a6-0d08-450e-9f12-c1bf09476b61)
Img1: the limit of the useful reading

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-binary-search-trees

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

.radtrad

**Comment by codyloyd** [comment]
I think it's fine, actually. Even learners that have seen those code examples still often have a hard time implementing it themselves.  Seeing the thing in code, and creating it yourself are quite different IMO.

If we have learners that are just copy/pasting the answer, then they're just hurting themselves.  We can't protect people from that.

So, while I appreciate your point here, I don't think we actually need to make a change in this instance.
