### ISSUE TITLE
Javascript Course: Add example testcases to Knight Travails

### ISSUE THREAD

**Issue by ApurvR20** [TheOdinProject/curriculum#26397]
### Describe your suggestion

In Knight Travails Project, there is no way to test if the code is correct or not. My suggestion is to either add 

1. A file of few testcases, and a file of all possible answers. Since each pair of start and end points can have many correct routes, ~10 testcases might be enough to check the code but not be too much of a burden on the contributor.

2. Some tests, like in the js-exercises, which would be much easier for the student, but much more burden on the contributor
 
3. A link to an algorithmic problems platform like Codeforces/Codechef/Leetcode etc. Since the problems in "A bit of CS" section are basically data structure/algorithm problems, linking the user to a similar enough problem could help them train their CS muscles as well as use the browser IDEs on these websites to easily test the solution. However the problem of training the user would arrive, and coursework for this section might need to be changed dramatically.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-knights-travails

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

gc_0019

### (Optional) Additional Comments

If the maintainers agree to go through addition #2, it will be some time before I am able to contribute. I haven't completed the testing section yet, and haven't written tests before. If urgent, someone more capable could go through with implementing the tests, given #2 is chosen.

**Comment by Baguirre03** [comment]
I dont think that we should necessarily include a tests file for them, but I do think some additional examples would be nice. I wasnt quite sure if my was actually working for a little because of the few examples there were (and I dont know the quickest path either lol!) 

Maybe we could link to someones project whom has a UI and just be like (hey if you want to make sure your path _is_ actually the quickest use this. 

Or just include two more (a little more complex) examples in 
```js
knightMoves([0,0],[1,2]) == [[0,0],[1,2]]
knightMoves([0,0],[3,3]) == [[0,0],[1,2],[3,3]]
knightMoves([3,3],[0,0]) == [[3,3],[1,2],[0,0]]
```

**Comment by ApurvR20** [comment]
> I do think some additional examples would be nice.

Yes, that could be helpful, with a few examples giving out multiple correct paths for a pair of endpoints. This can provide the learner with concrete data to compare with.

> Maybe we could link to someones project whom has a UI and just be like

This has the same problem, as most liked submissions with UI, showed a single correct path. By manually calculating, I was able to find an equally correct path which is different from UI. 
UI might also cause learners to believe they need to build one of their own, when it is not asked in the requirements.

Odin Project curriculum has generally been comprehensive in providing information and clearing doubts of learners. I suggest it should follow that approach and implement one of the options.

**Comment by Baguirre03** [comment]
Im thinking this:
>
You can think of the board as having 2-dimensional coordinates. Your function would therefore look like:
```js 
knightMoves([0,0],[1,2]) == [[0,0],[1,2]]
```
Note: _Sometimes there is more than one fastest path_, an example of this is shown below. Either answer will work.
`knightMoves([0,0],[3,3]) == [[0,0],[2,1],[3,3]]` or `knightMoves([0,0],[3,3]) == [[0,0],[1,2],[3,3]]`
`knightMoves([3,3],[0,0]) == [[3,3],[2,1],[0,0]]` or `knightMoves([3,3],[0,0]) == [[3,3],[1,2],[0,0]]`

**Comment by ApurvR20** [comment]
I like this. This note removes any doubt in the mind of the learner. I would still recommend two more examples, so the learner can use them to test their code. Testing every combination of endpoints seems overkill.

**Comment by ManonLef** [comment]
I think this is a great idea. I'd also like to see the longest path possible added from [0,0] to [7,7] because I personally ran into a recursion issue that made it seem I had a working solution, except it didn't for paths over 5 steps :)

**Comment by codyloyd** [comment]
alright @ApurvR20 you can go ahead and work on this

**Comment by ApurvR20** [comment]
Sorry for the delay, I was in bad health.
