### ISSUE TITLE
React: Reword TS mention to shift focus towards a future consideration

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26405]
### Describe your suggestion

In the PropTypes lesson, when it mentions TS it says:
> We don’t cover it in our curriculum yet, but it’s worth learning about it if you’d like more safety while writing your code.

In my honest opinion, I feel this could be at a bare minimum reworded to something like

> We don’t cover it in our curriculum, but in the future, it may be worth learning about it if you’d like more type safety while writing your code.

This may or may not be coupled with the next paragraph being adjusted slightly to match this sort of tone e.g.

> Learning TypeScript can be a lot of overhead when you’re already learning React and the best way to prepare for this is to continue developing your JavaScript foundation. [Even the TypeScript team advises this!](https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html#learning-javascript-and-typescript) In the future, if you do go in the direction of learning TypeScript, our recommendation would be picking up a previous project and refactoring the components one by one to TypeScript. Learn by doing!

I feel this retains the intention of mentioning what TS is, but shifts any interpretations of it away from "this may be something to learn now" (where there will be no curriculum support) or "is the lesson saying proptypes or TS is better?", and more clearly to "this is what it is, in case you were curious before. Anyway, back to the lesson and curriculum".

### Path

NodeJS and Ruby (React)

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-type-checking-with-proptypes and  https://www.theodinproject.com/lessons/react-new-type-checking-with-proptypes

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by MaoShizhong** [comment]
@eyaldavidszt (guzel on discord) mentioned as well that [the first assignment link](https://legacy.reactjs.org/docs/typechecking-with-proptypes.html) mentions to use TS instead of proptypes (and the resource also goes through the old built-in proptypes instead of the separate library).
They suggested adding a clarification on this in regards to using it for the purposes of learning instead of TS (in which the suggestion is of course more for real-world usage).

If this issue is agreed on and work assigned, I'm more than happy for Guzel to be assigned it instead of me if they wished to.

**Comment by codyloyd** [comment]
I like your proposal here and agree that we should clean that up a little bit.

I am not too familiar with the recent React content, so we should probably get a thumbs-up from someone on that team @TheOdinProject/react Anyone have any opinions here?

**Comment by CouchofTomato** [comment]
@TheOdinProject/react Can someone pick this up please.

**Comment by MaoShizhong** [comment]
Gentle bump ^^'

**Comment by CouchofTomato** [comment]
I've requested someone on the react team to pick this up.

**Comment by 01zulfi** [comment]
@MaoShizhong Sounds good to me, please create a pull request.

**Comment by JoshDevHub** [comment]
Closed by #26958
