### ISSUE TITLE
Potential error in description of 'href' element.

### ISSUE THREAD

**Issue by Eric-Windsor** [TheOdinProject/curriculum#26400]
### Describe your suggestion

Where it mentions the 'href' attribute of the anchor elements in (https://www.theodinproject.com/lessons/foundations-links-and-images) it says href is 'hyperlink reference' even though the assignment video and other sources say 'hypertext reference'. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

thebullway

### (Optional) Additional Comments

I'd fix it myself but when I don't know how to edit it, and I also don't know what forking the GitHub means. Sorry.

**Comment by ManonLef** [comment]
Good catch! I will open it up for contributors since you've indicated you don't want to work on it yourself

**Comment by scottwright-dev** [comment]
I'd like to fix this one please.

**Comment by ManonLef** [comment]
Thanks @scottwright-dev you've been assigned!

**Comment by faizan-20** [comment]
is the issue still open? Can I work on this?

**Comment by ManonLef** [comment]
@faizan-20 I have assigned the issue opener right above your message :) It's not open anymore
