### ISSUE TITLE
Git Basics: <Short description of your suggestion>

### ISSUE THREAD

**Issue by surajkumarr** [TheOdinProject/curriculum#26402]
### Describe your suggestion

To access the github SSH key need to be setup and updated in git site

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

please add instruction on setting up ssh public key  for Git

**Comment by ManonLef** [comment]
Could you please explain what you're missing from the instructions? In the [previous lessons the instructions are given for setting up git](https://www.theodinproject.com/lessons/foundations-setting-up-git)

**Comment by Boltjazz** [comment]
you can also work around by cloning the https url

**Comment by ManonLef** [comment]
sure @Boltjazz but I don't believe any instructions are missing for our lessons which this user seems to imply.

**Comment by Boltjazz** [comment]
@ManonLef can we ask him a SS or an img showcasing the issue?

**Comment by ManonLef** [comment]
@Boltjazz Respectfully, I prefer we wait for a response. Since are not really meant as help threads. [Our Discord](https://discord.com/invite/fbFCkYabZB) would be a far better place for getting issues :) 

They stated the following for opening this issue:
> please add instruction on setting up ssh public key for Git

So realistically we can assume they think we don't have said instructions. But we do, so I think they must have missed it.

**Comment by surajkumarr** [comment]
> @Boltjazz Respectfully, I prefer we wait for a response. Since issues are not really meant as help threads. [Our Discord](https://discord.com/invite/fbFCkYabZB) would be a far better place for getting help while running into issues with setting up :)
> 
> They stated the following for opening this issue:
> 
> > please add instruction on setting up ssh public key for Git
> 
> So realistically we can assume they think we don't have said instructions. But we do, so I think they must have missed it.

Sorry may bad. I accessed the link directly through google search and missed the first page / session. It is clearly mentioned how to setup ssh keys. Thank you for the response

**Comment by ManonLef** [comment]
No problem! Thanks for the follow up 😊
