### ISSUE TITLE
Refs And Memoization: <Short description of your suggestion>

### ISSUE THREAD

**Issue by jasonHYLam** [TheOdinProject/curriculum#26419]
### Describe your suggestion

There's a typo in the title: it should be "Memorization", not "Memoization". 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-refs-and-memoization

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by ManonLef** [comment]
You probably found out since you closed this. It is actually called `memoization`
:)
