### ISSUE TITLE
Foundations (How Does the Web Work?): Last question should be rephrased

### ISSUE THREAD

**Issue by pulgamecanica** [TheOdinProject/curriculum#26410]
## ❓ I find the Assignment's last question to be out of topic.

***

> "In your own words, explain what happens when you run a search on google.com."

***

Because there is not enough information to answer the question fully.
The question is very open from my perspective.
Explaining what "happens" when you run a search on google.com could be interpreted in many ways.
One could think that we are expected to explain how Google receives the client query and finds the most adequate results, then organizing the results and responding back with a list of possible options which correspond to the query. This is in a way explaining how the search engine is able to prompt an adequate result.

It became clear to me after some thinking that I should be answering the question in terms to what I read in this module.
Explaining how my web browser will send the request after finding google Domain Name IP, then it goes through the ISP, to a Router, until it reaches google server and gets back to me, but never the less I think the question should be:

***

> "In your own words, explain the steps your web browser goes when you run a search on google.com." 🆕 

***

What do you think? 🗣️ 

***

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-how-does-the-web-work

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

pulgamecanica

**Comment by ManonLef** [comment]
I've assigned you so you can file a PR, since you indicated you'd like to work on it. We can discuss the proposal you have there. If you feel it could be more clear, then it probably could be enhanced either way. Thanks for doing this!

**Comment by pulgamecanica** [comment]
Thanks for the opportunity! I'll work on that PR! 😄
