### ISSUE TITLE
React: Emphasize layout routes and moving router outside the react tree

### ISSUE THREAD

**Issue by fcasibu** [TheOdinProject/curriculum#26427]
### Describe your suggestion

I would suggest to emphasize the use of layout routes and not defining the router inside a component with react-router-dom.

**Issue 1:**
I've commonly see people struggling with passing data to different routes, because of what they've followed in the lesson. Also, the common advice is to use React's Context API, but it is not yet taught at this point
```js
const router = createBrowserRouter([
  {
    path: "/",
    element: <App />,
    errorElement: <ErrorPage />,
  },
  {
    path: "profile/",
    element: <Profile />,
  },
]);
```
The solution does not prevent the use of `context` but this is a necessary evil since the API is quite simple to use with like two lines of code and not a full blown Context API that requires other kinds of setup. 
ref: [Outlet Context](https://reactrouter.com/en/main/hooks/use-outlet-context)

And this pattern is encouraged in their examples repository as well for data routers. Even if we don't completely mention outlet context, it's still a great pattern to be used

Solution:
The use of a layout route:
```js
const router = createBrowserRouter([
  {
    path: "/",
    element: <Layout />, // can utilize outlet context to pass down props and act as the common ancestor
    ...
    children: [
      {
        index: true,
        element: <App />,
        ...
      },
      {
        path: "/profile",
        element: <Profile />,
        ...
      }
    ]
  }
]);
```
**Issue 2:**
There are scenarios where I've seen people add the router *inside* a component with state in it. The react-router-dom docs emphasizes that the router should only have **one instance** [The note here](https://reactrouter.com/en/main/routers/create-browser-router#createbrowserrouter)

The current one in the lesson makes use of a component and for the most part it is completely fine because there are no states that makes the component re-render, but people will make use of this and try to define state inside this component. 

This applies to issue 1 where state is added inside the component to pass it down to different route components as props

```js
const Router = () => {
  const router = createBrowserRouter([
    {
      path: "/",
      element: <App />,
      errorElement: <ErrorPage />,
    },
    {
      path: "profile/:name",
      element: <Profile />,
    },
  ]);

  return <RouterProvider router={router} />;
};
```

Solution:
Emphasize this particular note that the docs have and place it before the component above. Either make sure that state shouldn't be added inside the component OR just keep the router outside the component because we've created a separate file and that already makes it quite modular.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-react-router

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

nevz

**Comment by ManonLef** [comment]
Could someone from @TheOdinProject/react look at this please :)

**Comment by fcasibu** [comment]
To be done by https://github.com/TheOdinProject/curriculum/issues/26502 if confirmed
