### ISSUE TITLE
Introduction: What is NodeJS?: Restructure lesson layout to fit layout style guide

### ISSUE THREAD

**Issue by adriananin** [TheOdinProject/curriculum#26422]
### Describe your suggestion

The structure of this lesson does not follow the structure of the [layout guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lesson-layout) for lessons. The Additional resources section comes before the Knowledge check section which is inconsistent with the usual layout.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-what-is-nodejs

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

adrianea

**Comment by ManonLef** [comment]
Thanks, I'll assign you.
