### ISSUE TITLE
Join the Odin Community: <Short description of your suggestion>

### ISSUE THREAD

**Issue by AFLcaan** [TheOdinProject/curriculum#26423]
### Describe your suggestion

Logged in on the discord server and to complete the steps to allow me to talk, I have to verify my phone number.
I have tried many yet the sms message is not coming through.
Now when I try, it says "unable to send sms"

What might be the problem?

### Path

Foundations

### Lesson Url

https://discord.gg/fbFCkYabZB

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

I can't get the discord server to send an sms message to my phone. It is not enabling me to talk

**Comment by ManonLef** [comment]
This question would be better directed to [Discord, you can find their help page on verification here](https://support.discord.com/hc/en-us/articles/6181726888215-Verification-Required-FAQ). Verification is not handled by us, it's just a server setting we turned on as a safety measure.
