### ISSUE TITLE
Foundations: "Reference vs Value" concept could be given more attention in JS fundamental 5

### ISSUE THREAD

**Issue by satvator** [TheOdinProject/curriculum#26433]
### Describe your suggestion

I would like to attach the link to the "Web Dev Simplified" YT video for the same in the additional resources.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-5

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

Also, there are a couple of concepts like "nodes vs. element" and "global addEvent listener" which are not so hard to grab and have been described explicitly in one of  "Web dev simplified" JS tutorials. I would highly recommend it added to the additional resources in the "DOM manipulation and events" chapter.

**Comment by ManonLef** [comment]
Thanks for the suggestion. Could you please give more context?

- what exactly is covered in the video (which preferably should be linked in your issue)
- why should it be in this lesson?
- what does it cover that is also covered in the lesson and what isn't covered in the lesson?

Thanks in advance for the info

**Comment by satvator** [comment]
[image: image.png]
this snippet is from one of the links attached in this chapter i.e.
"Foundations JS part 5", and I am finding it hard to comprehend since (as
far as I know) there was no such mention of reference or value explicitly
anywhere before this chapter. Now, since this chapter is all about objects
and arrays, I think it would be a great time to understand this topic.
So, the video that I am suggesting, contains a few examples in the very
same context which I found really helpful as it also helped me understand
the lines that are there in the above snippet.
Here's the link to the video, in case you want to have a look:
https://youtu.be/-hBJz2PPIVE?si=kTBehBNSPlUhZThb

I have also suggested two additions for the previous chapter i.e. "DOM
manipulation and events".
Firstly, there's nowhere mention of the concept
'GlobalAddEventListener'..so here's the link to that video which has
provided info for the same and also will strengthen the already covered
concept of 'addEventListener':
https://youtu.be/XF1_MlZ5l6M?si=TTHrqgvkkhkmZqPw
Secondly, I watched this video of the same Youtuber where he explained the
difference between Nodes and Elements quite explicitly and I found it
extremely intriguing and helpful, so I would suggest that too:
https://youtu.be/rhvec8cXLlo?si=9hAV4kDb8H3OIX-G

**Comment by CouchofTomato** [comment]
@ManonLef 

Do you still want to respond to this or are you happy for someone else to take it on?

**Comment by ManonLef** [comment]
I'm so sorry @CouchofTomato , I missed the follow up on this. I'd love for someone else from the @TheOdinProject/foundations to have a look and take it on. 

My apologies for the delay @satvator, I'm a bit too short on time to go through the proposed content and hold it to our current content.

**Comment by satvator** [comment]
No problem, I understand.

**Comment by wise-king-sullyman** [comment]
Hello @satvator, thanks for making this issue.

Covering pass by reference vs pass by value in fundamentals 5 does seem like a good idea, but we would prefer to do so with either our own content or through an article linked as an assignment rather than a video.

Would you be interested in doing that?

**Comment by satvator** [comment]
Hey there!!
Yes, I would love to contribute in whatever way I can. Although, I'm not
really sure how you want me to do it if not by sharing video links.

**Comment by thatblindgeye** [comment]
@satvator the more straight forward approach would be researching written articles that cover the topic, and see which ones felt the most helpful. You could also make an attempt at adding a new section of content in the lesson, but that may require more of an understanding of the concept and not as straight forward as providing an existing resource.

**Comment by thatblindgeye** [comment]
Going to close this out for now. @satvator if you'd still like to work on this feel free to ping in this issue. In the mean time this topic could be one that users could research on their own.
