### ISSUE TITLE
Foundations/Prerequisites: Update lists per layout style guide

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26437]
Lists should be updated in the following ways to align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md):

- Any unordered list items that are created with an asterisk `*` are replaced with a hyphen `-` instead. For example, `* A list item` should be updated to `- A list item`
- The list item content is updated so it only has a single space before it. For example, `1.   A list item` has 3 spaces before the list item content ("A list item"), and should be updated to `1. A list item`
- Appropriate punctuation is added at the end of each list item in the "Lesson overview", "Assignment", "Knowledge check", and "Additional resources" sections
  - Follow the [Google style guide ](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists) to determine when to add punctuation
- Any additional updates mentioned for specific lessons

### Guidance:

- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` keyword. 

### Lessons to update

- [x] @scottwright-dev [Computer basics](https://www.theodinproject.com/lessons/foundations-computer-basics)
- [x] @rohan843  [How does the web work?](https://www.theodinproject.com/lessons/foundations-how-does-the-web-work)
- [x] @ht-l1  [Installation overview](https://www.theodinproject.com/lessons/foundations-installation-overview)
- [x] @Sushant9473  [Installations](https://www.theodinproject.com/lessons/foundations-installations)
- [x] @ScaxCodes  [Text editors](https://www.theodinproject.com/lessons/foundations-text-editors)
- [x] @VMadhuranga  [Command line basics](https://www.theodinproject.com/lessons/foundations-command-line-basics)
- [x] @matthewsanner  [Setting up git](https://www.theodinproject.com/lessons/foundations-setting-up-git)

**Comment by scottwright-dev** [comment]
I'm happy to do these.

**Comment by rohan843** [comment]
I'd be happy to work on one of the lessons.

**Comment by ht-l1** [comment]
hope to take one if possible :)

**Comment by Sushant9473** [comment]
I'd be happy to work on one of these lessons.

**Comment by ScaxCodes** [comment]
I would also love to help out here.

**Comment by VMadhuranga** [comment]
I would also like to help if possible

**Comment by matthewsanner** [comment]
Looks like there's seven of these, I would happily take the last one!

**Comment by thatblindgeye** [comment]
Wow quick sign ups, thanks y'all! @Sushant9473 @rohan843 @ht-l1 @scottwright-dev @matthewsanner @VMadhuranga @ScaxCodes I've assigned you each a lesson in the original comment

**Comment by ryanleslie1997** [comment]
Hey, I'm happy to help out too :)

**Comment by RushilJalal** [comment]
Can I help too?

**Comment by lewisthagichu** [comment]
I would like to work on this.

**Comment by RitaDee** [comment]
Can I work on this?

**Comment by ManonLef** [comment]
@ryanleslie1997 @RushilJalal @lewisthagichu @RitaDee 
all spots are already filled. Thanks for being willing to help though!

**Comment by RitaDee** [comment]
> @ryanleslie1997 @RushilJalal @lewisthagichu @RitaDee all spots are already filled. Thanks for being willing to help though!

Thank you.

**Comment by matthewsanner** [comment]
Hey there, are there any issues with my pull request?

**Comment by ManonLef** [comment]
@matthewsanner I had a look and left a comment :)

**Comment by odilsonjs** [comment]
I would be a happy to work on this issue
