### ISSUE TITLE
React: Add an article about act()

### ISSUE THREAD

**Issue by Haswell-s** [TheOdinProject/curriculum#26435]
### Describe your suggestion

I'm still trying to wrap my head around act. [This](https://javascript.plainenglish.io/you-probably-dont-need-act-in-your-react-tests-2a0bcd2ad65c) article talks about i'ts modern use cases (or not-to-use cases)
I would like to add to additionals

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-mocking-callbacks-and-components

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by i5x64BIT** [comment]
[This one](https://codilime.com/blog/why-should-you-be-grateful-for-act-warnings-in-react-tests/) is also great, it talks about act in general, let's discuss them both :)

**Comment by ManonLef** [comment]
@TheOdinProject/react could someone have a look at this suggestion?

**Comment by i5x64BIT** [comment]
@ManonLef still no reply...

**Comment by 01zulfi** [comment]
The suggested resource looks good. @i5x64BIT I've assigned you the issue, please make a PR

**Comment by CouchofTomato** [comment]
@i5x64BIT Are you still interested in working on this?

**Comment by 01zulfi** [comment]
I'm opening this up for contributions. Please comment below if you want to be assigned.

**Comment by thejon07** [comment]
iam interested

**Comment by 01zulfi** [comment]
@thejon07 assigned.

**Comment by CouchofTomato** [comment]
@thejon07 any update?

**Comment by thejon07** [comment]
First of all, I apologize for the delayed response. I've been occupied with another project and couldn't contribute to this one. However, I'll provide you with an update by tomorrow. :)

**Comment by thejon07** [comment]
how can i start development server

**Comment by i5x64BIT** [comment]
> how can i start development server

There isn't one, it's only an md file.
You can use the [markdown preview](https://www.youtube.com/watch?v=4sJSaQI5RnU) in vscode before commiting :)

**Comment by i5x64BIT** [comment]
@01zulfi assign me

**Comment by BryanF1nes** [comment]
What is the status on this issue?

I see @i5x64BIT would like to be assigned. If they are still interested, if not I'd be happy to take a stab at it.

**Comment by CouchofTomato** [comment]
@thejon07 Are you still working on this?

**Comment by i5x64BIT** [comment]
> What is the status on this issue?
> 
> I see @i5x64BIT would like to be assigned. If they are still interested, if not I'd be happy to take a stab at it.

Sorry I wan't on gh for a while, I'm on it

**Comment by Rllopez0410** [comment]
@CouchofTomato, if @thejon07 is a bit busy at the moment i would love to work on this issue.

**Comment by CouchofTomato** [comment]
@Rllopez0410 I've assigned you.

**Comment by Rllopez0410** [comment]
@CouchofTomato thank you.

**Comment by Rllopez0410** [comment]
Will be adding an article ASAP. had to take some time off to put a bit more of my focus at work.
