### ISSUE TITLE
Rails: Update Assignment to align with Rails docs update.

### ISSUE THREAD

**Issue by Leo-U** [TheOdinProject/curriculum#26446]
### Describe your suggestion

An additional section has been added to the Parameters section of [these docs](https://guides.rubyonrails.org/action_controller_overview.html#composite-key-parameters).

[Here's](https://web.archive.org/web/20230921025856/https://guides.rubyonrails.org/action_controller_overview.html#parameters) what it used to look like. [Here's](https://guides.rubyonrails.org/action_controller_overview.html#default-url-options) what it looks like now.

As a result, the TOP Assignment is now outdated, since what was previously section 4.5 is now 4.6, because the added section was inserted between the assigned sections 1 thru 4.5.3.

The added section, 4.4 Composite Key Parameters, is pretty short, so one solution would be to make the assignment say
> sections 1 - 4.6.3 and 5.2

Or, it could be left out, so the solution would be to make the assignment say
> sections 1 - 4.4, 4.6 - 4.6.3, and 5.2

I have double checked the differences in the text using an online text diff checker, and at least in the context of the assigned reading for this lesson, the aforementioned changes are the only ones that were made -- aside from some minor phrasing changings in the introductory paragraph of 4.2.

I do not want to work on this issue.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-controllers#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
could someone from the @TheOdinProject/ruby team have a look please :) ?

**Comment by rlmoser99** [comment]
I think the best solution would be to update the lesson with the first suggestion.

> sections 1 - 4.6.3 and 5.2

**Comment by scottwright-dev** [comment]
I am happy to work on this.

**Comment by rlmoser99** [comment]
Thanks, @scottwright-dev. This issue has been assigned to you.

**Comment by scottwright-dev** [comment]
Thank you @rlmoser99.
