### ISSUE TITLE
Transitions: Codepen example does not match below description

### ISSUE THREAD

**Issue by mononoken** [TheOdinProject/curriculum#26440]
### Problem
Currently, the second paragraph below the first Codepen example states:
```
This was achieved using the `transition` property, which is actually a shorthand property for `transition-property`, `transition-duration`, `transition-timing-function` and `transition-delay`.
```
However, the Codepen example uses the 4 longhand properties, not `transition`.

### Solutions
We should either:
1. Change the Codepen to use the shorthand `transition` property AND reword the shorthand description below so it makes sense with the context.
2. Or change the second paragraph below the Codepen example to just state the example uses the longhand and that a shorthand exists. Something like this:
```
This was achieved using four properties, `transition-property`, `transition-duration`, `transition-timing-function` and `transition-delay`, but the shorthand `transition` property could substitute these for the same effect.
```

I suggest the second solution as it is less work, and I think seeing the longhand properties as the first intro is easier to follow along for learners before reading any descriptors.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/advanced-html-and-css-transitions

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mononoken

**Comment by ManonLef** [comment]
@TheOdinProject/html-css could someone have a look?

**Comment by vrun1208** [comment]
Hi @ManonLef, Hope you are well!
If no one is working on this issue, You can assign me.🚀
The second paragraph which @mononoken mentioned is actually confusing and also in snippet `transition` property is not used.

**Comment by Swapnilnaique** [comment]
I would like to work on this issue

**Comment by abinash-boruah23** [comment]
Hi! I'd like to fix this issue.

**Comment by Shauryagulati** [comment]
I'd like to work on this issue if no one's working on it.

**Comment by ManonLef** [comment]
Thanks for all the offers everyone, but I don't think you can change TOP's codepens :). @codyloyd can you confirm if anything here needs updating, it has to be done by a team member with the appropriate rights?

**Comment by wise-king-sullyman** [comment]
Fixed.
