### ISSUE TITLE
JavaScript: simple syntax error in the factory function example

### ISSUE THREAD

**Issue by Contrigra** [TheOdinProject/curriculum#26457]
### Describe your suggestion

In this example (https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#private-variables-and-functions): 
```
function createUser (name) {
  const discordName = "@" + name;

  let reputation = 0;
  const getReputation = () => reputation;
  const giveReputation = () => reputation++;

  return { name, discordName, getReputation, giveReputation };
}

const josh = createUser("josh");
josh.giveReputation();
josh.giveReputation();

console.log({
  name: josh.discordName,
  reputation: josh.getReputation
});
// logs { name: "josh", reputation: 2 }
```

the `console.log` part is a bit wrong: 

```
console.log({
  name: josh.discordName,
  reputation: josh.getReputation
});
// logs { name: "josh", reputation: 2 }
```

It will log ```{ name: '@josh', reputation: [Function: getReputation] }```

So either the comment should be rewritten to reflect the correct behaviour of `console.log`  part, or change everything to reflect the original intention. As an example it could be like this: 

``` 
console.log({
  discordName: josh.discordName,
  reputation: josh.getReputation()
});
// logs { discordName: "@josh", reputation: 2 }
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#private-variables-and-functions

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

contrigra

### (Optional) Additional Comments

Don't beat me, first time opened an issue like this ^^

**Comment by Lofty-Brambles** [comment]
```js
console.log({
  discordName: josh.discordName,
  reputation: josh.getReputation()
});
// logs { discordName: "@josh", reputation: 2 }
```
- that does indeed look like the intended example to me :D

**Comment by ManonLef** [comment]
Thank you @Contrigra 
I've assigned you :)
