### ISSUE TITLE
Alignment: Flexbox trash course has information about adding responsiveness

### ISSUE THREAD

**Issue by ryanleslie1997** [TheOdinProject/curriculum#26452]
### Describe your suggestion

Hi I just wanted to make a suggestion for the flexbox crash course (in the additional resources) as it has information about responsiveness/media queries which hasn't been covered yet. Maybe it would be good to include a message beside the link to only watch until a certain point.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-alignment#additional-resources

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

rleslie97

**Comment by ManonLef** [comment]
Could you direct me to the specific section from that video you have in mind? Since this is not an assignment, but a non-required additional resource, we can usually expect more information being introduced beyond what's covered in the lesson.

**Comment by ryanleslie1997** [comment]
Yeah no problem. It's at 45:13. I think it only includes one of the media queries. Also that's fair enough about it being an additional resource. So it's probably not a big deal at all.

**Comment by ManonLef** [comment]
Thanks for the update @ryanleslie1997
It looks like it touches upon it, but it's not a deep dive and major part of the video. It's very short even. 

I vote for leaving it as is for now. Thanks for the suggestion however, we do appreciate it!
