### ISSUE TITLE
Installing Node.js: Missing how to actually install nvm 

### ISSUE THREAD

**Issue by Zalamit13** [TheOdinProject/curriculum#26456]
### Describe your suggestion

After the introduction, the lesson starts with two options for linux and macos, and then it directly goes to "Now that we have nvm installed, we can install Node." and starts by the installation guide for Node, assuming that it already stated how to install nvm. 
I had to look up in other sites on how to install nvm BEFORE continuing the lesson. 
I hope this gets fixed

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installing-node-js

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

The first lessons of HTML and CSS were amazing, to say the least, i understood so many things that i have glossed over before while studying HTML/CSS in college.
However, it was a bit rough with JS. I know it is a broad programming language and much more complicated (to teach and to learn) than HTML/CSS, but i would've loved it to be directly on the ODIN website instead of linking a bunch of articles here and there, in multiple lessons.

**Comment by vrun1208** [comment]
Hi @Zalamit13, Actually the options `linux` and `macos` are dropdowns and inside them you can find all the steps.

**Comment by Zalamit13** [comment]
Hi @vrun1208, i have Windows. I found out that nvm doesn't have support on Windows though.

**Comment by vrun1208** [comment]
Yes, You're right! @Zalamit13 And for windows users no reference is given which makes it hard to understand. Okay now I got the issue!

**Comment by ManonLef** [comment]
We don't support Windows and hence there are (and also will not be) any instructions for it. Glad you enjoyed the chapters! For making sure you can follow along with the instructions, I do recommend looking at getting a supported OS setup. A VM is the easiest and less intrusive one to start with.

**Comment by Zalamit13** [comment]
@ManonLef That's unfortunate, maybe a small statement about the supported OS(s) would've been helpful, to avoid any confusion.

**Comment by ManonLef** [comment]
@Zalamit13 The supported OSes have a [full chapter dedicated to them](https://www.theodinproject.com/lessons/foundations-installation-overview) already.

**Comment by Zalamit13** [comment]
Ah ok thanks @ManonLef, my bad.
