### ISSUE TITLE
Javascript/Factory_Functions_Lesson: Fix an indentation issue.

### ISSUE THREAD

**Issue by Lofty-Brambles** [TheOdinProject/curriculum#26450]
### Describe your suggestion

Under assignments, in the first point, the bulleted list does not render as a list. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

_lofty.dev

**Comment by ManonLef** [comment]
thank you, I'll open it up for contribution!

**Comment by ryanleslie1997** [comment]
Hey, I'm happy to work on this.

**Comment by ManonLef** [comment]
I'll assign it to you @ryanleslie1997 
thank you :)

**Comment by ryanleslie1997** [comment]
@ManonLef Hi I was just looking for some clarification on this and a hint on how to get started (It's the first issue I've worked on). Are the two linked sections supposed to be shown as bullet points?

![image](https://github.com/TheOdinProject/curriculum/assets/49491916/005f0cbd-4bf1-4db4-a109-5be3bbf65b6d)

**Comment by abinash-boruah23** [comment]
hi! do you want the list to be rendered as an unordered list because it does render as a list, but as an ordered one
![Uploading Screenshot 2023-10-14 at 7.58.40 AM.png…]()

**Comment by abinash-boruah23** [comment]
Hi! Do you want the links  "The article on scope" & "The article on closures" as two separate list items?

**Comment by ManonLef** [comment]
@ryanleslie1997 yes please

@abinash-boruah23 yes, and Ryan is working on this :)

**Comment by ryanleslie1997** [comment]
Hi, I'm unsure how to do this.

**Comment by ManonLef** [comment]
@ryanleslie1997 our [contribution guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) section on lists might help?

**Comment by abinash-boruah23** [comment]
This seems like a fairly simple issue. I can maybe try to fix it if @ryanleslie1997 doesn't mind.

**Comment by ryanleslie1997** [comment]
I dont mind. Thank you Abinash.



Sent from my Galaxy



-------- Original message --------
From: Abinash Boruah ***@***.***>
Date: 15/10/2023 05:48 (GMT+00:00)
To: TheOdinProject/curriculum ***@***.***>
Cc: Ryan Leslie ***@***.***>, Mention ***@***.***>
Subject: Re: [TheOdinProject/curriculum] Javascript/Factory_Functions_Lesson: Fix an indentation issue. (Issue #26450)


This seems like a fairly simple issue. I can maybe try to fix it if @ryanleslie1997<https://github.com/ryanleslie1997> doesn't mind.

**Comment by JatinPhogat** [comment]
Hey @ManonLef , i would like to work on this if anyone haven't completed it yet

**Comment by ManonLef** [comment]
@ryanleslie1997 I'm sorry I've missed this. It's not a big issue for me to guide you on how to do it. So I'll let you decide if you wish some guidance or rather hand it over to someone else?

**Comment by DevAranCarter** [comment]
Hi @ManonLef, is anyone currently working on this? Would love to contribute if not.

**Comment by ryanleslie1997** [comment]
Hi, I'm happy for this to be handed to someone else.
________________________________

**Comment by Torenrob** [comment]
Hi, I was looking to volunteer for this issue but looks like the issue has been resolved. May want to close this one out.

**Comment by JoshDevHub** [comment]
Thanks for letting us know @Torenrob :raised_hands:
