### ISSUE TITLE
Foundations: Correcting VSCode keyboard shortcut info - Linux

### ISSUE THREAD

**Issue by aestpunk4** [TheOdinProject/curriculum#26460]
### Describe your suggestion

Hi!

At the section [VSCode keyboard shortcut ](https://www.theodinproject.com/lessons/foundations-working-with-text#:~:text=VSCode%20keyboard%20shortcut) the shortcut for Linux is not right; it should be changed to Ctrl + Shift + /.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-working-with-text#:~:text=VSCode%20keyboard%20shortcut

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

aestpunk4

**Comment by ManonLef** [comment]
Thanks for your suggestion. That is not what the [VSCode document](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf) tells us. Just to be sure and gather more info: Could you tell me which bistro you're on?

**Comment by aestpunk4** [comment]
Sorry, I just realized that using a hungarian keyboard confused me a little bit. I close the (non-existent) issue.
