### ISSUE TITLE
Active Record Queries: Section numbers incorrect

### ISSUE THREAD

**Issue by bradenr402** [TheOdinProject/curriculum#26465]
### Describe your suggestion

Several of the section numbers for the Rails Guide on Active Record Querying in the assignment section are incorrect. Here is a list of the errors:
- Existence of Objects is section 20, not section 21
- Calculations is section 21, not section 22
- Joining Tables is section 12, not section 13
- Find or Build a New Object is section 18, not section 19
- Scopes is section 14, not section 15
- Finding by SQL is section 19, not section 20

Basically, the section numbers are offset by 1. (I assume a section was either removed or combined with another section after the creation of the lesson.)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-active-record-queries#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by lewisthagichu** [comment]
I would like to work on this issue. Assign it to me, please.

**Comment by lewisthagichu** [comment]
Thanks.

**Comment by lewisthagichu** [comment]
Hey there, any issues with my pull request?

**Comment by KevinMulhern** [comment]
A reviewer has been assigned @lewisthagichu. They'll get back to you as soon as they get a chance to have a look at it.

**Comment by lewisthagichu** [comment]
Noted. Thanks.
