### ISSUE TITLE
Advanced Selectors: <add notes to the assignment>

### ISSUE THREAD

**Issue by phoever23** [TheOdinProject/curriculum#26466]
### Describe your suggestion

This assignment article [Shay Howe’s article on Complex Selectors](https://learn.shayhowe.com/advanced-html-css/complex-selectors/) still uses ":" to write pseudo-elements, while it's recommended to use "::" currently. It would be nice to mention that in the assignment.

### Path

Node / JS

### Lesson Url

https://learn.shayhowe.com/advanced-html-css/complex-selectors/#pseudo-elements

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Thanks, could you please share the link to the lesson this article is in?

**Comment by phoever23** [comment]
> Thanks, could you please share the link to the lesson this article is in?

[https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors](url)

**Comment by ManonLef** [comment]
https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors You have wrapped your URL in `[]` with a blank url inside `()` so it doesn't link :)
[here's the lesson link for future reference](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors)

It looks like the article itself mentions the single vs double colons and how they should be used for pseudo-elements specifically, but then still has single colon for pseudo-elements. 
![Screenshot 2023-10-10 at 09 41 26](https://github.com/TheOdinProject/curriculum/assets/81025586/887fd543-eaac-48fa-9ad5-89ecf6a6f0a6)

We could add a note, but we could also consider finding a more up to date resource for this. What do you think? Perhaps you see an article in the additional resources that could be a good replacement?

**Comment by phoever23** [comment]
I apologize for my mistakes, as this is my first time reporting an issue. Thank you so much for correcting me.
Compared to other contents in the additional resources, this article is more concise and comprehensive. So I think adding a note may be enough.

**Comment by ManonLef** [comment]
Thanks so much, I'll open it up for contribution

**Comment by ht-l1** [comment]
hey would love to take this one! So we want a note clarification, not a replacement link in the Additional Resources?

**Comment by ManonLef** [comment]
@ht-l1 Since this article is part of the assignment, we didn't consider a replacement link in the Additional Resources. I proposed looking if one of the additional resources could replace this article. It's quite a good article and I'm not sure if a good replacement can be found. Perhaps in the future we will. 

The fact the article itself has a note about the pseudo-elements, I think it's good to just add a disclaimer that it sometimes uses the old single colon still, and that we now expect to use double. You could even link that to the section in this lesson where it's discussed but I don't find that extremely necessary. 

Currently the assignment says:
> Read [Shay Howe’s article on Complex Selectors](https://learn.shayhowe.com/advanced-html-css/complex-selectors/). This covers most of the content of this lesson in a bit more detail.

I suggest something like the below
> Read [Shay Howe’s article on Complex Selectors](https://learn.shayhowe.com/advanced-html-css/complex-selectors/). This covers most of the content of this lesson in a bit more detail. As stated in their article, they sometimes use a single colon instead of a double one for pseudo-elements. Please keep in mind that the double colon is now the standard. 

Feel free to give your own spin to it.

**Comment by AliHussienabdo** [comment]
...

**Comment by ht-l1** [comment]
Thank you @ManonLef , I just submitted a pull request. I really only changed that specific bullet, but somehow the pull request file shows many other changes I didn't make. I'm not sure what happened - I did a full sync from this repo before cloning to my local drive. How should I proceed from here?

**Comment by Abhrajitdas02** [comment]
@ManonLef  Can I work on this issue?

**Comment by ManonLef** [comment]
@Abhrajitdas02 thanks for your interest, but the person in the comment above you is assigned this issue. You can see if someone is already assigned by checking in the comment section if a maintainer assigned it, or in the top right of the web view, ss below. 
![Screenshot 2023-10-14 at 16 56 11](https://github.com/TheOdinProject/curriculum/assets/81025586/4f4edd01-79c2-4f38-b27b-1b95d5ff0cf9)
