### ISSUE TITLE
NodeJS: Insufficient info about escaping and saftey

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#26478]
### Describe your suggestion

-express tutorial doesn't sufficiently introduce escaping, what it is and why we use it
-express tutorial escapes user input with express-validator and then again when displaying it with pug
-pug's documentation offers no information about the difference between escaped and unsecaped interpolation
-this contributes to confusion about escaping, sanitization an why we would use then and when
-i found [This article](https://blog.presidentbeef.com/blog/2020/01/14/injection-prevention-sanitizing-vs-escaping/#:~:text=The%20security%20industry%20seems%20to,irreversible%20stripping%20of%20special%20characters.) which cleared things up for me
This is related to [this discord discussion](https://discord.com/channels/505093832157691914/597796701650026517/1161748280024256543) with Fred

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Omar (onsmak) @onsmak

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/javascript thoughts?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript This one still needs a review please

**Comment by 01zulfi** [comment]
@OmarNaguib Thanks for opening the issue.

I'm not sure if we'll go in-depth into escaping. We'll be replacing Pug with [EJS](https://ejs.co/#docs) as the template engine and escaping is straightforward with the `<%=` tag.

The linked article is valuable, maybe we can add it to the new #27642 lesson.

**Comment by thatblindgeye** [comment]
Closing per comment above. New lesson issue is already open and references this issue, so we can backtrack to get to the article mentioned in the original comment if needed.

**Comment by OmarNaguib** [comment]
@01zulfi, @thatblindgeye , Thank you
i has a question
Is it possible for me to contribute to the Node refresh, or is that reserved for people strictly within the official team
i would be happy to join
