### ISSUE TITLE
Adding code of conduct to repository

### ISSUE THREAD

**Issue by mohitd404** [TheOdinProject/curriculum#26487]
### Describe your suggestion

We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

### Path

Foundations

### Lesson Url

https://contrib.rocks/

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

Kindly assign this issue to me ! i would love to work on it !

**Comment by Asartea** [comment]
There is already a Code of Conduct for all of the TOP repos at https://github.com/TheOdinProject/.github/tree/main/CODE_OF_CONDUCT.md
