### ISSUE TITLE
JS Recursive Methods: Add a video as an additional resource

### ISSUE THREAD

**Issue by silenceinspace** [TheOdinProject/curriculum#26497]
### Describe your suggestion

Understanding recursion, especially the call stack, may be challenging for most folks. I faced the same problem - I couldn't get how exactly the recursion unwraps all its subcalls once it reaches the base case.

I found this video really helpful: https://www.youtube.com/watch?v=M-5nzjxtXpQ (starting from 9:44 there, the author shows how to visualize recursion better with debugger in Chrome. I have never really opened it in the browser before. However, it is honestly nice how one can walk through every step in the recursion and follow the logic)

I think others could benefit from it. Moreover, neither the article nor the already mentioned resources do not mention this way of visualizing recursion. Otherwise another resource I came across while trying to grasp the Fibonacci recursion was https://recursion.vercel.app/. It has really smooth animations and you can walk through every recursive call. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment]
These resources both look good to me, the visualization app is especially neat!

If we remove that Medium article that we talked about in your open PR I'd be on board with adding both since they each bring something new to the lesson.

If we don't remove that Medium article we'll have to talk through which of these two would be better to include.

**Comment by silenceinspace** [comment]
Sounds solid! Then I will keep an eye on both the issue and PR. Thank you for your effort, Austin!

**Comment by wise-king-sullyman** [comment]
@silenceinspace do you still want to replace that Medium article with the new resources you'd found here?

**Comment by silenceinspace** [comment]
@wise-king-sullyman hi Austin, glad to hear from you here again. Yes, absolutely! Can you make it happen? :D

**Comment by wise-king-sullyman** [comment]
@silenceinspace What is it you're needing on our end? Do you have a PR up already?

**Comment by silenceinspace** [comment]
@wise-king-sullyman well, I do have a PR #26495  which initially suggested to remove one already existing resource (medium article) in that lesson.
So I think I could update the PR with removing the article and including the two resources I mentioned in this issue's description. Should I go for it?

**Comment by wise-king-sullyman** [comment]
Yep you can update that PR, or just open a new one, up to you!

**Comment by silenceinspace** [comment]
@wise-king-sullyman I was going to update my PR to include the alternative resources, but I noticed I was not the only one who had a problem with the medium article. Somehow, #26703 PR fixed what didn't sit right with me. Even though my resources were not included, I am totally cool with the new one.
Anyways, thank you Austin for the willingness to work on my PR and issue. I will close the issue!:)

**Comment by wise-king-sullyman** [comment]
If you'd still like to add your resources please feel free to put a new PR up! Of course if you no longer want to I totally understand, but IMO there's room for one more resource there and there could be a debate over which visualization site is better.
