### ISSUE TITLE
Problem Solving: Broken link on Problem Solving Assignment

### ISSUE THREAD

**Issue by ved4a** [TheOdinProject/curriculum#26494]
### Describe your suggestion

The link to the article from 'The Viking School' no longer works, even from the web archive. It simply cannot be reached.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-problem-solving

### The actual link in question

https://web.archive.org/web/20211229231605/https://www.vikingcodeschool.com/software-engineering-basics/what-is-pseudo-coding

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by radtradcath** [comment]
Working fine on my end. Time taken for page to load is a bit above average, but it works fine.

**Comment by wise-king-sullyman** [comment]
Seems to work for me as well, though pointing to the web archive isn't ideal IMO. I wonder if we should try to find a replacement resource.

WDYT @TheOdinProject/foundations ?

**Comment by zachmmeyer** [comment]
It took a while but it eventually loaded for me.

**Comment by radtradcath** [comment]
If the approval succeeds, may I work on this, please?

**Comment by wise-king-sullyman** [comment]
@radtradcath sure! I've gone ahead and assigned you.

Give this a few days so that we can see if any maintainers oppose the idea of switching it, then if you'd like to start the hunt for a good replacement that would be much appreciated.

**Comment by radtradcath** [comment]
> @radtradcath sure! I've gone ahead and assigned you.
> 
> Give this a few days so that we can see if any maintainers oppose the idea of switching it, then if you'd like to start the hunt for a good replacement that would be much appreciated.

Sure, @wise-king-sullyman ! All get ahead of this. Thank you.

**Comment by zachmmeyer** [comment]
Added the link so other do not have to go finding it.

**Comment by radtradcath** [comment]
Hey @wise-king-sullyman . Is the absence of comments an indication of approval? Or should I wait for other maintainers to manifest their ideas? 
Sorry if the question feels silly. Don't want it to look like I'm neglecting the issue.

**Comment by wise-king-sullyman** [comment]
@radtradcath yep I'd say you can go ahead now!
