### ISSUE TITLE
Entire Course: Add "Rabbit Hole" and "No Gos" to all projects

### ISSUE THREAD

**Issue by bycdiaz** [TheOdinProject/curriculum#26504]
### Describe your suggestion

In [Basecamp's resource on the Shape Up process](https://basecamp.com/shapeup), there are ideas called "[Rabbit Holes](https://basecamp.com/shapeup/1.5-chapter-06#ingredient-4-rabbit-holes)" and "[No Gos](https://basecamp.com/shapeup/1.5-chapter-06#ingredient-5-no-gos)" that I think we could introduce to project prompts in our curriculum.

Sometimes learners are spending time on ideas that the project does not require. Or pursuing implementations that are not useful for the task at hand.

In the calculator project, writing logic that accomplishes the order of operations could be considered a "Rabbit Hole." To save learners some time, we can include a section on Rabbit Holes and briefly describe the suggested implementation. e.g. Do not use order of operations.

In a project like Rock Paper Scissors, a "No Go" can be something like responsiveness. Explicitly indicating that responsiveness is not an objective can help learners execute on the core functionality that matters at that point in time.

I use this process at work and am happy to advise!

**Task**:
Adding "Rabbit Hole" and "No Gos" sections to all projects would be extremely beneficial for learners.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

bycdiaz

### (Optional) Additional Comments

Rather than tackle this in one very big PR, I recommend creating a branch that then has sub branches for every project. We can review and merge to that initial branch. Then once content for each project is in, merge to `main`. This gives us the opportunity to assign different folks to different projects.

Project Board: https://github.com/orgs/TheOdinProject/projects/42/views/1

Discussion for this PR will happen here: https://discord.com/channels/505093832157691914/1163207158633087076

**Comment by kahmoh** [comment]
With some guidance, I'd be happy to take this on!

**Comment by bycdiaz** [comment]
@kahmoh Let's do it. Create a thread in `#contribution-opportunities` on Discord and ping me. We'll coordinate there.

**Comment by JoshDevHub** [comment]
Just chiming in with some thoughts and echoing my support for this. We use Shape Up in one of the other open source communities I work with and I love it.

In the real world, what you're *not* going to work on is often just as important as what you *are* going to work on. Scope creep can easily waste a lot of time/money/resources, and I think it's a great idea to prepare learners for this by introducing them to these concepts.

**Comment by bycdiaz** [comment]
@JoshDevHub, if you're ok with it, I'd love to include this remark when we first introduce these ideas. 

`In the real world, what you're not going to work on is often just as important as what you are going to work on.`

And yeah, I think helping learners narrow their focus is gonna' be super helpful.

**Comment by bycdiaz** [comment]
@kahmoh Made a thread: https://discord.com/channels/505093832157691914/1163207158633087076

**Comment by kahmoh** [comment]
@bycdiaz Thanks, it seems I don't have permissions to talk in both the channel and the thread. If there's something you need to update regarding my permissions to do so, I'll be happy to give you my discord username. Also, as a heads-up, I'm working from the UK, I wanted to let you know, so any time delay is a bit more clear.

**Comment by bycdiaz** [comment]
@kahmoh No worries on the time difference. We'll make it work. Just made an adjustment to the thread. You should be able to write in there now.

**Comment by rishikumars-in** [comment]
Great idea @bycdiaz! I would like to work on this.

**Comment by bycdiaz** [comment]
Hey y'all.

I cracked open a project and started to think about what these new sections can look like. And I don't think it's gonna' be a simple addition. I think we'll need to make adjustments to the rest of the project prompts to make these new sections make sense. And in that thinking, I'm also feeling like it would be useful to just standardize the project prompts to make them like pitches (from the basecamp book).

I think we can/should pause on actively working on this. I do expect we'll add the rabbit hole/no gos in some form. But what that form will look like feels like it's worth discussing a little more.
