### ISSUE TITLE
Rendering Techniques: <Short description of your suggestion>

### ISSUE THREAD

**Issue by futuressobright** [TheOdinProject/curriculum#26507]
### Describe your suggestion

I'm not sure what is being stated in the paragraph titled "Falsy values in JSX, a common pitfall."

More clear might be be a list of which values are falsy, and which are not - or perhaps we need two sets of lists, one for JS and one for React - is that the point?

Thanks.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-rendering-techniques

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Gnuguy

**Comment by wise-king-sullyman** [comment]
It looks like it's just trying to clarify why some falsy values render and some don't, it does seem like it could potentially be worded a bit better though.

**Comment by ScaxCodes** [comment]
Good morning, I would love to help with this and already have a wording in my mind.

**Comment by wise-king-sullyman** [comment]
All yours @ScaxCodes, thanks!

**Comment by ScaxCodes** [comment]
Sorry, totally forgot about this. Gonna work on it soon!

**Comment by ScaxCodes** [comment]
@wise-king-sullyman finally done, sorry for the delay

**Comment by wise-king-sullyman** [comment]
@ScaxCodes absolutely no worries! We're all volunteering our time here. Thank you for taking the time to push up a fix! 💪
