### ISSUE TITLE
HTML Boilerplate: Broken link

### ISSUE THREAD

**Issue by tomaszciupek** [TheOdinProject/curriculum#26501]
### Describe your suggestion

In HTML Boilerplate lesson there is a broken link at the bottom of the page: https://www.positioniseverything.net/html-encoding/

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-html-boilerplate

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by bizarf** [comment]
I just checked that link and it's working fine for me. Is it still not working for you?

**Comment by tomaszciupek** [comment]
It appears to be fine now. Unlucky timing :)
