### ISSUE TITLE
Webpack: Add mention of template repos

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26515]
### Describe your suggestion

The webpack lesson has very recently been updated but one extra thing it could do with is a quick mention about template repos for future setup convenience. Occasionally people do question whether they need to do all of the config themselves from scratch every new project or "hack it" by copying and pasting locally, whereas a template repo with a basic configuration and file structure would be far more convenient.

I don't imagine this will be much work for someone to do.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-webpack

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by ManonLef** [comment]
I think a mention of template repositories is definitely useful. I am however thinking it might be good if people get a feel for how this is set up, where the files reside, and generally get comfortable with the structure by setting up manually a few times. Would it be an idea to push it further a little and mention the template repo when ESLint and Prettier is introduced?

**Comment by MaoShizhong** [comment]
> I think a mention of template repositories is definitely useful. I am however thinking it might be good if people get a feel for how this is set up, where the files reside, and generally get comfortable with the structure by setting up manually a few times. Would it be an idea to push it further a little and mention the template repo when ESLint and Prettier is introduced?

I quite like that suggestion. I was thinking just before that rather than putting it in the Webpack lesson itself, maybe it'd be more sensible after the restaurant page project's steps that handle the setup but on reflection, I think the Linting lesson is actually far more appropriate and topical.

**Comment by MaoShizhong** [comment]
Gentle bump - any other thoughts/suggestions?
I quite like the idea of mentioning template repos come linters/formatters, since it should be a huge mention given how simple they are to set up. Even if webpack and manual config won't be used for projects after the JS section, it's still beneficial for people to be aware of template repos for future use (e.g. perhaps even in the Node part with express).

**Comment by wise-king-sullyman** [comment]
Agree and I'm on board with the suggestions here, thanks @MaoShizhong!

**Comment by MaoShizhong** [comment]
If no one grabs this then I'm happy to do it

**Comment by wise-king-sullyman** [comment]
How long would you like to give others to take it before you do?

**Comment by MaoShizhong** [comment]
@wise-king-sullyman I guess it's been long enough and no one's up for it so I'll grab it and pop a PR in later tonight.
