### ISSUE TITLE
Create feature branch off main

### ISSUE THREAD

**Issue by bycdiaz** [TheOdinProject/curriculum#26510]
- [ ] Create a branch off of the [curriculum's main branch](https://github.com/TheOdinProject/curriculum) that will serve as our feature branch. This can be named something like: `no-gos-rabbit-holes-foundations`.
- [ ] Push branch up.
- [ ] Make team aware of the branch being available in the team channel.

**Comment by odin-student-3** [comment]
🧿💋🧿
