### ISSUE TITLE
TEST - please ignore. testing permissions

### ISSUE THREAD

**Issue by bycdiaz** [TheOdinProject/curriculum#26517]
### Describe your suggestion

TEST

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by odin-student-3** [comment]
hi @bycdiaz

**Comment by odin-student-3** [comment]
Glad I could be of help :)
