### ISSUE TITLE
The Cascade: Rephrase a sentence for better understanding

### ISSUE THREAD

**Issue by odilsonjs** [TheOdinProject/curriculum#26523]
### Describe your suggestion

Under the subheading "Specificity"
(hint: you can use Ctrl + F and search exactly what I quoted, that's how it appears on the page)

", and a type selector will always beat any number of anything less specific than it."
this is super confusing to understand. Maybe it could be rephrased as: ", and a type selector will always beat any number of less specific selectors."

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

odilsonjs

### (Optional) Additional Comments

It's my first contribution and i love The Odin Project💖

**Comment by KevinMulhern** [comment]
Thanks @odilsonjs, makes sense to me. It's been assigned to you 💪
