### ISSUE TITLE
React Course: Correct typo in Class Based Components lesson

### ISSUE THREAD

**Issue by BobSlim** [TheOdinProject/curriculum#26522]
### Describe your suggestion

"All the components by far, have been functional in style and syntax" => "All the components **so** far have been functional in style and syntax"

- Changes by => so.
- Remove comma? I'm not sure if this is grammatical, but it sure reads better without.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-class-based-components

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

bobslim

**Comment by KevinMulhern** [comment]
Thanks @BobSlim, I've assigned this to you.
