### ISSUE TITLE
The cascade: Rephrase for better understanding

### ISSUE THREAD

**Issue by odilsonjs** [TheOdinProject/curriculum#26528]
### Describe your suggestion

Under the subheading "Specificity"
(hint: you can use Ctrl + F and search exactly what I quoted, that's how it appears on the page)

"a larger amount of a single selector will beat a smaller amount of that same selector."
I was honestly extremely confused by what is even meant🤔

I think it could be rephrase by something like this: "A greater specificity of a single selector takes precedence over a lesser specificity of the same selector."

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

odilsonjs

### (Optional) Additional Comments

Contribute with ❤ to open source projects

**Comment by KevinMulhern** [comment]
Hey @odilsonjs, can this be rolled into https://github.com/TheOdinProject/curriculum/issues/26523 please?

For anything small like this, feel free to skip making an issue and go straight to making PR. It's often easier to judge the idea that way.

**Comment by odilsonjs** [comment]
Hello @KevinMulhern, yes, it makes sense🤔, 
i'll try to go straight and make a PR for any small changes like this from now.

Thanks.
