### ISSUE TITLE
Introduction to RSpec: Update the number of downloads

### ISSUE THREAD

**Issue by odilsonjs** [TheOdinProject/curriculum#26527]
### Describe your suggestion

According to me the number of download for RSpec framework is a bit out dated. i suggest to improve it to 700 millions, as we can see it in the docs: https://rubygems.org/gems/rspec

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-introduction-to-rspec

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

odilsonjs

**Comment by KevinMulhern** [comment]
Thanks @odilsonjs, sounds good to me - you've been assigned.
