### ISSUE TITLE
NodeJS Messaging App: Mention expectations regarding realtime updates

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26525]
### Describe your suggestion

In the current NodeJS course, there are no lessons that introduce how to manage low-latency realtime updates, be that via long polling or websockets or some other alternative. Whilst I don't think it's vital such a lesson be written and added to the course, I think it's at least important to mention in the messaging app spec that it does not expect realtime updates (I think many people will adopt a REST API approach for their own backend).

I propose mentioning that expectation (or lack thereof) and perhaps also mentioning that if after the course the learner is interested in looking into this, they might be interested in long polling or websockets via something like `socket.io`.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-messaging-app

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by KevinMulhern** [comment]
Thanks for taking the time to write this up @MaoShizhong. Sounds like a good idea to me.

@TheOdinProject/javascript any thoughts?

**Comment by MaoShizhong** [comment]
Upon further reflection, I'm actually wondering whether it would be beneficial to have a lesson on websockets and socket.io? I currently do not have experience with this but intend to look into it and SSE for Odinbook and also as a rewrite for a lot of my messaging app features (as REST API is certainly not the most appropriate for such a thing). I have looked into long-polling and SSE but certainly for the messaging app, neither of these seem very suitable (SSE perhaps for a lot of the features of Odinbook though).

Having a websockets lesson would also be much more in line with how the Rails course has a websockets lesson at the end, right before the FP which is also essentially Odinbook.

Thoughts? If it sounds like a good idea, I am planning on looking into rewriting my messaging app with socket.io (perhaps even a mix if it's possible? For some parts that are more suited to the REST API pattern) and think perhaps if working with people to adapt the Rails websockets lesson for Node and socket.io would be feasible?

**Comment by wise-king-sullyman** [comment]
Sounds great to me, @MaoShizhong is this something you'd still like to do?

**Comment by MaoShizhong** [comment]
@wise-king-sullyman Yep, I'll add the expectation mention in.
Anything else e.g. websockets is much more ambitious and something for a future discussion if I do explore it enough but not relevant right now.
