### ISSUE TITLE
NodeJS: Where's Waldo App, Direction 1

### ISSUE THREAD

**Issue by Amiriel01** [TheOdinProject/curriculum#26537]
### Describe your suggestion

While starting the Where's Waldo project I noticed that direction number one seemed out of place. Learners have been creating GitHub repositories since the first project in Foundations. I suggest that the directions remove number one. 

![topdirection1](https://github.com/TheOdinProject/curriculum/assets/112915165/dffd8de2-7637-4484-a25e-a06ada969d74)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-where-s-waldo-a-photo-tagging-app

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Amiriel

**Comment by KevinMulhern** [comment]
Nice spot, thanks @Amiriel01 - it's been assigned to you 💪
