### ISSUE TITLE
React Router: "Create a default Profile component" maybe should be "Create a DefaultProfile component"

### ISSUE THREAD

**Issue by jasonHYLam** [TheOdinProject/curriculum#26533]
### Describe your suggestion

In the React Router, the student is prompted to create a new Component for a default profile. However I found it unclear that this should be titled 'DefaultProfile' as it was not expressed in the text; instead it says default Profile, rather than 'DefaultProfile' which I felt is probably the more correct version. Especially as the next line states 'DefaultProfile'. 
![image](https://github.com/TheOdinProject/curriculum/assets/105083538/4cf5287f-92c9-4287-b20b-ac99b8f866c5)

This change may also reduce confusion, as the student has already created a Component called Profile earlier in the lesson.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-react-router

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks @jasonHYLam. Sounds good to me - I've assigned it to you.
