### ISSUE TITLE
Join the Odin Community: Update discord command syntax

### ISSUE THREAD

**Issue by snczas31** [TheOdinProject/curriculum#26532]
### Describe your suggestion

ex `/giphy hi` is not working instead use `/gif hi` and all other discord commands starting with ! has been updated to / .

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

snczas31_93900

**Comment by KevinMulhern** [comment]
Thanks for reporting @snczas31, I've assigned this to you.
