### ISSUE TITLE
JavaScript/More_Testing: Emphasize that setting up jest for webpack is not required

### ISSUE THREAD

**Issue by fcasibu** [TheOdinProject/curriculum#26548]
### Describe your suggestion

I've seen a commonly asked question where in the lesson [More Testing](https://www.theodinproject.com/lessons/node-path-javascript-more-testing) assignement 6 describes:

> And finally, if you wish, you can add Jest to your webpack setup. Read about that process [here](https://jestjs.io/docs/webpack).

Problem: Even though we already have completed projects where we only use jest/babel to test it still gives an impression that we still need to setup jest for webpack in the following project, but this is not the case because like the documentation describes, it's useful for handling static assets, css modules, etc in tests. These things are not necessary in fully testing the modules in the following project Battleship. It is also encouraged to create the project and create the modules without handling any kind of DOM manipulation as a good practice, so we won't really see any issues coming up even if they ignored this assignment.

Solution: Emphasize that setting up jest for webpack is not necessary. This I think could also be more of an additional resource than an assignment (IMO)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-more-testing

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

nevz

**Comment by KevinMulhern** [comment]
Can someone from @TheOdinProject/javascript take a look at this please?

**Comment by wise-king-sullyman** [comment]
I agree that can probably be moved to the additional resources section.

**Comment by aconstas** [comment]
I would love to work on this! Can I be assigned?

**Comment by wise-king-sullyman** [comment]
All yours @aconstas, thanks!
