### ISSUE TITLE
Setting up Git: Change wording under creating an SSH key

### ISSUE THREAD

**Issue by HiJak3r** [TheOdinProject/curriculum#26557]
### Describe your suggestion

When arriving at the `ssh-keygen -t ed25519 -C "your@email.com"` portion of the Setting up Git page, it was a bit confusing on which email to use. I wasn't sure whether to use my hidden GitHub email or my real personal email.

Instead, I'd just change the line to be something like:
`ssh-keygen -t ed25519 -C "yourPersonal@email.com"`

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Hey @HiJak3r 

I've not come across this issue before. Because the very next instruction after that is clarifying what you'd enter if using a private github email then perhaps we should instead add a note to clarify that you should use either your personal email or a private github email if you are using that. We could add it just above the screenshot where you enter your username and email.

What do you think?

**Comment by HiJak3r** [comment]
That sounds like it'd make it clearer! I think going with that or adding something extra in the tip bubble beneath the code part would be great :)

**Comment by CouchofTomato** [comment]
@HiJak3r 

Awesome. You've indicated you're happy to work on the issue. Should I assign you?

**Comment by HiJak3r** [comment]
Sure! I can take care of it.

Is there anything I have to do to gain access to make changes?

**Comment by CouchofTomato** [comment]
@HiJak3r 

You would need to fork the cirriculum repo and then make the changes and submit a PR. There are some instructions found in the README of the repo https://github.com/TheOdinProject/curriculum

Let me know if you need anything clarified.

**Comment by HiJak3r** [comment]
@CouchofTomato 

I believe it should be submitted now.

Thank you for all the help and being kind :)
