### ISSUE TITLE
Files and Serialization: Knowledge Check mismatch with changed assignment

### ISSUE THREAD

**Issue by macauleydev** [TheOdinProject/curriculum#26559]
### Describe your suggestion

The last two questions under this page's [Knowledge Check](https://www.theodinproject.com/lessons/ruby-files-and-serialization#knowledge-check) -- 

> - [How would you check if a file exists using the File object in the command line?](http://ruby.bastardsbook.com/chapters/io/)
> - [In a Download directory containing 5 files, how would you count the number of files in that directory using the Dir object?](http://ruby.bastardsbook.com/chapters/io/)

-- refer to the previous version of Assignment 5, which was changed when issue #23847 was closed four months ago.

(That change replaced the [Bastard's Book reading](http://ruby.bastardsbook.com/chapters/io/), which explores the File and Dir classes but contains some outdated URI syntax, with a newer [Kiprosh reading](https://blog.kiprosh.com/serialization_in_ruby_on_rails_part_one/) which like Assignments 3 and 4 focuses on serialization formats.)

I can see two possible solutions to this mismatch:

1. Rewrite these two knowledge checks to refer to the current Assignment 5, the Kiprosh reading.
2. Change Assignment 5 to a reading more similar to the previous Assignment 5 and compatible with the existing knowledge checks (and update their links accordingly).

Personally, I would lean toward Solution 2, since otherwise the assignments from this page mention the File class only barely ([one paragraph](https://thoughtbot.com/blog/io-in-ruby#file) from Assignment 1) and the Dir class not at all.

A simple Solution 2 could be to swap the current first additional resource, [Zetcode’s section on Input/Output in Ruby](http://zetcode.com/lang/rubytutorial/io/) (which deals with both File and Dir classes), with the Kiprosh reading, so that Zetcode becomes Assignment 5 and Kiprosh becomes one of the Additional Resources.

(Alternatively, a new resource could be found as a better replacement for the previous Assignment 5, Bastard's Book reading.)

I'm willing to help, but would defer to perspective and recommendations from more experienced Ruby/Rails developers, as I'm only encountering these topics for the first time.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-files-and-serialization#knowledge-check

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

A more minor point of confusion is that the knowledge checks on this page refer to IO, File, and Dir as "objects" rather than "classes". I believe simply replacing the word "objects" with "classes" would be more accurate.

**Comment by CouchofTomato** [comment]
@macauleydev 

I apologise for the delay in picking this up. I haven't located a better resource so I'm happy to go with solution 2 from your proposal using the resource you provided if you want?

**Comment by macauleydev** [comment]
Thanks, @CouchofTomato. I also haven't found a better free resource. (Programming Ruby, "the pickaxe book", is widely recommended and covers these topics, but it's not free.)

If you assign me to this issue, I'll make a PR for my above-proposed "simple Solution 2", swapping Zetcode and Kiprosh.

**Comment by CouchofTomato** [comment]
@macauleydev 

All yours :)
