### ISSUE TITLE
NodeJS/Getting Started: Add http.createServer documentation to HTTP section 

### ISSUE THREAD

**Issue by BobSlim** [TheOdinProject/curriculum#26558]
### Describe your suggestion

createServer is an essential component of the upcoming project (I think), however this block of documentation does not mention it. Alongside the link for making HTTP requests, there should be documentation about how to receive HTTP requests.

Note: if documentation is provided elsewhere, and I've just missed it - it should be duplicated or moved to this section.

Potential candidates:
- [From the same folder as the lesson on http requests](https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/node-js-web-server/node-http-server.en.md) 
- [From w3 schools tutorial](https://www.w3schools.com/nodejs/nodejs_http.asp)  
  - (the W3 schools tutorial is "optional extra credit", therefore cannot be pointed to as the source of this documentation.)
- [From nodejs](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-getting-started

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

bobslim

**Comment by wise-king-sullyman** [comment]
I'm also not seeing anything where we explicitly discuss `createServer` other than a brief single snippet mention of it.

@TheOdinProject/javascript am I missing it here as well? I'm surprised we don't get a ton more questions about this if not.

**Comment by wise-king-sullyman** [comment]
This is something that should still probably be resolved, since nobody else voiced that there was something missed I assume that means action is needed here.

**Comment by mekbibDev** [comment]
Hey, I would like to help if you still need help.  I would go about by linking the official documentation [http.createserver](https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener ) in the assignment section. Although the `#` isn't working for some reason. It does have a lot of options which I don't believe we need to know yet at this point so I could also add a small summary on the assignment like "it basically allows us to create a web server and allows us to register handlers that would be executed every time we get a request" and that "you probably won't make much use of the options" 

oh I'm only at the part express 104 so I don't actually know if we might need the options tho

**Comment by wise-king-sullyman** [comment]
@mekbibDev sounds like a plan to me! All yours!
