### ISSUE TITLE
JavaScript: Battleship project confusing assignment's instruction

### ISSUE THREAD

**Issue by kamaladdi34** [TheOdinProject/curriculum#26566]
### Describe your suggestion

I find this instruction in the battleship project's assignment confusing:

_isSunk() should be a function that calculates it based on their length and the number of ‘hits’._

My suggestion:

_isSunk() should be a function that calculates whether a ship is considered sunk based on its length and the number of hits it has received._
 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

juicedrippy

**Comment by CouchofTomato** [comment]
@kamaladdi34 

This seems a reasonable change. I'm happy to assign this to you if you want?

**Comment by kamaladdi34** [comment]
@CouchofTomato Yes I would like to work on it, this would be my first contribution on github ever.

**Comment by MaoShizhong** [comment]
You've got this!
