### ISSUE TITLE
Managing State With The Context API: Full stop missing

### ISSUE THREAD

**Issue by jasonHYLam** [TheOdinProject/curriculum#26567]
### Describe your suggestion

I noticed that a full stop was missing from this paragraph. I'd be happy to work on it.
![image](https://github.com/TheOdinProject/curriculum/assets/105083538/331e8e96-3116-4dd9-bc02-4f0b26845493)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-managing-state-with-the-context-api

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@jasonHYLam 

Feel free to submit a PR and someone will review it
