### ISSUE TITLE
Introduction To State: The CodeSandbox is not responsive on small screens

### ISSUE THREAD

**Issue by LaythAlqadhi** [TheOdinProject/curriculum#26565]
### overflowing issue in React course

Hello! I've noticed an overflow issue in CodeSandbox while using my smartphone.
![IMG_5524](https://github.com/TheOdinProject/curriculum/assets/125077045/d991cacf-72e8-4f43-8d23-b6f88dde83ee)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Hey @LaythAlqadhi 

Thanks for bringing this to our attention. I'm not sure if this is something we can resolve but will investigate.
