### ISSUE TITLE
NodeJS/Getting Started:  Error 404 on links referenced from NodeJS official docs

### ISSUE THREAD

**Issue by iamashay** [TheOdinProject/curriculum#26578]
### Describe your suggestion

I was going through the "Getting Started" lesson in the NodeJS course and noticed that all the articles pointing to https://nodejs.dev/en/learn/* are resulting in a 404 error.

For better clarity, here are the specific lines where I found the broken links in the "Assignment" section:

- [NodeJS.dev](https://nodejs.dev/en/learn)
- Learn how to run Node.js scripts from the terminal in [this](https://nodejs.dev/en/learn/run-nodejs-scripts-from-the-command-line/) lesson.
- Learn quickly about .env files and how we use them [here](https://nodejs.dev/en/learn/how-to-read-environment-variables-from-nodejs/)!
- Then, let’s start [writing files](https://nodejs.dev/en/learn/writing-files-with-nodejs/) in Node.
- Finally, we’ll learn how to [read files](https://nodejs.dev/en/learn/reading-files-with-nodejs/).
- Let’s get an [introduction](https://nodejs.dev/en/learn/an-introduction-to-the-npm-package-manager/) to NPM.
- Follow along the [Event Emitter](https://nodejs.dev/en/learn/the-nodejs-event-emitter/) section.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-getting-started

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

**Comment by iamashay** [comment]
I have found the replacement markdown github files for those broken links. Is it okay for me to work on this?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Can someone take a look and confirm if this is how we want to move forward with this issue?

**Comment by thatblindgeye** [comment]
@iamashay can you confirm that you're still getting 404s from those links? When I try navigating to them from the lesson I have no issue, and we do currently link to some GitHub MD files (with a note before the Assignment section).

If you still are, then since we already are linking to GitHub links for certain content then I don't see why we wouldn't do the same for other links, in which case I'd say go ahead and open a PR.

**Comment by iamashay** [comment]
@thatblindgeye , yes, links are working now. #26596 seems to have replaced the links with the live ones.

**Comment by thatblindgeye** [comment]
Gotcha! In that case if you aren't noticing any other issues I'll close this out. If you notice any other issues please reply here or feel free to open a new issue, thanks for letting us know in the first place!
