### ISSUE TITLE
JavaScript: Improve instructions for 'Binary Search Trees' project.

### ISSUE THREAD

**Issue by Ngonidzashe-Zvenyika** [TheOdinProject/curriculum#26576]
### Describe your suggestion

The 'levelOrder, inOrder, preOrder and postOrder' functions are said to take another function as a parameter, however, the instructions do not explain the purpose of this function. My understanding is that it is a random optional callback to manipulate the nodes in the order which they are traversed. I propose to explain this to learners as they may get stuck wondering how to implement this callback when in actuality it is not the focus of the task.

Furthermore, the syntax for the  inOrder, preOrder and postOrder functions in the assignment instructions could be improved to use the camel-case naming convention.

![screenshot](https://github.com/TheOdinProject/curriculum/assets/123906490/5a5e9039-fd3f-483c-982f-b340932a3de1)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-binary-search-trees

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Hey @Ngonidzashe-Zvenyika 

I agree this could be clearer. I've assigned this to you.

**Comment by Ngonidzashe-Zvenyika** [comment]
Hey @CouchofTomato 

Awesome, working on it now.
