### ISSUE TITLE
HTML Boilerplate: Issues with externally linked content under Additional Resources 

### ISSUE THREAD

**Issue by Bagolly** [TheOdinProject/curriculum#26579]
### Describe your suggestion

The [first](https://www.positioniseverything.net/html-encoding/) website linked under the Additional Resources section, titled _HTML Encoding Reference for Beginners: Understanding Character Sets_ states, that
> UTF-8 has the privilege of being quite backward-compatible since it is a subset of ASCII.

which is obviously wrong. Furthermore,
>Text, images, graphics, video, data compilations, and all other forms of information that appear to the website reader are made up of “characters” in webpage content.

also sounds off, as many of the mentioned data types are primarily stored in binary file formats, that cannot be (meaningfully) interpreted as a sequence of characters, such as .jpg, .png, and raster image file formats in general.

I am not a professional web developer, so my issues might be the result of my lack of knowledge, so perhaps someone with more technical experience could read through the article, and remove if necessary?

Lastly, I'm not sure if this is the right template to flag issues with content in the external website itself, but the description does include _broken links_, and _suggest another resource_, so this seemed the most appropriate.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-html-boilerplate

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
Hey @Bagolly 

Thanks for bringing this to our attention.

I think they've just made a mistake in the first instance and meant to say that ascii is a subset of utf-8.

Since this is an additional resource I think it's best we just remove it. Since you haven't indicated you are happy to work on it I assume you are happy if we mark this as open for others to work on?

**Comment by Bagolly** [comment]
Hey @CouchofTomato 

> I assume you are happy if we mark this as open for others to work on?

Of course!

**Comment by CouchofTomato** [comment]
Open for anyone that wants this

**Comment by sahilshityalkar** [comment]
hey i want to work on this , i want to Make my First Open Source Contribution. can i remove first Additional Resources ? help me .
