### ISSUE TITLE
(NodeJS) Getting Started: Many Links Are Broken

### ISSUE THREAD

**Issue by jasonHYLam** [TheOdinProject/curriculum#26582]
### Describe your suggestion

The links in the "Getting Started" NodeJS lesson are broken. I notice that the lesson states that it links 'directly to the markdown files on their GitHub repository', however for the assignment, many links are broken. 

Example: https://nodejs.org/en/learn/run-nodejs-scripts-from-the-command-line
![image](https://github.com/TheOdinProject/curriculum/assets/105083538/dae25e07-7e75-4471-8943-e73b1c7dce05)

The knowledge checks are fine and correctly link to the github rep markdown files. 
I propose that the broken links be replaced with the github repo links.

I have compiled a list of links which I believe are the correct links, however of course someone who is responsible for putting together the curriculum should have a check to see if they are appropriate. I'd be happy to implement these changes. 

![image](https://github.com/TheOdinProject/curriculum/assets/105083538/0d668969-708d-4f5f-835f-d7f3dc740404)
maybe should be:
https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/command-line/node-run-cli.en.md
+ all other links in that directory, except for the one on environment

![image](https://github.com/TheOdinProject/curriculum/assets/105083538/43b9e033-ee10-4867-a10a-1387552b8855)
maybe should be:
https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/command-line/node-environment-variables.en.md

![image](https://github.com/TheOdinProject/curriculum/assets/105083538/6100e872-b2ef-47d8-8caf-ac1ff81d574a)
maybe should be:
https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/node-js-modules/node-module-http.en.md

![image](https://github.com/TheOdinProject/curriculum/assets/105083538/c2cf908b-29a4-489c-bffb-e45e56fe2411)
maybe should be:
https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/manipulating-files/node-writing-files.en.md

![image](https://github.com/TheOdinProject/curriculum/assets/105083538/87d0323d-d89d-4619-a5b7-ec18bf72c67d)
maybe should be:
https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/manipulating-files/node-reading-files.en.md

![image](https://github.com/TheOdinProject/curriculum/assets/105083538/a5dbce63-181a-42bd-a74a-8aa3752f886c)
maybeshould be:
https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/node-js-package-manager/how-to-use-npm-package/index.en.md

![image](https://github.com/TheOdinProject/curriculum/assets/105083538/4c0ab089-90d6-4b8f-a12d-c293304a5d90)
maybe should be:
https://github.com/nodejs/nodejs.dev/blob/aa4239e87a5adc992fdb709c20aebb5f6da77f86/content/learn/node-js-modules/node-module-events.en.md

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-getting-started#knowledge-check

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

jaleel4792 , or prodijay

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Linked to the other issues about broken links. Can someone decide what we want to do about it.
