### ISSUE TITLE
How To Deal With Side Effects: Example Problem Not a Recommended Use of an Effect

### ISSUE THREAD

**Issue by columk1** [TheOdinProject/curriculum#26592]
### Describe your suggestion

The main example from the lesson is presented as a problem that we need an effect to solve:

```javascript
setInterval(() => {
    setCounter(count => count + 1)
  }, 1000);
```

The React Docs suggest using a conditional for this kind of problem. Using the following makes the counter render correctly and is simpler and less error prone than using an effect:

```javascript
if (counter === 0) {
    setInterval(() => {
      setCounter((count) => count + 1)
    }, 1000)
  }
```

My recommendation is that the lesson makes it clear that the counter is just an example to show students how effects can be used.

Furthermore, I noticed lots of unnecessary use of effects in submitted Memory Card projects. Using effects to respond to events, to state changes etc. Perhaps this stems from this lesson or from the Memory Card project brief which encourages their use.

If I'm wrong about the counter example and there is a good reason to use an effect here (could there be a memory leak with my method?) this reasoning should be mentioned in the lesson so that the benefits of the effect over a conditional are clear. The lesson should also remind students that effects should be used for very little else apart from syncing with an external store.

[React Docs - You Might Not Need an Effect](https://react.dev/learn/you-might-not-need-an-effect)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-how-to-deal-with-side-effects

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

columk

**Comment by iamashay** [comment]
From what I understand, we would need to cleanup the interval as well during unmount of the component in which useEffect is useful. With your code, I think, the interval will keep on running in the background even after the component has been unmounted causing unnecessary memory usage.

**Comment by columk1** [comment]
Ah, okay. I thought it might be garbage collected but if that's the case, using an effect makes sense. Thank you.
