### ISSUE TITLE
Odinbook (Node + Ruby): Facebook authentication now requires business verification to put app in live mode

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26597]
### Describe your suggestion

In the [Node OdinBook](https://www.theodinproject.com/lessons/nodejs-odin-book) and [Rails FP](https://www.theodinproject.com/lessons/ruby-on-rails-rails-final-project) projects, users are required to implement Facebook authentication (e.g. via Passport/OmniAuth etc.)

Unfortunately it seems back in March of this year, there was a [major policy change](https://www.linkedin.com/pulse/whats-new-app-developers-facebooks-recent-business-policy-bansal/) whereby Facebook requires live apps to be registered to a verified business (which requires uploading documents if business details could not be found).

As such, creating an app in the Meta dev portal only sets it to development mode, preventing it from being accessible/accessing the FB API once your server is deployed. During development mode, only whitelisted test accounts will work over localhost.

This has led to my [painfully headachey problem](https://discord.com/channels/505093832157691914/597796701650026517/1167600520572174476) where testing locally with my FB account (that's also my Meta dev account and so is whitelisted) works as intended, but any other FB account (so not on the whitelist) will not work locally. When the server is deployed, even with the appropriate whitelisted domains/OAuth redirect URLs set, no FB account (inc. mine) work at all (they return a 403 and an otherwise blank page with `Forbidden` on it, or sometimes a `App not active
This app is not currently accessible and the app developer is aware of the issue. You will be able to log in when the app is reactivated.` page).

The `App not active` error page is reached on many of the past submissions (both Node and Rails) which confirms this is an issue due to the business verification policy change earlier this year.

### The main point
Therefore, both pathways' Odinbook projects ought to have their spec changed to no longer require Facebook authentication, lest learners tear as much hair out as I have trying to figure out why things work locally but not deployed (and very little information about it is online due to it being a somewhat recent change - even the current information on it was difficult to find and the Meta docs/passport docs do not talk about it unless you go digging in the Meta docs).

Google OAuth2 also seems to require some kind of app/business verification for similar privileges.

Edit: `passport-github2` works in production and setting up a Github app was somewhat simple (very similar to how Facebook setup was, probably as simple as it used to be). I have not tested production with setting up an OAuth app via Github (either can be used) but given a skim of their docs, the process is very similar and I imagine it should work fine it the app was set up as an OAuth app instead of Github app.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-odin-book and https://www.theodinproject.com/lessons/ruby-on-rails-rails-final-project

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by bizarf** [comment]
I've implemented Github auth using passport-github2 and it's working. I think this should be the recommended auth to use due to how easy it is to setup as mentioned above. I was even able to reuse my Facebook auth coding in my app. 

I'm not sure if Twitter/X auth is a good alternative for anyone considering that. The free tier only allows 1 project and that 1 project can only have 1 app. passport-twitter also depends on express-session which the documentation never mentioned, so I gave up on dealing with that possible headache.

**Comment by MaoShizhong** [comment]
I'm not entirely sure if a 1:1 sub-out with `passport-github2` for `passport-facebook` would work since it doesn't include as much of/include the same sort of info that you could get from the Facebook API. But perhaps change the Facebook auth "requirement" to something more like
> You could consider adding additional authentication options on top of a simple username/password. There are many alternative authentication strategies out there. Facebook authentication requires business verification to use outside of a testing environment with whitelisted accounts so unfortunately you will not be able to use it in this project once you deploy it. However, as of writing this lesson, Github can be used in production for free and if you are already using Passport, implementing this will not require much code at all.

Perhaps a little less waffly but something among those lines?

**Comment by bizarf** [comment]
Oh yeah, I did have to tweak make some small tweaks, like the name field is optional for GitHub so it might not exist in the profile object that's returned. 

I would say that paragraph looks good. It clears up why older projects have Facebook auth, why it doesn't work now, and provides an optional solution for those looking for a working alternative auth.

**Comment by CouchofTomato** [comment]
@KevinMulhern 

Any thoughts on this mate?

**Comment by wise-king-sullyman** [comment]
I know I wasn't tagged on this but I'm a big fan of this suggestion.

Also I've recently set up GitHub OAuth for a work project and would be happy to review the PR for this if nobody is opposed to the switch.

**Comment by Asartea** [comment]
Note that the NodeJS part of this issue is already covered by #26758

**Comment by MaoShizhong** [comment]
@Asartea Awesome, forgot you were working on that!
Any plans to make a parallel for the Rails FP? Considering that for the most part it's the same as Odinbook but also that the Facebook auth issue will still be there in the instructions.

**Comment by Asartea** [comment]
>  Any plans to make a parallel for the Rails FP? Considering that for the most part it's the same as Odinbook but also that the Facebook auth issue will still be there in the instructions.

I mean, if its wanted, sure. I originally only filed the issue for NodeJS OdinBook because Rails already has a freeform build a website, but with the narrowing in scope I agree it would be an improvement to make the change on both projects.

@maintainers thoughts?

**Comment by wise-king-sullyman** [comment]
I would be in favor, but I'd want to hear from one of the @TheOdinProject/rails-path maintainers.

**Comment by KevinMulhern** [comment]
Sorry, just seeing I'm tagged in this. Yep, I think Github Oauth is the way to go for the Rails path too  🚀

**Comment by Asartea** [comment]
> Sorry, just seeing I'm tagged in this. Yep, I think Github Oauth is the way to go for the Rails path too 🚀

What do you think re: just copying the NodeJS rewrite (https://github.com/TheOdinProject/curriculum/pull/26758) to the Rails path?

**Comment by KevinMulhern** [comment]
Changing everything to more generic with "social media" instead of "Facebook"? - yep, I'd be very down for that.

**Comment by Asartea** [comment]
This can be closed; the above linked PR's have resolved it
