### ISSUE TITLE
Node JS - Authentication Basics: Add a link to Passport: The Hidden Manual

### ISSUE THREAD

**Issue by bizarf** [TheOdinProject/curriculum#26601]
### Describe your suggestion

Passport's documentation doesn't explain how it's functions work or what happens, and instead hopes that the user will either play around until it works or just accept what they've written. Someone wrote a document that provides the missing explanations which me and a few others have found useful. This document should be added to this lesson, so that others can benefit from it. I'm not sure where to place it though. Maybe it should go in the Additional Resources area?

https://github.com/jwalton/passport-api-docs

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-authentication-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

bizarf

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by 01zulfi** [comment]
@bizarf We can put the proposed resource in the Additional Resources section of the lesson. I've assigned the issue to you, please make a pull request
