### ISSUE TITLE
Javascript: Clearly state in 'Project: Battleship' that it's compulsory to create a system that let players place ships

### ISSUE THREAD

**Issue by radtradcath** [TheOdinProject/curriculum#26600]
### Describe your suggestion

Inside assignment steps for the Battleship project, it's not clear that creating a system to allow players to place their ships is mandatory.

> Section 4.2 states that "You **_can_** implement a system for allowing players to place their ships later.".

>Section 5.2 states that "You **_can_** polish the intelligence of the computer player by having it try adjacent slots after getting a ‘hit’.".

> Section 5.1 states that "There are several options available for letting users place their ships. You can let them type coordinates for each ship, or investigate implementing drag and drop."

Sections 4.2 and 5.2 have similar phrasing, leading learners to believe that both features are optional. But reaching 5.1, learners get the feel that implementing a system to allow players to place ships is actually needed.

I suggest a small rephrasing of 4.2 to remove this small conflict, clearly stating that it's compulsory:

> Section 4.2: "You **_are going to_** implement a system for allowing players to place their ships later.";

> Section 5.1: **_"Implement the system that allow players to place their ships._** There are several options available for letting users place their ships. You can let them type coordinates for each ship, or investigate implementing drag and drop."
### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

.radtrad

### (Optional) Additional Comments

Idea comes from this Discord discussion, starting from https://discord.com/channels/505093832157691914/505093832157691916/1166861020627738634

It was said that this wasn't the first time learners were confused about it.

**Comment by columk1** [comment]
Good point, I thought section 5 was all optional but looking back it reads more like 5.1 and 5.2 are mandatory and 5.3 is optional.

What about:

4.2: You ~~ can~~ **will** implement a system for allowing players to place their ships later.
5.2: "~~You can polish~~ **Polish** the intelligence of the computer player by having it try adjacent slots after getting a ‘hit’.

**Comment by radtradcath** [comment]
> Good point, I thought section 5 was all optional but looking back it reads more like 5.1 and 5.2 are mandatory and 5.3 is optional.
> 
> What about:
> 
> 4.2: You ~~can~~ **will** implement a system for allowing players to place their ships later.
> 5.2: "~~You can polish~~ **Polish** the intelligence of the computer player by having it try adjacent slots after getting a ‘hit’.
> 
> 

But the context, I don't think 5.2 is compulsory, only 4.2. That's why I didn't touch it. 

I placed the quotation to 5.2 in order to compare an optional task to a compulsory one. Let's see what maintainers say.

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Can someone take a look please.

**Comment by 01zulfi** [comment]
Sounds good, @radtradcath. I've assigned the issue to you, please make a pull request
