### ISSUE TITLE
Git Basics: Typo in Screenshot on Assignment Step 3 of Git Basics Page

### ISSUE THREAD

**Issue by elcharbs** [TheOdinProject/curriculum#26613]
### Describe your suggestion

On the Git Basics stage of the Foundations Course ([linked here](https://www.theodinproject.com/lessons/foundations-git-basics)), Step 3 of the "Create the repository" assignment has a typo.

The sentence is currently "Give your repository the name “git_test” in the repository name input field" however, the screenshot attached to this step says "git-test". Either the text or the screenshot ought to be updated. Super minor but flagging since it should be a quick fix :)

![Screenshot 2023-10-29 at 5 22 04 PM](https://github.com/TheOdinProject/curriculum/assets/60406297/7b6092ff-0580-4db0-84e1-63fdf0d6d263)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

elcharb

**Comment by Sumitwarrior7** [comment]
Can you assign me this issue , i want to work on it and contribute to this amazing project
