### ISSUE TITLE
Objects and Object Constructors: External learning resources are  deprecated

### ISSUE THREAD

**Issue by alexwittwer** [TheOdinProject/curriculum#26629]
### Describe your suggestion

The assignment and curriculum heavily references outdated .__proto__ and [[Prototype]] methods for getting prototype values, and insists that Object.prototype.example is best practices.

In fact, all of the learning material references it as such, but it gets messy trying to learn when you have three different names for things, and the learning material says to use a deprecated method like .__proto__

**Recommendation**: Source new material that explains the prototype property as its currently implemented and used in best practices, and only reference the old methods of calling prototype as a side note, like what is done with JQuery and ilk. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please.

**Comment by wise-king-sullyman** [comment]
Hey @alexwittwer thanks for making this issue.

Agree that if someone can find a resource that conveys the core concepts as well as the current resources without the baggage of the old (not best practice) ways of accessing prototype that would be ideal.

**Comment by kamranzafar4343** [comment]
I can contribute to this project with some guidance?

**Comment by fabulousgk** [comment]
Perhaps: https://dev.to/lawrence_eagles/understanding-prototypal-inheritance-in-javascript-4f31

**Comment by yuliana-r** [comment]
Is help still wanted on this one?

**Comment by lcarlo23** [comment]
On Javascript.Info there's a relatively new article that might be added right after the original assignment:
https://javascript.info/prototype-methods

It takes original examples from the assignment link but using the new methods explained in the lesson.
