### ISSUE TITLE
Installing Node.js: Add a command for Circumventing DNS level blocking enforced by some ISPs in India and some other countries.

### ISSUE THREAD

**Issue by ShubhayuGoswami** [TheOdinProject/curriculum#26637]
### Describe your suggestion

The line of code below is provided for installing the script that will run nvm installation

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash`

This however will not work in most cases if someone is using an ISP from India (my Case) or any other country that has ISP's blocking [https://raw.githubusercontent.com/](https://raw.githubusercontent.com/) at the DNS level.

The following line of code should be used in the terminal in order before beginning the installation process in order to circumvent such restrictions

`echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null`

Sources:-
[rachit77's comment](https://github.com/nvm-sh/nvm/issues/2392#issuecomment-1427623260)
[Alfredoeb9's comment](https://github.com/nvm-sh/nvm/issues/2392#issuecomment-1482066106)

That's all from my side.
Thanks & regards.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installing-node-js

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

shubhayugoswami

**Comment by CouchofTomato** [comment]
@xandora Can you offer your opinion on this one please mate.
