### ISSUE TITLE
Project: Battleship: Rewrite sentence about mocking appendChild

### ISSUE THREAD

**Issue by cakegod** [TheOdinProject/curriculum#26643]
### Describe your suggestion

The following sentence about mocking appendChild causes confusion about whether or not the odinite should test the DOM:

> You can use mocks to make sure that DOM methods like appendChild are being called, but try your best to keep those things outside of the app logic.

I would rewrite this sentence to explicitly mention that the odinite should NOT test the DOM.

### Path

Ruby & Node path

### Lesson Url

- Ruby path: https://www.theodinproject.com/lessons/javascript-battleship
- Node Path: https://www.theodinproject.com/lessons/node-path-javascript-battleship

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Cake

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript can someone review

**Comment by 01zulfi** [comment]
Agreed, Odinites shouldn't be testing the DOM in this project. @cakegod I've assigned you the issue, please make a pull request
