### ISSUE TITLE
NODE: Typo in google form survey on Admin Dashboard project page

### ISSUE THREAD

**Issue by joshunk** [TheOdinProject/curriculum#26648]
### Describe your suggestion

There are two typos in the Google Format the end of the Admin Dashboard project page. [Here](https://docs.google.com/forms/d/e/1FAIpQLSf_hNwIjvqcPZyl9Lx41mgJNQKp04qOro03SI8ABw4Zp7U_4w/viewform) 

"Your" should be updated to "You're"

"If your taking the Ruby on Rails path..."
"If your taking the JavaScript path..."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-admin-dashboard

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

sacrifice87

**Comment by DavidxDl** [comment]
Could i work on this?

**Comment by Swapnilnaique** [comment]
I'd like to work on this issue

**Comment by rlmoser99** [comment]
Actually these google forms are only editable by the maintainer team. I have updated these forms, so I will be closing this issue.
