### ISSUE TITLE
Asynchronous Code : Add video resource explaining JavaScript Promises

### ISSUE THREAD

**Issue by Ariech** [TheOdinProject/curriculum#26653]
### Describe your suggestion

While I was researching various resources to fortify my understanding of JavaScript Promises, I came across this [video](https://www.youtube.com/watch?v=TnhCX0KkPqs) that I found exceptionally helpful and clear. The video offers numerous examples and serves as an excellent introduction to the topic.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-asynchronous-code

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

Yaess

**Comment by rlmoser99** [comment]
Can someone on the @TheOdinProject/javascript team take a look at this?

**Comment by janaiscoding** [comment]
+1 for Color Code videos. Amazing series.

**Comment by CouchofTomato** [comment]
@Ariech 

Would you be happy to create a PR to add this. It will be easier to assign someone to review it from a PR than an issue.

**Comment by Ariech** [comment]
@CouchofTomato 

Sure thing, I can work on that. Although I can start on Monday, as I'm not available during the weekend, if that's not a problem :)

**Comment by Ariech** [comment]
@CouchofTomato Hey! Just a heads up, that I created PR for this issue
