### ISSUE TITLE
Foundations/HTML Foundations: Update lists per layout style guide

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#26664]
Lists should be updated in the following ways to align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md):

- Any unordered list items that are created with an asterisk `*` are replaced with a hyphen `-` instead. For example, `* A list item` should be updated to `- A list item`
- The list item content is updated so it only has a single space before it. For example, `1.   A list item` has 3 spaces before the list item content ("A list item"), and should be updated to `1. A list item`
- Appropriate punctuation is added at the end of each list item in the "Lesson overview", "Assignment", "Knowledge check", and "Additional resources" sections
  - Follow the [Google style guide ](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists) to determine when to add punctuation
- Any additional updates mentioned for specific lessons

### Guidance:

- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` keyword. 

### Lessons to update

- [x] @VMadhuranga  [Introduction to HTML and CSS](https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css)
- [x] @Swapnilnaique  [Elements and tags](https://www.theodinproject.com/lessons/foundations-elements-and-tags)
- [x] @brandonlopes  [HTML boilerplate](https://www.theodinproject.com/lessons/foundations-html-boilerplate)
- [x] @Khaled0P  [Working with text](https://www.theodinproject.com/lessons/foundations-working-with-text)
- [x] @Servante  [Lists](https://www.theodinproject.com/lessons/foundations-lists)
- [x] @VMadhuranga  [Links and images](https://www.theodinproject.com/lessons/foundations-links-and-images)
  - Update the ordered list under the "Absolute and relative links" heading to an unordered list, and add punctuation
- [x] @Servante  [Commit messages](https://www.theodinproject.com/lessons/foundations-commit-messages)
  - Add a period at the end of the list items before the "When to commit" section (where the first item begins, "Provides a subject that specifies..."
- [x] @Steliospne  [Project: Recipes](https://www.theodinproject.com/lessons/foundations-recipes)

**Comment by VMadhuranga** [comment]
I would like to help out here

**Comment by Swapnilnaique** [comment]
I'd like to work on this

**Comment by thatblindgeye** [comment]
@Swapnilnaique @VMadhuranga assigned you both a lesson!

**Comment by Swapnilnaique** [comment]
> @Swapnilnaique @VMadhuranga assigned you both a lesson!

I'd like to confirm that, this is what the issue is referring to : 
```
*...`<p>` is the opening tag.
*...`some text content` represents content wrapped within the opening and closing tags. 
*...`</p>` is the closing tag.
```
must be changed to 
```
*.`<p>` is the opening tag.
*.`some text content` represents content wrapped within the opening and closing tags. 
*.`</p>` is the closing tag.
```
In [/curriculum/foundations/html_css/html-foundations/elements-and-tags.md](https://github.com/TheOdinProject/curriculum/blob/main/foundations/html_css/html-foundations/elements-and-tags.md)

**Comment by thatblindgeye** [comment]
@Swapnilnaique yep!

**Comment by brandonlopes** [comment]
I'd like to give this a shot :)

**Comment by thatblindgeye** [comment]
@brandonlopes assigned!

**Comment by Khaled0P** [comment]
would like to give this a shot!

**Comment by Servante** [comment]
I'd like to help out if there are any left :)

**Comment by rlmoser99** [comment]
I'd like to add to this issue that any numbered lists should use lazy numbering
https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lazy-numbering

**Comment by thatblindgeye** [comment]
@Servante assigned you a lesson!

**Comment by VMadhuranga** [comment]
@thatblindgeye if you don't mind i can take another one

**Comment by thatblindgeye** [comment]
@VMadhuranga assigned you another one!

**Comment by Servante** [comment]
I'd be happy to take another as well if no one else is biting.

**Comment by thatblindgeye** [comment]
@Servante assigned you another one

**Comment by Swap2104** [comment]
If no one else wants to, then I can do another one

**Comment by Steliospne** [comment]
Would love to help for do the last one!

**Comment by thatblindgeye** [comment]
@Steliospne you can take on the last one!

@Swap2104 since you had worked on one already, just wanted to give another contributor an assign. thanks for volunteering, though! 😃
