### ISSUE TITLE
JavaScript course: Remove overly long note on Factories vs Classes

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#26675]
### Describe your suggestion

In the Classes lesson, the fifth bullet point in the [Assignment](https://www.theodinproject.com/lessons/node-path-javascript-classes#assignment) section links to content about factories vs classes (and really composition vs inheritance) in JavaScript. It comes with this note attached:
> [This article](https://medium.com/@rajaraodv/is-class-in-es6-the-new-bad-part-6c4e6fe1ee65) provides some pros and cons for classes. [FunFunFunction’s video on Composition over Inheritance](https://www.youtube.com/watch?v=wfMtDGfHWpA) elaborates on the cons mentioned in the article and does a great job of going over the topic. Many people think that class syntax is misleading for JavaScript and Inheritance is best avoided, and thus Factory Functions (from the previous lesson) that use Composition are inherently better. We are NOT saying that classes are bad or that inheritance should never be used! We just want you to be informed of the opinions of both sides.

In my opinion, everything after the first sentence of that note is unnecessary, and also confusingly worded. It seems that a lot of learners seem to especially trip up on "Many people think that class syntax is misleading for JavaScript and Inheritance is best avoided, and thus Factory Functions (from the previous lesson) that use Composition are inherently better". The intention of that sentence is for it to be one expression, but many people seem to read the second part after the comma as something TOP is saying, rather than the opinion of the people in the first half.

Removing everything but the first sentence would leave it as just:
> [This article](https://medium.com/@rajaraodv/is-class-in-es6-the-new-bad-part-6c4e6fe1ee65) provides some pros and cons for classes. [FunFunFunction’s video on Composition over Inheritance](https://www.youtube.com/watch?v=wfMtDGfHWpA) elaborates on the cons mentioned in the article and does a great job of going over the topic

This still gets the point across, without the pitfalls of the longer note

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-classes

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

asarta

### (Optional) Additional Comments

See eg [this Discord discussion](https://discord.com/channels/505093832157691914/505093832157691916/1170738395866218566)

**Comment by Ariech** [comment]
Hi! I'd like to pickup this task
Yaess

**Comment by Asartea** [comment]
^ Discussed this over on Discord; happy to cede this to them

**Comment by rlmoser99** [comment]
@Ariech Typically before working on a PR, you want to make sure a maintainer has reviewed this issue and moved it from "Needs Triage" to "Ready for work". 

Please review our contributing guide, especially this section.
https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#being-assigned-an-issue

**Comment by ManonLef** [comment]
Thanks for opening this issue @Asartea, I will look at @Ariech 's PR on this.
