### ISSUE TITLE
JS Computer Science: Mention running .js files in Node and import compatibility

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26679]
### Describe your suggestion

In the JS comp sci section, in the recursion project there is a small instruction for running your code in Node. At this point, that likely won't cause issues as the files will be small so most will likely have everything they need to run in a single file.

For Linked List to Knight Travails, if someone decides to use modules (e.g. separating their Node and LinkedList/BinarySearchTree functions/classes, or perhaps their "driver script" that tests their code), there is a chance they may encounter issues by trying to use ESM syntax where Node does not yet support it by default (either must use `.mjs` file extension or include a `package.json` with `"type": "module"` in it, for example).

Learners will not have learnt about commonJS syntax yet. Previously, some people have asked in Discord about an error they got due to running a `.js` file using ESM.

I propose in the Linked Lists project adding a small lesson note that says something like:

> By default, Node uses something called CommonJS modules and not ES6 modules meaning unless you configure it to do so, it will not be able to understand your ES6 import/export syntax. For simplicity here, keep everything in a single file.

In Node 21.x (current, not yet LTS), this behaviour is looking to change where they now have an experimental flag that will allow Node to automatically switch to ESM if it detects it being used in the file (unless it is told specifically to use CJS e.g. `.cjs`). An interesting thing to look out for in the future!

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-linked-lists

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by rlmoser99** [comment]
Can someone on the @TheOdinProject/javascript team review this issue please.

**Comment by 01zulfi** [comment]
@MaoShizhong, thanks for creating this issue.

I think we should enable our learners to create separate files as needed. We should add instructions on how they can use ES6 modules by using a `package.json` with `type="module"`. What do you think?

**Comment by MaoShizhong** [comment]
@01zulfi How does something like this sound?

> By default, Node uses something called CommonJS modules and will not recognise import/export syntax from ES6 modules. To use ES6 modules, you can either use the file extension `.mjs` instead of `.js`, or create a `package.json` file in the root of the project directory that contains `"type": "module"` (which will allow you to stick to `.js`). You can read more about the difference between ES6 modules and CommonJS modules [here](https://blog.logrocket.com/commonjs-vs-es-modules-node-js/).

**Comment by 01zulfi** [comment]
Your suggestions sounds good, but it lacks the instructions for executing es6 modules if they want to.

**Comment by MaoShizhong** [comment]
Then like as is mentioned in the recursion project, we can just add to run `node script_name.js` after doing whichever method.

> By default, Node uses something called CommonJS modules and will not recognise import/export syntax from ES6 modules. To use ES6 modules, you can either use the file extension `.mjs` instead of `.js`, or create a `package.json` file in the root of the project directory that contains `"type": "module"` (which will allow you to stick to `.js`). For example, if you had driver script written in a `script.js` file that imports things using ES6 module syntax, then after applying one of the methods above, you can then run it with `node script.js` (or `.mjs` if using that). You can read more about the difference between ES6 modules and CommonJS modules [here](https://blog.logrocket.com/commonjs-vs-es-modules-node-js/).

**Comment by 01zulfi** [comment]
@MaoShizhong, sounds good tome. The wording could be concise but we can discuss that in the PR. Assigned.
