### ISSUE TITLE
Fundamentals Part 1: <Short description of your suggestion>

### ISSUE THREAD

**Issue by abuel3zaym** [TheOdinProject/curriculum#26678]
### Describe your suggestion

The link to the variables tutorial is not working

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-1

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Asartea** [comment]
I can access it just fine (presuming you mean https://javascript.info/variables). Is it still not working for you?

**Comment by rlmoser99** [comment]
Same here. This link is working for me, as well.
