### ISSUE TITLE
Block and Inline: first bullet point broken link

### ISSUE THREAD

**Issue by renehoyosp** [TheOdinProject/curriculum#26694]
### Describe your suggestion

Learn layout website link is broken

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-block-and-inline

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

donsuero

**Comment by CouchofTomato** [comment]
@renehoyosp 

Can you confirm which link you're referring to please.

**Comment by Swap2104** [comment]
All the links are working I believe.

**Comment by CouchofTomato** [comment]
Closing as we haven't heard back
