### ISSUE TITLE
Introduction to HTML and CSS: Broken link in assignment/knowledge check section

### ISSUE THREAD

**Issue by Amer-Alic** [TheOdinProject/curriculum#26696]
### Describe your suggestion

In the "knowledge check" section there is a link for "What do HTML and CSS stand for" which is not working and when you open it, it says it is not a safe page.

https://brytdesigns.com/html-css-javascript-whats-the-difference/ now redirects to a registrar advert.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by xandora** [comment]
Thanks for reporting, we'll get it fixed up shortly.

**Comment by CouchofTomato** [comment]
Seems to be working now.

**Comment by dev-ameen007** [comment]
@Amer-Alic  The link is working now, check for yourself and close the issue.
