### ISSUE TITLE
Foundations/HTML Foundations: Update codeblock delimiters per layout style guide

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#26695]
Codeblocks should be updated to align with new changes in our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

In the lessons named in this issue, codeblocks will be opened by a set of 3 tildes (the `~` character) and then closed by another set of 3 tildes. To align with the style guide, these tilde characters need to change to backticks (the `` ` `` character). Be sure to refer to [the codeblocks section](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks) of the style guide for an example of what this should look like.

### Guidance:
- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx`, since this issue is divided into sections, individual PRs should **NOT INCLUDE** the `closes` keyword.

### Lessons to update
- [x] @tushar-droid [Elements and Tags](https://www.theodinproject.com/lessons/foundations-elements-and-tags)
- [x] @DavidxDl [HTML Boilerplate](https://www.theodinproject.com/lessons/foundations-html-boilerplate)
- [x] @SyndicateGit [Working with Text](https://www.theodinproject.com/lessons/foundations-working-with-text)
- [x] @Khaled0P [Links and Images](https://www.theodinproject.com/lessons/foundations-links-and-images)
- [x] @joayo13 [Commit Messages](https://www.theodinproject.com/lessons/foundations-commit-messages)
- [x] @danieletie [Project: Recipes](https://www.theodinproject.com/lessons/foundations-recipes)

**Comment by JoshDevHub** [comment]
@tushar-droid In the last issue, you said you'd like to work on one of these, but I couldn't assign you any because all the work was already taken for that issue.

If you'd like to pick up one of these lessons, comment here and let me know

**Comment by tushar-droid** [comment]
Hey @JoshDevHub, i would loveeeee to contribute and help please and thank you :)

**Comment by JoshDevHub** [comment]
Awesome @tushar-droid :raised_hands: 

I've assigned you the Elements and Tags lesson

**Comment by DavidxDl** [comment]
I never worked on a issue before, if this is a good one to start with please assign me to it!

**Comment by JoshDevHub** [comment]
Thank you for volunteering @DavidxDl 

I've assigned you to work on the HTML Boilerplate lesson.

**Comment by SyndicateGit** [comment]
Hey @JoshDevHub! New to open source contributions. I've read the contributing md and would love to take on one of these tasks!

**Comment by JoshDevHub** [comment]
Welcome to contributing to open source @SyndicateGit 

I've assigned you the Working With Text Lesson

**Comment by DavidxDl** [comment]
@JoshDevHub can u help me? i did my pull request hours ago #26702 is there somthing wrong or i just have to wait? cause i saw others people PRs pass before main :(

**Comment by Khaled0P** [comment]
would love to help out!

**Comment by JoshDevHub** [comment]
Thank you for volunteering @Khaled0P 

I've assigned you the Links and Images lesson

**Comment by joayo13** [comment]
Hey, I'd like to help out with one of the lessons. : )

**Comment by danieletie** [comment]
Hey, I'd love to help with the lessons as well.

**Comment by JoshDevHub** [comment]
Absolutely @danieletie 

Assigned you to the Project: Recipes lesson :+1:

**Comment by ardamoin** [comment]
Hi. I'd like to contribute if the task is not assigned to anyone.

**Comment by danieletie** [comment]
> Absolutely @danieletie 
> 
> Assigned you to the Project: Recipes lesson :+1: 

Hello @JoshDevHub,
Do you think you could help take a look at my PR at your earliest convenience please. 

Thank you very much🙏🏿

**Comment by JoshDevHub** [comment]
Good work everyone :rocket:
