### ISSUE TITLE
React: Introduction to React: Poor Reading Assignment 

### ISSUE THREAD

**Issue by columk1** [TheOdinProject/curriculum#26717]
### Describe your suggestion

The quality of the assignment 4 article is very poor. It is an exemplar of bad SEO writing, with keywords prioritized over content. Some examples: 

(All of the following lines are in the assigned article, most of them headings)

“The benefits of ReactJS and reasons to choose it for your project"
"With so many companies using React JS including some of the top brands in the whole world, React must be offering some extraordinary benefits, right?"
"What are the key benefits of React JS that encouraged so many businesses and popular brands to use it?"
"Key benefits of react js for front-end development"
"React JS offers tons of benefits. Let’s see the key benefits of React JS to understand why it stands out from other front-end development frameworks."
"13 Reasons why react js can be the best choice for your project"
"Below we mention the top reasons why React JS can be the best framework for your project.”

Pretty shocking! You can see why it's the top result on Google. I found it really hard to read.

I suggest replacing it with the following Geeks for Geeks article: https://www.geeksforgeeks.org/what-are-the-advantages-of-react-js/

It's much shorter but the quality is better. It lists 8 benefits and then expands on them concisely. The current assignment lists more benefits but the Geeks for Geeks post combines some of these into one. I think it's a lot clearer and easier to read.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

columk

**Comment by KevinMulhern** [comment]
@TheOdinProject/react any thoughts on this?

**Comment by 01zulfi** [comment]
@columk1 sounds good to me. Please create a pull request.
