### ISSUE TITLE
React: Add another reminder in Keys that props will be covered

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#26722]
### Describe your suggestion

In the keys lesson I feel it would be beneficial that props will be covered in the next lesson like it is hinted at in the lesson before. Just to make sure the learner does not focus too much on what is happening with passing data but just keys instead. 

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-keys-in-react

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mfrayray

**Comment by 01zulfi** [comment]
@Baguirre03 Sounds good, please create a pull request
