### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by nidafarooqui** [TheOdinProject/curriculum#2672]
The link for "Mighty Spring - get matched to startup jobs" at http://www.theodinproject.com/getting-hired-as-a-web-developer/collecting-job-leads is broken.

**Comment by kriox26** [comment]
@KevinMulhern @muzfuz Any alternatives to this website or should we remove it??

**Comment by nidafarooqui** [comment]
I'm sure there are lots of alternatives but I was wondering why you guys didn't mention https://angel.co/jobs? Is that on purpose?

**Comment by muzfuz** [comment]
I say we remove the broken link.  Happy to put up anything else that is helpful, though someone should vet it to make sure they accept Junior developers - not all hiring platforms do.
