### ISSUE TITLE
Common Data Structures and Algorithms: <Broken link in additional resources>

### ISSUE THREAD

**Issue by EssenceCode** [TheOdinProject/curriculum#26724]
### Describe your suggestion

in the additional resources section there is a link "Another free course on algorithms by Udacity" when you open it, it is showing a error **404 not found**.
**Link:**
[https://www.udacity.com/course/cs215](url)
**Screenshot:**
![Screenshot 2023-11-12 101111](https://github.com/TheOdinProject/curriculum/assets/118383162/d20d1e2f-e1c0-4825-9cc3-e257f364bbbd)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-common-data-structures-and-algorithms

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by Swapnilnaique** [comment]
I'd like to work on this.
I'm not quite sure, but i think it is referring to this course
https://www.udacity.com/course/intro-to-algorithms--cs215

**Comment by leonardo-vic3nte** [comment]
@Swapnilnaique 
Judging by te name, it seems it is the correct one.

I would also like to work on this fix, if possible.

**Comment by 01zulfi** [comment]
Thanks for creating this issue @EssenceCode and thanks for wanting to work on it @leonardo-vic3nte 

@Swapnilnaique That looks like the correct link. Since you commented earlier, I'll assign this issue to you. Please create a pull request

**Comment by 01zulfi** [comment]
@Swapnilnaique This change will be needed for two lessons across separate paths

1. https://www.theodinproject.com/lessons/ruby-common-data-structures-and-algorithms
2. https://www.theodinproject.com/lessons/javascript-common-data-structures-and-algorithms
