### ISSUE TITLE
Commit Messages: Rephrase sentence for clarity

### ISSUE THREAD

**Issue by Gwynim** [TheOdinProject/curriculum#26723]
### Describe your suggestion

There is a typo in the additional resources section - "While the Yarn and creating releases information might not be immediately necessary for Foundations, **you don’t need to worry about it for now**. So, feel free to explore and enhance your commit messages and development workflow."

The bold section does not complete the part of its sentence before the comma, nor does it effectively transition into the following sentence. There is missing information on the importance of mentioning Yarn and creating releases, such as if this information is relevant for future lessons or use cases outside The Odin Project.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-commit-messages

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by MaoShizhong** [comment]
Agreed. In fact, I feel that entire paragraph is quite strangely worded:
> Explore this amazing tutorial video on Conventional Commits ➔ [Full Video Link](https://www.youtube.com/watch?v=OJqUWvmf4gg). The video showcases best commit message practices, including Yarn (a package manager) and creating releases. While the Yarn and creating releases information might not be immediately necessary for Foundations, you don’t need to worry about it for now. So, feel free to explore and enhance your commit messages and development workflow.

I feel something more along the lines of
> Explore this amazing tutorial video on Conventional Commits ➔ [Full Video Link](https://www.youtube.com/watch?v=OJqUWvmf4gg). The video showcases the Conventional Commits template from the resource above. It also mentions creating releases and shows using something called "Yarn". These two parts are out of scope for this part of the course, so don't worry about them and instead focus on the commit template.

would be more appropriately worded, given the context it's in.

**Comment by JoshDevHub** [comment]
I agree this is worded strangely.

What you've changed it to in your message above reads quite nicely though @MaoShizhong. Since the OP has indicated they don't want to work on this, would you be interested in making the change?

**Comment by MaoShizhong** [comment]
@JoshDevHub If OP doesn't want to them I'll happily make the change. It'll be a quick PR to open for review

**Comment by JoshDevHub** [comment]
I've assigned you @MaoShizhong :rocket:
