### ISSUE TITLE
<NodeJS>: <MongoDB University assumes user already has mongo installed>

### ISSUE THREAD

**Issue by Royuin** [TheOdinProject/curriculum#26727]
### Describe your suggestion

In the 4th lesson of MongoDB University the course assumes that the user already has mongo installed but there's no mention of installing it on theodinproject or the University course before this. I think we should have the commands shown to the user so they can install before beginning the course or, linking to the install page for Ubuntu on MongoDB. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-to-mongodb

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

royuin

**Comment by 01zulfi** [comment]
@Royuin Can you share a link or a screenshot where this requirement is mentioned? When I did the course a while back, they don't require you to install anything locally. All of the course takes place in their in-browser environment

**Comment by Royuin** [comment]
@01zulfi It's in the installing mongoDB compass section. 

Link: https://learn.mongodb.com/learn/course/connecting-to-a-mongodb-database/lesson-3-connecting-to-a-mongodb-atlas-cluster-with-compass/learn?client=customer&page=2

![Screenshot from 2023-11-15 08-02-21](https://github.com/TheOdinProject/curriculum/assets/77414756/b2a634eb-c82e-4644-8e64-ac2dc45cdcf1)

**Comment by 01zulfi** [comment]
Looks like this is a new section. @TheOdinProject/javascript, how do we handle this?

**Comment by xandora** [comment]
@01zulfi Looks like this part of the course is just going through multiple ways to connect to MongoDB Atlas. We could probably just note to skip the Compass section.

**Comment by 01zulfi** [comment]
@xandora sounds good

@Royuin Are you available to incorporate the above suggestion?

**Comment by Royuin** [comment]
@01zulfi Yes, I am!

**Comment by 01zulfi** [comment]
@Royuin Assigned
