### ISSUE TITLE
Node.JS (Mini-message board): Add step to connect messages to MongoDB

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#26720]
### Describe your suggestion

In the deployment section of Node.JS this is the first point in the assignment ->

> Deploy your [Mini Message Board project](https://www.theodinproject.com/lessons/nodejs-mini-message-board) to one of the hosting providers we’ve mentioned. If you need help deciding which one to use, we recommend Fly.io in conjunction with MongoDB Atlas for your database. The important thing to take away from this first deployment is getting experience deploying. Don’t worry if you don’t understand everything that’s happening. That will come with time.

Although after completing the `mini-message-board` project there is never instructions to connect the `messages` to MongoDB. I think that there should be a step that the messages are connected and used from MongoDB and not just for the session. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-mini-message-board

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mfrayray

### (Optional) Additional Comments

We <3 open source

**Comment by Baguirre03** [comment]
Gentle bump :) Id like to not have users. have their username and password out on github if possible!

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look please

**Comment by 01zulfi** [comment]
@Baguirre03 thanks for creating this issue. 

I'm debating whether we need to have learners connect a database to this project at all. What do you think?

**Comment by Baguirre03** [comment]
@01zulfi - hmm, why so? This is after the MongoDB lesson and is kind of the point of a message board? Being able to see past messages and not just chat to yourself no?

**Comment by MaoShizhong** [comment]
Closing as superceded by the Node revamp milestone 1 release
