### ISSUE TITLE
Foundations/CSS Foundations & Flexbox: Update codeblock delimiters per layout style guide

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#26738]
Codeblocks should be updated to align with new changes in our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

In the lessons named in this issue, codeblocks will be opened by a set of 3 tildes (the `~` character) and then closed by another set of 3 tildes. To align with the style guide, these tilde characters need to change to backticks (the `` ` `` character). Be sure to refer to [the codeblocks section](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks) of the style guide for an example of what this should look like.

### Guidance:
- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx`, since this issue is divided into sections, individual PRs should **NOT INCLUDE** the `closes` keyword.

### Lessons to update
- [x] @Swapnilnaique [Intro to CSS](https://www.theodinproject.com/lessons/foundations-intro-to-css)
- [x] @leonardo-vic3nte [The Cascade](https://www.theodinproject.com/lessons/foundations-the-cascade)
- [x] @janaiscoding [The Box Model](https://www.theodinproject.com/lessons/foundations-the-box-model)
- [x] @Servante [Axes](https://www.theodinproject.com/lessons/foundations-axes)

**Comment by Swapnilnaique** [comment]
I'd like to help here

**Comment by JoshDevHub** [comment]
Awesome @Swapnilnaique :raised_hands: 

Assigned you the Intro to CSS lesson

**Comment by leonardo-vic3nte** [comment]
I'd like to help !

**Comment by JoshDevHub** [comment]
Thank you for volunteering @leonardo-vic3nte 

I've assigned you the lesson on The Cascade

**Comment by janaiscoding** [comment]
Hey, this wouldn't be a first issue for me, but if it's okay I would also like to help on this! 😊

**Comment by JoshDevHub** [comment]
Thank you for volunteering to help @janaiscoding 

This is marked as a good first issue so first time contributors know that it'll be approachable, but that doesn't mean it's for first time contributors only.

So it's absolutely okay for you to take one these on. I've assigned you The Box Model lesson.

**Comment by Servante** [comment]
I'd like to help if needed

**Comment by JoshDevHub** [comment]
Thank you for volunteering @Servante :raised_hands: 

I've assigned you the Axes lesson in the section on flexbox.

**Comment by JoshDevHub** [comment]
Explicitly assigning those of you who are working / have worked on this. This is just for logging purposes, and doesn't mean you have anything left to do if you've already submitted your PR.
