### ISSUE TITLE
Managing State With The Context API: There’s a typo in the snippet

### ISSUE THREAD

**Issue by LaythAlqadhi** [TheOdinProject/curriculum#26739]
### A typo in the snippet

There's a typo in the snippet, exactly in the line `<div class="cart-icon">{cartItemsCount}</div>`, where it should be `<div className="cart-icon">{cartItemsCount}</div>`.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-managing-state-with-the-context-api

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@LaythAlqadhi that definitely is a typo. Please create a pull request
