### ISSUE TITLE
PaaS Deployment: Add adaptable.io as a suggested PaaS

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26731]
### Describe your suggestion

Several PaaS are suggested in the deployments lesson when either pathway reaches backend material. 3/4 of these have free plans but have some kind of limitation on them (understandable) be that hour/credit limit or number or free apps allowed. Heroku also no longer has a free tier like it used to.

I propose adding [Adaptable](https://adaptable.io/) as another suggested PaaS. I have deployed 7 free apps on it (some backend API only, some with view templates (e.g. inventory app/members only etc.) and have not encountered app/credit limitations. The process of deployment was also very smooth, pretty much the same as Render/Railway (web interface - sign in and connect to repo then add environment variables in a settings tab). Their idle wake times have been faster than Render in my experience too (a nice thing though a minor point for the course's purposes).

All in all, if feels kind of like how Heroku was back in the day and for now, has not shown plans to change that structure (who knows what will happen in the future...). Perhaps to avoid throwing too many PaaS at learners in that lesson, Adapatable could replace Heroku in that list?

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-deployment and https://www.theodinproject.com/lessons/ruby-on-rails-deployment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Mao

**Comment by JoshDevHub** [comment]
It looks like they may not have support for Ruby/Rails? At least there's nothing in the docs about it and it lacks a "deploy template" (unless you count managing the deploy from a Dockerfile, which I don't).

It's pretty awesome if it doesn't have the limitations of the other free services though. Does it require a credit card number even if you only intend to use the free tier? That'd be a big plus if it doesn't imo.

**Comment by MaoShizhong** [comment]
> It looks like they may not have support for Ruby/Rails? At least there's nothing in the docs about it and it lacks a "deploy template" (unless you count managing the deploy from a Dockerfile, which I don't).
> 
> It's pretty awesome if it doesn't have the limitations of the other free services though. Does it require a credit card number even if you only intend to use the free tier? That'd be a big plus if it doesn't imo.

That's actually a huge oversight, good catch!
I also cannot see anything for Rails deployment on their site/docs and definitely don't consider a Dockerfile appropriate for the course. Perhaps we could get someone with a rails app to quickly test it to see if a template is even needed? From the way to docs has it, I wouldn't think so without Docker but it wouldn't hurt to try.

For Node it's been amazing and I do not recall grabbing my credit card for it at all (it should only ask for a credit card when you actually make a subscription to a paid plan).

**Comment by 01zulfi** [comment]
The free plan sounds good, +1 on its inclusion

**Comment by MaoShizhong** [comment]
@01zulfi Since adaptable does not support Rails without docker (and so out of the scope of the curriculum), would you still feel it worth including with a Node-only note?

**Comment by JoshDevHub** [comment]
I just remembered that the latest version of Rails generates a Dockerfile when the project is initialized. This is the version of Rails that learners use in the curriculum.

When I have the time, I can look and see if I can get a working Rails deploy up with no (or maybe very minimal) manual work with the generated Dockerfile.

**Comment by MaoShizhong** [comment]
Thank you, Josh. I'm ignorant of Rails stuff so I appreciate the help when you're able to!

**Comment by KevinMulhern** [comment]
Sorry to interject, but I thought it was worth mentioning that the Rails and Node deployment lessons are separate files. Mostly because of scenarios like this where there are better options out there for each stack.

If the Docker Rails deploy doesn't work it, it shouldn't be an issue to update just the Node lesson.

**Comment by MaoShizhong** [comment]
@KevinMulhern That's awesome, thank you for the clarification. I'll await Josh's experiment since there's no rush on the Node end either (already got good options) and then update accordingly.

Would people think it more sensible to replace heroku in the deployment list or to add it as a new option?

**Comment by JoshDevHub** [comment]
@KevinMulhern Thank you for interjecting :laughing: 

Yeah in that case, maybe we can just plow forward with adding this for node. I might still give it a test drive later with rails, but I think it'll always be susceptible to changes that could occur in the app's dependencies (ie. needing `vips` or `imagemagick` to run ActiveStorage, or needing redis for background jobs or websockets, etc). If some change like that happens, the Dockerfile would need to be updated, and this just sounds out of scope for our learners.

**Comment by MaoShizhong** [comment]
I'll pop a PR in for the Node deployments tonight. Shall I replace Heroku or add it as a new option?

**Comment by JoshDevHub** [comment]
> I'll pop a PR in for the Node deployments tonight. Shall I replace Heroku or add it as a new option?

I'll defer to a javascript maintainer on that one. @TheOdinProject/javascript
