### ISSUE TITLE
Etch-a-sketch: Be even more explicit about using flex and not grid

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26732]
### Describe your suggestion

[Recent Discord discussion](https://discord.com/channels/505093832157691914/505093832157691916/1173712007531335700) raised some good ideas about the current Etch-a-Sketch project's instructions. Despite having been changed already to remove mentions of CSS grid and suggest practising flexbox, I've still seen plenty of people in the server talk about/suggest/struggle with using Grid because they've tried to learn it by themselves, especially after having (naughtily) looked at past submission code which did use grid (due to a different curriculum structure at the time).

[A good suggestion](https://discord.com/channels/505093832157691914/505093832157691916/1173713616281800804) was made to replace some of the wording to try and not subliminally hint at using "grid". In addition, I'd also propose adding a small mention to use flexbox and *not* use CSS Grid (as opposed to simply suggesting it would be a good time to practice flexbox), which apparently plenty have interpreted that as just a suggestion. So they jump to use grid if/when they struggle with flexbox.

Thoughts?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-etch-a-sketch

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by fabulousgk** [comment]
I think this is great.  Learners really need to use flex here to master the tool.  Not only does using grid cause complications, but it takes away from an important learning opportunity.

I agree about being explicit "This exercise is for you to practice your flex-box skills, successful projects will use this."  Something along those lines, but better.

**Comment by 01zulfi** [comment]
what do we do with our naughty learners 😆 

@MaoShizhong @fabulousgk The suggestion sounds good. Instruction 2.3 has a Flexbox mention, we could just rephrase that instruction to be more imposing on our learners to use Flexbox and not other alternatives they might find on Google i.e. CSS Grid. Thoughts?

**Comment by MaoShizhong** [comment]
@01zulfi I'm definitely in agreement with rewording that current flexbox "suggestion". Wouldn't have originally thought it'd need being made more explicit but evidently discord interactions have shown otherwise.

**Comment by 01zulfi** [comment]
@MaoShizhong Go for it!
