### ISSUE TITLE
Node Path Object Constructors: Returning closured variable instead of intended instance property

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#26737]
### Describe your suggestion

In one of the code [examples](https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors#object-constructors) on this lesson:
The constructor has a method `sayName` that logs `name` instead of `this.name`. 
While this is syntactically valid, it returns the argument the constructor was called with via closure, instead of the intended instance's name property. This goes unnoticed until one changes the name property of the instance, and then observes the disparity.

Steps to reproduce:
```
function Player(name, marker) {
  this.name = name;
  this.marker = marker;
  this.sayName = function() {
    console.log(name)
  };
}
const player1 = new Player('steve','X')
player1.sayName() // 'steve'
player1.name = 'paul'
player1.sayName() // still 'steve' but you would expect it to be 'paul'
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Damon

### (Optional) Additional Comments

[The learner who noticed, and the conversation that followed](https://discord.com/channels/505093832157691914/513125308757442562/1173975606086615073)

**Comment by 01zulfi** [comment]
@damon314159 Sounds good, please create a pull request
