### ISSUE TITLE
Introduction to Web Development: <Short description of your suggestion>

### ISSUE THREAD

**Issue by terr0r-exe** [TheOdinProject/curriculum#26759]
### Describe your suggestion

Towards the end of this page, there's a link ->[“Why Learning to Code is So Damn Hard”](https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/). This link leads to a 404 page.
![2023-11-17 18_55_18-404 — Page not found — Mozilla Firefox](https://github.com/TheOdinProject/curriculum/assets/109326404/0c4f0e7b-4adf-4a2d-9091-8fa5d7eb86a3)

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
Thank you for creating this issue. This has already been reported and will be resolved shortly: https://github.com/TheOdinProject/curriculum/issues/26753
