### ISSUE TITLE
Introduction to Web Development: https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/ Link Not Found

### ISSUE THREAD

**Issue by nicholsansley** [TheOdinProject/curriculum#26753]
### Describe your suggestion

The link is broken for: https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/

(last paragraph of this section)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@nicholsansley, thanks for creating this issue, I was able to find the webpage using the Wayback Machine: https://web.archive.org/web/20230630111131/https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/

I'm opening this up for contribution. Acceptance Criteria:

- [ ] Replace broken link with the link I commented above

If anyone wants to work on this, please comment below to be assigned

**Comment by JohnMikko27** [comment]
I would like to work on this!

**Comment by DavidxDl** [comment]
i could do it!

**Comment by 01zulfi** [comment]
@JohnMikko27 You are assigned, please make a pull request.

@DavidxDl Thanks for taking interest in contributing!
