### ISSUE TITLE
How To Deal With Side Effects: Switch additional resources links order

### ISSUE THREAD

**Issue by radtradcath** [TheOdinProject/curriculum#26756]
### Describe your suggestion

Additional Resources in "How to Deal With Side Effects" from React course are in incorrect positions. The anchor that includes `....again from Epic React` should be last. Also, there's a comma missing after the end of it.

![image](https://github.com/TheOdinProject/curriculum/assets/138630339/e25931ce-a14b-4c3d-90fb-fcc8681f6e8a)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-how-to-deal-with-side-effects

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@radtradcath Sounds good to me, please make a pull request
