### ISSUE TITLE
Linked Lists: Project Clarification

### ISSUE THREAD

**Issue by aconstas** [TheOdinProject/curriculum#26761]
### Describe your suggestion

Should we clarify whether students are expected to build this project just from reviewing all provided materials? Or do students need to do more outside research into building this project?

It seems like from the resources provided up until the project, there is not enough information on JavaScript syntax relating to building a Linked List.

The resources cover syntax but in [Java](https://web.archive.org/web/20200217010131/http://www.cs.cmu.edu/~adamchik/15-121/lectures/Linked%20Lists/linked%20lists.html).

I think adding some clarification could ease student self-doubt and anxiety.

i.e "You will need to do some independent research to successfully complete this project." or "You should be able to hack this up after completing the previous lessons."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-linked-lists

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

aconstas

**Comment by 01zulfi** [comment]
@aconstas I'm not sure I understand what you're saying. All the JavaScript syntax required to build a Linked List is already covered in the curriculum prior to this lesson. Classes, functions, variables, etc should be familiar to the learners. I'd love to know your thoughts, thanks

**Comment by aconstas** [comment]
@01zulfi 
Thank you for your response!

I appreciate the comprehensive coverage of JavaScript syntax in the curriculum. However, I noticed a potential area for enhancement regarding the implementation of linked lists. Specifically, I realized through further research that properties like .next, .head, .tail, and .prev are not reserved JavaScript keywords or built-in syntax, but rather common conventions in linked list implementations. This wasn't immediately clear to me during the lesson, which led to some confusion.

To assist learners who might face a similar challenge, I propose adding an 'Additional Resources' section. This section could include articles or guides that explicitly clarify these conventions and their use in linked list implementations. For instance, resources like:

    [Beginner's guide to Linked List in JavaScript](https://dev.to/judis07/beginners-guide-to-linked-list-in-javascript-31cf)
    [Implementation of LinkedList in JavaScript](https://www.geeksforgeeks.org/implementation-linkedlist-javascript/)

These resources could provide valuable insights for learners, ensuring a clearer understanding of how linked lists are structured in JavaScript. Or, perhaps there can be this clarification within the text of the lesson.

I look forward to hearing your thoughts on this suggestion. Thank you!

**Comment by KevinMulhern** [comment]
From a cursory glance over those resources, those resources seem to be walk throughs of how to do the Linked List project?

**Comment by aconstas** [comment]
@KevinMulhern Now that I'm looking over the lesson again and the resources provided, I think that this is probably a non-issue, more of a slight confusion on my part with how the resources in Java can translate to JavaScript. Going to close this issue!
