### ISSUE TITLE
JavaScript: Clearer example on Prototypal inheritance with factories

### ISSUE THREAD

**Issue by Gaberinoo** [TheOdinProject/curriculum#26771]
### Describe your suggestion

The code in the `Prototypal inheritance with factories` creates a new object that will always have a reputation of 0 since its calling on the `createUser` factory function to create a new object instead of using the one that was previously created. I suggest changing it to: 

```
 function createPlayer (createUserObj, level) {
   const { name, discordName, getReputation } = createUserObj;
 
   const increaseLevel = () => level++;
   return { name, discordName, getReputation, increaseLevel };
 }
```

Or if the intention is just to show that you can use properties already present in an already existing factory:

```
function createPlayer (name, level) {
  const { discordName, getReputation, giveReputation } = createUser(name);

  const increaseLevel = () => level++;
  return { name, discordName, getReputation, giveReputation, increaseLevel };
}
```

This way the student can pass the `josh` object created above in the lesson as the argument and it will have its properties and the `getReputation` method will work as intended, I believe this change could help clarify the intention of extending the factory.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Can someone take a look please.

**Comment by wise-king-sullyman** [comment]
Thanks for submitting this!

Agree that it's a bit confusing at the moment. I think your second suggestion is more in line with the lesson intent, but that part of the intent was to show that in doing so you can hide some properties as well. Maybe add `giveReputation` but take `discordName` away?
