### ISSUE TITLE
Introduction to HTML and CSS: <Short description of your suggestion>

### ISSUE THREAD

**Issue by rudygl1999** [TheOdinProject/curriculum#26782]
### Describe your suggestion

Several references to HTML and CSS being programming languages in the material. It's just a detail, but since it is the foundations course, it is not ideal to put those terms in the material, as they might cause confusion later on to the students. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by BaoNguyen09** [comment]
So how can I help to address this issue?

**Comment by xandora** [comment]
I'm not sure what the issue you are reporting is. We are very upfront in that lesson with the distinction that HTML and CSS aren't *technically* programming languages.

In fact, we have this paragraph in the very lesson you linked to:

> Many great resources out there keep referring to HTML and CSS as programming languages, but if you want to get technical, labeling them as such is not quite accurate, because they are only concerned with presenting information.

Could you clarify what you mean with some examples perhaps?

**Comment by KevinMulhern** [comment]
Thanks for reporting @rudygl1999, but I think the label we provide on the lesson should be enough. But, If you can find a better resource definitely feel free to make a PR.
