### ISSUE TITLE
Recursion: Remove Fibonacci 1-liner comment

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26780]
### Describe your suggestion

In both pathways' recursive fibonacci assignments, there is a small comment that the recursive solution can be done in just a few or even a single line. Even though it then says to not consider those requirements, this comment just feels very "un-TOP-like" and I can 100% see some people just seeing the comment as a potential challenge which is unproductive to do (and not a skill you'd want to be seeing much in production code anyway).

I propose to simply remove this comment from the assignments, so the instruction simply states to write the same function from the previous step using recursion, and that's it.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursion & https://www.theodinproject.com/lessons/ruby-recursion

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

**Comment by Swap2104** [comment]
I'd like to help here

**Comment by MaoShizhong** [comment]
If approved, happy for @Swap2104 to be assigned instead.
The line will need to be removed in both the JS recursion project file and the Ruby one.

**Comment by JoshDevHub** [comment]
I agree that it's very un-TOPish. Most one liners I see for this also have terrible performance.

Thanks for bringing this up @MaoShizhong :raised_hands: 

I've assigned you to work on it @Swap2104. I might recommend just removing the entire 2nd sentence for the 2nd item in the Fibonacci assignment.

**Comment by Swap2104** [comment]
@MaoShizhong  Thank you for giving me this opportunity, sorry I did not see the "Would like to work on this issue"  checked.

**Comment by MaoShizhong** [comment]
@Swap2104 No problem. It's always good to check to make sure but it was only a simple thing to do so no problem letting you take it :+1:
