### ISSUE TITLE
The Asset Pipeline: Inconsistency of links in the 'Knowledge Check' section with the Assignment.

### ISSUE THREAD

**Issue by MKMaths22** [TheOdinProject/curriculum#26786]
### Describe your suggestion

The Assignment in this lesson is to read sections 1-3 of the Rails Guides On The Asset Pipeline, however in the 'Knowledge Check' section, the links for 'How do you include an asset in your views or layout' and 'What does the require tree method do in a manifest-file' both take us to section 4 of the Rails Guide.
Either these links go to the wrong destination, or the Assignment should include section 4; this is an inconsistency.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-the-asset-pipeline

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/rails-path thoughts?

**Comment by MKMaths22** [comment]
Hi, I'm not sure what to say, is there something not clear about my suggestion? Two of the links at the bottom of the lesson go to section 4 of the Rails Guide, which does not seem to make sense when the Assignment is to read sections 1 to 3.

**Comment by ChargrilledChook** [comment]
@wise-king-sullyman @MKMaths22 The issue seems to have been caused by the most recent rails guides re-ordering the content (the links are essentially the same, but they used to be in section 2). Changing the reading to sections 1 - 4 seems like a good quick fix.

An example of the old structure https://guides.rubyonrails.org/v6.1/asset_pipeline.html#coding-links-to-assets

**Comment by wise-king-sullyman** [comment]
@MKMaths22 to be clear: I don't think there was anything unclear about your suggestion.

I was triaging your issue and requesting input from the Rails team as I've been out of Rails for a few years now and had no idea if the proper resolution would be changing the assignment or changing the knowledge checks.

Sounds like changing the assignment is the right path, thanks @ChargrilledChook! And thanks for reporting @MKMaths22!

**Comment by Ahm3rIjaz** [comment]
Hi, I would like to work on this if this not fixed yet.
