### ISSUE TITLE
Introduction to Web Development: <Short description of your suggestion>

### ISSUE THREAD

**Issue by n13lluss** [TheOdinProject/curriculum#26788]
### Describe your suggestion

The last link “why coding is so damn hard” doesnt work

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
Thanks for reporting - duplicate of https://github.com/TheOdinProject/curriculum/issues/26753
