### ISSUE TITLE
React Router: code walkthrough is confusing

### ISSUE THREAD

**Issue by NomadiCxac** [TheOdinProject/curriculum#26793]
### Describe your suggestion

Out of all the lesson modules, this was the only one where I felt like the (more accurately; "my perceived") intended outcome did not match up with the actual outcome of the walkthrough project. I had thought that the final result was supposed to show a fully working "/profile" page with links to display either a default / popeye or spinach.  I had read the lesson top to bottom and followed all the code step by step, but had to stop after the last line of coding examples.

I thought that because I saw the path configuration lead to an error page and did not see the Popeye / Spinach pages or even have links to display them, I had not followed the lesson correctly.

Suggested Change:

It would be nice to put a disclaimer or something that is blatantly obvious / idiot (me) proof to denote that after the routing refactor; we have handled the bad path and compartmentalized our code but have to wire up the pages.
OR
Prompt/Notify the TOP-Student that it is up to them to make the paths work. Preferably in the conclusion section, as the 1st assignment task OR anywhere immediately after the last code example.

Additional Note:

I know that task # 2 prompts the student to action this:
Go and add a few new routes to the application we created above; playing around with it is the best practice. Consider deleting it completely and rewriting it for practice.

However, I find it hard to move onto the assignment section if I "feel" like I haven't "correctly" followed the code/read along above.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-react-router

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

TOP IS AWESOME

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/javascript thoughts?

**Comment by 01zulfi** [comment]
@NomadiCxac, thanks for creating this issue. I agree, we could improve the wording, looks like it's already being worked on in https://github.com/TheOdinProject/curriculum/pull/27043

**Comment by 01zulfi** [comment]
resolved with https://github.com/TheOdinProject/curriculum/pull/27043
