### ISSUE TITLE
Git Basics: git-test typo

### ISSUE THREAD

**Issue by GTSaketh** [TheOdinProject/curriculum#26791]
### Describe your suggestion

There is a typo in Git Basics: Assignment https://www.theodinproject.com/lessons/foundations-git-basics#assignment

In 3rd point it says "Give your repository the name “git-test” in the repository name input field."

While in 7th point it says "To test this, you can cd into the new git_test folder that was downloaded"

Since git_test presents in another line and other screenshots aswell.

My Recommendation is to change 3rd point in Assignment to:-

"Give your repository the name “git_test” in the repository name input field."
Also need to change the sreenshot below this point.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

gtsaketh

**Comment by Swap2104** [comment]
Would like to help

**Comment by wise-king-sullyman** [comment]
It looks like #26813 addresses the text component of this issue but not the screenshot, @Swap2104 since you asked to help on this issue already would you like to update the screenshot?

**Comment by Swap2104** [comment]
@wise-king-sullyman  I'd be happy to help
