### ISSUE TITLE
Rock Paper Scissors: <Winning condition clarification>

### ISSUE THREAD

**Issue by Steliospne** [TheOdinProject/curriculum#26797]
### Describe your suggestion

Hey, I am going through the curriculum as we speak and I noticed that at the project of Rock-Paper-Scissor it's a bit unclear if the game should end after 5 wins of either the computer or the player or if it's a best out of 5. 

> Use the previous function inside of this one to play a 5 round game that keeps score and reports a winner or loser at the end.

I interpret that as a best out of 5 rounds. Most of the solutions I see from other people including the top ones, take the other approach and they check if the player or the computer won 5 times.

I think just a small clarification will fix this.

You have done an amazing job so far I am really grateful.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-rock-paper-scissors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

codinggoat

**Comment by lohikaarme** [comment]
I would like to help out and be assigned this task.

**Comment by wise-king-sullyman** [comment]
I also took it to mean best out of 5, clarification here definitely doesn't seem like a bad idea.

Thanks @Steliospne!
