### ISSUE TITLE
Foundations/JavaScript Basics: Update codeblock delimiters per layout style guide

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#26794]
Codeblocks should be updated to align with new changes in our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

In the lessons named in this issue, codeblocks will be opened by a set of 3 tildes (the `~` character) and then closed by another set of 3 tildes. To align with the style guide, these tilde characters need to change to backticks (the `` ` `` character). Be sure to refer to [the codeblocks section](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks) of the style guide for an example of what this should look like.

### Guidance:
- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx`, since this issue is divided into sections, individual PRs should **NOT INCLUDE** the `closes` keyword.

### Lessons to update
- [x] @janaiscoding [Fundamentals Part 1](https://www.theodinproject.com/lessons/foundations-fundamentals-part-1)
- [x] @Steliospne [Fundamentals Part 3](https://www.theodinproject.com/lessons/foundations-fundamentals-part-3)
- [x] @cl8396 [Problem Solving](https://www.theodinproject.com/lessons/foundations-problem-solving)
- [x] @Chinchilla15 [Understanding Errors](https://www.theodinproject.com/lessons/foundations-understanding-errors)
- [x] @Swap2104 [Project: Rock Paper Scissors](https://www.theodinproject.com/lessons/foundations-rock-paper-scissors)
- [x] @Ashish-Krishna-K [Installing Node.js](https://www.theodinproject.com/lessons/foundations-installing-node-js)
- [x] @lohikaarme [Clean Code](https://www.theodinproject.com/lessons/foundations-clean-code)
- [x] @dmaret [DOM Manipulation and Events](https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events)

**Comment by janaiscoding** [comment]
Hello. Would be more than happy to help updating any lesson if that's okay! 😁

**Comment by JoshDevHub** [comment]
Awesome @janaiscoding 

I've assigned you Fundamentals Part 1

**Comment by Steliospne** [comment]
Hey! I would love to make my first contribution by updating Fundamentals Part 3.

**Comment by JoshDevHub** [comment]
Awesome @Steliospne . Very glad to have first time contributors :raised_hands: 

I've assigned you Fundamentals Part 3. Let me know if you need any help with anything.

**Comment by cl8396** [comment]
Hi, I'd be up for updating a lesson - dealer's choice

**Comment by JoshDevHub** [comment]
Thank you for volunteering @cl8396 

I've assigned you the Problem Solving lesson.

**Comment by JoshDevHub** [comment]
Awesome new @Chinchilla15 

I've assigned you the Understanding Errors lesson

**Comment by Swap2104** [comment]
Would be happy to help here if it's ok.

**Comment by JoshDevHub** [comment]
@Swap2104 Thank you for volunteering

I've assigned you the Rock Paper Scissors project.

**Comment by Ashish-Krishna-K** [comment]
Hi, I would like to make my first contribution by helping with this issue.

**Comment by JoshDevHub** [comment]
Thank you for volunteering @Ashish-Krishna-K 

I've assigned you the Installing Node.js lesson

**Comment by lohikaarme** [comment]
I would like to help out and be assigned a task.

**Comment by JoshDevHub** [comment]
Awesome @lohikaarme ! Thank you for volunteering.

I've assigned you the Clean Code lesson.

**Comment by dmaret** [comment]
Hi! If the DOM Manipulation and Events lesson hasn't been assigned to anyone yet, I'll give it a try.

**Comment by JoshDevHub** [comment]
Glad to give that lesson to you @dmaret 

Thank you for volunteering.

**Comment by JoshDevHub** [comment]
Thanks for contributing everyone :raised_hands:
