### ISSUE TITLE
Int. HTML/CSS: Clarify "stance" on learning CSS frameworks/preprocessors at this point

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26810]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the current lesson on CSS frameworks/preprocessors, the lesson states:

> You should be aware that, at this point in your learning, both frameworks and preprocessors are options for you, but that neither of them is necessary.

However, much of the given advice by many (including those part of the TOP team) about trying to learn any of these during the course, especially earlier on where the lesson is, advises against doing so and to prioritise learning fundamentals through vanilla CSS.
This is both due to vanilla CSS being the shared foundation for all of those, allowing for a more experienced user to learn whatever framework they need whenever, but also because several professionals have shared that they were asked about/tested on framework/preprocessor knowledge in interviews very few if any times (even when the tech was used in the job listing). This is a stance I personally agree with.

I feel the current wording of the lesson conflicts a little with this common advice. I feel it reads a little more like a "if this interests you, feel free to learn them yourself going forward" thing and less a "these are what they are just so you know, but we advise to focus on fundamentals via vanilla CSS". Somewhat often, people will come to the discord server and ask about whether it's appropriate for them to start learning bootstrap or tailwind etc. for the course going forward, so to me, that supports this current framing of the lesson.

If the stance would be better off focusing more on advising developing fundamentals and the lesson simply more being to make aware of those technologies, I propose rewording some of the parts to be more explicit with that.

---

Side notes:
- The opening paragraph states `Through your experiences, you have no doubt encountered a CSS framework or two.` which I don't believe is accurate for a good portion of people and could benefit from being reworded or even just removed.
- The 2nd paragraph in the preprocessors section states `CSS preprocessors are extensions to vanilla CSS that provide some extra functionality such as nesting, mixins, and variables.` which is also slightly inaccurate as CSS now natively has nesting (80% browser support and rising fast) and variables (which has already been taught before this lesson). This little bit would also benefit from being updated.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-frameworks-and-preprocessors & https://www.theodinproject.com/lessons/intermediate-html-and-css-frameworks-and-preprocessors

**Comment by wise-king-sullyman** [comment]
Agree with you on all points here, thanks @MaoShizhong!
