### ISSUE TITLE
Link your discord account to your github 

### ISSUE THREAD

**Issue by nworahsamking** [TheOdinProject/curriculum#26826]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

i cant even login on my discord account , if i want to login what am seeing is that my account has been disabled after 30 seconds of registering .

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community

**Comment by KevinMulhern** [comment]
Sorry your having trouble, but this isn't an issue on our end. [Discord support](https://support.discord.com/hc/en-us) is your best bet.
