### ISSUE TITLE
Ruby: Debugging Lesson

### ISSUE THREAD

**Issue by Wong-WS** [TheOdinProject/curriculum#26835]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

On Ubuntu updates/upgrades
"sudo apt update
sudo apt upgrade"

clarified that for Mac users is not necessary to do this step

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-debugging

**Comment by KevinMulhern** [comment]
Thanks for reporting @Wong-WS.

@TheOdinProject/rails-path, correct me with if I'm wrong. But I think this open ssl issue only affected Ruby 3.1 and has been fixed? we can remove those instructions in [this content](https://www.theodinproject.com/lessons/ruby-debugging#debugging-with-pry-byebug)?

**Comment by Wong-WS** [comment]
I’m not sure because I didn’t experience any issue with open ssl when doing
the course, I’m reporting the issue is because this part of the course
didn’t say clearly that Mac user don’t need to do it. This is only
applicable to Ubuntu users.
