### ISSUE TITLE
Foundations: Clarify image dimension info

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#26841]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the section on img size in the CSS lesson, we give an example and encourage its use:

```img {
  height: auto;
  width: 500px;
}
```

Then we have a paragraph that somewhat explains the issue around page jumps when loading.  But the way it is currently written, I think is confusing.  To me the paragraph is saying that we should use the auto syntax to prevent jumps, but this is incorrect.

In fact, this is the reason we added the encouragement to always specify dimensions in HTML.  In order for auto to function without page jumps you must specify the HTML attributes.

I think we need to clarify this paragraph to make clear we are saying that height and width need to be specified in the HTML.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### (Optional) Discord Name

therealpibbles

**Comment by A-Kiwams** [comment]
Can I work on it?

**Comment by KevinMulhern** [comment]
With the PR being closed, I assume this can be closed too @fabulousgk?

**Comment by fabulousgk** [comment]
@KevinMulhern This is actually for a related but separate issue.

**Comment by KevinMulhern** [comment]
Sorry @fabulousgk, my mistake. I should looked a

**Comment by KevinMulhern** [comment]
Whats your thoughts on this @TheOdinProject/html-css?

**Comment by fabulousgk** [comment]
A little bump

**Comment by 01zulfi** [comment]
@fabulousgk, thanks for creating this issue.

> It’s best to include both of these properties for <img> elements, even if you don’t plan on adjusting the values from the image file’s original ones. When these values aren’t included, if an image takes longer to load than the rest of the page contents, the image won’t take up any space on the page at first, but will suddenly cause a drastic shift of the other page contents once it does load in. Explicitly stating a height and width prevents this from happening, as space will be “reserved” on the page and will just appear as a blank space until the image loads.

Doesn't this paragraph mention it clearly that we need both height and width to tackle layout shift? What changes do you have in mind?

**Comment by fabulousgk** [comment]
@01zulfi The thing is, auto will only prevent that layout shift if height and width were provided as attributes on the HTML

This may be somewhat esoteric...but

> These properties work in conjunction with the height and width attributes in the HTML. It’s best to include both of these properties and attributes for image elements, even if you don’t plan on adjusting the values from the image file’s original ones. When these values aren’t included, if an image takes longer to load than the rest of the page contents, it won’t take up any space on the page at first but will suddenly cause a drastic shift of the other page contents once it does load in. Explicitly stating a height and width prevents this from happening, as space will be “reserved” on the page and appear blank until the image loads.

**Comment by 01zulfi** [comment]
@faddaful Nice, I did not know that. I'll leave the issue to someone from @TheOdinProject/html-css

**Comment by codyloyd** [comment]
I think this would be an acceptable addition here, as long as it doesn't create further confusion.  I say go for it @fabulousgk 👍🏽
