### ISSUE TITLE
Installations: WSL2 Proper Installation

### ISSUE THREAD

**Issue by arnnv** [TheOdinProject/curriculum#26846]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the curriculum, in Step 1.1, we enable 'Windows Subsystem for Linux' in 'Windows Features.' However, attempting to run 'wsl --install' in Step 1.2 will not work because it detects the Linux subsystem as already installed. It is advised to skip enabling WSL in Step 1.1 and proceed directly to Step 1.2 instead.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

**Comment by Asartea** [comment]
Done in https://github.com/TheOdinProject/curriculum/pull/26849

**Comment by KevinMulhern** [comment]
Thanks @Asartea
