### ISSUE TITLE
Intermediate HTML and CSS Course: Update codeblock delimiters per layout style guide

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#26842]
Codeblocks should be updated to align with new changes in our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

In the lessons named in this issue, codeblocks will be opened by a set of 3 tildes (the `~` character) and then closed by another set of 3 tildes. To align with the style guide, these tilde characters need to change to backticks (the `` ` `` character). Be sure to refer to [the codeblocks section](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#codeblocks) of the style guide for an example of what this should look like.

### Guidance:
- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx`, since this issue is divided into sections, individual PRs should **NOT INCLUDE** the `closes` keyword.

### Lessons to update
- [x] @helenanisic [SVG](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-svg)
- [x] @leonardo-vic3nte [More Text Styles](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles)
- [x] @dmaret [Advanced Selectors](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors)
- [x] @Chinchilla15 [CSS Functions](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-css-functions)
- [x] @janaiscoding [Custom Properties](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-custom-properties)
- [x] @riarsdev [Form Basics](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics)
- [x] @Steliospne [Creating a Grid](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-creating-a-grid)
- [x] @leonardo-vic3nte [Positioning Grid Elements](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-positioning-grid-elements)
- [x] @aconstas [Advanced Grid Properties](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties)

**Comment by helenanisic** [comment]
Hey, I would be happy to work on this.

**Comment by leonardo-vic3nte** [comment]
Would not be my first contribution, but i would love to help as well, if possible.

**Comment by JoshDevHub** [comment]
Thank you for volunteering @leonardo-vic3nte 

The "good first issue" tag is just to let people know that it's approachable. It doesn't mean that this is only for first time contributors.

So you're very welcome to contribute for this! I've assigned you the More Text Styles lesson :+1:

**Comment by dmaret** [comment]
I'd love to help contribute!

**Comment by JoshDevHub** [comment]
Great @dmaret 🙌 

I've assigned you the Advanced Selectors lesson.

**Comment by Chinchilla15** [comment]
Hi there! Would love to contribute again if that's okay :)

**Comment by JoshDevHub** [comment]
Thank you for volunteering @Chinchilla15 

I've assigned you the CSS Functions lesson

**Comment by riarsdev** [comment]
I'm interested in contributing to this issue, count me in!

**Comment by leonardo-vic3nte** [comment]
I can contribute more if it is possible

**Comment by JoshDevHub** [comment]
Thank you all for volunteering :raised_hands:

@riarsdev I'm assigning you the Form Basics lesson

@Steliospne I'm assigning you the Creating a Grid lesson

@leonardo-vic3nte  I'm assigning you the Positioning Grid Elements lesson

**Comment by aconstas** [comment]
@JoshDevHub Hi Josh! I was searching through the codebase and found some more areas using "~~~" instead of the backticks. Do you think I can create an issue for some of these? I can create the issues by lesson and open it up to others willing to contribute as this issue had done. Curious to hear your thoughts :)
-Alex
![image](https://github.com/TheOdinProject/curriculum/assets/82304192/c60d1e6a-7e90-456c-81b5-59026a1c39bb)
(search for "~~~")

**Comment by JoshDevHub** [comment]
@aconstas Thanks for knocking the databases section out :muscle: 

If you'd like to make an issue, go for it! I only have a few requests:
- Let's start doing the JavaScript content next. Maybe start with an issue on the Organizing Your JavaScript Code section
- Try to copy the template I've used for these issues.
- Make sure you tag me with @ in the issue. This is just so I can follow development and be notified when people participate and can merge their PRs.

**Comment by aconstas** [comment]
@JoshDevHub Thanks Josh! Sounds great. I'll get on it!
