### ISSUE TITLE
React: Setting Up A React Environment: Mention broken repo in one of the assignment articles

### ISSUE THREAD

**Issue by CCeph** [TheOdinProject/curriculum#26853]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the [guide for React Developer Tools](https://www.pluralsight.com/guides/debugging-components-with-react-developer-tools) assignment article, there is an [example repo](https://github.com/ChrisDobby/pluralsight-guide-react-dev-tools) that is used to explain how to use the react dev tools.

The article does not give any links to a hosted webpage, so I assumed it intends for you to clone the repo and locally host it to follow along with the guide. However, when you do that and follow the instructions in the documentation, you encounter an error and can't host the page. You need to run "npm audit fix --force" in order to fix the issue. Then the page compiles with an error because babel-eslint is missing, so I installed it separately.

I think that these extra hoops should be mentioned in the assignment section as it took quite a while for me to fix this issue. I spent more time trying to get the repo to work than reading the article. Otherwise, maybe find another article to link, or mention that the repo is not needed to avoid people going down a rabbit hole.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

### (Optional) Discord Name

cceph

**Comment by KevinMulhern** [comment]
Pinging @TheOdinProject/react

**Comment by 01zulfi** [comment]
@CCeph, thanks for creating this issue.

We're using an archived version of that article in the lesson. I think we should just replace it with another resource. I've found these resources promising:

- https://www.debugbear.com/blog/react-devtools
- https://www.toptal.com/react/debugging-react-developer-tools

Please go through them and replace the current resource with any of these two. I've assigned this issue to you.

**Comment by CCeph** [comment]
@MaoShizhong Sorry for the late reply. Would it be a problem if this issue is assigned to someone else?

**Comment by MaoShizhong** [comment]
@CCeph No problem at all! I'll open this up for assignment again.

**Comment by yuliana-r** [comment]
@MaoShizhong you can assign this to me, thanks :)
