### ISSUE TITLE
Node.js: Move security configuration lesson up

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#26851]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I believe that this security lessons should be moved up in the curriculum. At this point people will have been using MongoDB and have to use their key to connect to it. We hint at using DotEnv previously, but I think it would be beneficial just to include it. These projects are most likely being pushed to github and  we shouldn't want them to figure it out on their own (even if its simple) and have their username and password shown in a public place. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-security-configuration

### (Optional) Discord Name

mfrayray

### (Optional) Additional Comments

we <3 open source

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @Baguirre03. @TheOdinProject/javascript can we get your thoughts on this please?

**Comment by 01zulfi** [comment]
@Baguirre03, thanks for creating an issue.

I think there could be value in moving this lesson earlier. Do you have a place in mind?

**Comment by Baguirre03** [comment]
Yeah. Depending on if you feel we should add the MongoDB connection to mini-message board, I think it should come right after or preferably before that lesson. Considering people are going to be looking it up anyway if they are pushing to github, _or_ thye. are leaving their key exposed in their code

**Comment by Baguirre03** [comment]
Gentle bump since it really is not a huge change :) , lesson is short and pretty important. Understand yall are busy though!

**Comment by MaoShizhong** [comment]
#28381 will resolve this when revamp milestone 1 gets released.
