### ISSUE TITLE
Fundamentals Part 4: <Short description of your suggestion>

### ISSUE THREAD

**Issue by AaronGulman** [TheOdinProject/curriculum#26863]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I have to constantly go through “solutions” while doing the “Javascript-exercises “(Fundamentals Part 4) because there are things that are not even taught during the course , like ,for instance , rest arguments that are used in the following :

// we have 2 solutions here, an easier one and a more advanced one.
// The easiest way to get an array of the rest of the arguments that are passed to a function
// is using the rest operator. If this is unfamiliar to you look it up!

const removeFromArray = function (array, ...args) {

  // create a new empty array

  const newArray = [];

  // use forEach to go through the array

  array.forEach((item) => {

    // push every element into the new array
    // UNLESS it is included in the function arguments
    // so we create a new array with every item, except those that should be removed

    if (!args.includes(item)) {
      newArray.push(item);
    }
  });

  // and return that array
  return newArray;
};

// A simpler, but more advanced way to do it is to use the 'filter' function,
// which basically does what we did with the forEach above.

// var removeFromArray = function(array, ...args) {

//   return array.filter(val => !args.includes(val))

// }
//

module.exports = removeFromArray;
“ I don’t even remember ever encountering (…args)  in any of the classes that are included in the course.

https://www.w3schools.com/js/js_arrays.asp
https://www.w3schools.com/js/js_array_methods.asp

The two links are included in the lesson that is right before "Fundamentals Part 4” ,none of which include anything about .filer or “…args”. Though I think I remember coming across .filter. I absolutely love the Odin Project. It is amazing. However, I am a bit disappointed that I was asked during the course to do something I was never taught in the first place.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-4

**Comment by KevinMulhern** [comment]
Thanks for reporting @AaronGulman. There is a comment in the exercise that addresses this
```
is using the rest operator. If this is unfamiliar to you look it up!
```

Some of the solutions we have are aimed at exposing learners to different approaches. Filter should be the solution most learners naturally go for because its taught in the MDN article we link on the lesson https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#map_and_filter
