### ISSUE TITLE
JavaScript: Replace articles with substandard English

### ISSUE THREAD

**Issue by evangd** [TheOdinProject/curriculum#26864]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I've noticed a few articles in the Full-Stack JavaScript course written by authors whose English grammar is not quite up to snuff. I understand that many programmers come from countries where English may not be their primary language, or even one taught in school, and that many TOP students have a native language other than English, but I think that the course materials need to be held to a higher standard. The articles I've noticed so far are:

[This one](https://dev.to/tomekbuszewski/module-pattern-in-javascript-56jm)
[And this one](https://dmitripavlutin.com/gentle-explanation-of-this-in-javascript/)

Especially considering that these particular articles involve making very subtle but specific distinctions between the various approaches they are comparing, I think it would be best if they were replaced with resources whose grammar is clear enough not to further confuse students.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#factory-functions

**Comment by KevinMulhern** [comment]
Thanks for reporting @evangd. They don't seem too bad to me. But if we can find good alternative, replacement resources it would make this issue actionable..

**Comment by evangd** [comment]
I was mostly curious to see if anyone had the same feelings I did about these articles, but if they work for the vast majority of students, then I see no reason to change them. Thanks for your response.

**Comment by CouchofTomato** [comment]
Closing this out because it seems like a change isn't needed at this time. We can reopen if necessary.
