### ISSUE TITLE
HTML Boilerplate: Google Chrome not installed in WSL

### ISSUE THREAD

**Issue by Platundi** [TheOdinProject/curriculum#26862]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It tells to use google-chrome command to open html file but chrome is not installed in wsl.
Installation Lesson WSL2 instruction tell you to install Google by visiting download page, which is not possible through WSL CLI, or atleast not described how to do that. Only possible after following the Linux instructions for installing Google.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-html-boilerplate

**Comment by Asartea** [comment]
Just tagging myself to remind me to look at this later; I think there's a reason we did what we did

**Comment by 01zulfi** [comment]
@Platundi, thanks for creating this issue.

@TheOdinProject/installations, can someone take a look please.

**Comment by Asartea** [comment]
Sorry, I forgot to look at this: from my memory, several people (I know I did at least) encountered issues with running a browser via WSL (mine would keep crashing). We could try and figure out if there is a workaround for this; alternatively, I think `explorer.exe file` should open an HTML (or well anything Windows considers browsery) file in the user's default browser, which I think would be the easier way to deal with this

**Comment by AirDevil188** [comment]
I've been helping in tech help channels on Discord, and I have also noticed that several people get stuck on this. 

We troubleshoot and solve this by making Linux GUI apps run  on the Windows Subsystem with the help of this article:

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

and pointing to the Google Chrome section there.

But as Asartea already pointed out, I think that for the people that are really just beginners It would be a lot easier for them to just run Google Chrome  with explorer.exe index.html command. 

But also, then we must make sure that everyone's default browser is Google Chrome.

**Comment by nguyenlekhtn** [comment]
My opinion is it's not right to force learners to change their their default browser to a specific one, just to follow our curriculum. I think the other choice is better.

**Comment by AirDevil188** [comment]
Maybe I just found even better and easier solution:

Why not just make a alias that leads to the path of Chrome?

So in Ubuntu terminal user can type: 
alias chrome ="/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe"

And then, just use 
chrome index.html 

this would open up Chrome from the Ubuntu terminal without changing the default browser.

**Comment by Mclilzee** [comment]
By using the command `explorer.exe .` the file system will open up, and the student will only have to drag their HTML file to their browser. I find this solution good enough for now, until later where they start working with live servers like webpack and stop requiring to open a single HTML file into the browser.

**Comment by kamranzafar4343** [comment]
I want to contribute to it with little guidance!

**Comment by Mclilzee** [comment]
I have been working on a script that should create a function to get the google-chrome installed on windows to work

you can check the script here https://github.com/Mclilzee/arch-config/blob/main/bin/google-chrome.sh

I will just need to create that script on TOP repo and link to that one instead of my personal repo. But for now you can test it out using the link to my repo by copying and pasting this command into your WSL Terminal.

```bash
source <(curl https://raw.githubusercontent.com/Mclilzee/arch-config/main/bin/google-chrome.sh) && source ~/.bashrc
```

After running the command, you should have `google-chrome` functioning properly.

**Comment by Asartea** [comment]
It worked for me (after I made a small adjustment because I don't run a fully installations compliant setup)

**Comment by Asartea** [comment]
Another option that was [raised on Discord today](https://discord.com/channels/505093832157691914/1179839248803844117/1199375394764238848) is `wslview` as part of the `wslu` package. This is supposedly installed on all WSL2 Ubuntu's*, and allows an user to open a file in their default browser by using `wslview <file-name>`. I think this has my preference over the earlier options, both because its less of a black box and because its officially supported (and therefore should continue to work)


* But I didn't have it, so not sure how much we can trust that: we can always add a step to check if it works and otherwise use `sudo apt install wslu` to install it

**Comment by adhilkhan2023** [comment]
i have checked if wslview is working for me, and it's working for me and i can open .html files from wsl2 in my default browser.

**Comment by Asartea** [comment]
This remains one of the leading causes of questions in #wsl-view: could we perhaps decide on a course of action? My personal preference goes to using `wslview`, as it doesn't rely on using Bash to do magic.

**Comment by Asartea** [comment]
poking @Mclilzee @xandora

**Comment by Mclilzee** [comment]
@Asartea I'm curious, why do you believe `wslview` would be better than the script provided above? When I tested it out, it acted the same as `explorer.exe` which opens a file in your default browser, and for me, I also had to install it separately. What changes does it provide that isn't present in `explorer.exe`?

**Comment by Samusear** [comment]
I just used @Mclilzee script and it worked fine I don't want to change by default browser to chrome and shouldn't have to follow this course. I just ran into this problem and after about half an hour of searching this was the only thing I could find that actually fixed the issue; whereas everything else I read just said well use this instead like `wslview` or `explorer.exe` . If this is a known problem it should be addressed in the curriculum if people can't get the foundations down they are going to give up early.

**Comment by dimenoste** [comment]
A summary of the options to open a file on a browser through wsl : 

**Option 1** 
wslview index.html

**Option 2** 
explorer.exe index.html

While these options will change your default browser on windows, this one lets you **specify the browser you want to use** but it is more verbose  : 

**Option 3** 
>export BROWSER="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
>"$BROWSER" file://wsl$/Ubuntu/home/dime/html-boilerplate/index.html
it is more verbose that just doing "explorer.exe"

**Comment by asukmana** [comment]
hi guys

this works for me [https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
but imo this not for a beginner
for beginner use $explorer.exe index.html

**Comment by ManonLef** [comment]
@xandora giving you a tag since I think you know most about WSL, but correct me if I'm wrong :)
