### ISSUE TITLE
i don't know why my discord invite won't accept

### ISSUE THREAD

**Issue by Obinazo** [TheOdinProject/curriculum#26898]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

help me

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community

**Comment by fabulousgk** [comment]
@Obinazo what happens when you try to join the server?

**Comment by fabulousgk** [comment]
Can you try this one please: https://discord.gg/theodinproject

**Comment by JoshDevHub** [comment]
Sorry you're having difficulty joining. If the issue persists, try direct messaging `ModMail#5460` on discord to contact our team of moderators for support.

I'll be closing this issue because it's not a problem with the curriculum. Hope to see you soon in the discord server :+1:
