### ISSUE TITLE
Working with APIs: Suggesting a new Weather API tool due to some recent complaints observed on the Discord chats.

### ISSUE THREAD

**Issue by Advaitmenon1106** [TheOdinProject/curriculum#26897]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

#### Why?<br></br>
When I started The Weather App project, I found that despite no syntax errors existing in my project, the API wasn't fetching results due to an issue from their end and logged errors instead of the expected Promise on the console. Moreover, I was not able to sign in to Weather API to access their documents, my API Key, etc.

On further probing, I found that, of late, people in the Discord community have been reporting similar issues with the sign-in process. 

Keeping these hindrances in mind, I decided to surf for better alternatives to Weather API, and this "better alternative" came in the form of Visual Crossing and its API: https://www.visualcrossing.com/

#### Salient features:- <br></br>
> The Timeline Weather API is the simplest and most powerful way to retrieve weather data. You can request data over any time window including windows that span the past, present, and future. The API will take care of the combining historical observations, current 15-day forecasts, and statistical weather forecasts to create a single, consolidated dataset via a single API call.

Source: https://www.visualcrossing.com/resources/documentation/weather-api/timeline-weather-api/

- Well-written documentation (linked above).
- Inbuilt query builder which can help the users recognise how their fetch URLs need to be structured for accurate results.
- 1000 API calls per day in the free tier (which, in my opinion, is more than sufficient for a TOP project constructed to make its learners learn how Promises/Async work(s) in JS.
- Works on the same lines as the current Weather API, so there is very little that needs to be done in terms of the steps, beyond some minor modifications.
- No need to add a payment method for a £0 "transaction" (free tier) unlike the top Google search result for the search "Weather API", the result being: https://openweathermap.org/api, which wastes people's time by asking them to fill in their details and then proceeds to ask for payment details.

![image](https://github.com/TheOdinProject/curriculum/assets/94791117/ca69ab96-2fe6-4534-b1bb-1a4f5245d6ea)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis

### (Optional) Discord Name

Advait (a_v_it)

### (Optional) Additional Comments

Props to jeliotj (discord: Jeliotj) for suggesting a Github issue. Admittedly, I did not give a second thought as to the estimate of the number of people who would be facing the same issue as me, until they mentioned the dicey nature of weatherap.com- which is when I decided to bother looking into the Discord chat history to see for myself.

**Comment by JoshDevHub** [comment]
Thoughts on this one? @TheOdinProject/javascript

**Comment by 01zulfi** [comment]
@Advaitmenon1106, thanks for creating a well-researched issue.

Replacing the current weatherapi could be a significant rewrite of the lesson. Could you provide examples of the errors, Discord conversations etc? We just need to be extra confirmation before taking on this change. Hope that's understandable, thanks.

**Comment by Advaitmenon1106** [comment]
> @Advaitmenon1106, thanks for creating a well-researched issue.
> 
> Replacing the current weatherapi could be a significant rewrite of the lesson. Could you provide examples of the errors, Discord conversations etc? We just need to be extra confirmation before taking on this change. Hope that's understandable, thanks.

1. https://discord.com/channels/505093832157691914/690590001486102589/1181667304145166366 (Their code was seemingly correct- based on the reply by a club-40 member, yet they faced some issue).
2. https://discord.com/channels/505093832157691914/505093832157691916/1181307863906390036
3. https://discord.com/channels/505093832157691914/505093832157691916/1181241479713271912
4. https://discord.com/channels/505093832157691914/505093832157691916/1181261349200867398
5. https://discord.com/channels/505093832157691914/513125308757442562/1179157271016656956

6. https://discord.com/channels/505093832157691914/505093832157691916/1181308165317472407 (A message by Damon)

7. https://discord.com/channels/505093832157691914/505093832157691916/1180218213984899172 (This is a message which also has a reply to it by Veru, citing some issues).

8. I myself had issues in signing in to weatherAPI despite my login credentials being accurate.

@01zulfi Sorry for the delay in response, but here are some messages I found on discord, by searching for 2 keywords: "weather API" and "weatherapi". Apologies if there's any repetition in them.

**Comment by MaoShizhong** [comment]
Can confirm on my end that this morning, https://www.weatherapi.com/docs/ opened fine but trying to register for a new account resulted in a 502.
As of writing this, even the doc link now results in a 502 and matches what most of those previous reports say.

So whilst it does look like an intermittent issue as opposed to a permanent one, it's certainly a repeated issue that will stop learners from obtaining an API key and/or reading the documentation/playing with the API explorer. So since this is not the first time it's happened and it's happened several times over a longer period, I do think changing the recommended API is a sensible thing to do even if it does require a more involved rewrite of some lessons' parts.

I have actually used VisualCrossing in my weather app way back when with very little issue. It's a great little free API that I switched to only because after the 30 day free trial expired for WeatherAPI, the free tier reduced from a 7 day forecast to a 3 day forecast, breaking my app.
VisualCrossing still works fine even now with a 7 day forecast ([example of VisualCrossing working in an app still](https://maoshizhong.github.io/weather-app/)).

There are some subtle parts of its response structure that I prefer WeatherAPI with, but for 99% of stuff, it's just as intuitive to use. So I agree with the points @Advaitmenon1106 brought up about it.

**Comment by 01zulfi** [comment]
@Advaitmenon1106 Sorry it took me so long.

Agreed with all of the points above. Are you up for working on this?

**Comment by Advaitmenon1106** [comment]
@01zulfi Sure

**Comment by thatblindgeye** [comment]
@Advaitmenon1106 just checking in on the status of this issue

**Comment by Advaitmenon1106** [comment]
Sorry about the delay. I'll start working on this ASAP.
