### ISSUE TITLE
Ruby Course: Update "Using Git in the Real World" instructions to encourage follow-along without assigned issues

### ISSUE THREAD

**Issue by jonathanmeneses** [TheOdinProject/curriculum#26905]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Description of Issue
In the Ruby Course lesson, the instructions say "We’ll assume here that you have commented on an open issue on our repo and that it has been assigned to you", which implies the lesson can't be completed until this is the case. 

However, later in the lesson (at the end), in the "sending your pull request" section, it notes "If you have been following along with the above steps to get familiar with this workflow, you should stop at this point. If you have completed an assigned issue, the final step is to submit a pull request to merge your feature branch into the original upstream repository’s main branch. This can be done using GitHub’s interface." 

### Impact

This may cause users that don't currently have an assigned issue to follow-along without making changes, and then cause re-work from having to go back once they realize that they could have follow-along without an assigned issue.

### Requested Change

I'd recommend adding a disclaimer at the beginning of the lesson to note that users can follow-along with some "dummy" change without being assigned an issue. I would also like to make the wording of "stop here" bold to be a clear delineation. 

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-using-git-in-the-real-world

### (Optional) Discord Name

jme_atx

### (Optional) Additional Comments

This is very meta, making a change to the lesson that walks you through making a change.

**Comment by jonathanmeneses** [comment]
I'd like to work on this issue if possible!

**Comment by JoshDevHub** [comment]
Yeah I agree the lesson doesn't make it clear that you don't have to be doing it *for real*. I've assigned it to you @jonathanmeneses
