### ISSUE TITLE
Express 102: CRUD and MVC: <Better wording in the assigment section>

### ISSUE THREAD

**Issue by Kirnic21** [TheOdinProject/curriculum#26921]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The assigment: "Continue where we left off with the MDN library tutorial (Part 3)" is kinda ambiguous, could mean "Continue(the rest of the tutorial) where we left off with the MDN library tutorial (Part 3)" or "Continue(only this part) where we left off with the MDN library tutorial (Part 3)", i would suggest using a better verb than "Continue" like "Read the MDN library tutorial(Part 3)"

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-express-102-crud-and-mvc

### (Optional) Discord Name

Kirnic

**Comment by Asartea** [comment]
If @Kirnic21 doesn't want to take this could I be assigned it?

**Comment by CouchofTomato** [comment]
All yours :)
