### ISSUE TITLE
Using Git in the Real World: Inconsistency and bad UX in "Knowledge Check" Section 

### ISSUE THREAD

**Issue by garrza** [TheOdinProject/curriculum#26934]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The last link in the "Knowledge Check" section asks "Can you directly send your changes to a repository that you don’t own/have write access to?". The question points towards `href='#send-changes' `, which is correct, but since the `#id` is given to a two line `span`, the view ends up being very inconsistent with all of the references in the rest of the course which often link towards the title of the section the question is answered in. 

I believe the question should link to `#sending-your-pull-request`, rather than `#send-changes'` to answer the question in the field of view of the user, and keep it consistent with the rest of the course.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world

### (Optional) Discord Name

garrza

**Comment by CouchofTomato** [comment]
Yeah I agree. Although it is correct, it's very jarring and at first glance can look like you've been taken to some random part of the page.

Since you've indicated you're happy to work on this I've assigned you.
