### ISSUE TITLE
Problem Solving: <Short description of your suggestion>

### ISSUE THREAD

**Issue by seanapowi** [TheOdinProject/curriculum#26938]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hello Odin Tam, 
Enclosed here is the problem
[If you haven’t seen this before and it looks strange, it’s actually straightforward. We declare a variable i and assign it 1: the initial value of the variable i in our loop. The second clause, i <= answer is our condition. @_We want to loop until i is greater than answer_. (**this last statement should be corrected, I think we want to loop until i is less or equal to answer**]

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-problem-solving

### (Optional) Additional Comments

Nothing else, thank you

**Comment by CouchofTomato** [comment]
`I think we want to loop until i is less or equal to answer`

We want to loop while i is less or equal to answer. If it was until i is less, the loop would break on the very first iteration because that statement is true. i is less than answer when it runs the first time.
