### ISSUE TITLE
Installing Node.js: <curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 130275 ms: Connection timed out>

### ISSUE THREAD

**Issue by PraveenSinghKshatri** [TheOdinProject/curriculum#26941]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 130275 ms: Connection timed out

I've spent 2 hours trying to figure out what is wrong. None of the online solutions on GitHub or other platforms helped. No relevant YouTube video to fix this issue.

I'm using VM VirtualBox to run Xubuntu to participate in The Odin Project.

I'm stuck!!! No idea how to move forward with installation. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installing-node-js

### (Optional) Additional Comments

 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 130275 ms: Connection timed out

I've spent 2 hours trying to figure out what is wrong. None of the online solutions on GitHub or other platforms helped. No relevant YouTube video to fix this issue.

I'm using VM VirtualBox to run Xubuntu to participate in The Odin Project.

I'm stuck!!! No idea how to move forward with installation. 
![Screenshot_2023-12-16_18-42-27](https://github.com/TheOdinProject/curriculum/assets/150531004/675052a2-b6f2-460e-a394-fd12c8c348eb)

**Comment by CouchofTomato** [comment]
Sounds like you might be trying to connect from behind a proxy or something. Do you use a vpn?

Can you try `wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash` and let me know if you get the same output?

**Comment by PraveenSinghKshatri** [comment]
> Sounds like you might be trying to connect from behind a proxy or something. Do you use a vpn?
> 
> Can you try `wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash` and let me know if you get the same output?

It didn't work. 
I have tried several times.
![result](https://github.com/TheOdinProject/curriculum/assets/150531004/139a4856-33a1-497a-a57b-26e6d7cbd76f)
![wget](https://github.com/TheOdinProject/curriculum/assets/150531004/ef4c340d-9cf3-42a1-b870-29ff28ecaa4a)

**Comment by scheals** [comment]
If I can butt in, this seems to be an issue stemming from an ISP block. A different issue described a way to circumvent the block by changing the DNS resolver: #26637. Alternatives exist, like grabbing the file directly from GitHub/cloning the entire repo/copy-pasting the file contents locally.

**Comment by PraveenSinghKshatri** [comment]
@scheals I've tried to clone the git hub repo as well.
but still didn't work

**Comment by scheals** [comment]
> @scheals I've tried to clone the git hub repo as well. but still didn't work

Can you provide a screenshot of your terminal?

**Comment by PraveenSinghKshatri** [comment]
@scheals screenshot already posted above.. want me to try something else please suggest.

**Comment by scheals** [comment]
> @scheals screenshot already posted above.. want me to try something else please suggest.

I want a screenshot of your clone failing as you've just mentioned that it did not work.

**Comment by PraveenSinghKshatri** [comment]
@scheals 
https://github.com/nvm-sh/nvm.git
git@github.com:nvm-sh/nvm.git
![curl](https://github.com/TheOdinProject/curriculum/assets/150531004/a9098776-1b75-4cb5-b08f-7b05433e203a)
![clone](https://github.com/TheOdinProject/curriculum/assets/150531004/b21cda79-8777-4d33-a5f9-6370b8822268)

**Comment by scheals** [comment]
@PraveenSinghKshatri 
Nice, so it did clone. You now need to run the script you couldn't download directly, go into the repo's directory and do these commands in the terminal:
```bash
chmod +x install.sh
./install.sh
```
 the second one should just start the installation process normally.

**Comment by PraveenSinghKshatri** [comment]
@scheals 
![installed](https://github.com/TheOdinProject/curriculum/assets/150531004/689d4285-c64d-4c6b-8bce-5fe3b85a2dbf)
 and after this sir can i follow what's written on TOP ?

**Comment by scheals** [comment]
@PraveenSinghKshatri I'm just a guy, no need for a sir. And yeah, you should be good to proceed to Step 2 in the instructions.

**Comment by PraveenSinghKshatri** [comment]
@scheals You are a teacher in this context and your solution worked. Thank you just a guy sir!
Yesterday TOP asked me to pick Ruby or JS 
I might have picked JS was i wrong to do so?

**Comment by scheals** [comment]
Nope, that wasn't a wrong choice. It's just that your Internet provider for some reason or another blocks the `githubusercontent.com` domain. This lesson is in Foundations, so everyone regardless of path chosen afterwards has to complete it.

**Comment by PraveenSinghKshatri** [comment]
I see, well Yesterday I've skipped these steps and continued to choose a path.
There were 2 options Ruby and Node.
I've chosen Node. I've seen your profile and you are doing Ruby and @CouchofTomato is doing Ruby too.
I'm curious whether Ruby is a good start or node JS?

**Comment by scheals** [comment]
I believe this conversation would be more fit for our discord server. As for skipping, don't. The curriculum is meant to be taken in order without any skipping. That's all from me here.

**Comment by PraveenSinghKshatri** [comment]
@scheals 
![node](https://github.com/TheOdinProject/curriculum/assets/150531004/27a380b3-78e4-4f97-ae25-96e7b2c213db)
Just a guy sir! i ran into another error. please help

**Comment by PraveenSinghKshatri** [comment]
Problem solved and successfully installed. Thanks to everyone for your help.
