### ISSUE TITLE
Foundations/All Course: Add "previous lesson" button and/or numeric routes

### ISSUE THREAD

**Issue by juliocjuri** [TheOdinProject/curriculum#26956]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

When I'm taking lessons, the thing i do on a daily basis is to go back to the content of the previous day. That way i can clarify the context of the current lesson. But currently on TOP the only option to do this is to go back to the dashboard, as I do not remember the exact route of the previous lesson. Would be interesting to have a previous lesson button or make numeric routes. For example: foundations/html-and-css/lesson-1 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-axes

### (Optional) Additional Comments

The link is the lesson i was at in the moment

**Comment by CouchofTomato** [comment]
Hey @juliocjuri 

We used to have this but it was removed because nobody used it. I'm not sure this is a feature we'd bring back or not. @KevinMulhern do you know if this was discussed and a decision made already?

**Comment by rlmoser99** [comment]
Here is the relevant issue on the `theodinproject` repo where this change would need to be made. I will be closing this issue, since there is already one.
https://github.com/TheOdinProject/theodinproject/issues/2623
