### ISSUE TITLE
Common Data Structures and Algorithms: Knowledge Check Question Clarification

### ISSUE THREAD

**Issue by Gajdascz** [TheOdinProject/curriculum#26954]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Common Data Structures and Algorithms lesson, the Knowledge check question: 
- "What type of algorithm would you use to perform a binary search?"

Seems a bit misleading.

<details>
<summary>Answer Spoiler</summary>
I don't view divide and conquer as an algorithm itself, but rather a method used in algorithm design and problem solving. That said, binary search itself is an algorithm.
</details>

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-common-data-structures-and-algorithms

### (Optional) Discord Name

_imnolan

**Comment by rlmoser99** [comment]
Can someone on the @TheOdinProject/ds-a team review this issue.

**Comment by JoshDevHub** [comment]
@Gajdascz Thank you for raising this issue.

I agree that the current wording is a bit confusing here. What do you think it should change to? Maybe something like "What type of algorithm design does binary search use?"

Let me know what you think and I'll assign it to you :thumbsup:

**Comment by Gajdascz** [comment]
@JoshDevHub Absolutely, I'm happy to help. 

After reviewing the recursive methods section where the answer is first introduced, I believe 

"Which recursive problem-solving method/algorithm design principle does binary search implement?"

is a fair way to ask the question that hints at previously learned material.

**Comment by JoshDevHub** [comment]
That sounds great to me. I've assigned you @Gajdascz
