### ISSUE TITLE
[React] : Vite + React template homepage image is not showing

### ISSUE THREAD

**Issue by yellowsamuray** [TheOdinProject/curriculum#26964]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The image link for Vite + React homepage is not working
<br>
<br>
<img width="729" alt="Screenshot 2023-12-21 at 10 40 38 AM" src="https://github.com/TheOdinProject/curriculum/assets/31334367/795d7911-4fc0-4257-b2f6-8e4c22469ae4">
<br>
<br>
Here is the MD file and how it should look like
<br>
<br>
<img width="1061" alt="Screenshot 2023-12-21 at 10 49 22 AM" src="https://github.com/TheOdinProject/curriculum/assets/31334367/e00949b8-9f49-4acd-a9c1-e5df582cdcba">

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

**Comment by rlmoser99** [comment]
The image is loading correctly for me. Out of curiosity, what browser are you using?

Is anyone else having this issue on the @TheOdinProject/react team?

**Comment by yellowsamuray** [comment]
I am using Chrome Version 120.0.6099.109

**Comment by 01zulfi** [comment]
@yellowsamuray, thanks for creating this issue.

The image is loading correctly for me as well. Can you check again please, @yellowsamuray?

**Comment by yellowsamuray** [comment]
@01zulfi It's still not working for me. I think there is something wrong with my browser. I will close this issue. Thank you very much for the help.
