### ISSUE TITLE
Javascript: Project: Battleship. Unclear if a Button to Randomly Place Ships is Acceptable or Not

### ISSUE THREAD

**Issue by columk1** [TheOdinProject/curriculum#26968]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

> 5.1 "Implement the system that allows players to place their ships. There are several options available for letting users place their ships. You can let them type coordinates for each ship, or investigate implementing drag and drop."

It's unclear whether a button to allow players to auto-place their ships is acceptable here. Technically they are placing their ships. They can keep clicking until they get a configuration they are happy with, but they are not placing their ships where they choose.

If this is not acceptable, I suggest making a small change to reflect this:

> 5.1 Implement the system that allows players to **choose where to** place their ships.

If it is acceptable then it should be made explicit. I don't think it is, but here is an suggestion just in case:

5.1 You can let them type coordinates for each ship, **cycle through random placements,** or investigate implementing drag and drop.

I have seen multiple users on Discord confused about this and I wasn't sure about it myself when I did the project.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

### Discord Name

columk

### Additional Comments

[Discord question relating to this issue](https://discord.com/channels/505093832157691914/513125308757442562/1187474091867918336)
This isn't the first time I've seen someone confused about this issue so I think a PR will be helpful.

**Comment by rlmoser99** [comment]
Can someone on @TheOdinProject/javascript team review this issue.

**Comment by 01zulfi** [comment]
@columk1, thanks for creating this issue.

I feel a button to auto-place their ships is acceptable. Please create a pull request with the required changes.
