### ISSUE TITLE
Ruby Course: Use official documentation (docs.ruby-lang.org) instead of ad-supported 3rd party (ruby-doc.org)

### ISSUE THREAD

**Issue by macauleydev** [TheOdinProject/curriculum#26960]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

It is all too easy to confuse the 3rd-party, ad-supported website, `ruby-doc.org`, for official Ruby documentation, which it is not.

Besides this site's official-sounding name, The Odin Project's curriculum contains far more links to it (34) than to the official Ruby documentation, `docs.ruby-lang.org` (4).

This confusion is not unique to The Odin Project and has been discussed for example in [this Reddit thread](https://www.reddit.com/r/ruby/comments/14sw4px/whats_the_difference_between_rubydocorg_and/), which also gives a reproducible example of an additional issue with 3rd-party Ruby documentation:

- Certain intra- and inter-document links fail on sites like `ruby-doc.org` while functioning correctly on the official site, `docs.ruby-lang.org`.

You can reproduce the broken link test as follows:

1. Load your Ruby documentation site of choice.
2. Find and open the page, "OptionParser".
3. Search on this page for "Parameters for New Options" and see if the link works correctly.

I encountered issues like this on a daily basis when I started working through TOP's Ruby Course & mistakenly assumed the blame lay somehow with the maintainers of Ruby. My ad-blocker made it even less obvious that `ruby-doc.org` was a 3rd-party site.

My current favorite 3rd-party documentation site, `DevDocs.io` (maintained by freeCodeCamp & [listed as an additional resource](https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css#additional-resources) in one TOP Foundations lesson) -- passes this test. But multiple other 3rd-party sites including `ruby-doc.org` fail it. And I think it's a better policy to link to a language's official documentation than to any 3rd-party documentation.

 Thankfully, TOP's Ruby documentation links should be easy to fix in bulk by doing a curriculum-wide find and replace of:
`https://ruby-doc.org/*/`
with:
`https://docs.ruby-lang.org/en/3.2/`
as the two sites have the same URL endings. (At least, this worked on the links I tested so far, and it would be easy to test the others and make adjustments if needed.)

I am happy to make a PR for this change if approved.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-basic-data-types

### (Optional) Discord Name

macauleydev

**Comment by macauleydev** [comment]
On looking further (to find where TOP explicitly introduces Ruby documentation), I see that [LaunchSchool](https://launchschool.com/) (source for the assignments on TOP's [first Ruby lesson](https://www.theodinproject.com/lessons/ruby-how-this-course-will-work) and 5 subsequent lessons, and whose materials seem generally excellent) erroneously identifies `ruby-doc.org` as the official documentation source -- and in the section headed "Reading Documentation":

> In this section we're interested in understanding how to read Ruby documentation, so let's take a look at an example. The image below is a screenshot for the String class from the official Ruby documentation source, [www.ruby-doc.org](https://ruby-doc.org/3.2.0/String.html)

So to fully address this issue, I suggest not only updating TOP's direct links to Ruby documentation, but also:

- Adding a brief note on Assignment 3 of TOP's Ruby Course's [How This Course Will Work](https://www.theodinproject.com/lessons/ruby-how-this-course-will-work#assignment) lesson explaining the confusion around `ruby-doc.org` vs. `docs.ruby-lang.org` as official documentation source and warning against LaunchSchool's misstatement.
- Reaching out to Launch School to see if they will correct their own website in this regard. (I will try to do this now & update below if I hear back.)

**Comment by JoshDevHub** [comment]
Great issue @macauleydev 

I've reached out to the folks at Launch School before to make changes and they were accommodating and friendly. So I'm hopeful that they'll change it without us having to make a special note about it.

I like your idea to replace the 3rd party docs with the official ones. A nice side effect is that while you're at it, you'll fix the way a lot of our current links are still pointing to ruby 3.1 documentation.

I'm assigning you since you indicated you'd like to work on this :raised_hands:

**Comment by macauleydev** [comment]
Launch School responded and fully updated the references on their website within 12 hours of my email!

(They mention that `ruby-doc.org` was once "well maintained and superior to `ruby-lang.org`", which may help explain why it came to be so widely referenced in the Ruby community.)

So I think updating TOP's Ruby documentation links will suffice to resolve this issue.

(I'm open to considering a note box, but not convinced it's necessary, especially as Launch School has just added one at the end of their "[Reading Documentation](https://launchschool.com/books/ruby/read/preparations#readingdocumentation)" section.)

**Comment by macauleydev** [comment]
@scheals Thanks for sharing that. For consistency and simplicity, my PR just made everything point to the official Ruby documentation.

RubiAPI.org definitely seems like one of the better 3rd-party sources. I'm also a fan of DevDocs.io (as mentioned), and am currently trying Dash (macOS, not free). But again, I'm not sure whether (and if so, where and how) it's worthwhile to mention these in the TOP Ruby curriculum.
