### ISSUE TITLE
Foundations - RPS Project: Unclear instruction

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#26963]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

This line is driving me nuts...
> Account for TIES by re-playing the round.
Is the intent here that learners should re-run the playRound function if a tie occurs (ie, in the game function), or are we asking them to recurse the playRound function when a tie occurs until a result is achieved?

Personally, I think what we really want is for them to return a string "You tied, try again!".  And then, in the game() function, we want them to implement logic to rerun the turn.

Either way, I think we need to reword this to be clear about what we want. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-rock-paper-scissors

**Comment by fabulousgk** [comment]
As I have continued to do this project, it occurs to me that any rational system at replying a round is going to require a loop, which we tell them they don't need to do in this project, so maybe at this point we should not ask them to handle a TIE in any form than just print it was a TIE

**Comment by MaoShizhong** [comment]
Can agree that I think the current instructions aren't necessarily the most appropriate given the lack of expectation to use loops - [point raised in this discord interaction](https://discord.com/channels/505093832157691914/513125308757442562/1187703863504019496).

Given that, I feel the most appropriate resolution would be as fabgk said to not expect a round repeat upon a tie, and to also reword the following:
> Use the previous function inside of this one to play a best-of-five game that keeps score and reports a winner or loser at the end.

to something perhaps more like
> Use the previous function inside of this one to play a five round game that keeps score and reports the result at the end.

**Comment by fabulousgk** [comment]
The parts brought up in that discord by @MaoShizhong are also great and pretty much related, if they have no objections and the maintainers agree, I will include that in my changes.

**Comment by rlmoser99** [comment]
Thank you for bringing this to our attention. Can someone on the @TheOdinProject/foundations team take a look at this issue?

**Comment by fabulousgk** [comment]
Also...the function name game() should likley be changed, perhaps to playGame().  In a later lesson we teach that functions should always start with a verb, and while that is not on the plate quite yet, I think we should always practice good technique early on.

**Comment by thatblindgeye** [comment]
Personally I would be in agreement of removing the "replay a round on a tie" instruction. Considering this is the first JS project, I think even without this instruction it's still a good intro to bringing the knowledge learned thus far together. And relying on something that the project itself says "you'll learn about this thing in the next lesson" doesn't make much sense without rewriting/reordering things further.

**Comment by fabulousgk** [comment]
If the maintainers are agreeded, can this be assigned to me? 

Thank you all

**Comment by wise-king-sullyman** [comment]
I'm on board with removing the tie replaying, also on board with the suggested function name change.

Thanks @fabulousgk and (everyone else who has been involved in this discussion!), all yours!
