### ISSUE TITLE
Foundations - DOM Manipulation & Events: Weird display issue caused by a div element.

### ISSUE THREAD

**Issue by recleun** [TheOdinProject/curriculum#26969]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There's a display issue in a paragraph right below "Adding HTML content" header. I verified it through Google Chrome (First image) and Firefox (Second image), and Google browser on mobile, all give similar results.

After some little digging around, I found out that this is caused by a div element inside the .md file for the lesson, parenting the paragraph.

```md
<div class="lesson-note--tip" markdown="1">

Note that textContent is preferable for adding text, and innerHTML should be used sparingly as it can create security risks if misused. Check out [this video](https://youtube.com/watch?v=ns1LX6mEvyM) if you want to see an example of how.

</div>
```

I copied the .md file and removed the div and viewed it on the Lesson Preview Tool, and the issue was solved. I'm personally not sure what this div is for, the only solution I know about is just removing it.

Edit: I found another problem like this on the same page, and it gets fixed by editing the div too.

![chrome](https://github.com/TheOdinProject/curriculum/assets/98621222/aad439f8-b40f-4d59-b7b3-64bf2f7a7561)
![firefox](https://github.com/TheOdinProject/curriculum/assets/98621222/9d8c2647-adfc-43bd-9bdc-4be80ab1f76b)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events#dom-methods

### (Optional) Discord Name

recleun

### (Optional) Additional Comments

If this issue gets resolved the way I suggested (or at least in any way), then this will be my first time to contribute to a GitHub repo on my own.

**Comment by recleun** [comment]
Quick note: I copied the .md file and changed the class of the div to `lesson-note-tip` and it worked (tested on the preview tool), and I think this is a better solution than removing/moving the text to outside of the div.

**Comment by rlmoser99** [comment]
Great catch! However, the solution is not to remove the div. We actually want these sections to stand out. You can find the correct way this should be in our style guide. (I believe the class name just needs updating).

https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#note-boxes

I'll assign you this issue.
