### ISSUE TITLE
Webpack: Move webpack merge/modes mention to a later lesson

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#26977]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In #26381 and #26552 I ended up adding step 4 of the webpack lesson assignment which took the user through the difference between development/production mode and using `webpack-merge` to set a dev and prod config tied to their own npm scripts.

Whilst this has proved convenient for some people (especially after more experience with Webpack) and has reduced the number of questions concerning the warning when no mode is specified, in hindsight, I feel it is not necessary to include that part in the Webpack lesson as it's not strictly necessary to get started with it. I feel it would be more beneficial moved to a later lesson e.g. the linting lesson (though still not 100% sure if this would the best place either?) in order to give the learner more time to use and get a feel for webpack before then introducing convenience measures.

This came about starting with [this Discord discussion](https://discord.com/channels/505093832157691914/505093832157691916/1174867129040912454) and keeping an eye on things since then, whilst fewer Qs about webpack mode came up, there seemed to be more confusing about webpack as a whole than needs be as people were already struggling to get to grips with the more important parts of using webpack let alone dealing with the difference between mode configs (if anything, the less unnecessary config they need to do at the start, the simpler the learning curve would be I feel). `Html-webpack-plugin` and css/style loaders I feel are the primary ones needed for straightforward workflow and understanding the roles of src/dist and should be plenty to get through restaurant page and to-do list. It just feels currently that webpack-merge and modes will serve only to overwhelm at the point they're mentioned.

Thoughts?

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-webpack

### (Optional) Discord Name

Mao

**Comment by rlmoser99** [comment]
Thank you for taking the time to make an issue. Can someone from the @TheOdinProject/javascript team, please review this issue, as well as a closely related one:
https://github.com/TheOdinProject/curriculum/issues/26976

**Comment by JoshDevHub** [comment]
Hey @MaoShizhong 

We agree that it makes sense to move the merge/modes later. With #26976 we're maybe going to explore some broad reorganization of the webpack content, and it seems like this could impact the way we proceed here.

Did you have any particular reason you wanted to move it to the linting lesson?

**Comment by MaoShizhong** [comment]
Moving to backlog.
This is something that'll be worked on in conjunction with the larger ESM/Webpack lesson restructuring detailed in #26976
