### ISSUE TITLE
Setting Up A React Environment: <Short description of your suggestion>

### ISSUE THREAD

**Issue by High-Banana** [TheOdinProject/curriculum#26979]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In Assignment part, in number 2 the link to checkout the guide for React Developer Tools links to some other website called pluralsight. I don't think it is supposed to be like that.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

**Comment by rlmoser99** [comment]
Thanks for taking the time to make an issue. However, this is a duplicate, so I will be closing it.
https://github.com/TheOdinProject/curriculum/issues/26948
