### ISSUE TITLE
<React>: <Wrong link for number 2 in the assignment>

### ISSUE THREAD

**Issue by JohnMikko27** [TheOdinProject/curriculum#27004]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

for the setting up react environment lesson in the react course, the link for number 2 brings me to this website https://www.pluralsight.com/browse which doesn't seem to be about the guide for react dev tools 
<img width="753" alt="Screenshot_2023-12-26_at_9 08 02_PM" src="https://github.com/TheOdinProject/curriculum/assets/54955894/e6260ebd-c1a3-442c-9fb6-224dc00d5d92">

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

**Comment by rlmoser99** [comment]
Thanks for taking the time to make an issue. However, this is a duplicate, so I will be closing it.
https://github.com/TheOdinProject/curriculum/issues/26948
