### ISSUE TITLE
Foundations - Landing page project: suggestion to add discord invite link

### ISSUE THREAD

**Issue by AnimeshKumar923** [TheOdinProject/curriculum#27000]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I suggest adding a discord invite hyperlink to [this line](https://github.com/TheOdinProject/curriculum/blob/72156b33008de26739af6b63d77aeb4b6a3eafc1/foundations/html_css/flexbox/project-landing-page.md?plain=1#L40C41-L40C55) so that the user can directly go into the help section of the discord server (html-css-0/1 anyone of those).

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-landing-page

### (Optional) Discord Name

Server name: Animesh; (username: animeshkumar923)

### (Optional) Additional Comments

Would love to hear your opinion on this...

**Comment by rlmoser99** [comment]
Thank you for taking the time to make this issue. I think a link to `html-css-0` would be good here. If needed, here is an example of how we've done this in another lesson.

https://github.com/TheOdinProject/curriculum/blob/97c52c48b3a326c8962072842e006a46002d23b0/foundations/introduction/motivation_and_mindset.md?plain=1#L18
