### ISSUE TITLE
Setting Up A React Environment: PluralSight link points to generic Browse page instead of specific article

### ISSUE THREAD

**Issue by Chorwhat** [TheOdinProject/curriculum#27008]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The link is intended to open as: https://www.pluralsight.com/guides/debugging-components-with-react-developer-tools

but instead redirects to https://www.pluralsight.com/browse

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

### (Optional) Discord Name

Shingfling

### (Optional) Additional Comments

This is my first issue report!

**Comment by KURELLANAVEEN** [comment]
Hey @Chorwhat , as you said this is your first issue report. I appreciate you work. But before creating a new issue or a PR, once check whether the issue or PR is open or not. The issue you have raised is already a open issue(#26853 ) and open PR(#26949 ). Check out this (https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md), it states you to follow certain rules before opening the issues and PR. This might help your future contributions.

Thankyou!

**Comment by rlmoser99** [comment]
I will be closing this duplicate issue.
