### ISSUE TITLE
Introduction To State: Code Sandbox Embed Should Show Code

### ISSUE THREAD

**Issue by weboffools** [TheOdinProject/curriculum#27009]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

<img width="653" alt="Screenshot 2023-12-27 at 6 31 08 PM" src="https://github.com/TheOdinProject/curriculum/assets/125320536/d5673e7b-ba62-4093-b26f-f34307d851cd">

The embed doesn't show code by default and makes it difficult to get to the code within the embed. It can be accessed by clicking on it and going to Code Sandbox.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

### (Optional) Discord Name

jeliotj

**Comment by 01zulfi** [comment]
@weboffools, thanks for creating this issue. I'll take a look when I can

**Comment by MaoShizhong** [comment]
Closing as this has been fixed.
