### ISSUE TITLE
Make SQL course path agnostic

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27014]
## Course overview

[Current SQL databases course](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/databases) in the Ruby on Rails path references RoR specific concepts. The course should be path agnostic so it can be included in other paths.

## Course outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Path agnostic SQL course 

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by Lofty-Brambles** [comment]
Can I get this assigned to me?
