### ISSUE TITLE
Foundations - Box Model: Prefer outline over border

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27015]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

It has been pointed out on Discord (https://discord.com/channels/505093832157691914/516751477306294273/1190095841839554681) that using outline is preferable to border when highlighting boxes for troubleshooting etc.  While we do not talk about doing this for troubleshooting here, many use this snippet as a way to do so, so updating would be benificial.

Outline will not affect the box model like border does.

Hat tip to @US-General who can pick this up if they want it, otherwise I will do it.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-box-model

**Comment by 01zulfi** [comment]
@fabulousgk, thanks for creating this issue.

I do agree with the change, though I'd like someone with more HTML/CSS prowess give a sign off. @TheOdinProject/html-css, please look at this.

**Comment by codyloyd** [comment]
approved 👍🏽
