### ISSUE TITLE
[Foundations: Working With Text] Grammatical Error in HTML Section

### ISSUE THREAD

**Issue by x0tek-1** [TheOdinProject/curriculum#27019]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a typo in the first CodePen of the HTML section. It reads "I am a html" when the proper article should be "I am **an** html". Minor, but I hope this helps in some small way <3
![image](https://github.com/TheOdinProject/curriculum/assets/105384064/3e87149c-b30f-485f-b3a6-15097cddfee2)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-working-with-text

**Comment by Servante** [comment]
I'll fix this if no one else wants it.

**Comment by Churtified** [comment]
I would like to fix the typo if possible!

**Comment by 01zulfi** [comment]
@x0tek-1, thanks for creating this issue. @Servante @Churtified, thanks for wanting to contribute.

This fix will need to be made on The Odin Project's CodePen account, which only the maintainers have access to. @TheOdinProject/html-css, please take this up.

**Comment by wise-king-sullyman** [comment]
Fixed.
