### ISSUE TITLE
Advanced HTML and CSS: Clarify purpose of the Homepage Project

### ISSUE THREAD

**Issue by JakeNead** [TheOdinProject/curriculum#27035]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The last sentence in the introduction for this lesson could be more explicit in explaining if people should use this as their actual portfolio. 

Right now it ends with, "The main focus is on achieving the specified layouts and responsive behavior."

We could add onto the end of this sentence:
"...rather than a complete portfolio."
or
"...but this can become your portfolio site while job hunting."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-homepage

### (Optional) Discord Name

GoatMoat

**Comment by 01zulfi** [comment]
@JakeNead Thanks for creating this issue.

I'm on the fence regarding this change. @TheOdinProject/html-css, thoughts?

**Comment by codyloyd** [comment]
I don't think this is a huge issue...but it wouldn't hurt anything to add it either.  I say go for it @JakeNead

**Comment by JakeNead** [comment]
Thanks, @01zulfi and @codyloyd. This is only a minor tweak but it would have been helpful for me to know how much effort to put into this project. I'll get on this soon.
