### ISSUE TITLE
Ruby: Performance Issues in Predicate Enumerable Methods Lesson Code

### ISSUE THREAD

**Issue by endrohat** [TheOdinProject/curriculum#27038]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There are a few issues in the lesson's code for example 

```ruby
numbers = [5, 6, 7, 8]
element = 6
result = false

numbers.each do |number|
  if number == element
    result = true
  end
end

result
```
In this piece of code they are trying to implement ```include?``` method which returns true if an element is within an array.
The example code traverses all the elements of the array instead of breaking after finding the first element

For Eg.

```ruby
numbers.each do |number|
  if number == element
    result = true
    break
  end
end
```
I think it is important to highlight that fact to the students as they have already seen the break statement before .
This could also be left as an exercise .
The remainder of this lesson also has similar issues like this

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-predicate-enumerable-methods

**Comment by JoshDevHub** [comment]
Sounds good to me. I would just change the code examples to short circuit where possible like your example does. No need to include this as an exercise or anything.

Since you've checked the box saying you'd like to work on it, I've assigned it to you. @endrohat
