### ISSUE TITLE
Rendering Techniques: <Wrong instructions for if conditions>

### ISSUE THREAD

**Issue by sevleo** [TheOdinProject/curriculum#27040]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The following part appears to be incorrect:

> If we remove the animals property:
```
function App() {
  const animals = [];

  return (
    <div>
      <h1>Animals: </h1>
      <List />
    </div>
  );
}
```
> The first if statement will now execute and return a `<div>` with the text “Loading…” This is often the case when you are fetching from an API, since it might take some time to actually retrieve the data, it is good practice to show an indicator for that.

If we remove values from the "animals" property, as demonstrated in the code snippet above, then the second if condition will execute and return a div with the text "There are no animals in the list!", and not a div with the text "Loading...".

To solve this, we need either to update this paragraph or update the code snippet to something which will trigger the first if condition.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-rendering-techniques

### (Optional) Discord Name

sleos

**Comment by mark-P0** [comment]
> If we remove the animals property:

I believe this refers to the props of the `<List />` component

i.e. from this:
```jsx
<List animals={animals} />
```

to this:
```jsx
<List />
```

**Comment by sevleo** [comment]
Oh yes, this is correct. Now it works as expected, I missed that :)
