### ISSUE TITLE
Deployment: Adaptable.io requires credit cards

### ISSUE THREAD

**Issue by mark-P0** [TheOdinProject/curriculum#27044]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

![image](https://github.com/TheOdinProject/curriculum/assets/63066834/82b5fa5f-3bfc-4d0c-96b0-ace3a1898976)

Adaptable.io seems to now require credit cards. The left side of the screenshot above is shown as a step on app deployment. I am a new user of the service. This now contradicts how it was described on the lesson.

(I am logged in on the screenshot above, but I just edited out my picture and location)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-deployment

### (Optional) Discord Name

E('Mark')

**Comment by 01zulfi** [comment]
thanks for creating this issue

@mark-P0 you're assigned, please create a pull request
