### ISSUE TITLE
Foundations: Be more explicit about exercise solutions not being the only solutions

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#27053]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

A very common concern amongst foundations learners in the community is that their solution to whatever CSS/JS exercise may not be "valid" or even "good" compared to provided solution for each.

Currently from what I could find, the only explicit mention about the purpose of these solutions is in the general exercises repos' README, something that I can imagine either does not get read or does but some details easily forgotten when coming back to do the later exercises.
> Keep in mind that TOP's solution is not the only solution. If your solution differs wildly from TOP's solution (and still passes the self-check criteria), feel free to ask about it in the chatroom.

The lessons that link to these exercises as assignments only contain:
> Note: Solutions for these exercises can be found in the solution folder of each exercise.

I believe this part in those lessons can be reworded to be more explicit about the provided solutions being only one way to do things that learners can look at after completing their own, and that as long as the requirements are met, whatever they did is valid.

#### Side note: 
I think the exercise repos' README mention could actually be tweaked very slightly so it says 
> If your solution differs wildly from TOP's solution (and still passes the self-check criteria), that's completely fine. Do feel free to ask about it in the chatroom if there are parts you do not understand.

This is because several times, people have come in concerned their solution isn't valid precisely *because* they interpreted that note as "if your solution differs, check with the community if it's valid".

#### Proposed actions:
- Reword the "Note: Solutions for these exercises..." part in all relevant lessons to clarify and reinforce the intent shared in the repos' READMEs
- Tweak wording of the repos' READMEs for that note as per above

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css https://www.theodinproject.com/lessons/foundations-the-cascade#assignment  https://www.theodinproject.com/lessons/foundations-alignment  https://www.theodinproject.com/lessons/foundations-block-and-inline#assignment https://www.theodinproject.com/lessons/foundations-fundamentals-part-4 https://www.theodinproject.com/lessons/foundations-fundamentals-part-5#assignment

**Comment by 01zulfi** [comment]
> Reword the "Note: Solutions for these exercises..." part in all relevant lessons to clarify and reinforce the intent shared in the repos' READMEs

Can you clarify what you changes you have in mind here?

I do agree with the proposed changes in the exercises repos' READMEs.

**Comment by MaoShizhong** [comment]
@01zulfi Perhaps rewording those parts in the relevant lessons to something like

> When you have completed an exercise, the solution folder for the exercise provides a solution you can look at.  If your solution differs from the provided one then that's completely fine so long as you still meet the exercise's requirements. If there are any parts about the provided solution that you do not understand, feel free to ask about them in our Discord community.

**Comment by MaoShizhong** [comment]
Just seen that #27055 adds a needed "Read the repo README" to the first time learners are directed to the CSS exercises repo - really like that.
Though I think this issue is focused more on "drilling in" the understanding, so to speak, that there is no one solution to rule them all by rewording those relevant lessons' solution note.

**Comment by 01zulfi** [comment]
I feel like we're doing a bit of unneeded repetition in the lesson and the repo readmes. The lesson already instructs learners to read the readmes. IMO we should only make your proposed changes in the repo readmes.

**Comment by MaoShizhong** [comment]
If you feel the current lessons' solution note wording is fine as it is (after the README changes) then that's no problem and we can go along with that :)

**Comment by 01zulfi** [comment]
Sure. @MaoShizhong, assigned.
