### ISSUE TITLE
Foundations JavaScript Part 1 : Add an introduction to what is JavaScript

### ISSUE THREAD

**Issue by BelhassenB** [TheOdinProject/curriculum#27059]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the [foundations Javascript Fundamentals Part 1](https://www.theodinproject.com/lessons/foundations-fundamentals-part-1) , it dives directy into the variables and numbers which is good but as a total beginner I want to know what is Javascript, yes it's a programming language but I don't know what it does and how.

In the HTML/CSS part there was an introduction and a [link](https://brytdesigns.com/html-css-javascript-whats-the-difference) that introduce HTML vs CSS vs Javascript. In this link it talks about Javascript but personally I've spent a lot of time in HTML/CSS wich made me forget how JS works and what it does.

I suggest adding a paragraph or two to the introduction and also add this [link](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript) of MDN which gives a good introduction.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-1

**Comment by 01zulfi** [comment]
@BelhassenB Thanks for creating an issue, sounds good to me.

I'm opening this issue up for contributions. Please comment below to be assigned.

Acceptance criteria:

- [ ] Add a brief introduction of JavaScript in the [Fundamentals Part 1 lesson's introduction section](https://www.theodinproject.com/lessons/foundations-fundamentals-part-1#introduction)
- [ ] Add [MDN's What is JavaScript? article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript) in the lesson's additional resources section

**Comment by Churtified** [comment]
I'm happy to contribute!

**Comment by 01zulfi** [comment]
@Churtified, assigned.

**Comment by Valeria-D-23** [comment]
I would like to work on this issue

**Comment by kamranzafar4343** [comment]
@Valeria-D-23 it is already saying that the pull request will close that issue.
