### ISSUE TITLE
Git Basics: <Ctrl + backtick>

### ISSUE THREAD

**Issue by hstrm** [TheOdinProject/curriculum#27066]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It was suggested to me on the Discord server to report this issue. 

The instructions say: 
""Go back to your terminal or if you’re using Visual Studio Code you can open the built-in terminal by pressing Ctrl + ` (backtick). Then type git status. You’ll notice that README.md is now shown as not staged or committed."

Ctrl + backtick isn't the default keybinding with all layouts, and perhaps the instruction should be changed to go through the menu and toggle it there. I use a Swedish keyboard and the default is ctrl+ ö for example. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics

### (Optional) Discord Name

Hstrm

**Comment by Swap2104** [comment]
I'd like to work on this

**Comment by 01zulfi** [comment]
@TheOdinProject/foundations, I'm not sure how to deal with various keyboard layouts when mentioning shotcuts. Any ideas?

**Comment by Swap2104** [comment]
> not sure how to deal with

Can we mention the shortcut / method to check the shortcut to toggle terminal ??

**Comment by codyloyd** [comment]
surely anyone that knows they're using a nonstandard keyboard knows they'll have to search for commands 🤔 

it wouldn't hurt to add a little note that says "if the shortcut doesn't work for you, find it in the menu"... but I don't think it's that big of an issue really.

**Comment by hstrm** [comment]
As a newbie I had no idea of where to search for other keybindings, maybe I
could've googled it but I chose to ask I the discord instead. Maybe less
people will ask repeat questions about the same thing in the future with a
note? Or maybe it clutters the site

Den tis 9 jan. 2024 16:51Cody Loyd ***@***.***> skrev:

**Comment by MaoShizhong** [comment]
Perhaps in the interest of making things easier for everyone (because not everyone using a non-standard layout will know that an instruction telling them to use a specific binding may not work because it's different for theirs), something like this might not hurt:
> ...you can open the built-in terminal by going to the `View` menu in the top toolbar then clicking `Terminal`. Take note of the keyboard shortcut next to it to make life easier (for most keyboard layouts, this will be <kbd>Ctrl</kbd> + <kbd>`</kbd> (backtick)).

Might not even need to mention the ctrl backtick part.

**Comment by thatblindgeye** [comment]
I'd be good with updating this verbiage in this instance. It doesn't really hurt to add something like "Do this task via the VS code menu bar, but here's the typical keyboard shortcut as well". If we get other comments regarding keyboard shortcuts in other lessons we may need to revisit how we write them.

**Comment by wise-king-sullyman** [comment]
Suggestion sounds good to me, have at it @Swap2104!

**Comment by thatblindgeye** [comment]
@Swap2104 just checking in on whether you'd still like to work on this?

**Comment by Swap2104** [comment]
> @Swap2104 just checking in on whether you'd still like to work on this?

Sorry I completely forgot about it. I'll finish it today.

**Comment by CouchofTomato** [comment]
Closing as the PR was closed already
