### ISSUE TITLE
Fundamentals Part 2: <Grammar fix>

### ISSUE THREAD

**Issue by OshaneWright10u** [TheOdinProject/curriculum#27076]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I noticed that this sentence in this lesson at the strings section at number 3 is using incorrect grammar, i think it should be "a method has a bit of functionality built into the language or specific data types" instead of "a method is a bit of functionality built into the language or specific data types".

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-2

### (Optional) Discord Name

oshane_o

**Comment by Churtified** [comment]
I could be wrong in the context of what it is trying to convey, it sounds correct to me. Both sound grammatically correct though.

**Comment by OshaneWright10u** [comment]
I see, i wouldn't call my self a expert on grammar but it sounds off to me.

**Comment by 01zulfi** [comment]
@OshaneWright10u, I don't think there are grammatical errors in this context. The lesson is trying to say that a method is functionality that is built into a programming language similar to variables or loops.

I'm closing this issue now, feel free to comment below if you have any questions.

**Comment by OshaneWright10u** [comment]
Ok see.
