### ISSUE TITLE
Foundations - Flexbox Alignment: Frequent confusion about CSS Tricks article

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27075]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I have seen a question about what parts of this article need to be studied come up in discord several times:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

I think just a small edit would help clarify:

> is a classic. There isn’t any new information for you here, but the images and examples are super helpful. It would be a good idea to review parts 1-3 and part 5 and then bookmark it as a great cheat sheet for future reference. (Keep it handy for the practice exercises!)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-alignment

**Comment by Churtified** [comment]
I'm happy to take this if it seems like a good change!

**Comment by 01zulfi** [comment]
@fabulousgk sounds good to me, assigned.

@Churtified Thanks for wanting to contribute, but @fabulousgk already expressed interest in this issue using the checkbox above.
