### ISSUE TITLE
<Foundations>: Unify description of instruction sections for WSL2

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#27082]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a discrepancy between how the WSL2 instructions are called between the [Installations lesson](https://www.theodinproject.com/lessons/foundations-installations#os-installation) where the section is called `WSL2` and the [Text Editors lesson](https://www.theodinproject.com/lessons/foundations-text-editors#vscode-installation) where it is called `WSL`. It most likely should be `WSL2` everywhere since the bit in `Installations` says:
> WSL2 and Linux instructions
> Because WSL2 is a full-fledged Linux distribution, almost everything that the curriculum teaches about Linux is also applicable to WSL2. In future lessons, whenever there are instructions that differ by OS, you should follow the Linux instructions, unless the lesson includes **WSL2-specific instructions**.

There are probably more places where making sure WSL is called WSL2 where it matters, for example it is called WSL2 in [Installing PostgreSQL lesson](https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql).

This is to avoid confusion as to whether the curriculum is giving instructions for *any* WSL version or WSL2 specifically which is actually the case.

### Path

Foundations, Ruby / Rails, Node / JS, Other / NA

### Lesson Url

Most important seems to be https://www.theodinproject.com/lessons/foundations-text-editors

**Comment by 01zulfi** [comment]
@scheals, good call. 


I'm opening this issue up for contributions. Please comment below to be assigned.

Acceptance criteria

- [ ] For the entire curriculum, replace occurrences of WSL to WSL2

**Comment by Jaytpa01** [comment]
I'd be happy to work on this!

**Comment by Churtified** [comment]
I'm happy to take it :)

**Comment by 01zulfi** [comment]
@Jaytpa01, assigned. Please make a pull request.
