### ISSUE TITLE
HashMap Data Structure: Pigeonhole Principle

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#27081]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Not sure if this is more suited to an issue or a discussion - feel free to move it.

The lesson states "we know for a fact that if almost all buckets have items in them, then collisions are guaranteed, it is mathematically impossible not to." This is true, but implicitly invokes the [Pigeonhole Principle](https://en.wikipedia.org/wiki/Pigeonhole_principle) such that when there are more items than buckets, there must be a collision. 

I think the current wording allows for a misinterpretation that this is a probabilistic argument, something like "if we have lots, there surely has to be a collision!" when it is not the case that it is probabilistic, as it is deterministic.

I wonder if it would be a good idea to include a link to the wikipedia article above in additional resources, and then elude to that in the paragraph I quoted from.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-hashmap-data-structure

### (Optional) Discord Name

Damon

**Comment by JoshDevHub** [comment]
I think this makes sense, and I agree that the way it's worded currently can make it feel like more of a probabilistic analysis.

Since you indicated you'd like to work on it, I'll assign you. Be sure to make your changes in `javascript/computer_science/hash_map_data_structure.md` AND in `ruby/computer_science/hash_map_data_structure.md`
