### ISSUE TITLE
Foundations, Working with Text (37%); Suggestion about <u> (underlined)

### ISSUE THREAD

**Issue by Ivnringostar** [TheOdinProject/curriculum#27084]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the lesson that I specify in the title of this tip, I suggest that you put the tag of `<u>` , since it also shows the `<strong>` and `<em>` tags . I think that putting it all together, if this tag is included later in the course, would be better and easier to remember, but if the `<u>` tag is not included in this curriculum, it would be good to put it.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-working-with-text

### (Optional) Discord Name

Ringo / ivnringostar37

### (Optional) Additional Comments

In the same lesson, I saw that the examples that puts TOP are not like the boilerplate of the previous lesson. (Image)
![Screenshot_2024-01-08_16-15-12](https://github.com/TheOdinProject/curriculum/assets/147585549/1769a760-597b-4e45-b586-02f8113beb77)

**Comment by 01zulfi** [comment]
@TheOdinProject/html-css, thoughts?

**Comment by codyloyd** [comment]
I think the `u` tag is very very rarely used... most underlined text is reserved for links which are underlined by default.  We do not need to include this here.

**Comment by JoshDevHub** [comment]
Yeah I don't think I've ever seen `<u>` in the wild. Introducing it feels like it could potentially confuse learners into thinking it's common practice to use `<u>` to underline rather than via `text-decoration`.

Going to close this as unplanned.
