### ISSUE TITLE
CV Application: Choosing on which site to deploy

### ISSUE THREAD

**Issue by Sokolan** [TheOdinProject/curriculum#27092]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

CV Application is the first project which we deploy, and as such we introduced to 3 different options.
The lesson does mention in the instructions:

> Push the results and deploy them with any of the options mentioned below!

But I'm not sure how clear it is (wasn't for me) if there's really difference between the 3 options.
I would suggest to add a clarification to this instruction such as:

> Push the results and deploy them with any of the options mentioned below! 
_For the meantime there's no difference between them, so you can just pick one._

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-cv-application

**Comment by 01zulfi** [comment]
@Sokolan There are differences in each of the provided options. I think you mean that it really doesn't matter which platform you use to deploy. With that perspective, I think we could make the following change:

> Push the results and deploy them with any of the options mentioned below. It doesn't really matter which platform you choose as long as your project is live on the internet!


What do you think?

**Comment by 01zulfi** [comment]
@Sokolan sounds good to me, Assigned, please make a pull request.
