### ISSUE TITLE
Advanced HTML and CSS Course (Transforms): Remove the incorrect article

### ISSUE THREAD

**Issue by Ariech** [TheOdinProject/curriculum#27096]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There seems to be an incorrect article linked in the transform lesson, regarding the concept of reading from left to right and right to left. The mentioned [article](https://codepen.io/bali_balo/post/chaining-transforms),  states that the order of reading doesn't matter for the end result. This is not accurate, as we can see in the example linked by TOP [codepen](https://codepen.io/TheOdinProjectExamples/pen/XWeJWWr), and it's further explained in the MDN [transform order](https://developer.mozilla.org/en-US/docs/Web/CSS/transform#transform_order). 
 
 I believe the mentioned article should be removed from the curriculum or be replaced with something that conveys its information correctly.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transforms#chaining-multiple-transforms

### (Optional) Discord Name

Yaess

### (Optional) Additional Comments

[Discord question](https://discord.com/channels/505093832157691914/516751477306294273/1193960604495511562) asked by me answered by Mao, that explains the issue.

**Comment by 01zulfi** [comment]
@TheOdinProject/html-css, can someone please take a look

**Comment by DonnieAndMooie** [comment]
I think removing the article seems best as it contradicts what the rest of the lesson says.

I would be happy to do this.
