### ISSUE TITLE
All: Update the 'Knowledge check' questions to be contained inside the details element

### ISSUE THREAD

**Issue by DreamVenerable** [TheOdinProject/curriculum#27090]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I really liked the Knowledge check section on the Turbo lesson. And to be consistent, I thought we should update all of them to be like it.

Most lessons:
![Screenshot 2024-01-08 at 11 41 55 PM](https://github.com/TheOdinProject/curriculum/assets/114648602/38d7bcaa-707e-448f-acd6-7818147052ed)

Turbo and Stimulus lessons:
![Screenshot 2024-01-08 at 11 41 30 PM](https://github.com/TheOdinProject/curriculum/assets/114648602/d824f859-e8f7-4cb3-bd64-2407e62f4017)

### Path

Foundations, Ruby / Rails, Node / JS

### Lesson Url

All the lessons that contain the 'Knowledge check' section

### (Optional) Discord Name

dreamvenerable

### (Optional) Additional Comments

I'm not sure if it used to all be like the Turbo lesson and it was changed to be links, and those 2 lessons were missed, if so then this issue would be to change them into links.

**Comment by 01zulfi** [comment]
@DreamVenerable, thanks for the suggestion.


@TheOdinProject/maintainers, what do y'all think?

**Comment by codyloyd** [comment]
agree that we should be consistent.

**Comment by DreamVenerable** [comment]
@rlmoser99 so we should change Turbo and Stimulus lessons to be links?

**Comment by rlmoser99** [comment]
Yes, because that is what our current style guide requests:
https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md

If we want to change this, it is a much bigger conversation.

**Comment by DreamVenerable** [comment]
Sure thing, I can see the merit in link over dropdown

**Comment by thatblindgeye** [comment]
Yeah those lessons really shouldn't have had dropdowns used for the knowledge checks. It's hazy, but I want to say one of the reasons for shifting away from the dropdowns was that users could just go to them and get the answers instead of actually doing the lesson? Maybe something along those lines. The links at least require the user to still re-read the related content so that they can answer the KC.

**Comment by JoshDevHub** [comment]
We're gonna shift this issue towards fixing these Knowledge Check sections to use the format specified in the [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lesson-layout) (see list item number 5)

Acceptance criteria:
- [ ] Update the Turbo lesson to use the correct knowledge check format
- [ ] Update the StimulusJS lesson to use the correct knowledge check format

Do you want to work on this @DreamVenerable ? If so, I'd be glad to assign you. If not, I'll open it up for other contributors.

Also if you want to discuss the format of the knowledge check section and any way you think they can improve, you're definitely free to make a [discussion](https://github.com/TheOdinProject/curriculum/discussions) for that.

**Comment by JoshDevHub** [comment]
Going to open this up for other contributors. Should be a nice opportunity for someone who's new to contributing. See my post above for the acceptance criteria.

**Comment by rubicon2** [comment]
Hi Josh, I would be happy to give this a shot. 

The convention is for the knowledge check links to refer back to earlier sections within the lesson, but there is a question in the Turbo lesson (https://www.theodinproject.com/lessons/ruby-on-rails-turbo) about Turbolinks, which isn't mentioned at all in that lesson.

However, it does appear in the Turbo Drive lesson (https://www.theodinproject.com/lessons/ruby-on-rails-turbo-drive). 

In this instance I take it the correct course of action would be simply to remove a knowledge check item that has no relevant section within the lesson?

**Comment by JoshDevHub** [comment]
@rubicon2 Thank you for volunteering. I'll assign you.

And yes, for the knowledge check on Turbolinks, you can just remove it since it's not referenced anywhere in the lesson.
