### ISSUE TITLE
Ruby Course: Add Rubocop / Linting Lesson

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#27091]
### Discussed in https://github.com/TheOdinProject/curriculum/discussions/25674

<div type='discussions-op-text'>

<sup>Originally posted by **ChargrilledChook** March 14, 2022</sup>

Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Rubocop is a very useful tool that is regularly recommended in Discord (as well as briefly introduced in the OOP section). 

However, it is often also a source of confusion and questions in Discord, with many learners not understanding the difference between Rubocop the gem and the IDE integration. We also give very little context on how to read the output.

Introducing a lesson that covered topics such as installation and configuration, how to interpret / look up offenses on the community style guide and basic customization could provide a lot of value to learners, as well as provide parity with the linting lessons in the JS section.

**2. Acceptance Criteria:**
A lesson that covers:
-  [ ] Gem installation + IDE integration
-  [ ] Difference between CLI and IDE versions, visual examples
-  [ ] Brief explanation of linting
-  [ ] Intro to community style guide + difference between different types of rules (style, lint, performance etc)
-  [ ] Explanation of more confusing rules (such as ABC / cyclomatic complexity metrics)
-  [ ] How to write a custom .rubocop.yml / add plugins

**3. Additional Information:**

If the maintainers like this idea I'm happy to create a more detailed lesson outline for discussion  and/or provide a draft.
</div>

**Comment by JoshDevHub** [comment]
@scheals Gonna discuss the rubocop stuff here. I'll assign you to work on it.

Feel free to ask any questions you may have. I'll post some of my notes, ideas, and links here later when I'm booted back in my Ubuntu environment, although the "Acceptance Criteria" in the OP (originally written by Chook), hits most of the main points I was planning to go over.

**Comment by scheals** [comment]
Just giving a heads up that I'm slowly working on it :) Your notes, ideas and links would be very appreciated!

**Comment by JoshDevHub** [comment]
Thanks for reminding me of this @scheals

In looking at my notes, I had most of the things pointed out above.

I think one of the important things is introducing the idea of linting/formatting. Why is this important? Can borrow ideas from how this is done in the JavaScript course. Probably a good idea to link to an article or wikipedia page or something that explains what "linting" even is. I think some good points to hit on the "why" of it might include:
- helps a team of developers achieve a more consistent style and formatting across the project
- helps catch common errors before runtime (like a missing `end`, for example)
- helps with integrating certain "good" practices. rubocop is nice about suggesting alternate ways to format nested conditionals for example.

I thought it'd be nice to have people create a new "project" or really a playground to install it and try things out. Gives people a place to practice with `bundle init` and adding things to the Gemfile. So maybe a little walk through doing that, have them add the rubocop gem, and then have them make a ruby file that has some blatant lint issues in it ie:
```rb
# linting_playground.rb

def badMethodDefinition a, b
  puts "This method definition has stylistic problems"
end
```
Then they could run the CLI against that and see the problems. Then maybe walk through how to integrate with VSCode and have the diagnostics show up in the IDE itself.

This was just my (unpolished) idea for introducing it. Feel free to ignore or change things lol.

That's about as far as I get with my thinking and development of this. Also think the Acceptance Critera in the original post has some important items to hit on (the style guide, rules that are difficult to understand, etc.)

Definitely let me know if you have any questions or just want feedback on any ideas or anything.

**Comment by scheals** [comment]
Cheers for this Josh. I've been eyeing the JS Linting lesson a little and so far have started to hit on those points I believe.

And as for the new "project" - in the WIP version I'm just getting folks to go back to their Caesar Cipher project. I am going to check like a dozen of such recently submitted projects to check if Rubocop picks up something in every single of them (I would expect that to be the case). This way they can improve something they've already worked on and it'll set the stage for the future test adding. So seems like great minds think alike :D 

CLI -> VSC is my direction as well, especially since w/ VSC we've got the overhead of Ruby-LSP now and things might change.

Fingers crossed I have the first rough draft of the lesson finished by tomorrow.

Also, a mental note for both you and me: 
Ruby-LSP VSC extension has moved to a monorepo, so we need to make sure our links in #27128 are updated.
