### ISSUE TITLE
Custom Properties: <Correct an inaccurate statement>

### ISSUE THREAD

**Issue by bigjordshp** [TheOdinProject/curriculum#27111]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

"First we used JavaScript to add a class attribute on our html element (We don’t have direct access to the html element in the HTML tab on codepen, but you should be able to see the class being applied in the browser’s inspector) so that our page has a default theme."

This is not accurate, the JS changes the class but does not apply a default one.  A setting (using the cogwheel button on codepen) in the HTML tab has explicitly stated that the html should have a class of "dark". This is evident upon opening this code in VS Code, it will not have a default class and what appears to be the light theme will have no styling. If the JS actually applied a default class it would do so in an IDE also. 

Perhaps reword this to : 
"First we applied a default "dark" class to our html element using the settings button on the HTML tab (We don't have direct access to the html element in the HTML tab on codepen, but you should be able to see the class being applied in the browser’s inspector) so that our page has a default theme."

This change would simply be for accuracy, and not having the reader struggling to find how the JavaScript is supposedly applying the default class.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-custom-properties

### (Optional) Additional Comments

This is my first time I hope I didn't mess up anything (per the Contributing Guide). Just trying to be helpful.

**Comment by Jaytpa01** [comment]
This is a really good find!

I wanted to offer an alternative wording that I personally think flows a bit better:

“First, since we don’t have direct access to the root element in the HTML tab on codepen, we’ve applied a default class of `dark` using the settings menu. Feel free to open the pen and change this setting to see how it behaves! Next…"

Either way, no matter what the final decision on the rewording is I’d be happy to work on this!

**Comment by bigjordshp** [comment]
Yeah my rewording is definitely just a loose idea as to what should be explained. Yours is better for sure.

**Comment by wise-king-sullyman** [comment]
Thanks for putting this issue together, @Jaytpa01 that suggestion sounds good to me, have at it!
