### ISSUE TITLE
Foundations/CSS Foundations: Update lists per layout style guide

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#27118]
Lists should be updated in the following ways to align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md):

- Any unordered list items that are created with an asterisk `*` are replaced with a hyphen `-` instead. For example, `* A list item` should be updated to `- A list item`
- Lazy numbering is used for ordered list items, e.g. instead of having list items prefixed with `1., 2., 3...`, they are all prefixed with `1., 1., 1...`
- The list item content is updated so it only has a single space before it. For example, `1.   A list item` has 3 spaces before the list item content ("A list item"), and should be updated to `1. A list item`
- Appropriate punctuation is added at the end of each list item in the "Lesson overview", "Assignment", "Knowledge check", and "Additional resources" sections
  - Follow the [Google style guide ](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists) to determine when to add punctuation
- Any additional updates mentioned for specific lessons

### Guidance:

- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` keyword. 

### Lessons to update

- [x] @Churtified  [Intro to CSS](https://www.theodinproject.com/lessons/foundations-intro-to-css)
  - This lesson should only need a spacing update in the Assignment list, but double checking doesn't hurt!
- [x] @rosecodez  [The cascade](https://www.theodinproject.com/lessons/foundations-the-cascade)
- [x] @Slashmyaxl  [The box model](https://www.theodinproject.com/lessons/foundations-the-box-model)
- [x] @rosecodez  [Block and inline](https://www.theodinproject.com/lessons/foundations-block-and-inline)

**Comment by Churtified** [comment]
I'm also happy to take a lesson here :)

**Comment by rosecodez** [comment]
I would like to pick up a lesson :-)

**Comment by Slashmyaxl** [comment]
I would also be happy to help with any of these lessons.

**Comment by rosecodez** [comment]
If there are no other volunteers in the next days I would like to help with the last lesson :-)

**Comment by thatblindgeye** [comment]
@rosecodez all yours!

**Comment by JoshDevHub** [comment]
Thanks for the work everyone 💪 

Closing this down because all the lessons have been completed.
