### ISSUE TITLE
Foundations/JavaScript Basics: Update lists per layout style guide

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#27119]
Lists should be updated in the following ways to align with our [layout style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md):

- Any unordered list items that are created with an asterisk `*` are replaced with a hyphen `-` instead. For example, `* A list item` should be updated to `- A list item`
- Lazy numbering is used for ordered list items, e.g. instead of having list items prefixed with `1., 2., 3...`, they are all prefixed with `1., 1., 1...`
- The list item content is updated so it only has a single space before it. For example, `1.   A list item` has 3 spaces before the list item content ("A list item"), and should be updated to `1. A list item`
- Appropriate punctuation is added at the end of each list item in the "Lesson overview", "Assignment", "Knowledge check", and "Additional resources" sections
  - Follow the [Google style guide ](https://developers.google.com/style/lists#numbered-lettered-bulleted-lists) to determine when to add punctuation
- Any additional updates mentioned for specific lessons

### Guidance:

- Comment on this issue to let us know you'd like to get a lesson assigned to you. You can also ask for a specific one
- Please wait until you are assigned by a maintainer before starting to work on this issue to avoid multiple people working on the same lessons
- Make sure to read the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) before starting your first contribution
- Please add the following to your PR in the Issues section: `Related to #xxxxx` , since this issue is divided into sections, individual PR's should **NOT INCLUDE** the `closes` keyword. 

### Lessons to update

- [x] @Churtified - [Fundamentals 1](https://www.theodinproject.com/lessons/foundations-fundamentals-part-1)
- [x] @damon314159  [Fundamentals 2](https://www.theodinproject.com/lessons/foundations-fundamentals-part-2)
  - Should only need punctuation added to the sub-bullet points of the Assignment section
- [x] @rosecodez  [JavaScript Developer Tools](https://www.theodinproject.com/lessons/foundations-javascript-developer-tools)
- [x] @Churtified [Fundamentals 3](https://www.theodinproject.com/lessons/foundations-fundamentals-part-3)
- [x] @rosecodez  [Problem solving](https://www.theodinproject.com/lessons/foundations-problem-solving)
- [x] @damon314159  [Understanding errors](https://www.theodinproject.com/lessons/foundations-understanding-errors)
- [x] @Kalki2706  [Project: Rock Paper Scissors](https://www.theodinproject.com/lessons/foundations-rock-paper-scissors)
- [x] @AdebayoEmmanuel  [Clean code](https://www.theodinproject.com/lessons/foundations-clean-code)
- [x] @adityax4  [Installing Node.js](https://www.theodinproject.com/lessons/foundations-installing-node-js)
- [x] @thatsthat  [Fundamentals 4](https://www.theodinproject.com/lessons/foundations-fundamentals-part-4)
- [x] @adityax4  [DOM manipulation and events](https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events)
- [x] @roopxx  [Revisiting Rock Paper Scissors](https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors)
- [x] @Ruchita1010  [Project: Etch a Sketch](https://www.theodinproject.com/lessons/foundations-etch-a-sketch)
- [x] @anasmustafa123  [Fundamentals 5](https://www.theodinproject.com/lessons/foundations-fundamentals-part-5)
- [x] @Churtified  [Project: Calculator](https://www.theodinproject.com/lessons/foundations-calculator)

**Comment by Churtified** [comment]
I'm happy to take some lessons (I would do it all if no one wants). MY OCD would love this.

**Comment by thatblindgeye** [comment]
@Churtified  We'd like to allow as many users to contribute (especially for the first time to open source), so for now I've assigned you one lesson

**Comment by Churtified** [comment]
@thatblindgeye Thanks, I appreciate it. Could you assign and I'll get to it :)

**Comment by thatblindgeye** [comment]
@damon314159 assigned you a lesson!

**Comment by rosecodez** [comment]
Would love to pick up a lesson here :-)

**Comment by thatblindgeye** [comment]
@rosecodez assigned you a lesson!

**Comment by Churtified** [comment]
Happy to take another if required :)

**Comment by thatblindgeye** [comment]
@Churtified since there's a good amount in this issue assigned you another!

**Comment by rosecodez** [comment]
I can pick one more as well :)

**Comment by damon314159** [comment]
If more are going I can help... :P

**Comment by Kalki2706** [comment]
I would also like to take one!

**Comment by AdebayoEmmanuel** [comment]
Please assign me one of the lessons.

**Comment by adityax4** [comment]
Hello there! I'm interested in contributing and would be delighted to take on some lessons. Thank you!

**Comment by thatsthat** [comment]
I can also take one if needed

**Comment by thatblindgeye** [comment]
@Kalki2706 @AdebayoEmmanuel @adityax4 @thatsthat assigned y'all a lesson!

**Comment by adityax4** [comment]
Hey, I'm happy to take on more lessons.

**Comment by thatblindgeye** [comment]
@adityax4 gave you another lesson

**Comment by roopxx** [comment]
Hi there!
I'm excited to contribute to this issue! I'll take this up as my first contribution, perhaps two ;-)

**Comment by Ruchita1010** [comment]
I would also like to take one (or more if needed) lesson!

**Comment by kamranzafar4343** [comment]
I would also like to take one lesson!

**Comment by thatblindgeye** [comment]
@roopxx @Ruchita1010 @kamranzafar4343 assigned you all a lesson!

**Comment by kamranzafar4343** [comment]
@thatblindgeye Is there a timeline in which I should complete?  Because I have my final exams next week, so I will complete this in the current month!

**Comment by thatblindgeye** [comment]
@Churtified assigned you the last lesson!

@kamranzafar4343 I'd say within the next week, within 2 weeks at the absolute latest. If you'd like we can reassign your lesson so that you can focus on exams. We do plan on opening up more issues similar to this, so there'll be other opportunities to contribute when you have the time!

There's no pressure either way, though. I definitely understand needing to focus on exams and nobody would fault you for that, but just let me know!

**Comment by kamranzafar4343** [comment]
Alright, i will do it.

**Comment by thatblindgeye** [comment]
@anasmustafa123 you got it!

**Comment by thatblindgeye** [comment]
@Ac394 thanks for the interest! However all the lessons for this issue have been assigned.

**Comment by thatblindgeye** [comment]
Thanks everyone for their help on this! 🎉
