### ISSUE TITLE
Introduction to Grid: <Broken image>

### ISSUE THREAD

**Issue by EssenceCode** [TheOdinProject/curriculum#27112]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

Image link is broken as we cannot see the proper image and when i opened devtools to check the image link i am getting an privacy error.

broken image screenshot:
![broken-image](https://github.com/TheOdinProject/curriculum/assets/118383162/3d622494-9c02-4667-903e-f4ddfbbbfa56)

checking the image in devtools screenshot:
![link](https://github.com/TheOdinProject/curriculum/assets/118383162/f5e31f52-88d4-45b0-be92-967c75750b16)

privacy error screenshot:
![link-error](https://github.com/TheOdinProject/curriculum/assets/118383162/d73c3563-5098-4870-b5d7-fd3dfd6897d8)

what it should look like:
![what-it-should-look-like](https://github.com/TheOdinProject/curriculum/assets/118383162/afba6afa-145c-4931-90a4-d87308db2bbb)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction-to-grid

**Comment by Jaytpa01** [comment]
I had a look at this myself and everything is working as expected for me. I verified this on both my phone and PC

Looking at the error your browser was showing **NET::ERR_CERT_COMMON_NAME_INVALID** and reading a bit more about it [here](https://cheapsslsecurity.com/blog/fix-err-cert-common-name-invalid/), my best guess is that the image hosting service had misconfigured their SSL certificates - but have since fixed it

**Comment by EssenceCode** [comment]
I just look at the lesson link in my phone and it's also working for me now too. As for the PC i didn't check yet as i am not on my PC.

And from the looks of it, the site itself have the problem and not the link and the site is fixed now. So is it safe to say the issue is resolved?

**Comment by wise-king-sullyman** [comment]
Thanks for reporting! Going to go ahead and close this issue since it sounds like it resolved itself.
