### ISSUE TITLE
Intermediate HTML and CSS - Advanced Selectors: Clarify general sibling selector

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27137]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Should we add a bit to this to clarify that the general sibling selector only selects siblings after the element?

> Finally, if we want to select all of an element’s siblings and not just the first one, we can use the general sibling combinator ~.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors

### (Optional) Discord Name

fabulousgeek

**Comment by wise-king-sullyman** [comment]
I'm not against a slight tweak to make that clear, thanks!
