### ISSUE TITLE
Intermediate HTML and CSS - More Text Styles: Add information on performance considerations with fonts

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27133]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I believe it would be a good idea to add some info on performance considerations and issues with text flashing to the section on fonts.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles

### (Optional) Discord Name

fabulousgeek

**Comment by wise-king-sullyman** [comment]
Sounds like a good addition to me, thanks!
