### ISSUE TITLE
Intermediate HTML and CSS - CSS Units:  Add link to additional resources

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27131]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I recently came across this and really like it as a resource; I think it would be a good addition to the Additional resources:
https://whatunit.com/

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-css-units

### (Optional) Discord Name

fabulousgeek

**Comment by wise-king-sullyman** [comment]
I'm on board with adding this resource, though I'd love if someone that's more knowledgeable about this topic from @TheOdinProject/html-css could chime in.

**Comment by codyloyd** [comment]
while this is neat.. i think it _waaaay_ overcomplicates the issue

**Comment by fabulousgk** [comment]
Ok, np!
