### ISSUE TITLE
How To Deal With Side Effects: Better explanation of Clock going berserk

### ISSUE THREAD

**Issue by Rosendo-Martinez** [TheOdinProject/curriculum#27136]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I do not think the reason the Clock goes berserk is explained well. I think it would be better if it was made explicate that each rerender of Clock calls the setInterval(...), which means you are adding a new setInterval each rerender. This is what makes the Clock go berserk.

Maybe the lesson was trying to get a different point across and that is why it was set up this way, but still I think it is confusing.

![image](https://github.com/TheOdinProject/curriculum/assets/97209503/80cab13a-4f31-4035-8263-5613982926f0)

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-how-to-deal-with-side-effects

**Comment by wise-king-sullyman** [comment]
I agree the explanation seems like it could be improved.

**Comment by stephengroe** [comment]
I'm happy to take this!

**Comment by wise-king-sullyman** [comment]
All yours @stephengroe, thanks!
