### ISSUE TITLE
Intro to CSS: Lesson 3 typo and suggested fixes.

### ISSUE THREAD

**Issue by DominicNugent** [TheOdinProject/curriculum#27148]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the readme.md file for lesson 3 of the CSS exercises (03-grouping-selectors), paragraph 2, the word "instead" is used twice in one sentence. This is redundant. Really, you can tighten up the copy and here's three ways:

Original sentence: "Instead of having a single element with two different rules applied, though, you're instead going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."

Option 1 (smaller fix, deleting the redundant word): "Instead of having a single element with two different rules applied, though, you're going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."

Option 2 (better fix): "For this exercise, you're instead going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."

Option 3 (more complete fix, with my rationale): The first paragraph of this readme covers a coding solution it says we hopefully used, and then tells us that we're not gonna do that here. Really, there's not much value to stating this as whether we pursued that solution or not, you've admitted that it doesn't impact this lesson. So I'd cut down the wording to remove this, which means the first two paragraphs can be joined.

"Let's build a little off the previous exercise. Here, you're going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### (Optional) Discord Name

djn_coder

**Comment by Churtified** [comment]
This would be a good first contribution. I'm happy to take it though if no one wants!

**Comment by JoshDevHub** [comment]
@DominicNugent I definitely agree that the copy can be cleaned up there.

Can you remake this issue over in that the CSS exercises repo? That repo is where problems with those exercises should be addressed.

**Comment by JoshDevHub** [comment]
Went ahead and made it myself. Thank you for your suggestion.

I'll be closing this issue and further work will happen in the css-exercises repo
