### ISSUE TITLE
Javascript : A video resource on visualizing Prototypes and the Prototype Chain. 

### ISSUE THREAD

**Issue by mohammednumaan** [TheOdinProject/curriculum#27145]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

A video resource to help visualize prototypes and the prototype chain. 
Source : https://www.youtube.com/watch?v=01jVgCK-HX4

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors#the-prototype

### (Optional) Discord Name

void.jsx

**Comment by CouchofTomato** [comment]
That section already has quite a few resources so it might be tricky to add this.

@TheOdinProject/javascript Anyone have a view on this?

**Comment by nikitarevenco** [comment]
As someone who recently learnt about prototypes, I really feel this is unnecessary, in my experience the concept isn't incredibly difficult to grasp and there are already enough resources in that lesson imo.

**Comment by mohammednumaan** [comment]
I agree. This doesn't seem to be much of an issue. should I close this issue?

**Comment by thatblindgeye** [comment]
Per comments above will close this
