### ISSUE TITLE
Intermediate HTML and CSS - Custom Properties: New video resource

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27144]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I found this video on custom properties really interesting.  It demonstrates well how much cool you can use these properties, I recommend adding as an additional resource

https://www.youtube.com/watch?v=_2LwjfYc1x8

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-custom-properties

### (Optional) Discord Name

fabulousgeek

**Comment by CouchofTomato** [comment]
@TheOdinProject/html-css Anyone have an opinion on this?

**Comment by codyloyd** [comment]
approved.
