### ISSUE TITLE
Foundations: add extra notes about how password typing works

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#27142]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

We have a note in [Command line basics](https://www.theodinproject.com/lessons/foundations-command-line-basics) about characters not being visible as you type them when using stuff like `sudo`. The learner will however encounter this phenomenon already in at least two of the possible installations (WSL and Linux; not sure about Chrome and MacOS).

~~As this tends to be one of the primary sources of confusions on Discord I think it would be better if we move the note to the Installations lesson~~

As getting confused about how passwords work is in my experience one of the leading causes of confusion on Discord I think it would be better if notes were added to every lesson on the foundations path that involves this (after which the learner has presumably done it enough to know how it works

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### (Optional) Discord Name

asarta

### (Optional) Additional Comments

See [this Discord discussion](https://discord.com/channels/505093832157691914/690588860085960734/1196773996151193660)

Might be a good first issue?

**Comment by Asartea** [comment]
Amended the issue per [Discord discussion](https://discord.com/channels/505093832157691914/1196774968864817262/1197583806790631444):

> Also, Core suggested that it would be a good idea to mention the password thing every time it might pop up in going through the lessons:
> 
>      add a note (like one of the colored notes) in each place in the lesson (where appropriate)

**Comment by JoshDevHub** [comment]
This seems good to me (also seems there's already some core buy-in from the discord)

I'll assign you because you indicated you'd like to work on it @Asartea
