### ISSUE TITLE
Objects and Object Constructors: Explain Object.create

### ISSUE THREAD

**Issue by harristom** [TheOdinProject/curriculum#27143]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The Knowledge Check says you should be able to explain what Object.create does but it is not mentioned anywhere in the preceding material

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

**Comment by Churtified** [comment]
I'm happy to add something, if you have any suggestions :)

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone take a look at this please. There is a resource on Object.create but it only seems to be linked in the knowledge check section.

**Comment by thatblindgeye** [comment]
It's mentioned in the [Dmitri Pavlutin’s article on the this keyword](https://dmitripavlutin.com/gentle-explanation-of-this-in-javascript/) assignment item, albeit very briefly:

>Object.create() creates a new object myDog and sets its prototype from the first argument. myDog object inherits sayName method.

which also links to the MDN docs for Object.create. That said, considering it's such a brief mention, and we have some an additional resource item that links to some videos for it, we could remove the lesson overview item and knowledge check item that mentions Object.create. It feels more like a "there's also this other concept..." kind of topic rather than a "you must understand this as part of the lesson intent".

@Churtified would you be interested in making such an update?

**Comment by Churtified** [comment]
> It's mentioned in the [Dmitri Pavlutin’s article on the this keyword](https://dmitripavlutin.com/gentle-explanation-of-this-in-javascript/) assignment item, albeit very briefly:
> 
> 
> 
> >Object.create() creates a new object myDog and sets its prototype from the first argument. myDog object inherits sayName method.
> 
> 
> 
> which also links to the MDN docs for Object.create. That said, considering it's such a brief mention, and we have some an additional resource item that links to some videos for it, we could remove the lesson overview item and knowledge check item that mentions Object.create. It feels more like a "there's also this other concept..." kind of topic rather than a "you must understand this as part of the lesson intent".
> 
> 
> 
> @Churtified would you be interested in making such an update?

Yes I can do it :)

**Comment by thatblindgeye** [comment]
@Churtified you're assigned!

**Comment by khhuang7** [comment]
> It's mentioned in the [Dmitri Pavlutin’s article on the this keyword](https://dmitripavlutin.com/gentle-explanation-of-this-in-javascript/) assignment item, albeit very briefly:
> 
> > Object.create() creates a new object myDog and sets its prototype from the first argument. myDog object inherits sayName method.
> 
> which also links to the MDN docs for Object.create. That said, considering it's such a brief mention, and we have some an additional resource item that links to some videos for it, we could remove the lesson overview item and knowledge check item that mentions Object.create. It feels more like a "there's also this other concept..." kind of topic rather than a "you must understand this as part of the lesson intent".
> 
> @Churtified would you be interested in making such an update?

Thanks for removing these references! Additional question - when I searched the topic on Discord, it seemed like Object.create was used and previously recommended in various articles. Some of that discussion was within the last 2 years so made it tough for me to induce that Object.create is now outdated. So, could it be worth mentioning this and providing a brief context for "Object.create" somewhere in the TOP material (even if just as an aside), for new developers who come across it in old code or discussions?
