### ISSUE TITLE
<Foundation>: <Lesson:Links and Images, typo>

### ISSUE THREAD

**Issue by Mefisto756** [TheOdinProject/curriculum#27152]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In section "Knowledge check", there is content tree("Introduction, Lesson overview, Preparation etc.") instead of questions 
![image](https://github.com/TheOdinProject/curriculum/assets/5430862/011ce5a5-e45b-4802-9fe7-e102980e2e1d)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images#knowledge-check

**Comment by fabulousgk** [comment]
This is a result of a bad merge: https://github.com/TheOdinProject/curriculum/commit/28009136563b33111dce53068037ffda37001f32
