### ISSUE TITLE
Foundations/Links and Images: Rewrite Knowledge Check with questions

### ISSUE THREAD

**Issue by khhuang7** [TheOdinProject/curriculum#27156]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Knowledge Check section in Links and Images (HTML Foundations) is currently a list of hyperlinks to all sections on the page. Change this list to a list of questions to provide a better test of knowledge.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images#knowledge-check

### (Optional) Discord Name

katastrophe_93180

### (Optional) Additional Comments

I'd love to work on this issue as a test of my own knowledge :)

**Comment by fabulousgk** [comment]
Looks like this got messed up here: https://github.com/TheOdinProject/curriculum/commit/28009136563b33111dce53068037ffda37001f32

Just need to restore the previous

**Comment by fabulousgk** [comment]
And this is a dulpicate of: https://github.com/TheOdinProject/curriculum/issues/27152
