### ISSUE TITLE
Recursive Methods: Solution in assignment is wrong

### ISSUE THREAD

**Issue by BinoManjesh** [TheOdinProject/curriculum#27154]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The solution provided for question 6 in the [article](https://www.codingame.com/playgrounds/5422/js-interview-prep-recursion) linked in the "Test Yourself" section seems wrong to me. It fails the following test case:-
```js
var nestedObject = {
  data: {
    a: { value: 1 },
    b: { value: 2 },
  },
};

console.log(contains(nestedObject, 2)); // should be true, returns false

function contains(obj, value){
	for(var key in obj){
		if(typeof obj[key] === 'object'){
			return contains(obj[key], value);
		}

		if (obj[key] === value){
			return true;
		}
	}
	return false;
}
```

Correct code:
```js
function contains(object, value) {
  if (typeof object != "object") {
    return object === value;
  }
  for (const key in object) {
    if (contains(object[key], value)) {
      return true;
    }
  }
  return false;
}
```

Maybe a note should be added with the correct code?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods

### (Optional) Discord Name

bonothebonobo

**Comment by JoshDevHub** [comment]
Yeah this makes sense to me.

Main problem I have with a note is that it will probably get read before the user has had a chance to attempt the exercise for themselves. So we probably want some way to:
1. Tell the user there's an issue with that problem's solution
2. Show the actual solution, but in a way where a learner couldn't immediately read it accidentally. A link strikes me as the most obvious way to do it.

What do you think? @BinoManjesh ?

**Comment by BinoManjesh** [comment]
Yes adding a link would be better

**Comment by JoshDevHub** [comment]
Okay cool I'll assign you to work on this @BinoManjesh 

### Acceptance Criteria
- [ ] Add a note that explains the answer to problem 6 in the assignment is incorrect
- [ ] In the note, embed a link to [this gist](https://gist.github.com/JoshDevHub/b00125f483d4a1ecc257eaa030916973) where I've written down the actual answer. This is mostly the same code as what you've shown, it just sidesteps a bug with `null` (because `typeof null === 'object'`), and uses more modern practices (ie. no `var`).

Let me know if you have any questions
