### ISSUE TITLE
Homepage: Google form survey questions mix JS and Ruby path

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/curriculum#27164]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

<img width="478" alt="image" src="https://github.com/TheOdinProject/curriculum/assets/48169481/2c6d66c9-4a1a-42f2-ba2a-cc4f886a4abc">

https://discord.com/channels/505093832157691914/505093832157691916/1197955195083169792

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-homepage

### (Optional) Discord Name

Fred | Blog API

**Comment by JoshDevHub** [comment]
Yeah this should definitely be updated. Thanks for making this @JustWaveThings :raised_hands:

**Comment by KevinMulhern** [comment]
Thanks for reporting @JustWaveThings 

Fixed!
<img width="320" alt="Screenshot 2024-01-29 at 08 34 09" src="https://github.com/TheOdinProject/curriculum/assets/7963776/4a644e8c-b470-4457-9da3-b767ec570237">
