### ISSUE TITLE
Express 101: tell people not to delete the boilerplate

### ISSUE THREAD

**Issue by ddomhall** [TheOdinProject/curriculum#27179]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I might be an idiot but following the MDN tutorial, I deleted all the boilerplate for a 'fresh start' and then realised I needed it half way through so I had to 'merge' a fresh copy with my progress so far.

Suggesting a simple change to the last 2 sentences of step 2 of the assignment from:
"You only have to do part 2 for now. We will continue where we leave off later."
to:
"You only have to do part 2 for now. Don't delete anything and we'll continue where we leave off later."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-express-101

### (Optional) Discord Name

domozor

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @ddomhall, any thoughts on this one @TheOdinProject/javascript?

**Comment by thatblindgeye** [comment]
I'm not sure it's really necessary to add that in, as the verbiage does state that we'll continue where we left off later. I wouldn't be super opposed to including the verbiage, but this could just have been a mistake that could have happened even with that disclaimer. Maybe the implied "don't delete anything" that comes with "we'll continue where we left off" isn't enough, but it may also depend how much time passed between doing this assignment and deleting things. Even with a disclaimer, it may not be remembered if stuff was deleted some time after this assignment was completed.

**Comment by ddomhall** [comment]
It's such a small issue that I'm happy for it to be deleted or closed as not planned, only worth acting if multiple people raise something similar. It's just a user error that took an hour or two to fix

**Comment by thatblindgeye** [comment]
@ddomhall I'll leave this open for now to see if anyone else ran into a similar issue

**Comment by thatblindgeye** [comment]
Going to close this for now. If anyone has other thoughts please feel free to comment.
