### ISSUE TITLE
Setting up Git: <change link on ssh test>

### ISSUE THREAD

**Issue by LorenzoAngius** [TheOdinProject/curriculum#27172]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hi, i think it's better if the link to the guide to test the ssh key (step 2.5) should point directly on the linux tab, since everyone will use that information, except for mac user. it saves some headaches trying to use git bash instead of the terminal for who use WSL (like myself LOL). Thank you very much

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### (Optional) Discord Name

Angius

**Comment by kamranzafar4343** [comment]
@TheOdinProject Can someone take a look at this please!

**Comment by fortypercenttitanium** [comment]
> @TheOdinProject Can someone take a look at this please!

Please do not ping us to look at issues on our own repository. We will get to them when we get to them.

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @LorenzoAngius, @TheOdinProject/installations I'd appreciate any input you have please?

**Comment by xandora** [comment]
Sounds like a reasonable suggestion to me. 👍

**Comment by JoshDevHub** [comment]
Seems people are on board with this :rocket:

Since the original poster indicated that they don't want to work on it, I'll open it up for others to contribute to. Also seems like it'd be a nice first issue.

### Acceptance criteria:
- [ ] Change the link under step 2.5 that has the text "this article from GitHub" to point to:
    ```
    https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection?platform=linux
    ```
Comment below to be assigned.

**Comment by rupaltyagi** [comment]
Hello! I would like to work on this issue for my first contribution. Can you assign this issue to me?

**Comment by JoshDevHub** [comment]
Hi @EssenceCode 

Thank you for volunteering. I've assigned you to work on this. Let me know if you need any help.

Thank you for volunteering as well @rupaltyagi ... unfortunately I had to give it to the first person who volunteered. You can check out our other issues for more opportunities to contribute. The issues for updating lists in the curriculum (like [this one](https://github.com/TheOdinProject/curriculum/issues/27118)) are good for first time contributors.

**Comment by rupaltyagi** [comment]
It's okay @JoshDevHub The one you suggested has been closed but I'll look for some more first good issues.
