### ISSUE TITLE
Foundations: Add warning against posting project submissions containing NSFW content

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27171]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I saw someone come in the discord chat saying that they got banned for posting a project submission containing NSFW material, and they had no idea that wasn't allowed. So I think it would be very useful to have an important notice on the first/first and second project letting people know that if they ever submit a project with NSFW material their account will be banned.

Obviously, 99.9% of people wouldn't ever do something like this, but it is important to understand that there are most likely actual children going through TOP and it would be best to minimise the risk of something like this happening.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes

**Comment by kamranzafar4343** [comment]
@nikitarevenco how do we do that?

**Comment by kamranzafar4343** [comment]
I would like to contribute with some guidance! Like from where should i start this?

**Comment by fortypercenttitanium** [comment]
@nikitarevenco Was the person banned from Discord or from the TOP site?

**Comment by nikitarevenco** [comment]
> @nikitarevenco Was the person banned from Discord or from the TOP site?

They were banned from the TOP site

**Comment by fortypercenttitanium** [comment]
My initial reaction to this is that people should have a bit of common sense. If you complete a project using NSFW material, that's fine, but actually submitting it to the site to showcase? When there are very clear "Report" buttons? I'm not so sure this change is necessary.

I'll wait to hear what others have to say.

**Comment by KevinMulhern** [comment]
I agree with @fortypercenttitanium, this is the first time a legitimate user has been banned over this. It's usually bots or trolls. It may be an overreaction to slap down warnings for the moment.

But if it happens again, we could [link to this part of our community rules](https://www.theodinproject.com/guides/community/rules#respect) before learners submit their first project. Our solutions are an extension of our community - the same guidelines for posting content should apply.

**Comment by kamranzafar4343** [comment]
> I agree with @fortypercenttitanium, this is the first time a legitimate user has been banned over this. It's usually bots or trolls. It may be an overreaction to slap down warnings for the moment.
> 
> But if it happens again, we could [link to this part of our community rules](https://www.theodinproject.com/guides/community/rules#respect) before learners submit their first project. Our solutions are an extension of our community - the same guidelines for posting content should apply.

This is best decision for this issue.
