### ISSUE TITLE
Flexbox Alignment: Deemphasise focus on media queries in article examples

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#27170]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

[Part 5](https://css-tricks.com/snippets/css/a-guide-to-flexbox/#aa-examples) of assignment link 3 includes a few examples involving media queries. While these aren't really focused on, [this Discord Q](https://discord.com/channels/505093832157691914/516751477306294273/1198223795698270218) made me wonder if it would be on the safe side to just mention in the assignment text not to worry about the media query parts and that they will be covered later in the course? Just to reassure the learner they've not missed anything/avoid going down a potential rabbit hole.

e.g.
> The [CSS Tricks “Guide to Flexbox”](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) is a classic. The images and examples are super helpful. It would be a good idea to review parts 1-3 and part 5 (don't worry about the media query parts, we will cover them later in the course) and then bookmark it as a great cheat sheet for future reference (keep it handy for the practice exercises).

Thoughts?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-alignment

**Comment by KevinMulhern** [comment]
Thanks @MaoShizhong, sounds like a good idea 💪
