### ISSUE TITLE
Tables: <Malicious website under tables section>

### ISSUE THREAD

**Issue by YvesConcepcion** [TheOdinProject/curriculum#27186]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

https://pencilandpaper.io/articles/ux-pattern-analysis-enterprise-data-tables

Pencil & Paper published a great [article about things you can achieve with tables](https://pencilandpaper.io/articles/ux-pattern-analysis-enterprise-data-tables) if you dare to spend some time giving them some love. They suggest some good habits on how you should format your data which is pretty simple and makes a huge difference. These are not a list of must dos to a table, but ideas worth keeping in mind for the next time a table is bothering you with how it looks

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-tables

**Comment by Lofty-Brambles** [comment]
What is the "malicious" website here? 'Cause all I see is the article that read just right?

**Comment by JoshDevHub** [comment]
Yeah I don't see anything malicious here. Can you provide any more information about what problem you're seeing @YvesConcepcion

**Comment by YvesConcepcion** [comment]
My apologies, when I clicked on the article 2 days ago I was redirected to an iPhone giveaway, I tried accessing it now and the issue seems fixed. 

https://pencilandpaper.io/articles/ux-pattern-analysis-enterprise-data-tables/

**Comment by JoshDevHub** [comment]
Okay cool. Thank for reporting @YvesConcepcion ... definitely want to be alert about these sorts of things.

Gonna close this issue down since it seems to have been resolved.
