### ISSUE TITLE
Restaurant Page: Student solution does not work anymore. Yesterday it did

### ISSUE THREAD

**Issue by CescoMinchia** [TheOdinProject/curriculum#27182]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

can we ask the student to publish the solution again?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-restaurant-page

### (Optional) Additional Comments

Thank you

**Comment by KevinMulhern** [comment]
Thanks for reporting, the link on step 6 of the assignment is broken

> Next, set up your restaurant site to use tabbed browsing to access the Contact and Menu pages. [Look at the behavior of this student solution](https://eckben.github.io/bearysBreakfastBar/) for visual inspiration.
