### ISSUE TITLE
Private Events: As of 23/01/2024 the link for 'Add Solution' does not work.

### ISSUE THREAD

**Issue by MKMaths22** [TheOdinProject/curriculum#27189]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

On the Project: Private Events page, the button is faulty for 'Add Solution', above the list of solutions. I have tried single and double-clicking it, to no avail.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-private-events

### (Optional) Discord Name

PJPlaysDoom

**Comment by JoshDevHub** [comment]
Can you remake this issue on the main site repo? @MKMaths22 

Link: https://github.com/TheOdinProject/theodinproject

This repo only holds curriculum content in markdown files. We have no way of adjusting anything about how the site works here. I'll be closing this issue, but definitely remake it on the main site where it can be addressed.
