### ISSUE TITLE
Foundations Course: video and audio tags not introduced

### ISSUE THREAD

**Issue by kadzaki** [TheOdinProject/curriculum#27199]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Video and audio tags are not introduced in the "HTML Foundations" section in "Foundations Course"

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

**Comment by KevinMulhern** [comment]
Same as https://github.com/TheOdinProject/curriculum/issues/27198#issuecomment-1908642154
