### ISSUE TITLE
Foundations Course: Links and Images

### ISSUE THREAD

**Issue by kadzaki** [TheOdinProject/curriculum#27198]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

On the "Links and Images" lesson, there is no mention to the mailto syntax when creating links.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @kadzaki, but thats intentional, we only cover what learners will find relevant and be able to use in the projects that come after. 

TOP doesn’t aim to cover everything, that would be a slog for learners and best left for official documentation.
