### ISSUE TITLE
Markdownlint: Format of math expressions with multiplication

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#27200]
### Problem

In a few places in the curriculum, the asterisk character is used in the lesson content for specifying multiplication operations. One example of this can be seen in the time complexity lesson: [link](https://github.com/TheOdinProject/curriculum/blob/main/javascript/computer_science/time_complexity.md?plain=1#L224)

These expressions can raise issues with Markdownlint where it's interpreting these as emphasis markers. We should come up with an accepted style for how to write these without triggering any problems with Markdownlint.

### Possible Solutions:
1. The expression can be wrapped in backticks ie:
    ```md
    The factorial of 4(4!) is `4 * 3 * 2 * 1`.
    ```
2. The expression can escape the asterisks with `\`:
    ```md
    The factorial of 4(4!) is 4 \* 3 \* 2 \* 1.
    ```
3. Instead of an asterisk, the multiplication unicode symbol can be used. The HTML entity is `&times;` and it renders to look like &times;
    ```md
    The factorial of 4(4!) is 4 &times; 3 &times; 2 &times; 1.
    ```
Maybe there are some others as well, but these are the ones that immediately come to mind for me.

**Comment by JoshDevHub** [comment]
Do you have any opinions on this @thatblindgeye ?

**Comment by thatblindgeye** [comment]
Ah good catch on this!

I personally would probably lean towards using inline code, but honestly I would be fine with any of the options you outlined above.

**Comment by JoshDevHub** [comment]
Yeah I think I'm leaning inline code too.

I think I'll add a little note in the LAYOUT_STYLE_GUIDE around where emphasis is mentioned.
