### ISSUE TITLE
Fundamentals Part 1: <Short description of your suggestion>

### ISSUE THREAD

**Issue by elamien** [TheOdinProject/curriculum#27204]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

4. Let’s use variables!
Type this statement at the top of the script tag: let a = 10
In the console console.log(a) should print 10
Try the following in the console: 9 * a
and this: let b = 7 * a (returns undefined *) and then console.log(b)

"(returns undefined *) " returns undefined where? We were just working within our file ("let a = 10") and it suddenly is referring to "b = 7 * a" returning undefined, but we are still in the file right...? a new learner would think so but it is actually referring to typing "b = 7 * a" within the console NOT the file we are playing around in. It DOES NOT instruct us to try "b = 7 * a" IN the console, it only assumes for us to know that. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-1#assignment

### (Optional) Discord Name

humood

**Comment by allamein** [comment]
Thanks @JoshDevHub ! I'm on it!

**Comment by JoshDevHub** [comment]
@elaminy 

Are you still working on this? No rush, just interested in the status of it.

**Comment by elaminy** [comment]
Will get done tomorrow since im all free now!

**Comment by Rllopez0410** [comment]
Hey @elamien, are you i can take care of this issue if you're occupied.

**Comment by KevinMulhern** [comment]
Hey @Rllopez0410, sorry it's been a while, are you still interested in this one?

**Comment by Rllopez0410** [comment]
@KevinMulhern yes.

**Comment by KevinMulhern** [comment]
Thanks @Rllopez0410 💪
It's assigned to you!
