### ISSUE TITLE
Binary Search Trees: Clearer distinction between node and value

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#27217]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Many learners when they show their code snips for this project tend to think (which they show in their code) that nodes and value as the same thing. They will traverse the tree for a value to delete or get the height of, instead of taking a node. Their post/pre/in-order callbacks will accept a value as their argument, instead of a node. That sort of thing. It leads to a lack of understanding of the point of a tree, which is to arrange objects, not numbers, and to hard to repair code, since its rarely clear to the learner at any given moment what arguments should be of what type 

The lesson muddies the waters on this by stating that the delete function should accept a value instead of a node, when this isn't the case. The only functions that should have arguments of value are those that would construct a new node (insertions), or exactly the function find. All others should work exclusively with the nodes themselves. Then you can leverage find to return references to certain nodes from their value when appropriate (`delete(find(value))`). 
In fact it might even be more appropriate to say that insertions should take a node argument too, and have them be called with an explicitly constructed node, but I'd be willing to compromise on that one. Something like this: `insert(new Node(value))`

This to some extent may also apply to the linked list lesson, but it is most prevalent here. I think a reword of the assignment with this in mind, as well as a note earlier in the lesson talking about the difference between a node and a value could help.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-binary-search-trees

**Comment by JoshDevHub** [comment]
I think the expectations could probably be made more clear. Imo it'd be cool to have the requirements work a bit more like they do in the [linked list assignment](https://www.theodinproject.com/lessons/javascript-linked-lists#assignment), where parameters are explicitly shown.

I disagree with you regarding `delete()` though. This should absolutely take a value param for a couple of different reasons:
1. A user of the code is much more likely to delete by value.
2. `delete(find(value))` is an inefficient method of deleting by value. If the target to delete is a leaf node, you don't want to pull a reference to the target directly. You need a reference to its parent node, and then set the parent's `left` or `right` (whichever is pointing to the target) to `null`. Seems to me that way of doing it double searches the tree, which is no good.

To me, having `delete()` take a node would be like having objects/hash maps take a node to access a value. That may be how the data is stored internally, but a user of the interface doesn't need to care or even know how the structure works internally.

**Comment by damon314159** [comment]
The double search is a valid concern - point taken

**Comment by JoshDevHub** [comment]
If you have any interest, I'd still gladly accept a PR that includes parameter data for the different methods (like the linked list project does).

Or if you don't, we could close this down. Let me know :thumbsup:

**Comment by damon314159** [comment]
Yeah I'll do that

**Comment by JoshDevHub** [comment]
Cool. I'll assign you then :+1:
