### ISSUE TITLE
Fundamentals Part 2: <Instructed to do exercises at the end, except there are none.>

### ISSUE THREAD

**Issue by elamien** [TheOdinProject/curriculum#27214]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In step 2 o strings, it says "Go through [this lesson](https://www.w3schools.com/js/js_string_methods.asp) to learn a bit more about what you can do with strings… be sure to take a peek at [the String Reference](https://www.w3schools.com/jsref/jsref_obj_string.asp) page near the bottom, and do the exercises at the end!" except that there are no exercises at the end of the page they link which is (https://www.w3schools.com/jsref/jsref_obj_string.asp)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-2

### (Optional) Discord Name

humood

**Comment by fabulousgk** [comment]
I believe the intent is to do the excersises at the end of the lesson link, not the reference.  I can see the confusion there, probably just a small rewrite to clarify.

**Comment by JoshDevHub** [comment]
Yeah I could see how this could be a little confusing, but it means to do the exercises at the bottom of the first link. Should be able to change the wording around to make this more clear.

Since you indicated you'd like to work on this, I'll assign you @allamein

**Comment by fabulousgk** [comment]
If @elaminy no longer wants to do this change, I will do it.

**Comment by elaminy** [comment]
@fabulousgk Sorry I have been extremely busy with college applications. I can still do it after a few days. If you would instead do it now, that is okay with me.

**Comment by fabulousgk** [comment]
@elaminy No problem at all, you have at it.  I just wanted to make sure it got done is all.  Good luck with your applications!

**Comment by JoshDevHub** [comment]
Yeah you're very welcome to keep working on it @elaminy 

Let us know if you need anything.

**Comment by Rllopez0410** [comment]
if @elaminy is still busy, i would love to take over this issue for an immediate fix if that's okay.

**Comment by elaminy** [comment]
you got it @Rllopez0410

**Comment by Rllopez0410** [comment]
@JoshDevHub is that okay with you as well?

**Comment by JoshDevHub** [comment]
Sure I'll assign you to work on it @Rllopez0410 

Let me know if you have any questions.
