### ISSUE TITLE
Javascript course -> javascript-working-with-remotes: $ git push origin main $ git rebase -i --root $ git push --force $ git log. |"The command git push --force doesn't work|"

### ISSUE THREAD

**Issue by sabbir292** [TheOdinProject/curriculum#27211]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

javascript-working-with-remotes: 
$ git push origin main 
$ git rebase -i --root 
$ git push --force 
$ git log 

(after the rebase we cannot force push the changes with just "git push --force" as we are not in any branch. the command should be "git push --force origin <remote branch>").

Error : fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-working-with-remotes

### (Optional) Discord Name

sabbir292

### (Optional) Additional Comments

Thanks for creating the awesome course.

**Comment by JoshDevHub** [comment]
Nice find. Assigning you to correct the command.

**Comment by sabbir292** [comment]
Thank you for your response ❤️

**Comment by sabbir292** [comment]
Thank you for assigning me. I am on it 😊

**Comment by sabbir292** [comment]
Kindly unassign and close this issue, as the issue occurred due to my own mistake.

like this issue only occurs if we modify a file, lets assume I have created file1.md and then added some text in it. |
later if I do a git reabse -i --root and delete the commit that added the file1.md, then the head is detached and if we want to force push it wont work, 

sorry for creating the issue.

**Comment by JoshDevHub** [comment]
Ah somehow I missed that your head had gotten detached.

Yeah this makes sense, and no worries. These kinds of things happen.
