### ISSUE TITLE
Installations: Brand WSL2 as advanced

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#27218]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

While WSL2 is probably the easiest to install, it is the hardest to reason about and understand what is on the Windows side, what is on the Ubuntu side, what is WSL2, where one should seek help `#ubuntu-help` or `wsl-help`? Google for Ubuntu solutions or Windows solutions? WSL2? Solutions?

[A message from a user YourLocalCafe on Discord](https://discord.com/channels/505093832157691914/1179839248803844117/1200812470214864897) illustrates this perfectly:
> Maybe this is just me but the installations for WSL2 are kind of confusing. Like the VS Code and Chrome installations are just the regular windows installs which I already had on my system. But when I tried to follow along the linux instructions (as is said to do in the curriculum) my WSL2 complains that the installations are missing, maybe this is because it runs in a different partition, so to solve this they need to be installed separately with the linux instructions in that partition. (At least thats how I was able to follow the linux instructions later.)
Is there something I am missing here? Because I cant seem to get my existing windows install  to work with WSL2 for Chrome.
VS Code however, got auto installed by WSL2 when I tried to run code . in the terminal after installing the WSL extension on VSC.
Thank you for taking the time to read this.
:) 

As such, I suggest two things:
- Add `Advanced` next to WSL2,
- Mention that WSL2 is still installing and using a new OS - there have been people that have decided on WSL2 because they thought they are not going to change the OS they're using. To some degree it is true but it also illustrates how confused about WSL2 people are.
- Reiterate that VirtualBox is going to be the easier option.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

**Comment by JoshDevHub** [comment]
This all sounds completely reasonable to me. Assigning you @scheals :raised_hands:
