### ISSUE TITLE
Using Git in the Real World: Conventional commits

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#27216]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

A suggestion that it might be worth including conventional commits in the real world git lesson, since a large number of people have adopted the standard in some capacity, and meaningful commit messages are made that much easier by there being a convention to follow which is designed with consistency and communication in mind

https://www.conventionalcommits.org/en/v1.0.0/

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world

**Comment by fabulousgk** [comment]
It is linked way back in the commit messages lesson.  But a refresher here might be good.

**Comment by JoshDevHub** [comment]
I don't think there's any harm in mentioning it again. Assigning you to work on it @damon314159 :+1:

**Comment by CBID2** [comment]
Hey @damon31415. If you need help on how to describe these kinds of commits, feel free to refer to my [freeCodeCamp article on this topic ](https://www.freecodecamp.org/news/how-to-write-commit-messages-maintainers-will-like/)
