### ISSUE TITLE
Rails Basics/Express & Mongoose: Update costs associated with Fly.io (they updated their pricing)

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/curriculum#27213]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Fly.io recently announced that they will begin charging for stopped machines, based on the disk space it's using. 
https://community.fly.io/t/we-are-going-to-start-collecting-charges-for-stopped-machines-rootfs-starting-april-25th/17825

All the details are in that announcement, but it is to my understanding that your project will not cost $0. Since our usage would be very, very low, I imagine that the vast majority of users would pay close to $0 anyways, but it might be nice to mention this so no one is surprised when time comes for billing.

Both of these would need a slight update in wording:
The Rails deployment lesson: https://www.theodinproject.com/lessons/ruby-on-rails-deployment
The Node.js deployment lesson: https://www.theodinproject.com/lessons/nodejs-deployment

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-deployment

### (Optional) Discord Name

Eduardo06sp

**Comment by JS-tice** [comment]
Their announcement seems a bit unclear on their pricing model going forward:

> Is this the end of Fly.io free allowances?
> 
> No. Our free allowances let you run ‘Up to 3 shared-cpu-1x 256mb VMs’ 24/7. We also have been discounting up to $5.00 of usage on invoices so that means if you have 3 stopped machines for the entire month each having 1GB of RootFS usage that is $0.45 so far from breaking your free allowances.

This seem to imply that usage under $5 will be free, but their docs mention no such discount.

**Comment by Eduardo06sp** [comment]
I visited the billing preview that they updated
https://fly.io/dashboard/personal/billing

it shows me an estimated charge of less than $0.1,
further adding to my confusion

just wanted to throw in there that someone asked for clarification about this,
but they never replied to them in that forum post :cry:

**Comment by JoshDevHub** [comment]
Hmm yeah, this is confusing.

Maybe we can just be less specific for now and say that come April, you *may* receive small charges for having apps deployed on Fly.

We can be more specific after it goes live and we see how much learners are being charged to host apps there.

**Comment by Eduardo06sp** [comment]
I think that's the best option for now.

I would love for this Issue to be shared in our `#contribution-opportunities` channel because it's a nice little opportunity for first-time contributors. Just a suggestion! :}

**Comment by JoshDevHub** [comment]
Yeah cool. New acceptance criteria. Also should be approachable for first time contributors

### Acceptance Criteria
- [ ] In both the Rails and Node deployment methods, mention that Fly is changing their pricing model in April and that learners may be charged a small monthly fee (almost certainly less than $1 USD) for hosting apps on the platform.

Comment below to be assigned.

**Comment by JS-tice** [comment]
They answered a question clarifying their pricing model today:

> @lubien You state that “We also have been discounting up to $5.00 of usage on invoices so that means if you have 3 stopped machines for the entire month each having 1GB of RootFS usage that is $0.45 so far from breaking your free allowances.”.
> 
> Just to be sure: Does that mean that if my billing per month does not exceed $5.00 per month I have to pay nothing? Or is that meant in the way that you don’t bill before $5.00 are exceeded in the sense that if one uses $0.51 of machines for 10 months, one will be billed? In that case that would be the end of free allowances wouldn’t it?
> 
> Just to be clear currently it looks like my monthly billing with the new charging scheme will be more around $0.60 per month, however I want to know whether I will be able to use fly.io for free only for some months after the changes or longer term.

[Their response](https://community.fly.io/t/we-are-going-to-start-collecting-charges-for-stopped-machines-rootfs-starting-april-25th/17825/29):

> Hi @RaoulLuque !
> 
> I can see you’re on the old Hobby Plan which is $0/mo. We have our free allowances that let you run 3 machines 24/7 AND also the waiving of invoices that are lower than $5 (thats not going change now) so you should be good to go with zero charges. If things ever change on your account we will make sure to communicate with a big heads up too but if you feel more comfortable you can also let your machines just run 24/7.

To summarize:

Fly.io includes offers the following resources for free

- Up to 3 shared-cpu-1x 256mb VMs
   - The VMs are completely free while they are running, but they might add a few cents to your invoice if you leave them stopped.
   - Invoices under $5 are waived, so you don't need to worry about being charged even if you have free machines stopped, so long as you stay within these limits.
- 3GB persistent volume storage (total)
- 160GB outbound data transfer

Perhaps it is still a good idea to add this information to the lessons, so that students don't see small amounts in their invoices and think they will be charged, specially since the bit about invoice waving is not mentioned in their documentation.

**Comment by RaoulLuque** [comment]
As the person that asked the Question on the Fly Forum - in a sense a student. I would find the addition of that information especially the (monthly!) waving quite helpful/useful.

**Comment by alexkozlovm** [comment]
Can I please be assigned to this?

**Comment by JoshDevHub** [comment]
Sure thing @alexkozlovm 

I've assigned you. Let me know if you need anything.

**Comment by alexkozlovm** [comment]
Thank you, I can work on this as soon as #27263 (My PR) is closed or merged.

**Comment by maahsnd** [comment]
If @alexkozlovm is not working on this, I'd be happy to.

**Comment by JoshDevHub** [comment]
It appears they've stepped away from this so yeah, I'll reassign it to you @maahsnd 

Let me know if you have any questions.
