### ISSUE TITLE
Computer science: Warn about potential confusion with C and C++ code.

### ISSUE THREAD

**Issue by kahmoh** [TheOdinProject/curriculum#27224]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Project: Recursion, there is a link to a wikipedia article explaining the merge sort algorithm and showing examples in what I believe is c++ code. For me trying to make sense of this code was very difficult compared to a language like Javascript, this issue is suggesting a warning about the C and C++ code that shows up in the computer science section, as I believe learners could get stuck trying to understand it. 

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursion

### (Optional) Discord Name

kahmoh

**Comment by JoshDevHub** [comment]
Sorry if this caused you confusion.

I think a little note that warns learners off reading the code in that wikipedia article would be good. Since you indicated you'd like to work on this, I'm assigning it to you @kahmoh
