### ISSUE TITLE
React: Disable AI for Code Sandbox Repos

### ISSUE THREAD

**Issue by Samuel-Duncan** [TheOdinProject/curriculum#27239]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Currently, AI code completion is enabled in the Code Sandbox repository in the assignment section of the Class Based Components lesson for React. This makes the assignment trivial, as the AI practically does all of the work for you. There is an option to disable AI for all users who access a sandbox repo. I have included this option as a screenshot. I currently have not noticed this issue in any other sandboxes on the TOP website, however it would be ideal to ensure this setting is applied to all sandbox repos on the website for learning purposes. Please let me know if there is anything I can do to contribute to fixing this!
![disable-code-sandbox-ai](https://github.com/TheOdinProject/curriculum/assets/110263216/7d5c4aca-a4c6-465d-9ae3-91ea46613220)

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-class-based-components#assignment

### (Optional) Discord Name

mantra_mantis

**Comment by CouchofTomato** [comment]
@TheOdinProject/react 

Can someone take a look at this please.

**Comment by nikitarevenco** [comment]
As an example, just take a look at the code below. I was doing an exercise and the AI just completes the entire line for me. Really annoying.

![image](https://github.com/TheOdinProject/curriculum/assets/154856872/5d23b572-aaa9-4e9c-b6ea-e7937fe4d70f)

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Still need someone to review this.

**Comment by MaoShizhong** [comment]
Closing as it looks like this has been resolved.
