### ISSUE TITLE
Computer Science: Recursion Project: Use proper heading structure

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#27238]
### Problem

The recursion project content in both the JavaScript and Ruby paths should change to conform to the [project layout](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#project-layout) specified in the LAYOUT_STYLE_GUIDE.

This will involve a bit of a refactor on the organization of the content, as currently there are two separate assignments on the page and no introduction.

### Lesson(s)
- https://www.theodinproject.com/lessons/ruby-recursion
- https://www.theodinproject.com/lessons/javascript-recursion

### Acceptance Criteria
- [ ] Add an introduction section to the project
- [ ] Move the Fibonacci exercise and the merge sort exercise into one assignment block
- [ ] Make sure you change the project content in both the Ruby and the JavaScript course material

**Comment by thomasmcinnis** [comment]
@JoshDevHub this is tangentially related to my recently opened issue #27392 

I would be happy to have a run at this under advice but the time to complete may be several weeks.

**Comment by JoshDevHub** [comment]
Yeah I can assign this to you as well. When you make the PR, you can link both issues for closing.

And let me know any questions you might have on this one. I realize I left rather nonspecific, abstract requirements.

**Comment by thomasmcinnis** [comment]
Reflecting on the project and its relation to the preceding Recursion Lesson, is the Fib assignment valuable? I get why the fib problem was written as a Warmup. In some ways it feels like it belongs to the proceeding module.
I can absolutely roll it into a dual project with Merge Sort, just flagging that they seem like an odd-couple! Especially because the bulk of the background and required reading on this Project will relate to the meatier task of Merge Sort.

**Comment by JoshDevHub** [comment]
I like the Fibonacci exercise. It has an interesting wrinkle it that can make for a challenging problem to solve.

I'm probably willing to be swayed on it, but it's probably best that's moved to a different issue so things specific to that can be discussed (ie. what do we do about all the existing fib/merge sort project solutions?).

For this issue, let's just stick to having the two together for now.

**Comment by thomasmcinnis** [comment]
@JoshDevHub before I do this for Ruby as well and submit the PR, maybe have a look at this preview and let me know if I am on the right track:
https://www.theodinproject.com/lessons/preview?uuid=43d6fbd8-c5f9-4066-8216-8fc7309fd2f7

**Comment by JoshDevHub** [comment]
@thomasmcinnis That looks excellent! You're absolutely on the right track :rocket:
