### ISSUE TITLE
<React>: <Type Checking with Prop Types additional resources>

### ISSUE THREAD

**Issue by Dillonpw** [TheOdinProject/curriculum#27249]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The additional resources section is currently empty for this lesson, I'd like to suggest a few useful links that will provide extra information for those curious about adopting TypeScript for their later projects.

"If you are interested in using TypeScript in your upcoming projects and want to learn more:"
- [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/2/basic-types.html)
- [Official React docs TypeScript guide](https://react.dev/learn/typescript)
- [Open source React/TypeScript cheat sheet](https://react-typescript-cheatsheet.netlify.app/docs/basic/setup/)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-type-checking-with-proptypes

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Anyone have an opinion on this?

**Comment by MaoShizhong** [comment]
Not Xari but I'm of the opinion that we leave the proptypes lesson as is i.e. not add typescript resources in the AR section, nor move the `What about TypeScript` section.

It's agree that it'll unlikely cause anyone who's already chosen to use TS independently to stop using TS for the rest of the course (although I actually did that not too long into the Node section). However, I think it still has benefits of bringing attention to why TS isn't included in the curriculum for now and also reassuring anyone who may be considering it around this point. The placement in this particular lesson is topical and keeping it in the main lesson contents both (IMHO) enhances visibility and reinforces the bullet for assignment step 1.

**Comment by thatblindgeye** [comment]
@MaoShizhong at the very least what do you think about removing the link to the Typescript docs? Or updating the link to redirect to the wiki page on TS to serve more as a "definition link"?

**Comment by MaoShizhong** [comment]
@thatblindgeye I'd be good with just dropping the TypeScript link and just keeping the text as straight text.

**Comment by thatblindgeye** [comment]
@Dillonpw would you still be interested in working on this based on the above comments?

**Comment by Dillonpw** [comment]
Sure! I'll submit a pull with the suggestions in mind as soon as possible.

**Comment by Dillonpw** [comment]
@thatblindgeye Sure! I'll submit a pull with the suggestions in mind as soon as possible.
