### ISSUE TITLE
Dynamic User Interface Interactions: Removing the requirement for smooth transition

### ISSUE THREAD

**Issue by Sokolan** [TheOdinProject/curriculum#27247]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Currently in the "Dynamic User Interface Interactions" the assignment of `Image slider" instruction .3 is as follows:

>  Once you have the slider positioned properly, build functions for “next” and “previous” which will advance to the next or previous slide accordingly. **Make the transitions smooth using effects**.

The issue is that animations haven't been introduced yet, they appear only in the next course "Advanced html and css".

My suggestion is to remove this _requirement_, as the main goal of this practice (as far as I understand it) is to practice JavaScript techniques to build the slider, and less emphasis on the css part.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-dynamic-user-interface-interactions

### (Optional) Discord Name

Sokolan

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript can someone review please.

**Comment by thatblindgeye** [comment]
I'd agree we should remove that requirement. For context, I'm pretty sure this lesson was written before the HTML/CSS overhaul, which would explain why that requirement is there. I don't think we should be asking users to put a pause on this lesson to go learn about something that's required for this lesson, when we'll be covering that sort of topic not long after.

**Comment by Sokolan** [comment]
So beside removing the requirement in the assignment, you're also suggesting to remove the quote in the introduction.
Maybe the "Mobile menus" part is also a little out of the scope here? as responsive design is being introduced in "Advance HTML and CSS". This change will lead to the questions in the "Knowledge check" to be irrelevant tho (so removing those too?).

**Comment by thatblindgeye** [comment]
There's a comment in a discussion kinda related to this: https://github.com/TheOdinProject/curriculum/discussions/26390#discussioncomment-8445550

I'd agree with removing the Mobile menu portion of this lesson, though, in addition to what was mentioned above. Plus any other necessary changes (such as knowledge checks) that would be affected.

**Comment by MaoShizhong** [comment]
https://discord.com/channels/505093832157691914/505093832157691916/1222644707587526726

A recent case where another learner was confused by the "smooth transitions" requirement despite not coming across transitions yet.

I think at the very least, while other ideas are being discussed in that linked discussion, we should do a small PR that just removes that one "smooth transitions" sentence. Perhaps even replace it with "You do not need to animate the slides changing."

IMO this will reduce confusion ASAP, then any further changes to this specific lesson could be done in a separate issue as they're not directly related to this specific one.
Larger changes may well come in the future as a result of that linked discussion.

Thoughts @thatblindgeye? If sensible, we can assign Sokolan to have that sentence removed/replaced to resolve this particular issue.

**Comment by thatblindgeye** [comment]
I think at the least as part of this issue we should:

- remove the mention of smooth transitions in the "image slider" section
- remove the entire mobile menu section (but keep the dropdown menu content)
- remove the blockquote in the Introduction that links to the video on animations

I'll post in the linked discussion again to try and get the ball rolling there for any further possible updates to this lesson.

**Comment by MaoShizhong** [comment]
I think those three suggestions make perfect sense, and would be happy to see them go.

**Comment by thatblindgeye** [comment]
@Sokolan would you be interested still in making the updates discussed above?

**Comment by Sokolan** [comment]
Sorry for the late response.
I'll be glad to implement those changes, will make a PR in the next few days.

**Comment by MaoShizhong** [comment]
@Sokolan While making those changes, would you be able to also apply the following link-based changes as per the following spreadsheet?

https://docs.google.com/spreadsheets/d/1E1OJqUfBODvjdFMNgFMY_GvOLrOzV4ujL9o7Nxzg2zk/edit?usp=sharing

You can find the instructions in the `JavaScript` tab, under the `Dynamic User Interface Interactions` rows. Just a small link text change, and a little restructuring of a sentence into a sentence+list to make some links easier to name descriptively.

Let me know if you have any issues with this.
