### ISSUE TITLE
Intermediate HTML and CSS - More Text Styles: Missing assignment section

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27241]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Intermediate HTML and CSS - More Text Styles lesson is missing an assignment section, so it needs to be reworked a bit to bring into line with the curriculum standard.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles

### (Optional) Discord Name

fabulousgeek

**Comment by CouchofTomato** [comment]
Happy for you to work on this issue @fabulousgk

**Comment by fabulousgk** [comment]
This is going to a bit bigger due to the changes made about GPDR.  That change which is good, brings up some other issues like the fact that we proceed immediately to show how to use Google Fonts after saying not too.  We also link to a library called Font Library that may or may not be GPDR compliant (I have sent an email asking).  My proposal is to refactor the lesson to be more general about GPDR issues, and explain better that self hosting the fonts resolves this.  We can also link to https://fonts.bunny.net/ witch is a GPDR compliant replacement fo Google.

All this while also converting some things into an assignment...
