### ISSUE TITLE
Working With Text: Revert change #27245

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27246]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

PR #27245 changed an to a before h1.  This is incorrect grammar and should be reverted.

a is used when the next *sound* is consonant
an is used when the next *sound* is a vowel.

When pronouncing the h in h1, we say *ayech*, which is a verb sound.

https://blog.apastyle.org/apastyle/2012/04/using-a-or-an-with-acronyms-and-abbreviations.html

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-working-with-text

### (Optional) Discord Name

fabulousgeek

**Comment by CouchofTomato** [comment]
Thanks @fabulousgk 

My understanding is the correct pronounciation of h is like aitch, it has an a sound and therefore 'an' is considered correct from everything I've read.

Happy to look at any resources you might have that suggest otherwise.

**Comment by CouchofTomato** [comment]
Reading your comment again I can see we agree. I think maybe you've read the diff wrong because the PR merged corrects `a` to `an` so I'm closing this out.

**Comment by fabulousgk** [comment]
Wow, talk about dyslexya lol.  I certainely did read that all wrong.  Sorry about that.  Ugg
