### ISSUE TITLE
Introduction To State: CodeSandBox out of credits

### ISSUE THREAD

**Issue by Roundsquared** [TheOdinProject/curriculum#27253]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

When viewing the Intro to State lesson, the sandbox displays an error message indicating that the site is out of credits. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

**Comment by JoshDevHub** [comment]
Thanks for reporting this. This seems like a big issue.

Gonna tag our @TheOdinProject/react team, and see if they have thoughts on a solution.

**Comment by xandora** [comment]
Looks like we have four lessons that might need attention:

https://github.com/search?q=repo%3ATheOdinProject%2Fcurriculum%20codesandbox&type=code

**Comment by djcrago** [comment]
If you hit the Fork button it displays the message, "Failed to fork: (401) You don't have the needed authorization for this workspace (The Odin Project)." However if you click the Fork button **again** then it works. Just thought I might share this here for others.

**Comment by MaoShizhong** [comment]
Closing this as #27666 has provided a temporary resolution until we can sort out a longer term alternative.
