### ISSUE TITLE
Real World Git: Add assignment section

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#27255]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In line with the layout style the using git in the real world lesson needs an assignment section added

Referenced in the merged PR #27243

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world

**Comment by SumonGFC** [comment]
Looking at the structure of the lesson, it seems that the simplest fix for this would be to wrap [lines 28-60](https://github.com/TheOdinProject/curriculum/blob/main/git/intermediate_git/using_git_in_the_real_world.md?plain=1#L28-L60) in an assignment div (This includes `Initial setup`, `Ongoing workflow`, and `Sending your pull request` sections)
