### ISSUE TITLE
Foundations: Rename lessons 'Foundations Part X' to be more descriptive 

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27278]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The title of some of the lessons in the JavaScript section in Fundamentals really don't tell much, if anything at all what the lesson is about. At some point one may want to come back to these lessons to review the material, how would they know which lesson teaches what? I feel it would be worth re-naming these lessons to be more descriptive. 

I'll be including the Learning Objectives of each lesson to help you decide what you think about this idea so you don't have to guess.

### Fundamentals Part 1 → Variables and operators 
- How do you declare a variable?
- What are three different ways to declare a variable?
- Which one should you use when?
- What are the rules for naming variables?
- What are operators, operands, and operations?
- What is concatenation and what happens when you add numbers and strings together?
- What are the different types of operators in JavaScript?
- What is the difference between == and ===?
- What are operator precedence values?
- What are the increment/decrement operators?
- What is the difference between prefixing and postfixing them?
- What are assignment operators?
- What is the Unary Plus Operator?

### Fundametals Part 2 → Data types and conditionals
- Name the eight data types in JavaScript.
- Understand the difference between single, double, and backtick quotes.
- Embed a variable/expression in a string.
- Understand what a method is.
- Name the three logical operators.
- Understand what the comparison operators are.
- Understand what conditionals are.
- Understand what nesting is.
- Understand what truthy and falsy values are.

### Fundamentals Part 3 → Function basics
- How to define and invoke different kinds of functions.
- How to use the return value.
- What function scope is.

### Fundamentals Part 4 → Arrays and loops
- Using arrays.
- Using built-in array methods.
- Using loops.
- Getting your hands dirty with TDD exercises.

### Fundamentals Part 5 → Object basics
* Creating objects.
* Accessing object properties.
* Being able to use multiple object operators.
* Being able to use some powerful array functions.

### Path

Foundations

### Lesson Url

JavaScript section of the Fundamentals course, lessons 'Fundamentals Part X'

### (Optional) Discord Name

Revenco

**Comment by silenceinspace** [comment]
Interestingly, there is the [issue](https://github.com/TheOdinProject/curriculum/discussions/25446#discussion-5175375) with the exact thoughts, which was long ago converted into a github discussion inside this curriculum. Quite a few people agreed that it was indeed appropriate to more explicitly name lessons inside JavaScript basics. So I would like to second this suggestion to finally complete what was requested a few years ago:D

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone review please.

**Comment by KevinMulhern** [comment]
Sorry for the delay @thatblindgeye, renaming will be fine thankfully, progress will carry over 🎉

**Comment by thatblindgeye** [comment]
@nikitarevenco would you be interested in making PRs both in this repo and our webapp repo to resolve this issue?

**Comment by nikitarevenco** [comment]
> @nikitarevenco would you be interested in making PRs both in this repo and our webapp repo to resolve this issue?

Alright, I changed both the file names for this repo and the webapp repo aswell I changed the descriptions/titles for the lessons.
