### ISSUE TITLE
Intermediate HTML and CSS: Project: Sign-up Form 

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27271]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The current instructions state:

> Checking that the password fields match each other requires javascript. Try to implement this if you feel confident, otherwise just validate each field separately.

I don't think we should ask learners to do activities covered later in the curriculum. While this is optional, it still encourages learners to go down a rabbit hole rather than complete the task and move on.  To me, this is in the same category as the recursion in tic-tac-toe and loops in the initial etch-a-sketch, which we removed for similar reasons.

I think we should update the instructions to:

>Validating that the password fields match each other requires JavaScript. Using JavaScript to validate forms is covered in a future lesson.  For now, just validate each field separately.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-sign-up-form

### (Optional) Discord Name

fabulousgeek

**Comment by CouchofTomato** [comment]
@codyloyd  I'd value your opinion here please.

**Comment by MaoShizhong** [comment]
I'm very much for this. I've seen a fair few try to deal with JS form validation before we teach it, and go down rabbit holes, as well as come up with very unintuitive solutions given they tried to learn independently, and not after learning about things with the curriculum.

Assigning you, @fabulousgk

**Comment by Yousseif-Dawoud-Dev-Monster** [comment]
good

**Comment by fabulousgk** [comment]
Oh wow, I tottaly forgot about it.  I will get it done.  Putting on my reminders now
