### ISSUE TITLE
HashMap Data Structure: <why is index 508 for fred? shouldnt it be 385>

### ISSUE THREAD

**Issue by FluffyRudy** [TheOdinProject/curriculum#27295]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

function stringToNumber(string) {
  let hashCode = 0;
  for (let i = 0; i < string.length; i++) {
    hashCode += string.charCodeAt(i);
  }

  return hashCode;
}

function hash(name, surname) {
  return stringToNumber(name) + stringToNumber(surname);
}

We not only consider the first letters with this technique. Instead, we take the entire name and convert it into numbers.

You might be thinking, wouldn’t it just be better to save the whole name as a hash code? That is true. This would make it unique for each name, but in the context of hash maps, we need the hash code to be a number. This number will serve as the index to the bucket that will store the key value pair. More on buckets in the next section.
[Buckets](https://www.theodinproject.com/lessons/javascript-hashmap-data-structure#buckets)

Buckets are storage that we need to store our elements. Simply, it’s an array. For a specific key, we decide which bucket to use for storage through our hash function. The hash function returns a number that serves as the index of the array at which we store this specific key value pair. Let’s say we wanted to store a person’s full name as a key “Fred” with a value of “Smith”:

    Pass “Fred” into the hash function to get the hash code which is 508.
    Find the bucket at index 508.
    Store the key value pair in that bucket. In this case, the key would be “Fred” and the value would be “Smith”.

### Describe your suggestion
why is this 508? sum of ascii value of Fred is supposed to be 385. I got confused.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-hashmap-data-structure

**Comment by JustWaveThings** [comment]
I'm not a maintainer, I may have some insight into why '508' and 'Fred' are paired. When the lesson was created, I had 508 points in the TOP Discord server. Other people mentioned in the lesson matched their current point value at that time.

**Comment by JoshDevHub** [comment]
This was more meant to be hypothetical than related exactly to the hash function that was given. I could see how this would be confusing though.

Would you be okay with submitting a PR that uses the number calculated from the given hash function? @FluffyRudy
