### ISSUE TITLE
Intermediate HTML and CSS - Positioning Grid Elements : Assignment contains information not yet covered

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27309]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The assignment is to read section 4 of the CSS tricks article, but that part is quite extensive and covers functions and units not yet covered.  I suggest moving that assignment to the next lesson "Advanced Grid Properties"

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-creating-a-grid

### (Optional) Discord Name

fabulousgeek

**Comment by JoshDevHub** [comment]
Seems like a good idea to me. You still interested in working on this @fabulousgk ?

**Comment by fabulousgk** [comment]
Yes, I will do it.

**Comment by JoshDevHub** [comment]
Awesome. Assigned you
