### ISSUE TITLE
NodeJS: Suggest Cloudinary for handling image upload features

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#27314]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Cloudinary is currently mentioned in the Rails final project (in an additional resource) as an option for storing images uploaded by a user.
I and several others have have a good experience using this too within some of our Node projects. This makes the issue of both storing images as well as performance when loading to a website significantly better than, say, storing the buffer data directly in MongoDB. Instead, multer would save the uploaded file temporarily and use that to upload to Cloudinary and store the returned image URL in the database, then delete the temporary file from memory.
Deleting Cloudinary images is also fairly simple with their Node SDK.

Since the Rails FP already suggests this, I think it would be good to also suggest this in the Node section. I originally thought suggesting it in Odinbook but given that uploading images and multer is first mentioned as an extra credit step in the Inventory Application, perhaps adding a link to the docs for Cloudinary's Node SDK there would be a more appropriate place.

Thoughts?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-inventory-application

**Comment by JoshDevHub** [comment]
This is very sensible to me. Seems like an easy win for stepping closer to feature parity with the Rails final. Assigned :rocket:
