### ISSUE TITLE
Foundations/Revisiting Rock Paper Scissors: Update Lesson Structure

### ISSUE THREAD

**Issue by roopxx** [TheOdinProject/curriculum#27332]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The "Revisiting RPS" lesson currently lacks a conventional lesson structure, as it is not a project but rather a lesson. To align with the standard lesson format and ensure consistency across the curriculum, it should include a "lesson overview" section.

Additionally, including a "lesson overview" section will maintain consistency across the curriculum, ensuring that all lessons follow a standardised structure for improved user experience and clarity.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors

### (Optional) Additional Comments

This suggestion arose from the discussion in PR #27294, as suggested by @thatblindgeye.

**Comment by maahsnd** [comment]
I'm interested in working on this--depending on whether folks think this would be a reasonable issue to take on as my first contribution.

**Comment by thatblindgeye** [comment]
@maahsnd it might depend on your familiarity with the content in this lesson, as it requires adding a "Lesson overview" section as well as a "Knowledge check" section. There isn't a ton of content learned in the lesson, though, so neither section should be all that large. If you'd want to try making an attempt I can assign you, and we can help fine-tune things if needed.

**Comment by maahsnd** [comment]
@thatblindgeye It's been about a year since I did that lesson myself. I just read through it again, and it seems like the main points are A: introduction/explanation of git branching and getting some practice with it, and B: getting some practice with event listeners and DOM manipulation. I'm happy to make an attempt at channeling that into a lesson overview and knowledge check.

**Comment by thatblindgeye** [comment]
I'll assign you then @maahsnd !
