### ISSUE TITLE
Basic Data Types: Remove the nested lists (Knowledge check, Additional Resources)

### ISSUE THREAD

**Issue by kapustindev** [TheOdinProject/curriculum#27345]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

@kapustindev that error regarding `value of lineNumber...` is due to how the rule is creating errors and how this particular lesson is structured, so nothing for you to update here. Can you just open a followup issue for this lesson to remove the nested lists in both the Knowledge check and Additional Resources sections?

_Originally posted by @thatblindgeye in https://github.com/TheOdinProject/curriculum/issues/27334#issuecomment-1937837398_

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-basic-data-types

**Comment by JoshDevHub** [comment]
Thank you for making this issue @kapustindev 

Since you indicated you don't want to work on it, I'll be opening this up for others to contribute to. Comment below to be assigned.

### Acceptance Criteria:
- [ ] In the [knowledge check section](https://www.theodinproject.com/lessons/ruby-basic-data-types#knowledge-check) for the Ruby basic data types lesson, the list nesting should be removed.

So for example:
```md
<!-- bad -->
- Numbers
  - <a class="knowledge-check-link" href="#numbers">What are the basic arithmetic operators you can use on numbers? </a>
  - <a class="knowledge-check-link" href="#integers-and-floats">What's the difference between an integer and a float?</a>

- Strings
  - <a class="knowledge-check-link" href="#strings">What is a string?</a>
  - <a class="knowledge-check-link" href="#double-and-single-quotation-marks">What are the differences between single and double quotes?</a>

<!-- good -->
- <a class="knowledge-check-link" href="#numbers">What are the basic arithmetic operators you can use on numbers? </a>
- <a class="knowledge-check-link" href="#integers-and-floats">What's the difference between an integer and a float?</a>
- <a class="knowledge-check-link" href="#strings">What is a string?</a>
- <a class="knowledge-check-link" href="#double-and-single-quotation-marks">What are the differences between single and double quotes?</a>
```

Also this should be a nice issue for any potential first time contributors.

**Comment by Darknab** [comment]
I'd like to contribute, can you assign me please?

**Comment by thatblindgeye** [comment]
@Darknab assigned!
