### ISSUE TITLE
Introduction to Web Accessibility: Replace the link in the 2nd assignment with direct YouTube Link

### ISSUE THREAD

**Issue by RT44n** [TheOdinProject/curriculum#27348]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The second assignment links to w3 org page with links to YouTube videos. Replace this with compilation video(linked on the page) or a playlist of these individual videos(can be found on the w3 channel page).

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-introduction-to-web-accessibility

**Comment by MaoShizhong** [comment]
@RT44n Thank you for opening this issue.

My feeling is that this isn't something that seems vital to change. Having the separate videos with descriptive titles, even if they're short videos, feels like it makes it clearer what each individual video is about as they're about separate concepts. The compilation video, while convenient, only really reduces a few clicks so doesn't immediately feel like a necessary change.

Would like to hear your thoughts on that though. Is there something about linking directly to the compilation video that you feel is of significant benefit to a learner over what's currently the case?

**Comment by RT44n** [comment]
To be honest, I don't think the descriptive titles make any difference since the videos start with a short explanation about what they are but I can see some people preferring the individual videos. If that is the case then there is a playlist of Individual videos on the same channel. (https://youtube.com/playlist?list=PLhDEeYUfW02Qo4r2KlzagxZxhYcZADee-&si=teH4r97ZJj5fMkWy)

**Comment by fabulousgk** [comment]
I think sometimes it is good to link to websites not directly to YouTube for a couple reasons.

1) It introduced learners to the the website as a resource on the topic
2) It is a way of giving credit to the producers.

**Comment by MaoShizhong** [comment]
I think those are valid and sensible points as well.
All in all, I'm not convinced there is significant value gained from changing the current implementation. That's not say the suggestion is worse than current, only that we have the current and I don't think the proposed change makes anything significantly better nor significantly worse. It's just different.

Though I definitely do like the consideration of being made aware of the website itself that a user might explore/revisit at some point, as opposed to straight to just a video/playlist on YouTube and that's it.

So I think in this scenario, I'm going to close this issue as I do not feel the change is a necessary one to make.
