### ISSUE TITLE
Natural Responsiveness: Add a note regarding media queries used in the 2nd Assignment,

### ISSUE THREAD

**Issue by RT44n** [TheOdinProject/curriculum#27353]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The 2nd assignment, 'Using percentages in CSS' links to an article which uses 'media queries' in its example. This concept is introduced a little later. I think adding a little note about media query might be helpful to users.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-natural-responsiveness

**Comment by MaoShizhong** [comment]
Might not be the most vital given the media queries lesson is only in 2 lessons' time, but it probably wouldn't hurt to add a small mention just for reassurance.

Assigning this to you :+1:

**Comment by RT44n** [comment]
Something like this?

>     1. You will note that the examples here use **@media**. These are known as media queries. You will learn about them in a later lesson. For now, just know that we can use them to set different CSS values for different screen sizes.

**Comment by MaoShizhong** [comment]
> Something like this?
> 
> > ```
> > 1. You will note that the examples here use **@media**. These are known as media queries. You will learn about them in a later lesson. For now, just know that we can use them to set different CSS values for different screen sizes.
> > ```

Probably not even that, to be honest. Something simple like the below should be more than sufficient.
> - Don't focus too much on the `@media` parts, as we will cover media queries very soon.

**Comment by MaoShizhong** [comment]
@RT44n 
> Something like this?
> 
> > ```
> > 1. You will note that the examples here use **@media**. These are known as media queries. You will learn about them in a later lesson. For now, just know that we can use them to set different CSS values for different screen sizes.
> > ```

Probably not even that, to be honest. Something simple like the below should be more than sufficient.
> - Don't focus too much on the `@media` parts, as we will cover media queries very soon.
