### ISSUE TITLE
Variables and operators: Typo/wrong term in assignment

### ISSUE THREAD

**Issue by 95therese** [TheOdinProject/curriculum#27369]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Part 3 of the assignment asks you to print the result of an equation. However, a mathematical equation describes the _equality_ of two mathematical expressions. Since there is no equals sign present, it's not an equation. But it is a mathematical expression.

Suggested wording: "Print the value of the following expression:"

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-variables-and-operators

**Comment by Churtified** [comment]
I can make the change :)

**Comment by JoshDevHub** [comment]
Seems like a good change to me.

Assigned @Churtified
