### ISSUE TITLE
NodeJS: Change approach to handling static files in Webpack lesson

### ISSUE THREAD

**Issue by davidstaab** [TheOdinProject/curriculum#27362]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the lesson `node-path-javascript-webpack`, the assignment Step 3-1 says:

> Note that if you decide to use `webpack-dev-server`, the tutorial example sets it to serve from `dist`. If you are using `html-webpack-plugin`, you will want to change this to serve from `src` instead. This will make development much easier as all of your work and any file paths you use can be kept within `src`...

Following a discussion with Mao on the Discord (begins [here](https://discord.com/channels/505093832157691914/597796701650026517/1207411395163852830) / pertinent conclusion [here](https://discord.com/channels/505093832157691914/597796701650026517/1207435217648885870)), it seems more appropriate to configure `devServer.watchFiles` with the template HTML file, instead.

### Reason:
If the devServer is pointed at `./src`, it can give the developer a false belief that Webpack has been configured correctly. The devServer will host all files in the development project, but some of those files might not be linked to the source tree, meaning they won't appear in the production code. ("Why don't my images appear on the github page for this project?! They appear on my machine!")

It would be better, perhaps, to tell the devServer to watch `template.html` for changes and leave `devServer.static = './dist'`. This should trigger an update on the server when the HTML file changes, while correctly representing the production configuration.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-webpack

### (Optional) Discord Name

stobber

**Comment by cakegod** [comment]
I can work on this issue.

**Comment by MaoShizhong** [comment]
I think this is a sensible change to be made - assigning you, Cake :tada:
