### ISSUE TITLE
DOM Manipulation and Events: <bracket notation issue for kebab case assignment>

### ISSUE THREAD

**Issue by alienfunbug** [TheOdinProject/curriculum#27389]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There may be a typo on Dom Manipulation/Events -> Adding inline style ->  kebab-cased CSS rule from JS:

**-div.style['background-color'] // also works**  is listed in the curriculum and potentially should be

**-div.style=['background-color: white;'] //** missing the assignment operator [and color optional]

It may seem trivial but to experienced eyes, but I was stuck  researching this for a few minutes to resolve it locally.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

### (Optional) Discord Name

lewiscaroll

### (Optional) Additional Comments

Thanks so much! Hopefully this isnt too silly to fix!

**Comment by MaoShizhong** [comment]
`div.style=['background-color: white;']` would be incorrect. That tries to assign an array containing the string `'background-color: white;'` to the `div`'s `.style` property.

That part of the lesson is showing how you can (and can't) access the `.backgroundColor` property on the `.style` property object.
`div.style.backgroundColor` accesses it just fine, as does `div.style['backgroundColor']` and also `div.style['background-color']`, but `div.style.background-color` without the bracket-string property accessing won't (because of the subtract).

Though I agree that it might be a little confusing that the 4th line includes an assignment to the `.cssText` property.
I don't actually think that line falls in line with the concept the first 3 lines are talking about, which is how you can't use kebab-case in JS outside of a string context.

**Comment by alienfunbug** [comment]
hey mao!! thanks for getting to my task "<bracket notation issue for kebab case assignment> #27389". Two things, so in your post you actually clarified my intitially issue: I thought the assignment went IN the brackets. So now I'm all set on that. Secondarily, here i've thrown up the code pen showing the second method passing the array to .style and it working. https://codepen.io/LewisCaroll/pen/KKEEOXp

Thanks again!

**Comment by MaoShizhong** [comment]
[Responded to on Discord](https://discord.com/channels/505093832157691914/516751477306294273/1209204828027359232)

Summary: interesting quirk of `[object CSSStyleDeclaration]` specifically and not syntax that will work for other kinds of objects.

It's definitely not a syntax I would think the curriculum should teach as being valid though, as it's very unintuitive and specific only to this case and not in general.

What I do think is strange about the current lesson's code snippet you highlighted though, is the 4th line 
> `div.style.cssText = "background-color: white;" // sets the div's background-color by assigning a CSS string`

`cssText` assignment is already shown in the previous code snipper, and the following code snippet is talking specifically about accessing a `.style` object property and how you can't use kebab case outside of bracket/string syntax. The 4th line doesn't relate to this example at all.

So I think if anything, there might be a case for removing that one line from that code snippet.

**Comment by MaoShizhong** [comment]
@alienfunbug Would you be up for removing the last line of that code block example? i.e.
```js
div.style.background-color // doesn't work - attempts to subtract color from div.style.background
div.style.backgroundColor // accesses the div's background-color style
div.style['background-color'] // also works
div.style.cssText = "background-color: white;" // sets the div's background-color by assigning a CSS string
```
Remove the `.cssText` line only.
You could also add `div.style['backgroundColor'] // also works` as both camel and kebab case work when using a string with bracket notation. Only the dot notation with kebab case does not work.
I think the last line with `.cssText` is the odd-one-out and is what may have caused your confusion, so no doubt others may have had a funny moment too.

If you'd like to do this, I can assign you to this.

**Comment by alienfunbug** [comment]
Undoubtedly yes!!! Please do!
