### ISSUE TITLE
Object basics: arr.reduce example shows wrong output

### ISSUE THREAD

**Issue by catagonus** [TheOdinProject/curriculum#27383]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the section about the reduce method, the example says:

arr.reduce((total, currentItem) => total * currentItem, 1); // Outputs [1, 2, 6, 24, 120];

reduce() returns a single value. In this example, it should say "Outputs 120"

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-object-basics

**Comment by yuusan64** [comment]
I'll be happy to take this up!
