### ISSUE TITLE
Recipes: <Short description of your suggestion>

### ISSUE THREAD

**Issue by rmn-k** [TheOdinProject/curriculum#27380]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

After the completion of the assignment listed on the page,
we are asked to upload our website on the web but I didn't get the option of changing my Branch from 'none' to 'main'.
Probably it was happening as the step of pushing our local files to the GitHub repository was missing from the instructions.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes

**Comment by MaoShizhong** [comment]
@rmn-k Thank you for opening this issue.
Just above the assignment section, there's a section labelled `Tips on when to commit`, which is part of the instructions for setting up the project repo and cloning it.
In that section, it reminds about the git workflow of `add -> commit -> push` and when would be sensible times to do so.

**Comment by MaoShizhong** [comment]
Closing as it no further response nor further action required.
