### ISSUE TITLE
Installations: Add a note, for the paste shortcut

### ISSUE THREAD

**Issue by AirDevil188** [TheOdinProject/curriculum#27390]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Hello, for the past few months I've been active on the discord especially in the tech support channels. 

I've noticed that a lot of users  are making spelling mistakes with `wget` command when downloading `chrome` or `vscode`. Would it be a good idea to maybe add somekind of note for the users just to inform them that they can also paste the commands from the browser to the terminal with `Ctrl + Shift + V` or `Command + V` on Mac? 

I know that I'm suggesting for this to be added before the `Command Line Basics` lesson but I think that it would be a good idea to make users aware of this option. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### (Optional) Discord Name

Uki

**Comment by wise-king-sullyman** [comment]
Thanks for submitting this issue!

@TheOdinProject/installations thoughts? I'm not sure it's really *needed* but I'm not against this if it might help prevent some issues.

**Comment by MaoShizhong** [comment]
Can also agree that a somewhat common occurrence in the Discord server is people making typos with the full commands because they thought they couldn't paste via `ctrl + v`.

**Comment by wise-king-sullyman** [comment]
A +1 and no objections is good enough for me, have at it @AirDevil188!
