### ISSUE TITLE
New project: Solar System

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27396]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The advanced HTML and CSS course's `Animation` section feels like it's missing something. And that is, **a project**. 

The final CSS/HTML project which is the Homepage doesn't have any requirements for making anything animated, so in my opinion a project in this section would be an awesome addition to help learners practice their CSS animation skills.

This project draft is just an example of what I think a possible project related to animation could be. If you have any other ideas, please put them down below! 

- **(Codepen example)** [Solar System - CSS Only](https://codepen.io/atsudodev/pen/YzYegKW)
- **(Lesson preview link)** [Project: Solar System](https://www.theodinproject.com/lessons/preview?uuid=a0b19901-bdaa-4301-afd4-5613fa4fd053)

### Path

Foundations, Ruby / Rails, Node / JS

### Lesson Url

Advanced HTML and CSS, after the third lesson on animations

### (Optional) Discord Name

Revenco

**Comment by wise-king-sullyman** [comment]
Hello and thank you for submitting this issue!

This is actually a topic that is already in broad discussion here https://github.com/TheOdinProject/curriculum/discussions/26390

**Comment by KevinMulhern** [comment]
Thanks for the detailed write up @nikitarevenco, since this is linked on that [discussion](https://github.com/TheOdinProject/curriculum/discussions/26390), I'll close this out for now.
