### ISSUE TITLE
Rails and Node courses: Deployment lesson structure

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#27394]
### Problem

In both the [Rails deployment](https://www.theodinproject.com/lessons/ruby-on-rails-deployment) and [Node deployment](https://www.theodinproject.com/lessons/nodejs-deployment) lessons, sections are titled with emphasis styling rather than headings. This violates our style guide and lint rules for the curriculum lesson content. Example of what I mean:
```md
<!-- emphasis -->
**Free Tier**

- You can host three apps for free before you need to start paying.

<!-- should use headings instead: -->
#### Free Tier

- You can host three apps for free before you need to start paying.
```
But there's another problem with this: the style guide / lint tool also specify that headings should not be repeated in a lesson. But the structure of these emphasis-as-heading sections are repeated for the different services described in the lesson. To get around this, we'll need to use a strategy that keeps the heading names unique. So we might have a structure like:
```md
### Heroku

#### Heroku Free Plan

#### Heroku Links

### Render

#### Render Free Plan

#### Render Links
```

### Acceptance Criteria
- [ ] Fix the emphasis-as-heading issues in the [Rails deployment lesson](https://www.theodinproject.com/lessons/ruby-on-rails-deployment)
- [ ] Fix the emphasis-as-heading issue in the [Node deployment lesson](https://www.theodinproject.com/lessons/nodejs-deployment)

**Comment by JoshDevHub** [comment]
@thatblindgeye 

Before fully opening this up to contributions, I wanted to ask if the plan I had for this seemed good or if you maybe had a different ideas for this type of situation.

**Comment by thatblindgeye** [comment]
@JoshDevHub 💯 what I would do, yep. Maybe down the line we can see if those lessons can be tweaked a little further to not need as many sub-sections, but for now let's go with what you outlined above.

**Comment by JoshDevHub** [comment]
Awesome. So we'll go with the plan I outline in the OP.

Opening this up for contributions. Comment below if you want to work on this.

**Comment by nikitarevenco** [comment]
Sure, I'm happy to work on this.

**Comment by JoshDevHub** [comment]
Assigned @nikitarevenco

**Comment by nikitarevenco** [comment]
> Assigned @nikitarevenco

Alright, I've linked the pull request.
