### ISSUE TITLE
Introduction to HTML and CSS: broken link

### ISSUE THREAD

**Issue by chalpenny** [TheOdinProject/curriculum#27406]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The link for "What is the difference between HTML, CSS and JavaScript?" opens a page with the following error: "Application error: a client-side exception has occurred (see the browser console for more information)."

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

### (Optional) Discord Name

chalps

**Comment by rubicon2** [comment]
Hi Chalpenny, I have checked out the link and it opens fine for me. Just to be sure, it is [this one](https://www.brytdesigns.com/html-css-javascript-whats-the-difference)? I'm using Firefox. Are you using a different browser?

**Comment by chalpenny** [comment]
Oh interesting.  I'm using Chrome, I've attached a screenshot. When I open
it in Firefox, it works.

Thanks for the quick response!

**Comment by chalpenny** [comment]
Oh weird! Sounds like a me problem, then.  I'll see if there's something in
my settings going on. Thanks for checking!

**Comment by JoshDevHub** [comment]
I'll close this because the link does seem to be working.

Thank you for contributing! Definitely let us know if you encounter other problems.
