### ISSUE TITLE
Knights Travails: point out that you should go through every page in the linked 'Khan Academy' article

### ISSUE THREAD

**Issue by qirele** [TheOdinProject/curriculum#27408]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Khan Academy article contains valuable information on how to store graphs in JavaScript called 'Representing Graphs', which I think is crucial to solving knights travails. Instead what is linked is the first part of the 'Khan Academy' lesson, which is [link](https://www.khanacademy.org/computing/computer-science/algorithms/graph-representation/a/describing-graphs). I think it would help if the [Representing Graphs](https://www.khanacademy.org/computing/computer-science/algorithms/graph-representation/a/representing-graphs) was linked in the beginning of the lesson too. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-knights-travails

**Comment by JoshDevHub** [comment]
Seems like a great idea to me @qirele 

I'm assigning you to work on it @perugi
