### ISSUE TITLE
Passing Data Between Components: Move 'Missing Props Validation' to previous lesson

### ISSUE THREAD

**Issue by remel-crowe** [TheOdinProject/curriculum#27409]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I'm working through the [Getting Started With React] section of the course and when coding along (which although not instructed to in this lesson, has become common practise for me and I assume some others) I came across the 'Missing Props Validation' error in my IDE. Not knowing what it was or how it affected my code I spent a some time researching and changing config files to make it go away. For a little I thought I couldn't move on without removing the error and then when I finally did, there was a section about it on the next lesson. My suggestion is that the small section about this error is brought forward one lesson for anyone who is coding along from the start.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-passing-data-between-components

### (Optional) Discord Name

Squiff

### (Optional) Additional Comments

This also includes the lesson before: 
https://www.theodinproject.com/lessons/node-path-react-new-keys-in-react

Not sure if this is necessary but better safe than sorry.

**Comment by wise-king-sullyman** [comment]
Moving it up makes sense to me, thanks!
