### ISSUE TITLE
Testing Basics: Remove suggestion to watch the mocking videos from FFF

### ISSUE THREAD

**Issue by perugi** [TheOdinProject/curriculum#27424]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the [Testing Basics](https://www.theodinproject.com/lessons/node-path-javascript-testing-basics/) lesson assignments, the assignment on the Fun Fun Functions videos suggest that the first three videos should be watched and others are worthwile. However, since these videos on mocking are assigned in the [More Testing](https://www.theodinproject.com/lessons/node-path-javascript-more-testing) lesson anyway, and they are not needed for the project in between the two lessons, I suggest to reword the last sentence to something like "No need to watch the rest of the videos in the series, as we will look at mocking in one of the following lessons."
It's a small optimization, but it gets the learner to the TDD project sooner, without overwhelming him with information on mocking. I would of course keep the mocking videos as an assignment in the [More Testing](https://www.theodinproject.com/lessons/node-path-javascript-more-testing) lesson.

I can work on this issue if it is approved, but since it is a good first issue, I can leave it to someone else to practice contributing to TOP.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-testing-basics

**Comment by Hwent** [comment]
Your rewording suggestion makes sense, I would like to fix this as my first contribution to TOP.

**Comment by wise-king-sullyman** [comment]
I agree as well, thanks for putting together this issue and offering it up to others as a good first issue @perugi!

Have at it @Hwent!
