### ISSUE TITLE
Deployment: incorrect link to Fly.io "Guide: Official getting started with NodeJS on Fly.io guide"

### ISSUE THREAD

**Issue by matthewaubert** [TheOdinProject/curriculum#27435]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I believe the link to Fly.io "Guide: Official getting started with NodeJS on Fly.io guide" is incorrect. I am redirected to a different URL path with unclear instructions on how to begin. I ended up figuring it out by creating an account and following the instructions provided there.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-deployment

### (Optional) Discord Name

SlightlyQuixotic

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/javascript can someone investigate this?

**Comment by MaoShizhong** [comment]
According to Wayback Machine, some time between 23rd Aug '23 and 6 Dev '23, Fly did a bit of an overhaul of their docs, especially the JS framework section and removed the "Node app" example entirely. Not entirely sure why (I think I recall it being mentioned at some point on Discord a few months ago).

Just checked the [23rd Aug '23 snapshot](https://web.archive.org/web/20230823151155/https://fly.io/docs/languages-and-frameworks/node/) and followed the instructions there (including following the links there to install/signup/login) and successfully deployed a test app without issues. So it looks to still be working fine and they've just overhauled and pruned their docs, but haven't made breaking changes to the process.

**Comment by MaoShizhong** [comment]
Yep, just double checked with this to make sure the snapshot I linked is the latest snapshot with the correct content and that the content does indeed still work as written (including the content in the links to installation/login within that snapshot). It's just no longer available via the current docs and the current lesson link.

I think replacing that broken link with https://web.archive.org/web/20230823151155/https://fly.io/docs/languages-and-frameworks/node/
will suffice.
Opening this up for anyone to request being assigned.

**Comment by kol3x** [comment]
> Yep, just double checked with this to make sure the snapshot I linked is the latest snapshot with the correct content and that the content does indeed still work as written (including the content in the links to installation/login within that snapshot). It's just no longer available via the current docs and the current lesson link.
> 
> I think replacing that broken link with https://web.archive.org/web/20230823151155/https://fly.io/docs/languages-and-frameworks/node/ will suffice. Opening this up for anyone to request being assigned.

Hey! I'd be happy to fix it. Fixing typos and broken links is my open-source specialty... :disappointed:

**Comment by kol3x** [comment]
To be specific, they deleted a bunch of JS framework guides on september 1st according to this commit:
https://github.com/superfly/docs/commit/1bf9c57d5a19cfbe5d01cdb829384c7d0abda964#diff-75d55dec152c3ecb82c97140f19beddf4df7eda406c52f08b3a49ddb7945c000
With no explanation whatsoever...
I investigated in case a link to a github file with the same instructions would be more appropriate, but it's not very readable:
https://github.com/superfly/docs/blob/c79495c73f8d4c4b63cdf9719fa1ef99889378f6/languages-and-frameworks/node.html.markerb
So webarchive version is good enough, I suppose.

**Comment by MaoShizhong** [comment]
@kol3x Thanks for investigating a bit further. Looks like the webarchive link is the best thing for the time being.
And hey, typos/broken links are just as important :P My first ever contribution was a one word typo and look where that got me in the end...
