### ISSUE TITLE
Function Basics: <Change attached link.>

### ISSUE THREAD

**Issue by crasion528** [TheOdinProject/curriculum#27430]
### Checks

- [x] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

This is a proposed fix for "Knowledge Check" section for the question "What are return values?" Although the link attached to the question is the correct resource, it would be better to link the header on the resource page of the specific section that should be jumped to. e.g. (Instead of the page loading from the top it jumps straight to the text needed to be reviewed.)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-function-basics

### (Optional) Discord Name

crasion528

### (Optional) Additional Comments

Would love to do this simple fix.

**Comment by wise-king-sullyman** [comment]
Sounds great, thanks!
