### ISSUE TITLE
hey i noticed a possible issue with the learning material. 

### ISSUE THREAD

**Issue by jstoltz2** [TheOdinProject/curriculum#27436]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

This issue I've come up with on multiple occasions id feel it'd be burdensome to ask for further explanations constantly. so i can suggest another resource added to detail why and when certain commands are used in greater detail. i feel like currently my issue is best explained in this example. This does x and this does xy both can be used but sometimes xy is needed over x. but never explains or barely explains when that is the case or why. Id suggest adding additional resources to possibly further explain why some things are needed over others or why a certain command is needed at all. So example The charAt() Method, i know the character is H but why do i care whats the point why and when would i need to know that. when and why would i need to use that over The charCodeAt() Method and why am i to care that document.getElementById("demo").innerHTML = text.charCodeAt(0); is the 72nd character. i guess im confused where how and why these are applied and its not just this command string but honestly much of the JavaScript module has left me with the same confusions and issues. as i fear the reason to half of it either is explained too late as i haven't gotten there or just isnt explained (which means i have next to no clue on its relevancy or where it belongs in my commands and why. so when im presented to do my own examples i'm left wondering what i'm even supposed to do at times. i know how to do xy and z i just dont know why or when. this isn't always the case so i cant point out every specific module that does this but some in css and many in JavaScript seem to have this issue for me personally. any suggestions to find explanations ect all in the same place would be helpful. Although edits and restructuring of some of the organization could most definitely be not only helpful for me but others who share said sentiment keeping all relevant information in the same module including explanations to any key words used in said module. Any suggestions would also be appreciated.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals

**Comment by takinabradley** [comment]
Hey @jstoltz2 

Your suggestion is, admittedly, very broad and hard doesn't exactly provide a clear path forward.

I would suggest that you should feel comfortable asking questions though in the Discord! There are a bunch of helpful people around, and they're likely to respond to simple questions to help give you clarity.

The beginning of the JavaScript module cab be hard- there's a lot of information and ideas you need to get exposed to before being able to do new and exciting things related to programming! **Remember, you don't need to memorize or completely understand everything** by the end of a lesson, and you'll most definitely get practice with many concepts as you push through the curriculum. The practice is where the real learning and understanding starts to come in. 

All the helpful methods you might hear about are likely to serve well you later, when you have an actual problem to work on. Until then, they're nice tidbits to have at least *heard of*, so you have an idea of what's possible. When you have a problem in front of you, it'll be more clear which methods are useful to you in order to achieve what you want to accomplish.

Read the material, do the practice, answer the knowledge checks. If you can do all that, you're probably doing great! And if you get stuck, ask for help 😄

**Comment by jstoltz2** [comment]
Hello again,I can compile a list but it'll take some time and a word document. I'm not trying to be rude but the disorganization I feel runs rampant in some modules so specifics off base isn't possible when the entire module could use less disorganization. I CANT be specific without information overflow so I thought a personal email or somthing may be more... appropriate. Is there anywhere I can submit a word document pointing out the errors in curriculum structure? Because the structure does need work regardless.

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 25, 2024 at 8:21 PM, ***@***.***> wrote:   


Hey @jstoltz2

Your suggestion is, admittedly, very broad and hard doesn't exactly provide a clear path forward.

I would suggest that you should feel comfortable asking questions though in the Discord! There are a bunch of helpful people around, and they're likely to respond to simple questions to help give you clarity.

The beginning of the JavaScript module cab be hard- there's a lot of information and ideas you need to get exposed to before being able to do new and exciting things related to programming! Remember, you don't need to memorize or completely understand everything by the end of a lesson, and you'll most definitely get practice with many concepts as you push through the curriculum. The practice is where the real learning and understanding starts to come in.

All the helpful methods you might hear about are likely to serve well you later, when you have an actual problem to work on. Until then, they're nice tidbits to have at least heard of, so you have an idea of what's possible. When you have a problem in front of you, it'll be more clear which methods are useful to you in order to achieve what you want to accomplish.

Read the material, do the practice, answer the knowledge checks. If you can do all that, you're probably doing great! And if you get stuck, ask for help 😄

**Comment by jstoltz2** [comment]
*apologies I had a typo meant to say I feel the modules could use some restructuring regardless. I don't mean to undermine your guy's work. 

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 26, 2024 at 5:14 AM, L ***@***.***> wrote:   Hello again,I can compile a list but it'll take some time and a word document. I'm not trying to be rude but the disorganization I feel runs rampant in some modules so specifics off base isn't possible when the entire module could use less disorganization. I CANT be specific without information overflow so I thought a personal email or somthing may be more... appropriate. Is there anywhere I can submit a word document pointing out the errors in curriculum structure? Because the structure does need work regardless.

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 25, 2024 at 8:21 PM, ***@***.***> wrote:   


Hey @jstoltz2

Your suggestion is, admittedly, very broad and hard doesn't exactly provide a clear path forward.

I would suggest that you should feel comfortable asking questions though in the Discord! There are a bunch of helpful people around, and they're likely to respond to simple questions to help give you clarity.

The beginning of the JavaScript module cab be hard- there's a lot of information and ideas you need to get exposed to before being able to do new and exciting things related to programming! Remember, you don't need to memorize or completely understand everything by the end of a lesson, and you'll most definitely get practice with many concepts as you push through the curriculum. The practice is where the real learning and understanding starts to come in.

All the helpful methods you might hear about are likely to serve well you later, when you have an actual problem to work on. Until then, they're nice tidbits to have at least heard of, so you have an idea of what's possible. When you have a problem in front of you, it'll be more clear which methods are useful to you in order to achieve what you want to accomplish.

Read the material, do the practice, answer the knowledge checks. If you can do all that, you're probably doing great! And if you get stuck, ask for help 😄
