### ISSUE TITLE
Introduction: What is NodeJS?: <Broken link>

### ISSUE THREAD

**Issue by Hwent** [TheOdinProject/curriculum#27443]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Broken link [Node.js website](https://nodejs.org/en/docs/guides/getting-started-guide). Link to 404: Page not Found.
I guess [Node.js website](https://nodejs.org/en/learn/getting-started/introduction-to-nodejs) is the correct page.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-what-is-nodejs

### (Optional) Discord Name

Hwent

**Comment by Diego-dot-web** [comment]
Hi, can I take this issue?

**Comment by Hwent** [comment]
> Hi, can I take this issue?

Only maintainer can assign issues.

**Comment by Diego-dot-web** [comment]
Guess I'll wait till' be assigned

**Comment by wise-king-sullyman** [comment]
Thanks for putting up this issue!

I've assigned @Hwent since he marked that he was interested in working on the issue, but @Hwent if you would like to leave it to @Diego-dot-web I can re-assign it.

**Comment by Hwent** [comment]
@wise-king-sullyman should I combine two issues I have to one pull request?

**Comment by wise-king-sullyman** [comment]
@Hwent we generally discourage that, but since they should both be quite small you can in this instance
