### ISSUE TITLE
Node Authentication Basics: Add `Assignment` section content

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#27451]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The [Node Authentication Basics lesson](https://www.theodinproject.com/lessons/nodejs-authentication-basics) currently misses an `Assignment` section. As per #27242, this issue has been opened to discuss what might be best to put into one.

My initial feeling's attracted towards the `Additional Resources` section. The [first 6 videos of the user auth/express/passport Youtube playlist](https://www.youtube.com/playlist?list=PLYQSCk-qyTW2ewJ05f_GKHtTIzjynDgjK) I think is a great playlist that actually shows lots of the pieces of passport's parts being used. I'm not fully convinced by the necessity of video 4 ("What is Express middleware and how does it work?") at this point in the course, given learners will have already played around with Express and middleware a bit by then. So my mind is on videos 1-3, then 5-6.

Additionally, it may be good to also add the [Passport hidden manual](https://github.com/jwalton/passport-api-docs) in the assignment, as it also expands on and explains more of what the different passport abstractions do and how they work.

Passport is definitely somewhat notorious for having terrible and unintuitive documentation, with most of their "documentation" being in the form of super simple examples with many of the methods and their options not explained unless the learner digs into the source code. I feel the above two resources do help break that barrier down even a little.

I think the [Computerphile Youtube video on "how not to store passwords"](https://www.youtube.com/watch?v=8ZtInClXe1Q) can be left as an additional resource. A nice video nonetheless.

Thoughts?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-authentication-basics

**Comment by wise-king-sullyman** [comment]
Putting you on this so that you can take point on it, thanks!

Also: that "how to to store passwords" video is an absolute classic.
