### ISSUE TITLE
 More Testing: Split confusing question into two

### ISSUE THREAD

**Issue by bigacz** [TheOdinProject/curriculum#27453]
### Checks

- [x] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the **Mocking** section of the lesson there's a metaphor: *'tightly coupled code' problem*.
After going through lengthy **Assignment** section you forget what it really means and question "What are two solutions to the tightly coupled code problem?" appears to be asking how should you deal with tightly coupled code in general (especially, that concepts such as pub/sub are covered in one of the resources).

But in reality this question is asking about testing tightly coupled code.

So my suggestion is to replace this question with these:

What should you try before testing a tightly coupled code?
How can you test a code that can't be decoupled?

And giving them links respectively:
1. Creating a link above "Making this testable requires us to [...]",
2.  "Mocking" header.

As a result of those changes following spans (i think) can be deleted: 
<span id='two-solutions'>

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-more-testing

### (Optional) Discord Name

beegee

**Comment by wise-king-sullyman** [comment]
Sounds like a good change to me, thanks!
