### ISSUE TITLE
Falsy values in jsx

### ISSUE THREAD

**Issue by JuliaShlykova** [TheOdinProject/curriculum#27462]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

According to the documentation and [React conditional rendering](https://react.dev/learn/conditional-rendering#logical-and-operator-) there is no such thing as "falsy values in jsx are different from js".
If we are using **logical AND** in jsx it works the same as in js [Logical AND](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND).
`0 && 1 //0`
`'' && 'a' //''`

If we are using **ternary operator,** it works the same as in js:
```javascript
function List(props) {
  let b = 0;

  return (
    <ul>
      {props.animals.map((animal) => {
        return b ? <li key={animal}>{animal}</li> : null;
      })}
    </ul>
  );
}
``` 

This Component won't display anything.

Would you be so kind to correct warning block about **Falsy values in JSX, a common pitfall**?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-rendering-techniques#conditionally-rendering-ui

**Comment by KevinMulhern** [comment]
Thanks @JuliaShlykova, @TheOdinProject/react any thoughts on this?

**Comment by MaoShizhong** [comment]
Falsy values **are** treated differently in JSX in specific instances.

`&&` returns the left side if falsy, otherwise returns the right side.
Hence if an array is of length `0`, then `if (arr.length && foo)` will return the left hand side (`0` is falsy) which __when coerced to a boolean__ will equate to `if (false)`.

But in JSX, React still has to render `0`. If it didn't, any counter that has a value of 0 would not have the 0 render unless you converted it to a string, which you'd often not want to do when all the other truthy numbers work fine.

```jsx
{arr.length && arr.map((el, i) => <p key={i}>{el}</p>)}
```
You'd think that if the array isn't empty, the left side is truthy so it goes to returning the mapped JSX.
But if the left side is `0`, it will render the character `0` instead which is likely not what we want done (which is to render nothing if the array is empty).
The appropriate way to do that would be
```jsx
{arr.length > 0 && arr.map((el, i) => <p key={i}>{el}</p>)}
```
Where if empty, the left side would evaluate to `false` which is not rendered, unlike `0`.

So in JSX, only `false`, `null` and `undefined` are not rendered. `''` and `0` whilst still logically falsy, will still be rendered on screen.

**Comment by JoshDevHub** [comment]
How do we feel about the final sentence in the note?
> To avoid any pitfalls, it’s essential to understand that certain falsy values behave differently in JSX when compared to JS.

I'm not sure that I like it. The logical behavior around what's truthy/falsy is the exact same between the two. The *rendering behavior* of JSX will treat certain falsy values differently, but I don't think that has an apples-to-apples comparison with vanilla JavaScript. This makes me feel iffy about that final sentence.

**Comment by MaoShizhong** [comment]
I was going to say if that last bit can cause confusion to just switch the wording to not say `certain falsy values behave differently` but `0 and '' render differently ... compared to other falsy values` but then thought, wouldn't an example for that lesson-note just be the clearest?

```md
<div class="lesson-note lesson-note--warning" markdown="1">

#### Falsy values in JSX, a common pitfall

In JSX, there can be some confusion regarding which values render content and which do not, especially when it comes to falsy values. It's important to note that while values like `null`, `undefined`, and `false` don't render anything, other falsy values such as `0` or `''` (an empty string) are perfectly valid in JSX and will be rendered as expected. To avoid any pitfalls, it's essential to understand that certain falsy values behave differently in JSX when compared to JS. 

</div>
```
becomes
````md
<div class="lesson-note lesson-note--warning" markdown="1">

#### `0` in JSX, a common pitfall
```jsx
function App() {
  const emptyArray = [];
  const notEmptyArray = ['array is no longer empty'];

  // replace notEmptyArray.length with emptyArray.length and see what happens
  return <div>{notEmptyArray.length && <p>Array is not empty</p>}</div>;
}
```
With `notEmptyArr.length`, it is `1` which is truthy and so the `<p>` element is rendered as you'd expect. However with `emptyArr.length`, even though the length is `0` and thus falsy (meaning the `&&` behaves as you'd expect and does not render the `<p>` element), `0` is still perfectly renderable JSX and so instead of nothing inside the `<div>`, it renders `0`.

Using something like `emptyArr.length > 0` achieves the same effect but without rendering `0` when empty because the expression evaluates to `false` instead of `0`.

</div>
````
Thoughts?

**Comment by MaoShizhong** [comment]
Or in fact even more straightforward, link to the react docs for conditionak rendering which has a pitfall note about this that explains it very clearly?

https://react.dev/learn/conditional-rendering#logical-and-operator-

**Comment by JoshDevHub** [comment]
Yeah the docs explain it really well in that note, and they give a nice example. That's probably the best thing to do.

**Comment by MaoShizhong** [comment]
Awesome - I'll open this up for someone to be assigned then. Whoever that is can replace the lesson-note content with something like
```md
#### Numbers and `&&` - a common pitfall

When using `&&` for conditional rendering, don't put numbers on the left side. The React docs on [conditional rendering](https://react.dev/learn/conditional-rendering#logical-and-operator-) provide more details about this in the `Pitfall` box in the section about `&&`.
```

**Comment by forge34** [comment]
i would like to be assigned this issue if possible .
