### ISSUE TITLE
Community Guides: Merge section into Foundations

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27470]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I'm at React at only just now realised TOP has an entire section of 'hidden' lessons. These lessons aren't linked everywhere except the footer amongst 20 other links it is unlikely that more than a few % of people have actually read these lessons, and I think they are very valuable.

<img src='https://github.com/TheOdinProject/curriculum/assets/154856872/f1b3f26e-859b-41a6-bc87-9043f664365d' height='200px' width='auto'>
<img src='https://github.com/TheOdinProject/curriculum/assets/154856872/c0abfa2f-7a96-45e3-a372-5405b9a9a3f4' height='200px' width='auto'>

This entire section, `Community Guides` should just be merged into **Foundations** and placed after the `Introduction` section but before `Prerequisites` 

<img src='https://github.com/TheOdinProject/curriculum/assets/154856872/bfa9a73e-3c7d-4a6b-99b0-3dd02de5d383' height='200px' width='auto'>

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/guides/community

### (Optional) Discord Name

https://www.theodinproject.com/guides/community

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @nikitarevenco 

Those guides were designed as "onboarding" docs for the community. There were plans for making them more visible by listing them on a community landing page. That might still happen.

But I don't think they belong in foundations. A decent portion of our site users never join our Discord and wouldn't find them useful. We'd also like everyone get to the coding parts of foundations as quickly as they can.
