### ISSUE TITLE
Rails course, Active Record Basics lesson: Split into multiple lessons

### ISSUE THREAD

**Issue by Leo-U** [TheOdinProject/curriculum#27477]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### The old version and what happened

If you go [here](https://web.archive.org/web/20150207114235/http://www.theodinproject.com/ruby-on-rails/active-record-basics), you can see a much older version of how this lesson used to look. You'll see that the lesson used to have multiple reading assignments to read those docs, inserted throughout the content. Each pre-assignment reading was originally intended as some light, high-level browsing to do before diving into those docs.

At some point, the decision was made to compile all of the 'overview reading' into a single chunk, have the student read all of that introductory text first, and then have the student read all those assigned docs at once. **I'm not questioning that decision -- it was valid because its purpose (I assume) was to make the layouts of all TOP lessons consistent. That's totally fine and I respect it.**

### The main problem

That correction introduced a problem which, IMO, should now be fixed also: by the time you're reading, for example, the Migrations section, **you were supposed to have already done some docs reading!** That matters, and I think I can give some evidence that it does:

![Screenshot from 2024-02-27 16-27-47](https://github.com/TheOdinProject/curriculum/assets/47509535/f7738952-34f8-4f02-9fe7-4bb1b68fc1c9)

As you can see outlined in red, the lesson is stating that you should have 'just learned above' how to set up a model file. The reader of the new version thinks "ok, it's referring to that '30 seconds about working with models' section I just read". So you scroll up there to check where it says how to set up the model. Does it? To the best of my understanding, it doesn't. It says that "you create a model called User, which is really just a Ruby file which inherits from Active Record". But that's it. The rest of the section briefly demonstrates *how to add a new user, which is a new instance of the already-existing User model, not a new model*. IMO, that section doesn't include the steps for actually setting up a model file.

So, could "just learned above" have originally been a reference to the **assigned reading**? I think very likely so! As you can see, [this section of the assigned reading](https://guides.rubyonrails.org/active_record_basics.html#creating-active-record-models) does provide greater detail:

![Screenshot from 2024-02-27 16-45-51](https://github.com/TheOdinProject/curriculum/assets/47509535/0cccecad-4eeb-4d06-ab41-96314810a669)

### Another problem
The other problem is I guess more psychological - - the sheer volume of the lesson content as it stands now. The preliminary reading is now more of a chore. And reading those docs all at once? I've done it, and I think it's a lot.

### Proposed solution
I would very much like to complete this task myself. I think the correct course of action is to split up the lesson, because that way it doesn't override the previous decision to keep the layout of the lessons consistent. That should make everyone happy -- the lesson layouts would be consistent, and the doc reading assignments would be correctly interleaved between the lesson text as was intended by the original author.

### Obstacles implementing the solution
Ok, I realize what I'm proposing is a big job and an extreme change. The new lessons would need to be formatted correctly -- they would need to have the proper sections, like Introduction and so on. So the content of each lesson would need to be re-arranged and edited pretty drastically. That's a lot, but I'm willing to give it a shot. Any content modification would of course be subject to everyone else's approval. It's conceivable that the job is too much for one person, in which case it would need to be split up. But I'd like to do it all myself if possible.

Aside from the writing, I don't actually have a full understanding of what else I'd need to do because I've never made a contribution as significant as adding new lessons. But, I could use [the guide](https://github.com/TheOdinProject/.github/blob/92e0734abfb36110d140c31f6cc9671935fc2862/CONTRIBUTING.md), [the wiki](https://github.com/TheOdinProject/theodinproject/wiki), fork and clone the repo, etc, and figure things out from there.

So, what do you guys think of my proposal? Is it alright if I do it?

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-active-record-basics

### (Optional) Discord Name

leo_jj

**Comment by Leo-U** [comment]
Since no one has replied, I'm just gonna start work on it. At some point, I'll eventually do a PR and then I'll see what happens.

**Comment by KevinMulhern** [comment]
@Leo-U it can take us a while to review and reply to things, please don't take it personally. We have a 100+ issues and we're all volunteers.

I like the idea of this, the assignment section being broken down into sub-headings is indicative this lesson is trying to do too much. We can probably have lessons for each of the subheading:

<img width="758" alt="Screenshot 2024-03-01 at 00 40 55" src="https://github.com/TheOdinProject/curriculum/assets/7963776/93a5e528-209a-49e2-9387-5863bced645a">
of this, but

But, we'd better doing this lesson by lesson instead of all in one go in a mega PR if thats what you had in mind from your recent comment? - It'll be easier for you to manage, and easier for us to review.

Starting by breaking out an associations lesson is probably the smartest way to go. We can start small, assess the quality see what happens from there. Doing them back to front from associations to migrations will also mean can ship the lessons straight away instead of waiting for them all to be done.

**Comment by Leo-U** [comment]
Ah gotcha. Sorry if I came across impatient there. I know you guys are busy. Just wanted to document my intent to start :) Yes, doing it all in one giant PR does sound harder. Associations first sounds great.

Let me see if I can figure out a plan of action then. I don't know your guys' process here, so correct me if I'm wrong. Here's my current plan:

1. Fork and clone per [this guide](https://github.com/TheOdinProject/theodinproject/blob/3cf247367e2a2a75b23e0aba33dad628d4a2189e/CONTRIBUTING.md)
2. Using [this guide](https://github.com/TheOdinProject/theodinproject/wiki/Adding-a-Lesson) and other wiki info as needed, work on the Associations lesson, paste content from the Active Record Basics lesson to that one. Format/edit the new lesson as needed. Maybe add a notice to the lesson title/s so that people know why there's duplicated content in both Active Record Basics and the new Associations lesson.
3. Open a PR by again following the instructions in CONTRIBUTING.md and await feedback.
4. Then if all goes well, do the next lesson. Meanwhile, just leave the Active Record Basics lesson in place, worry about removal later.

**Comment by JoshDevHub** [comment]
@Leo-U Your plan sounds good to me. I'll assign this to you.

Definitely let us know if you have questions or need help with anything while you're working on this.

**Comment by Leo-U** [comment]
Status update and advice request:

I managed to get TOP running locally after forking and cloning `TheOdinProject/theodinproject`. I have also completed [these instructions here](https://github.com/TheOdinProject/theodinproject/wiki/Adding-a-Lesson).

But I think I may have skipped a step. If I understand correctly, I should have forked and cloned `TheOdinProject/curriculum` first, worked on the new Associations lesson, added the markdown file to the appropriate location in the local directory, and *then* followed the Adding a Lesson instructions with the other repo.

So my current plan is as follows -- please let me know if it's correct:

1) Finish the new lesson file, format correctly per that repo's instructions, etc., making sure the filename matches the `github_path` key in the lesson file in `TheOdinProject/theodinproject`.

2) Do a PR on the `TheOdinProject/curriculum` repo.

3. Re-seed per step 3 of _Adding a Lesson_.

4) Do a second PR on the `TheOdinProject/theodinproject` repo.

**Comment by JoshDevHub** [comment]
Yep that all sounds about right. One thing to potentially note: you'll have to wait for the first PR to the curriculum repo to be approved and merged before the 2nd one can be done.

**Comment by Leo-U** [comment]
Ok, thanks for everyone's help!

So, should I go ahead and rinse and repeat with validations?

So that would be:
- Add new validations lesson
- Remove the validations content from the Active Record Basics lesson
- Submit PR

**Comment by JoshDevHub** [comment]
Yep, same process for that section.

Thank you for your work on this :rocket:

**Comment by Leo-U** [comment]
@JoshDevHub Hi, thank you for all your help! One more thing -- the final lesson order for Active Record Basics section should be Active Record Basics, Migrations, Basic Validations, then Associations. Currently, the associations lesson comes after validations, but it should be last.

**Comment by JoshDevHub** [comment]
@Leo-U Thank you for all your work on this.

The ordering of the lessons is a silly mistake on my end. Would you be okay with fixing that by PRing to the main repo? All you need to do is arrange them in the correct order in this file: https://github.com/TheOdinProject/theodinproject/blob/main/db/fixtures/paths/full_stack_rails/courses/rails.rb#L55-L59

**Comment by Leo-U** [comment]
@JoshDevHub Sure! Thanks for the opportunity.
