### ISSUE TITLE
Typo on the Foundations page

### ISSUE THREAD

**Issue by janbury** [TheOdinProject/curriculum#27479]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There's a typo in "questions", it says "qeustions".

"Check out the [frequently asked qeustions](https://www.theodinproject.com/faq) section."

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-how-this-course-will-work

**Comment by MaoShizhong** [comment]
@janbury great spot!
Nice easy issue for first time contributors up for grabs!

**Comment by StepQuest** [comment]
I would get this

**Comment by MaoShizhong** [comment]
And get this you shall :)

**Comment by KevinMulhern** [comment]
Hey, sorry, we got [a PR](https://github.com/TheOdinProject/curriculum/pull/27478) in for this just before a few minutes before the issue was created.

**Comment by MaoShizhong** [comment]
@KevinMulhern ah damn, I checked the PRs but didn't spot this typo being included in that one. Thanks for the catch!

**Comment by KevinMulhern** [comment]
It's all good, easily done 😄
