### ISSUE TITLE
Curriculum: update mention of Twitter to X

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#27483]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Replacement for https://github.com/TheOdinProject/curriculum/pull/26627#event-11941748537

Essentially we want to replace most mentions of Twitter to "X (Twitter)", as well as "tweets" to "posts".

Whomever would like to work on it just needs to double check the linked PR above for comments regarding intended work to be done.

### Path

Other / NA

### Lesson Url

N/A

**Comment by Asartea** [comment]
I think it would be best to follow the established convention of writing something like X (the platform formerly known as Twitter) on the first occurrence and then writing plain X afterwards. This gives the reader a definition of what we mean by X, without constantly repeating the X (Twitter) construct

**Comment by nikitarevenco** [comment]
Sure, I can work on this. Should I put all of this into a single PR if I get assigned?

**Comment by thatblindgeye** [comment]
@Asartea ++ agreed with what you said!

@nikitarevenco I'll assign you. And I'll say yeah this can all be put into a single PR. The original PR was only 13 files and I don't believe there were a ton more files that needed updating beyond that. If it gets beyond 25-30 files you can reach out to double check, though.
