### ISSUE TITLE
PR template: Add a checkbox for having resolved all markdownlint issues?

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#27489]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

As resolving all markdown lint issues has become a de facto requirement for a PR to be merged, should the PR template have a checkbox in the Requirements section for `I have ensured [markdownlint](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#curriculum-linting) doesn't flag any issues for any lesson files are included in this PR.`

### Path

Other / NA

### Lesson Url

N/A

### (Optional) Discord Name

asarta

**Comment by cakegod** [comment]
Yep, I agree. 

That aside, I wonder if we also mention the linter in [LAYOUT_GUIDE_GUIDE.md](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

**Comment by Asartea** [comment]
> That aside, I wonder if we also mention the linter in [LAYOUT_GUIDE_GUIDE.md](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

I don't believe we do. It is mentioned in the [Repo specific instructions part of the global CONTRIBUTING.md](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#curriculum-linting) file, which gets linked via README.md, but I think specifically shouting it out there would also be good

**Comment by cakegod** [comment]
Oops, that's what I meant! My sentence was missing a verb.

Either way, I think it's a good idea. Mentioning it there, plus mentioning it in the issue template, should be good enough.

**Comment by JoshDevHub** [comment]
I think something like this is probably good to include.

My only hesitation is that contributors can't fully run the lint tool unless they have node installed, and people working through our curriculum don't install node until close to the end of Foundations.

**Comment by JoshDevHub** [comment]
Regarding my last comment, would there potentially be a way to word the checkbox such that it works well for less experienced contributors who haven't installed Node?

**Comment by MaoShizhong** [comment]
One big thing I think may need to be considered is that not everyone opening PRs will be doing so via a local fork. Especially with first-time contributors and/or simple contributions like typos/grammar errors, people often go through the `Improve on GitHub` link at the bottom of each lesson page which will auto-fork if necessary then allow them to edit and PR directly in GitHub itself without any local stuff.

These people will not have any access to markdownlint until the PR action runs.
If we make this a checkbox requirement, what are we saying about that process of PRs?

Once we do fix all the current linting errors (style as well as lesson structure and accessible links), which will take a while yet, we would only need to request changes if an incoming PR makes the linter angry for whatever reason. Those changes can still be done directly in GitHub and a maintainer can easily provide the exact changes necessary.

**Comment by Asartea** [comment]
> One big thing I think may need to be considered is that not everyone opening PRs will be doing so via a local fork. Especially with first-time contributors and/or simple contributions like typos/grammar errors, people often go through the Improve on GitHub link at the bottom of each lesson page which will auto-fork if necessary then allow them to edit and PR directly in GitHub itself without any local stuff.

~~Ah great, more complications~~

I was already thinking the note would be getting too long and with this especially, I fear we'd end up with a paragraph length checkbox. What do you think about instead keeping just the original line in the PR template, and then adding a note in the contributing guide? I'm thinking something like this:

> Note: The VSCode plugin requires that you develop locally, and the package requires that you have Node installed. If you have not yet installed Node and/or are making your contribution through the GitHub website, you can just submit the PR, and automated tests will identify any linter errors.

**Comment by MaoShizhong** [comment]
What do you and/or @JoshDevHub think about adding a little to the suggested contribution guide text as such:
> Note: The VSCode plugin requires that you develop locally, and the package requires that you have Node installed. If you have not yet installed Node and/or are making your contribution through the GitHub website, you can just submit the PR, and automated tests will identify any linter errors. If you are unsure how to handle any particular linter errors, feel free to add a comment to your PR saying so, and a maintainer can advise you on how to proceed.

But I'm personally in favour of not changing the PR template checkbox requirements specifically because of the points I mentioned above. The current checklist is fully doable regardless of PR method.

**Comment by MaoShizhong** [comment]
Closing this because #27762 will add a repo-specific contributing guide, and a follow-up will then amend mentions of the contributing guide to include both the existing general one, as well as the respective repo-specific guide. 

So the linting stuff will be covered as part of that.
