### ISSUE TITLE
New Course: TypeScript

### ISSUE THREAD

**Issue by mehkij** [TheOdinProject/curriculum#27495]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Could we get a dedicated TypeScript course that comes after the vanilla JS course? I know there's a section in the React course in the propTypes lesson that mentions TypeScript and warns against learning it if you haven't learned vanilla JS yet, but I think that TS has become the default for most developers nowadays, and is worth learning. Although it wouldn't stop users from doing it, you could also include a warning similar to the warning at the beginning of the React course to dissuade users from learning TS before JS.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/paths/full-stack-javascript

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @mehkij. We have an [existing discussion about Typescript](https://github.com/TheOdinProject/curriculum/discussions/27208) on TOP. To keep it all in one place, would you mind sharing your thoughts on that thread please?

**Comment by mehkij** [comment]
> Thanks for the suggestion @mehkij. We have an [existing discussion about Typescript](https://github.com/TheOdinProject/curriculum/discussions/27208) on TOP. To keep it all in one place, would you mind sharing your thoughts on that thread please?

Yep my bad, definitely wasn't aware of this thread. Didn't pop up for some reason when I searched for it.
