### ISSUE TITLE
Markdownlint: TOP001 rule is unclear

### ISSUE THREAD

**Issue by cakegod** [TheOdinProject/curriculum#27498]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The TOP001 rule regarding descriptive text labels is confusing. The detail of the rule, `Links must have a more descriptive text label` does not indicate what is wrong with the text, making it difficult to fix the issue without looking at the rule implementation. Additionally, the rule (and the other custom rules) do not have documentation. 

I would do the following:
- Change the detail from `Links must have a more descriptive text label.`  to `Link text should not contain 'this' or 'here'`, 
- Add a documentation file using the same [structure as the default rules](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md). It will contain a description of the rule, what it is for, examples of text that break the rule, and corrected versions of the examples. 
- Link the rule's documentation to the rule through the `information` prop. This enables the Odinite to open the documentation's link when the rule is triggered if he's using the VSC plugin.

### Path

Other / NA

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/markdownlint/TOP001_descriptiveLinkText/TOP001_descriptiveLinkText.js

### (Optional) Discord Name

Cake

### (Optional) Additional Comments

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/TheOdinProject/curriculum/issues/27546
- [ ] https://github.com/TheOdinProject/curriculum/issues/27547
```

**Comment by Asartea** [comment]
> Link text should not start with 'this' or 'here'

Based on personal experience, I think links can't contain `this` or `here` at all

**Comment by cakegod** [comment]
> @cakegod just to share the intent behind this rule as it currently is written, originally I was checking links that have "this" or "here" in the text, and also has ~5 or less words before and/or after "this"/"here". So "check out this video" would get flagged as invalid, but "this article on flex-grow from the MDN docs" wouldn't.
> 
> The issue I felt was that whatever number of words before/after would be arbitrary and not really beneficial. "this really cool article from AwesomeSite is worth a read" wouldn't get flagged as invalid even though it is invalid.
> 
> So the regex just checks whether "this" or "here" exists, which catches more invalid links, but unfortunately does catch some false positives. "This article on flex-grow from MDN" will get flagged as an error, and while that isn't really invalid, we could still update the link text to pull "this" out: `this [article on flex-grow from MDN](...url)`, or we could include the markdownlint comment to disable the rule for that line.
> 
> I agree that the error message can be improved, though. It still needs to be generic enough that it'll fit in any scenario (since we can't assume the context of every link), but including some additional verbiage to briefly explain how to resolve it or why the error was thrown wouldn't hurt. If you'd like I'll assign this to you to improve the error message @cakegod , and if you have any questions please let us know

What about the documentation file? I think it could only be beneficial. We probably also want to add it to the other custom rules.

**Comment by thatblindgeye** [comment]
Do you mean the styleguide MD file?

And if the other custom rules aren't clear enough we can certainly tweak them, but I think most of them should be pretty clear in their error messages. "Headings should not contain inline code" for example, and then for the heading structure it should typically include a message stating what was expected (either a specific heading level or a heading content) and what was actually encountered.

**Comment by cakegod** [comment]
I mean having [documentation](https://github.com/DavidAnson/markdownlint/tree/main/doc) similar to Markdownlint's in-built rules. Even if the rules are clear, it doesn't hurt to document them.

**Comment by thatblindgeye** [comment]
Ah gotcha. I wouldn't be opposed to some documentation like that. I think this should be tackled as 2 separate issues: 1 to update the error message for TOP001, and another to add a markdown file for each rule that documents it better. I'll update your original post with acceptance criteria, and if you'd like to be assigned to either/both still just let me know @cakegod (there should be separates PRs for each acceptance criteria)

**Comment by cakegod** [comment]
Sure; assign me to both.

**Comment by MaoShizhong** [comment]
@cakegod Just want to confirm if everything that you expected to work on has been completed? If so, I can complete this issue.

**Comment by cakegod** [comment]
You can close it.
