### ISSUE TITLE
Ruby: Discrepancy in Ruby extensions for VS Code

### ISSUE THREAD

**Issue by Grayvox** [TheOdinProject/curriculum#27502]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the lesson "Debugging" under the Ruby course, you are instructed to check that you have the "Ruby extension" and the "rdbg extension". However, the Ruby extension linked to is the now deprecated one, instead of the Ruby LSP extension that you're instructed to install at the start of the course. Minor, but I would like to fix this if possible

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-debugging#assignment

**Comment by JoshDevHub** [comment]
Hello and thank you for making this issue @Grayvox 

This is definitely a problem, but it's already set to be addressed in #27128, which we're hoping to merge soon. If you were to work on this, we'd almost certainly have to untangle merge conflicts around this. So unfortunately, I'll have to close this issue.

Thank you for taking the time to make this issue though, and I look forward to future contributions if/when you notice other problems in the Ruby/Rails course.
