### ISSUE TITLE
Function basics: add image showing what parameters and arguments stand for

### ISSUE THREAD

**Issue by cakegod** [TheOdinProject/curriculum#27539]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Odinites tend to confuse functions terminology. I suggest including the following image showing what each term stands for.
![function_terminology](https://github.com/TheOdinProject/curriculum/assets/36206278/a8418acc-d615-4c48-b12f-844e221df532)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-function-basics

### (Optional) Discord Name

Cake

**Comment by KevinMulhern** [comment]
Thanks for putting this together @cakegod. Sounds like a good idea to me!

What did you use to make the image? it looks great!

**Comment by cakegod** [comment]
@KevinMulhern I've used [Snappify](https://snappify.com/), but the free tier is quite limited.

**Comment by nikitarevenco** [comment]
I can work on this
