### ISSUE TITLE
Axes: <Flexbox Cheat Sheet makes Google Chrome's Native Anti-Malware Notification>

### ISSUE THREAD

**Issue by Deyody** [TheOdinProject/curriculum#27531]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I went to use the cheat sheet and Chromes native security service had to notify me, thought it was something you'd like to know. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-axes

### (Optional) Discord Name

fantasticplanet

### (Optional) Additional Comments

Can you also send me a copy, I didn't want to go onto the site.  :100:

**Comment by MaoShizhong** [comment]
@Deyody Thank you for opening this issue.
I have not been able to replicate this myself. I have tested the link in question on several devices using Chrome (and Firefox for good measure) and have not received any security-related notifications/logs/blockage from it. i.e. the site loads perfectly fine on my ends like any other site without security issues.

Could you share an example of what notification you are receiving?

**Comment by Deyody** [comment]
It did not happen the next time I had gone to use it, strange. Not sure
what happened there, hopefully it's not on my end hahaha
