### ISSUE TITLE
Easy Fix : I noticed that this link in the lesson is broken/expired.

### ISSUE THREAD

**Issue by Javantax** [TheOdinProject/curriculum#27542]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The link for the "The Odin Project" discord server is broken/expired.

On the second point on the Assignment area:

"Now, sign in to our **_[Discord server](https://discord.gg/fbFCkYabZB)_**. Pop in and say hello! We’ve created an introductions room which is a great place to introduce yourself and we’re always happy to welcome new community members. We have chat rooms for every development topic covered in our curriculum. Log into the chat and start exploring!"

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community#why-a-community-is-awesome-for-you:~:text=Now%2C%20sign%20in,and%20start%20exploring!

### (Optional) Discord Name

Javanta

### (Optional) Additional Comments

We can fix this by just going to the "The Odin Project" discord server and generating an non-expiry invite and then putting that new link over there in the html.

**Comment by fabulousgk** [comment]
The link works fine for me, tried in an Incognito window.  Having said that, it should be updated to the custom invite anyway https://discord.gg/theodinproject

**Comment by Javantax** [comment]
> The link works fine for me, tried in an Incognito window. Having said that, it should be updated to the custom invite anyway https://discord.gg/theodinproject

Hmm ok, I don't know why it doesn't work in the normal browser.

**Comment by KevinMulhern** [comment]
Invites can sometimes act weird for people if they've got Discord running on more than one tab. Do you have Discord open on any other tabs?

**Comment by Javantax** [comment]
> Invites can sometimes act weird for people if they've got Discord running on more than one tab. Do you have Discord open on any other tabs?

No, I don't even use discord on my browser.

**Comment by MaoShizhong** [comment]
> The link works fine for me, tried in an Incognito window. Having said that, it should be updated to the custom invite anyway https://discord.gg/theodinproject

Thanks @fabulousgk - just reminded I need to update my descriptive link spreadsheet to have all our discord server links also updated to this.

**Comment by JoshDevHub** [comment]
> No, I don't even use discord on my browser.

What operating system and browser are you using?

**Comment by Javantax** [comment]
> > No, I don't even use discord on my browser.
> 
> What operating system and browser are you using?

MacOS Sonoma 14.2.1 (23C71)
With Chrome Version 122.0.6261.94 (arm64)

**Comment by JoshDevHub** [comment]
Does the https://discord.gg/theodinproject link work for you or does that one fail as well @Javantax

**Comment by Javantax** [comment]
> Does the https://discord.gg/theodinproject link work for you or does that one fail as well @Javantax

Yea, it's working fine now.

**Comment by JoshDevHub** [comment]
Glad to hear it's working!

Would you be okay with making a small PR to update the link to the https://discord.gg/theodinproject ?

**Comment by Javantax** [comment]
> Glad to hear it's working!
> 
> Would you be okay with making a small PR to update the link to https://discord.gg/theodinproject ?

Yes, I would love to do that!

So I just need to fork the repository and then clone it and make the change in the code and then push to origin? (I'm new to this sorry!)

**Comment by kol3x** [comment]
> > Glad to hear it's working!
> > Would you be okay with making a small PR to update the link to https://discord.gg/theodinproject ?
> 
> Yes, I would love to do that!
> 
> So I just need to fork the repository and then clone it and make the change in the code and then push to origin? (I'm new to this sorry!)
Kind of. There is a step-by-step instruction in [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md). As long as you follow it, it's a pretty easy process.

**Comment by kol3x** [comment]
> > Glad to hear it's working!
> > Would you be okay with making a small PR to update the link to https://discord.gg/theodinproject ?
> 
> Yes, I would love to do that!
> 
> So I just need to fork the repository and then clone it and make the change in the code and then push to origin? (I'm new to this sorry!)

Kind of. There is a step-by-step instruction in [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md). As long as you follow it, it's a pretty easy process.

**Comment by JoshDevHub** [comment]
> Yes, I would love to do that!
> 
> So I just need to fork the repository and then clone it and make the change in the code and then push to origin? (I'm new to this sorry!)

You have it mostly right and as was said above, you can use our contributing guide to fill in the gaps. Let us know if you have any questions.

Assigning you to work on this.

**Comment by Javantax** [comment]
> > Yes, I would love to do that!
> > So I just need to fork the repository and then clone it and make the change in the code and then push to origin? (I'm new to this sorry!)
> 
> You have it mostly right and as was said above, you can use our contributing guide to fill in the gaps. Let us know if you have any questions.
> 
> Assigning you to work on this.

Thanks for giving me the chance.

I have opened a pull request following the guidelines.
