### ISSUE TITLE
React: Code sandbox AI disable

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27552]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

All of the code sandbox examples have AI autocompletion which is really annoying
For example, in the Class Based Components assignment, I forked the code sandbox, and when I was trying to complete one of the assignment items it straight up just autofilled an entire line for me 

<img src="https://github.com/TheOdinProject/curriculum/assets/154856872/c920fc43-599b-4ff7-8e04-6b5458580019" height="auto" width="70%">

It seems that this can only be disabled by whoever created the code sandbox example, [as said in the official instructions](https://codesandbox.io/docs/learn/ai/codeium#settings-and-configuration). 

### Path

Ruby / Rails, Node / JS

### Lesson Url

React Section

### (Optional) Discord Name

Revenco

**Comment by fabulousgk** [comment]
Duplicate: https://github.com/TheOdinProject/curriculum/issues/27239

**Comment by nikitarevenco** [comment]
> Duplicate: #27239

Thank you for letting me know!
