### ISSUE TITLE
JavaScript Course: New section "Functional Programming"

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27558]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

TOP doesn't touch on a few functional programming concepts which I believe are very interesting to learn about and, learners should be aware of since it will help broaden their knowledge and in their future, they may end up working on code that uses functional programming style.

#### Functional Programming
- Introduction
  - The JavaScript course already touches on pure functions, however I think they could be referenced again as well as a general introduction to functional programming, what it is, etc in an **Introduction** lesson 
- Currying
- Higher Order Functions
- Composition
- (Possibly) a project where the learner needs to use functional programming

lessons will also be supplied with TDD exercises in the odin exercises repository

Let me know what you think about this!

### Path

Node / JS

### Lesson Url

JavaScript Course

### (Optional) Discord Name

Revenco

**Comment by MaoShizhong** [comment]
@TheOdinProject/javascript thoughts?

My initial thoughts are that while individual FP concepts/techniques are certainly powerful and helpful, I'm not so sure on the value of dedicating a section to "leaning about functional programming" within the context of this curriculum. I'd imagine that if individual FP-based concepts/techniques are significantly valuable to learn about, rather than having a dedicated FP section, they would be better off integrated into existing lessons where most appropriate.

i.e. instead of going "okay, now we're going to learn about FP" and perhaps get people to shift focus and practise those things, drop in the valuable stuff as and when they'd be valuable to gain awareness of.

**Comment by JoshDevHub** [comment]
Personally think these things could absolutely be mentioned, but I don't know about a whole section on it. Some of these I'd have doubts could really fill out a whole lesson. Assuming the learner has already been exposed to things like `Array.prototype.filter()`, they already know about higher order functions (maybe just not by that name).

But yeah interested in other people's thoughts on this as well.

**Comment by thatblindgeye** [comment]
I'm also of the view that some of these topics would work better sprinkled into the curriculum rather than an entire section dedicated to them. Currying is one of those topics that I don't think is really necessary within the context of the curriculum, though.

**Comment by 01zulfi** [comment]
@nikitarevenco Thanks for opening this issue.

Not sure if we need an entire section, as I think learners get naturally introduced to some of these concepts. As @JoshDevHub mentioned, learners already know about higher order functions in foundations via the array methods. Similarly, leaners get exposed to currying in the [passing data between components lesson](https://www.theodinproject.com/lessons/node-path-react-new-passing-data-between-components#functions-as-props)

**Comment by MaoShizhong** [comment]
Closing as it looks like we're in agreement that we won't be planning to have a dedicated section for FP.
