### ISSUE TITLE
Fetching Data In React: Add section that talks more about error handling

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27568]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Hey, so I'm currently going through this lesson and I realised that the idea about throwing errors hasn't really been talked about very much. The closest it gets to it is in the [async await](https://www.theodinproject.com/lessons/node-path-javascript-async-and-await#error-handling) lesson. But the lesson doesn't touch on generating our own errors or "rethrowing". So I was thinking maybe a section that goes over these points will be useful to the reader:

- What is the **throw** operator
- Rethrowing
- How error objects are structured
- Creating custom errors by extending the base Error class, which can be very useful to check which type of error we've thrown via `instanceof` or giving the error object custom properties 

Let me know what you think about this

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react

### (Optional) Discord Name

Revenco

**Comment by JoshDevHub** [comment]
Any thoughts on this @TheOdinProject/react ?

**Comment by MaoShizhong** [comment]
I don't think we really need to dedicate time in the curriculum to error handling beyond what it covers already. I'm not sure there's not so much *necessity* in going through that in more specific detail.

For the course, you really don't need to know how Error objects are constructed, nor do you really need to dig into creating your own errors that extend Error. While they have their uses, I can't see how those uses are significant enough to dedicate time to looking into. I'm very certain that should someone encounter a situation where this holds great value (be that within or after the course), they'd be more than capable of looking this up for themselves. But it doesn't feel like an important enough topic to need its own study within the curriculum, in my honest opinion.

**Comment by MaoShizhong** [comment]
Closing as it doesn't seem like we're planning to action on this further.
For now, error handling is covered sufficiently within the curriculum to serve its goals, and anything on top of that can be independently researched if needed.
