### ISSUE TITLE
JavaScript: Update Knowledge Check links

### ISSUE THREAD

**Issue by khhuang7** [TheOdinProject/curriculum#27560]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Knowledge Check, the following bullets link to the same lesson using fragment identifiers that don't seem to exist, and just need to be created in the lesson content:

- [Explain what the concepts “entry” and “output” mean in relation to webpack.](https://www.theodinproject.com/lessons/node-path-javascript-es6-modules#webpack-knowledge-check) (#webpack-knowledge-check)
- [Explain one of the main benefits of writing code in modules.](https://www.theodinproject.com/lessons/node-path-javascript-es6-modules#module-knowledge-check) (#module-knowledge-check)
- [Explain “named exports” and “default exports”.](https://www.theodinproject.com/lessons/node-path-javascript-es6-modules#exports-knowledge-check) (#exports-knowledge-check)

I see there is an open issue #26976 to update the whole lesson, but this seems like a quick fix in the meantime.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-es6-modules#knowledge-check

### (Optional) Discord Name

katastrophe_93180

**Comment by MaoShizhong** [comment]
@khhuang7 Thank you for opening this issue.
This seems like a sensible thing to fix now, as the issue you linked is a much larger task that will take a while to complete, so I'll assign you for this one.
