### ISSUE TITLE
Homepage: Feedback form is outdated

### ISSUE THREAD

**Issue by George-Gabechava** [TheOdinProject/curriculum#27564]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The feedback form in node path for the Project: Homepage seems to be a form from a different section of the course.

The header: "**RoR -** Advanced HTML and CSS feedback" 
"RoR" title may cause confusion. 

The Last Question: "If you are on the JavaScript path, on a scale of 1 being poor to 5 being great and would not change anything. How would you rate your experience with the **Ruby on Rails** path so far?"
should instead say:
If you are on the JavaScript path, on a scale of 1 being poor to 5 being great and would not change anything. How would you rate your experience with the JavaScript path so far?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-homepage

### (Optional) Discord Name

gtothesquared

**Comment by JoshDevHub** [comment]
Thank you for making this issue. That's definitely a problem we'll want to get cleaned up.

I see that you've marked that you'd like to work on this, but unfortunately, this is something that can only be changed by people who have access to The Odin Project google account (because it's in a google survey). So I'll have to get one of the maintainers with access to fix it. Sorry about that.

**Comment by wise-king-sullyman** [comment]
There's no PR since the changes were just in a google form but I have made the suggested updates, everything look good to you know @George-Gabechava?

**Comment by MaoShizhong** [comment]
Closing as no response, and also confirmed accessing the form via the project results in a good-looking and reading form :muscle:
