### ISSUE TITLE
Common Data Structures and Algorithms: Link redirects

### ISSUE THREAD

**Issue by Gohan61** [TheOdinProject/curriculum#27577]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The third assignment link ['What is an algorithm and how does it make you a better programmer?'](http://blog.thefirehoseproject.com/posts/what-is-an-algorithm/) is redirecting to an about page of a bootcamp. 

Searching for the link on Wayback machine retrieves the correct [website](https://web.archive.org/web/20231223233808/http://blog.thefirehoseproject.com/posts/what-is-an-algorithm/) 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-common-data-structures-and-algorithms

### (Optional) Discord Name

gokhan.reads

**Comment by MaoShizhong** [comment]
Thanks for catching this. I've assigned this to you.
