### ISSUE TITLE
Change the guide in the Installations  lesson for installing Ubuntu

### ISSUE THREAD

**Issue by AirDevil188** [TheOdinProject/curriculum#27580]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Installations lesson for installing Ubuntu we link to this Medium guide: 
https://medium.com/linuxforeveryone/how-to-install-ubuntu-20-04-and-dual-boot-alongside-windows-10-323a85271a73 
from Dave's RoboShack. The guide is correct for the most part expect the fact that in the 2024. 16gb is not enough for the `root` `/` partition. As it was already mentioned by Scheals and Frank several times on the Discord channels. And as a  result of this because some users don't ask for help on the Discord they end up only giving 16gb for the `root` partition. And they end up having either to use `Live USB`,  boot from it install `gparted` and then shrink more space for the `root` partition. Or find some other way to do it.

Could we add a note before that article to warn users to add 30gb+ for the  `root` partition? 

Or maybe find a replacement for that guide or write our own version? 

Thanks.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### (Optional) Discord Name

airdevil188 (Uki)

**Comment by JoshDevHub** [comment]
Gonna tag @TheOdinProject/installations for this.

I agree than 16gb root is wayyy too small in 2024. I wonder if we even really need to separate root and `home/` for our users? It's simpler not to, and the main case for keeping it separate is to facilitate distro hopping, which shouldn't be a consideration for people learning through TOP.

**Comment by AirDevil188** [comment]
> Gonna tag @TheOdinProject/installations for this.
> 
> I agree than 16gb root is wayyy too small in 2024. I wonder if we even really need to separate root and `home/` for our users? It's simpler not to, and the main case for keeping it separate is to facilitate distro hopping, which shouldn't be a consideration for people learning through TOP.

Hmm, maybe that would be a good idea? I think that it could be a lot esier for new users, especially for the beginners  to go with `default partition scheme` option?

The things that  I can see that would benefit the users if they have an seprate `home` partition are:

- It makes system more "organized"? 
 - It's easier when it comes to the installation of  a newer Ubuntu version or a new distro without losing most of your configuraiton settings
 
 
 Eaither way. I think the guide from the `Installations` lesson should be fixed. 
 
Please, let me know what you guys think.
