### ISSUE TITLE
Recipes: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Panzer0** [TheOdinProject/curriculum#27581]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The contents guide contains the following outdated information regarding GitHub:

"A GitHub paid account is required to publish a private repository.".

While this used to be the case, as of now free accounts no longer possess a private repository limit. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes

### (Optional) Discord Name

panzer0panzer

**Comment by MaoShizhong** [comment]
Closed as the respective PR was also closed.
No action required as while free accounts can have private repos, the lesson note is talking about publishing a GH Pages site from a private repo, which currently still requires a paid account to do (i.e. free accounts can only publish GH Pages sites from public repos).

**Comment by MaoShizhong** [comment]
@Panzer0 Thank for you opening this. In the future, it would be preferable to not submit a PR for an open issue until the issue has been approved for work and you've been assigned to do it. We wouldn't want you to potentially do a fair amount of work on something only for it to be closed without merging for whatever reason!

For simple fixes like typos etc. then you can still open a PR directly without first opening an issue. But if you do choose to open an issue, best to wait until assignment before working on a PR :+1:

**Comment by Panzer0** [comment]
Oh, you're correct. My apologies!
