### ISSUE TITLE
New Lesson: Routes

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27605]
## Lesson overview

New routes lesson for the Express section

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Cover definition in routing
- Query & route parameters
- Express Router
- Dealing with static assets
- Code examples covering aforementioned concepts

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by Lofty-Brambles** [comment]
👋 I'd like to see what I can do!

**Comment by MaoShizhong** [comment]
Taking this one as per Lofty's request.
