### ISSUE TITLE
New Lesson: Controllers

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27615]
## Lesson overview

Cover controllers part of MVC architecture in Express land

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Cover definition of controllers
- Cover different response methods
- How to handle exceptions
- Deep dive into middlewares and its use cases like validation, authentication (actual implementation in later lessons)
- What is `next` in a controller
- Relevant code examples and discuss file structure

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by fcasibu** [comment]
would love to be assigned on this one!
