### ISSUE TITLE
Websockets and Actioncable: To add instructions before generating channel in case of error messages.

### ISSUE THREAD

**Issue by MKMaths22** [TheOdinProject/curriculum#27611]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

I am currently on this lesson and got the following error when I first tried the 'rails generate channel room' command: "You have already activated error_highlight 0.6.0, but your Gemfile requires error_highlight 0.5.1. Prepending 'bundle exec' to your command may solve this. (Gem::LoadError)"
After some searching on StackOverflow I found Elijah Ayandokun's answer on https://stackoverflow.com/questions/6317980/you-have-already-activated-x-but-your-gemfile-requires-y after other answers had not worked for me. Deleting the Gemfile.lock and running "bundle install" allowed the generate command to work correctly. I was working on the old RailsCars project, as suggested in the lesson. Would it be helpful for other learners to be warned of this potential problem and given a solution? 

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-websockets-and-actioncable

### (Optional) Discord Name

PJPlaysDoom

**Comment by MKMaths22** [comment]
A link to the SO article may not be necessary, but I suggest a warning in the lesson such as 'You may get an error message like this. If so, delete your Gemfile.lock and run 'bundle install' before trying this command again.'

**Comment by CouchofTomato** [comment]
@MKMaths22 

I'm ok with that. I'll assign you since you've indicated you want to work on it.

**Comment by MKMaths22** [comment]
So I have tried the pull request, but the Lint process has flagged 11 problems with the Markdown file, most of which are nothing to do with my changes. Should I carry out fixes for all of these other issues as well? Some are trivial, such as correcting 'Javascript' to 'JavaScript'. Others look tricky, such as the duplicate 'Connections' headings.

**Comment by CouchofTomato** [comment]
@MKMaths22 

Is that why you closed the PR?

You don't have to tackle them in the same PR. You can choose to but it isn't required.

**Comment by MKMaths22** [comment]
OK, thanks @CouchofTomato, I have made a fresh pull request, which of course generated the same errors.

**Comment by CouchofTomato** [comment]
@MKMaths22 

It looks like the PR is to your own fork. You need to make a PR back to our repo for me to be able to look at this.
