### ISSUE TITLE
New Lesson: Views

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27616]
## Lesson overview

Discuss views part of MVC architecture in Express land via EJS

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Introduce EJS as a template engine
- Instructions to set it up
- Relevant code examples covering syntax and handling dynamic data
- A code example covering forms

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by jasonHYLam** [comment]
Happy to write the introduction for now!
