### ISSUE TITLE
Motivation and Mindset: Monkeytype suggestion 

### ISSUE THREAD

**Issue by elwwan** [TheOdinProject/curriculum#27623]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The suggestion to use Monkeytype to improve your typing speed is there twice. I suggest only putting it once.
![image](https://github.com/TheOdinProject/curriculum/assets/87530085/acc50c17-3f85-4a08-9d09-9ced0cc042f6)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-motivation-and-mindset

**Comment by MaoShizhong** [comment]
@elwwan Thank you for opening this issue. 

This is something we're awaiting a fix on in #27604

**Comment by MaoShizhong** [comment]
Closing as this has been fixed in #27656
