### ISSUE TITLE
Foundations: Fix confusing video links in HTML Foundations

### ISSUE THREAD

**Issue by TheSeagullDev** [TheOdinProject/curriculum#27627]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Links to the videos by Kevin Powell in many of the HTML foundations lessons link to a playlist, not an individual video. This can cause some confusion as to which videos to watch, especially the first time. It would make sense to either change these links to going directly to the videos or add a clarification that only specific videos should be watched.

### Path

Foundations

### Lesson Url

Varios HTML Foundations lessons

### (Optional) Discord Name

theseagulldev

**Comment by MaoShizhong** [comment]
@TheSeagullDev thank you for opening this issue.

Could you provide links to each the relevant lessons and whereabouts in each the link in question would be? That would provide a lot of context -thanks.

**Comment by TheSeagullDev** [comment]
Links are in the assignment sections of

- [Elements and Tags](https://www.theodinproject.com/lessons/foundations-elements-and-tags#assignment)
- [HTML Boilerplate](https://www.theodinproject.com/lessons/foundations-html-boilerplate#assignment)
- [Working with Text](https://www.theodinproject.com/lessons/foundations-working-with-text#assignment) x2
- [Links and Images](https://www.theodinproject.com/lessons/foundations-links-and-images#assignment) x3

I also noticed that some of the links are inconsistently styled with regards to what part of the text is actually linked, but that may be beyond the scope of this issue.

**Comment by MaoShizhong** [comment]
@TheSeagullDev Thanks for providing the context.
Yep, I 100% agree on all of those - they can definitely have their links changed to be just the videos without the playlist attached.

Since you expressed you wanted to work on this, I'll assign you. You don't have to change the link texts - just the actual attached links. If any other linting errors come get flagged when you open the PR, you also don't need to address them if you do not want to/do not know how best to.
