### ISSUE TITLE
New Lesson: Forms and Data Handling

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27642]
## Lesson overview

Strategy on using forms for create/update and data sanitisation and validation

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Discuss forms and how to handle create and update entity forms in Express
- How to deal with error messages
- Discuss data sanitisation & validation via [Express validator](https://express-validator.github.io/docs/) 
- Code examples for above

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms is a good guide for this lesson

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by LexiphanicStroon** [comment]
Commenting to be assigned :)

**Comment by cmedina-dev** [comment]
Commenting to also be assigned 👍
