### ISSUE TITLE
Object Basics (foundation): Other small-scale changes: arr.map(function) needs to be put into a new array. This should be specified.

### ISSUE THREAD

**Issue by biandresen** [TheOdinProject/curriculum#27644]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I tried to write out console.log(arr) after the map (example of arr.map(addOne)) but it didn't work. It did however work when I added the mapped array straight into a new array, like this:
const newArr = arr.map(addOne);
console.log(newArr)

Maybe it's only me, but I didn't know the array itself wouldn't get the new numbers. 

Suggestion:
Specify that the altered content has to go into another array. The original array doesn't morph the content. This goes for these three methods: map, filter and reduce.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-object-basics

### (Optional) Discord Name

Birando

**Comment by MaoShizhong** [comment]
@biandresen Thank you for opening this issue.
Looking through the section you mentioned, I agree - it does not make it clear that the original array is untouched and those methods return a new array. So yes, this should definitely be made clear. I think the original code snippets came from whoever wrote them using the browser console, where if you enter something like `arr.map(addOne)` after doing the previous code, the browser would show the return value which would be `[2, 3, 4, 5, 6]`. But that's not made clear. I think just being explicit with a new variable and directly logging the new variable is the least vague.

Opening this up for help.
All 3 array methods (map/filter/reduce) need to be made clear that they do not alter the original array at all but instead return a new value (a new array in the case of map/filter, and just the reduced value for reduce).
The relevant code snippets ideally would also demonstrate assigning to a new variable, then logging the new variable output e.g.
```js
const filteredArray = arr.filter(isOdd);
console.log(filteredArray); // [1, 3, 5]
```

**Comment by nikitarevenco** [comment]
Oops. I am happy to fix this oversight!

**Comment by cakegod** [comment]
@MaoShizhong @nikitarevenco 
We could use a warning lesson note. Also, I am not a fan of those right-sided comments. I prefer them above the code:
 ```js
function addOne(num) {
  return num + 1;
}
const arr = [1, 2, 3, 4, 5];

// Logs [2, 3, 4, 5, 6]
console.log(arr.map(addOne))

```

**Comment by MaoShizhong** [comment]
@cakegod Agreed about "above" comments in general, though what is common (and certainly throughout the curriculum) is to have "output" comments on the right of the code.
