### ISSUE TITLE
Emmet: Remove assignment step 3

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#27687]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Conversation around this message for reference: https://discord.com/channels/505093832157691914/505093832157691916/1221960411977613333

The [Emmet lesson](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-emmet) has 3 assignment steps. Step 3 links to the full Emmet docs and while it says no need to memorise things, it does invite exploring "all the possibilities". This can lead to a *huge* rabbit hole for something that really isn't particularly valuable to rabbit hole into vs moving on.

The first two assignment steps are more than sufficient for the lesson, and the additional resources are also more than sufficient that no more need be added. Step 3 can be removed.

Opening this up for anyone to contribute - preference for people who have not done many or any PRs before. This should be a very simple change as only a single assignment step needs to be removed. No other changes need be made to the lesson file (including any pre-existing linting errors).

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-emmet

**Comment by Kacegz** [comment]
Hello, I'd like to help with this one

**Comment by ANOKpanda** [comment]
I did sure can help with this if that's ok.
