### ISSUE TITLE
Sign-up Form: Unclear wording in #4 and #7 of the tips section

### ISSUE THREAD

**Issue by tylerbruno** [TheOdinProject/curriculum#27685]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Following Mao's agreement in the wording being unclear, it could be good to look back at list items 4 and 7 under the tips section. It seems unclear what it trying to be conveyed with regards to the "error class" in item 4 and item 7 discussing JavaScript validation.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-sign-up-form

### (Optional) Discord Name

tb236

**Comment by MaoShizhong** [comment]
For reference: https://discord.com/channels/505093832157691914/516751477306294273/1221910345451438091

Step 4 says "password inputs should be given an `error` class".
It is not explicit that it should be given such a class only when invalid, and have that class removed when valid.

Further, using a class approach for this would suit JS-based validation, which has not been covered yet. CSS with on HTML-based validation would mean this step is better served via the `:invalid` pseudo-class, just like how `:focus` is mentioned in the step below.

@tylerbruno If you're happy to change the wording of step 4 to be something more like 
> The inputs, by default have a very light border (`#E5E7EB`), but we’ve included 2 variations. For starters, the password inputs should have a red border if they contain an invalid password. This can be handled with the `:invalid` pseudo-class you've learned in the previous lesson.

Then I can assign this to you. Step 7 is fine as it is IMO.

**Comment by tylerbruno** [comment]
I can take care of it.
