### ISSUE TITLE
. Setting up Git: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Catangel007** [TheOdinProject/curriculum#27684]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Applications needed to run Git in my system are not available for download in my country Nigeria. what is the next cause of action?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

**Comment by henrylin03** [comment]
hi, at which step of the page are you getting stuck? In step 1, are you using PC, Mac or Chrome OS?

**Comment by Catangel007** [comment]
> hi, at which step of the page are you getting stuck? In step 1, are you using PC, Mac or Chrome OS?

resolved , Thank you.

**Comment by JoshDevHub** [comment]
Closing this since the OP marked it as resolved.
