### ISSUE TITLE
GEvent Manager: Fix google api installation

### ISSUE THREAD

**Issue by brazhnyknorman** [TheOdinProject/curriculum#27694]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

For the Project: Event Manager lesson, it states to install the google api client. This is deprecated, and instead if you want to install the civicinfo gem, you need to use $ gem install google-apis-civicinfo_v2 please update this

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-event-manager

### (Optional) Discord Name

brazhnyk

**Comment by JoshDevHub** [comment]
Related to #23552

**Comment by JoshDevHub** [comment]
Should be able to proceed with this work now that the project management stuff has been set up.

### Acceptance Criteria
- [ ] Have learners set up a Gemfile local to this project with the `google-apis-civicinfo_v2` listed.
- [ ] Change the command to run the program from `ruby lib/event_manager.rb` to `bundle exec ruby lib/event_manager.rb`. This will be necessary to have the civic info API gem picked up. This command will have to be updated in numerous places throughout the lesson.

I'll open this up for contributions. Please comment below to be assigned.

**Comment by PivtoranisV** [comment]
Hi guys, I can help with this
I recommend using [bundler](https://bundler.io/) to install gems. It is smart enough to check against the Ruby version requirement and find a set of gem releases that will satisfy the environment. Also, it will be a good practice to do this in such a way, as was described in the Project Management lesson

I think this command will be better to use:
``$ bundle install``
``$ bundle add google-apis-civicinfo_v2``

Please, let me know what do you think?
