### ISSUE TITLE
HashMap project: Fix typo in Step 1

### ISSUE THREAD

**Issue by j-mcQueen** [TheOdinProject/curriculum#27699]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a typo of "inaccurate" in step 1 of the HashMap project. Typo contains an extra "c".

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-hashmap

### (Optional) Discord Name

sidge

**Comment by MaoShizhong** [comment]
Thanks for raising this @j-mcQueen 
Since you did not check the assignment box, I'll open this up for contribution if anyone wants to comment to be assigned.

If you do wish to be assigned to this, let me know!

**Comment by Lalithkumarponnambalam** [comment]
Hello @MaoShizhong, as a new contributor, could you please assign this task to me?

**Comment by MaoShizhong** [comment]
Of course you can! Assigned you @Lalithkumarponnambalam

**Comment by Lalithkumarponnambalam** [comment]
Apologies, @MaoShizhong. Next time, I'll make sure to handle that properly. For upcoming tasks
