### ISSUE TITLE
CV Application Project: Provide project specification

### ISSUE THREAD

**Issue by thomasmcinnis** [TheOdinProject/curriculum#27701]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is no description of what a "CV Application" is in the introduction or the assignment steps.

(Admittedly I am an idiot, and didn't even know that online resume makers were a thing.)

Understanding the project requires venturing into community solutions, where submissions vary from full blown graphical page layout designers with font/color/styling editing, to what appear to be nothing more than forms which don't render anything resembling a CV to the page.

I propose adding a short list of requirements to prevent learners spending time on things which don't matter, and ensuring learning outcomes (working with state, deploying a react app) are kept in focus.

Eg:

```
- You will make an app where users can generate a CV
- The user can add personal information, contact details, education and work history, and references
- The app should display the results of the input information laid out like a CV
- Users should be able to add multiple education, work and reference items, re-order them and edit or delete them
- For inspiration, have a look at (add link to good example)
- After building your app, you will learn how to deploy your new React app with one of the providers below
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-cv-application

### (Optional) Discord Name

latch909

**Comment by MaoShizhong** [comment]
@thomasmcinnis Thanks for opening this issue.

I don't think we need to really expand on the project spec itself much at all, given what you've provided is pretty much what the spec already says, just via slightly different wording.
People can already get visual inspiration from looking at submitted live previews (which hasve always been perfectly fine to view before doing the project - it's only the code that's not sensible to view until after completion).

That being said, I wouldn't be opposed to the introductory paragraph being clearer on what a "CV application" is, especially for people in countries where resumes are more common and they may not have even heard of the term "CV".

Perhaps something like rewording the first paragraph from:
> Congratulations, you have made it to the very first React project. In this project, you will be creating a small CV application. It’s a great project to get you started because it includes many of the basic concepts you’ve learned so far, without a huge overhead of complexity.

to 

> Congratulations, you have made it to the very first React project. In this project, you will be creating a small application where users can input their information and generate a CV/résumé. It’s a great project to get you started because it includes many of the basic concepts you’ve learned so far, without a huge overhead of complexity.

How does something like that sound (exact wording not set in stone, just a suggestion)?

**Comment by thomasmcinnis** [comment]
@MaoShizhong that is definitely the 80:20 change that would get the job done.

(I was going to push back on references as the todo app project provides links to several actual todo apps, and I would argue that a todo app is something most people would have higher familiarity with. But looking for good examples of resume builder apps, they all highlight the customising of styling and design, which if anything would nudge people toward un-productive rabbit holes, so I can't suggest any good options for this.)

Happy to make a pr with your suggested wording, let me know.

**Comment by MaoShizhong** [comment]
@thomasmcinnis I'd be happy with the suggested wording for now. 

As for live examples (that aren't student previews), I agree - many would be for actual realistic use and so will have a lot of focus on visuals and design. Whereas this project is just the first of the React course where the focus is components and state, not much else. Visually it can be as simple and ugly as can be since style and layout (beyond the bare minimum) isn't vital.

I'll assign you for this

**Comment by MaoShizhong** [comment]
@thomasmcinnis Just checking in to see if you still wished to work on this?

**Comment by MaoShizhong** [comment]
@thomasmcinnis Is this still something you would like to work on?

**Comment by MaoShizhong** [comment]
Due to no response, I'll open this up for assignment.
The small [change to make is outlined in this comment](https://github.com/TheOdinProject/curriculum/issues/27701#issuecomment-2025256828).

Please comment if you would like to be assigned this.

**Comment by mathdebate09** [comment]
Hey @MaoShizhong, I can work on this, can you assign it to me?

**Comment by MaoShizhong** [comment]
Go for it @mathdebate09
