### ISSUE TITLE
Class Based Components: Page snaps to the bottom when the VM embed loads

### ISSUE THREAD

**Issue by RT44n** [TheOdinProject/curriculum#27702]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

When you load the lesson page, it initially loads you on the top of the page but as soon as the VM loads in, it snaps to the bottom to focus on the VM.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-class-based-components

**Comment by MaoShizhong** [comment]
Closing as this just seems like browser-specific behaviour (at least Firefox, and not on Chrome) and the codesandbox cookie banner, which we won't be able to do anything about.
