### ISSUE TITLE
Rails: Installing PostgreSQL: Broken section links

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#27705]
### Problem

In the Rails course's [Installing PostgreSQL lesson](https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql), some of the section links don't work properly. This behavior starts at the section "Creating a Rails application backed by PostgreSQL." You'll see that if you click on that heading, you'll be directed to the top of the page rather than to that section. Same for each of the headings below that one.

This occurs due to some of the codeblocks in this section throwing off our Markdown parsing that applies section ids. The two places this occurs:
- [1](https://github.com/TheOdinProject/curriculum/blob/main/ruby_on_rails/advanced_forms_and_activerecord/installing_psql.md?plain=1#L144-L146)
- [2](https://github.com/TheOdinProject/curriculum/blob/main/ruby_on_rails/advanced_forms_and_activerecord/installing_psql.md?plain=1#L266-L268)

### Solution

For the two aforementioned codeblocks, we need to remove the angle brackets surrounding `role_name` to get it to parse correctly.
```
# bad
<role_name>=#

# good
role_name=#
```

Comment below to be assigned.

**Comment by Ac394** [comment]
I'm up for it if you want!

**Comment by JoshDevHub** [comment]
Thank you for volunteering @Ac394 

I've assigned you. Let me know if you have any questions.

**Comment by Ac394** [comment]
I've submitted the PR, but I couldn't thoroughly test it with the Markdown preview tool since it doesn't display the section links.
