### ISSUE TITLE
Object Oriented Programming: <There are error link 3,4 in assginment>

### ISSUE THREAD

**Issue by loimaxto** [TheOdinProject/curriculum#27715]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

change it

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-object-oriented-programming

**Comment by JoshDevHub** [comment]
Hello @loimaxto, thank you for raising this issue.

Can you provide some more information about what it is that you're experiencing? I clicked through all the links in the assignment for that lesson, and none of them have any obvious issue or error.

**Comment by loimaxto** [comment]
Sorry for my bad at english , this is what happened when i clicked the link
of ruby-object oriented programming assignment . I am not sure why this
occured so I just reported it to let you know. sorry if i interrupted you.
[image: image.png]
[image: image.png]

**Comment by JoshDevHub** [comment]
@loimaxto Your English is fine, and you're not interrupting anything. No need to apologize :smiley: 

That said, I can't see your images when you send them through email. You'll need to visit this issue by navigating here in your web browser, where you'll then be able to attach images in a post.

Let me know if you have any other questions.

**Comment by loimaxto** [comment]
Thank you ! Here is the problem I have met:
![image](https://github.com/TheOdinProject/curriculum/assets/121563086/0b4a0420-99af-4026-9e70-05565beff325)
![image2](https://github.com/TheOdinProject/curriculum/assets/121563086/ddc478cb-2a75-4410-921e-3db7b98c3162)

**Comment by CouchofTomato** [comment]
Both of these links are working for me. I'll leave this issue open for now though to see if anyone else is experiencing an issue.

Where are you trying to connect from @loimaxto

**Comment by loimaxto** [comment]
I am connecting from Vietnam.

**Comment by BryanF1nes** [comment]
Both links are working for me as well. I tested from my internet here in the United States.

I also tested them using this site [geo-browse](https://geotargetly.com/geo-browse) to replicate as if I was in Vietnam and did not seem to have an issue either. Of course I'm not sure how reliable this actually is.

**Comment by anasamer056** [comment]
Medium is blocked in my country, Egypt, for some reason. I used to think that all Medium links are broken too. Perhaps you could try using a VPN, @loimaxto ?

**Comment by loimaxto** [comment]
I will try it, thanks!
