### ISSUE TITLE
Using git in the real world: convert step to a Note card and not an instruction

### ISSUE THREAD

**Issue by Mtendekuyokwa19** [TheOdinProject/curriculum#27722]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The  notification is placed as if it is a step but it is more of a note or something you hsould keep in mind so there is no need for numbering and the styling should be somewhat of a blockquote

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world#:~:text=Note%20that%20a%20git%20fetch%20upstream%20followed%20by%20a%20git%20merge%20upstream/some_branch%20is%20the%20EXACT%20same%20thing%20as%20doing%20a%20git%20pull%20upstream%20some_branch.%20We%20prefer%20to%20split%20it%20up%20here%20so%20that%20we%20can%20explicitly%20walk%20through%20the%20steps.

**Comment by MaoShizhong** [comment]
@Mtendekuyokwa19 Thanks for opening this issue. This makes sense and I agree would be more appropriate as a lesson note. It'd probably also be better placed at the end of that bit (before "sending your pull request") rather than sitting in the middle of the ordered list breaking up the flow. If it's placed at the end of that bit, the language would also need tweaking to use past tense e.g.
> We split it up here so that we could explicitly walk through the steps.

I'll assign this to you.

**Comment by Mtendekuyokwa19** [comment]
Sorry mao but i have a question.  should i simply fork the repo and then go to the markdown file for the lesson and make that tweak and then make a pull request. I do not know ruby and other langs used for the top website?

**Comment by MaoShizhong** [comment]
@Mtendekuyokwa19 Yep, everything for this will be kept to to the curriculum repo here.
Follow the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) to fork this repo and make changes to the appropriate lesson markdown file, then PR once you're happy with your changes.
You can test how your lesson would look by copying your markdown into the [Markdown preview tool](https://www.theodinproject.com/lessons/preview).

Once a maintainer (may not be me) has reviewed and approved, after we merge then the website should automatically update with the changes within a few minutes.

**Comment by Mtendekuyokwa19** [comment]
Ok thank you let me hop onto it
