### ISSUE TITLE
Clean Code: <Missing semicolon in code example A>

### ISSUE THREAD

**Issue by danieletie** [TheOdinProject/curriculum#27724]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the **what is clean code** lesson content, the second paragraph says 

> In the first example, single-letter variables are used, there is a semicolon in the middle of lines, and the indentation is inconsistent. The result is a piece of code that is confusing and messy.

referring to this piece of code

```
const x = function (z) {
  const w = "Hello ";
return w + z
};

x("John");

```

but there is no semicolon in the middle of any line.

What can be done? Reintroduce the semi colon or remove the  reference to a semicolon?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code

### (Optional) Discord Name

daniel.scrypt

**Comment by MaoShizhong** [comment]
Thanks for opening this issue, @danieletie.
The reference to the semicolon can be removed, as that's a carry over from an old example that was changed since it used arrays and array methods, something not actually taught by that point.

I'll assign this to you.

**Comment by danieletie** [comment]
Hello @MaoShizhong  

I just noticed that down the lesson, reference is made to the semicolon again. See here:

> Example B represents clean code. While you may not know what each part does, it’s much easier to guess what’s happening because the functions and variables are named clearly. The indentation follows a consistent and logical pattern, and there are no semicolons interrupting the code within a line.

Also, I think this part of the lesson, **camelCase** 

> camelCase is a naming convention that allows writing multiple words together without spaces or punctuation. In camelCase, when a variable name consists of multiple words like our setTimeout example, the first word is written completely in lowercase, while the second word (and any subsequent words) are capitalized.

is better worded as 

camelCase is a naming convention that allows writing multiple words together without spaces or punctuation. In camelCase, when a variable name consists of multiple words like our setTimeout example, the first word is written completely in lowercase, while the first letter of the second word (and any subsequent words) are capitalized.

Is it okay if I make this changes and make a pull request?
