### ISSUE TITLE
Setting up Git: <git init step needs to be added >

### ISSUE THREAD

**Issue by trigg78** [TheOdinProject/curriculum#27728]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I received fatal error: not a git repository. it seems i needed to run the git init command before i could associate my user email

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

**Comment by KevinMulhern** [comment]
Would you be happy for this one to be closed @MaoShizhong?

**Comment by MaoShizhong** [comment]
@KevinMulhern Yeah, no response from the issue author and seems to be a user error, so no further action from us. Thanks, Kevin!
