### ISSUE TITLE
Introduction to Frameworks:  Change to a descriptive link text

### ISSUE THREAD

**Issue by Crn0** [TheOdinProject/curriculum#27734]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

On the assignment section, number two to be exact.
I think we can make the links text more accessable by making it more descriptive, as it is using **this article** and **this description** as a text.
![IMG_20240402_103212](https://github.com/TheOdinProject/curriculum/assets/118383162/a45c45e8-1b9d-445a-84e7-dd715562ff3e)
We can change it to: Glance over RubyGarage's article about [technology stack for web application development](https://rubygarage.org/blog/technology-stack-for-web-development) or this documentation about [server-side web frameworks](https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Web_frameworks) from Mozilla’s website to understand some of the thought process that goes into picking a framework.

If you have another suggestion please let me know.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-to-frameworks

### (Optional) Discord Name

Crno

**Comment by MaoShizhong** [comment]
Thanks for opening this @Crn0.

This is something that will be handled in an upcoming epic, just like the Foundations one you contributed to (thank you again for that), which will span the entirety of the full stack JavaScript pathway. There are other links in that lesson which don't trigger the lint rule, but still need improving on the descriptive link text side of things.

**Comment by Crn0** [comment]
Thanks for letting me know, Mao! As i also saw some link text in the next lesson that needs to be change. And planned to open an issue on that too, i guess I don't need to open anymore as it will be handled.

Also, a question, regarding this issue as it will be handled on the upcoming epic, what will be the state of this? Will it be close or just left it open here while the maintainers are reviewing the draft.

**Comment by MaoShizhong** [comment]
Hmmm, I think even though the exact details of what gets changed to what may be altered, I know this will be addressed as part of that. So I'll close this issue, and you're of course more than welcome to comment to be assigned on the epic once it does leave draft.
