### ISSUE TITLE
Browser Compatibility: Additional Resources link is broken

### ISSUE THREAD

**Issue by catagonus** [TheOdinProject/curriculum#27730]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Additional resources link to article on "history of web browsers" is broken. Even going to the site, searching for the article, and clicking on their link to it doesn't work. I found an alternate link to the article on Medium https://taskade.medium.com/history-of-web-browsers-the-evolution-of-digital-productivity-%EF%B8%8F-28fa2d4130fb

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-browser-compatibility

**Comment by CouchofTomato** [comment]
Hey @SaurabhGurjar

I can see you created a solution for this but you haven't opened a PR back to our repo so we can review and merge. Are you planning on doing that?

**Comment by SaurabhGurjar** [comment]
Yes, I was waiting for a maintainer to comment on this issue so I could ask to fix this issue. But now the link is working, some has fix the issue.

**Comment by SaurabhGurjar** [comment]
Yes, I was waiting for a maintainer to comment on this issue so I could ask to fix this issue. But now the link is working, someone has fixed the issue.

**Comment by SaurabhGurjar** [comment]
Yes, I was waiting for a maintainer to comment on this issue so I could ask to fix this issue. But now the link is working, someone fixed the issue.

**Comment by MaoShizhong** [comment]
Closong as fixed in #27740
