### ISSUE TITLE
Intermediate HTML and CSS Course: Media Queries are brought up without any explanation in the "Advanced Grid Properties" Lesson

### ISSUE THREAD

**Issue by bharadr** [TheOdinProject/curriculum#27751]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the Intermediate HTML and CSS Course, in the Advanced Grid Properties lesson, if you go to the section titled

[auto-fit and auto-fill](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties#auto-fit-and-auto-fill) 

The lesson tries to demonstrate the value of auto-fit and auto-fill by comparing them to media queries two times.

"Solving this problem with media queries would be a lot of typing. Thankfully, auto-fit and auto-fill are here to save the day!"

and 
"Notice how when we resize, the columns automagically know how many will fit across without any media queries whatsoever. If you don’t think that’s cool, you better check your pulse!"

The tone of these comparisons makes it seem like we should very familiar with media queries by now as a concept. But I don't recall them ever being covered seriously in any previous lesson.

In fact, I went through the entire curriculum and found Media Queries only as a lesson in the Advanced HTML and CSS Course.

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-media-queries

Can we please either remove these references to media queries, or mention in the lesson that media queries are a topic that will be covered in a more advanced section? Right now, comparing auto-fit and auto-fill to media queries is confusing for students because they don't know what they are.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties

### (Optional) Discord Name

scheinwerfer

**Comment by MaoShizhong** [comment]
Thanks for opening this issue, @bharadr.

I agree, the current wording does make it seem like people should already be familiar with what media queries are. Probably the most effective resolution for this would be to just reword those little bits to not include any mentions of media queries at all.

Since you didn't check the assignment box, I'll open this up for contribution if someone wants to comment below to be assigned.

**Comment by BryanF1nes** [comment]
I can take this if no one else has requested to handle this.

**Comment by MaoShizhong** [comment]
Have at it, @BryanF1nes!

**Comment by BryanF1nes** [comment]
Just wanted to provide an update on this. I will be working on this issue this week, got a little distracted with some other PRs and kinda forgot I still had this assigned to me.
