### ISSUE TITLE
Copy/paste does not work properly on git\intermediate_git\working_with_remotes.md

### ISSUE THREAD

**Issue by robinzclark777** [TheOdinProject/curriculum#27768]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The code snippets on lines 20-40 have a "$" in the text.  When you copy the snippets into your terminal, the commands don't work because of the unneeded "$".

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-working-with-remotes

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @robinzclark777, a sensible change needed.
We do have a lint rule (that was implemented after this lesson was written) whereby the linter gets angry if you include the `$` in these sorts of situations for this very reason.

Assigning this to you.
