### ISSUE TITLE
Revisiting Rock Paper Scissors: <Screenshot is not loading>

### ISSUE THREAD

**Issue by RoaaK95** [TheOdinProject/curriculum#27766]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Screenshot of 'Dropdown menu of branches on Github is not loading'

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors

**Comment by MaoShizhong** [comment]
Thanks for opening this @RoaaK95.
On my end, all the images in the lesson are loading perfectly fine.
I would try refreshing the page, clearing the browser cache, trying the page in an incognito window or different browser, perhaps a different device/network connection even. Let us know how that goes.

But I can confirm that on several devices/browsers on my end, the images do load fine.

If push comes to shove, you can view the image directly in this repo at https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/revisiting_rock_paper_scissors/imgs/00.png

**Comment by RoaaK95** [comment]
It seems that the problem is from my end, I will try to solve it.
Thank you.

**Comment by MaoShizhong** [comment]
Awesome!
