### ISSUE TITLE
Installations: Update a link to an external resource within the OS installation section

### ISSUE THREAD

**Issue by dimakreminskyi** [TheOdinProject/curriculum#27777]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I noticed that a sentence in one of the lessons is using an incorrect link to an external resource (the screenshot provided).
The lesson: Foundations path → Foundations course → Installations lesson → OS Installation section → Virtual Machine toggle block → step 2.2.4
The sentence: Alternative instructions for enabling virtualization in BIOS/UEFI settings.
The supposed link: https://2nwiki.2n.cz/pages/viewpage.action?pageId=75202968.
Actual link: redirects to https://wiki.2n.com/.
![Screenshot (1105)](https://github.com/TheOdinProject/curriculum/assets/45992624/c14a2e3a-0a9e-4faa-bef3-769631ab1149)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations#os-installation

### (Optional) Discord Name

deemadev24

### (Optional) Additional Comments

This is my first bug report. I looked through all the suggested sections and rules for contributors and newbies (including open issues and open pull requests, nothing found with mentioned bug) and hope I don't break any rules. If so, please point me to the relevant docs so I can fix myself next time. Thank you.

**Comment by scheals** [comment]
I believe https://wiki.2n.com/faqac/en/virtualizace-vt-x-amd-v-povoleni-virtualizace-na-vasem-pocitaci-pro-spusteni-2n-access-commander-100572533.html would be the same link as used before.

**Comment by dimakreminskyi** [comment]
> I believe https://wiki.2n.com/faqac/en/virtualizace-vt-x-amd-v-povoleni-virtualizace-na-vasem-pocitaci-pro-spusteni-2n-access-commander-100572533.html would be the same link as used before.

Probably you are right. I'm new to the course and don't know what the previous link was. So I didn't provide it.

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @dimakreminskyi and thanks @scheals for finding a working link.

Since the assignment box wasn't checked, I'll open this up for contribution should anyone want to comment below and be assigned.

**Comment by MaoShizhong** [comment]
Assigned you, @kudamndau
