### ISSUE TITLE
Installing Rails: Lesson suggests it is independent of previous content

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#27782]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The lesson starts with:
> If you went through the [Ruby course](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby) you will have already installed Ruby. But if you haven’t done that, then now is the time to [install it](https://www.theodinproject.com/lessons/ruby-installing-ruby) as you will need Ruby installed before we tackle installing Rails.

This is unnecessary. Nobody who is going through the curriculum the intended way is going to end up in this lesson without Ruby installed. If someone wants to only use RoR content, they should be knowledgeable enough to know that "Ruby" in "Ruby on Rails" is something foundational for the framework.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-installing-rails

**Comment by MaoShizhong** [comment]
Makes perfect sense :ok_hand: Thanks as always, @scheals

**Comment by kudamndau** [comment]
I would be happy to help with this one if that's OK @MaoShizhong

**Comment by MaoShizhong** [comment]
@kudamndau Have at it. Just need those two sentences deleted.

**Comment by kudamndau** [comment]
Noted
