### ISSUE TITLE
Advanced HTML and CSS - Keyframes: Animate transform instead of width and height 

### ISSUE THREAD

**Issue by royalh23** [TheOdinProject/curriculum#27788]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I was doing the Keyframes lesson and realized that instead of using `transform` to `scale` the ball in the last example, `width` and `height` properties are animated instead. We've already been taught that animating any properties other than `transform` and `opacity` are expensive, and thus I think animating `width` and `height` in the lesson might confuse some learners. Here's the relevant code snippet:

```
@keyframes change-color {
  from {
    background-color: red;
  }
  
  50% {
    width: 200px; // use transform: scale(2) instead
    height: 200px;  
    background-color: blue;
  }

  to {
    background-color: green;
  }
}
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-keyframes

**Comment by KevinMulhern** [comment]
Thanks @royalh23, @TheOdinProject/html-css can we get you're input on this one please?

**Comment by MaoShizhong** [comment]
I think it makes sense to use a transform there instead.
Technically, `transform: scale(2)` is a little different in that it'll just scale the element itself, including border size, whereas animating the width/height will only change the space taken up by the element as a whole (regardless of box-sizing).

Don't think that's a differentiation that's important to include, and I can't think of many cases with that kind of animation where you'd purposely want to just change the width/height and not just scale the whole thing. Since the lesson says `we have also specified that the ball double in **size.**`, we should be fine to just replace the relevant code.

The codepen will need to be changed accordingly as well.

**Comment by royalh23** [comment]
> I think it makes sense to use a transform there instead.
> Technically, `transform: scale(2)` is a little different in that it'll just scale the element itself, including border size, whereas animating the width/height will only change the space taken up by the element as a whole (regardless of box-sizing).
> 
> Don't think that's a differentiation that's important to include, and I can't think of many cases with that kind of animation where you'd purposely want to just change the width/height and not just scale the whole thing. Since the lesson says `we have also specified that the ball double in **size.**`, we should be fine to just replace the relevant code.
> 
> The codepen will need to be changed accordingly as well.

How should I go about making the changes? Do I need to be assigned first?

**Comment by royalh23** [comment]
@MaoShizhong @KevinMulhern  I want to make a PR but don't know how I'm supposed to change the codepen. Would appreciate some guidance

**Comment by MaoShizhong** [comment]
Going to assign you @royalh23. I think changing the height/width adjustment to simply `transform: scale(2);` makes much more sense here (esp. since we've already covered transforms).

We will handle the codepen on our side so both parts are changed at roughly the same time.

**Comment by royalh23** [comment]
@MaoShizhong Gotcha. Will make a PR tomorrow
