### ISSUE TITLE
Linting: Lesson lists plugins/tutorials for unsupported text editors

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#27781]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The lesson contrary to the overall curriculum philosophy lists plugins and tutorials for text editors that are not VSC, even for the EOL Atom.

At minimum, the reference to Atom should be removed. 

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-linting

**Comment by MaoShizhong** [comment]
This is something that's planned as part of a descriptive links epic for the Node pathway coming soon, but while that's being finalised still, I'll open this one for individual contribution and perhaps it'll get completed before the descriptive links thing for that part.

In https://github.com/TheOdinProject/curriculum/blob/main/javascript/javascript_in_the_real_world/linting.md?plain=1 : 
```markdown
1. Far more useful are linting plugins for your favorite text editor. Most editor plugins allow you to automatically lint your code as you are writing it, and will show the errors right in the editor, which makes resolving them *much* simpler. We can't cover *every* editor installation but some of the more popular are:
   1. Visual Studio Code - [The Plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and [a tutorial](https://www.digitalocean.com/community/tutorials/linting-and-formatting-with-eslint-in-vs-code).
   1. Sublime Text - [The Plugin](https://github.com/roadhump/SublimeLinter-eslint) and [a tutorial](http://jonathancreamer.com/setup-eslint-with-es6-in-sublime-text/).
   1. Atom - [The Plugin](https://atom.io/packages/linter-eslint) and [a tutorial](https://medium.freecodecamp.org/how-to-set-up-eslint-in-atom-to-contribute-to-freecodecamp-3467dee86e2c).
   1. Vim - [Use the ALE plugin](https://github.com/dense-analysis/ale). If you use Vim you already know what you're getting into. ALE is a great plugin, but the setup and configuration can be a little tricky.
```
needs to be turned into just
```markdown
1. There is an [ESLint extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) which can lint your files as you write, without you needing to rerun the `eslint` command every time. If your project also contains an ESLint configuration file, the extension will automatically use those rules for that project. Here is a [tutorial on using the ESLint extension in Visual Studio Code](https://www.digitalocean.com/community/tutorials/linting-and-formatting-with-eslint-in-vs-code).
```

So replacing the parent bullet and removing the nested ordered list.
Opening this up for contribution if anyone wishes to comment to be assigned.

**Comment by yuliana-r** [comment]
Happy to help with this @MaoShizhong

**Comment by MaoShizhong** [comment]
Assigned @yuliana-r
