### ISSUE TITLE
Setting Up A React Environment: YouTube video no longer available

### ISSUE THREAD

**Issue by Gohan61** [TheOdinProject/curriculum#27799]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The YouTube video under 'Additional resources': [Vite React App with EsLint & Prettier in VSCode (2023)](https://www.youtube.com/watch?v=SMbqi1HPprc) is now private and no longer available.
![Eslint-prettier-vite-video](https://github.com/TheOdinProject/curriculum/assets/90203619/8717961a-8377-421f-a219-7efc57845720)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

### (Optional) Discord Name

gokhan.reads

### (Optional) Additional Comments

I found this article [https://medium.com/@nedopaka/setup-a-react-vite-project-with-prettier-vitest-2024-12e291669b4b](url) but I am not sure if it is a good replacement and would like someone to give feedback if it would be a good replacement.

**Comment by KevinMulhern** [comment]
Thanks for reporting @Gohan61. 

Does anybody know of any good alternatives?

**Comment by JoshDevHub** [comment]
Your replacement article may be good, just maybe with a note that you don't have to dig into vitest? It would be nice to replace this with a text resource in my opinion.

Gonna tag the JS team for other thoughts @TheOdinProject/javascript

**Comment by Gohan61** [comment]
I found this article posted 5 days ago which seems to cover it without the unnecessary .

[https://dev.to/topeogunleye/building-a-modern-react-app-with-vite-eslint-and-prettier-in-vscode-13fj](url)

**Comment by JoshDevHub** [comment]
I should've tagged the React team in my earlier post :upside_down_face:

Thanks for linking that 2nd article. I'll ping the @TheOdinProject/react team to get their thoughts on it.

**Comment by MaoShizhong** [comment]
That article has an error with the initial command `mkdir vs cd rvs npm init -y` and I think it'd look a bit messy adding a correction note in our additional resource.

However, I'm not even sure we need that additional resource in the first place.
The vite app creation command in the lesson and docs ship with ESLint by default.
The only extra you'd need to do is install Prettier as well, which many (though not all) would already be using.
The instructions for installing Prettier and configuring it with eslint via `eslint-config-prettier` are identical to the way things are done via the Linting lesson.

So I'm not actually sure the AR is needed given it provides nothing new that isn't already covered in the lesson. So I'm actually in favour of just axing that AR.

**Comment by MaoShizhong** [comment]
@Gohan61 I'll assign you to remove that additional resource. Given the above, there isn't really a need for it anyway so a replacement isn't necessary in my honest opinion.
