### ISSUE TITLE
Introduction: What is NodeJS?: Event loop video already in JavaScript course

### ISSUE THREAD

**Issue by kyledinardi** [TheOdinProject/curriculum#27798]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The "What the heck is the event loop anyway?" video is already listed in the assignments of the "Asynchronous Code" lesson in the JavaScript course. I'd suggest removing it from one of the lessons' assignments.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-introduction-what-is-nodejs

**Comment by KevinMulhern** [comment]
Thanks for reporting @kyledinardi 

@TheOdinProject/javascript do you think its worth repeating this resource here or could it be 🪓 'd?

**Comment by kyledinardi** [comment]
On second thought I'm not sure. It IS relevant to both lessons and they are separated by quite a bit of content. Maybe it'd be best to just acknowledge that it was in the previous lesson with a lead-in such as "If you missed it in the JavaScript course, ".

**Comment by MaoShizhong** [comment]
I *really* like that video and feel it really should be repeated given both how helpful it is for the Node section, as well as the amount of time that would likely have passed between the async JS lesson and the Node section. IMO it's just that good of a talk.

I'd definitely be in favour of amending the verbiage for that assignment step to something along the lines of a reminder, like "You may remember [video title](link to video) from an earlier part of the course ...", and to drive home how valuable that video is for understanding the event loop.

**Comment by mohammednumaan** [comment]
@MaoShizhong @kyledinardi I have a suggestion. We could instead re-write that sentence (*What is the Node Event Loop?*) to something like :

```
This video was previously linked in the lessons. Take your time and watch it again. It's a good refresher on how the Node event loop operates.
```

is this a good idea?

**Comment by mathdebate09** [comment]
Hey @CouchofTomato, I'd love to take this issue up, can I just have your opinion if it'd be useful to refer previous lesson like
- What is the Node Event Loop? You may remember [Event Loop at JSConf](https://youtu.be/8aGhZQkoFbQ?si=6NfUEoi0w8B9h1lp) from an earlier lesson in Javascript section about [Asynchrounous Code](https://www.theodinproject.com/lessons/javascript-asynchronous-code#assignment)... don't skip it!
-or-
- What is the Node Event Loop? You may remember this [fantastic video](https://youtu.be/8aGhZQkoFbQ?si=6NfUEoi0w8B9h1lp) from an earlier part of the course... don't skip it!

**Comment by MaoShizhong** [comment]
@mathdebate09 A bit of both. The first option is better and has sufficiently accessible link text, but I don't think we need to specifically mention and link to the Async lesson itself. We can just say "earlier part of the course" for that bit.

**Comment by mathdebate09** [comment]
@MaoShizhong agreed, mentioning the whole thing makes it absurdly long
