### ISSUE TITLE
Join the Odin Community: Problem with verify phone number on discord

### ISSUE THREAD

**Issue by loimaxto** [TheOdinProject/curriculum#27795]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I can't verify my phone number to ask questions on Discord. When ask for support staff of discord this is their reply:
![image](https://github.com/TheOdinProject/curriculum/assets/121563086/0c952103-2224-439a-8b51-317d290d77ad)
I had tried with some numbers too but it didn't work.( ALL of them are real number that have already registered )
Is there anyways else to start chatting in our community? ( or can you turn off verify phone in order to chat?)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community

### (Optional) Discord Name

loimaxto

**Comment by scheals** [comment]
Send a DM to ModMail account and you'll be able to converse with the moderation team to potentially grant you an exception. IIRC Discord doesn't accept some of the phone carriers and for sure doesn't like various services that provide phone numbers that are not your usual big carriers.

**Comment by fabulousgk** [comment]
This is unfortunate, Discord is very strict about these phone numbers.  I am not sure what our Maintainers and Mods ...and there you go

**Comment by JustWaveThings** [comment]
@loimaxto - you can use this form to make your request:  https://docs.google.com/forms/d/e/1FAIpQLSdaOofk3-3yXisP-xlOVUweuGKBxFRcOJalza9Q45IlRbZ5ig/viewform

**Comment by MaoShizhong** [comment]
Closing this issue as it's a Discord concern as opposed to a repo-related concern.
But thanks for raising the issue @loimaxto - the form above that Fred linked will be the best way to go.
