### ISSUE TITLE
Battleship: Clarify Ship Implementation Options in Gameboard Task

### ISSUE THREAD

**Issue by Looch8** [TheOdinProject/curriculum#27806]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the task description for implementing the Gameboard class/factory, there's a discrepancy regarding the supported implementation options for the Ship class/factory. While initially, we mention that the Ship class/factory can be either a class or a factory function, the subsequent task only references the factory function option.

To ensure clarity and consistency, I recommend we update the task description to explicitly state that the Gameboard class/factory should support both class-based and factory function-based Ship objects.

<img width="557" alt="Screenshot 2024-04-17 at 7 58 50 PM" src="https://github.com/TheOdinProject/curriculum/assets/101569600/98c6279b-8213-4aa4-807f-a384c8d0a3fb">
<img width="564" alt="Screenshot 2024-04-17 at 7 58 57 PM" src="https://github.com/TheOdinProject/curriculum/assets/101569600/fe0fe9d0-67e8-4926-b728-12e7c4d3530f">

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

**Comment by MaoShizhong** [comment]
Good catch on that oversight - assigned you @Looch8
