### ISSUE TITLE
Foundations: Add new `Effective Learning Techniques` section, move learning techniques content to it, and collaborate to add more content

### ISSUE THREAD

**Issue by Leo-U** [TheOdinProject/curriculum#27803]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

#### Introduction
First things first – since, IMO, this issue has been apparent for a while, I imagine that other people already have some ideas and would want to work on it.  I did go through the open issues with the `content:Foundations` label, and I didn't see a relevant open issue, but there are 94 open issues in totaI. I apologize if I missed a relevant one. If this issue gets approved, I think it should be a significant collaborative effort, so that no one's strong ideas are left out. @bycdiaz, if I remember correctly, in Discord you once said that you have a background in education. I'd appreciate any insights or thoughts you have on this thread.

#### Proposal
Why don't we move all the 'non-motivational' content – all of the study methods – from the [Motivation and Mindset](https://www.theodinproject.com/lessons/foundations-motivation-and-mindset) lesson to a new section right after the Prerequisites section, title it something like 'Effective Learning Techniques', and also add additional content while we're at it. There's an entire science of determining the best ways that we monkeys learn, so there's no way we can't add more. A lesson for each technique, maybe.

#### Suggestion for Additional Content
Some YouTube videos by a [Dr. Justin Sung](https://www.youtube.com/@JustinSung) have caught my attention recently:

His 2 part video series:
1. [Ultimate Study Technique Tier List (Learning Coach Edition)](https://www.youtube.com/watch?v=WkjVaMDheJ4)
2. [How I UPGRADE the Most Popular Study Techniques](https://www.youtube.com/watch?v=YyMA9RwAcGE)

And this one: [My Most POWERFUL Study Trick (Any Subject)](https://www.youtube.com/watch?v=UY2GO1ML-Bo)

In that last one, if you start playing [here](https://youtu.be/UY2GO1ML-Bo?t=965), watch where he says 'if you're not doing interleaving' – he laughs. It's not the main topic of his video, but clearly interleaving is important. I did a google search, and found [this document that defines it](https://www.med.uvm.edu/docs/interleavingb88a77f025ec4640b3e92d87e25fe5d9/active_learning/the_science_of_learning-interleaving.pdf?sfvrsn=b0663169_0).

#### Interleaving as a Way to Avoid Rabbit Holes

Now that I more clearly understand what interleaving is, I think that the 'mass practice' described in the aforementioned document might be exactly what I've been doing. My strategy has frequently consisted of sitting down for hours, days, or longer, and trying to read coding documentation. I have spent days on a single documentation webpage. No diversification of content – I've just been brute forcing it, one block at a time. I will continue to brute force it unless I actually change my technique. And there's no way I'm alone.

That's why I think that the content that discusses rabbit holes should transition to more content that discuses the principle of interleaving and why it's so important. Another technique might be more appropriate, but I haven't learned about many yet. But in my opinion at the moment, it seems clear that interleaving is an actionable and effective technique to avoid rabbitholing, if you define rabbitholing as 'spending too much time on one thing'.

#### What Other Techniques Should Be Added

There's a wealth of material on Dr. Sung's channel, so there's a lot of topics that that could be added to The Odin Project, but just off the top of my head, something about 'active recall', otherwise known as the [testing effect](https://en.wikipedia.org/wiki/Testing_effect), is intriguing.

It would be necessary to determine which techniques to include and which should not. Some might be more optimal for traditional education, although personally, I'd tend to lean more towards 'what works for them must work for us'.

#### Asking Permission To Use The Videos

If we're going to use those videos, I'm thinking we should ask his permission. He might even be willing to do some kind of limited collaboration or feedback if he has a few minutes to spare. It wouldn't necessarily be wasting his time. He has a class that helps students around the world learn how to learn called iCanStudy and also has a Discord channel. Linking his content and discord channel might attract Odin Project students to his classes. I'd be willing to try and contact him or someone in his organization to at least get his permission to use the videos, if I'm given the go ahead.

#### Conclusion

I'd just to reiterate and clarify that as long as this issue gets addressed, I don't care that much about the nitty gritty implementation details. I'd **definitely** like to contribute significantly – I enjoy writing and like to think I'm pretty decent at it. If no one else wants to write content, then I'll gladly handle that end of things. But I understand that everyone has their own ideas and plans that are likely already in motion, and that anyone who helps create the content will have kind of a rubber duck/Feynman technique opportunity by doing so, which is another reason why more extensive collaboration is a plus for all involved.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-motivation-and-mindset

### (Optional) Discord Name

leo_jj

**Comment by JoshDevHub** [comment]
Thank you for making this issue.

Gonna ping our @TheOdinProject/foundations team to get opinions on these additions.

**Comment by Leo-U** [comment]
> Thank you for making this issue.
> 
> Gonna ping our @TheOdinProject/foundations team to get opinions on these additions.

Thank you. Just some additional info -- I'm having doubts about the extent of my suggestions. The content might be entirely sufficient right now. I never actually read the Motivation and Mindset lesson until recently, which is probably a big part of why my learning technique is so terrible. That flow chart looks like it could be extremely useful. So the actual content might be entirely sufficient.

I still like idea of separating out the learning techniques though into a separate lesson or section though. Maybe the other suggestions are still valid too. I'll await your guys' advice.

**Comment by MaoShizhong** [comment]
Personally, I think the original proposal specifically is a little much. That's coming from a an angle of "we're a web dev curriculum first and foremost, not a course aimed at teaching you the science and research backing up specific learning techniques". As in, if it would be valuable to make readers aware of certain things, it'd be to become aware of the techniques *as suggestions*, as opposed to diving into the science behind those techniques.

Also if we put ourselves in the shoes of a learner starting the curriculum, you'd need to find a balance between being made aware of valuable information, and overloading with stuff that's just too much at that point for us as new learners.

Frankly, a lot of learners just won't care (for better or for worse) and will want to get started with programming stuff, not read additional lessons on the details behind multiple different learning techniques that honestly just take time and experience to figure out for yourself. IMO, if someone's sincere about their learning, they'd likely come across and try different learning techniques at some point in their journey.

Perhaps there could be a little restructuring of that lesson to make it easier to digest and provide additional valuable information (I think some of the paragraphs can have line breaks added for easier reading). But I'm not sure the extent of a whole new large section/lessons on learning techniques is appropriate for a web dev curriculum, as opposed to an education-studies curriculum or something like that.

If a few individual resources/topics are missing from the lesson and would provide significant value being inserted, I'd definitely support that.

**Comment by Leo-U** [comment]
@MaoShizhong

I agree. How about something like this as a minimal addition? A simple image that shows blocked and interleaved practice side by side. Not necessarily this one, but one like it.
![85666780-b447-45cd-983e-6255ad44971f](https://github.com/TheOdinProject/curriculum/assets/47509535/187ae954-aa66-497d-9802-4ed0c7fd6444)

I feel like with a better image and description than I'm providing now, it could be very intuitively clear why the interleaving is superior.

For example, if I have a test in a week, it makes more sense to immediately cover all topics on the first day, and again on the next days, rather than try and spread out the topics across the week in blocks. So there seems to be a kind of timing advantage that's clearly apparent. I think even without there being a deadline or test, the principle applies.

Also there's the psychological benefit of not doing the same thing.

I feel like the principle is related to how TOP gives you reading assignments from multiple sources. Attacking a problem from multiple angles.

**Comment by MaoShizhong** [comment]
I feel that might be something that can easily be interpreted as taking the curriculum in a non-linear order. The curriculum is designed to be a followed linearly, and to narrow your focus to the road TOP takes you down. While I get where you're coming from with the interleaving specifically, I think a more practical issue people face is misaligned expectations of how well you need to "understand" things before moving on/facing projects etc.

A common problem we face is people believing they're expected to know how to solve projects from memory when they get  to them, i.e. treating projects as tests of knowledge, instead of playgrounds to get practical experience (where understanding *actually* starts to occur). That's why they often spend hours trying to memorise documentation, seeking every resource under the sun to make sure they "master" the topic before approaching the projects, writing their own documentation for revision purposes like preparing for an exam etc.

Instead, people start to improve leaps and bounds when they realise that's not the expectation, and that awareness of concepts as per the lessons is sufficient to approach projects to practise (and start learning) those concepts and techniques. Fully aware and accepting they will forget some things, will continue to struggle but have their focus in a better and more manageable position.

And I'm not sure we need to dive into interleaving or similar for that, especially when I feel it's easy for people to think they *should* jump around and do this lesson now, that lesson in a bit, come back to the project amd doing lessons ahead etc.

Bear in mind this is just my personal opinion, so I'm interested in the opinions of others on the team.

**Comment by Leo-U** [comment]
Fair enough, the prescribed lesson order is likely best.

However, if I understand it correctly, the principle doesn't have to apply to topics. Activities count as well.

So like, a basic example would be doing coding and docs reading today, rather than just reading docs. Enhances learning.

**Comment by Leo-U** [comment]
Fair enough. Apologies for overlooking the lesson content before writing the issue.

If I could narrow it to a single suggestion, it would be the idea of separating out the 'learning to learn' content from the motivational content, on the basis that a lesson title should fully describe the contents of the lesson. That'd mean creating an additional lesson or modifying the title.

**Comment by MaoShizhong** [comment]
Nothing to apologise for!

I feel like the "mindset" part of the title can include the "learning to learn" concepts, and I'm wondering if instead of extracting out to a completely separate lesson, if you perhaps might have an idea for an improvement to the lesson title?

I say that primarily because I think for what we want to go for, the current lesson structure and contents is mostly fine as it is, and I'm sure we really *need* a separate lesson.

@TheOdinProject/maintainers Any thoughts on this?

**Comment by Leo-U** [comment]
> if you perhaps might have an idea for an improvement to the lesson title?

Motivation, Mindset, and Learning Strategies, or any other title that explicitly conveys the content.

**Comment by thatblindgeye** [comment]
I wouldn't be opposed to updating the lesson title, but something to keep in mind is that we do tell users that the curriculum is meant to be taken in order, without skipping. If a user skips a lesson then that will be on them. Likewise if a user opts to not complete newly added lessons.

That said, if in this case it's less that a new lesson was added, but new content was added to an existing lesson, it may not be clear whether that new content is significant or not if the lesson title itself doesn't change. So a user may not know to even revisit such a lesson (even if the lesson's completion state was reset; that isn't inherently indicative that new content was added to the lesson, just that *something* caused the completion state to reset).

**Comment by MaoShizhong** [comment]
Given the above, we're happy enough with the current title and don't feel it vital that it be changed with the scope of the proposed problem. Some lessons include a little more than the title explicitly describes, and we make clear that lessons should be taken in order without skipping so if someone does that, that's on them. And making db changes from the website repo could confuse learners with a change badge that doesn't signify any meaningful content edit.

**Comment by Leo-U** [comment]
Ah no problem. Didn't realize multiple maintainers didn't approve of the title change. Sorry for leaving this issue open for so long.
