### ISSUE TITLE
Getting Started: Introduction to npm already in last lesson

### ISSUE THREAD

**Issue by kyledinardi** [TheOdinProject/curriculum#27821]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The "Introduction: What is NodeJS?" lesson assignment 4 says to read the Node.js "Getting Started" section up to the TypeScript module. This section of the website already includes the "An introduction to the npm package manager" module. I'd suggest removing it form the assignments of TOP's Node.js "Getting Started" lesson.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-getting-started

**Comment by JoshDevHub** [comment]
That seems reasonable to me. And since you indicated you'd like to work on this, I'll assign you.

Let us know if you have any questions.
