### ISSUE TITLE
Object Basics: Filter Method section references nonexistent code

### ISSUE THREAD

**Issue by txfgh** [TheOdinProject/curriculum#27839]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The Foundations course's Object Basics lesson has a section about the Filter Method:
https://www.theodinproject.com/lessons/foundations-object-basics#the-filter-method
The section repeatedly references a function called isOdd which is not present in the code as an anonymous function is used instead.
The two paragraphs above the code make it sound like isOdd is being discussed as if it theoretically exists, while the text below the code is confusing to read as it references isOdd as though it should be present in the code sample but isn't.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-object-basics

**Comment by MaoShizhong** [comment]
Thanks @txfgh for opening this issue. Looks like the intention was to have the code example have an `isOdd` function defined separately, then passed into `.filter` as the callback argument (similarly to how the `.map` example starts with a separately defined function. But then when the example was written, there was just an oversight where the person writing it used an arrow function defined inline instead.

Opening this up for contribution if someone wants to comment to be assigned.

**Comment by Crn0** [comment]
Hello, Mao o/. I would like to be assigned to this issue.

**Comment by MaoShizhong** [comment]
All yours @Crn0!
