### ISSUE TITLE
Common Data Structures and Algorithms: Dead link in knowledge check

### ISSUE THREAD

**Issue by DavAnders** [TheOdinProject/curriculum#27840]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a dead link that redirects to an irrelevant site in the Knowledge Check section.
"What are the enqueue and dequeue properties?" linking to http://blog.thefirehoseproject.com/posts/what-is-an-algorithm/ looks like it is not hosted anymore.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-common-data-structures-and-algorithms

**Comment by Siriuszx** [comment]
Hey there @DavAnders! If you ever need a resource and you can't progress any further without it, you can use [this website](https://web.archive.org/) as well 🙂

**Comment by wise-king-sullyman** [comment]
@DavAnders thanks for putting up this issue!

@Siriuszx I've went ahead and assigned you since I see you have a PR up for this. We really appreciate your initiative, but in the future please request to be assigned on an issue before putting a PR up.

**Comment by Siriuszx** [comment]
@wise-king-sullyman oh, sorry my bad

**Comment by wise-king-sullyman** [comment]
@Siriuszx no need to apologize for volunteering your time!

I just don't want to see you potentially putting time into a PR in the future just for us to have to close it because someone else got assigned to the issue 🙂
