### ISSUE TITLE
Foundations:Links and Images add deep dive videos into noopener and noreferrer

### ISSUE THREAD

**Issue by ahammednibras8** [TheOdinProject/curriculum#27849]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In this lesson talking about 'rel' attribute of "a" tag (`<a href="link to a website" target="_blank" rel=noopener noreferrer">This is a link<a>`) on this topic we can add a video of youtube (https://youtu.be/wWzlN096DvA?si=vLcTAF5-O7e8YG_z and https://youtu.be/4Cnp-q54Ulo?si=oxo76_PxGL2kk_Ld) This two video will be helpful for the students.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

### (Optional) Discord Name

ahammednibras

### (Optional) Additional Comments

It is also helped me then i think it will also help others.Thank you for your time.

**Comment by wise-king-sullyman** [comment]
Thanks for making this issue!

Do these videos cover material we aren't already covering in our current content? If so what are the additional items being covered?

**Comment by carlosfrontend** [comment]
Hello guys, how are you?
It would be a pleasure for me to work on this.

**Comment by MaoShizhong** [comment]
Closing since our content already covers what should be sufficient for the topic, and no further response from the issue author.
