### ISSUE TITLE
Fetching Data In React: Check loading before check error

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#27844]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the examples in this lesson, the loading is set to false when the fetch resolves, successfully or not, which is fine:
```jsx
// ....
.catch((error) => setError(error))
.finally(() => setLoading(false));
```
And then later on, when deciding what JSX to return, error is tested before loading:
```jsx
if (error) return <p>A network error was encountered</p>;
if (loading) return <p>Loading...</p>;
// ...
```
To me this is backwards. While it doesn't make any visible difference in this case, (since if error would be set, loading is also set to false at the same time), I would suggest that the loading flag should be checked first. There may be some example where you have a fetching implementation that attempts two or three times before rejecting, and in that case you would want the loading "curtains" to stay up while your code attempts to resolve errors in the background, that you wouldn't want to show just yet. 
An error needn't always signify the end of loading. While the end of loading should always show an error if that's the result.

The reasoning goes something like:
- are we still attempting to load? 
  - Yes, then show loading. 
  - No, then show the result (good or bad).
  

I suggest those two lines have their order swapped, unless there's a good reason why its been done this way

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react

**Comment by MaoShizhong** [comment]
It's a small nit but I agree with the logic and personally check loading first too.

**Comment by damon314159** [comment]
Tiny nits today prevent bugs later :P
