### ISSUE TITLE
Function Basics: Extend note on not doing the MDN exercises to the second exercise bullet point

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#27861]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In #24895 there was a warning added to the first exercise against doing the MDN exercises, as they involve knowledge TOP hasn't touched at that point. Someone recently pointed out the second exercise article also links to those, and while I think most learners will understand the bullet point to apply to both, I don't think there's any harm in making that explicit

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-function-basics

### (Optional) Discord Name

asarta

### (Optional) Additional Comments

Probably a good first issue

**Comment by wise-king-sullyman** [comment]
Agree, thanks!

**Comment by yuliana-r** [comment]
Happy to help with this if there's no takers!

**Comment by MaoShizhong** [comment]
Assigned, @yuliana-r!

**Comment by yuliana-r** [comment]
Sorry about the delay on this - I figured it might look a bit better to have a single note covering both articles but if needed, happy to redo and add the note to both individually instead
