### ISSUE TITLE
Update Lesson: Authentication Basics

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27871]
## Lesson overview

Update the current [Authentication Basics lesson](https://www.theodinproject.com/lessons/nodejs-authentication-basics) to align with Node Revamp

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Replace MongoDB/Mongoose instructions with equivalent PostgreSQL/node-postgres instructions
- Replace `connect-mongo` for storing sessions with [`connect-pg-simple`](https://www.npmjs.com/package/connect-pg-simple)

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by fcasibu** [comment]
Hi, I would like to work on this one ✋
