### ISSUE TITLE
Update Lesson: Deployment

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27870]
## Lesson overview

Update the current [NodeJS deployment lesson](https://www.theodinproject.com/lessons/nodejs-deployment) to align with Node Revamp

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Remove mentions of MongoDB
- Add a note somewhere that learners can keep their server instance and database instance on one PaaS or use separate PaaS's to reduce hosting costs
- Add database hosting services in the PaaS list like [Koyeb](https://www.koyeb.com/docs/databases) and [Neon](https://neon.tech/) 

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by BryanF1nes** [comment]
Put me in coach!
