### ISSUE TITLE
Deployment: Outdated Fly.io Information

### ISSUE THREAD

**Issue by DevlinRocha** [TheOdinProject/curriculum#27895]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

>Fly.io: Free Plan
> - You can host three apps for free before you need to start paying.
> - Requires a credit card.
> - Fly.io waives monthly invoices that total less than $5 USD. So, although it may look like you are being charged, it’s very unlikely that you will exceed $5 and actually have to pay.

The Fly.io free plan has been sunset as the "Legacy Hobby Plan" and replaced with the "Hobby Plan" which gives a free $5 credit once to start and and no longer offers a monthly $5 credit, similar to other "free plan" offerings from other PaaS.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-deployment

### (Optional) Discord Name

DevlinRocha

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @DevlinRocha 
Honestly, when Fly.io switched to their current pricing plans, things really weren't clear and I remember the support forums full of questions, as well as team members "clarifying" and somehow making the situation more confusing.

Looks like their docs have actually been updated with the current system with more clarity! So now, similar to Railway, new accounts are given a one-time $5 grant that will only start being used up for usage that exceeds the free allowance. Once the credit is gone, you'll be put onto the standard $5/mo plan.
Nice and simple (but unfortunate that it's more restricted than before...)

**Comment by Eduardo06sp** [comment]
@MaoShizhong doesn't Fly.io still have a free allowance (< $5/month gets waived)?

> Resources included for free on all plans:
>
>   * Up to 3 shared-cpu-1x 256mb VMs
>   * 3GB persistent volume storage (total)
>   * 160GB outbound data transfer 
>
> Additional resources are billed at the usage-based pricing detailed below.

https://fly.io/docs/about/pricing/#free-allowances

From their help forum:
> We shipped a change a few months ago to waive invoices under $5.

https://community.fly.io/t/questions-on-100-billing-discount/11133/5

I don't use Fly.io so I can't confirm anything, but it seems like our small projects should come out to be free.

**Comment by MaoShizhong** [comment]
@Eduardo06sp That help forum post was from March 2023 when the legacy free plan was still in place. Earlier this year, they scrapped what used to be the free tier - now called the "legacy hobby plan" which is still available to existing users who were already on it, but new accounts are automatically put on their new free trial, where you get $5 credit that will only start to be used once you exceed the free resource allowance.
Once the $5 is up, you must switch to one of the paid plans (the $5/mo Hobby plan being the default switch). A little bit above the free allowance section of the docs has more detail about the current system.

<https://community.fly.io/t/free-plan-clarification/18661/7>

**Comment by MaoShizhong** [comment]
@DevlinRocha Just a courtesy check in to see if this is still something you wish to work on?

**Comment by DevlinRocha** [comment]
My apologies, @MaoShizhong! I can get started on this now and should have a PR up soon. I did have a quick question -- with the new context of Fly.io no longer offering a true free plan, is it still what The Odin Project recommends?

> [If you need help deciding which one to use, we recommend Fly.io.](https://github.com/TheOdinProject/curriculum/blob/main/nodeJS/express_and_mongoose/deployment.md?plain=1#L244C160-L244C224)

**Comment by MaoShizhong** [comment]
No worries, genuinely no rush - all of us are volunteers here, so it's just a courtesy check in.

About the recommendation, hmmm. I believe that recommendation is primarily a "if you still can't make a choice", but in previous projects where we've offered choices for things (e.g. deploying React front end only), we've gone with "any is fine".

I think personally at least, I'd probably prefer for it to say something more like

> Any of the free options will work for curriculum purposes, so it doesn't matter which you pick for these.
