### ISSUE TITLE
JavaScript: Update place ship instruction 

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/curriculum#27890]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Here is the current direction within the project:
> Gameboards should be able to place ships at specific coordinates by calling the ship factory or class.

I think this could be reworded, as some people may think that this means the ship object must have a place() method. But instead the only thing you really need to do is have the ship object somewhere within the gameboard array. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

### (Optional) Discord Name

mfraryay

### (Optional) Additional Comments

We <3 open source! First issue in a while here :shoc

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @Baguirre03.
Do you happen to have any links/examples of where this caused a problem for people?
It's not one I've particularly noticed being a pain point, and my initial read would be that calling the factory or class would construct a new Ship object, where then the gameboard placement would (?) seem intuitive.

But of course, if this has been an actual pain point then we can definitely look to address the wording.

**Comment by Baguirre03** [comment]
It happened only a couple of times where i have seen it be a little confusing for people in the discord! Im okay with keeping it how it is though :salute: 

Maybe a simple rewording?
 > Gameboards should have a `placeShip` function which calls the `Ship` factory or class and places it at specific coordinates

**Comment by MaoShizhong** [comment]
What do you think about the following?

> Gameboards should have a `placeShip` function that creates a new `Ship` object, and places it at the specified coordinates.

**Comment by Baguirre03** [comment]
bueno 👍

**Comment by MaoShizhong** [comment]
Assigned @Baguirre03

**Comment by Baguirre03** [comment]
We can just drop @MaoShizhong
