### ISSUE TITLE
Express 102: CRUD and MVC: <Short description of your suggestion>

### ISSUE THREAD

**Issue by connectGBI** [TheOdinProject/curriculum#27898]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Your link 
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoosee

doesn't work. This does

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

Looks like you have an extra e at the end there 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-express-102-crud-and-mvc

**Comment by MaoShizhong** [comment]
Thanks for bringing this up @connectGBI, that's my mistake missing the typo in a recent PR.

**Comment by damon314159** [comment]
Happy to fix it
