### ISSUE TITLE
Foundations[Arrays and Loops] : Map/Filter/Reduce before they are taught.

### ISSUE THREAD

**Issue by gabriel-05-dev** [TheOdinProject/curriculum#27905]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Foundations Course -> Javascript Basics -> Arrays and Loops/Object Basics

- What was the problem?

As a complete beginner to JS, i had a hard time understanding what map/filter/reduce does and encountered task 11 and 12 on the Arrays and Loops lesson  before learning them. I also looked it up and other users felt the same way about these exercises. 

I find that it is hard to understand how reduce/map/filter work without referring to a really good guide, such as the object basic lesson. 

- What do i propose?

Moving the object basics lesson or taking some of the content from that lesson, and putting it before the javascript excersise in the arrays and loops section.

- What will this help?

This will help users understand how to loop through objects in arrays and help to make learning a bit faster and more efficiently.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-arrays-and-loops

### (Optional) Discord Name

gsxr600_cc

**Comment by gingkapls** [comment]
The linked lesson only asks you to do exercises 1-7 though, none of which require you to use any of map/filter/reduce.

**Comment by MaoShizhong** [comment]
Best me to it @gingkapls 

Thanks for opening this issue @gabriel-05-dev. What gingkapla said is correct - the lesson you linked only instructs to do exercises 1-7, none of which require the methods you mentioned (even the ones that can be solved with them, AFAIK the TOP solutions do not use them for this exactly reason). You are only tasked to do exercises 8-12 in the Object Basics lesson, which is where you do learn about those methods.
