### ISSUE TITLE
New Lesson: Environment Variables

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27907]
## Lesson overview

What and why env vars && using `dotenv`. This new lesson will be placed before the new Express section. The [security configuration lesson](https://www.theodinproject.com/lessons/nodejs-security-configuration) will be removed as a result.

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- What are environment variables and why they're useful && env vars live in Node's `process.env`
- Mention that we can manually populate `process.env` using the `export` cli command
- Mention there's a better way with the `dotenv` package
- Give a simple code example of installing & using `dotenv`

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by MaoShizhong** [comment]
I'm happy to take this one. Whereabouts in the lesson order are you thinking this should be placed? Given that the Intro to Express was written with the assumption that environment variables have already been taught (though this can be amended accordingly).

**Comment by Baguirre03** [comment]
Oops. If youre too busy could I take this one Mao :) Would love your feedback on it though!

**Comment by MaoShizhong** [comment]
No worries at all, wasn't actually aware of the prior Discord discussion! All yours and looking forward to it! :tada:

**Comment by 01zulfi** [comment]
@MaoShizhong I totally forgot about the env var mention in the Intro to Express lesson, good callout.

The env var lesson would be pretty much independent from any surrounding lessons, we could place it before the Express section altogether (updated the issue description accordingly).

**Comment by MaoShizhong** [comment]
Yeah, prior the the Express section probably makes most sense given it's a general Node thing :+1: One step further in the milestone! :tada:

**Comment by Baguirre03** [comment]
To-Do: today!

**Comment by MaoShizhong** [comment]
Assignee changed on request
