### ISSUE TITLE
Motivation and Mindset: Rephrase part about typing speed from additional resources

### ISSUE THREAD

**Issue by gingkapls** [TheOdinProject/curriculum#27919]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The third bullet in the additional resources introduces resources to increase typing speed if the learners are interested.

While trying to improve typing speed is not bad by itself, learners at this point may not be able to accurately judge whether or not their typing speed will hold them back during development.
It also goes against the conventional advice of not worrying about typing speed as the time spent thinking will be a bigger bottleneck.

The part introduces confusion in my opinion, and should be removed.

Alternatively, we could preface it by saying something along the lines of
> "Your typing speed will not be the bottleneck during development, even in a professional environment, but if you are still interested in improving your speed, you can look into the following resources"

to reiterate the fact that they don't necessarily _need_ to improve their typing speed.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-motivation-and-mindset#additional-resources

### (Optional) Discord Name

ginned

**Comment by aceus0** [comment]
Personally I find the current language perfectly fine. 

First its in additional resources which is always "optional", second it "If you find your typing speed is holding you back", which lets the learners gauge for themselves. 

To your point about typing speed not being a bottleneck, I think generally it won't, but there are certainly cases where it could be (technical interviews, coding assessments, etc).

**Comment by ryanleslie1997** [comment]
I think the advice about improving your typing speed is actually quite important. Improving your typing speed is only going to help in my opinion. I don't see any reason for this to be removed.

**Comment by MaoShizhong** [comment]
I personally don't feel too strongly about the current wording of that AR, especially because like others mentioned, it's an AR and not an assignment or otherwise in the main lesson contents. Don't think it needs to be removed. It's a fun little thing people like to improve on and getting more familiar with a keyboard just in general can help you use it better when programming, so it's not bad at all.

That being said, I wouldn't be opposed to a little "softening" of the wording to mention the real bottleneck, such as (suggestion only):
> While thinking and research time is a bigger bottleneck than raw typing speed, if you'd like to practice your typing skills then some excellent options include [typing.com](https://www.typing.com/), [TypingClub.com](https://www.typingclub.com/) and [Monkeytype](https://monkeytype.com/).

If you're happy to make this sort of change @gingkapls then I can assign this to you.

**Comment by gingkapls** [comment]
Yeah, after seeing the responses I think it has a greater benefit than I had assumed, and that it has a place in the lesson.

I still believe that we could use a little change in the wording, and if you feel so too I'd be glad to work on it.

**Comment by MaoShizhong** [comment]
Go for it @gingkapls
