### ISSUE TITLE
Websockets and Actioncable: Add "dartsass-rails" install to ActionCable walkthrough lesson

### ISSUE THREAD

**Issue by kjester15** [TheOdinProject/curriculum#27917]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the following ActionCable walkthrough [https://github.com/TheOdinProject/curriculum/blob/main/ruby_on_rails/mailers_advanced_topics/actioncable_lesson.md](url), we're instructed to install bulma-rails, then update our application.css file extension to application.scss.  

Doing so results in the following error: "LoadError (cannot load such file -- sassc):". Upon checking the bulma-rails documentation, it's suggested to run "rails tmp:clear and restarting the server" when getting that error, which did not fix the issue. I noticed steps 2 and 3 of the installation process are as follows:

Run ./bin/bundle add dartsass-rails
Run ./bin/rails dartsass:install

These steps are both left out of the above walkthrough. After installing, my app worked as intended.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-websockets-and-actioncable

### (Optional) Discord Name

kjester

**Comment by JoshDevHub** [comment]
Thank you for making this issue! @kjester15 

This is definitely a problem. Since you indicated you'd like to work on this, I've assigned you. Let me know if you have any questions.
