### ISSUE TITLE
New Project: File uploader site

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27926]
## Project overview

File uploader site project for learners to practice Prisma ORM.

## Project outline

The following items define the scope of the project. The project outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

-  

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the project template using the following command (replace `project_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/project-template.md 
```

**Comment by cmedina-dev** [comment]
@01zulfi I can work on this one, assuming it's still open?
