### ISSUE TITLE
New Lesson: Prisma ORM

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/curriculum#27925]
## Lesson overview

Lesson on what are ORMs and introduce Prisma.

## Lesson outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Explain the challenges that learners might face when using raw sql in their codebase. these include:
    - altering a table after that table has been populated with data is a hassle
    - there's no place inside the codebase that sufficiently describes tables, columns, and their data types. you have to login into the db to get that data
- Introduce the concept of ORMs to the learners: it can solve all of the above and more!
- Introduce Prisma and why we've chosen to cover it in the curriculum
- Mention that Prisma has A LOT of features but we'll only be using a small subset of features available:
    - Prisma Schema definition: explain what a Schema is with an example. Additionally, mention this is the Model part of MVC architecture
    - Querying with Prisma client: learners can use the prisma library to query the DB; it has handy functions for common operations like filtering & sorting. Mention that Prisma allows raw queries as well in case the learner needs it
    - Basic of migration: explain what a migration is and a small description on how Prisma handles it (i.e. creates a `migration` folder to track 'em)
- Link Prisma's getting started guide. Tell learners this guide has almost everything they'll need for the upcoming projects. Link Prisma's data migration guide in case they need to run migration on existing data. Encourage learners to explore the documentation.

## Acceptance criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get the lesson template

Download the lesson template using the following command (replace `lesson_name` with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

**Comment by fcasibu** [comment]
hi, would like to work on this!
