### ISSUE TITLE
Express 102: CRUD and MVC: Freecodecamp link not working

### ISSUE THREAD

**Issue by SirGram** [TheOdinProject/curriculum#27934]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

[Freecodecamp ](https://www.freecodecamp.org/news/simplified-explanation-to-mvc-5d307796df300)link mvc explanation is missing

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-express-102-crud-and-mvc

**Comment by Asartea** [comment]
Seems to be now located at https://www.freecodecamp.org/news/simplified-explanation-to-mvc-5d307796df30/ (dropping the last 0)
