### ISSUE TITLE
Function Basics: Link Expired

### ISSUE THREAD

**Issue by Dev-Siwach** [TheOdinProject/curriculum#27937]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

link for the 'JavaScript Call Stack' lesson is changed.
This is the link in TOP website - 'https://www.javascripttutorial.net/javascript-call-stack/'
This is the actual link to the page - 'https://www.javascripttutorial.net/javascript-tutorial/javascript-callback/'

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-function-basics

### (Optional) Discord Name

kalla_billa

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @Dev-Siwach. I have been unable to replicate this issue on my end with multiple machines and browsers.

The Function Basics lesson's assignment 5 - https://www.javascripttutorial.net/javascript-call-stack/ - is fully accessible on my end
![image](https://github.com/TheOdinProject/curriculum/assets/122839503/58ae66af-8fe5-475f-a0f4-8798a0e2e848)

Meanwhile, the new link you've shared - https://www.javascripttutorial.net/javascript-tutorial/javascript-callback/ - links to a different page on a different topic entirely (callbacks vs call stacks).

**Comment by MaoShizhong** [comment]
Closing as the current link in the lesson is working as of this comment. Unable to replicate issue.
