### ISSUE TITLE
Problem Solving: incorrect description of the 'for' loop condition

### ISSUE THREAD

**Issue by RabbitHole26** [TheOdinProject/curriculum#27930]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hello,

It seems like the description of the *for* loop doesn't align with the code. In the code snippet *i* is **less or equal** *answer*, while the description states: 

'We want to loop until *i* is **greater** than answer.'

![for-loop-description](https://github.com/TheOdinProject/curriculum/assets/138439310/b2a3e0fb-85d0-417f-9620-a8263a725066)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-problem-solving

**Comment by MaoShizhong** [comment]
Thanks for opening this issue, @RabbitHole26.

The code and text are both correct. The middle part of a `for` loop determines the condition that's checked, where if `true`, the loop continues and if `false`, the loop stops.

So `i <= answer` means "keep looping if `i` is less than or equal to `answer`", which means the same thing as "loop until `i` is greater than `answer`"

**Comment by RabbitHole26** [comment]
You are totally right, I apologize for raising this issue.

**Comment by MaoShizhong** [comment]
No worries at all, definitely nothing to apologise for! It's always good to raise what you believe is an issue just in case. Glad it's been clarified now!
