### ISSUE TITLE
The Box Model: Small QOL improvment 

### ISSUE THREAD

**Issue by RemanthManyam** [TheOdinProject/curriculum#27947]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

(It's not an issue..a small qol improvement kinda thing). 
The definitions of padding, margin, border are in that order but in the img explaining them, they are in padding, border, margin order(which looks like correct  order coz padding < border < margin i think).
Problem: When i moved on to next lectures my mind confused border and margin exchaning their funtion ..lol
Solution: The defintions should be in order: padding, border, margin

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-box-model

### (Optional) Additional Comments

It's not a big deal...thing is in defintions they are in one order and image they are in different order so mind confuses them

**Comment by MaoShizhong** [comment]
Thanks for opening the issue @RemanthManyam.

While I don't think there's actually any real problem with the current order vs image, I do think it makes sense to introduce the 3 parts in the `p -> b -> m` order, given that's the order they come in from the content box outwards. I'll assign you for this little change.

**Comment by MaoShizhong** [comment]
@RemanthManyam We have a [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) with all the information you'll need there.
Given you're still early in the curriculum and may not be as comfortable with Git yet, and that this is a fairly simple change to be made to a single lesson file (just swapping the order of the padding/margin/border list and the paragraph above it (I think those are the only bits that would need changing around), you can do so via the `Improve on Github` link at the bottom of the lesson page on the website itself.

As you get a little more experience with Git through the upcoming projects, for future PRs, you may wish to do things locally as per that contributing guide.

**Comment by MaoShizhong** [comment]
Just so you know, the issue gets left open. You've done your PR correctly where you've filled the form and set the "Closes" keyword to link to this issue, meaning once any maintainer approves and merges that PR, it will trigger this issue to close as completed.
Until that point, or a maintainer manually closes the issue for whatever reason, it stays open while the PR's up.
