### ISSUE TITLE
HashMap Project: Missing option for factory function in HashSet

### ISSUE THREAD

**Issue by shamblonaut** [TheOdinProject/curriculum#27942]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

As opposed to the norm followed till that point, the instruction for creating a hash set only references classes (I assume this was just forgotten to add).

Exhibit (under **Extra Credit** in the Assignment section):
> - Create a class `HashSet` that behaves the same as a `HashMap` but only contains `keys` with no `values`.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-hashmap

### (Optional) Discord Name

Shamblonaut

**Comment by MaoShizhong** [comment]
Go for it @shamblonaut
