### ISSUE TITLE
Testing Practice: Clarification on caeser cipher.

### ISSUE THREAD

**Issue by dvs-codes** [TheOdinProject/curriculum#27968]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the caeser cipher function, it is not clear whether we have to test considering punctuations or not ? if yes then in which way ? for example, in alphabet and numbers we shift in order eg. for factor 2 'a' becomes 'c' but if we have do it for let's say the period ('.') which way does it go ?
![image](https://github.com/TheOdinProject/curriculum/assets/132570673/a3dc2de3-b1ba-4fde-8080-31c4464c261e)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-testing-practice

### (Optional) Discord Name

DVS-CODES

**Comment by dvs-codes** [comment]
yeah I think we should make it little clear, we should provide a clearcut
example too so that it's understood properly ? eg. Ab,C.De ==> Bc,D.Ef (for
factor 1, punctuations remain as it is.)

**Comment by CouchofTomato** [comment]
Thanks. You haven't indicated you want to work on this issue so I'm opening it up for others.

**Comment by CouchofTomato** [comment]
@catbree Sure. Thanks for taking this on. It's all yours.
