### ISSUE TITLE
Objects and Object Constructors: Typo - missing word

### ISSUE THREAD

**Issue by Yagrr** [TheOdinProject/curriculum#27979]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a typo in "The Prototype" section. 
Number 2 on the list the sentence reads: 
"Is the function part of the player1’s prototype" 

when it should be, as referred throughout the list:
"Is the `.valueOf ` function part of the player1’s prototype" 

![typo](https://github.com/TheOdinProject/curriculum/assets/90156764/c9fef45e-6ccc-47ef-bdfd-82d7f1060d45)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

**Comment by CouchofTomato** [comment]
Hi @Yagrr 

The function name is implied from point 1 so doesn't need to be explictly named in point 2.
