### ISSUE TITLE
Using Git in the Real World: Fix step 5 in "Ongoing workflow"

### ISSUE THREAD

**Issue by T0nci** [TheOdinProject/curriculum#27976]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

A lesson is misreferenced in step 5 in "Ongoing workflow". The learner doesn't encounter how to fix merge conflicts until the next lesson - "Working with Remotes" in the Assignment section.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world

**Comment by MaoShizhong** [comment]
Good spot - assigning you to fix the link and text :rocket:
