### ISSUE TITLE
Rock Paper Scissors: ambiguous instruction on step 5

### ISSUE THREAD

**Issue by sukairaida** [TheOdinProject/curriculum#27988]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

On the step 5 of the project assignment the third instruction says "Make your function’s `humanSelection` parameter case-insensitive so that players can input “rock”, “ROCK”, “RocK”, or other variations." but in the previous (second) instruction that parameter was defined as `humanChoice`.

![image](https://github.com/TheOdinProject/curriculum/assets/169105926/7fcd6c9b-f729-4648-aa0b-ec6506c37d4b)

Shouldn't the third instruction refer to "humanChoice" since that is the parameter that we defined in the `playRound` function? 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-rock-paper-scissors

**Comment by MaoShizhong** [comment]
Good catch, you're right - that step should refer to `humanChoice`, as that's the name of the defined parameter.
I'll assign you to this :rocket:
