### ISSUE TITLE
HashMap Data Structure: Paragraph about overwriting values seems misplaced

### ISSUE THREAD

**Issue by gingkapls** [TheOdinProject/curriculum#27982]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the [heading on buckets](https://www.theodinproject.com/lessons/javascript-hashmap-data-structure#buckets) there is a paragraph that talks about overwriting values if the same item already exists in the hash table (with the same key and value).

> What if we found the hash code, but also the key value is the same as what we already have in the bucket? We check if it’s the same item by comparing the keys, then we overwrite the value with our new value. This is how we can only have unique values inside a Set. A Set is similar to a hash map but the key difference (pun intended) is that a Set will have nodes with only keys and no values.

This paragraph comes right after the part that talks about retrieving values from the hashmap.

The paragraph is more relevant to the preceding part which talks about inserting values into the hashmap.

As it stands now, it's easy to mistake overwriting being a part of the retrieval function.

I think it would help with the flow of the section if we moved it to the part which talks about inserting values into the hashmap with some changes to the verbiage.

[The section right now](https://www.theodinproject.com/lessons/preview?uuid=9b388379-156a-4b62-8bd2-d8c8714ba35b)

[Section with proposed changes](https://www.theodinproject.com/lessons/preview?uuid=6fd1e7c3-63a2-46bb-88b8-b361b63a762e)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-hashmap-data-structure

### (Optional) Discord Name

ginned

**Comment by CouchofTomato** [comment]
Hey @JoshDevHub 

Do you want to give your opinion on this one?

**Comment by JoshDevHub** [comment]
Related to: #27174

I think the suggested changes are fairly good though, and I'd probably accept a PR for this.

One tweak I'd recommend is right here:
> Now if we wanted to get a value using a key:
>
> 1. Put each entry inside a bucket as a `Node` item, which holds both the key and the value.
> 1. To retrieve the value, we hash the key and calculate its bucket number.

I think it's better to remove the first item in the list here. The `get` method for a hash map does nothing with setting up data -- it retrieves data that already exists.

Since you indicated you'd like to work on this, I'll assign you @gingkapls 

Let me know if what I wrote above doesn't make sense or if you have any other questions.
