### ISSUE TITLE
Etch-a-Sketch: Grammer in Challenge text

### ISSUE THREAD

**Issue by ryanleslie1997** [TheOdinProject/curriculum#28004]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Small grammar error in the following text:

 **The objective is to achieve a completely black square only ten interactions.**
(The text is in the challenge section under point 2)

There should be a 'in' or 'with' added between 'square' and 'only'.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-etch-a-sketch

### (Optional) Discord Name

rleslie97

**Comment by ryanleslie1997** [comment]
I think this would be a good first issue.

**Comment by MaoShizhong** [comment]
Thanks @ryanleslie1997 - opening this up to be assigned

**Comment by sukairaida** [comment]
I would like to be assigned to this if possible.

**Comment by MaoShizhong** [comment]
Go for it @sukairaida
