### ISSUE TITLE
Ruby: Update instructions to install 3.3.0

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#28016]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

3.3.0 is stable enough for us to use it with the curriculum, and we're already using it on the TOP site itself.

### Acceptance Criteria
- [ ] In the [ruby installation lesson](https://www.theodinproject.com/lessons/ruby-installing-ruby), tell learners to install 3.3.0 instead of 3.2.2
- [ ] Throughout the ruby course, documentation links need to be changed to point to the docs for version 3.3. You can find where these links are by running `grep -rnH "docs.ruby-lang.org/en/3.2/"`. Each of these links should change to have `/en/3.3` in the parameters.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

**Comment by nicholschm** [comment]
I was preparing to submit an issue for this, and if deemed necessary I am able to submit a Pull Request updating the curriculum files if I am assigned.

**Comment by JoshDevHub** [comment]
Thank you for volunteering @nicholschm :raised_hands: 

I'll assign you to work on a Pull Request for this. Let me know if you have any questions or anything.
