### ISSUE TITLE
Classes: First two links under 'Knowledge Check' refer to the same article.

### ISSUE THREAD

**Issue by Speerstra** [TheOdinProject/curriculum#28015]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

update the second link to the correct article

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-classes

**Comment by CouchofTomato** [comment]
Thanks for reporting this @Speerstra

**Comment by sukairaida** [comment]
That article does have an image explaining the differences between classes in Java and JavaScript, would it be enough to update the link so it leads to that specific section? like: https://rajaraodv.medium.com/is-class-in-es6-the-new-bad-part-6c4e6fe1ee65#e6b3 or would it be better to look for a different article?

**Comment by Speerstra** [comment]
Hi Sukairaida,

Either sounds good to me. As a third option, 'Ruby' could be removed from
the link text.

**Comment by sukairaida** [comment]
I don't see Ruby being mentioned in any of the articles so it would be a good idea to just leave 'Java' in the lesson and to update the link to be more specific. I can do this if you want @CouchofTomato

**Comment by CouchofTomato** [comment]
@sukairaida All yours
