### ISSUE TITLE
Installing Rails: Update Instructions for Installing Yarn on Ubuntu

### ISSUE THREAD

**Issue by nicholschm** [TheOdinProject/curriculum#28022]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The lesson for installing Rails contains a section dedicated to installing Yarn. This section provides a link to the Yarn Download page, and recommends to users that it should be installed through npm. I had issues on Ubuntu when setting up a local clone of the Web App Repo at this step. After progressing through the [Running The Odin Project Locally](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#install-javascript-modules) guide I noticed there was a note with a link for Ubuntu users to install Yarn [Linuxize](https://linuxize.com/post/how-to-install-yarn-on-ubuntu-18-04/). This link is also outdated, there is an article with updated instructions for newer versions of Ubuntu [Updated Link](https://linuxize.com/post/how-to-install-yarn-on-ubuntu-20-04/) from the same source.

I am proposing updating the Installing Rails lesson to include the contents of the note found in the Running The Odin Project Locally guide, and updating the link to account for newer versions of Ubuntu. I would gladly submit a Pull Request with those changes if assigned.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-installing-rails#step-12-install-yarn

**Comment by JoshDevHub** [comment]
@nicholschm Thank you for making this issue.

I'm wondering a bit more about your specific issues with installing yarn via npm? What was the exact problem with doing this? Did you have issues getting `npm` itself installed?

**Comment by nicholschm** [comment]
Hello Josh,

Regrettably I did not screenshot the exact error message I received at the time, however I did take notes regarding any errors I encountered in the installation processes. There seemed to be a conflict with cmdtest and Yarn, which required using `$ sudo apt remove cmdtest` prior to installing yarn. I searched through the RTOPL guide and came across the included note for Ubuntu users further on, and was able to utilize the directions from the included link to straighten the issue out.

As another test, I just installed a fresh copy of Ubuntu to attempt to recreate the errors, and attempted to install Yarn via npm. The install worked with some minor adjustments:

1) npm not installed, installed using `$ sudo apt npm install`
![Screenshot from 2024-05-21 15-53-44](https://github.com/TheOdinProject/curriculum/assets/77590673/bfac1053-3d46-464f-a8f3-1fe0f767a44e)

2) File access issue when running `$ npm install --global yarn`
![Screenshot from 2024-05-21 15-56-01](https://github.com/TheOdinProject/curriculum/assets/77590673/de1b40f5-0733-4da7-a8c9-e116826cc355)

3) Issue can be corrected using sudo to install
![Screenshot from 2024-05-21 15-57-33](https://github.com/TheOdinProject/curriculum/assets/77590673/f5d6968b-3073-4f84-956e-a9892a9b3430)

I did not encounter the same conflict with cmdtest on this iteration, so unfortunately I could not recreate it for you. I would still propose including the note specifically related to installing Yarn on Ubuntu, which avoids utilizing npm and installs directly from the Yarn repository without any adjustments or additional installations required, however that would be entirely at your discretion. 

Thank you for responding, I am a CS student looking to contribute in any way I can to improving the project.

**Comment by JoshDevHub** [comment]
Ah okay. I would definitely *not* install npm through `apt`. This is likely the result of any problems you've had while setting this up.

A better way would be to install a version manager for NodeJS. The TOP curriculum walks through installing `nvm` (or node version manager) in [this foundations course lesson](https://www.theodinproject.com/lessons/foundations-installing-node-js). By the time a learner makes it to the Rails course, it's assumed they will have already done that and therefore isn't mentioned anywhere.

To me, the best way forward on this would be to change the main site's wiki to reference the lesson for installing Node in the event that someone is setting up TOP locally without having done that installation.

Unfortunately I believe the wiki is read-only for contributors, so that change will have to be handled on our end.

> Thank you for responding, I am a CS student looking to contribute in any way I can to improving the project.

That's awesome! Glad to have new contributors.

**Comment by MaoShizhong** [comment]
@JoshDevHub https://discord.com/channels/505093832157691914/505093832157691916/1242804726303686676 Regarding the lesson's intention to install Yarn Classic, is the team aware of/planning anything regarding Classic's EOL as per https://classic.yarnpkg.com/en/docs/install#windows-stable?

**Comment by JoshDevHub** [comment]
@MaoShizhong I don't think there are any plans, and I'm not even sure yarn classic has a concrete EOL date?

The TOP main site is still using classic, so I figure we'll update the curriculum instructions to modern whenever that gets changed.

**Comment by nicholschm** [comment]
> Ah okay. I would definitely _not_ install npm through `apt`. This is likely the result of any problems you've had while setting this up.
> 
> A better way would be to install a version manager for NodeJS. The TOP curriculum walks through installing `nvm` (or node version manager) in [this foundations course lesson](https://www.theodinproject.com/lessons/foundations-installing-node-js). By the time a learner makes it to the Rails course, it's assumed they will have already done that and therefore isn't mentioned anywhere.
> 
> To me, the best way forward on this would be to change the main site's wiki to reference the lesson for installing Node in the event that someone is setting up TOP locally without having done that installation.
> 
> Unfortunately I believe the wiki is read-only for contributors, so that change will have to be handled on our end.

@JoshDevHub I understand, and I agree with you that referencing a Node installation would help resolve that issue. I have not completed the curriculum yet, I went directly to the Contributing Guides looking to get the web app running locally and seeing if there were any gaps in the directions I could help improve as a new user. I am new to Ubuntu as well, so I thought this would be a good usability test as someone without prior experience with the project. 

Also, I noticed this option when browsing the Wiki page:
![image](https://github.com/TheOdinProject/curriculum/assets/77590673/c3e42348-b5ca-4956-b023-1e451c759143)

When clicking Open an issue I am redirected to submitting an issue for the Web App repo. I intended to open a separate issue for something minor on a Wiki page, so if that is the preferred method for submitting issues related to the Wiki I will go through theodinproject repo's issue submission. 

Thank you again for your help and guidance!

**Comment by JoshDevHub** [comment]
I've updated the wiki to make sure people have installed node before proceeding with the yarn installation stuff. I'll be closing this issue as completed. Thanks for alerting us to this problem.

> When clicking Open an issue I am redirected to submitting an issue for the Web App repo. I intended to open a separate issue for something minor on a Wiki page, so if that is the preferred method for submitting issues related to the Wiki I will go through theodinproject repo's issue submission.

Yeah if you noticed a different problem with the wiki, you can absolutely raise an issue on the web app repo.
