### ISSUE TITLE
Ruby on Rails: Final project links to paperclip-cloudinary which relies on the deprecated paperclip gem

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/curriculum#28026]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Under the additional resources section of the final project, TOP reads:
> For an alternative to using AWS S3 for image storage take a look at this [cloudinary](https://github.com/GoGoCarl/paperclip-cloudinary)

The link takes you to the `paperclip-cloudinary` gem, which relies on the deprecated [paperclip](https://github.com/thoughtbot/paperclip) gem.

I can't confidently make a suggestion, but there seems to be an official gem from Cloudinary's docs:
https://cloudinary.com/documentation/rails_integration
I took a quick skim, and it seems like it would require installing the `cloudinary` gem and just setting it up.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-rails-final-project#additional-resources

### (Optional) Discord Name

Eduardo06sp

**Comment by JoshDevHub** [comment]
Thanks for making this issue @Eduardo06sp 

I think it's sufficient just to update the link to direct to cloudinary's docs. At this stage (ie. very late in the curriculum), we're generally wanting people to read docs with very little direction.

Opening this up for contributions. Comment below if you want to work on it. As it's just a link update, should be a good issue for any first time contributors.

**Comment by carlosfrontend** [comment]
Hello guys!,  I'm on the "Using Git in the Real World" lesson. If it is simply replacing one link with another, I would be happy to be assigned this task as my first task. Greetings!

**Comment by CouchofTomato** [comment]
@carlosfrontend All yours

**Comment by carlosfrontend** [comment]
Thanks @CouchofTomato , I will do it

**Comment by carlosfrontend** [comment]
I updated it in this [PR](https://github.com/TheOdinProject/curriculum/pull/28034)

**Comment by carlosfrontend** [comment]
Thanks at you for merged it @JoshDevHub 👍
