### ISSUE TITLE
Working with External APIs: Add Mention of OmniAuth Via Devise

### ISSUE THREAD

**Issue by kjester15** [TheOdinProject/curriculum#28033]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Under the section "Implementing OAuth 2.0 in Rails – Use OmniAuth!" in the "Working with External APIs" lesson of the rails course, I think it would be beneficial to mention that devise offers omniauth integration. 

The end of the section also says this - "We’ll leave it to the projects to walk through using Omniauth since it’s much easier to learn by doing than reading a bunch of bullet points." - but I don't believe there is any walkthrough in any of the remaining projects until the final project, when you're tasked with doing it yourself. I would suggest either removing that bit, or adding an actual walkthrough to one of the projects in order to practice it. I think it could be helpful, but probably isn't entirely necessary.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-working-with-external-apis

### (Optional) Discord Name

kjester

**Comment by JoshDevHub** [comment]
Thank you for making this issue @kjester15 

I agree with both of your points and will assign you to work on it.

### Acceptance Criteria
- [ ] Mention that devise has OAuth integration (maybe link to their [wiki page on it](https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview)?)
- [ ] Remove mention of the "walk through" in future projects

Let me know if you have any questions.
