### ISSUE TITLE
Factory Functions and the Module Pattern: The link for additional resource to the interactive scrim on factory functions should be changed

### ISSUE THREAD

**Issue by Barister** [TheOdinProject/curriculum#28031]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The link is broken as i inderstood. 
[interactive scrim on factory functions](https://scrimba.com/scrim/c2aaKzcV).
The app doesn't work on this page because they changed the project.
I suppose the right link now - https://v1.scrimba.com/scrim/c2aaKzcV

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern

**Comment by CouchofTomato** [comment]
Thanks for picking this up. Opening this up for help

**Comment by sukairaida** [comment]
I can take this if no one else is interested

**Comment by MaoShizhong** [comment]
@sukairaida all yours
