### ISSUE TITLE
JavaScript Course: Adding note about template literals on import statements

### ISSUE THREAD

**Issue by aceus0** [TheOdinProject/curriculum#28049]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

[ES6 Modules](https://www.theodinproject.com/lessons/node-path-javascript-es6-modules#es6-modules-finally)

As someone who uses template literals ```(`)``` more than I problably should, I attempted to write my first import statement using them, which left me trying to figure out why I couldn't run ```npx webpack``` sucessfully.

That said, i'd like to add a little note box, perhaps like the one on [the Factory Functions lesson,](https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#the-module-pattern-iifes) that mentions that template literals can't be used for import/export statements, and to stick to quote or double quote for import/export.

Lessons in Foundation don't inform that template literals have things they can't do over other string declarations, in fact the [MDN doc](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings#single_quotes_double_quotes_and_backticks) that first introduces them only lists that they are better than other string declarations. But that might be for another day.

For now I'd like to add a small note about them in the ES6 Modules Lesson. I'd be happy to work on it.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-es6-modules

### (Optional) Discord Name

aceus_

### (Optional) Additional Comments

First Issue and possible first contribution!

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @aceus0.
The [MDN docs for `import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#module-name) do state that you can only use single or double quotes for the module name (i.e. no template literals). I'm not opposed to a quick note in the current lesson though reinforcing that, perhaps best as an additional comment to the following code block:

![image](https://github.com/TheOdinProject/curriculum/assets/122839503/76c70b50-071d-489b-860a-4e024c567e4c)

How does that sound to you?

**Comment by aceus0** [comment]
@MaoShizhong, sure that sounds good. Just want to help others avoid this pitfall! 

I'll get working on it today.

**Comment by MaoShizhong** [comment]
Awesome. When I get the chance, I can pop a similar note in #27953. Wouldn't hurt to just be explicit about it for clarity.
