### ISSUE TITLE
Ruby On Rails: Problem in Knowledge Check of Routing Lesson. Postman Chrome extension is deprecated

### ISSUE THREAD

**Issue by AhmedTheGreatest** [TheOdinProject/curriculum#28050]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Problem
In the Routing section of The Ruby on Rails course, there is a Knowledge Check about the deprecated Postman Chrome Extension which is now replaced with the Postman Native App. This Knowledge Check question is related to the 7 year old REST API video by Brad Traversy which is linked in the Assignment section.

### Solutions
**There can be a few solutions to solve this problem:**
1. Remove the knowledge check question.
2. Add a disclaimer about the deprecation of the extension.
3. Replace the video about APIs with some other one.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-routing#knowledge-check

### (Optional) Discord Name

tornado_77

### (Optional) Additional Comments

This is my first time contributing to open-source.

**Comment by JoshDevHub** [comment]
@AhmedTheGreatest Hello and thank you for making this issue.

If you have a good, up-to-date video that could replace the current video, I think that would be the best thing to do here. If not (I realize looking for a replacement could be a lot of work), I think we could remove the knowledge check and have a note in the Assignment that mentions that the extension shown in the video is deprecated. I would accept a PR that does either of these things.

> This is my first time contributing to open-source.

Welcome! Always great to have new contributors.

**Comment by AhmedTheGreatest** [comment]
Hello, thanks for assigning it to me. I'll certainly try to find some replacement videos or else just remove that knowledge check and add a disclaimer. I'll see if I can do it today or else I'll do it tomorrow as it's night here. I'll first send you the replacement if I find one. Thanks, a lot.

**Comment by AhmedTheGreatest** [comment]
Hello @JoshDevHub . Will this [video](https://www.youtube.com/watch?v=PfujVETI-i4) work? It I think is not as good as the other one and it uses the web version of postman? There is also this good [blog](https://blog.postman.com/rest-api-examples). I think I should just remove the knowledge check and add a note about its deprecation.

**Comment by JoshDevHub** [comment]
Hey @AhmedTheGreatest 

Yeah let's just remove the knowledge check and add a note about the deprecation. We can always think about a replacement later down the line. The quick fix will help people who are going through this lesson right now.

Thank you for finding this and volunteering to fix it :muscle:

**Comment by AhmedTheGreatest** [comment]
I have submitted a Pull Request.
