### ISSUE TITLE
The Asset Pipeline: <learning overview item with no reference in lesson>

### ISSUE THREAD

**Issue by Leo-U** [TheOdinProject/curriculum#28064]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

It looks like third third lesson overview item, 'How to display raw HTML-code in your app', is a reference to a removed part of the lesson. Suggest either removal of the learning objective or inclusion of explanatory content

Note - there's already [a stale issue](https://github.com/TheOdinProject/curriculum/issues/25588) re. this lesson. Not sure if it's relevant but I thought it's worth linking here.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-the-asset-pipeline

**Comment by KevinMulhern** [comment]
Great spot! thanks for reporting @Leo-U.

It looks like [that content](https://github.com/TheOdinProject/curriculum/pull/25615) was removed a while ago. That lesson overview item can definitely go!

**Comment by theSamyak** [comment]
> Great spot! thanks for reporting @Leo-U.
> 
> It looks like [that content](https://github.com/TheOdinProject/curriculum/pull/25615) was removed a while ago. That lesson overview item can definitely go!

Hi, @KevinMulhern 
Since the issue hasn't been addressed yet, I propose labeling it as a good first issue or you can reassign it to me. I would resolve this promptly. Thanks.

**Comment by CouchofTomato** [comment]
@Leo-U Are you happy for someone else to work on this?

**Comment by Leo-U** [comment]
Yes no problem, thank you!
