### ISSUE TITLE
Command Line Basics: Remove Assignment & Additional Resource Items

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#28069]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I have completed TOP up to the Node section. I've genuinely never had to use a pipe or a filter. I remember spending hours on that lessons trying to understand it / practice etc. I was extremely confused at the time. And it slowed me down from doing things that in my opinion are more important at this stage. 

I don't think that these two lessons are going to be useful to learners this early on. If odin wants to go deeper into shell scripting, which is indeed very powerful - it should be introduced at a later point.

Learners don't need to understand how to pipe commands or filter stuff to go through TOP. The most complicated commands I used while doing the Odin Project were the ones listed up to and including Lesson 3. (Working with Files)

**Even the assignment isn't asking learner to practice using pipes or filters.**

Next: Most of the additional resources are also too complicated. We have to think about the demographic of the learners - a lot of whom have likely never have used the command line before. If learning these things isn't required, then why keep them in?

Additional Resource Item 1:
![image](https://github.com/TheOdinProject/curriculum/assets/154856872/8c7f4508-d47e-428f-b578-cbaf57ef50f4)

Why would learners need to know about this?

2: This is fine to leave in, imo. Covers most of the stuff covered in the first 3 lessons.

![image](https://github.com/TheOdinProject/curriculum/assets/154856872/e626e7d6-4595-4f94-b845-a0d6f8bbe88e)

3: 
![image](https://github.com/TheOdinProject/curriculum/assets/154856872/e53d14a3-c4f3-4b8b-bf18-26d6bca11c61)

I appreciate the site's utility, however if the most complex commands we are expecting learners to perform at this point are mv and ls, I don't think it's worth keeping this in.

4:
![image](https://github.com/TheOdinProject/curriculum/assets/154856872/c679d2ce-352a-4c03-91d2-0a1f5bab7f19)

The commands listed in this 'cheatsheet' are too complicated. Cheatsheets usually require some familiarity to be comfortable, anyway. So someone completely new would understandably be completely overwhelmed.

5: This is also fine to leave in imo, goes over the relevant stuff.

6: This playlist goes into Debian, Fedora. Not really relevant to TOP, also this series goes wayy beyond and covers some sysadmin stuff which learners also don't need to know. 

Total proposal:
- Remove all additional resources except `2` and `5`.
- Remove the assignment to read  `Pipes and Filters`

I think it'd be nice to introduce more CLI ideas later on in the course potentially, but not at this point. Using a terminal significantly speeds up workflow but speed isn't a concern for a learner at this stage. Like a lot of them have ever only used a graphical file manager at this point.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-command-line-basics

### (Optional) Discord Name

Nikita Revenco

### (Optional) Additional Comments

If this issue is accepted, leaving it for first time contributors.

**Comment by JoshDevHub** [comment]
Hello @nikitarevenco. Thank you for making this issue.

I think I'm following with most of what you say here. Something I'm a bit confused about though:
>  Remove all additional resources except 2 and 5.
>  Remove the assignment to read Working with Files and Directories and Pipes and Filters

Remove the assignment to read "Working with Files and Directories"? That one seems essential to me. It introduces `mkdir`, `touch`, `rm`, `mv`, etc.

**Comment by nikitarevenco** [comment]
> Hello @nikitarevenco. Thank you for making this issue.
> 
> I think I'm following with most of what you say here. Something I'm a bit confused about though:
> 
> > Remove all additional resources except 2 and 5.
> > Remove the assignment to read Working with Files and Directories and Pipes and Filters
> 
> Remove the assignment to read "Working with Files and Directories"? That one seems essential to me. It introduces `mkdir`, `touch`, `rm`, `mv`, etc.

Hmm I must've missed something, looks like that one is definitely good to keep.

**Comment by MaoShizhong** [comment]
I'm personally in agreement with removing the "Pipes and Filters" assignment step, as well as the proposed AR changes for the exact reasons highlighted.
@TheOdinProject/maintainers any additional/differing thoughts?

**Comment by JoshDevHub** [comment]
I think I agree with the proposed changes so long as we're keeping the files and directories assignment.

If that all sounds good, we can proceed on this. Since the OP didn't indicate they want to work on this, I'll open up to anyone to contribute.

### Acceptance Criteria
In the [command line basics lesson](https://www.theodinproject.com/lessons/foundations-command-line-basics) do the following:
- [ ] In the Assignment section, remove the link to the Pipes and Filters section of the Unix Shell Course
- [ ] In the Additional Resources section, remove all items except the 2nd (the "Learn Enough Command Line to be Dangerous" link) and the 5th (the "Command Line Flash Cards" link)

Comment below to be assigned.

**Comment by mathdebate09** [comment]
Hi @JoshDevHub , I can work on this issue, can you please assign it to me :)

**Comment by zachmmeyer** [comment]
Well that was embarrassing.
You're up, @mathdebate09 !

**Comment by mathdebate09** [comment]
Thanks @zachmmeyer, no problem 😂
