### ISSUE TITLE
Testing Basics: Broken link: "Read about the basic process and the benefits of TDD."

### ISSUE THREAD

**Issue by IanBellomy** [TheOdinProject/curriculum#28068]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Broken link in Testing Basics: Assignment: 1. : Read about the basic process and the benefits of TDD

Page returns 503: 
https://web.archive.org/web/20211123190134/http://godswillokwara.com/index.php/2016/09/09/the-importance-of-test-driven-development/.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-testing-basics

**Comment by JoshDevHub** [comment]
Hello @IanBellomy, thank you for making this issue.

That link doesn't 503 for me:
![Selection_422](https://github.com/TheOdinProject/curriculum/assets/88392688/7794a087-e781-49dd-a208-774215e9a98f)

503 codes usually come from a server being temporarily too busy to respond to the request or from being under maintenance. Can you try again and confirm that it works?

**Comment by SumonGFC** [comment]
The link works for me.

**Comment by JoshDevHub** [comment]
Yeah I'm going to close this. If you look back and it's still giving you trouble, just let me know and I'll reopen it @IanBellomy

**Comment by IanBellomy** [comment]
Apologies, indeed, all good.

**Comment by hbar1st** [comment]
hi guys, can we re-open this? The link is not working today.

**Comment by JoshDevHub** [comment]
Works fine for me right now, so I'm inclined to keep it closed.

Webarchive has been experienced a big DDoS attack lately that has caused it a lot of problems. You'll have to be patient with them until that all gets sorted out.
