### ISSUE TITLE
 Techniques: <most of the external links refuses to load>

### ISSUE THREAD

**Issue by rinanizza** [TheOdinProject/curriculum#28065]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

#Most of the external links refuses to load
### Path

Other / NA

### Lesson Url

https://react.dev/learn/conditional-rendering#conditionally-returning-jsx

**Comment by JoshDevHub** [comment]
@rinanizza Sorry you're having trouble with the links. Is this still a problem that you're facing?

Like @Dillonpw said, that isn't a link to a lesson on TOP. If it's meant to be a link that doesn't work, it seems to work just fine for me (and others).

**Comment by rinanizza** [comment]
Well understood., thanks.

**Comment by MaoShizhong** [comment]
Closing as TOP link or not, the link seems to work fine and others cannot replicate a broken link.
