### ISSUE TITLE
Links and Images: broken link

### ISSUE THREAD

**Issue by kartavious** [TheOdinProject/curriculum#28079]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The link to the practice image of the dog is broken. The target page no longer exists. Please update the link so that it points to a valid image.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

**Comment by PrathamVerma999** [comment]
hi I can download the picture, I believe https://unsplash.com/photos/Mv9hjnEUHR4/download?force=true&w=640 is the link you're referring to? if so, it is working perfectly fine.

**Comment by MaoShizhong** [comment]
I can also confirm that both instances of this link correctly download the image automatically on click - works on my machine with Chrome, Firefox, Brave, and on mobile as well.

@kartavious Can you confirm if this is still broken for you? Does it work if you try clearing browser cache, different browsers, different devices, resetting internet connection etc.?

I have attached the image below.

![charlesdeluvio-Mv9hjnEUHR4-unsplash](https://github.com/TheOdinProject/curriculum/assets/122839503/e43b7cc5-f4fa-4c3b-9e50-97d417dd977c)

**Comment by MaoShizhong** [comment]
Closing due to no response and also unable to replicate issue.
