### ISSUE TITLE
Rock Paper Scissors: <Third bullet point in the "Setup the project structure" step should be formulated differently>

### ISSUE THREAD

**Issue by emmahare** [TheOdinProject/curriculum#28083]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

"Check if webpage includes JavaScript" can be confusing, especially to beginners, seeing it doesn't properly describe what the individual is doing (or supposed to be doing). My suggestion would be to change that into: "Check if JavaScript is linked correctly". 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-rock-paper-scissors

### (Optional) Discord Name

BakedBeansOnToast

**Comment by MaoShizhong** [comment]
I dig it. Assigned to you
