### ISSUE TITLE
Positioning : Adding Beginner-Friendly CSS Positioning Videos

### ISSUE THREAD

**Issue by Finn245** [TheOdinProject/curriculum#28080]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I found a great, beginner-friendly video that would be a valuable addition to the "Additional Resources" section in the "Positioning" lesson. It showcases some really good, easy, and useful examples of how to use CSS positioning, including real-world applications.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-positioning

### (Optional) Additional Comments

I would love to contribute videos like these or any type of documentation that helped me throughout my learning ^^ .

**Comment by MaoShizhong** [comment]
Thanks @Finn245. You'll need to share the resource with us so the team can review it first.

**Comment by MaoShizhong** [comment]
Looks like you've already opened a PR for this #27868, so I'll close this issue. The assigned maintainer had been super busy with IRL stuff so wasn't able to get round to your PR.

**Comment by Finn245** [comment]
Sure no problem!
