### ISSUE TITLE
Possible copyright violation in Introduction to Git: <Short description of your suggestion>

### ISSUE THREAD

**Issue by toeireishuman** [TheOdinProject/curriculum#28081]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

This issue was already addressed before in [here](https://github.com/TheOdinProject/curriculum/issues/26109). I raised it because it seems like the previous issue is "stale".

This post is mostly to remind the contributors/maintainers that the video link is still in the lesson's assignment. The previous discussion already talked about removing the video, but it's still there. I watched it. I hope this gets addressed because it is really unfair to the authors of the Pro Git book. 

Please let me know if I raised this issue incorrectly.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-git

**Comment by xandora** [comment]
Thanks for bringing this up, it seems it fell off our radar last time around. You haven't ticked the box to indicate you'd like to work on it, so I'm going to open it up to others as a contribution opportunity. If you do want to work on it, let us know and we can assign it your way.

---
Info to contributors:

This change is to replace the plagiarizing Git History video in the "Introduction to Git" lesson. It needs to be replaced by either an appropriately attributed and licensed alternative video, or simply replaced with a link to the same content on the git-scm.com website.

Acceptance Criteria:
[ ] DevTips video removed from the lesson, and replaced with:
[ ] An appropriate alternative video OR
[ ] A link to similar content such as the git-scm.com Pro Git chapter
[ ] Copy surrounding the link is updated to make sense after the replacement has been made

**Comment by Grayvox** [comment]
I believe I can help and would like to be assigned this issue

**Comment by xandora** [comment]
> I believe I can help and would like to be assigned this issue

@Grayvox Thanks for putting your hand up for this one. Assigned.
