### ISSUE TITLE
React: Sandbox links don't work in the second assignment

### ISSUE THREAD

**Issue by royalh23** [TheOdinProject/curriculum#28089]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the second [assignment](https://www.developerway.com/posts/how-to-fetch-data-in-react), sandboxes dont' work since the API links they contain are broken. For example, [this sandbox](https://codesandbox.io/p/sandbox/basic-waterfall-example-forked-96dyxm) will throw an error (which is one of the many sandbox links in the article).

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react#assignment

**Comment by MaoShizhong** [comment]
Thanks @royalh23, can also confirm it seems the API links that article uses are broken. Was about to suggest contacting the article author to let them know while looking for a potential replacement article in the meantime, but it looks like you may have already done so? Looks like their codesandboxes should be fixed pretty soon. I'll keep an eye on it

**Comment by MaoShizhong** [comment]
Ah, a well that's fortunate timing then. Should be fixed within the next couple of days then based on the author's reply :tada:

**Comment by MaoShizhong** [comment]
Closing as it looks like the article's codesandboxes have been fixed :tada:
