### ISSUE TITLE
Ruby On Rails: Capitalization / Formatting issue in Members Only project

### ISSUE THREAD

**Issue by AhmedTheGreatest** [TheOdinProject/curriculum#28093]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is an issue in the assignment section of the Members Only! project that is part of the Ruby On Rails course. The 'n' of the note is uncapitalized. I suggest we can also make it a note box instead.
![image](https://github.com/TheOdinProject/curriculum/assets/67534373/72b85771-4881-46aa-b7f1-d4dac0bc37f4)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-members-only

### (Optional) Discord Name

tornado_77

### (Optional) Additional Comments

Sorry for not a very detailed and long issue as its just a small problem.

**Comment by MaoShizhong** [comment]
A note box is sensible - assigned

**Comment by AhmedTheGreatest** [comment]
I have submitted a pull request.

**Comment by AhmedTheGreatest** [comment]
The David Anson Check is failing...
