### ISSUE TITLE
CSS Units: <Short description of your suggestion>

### ISSUE THREAD

**Issue by ChhetriPrem** [TheOdinProject/curriculum#28091]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

We have units for viewport like dvh dvw or svh svw or lvh etc. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-css-units

**Comment by JoshDevHub** [comment]
Hello @ChhetriPrem. Thank you for making this issue.

What is your suggestion for these units exactly? How do you want to incorporate them into the lesson?
