### ISSUE TITLE
getting_hired: fix typo 

### ISSUE THREAD

**Issue by fadingmorsecode** [TheOdinProject/curriculum#28098]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a typo on line 7 (change opportunites to opportunities).

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-getting-hired-qualifying-job-leads

**Comment by emmahare** [comment]
Hi, I took a look into the lesson you linked, and I can't seem to find the typo you're referring to. Perhaps you've linked the wrong lesson? If you haven't, then could you be a little bit more specific about where the typo is located? Thanks!

**Comment by emmahare** [comment]
Sorry, now I've seen it! It's in the link, but it's in the link located in the third paragraph. 

I wouldn't mind opening a pull request to change it!

**Comment by AhmedTheGreatest** [comment]
Hello, I am willing to work on this issue, as the OP (the person who has issued the issue) has stated that they don't want to work on this.

**Comment by MaoShizhong** [comment]
Thanks for offering, both of you. Since @emmahare was first, I've assigned her.

**Comment by AhmedTheGreatest** [comment]
Okay!!
