### ISSUE TITLE
Ruby On Rails: Leftover Asterisk (*) from the last Pull Request in Members Only

### ISSUE THREAD

**Issue by AhmedTheGreatest** [TheOdinProject/curriculum#28102]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the last Pull Request, I changed the note regarding Devise to be a note box. But I forgot to remove the asterisk at the end of the note as shown by the picture below. I just noticed it and I would like to be able to fix this minor problem.
![image](https://github.com/TheOdinProject/curriculum/assets/67534373/c36feb9d-9d39-4403-89c8-0f6bd02c001f)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-members-only

### (Optional) Discord Name

tornado_77

### (Optional) Additional Comments

Sorry, that I forgot to remove it in the last PR.

**Comment by MaoShizhong** [comment]
:+1:
