### ISSUE TITLE
Command Line Basics: Add note in case of missing Desktop folder 

### ISSUE THREAD

**Issue by EmmaBeansHare** [TheOdinProject/curriculum#28115]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The [Navigating Files and Directories](https://swcarpentry.github.io/shell-novice/02-filedir.html) link in the [Command Line Basics](https://www.theodinproject.com/lessons/foundations-command-line-basics) lesson leads to a useful guide to navigating and locating files and directories in a computers system. One of the exercises requires the user to type "**ls -F Desktop**" into their command line. Initially this isn't a problem, however it *can* happen, that a Desktop folder doesn't exist in a users system. And there have been cases, in which we've been asked about/for help with such issue on Discord. 

@gingkapls actually thought this could be a good thing to implement, and I agree with them, so we've agreed on me taking over opening the issue:
Our suggestion would be to add in a note somewhere around the Assignment section which would assure the user that not having a Desktop folder *isn't* a major issue, or isn't an issue at all. Because not finding a Desktop folder on your own system can seem a bit scary, especially with "**Note that if a directory named Desktop does not exist in your current working directory, this command will return an error. Typically, a Desktop directory exists in your home directory, which we assume is the current working directory of your bash shell.**" written beneath the example the user should be copying.  

Additionally, we could link it to a guide to how to solve this, given we have/find a fitting guide or can create one, but I'm still searching for appropriate answers to that sort of issue. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-command-line-basics

### (Optional) Discord Name

BakedBeansOnToast

**Comment by gingkapls** [comment]
Thanks for opening the issue Emma!
There is [another resource](https://swcarpentry.github.io/shell-novice/03-create.html) in the same lesson that assumes that the users have a `Desktop` folder in their home directory as well.

I think your proposal is plenty good. As for the solution, we could add a part at the end where we tell users to create a `Desktop` folder using `mkdir`, so that their environment is consistent with those of the exercises.

**Comment by wise-king-sullyman** [comment]
Sounds like a good plan to me! Thank you to you both!

**Comment by emmahare** [comment]
Thank you for assigning me!

I'm working on the note, but I just wanted to get opinions on where the note should be placed. 

I personally think placing the note *above* the two existing notes in the assignment section would be best, seeing the note we're adding is meant for something that could happen to anyone, and would prove useful not only when the user simply *doesn't* have a Desktop folder, but also to come back to when a user accidentally deletes their Desktop folder. 

Many thanks in advance!
