### ISSUE TITLE
HashMap Data Structure: Clarify what it means for a map to be "75% full"

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#28119]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There seems to be confusion from some learners about whether reaching (load factor * capacity) means that many entries or means that many buckets with one or more entries. See conversation that spurred this issue here: https://discord.com/channels/505093832157691914/505093832157691916/1245839364890562642
I'm happy to amend the current paragraph under the [when-do-we-know-that-its-time-to-grow-our-buckets-size](https://www.theodinproject.com/lessons/javascript-hashmap-data-structure#when-do-we-know-that-its-time-to-grow-our-buckets-size) heading to make it clear that it's entries that count.

I note that there are two other issues that might be vaguely relevant, but are stale. I can potentially work some of those things in if there's any clear direction on what's happening with them? Not sure on that one
See: #27174 and #27682

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-hashmap-data-structure

### (Optional) Additional Comments

We :heart: open source

**Comment by JoshDevHub** [comment]
I've seen this same confusion arise and absolutely am onboard with clarifying this point.

Glad to assign you @damon314159 

After you've completed this, feel free to bump either of those other stale issues if you want to help work on those.
