### ISSUE TITLE
HashMap: <Implement examples/tests to test out Hash Map code>

### ISSUE THREAD

**Issue by elishamutang** [TheOdinProject/curriculum#28117]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There should be some examples or tests that users can test out their Hash Maps to see if they've implemented it correctly.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-hashmap

**Comment by wise-king-sullyman** [comment]
Sounds like a good idea to me, thanks!
