### ISSUE TITLE
Revisiting Rock Paper Scissors: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Slimdaddy254** [TheOdinProject/curriculum#28114]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

3. If everything goes fine, our rps-ui branch is now successfully merged with main! Use git log and you’ll see all the commits you’ve made to your feature branch on top of the commits you made to the main branch. Now for our final step!

I have realised with the instruction above on git log, there is no instruction for one to press "q" in order to exit git log. Took me a while as a newbie to figure  out  how to exit git log,but i think it would help if it was there before moving to the next step.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors

### (Optional) Discord Name

Shadee

**Comment by JoshDevHub** [comment]
Hello @Slimdaddy254. Thank you for making this issue.

I think your suggestion is very sensible. Since you indicated you want to work on it, I'll assign you. Let me know if you have any questions.

**Comment by Slimdaddy254** [comment]
You can review my commit.

**Comment by JoshDevHub** [comment]
Hi @Slimdaddy254 

Me just looking at a commit you've made on your fork isn't enough to get the change merged into the curriculum. You need to open a Pull Request (or PR) to this repository with your proposed changes. Please see our [contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md#how-to-contribute) for information on how to do this.

**Comment by KevinMulhern** [comment]
@Slimdaddy254 did you see Joshs suggestion?

**Comment by Slimdaddy254** [comment]
Just seen it.
