### ISSUE TITLE
The Cascade: <Fix broken URL of additional resource  called "Interactive Scrim on the CSS cascade">

### ISSUE THREAD

**Issue by stoai0** [TheOdinProject/curriculum#28126]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The additional resource called "Interactive Scrim on the CSS cascade" seems to be a broken link : 

- https://scrimba.com/scrim/c9gwmnAR

I believe (but I am very much a beginner) that this might be due to Scrimba releasing a V2 website and therefore changing their domain name. The new lessons are on V2.scrimba.com whereas the "legacy" ones seem to be accessible only via V1.scrimba.com

If that resource is still deemed useful, I would recommend changing the link to : 

- https://v1.scrimba.com/scrim/c9gwmnAR 

This would need to be done directly in the lesson, because right now the behavior of the website with the current URL is that they redirect us to the V2 website and I get a 524 error trying to load a page that doesn't exist.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade

### (Optional) Discord Name

Tailwhip

**Comment by MaoShizhong** [comment]
Thanks @stoai0. Looks like this is (for now) the only scrimba in the curriculum with this issue.
Since you didn't check the assignment box, I'll open this up for assignment - please comment below if you'd like to be assigned to this.

### Acceptance criteria

- [ ] Change the href for the above Scrimba to `https://v1.scrimba.com/scrim/c9gwmnAR` in `The Cascade`.

**Comment by mathdebate09** [comment]
Hey @MaoShizhong, I can work this fix up :)

**Comment by MaoShizhong** [comment]
Go for it @mathdebate09
