### ISSUE TITLE
Int HTML/CSS Form Basics: Use level 4 headings instead of emphasis

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#28120]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The [Form Basics lesson](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics) currently uses a lot of subsection headings that are in the format `**Heading**` instead of `#### Heading`. This creates an issue when we render the lesson page on the TOP site because the "heading" will only visually appear like a subsection heading but will not actually be an `<h4>` element that's clickable.

Please comment below if you would like to be assigned to the following task (best done locally to make linting and fixing much quicker and easier).

### Acceptance criteria

- [ ] Following this repo's [linting instructions](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md#curriculum-linting), run
  ```bash
  npm run fix:lesson -- intermediate_html_css/forms/form_basics.md
  ```
- [ ] There should be 15 remaining MD036 lint errors, each should be manually fixed to be level 4 markdown headings (`####`) e.g. `**Labels**` should be fixed to `#### Labels`. There should not be any other lint errors after this.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics

**Comment by soniikot** [comment]
Hello,
It is my first time when I try to fix something, but since I am going through an advanced git lesson, I would like to try.
Do I understand correctly I need to correct sub-headings tags from strong to h4?

**Comment by MaoShizhong** [comment]
Assigned you @soniikot :rocket:

Yes, if you do the first step described above, which is to run the lint fixer command, you'll be left with 15 subheadings that are in the format `**Subheading**`. You then need to change all 15 of these to the format `#### Subheading`
