### ISSUE TITLE
The Cascade: <'The CSS Cascade' link is broken in Additional Resources>

### ISSUE THREAD

**Issue by shivanshu2307** [TheOdinProject/curriculum#28189]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

'The CSS Cascade' link is broken in Additional Resources section, opening the link lands to 404 file not found page.
[https://wattenberger.com/blog/css-cascade](url)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade

### (Optional) Discord Name

peaksbluffs

**Comment by mathdebate09** [comment]
She also has an older version of her website [https://2019.wattenberger.com](https://2019.wattenberger.com)(linked at bottom of here newer website) wherein the blog article is still active at [The CSS Cascade](https://2019.wattenberger.com/blog/css-cascade)

**Comment by shivanshu2307** [comment]
Thanks!
