### ISSUE TITLE
JavaScript: How This Course Will Work: <Change sentence formation>

### ISSUE THREAD

**Issue by EmmaBeansHare** [TheOdinProject/curriculum#28194]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the last paragraph of the [The Path](https://www.theodinproject.com/lessons/node-path-javascript-how-this-course-will-work#the-path) section of the [How this course will work](https://www.theodinproject.com/lessons/node-path-javascript-how-this-course-will-work) lesson, the last sentence should be formatted differently. 

It is currently formatted as follows: 

"This is the kind of project that you’ll consider including in your portfolio *as an example to demonstrate to prospective employers you have strong web development skills.*"

And I myself am not exactly sure what might have been meant with the last (emphasised) part of this sentence. 

I think changing it into: 

"This is the kind of project that you'll consider including in your portfolio *to demonstrate your web-development skills to prospective employers.*"

or

"This is the kind of project that you'll consider including in your portfolio, *as an example, to demonstrate your strong web-development skills to prospective employers.*"

would be a good idea. (I've only emphasised the changed parts for these examples, they wouldn't actually be emphasised)

Thank you in advance!

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-how-this-course-will-work

### (Optional) Discord Name

BakedBeansOnToast

**Comment by wise-king-sullyman** [comment]
Sounds like a good change to me, I think I lean slightly toward the first option.

Thanks!
