### ISSUE TITLE
CSS: Add a new resource in 'Introduction to Flexbox' lesson

### ISSUE THREAD

**Issue by mathdebate09** [TheOdinProject/curriculum#28197]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I recently came across a [basic playground](https://flexbox.tech/) for flexbox which gets people working on what properties exist and how do they visually look when toggled.
This could be added either in the first lesson in flexbox section or in the last lesson, though last lesson has tonnage of advanced resources and this being a rather simpler one, I think we can add this up in the Introduction lesson, for the Additional Resources section.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox#additional-resources

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/html-css thoughts on this resource?

**Comment by mathdebate09** [comment]
I just rechecked the flexbox lessons, it seems we're currently overloaded on resources with flexbox, I'll close this issue.
