### ISSUE TITLE
Databases and SQL: Suggested Command in W3 Schools Editor Causes Error

### ISSUE THREAD

**Issue by columk1** [TheOdinProject/curriculum#28204]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Issue

The section on aggregate functions contains the following suggestion:

> See [W3 Schools’ article](http://www.w3schools.com/sql/trysql.asp?filename=trysql_select_groupby) and play around with the SQL in the window (try deleting the GROUP BY line) for an interactive visual.

Deleting this line in the linked editor changes the query from:
>SELECT COUNT(CustomerID), Country
FROM Customers
GROUP BY Country;

To:
>SELECT COUNT(CustomerID), Country
FROM Customers;

When the new query is run, it causes the editor to throw an error:
>Error in SQL:
You tried to execute a query that does not include the specified expression 'Country' as part of an aggregate function.

### Suggestion

Remove the text in parentheses.
>play around with the SQL in the window **(try deleting the GROUP BY line)** for an interactive visual.

Alternatively, the lesson should be more specific in what it wants students to learn by deleting this line. If the goal is to show students the error then it should come with an explanation that SQL needs to know how to group the rows for non-aggregated columns. The syntax in the current error message isn't enough for someone new to SQL.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/databases-databases-and-sql

### (Optional) Discord Name

columk

**Comment by DrantDumani** [comment]
Bumping this issue as I agree that the error message may not be enough for someone who is brand new to sequel. Plus, it can also be confusing to explicitly follow the directions the lesson gives you, only to run into an error.

**Comment by JoshDevHub** [comment]
Oh wow yeah. I think you can just get rid of that note about deleting the `GROUP BY` clause. It's ambiguous what the intent is, and I don't think it's all that important to go through the error that exists without having it present.

Since you indicated you'd like to work on it, I'm glad to assign you @columk1
