### ISSUE TITLE
Ruby on Rails Flight Booker: Broken link about Stripe Checkout Integration

### ISSUE THREAD

**Issue by AhmedTheGreatest** [TheOdinProject/curriculum#28203]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

## Problem:
There is a broken link regarding Stripe Checkout integration with Ruby on Rails in the Flight Booker Project. It probably happened because Stripe has I think revamped their Checkout system.

## Solution:
Should I replace it with [this](https://docs.stripe.com/checkout/quickstart)? Its probably not the same page. But It does tell how to integrate with Stripe Checkout with Ruby?

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-flight-booker#project-solution

### (Optional) Discord Name

tornado_77

### (Optional) Additional Comments

Just a quick issue. I could have directly made a Pull Request but wanted to know if the above provided link is fine.

**Comment by JoshDevHub** [comment]
@AhmedTheGreatest Nice find! Yes, that link you have should function as a good replacement. I've assigned you. Let me know if you have any questions.

**Comment by AhmedTheGreatest** [comment]
I have submitted a pull request! Thanks!
