### ISSUE TITLE
Installation Overview: Add a link to the list of reason why not to use Windows

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#28218]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

This lesson repeatedly mentions that TOP does not support Windows, but it doesn't mention much about the _why not_. I think adding a link to https://github.com/TheOdinProject/blog/wiki/Why-We-Do-Not-Support-Windows might help with answering that question. This also ties into https://github.com/TheOdinProject/odin-bot-v2/issues/547

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installation-overview

**Comment by theSamyak** [comment]
But it does mention why TOP doesn't support windows as you can see here - https://www.theodinproject.com/lessons/foundations-installation-overview#windows

**Comment by SumonGFC** [comment]
> But it does mention why TOP doesn't support windows as you can see here - https://www.theodinproject.com/lessons/foundations-installation-overview#windows

It does mention a single reason why Windows isn't supported (i.e. Linux development tools), but it is not nearly as comprehensive as the list provided by the [blog post](https://github.com/TheOdinProject/blog/wiki/Why-We-Do-Not-Support-Windows)

I do think a good compromise would be to hyperlink the blog post to the text "is not natively supported" on line 40 of [the lesson source](https://github.com/TheOdinProject/curriculum/blob/main/foundations/installations/installation_overview.md?plain=1#L38)
This I think would alleviate any immediate gripes about there being no support for windows.

**Comment by theSamyak** [comment]
While I understand the intention behind adding a link to the blog post, I believe the current level of detail on the reasons why TOP does not support Windows is sufficient. The primary reason as mentioned, is the lack of native support for Linux development tools on Windows. Adding the blog link might not provide significant additional insight or value to the lesson.

Moreover, TOP pages are already linked with numerous resources. Including links that do not add substantial educational value can potentially overwhelm readers and detract from the main content. IMO  It's better to keep the resources simple and relevant for a better learning experience.

That being said, I appreciate your suggestion. Have a good day :)

**Comment by CouchofTomato** [comment]
I would support it being added as an additional resource in case people are interested to know why

**Comment by mathdebate09** [comment]
I believe we should add the link to the blog, another additional explanation about why not would always help.
If the author hasn't ticked-in for working on the issue, I can work it up :)

**Comment by MaoShizhong** [comment]
Our links need to have sufficiently descriptive text for accessibility reasons. `blog post` is not sufficiently descriptive for where it leads to or what it is about.

Something like the following would be accessible enough:
> - For further information on The Odin Project and Windows, we have a [list of reasons why Windows is not a supported OS in The Odin Project](https://github.com/TheOdinProject/blog/wiki/Why-We-Do-Not-Support-Windows).

**Comment by theSamyak** [comment]
Oh, that makes sense. Thank you for pointing it out.

**Comment by Asartea** [comment]
Thanks for doing this @mathdebate09

**Comment by mathdebate09** [comment]
Always :rocket:
