### ISSUE TITLE
Setting up Git: A partition between two topics 

### ISSUE THREAD

**Issue by Ashking-net** [TheOdinProject/curriculum#28215]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a section in setting up git lesson where a certain section is given for mac users only and the next part is just normal tutorial for setting up git, but it causes problem cause there is no partition between the mac user special tut and normal guide which makes newbies think the next part is also part of mac users Tutorial, which causes huge problem in setting up git

in the image provided there is mac user specfic command and in next line i.e (Step 2.3) many linux user skip this thinking its related to mac user only,which result in them making no SSH key

![ss](https://github.com/TheOdinProject/curriculum/assets/172505089/0fc06a79-5e04-4c97-90a4-5a47a8a25f5e)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### (Optional) Discord Name

Ashking

**Comment by xandora** [comment]
We could make it a note section to give it some contrast with the following step.
![image](https://github.com/TheOdinProject/curriculum/assets/2021268/a2b7fc12-6020-455d-9685-5f88a59527bb)

**Comment by Ashking-net** [comment]
> We could make it a note section to give it some contrast with the following step. ![image](https://private-user-images.githubusercontent.com/2021268/339544743-a2b7fc12-6020-455d-9685-5f88a59527bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTk4NDksIm5iZiI6MTcxODU1OTU0OSwicGF0aCI6Ii8yMDIxMjY4LzMzOTU0NDc0My1hMmI3ZmMxMi02MDIwLTQ1NWQtOTY4NS01Zjg4YTU5NTI3YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTZUMTczOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZlZjYyZjRmMmU2MmU1YjA5YTA1OGRlZDE0NjU4YmIzMzQyNjdjY2Q5OGM2MWFkNWE4OWZiMWU0NDQ5YThlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TfeyXgwQdMmqhB9eau6lbnQ5JDJvb-MkqtI75gXJ6Ro)

yeah that would work

**Comment by theSamyak** [comment]
Since no one was assigned and it has been a week, I went ahead and resolved this issue. I apologize for not adhering to the policy of not starting work on open issues without assignment, which @MaoShizhong brought to my attention after I submitted my pull request.

Could you please review the changes this time and confirm if everything looks good on your end? If necessary, I am prepared to revert the changes and resubmit the pull request accordingly. Thankyou.

**Comment by MaoShizhong** [comment]
> Since no one was assigned and it has been a week, I went ahead and resolved this issue. I apologize for not adhering to the policy of not starting work on open issues without assignment, which @MaoShizhong brought to my attention after I submitted my pull request.
> 
> Could you please review the changes this time and confirm if everything looks good on your end? If necessary, I am prepared to revert the changes and resubmit the pull request accordingly. Thankyou.

In the future, the process would be to comment on the issue requesting assignment, then waiting to be assigned by a maintainer before opening a PR. In this case, since no one else has requested assignment, I'll assign you. One of the team will get to reviewing your PR in due course.

**Comment by theSamyak** [comment]
> > Since no one was assigned and it has been a week, I went ahead and resolved this issue. I apologize for not adhering to the policy of not starting work on open issues without assignment, which @MaoShizhong brought to my attention after I submitted my pull request.
> > Could you please review the changes this time and confirm if everything looks good on your end? If necessary, I am prepared to revert the changes and resubmit the pull request accordingly. Thankyou.
> 
> In the future, the process would be to comment on the issue requesting assignment, then waiting to be assigned by a maintainer before opening a PR. In this case, since no one else has requested assignment, I'll assign you. One of the team will get to reviewing your PR in due course.

Thanks!  I'll keep this in mind. Looking forward to contributing :)
