### ISSUE TITLE
Intro to CSS: <Please add the closed captioning on Scrim because I'm deaf>

### ISSUE THREAD

**Issue by jelewi90** [TheOdinProject/curriculum#28221]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

As a deaf learner, I will love to see and learn through this website become accessible for deaf learners like me.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### (Optional) Discord Name

Jelewi90

**Comment by xandora** [comment]
@webfliccy Looks like this is something you contributed to the curriculum, is there a closed captions toggle for these CSS scrims?

Original commit: https://github.com/TheOdinProject/curriculum/commit/182ed703b1774b188b69cd9e278c485c909da90d

**Comment by jelewi90** [comment]
There is no toggle and in advance in case, auto-generating is something
that you shouldn’t consider because it will not translate everything
accurately. Type out the closed captioning is much more accurate compared
to auto-generating captions.

**Comment by xandora** [comment]
@jelewi90 This might not be something we can accommodate. Those Scrims were not made by a maintainer from the TOP team as far as I can tell, so we don't actually have any control over them. We will investigate though.

**Comment by Asartea** [comment]
After searching around, I think Scrimba doesn't support subtitles/captions at all natively, so there is no way for us to add it. There are workarounds involving browsers/extensions autogenerating them, but nothing that adds them to the scrim itself

**Comment by theSamyak** [comment]
Hi @jelewi90,

I tried adding captions to that tutorial on Scrimba, but as @Asartea mentioned that there is no way to add captions to Scrimba like on YouTube. I have sent them a report, and let's see if they do something about it. The good news is there are many great alternatives available. One such resource I know of is [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics).

But if you find documentation boring and prefer a more practical learning approach, we have:

[freeCodeCamp](https://www.freecodecamp.org/learn/2022/responsive-web-design/): You will learn HTML, CSS, and web design by reading and working on projects. This is a great resource, and you will also receive a certification upon completion.
Another option I can suggest, although slightly controversial, is [w3schools](https://www.w3schools.com/css/default.asp). It could be a great resource for beginners learning CSS.

If you face any difficulties anywhere please drop me an email(hellosamyakj@gmail.com) or maybe reach out to me on [twitter](https://twitter.com/OGsamyak). I wish you good luck in your journey to be a developer :)

**Comment by KevinMulhern** [comment]
Thanks for all those helpful suggestions @samyuii. 

Closing as theres nothing we can do on our end unfortunately.
