### ISSUE TITLE
Growing and Shrinking: Typo in Additional Resources link

### ISSUE THREAD

**Issue by Marmoss** [TheOdinProject/curriculum#28238]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is a typo in one of the links in the additional resources .
Specifically this one:
![image](https://github.com/TheOdinProject/curriculum/assets/56823130/7d04838b-358d-43f1-8013-d95dd9930bea)

The link is:
https://www.youtube.com/watchv=u044iM9xsWU&t=1s&pp=ugMICgJhchABGAE%3D

It should be:
https://www.youtube.com/watch?v=u044iM9xsWU&t=1s

As spotted by the keen eyed Nevz in the discord
![image](https://github.com/TheOdinProject/curriculum/assets/56823130/7b3481da-69fe-4ff0-adaa-f014b060c45d)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-growing-and-shrinking

### (Optional) Discord Name

Marmo

**Comment by MaoShizhong** [comment]
Good catch, assigning this to you so you can PR the link fix.
