### ISSUE TITLE
Installations: Add a link to Chrome keyboard shortcuts in additional resources

### ISSUE THREAD

**Issue by Sivasankar300** [TheOdinProject/curriculum#28236]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

As during the course of the curriculum the students here often use browsers for plenty of tasks, Learning keyboard shortcuts for particularly the "Tabs & Windows" section in [Here](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-window-shortcuts) seems like it might be a good idea.

Though it could work in one of the later lessons too but I'm not sure where else it would work by not feeling _too_ out of place. 

Especially since this lesson is for _Installations_ but it's also the only lesson where Chrome is explictly mentioned.
![image](https://github.com/TheOdinProject/curriculum/assets/155282396/fa243c58-3271-4c87-94bc-737b2a9d2510)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/paths/foundations/courses/foundations

**Comment by TheSeagullDev** [comment]
This makes sense, I'd be happy to work on this.

**Comment by TheSeagullDev** [comment]
This may have fallen through the cracks, can a maintainer please assign this issue to me?

**Comment by CouchofTomato** [comment]
@TheSeagullDev What are you thinking for the addition? Just a link to a resource on it? Or writing out a whole section?

**Comment by TheSeagullDev** [comment]
I'd add it to additional resources with a quick sentence or two explaining how one might find shortcuts useful considering how much chrome is used throughout the curriculum.

**Comment by CouchofTomato** [comment]
@TheSeagullDev That sounds reasonable to me. I'll assign it to you.
