### ISSUE TITLE
Ruby: Add lesson note about API key security to Event Manager Project

### ISSUE THREAD

**Issue by SumonGFC** [TheOdinProject/curriculum#28246]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Event Manager project of the "Files and Serialization" section of the Ruby course, we are given a public API key with which to access Google's Civic Information API. Although the key is public and although APIs are covered in the RoR course,  I think it would be beneficial to add a lesson note about API key security and privacy, and explain how to add a file (containing the key) to the git exclude file and then import the key from that file.

Edit: Although it is also possible to export an environment variable containing the key in shell rc file (or directly in current terminal session), as this lesson is already quite long I think this may be unnecessary overhead. Also, I opt for git exclude file and not `.gitignore` since, to my knowledge, the curriculum hasn't mentioned the `.gitignore` file at all up to this point and the exclude file is generated by default in `.git/info/`

Edit2: I propose the lesson note should explain:
- That the lesson directly embeds the key into the source code
- Why it is best practice to not directly expose your keys in source code or to source control
- Why it is fine that the keys given to us here are exposed publicly
- A method to make git not track certain files (`.git/info/exclude`)
- That the RoR course will cover "Working with External APIs"

Approximately one sentence for each point above and 2-3 commands/instructions for excluding the file and importing the key into the source code. I think the best place for this lesson note would be inserted on line 693 in [curriculum/ruby/files_and_serialization/project_event_manager.md](https://github.com/TheOdinProject/curriculum/blob/f13ab3f8b925d92b0fbe806f3b86e67e2ffacf00/ruby/files_and_serialization/project_event_manager.md?plain=1#L693)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-event-manager#iteration-3-using-googles-civic-information

### (Optional) Discord Name

Chindiana Jones

```[tasklist]
### Tasks
```

**Comment by JoshDevHub** [comment]
Strongly disagree with using anything other than `.gitignore` for this. It's just the standard way, and introducing it here isn't going to be anymore complicated than introducing `.git/info/exclude`. The latter is likely to cause more confusion when the learner later comes to realize that method isn't really used.

Other than that, this all seems good to me. I'll assign you to work on it. Let me know if you have any questions @SumonGFC

**Comment by SumonGFC** [comment]
Writing out each individual step to make a .gitignore file then add the file name pattern etc. is actually quite a lot, and since this lesson is already somewhat long I think it's probably best to just give a brief description of the process.
