### ISSUE TITLE
Revisiting Rock Paper Scissors: Additional resources <The second link is not working>

### ISSUE THREAD

**Issue by Mishiez** [TheOdinProject/curriculum#28243]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The second link on  the additional resources is not working it brings an error 503.
Here is the link:
https://ndpsoftware.com/git-cheatsheet.html#loc=index;

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors#additional-resources

### (Optional) Discord Name

mish9882

**Comment by JoshDevHub** [comment]
@Mishiez The link is currently working for me. Can you check and verify that it now works for you?

**Comment by xandora** [comment]
I was getting the 503 yesterday when I checked. Works correctly for me today. Looks like it might have been a temporary outage.

**Comment by JoshDevHub** [comment]
Yeah the 503 code generally indicates a temporary outage from maintenance-type stuff. I'm going to close this for now, but if you're still having trouble with the link, let me know and I'll reopen it @Mishiez

**Comment by Mishiez** [comment]
I just checked and it's working fine
