### ISSUE TITLE
Passing Data Between Components: Changing single quote to a double

### ISSUE THREAD

**Issue by ImmaCheetah** [TheOdinProject/curriculum#28248]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

There is a typo in the Passing Data Between Components lesson with the button example under "Using props in React". 

> What if we wanted the text within our second button to be “Don’t Click Me!’?

"Don't Click Me!' ends with a single quote rather than a double quote

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-passing-data-between-components#using-props-in-react

### (Optional) Discord Name

cheet.

**Comment by MaoShizhong** [comment]
Thank you for opening this issue @ImmaCheetah. Since you've specified you wish to be assigned to this, I will assign you to work on this.
