### ISSUE TITLE
Ruby: HashMap Project: Add new section to test user hash map

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/curriculum#28257]
### Description

In this [PR for the JavaScript course](https://github.com/TheOdinProject/curriculum/pull/28245), additions were made to make it easier for users to test their hash maps. These same additions need to made to the [Ruby version of this project](https://github.com/TheOdinProject/curriculum/blob/main/ruby/computer_science/project_hash_map.md) (with appropriate translations of the code examples).

### Lesson

[Ruby: Computer Science: Project Hash Map](https://www.theodinproject.com/lessons/ruby-hashmap)

**Comment by SumonGFC** [comment]
I can do it

**Comment by elishamutang** [comment]
Ah damn, I thought I was assigned to this haha.

@JoshDevHub sorry I forgot to comment on this issue as I thought I was already assigned without needing to actually comment on the issue. Totally misread your comment from the PR. Looks like @SumonGFC has already worked on it? I was about to create a PR but then I checked on this issue and looks like Sumon has just created a PR for it.

**Comment by SumonGFC** [comment]
@elishamutang ohhhh sorry I assumed that since Josh posted this issue that it was open. I read the previous PR/issue yesterday and saw that  the Ruby course still needed to be updated. But reading your linked PR now I see that new comments were added indicating that you were indeed assigned to this issue. Shall I unsubmit my PR then? (sorry again haha)

**Comment by SumonGFC** [comment]
@elishamutang closed my PR. You are now free to submit yours. I'll make sure to not repeat this mistake in the future. Sorry once again for the inconvenience.

**Comment by JoshDevHub** [comment]
@elishamutang Ah yeah sorry for the miscommunication. GitHub doesn't just let me assign any random user to an issue, so you needed to comment here in order for me to assign the issue to you. I should've made that more clear. I can assign you now since you've commented in this issue.

Sorry for the wasted work @SumonGFC :cry: 
In the future, please wait for a maintainer to assign the issue before beginning work and submitting a PR. That can help avoid situations like this.

**Comment by elishamutang** [comment]
@SumonGFC No worries man :)

@JoshDevHub Thank you!
