### ISSUE TITLE
Block and Inline: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Cub0p** [TheOdinProject/curriculum#28279]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a typo in addition resources content. It should be Learn CSS Layout is **a** tutorial not Learn CSS Layout is tutorial.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-block-and-inline

**Comment by CouchofTomato** [comment]
Thanks. Opening this up for others to work on.

**Comment by theSamyak** [comment]
> Thanks. Opening this up for others to work on.

Hi, can you assign it to me? please.

**Comment by CouchofTomato** [comment]
All yours @theSamyak

**Comment by theSamyak** [comment]
Hi @CouchofTomato, Thankyou for assigning me. But taking another look, I realize there aren't many easy-fix issues remaining in the TOP curriculum. Since this also doesn't seem like a critical issue, I think it would be a perfect learning opportunity for someone making their first contribution. Sorry if I caused you any trouble.

**Comment by CouchofTomato** [comment]
No worries. I've unassigned you @theSamyak 

If anyone else wants a crack at this let me know.

**Comment by carisaelam** [comment]
I am currently on the "Using Git in the Real World" lesson and would be interested in taking a crack at this one.

**Comment by CouchofTomato** [comment]
@carisaelam All yours. Let us know if you do need any support.
