### ISSUE TITLE
Intermediate Git: Change HEAD^ to HEAD~

### ISSUE THREAD

**Issue by SumonGFC** [TheOdinProject/curriculum#28273]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In [A Deeper Look at Git](https://www.theodinproject.com/lessons/ruby-a-deeper-look-at-git), we can see that in [this section](https://www.theodinproject.com/lessons/ruby-a-deeper-look-at-git#splitting-up-a-commit) we are instructed to use `HEAD^` to refer symbolically to the parent of `HEAD`, but everywhere else in the lesson (like [here](https://www.theodinproject.com/lessons/ruby-a-deeper-look-at-git#changing-multiple-commits) and [here](https://www.theodinproject.com/lessons/ruby-a-deeper-look-at-git#branches-are-pointers)) we use `HEAD~(n)` to refer to parent(s) of `HEAD`. Although functionally the same within the context of this lesson, the distinction between these selectors is not explained which can lead to some potential confusion. I think the simplest fix for this (if one is necessary) would be to replace the `HEAD^` in the "Splitting up a commit" section with just `HEAD~` and omit any mention of the caret selector. Otherwise, an additional resource like [this SO post](https://stackoverflow.com/questions/2221658/whats-the-difference-between-head-and-head-in-git) does a good job of explaining the distinction, if a little advanced.

If this is a valid issue, then it might be good first issue for someone to handle the PR.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/ruby-a-deeper-look-at-git

### (Optional) Discord Name

Chindiana Jones

**Comment by CouchofTomato** [comment]
Do you think it's worth adding the link as an additional resource maybe?

I agree with the other proposed change and happy to open this up since you don't want to work on it

**Comment by SumonGFC** [comment]
@CouchofTomato Thank you. Please open it up for someone to handle (I think it would be a good first issue for someone to submit their first PR for). 

If the `HEAD^` is changed to `HEAD~`, then I actually don't think it is worth adding the SO post as an additional resource since the lesson would then make no mention of `HEAD^`.
If the `HEAD^` is left unchanged, then I do think the SO post as an additional resource would be necessary.
I am in favour of the former solution (changing `^` to `~`) as I think it is the most simple.

**Comment by mathdebate09** [comment]
Hey I'd love to work this issue up. Also, i agree with the simpler approach of just changing `HEAD^` to `HEAD~` & the additional resource turns out to to be redundant if there's no mention, and it looks like something that could be easily found by searching around SO

**Comment by SumonGFC** [comment]
@CouchofTomato please feel free to assign @mathdebate09 to this issue.
