### ISSUE TITLE
Express 105: Forms and Deployment: Include warning about Glitch's supported node versions

### ISSUE THREAD

**Issue by DrantDumani** [TheOdinProject/curriculum#28288]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

This lesson concludes the MDN Express Library tutorial, which instructs learners to deploy their library to Glitch. MDN mentions including the node version in the package.json file like so:

```js
  "engines": {
    "node": ">=16.17.1"
  }
  ```
However, it neglects to mention that glitch only supports up to node version 16.14. When assigning an engine greater than what glitch supports, it automatically and silently defaults to node v10, which confuses users who were following the tutorial to the letter by causing their deployment to break completely.
  
I believe that the assignment in this lesson should give a short warning about this in Glitch, as it only serves to confuse users who have been following the given MDN tutorial to the letter so far, especially since Glitch is not listed as one of the suggested services in the earlier Deployment lesson.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-express-105-forms-and-deployment

### (Optional) Discord Name

Elemeandor

### (Optional) Additional Comments

I would like to work on this issue.

_No response_

**Comment by MaoShizhong** [comment]
Thanks for opening this issue.
The MDN tutorial addresses this in the relevant part for Glitch deployment: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#troubleshooting_node.js_version

This was fixed on MDN's side in (https://github.com/mdn/content/pull/32695) 2 days ago.

Since no further action is required on our end, I'll close this issue.
