### ISSUE TITLE
More On State: Refactor code example to use better function naming principles.

### ISSUE THREAD

**Issue by kahmoh** [TheOdinProject/curriculum#28281]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the opening code example, and throughout we define and use a function called handleIncreaseAge. I believe this could follow a better naming convention by simply being called increaseAge. I remember earlier in the curriculum seeing a suggestion about words such as handle and handler not providing much to function names. This serves as a good example of naming convention for learners reading the lesson.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-more-on-state

### (Optional) Discord Name

kahmoh

**Comment by JoshDevHub** [comment]
@kahmoh Thank you for making this issue.

Can you point to where earlier in the curriculum it was suggested that you avoid the word `handle`?

**Comment by kahmoh** [comment]
@JoshDevHub Ive had a look around for the article I saw and couldn't seem to find it. Perhaps I saw it from my own research or it has been changed. Thanks for checking out this issue though!
