### ISSUE TITLE
Ruby On Rails: PostgreSQL Databases Offering Free Plans

### ISSUE THREAD

**Issue by DiptoSarkar182** [TheOdinProject/curriculum#28297]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the Deployment lesson of the Ruby On Rails course, I suggest adding a section titled "PostgreSQL Databases Offering Free Plans."

##### PostgreSQL Databases Offering Free Plans

- [Neon](https://neon.tech/)
- [Supabase](https://supabase.com/)
- [Koyeb](https://www.koyeb.com/)
- [Aiven](https://aiven.io/)

I found these database services offering free plans, which I believe would be immensely beneficial for fellow learners. This addition would provide learners with valuable resources to deploy their projects fully for free without any payment and credit card using [Render](https://render.com/) and any of the database service from above.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-deployment

### (Optional) Discord Name

noodlepudding

**Comment by CouchofTomato** [comment]
I think this will be too confusing for people just learning rails. Having to use a db not connected to their rails service provider is going to take them way outside their comfort zone for no benefit at this time.

Unless you think you have an easy explanation we can add?

**Comment by DiptoSarkar182** [comment]
> I think this will be too confusing for people just learning rails. Having to use a db not connected to their rails service provider is going to take them way outside their comfort zone for no benefit at this time.
> 
> Unless you think you have an easy explanation we can add?

Thank you for your feedback. I understand the concern about introducing complexity for learners new to Rails. To address this, can I provide a guide on how to deploy project in render with an external database?

**Comment by CouchofTomato** [comment]
The issue is probably going to be that over time services change and so the guide could become outdated.

**Comment by DiptoSarkar182** [comment]
> The issue is probably going to be that over time services change and so the guide could become outdated.

You are correct. I did not think that issue. It is indeed going to create problem when some services change their plan.
