### ISSUE TITLE
A Deeper Look at Git: Restructure code block

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#28298]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the lesson file for the "A Deeper Look at Git" lesson, we have a [bash code block](https://github.com/TheOdinProject/curriculum/blob/a540c6b9564085db0e5b09b522b5d823a4a60812/git/intermediate_git/a_deeper_look_at_git.md?plain=1) that contains things that should not be in that code block (not bash syntax and would be better outside of the code block). This also happens to result in some funky syntax highlighting when viewing the file on GitHub.

## Acceptance criteria

Please comment below if you wish to be assigned to work on this issue. Please do not being work until you have actually been assigned by a maintainer.

- [ ] The following change should be made:
  ````md
  ```bash
  You can amend the commit now, with
         git commit --amend
  Once you're satisfied with your changes, run
         git rebase --continue
  ```
  ````
  Should be replaced with
  ````md
  ```bash
  git commit --amend
  ```

  The command above will allow you to amend the commit. Once you're satisfied with your changes, you can complete the rebase with the following:

  ```bash
  git rebase --continue
  ```
  ````

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/ruby-a-deeper-look-at-git or https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

### (Optional) Additional Comments

Even though each pathway has a different URL, they share the same lesson file, so this change is only necessary for the one file.

**Comment by carisaelam** [comment]
Hi @MaoShizhong. I can clean this one up.

**Comment by MaoShizhong** [comment]
All yours!
