### ISSUE TITLE
Project Management: Adjust link of first assignment

### ISSUE THREAD

**Issue by lksae** [TheOdinProject/curriculum#28300]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

Link of first assignment leads to 404 error: https://github.com/ericmathison/articles/blob/master/understaning-require-in-ruby.md

It should be replaced with https://ericmathison.io/articles/require if this is the correct article.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-project-management

**Comment by mathdebate09** [comment]
An easier fix would be just fixing the typo error for the letter *understaning* to **understanding**, and the markdown preview works fair enough imo instead of the blog link (which might have hosting outages).

**Comment by lksae** [comment]
I totally agree with you. I didn't see the typo error.

**Comment by MaoShizhong** [comment]
Good spot. Assigning you @lksae to fix the typo in the link

**Comment by lksae** [comment]
Done
https://github.com/TheOdinProject/curriculum/pull/28311
