### ISSUE TITLE
Motivation and Mindset: Assignment link goes nowhere

### ISSUE THREAD

**Issue by mysticole928** [TheOdinProject/curriculum#28304]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the assignment section, the first option:

> To give your motivation a bit of a boost, read about the success of others in the [TOP Discord server’s Success Stories forum](https://discord.com/channels/505093832157691914/1089990025162260570).

The link opens Discord but goes nowhere.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-motivation-and-mindset

**Comment by MaoShizhong** [comment]
I am unable to replicate this on my computer or mobile, as clicking that link opens Discord and takes me straight to the success stories forum.

Can you confirm whether you've got a discord account and have joined The Odin Project's discord server?

**Comment by mysticole928** [comment]
In a subsequent lesson, there was a link to connect to Discord and connect to GitHub.

This lesson: https://www.theodinproject.com/lessons/foundations-join-the-odin-community


[https://www.theodinproject.com/assets/og-logo-dc2c719e367496ffaee876882b3f62c9b139279824de6a6e16448398fa513f7a.png]<https://www.theodinproject.com/lessons/foundations-join-the-odin-community>
Join the Odin Community | The Odin Project <https://www.theodinproject.com/lessons/foundations-join-the-odin-community>
The Odin Project empowers aspiring web developers to learn together for free
www.theodinproject.com

I was able to use that link to connect with Discord.

I (just now) went back went back to check that first lesson, the link for Discord now works.

I don't know if it's because I logged into or not.

Thanks for looking into it.



________________________________
