### ISSUE TITLE
Javascript Course: Update outdated instruction under Dynamic User Interface Interactions

### ISSUE THREAD

**Issue by JackBogart** [TheOdinProject/curriculum#28313]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Previously `Dynamic User Interface Interactions` had three assignments for a user to build. However #27846 removed one of them for mobile responsiveness as it was out of scope. There was a small inconsistency missed as a side effect of removing the assignment. The instructions for [Build an image carousel](https://www.theodinproject.com/lessons/node-path-javascript-dynamic-user-interface-interactions#build-an-image-carousel) are slightly outdated for step 1, as it says `This one is a little more involved than the last two...` despite only one assignment prior.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-dynamic-user-interface-interactions

### (Optional) Discord Name

colonelchicken

### (Optional) Additional Comments

Wasn't sure if I should make an issue for this or just make the PR considering it definitely needs to be changed.

**Comment by MaoShizhong** [comment]
Good spot! Assigning you to fix this.

An issue is perfectly fine. If you did make a PR fixing this, since it's small and an obvious bug fix, that'd also have been fine - doesn't matter too much either way in this case.
