### ISSUE TITLE
Ruby: Provide instructions on testing certain projects

### ISSUE THREAD

**Issue by Grayvox** [TheOdinProject/curriculum#28318]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I've noticed that a recent change to the Ruby course content includes instructions on testing the HashMap you create in the HashMap project. I thought this was a great addition, but feel as though it'd be a good idea to consistently give info on doing this for other projects where it's missing. Specifically:

- Recursion
- Linked Lists
- Knight Travails

This, of course, becomes irrelevant to add in projects further down when RSpec is introduced officially later in the course. Still I feel like it might be better to offer consistency in testing the projects (Perhaps providing the "Live preview" button on the projects I mentioned as well?) prior to getting into that. 

Would love to discuss thoughts on this!

### Path

Ruby / Rails

### Lesson Url

All the projects I listed.

### (Optional) Discord Name

delldasharky

**Comment by CouchofTomato** [comment]
A test is used in the hashmap to show how the load balance changes. It's called a test but really this is just showcasing that it works as expected so learners get to visualise better how a hashmap works.

How do you propose testing the other projects in a similar way?

**Comment by Grayvox** [comment]
> A test is used in the hashmap to show how the load balance changes. It's called a test but really this is just showcasing that it works as expected so learners get to visualise better how a hashmap works.
> 
> How do you propose testing the other projects in a similar way?

Recursion wouldn't be much considering it's just a Merge Sort and a couple Fibonacci method - but testing could be writing a series of puts statements in the main file to showcase that both versions of Fibonacci methods work exactly the same, and that the Merge Sort works correctly with a few cases of numbers.

For Linked Lists - testing each method under certain conditions (like using `#at(index)` with a negative number, for example) so the student can solve the problem and, ergo, write more fault tolerant code. 

For Knight Travails - there is already some written out code (for the fact that there can be one or more possible answers) and what it *should* result in, so that could just be tweaked to be a full on section in that project for writing out tests (or could just leave it alone for that one).

I understand if this seems a bit unnecessary for those projects, or less useful for certain ones I listed - though I will say this could lead the student to write more fault tolerant code if there is set things they have to watch out for written out in tests.

**Comment by CouchofTomato** [comment]
I get you. We'd love to have some actual prescribed tests, but that would push each learner to use the code structure and setup method we recommend which might help in some ways, but would also make it more difficult in others.

But I do think the proposed tests as described aren't really doing the same thing as the hash map section. The point of that is to illustrate a key concept of hashmaps, the balancing of the buckets.

So for recursion I could maybe see an example which shows in terminal output the execution flow of recursion, rather than just verifying their code works.

However I'm not against having a few examples for each of those exercises showing some example inputs and the expected outputs if they aren't already there.

**Comment by Grayvox** [comment]
> However I'm not against having a few examples for each of those exercises showing some example inputs and the expected outputs if they aren't already there.

Understood! I think offering some examples with expected outputs definitely makes more sense. If it's alright with you I'd like to be assigned the issue and can work on the examples as soon as possible.

**Comment by CouchofTomato** [comment]
@Grayvox All yours.

**Comment by Grayvox** [comment]
@CouchofTomato Upon thinking about it more and seeing the project - do you feel that Knight Travails even needs these exercises considering it has this section in it already? 
![image](https://github.com/TheOdinProject/curriculum/assets/144566632/b52fe693-9a2f-4dc9-b206-c0b2190add35)
I feel like this pretty much covers what you said makes sense and may deem another section on "examples of what should work" somewhat pointless. Thoughts?
