### ISSUE TITLE
Installations: Clarify that copy pasting should happen in the VM

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#28325]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Ever since a robust explanation of copy-pasting into the Terminal has been added to the Linux instructions the amount of VM users having issues with copy-pasting has increased by a lot. 

While this reduced the amount of people mistyping commands, it seems like the many sentences that tell learners that they should do everything in the VM after they set it up are not effective.

To complicate things, ever since TOP dropped Firefox support people are unaware that Xubuntu comes with a Web Browser. And perhaps ironically, it is a required part of the curriculum now to use something that it does not support.

There are potentially multiple avenues to explore that I can think of:
1. Separate VM instructions so they can explicitly call out opening Firefox inside the VM and copying from there.
2. In the setup instructions' Step 4 add a substep that asks the learner to close TOP in their Windows browser and to open it in the VM. Reiterate that from this point onwards they're supposed to follow Linux instructions while going through TOP.
3. Edit the copy-paste note box to include the VM exception.

I'm probably a fan of 2. because it feels the most natural for the flow of the instructions and it does not bloat the Chrome installation instructions further.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

**Comment by scheals** [comment]
Aye, this is coming up a lot in Discord. Probably the number one issue right now, actually. Not that I keep a tally.

VMs do support more than one screen - right now the problem is getting people to open TOP in their VM, they just keep going with the page open on Windows side and VM in a window, seems like. If they had the lesson open in the VM, they'd never have the problem.

**Comment by CouchofTomato** [comment]
Thanks for clarifying :)

I agree step 2 is probably the easiest to implement. I assume you're happy for me to open this up for others to work on?

**Comment by CouchofTomato** [comment]
thanks @scheals 

If anyone wants an easy contribution please let me know 🙏

**Comment by LAKSHYA201** [comment]
Hi @CouchofTomato , I had like to work on this issue.

**Comment by MidlifeMechanicus** [comment]
How timely! I just hit the Using Git in the Real World lesson, so I've opened a pull request on this issue.
