### ISSUE TITLE
Factory Functions and the Module Pattern: Broken link in Knowledge Check section

### ISSUE THREAD

**Issue by dot-sky** [TheOdinProject/curriculum#28324]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the [Factory Functions and the Module Pattern](https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#knowledge-check) lesson there's a broken link on the "Knowledge check" section. The "Describe IIFEs and what they stand for." bullet point currently links to [this page](http://adripofjavascript.com/blog/drips/an-introduction-to-iffes-immediately-invoked-function-expressions.html) which only shows an "Account suspended" message.
The link could be replaced with a link to this section of the lesson: [The module pattern - IIFEs](https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#the-module-pattern-iifes), because it contains the necessary content to answer the question.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern

**Comment by MaoShizhong** [comment]
Agreed on the resolution for this, assigning you since you specified you wish to work on this.
