### ISSUE TITLE
Linting and RuboCop: Unclear line, or weird phrasing.

### ISSUE THREAD

**Issue by McHeph** [TheOdinProject/curriculum#28335]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

there is a line that's unclear what it means: "Don’t forget the it must a dotfile, meaning it needs to have a dot before its name."
Maybe "The it must a dotfille" is supposed to be "That it must be a dotfile"?
This line is on the 6th paragraph under "Power Corrupts".

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-linting-and-rubocop

### (Optional) Discord Name

hephy_

**Comment by CouchofTomato** [comment]
Thanks for picking this up. Please go ahead with a fix.
