### ISSUE TITLE
<JS Recursive Methods>: <Clarify why code quiz question 6 is less incorrect and more incomplete>

### ISSUE THREAD

**Issue by stephspace** [TheOdinProject/curriculum#28341]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

TOP states in the recursive methods lesson that the “Question 6: Search JS object” solution is incorrect and provides a link to a different solution. I think It will be more helpful if it states that the code quiz solution is less "incorrect" and more "incomplete" since it does not account for null or objects with more properties.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods

### (Optional) Discord Name

return true

**Comment by MaoShizhong** [comment]
Agreed that the current wording with "incorrect" might be a little confusing for people when they can still see the "incorrect" solution provides the expected outcome for the exercise's test case. "Incomplete" feels more appropriate to me.

I'm wondering if instead of providing the explanation for why (not accounting for `null` and sibling properties) in the note box itself, we simply change "incorrect" to "incomplete" (or some wording that says it doesn't work for all test cases), and provide the brief context in the gist itself?

@JoshDevHub thoughts?

**Comment by JoshDevHub** [comment]
I think that all sounds like a good plan to me @MaoShizhong 

I'll assign @stephspace to work on a PR where "incorrect" is changed to "incomplete." I'll add some comments to my gist that mention the cases that are solved by the gist's solution :thumbsup:

**Comment by JoshDevHub** [comment]
Added some comments to [the gist](https://gist.github.com/JoshDevHub/b00125f483d4a1ecc257eaa030916973)

Let me know if you think anything should be edited with it @MaoShizhong @stephspace

**Comment by stephspace** [comment]
> I think that all sounds like a good plan to me @MaoShizhong
> 
> I'll assign @stephspace to work on a PR where "incorrect" is changed to "incomplete." I'll add some comments to my gist that mention the cases that are solved by the gist's solution 👍

Done 👍

**Comment by MaoShizhong** [comment]
> Added some comments to [the gist](https://gist.github.com/JoshDevHub/b00125f483d4a1ecc257eaa030916973)
> 
> Let me know if you think anything should be edited with it @MaoShizhong @stephspace

What do you think about if we reframe the loop comment to be explicit that `return contains()` will only check the first property of an object and not any others? As opposed to that it creates a problem with searching all values. e.g. something like:
```js
    // an important problem in the code quiz solution is that `return contains()` will only
    // search the first property of an object, as it will return whatever the result for it is.
    // If our value was nested within the second property, for example, it would never get checked
    // even if the first nested object did not contain it.
```

**Comment by JoshDevHub** [comment]
Agree on your wording @MaoShizhong :raised_hands: 

Updated the gist

**Comment by MaoShizhong** [comment]
Brilliant - all good once we can merge the PR :tada: Thanks, Josh.
