### ISSUE TITLE
Setting up Git: The link given in additional resources doesn't work

### ISSUE THREAD

**Issue by cmkaya** [TheOdinProject/curriculum#28357]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The link name [Understanding SSH Key Pairs](https://winscp.net/eng/docs/ssh_keys) doesn't work. I think there should be a different resourse related to SSH key pairs.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

**Comment by KevinMulhern** [comment]
Thanks for reporting @cmkaya, it's working for me at the moment. That site may have been down when you tried it, can you confirm if it's still not working for you please?

**Comment by xandora** [comment]
ERR_CONNECTION_REFUSED indicates that your network, your ISP, or perhaps the website itself is blocking you from viewing this resource.

**Comment by MaoShizhong** [comment]
@cmkaya Are you able to confirm if this is still an issue on your end, given the above?

**Comment by cmkaya** [comment]
@MaoShizhong Yes, I still have the problem. But maybe it is because of me. I don't understand.
