### ISSUE TITLE
A Very Brief Intro to CS: <Enhancement of resource: Introduction to DSA>

### ISSUE THREAD

**Issue by NewDev2005** [TheOdinProject/curriculum#28364]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Video: https://youtu.be/xWLxhF3b5P8?si=GcZRBhMo3kz30KDu
Timestamps: **0:00 - 7:01** (What are Data structures and Algorithm?)

This Tutorial has done a great job in explaining the true need of data structures and algorithm.like what are data structures and algortithm, why we need to know about data structures and algorithm, why compaines are looking for  candidates who know data structures and algorithm and How we can use the knowledge of data structures and algorithm to improve the performance and efficiency of the application.These topics are discussed in the video to clear all the doubts regarding the DSA in the timestamp of what are data structures and algorithm.

I kindly request the maintaners to take a look at the tutorial.
Thank you.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-a-very-brief-intro-to-cs

### (Optional) Discord Name

Htmx

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @nikitarevenco, can someone from the @TheOdinProject/ds-a team take a look at this please?

**Comment by JoshDevHub** [comment]
@NewDev2005 Thank you for making this suggestion.

I think this is a really cool resource and at just 7 minutes, it's pretty short and to the point as well. It also covers some ideas that are not present in other pieces of the assignment. I'll open this up for contribution.

### Acceptance Criteria
- [ ] In the [Ruby Course's Intro to CS Lesson](https://www.theodinproject.com/lessons/ruby-a-very-brief-intro-to-cs), add a new item in the `Assignment` section with the video above. It can say something like:
```md
1.  Watch the first section (from 0:00 - 7:01) of [Telusko's video on Data Structure's and Algorithms](https://www.youtube.com/watch?v=xWLxhF3b5P8) for a quick overview of Data Structures and Algorithms and why companies may be interesting in hiring candidates familiar with DSA.
```
- [ ] In the [JavaScript Course's Intro to CS Lesson](https://www.theodinproject.com/lessons/javascript-a-very-brief-intro-to-cs), add this same item to the `Assignment` section

Comment below to be assigned.

**Comment by MaoShizhong** [comment]
@owen-makes tagging so I can assign you to the issue as discussed in your PR.
