### ISSUE TITLE
Conclusion: Broken link

### ISSUE THREAD

**Issue by Gohan61** [TheOdinProject/curriculum#28388]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The link to Droplets under the DevOps section is broken [Droplets](https://docs.digitalocean.com/products/droplets/quickstart) The correct link is now [Correct link](https://docs.digitalocean.com/products/droplets/getting-started/quickstart/)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-conclusion

### (Optional) Discord Name

gokhan.reads

**Comment by JoshDevHub** [comment]
Nice find @Gohan61 

Should be simple enough to replace the link with the working one. Since you've indicated you'd like to work on this, I'll assign you. Let me know if you have any questions.
