### ISSUE TITLE
Authentication Basics: Fix Typos/Syntax

### ISSUE THREAD

**Issue by matthewaubert** [TheOdinProject/curriculum#28389]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

- `sign-up-form.ejs` code block: Missing `id` attributes in `input` elements
- Second sentence of "Authentication" section: Missing punctuation
- Passport code blocks: Incorrectly-placed semi-colons (e.g. after curly braces in `if`, `try/catch` statements)
- 4th paragraph of "Storing hashed passwords": Typo or unclear word in "Usually, the salt gets stored in the database in the **clear** next to the hashed value..."
  - Perhaps this should instead say something like "Usually, the salt gets stored in the database ~~in the clear~~ next to the hashed value..."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-authentication-basics

### (Optional) Discord Name

SlightlyQuixotic

**Comment by MaoShizhong** [comment]
Sensible spots - assigning you to this.
