### ISSUE TITLE
Sending Confirmation Emails: Add WSL instructions to setup letter_opener gem

### ISSUE THREAD

**Issue by AhmedTheGreatest** [TheOdinProject/curriculum#28386]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the project "Sending Confirmation Emails" of the Ruby on Rails course, it asks us to use the `letter_opener` gem. I had trouble trying to use it with WSL. After some time, I found the solution was to add the following to `config/environments/development.rb`:

```ruby
LetterOpener.configure do |config|
  config.file_uri_scheme = 'file://wsl.localhost/Ubuntu'
end
```

Additionally, I added the following to `~/.bashrc` to set the browser path so Launchy can detect it and open the email:

```bash
export BROWSER=/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe
```

The first snippet of code defines the `file_uri_scheme` for WSL, and the second one sets the browser path so Launchy can detect it and `letter_opener` can open the email.

I suggest that this fix for the issue be added to the project "Sending Confirmation Emails".

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-sending-confirmation-emails

### (Optional) Discord Name

tornado_77

**Comment by JoshDevHub** [comment]
Sounds like a nice fix to me. Thank you for making this issue @AhmedTheGreatest 

Since you indicated you'd like to work on this, I'll assign you. Let me know if you have any questions.

**Comment by AhmedTheGreatest** [comment]
Thanks! I'll hopefully work on this tomorrow!

**Comment by AhmedTheGreatest** [comment]
I have a question, should the information above be in something like a notebox or some other container?

**Comment by JoshDevHub** [comment]
> I have a question, should the information above be in something like a notebox or some other container?

I think a notebox sounds good to me.

**Comment by AhmedTheGreatest** [comment]
I am so sorry that I have not been able to work on this. I will try my best to create a pull request soon.
