### ISSUE TITLE
Ruby on Rails: Fix outdated event name in Websockets and ActionCable lesson

### ISSUE THREAD

**Issue by AhmedTheGreatest** [TheOdinProject/curriculum#28383]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is a mention of an outdated event name `turbolinks:load` in the Websockets and ActionCable lesson. Turbo Links is now replaced with, and is a part of Hotwire Turbo.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-websockets-and-actioncable

### (Optional) Discord Name

tornado_77

**Comment by JoshDevHub** [comment]
Nice find. I'll assign  you to work on it @AhmedTheGreatest

**Comment by AhmedTheGreatest** [comment]
Thanks @JoshDevHub I will try my best to do these issues within couple of days.
