### ISSUE TITLE
Connect Four: Change order of assignments

### ISSUE THREAD

**Issue by MidlifeMechanicus** [TheOdinProject/curriculum#28385]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The current assignment order currently includes the following as the first two steps: 

>1. Go back to the [Caesar Cipher Project](https://www.theodinproject.com/lessons/ruby-caesar-cipher) and write tests for your code. It shouldn’t take more than a half-dozen tests to cover all the possible cases. As always, use the git workflow you learned in [this foundations lesson](https://www.theodinproject.com/lessons/foundations-revisiting-rock-paper-scissors) to work on a new feature so you can work on your new code without fear.
>2. Clone [this repo](https://github.com/TheOdinProject/ruby_testing) and complete the lessons in the spec folder.

I would suggest reversing the order of these two steps. The information in step 2 would have made the work in step 1 much, much easier, and changed the way I handled step 1.

Examples include:

1. Being encouraged to refactor old code that was written prior to the testing lesson in order to make tests more manageable.
2. Explaining that functions that only include a get or put do not need to be tested.
3. Explaining the use of #stub to pass user inputs through functions.
4. The Arrange-Act-Assert workflow.

I think that students would benefit from being told to complete the lessons before being told to write tests for their Caesar Cipher project.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-connect-four

**Comment by JoshDevHub** [comment]
This makes perfect sense to me. Thank you for raising this issue @MidlifeMechanicus 

Since you indicated you'd like to work on this change, I'll assign you. Please let me know if you have any questions.
