### ISSUE TITLE
Markdownlint: Ensure checks only run when required

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#28432]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

My understanding of the current system for markdownlint (please correct me if I'm wrong) is that it works roughly like this:

- There is a single workflow, defined in `markdownlint.yml`, which uses an `on` filter to run for every pull request
- This workflow contains two jobs, which do the linting for lesson and project files respectively
- Each of these starts up a new Ubuntu instance, checks out the changes made in the PR, and then uses a GitHub action (`changed-files`) with a series of glob patterns to figure out if the PR touches a lesson/project file.
- If this is the case, it then runs the associated checker over the files found in the previous step

This has two major issues:
1) The first part of each job _always_ runs, even if it turns out we don't actually need it, including warming up, etc
2) If the PR only touches files of one of the types (intuitively I would assume that this is the case for the vast majority of PRs, which usually only touch a single file) this generates fake passed test results because the job that got skipped still counts as a successful test

GitHub however, also has its own built-in way of checking which files got affected, using a [`on.pull_request.paths`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) filter. Using this, the current glob patterns could be pulled into a filter statement at the very start, which would ensure that the workflow only starts up when required.

Unfortunately enough, this only works on a workflow level, so the current workflow file would need to be split into two different files, one for each type. On the other hand, the current shared functionality is basically zero, so this would not lead to a noticeable increase in code duplication 

### Path

Other / NA

### Lesson Url

N/A

### (Optional) Discord Name

asarta

**Comment by wise-king-sullyman** [comment]
Sounds like a solid change to me, thanks!

CC @thatblindgeye since the markdown lint stuff is your baby and I'm curious if you know something I don't about how the workflows were setup.

**Comment by Asartea** [comment]
> CC @thatblindgeye since the markdown lint stuff is your baby and I'm curious if you know something I don't about how the workflows were setup.

Ref https://discord.com/channels/505093832157691914/1124433492273545316/1262893834006954125 it doesn't seem like it, will  file a PR shortly
