### ISSUE TITLE
Installing Ruby: Outdated outcome messages of rbenv init

### ISSUE THREAD

**Issue by hebiscus** [TheOdinProject/curriculum#28436]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Rbenv got an update 2 months ago and message after running `rbenv init` has changed. In the lesson at #step-22-install-rbenv two outcome messages are now incorrect, which puzzles people.

I think instead of relying on the content of an outcome message, verifying if rbenv got installed correctly with `rbenv -v` would be better.

Specific commit with those changes in rbenv repo: https://github.com/rbenv/rbenv/commit/c3ba994ec2daccf4d160aea7f55dd5cc6fc873ef

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

### (Optional) Discord Name

hebiscus.

**Comment by JoshDevHub** [comment]
Hi thank you for making this issue @hebiscus !

We really just need to straight up change how the curriculum does this. Hopefully you're still up for making that PR!

The `rbenv init` script now automatically writes the necessary PATH updates to the user's shell profile. This means that after cloning the rbenv repository, users can just run `~/.rbenv/bin/rbenv init` in their terminal and everything will automatically be set up from there. There's no longer any need to run any of those `echo "eval blahblahblah"` commands. 

The user does still need to ruby-build, so don't touch those instructions.

Since you indicated you'd be okay with working on this, I'll assign you. Definitely let me know if you have any questions or any of the things I'm requesting are unclear to you. I'm very glad to help or explain more!

**Comment by JoshDevHub** [comment]
Any update on this @hebiscus ?

**Comment by hebiscus** [comment]
@JoshDevHub Will be taking care of this in the upcoming days, Sunday the latest

**Comment by beneficial-radish** [comment]
Hi. I had this issue as well, found the solution in the README, and was encouraged to contribute the solution. I was about to submit my pull request, but I guess since it's already been assigned, it will simply be cancelled without review if I try to submit it. This is my first time trying to contribute, so I guess it's good learning this lesson on something that was only two lines!

**Comment by beneficial-radish** [comment]
Oh! Hold up. It looks like this issue was closed without the instructions being modified? The init command is still the same.; doesn't match ~/.rbenv/bin/rbenv init

**Comment by Eduardo06sp** [comment]
@CouchofTomato I just tried following the exact steps for installing Ruby on Linux (https://www.theodinproject.com/lessons/ruby-installing-ruby).

Indeed, I ran into the issue multiple people said they ran into.

I had to run
```bash
~/.rbenv/bin/rbenv init
```

then right after that,
reset my terminal.

I know I'm kind of repeating some of the same thing,
but I wanted to assure you that with these changes,
it worked on a VM I fired up running a freshly installed Ubuntu 24.04 LTS.

**I have no idea if the MacOS instructions need to be updated.** I can test it on a Macbook if you need me to.

**Comment by beneficial-radish** [comment]
> @CouchofTomato I just tried following the exact steps for installing Ruby on Linux (https://www.theodinproject.com/lessons/ruby-installing-ruby).
> 
> Indeed, I ran into the issue multiple people said they ran into.
> 
> I had to run
> 
> ```shell
> ~/.rbenv/bin/rbenv init
> ```
> 
> then right after that, reset my terminal.
> 
> I know I'm kind of repeating some of the same thing, but I wanted to assure you that with these changes, it worked on a VM I fired up running a freshly installed Ubuntu 24.04 LTS.
> 
> **I have no idea if the MacOS instructions need to be updated.** I can test it on a Macbook if you need me to.

It looks like the mac instructions may have changed as well. 

> @CouchofTomato I just tried following the exact steps for installing Ruby on Linux (https://www.theodinproject.com/lessons/ruby-installing-ruby).
> 
> Indeed, I ran into the issue multiple people said they ran into.
> 
> I had to run
> 
> ```shell
> ~/.rbenv/bin/rbenv init
> ```
> 
> then right after that, reset my terminal.
> 
> I know I'm kind of repeating some of the same thing, but I wanted to assure you that with these changes, it worked on a VM I fired up running a freshly installed Ubuntu 24.04 LTS.
> 
> **I have no idea if the MacOS instructions need to be updated.** I can test it on a Macbook if you need me to.

I tagged you in the discord before thinking about linking this message here. I don't have a MacBook available to me, but I ran a search in the Ruby Help channel and found this from 7/29. Seems like it might be related to the recent update as well, but I can't be sure without seeing what they were looking at. 
https://discordapp.com/channels/505093832157691914/543074220691947531/1267441895382978631

**Comment by Eduardo06sp** [comment]
@beneficial-radish the solution for that user's issue was to add Homebrew to their PATH variable I believe.

on the Installing Ruby lesson, for MacOS, it tells you to:
> If it outputs a certain path, you’re good to go ahead! But if the terminal reads brew not found, please go through the [MacOS instructions in the setting up git lesson](https://www.theodinproject.com/lessons/foundations-setting-up-git) to get homebrew installed.

Once you go through that, there should be a message that tells you how to add Homebrew to your PATH, which, again, seems to solve this issue.

Additionally, there is a note on the Setting up Git lesson that reads:
> :warning: On an Apple Silicon Mac, you will have an extra step to take. If you look at the terminal output after installing Homebrew, you will see “Installation Successful!”. Further down in the terminal, there will be a section called “Next steps”. Reading the terminal may seem a bit intimidating, but this is a great chance to overcome those feelings. Follow the next steps as stated in your terminal (copy and paste the commands given) to add Homebrew to your PATH, which allows you to use the brew command prefix.

It is unclear to me if this is something that will happen every time, or only to certain users.

**Comment by beneficial-radish** [comment]
Gotcha. I haven't messed with MacOS on that level, so I wasn't sure if it was related to the new way that rbenv behaves.
