### ISSUE TITLE
Pattern Matching: Typo in "Array pattern match"

### ISSUE THREAD

**Issue by Adamnson** [TheOdinProject/curriculum#28445]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

 There is a sentence in the "Array pattern match" section that doesn't make much sense : This is where the as pattern can be used.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-pattern-matching

### (Optional) Discord Name

adamnson

**Comment by JoshDevHub** [comment]
What would be your suggested change for that content?

It's referring to the "As Pattern", which is already referenced multiple times in the lesson and has [its own section](https://www.theodinproject.com/lessons/ruby-pattern-matching#as-pattern-match) describing what it is.

**Comment by Adamnson** [comment]
You're right, I figured it out a little later.
