### ISSUE TITLE
Conclusion: Remove/update the relational data section 

### ISSUE THREAD

**Issue by royalh23** [TheOdinProject/curriculum#28452]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Conclusion lesson still references the old material about relational databases. Since the Node course has been updated recently, this section should either be removed or updated (e.g. you might want to look into MongoDB, which is a popular non relational database, etc.) 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-conclusion

**Comment by aaelsay3d** [comment]
Can this be a possible update?

Now that you have exposure to relational databases with PostgreSQL, you might be considering what other types of databases exist; namely non-relational databases. Understanding both types of databases and when to use them can set you up for success down the road. After all, not every problem requires a hammer. MongoDB is a popular choice for non-relational databases. Resources like [learn.mongodb.com](https://learn.mongodb.com/) offer tutorials and documentation to get you started.

**Comment by MaoShizhong** [comment]
All yours @royalh23

**Comment by royalh23** [comment]
> All yours @royalh23 

Thanks. Will make a PR in the morning

**Comment by royalh23** [comment]
> Can this be a possible update?
> 
> Now that you have exposure to relational databases with PostgreSQL, you might be considering what other types of databases exist; namely non-relational databases. Understanding both types of databases and when to use them can set you up for success down the road. After all, not every problem requires a hammer. MongoDB is a popular choice for non-relational databases. Resources like [learn.mongodb.com](https://learn.mongodb.com/) offer tutorials and documentation to get you started.

Looks good.

**Comment by MaoShizhong** [comment]
@royalh23 When you're at it, could you also change the end of the first paragraph so instead of saying 

> After all, you just built Facebook!

it says

> After all, you just built a social media site!

**Comment by royalh23** [comment]
> @royalh23 When you're at it, could you also change the end of the first paragraph so instead of saying 
> 
> > After all, you just built Facebook!
> 
> it says
> 
> > After all, you just built a social media site!

okay
