### ISSUE TITLE
Does this sentence makes sense?

### ISSUE THREAD

**Issue by sand33pn** [TheOdinProject/curriculum#2846]
http://www.theodinproject.com/ruby-on-rails/a-railsy-web-refresher

![fireshot capture 15 - learn ruby on rails -- a railsy web re_ - http___www theodinproject com_ruby](https://cloud.githubusercontent.com/assets/4760309/11565920/31fb308e-9a06-11e5-9e0c-bf99d23e607b.png)

**Comment by KevinMulhern** [comment]
It makes sense to me, changing "it brings a couple extra" to "it brings a couple of extra" would make it clearer though.

**Comment by KevinMulhern** [comment]
I changed the text in this commit https://github.com/TheOdinProject/curriculum/commit/a8e73d35827a8a2da578907ede57b57e0de5e3b1

**Comment by KevinMulhern** [comment]
Does it make more sense to you know @sand33pn?

**Comment by sand33pn** [comment]
The "about before about" part tripped me, I understand it now.

**Comment by KevinMulhern** [comment]
I can see how that would trip you up, I tidied that bit up too. Have a look at this commit and let me know if it reads better please https://github.com/TheOdinProject/curriculum/commit/ad485db7099addfcbd4dd9de23a7c85faabdac78

**Comment by sand33pn** [comment]
:relaxed::+1:

**Comment by KevinMulhern** [comment]
awesome, thanks for pointing it out :)
