### ISSUE TITLE
Foundations:  git commit without m option should be introduced in Commit Messages lesson

### ISSUE THREAD

**Issue by nguyenlekhtn** [TheOdinProject/curriculum#28471]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In previous lessons, learners are told to use `git commit -m <commit message>` to commit. In the Commit Messages lesson, a "commit with a body" concept is introduced, but the lesson doesn't explain how to make it. That led to a bunch of questions in our server asking how to do that.

In my opinion, the Commit Messages lessons should mention  `git commit` without m flag, which will open the Git Editor set by the user in Git Basics lesson, and the lesson should also remind user to set git editor in case learners missed that and saw vi opened instead.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-commit-messages

### (Optional) Discord Name

haru => {haru:}

**Comment by MaoShizhong** [comment]
Sounds sensible to me. Perhaps also adding a quick link to and reminder about [changing the commit editor](https://www.theodinproject.com/lessons/foundations-git-basics#changing-the-git-commit-message-editor) from Git Basics to make sure learners have changed it to VS Code.

I'll assign this to you

**Comment by KevinMulhern** [comment]
Hey @nguyenlekhtn, just checking in, how are you getting on with this? need any help?

**Comment by nguyenlekhtn** [comment]
> Hey @nguyenlekhtn, just checking in, how are you getting on with this? need any help?

Hi Kevin, sorry for delaying, I just made the PR
https://github.com/TheOdinProject/curriculum/pull/28655

**Comment by nguyenlekhtn** [comment]
> Hey @nguyenlekhtn, just checking in, how are you getting on with this? need any help?

Hi @KevinMulhern , sorry for delaying, I just made the PR
https://github.com/TheOdinProject/curriculum/pull/28655
