### ISSUE TITLE
Node JS Course: Small typos in Controller Lesson

### ISSUE THREAD

**Issue by odilson-dev** [TheOdinProject/curriculum#28470]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is a typos in a paragraph in the middleware section, it should be function, not fnuction.
![Screenshot 2024-07-20 at 23-08-25 Controllers The Odin Project](https://github.com/user-attachments/assets/f3e8df8a-62eb-42b2-96c8-41e2b0a627b8)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-controllers#middleware

### (Optional) Discord Name

Odilson DEV

**Comment by MaoShizhong** [comment]
Thanks @odilson-dev.
For future reference, little typos like this you can go straight to a PR without having to open an issue first *but only if there isn't already an open issue/PR for it of course*. If there isn't, feel free to just PR the typo fix.

**Comment by MaoShizhong** [comment]
@odilson-dev just a courtesy check in if this is still something you wish to PR a fix for?

**Comment by odilson-dev** [comment]
No, I think someone has already fixed it so i don't need to create a PR for this anymore

**Comment by odilson-dev** [comment]
> @odilson-dev just a courtesy check in if this is still something you wish to PR a fix for?

No, I think someone has already fixed it so i don't need to create a PR for this anymore

**Comment by MaoShizhong** [comment]
> > @odilson-dev just a courtesy check in if this is still something you wish to PR a fix for?
> 
> No, I think someone has already fixed it so i don't need to create a PR for this anymore

Technically since you were already assigned to this issue, they should not have opened a PR. Meaning the correct course of action would actually be closing their PR and approving yours once you open one, if you're still wanting to do it. That applies for any issue/PR, regardless of how simple or complex the change would be.

If you'd rather I just reassign this issue and use the existing PR, let me know. Either way is fine.
