### ISSUE TITLE
Object Basics: Changing order of the assignment

### ISSUE THREAD

**Issue by twoton-tdr** [TheOdinProject/curriculum#28496]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It would be much better if we keep the 3rd assignment at the 1st place because it explains the theory of some array methods which we are using at the 1st and 2nd assignments

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-object-basics

### (Optional) Discord Name

twoton_

**Comment by wise-king-sullyman** [comment]
Sounds like a good change to me, thanks!

**Comment by Crn0** [comment]
I would like to take on this issue.

**Comment by wise-king-sullyman** [comment]
@Crn0 all yours, thanks!
