### ISSUE TITLE
NodeJS Databases: Databases/Databases and SQL, duplicated link in additional resoures

### ISSUE THREAD

**Issue by andriinero** [TheOdinProject/curriculum#28500]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

First and second lessons of NodeJS Database Course contain links that point to the same resource.

[Databases Lesson](https://www.theodinproject.com/lessons/node-path-databases)
`- Hunter Ducharme created an e-book which is a [great documentation on how to do all the basics in SQL](https://hunter-ducharme.gitbook.io/sql-basics/).`

[Databases and SQL Lesson](https://www.theodinproject.com/lessons/node-path-databases-databases-and-sql)
`- Odinite Hunter D made his excellent notes into a [Git Book on SQL](https://hunter-ducharme.gitbook.io/sql-basics) which you should totally check out if you want a decent resource.`

This book is undoubtedly great, but maybe it would be a better fit for the second lesson where more advanced concepts are introduced and people understand common verbs and SQL syntax better?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-databases

**Comment by MaoShizhong** [comment]
@andriinero Makes sense, good catch. Just removing the duplicate additional resource from the first lesson will be great.
