### ISSUE TITLE
Environment Variables: mention NODE_ENV

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#28507]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

One of the examples on the env vars lesson shows a variable called `MODE` and compares it against production. The conventional name would be `NODE_ENV`. 

I can understand that perhaps referencing `NODE_ENV` might be misleading since maybe someone new to this thinks the words node and env are specific meaningful keys or something like that, but the learner will absolutely see `NODE_ENV` when researching bits and bobs, so I think it needs a mention to tackle that head on.

I think all it needs is a comment inside the code block underneath the `process.env.MODE` part that says something like:
`// Conventionally, we use 'NODE_ENV' to specify production or development, but the names are arbitrary and could be anything you choose`

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-environment-variables

**Comment by MaoShizhong** [comment]
Actually, I'm not entirely sure why I used `MODE` instead of `NODE_ENV`. It *would* be better to use `NODE_ENV`, then just briefly mention it's the conventionally name for the "mode" when first introduced.

I'll assign this to you.
