### ISSUE TITLE
Using PostgreSQL: Changing code snippet in 'Querying with pg'

### ISSUE THREAD

**Issue by WDWei** [TheOdinProject/curriculum#28510]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Under ''Querying with pg', the function 
```
async function createUsernamePost(req, res) {
  const { username } = req.body;
  await db.insertUsername(username);
  res.redirect("/");
}
```
Creates an object username and passes into `insertUsername(username)`. The db expects a varchar instead of an object and will produce null.
Suggest changing
`const { username } = req.body;` to `const  username  = req.body.user;` 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-using-postgresql

**Comment by MaoShizhong** [comment]
Going by the lesson instructions, you need to make a form with a single `username` text input. When submitted, and the form parsed by the server, `req.body` should be populated with a single `username` property containing a string with whatever value you submitted the form with.

Therefore, `const { username } = req.body` uses [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) to achieve the same result as `const username = req.body.username`
