### ISSUE TITLE
Installing PostgreSQL: there is no installation instruction for WINDOWS

### ISSUE THREAD

**Issue by NewGen2022** [TheOdinProject/curriculum#28511]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is no installation instruction for WINDOWS

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-installing-postgresql

**Comment by MaoShizhong** [comment]
There are no installation instructions for Windows, as [Windows is not a supported OS in the curriculum](https://www.theodinproject.com/lessons/foundations-installation-overview).

We provide supported OS options for Windows users, along with instructions, in the lesson that comes after the one I linked.
