### ISSUE TITLE
Introduction to Grid: irrelevant exercise

### ISSUE THREAD

**Issue by Tahahosseini** [TheOdinProject/curriculum#28527]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a part which says "Remember how much fun you had solving the card layout in this exercise?". but this exercise hasn't appeared in the course yet. neither in the foundations nor the intermediate html and css course.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction-to-grid#a-look-back-at-flex

**Comment by fadingmorsecode** [comment]
Appears at **07-flex-layout-2** ([Alignment - Foundations Course](https://www.theodinproject.com/lessons/foundations-alignment))

https://github.com/TheOdinProject/css-exercises/tree/main/flex/07-flex-layout-2

**Comment by MaoShizhong** [comment]
Closing as per above
