### ISSUE TITLE
Landing Page: <Broken link for the two images of the project>

### ISSUE THREAD

**Issue by Raruto123** [TheOdinProject/curriculum#28524]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

the two broken link : 

(https://cdn.statically.io/gh/TheOdinProject/curriculum/81a5d553f4073e593d23a6ab00d50eef8620796d/foundations/html_css/project/imgs/01.png)

(https://cdn.statically.io/gh/TheOdinProject/curriculum/81a5d553f4073e593d23a6ab00d50eef8620796d/foundations/html_css/project/imgs/02.png)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-landing-page

**Comment by miamam1** [comment]
okjomokkkkkk,

**Comment by Raruto123** [comment]
It wasn't working on my end when I originally posted this issue but yesterday it worked and now too.
Thanks for answering this issue, it can be closed now or Is it me who have to do that ?

**Comment by MaoShizhong** [comment]
The issue can be closed by any maintainer as well as the author themselves of course. Glad it's all working now, seems it was just a blip.
