### ISSUE TITLE
Databases: Add a note to mention insertion can also be performed without specifying the column name.

### ISSUE THREAD

**Issue by mohammednumaan** [TheOdinProject/curriculum#28526]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the second lesson of the Databases section, the lesson mentions only one way to insert data into the table. However, there are 2 different ways to insert data into the table in SQL.

The first one is mentioned in the lesson:
```
INSERT INTO users (name, email) VALUES ('foobar','foo@bar.com');
```
*Quick suggestion: Include details of when to use this method (for example, selecting specific columns to insert data)*

The second method is to **not** specify the column names which isn't included in the lesson. For example:
```
INSERT INTO users VALUES ('foobar','foo@bar.com');
```

There are some details that we need to keep in mind while using the second method (*order of values*) which can be added if this issue gets approved.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-databases-databases-and-sql

### (Optional) Discord Name

void.jsx

### (Optional) Additional Comments

I'll be happy to work on this issue if it gets approved.

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @mohammednumaan, however I don't see any value in adding this as a note, I think it might just muddy the water. The SQL lessons lean more towards the introductory side than comprehensive, we won't be able to cover everything!
