### ISSUE TITLE
Forms and Data Handling: createUser path is incorrect

### ISSUE THREAD

**Issue by jimmyli123** [TheOdinProject/curriculum#28538]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is an additional path in the createUser code mockup in the "Forms and Data Handling" page of the NodeJS Course. The example says "/users/create," but that path didn't work for me. I believe its "/create" without "users."
![image](https://github.com/user-attachments/assets/5bd7cb8e-93a4-44b8-be3e-91db8d56ba00)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-forms-and-data-handling

### (Optional) Discord Name

jimmmyyy#9098

### (Optional) Additional Comments

Not sure if I submitted an error report properly, but please let me know if there are ways for me to improve!

**Comment by MaoShizhong** [comment]
Ah that's one I missed in a recent PR. Good spot - assigning you to this so you can PR the fix
