### ISSUE TITLE
Installing PostgreSQL: Wrong postgresql command

### ISSUE THREAD

**Issue by Sudidal** [TheOdinProject/curriculum#28550]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

![issue](https://github.com/user-attachments/assets/10bca6e5-142d-43b8-978b-81ffa81bd4c7)
the command should be written in uppercase, like so:
GRANT ALL PRIVILEGES ON DATABASE <role_database_name> TO <role_name>;

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-installing-postgresql

### (Optional) Discord Name

oxide_m

### (Optional) Additional Comments

maybe give more attention to the semi-colon in the end of the command, it can be missed

**Comment by MaoShizhong** [comment]
Assigning you to make the keywords capitals, and feel free to add onto a sentence pointing out the semicolon and its necessity.

**Comment by damon314159** [comment]
worth noting that lowercase works fine for sql keywords, it's only a matter of convention and consistency with the rest of the TOP material

**Comment by Sudidal** [comment]
> worth noting that lowercase works fine for sql keywords, it's only a matter of convention and consistency with the rest of the TOP material

You are right, maybe "Inconvenient postgreSQL command" is better

**Comment by MaoShizhong** [comment]
More just "inconsistent SQL syntax style", since IIRC, the rest of the curriculum that involves SQL has keywords in all caps.
