### ISSUE TITLE
Conclusion: Fix typo in 'Using a Backend" section.

### ISSUE THREAD

**Issue by ToastedGMS** [TheOdinProject/curriculum#28554]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The final sentence in the page reads "You have **very come far** and you should be proud of yourself for getting to this point.", I imagine it should be "You have **come very far** and you should be proud of yourself for getting to this point."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-conclusion

**Comment by MaoShizhong** [comment]
Nice spot - assigned this to you. It will need changing in both React conclusion files, one for each pathway.
