### ISSUE TITLE
Classes: Change to questions in Knowledge Check and Reorder assignments to follow Lesson Overview

### ISSUE THREAD

**Issue by Meltasy** [TheOdinProject/curriculum#28574]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Knowledge Check section states ... "The following questions ...", yet all but one of the supposed questions are actually written as questions. I'd suggest amending them all to be written as questions.

The Lesson Overview and Knowledge Check section follow the same order, but the Assignments section doesn't follow that same order. So, I'd suggest amending, as follows:
1. Opinions regarding the pros and cons of classes.
2. Javascript.info's article on Getters and Setters and primer on class syntax.
3. MDN's docs on classes.
4. Static properties and methods.
5. FunFunFunction's video on COmpostion over Inheritance.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-classes

### (Optional) Discord Name

Meltasy

**Comment by MaoShizhong** [comment]
Thanks for opening this issue. I like the proposed assignment order. A small suggestion, on top of the assignment reordering, would you be happy to restructure the MDN docs assignment step so that instead of a single paragraph with multiple links, it has something like:

```md
1. [MDN’s docs on classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) are, as usual, a great resource for going a little deeper.
   - Take a look at the ["extends" documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/extends), including the "Mixins" section...........
   - Classes can also have[private class properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) that allow you to implement privacy similarly to factory functions.
   - Classes can have [static properties and methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static) which are properties and methods that are accessed on the class itself and not on the instance of a class. This is similar to how some string methods are accessed on the instance of a string itself e.g. someString.slice(0, 5) whereas some methods are called on the String constructor directly e.g. String.fromCharCode(79, 100, 105, 110).
```

I think that looks and reads a little nicer than the large paragraphs, especially when combined with the static properties/methods step.

**Comment by Meltasy** [comment]
No problem and I think your suggestion will work well. I'll get on to that now :-)

**Comment by Meltasy** [comment]
Done :-)
