### ISSUE TITLE
ES6 Modules: Change to questions in Knowledge Check and Reorder them (and Lesson Overview) to follow Lesson Content

### ISSUE THREAD

**Issue by Meltasy** [TheOdinProject/curriculum#28579]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Knowledge Check section states ... "The following questions ...", yet all but one of the supposed questions are actually written as questions. I'd suggest amending them all to be written as questions.

The Lesson Overview and Knowledge Check section follow the same order, but the assignments within the Lesson Content don't follow that same order. So, I'd suggest amending the Lesson Overview and Knowledge Check, as follows:

1. Explain what npm is and where it was commonly used before being adopted on the frontend. (no change)
2. Describe what a JavaScript module bundler like webpack is.
3. Explain what “transpiling code” means and how it relates to frontend development.
4. Briefly describe what a task runner is and how it’s used in frontend development.
5. Describe how to write an npm automation script.
6. Know how to install packages using npm.
7. Describe what npm init does and what package.json is.
8. Briefly explain what a development dependency is.
9. Explain what the concepts “entry” and “output” mean in relation to webpack.
10. Explain one of the main benefits of writing code in modules.
11. Explain “named exports” and “default exports”.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-es6-modules

### (Optional) Discord Name

Meltasy

**Comment by MaoShizhong** [comment]
Thanks for opening this issue.
#27953 has been approved and will resolve this issue, but hasn't been merged yet as it must only be merged alongside other PRs which are still in review. Since this issue isn't urgent like a bug fix or broken link, I'll close it as it'll be addressed in due course.

**Comment by MaoShizhong** [comment]
No worries - you wouldn't have likely spotted it anyway since it's a completely unrelated PR as part of a large set of changes.
