### ISSUE TITLE
Objects and Object Constructors: Change to questions in Knowledge Check

### ISSUE THREAD

**Issue by Meltasy** [TheOdinProject/curriculum#28573]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Knowledge Check section states ... "The following questions ...", yet all but one of the supposed questions are actually written as questions. I'd suggest amending them all to be written as questions.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

### (Optional) Discord Name

Meltasy

**Comment by MaoShizhong** [comment]
Agreed, assigning you to rephrase those as actual questions.

**Comment by Meltasy** [comment]
Done :-)
