### ISSUE TITLE
Installing Ruby: <Short description of your suggestion>

### ISSUE THREAD

**Issue by vishravd** [TheOdinProject/curriculum#28571]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Had to enter echo 'eval "$(rbenv init -)"' >> ~/.zprofile to get this to work

Not echo 'eval "$(rbenv init -)"' >> ~/.bash_profile or echo 'eval "$(rbenv init -)"' >> ~/.zshrc

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

**Comment by JoshDevHub** [comment]
Thank you for making this issue!

This will be resolved by #28436, so I'm going to close this issue to prevent any duplicate work.
