### ISSUE TITLE
Webpack: webpack.config.js and Production

### ISSUE THREAD

**Issue by zakingslayerv22** [TheOdinProject/curriculum#28589]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The number 1, under number 4 of the assignments mentions that "You’ll notice the above tutorial does not have a webpack.config.js file.". If it was referring to this link - https://webpack.js.org/guides/development/ ,the tutorial indeed has a webpack.config.js file. Look here https://webpack.js.org/guides/development/#setup . I do not know what the implications might be but I hope it is looked into.

You guys are doing a nice job!

On y va!

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-webpack

### (Optional) Discord Name

the_checkmate2.2

**Comment by MaoShizhong** [comment]
Step 4.1 is referring to the tutorial in step 4 itself, the production tutorial. That one doesn't have a webpack.config.js, because it replaces it with 3 differently named config files.
