### ISSUE TITLE
API Basics: <Short description of your suggestion>

### ISSUE THREAD

**Issue by its-clem-fandango** [TheOdinProject/curriculum#28593]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

just a heads up - the CRUD actions URL in https://www.theodinproject.com/lessons/nodejs-api-basics is broken

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-api-basics

**Comment by Asartea** [comment]
Discussed this with Mao, and there isn't really an equivalent to the lesson this links to in the revamped lessons, so its probably best to link to an external resource such as https://www.codecademy.com/article/what-is-crud

**Comment by MaoShizhong** [comment]
Yep, just replacing the link's href to https://www.codecademy.com/article/what-is-crud sounds good to me.

@its-clem-fandango assigning you to PR this change since you ticked the assignment box.

**Comment by its-clem-fandango** [comment]
just did the PR, let me know if there's anything I missed. Adding "open source contributor" to my resume now 😝
