### ISSUE TITLE
React: Some React examples import React without needing to.

### ISSUE THREAD

**Issue by Victor-M-Giraldo** [TheOdinProject/curriculum#28592]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I've noticed some of the React examples import React when you no longer need to do so after the release of React 17.

For example, this one is in the introduction to [react testing](https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react-testing). There might be more, in which case I can do a quick skim through to find the rest and fix those as well.

```js
// App.jsx

import React, { useState } from "react";

const App = () => {
  const [heading, setHeading] = useState("Magnificent Monkeys");

  const clickHandler = () => {
    setHeading("Radical Rhinos");
  };

  return (
    <>
      <button type="button" onClick={clickHandler}>
        Click Me
      </button>
      <h1>{heading}</h1>
    </>
  );
};

export default App;
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react-testing

**Comment by MaoShizhong** [comment]
Nice catch. Assigning you to remove the default import there, as it's not necessary.
While you're at it, could you also remove redundant default imports of `React` from the following lessons?
- Class-based components
- Refs and memoization
- How to deal with side effects
- Type checking with proptypes

**Comment by Victor-M-Giraldo** [comment]
> Nice catch. Assigning you to remove the default import there, as it's not necessary.
> 
> While you're at it, could you also remove redundant default imports of `React` from the following lessons?
> 
> - Class-based components
> 
> - Refs and memoization
> 
> - How to deal with side effects
> 
> - Type checking with proptypes

Sure, I can do that.
