### ISSUE TITLE
HTML Foundations: Links and Images: Update WSL2 Instructions

### ISSUE THREAD

**Issue by NobleValerian** [TheOdinProject/curriculum#28595]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The first suggestion is to make the file name for the downloaded image consistent with the provided instructions.  The instructions state the file name should be "dog.jpg", but the actual downloaded file name is "charlesdeluvio-Mv9hjnEUHR4-unsplash.jpg".

Secondly, following the instructions to drag and drop the file from Windows Explorer to the Terminal Window results in an error: "cp: cannot stat '[directory/filename]': No such file or directory".

Error presented on a Windows 11 machine and using WSL2 with VS Code.  The error also presented in the standalone terminal.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-links-and-images

### (Optional) Discord Name

LegacyUnbound

### (Optional) Additional Comments

Thanks for your time.  I appreciate the time and effort dedicated to this website.

**Comment by CouchofTomato** [comment]
@xandora Any input on this?

**Comment by xandora** [comment]
Yea, we don't seem to recommend renaming the downloaded the image in the WSL section, it's part of the Linux section immediately before:
![image](https://github.com/user-attachments/assets/712b0483-b9fa-458c-9502-605a0bc05eae)

Dragging and dropping files into the terminal only works if you're using the Microsoft provided profile (the one with the Tux icon). If you use the Canonical profile, you get incorrect path translation:
![image](https://github.com/user-attachments/assets/393d22e1-9b65-47f8-9628-6c80c28d898f)

**Comment by CouchofTomato** [comment]
@xandora Do you think we can just close this then?

**Comment by xandora** [comment]
@CouchofTomato we should probably chuck a step into the WSL instructions to rename the file.

**Comment by NobleValerian** [comment]
I'm downloading the image directly from the lesson page.  Isn't everyone getting the same image file?

**Comment by CouchofTomato** [comment]
Everyone should be getting the same image file

**Comment by NobleValerian** [comment]
> Everyone should be getting the same image file

Oh, I wasn't paying close enough attention to the attachments above.  I'm using the terminal with the Ubuntu logo.  I don't remember choosing between the two.  I think that's just what I ended up with after following the steps to setup WSL.

**Comment by joayo13** [comment]
Hey, I'd like to be assigned this issue. I think just adding the instruction to rename to dog.jpg could be added to the end of step 3.

**Comment by CouchofTomato** [comment]
@joayo13 Sorry for the delay. All yours if you still want it
