### ISSUE TITLE
Linting: Prettier's installation guide link links to wrong site

### ISSUE THREAD

**Issue by RichardGabelman** [TheOdinProject/curriculum#28615]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the section "Formatters", the link to Prettier's installation guide instead links to the [Prettier 2017 React Conference talk](https://www.youtube.com/watch?v=hkfBvpEfWdA). I believe the correct link should be "https://prettier.io/docs/en/install.html".

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-linting

### (Optional) Discord Name

chazusa

**Comment by MaoShizhong** [comment]
Oops, assigning you to replace the href with the actual installation link.
