### ISSUE TITLE
Codespell: remove only warn setting

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/curriculum#28613]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Currently, the `codespell` action has `only-warn` option set to 1, which means it will always succeed, even if errors are found[1]. This adds the risk of a maintainer forgetting that even when all checks are green, the logs still have to be manually inspected to see if there were errors. Reading through the original pull request adding it, it seems this was done because otherwise, codespell would only flag the first error[2].

This appears to no longer be the case however: testing it, it flagged all errors introduced, both in a single file and split across multiple files. With the original issue no longer relevant, it would be better to turn `only-warn` off, so checks will properly hardfail when they fail.

As a side note, while this is getting looked at anyway, can we also rename the file away from `testing.yml`, now that it's no longer the only test being run? I propose `codespell.yml` as the new filename.

[1] https://github.com/codespell-project/actions-codespell/tree/v2.0?tab=readme-ov-file#parameter-only_warn
[2] #22479

![image](https://github.com/user-attachments/assets/73ad4bf2-0c0b-41b7-9dd4-6cef70fc75e2)

### Path

Other / NA

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/.github/workflows/testing.yml

### (Optional) Discord Name

asarta

**Comment by CouchofTomato** [comment]
Makes sense to me
