### ISSUE TITLE
Intermediate HTML & CSS: More Text Styles - Line height codepen improvement

### ISSUE THREAD

**Issue by ItsTosh** [TheOdinProject/curriculum#28610]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the "More Text Styles" lesson, in the CodePen for: 
https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles#letter-spacing

The last CSS declaration is this:
```
.narrow {
  font-size: 48px;
  letter-spacing: -.15em;
}
```

The `-.15em` might confuse people, so it could be better to to write it like this, `-0.15em`, instead for better clarity.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles

### (Optional) Discord Name

toshcodes.

### (Optional) Additional Comments
I would work on it, but I have no idea how to edit the `<iframe>`

## Acceptance Criteria:
- [ ] Convert `-.15em` to `-0.15em` for the CodePen in line-height

**Comment by CouchofTomato** [comment]
@TheOdinProject/html-css Does anyone have any input on this?

**Comment by MaoShizhong** [comment]
Dropping the `0` in a `.X` situation is somewhat commonplace in general, though there's no harm in popping the `0` back in for both letter-spacing values in that Codepen.

We'd need core who has access to the Codepen account to make that edit though. I don't have access to that account.

**Comment by ItsTosh** [comment]
Thanks @MaoShizhong If it's a bit of a pain, then I feel like a simple note somewhere would suffice as well.

**Comment by wise-king-sullyman** [comment]
Done! Thanks for raising this @ItsTosh, if something still doesn't look right with it though just re-open this issue.
