### ISSUE TITLE
Databases: Remove assignment

### ISSUE THREAD

**Issue by NestorNebula** [TheOdinProject/curriculum#28618]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

There are actually 3 assignments in the "Databases and SQL" lesson.
1. [SQL Teaching](https://www.sqlteaching.com/).
2. [SQL Bolt](http://sqlbolt.com/).
3.  [SQLCourse's beginner course](https://www.sqlcourse.com/beginner-course/) and [SQLCourse's advanced course](https://www.sqlcourse.com/advanced-course/).

While the first one is a great introduction and is giving some great foundations, the second and the third ones as individuals are great but seems repetitive (particularly doing the 3rd first part after doing the 2nd) and the third doesn't add much after doing the second.

My suggestion is to remove either the second or the third assignment and to add it to the additional resources.

Considering that the lesson itself says:
```
If you’ve still got blind spots, check out the Additional Resources section below. Fear not and stick with it!
```
I think that the suggestion makes sense.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-databases-databases-and-sql

### (Optional) Discord Name

NestorNebula

**Comment by CouchofTomato** [comment]
I'm not against this. I think moving the second one makes sense because the third one is very comprehensive.

@TheOdinProject/javascript Anyone have a view on this.

**Comment by mohammednumaan** [comment]
@CouchofTomato Interesting, I found the second lesson more comprehensive than the third one, so I think it makes sense to move the third one.

**Comment by CouchofTomato** [comment]
Thanks for the input. I'm ok with whichever one being moved. @NestorNebula Assigning you
