### ISSUE TITLE
Deployment: PaaS default nodejs version 

### ISSUE THREAD

**Issue by Crn0** [TheOdinProject/curriculum#28621]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Add a note that some PaaS providers do not default to the LTS version of Node.js (e.g., Railway defaults to Node.js 18). Depending on the Node.js features you are using, you may need to explicitly specify the Node.js version in your package.json file.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-nodejs-deployment

**Comment by CouchofTomato** [comment]
Would this not be covered in the setup guide for the service itself which the user should follow?

**Comment by Crn0** [comment]
I don't know about the other services, as I used Railway, but I don’t see the default Node.js version being mentioned there. Essentially, you can deploy your GitHub repo directly. Their [quick start tutorial](https://docs.railway.app/quick-start) uses Next.js and Prisma (I started this project before the revamp), and they’re also installing the Railway CLI, which I think is out of scope for ToP. I’m not sure if it will make sense now given the revamp. It is also not mentioned which Node.js version is used.

Knowing the default Node.js version and whether it is an LTS version would be helpful, as my app broke due to Railway defaulting to Node.js version 18.x.x, which does not support a feature I used in my app.

**Comment by KevinMulhern** [comment]
Thanks @Crn0, a warning note sounds like a good idea. I've assigned it to you!
