### ISSUE TITLE
Component Lifecycle Methods: <The first link in assignment has no english translation, its still in spanish>

### ISSUE THREAD

**Issue by SanjayS808** [TheOdinProject/curriculum#28637]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The first link in assignment has no english translation, its still in spanish

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-component-lifecycle-methods

**Comment by KevinMulhern** [comment]
It's displaying correctly for me @SanjayS808
<img width="1286" alt="Screenshot 2024-08-18 at 10 29 19" src="https://github.com/user-attachments/assets/b98520ae-a562-43d2-bccb-5d8bd09966aa">


Can you take a screenshot of what you're seeing please?
