### ISSUE TITLE
OOP Principles: Change Knowledge Check to questions and amend link in #2

### ISSUE THREAD

**Issue by Meltasy** [TheOdinProject/curriculum#28632]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Knowledge Check section states ... "The following questions ...", yet all of them are written as statements. I'd suggest amending them all to be written as questions.

In the Knowledge check, the link in the second question refers to an article not covered / referred to during the lesson: https://medium.com/@cramirez92/s-o-l-i-d-the-first-5-priciples-of-object-oriented-design-with-javascript-790f6ac9b9fa.
Should the link be to the following article? https://duncan-mcardle.medium.com/solid-principle-1-single-responsibility-javascript-5d9ce2c6f4a5

Finally, I find the wording of the 1st assignment very repetitive. Do you think it would read better just to say:
1. The following article and videos mention the acronym SOLID before going on to talk about Single Responsibility. Single Responsibility is definitely the most relevant of the 5, but feel free to dig into the rest of the SOLID principles if you like.
   1. Read this article about SOLID principle 1: Single responsibility (JavaScript). It simplifies that which is covered in more detail in the the SOLID videos below.
   2. Watch The SOLID Design Principles by WDS to see code examples for each principle.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-oop-principles

### (Optional) Discord Name

Meltasy

**Comment by KevinMulhern** [comment]
Thanks for the suggestions @Meltasy, those all sounds like good changes to me. I've assigned you.

**Comment by Meltasy** [comment]
Thanks, I'll get onto that now :-)

**Comment by Meltasy** [comment]
That's done, do let me know if there's anything else. Have a lovely day :-)
