### ISSUE TITLE
Mini Message Board: Change "button" to "anchor" on item 11.

### ISSUE THREAD

**Issue by mikeyCos** [TheOdinProject/curriculum#28638]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

The project specifications suggests on item 11, 

> Add an “open” button next to every message to open a new page with the message details.

A button element does not make sense to trigger a GET request. I suggest, use an anchor element:

"Add an **anchor** element next to every message to open a new page with the message details."

An entire message could be wrapped around with an anchor element. Otherwise, the quotations can be extended from open to the end of button to describe a button-like element; "open button". 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-nodejs-mini-message-board

**Comment by mikeyCos** [comment]
On further thought, the button could be wrapped with form tags and make use of the form method attribute. If this is still an issue, please keep it open, otherwise close it.

**Comment by MaoShizhong** [comment]
I wouldn't be opposed to the wording being tweaked to 
> Add an "open" button or link...

**Comment by mikeyCos** [comment]
@MaoShizhong I see that I was assigned this issue. Does that mean I can work on the issue? If so, will it be a problem to use the "Improve this lesson on GitHub" link at the end of the lesson to make the edit and submit a pull request? Thank you.

**Comment by MaoShizhong** [comment]
Yep, being assigned means you've got permission to open a PR to address the issue. How you start and complete the PR doesn't matter, as long as a PR is created that will close this issue, then a maintainer can review in due course.
