### ISSUE TITLE
NodeJS: Typo in Introduction to Express Lesson.

### ISSUE THREAD

**Issue by mohammednumaan** [TheOdinProject/curriculum#28639]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the section `A Requests Journey` there is a small typo for the word `sending` :

![image](https://github.com/user-attachments/assets/fd5b2d3a-c132-43a6-b6fe-ff19d9ce4c0e)

The fix should be :

![image](https://github.com/user-attachments/assets/d7e6f9e1-af8b-4d0c-8ef4-135d7332e405)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-nodejs-introduction-to-express#a-requests-journey

### (Optional) Discord Name

void.jsx

### (Optional) Additional Comments

I'll be open to work on this small issue.

**Comment by MaoShizhong** [comment]
`.send`ing was intentional because the method used is `res.send`.

Though if people feel just saying "sending" instead of "`.send`ing looks better, then I'm not opposed to it being changed

**Comment by mohammednumaan** [comment]
@MaoShizhong Oh alright. I think it would be better including `res.send` in brackets. Something like this:

![image](https://github.com/user-attachments/assets/2f877442-92b9-4b77-bd34-692d3a481b5c)

**Comment by MaoShizhong** [comment]
That looks sensible to me. Assigning this to you @mohammednumaan
