### ISSUE TITLE
DOM Manipulation and Events: <Short description of your suggestion>

### ISSUE THREAD

**Issue by MID3EE-ARCH** [TheOdinProject/curriculum#28642]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is a small mistake in the article which is linked to another website "https://www.javascripttutorial.net/javascript-dom/javascript-keyboard-events/" in the assignment section of "https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events" in that article under the subheading "handling Keyboard event" in the code it's getDocumentById . I think it should be getElementById("messge") instead of getDocumentById("#message"). I noticed this when the code didn't work in browser ...

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

### (Optional) Discord Name

DevNChill

### (Optional) Additional Comments

I really love TOP , I wish I knew it before. Keep Up Guys !!

**Comment by fadingmorsecode** [comment]
There is a contact form linked in the footer. Perhaps you could relay the issue there.

**Comment by MID3EE-ARCH** [comment]
okay !! . I'll close this

**Comment by MID3EE-ARCH** [comment]
okay!!
