### ISSUE TITLE
Setting up Git: error in trying to install Git

### ISSUE THREAD

**Issue by trlang** [TheOdinProject/curriculum#28651]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I am trying to run the command:
sudo add-apt-repository ppa:git-core/ppa

I get the error:
`PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/git-core/ppa/ubuntu/ jammy main'
Description:
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 352, in main
    self.prompt_user_shortcut(shortcut)
  File "/usr/bin/add-apt-repository", line 145, in prompt_user_shortcut
    print(description)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 136-194: ordinal not in range(256)
`

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

**Comment by bycdiaz** [comment]
@trlang Am I correct in my impression that you'd like assistance troubleshooting this error? If so, we can't conduct technical support through our github issuess. If you'd like assistance, please share this over in our Discord community.
