### ISSUE TITLE
Ruby: Remove the broken link in the 'Additional Resources' section of the Conditional Logic lesson.

### ISSUE THREAD

**Issue by Eddy518** [TheOdinProject/curriculum#28664]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The third link('Learn ruby the hard way') in the Additional Resources of the Conditional Logic section is not working.
![Screenshot_2024-08-19-18-56-34_1920x1080](https://github.com/user-attachments/assets/b3305faa-287f-410b-a775-3cb1f155af03)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-conditional-logic

**Comment by JoshDevHub** [comment]
Generally would want to look for an alternate link, but since this is an additional resource, I think it's fine to remove it entirely like you're suggesting.

Since you indicated you want to work on it, I'll assign you. Let me know if you have any questions @Eddy518
