### ISSUE TITLE
Installations: The image of the tutorial is error

### ISSUE THREAD

**Issue by ramaanindyaa** [TheOdinProject/curriculum#28661]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Please fix the error

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

**Comment by KevinMulhern** [comment]
Thanks for the report @ramaanindyaa, but we're going to need more information. What image? screenshots are appreciated!

**Comment by ramaanindyaa** [comment]
[image: image.png]
as you can see above

Pada Sen, 19 Agu 2024 pukul 13.43 Kevin ***@***.***> menulis:

**Comment by KevinMulhern** [comment]
It doesn't look like an image uploaded @ramaanindyaa, can you try again please?

**Comment by KevinMulhern** [comment]
At this point, I'm just going to assume this is a troll post.

**Comment by ramaanindyaa** [comment]
![image (3)](https://github.com/user-attachments/assets/afbe0326-780d-42ca-847c-072f0a4db0f5)
here's the image

**Comment by KevinMulhern** [comment]
Thanks @ramaanindyaa, they are both working for me. It's likely a network/firewall issue on you're end.

<img width="869" alt="Screenshot 2024-08-19 at 08 03 34" src="https://github.com/user-attachments/assets/9013bdba-2876-42ea-9205-3fa9a1ff770d">

Check back on the lesson after a while, or try from a different network please

**Comment by ramaanindyaa** [comment]
Thanks, i'll try with a different network

Pada Sen, 19 Agu 2024 pukul 14.10 Kevin ***@***.***> menulis:
