### ISSUE TITLE
NodeJS, Ruby on Rails: Inconsistent Wording in PostgreSQL Installation Lessons

### ISSUE THREAD

**Issue by davidumoru** [TheOdinProject/curriculum#28676]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the `Installing PostgreSQL` section of both the Ruby on Rails and Node.js lessons, there are minor wording inconsistencies:

- In the Ruby on Rails lesson, the phrase `they should both the same` is grammatically incorrect:
![Screenshot from 2024-08-20 23-43-45](https://github.com/user-attachments/assets/ef2263ad-e4d8-4e36-b8e2-71e37a8614f9)

- In the Node.js lesson, the phrase `they should be both the same` is grammatically correct but could be improved for better readability:
![Screenshot from 2024-08-20 23-44-12](https://github.com/user-attachments/assets/760a426b-dfce-4067-9848-fb6d133e6528)

Suggested fixes:

- Ruby on Rails lesson: Change `they should both the same` to `they should both be the same`
- Node.js lesson: Change `they should be both the same` to `they should both be the same`

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql
https://www.theodinproject.com/lessons/nodejs-installing-postgresql

### (Optional) Discord Name

notumoru

### (Optional) Additional Comments

I'll be open to working on this small issue.

**Comment by MaoShizhong** [comment]
Makes sense to me - go for it.
