### ISSUE TITLE
Setting up Git: Set up GitHub email before installing Homebrew

### ISSUE THREAD

**Issue by LeviD8** [TheOdinProject/curriculum#28673]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I had an issue installing Homebrew, I believe we should set up our GitHub email before trying to install Homebrew. Currently it is the following step. From what I can tell (I'm new so this could mean nothing) it is looking for an authorized user and failing when it doesn't find one. I had to follow info in this link to get it to install on M1 MacBook Air. I seem to be on my way now.
https://stackoverflow.com/questions/39836190/homebrew-install-failed-during-git-fetch-origin-masterrefs-remotes-origin-mas

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### (Optional) Additional Comments

Thanks to everyone involved, looking forward to learning new skills!

**Comment by xandora** [comment]
The Homebrew install uses the HTTPS clone method, which doesn't require you to have anything git related set up. Your issue may have been something else, and was coincidentally resolve by you following some other instructions.

If you do have the error message from when you were trying to install Homebrew and it was failing though, it'd be useful to see that just so we can verify if we do need to consider an adjustment or not. The install instructions have been the same for macOS for quite a while, and I don't think we've had anyone make this suggestion before.

**Comment by LeviD8** [comment]
Thank you for the reply, as I retrace my steps more carefully it is certainly pointing towards user error on my side (surprise!). The doofus in me also took control when I was having the problem and didn't screenshot the error or save a log. 

I do remember it failing near the end of the download and just retried a few times afterwards where it kept failing at the same spot. I did have to delete the cellar and homebrew directories and didn't try to install again before adding my git email. I'm learning to commit better by now!

Thanks again for your help and appreciate the dedication to the project :)
