### ISSUE TITLE
Data Types and Conditionals: Unable to finish exercises with free Replit account

### ISSUE THREAD

**Issue by plmn95** [TheOdinProject/curriculum#28684]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It appears that Replit allows for up to three forks on the free account, therefore it's not possible to do all of the exercises at once unless you upgrade.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals

### (Optional) Discord Name

ognepoklonnik

**Comment by MaoShizhong** [comment]
Thanks for the issue @plmn95 
We have a note box in the lesson assignment addressing this (https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals#replit-fork-limit) - you can delete any repls you no longer need to make room for new ones.
