### ISSUE TITLE
Clean Code: <Tabs vs Spaces link leads to a private video>

### ISSUE THREAD

**Issue by Raumsegler1** [TheOdinProject/curriculum#28682]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Change the link to one that works.

What it currently looks like (at least for me):
![image](https://github.com/user-attachments/assets/61cd497d-c3c0-4aff-b952-e801daacb678)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code

**Comment by mathdebate09** [comment]
I can submit a quick pr but there's slight ambiguity

It's the video [https://youtu.be/V7PLxL8jIl8?si=kwhiICMk_ofjzEoR](https://youtu.be/V7PLxL8jIl8?si=kwhiICMk_ofjzEoR) but I don't exactly remember if it was a clip starting from [2:27](https://youtu.be/V7PLxL8jIl8?si=eq2QLhQhVqXugA2c&t=146) or the whole video

**Comment by JoshDevHub** [comment]
I think it would be best to just remove the link and reference to the show. Any clip for a random YouTube channel will be at risk for being taken down, so unless there's an official clip somewhere that can be more fully relied on, it's best to just get rid of it.

Would you be okay with making a PR to remove it @mathdebate09 ?

**Comment by mathdebate09** [comment]
Yes I agree with you on this one, So I'll have to just remove the whole line, right? No reference of the show

**Comment by JoshDevHub** [comment]
Yep exactly @mathdebate09 :thumbsup:

I'll assign you.

**Comment by MaoShizhong** [comment]
Always found this scene weird anyway, because unless you're talking about old software from zonks ago, hitting the tab key can enter space characters or tab characters depending on settings. Spaces vs tabs isn't really about people who use the tab key vs those who hit the spacebar N times :sweat_smile:
