### ISSUE TITLE
Transforms: Typo for QHMit as 'Quackit' ? 

### ISSUE THREAD

**Issue by susancantdance** [TheOdinProject/curriculum#28693]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

For the assignment, #1, it references "Quackit" - seems like it should be Qhmit?

Take a look at this [MDN demonstration of rotate3d](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate3d()) then read more about the property in this [Quackit article on rotate3d](https://www.qhmit.com/css/functions/css_rotate3d_function.cfm).

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transforms

### (Optional) Discord Name

suser

**Comment by MaoShizhong** [comment]
The site used to be called Quackit. Looks like the href was fixed when the site name changed, but the link text label wasn't changed at the same time. I'll assign you to fix this - good spot!

**Comment by MaoShizhong** [comment]
@susancantdance Just a courtesy check in if this is something you still wish to work on?

**Comment by susancantdance** [comment]
Yes! I'll get to it this week
