### ISSUE TITLE
Introduction to Flexbox: <Images are not loading due to source server privacy error>

### ISSUE THREAD

**Issue by dwiazizah** [TheOdinProject/curriculum#28711]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

All the images in the lesson are not loading because of privacy error of the source server. It happened to the lessons in foundation path before this lesson too. It might be only happened to certain location as it works well when I'm using VPN.
![privacy error](https://github.com/user-attachments/assets/76c09674-95c8-4f98-bc4b-3a956b3737ef)
![images not loading](https://github.com/user-attachments/assets/af292680-9a19-4acf-89e9-f048d6c7e8da)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox

**Comment by mathdebate09** [comment]
![Screenshot_20240828-164203.png](https://github.com/user-attachments/assets/c2077950-5f98-4b15-93f8-d69a703ca671)

![Screenshot_20240828-164205.png](https://github.com/user-attachments/assets/9bec6d8c-1155-4e58-bac4-8ebcd6107233)

It works on my device so I doubt if that's an issue on the cdn providers side.

Can you check what your proxy settings say? Sometimes other apps end up installing some proxy which messes with certain domains

**Comment by wise-king-sullyman** [comment]
Interest, https seems to be working properly for the images for me as well.

Is this something anyone else is seeing?

**Comment by dwiazizah** [comment]
Hi! This is how proxy setting 
<img width="349" alt="Capture" src="https://github.com/user-attachments/assets/31cc1144-e24d-4092-a37f-7b4af0dce418">

I just found out that cdn.statically.io is blocked in my country. I guess that is why.
