### ISSUE TITLE
Passing Data Between Components: Inconsistency in the code example

### ISSUE THREAD

**Issue by Lanut1** [TheOdinProject/curriculum#28736]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the section "Functions as props" there probably is an inconsistency in the second code example. The Button component hardcodes a URL, while the App component is made to accept different URLs.  If I am not mistaken, the main goal is to make Button more reusable with different styles and links. To improve component reusability, consider updating the example to pass the URL as a prop to the Button component.

Here's a suggested version:
```
function Button({ text = "Click Me!", color = "blue", fontSize = 12, handleClick, url = 'https://www.theodinproject.com' }) {
  const buttonStyle = {
    color: color,
    fontSize: fontSize + "px"
  };

  return (
    <button onClick={() => handleClick(url)} style={buttonStyle}>
      {text}
    </button>
  );
}

export default function App() {
  const handleButtonClick = (url) => {
    window.location.href = url;
  };

  return (
    <div>
      <Button handleClick={handleButtonClick} url = 'https://react.dev/learn/passing-props-to-a-component' />
    </div>
  );
}
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-passing-data-between-components

**Comment by wise-king-sullyman** [comment]
I'm not entirely sure what the original intent of the second example was, @bscottnz @01zulfi looks like yall did the original work on it, can you shine any light here?

**Comment by bscottnz** [comment]
I think the intention was to show how you can pass references to functions as props and call them within the child. Lanut1 is right here in that it doesn't really make sense to hard code the URL in the button, but I don't think passing the URL separately makes much sense either when you would instead just do `handleClick={() => handleButtonClick(URL)}`. 

I could edit it to show both examples, one like the one I just mentioned and another which passes just the reference in a way that makes more sense?

**Comment by Lanut1** [comment]
@bscottnz @wise-king-sullyman Thank you for the answers! For me, it would be really helpful to see how to correctly pass different URLs, as I was lost about this.

**Comment by wise-king-sullyman** [comment]
@bscottnz thanks! I agree that passing the URL as a separate prop feels odd here.

@Lanut1 like @bscottnz said a common approach to this sort of thing could be something like having the second examples `handleButtonClick` and passing it like:

```js
<Button handleClick={() => handleButtonClick('https://www.theodinproject.com') />
```

Since you've both volunteered to work on this it might be a good idea to collaborate if you'd both be open to that, but if either of you would rather I just pick who puts the PR up I can do that too 🙂 

---

This is really tangential but if you're curious, probably the most realistic but not relevant to what's trying to be demonstrated here approach:

You could have just a `url` or `href` or `link` prop on your `Button`, which when something is passed to it an anchor element (which just _looks_ like a button) is actually rendered instead of a button. That's kind of what we do for [this sort of application in the component library I maintain for work](https://www.patternfly.org/components/button/#links-as-buttons) for example.

**Comment by Lanut1** [comment]
@wise-king-sullyman thank you! This topic is more clear for me now! I'm very interested in learning how to create a PR, as I've never done one before.

**Comment by wise-king-sullyman** [comment]
@Lanut1 is this still a change you'd like to make?

**Comment by PJ-Bernal** [comment]
I was going to propose the exact same change. When I was taking the lesson I was kind of confuse, for me there wasn't a real reasson to hardcode the URL, but use the url as an 'attribute' is a good way to show all the buttons can have different URLs.

**Comment by Lanut1** [comment]
@wise-king-sullyman yes, I would like to change the App component:
``` 
<Button handleClick={() => handleButtonClick('https://www.theodinproject.com') /> 
```

and the Button component: 
``` 
<button onClick={handleClick} style={buttonStyle}>
 ```

**Comment by CouchofTomato** [comment]
@wise-king-sullyman Can you take a look at this please.

**Comment by wise-king-sullyman** [comment]
@Lanut1 sounds great!

**Comment by CouchofTomato** [comment]
@Lanut1 All yours if you want to do the change?

**Comment by Lanut1** [comment]
@CouchofTomato @wise-king-sullyman great, thank you! I will do the change!
