### ISSUE TITLE
Foundations Setting up Git: Clarify git e-mail config section to eliminate confusion

### ISSUE THREAD

**Issue by lukegrob** [TheOdinProject/curriculum#28739]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Someone in the discord said that **the instructions on which e-mail to use for your git --global config are slightly confusing, and they believed that the private email and personal email were interchangeable in this setup phase (and would not lead to pushing issues).**  And a regular said this question does arise from time to time in the discord (and there is, in hindsight, a stickied message on how to fix this issue in discord -- but perhaps that shows a use for a slight rework?).

This issue **specifically arises** when they have enabled **Keep my email addresses private** AND **Block command line pushes that expose my email** and then try to push after setting their non-private email as their config email.

My proposal would be to make this more explicit in some way, which could be done through some/all of the following steps:

- Bolding the line "If you plan to use this, make note of it now as you will need it when setting up Git in the next step." in Step 2.1
- Having a bolded "This is where you use the privatized email you made a note of in the last step" in Step 2.2, probably directly after the line "Be sure to enter your own information inside the quotes (but include the quotation marks)!"
- Reversing the code blocks in Step 2.2 slightly, where the **first** example shows **the privatized e-mail** being used (along with the username), and then the second example could be reworked to say "If you opted **not** to use the private GitHub email address...", with a plain, non-privatized email in the second box example.
- Potentially choose to _recommend_ in Section 2.1 that the privatized email option be used, which makes using the personal, non-private email the "non-recommended" option?

If it is agreed that this section could be improved somehow, I'd be happy to be assigned to make the changes as long as a choice is reached on how best to clarify this area.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### (Optional) Discord Name

ekuluke

**Comment by MaoShizhong** [comment]
I think we can definitely embolden the "If you plan to use this, make note of it now as you will need it when setting up Git in the next step." bit in step 2.1.

Additionally, what do you think about rewording the following?

> The commands below will configure Git. Be sure to enter your own information inside the quotes (but include the quotation marks)!

to

> The commands below will configure Git. Be sure to enter your own information inside the quotes (but include the quotation marks!) - **if you chose to keep your email private on GitHub, use your special private GitHub email from step 2.1.**

Then to flow better, after the first example, rephrase to 

> For example, if you set your email as private on GitHub, the second command will look something like this:

**Comment by lukegrob** [comment]
@MaoShizhong I think those greatly hit what I was hoping for, and I am hoping they will help without having to change the page more than is necessary.

I appreciate it could feel a little overkill, but I think exampling the two concepts as clearly as that will surely reduce some misunderstandings. There will always be people who misread or don't quite get the idea, but I'm hoping this reduces that to the minimum possible amount.

Happy to be assigned to this if desired.

**Comment by MaoShizhong** [comment]
Go for it :+1:
