### ISSUE TITLE
Rendering Techniques: <It is incorrectly suggested that .eslintrc.cjs should be updated to turn off error missing in props validation>

### ISSUE THREAD

**Issue by 1Amal** [TheOdinProject/curriculum#28747]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

It is incorrectly suggested that .eslintrc.cjs should be updated to turn off error" missing in props validation". I tried creating .eslintrc.cjs file in the project root folder and added the suggested rule. But it did nothing, so I researched online and found that it needs to be added to the eslint.config.js under rules as 'react/prop-types': 'off' this worked. 
This is from Chat GPT "Starting from ESLint v8.23.0, ESLint officially introduced support for eslint.config.js as the new recommended configuration format, which provides more flexibility and control compared to .eslintrc.* formats."

Thank you, team! I've learned so much from The Odin Project, and I'm eager to contribute and help make it even better!

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-rendering-techniques

**Comment by MaoShizhong** [comment]
Thanks @1Amal. `eslint-plugin-react` only recently added support for ESLint's flat config format (Vite still shipped with `.eslintrc` until very recently).

All we need to do is change the name of the file in the note box from `.eslintrc.cjs` to `eslint.config.js`. Since you ticked the assignment box, I'll assign this to you to PR.

**Comment by 1Amal** [comment]
Thanks [MaoShizhong](https://github.com/MaoShizhong), I will work on this !
