### ISSUE TITLE
Arrays and Loops: Jest needed for javascript testing exercises

### ISSUE THREAD

**Issue by iftakherhossain23** [TheOdinProject/curriculum#28744]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I followed the instructions to install Node.js and I attempted the first javascript exercise on Arrays and Loops however I would run into this error: 
![image](https://github.com/user-attachments/assets/429b3936-70fb-447e-b5f4-e06778012acd)

I did some research and solved this by installing jest.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-arrays-and-loops

### (Optional) Discord Name

ifty

**Comment by MaoShizhong** [comment]
Thanks @iftakherhossain23.
As per the [JavaScript exercises repo README](https://github.com/TheOdinProject/javascript-exercises?tab=readme-ov-file#how-to-use-these-exercises) (which the lesson assignment tells you to go through), our instructions tell people to install Jest and how to do so. Seems like you missed that bit.
