### ISSUE TITLE
Data Types and Conditionals: Clarify replit usage

### ISSUE THREAD

**Issue by sukairaida** [TheOdinProject/curriculum#28750]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I have seen people in multiple ocasions asking in the Discord server where the "fork" or "remix" buttons are after creating their accounts on Replit, I think the confusion comes from this paragraph that is before the exercises themselves: 

"To get started, create a free replit account and click “Fork” or “Remix” to access the exercises. Note: Feel free to browse the files on the left column to gain familiarity with it."

As it reads, it implies that you need to click one of those buttons to be able to access the exercises right after creating your account. It could be changed to something like "You will need to create a free replit account to do the next exercises. After you have done that, you can do the exercises in this assignment by opening their link and clicking "Fork" or "Remix" in their Replit page." I am not very good with words so if this can be phrased better let me know!

Some examples of people being confused about this: 

[example 1](https://discord.com/channels/505093832157691914/1179952911548174346/1281425308062318773), [example2](https://discord.com/channels/505093832157691914/505093832157691916/1280984031143395338), [example 3](https://discord.com/channels/505093832157691914/690590001486102589/1280486042746617871), and there are many more. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals

### (Optional) Discord Name

sukairaida

**Comment by MaoShizhong** [comment]
Thanks for opening the issue. I've noticed this too and think your suggestion is a fair change. Assigning this to you.

**Comment by DevNChill** [comment]
yep , it took 10 minutes to figure it out , had to google on how to use and fork replit .
