### ISSUE TITLE
Foundations: Replace malicious link with safe alternative

### ISSUE THREAD

**Issue by BottomToTheTop** [TheOdinProject/curriculum#28765]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

There is currently a link on the [Recipes](https://www.theodinproject.com/lessons/foundations-recipes) project that goes to a [website](https://brutalistwebsites.com/) that displays examples of brutalist web designs. I went on the website and I clicked on the third example to view their brutalist web design and it immediately started downloading malware. 

A prompt fix would be replace the link with a different website that displays brutalist web designs as it is unsafe for users to be at risk of downloading malware especially since the malicious site is at the top of the page.

Here are some examples of what it can be replaced with:
https://onepagelove.com/brutalist-websites
https://www.awwwards.com/awwwards/collections/brutalism/
https://webflow.com/made-in-webflow/brutalism

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes

**Comment by MaoShizhong** [comment]
Thanks for opening the issue. To be honest, we don't need the link at all anyway. We could probably just remove that part of the sentence then just combine the sentence with the next one e.g.

> The website will consist of a main index page which will have links to a few recipes. The website won’t look very pretty by the time you’ve finished but it’s important to keep in mind that this project is just to build your HTML chops; we will revisit this project in the future to style it up with CSS.

I'll assign this to you to open a PR for.
