### ISSUE TITLE
Conditional Logic: Link leads to video, not article

### ISSUE THREAD

**Issue by sukairaida** [TheOdinProject/curriculum#28774]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the second paragraph of the [logical operators](https://www.theodinproject.com/lessons/ruby-conditional-logic#logical-operators) section it says: 

> We recommend you read this article that explains the [differences between symbolic logical operators and their word versions](https://avdi.codes/how-to-use-rubys-english-andor-operators-without-going-nuts/).

But there is no "article" to read, the link leads to a video that does in fact explain the differences. I know this seems like nitpicking but this could be a good first issue for someone. 

I want to add that the mismatch comes from the issue https://github.com/TheOdinProject/curriculum/issues/21947 that replaced the previous article for a video.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-conditional-logic

### (Optional) Discord Name

sukairaida

**Comment by SeanAverS** [comment]
Hello,

I am interested on being assigned this. Would changing `read this article` to `watch this video`  be valid?
