### ISSUE TITLE
FS RoR: Conditional Logic: Possibly inappropriate metaphor

### ISSUE THREAD

**Issue by ruben-vl** [TheOdinProject/curriculum#28779]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the [paragraph on truty and falsy values in Ruby](https://www.theodinproject.com/lessons/ruby-conditional-logic#truthy-and-falsy-in-ruby), the metaphor of bugs in a decomposing body is used.

While this analogy can be funny (?), it's not really a visual I want to get in my head when learning to code (or really in any circumstance actually).

I get that it's just a metaphor, but not everyone will take this as funny or light-hearted, so it seems unnecessary in my opinion.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-conditional-logic

### (Optional) Discord Name

ruben-vl

**Comment by sukairaida** [comment]
Is funny how yesterday I read that too and thought the same. It is not a nice thing to imagine and it took me offguard. I really do believe that the Ruby lessons could be rewritten or at least modified to be more professional and clear, rather than having unnecessary metaphors, jokes and analogies.

I like this paragraph from Bjarne Stroustrup's "Programming principles and practice using C++", and in this context, even more the last sentence: 

> We try to respect your intelligence and to be considerate about your time. In our presentation, we aim for professionalism rather than cuteness, and we’d rather understate a point than hype it. We try not to exaggerate the importance of a programming technique or a language feature, but please don’t underestimate a simple statement like “This is often useful.” If we quietly emphasize that something is important, we mean that you’ll sooner or later waste days if you don’t master it. **Our use of humor is more limited than we would have preferred, but experience shows that people’s ideas of what is funny differ dramatically and that a failed attempt at humor can be confusing.**

**Comment by JoshDevHub** [comment]
Thank you for making this issue @ruben-vl . I'm fine with this joke being removed. Since you indicated you don't want to work on it, I'll open it up for someone else to work on. 

Comment below to be assigned.

**Comment by XAJX179** [comment]
can i be assigned?

**Comment by JoshDevHub** [comment]
@XAJX179 Thank you for volunteering! I'll assign you.

**Comment by ruben-vl** [comment]
Very nice fix @XAJX179, couldn’t have come up with a better one!

**Comment by XAJX179** [comment]
> Very nice fix @XAJX179, couldn’t have come up with a better one!

Thank you! ♥
