### ISSUE TITLE
Node.js learning

### ISSUE THREAD

**Issue by prashcr** [TheOdinProject/curriculum#2878]
In reference to #2874 

Since we want a catch all, here's my preliminary suggestion

Complete all the free sections on https://www.learnallthenodes.com
Complete how-to-npm, learnyounode, expressworks, learnyoumongo from NodeSchool, in that order.
The first website is pretty cool, they have a paid subscription but that mostly gives you access to more niche topics as a way to support the website. Otherwise, they're dedicated to keeping the site updated and teaching node for free. The video series goes through the process of building a rich MEAN app from the ground up.
The second is a pretty huge and global open-source movement, so the tutorials will definitely stay up to date, as tons of workshops and sites like FreeCodeCamp rely on them.

Optional: Read this short article series on Medium
The first article talks about typical web applications, like those built with Rails
The second article talks about what the MEAN stack is and how it compares to Rails
The third article is short tutorial that builds the most basic MEAN app possible
Disclaimer, the author is a Ruby engineer but seems to bash Rails a bit.
I found the first two articles to be a great read, as he concisely explains the history and concepts surrounding web apps.
The third article was especially awesome since the code is so compact and simple, you can read the code and understand what it's doing, and it serves as a really sweet reference since most of it is boilerplate that you'll have to write for every MEAN app. To top it off, there's a small assignment at the end too.
https://medium.com/@dickeyxxx/mean-the-monolith-crusader-47b2c30936cd#.sdn4bwagu

Last, but not least, I found it a bit disconcerting that Node.js comes before front-end frameworks in TOP, which is the opposite of how it's taught anywhere else, online or offline. Even the link I removed suggested starting with front-end first.

**Comment by KevinMulhern** [comment]
Hey @prashcr, Thanks for putting this together, all of your suggestions make sense. You clearly know a lot about node.js which is something that we haven't focused on much in Odin. I have an idea, why don't you build out that part of the curriculum? it's a catch all at the moment because no one really has put much time into it lately other than @muzfuz, who has been working on improving parts of the Javascript course in the past couple of months. You could break it out into as many sections as you want for different concepts with node. It will also need a few projects.

If you don't want to do that, could you put a pull request together, with your all the changes you want to make implemented on the node section that already exists. I really like what you have suggested here and I am positive that it would improve the node section drastically. 

If you do decide to build out that part of the curriculum it would be worth talking to @muzfuz to exchange ideas.

**Comment by muzfuz** [comment]
Yea the JavaScript section needs a lot of love.  I'm happy to talk it through more, as there definitely needs to be a clear approach for students to learn how the various JavaScript technologies fit together.

**Comment by prashcr** [comment]
Sounds good +1

I guess for a first step, we can agree on moving the server-side after the front-end. Not sure how to do that here though, I'm guessing it's on the main repo?

**Comment by KevinMulhern** [comment]
I think you just add a new file to the curriculum repo. Do what you have to do @prashcr. Are you on the slack chat for Odin? we have a private contributions channel over there that I can invite you to, so we can get communicate instantly when you have questions, want feedback etc

**Comment by prashcr** [comment]
Yep, under the same username. I looked around here, but the curriculum repo deals strictly with content. The `seeds.rb` file in the main repo is what loads the curriculum files from here in a specified order.

**Comment by muzfuz** [comment]
I'm not totally sure I agree with moving front-end JavaScript before the back-end.

NodeJS is not a framework - it's an environment for running JavaScript on a computer, and therefore a great way to teach _plain_ JavaScript.  (Granted, the curriculum currently isn't geared toward that right now).

Once you start talking about front-end JavaScript, the various APIs (even those included with the browser) can muddy the waters enough to make it confusing for students who are looking to understand the JavaScript syntax first.

So to my mind, the first port of call for any student should actually be JavaScript within the Node environment, but without any of the standard packages that it includes.  That way, they can become familiar with the syntax of JavaScript functions and object before moving on to the abstractions that front-end frameworks and libraries introduce.

**Comment by prashcr** [comment]
That is a valid point and there are some great NodeSchool tutorials that go over plain JS (using Node).

However, assuming that students are completing the curriculum in order, by the time they get to either front-end or back-end JavaScript, they would've already completed Codecademy JavaScript, Codecademy JQuery, (optionally, CodeSchool JQuery), built Project Etch-a-Sketch, and solved 3 Project Euler problems with it, all from the compulsory parts of the curriculum.

Sure, there might be some gaps in their knowledge that aren't explicitly covered, such as functional programming (e.g. map, reduce, filter, call, bind, apply) or a solid understanding of scopes/closures, but we certainly don't have to go over the basics again.

I myself followed TOP's track for JavaScript in Web Dev 101 earlier this year (but I fully completed every tutorial they mentioned, instead of doing half and putting it off till later). From there, I was able to pick up map, reduce and filter through FreeCodeCamp's bonfires, while I learned scopes/closures via google.

I found two solid NodeSchool tutorials for both though
https://github.com/timoxley/functional-javascript-workshop
https://www.github.com/jesstelford/scope-chains-closures

**Comment by KevinMulhern** [comment]
Hey @prashcr are you still working on this or should I close this issue?

**Comment by prashcr** [comment]
Hey, my apologies, I've gotten a bit busy as of late, and I'm not actively working on it at the moment

**Comment by KevinMulhern** [comment]
Ok I will close this for now, but if you want to come back to it in the near future please let me know :)
