### ISSUE TITLE
Rock Paper Scissors: Clarify in the hint that knowledge of arrays is not required

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#28785]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

It has come up more than once in the community discord that people think they need arrays to be able to select one of the three choices at random. While there certainly is an array solution, it is not the only one. You can do this with basic conditional flow. 

This leads to friction where people find by research a solution that is using arrays and wonder why arrays have not been introduced yet if they were required for the problem - which is not the case.

A change to the hint on step 2 of the assignment to say that arrays (which are covered later in the curriculum) are not required could ease this sticking point

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-rock-paper-scissors

**Comment by XAJX179** [comment]
The hint clearly links `Math.random` i dont understand why anyone would go into rabbit hole of arrays but since its a recurring issue a clarification can help save many people go down that rabbit hole.

**Comment by TitanTankNate** [comment]
I wonder if previous programming or mathematics background has anything to do with the students misunderstanding?  I have previous background, so I was perfectly happy to not need arrays for this.  But I feel like the common thread connecting many of these confused students is a lack of programming background?

I could be wrong, might be worth "surveying"?  Or leaving as is?

**Comment by MaoShizhong** [comment]
I've always found it weird how despite the project clearly coming before the lesson in arrays, some people still have so much trouble recognising that arrays are not necessary.

Nonetheless, I don't think it'd hurt to just stick on a little `(you won't need arrays here)` or similar to the end of the hint.
