### ISSUE TITLE
Intermediate HTML and CSS | Browser Compatibility: Add Infographic Video

### ISSUE THREAD

**Issue by TitanTankNate** [TheOdinProject/curriculum#28783]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the lesson [Browser Compatibility, section Browser History](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-browser-compatibility#browser-history), I believe a fitting infographic video could serve to supplement the material for visual learners, either as in in-line hyperlink or as a link in **Additional Resources**.

I recommend [the following 4m30s video](https://www.youtube.com/watch?v=W4wWdmfOibY), which quickly details browser history via market share, and really hits home TOP's choice of Chrome as the default browser.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-browser-compatibility

### (Optional) Discord Name

Nate || Int. HTML/CSS ##%

**Comment by DrantDumani** [comment]
Maybe Adaptable doesn't need to be removed as a PaaS option and the information can be updated instead. The Ruby path deployment lesson still lists Heroku as an option even though they don't have a free tier (though I don't know if that's an oversight). Adaptable's build plan is also cheaper than Heroku's.

I know that the idea behind using PaaS sites during the curriculum is that we shouldn't be looking to pay for anything we make while following ToP though. So maybe we can keep Adaptable around until other free tier options can be added?

**Comment by TitanTankNate** [comment]
@DrantDumani I believe you meant to place this comment on another issue.  Perhaps [this one](https://github.com/TheOdinProject/curriculum/issues/28784)?

**Comment by Rajaravi99** [comment]
Hi, I am happy to work on this

**Comment by CouchofTomato** [comment]
All yours @TitanTankNate
