### ISSUE TITLE
Restaurant Page: Inhouse deployment instructions

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#28780]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The current instructions defer to this [gist](<https://gist.github.com/cobyism/4730490>), which works fine for the first deployment, but causes some friction in one way or another when a user needs to make a change to their src and redeploy.

The gist has the user commit dist to main, which learners are previously told they should avoid, but it does work. However when the user next makes changes and redeploy, the same gist will fail with a "current branch behind remote" warning. This can't be solved with a pull, since what's going on here is one local branch is trying to correspond to two remote branches at once. The whole situation gets confusing. 

I propose an alternate workflow that:
- avoids this confusion
- keeps dist out of main
- dist remains in .gitignore throughout

```sh
# Initial deployment

# Make sure you have committed all your source files first
git checkout -b gh-pages
npx webpack --mode='production'
git add dist -f && git commit -m "Deployment commit"
git subtree push --prefix dist origin gh-pages
git checkout main


# Redeploying changes

# Make sure you have committed all your source files first
git checkout gh-pages && git merge main --no-edit
npx webpack --mode='production'
git add dist -f && git commit -m "Deployment commit"
git subtree push --prefix dist origin gh-pages
git checkout main
```

The webpack command can be swapped out with whatever the user's build command looks like

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-restaurant-page

**Comment by MaoShizhong** [comment]
Thanks @damon314159. I'll take a look at this properly in due course, but so far looks promising!

**Comment by MaoShizhong** [comment]
I like it @damon314159.
We can split off the deployment to its own assignment subsection (rather than a step 8), then perhaps briefly explain each step as necessary?

Since this is for the Restaurant Page, we can omit the production mode bit since that won't be mentioned until the next lesson. Perhaps the explanation for that bit might say something like "Now let's bundle our application into `dist` with our build command. For now, that's `npx webpack`." or something like that.

I'll assign this to you.
