### ISSUE TITLE
Classes: Contradictory info

### ISSUE THREAD

**Issue by hi-its-jack** [TheOdinProject/curriculum#28797]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hello, in the overview you state that there isn't much new to learn and then this is followed with quite a lot of learning objectives and reading material. Seems a bit of contradiction. Maybe needs changing?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-classes

**Comment by MaoShizhong** [comment]
Thanks for the issue @hi-its-jack. I've personally had some ideas already about the JS Classes lesson, and I agree with you that the wording is a bit strange there. It does make sense, classes aren't really a new concept/mechanic in JS - they're almost entirely syntactic sugar for constructor functions and prototypes people would have already learnt about. So there's no big new mechanics to learn like with the factory functions lesson, for example.

That being said, the assignment section has gotten a bit out of hand IMHO, so I can totally understand someone coming in new going "huh? That's not a little..." even though a lot of it is just alternative (and nicer) syntax for some things.

I'll bring this up with the team, as I've set out some plans for a minor rewrite of that lesson that'll hopefully make the above clearer.

**Comment by hi-its-jack** [comment]
That's great, thank you. And I appreciate you getting back to me. Loving
the Odin Project btw. Such an amazing resource

**Comment by S-yartey007** [comment]
An amazing resource indeed.
