### ISSUE TITLE
JavaScript Recursion: make clear whether to complete the exercises in linked resource

### ISSUE THREAD

**Issue by thereisnodeveloper** [TheOdinProject/curriculum#28790]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Proposed Change
Make it explicitly clear that the reader does NOT have to do any of the exercises in the JavaScript.info "Intro to Recursion" article.

Assumptions
The reader will follow the Assignment articles in the order listed.
In the absence of explicit instructions, the reader is likely to attempt the exercises included in linked articles.
Problem
Vague Instructions:
In the [recursion lesson](https://www.theodinproject.com/lessons/javascript-recursive-methods), under the "### Assignment" section, there is a link to an article from JavaScript.info. This article contains exercises. The current instructions state to "Read this intro to recursion" but do not clarify whether or not the reader should complete the exercises in the article.

Why is this an issue?
Often, when an outside article is linked, readers may assume they are supposed to complete the exercises. This is especially confusing when instructions such as "Read and follow along" or "Read and code along" are not provided, which would normally tell readers to actively engage with the exercises.

This issue is further complicated by advice from the TOP Discord suggesting that readers should "always try to do the exercises in the readings, if there are any."

Example of implicit suggestion to complete exercises:
From the [Foundations lesson](https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals):

JavaScript.info has a good tutorial on logical operators. A little heads up regarding this reading’s tasks: there will be questions where you see alert() with a number or string inside the parentheses. What’s happening here will be discussed later in the curriculum. Some of the answers may not make sense now, but they are accurate, and you will understand them as you progress in the curriculum. Don’t worry too much about it now!

Overlapping Exercises:
There are exercises, such as Fibonacci, that appear both in the JavaScript.info article and in the later "Project: Recursion" lesson.

Why is this an issue?
When combined with the unclear instructions mentioned above, this could lead readers to attempt the Fibonacci exercise (and others) in the JavaScript.info article prematurely.

Suggestions
You might consider adding a clear statement like: "You are not required to complete the exercises in the linked article."
Another option could be to rephrase the current instructions to something like: "Read the article but focus on understanding the concepts. There is no need to complete the exercises at this stage."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods)

### Proposed Change

**Make it explicitly clear that the reader does NOT have to do any of the exercises in the JavaScript.info "Intro to Recursion" article.**

### Assumptions
- The reader will follow the Assignment articles in the order listed.
- In the absence of explicit instructions, the reader is likely to attempt the exercises included in linked articles.

### Problem

1. **Vague Instructions**:  
   In the [recursion lesson](https://www.theodinproject.com/lessons/javascript-recursive-methods), under the "### Assignment" section, there is a link to an article from JavaScript.info. This article contains exercises. The current instructions state to "Read this intro to recursion" but do not clarify whether or not the reader should complete the exercises in the article.

   **Why is this an issue?**  
   Often, when an outside article is linked, readers may assume they are supposed to complete the exercises. This is especially confusing when instructions such as "Read and follow along" or "Read and code along" are not provided, which would normally tell readers to actively engage with the exercises.

   This issue is further complicated by advice from the TOP Discord suggesting that readers should "always try to do the exercises in the readings, if there are any."

   - **Example of implicit suggestion to complete exercises**:  
   From the [Foundations lesson](https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals):  

     > JavaScript.info has a good tutorial on logical operators. A little heads up regarding this reading’s tasks: there will be questions where you see `alert()` with a number or string inside the parentheses. What’s happening here will be discussed later in the curriculum. Some of the answers may not make sense now, but they are accurate, and you will understand them as you progress in the curriculum. Don’t worry too much about it now!

2. **Overlapping Exercises**:  
   There are exercises, such as Fibonacci, that appear both in the JavaScript.info article and in the later "Project: Recursion" lesson.

   **Why is this an issue?**  
   When combined with the unclear instructions mentioned above, this could lead readers to attempt the Fibonacci exercise (and others) in the JavaScript.info article prematurely.

### Suggestions
- You might consider adding a clear statement like: "You are not required to complete the exercises in the linked article."
- Another option could be to rephrase the current instructions to something like: "Read the article but focus on understanding the concepts. There is no need to complete the exercises at this stage."

**Comment by MaoShizhong** [comment]
Thanks for opening the issue. Adding something like "You do not need to complete the exercises at the end of the article." to the relevant assignment step would be great - assigning this to you.
