### ISSUE TITLE
Foundations: Function Basics (assignment), Explicity mention where the output is obtained

### ISSUE THREAD

**Issue by eGOist-sys** [TheOdinProject/curriculum#28792]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Some people might forget that the output is not obtained on the browser, but the console tab in the dev tools. it might be better to clarify that the output.log() prints the data in console.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-function-basics

**Comment by Rajaravi99** [comment]
Hi, can I work on it

**Comment by MaoShizhong** [comment]
Thanks for opening the issue @eGOist-sys. Is this something you've seen as a common issue in the community?

Given the name of the function `console.log` and the "how to run JavaScript code" linked just above that part of the assignment (which does state that `console.log` outputs in the developer console), I haven't thought this to be a big issue and haven't noticed it much myself at least.

**Comment by eGOist-sys** [comment]
sorry for replying this late as my school exams just got over. @MaoShizhong you're correct this might not be a big issue. but from someone's perspective who has very little experience with javascript or coding in general, this serves as a good refresher. sorry if the issue was not relevant and feel free to close the issue
