### ISSUE TITLE
Foundation Object Basics: Rename page reference

### ISSUE THREAD

**Issue by lukegrob** [TheOdinProject/curriculum#28795]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Object Basics page Assignment, it links to the **Arrays and Loops** page like so: 
>that we introduced in the [Fundamentals Part 4](https://www.theodinproject.com/lessons/foundations-fundamentals-part-4) assignment

As the Arrays and Loops page was renamed in February from "Fundamentals Part 4" to "Arrays and Loops", I think it would make sense to rename this link on this page, although the underlying link URL remains current.

This would be a pretty straightforward change for somebody's first contribution.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-object-basics

**Comment by MaoShizhong** [comment]
Assigned to you :+1:
