### ISSUE TITLE
Advanced Grid Properties: <broken images>

### ISSUE THREAD

**Issue by Dev-Emad-777** [TheOdinProject/curriculum#28815]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

update the src of images in the HTML examples ( TOP logo) 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties

### (Optional) Additional Comments

we could replace src with https://logo.clearbit.com/www.theodinproject.com

**Comment by CouchofTomato** [comment]
Can you provide a bit more context to what you're proposing please

**Comment by Asartea** [comment]
I think they are saying that the TOP logos in the codepen examples are broken, but at least for me those seem to work just fine?

**Comment by Dev-Emad-777** [comment]
in the example code there are a bunch of images in the tutorial boxes the src attribute of this HTML element is broken i.e. (invalid URL ) not displaying images at all.

**Comment by CouchofTomato** [comment]
I can view the images fine. Seems maybe an issue with your firewall or network.
