### ISSUE TITLE
Library: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Boodac** [TheOdinProject/curriculum#28820]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I know this is probably the default expected behavior on assignments but since item 1 is already "If you haven’t already, set up your project with skeleton HTML/CSS and JS files" it feels appropriate for item 1 to mention that you will want a git repo configured as well (since it later will ask you to post the solution).

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-library

### (Optional) Additional Comments

:heart: u guys

**Comment by MaoShizhong** [comment]
Honestly, I'm not really sure we *need* that first step as it is - seems pretty much expected by now.

I guess to reinforce that point and for future projects, what do you think about the following wording for step 1:

> 1. Set up your project as usual (Git repo, skeleton HTML/CSS and JS),

**Comment by CouchofTomato** [comment]
This may be being addressed in https://github.com/TheOdinProject/curriculum/issues/28780

**Comment by MaoShizhong** [comment]
> This may be being addressed in #28780

@CouchofTomato the issue you linked is unrelated to this one (wrong issue perhaps?)

**Comment by MaoShizhong** [comment]
Agreed, I don't think it's a big deal and not one I've seen tripping people up in the community, so I'm more inclined to leave it as it is.

@Boodac Is this something you've seen causing confusion with learners? Or more just a "for the sake of completeness of wording" sort of thing?

**Comment by Boodac** [comment]
> Agreed, I don't think it's a big deal and not one I've seen tripping people up in the community, so I'm more inclined to leave it as it is.
> 
> @Boodac Is this something you've seen causing confusion with learners? Or more just a "for the sake of completeness of wording" sort of thing?

It's something that briefly gave me pause, and I noticed both the assignment *before* and the assignment *after* mention the gir reply, so I would guess my answer would be more for consistency.

That said, I don't think imposter syndrome really goes away even this deep in the TOP. There are a lot of people in discord who are still very unsure of themselves by the time they hit library. Clarity can't ever really be a bad thing in the curriculum.

**Comment by MaoShizhong** [comment]
Fair enough. I'll assign this to you then, whether you wish to use the wording suggestion above or your own equivalent.

**Comment by MaoShizhong** [comment]
I only just realised that you didn't tick the assignment box @Boodac 

If you're happy to PR this then awesome. Otherwise, let me know if you'd rather I unassign then open for others to request assignment.

**Comment by Lofty-Brambles** [comment]
@MaoShizhong - If this is still an issue, maybe I can PR by replacing the first point with:
"If you haven’t already, set up a Git repository for your project with skeleton HTML/CSS and JS files. From here on out, we'll assume that you have already done this."
