### ISSUE TITLE
JavaScript: Clarify Coursera's Algorithm course video watch time 

### ISSUE THREAD

**Issue by ZackHoang** [TheOdinProject/curriculum#28849]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I was going through the resources linked in the assignment box of the Common Data Structures and Algorithm lesson in the JavaScript course. In the second assignment, it was written as so: 

![Screenshot from 2024-09-23 15-36-56](https://github.com/user-attachments/assets/3b31f9b8-771a-409d-b1a2-6abdfe4d5ffc)

`Learn about basic algorithms from [Coursera’s Algorithms course](https://www.youtube.com/watch?v=u2TwK3fED8A). The first 10 minutes are really the meat of the introduction to algorithms, the rest gets more mathematical (if you’re so inclined).`

Based on the wording, I thought that learners were supposed to watch the entire course playlist on YouTube, only to have found out that learners only need to watch at least the first 10 minutes of the video, thanks to clarification coming from @takinabradley
from our TOP discord. The miswording on this lesson might lead learners to watch the entire playlist, which is unintentional because the goal of this lesson is to introduce learners to the importance of Algorithm in programming. 

I would like to suggest some clearer wording here, which is to simply say to only watch the linked video (most importantly the first 10 minutes), not the entire course playlist, but they can if they are so inclined. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-common-data-structures-and-algorithms

### (Optional) Discord Name

vietanhhoang2507

**Comment by CouchofTomato** [comment]
Yeah I'm happy if you want to make a PR to clarify that only the linked video should be watched.
