### ISSUE TITLE
Intermediate HTML and CSS: Minor grammar error in the "Form Basics" lesson

### ISSUE THREAD

**Issue by june062** [TheOdinProject/curriculum#28855]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the assignment section of the Form Basics lesson, the instructions say to, "Read and follow along to..." when it should be "Read and follow along with..."

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-basics#assignment

**Comment by june062** [comment]
Please assign to me if you can. I'm ready to submit a PR.

**Comment by MaoShizhong** [comment]
All yours @june062
