### ISSUE TITLE
Block and Inline: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Theologicode** [TheOdinProject/curriculum#28851]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a link to a Youtube video here that is a music video, "Never Gonna Give You Up". I don't know necessarily that it is an error, but it looks like one to me. Nothing against Mr. Asterley.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-block-and-inline

### (Optional) Discord Name

zehsphyr

**Comment by damon314159** [comment]
That's there intentionally - it's a little easter egg of sorts

**Comment by MaoShizhong** [comment]
Yep, it's a longstanding internet joke that we put in on purpose and love seeing people come into Discord talking about it when they get caught out :)

Closing this issue as no action is required for this.
