### ISSUE TITLE
Getting Started: Knowledge check questions outdated

### ISSUE THREAD

**Issue by T0nci** [TheOdinProject/curriculum#28861]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The last three Knowledge check questions are for `npm` and the problem is that `npm` isn't mentioned much in the lesson(I think that is because there was content for `npm` but it was removed in some PR) - only just a few sentences in the W3Schools lesson in which they don't mention anything about local or global packages. They are just outdated. Only the first question is related to the material and the rest of the built-in Node packages we learn about have no questions about them.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-getting-started

**Comment by MaoShizhong** [comment]
Ah yes, looks like carryover from old material. All yours to remove those KC questions.

**Comment by T0nci** [comment]
What are your thoughts on adding relevant KC questions? Is it something that isn't needed since the user can test his knowledge in the first project?
