### ISSUE TITLE
Asynchronous JavaScript and APIs: Expand/clarify try...catch

### ISSUE THREAD

**Issue by c8in4** [TheOdinProject/curriculum#28866]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I suggest adding a lesson about `try...catch`.

It comes up for the first time in the [Working with APIs](https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis#fetching-data) as an example for the 'old' way to make an API request before introducing `fetch()`.

In comes up again in the following lesson  [Async and Await](https://www.theodinproject.com/lessons/node-path-javascript-async-and-await#error-handling) in the 'Error Handling' section. Here it is referenced like knowledge that should have been covered already in the curriculum but it hasn't been covered.

I'm not sure where to add this lesson maybe in the [Javascript in the Real World](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript#javascript-in-the-real-world) part of the curriculum.

### Path

Node / JS

### Lesson Url

I mentioned and linked the lessons in the 'suggestion' section.

### (Optional) Additional Comments

Let me know what you guys think. I just found myself being confused and thinking that I have missed part of the curriculum when I encountered `try...catch` in the before mentioned lessons.

I'd love to work on a `try...catch` lesson myself but I'd prefer to have somebody more experienced to help me with it.

Cheers

**Comment by T0nci** [comment]
I love the idea! Although a `try...catch` lesson might be overkill, an assignment MDN page or article in an already existing lesson(like Async and Await) would be perfect in my opinion.

**Comment by MaoShizhong** [comment]
`try...catch` definitely wouldn't need its own lesson but I wouldn't be opposed of course to expanding on in just a little for more clarity.

The way its currently presented is because it's not really anything all that new conceptually from what's already been shown.

If you use `.then()` syntax, then you'll want a `.catch()` call to handle any JS errors thrown along the Promise chain. Alternatively, you can use `async/await` syntax inside a `try` block, where you need a `catch` block to handle any JS errors thrown inside the `try` block. Same principle. `finally` blocks are handled the same way as `.finally()` in that syntax.

The context that the lesson introduces `try...catch` in is pretty much just alternative syntax (allowing for async/await syntax) for the `.then().catch()` syntax shown already.

What do you think about the following:

1. When `try...catch` is first mentioned, link to the MDN docs on [try/catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch).
2. Expand that paragraph just a little further e.g.
   > But there is another way: the mighty [try/catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) block! If you want to handle the error directly inside the async function, you can use `try/catch` with `async/await` syntax. If JavaScript throws an error in the `try` block, the `catch` block code will run instead (this can also be used for synchronous code).

**Comment by c8in4** [comment]
That sounds good. It just felt to me like I missed something because `try...catch` also appears in the [Fetch documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) in the first assignment of the [Working with APIs](https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis) lesson (which comes before the [Async and Await](https://www.theodinproject.com/lessons/node-path-javascript-async-and-await) lesson).

> What do you think about the following:
> 
>     1. When `try...catch` is first mentioned, link to the MDN docs on [try/catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch).
> 
>     2. Expand that paragraph just a little further e.g.
>        > But there is another way: the mighty [try/catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) block! If you want to handle the error directly inside the async function, you can use `try/catch` with `async/await` syntax. If JavaScript throws an error in the `try` block, the `catch` block code will run instead (this can also be used for synchronous code).

1. Should we add this as the first assignment to the [Working with APIs](https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis) lesson?

2. Should we add [lavascript.info on Error handling](https://javascript.info/try-catch) to the 'Additional resources' section of the [Async and Await](https://www.theodinproject.com/lessons/node-path-javascript-async-and-await) lesson?

**Comment by MaoShizhong** [comment]
The thing is that the first and last assignment resources in the [async await lesson](https://www.theodinproject.com/lessons/node-path-javascript-async-and-await#assignment) already go through `try...catch` syntax (of which the first one is already from javascript.info).

The Working with APIs lesson's example, as well as the first fetch docs example do include a try catch but the point of those examples isn't to focus on the try catch syntax, but literally just to show a code implementation of something. try catch only becomes an actual teaching point in the async await lesson and as above, in context is just alternative syntax for stuff that's already been taught.

So IMHO, we wouldn't need an additional resource but a slight rephrasing of the try catch paragraph + a link to the try catch docs ought to make a clearer introduction.

**Comment by c8in4** [comment]
Okay,
I'll work on that if that's alright with you.
@MaoShizhong

Do you just want me to make the change and create a PR or do you prefer it another way?

**Comment by MaoShizhong** [comment]
I'll assign you @c8in4 so you can open a PR when you're able to. A maintainer, whether me or someone else, can review it when they're able to.

**Comment by c8in4** [comment]
Sorry, my first PR failed a check. So I closed that one a created a new one.
Is it better practice to create a draft first or what's the recommended procedure?

**Comment by MaoShizhong** [comment]
> Sorry, my first PR failed a check. So I closed that one and created a new one. Is it better practice to create a draft first or what's the recommended procedure?

You don't need to close any PRs. PRs just track the branch you want us to pull code from, so if you need to make any changes, you just commit and push those changes to that branch. The PR on GitHub will update automatically.

With lint check failures, like you've done, if it's a straightforward stylistic issue like omitting necessary blank lines then you can just address it as per the error message. If it's a more contextual lint error (e.g. heading structure) then just comment asking if you need to do anything and a maintainer will let you know when reviewing.
