### ISSUE TITLE
<Intermediate HTML and CSS>: <Media queries are mentioned, but haven't yet been taught>

### ISSUE THREAD

**Issue by AngelMsaa** [TheOdinProject/curriculum#28885]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I thought media queries were a topic that was going to be taught later on, but they came up in the Custom Properties lesson to explain `prefers-color-scheme` and mentioned as if they had already been taught. It confused me, making me wonder if I had missed a lesson or something, only to find out it's supposed to be taught on Advanced HTML and CSS. 

It might be good either to briefly introduce them, explain that they'll be taught later on, or both. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-custom-properties#media-queries

**Comment by sarthakvermaa** [comment]
Hi @AngelMsaa! I would like to work on this issue. Can you please explain this issue in detail?

**Comment by AngelMsaa** [comment]
The following piece of text assumes prior knowledge of media queries, which was confusing as I hadn't been formally introduced to how media queries work. Since the course content hadn't covered them yet, it felt like I missed something or overlooked a previous lesson.

I reviewed the course structure, and realized that these were taught as part of a later lesson. To avoid this confusion, it might be helpful either to provide a brief explanation of what media queries are, clarify that these will be covered in the future, or both: 

I'm unsure what other details I can provide aside from repeating the suggestion.  Do let me know if you have any questions!

> Giving users the ability to toggle a theme themselves is great, but there’s another option for setting a theme that you may have come across on certain sites or applications: using the user’s theme setting from their operating system or user agent (like a browser). This can be accomplished with the prefers-color-scheme media query, which checks whether a user has selected a theme preference on their OS/user agent. As you view the example below, try changing the theme settings on your OS/user agent to see how the example updates in real time!
> 
> We first added custom properties on the :root element outside of the media query. This gives us a default theme in case a user doesn’t have a preference set on their OS or user agent, or if a browser doesn’t support the media query. In this case, we’re using our “light” theme colors as the default. Then we added a prefers-color-scheme media query for when a user has a dark theme set in their preferences.
> 
> Using the prefers-color-scheme media query can be pretty helpful for users since it doesn’t require them to manually change the theme to their preferred one. That said, you need to be aware of a few things when it comes to using this media query:
> 
> Only dark and light are valid values for the media query, so you can’t use it to implement any themes beyond these two basic ones.
> The light value for the media query is actually for when a user has a light theme specified or when they have no preference set.
> It doesn’t allow users to change the theme themselves, which can still be important in cases where a user might want to use the theme opposite of their OS/user agent preferred one for whatever reason.

Media Queries are specifically talked about, but

**Comment by sarthakvermaa** [comment]
@AngelMsaa So problem is only about mentioning prefers-color-scheme as if they were taught right? If I'm missing something please do tell. Till then, i will try to resolve this issue. Please assign.

**Comment by AngelMsaa** [comment]
No, not prefers-color-scheme, but Media Queries (https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-media-queries). Maybe a fix for this would be: 

> This can be done using the prefers-color-scheme media query, which lets you apply different styles based on the user's device or settings, like screen size or theme preference (light/dark mode).
>
> The prefers-color-scheme query checks if the user has selected a theme on their OS or browser. Don’t worry, we’ll cover media queries in more detail later. For now, try changing your OS or browser theme to see the example update in real time!

**Comment by JoshDevHub** [comment]
Thank you for making this issue @AngelMsaa 

I'm going to ping our @TheOdinProject/html-css team and get their opinions on how to proceed with this.

Thank you for your interest in working on this @sarthakvermaa. Please hold off on actually doing any work or submitting a PR for this issue until a maintainer from the HTML/CSS team takes a look at this and determines the best course of action.

**Comment by MaoShizhong** [comment]
I like the wording that @AngelMsaa proposed. Assigning you @sarthakvermaa to amend the end of the relevant paragraph accordingly.
