### ISSUE TITLE
Flight Booker: Fix broken Stripe link

### ISSUE THREAD

**Issue by jambalong** [TheOdinProject/curriculum#28888]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Issue:
This is technically not a duplicate of #28203 since that issue has been closed. However, I noticed in the `project_flight_booker.md` file, the sentence referring about Stripe integration is still hyperlinked to: https://stripe.com/docs/checkout/guides/rails due to a #28365 commit reversing the previous fix

### Suggested Fix:
I can update the hyperlink to point to the new documentation page: [Stripe Checkout](https://docs.stripe.com/checkout/quickstart)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-flight-booker

**Comment by JoshDevHub** [comment]
Thank you for making this issue @jambalong ! Your fix sounds good to me. I'll assign you.
