### ISSUE TITLE
Routes: For importing router only relative paths are working

### ISSUE THREAD

**Issue by Jashbaua** [TheOdinProject/curriculum#28900]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the last app.js code for importing routers it uses
const booksRouter = require("routes/booksRouter"); 
which gives this error 'Error: Cannot find module 'routes/authorsRouter'
instead  using relative path 
const booksRouter = require("./routes/booksRouter"); fixes it

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-routes

### (Optional) Discord Name

jash00994

**Comment by MaoShizhong** [comment]
Oops - good spot. Will be fixed in #28763
