### ISSUE TITLE
JavaScript: Clarify the worst-case scenario example in Big Ω (Omega notation) section

### ISSUE THREAD

**Issue by Maddily** [TheOdinProject/curriculum#28903]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I think that the explanation of the worst-case scenario under the **Big Ω (Omega notation)** section in the **Time Complexity** lesson is inaccurate/incomplete.

The lesson describes it as follows:
> In the worst case (Big O), which would happen if the item is not in the array, we would say it had linear complexity O(N). This is because the item we are looking for is not in the array, so our code must iterate on every value.

However, this explanation overlooks another important worst-case scenario: what if the element we're looking for is the last one in the array?

I believe the worst-case scenario can occur in two situations:
- **Item not found**: Same as the lesson explains, the algorithm must check each element, resulting in O(n) complexity.
- **Item found at the last position:** In this case, we would also check each element, including the last element, which again results in a time complexity of O(n).

Clarifying both scenarios is essential for a complete understanding of time complexity. Let me know what you think.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-time-complexity

### (Optional) Discord Name

Maddie

**Comment by JoshDevHub** [comment]
Yeah I think it's find to mention if the needle is the final element. I'll assign you. Be sure to also fix this in the Ruby course's version of this lesson.

**Comment by Maddily** [comment]
Thanks! I'll make sure to update both versions.
