### ISSUE TITLE
DOM Manipulation and Events: Confusing code example

### ISSUE THREAD

**Issue by Rokenrol** [TheOdinProject/curriculum#28908]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In "Targeting nodes with selectors" section there is an example of how to select child and sibling elements but it's written in such a way that it's likely to make people think that console.dir() method has something to do with selecting the elements.

A few days ago someone spent 2 hours in one of the js help channels trying to understand why console.dir is not selecting the child element when he was trying to recreate the example and helpers didn't understand what he was asking. Using variables instead of console.dir() would be less confusing for learners.

![example](https://github.com/user-attachments/assets/bdda4ff3-0a3b-427e-8093-d893e2f1e484)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

### (Optional) Discord Name

Rokenrol

**Comment by JoshDevHub** [comment]
Thank you for making this issue @Rokenrol 

Going to ping our @TheOdinProject/foundations team and see if anyone has input on this.

**Comment by MaoShizhong** [comment]
Agreed that the current comment wording makes it look like `console.dir` is involved in the selecting.

2 resolutions come to mind - no strong feelings about either, so let me know what you think:
1. Change the comments to say something like `// logs the...` instead of `// selects the...`, and change `console.dir` to `console.log`. This is the only place in the curriculum where `console.dir` is mentioned (literally just those two lines) so I think `console.log` will be more familiar at very little "loss".
2. Assign to variables instead of `console.dir`, though since both examples select the same element, you can't use the same variable name.

**Comment by davidumoru** [comment]
@MaoShizhong Can I work on this?

I think the first option (change to console.log) would be simpler and clearer for learners at this stage, especially since console.log is more familiar.

**Comment by Rokenrol** [comment]
I like the second one (assigning to variables) better, something like `const child = container.firstElementChild` and `const sibling = controls.previousElementSibling`, it's consistent with other two lines of code in the example.

**Comment by unconsideredtrifles** [comment]
Seconding @Rokenrol. I also prefer the second option.

**Comment by Lofty-Brambles** [comment]
The reason why it is `console.dir` is probably because it's for someone to put up in a REPL and check. I'd say, doing both would be a better option - assign to a variable with the comment `// selects ...` and add the `// logs ...` comment with a `console.log` after it.

**Comment by MaoShizhong** [comment]
Sorry a response took a while.

I like Lofty's hybrid suggestion. Assign to a variable - we would need to consider appropriate names considering the example selects the same element each time, or the HTML can be amended slightly so the example selects a different element each time, allowing for easier naming.

Then have a log after each one with an appropriate comment.

Happy to handle this @davidumoru? If so, I'll assign you.

**Comment by davidumoru** [comment]
> Sorry a response took a while.
> 
> I like Lofty's hybrid suggestion. Assign to a variable - we would need to consider appropriate names considering the example selects the same element each time, or the HTML can be amended slightly so the example selects a different element each time, allowing for easier naming.
> 
> Then have a log after each one with an appropriate comment.
> 
> Happy to handle this @davidumoru? If so, I'll assign you.

Yes, I'd like to take on this task. Please go ahead and assign it to me.
