### ISSUE TITLE
HTML Foundations/Project: Recipes: Add Instructions to Reuse HTML Boilerplate

### ISSUE THREAD

**Issue by alexanderlotz** [TheOdinProject/curriculum#28910]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

While the first section of the Recipes project instructs users to recreate the previously learned HTML boilerplate in `index.html`, there is no mention to add the same boilerplate to the recipe pages created afterwards. In its omission, there is an implication that the boilerplate is not necessary. Section two of this project should be updated with the instructions to use the HTML boilerplate in all created `.html` files to reinforce its importance.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes#iteration-2-recipe-page

**Comment by MaoShizhong** [comment]
Fair suggestion - might as well ensure clarity while it's new. @weeezik assigned

**Comment by weeezik** [comment]
I included commits from a different branch in this pull request by mistake. Submitting a new PR soon.
