### ISSUE TITLE
Webpack: I noticed that the first paragraph could be improved for grammar and clarity

### ISSUE THREAD

**Issue by RaihanSharif** [TheOdinProject/curriculum#28917]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

>While the introduction of ESM greatly mitigated some of the issues with managing individual script files and dependencies, there would still be performance issues to consider the more module files the browser would have to download individually (especially as more third-party libraries would be imported).

Would perhaps be clearer like this:

>The introduction of ESM greatly mitigated some of the issues with managing individual script files and dependencies. However, downloading a large number of module files individually can reduce perforamance, especially as more third party files are imported.

The latter breaks it down into two sentences which is a bit easier to understand.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-webpack

### (Optional) Discord Name

freakzilla149

**Comment by MaoShizhong** [comment]
Sensible improvement to me - go for it!
