### ISSUE TITLE
Intermediate HTML and CSS, Grid [Exact lesson up for discussion]: Additional Grid resource

### ISSUE THREAD

**Issue by Lofty-Brambles** [TheOdinProject/curriculum#28928]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Josh W. Commeau has an excellent (relatively?) new [CSS Grid article](https://www.joshwcomeau.com/css/interactive-guide-to-grid/)! As with his excellent flexbox article and it's interactive examples, this one is a pleasure to read. Wouldn't mind seeing this as a resource in the curriculum!

There might be a small question of where to add this article. Since this does use properties mentioned in the [Advanced Grid Properties](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties) lesson, it might be suited to be the first assignment itself, as a visualization of what's done thus far, before we ask the learner to do the exercises.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties

### (Optional) Discord Name

_lofty.dev

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/html-css thoughts?

**Comment by devnchill** [comment]
This lesson is already included in *additional resources* of [Advanced Grid Properties](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties#additional-resources)

**Comment by CouchofTomato** [comment]
If it's already included then I'll close this out
