### ISSUE TITLE
JavaScript: Broken Link on assignments section of "Testing Basics"

### ISSUE THREAD

**Issue by brandon-parkerson** [TheOdinProject/curriculum#28936]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The first link on the assignments section of "Testing Basics" from the JavaScript course goes to a page that does not load currently.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-testing-basics

### (Optional) Additional Comments

I can try to fix this if given a new link/resource. Keep in mind, I have never contributed to a project before. Thanks!

**Comment by MaoShizhong** [comment]
Holding off on this for a bit since it's a webarchive link and [webarchive just recently got DDoSed](https://www.engadget.com/cybersecurity/the-internet-archive-taken-down-by-ddos-attacks-222317044.html). So we're expecting our links to sites through them to be down for a bit.

**Comment by Sivasankar300** [comment]
That article is also on Medium it would seem. https://medium.com/@andrewlatta/why-learning-to-code-is-so-damn-hard-303eae632820, since I recall having read this before from the curriculum.

Though, Unless Archive.org doesn't come back up soon I doubt the link has to be changed.

**Comment by MaoShizhong** [comment]
We have a fair number of webarchive links throughout the curriculum. They're a huge resource and the DDoS attack was equally as huge, so they will be down for a little longer to do the right maintenance.

They will be back up eventually, just need to keep an eye on the situation.

**Comment by MaoShizhong** [comment]
Webarchive and our relevant links seem to be back up for me and have been so for a few days, as well as for others.
I'll close this issue now. If new problems with links arise then feel free to open a new issue for them.
