### ISSUE TITLE
OOP Principles: Broken Link in Assignment Section

### ISSUE THREAD

**Issue by assaf-git** [TheOdinProject/curriculum#28938]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It seems that the link of assignment no.2 is broken.

Error message received: 
"This site cannot be reached"

[https://web.archive.org/web/20200810210808/https://medium.com/@alexcastrounis/how-to-write-highly-scalable-and-maintainable-javascript-coupling-c860787dbdd4](url)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-oop-principles

### (Optional) Discord Name

_g00db0i_

**Comment by MaoShizhong** [comment]
Related https://github.com/TheOdinProject/curriculum/issues/28936#issuecomment-2405582372

**Comment by Goutamchoudhary907** [comment]
I want to work on this can you assign this to me

**Comment by assaf-git** [comment]
@Goutamchoudhary907  webarchive is back up and running
