### ISSUE TITLE
Introduction to Web Development: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Pipytoe** [TheOdinProject/curriculum#28951]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In "Conclusions" there is a suggested link in Assignments that doesnt load it is #1 "Why Learning to Code is So Damn Hard"

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

**Comment by MaoShizhong** [comment]
Webarchive (which a fair few of our links come from) was recently hit by a huge DDoS attack, so is temporarily down.
https://github.com/TheOdinProject/curriculum/issues/28936#issuecomment-2405582372

**Comment by Gabriel-Clements** [comment]
This may not be the right blog post the site was trying to link to, but it seemed right to me: https://medium.com/@andrewlatta/why-learning-to-code-is-so-damn-hard-303eae632820

**Comment by JoshDevHub** [comment]
We really don't want to use the medium link because it's plagiarism that doesn't give any credit or mention to the original author of the article.

@MaoShizhong There were plans to get this put on TOP's blog, but I can't do it myself for a couple of different reasons. I'll bring it up with the team.

**Comment by MaoShizhong** [comment]
Webarchive and our relevant links seem to be back up for me and have been so for a few days, as well as for others.
I'll close this issue now. If new problems with links arise then feel free to open a new issue for them.
