### ISSUE TITLE
Frameworks and Preprocessors: <The first link in the Assignment section is broken>

### ISSUE THREAD

**Issue by Ann2909** [TheOdinProject/curriculum#28952]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The first link in the Assignment section is broken

It says "This site can't be reached" when I clicked into it

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-frameworks-and-preprocessors

**Comment by davidumoru** [comment]
Hi @Ann2909,

Are you referring to the [brief overview of CSS frameworks](https://medium.com/html-all-the-things/what-is-a-css-framework-f758ef0b1a11)? If so, I was able to access it without any issues. If you're still facing this problem, it might be worth checking your connection or browser settings...

**Comment by wise-king-sullyman** [comment]
Seems to be working for me as well so I'm going to close this issue. If it's still not working for you though @Ann2909 feel free to reopen and we'll see if anyone else reports the same thing.
