### ISSUE TITLE
Installations: Suggestion that Chrome installation should be .deb and not a flatpak

### ISSUE THREAD

**Issue by mar2177** [TheOdinProject/curriculum#28950]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I think it should be menthioned that when installing a web browser, to be sure is a .deb  and not a flatpak. I was using the default installation which was flatpak, and when I reached the lesson in html where we add a local link, the "About Page"  and also an image that was provided, it was not working using the local links  like:   ./pages/about.html ..  as described in the lesson. 
After a lot of reasearch I learnt that local links and terminal commands work differently with flatpaks since they are like isolated instalations

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### (Optional) Additional Comments

The text should be corrected in the installations lesson:  https://www.theodinproject.com/lessons/foundations-installations

But the lesson where I was affected by this lack of information was here: https://www.theodinproject.com/lessons/foundations-links-and-images
Maybe could be added "note comment" also in this lesson "links and images"

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/installations thoughts?

**Comment by xandora** [comment]
I think we already make it pretty clear when we instruct users to download and install the deb version of Chrome

**Comment by o1Suleyman** [comment]
Ubuntu which is the recommended distro does not support Flatpaks by default. I think anyone that went out of their way to install Flatpak/Flathub should know better than to install the Flatpak instead of the deb.
