### ISSUE TITLE
Computer Basics: The password section is lacking Catch Phrase approach

### ISSUE THREAD

**Issue by stormlyte** [TheOdinProject/curriculum#28957]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Password section is outdated. Change to a source that include the Catch Phrase method, as that promotes users to create longer and still secure passwords.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-computer-basics#assignment

**Comment by Keshav-1803** [comment]
I would like to work on this issue... Can you assign it to me under gssoc and hacktoberfest ?

**Comment by wise-king-sullyman** [comment]
Thanks for making this issue, but I would actually prefer to keep the current resource. I believe it is perfectly adequate for our purposes, and having all the assigned reading in this section come from one source is great from a maintainability perspective. 

For those reasons I am going to close this issue, but thanks again for raising it, and thank you @Keshav-1803 for volunteering!
