### ISSUE TITLE
Form Validation with JavaScript: Change to questions in Knowledge Check

### ISSUE THREAD

**Issue by Meltasy** [TheOdinProject/curriculum#28969]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Knowledge Check section states ... "The following questions ...", yet all but one of them are actually written as questions. Do you think we should amend them all to be written as questions? Also, I wonder whether we should remove the last question, because I think it would have already been answered in the first question, or am I missing something?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-form-validation-with-javascript

### (Optional) Discord Name

Meltasy

### (Optional) Additional Comments

Issue #27279 is about refactoring the section which contains this lesson, so I'm not sure if you would want to hold off on this issue and address it at the same time as that issue.

**Comment by MaoShizhong** [comment]
Assigning you to rewrite the KC questions as actual question (which they should be of course). And yes, you can remove the last one since it's redundant because of the second KC question.

**Comment by Meltasy** [comment]
Thanks, I'll get on to that now :-)

**Comment by Meltasy** [comment]
Done :-)
