### ISSUE TITLE
Restaurant Page: <website in the assignment not working>

### ISSUE THREAD

**Issue by chillingTurtl** [TheOdinProject/curriculum#28989]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

the student's live preview example in the assignment section does not load and instead shows the error: 503 Service Unavailable

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-restaurant-page

### (Optional) Discord Name

yasdyvus

### (Optional) Additional Comments

You can't imagine how much I appreciate the work you guys are doing, and I'm proud to be part of the community

**Comment by CodeMaverick2** [comment]
It works you should check once more


![image](https://github.com/user-attachments/assets/f96456de-37de-4f30-9d39-b01fa25f0dae)

**Comment by Mohamedsayhii** [comment]
The link in the assignment is not working because it's part of the web archive site which down at the moment. Sadly the website is down because of cyberattacks.

**Comment by MaoShizhong** [comment]
@chillingTurtl still down for you or back up?
It's back up on my end and should be fine for people now since webarchive unfortunately went down due to DDoS attacks recently, but have since recovered.
