### ISSUE TITLE
Arrays and Loops: 'Skip' is written as 'Skim'

### ISSUE THREAD

**Issue by RemanthManyam** [TheOdinProject/curriculum#28987]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the loops section ,the 2nd resource or "2." has a typo. In the braces it says 'Skim the info...' instead of 'Skip the info...'

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-arrays-and-loops#loops

### (Optional) Discord Name

mysticgohan970

**Comment by CodeMaverick2** [comment]
I would like to solve this issue

**Comment by JoshDevHub** [comment]
I don't really see this as a typo, but I'm also glad to get a 2nd opinion from someone on the foundations team @TheOdinProject/foundations 

@CodeMaverick2 Thank you for your eagerness to contribute to the curriculum. Unfortunately we will have to close your PR. The author of this issue checked the box saying they'd like to work on this. When this is the case, we give priority to the issue author. It's important in the future to wait to be assigned an issue by a maintainer. This helps avoid duplicate work and wasted time. Hopefully you understand.

**Comment by MaoShizhong** [comment]
Also don't see any typo but honestly, we can probably just remove the "skim" bit altogether and just remind about the exercises. Feels a bit odd having that be the only thing we mention "skimming" with, and we really don't need to.

**Comment by JoshDevHub** [comment]
Yeah I actually agree with that @MaoShizhong 

Let's just remove that entire parenthetical bit @RemanthManyam

Instead of
> 2. Once again, same info, slightly different context from [JavaScript.info’s “Loops: While and For”](http://javascript.info/while-for). (Skim the info if you think you know it all, but don’t forget the tasks at the end of the page. You learn best by doing.)

Just have
> Once again, same info, slightly different context from [JavaScript.info’s “Loops: While and For”](http://javascript.info/while-for).

Since you indicated you'd like to work on this, I'll assign you. Let us know if you have any questions.

**Comment by MaoShizhong** [comment]
Nit, can we also get rid of the parens? No reason for those sentences to be in parens, and it looks extra weird punctuation-wise :sweat_smile:

**Comment by JoshDevHub** [comment]
Sounds great to me :thumbsup:
