### ISSUE TITLE
Discrepancy in code snippets in one of the lessons

### ISSUE THREAD

**Issue by B1t-Master** [TheOdinProject/curriculum#28999]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Under the lesson Factory Functions and the Module pattern, under the sub section "Prototypal inheritance with factories" , there are two code snippets and are implied they are supposed to do the **exact** same thing. However they vary slightly , the first code snippet creates a "discord username" for the created player , but the second does not do so.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern

### (Optional) Discord Name

bitmast3r

**Comment by EdMagal** [comment]
I don't think they are meant to do the same thing.
Both examples are about inheriting from `createUser` function, but in the first example the code "extract what you need from it, and re-return whatever you want to - hiding the rest as some private variables or functions!". In the otherhand, the second example is meant to be used in "case you want to extend" the `createUser` function.

First example discards the discordName.
Second example keeps everything `createUser` has to offer and adds more.
Right? :)

**Comment by B1t-Master** [comment]
> I don't think they are meant to do the same thing. Both examples are about inheriting from `createUser` function, but in the first example the code "extract what you need from it, and re-return whatever you want to - hiding the rest as some private variables or functions!". In the otherhand, the second example is meant to be used in "case you want to extend" the `createUser` function.
> 
> First example discards the discordName. Second example keeps everything `createUser` has to offer and adds more. Right? :)

Ahh I see , let me promptly close the issue then :+1:
