### ISSUE TITLE
Foundations: DOM Enlightment link in DOM Manipulation and Events lesson is dead

### ISSUE THREAD

**Issue by bizarf** [TheOdinProject/curriculum#28996]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the lesson "DOM Manipulation and Events" in the Foundations Course, there is a link to DOM Enlightenment in the additional resources section. This link no longer works as the domain has expired and instead leads to a GoDaddy page. Luckily there is a backup on Wayback Machine from Sept 29 which contains all of the information as it was a single page site. I would like to replace the current link with this one. 

https://web.archive.org/web/20240929034805/http://domenlightenment.com/

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

### (Optional) Discord Name

bizarf

**Comment by CouchofTomato** [comment]
As it's an additional resource only we can probably just remove it as an alternative. Do you think there's something in there worth keeping?

**Comment by bizarf** [comment]
> As it's an additional resource only we can probably just remove it as an alternative. Do you think there's something in there worth keeping?

That's a good question. I've never read this resource, so I can't really say if there is anything noteworthy. Someone else wanted to read it, so I checked if there was a backup. I guess removing it might be a better option since there's enough additional resources listed.

**Comment by CouchofTomato** [comment]
Happy if you want to open a PR to remove it
