### ISSUE TITLE
Intermediate HTML and CSS: Update outdated resources in the Browser Compatibility lesson

### ISSUE THREAD

**Issue by PivtoranisV** [TheOdinProject/curriculum#29003]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the [Additional resources](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby#additional-resources) section, we provide a [link](https://web.dev/articles/howbrowserswork) to the article (and it is an excellent article by the way), and first, what learner see when open this article is screaming burner, that it is outdated and much of this content is no longer accurate
<img width="908" alt="Screenshot 2024-10-25 at 12 17 09" src="https://github.com/user-attachments/assets/23627d11-1e93-4095-8571-bb284c2351bc">

I suggest updating this resource with this [article](https://github.com/vasanthk/how-web-works) (many things it is from the original article), but it looks like it is often updated and will not make the learner stop reading it, like the current one

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/intermediate-html-and-css-browser-compatibility

### (Optional) Additional Comments

If you still believe that the current article is up to date, we need to mention that, for example:

Take a look at this comprehensive primer on browsers and rendering engines article. Even though it was published in 2011 most of this information is relevant and worth reading. 

As always, thank you for the great work you are doing with maintaining such a great platform like TOP

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.

**Comment by MaoShizhong** [comment]
A fair update @PivtoranisV - assigning this to you.

@Musaveershaik apologies but the issue author has already requested assignment first so priority goes to them.
