### ISSUE TITLE
Data Types and Conditionals: like what

### ISSUE THREAD

**Issue by ValenL1** [TheOdinProject/curriculum#29024]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Yeah very nice course, but what is the point of setting a workspace with Linux and vscode if we are using this retit site or whatever that you only have 3 tries and have ton of unnecessary tools that at novice level that i think only  distracts you

and hey dont look at me with that face, im could be wrong bout this but its my impression as a noob in this, okay take care xoxo

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals

### (Optional) Additional Comments

yeah we love open source

                         xoxo

**Comment by TitanTankNate** [comment]
I fail to see where the productive issue is here.
