### ISSUE TITLE
Factory Functions and the Module Pattern: Typo

### ISSUE THREAD

**Issue by daliduraku** [TheOdinProject/curriculum#29020]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I found a question that is slightly misphrased, and just wanted to point it out.
[10:17 PM]
What common issues can you can face when working with constructors?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#assignment

### (Optional) Discord Name

zojzi

**Comment by MaoShizhong** [comment]
Assigning you to fix the typo. For typos, you can PR directly without having to wait for assignment through opening an issue *only if there isn't already an open issue or PR addressing the problem of course*.
