### ISSUE TITLE
React Router: Links missing in code

### ISSUE THREAD

**Issue by mhamza-khalid** [TheOdinProject/curriculum#29031]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The links to the children routes in the 4th code snippet under the (https://www.theodinproject.com/lessons/node-path-react-new-react-router#nested-routes-outlets-and-dynamic-segments) header are missing:

Currently:

```
import { Outlet } from "react-router-dom";

const Profile = () => {
  return (
    <div>
      <h1>Hello from profile page!</h1>
      <p>So, how are you?</p>
      <hr />
      <h2>The profile visited is here:</h2>
      <Outlet />
    </div>
  );
};

export default Profile;
```
It should have been:

```
import { Link, Outlet } from "react-router-dom";

const Profile = () => {
  return (
    <div>
      <h1>Hello from profile page!</h1>
      <p>So, how are you?</p>
      <hr />
      <h2>The profile visited is here:</h2>

      {/* Links to child routes */}
      <nav>
        <ul>
          <li>
            <Link to="spinach">Go to Spinach</Link>
          </li>
          <li>
            <Link to="popeye">Go to Popeye</Link>
          </li>
        </ul>
      </nav>

      <Outlet />
    </div>
  );
};

export default Profile;
```
Also the same problem is present in the 8th code snippet under (https://www.theodinproject.com/lessons/node-path-react-new-react-router#nested-routes-outlets-and-dynamic-segments). It should have been:

```
import { useParams, Link } from "react-router-dom";
import DefaultProfile from "./DefaultProfile";
import Spinach from "./Spinach";
import Popeye from "./Popeye";

const Profile = () => {
  const { name } = useParams(); // Retrieve the `name` parameter

  return (
    <div>
      <h1>Hello from the profile page!</h1>
      <p>So, how are you?</p>
      <hr />
      <h2>The profile visited is here:</h2>

      {/* Conditionally render based on `name` */}
      {name === "popeye" ? (
        <Popeye />
      ) : name === "spinach" ? (
        <Spinach />
      ) : (
        <DefaultProfile />
      )}

      {/* Links to navigate between dynamic routes */}
      <nav>
        <h3>Visit Other Profiles:</h3>
        <ul>
          <li>
            <Link to="/profile/popeye">Go to Popeye's Profile</Link>
          </li>
          <li>
            <Link to="/profile/spinach">Go to Spinach's Profile</Link>
          </li>
          <li>
            <Link to="/profile/unknown">Go to Default Profile</Link>
          </li>
        </ul>
      </nav>
    </div>
  );
};

export default Profile;

```
Instead of

```
import { useParams } from "react-router-dom";
import DefaultProfile from "./DefaultProfile";
import Spinach from "./Spinach";
import Popeye from "./Popeye";

const Profile = () => {
  const { name } = useParams();

  return (
    <div>
      <h1>Hello from profile page!</h1>
      <p>So, how are you?</p>
      <hr />
      <h2>The profile visited is here:</h2>
      {name === "popeye" ? (
        <Popeye />
      ) : name === "spinach" ? (
        <Spinach />
      ) : (
        <DefaultProfile />
      )}
    </div>
  );
};

export default Profile;

```
### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-react-router

**Comment by CouchofTomato** [comment]
@TheOdinProject/react Can someone review this please.

**Comment by MaoShizhong** [comment]
I agree with the above that it wouldn't make sense to have some navbar with links to individual profiles. The intent is to manually enter the URL into the address bar to access the appropriate page via client-side rendering. I think the lesson wording can be clearer on that being the intent, so would be happy for someone to make that instruction a little clearer if that's something you'd like to do @mhamza-khalid ? The code examples will not need amending.

**Comment by mhamza-khalid** [comment]
@wrspada02 @MaoShizhong Ah ok, so we are required to enter the route paths manually into the URL. Yes I agree that the intent could be included into the lesson wording because I couldn't catch that intent and thought the Links to update the URL were missing.

**Comment by MaoShizhong** [comment]
I'll assign this to you so you can PR an improvement to the wording to be clearer about the instruction.
