### ISSUE TITLE
Git Basics: <Short description of your suggestion>

### ISSUE THREAD

**Issue by kenbaker-gif** [TheOdinProject/curriculum#29044]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

_Well as I was pushing my code to the repository I encountered an error saying email is private thus it required me to put a no reply email I hope this error if encountered by other scholars I would recommend to address it in the upcoming curriculum updates please_

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics

### (Optional) Discord Name

kenbaker-gif

### (Optional) Additional Comments

The instructions are precise am pleased ✌️

**Comment by devnchill** [comment]
*Setting up git* lesson already mentions about private email .

**Comment by CouchofTomato** [comment]
Closing as it seems an answer has been provided
