### ISSUE TITLE
Introduction to Web Development: <Assignment #1 dead link>

### ISSUE THREAD

**Issue by wkosmos** [TheOdinProject/curriculum#29072]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Assignment task 1 in https://www.theodinproject.com/lessons/foundations-introduction-to-web-development links to https://web.archive.org/web/20230630111131/https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/, which no longer exists

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### (Optional) Discord Name

crionretro

**Comment by wkosmos** [comment]
https://medium.com/@andrewlatta/why-learning-to-code-is-so-damn-hard-303eae632820 is the article in question, but Medium requires a subscription

**Comment by rlmoser99** [comment]
@wkosmos Thank you for taking the time to make an issue, but this link opens fine for me. I wonder if there are other issues that prevent you from opening the link.

We want to avoid using a link from Medium, since requires a subscription. So I am going to close this issue for the time being.
