### ISSUE TITLE
Intermediate HTML and CSS: Remove mentioning browser compatibility with Internet Explorer

### ISSUE THREAD

**Issue by relativeSkeptic** [TheOdinProject/curriculum#29076]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The the Browser Compatibility section of the Intermediate HTML and CSS course remove mentioning the need to design website with Internet Explorer in mind. 

I am recommending the following section be removed from the Browser Compatibility section, " (like Internet Explorer) ". 

Internet Explorer is a deprecated browser and isn't even available to download [anymore](https://support.microsoft.com/en-us/windows/internet-explorer-downloads-d49e1f0d-571c-9a7b-d97e-be248806ca70) on Windows 10 or 11. While I understand that some enterprise applications and large companies likely still utilize internet explorer for one reason or another. I do not think this is something a new developer should keep in mind as they move forward. If they find themselves needing to design their web applications with Internet Explorer in mind I believe something has likely gone severely wrong in the development process. Most major websites have dropped support for Internet Explorer all together. 

For these reasons I would recommend not having new developers design their websites with Internet Explorer in mind, and remove this section from the course. 

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-browser-compatibility

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @relativeSkeptic, it sounds like a good idea to me!

**Comment by jayshah2005** [comment]
Hi, can I solve this issue?

**Comment by KevinMulhern** [comment]
I've assigned it to you, thanks @jayshah2005!
