### ISSUE TITLE
JavaScript Course: Expanding Additional Resources in JS Quick Review to Add jQuery Context 

### ISSUE THREAD

**Issue by RonnocNiksab** [TheOdinProject/curriculum#29098]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The additional resource section calls out the following, "It looks like this lesson doesn’t have any additional resources yet. Help us expand this section by contributing to our curriculum." It also notes, "A quick web-search on the topic will be more useful than any explanations here..."

I'd like to expand this section by adding high quality resources to help students understand the history of jQuery and possibly to get started with jQuery itself. Understanding how things were done (like DOM manipulation) can help one better understand why things are done how they are today.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-a-quick-review

### (Optional) Additional Comments

This is my first issue ever and I was inspired by The Odin Project to open it. I just wanted to say thanks upfront.

**Comment by RonnocNiksab** [comment]
Hi there @JoshDevHub 

I had a quick set of questions while we wait to hear back from the JavaScript team. 

1. Do you mind if I open up a tentative PR for the case where we choose to remove the jQuery content?
2. Are you able to assign me to work on this issue? (https://github.com/TheOdinProject/curriculum/issues/29124). I feel like I could wrap that one up pretty quickly.

I want to be especially mindful, hence the added questions. 😊

**Comment by fortypercenttitanium** [comment]
Hi all. I personally feel like the capacity to which we cover jQuery is ideal. I don't believe we're at a point where removing it entirely is beneficial, as I still do often run into it pretty often in the wild. However, I also feel like expanding on it is not in our best interest either. Let's leave this the way it is.

Thanks for the conversation surrounding this, and thank you @RonnocNiksab for seeking out ways to contribute. These are always conversations that are worth having, even if they don't conclude with any changes being made.
