### ISSUE TITLE
A Deeper Look at Git: <Change Knowledge check Q1 to a question and update links to material covered in lesson>

### ISSUE THREAD

**Issue by Meltasy** [TheOdinProject/curriculum#29108]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Knowledge check section Q1 should be a question, e.g. What does it mean for branches to be pointers? Also, the links take us to pages on git-scm that aren't covered in the lesson, so I'd suggest changing them to links on the same page, e.g Q1:  para headed 'Branches are pointers'; Q2: para headed 'Changing the last commit'; and Q3: para headed Changing multiple commits. Finally, it would make more sense to move Q1 to the bottom of the list of questions as it's covered at the end of the lesson.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

### (Optional) Discord Name

Meltasy

**Comment by JoshDevHub** [comment]
Hello @Meltasy and thank you for raising this issue.

Every point you've brought up makes perfect sense to me. I'll assign you to work on the PR :rocket:

**Comment by Meltasy** [comment]
Thanks, I've made the changes. Please note that I also removed the extra space in the Assignment list - Mao had told me to do this previously as it's TOP style. Please let me know if that's OK. Have a lovely day :-)
