### ISSUE TITLE
APIs and Building Your Own: Dead link in Additional Resources

### ISSUE THREAD

**Issue by dwlknsn** [TheOdinProject/curriculum#29105]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The **_Additional resources_** section includes an external link to a blog that appears to be dead. I get a 404 when I visit that page. I searched the author's list of articles to see if it's name had just changed, but I cannot find anything there.

- [Building a public-facing API using view templates instead of `#to_json`](http://blog.codepath.com/2011/05/16/if-youre-using-to_json-youre-doing-it-wrong/)

<img width="400" alt="Screenshot 2024-11-21 at 11 41 33" src="https://github.com/user-attachments/assets/d10ae649-b86c-4f7d-af7f-281bbcdb22ba">

Shall we remove the link, or replace it?

I'm not exactly sure what the original blog post discussed (probably jbuilder, but I can't be certain), so I can't suggest an alternative.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-apis-and-building-your-own

### (Optional) Discord Name

dwlknsn

**Comment by JoshDevHub** [comment]
@dwlknsn Thank you for making this issue.

Since it's an additional resource, I think it's absolutely fine to just remove it altogether. I'll assign this to you.

**Comment by dwlknsn** [comment]
@JoshDevHub opened PR #29110
