### ISSUE TITLE
Introduction to Grid (intermediate HTML and CSS): Improperly referenced png 

### ISSUE THREAD

**Issue by Hossam-Allam** [TheOdinProject/curriculum#29102]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The 'flex-exercise-desired-outcome.png' isn't linked properly

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/intermediate-html-and-css-introduction-to-grid

**Comment by MaoShizhong** [comment]
Ah yes, when the CSS exercises repo go structured, the paths all changed. The image href is still correct but the link href (the one that points to the exercise in the CSS exercises repo) needs to be changed to https://github.com/TheOdinProject/css-exercises/tree/main/foundations/flex/07-flex-layout-2

**Comment by Hossam-Allam** [comment]
:)

**Comment by MaoShizhong** [comment]
This issue doesn't need to be closed - it needs to be addressed. I'm just providing context for why it's an issue and what the fix would be. Anyone can request to be assigned to work on it and a team member can assign someone if so.

**Comment by Hossam-Allam** [comment]
I was going to fix it, but then I checked the live site and it appeared to be fixed so I closed the issue.

**Comment by MaoShizhong** [comment]
The image shows fine but the image is also a clickable link that takes you to the exercise itself, and the exercise link still needs fixing (clicking the image takes you to a 404 because the repo was recently restructured).

**Comment by Hossam-Allam** [comment]
Oh, I'll fix it then mb!

**Comment by MaoShizhong** [comment]
Heads up that you ought to wait for a maintainer to assign you to work on an issue before you open a PR. I'm not a maintainer so I can't assign you to it
