### ISSUE TITLE
Rails - JS Bundling: Rephraseing a sentence for more clarity

### ISSUE THREAD

**Issue by bellitabellota** [TheOdinProject/curriculum#29118]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The wording of the following sentence left me very confused about what was described in the previous section.

„Now that we have walked through how to install a Rails app with import maps let’s make our life a little bit easier and set it up with jsbundling-rails!“

It evokes the impression that the previous section was about the installation of a Rails app with importmaps. However, as it is actually about the installation of the „jsbundling-rails“ gem, it would be good if this could be expressed more clearly.

My suggestion is to modify this sentence a s follows:

„Now that we have walked through how to install the jsbundling-rails gem in a Rails app that was created with import maps let’s make our life a little bit easier and set it up right from the beginning!“

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-js-bundling

### (Optional) Discord Name

Bella--1

**Comment by JoshDevHub** [comment]
Hello @bellitabellota thank you for making this issue. I agree that the wording could be more clear, and I like your example wording.

Since you indicated you'd like to work on this, I'll assign you.

**Comment by bellitabellota** [comment]
Hi @JoshDevHub,
thank you for reviewing the issue I opened and assigning it to me.

Then I will get started with my first contribution :D
