### ISSUE TITLE
Controllers: Rails 8 docs conflicts with the current lesson (based on Rails 7)

### ISSUE THREAD

**Issue by Monatric** [TheOdinProject/curriculum#29121]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

My concerns are:
1. To explicitly allow parameters, the lesson suggests to use `require` with `permit`. However, I'm following the version 8 docs, but it strongly recommends to use `expect`, which "requires" and "permits" parameters all at once. The logic and syntax is understandable, but it kinda confused me which one should I use as I move forward in the curriculum, and even considered to downgrade the Rails version.
2. While this one is not originally an issue for me, I think it's also worth mentioning that the TOP lesson and docs exposes us about flash messages. The generated models and controllers in the project use a different syntax for the flash like so:
`format.html { redirect_to @car, notice: "Car was successfully updated." }`, unlike the lesson's introduction to flash messages.

This clearly led to a confusion. I suggest that the lesson must expose us for what's to come when following the Rails 8 docs, as well as what Rails generates in the project (since I also explore the project at the same time). This way, we'll be prepared for content, we'll know which is better/suited for certain cases, and minimise confusion for different Rails versions.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-controllers

### (Optional) Discord Name

Koko#8682

**Comment by JoshDevHub** [comment]
Thank you for making this issue @Monatric
