### ISSUE TITLE
More Text Styles: Change word.

### ISSUE THREAD

**Issue by WhamBamTurkeyAndHam** [TheOdinProject/curriculum#29129]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

A portion of the text under the first image says _'The point of this somewhat ridiculous string of font-families is to try using the default font of the system’s user interface.'_, the word _'using'_ should be **_'use'._**

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles

### (Optional) Discord Name

whambamturkeyandham

**Comment by JoshDevHub** [comment]
Hello @WhamBamTurkeyAndHam thank you for contributing to the curriculum.

I'm unsure what exactly you mean by your suggestion. If you replace "using" with "use" in that sentence, you end up with:
> The point of this somewhat ridiculous string of font-families is to try use the default font of the system’s user interface.

That "to try use" phrase is grammatically incorrect English. Glad to discuss more if you meant something else or there's not something I'm understanding about your suggestion.

**Comment by WhamBamTurkeyAndHam** [comment]
My apologies.

I haven't heard anyone around me use a sentence in this way and I have never used the sentence this way myself, so I thought the 'ing' was just accidentally added on.

I also just realised my suggestion was meant to say 'to use'.

**Comment by MaoShizhong** [comment]
Both "using" and "to use" are grammatically correct and would mean the same thing here.
