### ISSUE TITLE
Intermediate HTML and CSS: Fix emoji in advanced selectors lesson

### ISSUE THREAD

**Issue by TheSeagullDev** [TheOdinProject/curriculum#29143]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the section on the pseudo-elements ::before and ::after, one of the emojis used doesn't render for me (Using windows 10 with google chrome). Maybe change it to a more common emoji? 
![image](https://github.com/user-attachments/assets/658eaad1-f7fb-456a-9c16-1148aea08dbd)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors

### (Optional) Discord Name

theseagulldev

**Comment by wise-king-sullyman** [comment]
I don't think there's any downside to changing the emoji if it isn't rendering for some users. Thanks for making this issue!
