### ISSUE TITLE
Nodejs: OWASP Top Ten

### ISSUE THREAD

**Issue by Jtech3029** [TheOdinProject/curriculum#29159]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Looking through the curriculum, I noticed that there wasn't too much on website security. Although the odin project doesn't aim to teach cybersecurity, I still think it is vastly useful for people to still know vulnerabilities such as the OWASP Top Ten. My suggestion is to have a lesson that looks over the OWASP Top Ten and the fundamental ideas behind the flaws and have an assignment where you look over faulty code and try and identify any vulnerabilities the code may have.

### Path

Other / NA

### Lesson Url

Backend sections of the ruby and javascript paths since this issue is especially important for backend.

**Comment by wise-king-sullyman** [comment]
Thank you for making this issue!

Tagging @kashura (along with any other @TheOdinProject/maintainers who'd like to participate of course) for thoughts on this. 

It seems like an interesting idea to me, though I wonder if it would be too far out of the focus of our curriculum 🤔I'm also not personally familiar with the proposed resource here, so I can't really speak to that.

**Comment by rlmoser99** [comment]
I feel like this is out of the focus of our curriculum, though I am familiar with OWASP Top Ten because at work this is part of my required training every year. However, I think this would be great information to cover if we begin to create resources that are helpful to learn after completing TOP.

**Comment by kashura** [comment]
I concur with @rlmoser99 and @wise-king-sullyman . As important as secure practices should be, this is an odd fit into the curriculum at this time. To make this really valuable we would have to add a significant amount of content, and I am concerned with the pace we would be able to maintain the accuracy of it considering this is not our focus. 

Thank you for the suggestion and please do not hesitate to raise more!
