### ISSUE TITLE
Curriculum: Guidance on how to start contributing to the project

### ISSUE THREAD

**Issue by JulianColoma** [TheOdinProject/curriculum#29168]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I wanted to collaborate on the Curriculum project, so I created this PR https://github.com/TheOdinProject/curriculum/pull/29122 but I would like to know if this is the correct way to do it, or should I start looking at another repository or part of the code to contribute?

With this I'm only looking for guidance on how to start contributing to the project. Thanks in advance for your time.

### Path

Other / NA

### Lesson Url

https://github.com/TheOdinProject/curriculum/blob/main/git/foundations_git/git_basics.md

**Comment by wise-king-sullyman** [comment]
Hello, regarding your PR I'll be reviewing it as soon as I have the time 🙂 

Regarding this issue I'm not sure I understand. Are you just looking for additional feedback on your PR (which would really be better suited in the PR itself) or are you suggesting we improve our guidance on contributing generally?

**Comment by JulianColoma** [comment]
Thank you for your time! Yes, I would appreciate additional feedback on the PR. I thought this topic might need more context or discussion, but I can move it to the PR itself if that's more convenient.
