### ISSUE TITLE
Calculator: Add a new bug to watch for under the "Gotcha's" section

### ISSUE THREAD

**Issue by KHenkel95** [TheOdinProject/curriculum#29174]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I noticed that my project, along with a good number of the submitted calculators, have a bug where if the user enter's a single number and an operator and then persists in pressing operators the operations continuously run without ever entering a second number. (For example, pressing '2' then '+', followed up by continued '+'s results in the display showing 4, 6, 8, 10, 12, etc.) This also occurs in the middle of longer operations and while operating on results if multiple operators are selected in a row. I think this would be a good unintended behavior to list under the "Gotcha's" (assignment direction 7).

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-calculator

**Comment by wise-king-sullyman** [comment]
Seems like a good idea to me, thanks!

**Comment by KHenkel95** [comment]
Thank your for reviewing my issue and assigning it to me! I've submitted my change for review.
