### ISSUE TITLE
Installing Node.js: Node & NPM doesn't activate upon Terminal restart

### ISSUE THREAD

**Issue by GraysonSwaim** [TheOdinProject/curriculum#29187]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

On MacOS, node & rpm wouldn't work on terminal after restarting the session. It was forcing me to reinstall each time. I think this page needs to be clarified about proper installation.

**My Resolution:**
I added the following to my ~/.zhsrc file:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installing-node-js

### (Optional) Discord Name

bionic assassin

### (Optional) Additional Comments

You could talk about homebrew as an alternative.

**Comment by xandora** [comment]
Those lines are automatically added to the profile file during installation. If that didn't happen, then there was probably an error message presented during the process.

I don't believe the instructions in the lesson require any more clarification.
