### ISSUE TITLE
Introduction to HTML and CSS: <broken assignment link>

### ISSUE THREAD

**Issue by austinchong01** [TheOdinProject/curriculum#29182]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The link to the article for this lesson is not working.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

### (Optional) Discord Name

awetson #1210

**Comment by cLHanna** [comment]
I came here to raise the same issue. "Safari cannot establish a secure connection to the server".

**Comment by TheSeagullDev** [comment]
Getting the same issue with Chrome - the article also seems to be pretty unstable on the wayback machine so we might need to find an alternate article

**Comment by sajwan05** [comment]
Yes i was working through the first lesson of HTML and CSS and I found that link was not working due to browser and host different SSL protocol . I checked on Chrome and then on Firefox issue persisted. So I had to use waybackmachine to go through the article.

**Comment by space-adv** [comment]
same issue here!

**Comment by levthecoder** [comment]
link seems to be working for me with no issues
