### ISSUE TITLE
Investigation of need and feasibility of installation directions and bring up guide for affordable 64 Bit Single Board Computers (SBCs) 

### ISSUE THREAD

**Issue by hamzah-mujawar** [TheOdinProject/curriculum#29204]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Hi, 

There is a similar issue that was closed (see #16030).

I have recently opened a discussion, but I'm not sure if that is the right place to ask so I will link that discussion here #29203.

Happy to hear any feedback based on the discussion #29203.

Kind Regards,
Hamzah Mujawar

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installations

### (Optional) Discord Name

madgerbadger

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @hamzah-mujawar. But the discussion should be the central place for this, this issue isn't needed.
