### ISSUE TITLE
Middleman and Rack

### ISSUE THREAD

**Issue by sahal2080** [TheOdinProject/curriculum#2920]
Firstly thanks for a great project. I refer lots of people to it and the feedback is almost always good.

I looked at the curriculum recently and it reminded me of an article long time ago that helped A LOT when I was learning:
http://techiferous.com/2010/07/roadmap-for-learning-rails/

Surprisingly it's mostly the same but Odin is still missing nanoc and Rack. Though an argument can be made that they're not essential, I believe small bits of information can go a long way in connecting the dots for learners between Ruby and the web. 

I recommend Middleman over nanoc as it follows similar conventions to Rails so no time is lost. There are many good tutorials for it:
https://github.com/sbellware/middleman-lesson/blob/master/middleman.md
http://12devs.co.uk/articles/204/
http://willschenk.com/building-sites-with-middleman/

For Rack:
http://code.tutsplus.com/tutorials/exploring-rack--net-32976
https://gist.github.com/robbinhan/4247728
http://codenoble.com/blog/understanding-rack-middleware/

Hope this helps.

**Comment by KevinMulhern** [comment]
Hey @sahal2080, thanks for the links. Why don't you draft up section and project for rack and middleware to be included into the curriculum. This would be a great addition.

**Comment by KevinMulhern** [comment]
I am closing this issue, because while it's a nice to have feature and it's not a a actual issue.
