### ISSUE TITLE
Basic Associations: Slight Edit of Assignment

### ISSUE THREAD

**Issue by SeanMero** [TheOdinProject/curriculum#29216]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The assignment for this section is "Read the beginning of the [Rails Guides Associations Chapter](http://guides.rubyonrails.org/association_basics.html), just up until section 2.7", but that chapter does not have a section 2.7! I suppose it meant that we should read through Section 2.6.1.5? 

I am willing to do the edit myself (it would be my first contribution!) but I want to confirm the correct section number first.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-basic-associations

### (Optional) Discord Name

merofromvero

**Comment by CouchofTomato** [comment]
It's because they keep updating the guides which changes the ordering. Please feel free to submit a fix :)

**Comment by SeanMero** [comment]
Ok, I've submitted a fix ^_^

**Comment by SeanMero** [comment]
I have just realized that I did not create a pull request for my change. _Now_ I've submitted a fix.
