### ISSUE TITLE
Recursive Methods: Code Quiz link 404's

### ISSUE THREAD

**Issue by henrylin03** [TheOdinProject/curriculum#29223]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

the "Code Quiz" link in the "Test Yourself" section of the page (see screenshot below)

![image](https://github.com/user-attachments/assets/88f8d2e3-838c-465e-812e-ca98109fbfc0)

... leads to this link: https://www.codingame.com/playgrounds/5422/js-interview-prep-recursion

however, this page has a 404 error:
![image](https://github.com/user-attachments/assets/45aefb75-0d7e-402f-9fb7-0f7822680cc7)

suggest replacing games with alternative link (happy to discuss)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods

**Comment by CouchofTomato** [comment]
The link works for me. Are you still having an issue accessing it?

**Comment by henrylin03** [comment]
I've just tested on mobile now (404 is on computer) and it's working so I'll close this issue as it's probably something to do with my machine.

Thanks all and merry Xmas 🎄🙏
