### ISSUE TITLE
Setting up Git: Update Callout/Warning in Step 2.5 (Testing)

### ISSUE THREAD

**Issue by Selethenn** [TheOdinProject/curriculum#29227]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Under **Step 2.5 Testing your Key** the language "**(Don’t forget to omit the $ when you copy and paste the code!).**" is no longer applicable as github has updated the directions to remove the $ from their directions. 

It now reads as below:

```
ssh -T git@github.com
# Attempts to ssh to GitHub
```

I would suggest removing the language "**(Don’t forget to omit the $ when you copy and paste the code!).**" as it may cause confusion as the user will only have their $ in bash.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### (Optional) Discord Name

Daegs

**Comment by CouchofTomato** [comment]
All yours
