### ISSUE TITLE
Recursive Methods: <Test yourself  leads to a 404>

### ISSUE THREAD

**Issue by EndriGoxhaj** [TheOdinProject/curriculum#29246]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The test yourself segment, leads to a broken link

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursive-methods

**Comment by rlmoser99** [comment]
Thank you for taking the time to make this issue. However, both of the links in the Test yourself section work for me, so I am going to close this issue.
