### ISSUE TITLE
Introduction to HTML and CSS: <Assignment link not working>

### ISSUE THREAD

**Issue by GuiHoffT** [TheOdinProject/curriculum#29252]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

When I click on the assignment link it displays the message "500: Internal Server Error"

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

**Comment by rlmoser99** [comment]
Closing this issue, because there is discussion happening on an open PR.

https://github.com/TheOdinProject/curriculum/pull/29248
