### ISSUE TITLE
Rails: Hartl switched from RSpec to MiniTest but TOP lessons don't reflect this

### ISSUE THREAD

**Issue by cdouglass** [TheOdinProject/curriculum#3214]
The [Let's Get Building](http://www.theodinproject.com/ruby-on-rails/let-s-get-building) lesson goes into detail discussing TDD using examples from the Hartl tutorial, but these examples are all from an older version of Hartl using RSpec. The lesson would be more helpful if it used examples from the version of the tutorial that students are using.

**Comment by KevinMulhern** [comment]
Good point @cdouglass, We will add a ticket to get this fixed.

**Comment by KevinMulhern** [comment]
I got changed the example :smile:
