### ISSUE TITLE
Option to change default homepage when visiting main website

### ISSUE THREAD

**Issue by akshaybharwani** [TheOdinProject/curriculum#3314]
Whenever someone signs into TOP, they are redirected to the 'Courses' page. And when someone who is already signed in, visits www.theodinproject.com, they are on the same homepage as seen by the new users. For a person who has already seen all the steps and has been using the site for some time, it doesn't make sense.  When visiting FreeCodeCamp, the user is redirected to the last challenge you were on. We can do something similar here. Or maybe an option for the users, either the default homepage or a particular course or the last challenge you were on.

**Comment by KevinMulhern** [comment]
Hey @akshaybharwani, Nice suggestion. We have a bit of an idea for creating a dashboard that the user will be directed to if they are signed in. It will include stats about their progress and a link to the last lesson they were on.

**Comment by akshaybharwani** [comment]
That would be really awesome @KevinMulhern! Looking forward to that.

**Comment by KevinMulhern** [comment]
Hey @akshaybharwani, I am going to close this because its on our road map :smile:

**Comment by akshaybharwani** [comment]
No problem! :)
