### ISSUE TITLE
Two broken links in HTML & CSS basics

### ISSUE THREAD

**Issue by irishmac473** [TheOdinProject/curriculum#3318]
In Web Development 101/ The Front End/ HTML & CSS basics the links for OverAPI's HTML Cheat Sheet & OverAPI's CSS Cheat Sheet are broken. They take you to overapi.com/css/ and overapi.com/html/. If you remove the final back slash from each link they work.

**Comment by KevinMulhern** [comment]
Thanks @irishmac473, I just fixed it :smile:
