### ISSUE TITLE
Use of "swathe"

### ISSUE THREAD

**Issue by benjamincarlton** [TheOdinProject/curriculum#3449]
[Swathe](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=swathe) is defined as something used to wrap something else.

In context of the sentence, "[swath](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=swath)" (a broad area of something) should be used.

Or you could rewrite the sentence for even more clarity by removing the uncommon "swath(e)" altogether, e.g. We will cover a very broad area of knowledge here, and that's intentional. It's silly to dive straight into server-side programming... etc.

**Comment by KevinMulhern** [comment]
what page is this on @benjamincarlton?

**Comment by benjamincarlton** [comment]
http://www.theodinproject.com/web-development-101/how-this-course-will-work

I created a pull request after re-watching the video that isolates the specific changes and information to the page and line number.

Sorry for creating this issue. I should have done the pull request from the start, but this is my first contribution to open source material ever.
