### ISSUE TITLE
The Odin Project Blog Page

### ISSUE THREAD

**Issue by pawan92** [TheOdinProject/curriculum#3560]
Hey guys I realize you currently host a blog on tumblr, but I'd like to propose that we build a page on the site itself for our blog posts. This link to the page could potentially be on the top navigation bar. I think the positive to this are more people will be checking this out. Personally I was not even aware you guys had a blog until i talked to Kevin. We can also easily control the layout of the blog and empahsize the viking theme. currently it looks pretty bland and un-inviting. 
The blog content looks great but I would also recommend adding some other things and publishing a blog post weekly.
somethings I'd like to see added to the blog content:
-weekly status: what was accomplished and what will be accomplished
1. perform interviews of core team members (we would love to know how you got to where you are today and what you guys do for fun)-newbies can help out! This doesn't have to be weekly just interview everyone.
2. look for 2-3 software related news and provide the links to those articles for further reading (I'd like to keep up with technology and web dev and this is a great way)
3.List some open source resources/projects that we could jump into and start contributing. If Odin has any easy/starter issues list them here and invite newbies to give it a shot
4. A couple of miscellaneous memes/articles/jokes from the week that you found funny. doesnt have to be coding related but it could be
5. provide figures and people to follow on twitter/github/facebook that you see are influential and we could learn from. (examples: codenewbies on twitter, newbiecoderwarehouse on facebook, etc.) 
We could have a certain bunch of people dedicated to doing this every week.

**Comment by KevinMulhern** [comment]
Very well laid out pitch @pawan92, A blog that was visible on the site would indeed be awesome and great for spreading the word of what we are doing. 

The main issue I foresee with it is someone taking ownership, a weekly blog post might be too much of a commitment at the moment for the current mod's as we all have quite a bit on our plate. A monthly blog post on the other hand would be very achievable with the current man power. When we can grow the mod team we can then try and put out more frequent posts. It would also be awesome to get more students involved especially students who have got hired.

**Comment by eriktrautman** [comment]
Absolutely agree with the value of a blog as well as @KevinMulhern 's point about scoping and ownership.  I like sourcing posts from the community but someone will need to own the process of doing so.  Building the blog itself isn't trivial, though not overwhelming by any means.  Basically, if it can be narrowly scoped and owned by a single person, I'm open to it.  Else, it isn't something we have extra resources to take on.

**Comment by KevinMulhern** [comment]
Another option would be to use Medium and link it on Odin, a lot of sites seem to outsource their blog to Medium now. The advantage of doing this would be not having to worry about building out the blog infrastructure and maintaining it.

**Comment by KevinMulhern** [comment]
**A few more ideas**
If we decide to go with our own blog instead of Medium or something similar. I think we should structure it so new posts are uploaded via mark down files through github. Something similar to Jekyll. I don't believe that creating our own cms for it would be worth the time cost.

**Comment by pawan92** [comment]
@KevinMulhern i have heard about jekyll and agree with using markdown files. this gives a great opportunity for new users to try out pull requests like you said and help out!

**Comment by KevinMulhern** [comment]
Ok a couple of things we can make a decisions on:
Medium or Our own blog?
Who's going to own the development of this project?

My vote goes with our own blog, I can contribute a monthly 'state of odin post' and help out with development. You mentioned in slack that you would like to own this project @pawan92. That means spearheading development as well as maintaining it in the longer term 😄 is that something you would be up for?

**Comment by pawan92** [comment]
i agree with our own blog as well. later on we can always start a medium blog too. this will be more of a weekly newsletter kinda thing. yes i can own this and make sure we get something out every week and help with dev and maintain it. do we have a twitter handle? that would also be a good way to get things out too. if not im sure i can find someone interested in setting up one and coordinating it with them. i can start a blog channel on slack and go from there.

**Comment by KevinMulhern** [comment]
Okay thats settled, we will develop our own. Yeah we have a twitter handle @eriktrautman is the guy to talk to about that. Lets discuss how we will go about developing this over in the contributing channel on slack 😄

**Comment by eriktrautman** [comment]
I'd recommend considering what Free Code Camp has done as well, they have a solid system for crowdsourcing content on their blog on Medium: https://medium.freecodecamp.com/

**Comment by pawan92** [comment]
@eriktrautman i follow them on medium. quincy and the gang post some awesome helpful stuff 👍
