### ISSUE TITLE
Add Gearing up for success lesson to the start of Web Development 101

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#3752]
It will be about things the student can do for the greatest chance of success when learning programming, eg mindset for learning, tips to avoid procrastination etc.

Draft can be found here: https://github.com/TheOdinProject/curriculum/pull/4003

**Comment by KevinMulhern** [comment]
I have a unfinished draft wrote up for this, it will be my focus for the next few weeks to get this done.

**Comment by BrandanClothier** [comment]
The "Your Motivation For Learning Programming" and "the best ways to learn" sections are pretty messy and unconstructed in this 8 day old draft. If you've got a later version of this, I'd like to have a look and contribute a couple edits.

**Comment by KevinMulhern** [comment]
Hey @BrandanClothier yeah it's really messy right now, I just put all the ideas I could think of down. but I will clean it up this weekend 😄

**Comment by KevinMulhern** [comment]
First Draft finished https://github.com/TheOdinProject/curriculum/pull/4003
