### ISSUE TITLE
Adding DNS explanation

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/curriculum#4073]
From feedback form:
*****
In "How does the web work" section, there is not a tutorial explaning DNS. I have used http://www.howtogeek.com/122845/htg-explains-what-is-dns/ this article to understand what a DNS is. Maybe there are better tutorials, or maybe this is good but there should be something about DNS in there. 
*****

**Comment by KevinMulhern** [comment]
New DNS resources have been added https://github.com/TheOdinProject/curriculum/pull/4481
