### ISSUE TITLE
Edit Git basics and Move it into a new section on web dev 101

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#4148]
Because Git is used rather early on to upload the html and css project as well as the other projects in web dev 101 it would be beneficial to move this lesson to a new section that comes earlier in the course.

A part of this will be editing the lesson, it's focus should be on giving the student a high level overview of GIT and the basic workflow of committing and pushing changes.

http://www.theodinproject.com/web-development-101/git-basics

[*Lesson in progress*](https://github.com/TheOdinProject/curriculum/blob/master/extra_stuff/lessons_in_progress/git_basics.md)

**Comment by csrail** [comment]
Yay this is finished! :tada: 

These lessons should really help beginners understand how to use git!
The lessons are located in [Web Development 101](http://www.theodinproject.com/web-development-101#section-git-basics):
* [Git 101](http://www.theodinproject.com/web-development-101/introduction-git)
* [Git basics](http://www.theodinproject.com/web-development-101/git-basics)
* [Project Git basics](http://www.theodinproject.com/web-development-101/practicing-git-basics)

A huge thanks to @KevinMulhern for taking on this monster of a project! :sunglasses: 

The pull request from the main site repo: https://github.com/TheOdinProject/theodinproject/pull/206
