### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by m-chrzan** [TheOdinProject/curriculum#4346]
It appears that rubymonk.com is [down](http://downforeveryoneorjustme.com/rubymonk.com). This affects the [Files and Serialization](http://www.theodinproject.com/ruby-programming/files-and-serialization) assignment and the Additional Resources section of [Ruby Building Blocks](http://www.theodinproject.com/ruby-programming/ruby-building-blocks).

**Comment by KevinMulhern** [comment]
Hey @m-chrzan, thanks for raising this, I'm not sure if rubymonk is being maintained anymore. But lets wait a few days to see if it comes back online.

**Comment by tutordelphia** [comment]
Sounds like it will be back up soon:

@ponnappa Hi there, 
the website https://rubymonk.com/  has been down for over a week. It is troubling me and I wondered what happened?

Sidu Ponnappa ‏@ponnappa  Aug 1
@Tony_CT_Hsu An issue with our hosting company payments, we're getting it resolved by the end of this week. Apologies for the downtime.

**Comment by KevinMulhern** [comment]
Thanks for looking into this @tutordelphia, it's good to know they aren't down for good.

**Comment by tutordelphia** [comment]
Still down so far. 

Are there any tools that The Odin Project can use to monitor broken links and spelling mistakes? I've been fixing them as I come across them but for my own site I use CheckDog.com and a WordPress Plugin to do spelling and link checking. Are there any open source projects that provide the same functionality?

**Comment by KevinMulhern** [comment]
Good question, I don't know of any but that's something we should definitely look into.
We could build a rake task that checks for links in the content that returns 404's. Its been something I've been meaning to do.

**Comment by m-chrzan** [comment]
While we're waiting, I'd suggest adding another resource on serialization to the section - either as a replacement of the Ruby Monk link, or in the Additional Resources section. I found this [blog post](http://www.skorks.com/2010/04/serializing-and-deserializing-objects-with-ruby/) by Alan Skorkin useful and easy to follow, though it is a bit outdated.

**Comment by KevinMulhern** [comment]
That's not a bad idea @m-chrzan I also found this https://www.sitepoint.com/choosing-right-serialization-format/
