### ISSUE TITLE
Check: Are the Code School videos in the Web Developer Tools lesson working?

### ISSUE THREAD

**Issue by csrail** [TheOdinProject/curriculum#4365]
Want to double check with others - do the [videos](http://discover-devtools.codeschool.com/chapters/1/challenges/1?locale=en) for the [Web Developer Tools](http://www.theodinproject.com/web-development-101/developer-tools) lesson at Code School work for you? 

I have tried in both firefox and google chrome and I cannot load a video. If the videos cannot be loaded this would be that students would have to complete exercises without receiving any prior instruction.

**Comment by chrisgchambers** [comment]
Failing to load intermittently for me chrome. Loads video immediately about 20% of the time. Rest of the time spins and spins and spins.

**Comment by KevinMulhern** [comment]
Yeah it's not loading for me neither, I've added a note to that assignment and a reminder for myself to check this out again in a weeks time. I checked the forums on Codeschool and its something they are working on.

**Comment by KevinMulhern** [comment]
@csrail, @chrisgchambers the videos worked for me when I checked this morning. Can you guys please quickly test the videos work for you too incase it was a fluke. 

Thanks 😄

**Comment by chrisgchambers** [comment]
Working ok here.

**Comment by csrail** [comment]
I immediately regret pressing the play button.
Yes it's working at my end too albeit the cheesy music.

**Comment by KevinMulhern** [comment]
Haha thanks guys.
