### ISSUE TITLE
Breadth First / Depth First Video Unavailable on YouTube

### ISSUE THREAD

**Issue by chrisgchambers** [TheOdinProject/curriculum#4407]
ruby/data_structures_algorithms.md

http://www.youtube.com/watch?v=zLZhSSXAwxI is unavailable on YouTube.

It's not clear from context what the content of this video was, but I did find a good explanation of Breadth-First and Depth-First here:

https://www.youtube.com/watch?v=9RHO6jU--GU

Can someone familiar with the old video confirm this video will fill the gap?

**Comment by KevinMulhern** [comment]
Hey @chrisgchambers, thanks for finding another video. I'll leave this open for a couple of days for others to comment. But I'm sure the video you found is a good replacement.

**Comment by chrisgchambers** [comment]
I needed to  watch the next couple in that series to have enough information to do the binary search tree project. It may be worth trying to find something a little more succinct, but the information was indeed excellent.

**Comment by KevinMulhern** [comment]
What about the putting the series of videos in?

**Comment by chrisgchambers** [comment]
Sure. It's a little on the long side but very worthwhile imo.

**Comment by KevinMulhern** [comment]
Do you want to put a pull request together for it @chrisgchambers?
