### ISSUE TITLE
Found a wrong project submitted to student solution

### ISSUE THREAD

**Issue by jerrykuo7727** [TheOdinProject/curriculum#4433]
http://www.theodinproject.com/ruby-on-rails/sinatra-project
At the Student Solutions part of Project1: Ceasar Cipher reloaded,
I found <b>AaronGerry</b> submitted the web guesser instead of the Ceasar cipher. (Line 4)

Is it fine? Or should I pull a request to delete a wrong student solution like this one?

**Comment by KevinMulhern** [comment]
Hey @jerrykuo7727 nice catch, yeah that should be removed.

**Comment by jerrykuo7727** [comment]
Copy that.
