### ISSUE TITLE
An introduction to SQL is missing

### ISSUE THREAD

**Issue by csrail** [TheOdinProject/curriculum#4494]
In the [databases lesson](http://www.theodinproject.com/web-development-101/databases) at web development 101 has an obsolete link under step 1 of Assignment:

"Check out a pretty good plain-english explanation of SQL, written by Zed Shaw, at [Learn SQL The Hard Way](http://sql.learncodethehardway.org/book/introduction.html). Only read the introduction (unless you're feeling ambitious)."

- Zed Shaw has hidden the contents of his SQL book so the introduction is no longer accessible - you are instead redirected to a cover page.
- Need to find a replacement introduction to SQL - it should be basic and teach about the application and utility of SQL but not delve into its details.
- Note that **ANY OTHER** lessons linking to Zed Shaw's *"Learn ___ The Hard Way"* series may be broken.

As notified by @Liam-Hinzman.

**Comment by m-chrzan** [comment]
Zed's Command Line Crash Course link is also broken (points to Learn Unix the Hard Way cover page). Fortunately it's just an Additional Resources link (Web Development 101 > Command Line Basics), so removing it won't affect the curriculum.

[Learn Ruby the Hard Way](https://learnrubythehardway.org/book/) appears to still be free and available, so no issues there.

**Comment by KevinMulhern** [comment]
Thanks @m-chrzan, Zed Shaw has been forever banished from command line basics 😄 https://github.com/TheOdinProject/curriculum/commit/431646769751402a6d53dbdb4db65973d2c2b276
