### ISSUE TITLE
Misguided link

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/curriculum#4516]
Hi Odin Project!

Loving the curriculum so far! Just wanted to let you know that Assignment 1 of Databases (Check out a pretty good plain-english explanation of SQL, written by Zed Shaw, at Learn SQL The Hard Way...) doesn't point to a curriculum anymore. Seems like the book is still in its planning stages?

**Comment by eriktrautman** [comment]
Web Dev 101 > Back-End > Databases

**Comment by csrail** [comment]
Yup I have mentioned it in #4494 :)
I have read the introduction before so I know that the link was pointing to the correct resource but I think Zed has hidden it from view and is now redirecting to only a cover page.

It's been difficult trying to find a simple resource that is really similar in tone and overview but most end up being too comprehensive as an introduction and don't show real life examples of how SQL is used.
