### ISSUE TITLE
Atlassian Git tutorials change

### ISSUE THREAD

**Issue by m-chrzan** [TheOdinProject/curriculum#4535]
Part 2 of the assignment in A Deeper Look at Git links to `https://www.atlassian.com/git/tutorials/git-basics`, which doesn't exist any more - I'm guessing Atlassian changed how the tutorials are organized? The link nicely redirects to [the full list of git tutorials](https://www.atlassian.com/git/tutorials/) they offer, but not one of them is titled "Git Basics."

I'm sure we can still use the Atlassian tutorials, but it'd be good to point to a specific section of them.

**Comment by KevinMulhern** [comment]
Hey @m-chrzan thanks for opening this, I reckon they split that part into these three new parts.
https://www.atlassian.com/git/tutorials/setting-up-a-repository
https://www.atlassian.com/git/tutorials/saving-changes
https://www.atlassian.com/git/tutorials/inspecting-a-repository

**Comment by KevinMulhern** [comment]
do you want to create a pull request with those three links in step 2? to get another commit to your name in the contribution list 😄

**Comment by m-chrzan** [comment]
Sure thing!
