### ISSUE TITLE
Quick Typo

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/curriculum#4549]
Hello, I have found a typo on the site. It is on the "Command Line Basics" page in "Web Development 101". Under the "Points to Ponder", there is the question "Where will cd on it's own navigate you to?" which means "Where will cd on it is own navigate you to?", while it should be "Where will cd on its own navigate you to?". It's not a huge deal but I just figured that I'd let you guys know.

-Dan

**Comment by KevinMulhern** [comment]
Thanks @eriktrautman, fixed with https://github.com/TheOdinProject/curriculum/commit/25a63f439ac8c05973c4c71c79d18469a10a6a22
