### ISSUE TITLE
Change all mentions of slack to gitter and change the chat page link

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#4550]
In preparation for our move to gitter we need to go through the curriculum and change all mentions of slack to gitter.

From doing a global search on the curriculum files, these are the files where slack is mentioned:
* rails/conclusion.md
* web_development_101/project_installations.md

We will be removing the [chat page](http://www.theodinproject.com/chat) and linking directly to the new gitter general room instead. There is a link for the chat page in the gearing up lesson. This should be changed to this link instead https://gitter.im/TheOdinProject/theodinproject

**Comment by csrail** [comment]
Where git is located:

- [ ] the gearing up lesson includes mentions of slack
- [ ] the conclusion of the rails course
- [ ] the installfest project has mentions of slackand the main site:
- [ ] slack link button needs updating
- [ ] the chat page
- [ ] the contribution page

**Comment by KevinMulhern** [comment]
These are all on the main site @csrail 
* slack link button needs updating
* the chat page
* the contribution page

I've got them in this one https://github.com/TheOdinProject/theodinproject/issues/204

**Comment by csrail** [comment]
Cool. I updated the checklist.

**Comment by csrail** [comment]
The links have been updated and a pull request made: #4593
