### ISSUE TITLE
Rails 4.1 secret.yml

### ISSUE THREAD

**Issue by 105ron** [TheOdinProject/curriculum#4596]
I've come across an issue using github for rails 4.1. The file /config/secrets.yml should not be included in git commits and should be ignored. A note could be added to odin to git ignore these files so that users become aware of this issue as tutorials are written before compiling a rails app created this issue. Having these files on github for the public to see is a security issue that novice developers will not be aware of.

**Comment by KevinMulhern** [comment]
Thanks for opening this issue @105ron, we will look into this.
