### ISSUE TITLE
How to use the gitter chatroom

### ISSUE THREAD

**Issue by csrail** [TheOdinProject/curriculum#4620]
This needs a location to be placed at. Any ideas for this mini-lesson?

**Issues:**
1) A lot of people enter a chat room and have little reason to stay. 
2) They also have a poor understanding of how to ask a question.
3) They have difficulty formatting the question.

**Responses**
1) Talk about how chat is actually quite active but people have a limited amount of time a day so you may not get immediate responses. There are also different time zones. People are at various depths in the curriculum etc. In any case, chat is a good way to:
* a) get a heads up of common problems encountered, 
* b) discuss problems 
* c) encourage others to keep at it.

2) Be specific - know what you're looking for: what do you want your program to do? what is it doing instead?

3) Please show a screenshot or paste the code! It could be a million things if we don't have this info - users may also be considering the problem from the wrong perspective. Use markdown backticks!! Also if it is a more complex problem, push your code to github so we can clone it ourselves and play around with it.

**Comment by csrail** [comment]
Pull request at #4628.

**Comment by KevinMulhern** [comment]
This is live 🎉
