### ISSUE TITLE
Searching Binary Trees - Youtube link down

### ISSUE THREAD

**Issue by 105ron** [TheOdinProject/curriculum#4645]
http://www.theodinproject.com/ruby-programming/data-structures-and-algorithms?ref=lc-pb

On this page, item number 5 in Searching Binary Trees project links to this video...

http://www.youtube.com/watch?v=zLZhSSXAwxI

This video has been unavailable for the last couple of days. It says it appears earlier in the curriculum but I've not found any other broken youtube links in the computer science section. Thanks, Rhys.

**Comment by csrail** [comment]
Thanks for this @105ron ++

The website will update in 24 hours.
The changes were made here:
https://github.com/TheOdinProject/curriculum/blob/master/ruby/project_data_structures_algorithms.md
