### ISSUE TITLE
Minor text fix on Learn Web Dev 101 Rails Project

### ISSUE THREAD

**Issue by ayellapragada** [TheOdinProject/curriculum#4664]
In the [Rails Project](http://www.theodinproject.com/web-development-101/ruby-on-rails?ref=lc-pb) in Learn Web Dev 101, in the Extra Credit area # 2 says the following text:

"If you aren't comfortable with git, either skip ahead a few lessons to the introductory section on git or skip any of the $ git ... commands for now. They're essential to learn eventually but non-essential right now (it's sort of like saving your files on Dropbox)."

But you recently moved the git section up a couple chapters so its no longer true.

Fairly minor and probably won't confuse anyone, but should also be easy to fix once y'all decide how you wanted to fix it. Thanks!

**Comment by KevinMulhern** [comment]
👍 thanks for opening this @ayellapragada. I'll get it fixed.

**Comment by KevinMulhern** [comment]
Fixed with: https://github.com/TheOdinProject/curriculum/commit/2dba296049a571527613a0ff63a271e3ac9977a9
