### ISSUE TITLE
Mint website to copy is broken

### ISSUE THREAD

**Issue by csrail** [TheOdinProject/curriculum#4677]
In [Project: HTML Forms (with Mint)](http://www.theodinproject.com/html5-and-css3/html-forms) the example project page to copy is broken:

https://mint.intuit.com/login.event?task=S

There won't be any forms to copy.
Any suggestions?

**Comment by KevinMulhern** [comment]
Hey @csrail, it's displaying for me

**Comment by csrail** [comment]
That's good. I'm still getting a blank though so I wonder how reliable it is for other users; we'll just have to monitor.

I am using firefox at the moment and based in NZ so it might be one of those issues...
I might be able to put this up as a portfolio item if it's stable again heh.
