### ISSUE TITLE
TheOdinProject repository no longer contains a /dev branch

### ISSUE THREAD

**Issue by 105ron** [TheOdinProject/curriculum#4708]
http://www.theodinproject.com/ruby-programming/using-git-in-the-real-world?ref=lc-pb

The 'dev' branch appears to no longer exist within The Odin Projects git. The exercise says not to merge with 'Master' but there appears not to be any other options for the assignment? Thanks.

**Comment by KevinMulhern** [comment]
We should probably remove that part about the dev branch. We are planning on replacing those git lessons in the near future.

**Comment by csrail** [comment]
:feelsgood:  :shipit:

**Comment by KevinMulhern** [comment]
Created a new `dev` branch until we can get a chance to change those lessons
