### ISSUE TITLE
Troubleshooting Git Basics lesson

### ISSUE THREAD

**Issue by csrail** [TheOdinProject/curriculum#4749]
The newly launched git lessons have been going great so far - in fact there haven't been any problems bar one. This problem originates from the assignment in the [Git Basics lesson](http://www.theodinproject.com/web-development-101/practicing-git-basics). In particular, trying to introduce `git init` and then `git add *.c`.

It should be clear that `*.c` is a placeholder for a file with the extension `.c`. However a few students find it unclear what it is that they should be doing - they enter commands without appreciating neither the state they are in or the output:

`fatal: pathspec '*.c' did not match any files`

**The following section needs evaluation:**

Complete the first three sections of chapter 2 of Pro Git:
  * Section 1: [Getting a git repository](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository)
  * Section 2: [Recording changes to the repository](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository)
  * Section 3: [Viewing the commit history](https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History)

I was aware that the implementation of this material could stump a few people. However I think the trade off of improving the tenacity of students is an important skill we cannot overlook.

Suggestions?

**Comment by KevinMulhern** [comment]
what about replacing them with some of the atlassian guides instead
these ones to be specific:
* https://www.atlassian.com/git/tutorials/setting-up-a-repository
* https://www.atlassian.com/git/tutorials/saving-changes
* https://www.atlassian.com/git/tutorials/inspecting-a-repository

**Comment by KevinMulhern** [comment]
Another option would be to add a note telling the student the files used in the tutorial are dummy files they will have to create first. But that could get messy.

**Comment by csrail** [comment]
Although I do like the git tutorials on atlassian, there's an issue there with context regarding SVN as another version control system. Both the latter two links of atlassian look really good actually. It's just the first one (setting-up-a-repoistory) talks about random things.

Yea I don't like having to clean up loose ends like that, it'll add a dependency :hankey: that I don't want.

**Comment by KevinMulhern** [comment]
agreed on the second option I don't like that either. Yeah I just noticed they start talking about SVN.
One more option would be the git course on codecademy https://www.codecademy.com/learn/learn-git

I've heard good things about it

**Comment by csrail** [comment]
All right I'll concede with the codeacademy lesson.
Our additional resources cover all the background material for the more conceptual / theoretical people.

I'm go for codeacademy:  https://www.codecademy.com/learn/learn-git

**Comment by KevinMulhern** [comment]
👍 sounds good

**Comment by saqib1707** [comment]
Hi everyone,new to open source having basic knowledge of python , C++, javascript. Any easy issues to get started on to contributing to this repo..??

**Comment by csrail** [comment]
The 3-part Pro Git resource has been substituted entirely with the first interactive lesson of https://www.codecademy.com/learn/learn-git
