### ISSUE TITLE
Cannot access http://beginningruby.org/ 

### ISSUE THREAD

**Issue by aswinmohanme** [TheOdinProject/curriculum#4800]
**Problem**
The Site [http://beginningruby.org/](http://beginningruby.org/) displays nothing sensible when opened. [http://www.theodinproject.com/ruby-programming/ruby-building-blocks ](http://www.theodinproject.com/ruby-programming/ruby-building-blocks ) points to that website.

**Comment by KevinMulhern** [comment]
Thanks @aswinmohanme we will get this fixed

**Comment by aswinmohanme** [comment]
Now it shows that the domain name has Expired

**Comment by KevinMulhern** [comment]
Fixed with https://github.com/TheOdinProject/curriculum/commit/7083ed4aaded70b1e6d15530e0c39717834a1aad

**Comment by KevinMulhern** [comment]
This now links to the amazon page for the book
