### ISSUE TITLE
string's inside '#' makes it  display as comment.

### ISSUE THREAD

**Issue by riahtire** [TheOdinProject/curriculum#493]
in code examples at http://www.theodinproject.com/ruby-on-rails/routing 
it seems like everything behind '#' has been treated as comment, even when the '#' is in a quoted string. 
this problem maybe also exists in other page.

**Comment by onebree** [comment]
@N19270 -- @eriktrautman committed a change to their syntax highlighterm which in turn affects all pages. As you said, any page that had the issue you described is now fixed.

https://github.com/TheOdinProject/theodinproject/commit/32bfe58b4ec7d6d84685b6ba8ea8f9fda704e0ac

**Comment by N19270** [comment]
:+1:
