### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by nmacawile** [TheOdinProject/curriculum#5049]
The link 'The Anatomy of a Web Application' (http://www.buildingwebapps.com/transcript/79327-anatomy-of-a-web-application) under 'web_development_101/how_are_websites_built' is down.

**Comment by KevinMulhern** [comment]
Thanks @nmacawile we will get this fixed 😄

**Comment by ChadKreutzer** [comment]
Yup. looks like it doesn't exist at all. I never clicked on it, so I'm not sure what exactly it contained, but based on the title and the google slug, here are a couple potential replacements:
[Short and sweet on MVC with a cute name](http://blog.roberteshleman.com/2014/07/07/models-views-and-controllers-oh-my-anatomy-of-a-rails-app/)
[Looks like it was abandoned after part II, but what's there is pretty good](http://codergeneral.com/anatomy-of-a-rails-application-part-i-views/)

**Comment by KevinMulhern** [comment]
Nice find @ChadKreutzer, do you want to open a PR replacing the broken article with these? 😄

**Comment by ChadKreutzer** [comment]
Sure. Go ahead and assign me to it since I may not have time to finish it this morning.

**Comment by KevinMulhern** [comment]
It's all yours 😄 thanks Chad.
