### ISSUE TITLE
Scroll Bar Bugs

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5070]
* scroll bar appears on points to ponder list on ruby building blocks
* No scroll bar appears on student solutions for the event manager project (Reported)

**Comment by leosoaivan** [comment]
Related:
- Scroll bar appears on solutions to the Knight's Travails project, but not on solutions for Binary Search Tree project (http://www.theodinproject.com/courses/ruby-programming/lessons/data-structures-and-algorithms)

**Comment by codyloyd** [comment]
curses...
the only real way to deal with this is to either work on the lessons themselves, or remove scrollbars altogether.

I'll mess around and see what needs to be done to the lessons.

Kev: is there a way I can mess with the curriculum that gets pulled into my local version of the mainsite?  Not really sure how else to test changing curriculum stuff AND css stuff

**Comment by KevinMulhern** [comment]
I don't think so man, I would leave this until we do the the user projects feature. We should be starting it within the next couple of weeks anyway 😄

**Comment by codyloyd** [comment]
yay
