### ISSUE TITLE
Link not working on 'How Are Websites Actually Built in the Real World?'

### ISSUE THREAD

**Issue by JustinVx** [TheOdinProject/curriculum#5090]
On the ['How Are Websites Actually Built in the Real World?' page](http://www.theodinproject.com/courses/web-development-101/lessons/how-are-websites-built-in-the-real-world?ref=lnav) in Webdevelopment 101, the link to  ['The Anatomy of a Web Application'](http://www.buildingwebapps.com/transcript/79327-anatomy-of-a-web-application) is a webpage that seems to be deleted.

**Comment by KevinMulhern** [comment]
Hey @JustinVx, this was fixed this morning 😄 I just pushed out the fix.
