### ISSUE TITLE
Learn Ruby troubleshooting

### ISSUE THREAD

**Issue by csrail** [TheOdinProject/curriculum#5150]
Some students have recently come across the learn-ruby test suite and have been unable to run the rspec tests. Most of the issues were related to parent folders having spaces in between them. Improving visibility of this common troubleshooting problem will help a lot of users. It is already located in the README.md of the forked project but it is clear that some people are not reading it in its entirety.

Any ideas where to put it?
@105ron @KevinMulhern

**Comment by KevinMulhern** [comment]
Maybe put it at the top of the readme?

**Comment by 105ron** [comment]
https://github.com/105ron/learn_ruby/blob/aaa0c552a62ade858706bd3ffda72ca462d9df52/README.md . Something along those lines should cover it?

**Comment by ChadKreutzer** [comment]
@105ron Did you want to go ahead and push that up?

**Comment by 105ron** [comment]
@ChadKreutzer @KevinMulhern I don't have authoization to merge but I have made the pull request so this can be closed off.

**Comment by ChadKreutzer** [comment]
Moved to [Learn Ruby #9](https://github.com/TheOdinProject/learn_ruby/pull/9)
