### ISSUE TITLE
Remove twitter spam bot project

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5180]
Twitter seems to have changed their API making this project impossible to work with. We should remove this project and just have the server and browser project.

The description of this lesson on the main site will need to be updated to reflect this change. Whoever picks this up let me know and I'll make the change on the main site if you're not comfortable doing that.

Lesson in question:
http://www.theodinproject.com/courses/ruby-programming/lessons/ruby-on-the-web

**Comment by ChadKreutzer** [comment]
I'll be happy to take this, I'll take a shot at modifying the main site before asking for help--I'm thinking grep will be my friend to find the right file?

**Comment by KevinMulhern** [comment]
Hi @ChadKreutzer, thanks for taking this on. Yeah it should just be a one line change in the `seeds.rb` file on the main site. If you need any help with it give me a ping on gitter 😄

**Comment by KevinMulhern** [comment]
@ChadKreutzer solved this https://github.com/TheOdinProject/curriculum/commit/b8efa51b402ed2edcaff7c70c0afd8b06039fb7f
