### ISSUE TITLE
The link to backbone tutorials is broken

### ISSUE THREAD

**Issue by simoroshka** [TheOdinProject/curriculum#5186]
The website doesn't seem to exist anymore (or the link is wrong), the domain is on sale. 
The page with the broken link: 
http://www.theodinproject.com/courses/javascript-and-jquery/lessons/building-single-page-websites-with-angular-js-and-backbone-js

**Comment by KevinMulhern** [comment]
Thanks for reporting this @simoroshka 😄

**Comment by ChadKreutzer** [comment]
Consider it done. I'll Google around for an alternative tutorial.

**Comment by KevinMulhern** [comment]
Thanks @simoroshka 😄

**Comment by KevinMulhern** [comment]
@ChadKreutzer solved this https://github.com/TheOdinProject/curriculum/commit/c155957ebd1b0b75c27da73b31f199483c883915
