### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by OlehSliusar** [TheOdinProject/curriculum#5275]
In the lesson Introduction to Web Development >> About Web Developers >> 2: Web Development Jobs and Careers, there's a link to codecomputerlove which leads to a website that can't be reached.

**Comment by KevinMulhern** [comment]
Is this the link @OlehSliusar? 
http://www.codecomputerlove.com/blog/a-day-in-the-life-of-a-web-developer
It seems to be working for me

**Comment by KevinMulhern** [comment]
It might have been down when you tried it though

**Comment by OlehSliusar** [comment]
@KevinMulhern it doesn't work for me even now... That's strange

**Comment by OlehSliusar** [comment]
It works only in Tor browser. Maybe it's a problem of my country

**Comment by KevinMulhern** [comment]
Yeah it still works for me, very strange.

**Comment by KevinMulhern** [comment]
Hey @OlehSliusar, I'm closing this because it hasn't been reported anyone else. I think it might be a country problem as you suggested. Thanks for reporting it 😄

**Comment by OlehSliusar** [comment]
@KevinMulhern Ok, male
