### ISSUE TITLE
RestClient does not return Google Search

### ISSUE THREAD

**Issue by 105ron** [TheOdinProject/curriculum#5319]
See point 5.
https://github.com/TheOdinProject/curriculum/blob/master/rails/project_lets_build.md

A student was trying to get their rest-client bot to query Google. Their code was (or appeared to me to be) correct but Google seemed to be detecting the request was made outside the browser and returning the html for the Google home page and not the search results.

Is there a search engine we could use where the query would return the results page?

**Comment by ChadKreutzer** [comment]
Bing. I just tried it and it worked with Bing.

**Comment by ChadKreutzer** [comment]
Solved in issue #5339
