### ISSUE TITLE
Git Course

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5379]
This is the overview of the development of our Git course. Please feel free to leave suggestions in the comments, such as:
* Resources you think should be used in this course
* Lessons not on the lesson plan you think should be included
* Projects you think will make this course more engaging
* Any kind of feedback in general in relation to this course.

### We need your help
We encourage you to contribute to the development of this course if you can, the more help we get the better the course will be and the quicker we can get it out there.

### Overall learning Goals of this course
* Understand the difference between git and github
* Understand the basics of adding and committing
* Know how to undo changes, git reset, checkout previous version of a file
* Understand what a branch is
* Know how to use branches in a project, feature, branches, merging etc
* Know how to un do changes
* Understand what a remote is
* Know how to work with a remote, pushing and pulling and creating a Pull request

### Lesson Plan
Each lesson link here will lead to a separate issue for the lesson where we provide more details about the lesson if its not completed. If the lesson is completed the link will lead to the completed lesson file.

**Intermediate Git**
- [ ] [Branches](https://github.com/TheOdinProject/curriculum/issues/5382)
- [x] [Project - Branches](https://github.com/TheOdinProject/curriculum/issues/5384)
- [ ] [Undo Changes with Git](https://github.com/TheOdinProject/curriculum/blob/master/archive/git/undo_changes.md)
- [ ] [Project Undo Changes](https://github.com/TheOdinProject/curriculum/issues/5381)
- [ ] [Working with Remotes](https://github.com/TheOdinProject/curriculum/issues/5386)
- [x] [Project - Remotes](https://github.com/TheOdinProject/curriculum/blob/master/archive/git/project_git_remotes.md)

This course will be attached between webdev101 and the rest of the curriculum in each track.

**Comment by iansowinski** [comment]
Maybe it worth adding somewhere note about [student developer packs](https://education.github.com/pack). I think a lot of TOP students are enrolled on some universities and can benefit from it.

**Comment by KevinMulhern** [comment]
Thanks @iansowinski, I didn't know you github did stuff like that.

**Comment by iansowinski** [comment]
@KevinMulhern They do! Also I believe GitLab has option to host private repos for free (contrary to github witch allow users to have only public repos on free plan) - maybe it's worth mentioning somewhere. It may be confusing for some people though.

**Comment by KevinMulhern** [comment]
Yeah it could get confusing with introducing gitlab into the mix.

**Comment by akshaymukadam** [comment]
we can add `git-flow` which will help to understand how it is used in some companies
https://danielkummer.github.io/git-flow-cheatsheet/

**Comment by KannaDev** [comment]
>You can use GitHub developer pack only for educational content and none of other offers are actually free, we need to give our cc details to proceed in other offers... How will a student have a credit card..?


@Avizini Well, i've been using the github developer pack since I was in high school. I didn't have a CC and all of the ones I tried in the pack had no problem with me not having a CC.

**Comment by Avizini** [comment]
@KannaDev I checked it yesterday, I got my academic status verified and signed up for DigitalOcean. DigitalOcean asks me for a cc before I can do anything with my account! I signed up using the link provided by GitHub. However there are new offers added to the pack and I cannot access some because my school doesn't provide me with an email.

I was able to use NameCheap's, Travis, SendGrid and some other offers. So yeah, GitHub's Educational pack has some really good offers.

**Comment by KannaDev** [comment]
@Avizini Yeah, the digital ocean offer is so useful in my opinion. You have to add a CC before you can finish registering but they won't charge it unless your $50 Github credit runs out. If you don't have a CC I recommend you checkout [privacy.com](http://www.privacy.com/) they let you generate a CC if you link a bank acc. Pretty cool.

**Comment by Avizini** [comment]
@KannaDev > You have to add a CC before you can finish registering but they won't charge it unless your $50 Github credit runs out.

I know this. Also about privacy.com, I am under 18 and my country doesn't allow me to have a bank account. My parents won't do it either, so no luck for me! :(

**Comment by KannaDev** [comment]
@Avizini oh, same lol I am under 18 as well. I had to practically convince (beg) my parents to let me use their CC for something they don't understand (Digital Ocean VPS) even after I assured them they had nothing to worry about as nothing would be charged on the CC.

**Comment by I3uckwheat** [comment]
I've cleaned up this ticket for new and forward going conversation :)

**Comment by kashura** [comment]
[I found this to be a great, practical resource for learning Git](https://gitimmersion.com/index.html)

GitImmersion is released under a Creative Commons BY-NC-SA 3.0 License, so we could make changes if needed.
