### ISSUE TITLE
Git Course: Branches

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5382]
This is the lesson details for the proposed "Introduction to branches" lesson in our new Git course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach how to think conceptually about branches and what they are useful for.

### Learning Outcomes for Lesson
* The student understand what a branch is in git
* The student understand what the master branch is
* The student understands why branches are useful in projects, especially projects with a team
* The student understands what a feature branch is and what its used for
* The student understands what a spike branch is for

### Progress
- [ ] Introduction -summary of what the lesson is about and why its important
- [ ] Learning outcome list - same as the above learning outcomes
- [ ] Assignment - Add a few resources for the user to go through for this topic
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/git/git_branches_intro.md)

**Comment by horoxix** [comment]
Hey Kevin I would love to give this lesson a shot and work on it. It might take me a couple of days but I'd love to help.

**Comment by KevinMulhern** [comment]
Hey @horoxix, its all yours 😄 if you have any questions or want clarification on anything don't hesitate to let me know.

**Comment by 105ron** [comment]
@horoxix thanks for the help : smile:

**Comment by jacob-on-github** [comment]
@horoxix are you still working on this? If not, I'll work on it next week.

**Comment by KevinMulhern** [comment]
Hi @jacob-on-github I was going to reply to you on the other issue, but might as well do it here. We've heard nothing from @horoxix in a month so its safe to assume he's abandoned this. This ones all yours if you want to work on it.

**Comment by jacob-on-github** [comment]
@KevinMulhern I'll try to have this one knocked out in a week or so. Thanks.

**Comment by gionaufal** [comment]
Hello @KevinMulhern  and @jacob-on-github. I would like to help on this issue. Is there any branch with it already started?

**Comment by KevinMulhern** [comment]
Hey @horoxix, yeah the lesson has already been started [here](https://github.com/TheOdinProject/curriculum/blob/master/git/git_branches_intro.md) the file is up to date with the last work that was done to it so theres no branch for it 😄

**Comment by heyalvaro** [comment]
@KevinMulhern What is this lesson missing to be complete?

**Comment by KevinMulhern** [comment]
Hey @heyalvaro sorry for the late reply, all thats left is fleshing out the content under the different headings. All we have at the moment is "In this section, you will learn the basics of branching in Git." for example.
