### ISSUE TITLE
Git Course: Working with Git branches

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5383]
This is the lesson details for the proposed "Working with Git Branches" lesson in our new Git course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student the different the commands for working with branches in git.

### Learning Outcomes for Lesson
* The student knows how to create a branch
* The student knows how to checkout branches and to switch between branches
* The student knows how to merge a branch into another branch
* The student knows how to delete a branch

### Progress
- [ ] Introduction -summary of what the lesson is about and why its important
- [ ] Learning outcome list - same as the above learning outcomes
- [ ] Assignment - Add a few resources for the user to go through for this topic
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/git/working_with_git_branches.md)

**Comment by gionaufal** [comment]
Hi! I would like to work on this lesson

**Comment by KevinMulhern** [comment]
Hi @gionaufal, we decided to roll this lesson into [this one](https://github.com/TheOdinProject/curriculum/issues/5382). That lesson has had a bit of work done to it, but it could use more detailed content. If you want, you could work on that one?
