### ISSUE TITLE
Git Course: Git remotes

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5386]
This is the lesson details for the proposed "Git Remotes" lesson in our new Git course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student what a remote is and use to work with it.

### Learning Outcomes for Lesson
* The understands what a remote is
* The student knows how to view remotes on a local project
* The student knows how to add a remote
* The student knows how to get changes from a remote(pull)
* The student knows how to upload changes to a remote(push)
* The student knows how to fork and clone a repo to their machine
* The student knows how to submit a pull request to a remote that doesn't belong to them

### Progress
- [ ] Introduction -summary of what the lesson is about and why its important
- [ ] Learning outcome list - same as the above learning outcomes
- [ ] Assignment - Add a few resources for the user to go through for this topic
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/git/git_remotes.md)

**Comment by KevinMulhern** [comment]
Potential resource for this lesson https://guides.github.com/introduction/flow/

**Comment by jacobherrington** [comment]
@KevinMulhern I will work on this if it's still up for grabs.

**Comment by KevinMulhern** [comment]
Hi @jacobherrington, it sure is. I'm really looking forward to seeing what you come up with 😄

**Comment by jacobherrington** [comment]
@KevinMulhern I feel that this lesson should also cover removing old or unnecessary remotes as well, so that new developers following along might be able to undo any mistakes they make.

**Comment by KevinMulhern** [comment]
@jacobherrington sure, feel free to add anything that you think should be in there 👍
