### ISSUE TITLE
Git Course: Project Remotes

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5387]
This is the project details for the proposed "Git Remotes" project in our new Git course. If you want to work on this project please leave a comment to let us know.

### Description
This project will allow the student to practice submitting a PR to a repo that belongs to Odin.

The Student will be tasked with forking and cloning a repo which already has a file in it which will include a list of names of students who have completed this project in the past. Their task will be to create a branch and to add their name to the list. They will then submit a Pull request to get thier name added to the original repo.

### Progress
- [x] Create a repository which contains a file with student names in the odin org
- [x] Introduction -summary of what the student will be doing in the project
- [x] Detailed task list or walkthrough of what the steps the student should take to complete the project

### Template for this project
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/git/project_git_remotes.md)

**Comment by KevinMulhern** [comment]
@TheOdinProject/odinmods Ready for review please. Completed by @105ron.

**Comment by KevinMulhern** [comment]
@TheOdinProject/odinmods this needs a review please https://github.com/TheOdinProject/curriculum/blob/master/git/project_git_remotes.md

**Comment by mindovermiles262** [comment]
https://github.com/TheOdinProject/curriculum/pull/7546

My review was funky so I made a PR
