### ISSUE TITLE
Git Course: Conclusion

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5388]
his is the lesson details for the proposed "Conclusion" lesson in our new Git course. If you want to work on this lesson please leave a comment to let us know.

### Description
This will be the closing lesson in our Git course it will include a summary of everything taught in the course and how the student will use this in the future in a job setting. It will also include direction of where to find out more about git and how to get better at it.

### Progress
- [ ] Conclusion of course -summary of what the lesson the student learned and how they will use it all.
- [ ] Where to learn more - Direct the student to resources where they can learn more about git and advice them on how they can get better with git by using it.
### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/git/git_conclusion.md)

**Comment by Himanshi-Khandelwal** [comment]
I would like to help.

**Comment by Himanshi-Khandelwal** [comment]
please brief for what all I need to do.

**Comment by KevinMulhern** [comment]
@Himanshi-Khandelwal all is explained in the [README](https://github.com/TheOdinProject/curriculum/blob/master/README.md) for this repo 😄

**Comment by jacobherrington** [comment]
Was this issue abandoned? What needs to be done? @KevinMulhern

**Comment by hcarnes** [comment]
I would like to help with this issue if it is still active.

**Comment by Marethyu12** [comment]
@KevinMulhern Any progress? Is there's anything I can help you with?

**Comment by I3uckwheat** [comment]
@Marethyu12 Would you like me to assign this issue to you? Are you still interested?

**Comment by KevinMulhern** [comment]
Sorry for the late reply @Marethyu12, we should probably close this issue. We have no logical place to put this lesson. We intended to have courses for each subject as well as tracks but have decided against that now.
