### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by waglebr** [TheOdinProject/curriculum#5466]
There's a broken link under Student Solutions at the end of the page (http://www.theodinproject.com/courses/web-development-101/lessons/html-css)
![image](https://cloud.githubusercontent.com/assets/10777324/21473734/35d0fd1a-cafc-11e6-8773-dccdeda9f7b5.png)

**Comment by 105ron** [comment]
This link is on every project page. We might need to make another contributing.md as the easiest fix for this?

**Comment by KevinMulhern** [comment]
Yeah I was thinking about creating a temporary file which just included the video Erik made. This wont be a problem when the student submissions feature goes live.

**Comment by KevinMulhern** [comment]
This has been fixed
