### ISSUE TITLE
Ruby Course: Loops

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5496]
This is the lesson details for the proposed "Loops" lesson in our new Ruby course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student about why loops are used in programming and how to create different loops in Ruby.

### Learning Outcomes for Lesson
* The student understands what a loop is and why its useful
* The student understand what a Rubys `loop` is and how and when to use it 
* The student knows how to use a while loop in ruby
* The student knows how to use a for loop in ruby
* The student knows how use a times loop in ruby.
* The student knows how to use the until loop in ruby.
* The student knows how to use the upto and downto loops in ruby

### Progress
- [x] Break lesson into sub headings
- [x] Introduction -summary of what the lesson is about and why its important
- [x] Learning outcome list - same as the above learning outcomes
- [x] Rubys `loop` loop section
- [x] While loop section
- [x] For loop section
- [x] Times loop section
- [x] Until loop section
- [x] Upto and downto loops section 
- [ ] Exercises - these will be in an external repo (tbd)
- [ ] Further reading - add any further reading links which supplement this material

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basics/loops.md)

**Comment by KevinMulhern** [comment]
**Potential Resources**
https://launchschool.com/books/ruby/read/loops_iterators

**Comment by calandraz** [comment]
I'd be interested in taking a stab at this particular task. Do I write up everything myself based on the template or is this data supplied?

**Comment by KevinMulhern** [comment]
Hi @calandraz, the mods had a meeting last night about the format these lessons should take. We decided on to go with more original content. I've updated this issue and the template to reflect this new approach. If you have any questions about please let me know 😄

**Comment by calandraz** [comment]
@KevinMulhern so instead of linking the user to external sites to read about a particular concept, we are now providing that information? Can we provide a description on the concepts and still link to an external site for further learning? Just want to make sure I am getting everything correct so that I can start writing up necessary information.

**Comment by KevinMulhern** [comment]
Hey @calandraz, sorry we have been going between writing our own content or going with the same format.

We held a group vote to stick with using external resources and only writing our own content for best practices and pro-tips etc.

With that in mind this loops lesson should be pretty straight forward. It will follow the same kind of format as existing lessons.

Really all that needs to be done for this lesson write now is to write an introduction and choose a few external resources that collectively cover all the learning outcome points.

Here are some of the resources we have identified so far:
http://www.eriktrautman.com/posts/ruby-explained-iteration
http://zetcode.com/lang/rubytutorial/flowcontrol/
http://ruby.bastardsbook.com/chapters/loops/
http://www.skorks.com/2009/09/a-wealth-of-ruby-loops-and-iterators/
https://launchschool.com/books/ruby/read/loops_iterators#simpleloop

**Comment by calandraz** [comment]
Hi @KevinMulhern, thanks for clearing things up for me. I'd like to start working on this and will begin working on it immediately if that's cool.

**Comment by KevinMulhern** [comment]
It's all yours @calandraz 😄

**Comment by calandraz** [comment]
Hi @KevinMulhern, is there an external repo to link to in the Exercises section? That's all that's left to do.

**Comment by KevinMulhern** [comment]
@calandraz theres none yet, we are still planning out how the exercises will work in the external repo 😄

**Comment by calandraz** [comment]
@KevinMulhern ok, no problems...I'm about to try a pull request...let me know if any changes are needed!
