### ISSUE TITLE
Ruby Course: Arrays

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5497]
This is the lesson details for the proposed "Arrays" lesson in our new Ruby course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student about arrays and what you can do to them

### Learning Outcomes for Lesson
* The student understands what an array is
* The student knows how to access data in an array
* The student knows the different methods for adding data to an array
* The student knows the different methods for removing data from an array

### Progress
- [x] Introduction -summary of what the lesson is about and why its important
- [x] Learning outcome list - same as the above learning outcomes
- [x] Assignments
- [ ] exercises - 5 small basic exercises related to the topics covered in this lesson
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basics/arrays.md)

**Comment by KevinMulhern** [comment]
We should expand on the learning outcomes and make them more specific.

**Comment by leosoaivan** [comment]
I'll take a crack at this. Are we splitting this lesson off from the Ruby Basics lesson in Web Dev 101?

**Comment by KevinMulhern** [comment]
No problem @leosoaivan 😄 these series of lessons will be replacing the basics section on the ruby course.

**Comment by KevinMulhern** [comment]
**Potential Resources**
https://launchschool.com/books/ruby/read/arrays#whatisanarray

**Comment by charlesharries** [comment]
I'd also like to take a crack at this. I remember arrays really tripped me up when I first started getting into them. Has any progress been made on this in the past month?

**Comment by KevinMulhern** [comment]
Hi @charlesharries, @leosoaivan has completed a draft for this lesson. We have a bunch of other lessons ready and available to work on if you want contribute 😄

**Comment by OlehSliusar** [comment]
*Potential exercises*
https://www.hackerrank.com/domains/ruby/ruby-arrays/page:1

**Comment by leosoaivan** [comment]
@OlehSliusar this is pretty cool, I'll take a look when I can. @KevinMulhern, what do you think?

**Comment by KevinMulhern** [comment]
Looks good to me 👍 😄
