### ISSUE TITLE
Ruby Course: Hashes

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5504]
This is the lesson details for the proposed "Hashes" lesson in our new Ruby course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student about arrays and what you can do to them

### Learning Outcomes for Lesson
* The student understands what an hash is
* The student knows what a hash is good for
* The student knows how to access data in a hash
* The student knows the different methods for adding data to a hash
* The student knows the different methods for removing data from a hash

### Progress
- [x] Break lesson into sub headings
- [x] Introduction -summary of what the lesson is about and why its important
- [x] Learning outcome list - same as the above learning outcomes
- [x] Creating a hash section
- [x] Adding data to a hash section
- [x] Accessing data in a hash section
- [x] Changing data in a hash section
- [x] Removing data in a hash section
- [x] Merging hashes section
- [x] Useful hash methods section
- [x] Best practices section
- [ ] exercises - external repo with exercises and tests for feedback TDB
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basics/hashes.md)

**Comment by KevinMulhern** [comment]
**Potential Resources**
https://launchschool.com/books/ruby/read/hashes

**Comment by charlesharries** [comment]
I've written a lesson on hashes that I think covers everything a beginner ought to know about hashes. If I want to submit it, do I just submit a pull request the same way I do when adding project solutions?

**Comment by 105ron** [comment]
@charlesharries that is correct. If you submit a PR on [the file that is the template for this lesson](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basics/hashes.md) everyone will take a look and make suggestions and before it is merged into the curriculum. There was a few examples recently but they've been merged in the past couple of days.

**Comment by KevinMulhern** [comment]
Lesson content completed by @charlesharries https://github.com/TheOdinProject/curriculum/pull/5745#pullrequestreview-20180834
