### ISSUE TITLE
Ruby Course: Basic Enumerable Methods

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5505]
This is the lesson details for the proposed "Basic enumerable methods" lesson in our new Ruby course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student about arrays and what you can do to them

### Learning Outcomes for Lesson
* The student understands what an enumerable method is
* The student knows what the each enumerable method does
* The student knows what the each with index enumerable method does
* The student knows what the map enumerable method does
* The student knows what the select enumerable method does
* The student knows what the all? enumerable method does
* The student knows what the any? enumerable method does

### Progress
- [x] Break lesson into sub headings
- [ ] Introduction -summary of what the lesson is about and why its important
- [ ] Learning outcome list - same as the above learning outcomes
- [ ] Each method section
- [ ] Each with index method section
- [ ] Map method section
- [ ] Select method section
- [ ] All? method section
- [ ] Any? method section 
- [ ] exercises - 5 small basic exercises related to the topics covered in this lesson
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basics/basic_enumerable_methods.md)

**Comment by WendyBeth** [comment]
**Potential Resource**

https://mauricio.github.io/2015/01/12/implementing-enumerable-in-ruby.html

A blog post detailing the implementation of several enumerable methods.

**Comment by KevinMulhern** [comment]
Awesome resource @WendyBeth, thanks for sharing it here/
