### ISSUE TITLE
Ruby Course: Methods

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5506]
This is the lesson details for the proposed "Methods" lesson in our new Ruby course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student about arrays and what you can do to them

### Learning Outcomes for Lesson
* The student understands what an method is
* The student knows what a method is good for
* The student knows how to create a method
* The student knows how to use arguments with methods
* The student knows the difference between an implicit and explicit return from a method

### Progress
- [x] Break lesson down into sub headings
- [x] Introduction -summary of what the lesson is about and why its important
- [ ] Learning outcome list - same as the above learning outcomes
- [x] Rubys built in methods section
- [x] Creating your own method section
- [x] Parameters and arguments section
- [ ] Return values section
- [ ] Chaining methods section
- [ ] Best practices section 
- [ ] exercises tbd
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basics/methods.md)

**Comment by leosoaivan** [comment]
I'll take a crack at this. Are we splitting this lesson off from the Ruby Basics lesson in Web Dev 101?

**Comment by KevinMulhern** [comment]
**Potential Resources**
https://launchschool.com/books/ruby/read/methods#whataremethodsandwhydoweneedthem
