### ISSUE TITLE
Ruby Course: Project Stock Picker

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5522]
This is the project details for the proposed "Stock Picker" project in our new Ruby course. If you want to work on this project please leave a comment to let us know.

### Description
This project will be the same as the Stock Picker project that we already have in the ruby course.

### Progress
- [x] problem description -  description of what the student will be expected to build for the project
- [x] Tips/helpful external resources - list of tips or external resources the student may find useful.

### Template for this project
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basic_projects/project_stock_picker.md)

**Comment by jacobherrington** [comment]
Does this lesson still need to be written?
