### ISSUE TITLE
Ruby Course: Project Bubble Sort

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5524]
This is the project details for the proposed "Bubble Sort" project in our new Ruby course. If you want to work on this project please leave a comment to let us know.

### Description
This project will be the same as the bubble sort project that we already have in the ruby course.

### Progress
- [ ] problem description -  description of what the student will be expected to build for the project
- [ ] Tips/helpful external resources - list of tips or external resources the student may find useful.

### Template for this project
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basic_projects/project_bubble_sort.md)

**Comment by jacob-on-github** [comment]
I would like to work on this as I have time.

**Comment by KevinMulhern** [comment]
Hey @jacob-on-github this one is sort of already done https://github.com/TheOdinProject/curriculum/blob/master/ruby/basic_projects/project_bubble_sort.md

Sorry I should have closed this issue.

**Comment by jacob-on-github** [comment]
@KevinMulhern cool, are the other projects open? I can do whatever.
