### ISSUE TITLE
Let's fix 'ruby on the web'

### ISSUE THREAD

**Issue by iansowinski** [TheOdinProject/curriculum#5573]
Hi, ["Projects: Ruby on the web"](https://github.com/TheOdinProject/curriculum/blob/master/ruby/project_web.md) project is a mess, we are introduced with theory about TCPServer and then, first task is the same as one in theory part.

Proposed changes:
  - Move "Background Reading" section to ["Ruby on the web"](https://github.com/TheOdinProject/curriculum/blob/master/ruby/bringing_ruby_online.md)
  - Delete "explanation of how HTTP works" 
  - Add some nice description to task

**Comment by KevinMulhern** [comment]
Hey @iansowinski, thanks for opening this 😄 we agree it's a mess. We decided to remove this part of the curriculum as we believe it delivers little value.

**Comment by iansowinski** [comment]
Well, for me building web server was fun!

In one side-project I took advantage of sockets in general. Maybe curriculum should focus on more general things when it comes to transferring data. I don't know. I just did this part and it felt quite important :)

**Comment by KevinMulhern** [comment]
Remove it is a strong word, we will be archiving it and probably integrating it again at a later date in a more 'advanced' Ruby course. We have started overhauling the ruby course with the goal of keeping it focused on learning the basics, OOP, testing and good program design.
