### ISSUE TITLE
Split multi-project lessons into separate lessons

### ISSUE THREAD

**Issue by arun1595** [TheOdinProject/curriculum#5617]
Since we are going to be releasing the project submission feature soon, we can't have multiple projects in the same lesson anymore.(Learners might have different repos for each project).

This issue is focused on splitting the following multi-project lessons:

- [Building blocks](http://www.theodinproject.com/courses/ruby-programming/lessons/building-blocks)
- [Advanced Building blocks](http://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks)
- [OOP](http://www.theodinproject.com/courses/ruby-programming/lessons/oop)
- [File I/O and Serialization](http://www.theodinproject.com/courses/ruby-programming/lessons/file-i-o-and-serialization)
- [Recursion](http://www.theodinproject.com/courses/ruby-programming/lessons/recursion) - _Not sure if this needs to be split_
- [Data Structures And Algorithms](http://www.theodinproject.com/courses/ruby-programming/lessons/data-structures-and-algorithms)
- [Testing Ruby](http://www.theodinproject.com/courses/ruby-programming/lessons/testing-ruby)

/cc @KevinMulhern

**Comment by junkdeck** [comment]
You just made me realize there were more than one project per lesson. 
These "student solution" lists really need to be put in a frame or something so they don't take up so much space.

**Comment by KevinMulhern** [comment]
We are working on a solution for that problem @junkdeck 😄

**Comment by junkdeck** [comment]
Ah, good to hear!
In the Introduction to Web Development there are already some sections with their own scrollbars.
Would it possible to wrap the solution lists in those?

This lesson has one, for instance.
[Web Development Communities](https://www.theodinproject.com/courses/introduction-to-web-development/lessons/web-development-communities?ref=lnav)

**Comment by KevinMulhern** [comment]
@junkdeck we have some of them wrapped in scroll bars, its an imperfect solution though. They are easily broken by incorrectly formatted student solutions.

**Comment by junkdeck** [comment]
Yeah I couldn't really find anything specific in either the sourcecode for the page or the markdown here on GH. 
Next time I come across a solution list, I'll actually scroll past them instead of just hitting Home, heheh.
