### ISSUE TITLE
Ruby / A deeper look at git: "Using feature banches" esource not working anymore

### ISSUE THREAD

**Issue by iansowinski** [TheOdinProject/curriculum#5650]
Link no 4 not working anymore :(

http://www.theodinproject.com/courses/ruby-programming/lessons/a-deeper-look-at-git

**Comment by KevinMulhern** [comment]
Thanks for letting us know @iansowinski, I'll get these fixed. This is the second time in a year they have changed the links __shakes fist_

**Comment by iansowinski** [comment]
I tried to find it via webarchive, but something is not working. Hope, some of you guys can repair it :)

**Comment by KevinMulhern** [comment]
Fixed 😄 thanks again @iansowinski
