### ISSUE TITLE
Broken links on VCS Page

### ISSUE THREAD

**Issue by 105ron** [TheOdinProject/curriculum#5692]
[This page](http://www.theodinproject.com/courses/web-development-101/lessons/terms-to-know) on TOP instructs the students to read the [VCS terms to know](https://www.vikingcodeschool.com/web-development-basics/terms-to-know) page. Some of the Skillcrush pages such as [this one](http://www.skillcrush.com/terms/cookies.html) return a 404 error, but the first few pages load correctly. I think they may have moved. This issue was raised by @tempeste in the gitter chat, @eriktrautman might like to look? Thanks, Rhys.

**Comment by KevinMulhern** [comment]
@TheOdinProject/odinmods whats everyones thoughts on removing this lesson from the curriculum?

Link to the lesson.
 http://www.theodinproject.com/courses/web-development-101/lessons/terms-to-know

I think throwing a ton of explanations at the user at this early stage without any context isn't effective. They are likely to have forgotten about most of these by the time they become relevant again.

**Comment by leosoaivan** [comment]
Would having a tiny glossary section at the end of each lesson be useful? I think it'd solve the issue of throwing a laundry list of terms at the beginning, where they can't be matched to actionable lessons. 

Having a glossary would be narrower in focus and it's likely to be effective, though it would also be more work when re-writing the curriculum.

**Comment by KevinMulhern** [comment]
@leosoaivan that could work, I suppose we will be doing that in a way if we break the lessons up effectively.

**Comment by leosoaivan** [comment]
Either way, I think removing it is appropriate.

**Comment by 105ron** [comment]
Can we close this now @KevinMulhern ? Looks like it's been fixed.

**Comment by KevinMulhern** [comment]
@105ron yeah sounds good, we should maybe create a new issue for removing it. I still think this lesson isn't needed 🙈
