### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by OlehSliusar** [TheOdinProject/curriculum#5718]
There's a broken link in [Project: Paired Pomodoro Project](http://www.theodinproject.com/courses/web-development-101/lessons/pairing-project). The link is in "We are going to make a Pomodoro clock similar to [this](https://arcane-ravine-59782.herokuapp.com/) which will count down twenty-five minutes of work, indicate it is break time, count down five minutes, then start over again."

**Comment by KevinMulhern** [comment]
Thanks for raising this @OlehSliusar 😄 

@ChadKreutzer any ideas?

**Comment by ChadKreutzer** [comment]
Yeah. I moved the app to surge and I could have sworn I updated the link. Thanks for the heads up.

**Comment by ChadKreutzer** [comment]
Fixed. thanks again, @OlehSliusar for catching that.

**Comment by KevinMulhern** [comment]
Thanks @ChadKreutzer and @OlehSliusar 🎉
