### ISSUE TITLE
Re: Project: Installations - link to Quick Guide about Sublime Text doesn't work

### ISSUE THREAD

**Issue by nattilyb** [TheOdinProject/curriculum#5899]
Link to Quick Guide from Jennifer Mann about Sublime Text doesn't work

**Comment by leosoaivan** [comment]
Thanks for pointing that out @nattilyb. Unfortunately, it seems the page doesn't exist anymore.

**Comment by KevinMulhern** [comment]
Fixed https://github.com/TheOdinProject/curriculum/commit/e9ba6925b198ef92da6914eac14b55687ce3c2fc
