### ISSUE TITLE
Adding note about JetBrain's student offer?

### ISSUE THREAD

**Issue by iansowinski** [TheOdinProject/curriculum#6030]
JetBrain's software is [free for students](https://www.jetbrains.com/student/). Maybe it is worth to add a note about RubyMine somewhere? I personally don't like working with IDE's, but some people like this style of work, so maybe it is worth to mention it :)

**Comment by KevinMulhern** [comment]
Thanks @iansowinski, I think it would be worth mentioning too 😄

**Comment by iansowinski** [comment]
Yeah, question is: where to put it? Maybe [here](https://github.com/TheOdinProject/curriculum/blob/e9ba6925b198ef92da6914eac14b55687ce3c2fc/web_development_101/project_installations.md)?

**Comment by KevinMulhern** [comment]
Yeah that seems like as good of place as any @iansowinski

**Comment by iansowinski** [comment]
Ok, it's live, I'm closing :)
