### ISSUE TITLE
URL redirecting to another site

### ISSUE THREAD

**Issue by erencataltepe** [TheOdinProject/curriculum#6350]
Hello,

Last additional ressource link of section  "How are Websites Built in the Real World?" redirects to another page.
Here is the description and the original URL:

"Get a more general sense of Agile Development from the About.com Agile Development entry."
(http://ruby.about.com/od/rubyonrails/a/agile.htm)

Here is the redirected url:
(https://www.thoughtco.com/what-is-software-engineering-958652)

I searched for the appropriate link but i couldn't find on Internet.

**Comment by KevinMulhern** [comment]
Thanks @erencataltepe, This should now be fixed.
