### ISSUE TITLE
Javascript and JQuery: Comparing Javascript and Ruby

### ISSUE THREAD

**Issue by ayushkamadji** [TheOdinProject/curriculum#6621]
The videolink in YouTube from Berkeley SAAS is being made private. I couldn't view it.
```
<!-- javascript/comparing_to_ruby.md -->
## Your Assignment

1. Watch this [Javascript for Ruby Programmers Video](https://www.youtube.com/watch?v=wWIGEM4E9iw&list=PLxNY6twFc_xCxdSPLlxUS4C0VO3sni2DA)
```

[Video Link](https://www.youtube.com/watch?v=_m0Y9N6dBz0&list=PLxNY6twFc_xCxdSPLlxUS4C0VO3sni2DA&index=18)

**Comment by KevinMulhern** [comment]
This has been fixed
