### ISSUE TITLE
Sublime Text 3 Resource is no longer free

### ISSUE THREAD

**Issue by JonathanYiv** [TheOdinProject/curriculum#6898]
Regarding: curriculum/web_development_101/project_installations.md

The [linked 2.5 hour course ](https://code.tutsplus.com/courses/perfect-workflow-in-sublime-text-2) is no longer free.

[This](https://code.tutsplus.com/courses/perfect-workflow-in-sublime-text-2) might be a better resource although it requires installation?

**Comment by KevinMulhern** [comment]
Thanks for reporting this @JonathanYiv, the second link points to the same course? 

It might be worth just removing this from the curriculum altogether.

**Comment by JonathanYiv** [comment]
Whoops I mean this https://sublimetutor.com/

**Comment by KevinMulhern** [comment]
Nice find @JonathanYiv 😄 are you comfortable creating PR to replace the old sublime resource with this new one?

**Comment by JonathanYiv** [comment]
Yes, I can. I will do it today!
