### ISSUE TITLE
Web Development 101: Jquery lesson - update assignment 4

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#7027]
The image slider tutorial on the [jquery basics lesson](https://www.theodinproject.com/courses/web-development-101/lessons/jquery-basics) is a bit outdated and has been confusing students. We should either replace this resource with a similar up to date short tutorial or remove it entirely.

**Comment by codyloyd** [comment]
just toss it for now IMO.  I remember just copying most of the cod ein that one and not really learning much, and I got on just fine

**Comment by KevinMulhern** [comment]
👍 sounds good @codyloyd
