### ISSUE TITLE
Remove assignment 4 of jquery lesson on web dev 101

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#7029]
Remove the image slider tutorial on the [jquery basics lesson](https://www.theodinproject.com/courses/web-development-101/lessons/jquery-basics)

**Comment by chari407** [comment]
I have completed this and created a pull request. Please check. Thanks in advance. 😄

**Comment by chari407** [comment]
Hi @KevinMulhern .. Can you please comment on my PR ?? Thank you.

**Comment by 105ron** [comment]
Thanks @chari407 . I've merged it for you and closed the issue. The changes you have made will appear on the site shortly. Thank you for your help. Cheers, Rhys.
