### ISSUE TITLE
The Backend:Testing Basics

### ISSUE THREAD

**Issue by datagoil** [TheOdinProject/curriculum#7226]
The introduction on Testing Basics
 [https://www.theodinproject.com/courses/web-development-101/lessons/testing-basics](url) 
states that RSpec will be covered but it is not. 

the next section The Backend:Project;Ruby 
[https://www.theodinproject.com/courses/web-development-101/lessons/ruby?ref=lnav](url)
assumes RSpec was taught and moves on from there "You learned about RSpec in the previous section "

effawhyeye

**Comment by KevinMulhern** [comment]
Thanks for reporting this @datagoil, I'll push a fix out for this soon.
