### ISSUE TITLE
Broken Tutorial: Event Manager

### ISSUE THREAD

**Issue by Demo318** [TheOdinProject/curriculum#7374]
https://www.theodinproject.com/courses/ruby-programming/lessons/file-i-o-and-serialization

It seems that the 'warm up' project no longer works.

Sunlight Labs, the creator of the Congress API, had to shut its doors. Its projects have been handed over to others to maintain, but currently the Congress API is not accessible.

I downloaded several others' completed repos to test, and we all received the same error response from the Sunlight server. Here is the output I receive in my CLI:
```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:156:in `parse': 743: unexpected token at '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> (JSON::ParserError)
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: X1ZZoMQYte90FqdhKLrt_e4M8FC-dD4EwGQbd3j5xeSCAR36iyKtMw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:335:in `load'
	from /Users/Devin/.rvm/gems/ruby-2.3.3/gems/sunlight-congress-1.1.0/lib/sunlight/congress/legislator.rb:21:in `by_zipcode'
	from lib/event_manager.rb:22:in `block in <main>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/csv.rb:1771:in `each'
	from lib/event_manager.rb:16:in `<main>'
```

**Comment by KevinMulhern** [comment]
Thanks for reporting this @Demo318 Thankfully its only a warm up exercise so I think removing it will be the best solution.

**Comment by Demo318** [comment]
@KevinMulhern I can take care of this. However, I feel kinda bad loosing all the student solutions :-/

**Comment by Demo318** [comment]
Created PR https://github.com/TheOdinProject/curriculum/pull/7376

**Comment by mindovermiles262** [comment]
Submitted PR to Turing Project, The owners of the tutorial today.  You can view it [here](https://github.com/mindovermiles262/touringschool-curriculum/blob/master/source/projects/eventmanager.markdown) for the time being

**Comment by KevinMulhern** [comment]
Thanks for all your amazing work on this @mindovermiles262

**Comment by mindovermiles262** [comment]
I don't think the site is being maintained. The last commit was 8 months ago.

It it worth it to host the instructions ourselves? Wouldn't take too much more work, just a few minor formatting details to change.

**Comment by KevinMulhern** [comment]
@mindovermiles262 if you think its worth it, I'm happy with that plan 👍

**Comment by mindovermiles262** [comment]
Closed with https://github.com/TheOdinProject/ruby_course/pull/66 and https://github.com/TheOdinProject/theodinproject/pull/831
