### ISSUE TITLE
Rails Forms Lesson

### ISSUE THREAD

**Issue by JonathanYiv** [TheOdinProject/curriculum#7501]
http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormHelper.html#method-i-form_with
Work on replacing form_tag/form_for form lesson content with form_with content.

**Comment by KevinMulhern** [comment]
Should we move this over to the rails course @JonathanYiv?

**Comment by JonathanYiv** [comment]
Aye cap'n
