### ISSUE TITLE
Adding Documentation to Github Readme's for Project: Building Your Personal Website

### ISSUE THREAD

**Issue by ZASMan** [TheOdinProject/curriculum#7619]
I'm referring to the following website:

https://www.theodinproject.com/courses/getting-hired/lessons/building-your-personal-website

One piece of information that should be included with this section is the importance of presenting your information on Github well. Prospective job seekers should include a minimal description/documentation, screenshots, links to demos, etc. in their Github readmes for both non technical individuals and engineers reviewing them as a potential candidate. In doing so, candidates will show more competency and hold a prospective employer's attention better (I.E. on one's going to see that a candidate has a repository called 'Example Rails App' and then clone it locally to look at it without having any further information beforehand).

**Comment by leosoaivan** [comment]
Sounds like a good idea @ZASMan. I think you're more than welcome to put together some content that you think would be helpful and make a PR!

**Comment by bhkangw** [comment]
Hi @ZASMan I would love to share ideas and input on this as I just finished creating my own personal website/portfolio. Please let me know if you have something started!

**Comment by leonardovega** [comment]
Is it safe to close this issue since it was addressed in #8181?

**Comment by ZASMan** [comment]
Yes that’s fine with me!
