### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mikesabat** [TheOdinProject/curriculum#7623]
This link is broken: oreanarose: What makes a good web developer? > http://oreanarose.com/2010/12/what-makes-a-good-web-developer/

From the second step on the first course. https://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-web-development

**Comment by KevinMulhern** [comment]
Thanks For reporting this @mikesabat

**Comment by JonathanYiv** [comment]
Fixed
