### ISSUE TITLE
Web Development 101: Conclusion is indented

### ISSUE THREAD

**Issue by Mycroft1891** [TheOdinProject/curriculum#7640]
As you can see the conclusion is indented. A quick look at the Dev Tools says that there is an empty div with a class of `col-lg-3` right before the actual content. 

<img width="1440" alt="screen shot 2018-01-05 at 5 37 19 pm" src="https://user-images.githubusercontent.com/11302907/34618492-395a5740-f23f-11e7-94be-f093f29f47bd.png">

**Comment by KevinMulhern** [comment]
I opened an issue for this on the main site repo https://github.com/TheOdinProject/theodinproject/issues/850

Thanks for reporting this @Mycroft1891
