### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/curriculum#7649]
While adding dropdowns to Learning Outcomes I noticed that there are duplicate files.  Example: There were to files named `git_intro.md`, one in `curriculum/web_development_101` and the other in `curriculum/git`

**Comment by KevinMulhern** [comment]
The one it the git folder isn't being used, we could get rid of that one.

**Comment by mindovermiles262** [comment]
Taken care of
