### ISSUE TITLE
Ambiguity of item 2 in Assignment of Introduction to Front End

### ISSUE THREAD

**Issue by smarbaf** [TheOdinProject/curriculum#7708]
This item is ambiguous: is the student supposed to go through the exercise in detail or simply read the directed text? 
https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/introduction_to_the_front_end.md

**Comment by KevinMulhern** [comment]
Hi @smarbaf, you raise a good point about these assignments.

I propose we find a different resource which explains the frontend in a high level way.

**Comment by smarbaf** [comment]
Hi @KevinMulhern, thank you for your suggestion. We have added a quick fix on the wording and will look for some more materials.

**Comment by tansaku** [comment]
I wonder if https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started might be a better HTML overview from MDN? 

As for CSS, maybe https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/How_CSS_works and for JS, maybe https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript ...?

**Comment by KevinMulhern** [comment]
Thanks @smarbaf 😄 

@tansaku those look good, they probably would be better. I think the most ideal resource for this particular lesson would be something that explains what the frontend is without getting into the specifics of HTML and CSS. Just something that provides an overview.

Maybe something similar to this?
https://www.youtube.com/watch?v=BANChTkxYYY&list=PLwqG3V3cExWpCgHOcLEKg6z-InpjHr7MB

**Comment by smarbaf** [comment]
@KevinMulhern This is a good video - very simple and to the point. I'd love to see it included in the course.

**Comment by codyloyd** [comment]
I added the above video.  Closing this issue

Thanks everyone!
