### ISSUE TITLE
AWS cloud9

### ISSUE THREAD

**Issue by Archy-io** [TheOdinProject/curriculum#7734]
With the changes to cloud9, alot of these guides code does not work on AWS since it runs red hat Linux. The guides assume using original cloud9.  Could a small guideline be added to discourage or at least make aware the inconveniences of using AWS cloud9.

**Comment by 33Coder** [comment]
maybe consider take advantage of the amazing free course offered by https://www.udemy.com/learn-amazon-web-services-the-complete-introduction/. (Learn Amazon Web Services (AWS): The complete introduction  ) In this course  get hands on, and cover every AWS service available today .

**Comment by stefanludlow** [comment]
Agreed that Cloud9 as presented as an alternative solution can be quite challenging, with the recent changes. The rails installfest just doesn't work as well in that, and perhaps there is an alternative to point folks to? There is a Cloud9 Rails Tutorial that is already partially used, perhaps touching on that for setup.

**Comment by 33Coder** [comment]
I hope you continue to keep that enthusiastic attitude and actions about project and at the end of the you will get it done.

**Comment by mindovermiles262** [comment]
Closed due to inactivity
