### ISSUE TITLE
Link not working in "command line basics"

### ISSUE THREAD

**Issue by Birnotobi** [TheOdinProject/curriculum#7784]
https://www.theodinproject.com/lessons/command-line-basics

the link for codecademy's course is  404
https://www.codecademy.com/en/courses/learn-the-command-line
the course is available on their website, but under different adddres
https://www.codecademy.com/learn/learn-the-command-line

Didn't know where to report it, I was advised on chat to try here

Stay Awesome

**Comment by KevinMulhern** [comment]
Thanks for reporting this @Birnotobi, looks like an easy fix of just updating the URL 😄

**Comment by Birnotobi** [comment]
That is the reason that I pasted good link here ;) If I'd know how, I'd just fix it myself ;) Still new here

**Comment by jklemon17** [comment]
I'll give this a shot if that's all right.

**Comment by mindovermiles262** [comment]
Closed with #7786
