### ISSUE TITLE
Ruby Advanced Building Blocks links not opening in new tab

### ISSUE THREAD

**Issue by jklemon17** [TheOdinProject/curriculum#7799]
The links to outside sources in this particular lesson are not using target="_blank" to open in a new tab. This problem occurs in Chrome, but not in Firefox.

https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-ruby-building-blocks

**Comment by heyalvaro** [comment]
Just tested with Firefox and Chrome and all the links opened in a new page

**Comment by JonathanYiv** [comment]
What version of Chrome are you using?

**Comment by KevinMulhern** [comment]
Thanks for reporting this @jklemon17 

We use js to dynamically add the target attribute to links in lesson content. 

We've been getting reports of other js related errors. I think this its all related and caused by some stuff I was working on recently.

I'll investigate and leave an update here.

**Comment by leila-alderman** [comment]
I just tested all of the links there, and they all seem to be working fine now, so I'm closing this issue.
