### ISSUE TITLE
Add capability to translate courses

### ISSUE THREAD

**Issue by ricardovsilva** [TheOdinProject/curriculum#7955]
TheOdinProject idea is AWESOME! But, unfortunately, is not evebody here in Brazil that speak english. I would love to collaborate translating this content to Brazilian Portuguese.
Can anyone point me where to start? Is that possible or something should be developed?

**Comment by KevinMulhern** [comment]
Hey @ricardovsilva, thank you for offering to do this 😄 

The technical challenge for this is we pull lesson content in from the [curriculum repo](https://github.com/TheOdinProject/curriculum) on github and store it on the database for the site.

This setup means we can't really have translations on the site in the traditional way with [locales](http://guides.rubyonrails.org/i18n.html).

It is technically feasible though, we could have a locale column in the lessons database table that will allow us to store lesson content in different languages.

There are performance considerations to be had with this approach though and there will be a lot more work involved in updating lesson content from the seeds file etc. 

This isn't something thats on our road map at the moment, but I won't shoot it down. There is a lot of content to translate so I would like to see if there are enough people interested in doing the translating before committing technical support and adding this to the road map.

**Comment by codyloyd** [comment]
As a side-note a large majority of our content consists of references to external resources which are in english.  It wouldn't be acceptable to say we offer alternative languages, but require students to read english articles, watch english videos or read english documentation.

I understand the desire to offer translations, but I do not see how it will ever be possible.  Perhaps a better solution would be to use our content/framework and create a _new_ site with translated content and links to more appropriate external resources videos.

Our curriculum is open source, so as long as you are not charging people for access to it there should be no problem.

**Comment by I3uckwheat** [comment]
Closing this, I do not think it is feasible to translate this course unfortunately due to the exact reasons @codyloyd stated.
