### ISSUE TITLE
Exercises for trying Git in Lesson: Git Basics are missing.

### ISSUE THREAD

**Issue by UndeadMantis** [TheOdinProject/curriculum#7976]
[Lesson page.](https://www.theodinproject.com/courses/web-development-101/lessons/git-basics?ref=lnav)

In the Assignment block, the link for 
> 2. Now [try Git from codeschool.](https://try.github.io/levels/1/challenges/1) Follow the exercises up to and including “1.11 Pushing Remotely” then jump back here.

Leads to a 404. The exercises are missing.

**Comment by leosoaivan** [comment]
This looks like it might an acceptable alternative: https://learngitbranching.js.org/

Thoughts @KevinMulhern, @arun1595?

**Comment by leosoaivan** [comment]
Closed with https://github.com/TheOdinProject/curriculum/pull/7978
