### ISSUE TITLE
Learning Outcomes in "HTML and CSS Basics"

### ISSUE THREAD

**Issue by tansaku** [TheOdinProject/curriculum#8002]
In our study group we are working through [HTML and CSS Basics](https://www.theodinproject.com/courses/web-development-101/lessons/html-and-css-basics) at the moment and in reviewing the learning outcomes we are noting that there is quite a lot covered in the assignments that are not in the outcomes ...

In particular the Codeacademy CSS course has been updated to include things like CSS grid.  Do the learning outcomes need updating?  Or do the assignments need to change to specify which parts of the external resources should be reviewed?

Also, is there somewhere where the answers to the learning outcome questions are provided?

We were particularly confused by this question:

> How do CSS styles for a particular element get inherited? i.e. how does an element get its “default” styles?

the i.e. implies that CSS inheritance is all about elements getting their default styles (which come from the browser no?)  should this be an e.g.?  Should the question be re-phrased?  Do we want people to understand both the cascade and inheritance as described in https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance ?

Might it be an idea to link the learning outcome questions to specific resources - if not learners, at least for maintainers?

**Comment by CouchofTomato** [comment]
Hi @tansaku 

Thank you for your feedback.

The html and css course does need an update. It's always been a bit difficult because we are all volunteers who have our own workloads etc.

We've very recently starting trialling design sprints to tackle these needed updates in teams. We've just held the first one to add a section to the JS course about frameworks and html and css is a top priority for us going forwards so we would hope all your issues will be addressed then.

In the meantime we still welcome all PRs if you can see any immediate fixes that need to be implemented.

The idea is to roll out the sprints to outside contributors once we have the process nailed down so maybe that is an area you could assist with in future.

I believe you also organise some sprints in a similar way so if you have any advice we'd certainly welcome it.

**Comment by tansaku** [comment]
thanks @CouchofTomato - good luck updating everything.  In case it's any help here's our rough answers to the learning outcomes from that section:

```
* Why do we separate HTML and CSS?

to make things manageable, make things easier
to separate the cosmetic look and feel of the site from the HTML framework

HTML -> head, body, paragraphs, dividers <-- general layout
CSS --> styles that layout


* What are classes and IDs (and how are they different)?

help you identify specific elements of your page, so you can do things to those elements individually
- IDs unique on a single page
- multiple elements can have the same class <div id="button5" class="button-big"/>


* What are elements?

atoms of html documents

content sits in your elements
elements are the components that we divide our content into

the whole syntax is wrapped in an element
e.g. <div id="button5" class="button-big"/>


* What are tags?

<br />
<br></br>
<div>Content</div>
<div />
<image src="http://myimages.com/image.png"/>


* What are attributes?

elements or tags have them

<tag attr1="thing" attr2="otherthing"/>

<tag src="myimage.png" attr2="otherthing"/>

"key-value pairs"


* What are forms?

HTML forms are for data submission


    <form action="hello.html">
        <input type='text' name='hello' value='default'>
        <input type='submit' name='submit' value='Onwards'>
        <input type='submit' name='submit' value='Backwards'>
    </form>


HTML tables are for displaying table data e.g. spreadsheet
used to be used for layout, but now that's the role of CSS grids


* What is a div?

divider

<div class="first-sentence">This is a sentence</div>
<p class="first-sentence">This is a sentence</p>
<div><p>This is another sentence</p></div>
<div>This is another sentence</div>

p {
  margin: 15px;
}

.first-sentence {
  margin: 0px;
}

div { 
}


* What are selectors?

A pattern used by CSS to select an element

e.g. 

#button5
.big-button
p[data='highlight']

p {
  font-color: red;
}

basic CSS atom (rule) consists of

SELECTOR {  <-- declaration block
  property: value; <-- declaration
}

* What are properties?


A CSS rule-set consists of a selector and a declaration block: The selector points to the HTML element you want to style. The declaration block contains one or more declarations separated by semicolons.

CSS styles
e.g. font-color, background-color


* What are values?

values of the properties, e.g. red


* What is the "query string" in a URL and what does it do?

says which page to go to

http://fiona.org/page/abstract?page=3


* What is the difference between "pixels" and "ems"?

ems --> relative (how things are displayed) 1em = current fontsize e.g. 18px
pixels --> one unit (actual size)

Pixels (px): Pixels are fixed-size units that are used in screen media (i.e. to be read on the computer screen). One pixel is equal to one dot on the computer screen (the smallest division of your screen's resolution).

1240x1780

* How do CSS styles for a particular element get inherited? i.e. how does an element get its "default" styles?

defaults
--------

p {
  display: block;
  font-size: 10px;
}

div {
  display: block;
  font-size: 10px;
}

span {
  display: inline;
  font-size: 10px;
}


style.css
----------

p {
  font-size: 18px;
}

div {
  font-size: 18px;
  color: red;
}

index.html
----------

<style>

p {
  font-size: 18px;
}
</style>


<div>
  <p></p>
  <p style="font-size: 24px;"></p>
</div>


* What are two CSS attributes you can change to push an element around on the page?

padding/margin

float?
css grid?

* What are the three different ways to include CSS in your project or use CSS to style a particular element?

1) html element internal style attributes (inline style)
2) css file (link) <rel src="../styles.css"> (external style)
3) embedded styles (internal style sheet)

* What is the "default stylesheet" or "user agent stylesheet"?

default browser styles

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"


* Why use a CSS reset file?

different browser have different default styles
give your webpage the same set of defaults across all browsers
```

It's difficult to offer a pull request since the pages don't have a standard place to put example answers, although conceivably they could be added with popups like so:

<details>
  <summary>What are selectors?</summary>
<br/>
  <p>A pattern used by CSS to select an element

e.g. 
```
#button5
.big-button
p[data='highlight']
```
```css
p {
  font-color: red;
}
```
basic CSS atom (rule) consists of:

```
SELECTOR {  <-- declaration block
  property: value; <-- declaration
}
```
</p>
</details>

^^^ click on triangle to see answer

Although that's a pretty big change to your curriculum to make all the learning outcome answers available at a click ...

we're moving on to other sections now, but if you're interested in PRs with sample answers available vai clicking triangles (and that works in the main site) then let me know and perhaps we can put in PRs for all our "answers" to the learning outcomes ...

**Comment by tansaku** [comment]
It's difficult to offer a pull request since the pages don't have a standard place to put example answers, although conceivably they could be added with popups like so:

<details>
  <summary>What are selectors?</summary>
<br/>
  <p>A pattern used by CSS to select an element

e.g. 
```
#button5
.big-button
p[data='highlight']
```
```css
p {
  font-color: red;
}
```
basic CSS atom (rule) consists of:

```
SELECTOR {  <-- declaration block
  property: value; <-- declaration
}
```
</p>
</details>

^^^ click on triangle to see answer

Although that's a pretty big change to your curriculum to make all the learning outcome answers available at a click ...

we're moving on to other sections now, but if you're interested in PRs with sample answers available vai clicking triangles (and that works in the main site) then let me know and perhaps we can put in PRs for all our "answers" to the learning outcomes ...

**Comment by CouchofTomato** [comment]
Thanks @tansaku 

You've given us a bit to think about...

**Comment by happiguru** [comment]
[happiguru.github.io](url)
Please find above a link of my first project submitted for the odin project. Google Homepage. I appreciate any improvement to the project. Thanks

**Comment by I3uckwheat** [comment]
Closing as we are going to be working on a new HTML + CSS course. #16011
