### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by akaswen** [TheOdinProject/curriculum#8382]
Hey, in the organizing javascript section in the classes lesson, the first link to the article goes nowhere.  I checked the github repo of the guy who originally posted the article and it seems like he's taken it down.  Any suggestions for a replacement or would it be best to just take it out altogether?

**Comment by KevinMulhern** [comment]
Hi @akaswen, thanks for reporting this. Thats unfortunate about they guy taking his article down. I think we should remove it make the second link in that first assignment to focal point to resolve this

**Comment by akaswen** [comment]
okay, I can rewrite that then.
