### ISSUE TITLE
Ruby Course: Update "Using Git in the Real World" section

### ISSUE THREAD

**Issue by Jeremy-D** [TheOdinProject/curriculum#8465]
It looks like the "using git in the real world section" has become a bit out of date due to the restructuring of the curriculum repo. [Using Git in the Real Word](https://www.theodinproject.com/courses/ruby-programming/lessons/using-git-in-the-real-world)

Since it appears that there is no longer a dev branch, I was confused about where to fetch and merge from. 

I'm not sure if someone is creating a similar section in the new Git course but I thought maybe we could work on updating this section in the meantime.

**Comment by hoangtommy** [comment]
@Jeremy-D I also saw that the dev branch wasn't being used anymore. I changed the copy and my PR got accepted. I think we can close this issue now.
