### ISSUE TITLE
Web Dev 101 - Cloud 9 IDE/Installation Sections

### ISSUE THREAD

**Issue by nikkisa** [TheOdinProject/curriculum#8481]
In the installation section it mentions Cloud 9, but doesn't go into any depth. Because I already had a Cloud IDE setup, I didn't realize that while this is an option, it's a de-emphasized one compared to installing a local environment.

I think implicitly stating that this is an optional/supplementary environment would be helpful to people like myself. Also, emphasizing as a result that the local environment is REQUIRED to get the best/most out of the course especially as a new developer and that the Cloud isn't a substitute for it due to its ease and limitations for testing.

Thank you for your help!

**Comment by codyloyd** [comment]
This has been more or less addressed by our update installation instructions.
