### ISSUE TITLE
UX introduction

### ISSUE THREAD

**Issue by sp3fix** [TheOdinProject/curriculum#8609]
Hello everyone, first time creating an issue on here, so i would like to preface it by saying that i love the "odin project" platform and that i believe you already have a great product there. 

And at the same time, it has come to my attention that several people seem to miss the "drop down" information during some of the course, particularly at the beginning, resulting in issues that could have been easily prevented and that the good people on Gitter wouldn't have to dedicate so much time on.

With that in mind, i would maybe suggest adding a simple "virtual assistant" at the very beginning of the tutorial that can introduce new students to some of the features that they will encounter during their time on the website : drop down "hidden" information, "complete" button, "home" button to go back to the main interface, etc. 

At the end of the day, you can't build a system around ALL possible failure or you just end up sinking too many resources in it but i think that this might be a good addition for the sanity of the gitter 
that are helping people out with the same issues over and over again without a good way to know what went wrong, and how they missed something.

Thank for the great work,

**Comment by leosoaivan** [comment]
Could we add a CSS wiggle to the drop-down arrows when they come into view, to indicate that an action can/should be taken?

**Comment by I3uckwheat** [comment]
@leosoaivan I like that idea

**Comment by codyloyd** [comment]
i do not like the idea of a virtual assistant..... however we can probably update the design a little bit to make it more obvious that those can be expanded.

**Comment by zachmmeyer** [comment]
Should this be referenced on https://github.com/TheOdinProject/theodinproject as a PR? "Add wiggle to dropdown arrows"?

**Comment by I3uckwheat** [comment]
This has not been an issue for a long time interestingly, closing this for now, but will keep an eye out.
