### ISSUE TITLE
JavaScript in my project is not working. Anyone could help me? 

### ISSUE THREAD

**Issue by JunJie19** [TheOdinProject/curriculum#8676]
![screenshot 468](https://user-images.githubusercontent.com/44231496/48145278-6ca6f980-e2aa-11e8-9984-34d7b209b436.png)
![screenshot 469](https://user-images.githubusercontent.com/44231496/48145282-6e70bd00-e2aa-11e8-9e57-0161548836c7.png)

I have created variable itself however it doesn't execute when i click on it.
Is there something wrong with code? or i have not implement js code to function it?

Thank you very much.

**Comment by CouchofTomato** [comment]
Hi @JunJie19. The issues pages are not a suitable place for this. Can you please either post your issue in our gitter chat https://gitter.im/TheOdinProject/theodinproject or our forums https://forum.theodinproject.com/

**Comment by JunJie19** [comment]
Hi @CouchofTomato, Okay, Thanks a lot!
