### ISSUE TITLE
Update Rails Final Project: Replace Paperclip for Active Storage

### ISSUE THREAD

**Issue by heyalvaro** [TheOdinProject/curriculum#8724]
Since Paperclip is now deprecated should the curriculum be updated to use Active Storage?

**Comment by Deetss** [comment]
@heyalvaro Im going to start working on this! Thanks for the suggestion. If youd like to have a wack at it feel free.

**Comment by heyalvaro** [comment]
@Deetss I was on vacation and just saw your answer. Glad you liked the suggestion 😄

**Comment by I3uckwheat** [comment]
@Deetss Are you still working on this?

**Comment by Deetss** [comment]
This is done
