### ISSUE TITLE
Rails curriculum conclusion

### ISSUE THREAD

**Issue by AgonIdrizi** [TheOdinProject/curriculum#8878]
At the end of the rails course
https://www.theodinproject.com/courses/ruby-on-rails/lessons/conclusion-ruby-on-rails

**Ruby on Rails Tutor has free videos that highlight specific sections of Rails.** http://rubyonrailstutor.github.io/
Videos on the link are broken and also outdated(circa 2014)

I want to remove this broken links and to replace it with this:
https://www.youtube.com/watch?v=4ABesTeDKmQ&list=PL01nNIgQ4uxNkDZNMON-TrzDVNIk3cOz4
There are 10 apps building (from web-crunch) inside playlist, introducing different technologies from webpacer , multitenancy, e-commerce(card payments) etc.

Also I  want to add to this section a nice video for APIs from Le Wagon bootcamp (https://www.youtube.com/watch?v=oBW_VNg4qD0) 

Thanks

**Comment by hoangtommy** [comment]
@AgonIdrizi thanks for bringing this up. I can take it as an action item to remove the broken link to RoR Tutor and replace it with your suggested web-crunch series.

**Comment by hoangtommy** [comment]
@AgonIdrizi just submitted a PR updating the conclusion with your links.

**Comment by AgonIdrizi** [comment]
Thnx @hoangtommy.
