### ISSUE TITLE
Tayo Olayinka's Solution (Easy)

### ISSUE THREAD

**Issue by olayinkatayo** [TheOdinProject/curriculum#8935]
Solution

**Comment by uzorjchibuzor** [comment]
@olayinkatayo I think it is a PR you wanted to open?

**Comment by olayinkatayo** [comment]
Oh, yes. I was trying to create a PR for the very first time. Made a few mistakes before I got it right. So you're very correct. Thanks for pointing that out @uzorjchibuzor

**Comment by uzorjchibuzor** [comment]
You can close the issue.
