### ISSUE TITLE
Depreciated method in resource (SO)

### ISSUE THREAD

**Issue by Danshock** [TheOdinProject/curriculum#8943]
In _apis-and-building-your-own_ -> _Rendering Nothing or Errors_ and more specifically the Stackoverflow resource. The Stackoverflow's answer suggests using this code as a solution:
`render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)`
, however another user pointed out 

> As a side-note here, specifying the .html extension like this is deprecated (see discussion at github.com/rails/rails/issues/7288), so we should use render(:file => File.join(Rails.root, 'public/403'), :formats => [:html], :status => 403, :layout => false) (note the way I've specified the format)

What I suggest is maybe this could be mentioned to future users by explaining it on Odin's webpage or pointing to the correct method.

**Comment by leosoaivan** [comment]
I think that, on a broader level, everyone has to watch out for deprecated methods. Unfortunately, the curriculum can't easily address this on a granular level, unless it was to address truly breaking changes.

If you feel this might be considered a breaking change, I encourage you to open a PR with the necessary change.
