### ISSUE TITLE
Web Dev 101: How does the web works? - Broken link

### ISSUE THREAD

**Issue by tale-quale** [TheOdinProject/curriculum#9089]
Link to the page - https://www.theodinproject.com/courses/web-development-101/lessons/how-does-the-web-work
The second part of the assignments' point 5:
"...Then, find out what web browser you are using right now." - broken link on the word "now".
The site not available and I think need to fix that.

**Comment by hoangtommy** [comment]
@tale-quale what do you see when you click on the link **now**? I just tested it on two browsers and it looks like it works fine.

**Comment by leosoaivan** [comment]
Tested the link. Closing!

Thanks @hoangtommy!
