### ISSUE TITLE
Beginning Ruby book no longer free

### ISSUE THREAD

**Issue by leila-alderman** [TheOdinProject/curriculum#9197]
The first three lessons in the Ruby course include in the assignment reading chapters of the Beginning Ruby book. However, this book is no longer free on [Google Books](https://books.google.com.pk/books?id=MiGpDAAAQBAJ&printsec=frontcover#v=onepage&q&f=false). 

I suggest removing these links and perhaps replacing them with alternative resources. A previous related issue (https://github.com/TheOdinProject/curriculum/issues/8347) included a link to a pdf version of this book, but it appears to be illegally pirated. 

Any ideas for replacement? Or is there enough content already that this resource can simply be removed?

**Comment by leila-alderman** [comment]
In the OOP lesson (https://www.theodinproject.com/courses/ruby-programming/lessons/object-oriented-programming), the Additional Resources section states:
"For an alternative read to Beginning Ruby’s chapters on OOP, check out Launch School’s OOP."
(https://launchschool.com/books/oo_ruby/read/introduction)

So this lesson might be an easy and quick one to clean up.

**Comment by leila-alderman** [comment]
Interestingly, the [Files and Serialization lesson](https://www.theodinproject.com/courses/ruby-programming/lessons/files-and-serialization?ref=lnav) links to the [Amazon page](https://www.amazon.co.uk/Beginning-Ruby-Professional-Peter-Cooper/dp/1484212797) to buy the Beginning Ruby book, not even pretending that it's free. 

Would these chapters be alright to just remove from the lesson?

**Comment by KevinMulhern** [comment]
Hi @leila-alderman, thanks for raising this. 

1. The first three lessons will soon be replaced by brand new lessons, that will include different more up to date resources. I'd estimate that these lessons will be live within the month. But we could maybe replace Beginning ruby in these lessons with chapters from this free book https://launchschool.com/books/ruby/read/introduction

2. I agree that we should clean up the OOP lessons by replacing Beginning Ruby with that additional resource.

3. I agree with removing beginning ruby from the files and serialisation lesson as well.
