### ISSUE TITLE
Web Dev 101 HTML/CSS Project - RawGit is shutting down

### ISSUE THREAD

**Issue by benfowler04** [TheOdinProject/curriculum#9260]
The [HTML/CSS project](https://www.theodinproject.com/courses/web-development-101/lessons/html-css) lists two hosting options: GitHub Pages and [RawGit](https://rawgit.com). The latter is shutting down:

"RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.

GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.

If you're currently using RawGit, please stop using it as soon as you can."

The instructions for using RawGit should be removed or replaced. RawGit suggests these sites as alternatives:

[jsDelivr](https://www.jsdelivr.com/)
[CodeSandbox](https://codesandbox.io/)

**Comment by leosoaivan** [comment]
I think leaving GitHub Pages as the only remaining option is acceptable. Everyone's code is hosted on GitHub to begin with.
