### ISSUE TITLE
Remove cloud 9 and replace with better alternative

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#9426]
https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/pair_programming/prepare_to_remote_pair.md

Another solution may be better in it's place.

Related to:  #8481

**Comment by KevinMulhern** [comment]
I think there was talk about removing the pairing lessons, they haven't performed as we expected they would.

**Comment by I3uckwheat** [comment]
I think removing the project would be good enough in this case.
