### ISSUE TITLE
The meaning of a DNS,Web Development 101.

### ISSUE THREAD

**Issue by WoozyAdel** [TheOdinProject/curriculum#9494]
**Hello There!.**
While i was surfing the curriculum i found something i think is wrong after i looked up some other websites.
DNS is supposed to convert Domain Names into IP address but in the definition provided by the curriculum its the opposite.
**Screenshot:**
![screenshot](https://user-images.githubusercontent.com/47352705/52276815-7563a600-2953-11e9-9b3c-3c922ca9a6e5.png)

**Link:**
[https://www.theodinproject.com/courses/web-development-101/lessons/how-does-the-web-work?ref=lnav](url)

**Comment by mindovermiles262** [comment]
Closed with https://github.com/TheOdinProject/curriculum/pull/9636
